### ISSUE TITLE
[<bitnami wordpress>] <how to change the url>

### ISSUE THREAD

**Issue by FMPress** [bitnami/vms#100]
### Describe your issue as much as you can

I've installed bitnami wordpress, and i've found that to change the URL i have to go into wp-config.php as it's greyed out in the wp-admin console.

I went in there and changed this

![image](https://user-images.githubusercontent.com/109076036/178249112-a117f52f-f63c-4ed7-a625-b9efe2232aad.png)

to this

![image](https://user-images.githubusercontent.com/109076036/178249266-8479f01f-1e1e-479a-81d0-4a8b62d2ba6c.png)

Now the site will not load, but if i switch it back to wordpress it works just fine.... why?

**Comment by jotamartos** [comment]
To move WordPress to a different path, you also need to apply changes in the Apache's configuration (wordpress-vhost.conf and wordpress-https-vhost.conf files). You can find the solution here: 

```
bitnami@bitnami-wordpress-fdc9:~$ cat /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf
<VirtualHost 127.0.0.1:80 _default_:80>
  RewriteEngine On
  RedirectMatch "^/$" "/blog/"
  Alias /blog/ /opt/bitnami/wordpress/
  Alias /blog /opt/bitnami/wordpress
  ServerName www.example.com
  ServerAlias *
  DocumentRoot /opt/bitnami/wordpress
  <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /blog
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /blog/index.php [L]
    # END WordPress
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
</VirtualHost>
bitnami@bitnami-wordpress-fdc9:~$ cat /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf
<VirtualHost 127.0.0.1:443 _default_:443>
  RewriteEngine On
  RedirectMatch "^/$" "/blog/"
  Alias /blog/ /opt/bitnami/wordpress/
  Alias /blog /opt/bitnami/wordpress
  ServerName www.example.com
  ServerAlias *
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
  DocumentRoot /opt/bitnami/wordpress
  <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /blog
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /blog/index.php [L]
    # END WordPress
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
</VirtualHost>
```

Remember to update the wp-config.php file as well (you already did that)

```
bitnami@bitnami-wordpress-fdc9:~$ cat /opt/bitnami/wordpress/wp-config.php | grep "WP_HOME\|WP_SITEURL"
 * The WP_SITEURL and WP_HOME options are configured to access from any hostname or IP address.
 *  define('WP_HOME','http://example.com');
 *  define('WP_SITEURL','http://example.com');
define( 'WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/blog' );
define( 'WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/blog' );
```

You will just need to restart Apache for the changes to take effect

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

**Comment by malmualla** [comment]
Hello @jotamartos,

I faced issues with two plugins and its both result of wrong path, am wondering if I do apply changes in the Apache's configuration (wordpress-vhost.conf and wordpress-https-vhost.conf files) would fix it as well.

The first one is with WPML plugin and it seems common with other users of the plugin and its clearly explained in [this topic](https://wpml.org/errata/wpmls-style-sheets-point-to-ontent-instead-of-wp-content/). 

The Second issue is with CTX Feed plugin which is randomly switching the path between domain and IP address while generating the feed urls, discussed [here](https://wordpress.org/support/topic/issue-with-products-feed-urls/).

Here is the code of my wordpress-vhost.conf file which looks different

`<VirtualHost 127.0.0.1:80 _default_:80>
  ServerAlias *
  DocumentRoot /opt/bitnami/wordpress
  <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of sym
bolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
    # END WordPress
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
</VirtualHost>`

**Comment by jotamartos** [comment]
Hi @malmualla,

Those are plugins' specific issues so we suggest you contact the plugin's developers to know more about the issues and how to solve them. 

https://wordpress.org/support/

If the plugins generate a "loop" error (doesn't seem to be the case), we suggest you remove the symlink and move the wp-content folder to the /opt/bitnami/wordpress folder (more info [here](https://github.com/bitnami/vms/issues/23#issuecomment-1143966330))

**Comment by jotamartos** [comment]
>Am only facing issue with the domain which is generated as IP address sometimes.

Configure the domain in WordPress and update the database information 

https://docs.bitnami.com/aws/apps/wordpress/administration/configure-domain/
https://wordpress.org/plugins/better-search-replace/

If you continue running into this issue, please contact WordPress.

**Comment by Calgon6** [comment]
Hi there
I have the exact same issue but I am on a windows version of bitnami / Wordpress and the files mentioned above that need to be changed don't seem to exist.  Can someone point me in the right direction of the equivalent files ?

**Comment by mdhont** [comment]
Can you check this guide? (the same, but for installers):

https://docs.bitnami.com/installer/apps/wordpress/administration/configure-domain/

**Comment by andersonbosa** [comment]
Has anyone managed to accomplish this in the `bitnami/wordpress-nginx` image?
