### ISSUE TITLE
[<application>] <Database connection cannot be established>

### ISSUE THREAD

**Issue by mavalliani** [bitnami/vms#1001]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8c8a52d7-89a8-7d8a-a110-341f04517efe

### bndiagnostic output

some error logs:
```
2023-06-21 18:17:18 0 [ERROR] InnoDB: Page [page id: space=0, page number=50] log sequence
number 4200479366 is in the future! Current system log sequence number 3542625345.
2023-06-21 18:17:18 0 [ERROR] InnoDB: Your database may be corrupt or you may have copied
the InnoDB tablespace but not the InnoDB log files. Please refer to https://mariadb.com/kb
/en/library/innodb-recovery-modes/ for information about forcing recovery.
2023-06-21 18:17:18 0 [Note] InnoDB: Retry with innodb_force_recovery=5
2023-06-21 18:17:18 0 [ERROR] InnoDB: Plugin initialization aborted with error Data struct
ure corruption
2023-06-21 18:17:18 0 [Note] InnoDB: Starting shutdown...
2023-06-21 18:17:18 0 [ERROR] Plugin 'InnoDB' init function returned error.
2023-06-21 18:17:18 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2023-06-21 18:17:18 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-06-21 18:17:18 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2023-06-21 18:17:18 0 [ERROR] Aborting
```

my database is mariadb and my my.cnf path is /opt/bitnami/mariadb/conf/my.cnf

when I create an instance with the snapshot and do status on ctlscript.sh it shows:
cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)
then i try to start ctlscript.sh it shows:
Job for bitnami.service failed because the control process exited with error code. See "systemctl status bitnami.service" and "journalctl -xe" for details.

I also see that mariadb is not running. and i cannot start it. Apache and php-fpm starts fine

### bndiagnostic was not useful. Could you please tell us why?

did not solve the problem

### Describe your issue as much as you can

I use AWS Lightsail with bitnami stack for wordpress. All was running fine but then AWS did some maintenance and it feels some packages in bitnami stack has problems now. My site is down because of this.

**Comment by gongomgra** [comment]
Hi @mavalliani,

Thanks for using Bitnami. According to the bndiagnostic bundle you shared, your server is running out of resources to start new processes. You will have to use a different instance type with bigger resources

```
-----------------------------------
Display amount of free and used memory in the system
-----------------------------------
Running: free -m
In: /opt/bitnami

Output:

               total        used        free      shared  buff/cache   available
Mem:             472         257          66           4         148         197
Swap:            634           4         630
```
