### ISSUE TITLE
[Wordpress] How do we customize SSL 400 error message?

### ISSUE THREAD

**Issue by bits45** [bitnami/vms#1002]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

unknown

### bndiagnostic was not useful. Could you please tell us why?

unknown

### Describe your issue as much as you can

Hello team,

I'm new to NGINX and Wordpress 6.2 from Bitnami. I've been customizing my group's Wordpress and doing quite well. I've recently secured the site using our SSL certificate AND requiring the use of a Common Access Card (CAC) or Smart Card. This is all working well. However, I was hoping to customize the NGINX default 400 Bad Request Message, the one that states "No required SSL certificate was sent".

I've created a custom 400.html file, but cannot figure out how to modify the server directive in nginx.conf file to point to the custom 400.html file when a client goes to the Wordpress site without a CAC installed. I will have the custom 400.html page state that the problem MIGHT be that the user did not insert their CAC into the reader.

I've tried various changes in the /opt/bitnami/nginx/conf/nginx.conf file.

One: the following line in the server directive, but it didn't work.

error_page 400 /opt/bitnami/wordpress/400.html;

Also tried various things like this, and naturally restarted the entire bitnami service after each nginx.conf change.

        error_page 495 496 497 /400.html;
          location = /400.html {
          root /opt/bitnami/wordpress;
          internal;
        }

        if ($ssl_client_verify = "FAILED:CAC Card Required") {
          return 303 /400.html;
        }

Does anyone have a good answer to this configuration question?

I appreciate your time.

**Comment by gongomgra** [comment]
Hi @bits45,

Thanks for using Bitnami. Can you run the bndiagnostic tool and share the generated code with us so we can take a look at your Apache configuration?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by bits45** [comment]
Thanks!  You see mention of errors in the log file, these are old and only caused when I was testing certain configuration changes.  Everything is back to working order now, when I ran your diagnostic tool.  This site is private. 

Reminder, this site is currently working very well with out issues.  It is CAC-enabled.

bndiagnostic f96b039d-a5f9-02ac-ba1a-0b704defc45b

Thanks again for your time and consideration.

**Comment by bits45** [comment]
Team, I have re-run the diagnostic tool, but this time with my changes in the nginx.conf file.  I cannot tell if the nginx.conf file actually gets uploaded with the diagnostic results.  This should be more accurate as to what I'm attempting to do.

23783411-d2f4-30f3-86b4-89effe8155c5

Thanks again!  

Chris

**Comment by bits45** [comment]
I was able to finally clear out those old "currently false" errors that your diag tool had found.  One error mentioning the term "bla".  I did that the other day during a test config.  Not sure why the errors kept re-appearing even after I restarted the bitnami service with the good nginx config file.  Just now, I decided to "try" to clear the logs by stopping the bitnami service, clearing the access and error log files, then restarting the AWS instance.  That did the trick.  No more false (or old) errors showing up in any log files.

Sorry for any confusion.

**Comment by gongomgra** [comment]
Hi @bits45,

Thanks for your message. I'm glad you managed to fix your error! I'm closing this ticket as solved.

**Comment by bits45** [comment]
@gongomgra I didn't have an error, but I was hoping to customize the 400 error.  I cannot find any good clues online about creating a custom 400 message.  Any help is appreciated. 

Again, this is not a bug, just reaching out for help with the message.  If the entire site is secured with a smart card, then I do have have a way to tell the use that they need to insert a smart card, they get are presented with a 400 error message.  I'm hoping to make the error message more meaningful by giving visitors a clue as to why they're getting the 400 SSL error message.  Otherwise, I need to either multiple virtual hosts, one being insecure without a smart card, telling the user to then "click this link (to the secured virtual host), but only after inserting the smart card."

Sorry if I was not clear before.

**Comment by gongomgra** [comment]
Hi @bits45,

Sorry, I misunderstood your message. Can you run the bndiagnostic tool and share the generated code with us so we can take a look at the config changes you already did?

**Comment by gongomgra** [comment]
Hi @bits45,

I checked the previous bndiagnostic code you shared and I see you added the related config in the `nginx.conf` file. However, WordPress configuration is located in the `/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf` and `/opt/bitnami/nginx/conf/server_blocks/wordpress-https-server-block.conf`. You will need to place the configuration there. Remember to restart the NGINX services after updated the configuration for changes to take effect.
