### ISSUE TITLE
[wordpress] PHP Warning:  chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 173

### ISSUE THREAD

**Issue by adrianf0** [bitnami/vms#1006]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

_

### bndiagnostic was not useful. Could you please tell us why?

_

### Describe your issue as much as you can

The problem appears on a fresh AWS Lightsail instance with the WordPress application (bitnami).

For a call:
`$> sudo wp eval-file test.php`

it returns:
```
PHP Warning:  chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 173
Warning: chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 173
PHP Warning:  chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 173
Warning: chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 173
PHP Warning:  file_get_contents(test.php): Failed to open stream: Permission denied in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/eval-command/src/EvalFile_Command.php on line 61
Warning: file_get_contents(test.php): Failed to open stream: Permission denied in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/eval-command/src/EvalFile_Command.php on line 61
```

The test.php file:
```
$> cat test.php
<?php echo "test"; ?>
```

**Comment by mdhont** [comment]
What are you trying to do exactly? Is the application failing?

**Comment by adrianf0** [comment]
The application doesn't fail.
I want to call from my local `wp` instalation commands againts a remote server over SSH ([link](https://developer.wordpress.org/cli/commands/eval/)).

**Comment by mdhont** [comment]
It seems that to run commands against a remote server you need to run the wp command with the `--ssh=` parameter as described in the guide you shared.

**Comment by adrianf0** [comment]
@mdhont, due to access rights on bitnami (one needs to call _wp cli_ as root) the usage of `eval-file` with `--ssh=` will be even more problematic - it would be my eventual goal though.

For a moment, I would focus on the fact that the referred in the issue description call on the local bitnami server produces the error already. Have you had a chance to reproduce the issue?

**Comment by mdhont** [comment]
I haven't been able to reproduce it:

```
bitnami@debian:/opt/bitnami/wordpress/wp-content$ sudo wp eval-file test.php 
test
```

Did you make any further changes? Could you try with a regular wordpress php file?

**Comment by adrianf0** [comment]
Fixing permissions in the `wp-content` subdirectories (I thought I checked that properly earlier, sorry) fixed the issue. 
Thanks.
