### ISSUE TITLE
[Mattermost] Certificate SSL Let's Encrypt with or no Cerbot.

### ISSUE THREAD

**Issue by miltonardila** [bitnami/vms#1007]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9d4265ce-294f-778c-9e7a-721e164f9982

### bndiagnostic output

? Resources: Found possible issues
? Connectivity: Found possible issues
? Nginx: Found possible issues
✓ Processes: No issues found
✓ Mysql: No issues found

### bndiagnostic was not useful. Could you please tell us why?

For the time being, it is not a problem of resources.

### Describe your issue as much as you can

This is the second instance I create, trying to get Mattermost.

In the first instance everything worked correctly, and I used `sudo /opt/bitnami/bncert-tool` to create the SSL certificate. My domain has entered without problems with `https://` but my instance broke when I tried to upgrade, following the steps in the documentation `https://docs.bitnami.com/aws/apps/mattermost/administration/upgrade/`, until I read here that you can not upgrade. You must create a new instance with the upgraded image and migrate the data. If this is not the case please correct me.

In my current instance, I have the correct image, and it works from the public DNS provided by AWS, Mattermost is working without problems. What happens is that now my domain is not working, trying to create the SSL certificate but with Lego `https://docs.bitnami.com/aws/apps/mattermost/administration/generate-configure-certificate-letsencrypt/`.

There are directories that do not exist, the commands they write in the tutorial some do not work, etc ....

Question? Now that I have a new image working, what should I do to revoke or undo what I have done with Lego, and if it is better to do it with automated cerbot.

url DNS: `https://ec2-15-188-54-89.eu-west-3.compute.amazonaws.com/login`
domain pointed correctly but not working via SSL: `team.solucionesk.com`

I hope you can help me please.

**Comment by mdhont** [comment]
Could you try the manual approach?

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by miltonardila** [comment]
Hi @mdhont , thanks for replying.
Yes correct, that is the same guide that is in Bitnami's Mattermost documentation.
But in step 3 is where the problems start. It seems that there are some symbolic links that are no longer there as in the other guide.
I am going to perform these steps, but do you know if I should undo everything previously done, or just the process overwrites.
Thanks.

**Comment by miltonardila** [comment]
See step 3 is still giving me problems:
```
mv: cannot stat '/opt/bitnami/nginx/conf/bitnami/certs/server.csr': No such file or directory
chown: cannot dereference '/opt/bitnami/nginx/conf/bitnami/certs/server.crt': No such file or directory
chown: cannot dereference '/opt/bitnami/nginx/conf/bitnami/certs/server.key': No such file or directory
chmod: cannot operate on dangling symlink '/opt/bitnami/nginx/conf/bitnami/certs/server.crt'
chmod: cannot operate on dangling symlink '/opt/bitnami/nginx/conf/bitnami/certs/server.key'
```
Just as it happened to me before.

**Comment by miltonardila** [comment]
@mdhont Solved, step by step manually, there were previous files created by the other guides.
Now works correctly the domain with its SSL certificate. Somewhat confusing because the guides are different, by image and by infrastructure.

To close the thread, and leaving the SSL topic, to upgrade to version 7.10.3 I must wait for bitnami publish that image, mount another instance and migrate the data? If so, a Mattermost migration guide would be missing, please.

Best regards and thank you very much.

**Comment by mdhont** [comment]
Yes, to upgrade you need to launch a new instance and migrate the data there. The following guide shows how you can backup and restore Mattermost:

https://docs.bitnami.com/aws/apps/mattermost/administration/backup-restore/
