### ISSUE TITLE
[<Bitnami Wordpress>] <Service unavailable>

### ISSUE THREAD

**Issue by imerial** [bitnami/vms#1008]
Hello,

I have a WP instance in Lightsail. (8 GB RAM, 2 vCPUs, 160 GB SSD). But I keep getting the following error: 

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.Service Unavailable 
![thumbnail_image](https://github.com/bitnami/vms/assets/24517082/ecc3288c-f484-4a0d-bc32-8a4dbaf915ce)

Rebooting the server is the only thing that brings the site back but that is becoming a bit issue for me. The bndiagnostic tool is not help me understand what is going on. I have many other WP instances in Lightsail but this is the one site I have problems with. Any help would be greatly appreciated. 

Diagnostic below:

### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0ea2a44c-7d3c-399e-0db8-0a67a329a15a

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Fri Jun 23 19:36:06.593048 2023] [proxy_fcgi:error] [pid 787:tid
140318066149120] [client **ip_address**:62103] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer:
https://mysite.com/page/?fl_builder&fl_builder_ui_iframe
 [Fri Jun 23 19:36:36.2023] [proxy_fcgi:error] [pid 839:tid
140317017749248] [client **ip_address**:62117] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer:
https://mysite.com/sitepage/?fl_builder&fl_builder_ui_iframe
 [Fri Jun 23 19:36:53.793284 2023] [proxy_fcgi:error] [pid 1818:tid
140317000865536] [client **ip_address**:62119] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer:
https://mysite.com/mypage/?fl_builder&fl_builder_ui_iframe

```
Please check the following guide to troubleshoot server issues:
Press [Enter] to continue:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

===== End of bndiagnostic tool output =====
![thumbnail_image](https://github.com/bitnami/vms/assets/24517082/c6b94c77-4fa8-4e32-8eba-6129a73d2b4b)

### bndiagnostic was not useful. Could you please tell us why?

It doesn't explain what to do of if that is really what is causing the issue

**Comment by gongomgra** [comment]
Hi @imerial,

Thanks for using Bitnami. I visited your website at `https://tfYOUR_DOMAIN.com` and I see the WordPress login page. Did you manage to solve your issue?

**Comment by imerial** [comment]
Hi @gongomgra 
The problem still happens occasionally. I don't understand why. The only thing I can do is reboot the server. Do you have any suggestions based on the logs? I'd really appreciate it.

**Comment by gongomgra** [comment]
Hi @gongomgra,

I checked your bndiagnostic output and a couple of things caught my attention:

* I see your server received a lot of requests from a few IP addresses.
```
-----------------------------------
Check number of lines of Apache access log
-----------------------------------
Running: wc -l access_log
In: /opt/bitnami/apache2/logs/

Output:

42284 access_log



-----------------------------------
Check performance issues: Count number of requests for the 10 most active IP addresses in the last 100.000 requests
-----------------------------------
Running: tail -n 100000 access_log | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 10 | awk '{print $1}'
In: /opt/bitnami/apache2/logs/

Output:

16102
7855
5331
4426
1058
974
606
602
360
360
```

Can you check if your website is under a bot attack?

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/

* I see there is a cronjob configured to run every hour executing a script from the `wp-content` folder. Can it be causing your website to fail while it is running?

Apart from the above, I don't see any other error message in the Apache log other than the one that the tool detected, but unfortunately I don't know what causes it (maybe a plugin?).

**Comment by imerial** [comment]
HI @gongomgra. That's odd because I use a plugin called password protected (https://wordpress.org/plugins/password-protected/) to stop external traffic since I'm still working on the site. I don't understand how it's getting so much traffic. 
Have you heard about problems with this plugin before? Do you have any recommendations to hide the wp-login.php? I'm not sure if that will help with bots.

Thanks in advance!

**Comment by gongomgra** [comment]
Hi @imerial,

I'm afraid I don't have any previous experience with that plugin or how to hide the login page (to be honest, I don't know if WordPress supports it). Did you have any chance to check the guide I shared about bots?

Additionally, we recommend you to ask either to the plugins developers or in the official WordPress forums for further help on this. Notice you will find there people with deeper knowledge in WordPress than we have.

https://wordpress.org/support/forums/
