### ISSUE TITLE
LAMP: Lets Encrypt not executing http:// to https:// after most recent certificate installation

### ISSUE THREAD

**Issue by tooliedotter** [bitnami/vms#1009]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2d9b2902-360e-7ca7-3e56-5411abaa1f78

### bndiagnostic output

[Resources]
Your instance has little available RAM memory.
```
total used free shared buff/cache available Mem: 3885 1564 684 124 1637 1914
Swap: 0 0 0
```
[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the following guide to open server ports for remote access:  **<<- this is NOT ACCURATE, all 3 are open via an AWS security group, and websites are accessible**

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]
Found recent error messages in the MariaDB error log:
```
2023-06-24 21:36:25 1972 [ERROR] Incorrect definition of table
mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
```
[Apache]
Found recent error or warning messages in the Apache error log.
```
[Sat Jun 24 16:15:24.657096 2023] [core:error] [pid 2381:tid 139657239428096]
AH00046: child process 3040 still did not exit, sending a SIGKILL
```
===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

None of the above addressed my issue.

### Describe your issue as much as you can

I use a LAMP stack and have 21 websites on one server using a vhosts file for both http:// and https:// access. 

I wanted to add 2 new domains to my Let's Encrypt certificate on my server. The bncert-tool script failed, and crashed ALL 21 websites on my server. Apache died and would not restart. The script also revoked the previous certificate. I managed to update these files:

bitnami.conf
bitnami-ssl.conf
2 vhosts files

and got Apache going again. I re-ran the bncert-tool again and it appeared to run correctly BUT the directives to shift http:// to https:// and non-www to www are not working despite the files being correct -- I ran a comparison on the backup files and they were identical. 

Rather than trying to troubleshoot a previously broken system, I elected to start a new AWS instance of the same size and move all 21 websites. Yes, it took hours and hours. 

I successfully ran the bncert-tool again on this new instance, but once again, directives to shift `http:// to https://` and `non-www to www` are NOT working. I double-checked the vhosts files I use to ensure that they're pointing to the Let's Encrypt-specific SSL certificates instead of the server-generated ones, and they are.

- If I type in http://www.[websitename].com that's what comes up in the Address bar of the browser, rather than seeing the **https://**www.[websitename].com, and my browser warns me that the website connection is not secure. 
- If I type in https://www.[website name].com, that's what shows in the browser, and I see the lock. 
- If I type in http://[websitename].com, that's what shows in the Address bar, rather than seeing the http://**www**.[websitename].com, and the browser warns me that the connection is not secure. 
- If I type in https://[websitename].com, that's what shows in the Address bar, rather than the https://**www**.[websitename].com address. 

What do I have to do to get the `http:// to https://` and `non-www to www` directives to work?

**Comment by mdhont** [comment]
The following guide explains how to force HTTPS redirection:

https://docs.bitnami.com/aws/apps/wordpress/administration/force-https-apache/

**Comment by tooliedotter** [comment]
I have not changed anything yet: here's what's already in my bitnami.conf file:

`<VirtualHost _default_:80>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  # BEGIN: Configuration for letsencrypt
  Include "/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf"
  # END: Configuration for letsencrypt
  # BEGIN: Support domain renewal when using mod_proxy without Location
  <IfModule mod_proxy.c>
    ProxyPass /.well-known !
  </IfModule>
  # END: Support domain renewal when using mod_proxy without Location
  # BEGIN: Enable HTTP to HTTPS redirection
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
  # END: Enable HTTP to HTTPS redirection
  # BEGIN: Enable non-www to www redirection
  RewriteCond %{HTTP_HOST} !^www\. [NC]
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=permanent,L]
  # END: Enable non-www to www redirection
  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
`
Here's what's in bitnami-ssl.conf:

`<VirtualHost _default_:443>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/tooliedotterpress.com.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/tooliedotterpress.com.key"

  # BEGIN: Configuration for letsencrypt
  Include "/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf"
  # END: Configuration for letsencrypt
  # BEGIN: Support domain renewal when using mod_proxy without Location
  <IfModule mod_proxy.c>
    ProxyPass /.well-known !
  </IfModule>
  # END: Support domain renewal when using mod_proxy without Location
  # BEGIN: Enable non-www to www redirection
  RewriteEngine On
  RewriteCond %{HTTP_HOST} !^www\. [NC]
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [R=permanent,L]
  # END: Enable non-www to www redirection
  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
`

The only thing I see that might be missing is the inclusion of 127.0.0.1 to the following line:

  RewriteCond %{HTTP_HOST} !^localhost

Adding:
`!^(localhost|127.0.0.1)`

Do you see anything amiss in what Let's Encrypt put into the two CONF files?

**Comment by mdhont** [comment]
Can you try to rewrite the non www requests to the https domain directly:

```
  RewriteCond %{HTTP_HOST} !^www\. [NC]
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [R=permanent,L]
```

**Comment by tooliedotter** [comment]
I have 21 websites on this server; do I add those lines to the Virtual Hosts entry for each domain, as follows? [domain substituted]

```
## vaddhost: (my-domain.org) at *:443
<VirtualHost *:443>
    ServerName     my-domain.org
    ServerAlias    www.my-domain.org
    ServerAdmin    root@my-domain.org
    DocumentRoot   "/opt/bitnami/apache/htdocs/my-domain.org"
    SSLEngine on
    SSLCertificateFile "/opt/bitnami/apache/conf/my-server.com.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache/conf/my-server.com.key"
#   SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
#   SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"

    CustomLog      "/opt/bitnami/apache/logs/my-domain.org-access_log" combined
    ErrorLog       "/opt/bitnami/apache/logs/my-domain.org-error_log"
    <Directory "/opt/bitnami/apache/htdocs/my-domain.org">
      Options -Indexes +FollowSymLinks -MultiViews
      AllowOverride All
      Require all granted
    </Directory>
# BEGIN: Enable non-www to www redirection
	RewriteCond %{HTTP_HOST} !^www\. [NC]
	RewriteCond %{HTTP_HOST} !^localhost
	RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
	RewriteCond %{REQUEST_URI} !^/\.well-known
	RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [R=permanent,L]
# END: Enable non-www to www redirection
</VirtualHost>```

**Comment by mdhont** [comment]
It depends on your configuration, if you have a default virtualHost with rules that apply to each of them you can add it there instead.

**Comment by tooliedotter** [comment]
I have 2 vhosts files, one for port 80 and a nearly identical set for port 443. I did add one set of the non-www to www lines to one of the 21 website sets (as shown above) and **it did not work.** 

Is there a setting in another file that I should check? **I need this to work**. I could lose clients over this.

**Comment by tooliedotter** [comment]
Checking back, hoping for a reply.

**Comment by mdhont** [comment]
You could add another "default" vhost above the others with rules that apply to all:

```
# Default VirtualHost for redirection
<VirtualHost *:80>
    ServerAlias *
    RewriteCond %{HTTP_HOST} !^www\. [NC]
    RewriteCond %{HTTP_HOST} !^localhost
    RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
    RewriteCond %{REQUEST_URI} !^/\.well-known
    RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [R=permanent,L]  
   ...
</VirtualHost>
```
The redirection will take effect, and the subsequent rules from the second VirtualHost will be applied after the redirection occurs.

Another option is to add the same rules to all vhosts.

**Comment by tooliedotter** [comment]
I already tried adding the redirection to the top of the non-SSL vhosts file to see whether that worked, and it did not. Where else do I look, since this should work automatically?

**Comment by mdhont** [comment]
The following guide might be of help:

https://docs.bitnami.com/general/apps/wordpress/administration/redirect-custom-domains/

**Comment by tooliedotter** [comment]
MDHont, if you look at this part of my posts, you'll see I already have (and have had all along) ServerAlias entries for each and every website. 

https://github.com/bitnami/vms/issues/1009#issuecomment-1610116317

```
## vaddhost: (my-domain.org) at *:443
<VirtualHost *:443>
    ServerName     my-domain.org
    ServerAlias    www.my-domain.org
    ServerAdmin    root@my-domain.org
    DocumentRoot   "/opt/bitnami/apache/htdocs/my-domain.org"
etc ...
```

So apparently no one has any idea why the **redirects added by your Let's Encrypt scripts aren't working**. Nothing anyone has suggested has worked, and it seems that no one thinks it's worth digging into the LE script to double-check. 

I am disappointed to say that this issues remains UNresolved.

**Comment by mdhont** [comment]
Hi Toolie, 

Please accept my apologies, I will try to reproduce the issue on my side, but could you run the bndiagnostic tool again and send me the code? 

Regards,
Michiel

**Comment by tooliedotter** [comment]
Hi Michiel, here is the bndiagnostic output; again the report has errors, as noted below. 
------------------------------

===== Begin of bndiagnostic tool output =====


    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ? Processes: Found possible issues
    ✓ Apache: No issues found
    ✓ Php: No issues found



[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3885 2230 225 126 1429 1246
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud provider's documentation for more information.

Press [Enter] to continue:
You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-memory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. **<-- NOT accurate, they are all appropriately accessible** 

Please check the following guide to open server ports for remote access: https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-08-19 16:52:18 527886 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).

```
Please check the following guide to troubleshoot MariaDB issues:

Press [Enter] to continue:
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-mariadb/

[Processes]

One or more component's processes are not running:
```
apache not running  <-- **Not accurate, it IS running**
```
You can try to restart the process with the following command:

 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME


===== End of bndiagnostic tool output =====

**Comment by mdhont** [comment]
Hi Toolie,

You are using the following redirect rule (added automatically by bncert)

```
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
```

I think the issue is that it's using SERVER_NAME variable, which contains the value of the hostname. (the output of the "hostname" command in the terminal)

If there is only one domain this works, but if you are using many then you could use the HTTP_HOST variable which will give you the domain name of the request, regardless of the virtual host it is directed to.

```
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [R,L]
```

**Comment by tooliedotter** [comment]
Michiel, I think that's working!! I updated bitnami.conf and bitnami-ssl.conf. 

I see the change redirecting most sites to the HTTPS but it is inconsistent when it comes to the the www version of the URLs. For example:

telltoolie.com <-- comes up with neither SSL nor www
toolie.me <-- comes up with neither SSL nor www
toolie.link  <-- comes up with SSL but not www

None of these sites have anything besides a simple home page (I use them for other reasons) but they are listed in my Let's Encrypt certificate. The rest of my sites are Joomla sites, where I can have that software force the use of HTTPS throughout the site. 

Any further thoughts on this?

**Comment by mdhont** [comment]
Hi Toolie,

The issue could be that the rewrite rules are added to the default vhost:

    <VirtualHost _default_:443>
     ....

The default vhost acts as a fallback for any unmatched requests on port 443, but in your case it's better to use a wildcard:

    <VirtualHost *:443>

Could you try replacing it?

**Comment by tooliedotter** [comment]
Thanks Michiel, I did replace it and it doesn't seem to have made much difference. In fact, for the non-Joomla websites, it's random as to whether the redirect to HTTPS works, with or without the www prefix. You can try it yourself with these domains:

mjmglassstudio.com
toolie.me
toolie.link
telltoolie.com

**Comment by mdhont** [comment]
Could you tell me which sites are not redirecting to https, and which don't? And the same with redirection to www?

**Comment by tooliedotter** [comment]
Hi Michiel, I just updated my Let's Encrypt SSL certificate today (it was due to expire) and I appear to still be having problems. I'm making a complete list for your review; give me a day and I'll have the info for you.

**Comment by tooliedotter** [comment]
Hi Michiel, I have the Excel spreadsheet for you that contains all the domains and my test results, but I'd prefer not to post it here. Can you provide some other way to get the spreadsheet to you?

**Comment by mdhont** [comment]
You can send it to michield@vmware.com. Please also let me know in this thread after uploading it.

**Comment by Yasin-Ali-Cpuflat** [comment]
how you fix apache problem

**Comment by tooliedotter** [comment]
Hi Yasin, it's not fixed yet. Either Michiel or I will post the solution if we find one!

**Comment by tooliedotter** [comment]
@mdhont Michiel, I have emailed the files to you as of now.

**Comment by mdhont** [comment]
Hi Toolie,

Could you try adding the rewrite rules directly to the `apache/conf/vhosts/bitnami-apps-vhosts.conf` and the `apache/conf/vhosts/bitnami-apps-vhosts-ssl.conf` file in the <vhosts> directives of the domains that are not working?
