### ISSUE TITLE
[Bitnami Kafka on GCP] unable to create topic

### ISSUE THREAD

**Issue by anguillanneuf** [bitnami/vms#101]
### Describe your issue as much as you can

Reposting frrom https://github.com/bitnami/bitnami-docker-kafka/issues/267

### Name and Version

bitnami/kafka:3.2.0

### What steps will reproduce the bug?

1. Launch from GCP Marketplace. https://docs.bitnami.com/google/infrastructure/kafka/
2. SSH into VM from GCP Cloud Console.
3. Run `sudo /opt/bitnami/ctlscript.sh status` to confirm Kafka and Zooper are running.
4. Roughly follow https://docs.bitnami.com/google/infrastructure/kafka/administration/run-producer-consumer/ to create a topic but unable to do so. Similar to https://github.com/bitnami/bitnami-docker-kafka/issues/245.
   Command I ran: `sudo /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server [Primary internal IP address copied from VM network details]:2181 --topic my-kafka-topic`
   I also tried 1) the external IP copied from VM network details 2) `localhost:9092` as shown in the Kafka quickstart: https://kafka.apache.org/quickstart

### What is the expected behavior?

Create topic to succeed without having to alter anything in any config files. 

### What do you see instead?

```
tianzi@remote-kafka-vm:/opt/bitnami/kafka$ sudo /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server localhost:2181 --topic my-kafka-topic
Error while executing topic command : Timed out waiting for a node assignment. Call: createTopics
[2022-07-08 23:25:38,410] ERROR org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: createTopics
 (kafka.admin.TopicCommand$)
```

### Additional information

I didn't change any configs and was expecting everything to just work if SSH'ed into the server. Not sure what I'm missing.

**Comment by anguillanneuf** [comment]
Is the following expected? Do I not have a zookeeper running?

```
tz@remote-kafka-vm:~$ sudo /opt/bitnami/ctlscript.sh status
kafka already running
zookeeper already running
tz@remote-kafka-vm:~$ /opt/bitnami/kafka/bin/zookeeper-shell.sh localhost:2181 ls /brokers/ids
Connecting to localhost:2181

WATCHER::

WatchedEvent state:SyncConnected type:None path:null

WATCHER::

WatchedEvent state:SaslAuthenticated type:None path:null
[1001]
[2022-07-12 00:27:06,836] ERROR Exiting JVM with code 0 (org.apache.zookeeper.util.ServiceUtils)
tz@remote-kafka-vm:~$ 
```

**Comment by mdhont** [comment]
Can you check if kafka and zookeeper are running?

    sudo /opt/bitnami/ctlscript.sh status

Can you run the bndiagnostic tool?

    sudo /opt/bitnami/bndiagnostic-tool

**Comment by anguillanneuf** [comment]
Thank you @mdhont. The diagnostic tool was really helpful. My report (31ca933a-a338-2f7a-fdeb-7a959519e4ee) says connectivity issues. Let me try to update my firewall rules and try again. Will come back and update this thread if I make some progress.

**Comment by anguillanneuf** [comment]
I'm still unable to have a successful diagnostics. I have followed the documentation to open port 22, 80, and 443. But no luck. 

```
===== Begin of bndiagnostic tool output =====

 
    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

                                    
Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

de36d991-3247-c9d7-10a6-1b5ecfdf027a

And paste it in your Bitnami Support ticket.
```

**Comment by jotamartos** [comment]
Hi @anguillanneuf,

We are going to evaluate the information and will update this ticket once we have more any updates.

Thanks

**Comment by joancafom** [comment]
Hi @anguillanneuf 

It definitely seems we have some outdated guidelines in our documentation!

> tianzi@remote-kafka-vm:/opt/bitnami/kafka$ sudo /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server localhost:2181 --topic my-kafka-topic

This command is incorrect, you should use the following ones instead for creating topics:

```
$ export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf"

$ /opt/bitnami/kafka/bin/kafka-topics.sh --create --command-config /opt/bitnami/kafka/config/producer.properties --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic test
Created topic test.
```

Could you please verify it works for you as well?

**Comment by anguillanneuf** [comment]
@joancafom The commands in your comment above is working for me. However, it's not clean due to some outdated config options. 

```
tianzi_google_com@kafka-bitnami-vm:~$ /opt/bitnami/kafka/bin/kafka-topics.sh --create --command-config /opt/bitnami/kafka/config/producer.properties --bootstrap-server localhost:9092 --topic test
Created topic test.
[2022-07-29 21:42:23,119] WARN The configuration 'compression.type' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
[2022-07-29 21:42:23,120] WARN The configuration 'max.request.size' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
Created topic test.
-bash: Created: command not found
```

Will the docs be updated?

**Comment by joancafom** [comment]
Glad to see it worked! 

>However, it's not clean due to some outdated config options.

It is strange though. Those options are set in the default `producer.config` file, so it is not related to some particular configuration on our side. Nevertheless, they are just warnings and I don't think they are of great importance.

>Will the docs be updated?

Yes, we will work on updating the documentation to reference the new syntax, thanks!

**Comment by corico44** [comment]
The documentation has been successfully updated and can now be found here: https://docs.bitnami.com/general/infrastructure/kafka/.
Thank you very much for reporting this issue.
