### ISSUE TITLE
Found recent error messages in the MariaDB error log: ``` ??:0(std::error_code::default_error_condition() const)[0x7fb7282f4ed0]

### ISSUE THREAD

**Issue by ben-trumpetmedia** [bitnami/vms#1010]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e0f90839-7caf-5ef3-8c49-f935cb7d19b2

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ? Processes: Found possible issues
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 950 389 75 8 485 375 Swap: 634 
28 606
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
??:0(std::error_code::default_error_condition() const)[0x7fa482604ed0]

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Processes]

One or more component's processes are not running:
Press [Enter] to continue:
```
mariadb not running
```
You can try to restart the process with the following command:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Jun 25 17:00:05.212715 2023] [autoindex:error] [pid 1376:tid 
140261359224576] [client **ip_address**:42638] AH01276: Cannot serve directory 
/opt/bitnami/wordpress/wp-admin/css/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive, referer: binance.com
 [Sun Jun 25 17:08:28.938487 2023] [proxy_fcgi:error] [pid 1648:tid 
140260679874304] (70008)Partial results are valid but processing is incomplete: 
[client **ip_address**:18783] AH01075: Error dispatching request to : (reading 
input brigade)

```
Please check the following guide to troubleshoot server issues:
Press [Enter] to continue:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

mariadb is not running

### Describe your issue as much as you can

mariadb won't run. I just run sudo /opt/bitnami/ctlscript.sh restart

Only apach and php-fpm run

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one.
