### ISSUE TITLE
[wordpress] <bitnami Stack>

### ISSUE THREAD

**Issue by sanwar98** [bitnami/vms#1011]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Nil

### bndiagnostic output

    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Jun 26 18:32:12.585926 2023] [core:error] [pid 21881:tid 139957389543168]
[client **ip_address**:17554] AH00037: Symbolic link not allowed or link target
not accessible: /opt/bitnami/wordpress/wp-content, referer:
https://accentedge.health/wp-admin/themes.php
 [Mon Jun 26 18:33:21.904467 2023] [core:error] [pid 21881:tid 139957565789952]
[client **ip_address**:10697] AH00037: Symbolic link not allowed or link target
Press [Enter] to continue:
not accessible: /opt/bitnami/wordpress/wp-content, referer:
https://accentedge.health/wp-admin/index.php
 [Mon Jun 26 18:33:22.148975 2023] [core:error] [pid 21881:tid 139957498648320]
[client **ip_address**:10697] AH00037: Symbolic link not allowed or link target
not accessible: /opt/bitnami/wordpress/wp-content, referer:
https://accentedge.health/wp-admin/index.php

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

[Resources]

Your instance has little available RAM memory.
Press [Enter] to continue:
```
 total used free shared buff/cache available Mem: 1965 1044 90 142 831 608 Swap:
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I am not sure if the suggested guides are related to my issue or not

### Describe your issue as much as you can

My website got greyed and wordpress dashboard throws the following errors:

1) An automated WordPress update has failed to complete! Please notify the site administrator.

2)
The theme directory "astra-child" does not exist.
Error: The themes directory is either empty or does not exist. Please check your installation.

Furthermore i would also wanted to know the location of .maintaince file(or an alternatives to disable the automatic updates )

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one.
