### ISSUE TITLE
[WordPress] AH01630: client denied by server configuration for akismet plugin

### ISSUE THREAD

**Issue by jazzl0ver** [bitnami/vms#1012]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c33b957a-9823-62df-ccb6-4b9cd84f9f5f

### bndiagnostic output

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 472 352 5 35 114 71 Swap: 634
80 554
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Tue Jun 27 08:09:03.779996 2023] [authz_core:error] [pid 1797:tid
139784399873792] [client **ip_address**:21719] AH01630: client denied by server
configuration:
/opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/img/akismet-refresh-logo.s
vg, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config

```

### bndiagnostic was not useful. Could you please tell us why?

it doesn't provide a solution for the issue described

### Describe your issue as much as you can

After activating AkisMet plugin in the default bitnami wordpress installation on AWS Lightsail, there're the following errors in the apache's error_log:
```
[Tue Jun 27 08:08:50.277281 2023] [authz_core:error] [pid 1797:tid 139784550680320] [client x.y.244.58:3140] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/fonts/inter.css, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config&view=start
[Tue Jun 27 08:08:50.278839 2023] [authz_core:error] [pid 2935:tid 139784919959296] [client x.y.244.58:28397] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/akismet-admin.css, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config&view=start
[Tue Jun 27 08:08:50.282068 2023] [authz_core:error] [pid 1798:tid 139784601036544] [client x.y.244.58:1717] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/akismet-admin.js, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config&view=start
[Tue Jun 27 08:08:50.401675 2023] [authz_core:error] [pid 1797:tid 139784542287616] [client x.y.244.58:3140] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/img/akismet-refresh-logo.svg, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config&view=start
[Tue Jun 27 08:08:50.431177 2023] [authz_core:error] [pid 2935:tid 139784945137408] [client x.y.244.58:28080] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/akismet-admin.js, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config&view=start
[Tue Jun 27 08:08:50.565038 2023] [authz_core:error] [pid 1797:tid 139784533894912] [client x.y.244.58:3140] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/img/akismet-refresh-logo.svg, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config&view=start
[Tue Jun 27 08:09:03.493562 2023] [authz_core:error] [pid 1798:tid 139784567465728] [client x.y.244.58:61199] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/akismet-admin.js, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config
[Tue Jun 27 08:09:03.493738 2023] [authz_core:error] [pid 1798:tid 139784567465728] [client x.y.244.58:59450] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/akismet-admin.css, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config
[Tue Jun 27 08:09:03.493933 2023] [authz_core:error] [pid 1797:tid 139784491931392] [client x.y.244.58:21719] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/fonts/inter.css, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config
[Tue Jun 27 08:09:03.610522 2023] [authz_core:error] [pid 2935:tid 139784844424960] [client x.y.244.58:41249] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/img/akismet-refresh-logo.svg, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config
[Tue Jun 27 08:09:03.644780 2023] [authz_core:error] [pid 1797:tid 139784408266496] [client x.y.244.58:21719] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/akismet-admin.js, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config
[Tue Jun 27 08:09:03.779996 2023] [authz_core:error] [pid 1797:tid 139784399873792] [client x.y.244.58:21719] AH01630: client denied by server configuration: /opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/img/akismet-refresh-logo.svg, referer: http://a.b.140.52/wp-admin/admin.php?page=akismet-key-config
```

**Comment by jotamartos** [comment]
Please note that those errors are usually expected because the application may be blocking some requests that are not expected for example when accessing configuration files, or data that shouldn't be accessible from outside. In this case, as it's a Akismet-related error, I suggest you ask the plugin's developers to know if that's expected or not.

**Comment by jazzl0ver** [comment]
I'll try to report that issue to the Akismet developers. It would be nice though if you could also check what's wrong, b/c you package that plugin with your default installation

**Comment by bluefuton** [comment]
Hi folks 👋 I work on the Akismet team at Automattic and hopefully can help you figure this out.

These asset files in the error messages were all new additions in the recent Akismet 5.2 release:

https://akismet.com/blog/version-5-2-of-the-akismet-wordpress-plugin-is-now-available/

We made some changes to the .htaccess that is bundled with the plugin to allow public access to these new files:

https://plugins.svn.wordpress.org/akismet/trunk/.htaccess

...but it looks like Apache is blocking them in this case. Is there anything extra in Bitnami's config that might cause this to happen?

**Comment by jotamartos** [comment]
Thank you for the information @bluefuton. Due to security and performance reasons, we move all .htaccess information to a single htaccess.conf file when building the image. You can learn more about this here

https://docs.bitnami.com/general/apps/wordpress/administration/use-htaccess/

In this case, as the image was built using Akismet 5.1, it does not include the new changes in the htaccess.conf file so you get the error/warning messages in the log when updating the plugin to version 5.2. To solve this issue, you can simply update the htaccess.conf file with the new information and restart Apache for the changes to take effect. 

I just checked that our pipelines already built a new version of the WordPress solution including the latest version of the plugin and it should be available in the different marketplaces soon. 

Thanks

**Comment by jazzl0ver** [comment]
@jotamartos can you pls share the current wordpress-htaccess.conf that does not have issues with the latest akismet plugin?

**Comment by jotamartos** [comment]
You just need to update the information that is inside the akismet's Directory block 

```
<Directory "/opt/bitnami/wordpress/wp-content/plugins/akismet">
  # Only allow direct access to specific Web-available files.

  # Apache 2.2
  <IfModule !mod_authz_core.c>
        Order Deny,Allow
        Deny from all
  </IfModule>

  # Apache 2.4
  <IfModule mod_authz_core.c>
        Require all denied
  </IfModule>

  # Akismet CSS and JS
  <FilesMatch "^(form\.js|akismet(-frontend|-admin)?\.js|akismet(-admin)?(-rtl)?\.css|inter\.css)$">
        <IfModule !mod_authz_core.c>
                Allow from all
        </IfModule>

        <IfModule mod_authz_core.c>
                Require all granted
        </IfModule>
  </FilesMatch>

  # Akismet images
  <FilesMatch "^(logo-(a|full)-2x\.png|akismet-refresh-logo\.svg|akismet-refresh-logo@2x\.png|arrow-left\.svg)$">
        <IfModule !mod_authz_core.c>
                Allow from all
        </IfModule>

        <IfModule mod_authz_core.c>
                Require all granted
        </IfModule>
  </FilesMatch>
</Directory>
```
