### ISSUE TITLE
[Discourse] How to setup DISCOURSE_ENABLE_CORS env variable

### ISSUE THREAD

**Issue by aneeravagrawal** [bitnami/vms#1015]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

### bndiagnostic was not useful. Could you please tell us why?

suggested guide is not working as expected

### Describe your issue as much as you can

how to set DISCOURSE_ENABLE_CORS env variable  to true to enable CORS.

**Comment by jotamartos** [comment]
Hi @aneeravagrawal,

That's a specific env var that the Discourse team provides when deploying the solution and it's not supported in our VM. If you want to enable CORS in Discourse, I understand you need to follow a similar approach to the one we have for WordPress 

https://docs.bitnami.com/aws/apps/wordpress/configuration/enable-cors-wordpress/

You will basically need to enable CORS in the Apache's configuration (/opt/bitnami/apache/conf/vhosts/discourse-vhost.conf and /opt/bitnami/apache/conf/vhosts/discourse-https-vhost.conf files) and restart Apache for the changes to take effect. If the application requires to make any change to enable this functionality, you will need to review its documentation and configuration specifically.
