### ISSUE TITLE
Azure Marketplace Bitnami Drupal Image - Deprecated Image move to new subscription

### ISSUE THREAD

**Issue by mrcitizenkane** [bitnami/vms#1017]
Assisting a customer looking to move a production VM in Azure from one subscription to another. The VM in question was deployed using a Bitnami Drupal multitier image from the Azure Marketplace. The image was deprecated in March of this year. The documented process is to deallocate the VM, clone or move the disks, create a new VM with the existing disks. However, a key step is to accept the Marketplace offer/plan in the new subscription. Because offer/plan is now deprecated, it is not available to accept and the new VM will not come up. 

Is there any workaround to this to move the existing VM with minimal effort? Some way to disconnect the image from the marketplace? Or is the only option to build new and migrate data etc?

**Comment by mdhont** [comment]
Unfortunately the only possibility seems to build a new image and migrate the data. In any case could you share the the documented process you are referring to?

**Comment by mrcitizenkane** [comment]
Here is the MS docs: 

Powershell
https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/move-limitations/virtual-machines-move-limitations?tabs=azure-powershell#virtual-machines-with-marketplace-plans

AZ CLI
https://learn.microsoft.com/en-us/azure/virtual-machines/azure-cli-change-subscription-marketplace

**Comment by mdhont** [comment]
Thank you for sharing the links. Unfortunately in case of deprecation it's necessary to migrate the data.
