### ISSUE TITLE
How do I upgrade my operating system?

### ISSUE THREAD

**Issue by kshibay** [bitnami/vms#1018]
### Describe your issue as much as you can

We are using Debian GNULinux 10 as our Redmine server.

We have recently experienced several problems with linux on Debian GNULinux 10, including arbitrary code execution, and we would like to upgrade the OS version.

Could you please tell us how to deal with this problem?

Redmine itself is also "Redmine 4.1.1.stable" and I would like to know how to upgrade.

Thank you in advance for your help.

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, as a result, it is not possible to update the operating system without possibly causing issues with the application. We recommend launching a new instance and then migrate the Redmine data there.

**Comment by kshibay** [comment]
Sorry for the late reply.

I would like to create a new server from "redmine packaged by bitnami" and migrate data.

The old environment was MySQL and the new one is MariaDB. 500 error occurs when I export/import the dump file.

Is there a page that I should refer to when migrating the data?

**Comment by mdhont** [comment]
It shouldn't matter migrating from mysql to mariadb. What is more likely is that the difference between the old (mysql) and the new (mariadb) version are causing the error. These kind of issues exceed the scope of this forum which is only for Bitnami related configuration issues. I recommend asking in a dedicated Mariadb forum:

https://mariadb.com/kb/en/community/

**Comment by kshibay** [comment]
Thank you for your response.
I will inquire about it.
Please keep this issue closed.
