### ISSUE TITLE
[Lightsails Magento 2] Flush php not working

### ISSUE THREAD

**Issue by gastonciani** [bitnami/vms#1019]
### Describe your issue as much as you can

I have an AWS lightsail by bitnami and I'm trying to flush a string like "loading..." before running a function but only loads after finishing the function, for what i have read it has to do with mod_deflate or mod_gzip, but i could be wrong, i look for the modules in the .conf files but i couldn't find mention of the module, i also went to the .htaccess file but everything about the module is commented, how can i fix this problem

**Comment by gongomgra** [comment]
Hi @gastonciani,

Thanks for using Bitnami. I'm afraid I can't fully understand your question. Can you elaborate it a bit?

**Comment by gastonciani** [comment]
Sure i have this script, it runs fine in my localhost, i have also tried it in a empty ec2 instance with apache and php8 and works fine, it writes the message letter by letter in the frontend, but in the bitnami server the message only appears after finishing the phrase, as i said before, I've read that its has to do whit those modules, I think i don't need to disable it completely but just exclude this file or folder to work

`header("Content-type: text/event-stream");
header("Cache-Control: no-cache");

ob_end_flush();

$message = "Loading... please wait!";

foreach ( str_split($message) as $letter) {


    echo "event: message\n";
    echo "data: ".$letter."\n\n";
    flush();
    if(connection_aborted()) break;
    usleep(1000*50);
}
echo "event: stop\n";
echo "data: stopped\n\n";

//run other functions`

**Comment by mdhont** [comment]
Can you try to disable opcache?

To disable OPCache, change opcache.enable in your php.ini file and set it to 0  in `/opt/bitnami/php/etc/php.ini`
