### ISSUE TITLE
[wordpress] Site becomes unavailable every few weeks - timeout. 

### ISSUE THREAD

**Issue by Tilmiz** [bitnami/vms#102]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

fe54ebc4-7743-8f9c-09ac-eee25cda1d41

### bndiagnostic was not useful. Could you please tell us why?

I guess it is useful

### Describe your issue as much as you can

 ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Jul 11 06:00:22.318095 2022] [core:error] [pid 24004:tid 140078881797888] 
[client **ip_address**:42942] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
 [Mon Jul 11 09:49:21.731158 2022] [autoindex:error] [pid 24004:tid 
140078789478144] [client **ip_address**:58409] AH01276: Cannot serve directory 
Press [Enter] to continue:
/opt/bitnami/wordpress/wp-admin/css/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive, referer: binance.com
 [Mon Jul 11 13:07:29.972182 2022] [autoindex:error] [pid 24005:tid 
140079200720640] [client **ip_address**:62833] AH01276: Cannot serve directory 
/opt/bitnami/wordpress/wp-admin/css/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive, referer: binance.com

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

**Comment by mdhont** [comment]
As mentioned in the output of the bndiagnostic tool, there are many requests coming from the same IP addresses, which indicates a bot attack. The following guide shows how you can deny access to those adresses:

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/
