### ISSUE TITLE
[Akeneo] Marketplace unavailble

### ISSUE THREAD

**Issue by Groep-e** [bitnami/vms#1020]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bb791a39-16e0-140e-b654-6d5dd391a70e

### bndiagnostic output

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Processes: No issues found
    ✓ Mysql: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

not related to my issue i guess

### Describe your issue as much as you can

Hi there,

I try to add a bundle from the marketplace but it's all blocked.

I found this inside on the view appstore on the internet link ==> https://api.apps.akeneo.cloud/?utm_medium=pim&utm_content=marketplace_button&utm_source=http%3A%2F%2Flocalhost%3A80&utm_term=pim_administrator.

how can i change the localhost inside the link ?

thanks,

**Comment by mdhont** [comment]
The link doesn't seem to be working. Could you describe the steps to reproduce the issue?
