### ISSUE TITLE
[<bitnami-wordpress-apache-debian-vm>] <How to enable and configure mod_expires on a bitnami-wordpress-apache-debian-vm?>

### ISSUE THREAD

**Issue by parallelhearts1** [bitnami/vms#1021]
### Describe your issue as much as you can

Hi support, the path /opt/bitnami/apps/wordpress/conf/httpd-app.conf is outdated, so can you please help me. 

For your reference: https://onepagezen.com/add-expires-headers-wordpress-bitnami/

**Comment by mdhont** [comment]
You can find it here: ` /opt/bitnami/wordpress/conf/httpd-app.conf`
