### ISSUE TITLE
[WordPress] There has been a critical error on this website.

### ISSUE THREAD

**Issue by izzuddin-sk** [bitnami/vms#1024]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ID does not show, took long time loading

### bndiagnostic output

 ? Apache: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
    ✓ Resources: No issues found
    ? Wordpress: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Jul 03 17:31:57.138842 2023] [autoindex:error] [pid 14768:tid 
139699507128064] [client **ip_address**:38294] AH01276: Cannot serve directory 
/opt/bitnami/wordpress/wp-includes/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive
Press [Enter] to continue:
 [Mon Jul 03 22:11:04.223546 2023] [core:error] [pid 14768:tid 139699280525056] 
[client **ip_address**:34500] AH10244: invalid URI path 
(/dana-na/../dana/html5acc/guacamole/../../../../../../../etc/services?/dana/html
5acc/guacamole/)
 [Mon Jul 03 23:11:34.759573 2023] [proxy_fcgi:error] [pid 13651:tid 
139699481949952] [client **ip_address**:13035] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: http://www.kurma2u.com/
```

Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

Found recent WordPress plugin related error messages in the Apache error log.
Press [Enter] to continue:
```
[Mon Jul 03 09:01:31.900840 2023] [proxy_fcgi:error] [pid 6429:tid 
139700228376320] [client **ip_address**:33880] AH01071: Got error 'PHP message: 
PHP Fatal error: Uncaught Error: Call to undefined function 
a8aT-6=fh$Ķb7-85a-Þ~Ðe6£4dhhBeHaTQ8fa2c8kdí«2faí46b7!85áF*gK0eæc1beOa)QÂbm
CÑbÔ() in 
/bitnami/wordpress/wp-content/plugins/translatepress-business/add-ons-pro/vxlzutm
k.php:67
Stack trace:
#0 /bitnami/wordpress/wp-content
```

Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

I tried the suggested guide but it does not do anything.

### Describe your issue as much as you can

Hi, 
at first I think there's probably permission error, so I tried the permission default settings but nothing change.
```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress/
sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;
sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
```

next, I tried to deactivate all plugins but its loading for a very long time.

![chrome_sHBf9SiIx7](https://github.com/bitnami/vms/assets/133965334/1b40838e-d10c-4ed8-a7dd-d0a5d1a2f558)
![chrome_QMUimyYun4](https://github.com/bitnami/vms/assets/133965334/0e24fa83-0a26-4a20-801e-0de2be09036c)

**Comment by itsmemidhuz123** [comment]
Hi brother, could you please try reactivate all plugin one by one. As wordpress admin is not accessible, try using a command: wp plugin deactivate --all

This helps to deactivate all plugin at once, once fone try active each one by one.

Deactivate unnecessary plugin and delete accordingly if not necessary.

I hope this helps

**Comment by Yasin-Ali-Cpuflat** [comment]
hi am facing the same problem . can any body help?

**Comment by gongomgra** [comment]
Hi @Yasin-Ali-Cpuflat,

I see you opened a [new thread for your issue](https://github.com/bitnami/vms/issues/1144). We will close this thread and continue helping you there.
