### ISSUE TITLE
Redirect HTTPS IP access to domain

### ISSUE THREAD

**Issue by jnayak01** [bitnami/vms#1025]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c1ff0c19-819d-6551-18d0-906a432dfc01

### Describe your issue as much as you can

Hello, I'm working on Wordpress website hosted in AWS Lightsail with a Bitnami package.

I'd like to redirect all attempts to access the website's public IP (XX.XX.XX.XX) over to the domain. Basically, when a user or attacker tries to access https://xx.xx.xx.xx/home or https://xx.xx.xx.xx/some-page/ , we'd like to force-redirect them to https://www.mydomain.com/home or https://www.mydomain.com/some-page/ correspondingly.

So far, none of the solutions we've researched online have helped me.
The IP via HTTPS is still accessible, and accessing any random location (like https://ip/non-existing-file/) shows a 404 but it does not point to the domain.
If you access just the IP, without any subdirectory, it does not redirect you to the domain.

We are using the Bitnami HTTPS configuration tool (bncert) to enable HTTPS on our Certified by Bitnami WordPress instance on Amazon Lightsail (ref- https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-enabling-https-on-wordpress ). We followed the steps in the article to enable HTTP to HTTPS redirection and non-www to www redirection. Also we referred the following article to redirect All Domains To Your Own Domain And Force HTTPS - https://docs.bitnami.com/aws/apps/wordpress/administration/use-single-domain/

If you access the website via domain name, the redirections happen properly.

CURRENT INCORRECT BEHAVIOUR WE SEE

Allows website access via IP , and If you access the website via IP, the redirection to HTTPS happens but shows 'Certificate is not valid'.
Allows website access via IP , and If you access the website via IP, the redirection from non-www to www does not happen.
Summary - I want to restrict any access to the website via IP , instead redirect IP access through domain

I created a ticket earlier #949, and following suport provided in the ticket , i was able to solve the issue with HTTP. But the issue still persists for HTTPS. I cleared the cache and also tried accessing the website via IP in incognito mode. The HTTP redirection works fine but the issue still persists for HTTPS.

![IP via HTTPS access issue](https://github.com/bitnami/vms/assets/134688875/9acbdd43-6922-467a-8907-fbe3bea238bd)

**Comment by gongomgra** [comment]
Hi @jnayak01,

Thanks for using Bitnami. This question seems to be similar to another one you had recently. Can you check my last reply in that ticket?

https://github.com/bitnami/vms/issues/949#issuecomment-1588995369

**Comment by itsmemidhuz123** [comment]
Could you please try using cloudflare please, hope that helps you.

**Comment by jnayak01** [comment]
Hi @gongomgra ,

Thanks for your response. In your reply at #949 , you had replied below 

`From our experience, the second use case (accessing via HTTP with the IP address) is the most frequent of them. It is not usual accessing an IP address with HTTPS. In case you need to cover that specific use case, you will have to get your server IP address included in the SSL certificate, and also include the Apache configuration to redirect non-domain requests to your domain in the wordpress-https-vhost.conf file.`

I dif not understand the part  - `... In case you need to cover that specific use case, you will have to get your server IP address included in the SSL certificate, and also include the Apache configuration to redirect non-domain requests to your domain in the wordpress-https-vhost.conf file.`

Can you pls elaborate and explain me what you are suggesting me to do to resolve the issue ?

Thanks

**Comment by gongomgra** [comment]
Hi @jnayak01,

In general, SSL certificates are bound to domain names (`mydomain.com`) instead of IP addresses, but some SSL providers allow you to include a public IP address on it. According to its website, the [lego tool](https://go-acme.github.io/lego/), which is the tool we use to generate SSL certificates, supports it. However, I'm afraid I don't know if you would need to use a special flag when creating the certificate. Can you check it in the official forums?

https://github.com/go-acme/lego/discussions

Regarding the Apache configuration required, you already have it included in the HTTP config file (`wordpress-vhost.conf`) under the `# BEGIN: Redirect all domains to your own domain and force https` section. You will have to include the same section in the `wordpress-https-vhost.conf` file and restart Apache for changes to take effect.
