### ISSUE TITLE
Error while running bndiagnostic tool - Bitnami/Wordpress/ AWS Lightsail

### ISSUE THREAD

**Issue by jnayak01** [bitnami/vms#1026]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c1ff0c19-819d-6551-18d0-906a432dfc01

### Describe your issue as much as you can

I am getting  error while running bndiagnostics tool .

**Comment by mdhont** [comment]
Could you give more details regarding the issue you are having with the application?

**Comment by jnayak01** [comment]
Hello @mdhont ,

When I ran  bndiagnostic tool on AWS Bitnami Lightsail wordpress installation, it showed couple of errors on apache error log.
I referred https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/, but  was not able to resolve those errors . Can you take a look and suggest me resolution ? 

The bndiagnostic tool code for checking log is   c1ff0c19-819d-6551-18d0-906a432dfc01

Screen shot of error from apache error log - 
![image](https://github.com/bitnami/vms/assets/134688875/eda9656f-aa4b-4069-9dad-92fb3f99680c)


Thank You.

**Comment by mdhont** [comment]
Are you having an issue running the application itself?
