### ISSUE TITLE
Bitnami LightSail MySQL Connection Errror 

### ISSUE THREAD

**Issue by Sir-Gordon** [bitnami/vms#1027]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4a79ad1c-6c10-0daf-baeb-249fc2b307b1

### bndiagnostic output

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Resources: No issues found
    ✓ Mysql: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Jul 05 17:45:42.700575 2023] [proxy_fcgi:error] [pid 6467:tid 
140425532684032] [client **ip_address**:56654] AH01071: Got error 'PHP message: 
PHP Warning: mysqli_connect(): (HY000/2002): No such file or directory in 
/opt/bitnami/apache/htdocs/portal/zp-core/functions-db-MySQLi.php on line 30'
Press [Enter] to continue:
 [Wed Jul 05 17:46:00.689737 2023] [proxy_fcgi:error] [pid 7339:tid 
139646029788928] [client **ip_address**:52650] AH01071: Got error 'PHP message: 
PHP Warning: mysqli_connect(): (HY000/2002): No such file or directory in 
/opt/bitnami/apache/htdocs/portal/zp-core/functions-db-MySQLi.php on line 30'

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

The docs does not have my particular issue to resolve 

### Describe your issue as much as you can

Hi,

I am running the Bitnami LAMP Stack on AWS LightSail. I am using a CMS platform called Zenphoto to display a gallery of photos. The platform asks for my database credentials in a config file is is composed of 

```
////////////////////////////////////////////////////////////////////////////////
$conf['db_software'] = "MySQLi";
/** for historical reasons these fields reference mysql even though the database **
 ** might be a different software**/
$conf['mysql_user'] = '';           // Supply your Database user id.
$conf['mysql_pass'] = '';           // Supply your Database password.
$conf['mysql_host'] = 'localhost';  // Supply the name of your Database server.
$conf['mysql_database'] = 'zenphoto';       // Supply the name of Zenphoto's database
// If you're sharing the database with other tables, use a prefix to be safe.
$conf['mysql_prefix'] = ".";
$conf['mysql_port'] = "3306"; // Change if your server uses a different port

// If you are having problems with displaying some characters you may have to change
// the following:
$conf['UTF-8'] = true;

////////////////////////////////////////////////////////////////////////////////
// Required options
////////////////////////////////////////////////////////////////////////////////

// location of album folder.
// 'album_folder' is the name of the folder for the zenphoto albums.
// 'album_folder_class' determines how to interpret 'album_folder':
//    'std'         --  the folder must be a simple name. It resides in the root
//of the zenphoto installation.
//    'in_webpath'  --  the folder must be the full path of the album folder from
//the WEB root of the zenphoto installation. The WEB root of
//your i$
//if the$
//    'external'    --  the folder must be a full server path to the album folder.
//Images within an external folder are not visible to web
//browsers, so certain features such as flash players cannot
//display them
$conf['album_folder'] = '/albums/';
$conf['album_folder_class'] = 'std';

// Server Protocol

$conf['server_protocol'] = "https";

// Change this to "https" if you use an HTTPS server (a "https://..." url)
// Otherwise you should leave it at "http"
//
////////////////////////////////////////////////////////////////////////////////
// Zenphoto special URL rule definitions
//
// for further documentation see the rewrite.php doc block
//
$conf['special_pages'] = array(
'page'=> array('define'=>'_PAGE_', 'rewrite'=>'page'),
'search'=> array('define'=>'_SEARCH_', 'rewrite'=>'_PAGE_/search'),
'archive'=> array('define'=>'_ARCHIVE_', 'rewrite'=>'_PAGE_/archive'),
'tags'=> array('define'=>'_TAGS_', 'rewrite'=>'_SEARCH_/tags'),
'gallery'=> array('define'=>'_GALLERY_INDEX_', 'rewrite'=>'_PAGE_/gallery')
);
//
////////////////////////////////////////////////////////////////////////////////
// Path Overrides
////////////////////////////////////////////////////////////////////////////////
// Uncomment the following two lines ONLY IF YOU'RE HAVING PROBLEMS,
// like "file not found" or "not readable" errors.
// These allow you to override Zenphoto's detection of the correct paths
// on your server, which might work better on some setups.
////////////////////////////////////////////////////////////////////////////////

// define('WEBPATH', '/zenphoto');
// define('SERVERPATH', '/full/server/path/to/zenphoto');

////////////////////////////////////////////////////////////////////////////////
/** Do not edit below this line. **/
/**********************************/
$_zp_conf_vars = $conf;
unset($conf);
?>
```

In this file, I have my username, password, host, database, and port number. Somehow the platform is not seeing the correct hostname I think. 

I logged into AWS LightSail terminal and I was able to log into MySQL using the command:

```
mysql -u username -p password 

```

I double-checked the credentials in the config file and they match the username, password, and port. The host says localhost 
which had been working till today and now I can't see my site working.  Is there a way to identify the correct host for the 
MySQL database?

**Comment by Sir-Gordon** [comment]
Also forgot to add that my php.ini file was completely empty. I'm not sure why. I have made a copy from the php.ini-production file.

**Comment by gongomgra** [comment]
Hi @Sir-Gordon,

Thanks for using Bitnami. According to the bndiagnostic output, your Apache configuration is wrong. Can you check it?

```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: module log_config_module is built-in and can't be loaded
```

Apart from that, it looks like your database server is not recognized as part of the Bitnami installation. Did you modify anything else?

```
-----------------------------------
Get the ctlscript status
-----------------------------------
Running: ./ctlscript.sh status
In: /opt/bitnami

Output:

apache already running
php-fpm already running
```

Can you try starting a fresh new server?

**Comment by Sir-Gordon** [comment]
Hi @gongomgra 

The website was working fine. I did an SSL renewal and five minutes after that it crashed. The php ini file was empty when I initially opened it so I made a copy from the php.ini-production file. I don't think mysql is being recognized as I cannot get the status for it or find the service for it.

I can try starting a fresh new server. To port over my website I just move it to the htdocs folder?

**Comment by gongomgra** [comment]
Hi @Sir-Gordon,

How did you renew the SSL certificate? Our cronjob command is not supposed to remove or empty any file in your server. It is weird to me that the PHP ini file was empty after that.

Unfortunately, MySQL can't be reinstalled on your server, that's why I suggested launching a new server. The process to migrate your website depends on the website itself, but it normally requires to migrate the files and then import the database data into the new server.

**Comment by Sir-Gordon** [comment]
I used the AWS guide to renew the SSL. 
https://repost.aws/knowledge-center/lightsail-bitnami-renew-ssl-certificate

I don't even know how MySQL service got removed but the application still works to log in. 


I could launch a new server  but it would take a long time to migrate the website and setup to be working like before.

**Comment by Sir-Gordon** [comment]
Ended up resolving the issue. I didn't have to make a new server. I had to change the hostname from localhost to 127.0.0.1 since its TCP driven. The website is working fine now.  I still get the mysql.service not found yet I can login to mysql -h localhost or 127.0.0.1. I think my sock is working fine even though mysql is removed from /etc/init.d/ 

Is there a way to restore that or make a new script?

**Comment by gongomgra** [comment]
Hi @Sir-Gordon,

I'm afraid adding the MySQL server manually to the ctlscript is not possible. We highly recommend you to launch a new server and migrate the app data there. Sorry for the inconveniences.

**Comment by Sir-Gordon** [comment]
Hi, @gongomgra 

Well, I will hold onto this server as long as possible until it crashes for good. I checked that MYSQL is installed but the script in init.d has been removed.

**Comment by gongomgra** [comment]
Hi @Sir-Gordon,

Thanks for your message. We don't install our services into the `init.d` directory. We have been using a different custom approach for this (the `ctlscript.sh` controls them along with other tools). We are in the process of moving this to more standard solutions like `systemd`. At this moment, our virtual-machines configure Bitnami services with `systemd`, and we are working on generating the cloud images based on the same idea. Unfortunately, I can't provide any ETA on this.

https://bitnami.com/stacks/virtual-machine
