### ISSUE TITLE
Liferay portlet is temporarily unavailable

### ISSUE THREAD

**Issue by neilsrg** [bitnami/vms#103]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

fa7ee1f9-0fb5-a3a6-fbaf-790a5c60c62e

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Apache: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
```
Press [Enter] to continue:
 total used free shared buff/cache available Mem: 7978 5342 1449 9 1187 2381 
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

n/a

### Describe your issue as much as you can

I want to deploy my package **liferay_portletTemplate-1.0.0.jar** into liferay portal
- I uploaded to the /opt/bitnami/liferay/deploy folder
- chmod 777 so liferay can proceed
- The deployment was success

then, I login to liferay portal
- login as an admin
- edit a page
- search for the new deployed portlet called liferay_portletTemplate and drag it to the page
- the portlet displays Liferay_portletTemplte is temporarity unavailable
- Publish it
- then open the page, it still displays the Liferay_portletTemplte is temporarity unavailable message.

I check the the following folders:
- deploy: is empty, the package has been processed
- work: NO folder created for the new portlet I deployed.

2022-07-12 04:50:28.922 ERROR [ajp-nio-127.0.0.1-8009-exec-9][render_portlet_jsp:77] null
java.io.FileNotFoundException: /opt/bitnami/liferay/work/liferay_portletTemplate-1.0.0/org/apache/jsp/view_jsp.java (No such file or directory)
	at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]

Am I missing something? the permission, or others?
Why it doesn't create the application folder under the /opt/bitnami/liferay/work folder?

**Comment by mdhont** [comment]
Could you try changing the group of the files in that folder to tomcat?

    chown -R /opt/bitnami/liferay/deploy bitnami:tomcat
