### ISSUE TITLE
[AWS WordPress] Unable to connect through WinSCP/VSCode

### ISSUE THREAD

**Issue by hichotu** [bitnami/vms#1031]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9e85f760-340e-6a77-eb73-d1849e889d3b

### bndiagnostic output

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall

[Wordpress]

Press [Enter] to continue:
Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

Found recent WordPress plugin related error messages in the Apache error log.
```
[Mon Jul 10 10:11:26.587855 2023] [proxy_fcgi:error] [pid 35947:tid 
139881649010432] [client **ip_address**:61826] AH01071: Got error 'PHP message: 
PHP Deprecated: strstr(): Passing null to parameter #1 ($haystack) of type 
string is deprecated in 
/bitnami/wordpress/wp-content/plugins/woocommerce/includes/wc-page-functions.php 
on line 139PHP message: PHP Deprecated: strstr(): Passing null to parameter #1 
($haystack) of type string is deprecated in 
/bitnami/wordpress/wp-content/plugins/woocommerc
```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

### bndiagnostic was not useful. Could you please tell us why?

We are unable to connect to the server on WinSCP/VSCode

### Describe your issue as much as you can

We are unable to connect to this server, keeps on saying that the authentication failed.

**Comment by gongomgra** [comment]
Hi @hichotu,

Thanks for using Bitnami. I understand you were able to SSH connect to the server somehow in order to run the bndiagnostic tool, is that correct? In that case, I understand the issue is in the WinSCP/VSCode side, not sure if in the private SSH key format.
