### ISSUE TITLE
Bitnami - Azure VM - SSL certificate genrate behind load balancer and Azure Front door

### ISSUE THREAD

**Issue by kadiachirag** [bitnami/vms#1032]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

60e1e616-41f2-89d4-d6b1-672e2aab6961

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Php: Found possible issues
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
    ✓ Mysql: No issues found

[Php]

The following error appears in the
/opt/bitnami/php/var/log/php-fpm.log:
```
[10-Jul-2023 05:42:10] WARNING: [pool www] server reached max_children setting
(5), consider raising it

```
This error usually indicates PHP script execution is slow due to busy server

### bndiagnostic was not useful. Could you please tell us why?

the suggested guide not relevent to my issue

### Describe your issue as much as you can

Hi Bitnami Support Team,

I am trying Azure VM to generate an SSL certificate for secure traffic. VM is in a private network and behind Azure Front Door.

Below is Scenario trying to achieve 
Azure Bitnami VM  >> Load balancer >> Private Link Service >> Azure Front Door. 

Problem - SSL traffic (443) not offloading to VM, require SSL certificate and following lets encrypt link and would like to know which are additional parameters require for Step 2

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by kadiachirag** [comment]
Further more - Getting below response: 


root@xxxxx-Website:/opt/bitnami/letsencrypt# sudo /opt/bitnami/letsencrypt/lego --tls --email="ops@xyz123.com.au" --domains="www.xyx123.com.au" --path="/opt/bitnami/letsencrypt" run
2023/07/11 02:12:10 [INFO] [www.xyx123.com.au] acme: Obtaining bundled SAN certificate
2023/07/11 02:12:11 [INFO] [www.xyx123.com.au] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/244513333437
2023/07/11 02:12:11 [INFO] [www.xyx123.com.au] acme: use tls-alpn-01 solver
2023/07/11 02:12:11 [INFO] [www.xyx123.com.au] acme: Trying to solve TLS-ALPN-01
2023/07/11 02:12:18 http: TLS handshake error from 168.63.129.16:60887: EOF
2023/07/11 02:12:18 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/244513333437
2023/07/11 02:12:18 Could not obtain certificates:
        error: one or more domains had a problem:
[www-uat.hatchmaternity.com.au] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge

**Comment by gongomgra** [comment]
Hi @kadiachirag,

Thanks for using Bitnami. I'm afraid that's a very specific question regarding the lego tool itself. We recommend you to open the question in the official lego forums

https://github.com/go-acme/lego/discussions
