### ISSUE TITLE
[<LAMP Stack>] <Download .run file for linux server>

### ISSUE THREAD

**Issue by dippreneurlab** [bitnami/vms#1033]
### Describe your issue as much as you can

I need to download LAMP stack for a linux server. It is easy to install it with a .run file. But only two format provided - .ova format or cloud. So, where i should find it?

**Comment by gongomgra** [comment]
Hi @dippreneurlab,

Thanks for your interest in using Bitnami. Unfortunately, we dropped support for local installers some months ago. We recommend you to use our containers/helm charts or the local virtual-machine solutions.

You can find more information about the local installers support drop in the next link

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html
