### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by miarosemathews** [bitnami/vms#1036]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5490b9f6-de06-3483-79ec-7078fdd597e8

### bndiagnostic was not useful. Could you please tell us why?

did not tell me how to fix

### Describe your issue as much as you can

Sometimes when I load the domain quotientlabs.me it results in a server error and in the diagnostics tool the server is not reading the hostname as the ip address or domain name.

**Comment by mdhont** [comment]
Could you describe the issue in more detail? Also did you make any changes to the application or is it a fresh instance.
