### ISSUE TITLE
[wordpress-nginx] How to permanently disable the mariadb service 

### ISSUE THREAD

**Issue by minasgadalla** [bitnami/vms#1038]
### Describe your issue as much as you can

I'm currently running a Bitnami WordPress with NGINX and SSL stack on an Amazon EC2 instance. This instance has MariaDB running as one of the services, but I want to disable because I am using an AWS RDS and the mariadb consumes approx 7GB of ram (virtual).

I have been able to stop the MariaDB service using the `ctlscript.sh` command like this:
`sudo /opt/bitnami/ctlscript.sh stop mariadb`

However, I'm looking for a way to **permanently** disable MariaDB from starting, even after server reboots.

I checked the Bitnami startup script located at `/etc/init.d/bitnami`. This script uses a binary named 'provisioner' which seems to be responsible for starting the services, but since it's a binary, I cannot directly edit it to disable MariaDB. Checking online some guides instructed to mv ` /opt/bitnami/mariadb/scripts/ctl.sh`, but this file doesn't exist..

First of all, is it safe to disable the mariadb service? or is it used by bitnami for internal checks, logs etc?

If it ok, I would appreciate any guidance on how to disable MariaDB from starting up automatically without affecting the startup of the other services.

**Comment by mdhont** [comment]
Bitnami uses Gonit to manage services. You can disable the service as follows:

    sudo mv /etc/monit/conf.d/mariadb.conf /etc/monit/conf.d/mariadb.conf.disabled
    sudo gonit reload

**Comment by minasgadalla** [comment]
Thanks, that worked!

On the `/etc/monit/conf.d/` path there was already a `mariadb.conf.disabled` file, so I changed it to `mariadb.conf.disabled2`
