### ISSUE TITLE
[<LAMP>] Website showing different on www and non www

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1039]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0f166ede-f1bb-1338-6f3a-6a40dab9aa49

### bndiagnostic output

```
===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.

 total used free shared buff/cache available Mem: 453 263 27 0 162 177 Swap: 634 
96 538

You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.

[Sun Jul 09 22:43:37.750270 2023] [authz_core:error] [pid 57769:tid 
140353155823360] [client **ip_address**:51126] AH01630: client denied by server 
configuration: /opt/bitnami/apache/htdocs/.htaccessOLD2
 [Sun Jul 09 22:43:38.121938 2023] [authz_core:error] [pid 57769:tid 
140353139037952] [client **ip_address**:51138] AH01630: client denied by server 
configuration: /opt/bitnami/apache/htdocs/.htaccess~
 [Tue Jul 11 02:20:06.752890 2023] [core:error] [pid 66495:tid 140354355422976] 
[client **ip_address**:36572] AH10244: invalid URI path 
(/../../mnt/mtd/Config/Account2)

Please check the following guide to troubleshoot server issues:
Press [Enter] to continue:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====
```

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

Hi,

When I hit my website [without www](https://digitaldwarfs.com/) it shows the dummy test page. When I hit it [with www](https://www.digitaldwarfs.com/) it shows the default bitnami page.

Can you please advise.

Huzan

**Comment by gongomgra** [comment]
Hi @huzanf,

Thanks for using Bitnami. First of all, we recommend you to create a server backup that you can easily restore, or test the changes in a different new server and apply the required changes in your production server only when you are sure it will work.

If you are adding a custom application on top of Apache, we highly recommend you to follow our guide at https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

I also see you have the HTTP to HTTPS and non-www to www redirections in place in your Apache config, and I think this may be causing issues, although I can't understand why it is redirecting you to different htdocs folders.

```
  # BEGIN: Enable HTTP to HTTPS redirection
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
  # END: Enable HTTP to HTTPS redirection
  # BEGIN: Enable non-www to www redirection
  RewriteCond %{HTTP_HOST} !^www\. [NC]
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=permanent,L]
  # END: Enable non-www to www redirection
```

We recommend you to remove this custom configuration and then follow the "add custom PHP application" approach.

**Comment by huzanf** [comment]
Hi @gongomgra 

Could you please let me know how I can do this:
`We recommend you to remove this custom configuration`

**Comment by huzanf** [comment]
Hi @gongomgra 

Kindly support.

**Comment by huzanf** [comment]
> If you are adding a custom application on top of Apache, we highly recommend you to follow our guide at https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

I followed these steps, but my website is not showing.
http://app.digitaldwarfs.com/

Kindly support @gongomgra

**Comment by huzanf** [comment]
> If you are adding a custom application on top of Apache, we highly recommend you to follow our guide at https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

Hi @gongomgra 
I followed the steps. I changed the SSL certificate key to what it was earlier. The website doesn't get redirected from non-www to www automatically. Although I had made that transfer as yes while setting up the SSL

**Comment by gongomgra** [comment]
Hi @huzanf,

You need to open the file with a text editor in a SSH session (for example `nano`), remove the mentioned lines, save your changes and restart Apache for changes to take effect. Regarding the custom app, I visited your website and it shows a "test page" message. I understand that's the expected output.

![Screenshot 2023-07-17 at 17 33 58](https://github.com/bitnami/vms/assets/6660452/f654735c-c2d8-46ae-a09d-96e7dd3e736d)
