### ISSUE TITLE
[redmine] <Where can I get a previous version of Redmine>

### ISSUE THREAD

**Issue by kkawa16** [bitnami/vms#104]
### Describe your issue as much as you can

Hi, experts.

I'm looking for previous version of bitnami redmine for windows.
I'd like to use redmine 4.x for testing GitLab plugin that is not supported latest version of redmine.

Does anyone have a bitnami redmine 4.2.3-x ?

Thanks in advance.

**Comment by jotamartos** [comment]
Here you are! :) 

https://downloads.bitnami.com/files/stacks/redmine/4.2.3-4/bitnami-redmine-4.2.3-4-windows-x64-installer.exe

**Comment by kkawa16** [comment]
Thank you for your support !
