### ISSUE TITLE
Addition of Popular Webservers Category ( Virtual Machines ) For Serving Static Webpages on Cloud, Internet & Intranet Servers

### ISSUE THREAD

**Issue by linuxguist** [bitnami/vms#1040]
### Describe your suggestion as much as you can

Hi Bitnami Support Team,

1. is there a possibility of introducing a Pure Webserver Based Virtual Machines, for hosting static webpages only ?

For eg. a VM Containing any of these popular webservers:

    Apache HTTP Server
    NGINX
    Tiny Web Server
    KSWEB
    lighttpd
    Microsoft IIS
    Caddy
    Node. js.

2. On this Bitnami Webpage : https://bitnami.com/stacks/virtual-machine

     The "Search applications" textbox can be more appropriately renamed to "Search Categories" and the
     placeholder hint can be improved to say: CMS, e-Commerce, Blog, Wiki, Database etc.

This will enhance the scope of your current offering and people will come to know about your extensive work on various categories.

Thanks and Best Regards,

Nathan S.R.

**Comment by gongomgra** [comment]
Hi @linuxguist,

Thanks for your suggestion! We have some of them (those we currently offer) included under the "Developer Tools" category

https://bitnami.com/stacks/developer-tools

Hope it helps!

**Comment by linuxguist** [comment]
Yes @gongomgra thanks for the extensive list. Really helpful. Will now close this issue as resolved.
