### ISSUE TITLE
Bitnami Service: Failed to start LSB: bitnami init script

### ISSUE THREAD

**Issue by andresmurtello** [bitnami/vms#1041]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

not sure

### bndiagnostic output

Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ? Php: Found possible issues

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Jul 12 22:06:28.350764 2023] [proxy_fcgi:error] [pid 30033:tid
139945998018304] (70007)The timeout specified has expired: [client
**ip_address**:23362] AH01075: Error dispatching request to : (polling)
 [Wed Jul 12 22:10:43.399417 2023] [proxy_fcgi:error] [pid 29626:tid
139946417358592] (70007)The timeout specified has expired: [client
Press [Enter] to continue:
**ip_address**:35226] AH01075: Error dispatching request to : (polling)
 [Wed Jul 12 22:10:43.399433 2023] [proxy_fcgi:error] [pid 29627:tid
139946811717376] (70007)The timeout specified has expired: [client
**ip_address**:39098] AH01075: Error dispatching request to : (polling),
referer: http://34.192.208.199:80/admin/login.asp

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-07-13 16:12:20 0 [ERROR] Aborting

```
Please check the following guide to troubleshoot MariaDB issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Php]

The following error appears in the /opt/bitnami/php/logs/php-fpm.log:
```
[11-Jul-2023 16:18:38] ERROR: fork() failed: Cannot allocate memory (12)

```
This error  indicates there is a problem with the memory limit in PHP. Please
check the following guide to increase the number of PHP-FPM child processes:

https://docs.bitnami.com/general/apps/akeneo/administration/increase-memor
y-limit/

===== End of bndiagnostic tool output =====
Press [Enter] to continue:

Press [Enter] to continue:   

### bndiagnostic was not useful. Could you please tell us why?

yes it was

### Describe your issue as much as you can

Job for bitnami.service failed because the control process exited with error code.

Cant' restart my instance.

**Comment by gongomgra** [comment]
Hi @andresmurtello,

Thanks for using Bitnami. According to the error messages that you shared, your server is running out of free memory, which prevents Bitnami services to start. You will have to update your instance type to a bigger one for services to be run

```
[11-Jul-2023 16:18:38] ERROR: fork() failed: Cannot allocate memory (12)
```

**Comment by andresmurtello** [comment]
Thank you @gongomgra!
