### ISSUE TITLE
Magento  2.4.6-28 Cannot install sample data using AWS Lightsail Bitnami Image<title>

### ISSUE THREAD

**Issue by johnoa** [bitnami/vms#1042]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

na

### bndiagnostic output

na

### bndiagnostic was not useful. Could you please tell us why?

Believe this is not relevant for this issue.

### Describe your issue as much as you can

After vanilla installation of Bitnami Magento  2.4.6-28 image under AWS Lightsail it is not possible to install the sample data.

**Steps to reproduce.**

1.  Create new lightsail instance of Bitnami Magento  2.4.6-28.  Following the standard installation steps.  
2. Connect to instance
3.  `sudo su`
4. `bin/magento-cli deploy:mode:set developer`(Set developer as required)
5.  `bin/magento-cli sampledata:deploy`

**Error message received from composer:**

_In PluginManager.php(274) : eval()'d code line 188:
                                    
  chmod(): Operation not permitted  

Note: This is from a vanilla installation._

**Comment by johnoa** [comment]
It would appear that this is an issue with default permissions, standard user and group ownership are: bitnami:daemon.  The magento-cli command runs commands as daemon user.  If you change the permissions of the root magento dir:

 chown -R daemon:daemon <INSTALL_DIR> 

the sample data is installed correctly.

**Comment by gongomgra** [comment]
Hi @johnoa,

Thanks for using Bitnami and for reporting this issue. Can you confirm if your are running `sudo su daemon` in your command for step 2 or simply `sudo su` to become root? Do you also know if it is required to update permissions for the whole `/opt/bitnami/magento` installation or if it is enough to update some folders? Updating the whole `/opt/bitnami/magento` installdir may end up causing other usability issues. Do you happen to know if `daemon:bitnami` instead of `bitnami:daemon` for filesystem ownership would suffice? This way we will still provide the end users with enough usability to operate Magento installation as the `bitnami` user.

**Comment by johnoa** [comment]
HiWe ran “sudo su”Not sure if it’s required to update all the permissions on all folders. That would require investigation. After installing the sample data successfully we reverted ownership to bitnami:daemon (all files and directories). Not sure of the consequences of having ownership set to daemon:bitnami. Hope this helps in resolution of this issueOn 18 Jul 2023, at 08:17, Gonzalo Gómez Gracia ***@***.***> wrote:﻿
Hi @johnoa,
Thanks for using Bitnami and for reporting this issue. Can you confirm if your are running sudo su daemon in your command for step 2 or simply sudo su to become root? Do you also know if it is required to update permissions for the whole /opt/bitnami/magento installation or if it is enough to update some folders? Updating the whole /opt/bitnami/magento installdir may end up causing other usability issues. Do you happen to know if daemon:bitnami instead of bitnami:daemon for filesystem ownership would suffice? This way we will still provide the end users with enough usability to operate Magento installation as the bitnami user.

**Comment by gongomgra** [comment]
Hi @johnoa,

Thanks for your message and for sharing your solution with us!
