### ISSUE TITLE
Lightsail Bitnami Wordpress Site goes down after front end changes

### ISSUE THREAD

**Issue by Tidal-IT** [bitnami/vms#1045]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

 ccd5aaa5-a63f-985b-21fa-c82185483a1a

### bndiagnostic output

Hello,

My website goes down whenever there are some changes in the front end. I have to run /opt/bitnami/ctlscript.sh restart
to bring it back.  Below are the errors I see after running the diagnostic tool. 

Found recent error or warning messages in the Apache error log.
```
[Fri Jul 14 16:40:17.915063 2023] [proxy_fcgi:error] [pid 213184:tid
14224] [client **ip_address**:61920] AH01079: failed to make
connection to backend: httpd-UDS, referer:
https://*****f.com/?fl_builder&fl_builder_ui_iframe
 [Fri Jul 14 16:40:17.961 2023] [proxy:error] [pid 213184:tid
14007744] (2)No such file or directory: AH02454: FCGI: attempt to connect
to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Fri Jul 14 16:40:17.956093 2023] [proxy_fcgi:error] [pid 213184:tid
140028537087744] [client **ip_address**:61921] AH01079: failed to make
connection to backend: httpd-UDS, referer:
https://*****f.com/?fl_builder&fl_builder_ui_iframe
```

![problem](https://github.com/bitnami/vms/assets/138704452/57d6dca6-bbc3-49ff-9709-0ddbe5ae5092)

### bndiagnostic was not useful. Could you please tell us why?

somewhat

### Describe your issue as much as you can

Website goes down when front end changes are made. I need help solving the issue. 
Thank you in advance,

**Comment by Tidal-IT** [comment]
It went down again, so I ran the diagnostic tool again while it was down. Here's the code if that helps: a89f562a-e5df-a3dd-cbad-16a59f1fc118

It has the same problem

[Fri Jul 14 18:59:37.687021 2023] [proxy_fcgi:error] [pid 216722:tid
139960703252224] (104)Connection reset by peer: [client **ip_address**:64392]
AH01075: Error dispatching request to : , referer:
https://***f.com/?fl_builder&fl_builder_ui_iframe
 [Fri Jul 14 18:59:38.842025 2023] [proxy:error] [pid 215671:tid
139961911211776] (2)No such file or directory: AH02454: FCGI: attempt to connect
to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Fri Jul 14 18:59:38.842120 2023] [proxy_fcgi:error] [pid 215671:tid
139961911211776] [client **ip_address**:64401] AH01079: failed to make
connection to backend: httpd-UDS, referer:
https://****f.com/?fl_builder&fl_builder_ui_iframe
Press [Enter] to continue:

**Comment by gongomgra** [comment]
Hi @Tidal-IT,

Thanks for using Bitnami. According to your error messages, the issue seems to be more related to your plugins or custom themes than with Bitnami installation. We recommend you to open a new question in the official WordPress forums

https://wordpress.org/support/forums/
