### ISSUE TITLE
SSL Certification update on Bitnami

### ISSUE THREAD

**Issue by erygzn35** [bitnami/vms#1046]
### Describe your issue as much as you can

Hi Everyone,

We are publishing our company website from AWS Lightsail Instance with wordpress on bitnami service. Now we are using OpenSSL like Server Type: Apache/2.4.48 (Unix) OpenSSL/1.1.1n. We are generating a new SSL certificate for every 90days but finally purchased 5years esential wildcard SSL certificate from a hosting company.

Now our main problem is I do not have enough knowledge how to replace open SSL certification with a purchased wildcard? I found lots of tutorials on internet and they confused me a lot because I have no experience before with bitnami and SSL certification.

If anyone guide me or share a tutorial with me I would be glad.

Regards

**Comment by gongomgra** [comment]
Hi @erygzn35,

Thanks for using Bitnami. You can check our guide for this in the next link

https://docs.bitnami.com/virtual-machine/apps/wordpress/administration/enable-https-ssl-apache/

Hope it helps!
