### ISSUE TITLE
how to windows download, rather than a virtual machine? 

### ISSUE THREAD

**Issue by cr333d** [bitnami/vms#1047]
### Describe your issue as much as you can

I am  unable  to  access  wordpress  files(wpconfig).It was so easy to  use  windows version rather  than  virtual machine for  non coders.

**Comment by cr333d** [comment]
Atleast make a tutorial how to access wordpress files from virtual machine from non coders.In windows version it was easy for newbie to access.

**Comment by gongomgra** [comment]
Hi @cr333d,

Thanks for using Bitnami. Our virtual-machines are based on Linux. You can get more information on how to get access to the filesystem in the next guide

https://docs.bitnami.com/virtual-machine/faq/get-started/find-credentials/

You can also get more information on the general directory structure by checking the guide linked below

https://docs.bitnami.com/virtual-machine/faq/get-started/understand-directory-structure/

Hope it helps!
