### ISSUE TITLE
Akeneo - Cannot see image in wysiwyg editor from any other domain then Akeneo installation

### ISSUE THREAD

**Issue by PrologimaOwner** [bitnami/vms#1049]
### Describe your issue as much as you can

Hi everybody, I am the beginner in the Linux world and Akeneo application too. I am pretty excited how it works, but I could not find a way how to display image in the HTML (wysiwyg) field in Akeneo when the image comes from any other domain than the one where Akeneo application is installed.

To be more specific - Akeneo is installed on pim.mydomain.com and picture like https://pim.mydomain.com/media/show/4%252F1%252F7%252Fe%252F417ea2f60db0915945743339f6ecc66595ba8d18_file.jpeg/thumbnail is working without any problem, But for example this one not: https://lexibook.s5.cdn-upgates.com/z/z648203245ab33-lxbbg040pa-1.jpg

![akeneo_wysiwyg_no_image](https://github.com/bitnami/vms/assets/107675529/c288ebf8-de85-4bb9-952d-3e18fef467b0)

I suppose I have to enable using "foreign" domains or something like that. Please could anybody help me and give me exact advice how to do it?

Thank you very much.

**Comment by gongomgra** [comment]
Hi @PrologimaOwner,

Thanks for using Bitnami. That seems to be a question for the official Akeneo developers. Could you open your question in the official Akeneo forums?

https://www.akeneo.com/support-help-center/
