### ISSUE TITLE
LAMP website working on mobile data but not over WIFI

### ISSUE THREAD

**Issue by vasundharaDC** [bitnami/vms#105]
### Describe your issue as much as you can

Hi,
I recently faced an issue with my website. I am getting " Copyright 2021 Privacy Policy"  on my login page when I connect with the WIFI but I am getting my login page with mobile data.
WEBSITE: eschoolexpert.com
![image](https://user-images.githubusercontent.com/68239548/178420855-bafbd181-b6ab-449e-8209-0bafc9aacc27.png)
![image](https://user-images.githubusercontent.com/68239548/178420983-d3b67bc0-33fc-437a-9022-a9a5a30fe90b.png)

**Comment by mdhont** [comment]
Seems like it's an issue with the domain, it probably expired. I recommend contacting your DNS provider.

**Comment by vasundharaDC** [comment]
Thanks a ton.
