### ISSUE TITLE
[WordPress] Server response time is higher after system update in Lightsail

### ISSUE THREAD

**Issue by luka725** [bitnami/vms#1050]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d8244e1d-e63d-3c2e-e238-e86911e75316

### bndiagnostic was not useful. Could you please tell us why?

It was useful, Thanks!

### Describe your issue as much as you can

Hello, 
After some software updates relativity to WordPress, server response time is increased to 25s and more,
when shutting down elementor plugin, the server is normally functioning, 
I don't understand what is the issue but need to check.
please help me to debug the server to understand what is the issue.
Thanks and kind regards

**Comment by jotamartos** [comment]
>when shutting down elementor plugin, the server is normally functioning,

That's a performance issue of the application with a specific plugin. I suggest you contact the plugin's developers to know more about this. You can also contact the WordPress' support team to know more about how to debug the issue.

Thanks
