### ISSUE TITLE
[Magento] Cannot login to Admin panel with default 'user'

### ISSUE THREAD

**Issue by lfzamora81** [bitnami/vms#1053]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5a59a295-c0af-5be4-b365-dcf33f7de34b

### bndiagnostic output

? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Apache: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

there is plenty of memory (8GB) on fresh boot as well as public access to ports 22, 80, and 443

### Describe your issue as much as you can

 Latest Version: 2.4.6-33-r52 on Debian 11 

When attempting to login to the admin panel for the first time, using default credentials provided, the screen simply refreshes without any output or indication of an error but also, the login does not work with the text boxes emptying on the refresh.

Occasionally it is possible to get a generic "wrong credentials" or "incorrect captcha" red error text box but there does not appear to be any rhyme or reason other than different amounts of time have passed.

Tried using both http and https variants of the URL. The IP being used is simply the Elastic IP attached to the box. Based on some other 'similar' posts about cookies and caching I am thinking this may be the root issue somehow. Maybe as the instance is booting up it cannot find out its "proper" domain or base URL because of the Elastic IP?

Tried on Firefox and Chrome, same results.

Can ssh into the box with no trouble. Have tried "unlocking" the 'user' user but that does not seem to be the issue.

**Comment by lfzamora81** [comment]
On a hunch, went seeking the base URL setting but it appears to be kosher under the current circumstances:

`catalog/search/engine - elasticsearch7
catalog/search/elasticsearch7_server_hostname - 127.0.0.1
catalog/search/elasticsearch7_server_port - 9200
catalog/search/elasticsearch7_enable_auth - 0
catalog/search/elasticsearch7_username -
catalog/search/elasticsearch7_password -
catalog/category/root_id - 2
general/region/display_all - 1
general/region/state_required - AL,AR,AU,BG,BO,BR,BY,CA,CH,CL,CN,CO,CZ,DK,EC,EE,ES,GR,GY,HR,IN,IS,IT,LT,LV,MX,PE,PL,PT,PY,RO,SE,SR,US,UY,VE
analytics/subscription/enabled - 1
crontab/default/jobs/analytics_collect_data/schedule/cron_expr - 00 02 * * *
msp_securitysuite_recaptcha/frontend/enabled - 0
msp_securitysuite_recaptcha/backend/enabled - 0
twofactorauth/duo/application_key - Kxb04krwOHvpcQbd0yplzy72S7LXV0JWerusmkwALGumoYIwvJeKnjqiD9JW6OQL
web/secure/use_in_frontend - 0
web/secure/use_in_adminhtml - 0
web/secure/base_url - https://3.23.187.102/
web/unsecure/base_url - http://3.23.187.102/
web/seo/use_rewrites - 1
system/full_page_cache/caching_application - 2
system/full_page_cache/varnish/backend_host - localhost
system/full_page_cache/varnish/backend_port - 81`

**Comment by jotamartos** [comment]
Hi @lfzamora81,

I just launched a fresh Bitnami Magento instance and confirmed that it works properly. I could access the admin dashboard using different browsers (Firefox and Brave)

![Screenshot 2023-07-24 at 09 31 08](https://github.com/bitnami/vms/assets/8791635/74e48186-3be6-4d1f-bd8c-e9a1bd69df44)

Please review the official documentation of the application to know more about the supported browsers and their configuration to access the application. You can also contact the Magento's support team to know more about the issue you are running into.

**Comment by lfzamora81** [comment]
You are correct. I re-downloaded and initialized the image again and now it works. I have no idea what was wrong or what I did different on the other image but redeploying it (from fresh AMI) fixed it.

**Comment by bconner22** [comment]
I'm getting the same issue with [ami-0a2a990a7d9a28be9] on the recommended t3a.medium.  I got to the page with <MY_IP>/admin and logged in successfully with 'user' and the password from the EC2 system log.  I then get to this page(attached), and the credentials do not work here.  The page simply refreshes after I put in the user/pass, like OP mentioned.  This is on Safari and Chrome.
I can also ssh in just fine.
<img width="1437" alt="image" src="https://github.com/bitnami/vms/assets/10758527/038ca91b-02b1-433a-93b2-c2a9a4aee897">

**Comment by jotamartos** [comment]
>I got to the page with <MY_IP>/admin and logged in successfully with 'user' and the password from the EC2 system log

That means that you can access the admin page correctly. 

> I then get to this page(attached)

What's that page? As I just mentioned, you could log in to the admin panel of Magento (<MY_IP>/admin) so you have control over your app and can perform all changes you want.\

If you continue running into issues, please create a separate thread instead of reopening this old one.

**Comment by bconner22** [comment]
I logged into the admin page and it immediately redirected me to the page I posted.  I cannot get to the admin panel after I log in the first time.

**Comment by jotamartos** [comment]
I think that issue is related to the cookies of your browser. Please try using an incognito window or a different browser to see if the error persists. If that's the case, please contact the Magento's developers as we have not been able to reproduce the issue. 

Thanks
