### ISSUE TITLE
[Ghost] Job for bitnami.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by RepleteSS** [bitnami/vms#1055]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

580aef93-a22a-bd9d-9240-ca5f9c4e051f

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ✓ Mysql: No issues found
    ? Apache: Found possible issues

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1982 697 214 0 1070 1060 Swap:
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

You can also enable swap memory to improve performance.
Press [Enter] to continue:

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Jul 24 07:57:21.627477 2023] [proxy_http:error] [pid 9324:tid
140412681320192] [client **ip_address**:42014] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1

[Mon Jul 24 07:57:22.954388 2023] [proxy:error] [pid 9324:tid 140412664534784]
(111)Connection refused: AH00957: http: attempt to connect to
**ip_address**:2368 (127.0.0.1:2368) failed

Press [Enter] to continue:
[Mon Jul 24 07:57:22.954428 2023] [proxy_http:error] [pid 9324:tid
140412664534784] [client **ip_address**:41828] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

the suggested guides are not related to my issue

### Describe your issue as much as you can

I'm using Lighsail to host my ghost blog. But now bitnami is service is not running and the blog is giving a 503 error. Please help me to fix the issue. I have tried everything available on the internet but cannot fix it.

**Comment by gongomgra** [comment]
Hi @RepleteSS,

Thanks for using Bitnami. I see your server is running out of free memory, which can prevent Ghost server and other Bitnami services to run. We recommend you to increase the instance type

```
-----------------------------------
Display amount of free and used memory in the system
-----------------------------------
Running: free -m
In: /opt/bitnami

Output:

               total        used        free      shared  buff/cache   available
Mem:            1982         696         215           0        1070        1061
Swap:              0           0           0
```

Apart from that, notice similar performance issues have been reported for Lightsail instances due to the instances to be of burstable type. You can find more information in the issue linked below

https://github.com/bitnami/vms/issues/225
