### ISSUE TITLE
[Redmine] <Looking for Redmine 4.0 Stack or OVA>

### ISSUE THREAD

**Issue by testuserbit** [bitnami/vms#1057]
Is it possible to get a Redmine Installer or OVA for an older 4.0 version?

**Comment by jotamartos** [comment]
Hi @testuserbit,

Thank  you for your interest. As you know, we removed support for the Bitnami installers and most of the old releases several months ago. Redmine 4.0 is no longer in our records but you can still download Redmine 4.1 

https://downloads.bitnami.com/files/stacks/redmine/4.1.0-8/bitnami-redmine-4.1.0-8-linux-debian-9-x86_64.ova

**Comment by pravindodia** [comment]
Can we get ova for Redmine for debian version 4.0.3 stable

**Comment by jotamartos** [comment]
As I mentioned above, 4.0 is no longer in our records.

**Comment by pravindodia** [comment]
Ok Thanks for letting me know.

**Comment by jotamartos** [comment]
Yes, we have that one. Please use this link to download the OVA 

https://downloads.bitnami.com/files/stacks/redmine/4.2.5-7/bitnami-redmine-4.2.5-7-r01-linux-debian-10-x86_64-nami.ova

**Comment by pravindodia** [comment]
Thank you for the link
