### ISSUE TITLE
[LAMP] Need access to old OVA files

### ISSUE THREAD

**Issue by rogersantosferreira** [bitnami/vms#1058]
### Describe your issue as much as you can

Hello!
I have seen in several other tickets already solved some responses indicating download links for files from previous versions of OVAs.

I believe this is an important feature to make public on some list like: past archives. Would it be possible to have access to such a list?

I ask this because today I spent more than 5 hours looking for a LAMP 7.4 version and, even so, I didn't find the last release released for the 7.4 version of PHP. According to the changelog, it would be 7.4.33-10-r12.

It would be very helpful to have such a list, which usually appears in answers scattered around the internet pointing to something like: https://downloads.bitnami.com/files/stacks/lampstack/7.4.29-0/bitnami-lampstack-7.4.29-0-linux-debian-10-x86_64-nami.ova

Thanks in advance...

**Comment by jotamartos** [comment]
Here you are!

https://downloads.bitnami.com/files/stacks/lampstack/7.4.33-10/bitnami-lampstack-7.4.33-10-r12-linux-vm-debian-11-x86_64-nami.ova

I hope it helps!

**Comment by rogersantosferreira** [comment]
Thank you @jotamartos.
Just to quench my curiosity: is there a list or directory where we can search old versions of OVAs from bitnami machines or is this just for internal use by the support team?

Thanks again for your attention and promptness!

**Comment by jotamartos** [comment]
Old versions are not listed anywhere. You can try changing the version and see if the package is downloaded. However, many old versions were removed from the catalog when we removed support for the installers so that version might not be available. In that case, you can ask here to confirm if it's available or not.
