### ISSUE TITLE
[Odoo 15] Install apache and php along side Odoo server

### ISSUE THREAD

**Issue by mdfaisalpapa** [bitnami/vms#106]
I have installed Odoo 15 package by bitnami on AWS server. I have installed php also on the server. However unable to launch my php website as the port 80 is used by odoo15. Does odoo15 uses apache2 server? where is the htdocs folder located? Kindly guide where to locate my php based website.

**Comment by jotamartos** [comment]
The Bitnami Odoo solution comes with Apache but it does not include PHP, so you won't be able to deploy your PHP application there. If you want to deploy a PHP app, in the same server, you will need to install PHP using the system's packages and deploy a PHP server to serve your files and then connect Apache and that PHP server using the ProxyPass directives. Unfortunately, we do not have any guide to do so.
