### ISSUE TITLE
[AbanteCart] AWS default Admin login fails

### ISSUE THREAD

**Issue by Wink8008** [bitnami/vms#1060]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2accf5f7-4cf8-c2d7-cd9a-53660bf53201

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 975 420 69 21 484 383 Swap:
634 27 607
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

Press [Enter] to continue:
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Jul 24 12:44:59.234006 2023] [authz_core:error] [pid 1631:tid
140514535724800] [client **ip_address**:36944] AH01630: client denied by server
configuration: /opt/bitnami/abantecart/.htaccess
 [Mon Jul 24 12:44:59.246735 2023] [authz_core:error] [pid 2171:tid
140514871432960] [client **ip_address**:36970] AH01630: client denied by server
configuration: /opt/bitnami/abantecart/.htaccess.save
 [Mon Jul 24 16:59:01.270015 2023] [access_compat:error] [pid 2171:tid
140514955360000] [client **ip_address**:40168] AH01797: client denied by server
configuration: /opt/bitnami/abantecart/admin/config.php

```
Please check the following guide to troubleshoot server issues:
Press [Enter] to continue:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

didn't solve the problem

### Describe your issue as much as you can

Failure to login to the admin area of AbanteCart with the default username/password.
AbanteCart gives the error "No match for username and/or password"

On AWS Console i can see that inbound ports 22, 80 & 443 are open

**Comment by jotamartos** [comment]
>Failure to login to the admin area of AbanteCart with the default username/password.
>AbanteCart gives the error "No match for username and/or password"

Did you follow this guide to obtain the configured username and password to access the application?

https://docs.bitnami.com/aws/faq/get-started/find-credentials/

Thanks
