### ISSUE TITLE
[WordPress] Website is not loading on browser

### ISSUE THREAD

**Issue by Jimtrelos** [bitnami/vms#1063]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7513d23a-984-75cd-67bd-2121cf73c43c

### bndiagnostic was not useful. Could you please tell us why?

I cannot understand the guides

### Describe your issue as much as you can

well 2 days ago i was modifing my website and electricity was gone so my pc shut down abruptly. When i reopened it, i launched oracle vm virtualbox and then my wordpress website but the website is not loading at all on the browser...

**Comment by Jimtrelos** [comment]
so there are issues only in connectivity and/or in apache
![VirtualBox_bitnami-wordpress-6-6 2 2-r0-debian-11-amd64_27_07_2023_14_52_53](https://github.com/bitnami/vms/assets/140615722/7807b65a-fa81-407c-887a-2863e5522f1b)

**Comment by jotamartos** [comment]
It seems all services are up and running and the machine has enough RAM memory to work. Can you run this command from inside the VM?

```
curl -LI localhost
```

**Comment by Jimtrelos** [comment]
well i did... still not loading
it responded with this:

HTTP/1.1 200 ok
Date: Fro, 28 Jul 2023 14:19:48 GMT
Server: Apache
Link: <http://localhost/wp-json/>; rel="https://api.w.org/", <http://localhost/wp-json/wp/v2/pages/48>; rel="alternate"; type="application/json", <http://localhost/>; rel=shortlink
Content-Type: text/html; charset=UTF-8

**Comment by jotamartos** [comment]
Hi @Jimtrelos,

As you can see, Apache is working and it returned "200 ok", which means that there was not any error. If you are receiving errors, they probably exist in the WordPress' side. I suggest you disable the plugins/themes (you can rename the folders in the /opt/bitnami/wordpress directory) and check if you can access the app later. If that's not the case, please contact the WordPress' support team to know more about how to debug the issue and the options you have to solve it.
