### ISSUE TITLE
[<WordPress on AWS by Bitnami>] <How to Fix WordPress Media Library Not Showing Images?>

### ISSUE THREAD

**Issue by Jeep-ECMS** [bitnami/vms#1064]
### Describe your issue as much as you can

How can I fix the problem of WordPress Media Library Not Showing Images, I tried to deactivate all Plugins and tried to select many Themes, but still can't fix this.

**Comment by gongomgra** [comment]
Hi @Jeep-ECMS,

Thanks for using Bitnami. Can it be an issue with the WordPress hostname configured in the database for those files? We recommend you to create a server backup before modifying anything in the database and also to check this question with the WordPress developers in the official forums

https://wordpress.org/support/forums/

**Comment by Jeep-ECMS** [comment]
Thanks, the media is working itself, maybe WP have updated or somethings happen.
