### ISSUE TITLE
[<Dolibarr>] <Restore database and files>

### ISSUE THREAD

**Issue by pepelemoko37** [bitnami/vms#1066]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

https://docs.bitnami.com/general/apps/dolibarr/administration/upload-files/

### bndiagnostic output

https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh-keys/
https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh-password/
https://docs.bitnami.com/general/apps/dolibarr/administration/upload-files/

### bndiagnostic was not useful. Could you please tell us why?

I follow this tree tutorial but It's not working

### Describe your issue as much as you can

I try to restore my database and all my folder and files from my previous instance of Dolibarr install with XAMPP and backup.
Now I want to work with Bitnami and everything work but I cannot have acces of folders and files in the VirtualBox session. The file manager on Virtual box need credential for open session and for SFTP I need the SSH key but they are generate on the VM system and I dont have acces to it.

Do you have an idea for this kind of problem ?

Thank a lot

Guillaume

**Comment by gongomgra** [comment]
Hi @pepelemoko37,

Thanks for using Bitnami. I'm afraid I don't fully understand the issues you have. Can you please elaborate? If you followed the `enable-ssh-password` you should be able to SSH connect with your virtual machine from your host machine using the password you configured for the `bitnami` user. 

Apart from that, it looks like Dolibarr provides an export/import procedure for moving app data from one instance to another. You can check it in the link below

https://wiki.dolibarr.org/index.php?title=Mass_imports

Hope it helps!
