### ISSUE TITLE
[Redmine] How to get older version Redmine by Bitnami

### ISSUE THREAD

**Issue by german-moriello** [bitnami/vms#1068]
### Describe your issue as much as you can

Hi Bitnami team!
I'm trying to upgrade an old bitnami Redmine. We are currently on a 3.4.6 installation on Linux. Not really sure how to proceed.  
Are there any 3.x versions after this one? If there is, can you share the download link? If not, can you provide me with the recommended 4.x to start upgrading?
Thank you so much

**Comment by gongomgra** [comment]
Hi @german-moriello,

Thanks for using Bitnami. I'm afraid we no longer provide local installers anymore and we don't have the virtual-machine for such an old version either. The only asset for those Redmine versions are the containers, that can be found on DockerHub. Find below the link for version 3.4.6

https://hub.docker.com/r/bitnami/redmine/tags?page=1&name=3.4.6

Regarding the intermediate versions required for the upgrade and the upgrade steps, we highly recommend you to open a new question in the official Redmine forums, as upgrading between major versions may require additional steps like database schemas upgrades

https://www.redmine.org/projects/redmine/boards
