### ISSUE TITLE
[ELK] syslog forwarder

### ISSUE THREAD

**Issue by LHFGen** [bitnami/vms#1069]
### Describe your issue as much as you can

I recently configured a Bitnami syslog forwarder to forward McAfee logs to Microsoft Sentinel for analysis, successfully configuring TLS. Installed sentinel's syslog collector on Bitnami. May I ask whether this form can successfully achieve syslog log forwarding?

**Comment by jotamartos** [comment]
Hi @LHFGen,

Thank you for using Bitnami. This is a specific question about the application and how it works. We suggest you contact the app's support team to know more about it. Please note that we take the packages from the upstream website, so if the app supports that feature, you shouldn't run into any issue when configuring it. Please take a look at the official documentation too.

Thanks
