### ISSUE TITLE
LAMP: PHPMYADMIN Access on Mac

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#107]
### Describe your issue as much as you can

Hi,

I would like to know how can I connect to PHPMYADMIN on Mac using terminal?

**Comment by mdhont** [comment]
PHPMyAdmin is a browser application for managing the MySQL/MariaDB database. This guide shows how you can access the database directly:

https://docs.bitnami.com/aws/infrastructure/mysql/get-started/connect-mysql/
