### ISSUE TITLE
[CanvasLMS] Update Bitnami Canvas

### ISSUE THREAD

**Issue by wmublows** [bitnami/vms#1072]
### Describe your issue as much as you can

Hello. How do you update a Bitnami Canvas instance? Also, how do I run the sticky bit sudo chmod +t /tmp
 in AWS?

**Comment by jotamartos** [comment]
Hi @wmublows,

To update the app, you will need to launch a new server with the latest version and migrate your data from the current server to the new one. You will probably find more information regarding how to migrate the data in the official documentation.

Regarding the command you mention, you just need to access the console and run it. 

https://docs.bitnami.com/aws/faq/get-started/connect-ssh/
