### ISSUE TITLE
[AWS Lightsail LAMP] Web serving via IP vs. domains

### ISSUE THREAD

**Issue by MAiNPRoToCoL** [bitnami/vms#1073]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

02d81120-029a-f473-13f6-7f4813a62dc8

### bndiagnostic output

✓ Resources: No issues found
? Connectivity: Found possible issues
✓ Mariadb: No issues found
✓ Processes: No issues found
? Apache: Found possible issues
✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

apache syntax ok, but behavior strange

### Describe your issue as much as you can

my multiple hosts configurations in /opt/bitnami/apache/conf/vhosts functions as expected

but i lost the bitnami default page via IP and via other not apache configured domains names and im shown a virtual host page instead

im not sure if its expected behavior but I'd like not configured virtual hosts domains and direct ip to display from /opt/bitnami/apache/htdocs/index.html

thanks very much.

**Comment by mdhont** [comment]
> shown a virtual host page instead

Could you give more details? What do you mean with virtual host page?

**Comment by MAiNPRoToCoL** [comment]
A virtual host's webpage, sorry.

I have 3 configured and working virtual hosts websites. and strangely, the lowest named configuration file name is accessible via IP and and other not configured domain names instead of the default bitnami page in /opt/bitnami/apache/htdocs/index.html

**Comment by mdhont** [comment]
The following guide might be of help:

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

**Comment by MAiNPRoToCoL** [comment]
I've done so and followed it to the letter. it works. but what bitnami voodoo has apache displaying a vhosts website instead of the default bitnami page in /opt/bitnami/apache/htdocs when accessing the server via IP and other not apache configured domain names

**Comment by MAiNPRoToCoL** [comment]
?

**Comment by MAiNPRoToCoL** [comment]
the answer is in /opt/bitnami/apache/conf/httpd.conf folks

specifically the lines
IncludeOptional "/opt/bitnami/apache/conf/vhosts/*.conf"
Include "/opt/bitnami/apache/conf/bitnami/bitnami.conf"

depending on how you order them depends which page gets priority or not even served
