### ISSUE TITLE
[WordPress Multisite] WP Mail SMTP Plugin Settings just shows option to upgrade to Pro

### ISSUE THREAD

**Issue by geoff-bradford** [bitnami/vms#1075]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5a5ffc97-56a1-8910-2cc0-a4cb8d5552b5

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Not related to my issue

### Describe your issue as much as you can

Hi, sorry if this is the wrong place to post this!  I have a newly created instance of AWS Bitnami Wordpress Multisite.  Trying to get SNMP outgoing mail working.  There are instructions here for SMTP but not for multisite: https://docs.bitnami.com/aws/apps/wordpress/configuration/configure-smtp/

I see there are mail settings in the network parameters for the individual sites.  But in the plugin settings I only see the option to upgrade to pro for $49 a year.  Attaching a screenshot.  I just want to get warnings etc, not use email in the sites.  

There is wordpress multisite configuration here but nothing about SMTP.  https://docs.bitnami.com/aws/apps/wordpress-multisite/configuration/configure-wordpress-multisite/

![WP-Mail-SMTP-Settings](https://github.com/bitnami/vms/assets/141175634/743a1db8-33c2-4fd5-8862-da2af830a25a)

Thanks
Geoff

**Comment by jotamartos** [comment]
I just launched a fresh Bitnami WordPress Multisite instance and could activate the plugin without problems. As the plugin states, you need to configure it network-wide (in the network admin dashboard), not in a specific site. If you have more questions related to the plugin, please contact the plugin's developers.

![Screenshot 2023-08-03 at 11 36 21](https://github.com/bitnami/vms/assets/8791635/f2541b3a-920e-44d2-8344-f751c6dd338c)

**Comment by weeix** [comment]
> As the plugin states, you need to configure it network-wide (in the network admin dashboard), not in a specific site.
> 
> ![Screenshot 2023-08-03 at 11 36 21](https://user-images.githubusercontent.com/8791635/258069776-f2541b3a-920e-44d2-8344-f751c6dd338c.png)

@jotamartos Based on the screenshot you've shared, it appears that you're configuring settings for a specific site, correct? Please note that the Network Admin dashboard typically doesn't include menus such as Posts, Media, Pages, and so on.

In conclusion, individuals who utilize Wordpress Multisite have two options:

1. They can manually configure SMTP on each site.
2. They can opt to purchase WP Mail SMTP Pro.

Does that sound accurate?

**Comment by jotamartos** [comment]
Correct @geoff-bradford, I probably wrote the message incorrectly. The key point here is that the plugin has a free layer that allows you perform certain operations, if you need more options, you will need to go to the pro version. The developers of the plugin can provide more information about the differences between the free and paid versions.
