### ISSUE TITLE
[WordPress] bad performance when uploading files several users at same time 

### ISSUE THREAD

**Issue by xavier-alsina** [bitnami/vms#1077]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c8639615-dd05-2845-b095-e09be1670813

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Thu Aug 03 13:46:50.319937 2023] [proxy_fcgi:error] [pid 2098:tid 
140298395055872] [client **ip_address**:51910] AH01071: Got error 'PHP message: 
PHP Notice: PHP Request Startup: file created in the system's temporary 
directory in Unknown on line 0', referer: https://
 [Thu Aug 03 13:46:51.337943 2023] [proxy_fcgi:error] [pid 2170:tid 
140298722207488] [client **ip_address**:51916] AH01071: Got error 'PHP message: 
PHP Notice: PHP Request Startup: file created in the system's temporary 
directory in Unknown on line 0', referer: https://
 [Thu Aug 03 13:46:51.581295 2023] [proxy_fcgi:error] [pid 2157:tid 
140298841573120] [client **ip_address**:51908] AH01071: Got error 'PHP message: 
PHP Notice: PHP Request Startup: file created in the system's temporary 
directory in Unknown on line 0', referer: https://

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====
Press [Enter] to continue:

                                    
Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the fol
lowing code:

### bndiagnostic was not useful. Could you please tell us why?

1) ports are open, 2) no clue re performance

### Describe your issue as much as you can

Checking performance of my instance I see when there is concurrency of users uploading files at same time it takes a lot of time. Trying to debug I started today with a clean installation in lightsail as it comes from bitnami. Instance: 16 GB RAM, 4 vCPUs, 320 GB SSD. Wordpress 6.2.2-21 from bitnami.

The preformance for 1 user is as follows (for file of 1M, 5M and 10M): (Using jmeter and users hiting upload at same time, time in ms)

![image](https://github.com/bitnami/vms/assets/79367201/1c8e2aab-53df-4362-9619-947b05027458)

so far, so good. But when I try the test for 25 users it worsens a lot:

![image](https://github.com/bitnami/vms/assets/79367201/f85ba879-2c03-4a3d-ac4c-ed0cb31284d6)

(don't worry for the error %, that is because no plugin installed to manage the upload and returining 400 code, but in my developing instance returns 200 but same performance).

regarding this error all ports are open:
![image](https://github.com/bitnami/vms/assets/79367201/e6ea46cb-9228-4faa-8079-3a35177f8b61)
ports in lighstail:

![image](https://github.com/bitnami/vms/assets/79367201/ebe1ddc4-2bd9-4bcd-82c5-fb3413a6ccc5)

Re the [proxy_fcgi:error] I don't know if this is related ti uploading performance.

My question is: is this the expected performance for a <b>clean</b> isntallation? any option to improve performance for a site intensive in uploads?

thanks

**Comment by jotamartos** [comment]
I can see there are many messages like this one in the error_log file of Apache 

```
[Thu Aug 03 14:11:50.352013 2023] [proxy_fcgi:error] [pid 2185:tid 140298411677440] [client 83.40.57.173:53079] AH01071: Got error 'PHP message: PHP Notice:  PHP Request Startup: file created in the system's temporary directory in        Unknown on line 0', referer: https://DOMAIN.com/datos-propietario/
```

As you may know, this can slow down the server. You can read about it [here](https://medium.com/@yourthemeshop/how-to-turn-off-php-errors-in-wordpress-cd0204a8cc25). In order to remove those logging lines, you can edit the error_reporting parameter in the /opt/bitnami/php/etc/php.ini file. 

Apart from that, I also suggest you contact the WordPress' support team to know why PHP is logging that message and how you can improve the performance of the server. Please note that we modify the Apache's, PHP's and MariaDB's configuration according to the server you select when launching the instance. In this case, you can find some symlinks that take care of that configuration 

```
apache/conf/bitnami:
total 32
drwxrwxr-x 4 bitnami root 4096 Aug  3 13:10 .
drwxrwxr-x 6 bitnami root 4096 Jun 27 17:20 ..
-rw-rw-r-- 1 bitnami root  469 Aug  3 13:09 bitnami.conf
-rw-rw-r-- 1 bitnami root  948 Jun 27 17:37 bitnami-ssl.conf
drwxr-xr-x 2 root    root 4096 Aug  3 13:09 certs
lrwxrwxrwx 1 root    root   24 Aug  3 13:10 httpd.conf -> memory/httpd-xlarge.conf
...
mariadb/conf/bitnami:
total 12
drwxrwxr-x 3 root root 4096 Aug  3 13:10 .
drwxrwxr-x 3 root root 4096 Jun 27 17:37 ..
drwxr-xr-x 2 root root 4096 Jun 27 17:37 memory
lrwxrwxrwx 1 root root   21 Aug  3 13:10 memory.conf -> memory/my-xlarge.conf
...
php/etc:
total 276
drwxrwxr-x  5 root    root  4096 Aug  3 13:10 .
drwxr-xr-x 12 root    root  4096 Jun  6 15:18 ..
-rw-rw-r--  1 root    root    64 Jun 22 19:00 common.conf
drwxrwxr-x  2 root    root  4096 Jan  1  1970 conf.d
-rw-rw-r--  1 root    root    17 Jun 22 19:00 environment.conf
drwxr-xr-x  2 root    root  4096 Jun 27 17:37 memory
lrwxrwxrwx  1 root    root    25 Aug  3 13:10 memory.conf -> memory/memory-xlarge.conf
```

**Comment by xavier-alsina** [comment]
Thanks @jotamartos 
The problem is in the logging or in the error itself? Are you suggesting to simply remove the logging? No concern re the error itself?

I know the stack select the configuration depending on instance hardware, but increasing instance doesn't change the performance....

I'll try to remove the logging and come back.
thanks

**Comment by jotamartos** [comment]
>The problem is in the logging or in the error itself? Are you suggesting to simply remove the logging? No concern re the error itself?

You can disable the logging and check if the performance improves. However, I suggest you investigate the reason why WordPress is logging that much information. Its developers can provide more information in the WordPress' forums
