### ISSUE TITLE
[WordPress] Question about Event Scheduler

### ISSUE THREAD

**Issue by dblincoe24** [bitnami/vms#1078]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Error Using the Tool

### bndiagnostic was not useful. Could you please tell us why?

It generated a permissions error when attempting to run

### Describe your issue as much as you can

We created a few stored procedures that we would like to run on a nightly basis.  I have gone in and run this command to enable Event Scheduler:
SET GLOBAL event_scheduler = ON;

This seems to work for a day or two, but then it returns back to an "Off" state and the events won't execute.  
Looking through google it seems that there might be an ini file to adjust this setting, but I cannot find it.  Our instance is using a MariaDB.  
Is there a location where I can look to find this?  Thanks

**Comment by jotamartos** [comment]
>Looking through google it seems that there might be an ini file to adjust this setting, but I cannot find it. Our instance is using a MariaDB.

You can find the MariaDB-related files (and its configuration file) inside the /opt/bitnami/mariadb folder. Once you edit the configuration, please remember to restart the service by using the /opt/bitnami/ctlscript.sh script.

https://docs.bitnami.com/general/apps/wordpress/get-started/understand-default-config-mariadb/

**Comment by dblincoe24** [comment]
Thank you for the reply.  I added event_scheduler=ON to the my.cnf and restarted the services.  I will check tomorrow to see if the events processed as expected.
