### ISSUE TITLE
[Jenkins] bitnami/jenkins image fails to deploy in GCP

### ISSUE THREAD

**Issue by drumwhizz** [bitnami/vms#1079]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

fa0727c5-bdd1-812e-d7f1-49908f5e212a

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
    ✓ Apache: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1681 645 298 0 737 881 Swap: 0 
0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
Press [Enter] to continue:
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

.

### Describe your issue as much as you can

I have launched the bitnami/jenkins from the GCP Market place today.
In the Deployment Manager, as I deploy the image, using the default settings, one of the items in the tree (of things to install) fails: Software-Status software_status.py -> Jenkins-software config waiter.

The error displayed is:

jenkins-packaged-by has resource level errors
jenkins-software: {"ResourceType":"runtimeconfig.v1beta1.waiter","ResourceErrorCode":"504","ResourceErrorMessage":"Timeout expired."}

It does sound like I am running the image on an under powered/resourced VM (g1-small). Can you advise?

Thanks

Phil

**Comment by drumwhizz** [comment]
I will add that the Jenkins VM is running despite the deployment manager saying it failed. So it would be good to understand what the error code means?

**Comment by drumwhizz** [comment]
Out of interest I launched another Jenkins VM based on a n1-standard-1 machine type, and exactly the same error occurred. Again the VM appears to be running and I can log in and configure.

**Comment by jotamartos** [comment]
Hi @drumwhizz,

As we mentioned in [the past](https://github.com/bitnami/vms/issues?q=is%3Aissue+runtimeconfig.v1beta1.waiter), that's just a warning and it doesn't affect you. You can use the solution without problems. 

Have a good weekend!

**Comment by drumwhizz** [comment]
Thanks
