### ISSUE TITLE
[WordPress] Website cannot be reached using domain name

### ISSUE THREAD

**Issue by NyazJaff** [bitnami/vms#1080]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

87e3e2a3-9f27-df46-b8f3-2f45645f1642

### bndiagnostic output

    ✓ Apache: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ? Wordpress: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 
[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:
https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]
Some files don't have the expected permissions Please check the following guide: 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/
 

### bndiagnostic was not useful. Could you please tell us why?

I'm running bitnami on Lightsail not EC2

### Describe your issue as much as you can

Today without doing any changes, suddenly the website is no longe responding to domain name calls. 

I have checked my firewalls too and ports 22, 80 and 443 has no restrictions
<img width="764" alt="image" src="https://github.com/bitnami/vms/assets/15816737/a40734f8-e129-4779-b5da-b514398977b9">

I have already carried out the step to put correct Wordpress permissions as advised in one the urls in the diagnostic tool
<img width="738" alt="image" src="https://github.com/bitnami/vms/assets/15816737/333999f2-705a-46f7-87bc-72f4c141d039">

I appreciate if someone has any knowledge of this and can share some insight on how to fix this. 

I also checked if is the plugins but it's not because I can access the website using the public IP.

Many thanks

**Comment by jotamartos** [comment]
I just accessed your site using your domain (b****da.com). Is this now resolved?

**Comment by NyazJaff** [comment]
@jotamartos it's but not sure what fixed it. 
Thank you for looking into it.

**Comment by jotamartos** [comment]
Great! Please note that domain name changes takes some time to be fully propagated. You can verify that everything is correct by using this online tool 

https://www.whatsmydns.net/
