### ISSUE TITLE
[Weblate] Celery isn't running tasks 

### ISSUE THREAD

**Issue by martindmarques** [bitnami/vms#1081]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a5bd8bda-d707-532e-f284-95904ea3069e

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
Press [Enter] to continue:
[Tue Aug 08 02:37:29.162869 2023] [wsgi:error] [pid 2333:tid 140613211318016]
[remote **ip_address**:47980] [2023-08-08 02:37:29,162: INFO/2333]
storybook/api-dev: updating stats caches

[Tue Aug 08 02:37:37.923811 2023] [wsgi:error] [pid 2332:tid 140613118998272]
[remote **ip_address**:9502] [2023-08-08 02:37:37,923: INFO/2332]
storybook/api-dev: updating stats caches

[Tue Aug 08 02:37:39.539856 2023] [wsgi:error] [pid 2333:tid 140613169354496]
[remote **ip_address**:9516] [2023-08-08 02:37:39,539: INFO/2333]
storybook/api-dev: updating stats caches

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I had a problem with celery

### Describe your issue as much as you can

I encountered an issue with Celery tasks on my EC2 instance running Weblate Bitnami 4.16.4-2. Everything seemed to work fine, but the queued tasks in Celery don't seem to be executing. I wonder if there's any initial configuration that might be missing and not documented?

In the configuration file /opt/bitnami/weblate/lib/Weblate-4.16.4-py3.7.egg/weblate/settings.py, I see the following lines:
```
# Celery worker configuration for production
CELERY_TASK_ALWAYS_EAGER = False
#CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_BROKER_URL = "redis://127.0.0.1:6379/"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# Celery settings, it is not recommended to change these
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 200000
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TASK_ROUTES = {
    "weblate.trans.tasks.auto_translate*": {"queue": "translate"},
    "weblate.accounts.tasks.notify_*": {"queue": "notify"},
    "weblate.accounts.tasks.send_mails": {"queue": "notify"},
    "weblate.utils.tasks.settings_backup": {"queue": "backup"},
    "weblate.utils.tasks.database_backup": {"queue": "backup"},
    "weblate.wladmin.tasks.backup": {"queue": "backup"},
    "weblate.wladmin.tasks.backup_service": {"queue": "backup"},
    "weblate.memory.tasks.*": {"queue": "memory"},
}
```

Also, when running "ps aux | grep celery," I get the following output:

```
daemon 1988 0.1 4.4 238032 177712 ? S Aug07 1:03 /opt/bitnami/weblate/venv/bin/python -m celery -A weblate.utils worker --pidfile=/opt/bitnami/weblate/tmp/weblate.pid --logfile=/opt/bitnami/weblate/logs/celery.log --loglevel=INFO --queues=memory --prefetch-multiplier=10 -n memory@ip-[ip_number] --executable=/opt/bitnami/weblate/venv/bin/python
daemon 2070 0.0 3.6 237380 146524 ? S Aug07 0:02 /opt/bitnami/weblate/venv/bin/python -m celery -A weblate.utils worker --pidfile=/opt/bitnami/weblate/tmp/weblate.pid --logfile=/opt/bitnami/weblate/logs/celery.log --loglevel=INFO --queues=memory --prefetch-multiplier=10 -n memory@ip-[ip_number] --executable=/opt/bitnami/weblate/venv/bin/python
daemon 2071 0.0 3.6 237268 146444 ? S Aug07 0:02 /opt/bitnami/weblate/venv/bin/python -m celery -A weblate.utils worker --pidfile=/opt/bitnami/weblate/tmp/weblate.pid --logfile=/opt/bitnami/weblate/logs/celery.log --loglevel=INFO --queues=memory --prefetch-multiplier=10 -n memory@ip-[ip_number] --executable=/opt/bitnami/weblate/venv/bin/python
bitnami 13424 0.0 0.0 6240 640 pts/0 S+ 03:07 0:00 grep celery
```

When I check the queues using the command "weblate celery_queues," the output is as follows:
backup: 0
celery: 18
memory: 0
notify: 369
translate: 0

Is there anything I need to configure to ensure Celery tasks are processed correctly?

**Comment by jotamartos** [comment]
Is there any error in the Celery's log file `/opt/bitnami/weblate/logs/celery.log`? I also suggest you take a look at the [Weblate's official documentation](https://docs.weblate.org/en/latest/admin/install.html#monitoring-celery-status)
