### ISSUE TITLE
Unable to use the old problem anymore

### ISSUE THREAD

**Issue by pengge6292** [bitnami/vms#1082]
### Name and Version

Bitnami HTTPS Configuration Tool 1.1.1 --- Built on 2023-03-01 12:34:08 IB: 23.1.0-202301121337

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Historical Problem Cases

https://github.com/bitnami/vms/issues/387

shell：
```
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/latest/bncert-linux-x64.run
chmod +x ./bncert-linux-x64.run
./bncert-linux-x64.run --version
./bncert-linux-x64.run

chmod +x bncert-linux-x64.run
root@iZ2ze6qz5rr5v1wzl7buucZ:~/pg/test# ./bncert-linux-x64.run --version
Bitnami HTTPS Configuration Tool 1.1.1 --- Built on 2023-03-01 12:34:08 IB: 23.1.0-202301121337
root@iZ2ze6qz5rr5v1wzl7buucZ:~/pg/test# ./bncert-linux-x64.run
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory []:

Warning: The path does not seem to contain a valid Bitnami installation. Make
sure you have proper access rights, or choose a different directory.
Press [Enter] to continue:
```

### What is the expected behavior?

https://github.com/bitnami/vms/issues/387#issuecomment-1280670361

### What do you see instead?

https://github.com/bitnami/vms/issues/387#issuecomment-1280050083

### Additional information
docker run bitnami/wordpress:6
apache
If using this tool

Can be directly executed

You still need to log in to the tool website and bind a static IP address

Assumptions And Prerequisites
This guide assumes that:

You have deployed a Bitnami application and the application is available at a public IP address so that the Let’s Encrypt process can verify your domain.
You have the necessary credentials to log in to the Bitnami application instance.
You own one or more domain names.
You have configured the domain name’s DNS record to point to the public IP address of your Bitnami application instance.

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/

**Comment by mdhont** [comment]
Could you try the manual approach?

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by pengge6292** [comment]
Still can't do it

Do you need any special operations

For example, it is necessary to register and authenticate the domain name information to be generated, and so on











sudo /root/pengge/lego/lego --tls --email="heartdub@heartdub.com" --domains="heartdub.cn" --domains="www.heartdub.cn" --path="/root/pengge/lego/test" run
2023/08/22 14:13:37 No key found for account heartdub@heartdub.com. Generating a P256 key.
2023/08/22 14:13:37 Saved key to /root/pengge/lego/test/accounts/acme-v02.api.letsencrypt.org/heartdub@heartdub.com/keys/heartdub@heartdub.com.key

2023/08/22 14:13:38 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf
Do you accept the TOS? Y/n
2023/08/22 14:13:38 [INFO] acme: Registering account for heartdub@heartdub.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/root/pengge/lego/test/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2023/08/22 14:13:39 [INFO] [heartdub.cn, www.heartdub.cn] acme: Obtaining bundled SAN certificate
2023/08/22 14:13:40 [INFO] [heartdub.cn] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/257223643566
2023/08/22 14:13:40 [INFO] [www.heartdub.cn] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/257223643576
2023/08/22 14:13:40 [INFO] [heartdub.cn] acme: use tls-alpn-01 solver
2023/08/22 14:13:40 [INFO] [www.heartdub.cn] acme: use tls-alpn-01 solver
2023/08/22 14:13:40 [INFO] [heartdub.cn] acme: Trying to solve TLS-ALPN-01
2023/08/22 14:13:44 [INFO] [www.heartdub.cn] acme: Trying to solve TLS-ALPN-01
2023/08/22 14:13:48 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/257223643566
2023/08/22 14:13:49 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/257223643576
2023/08/22 14:13:49 Could not obtain certificates:
        error: one or more domains had a problem:
[heartdub.cn] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 123.57.31.239: Error getting validation data
[www.heartdub.cn] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 123.57.31.239: Error getting validation data
[root@vpn ~/pengge/lego/heartdub]# ping heartdub.cn
PING heartdub.cn (123.57.31.239) 56(84) bytes of data.
64 bytes from 123.57.31.239 (123.57.31.239): icmp_seq=1 ttl=56 time=39.2 ms
64 bytes from 123.57.31.239 (123.57.31.239): icmp_seq=2 ttl=56 time=39.2 ms
^C
--- heartdub.cn ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 39.212/39.240/39.269/0.200 ms
[root@vpn ~/pengge/lego/heartdub]# curl heartdub.cn
[root@vpn ~/pengge/lego/heartdub]# curl -I heartdub.cn
HTTP/1.1 301 Moved Permanently
Date: Tue, 22 Aug 2023 06:15:07 GMT
Server: Apache
X-Redirect-By: WordPress
Location: https://heartdub.cn/
Vary: User-Agent,Accept-Encoding
Connection: keep-alive
Content-Type: text/html; charset=UTF-8

**Comment by mdhont** [comment]
The issue seems to be the domain:

```
error: one or more domains had a problem:
[yourdomain.cn] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 123.57.31.239: Error getting validation data
[www.yourdomain.cn] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 123.57.31.239: Error getting validation data
[root@vpn ~/pengge/lego/heartdub]# ping yourdomain.cn
```

Does the domain point to the machine IP?

https://www.whatsmydns.net/

**Comment by pengge6292** [comment]
https://www.whatsmydns.net/#A/heartdub.cn

There is a corresponding domain name resolution

Why is it still 400



Do I need any special operations

**Comment by mdhont** [comment]
I recommend contacting Let's Encrypt. I found the following thread about this issue:

https://community.letsencrypt.org/t/certificate-not-being-created-due-to-error-getting-validation-data/70863

**Comment by pengge6292** [comment]
Okay, thank you
