### ISSUE TITLE
[Bitnami Wildfly] <War controller servlet not executing>

### ISSUE THREAD

**Issue by Jondaqs** [bitnami/vms#1083]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7aa3f82e-c1fb-0440-612f-a67298b838c9

### bndiagnostic output

✓ Resources: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
    ? Apache: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

I am able to upload and access the index.jsp file, but not able to call any other page via the controller servlet

### Describe your issue as much as you can

I have a war file with an index.jsp page, and other pagers are called via the controller servlet. The war is deployed, and can call the home page (index.jsp) . But when I try to reach the signup page which goes through the controller servlet the browser returns ??Not Found?? error. The web app runs well on my local wildfly server, but fails on the google cloud bitnami wildfly. It's quite frustrating and help would be welcome

**Comment by mdhont** [comment]
Can you paste the output?

**Comment by Jondaqs** [comment]
Thank you for follow up; I doubt its a command issue; I upload the war file to deployments folder; the war file is deployed successfully; when I got to the website url the index.jsp home page is called; but I can't reach any other url on the browser, it returns not found. THe web app hac the mvc architecture with the controller servlet redirecting urls to appropriate pages; I have also tried to compile the web app as a maven war package; and getting other errors

the error on the log file on the maven web app is:
Failed t
[server (1).log](https://github.com/bitnami/vms/files/12312149/server.1.log)
o define class com.survlinx.controller.ControllerServlet in Module "deployment.survlinxm-1.0-SNAPSHOT.war" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link com/survlinx/controller/ControllerServlet (Module "deployment.survlinxm-1.0-SNAPSHOT.war" from Service Module Loader): javax/servlet/http/HttpServlet

**Comment by Jondaqs** [comment]
sorted. Using Jakarta.* instead of javax.* worked
