### ISSUE TITLE
[SuiteCRM] Upgrading Debian 9 to 11 with Bitnami Installed

### ISSUE THREAD

**Issue by eflinc** [bitnami/vms#1085]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4ef80144-f2be-0f9c-9df9-0f2e0800c19f

### bndiagnostic output

Apache fund a few issues!

### bndiagnostic was not useful. Could you please tell us why?

Need further help. Diagnostics sent to Bitnami, so was useful!

### Describe your issue as much as you can

Hi 

I have inherited a Bitnami install from my predecessor and we have a requirement to upgrade Debian/Bitnami from Debian 9 to 11.
First question is does we need to just update Debian or does the Bitnami upgrade include Debian? Are they separately installed like OS and App? 
Completely new to this software, so just wondering how we can get to Debian 11 with the less stress?
Can I leave the Bitnami app alone, and just upgrade Debian, or will Bitnami need to be upgrade also?

Thanks in advance all

**Comment by eflinc** [comment]
Hi Juan

The second and third options both require us to download and install a new OVA file right?


Regards
________________________________

**Comment by jotamartos** [comment]
>The second and third options both require us to download and install a new OVA file right?

Correct. They will require to download the latest OVA and migrate the data from the old VM to the new one. The difference is that in the second option you will keep using the same version for Apache, PHP, MySQL and SuiteCRM and in the 3rd one you will also upgrade those components to the latest one.
