### ISSUE TITLE
Problem with my site NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by aelizondo82** [bitnami/vms#1086]
### Describe your issue as much as you can

Hello, Today I in to website, now I see an error with NET::ERR_CERT_DATE_INVALID

How can update o reactivate the certificate ssl?

I create the wordpress bitnami

**Comment by jotamartos** [comment]
Hi @aelizondo82,

You should have a job configured in your cronjob

```
sudo crontab -l
sudo crontab -l -u bitnami
```

You should find a `lego` command there. You can try to renew the certificate using the command. If that doesn't work, please run the Bitnami HTTPS configuration tool again to generate a new one 

https://docs.bitnami.com/aws/how-to/understand-bncert/
