### ISSUE TITLE
ELK Bitnami reboot issue

### ISSUE THREAD

**Issue by manigandan1821** [bitnami/vms#1089]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ff3f56ec-de2c-4999-a832-e60590cd10ba

### bndiagnostic output

Hi Team,
we are purchased ELK from AWS Marketplace.
As we are facing issue on ELK server uptime issue, and it is rebooting for every Tue, Frid. Can we know, why it is rebooting for only those particular days and how to stop it from rebooting.

From our end, we have observed that the system is powering on with this timestamp Aug  4 00:31:37 and the server is  coming up within this timestamp Aug  4 00:35:14.
Attached the screenshot for your reference.
![MicrosoftTeams-image (2) (1)](https://github.com/bitnami/vms/assets/110691632/ff3f56ec-de2c-4999-a832-e60590cd10ba)

### bndiagnostic was not useful. Could you please tell us why?

ELK Bitnami reboot issue

### Describe your issue as much as you can

Hi Team,
we are purchased ELK from AWS Marketplace.
As we are facing issue on ELK server uptime issue, and it is rebooting for every Tue, Frid. Can we know, why it is rebooting for only those particular days and how to stop it from rebooting.

From our end, we have observed that the system is powering on with this timestamp Aug  4 00:31:37 and the server is  coming up within this timestamp Aug  4 00:35:14.
Attached the screenshot for your reference.
![MicrosoftTeams-image (2) (1)](https://github.com/bitnami/vms/assets/110691632/a200e8fd-5628-4352-b1da-16b00faaf842)

**Comment by viswanath2222** [comment]
Can anyone reply on this issue?
As we are critically blocked on this incident @mdhont

**Comment by viswanath2222** [comment]
Hi Team,
We have raised an issue on 10/8/23, still the ticket has not been updated and we didn't get any resolution.

Kindly take this on priority and provide us the resolution ASAP and do the needful.

**Comment by jotamartos** [comment]
Hi @viswanath2222,

>ff3f56ec-de2c-4999-a832-e60590cd10ba

I tried to get more information using this id but it doesn't exist in our records. Could you please run the tool again so we can review the information in your system? 

>As we are facing issue on ELK server uptime issue, and it is rebooting for every Tue, Frid. Can we know, why it is rebooting for only those particular days and how to stop it from rebooting.

Please note that we do not configure any logic to stop/reboot the instances every Tuesday or Friday, this should be something external. We do not know if you configured any job that makes changes in the system during those days. For example, you could have configured a cronjob that restarts the machine every Tue and Fri, can you review that? 

The machine could be also running out of memory and  that may be the reason of this. Can you monitor the RAM usage at those times or the requests the server is receiving to see if there is not a bot/attacker accessing your site? 

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-connections-bots-apache/

>systemd-logind: Power key pressed.

As you can see in this other thread, it seems someone or something is making the server to stop 

https://unix.stackexchange.com/questions/454329/unexpected-shutdown-with-a-power-key-pressed-log

Can you try the suggestion in the thread to see if that makes any change?
