### ISSUE TITLE
[BNCert-Tool] your connection to this site is not fully secure

### ISSUE THREAD

**Issue by prodigygeorge** [bitnami/vms#109]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1c5d8b09-d062-71fe-78dd-bcc88271f05d

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Mysql: No issues found
    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Php: No issues found
    ✓ Processes: No issues found
 

 
[Apache]

Found recent Pagespeed related error messages in the Apache error log:
```
[Tue Jul 12 13:34:28.472521 2022] [pagespeed:error] [pid 19024:tid 
140580814071552] [mod_pagespeed **ip_address**-0 @19024] PageSpeed Serf fetch 
failure rate extremely high; only 108 of 406 recent fetches fully successful; is 
fetching working?

```
Press [Enter] to continue:
We suggest disabling pagespeed and check if that improves the behavior. Please 
check the following guide to disable Pagespeed:
 
https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespe
ed/#disable-pagespeed

Found recent error or warning messages in the Apache error log.
```
[Tue Jul 12 06:16:06.096653 2022] [core:error] [pid 26556:tid 140581040674560] 
[client **ip_address**:55710] AH00126: Invalid URI in request POST 
/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1
 [Tue Jul 12 07:49:25.353564 2022] [autoindex:error] [pid 26556:tid 
140581124601600] [client **ip_address**:60482] AH01276: Cannot serve directory 
/opt/bitnami/apps/letsencrypt/.well-known/: No matching DirectoryIndex 
(index.html,index.php) found, and server-generated directory index forbidden by 
Options directive

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

Press [Enter] to continue:
A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

[Resources]

Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem Size Used Avail Use% Mounted on /dev/sda1 20G 16G 2.9G 85% /
```
Please check your cloud provider's documentation for more information.

### bndiagnostic was not useful. Could you please tell us why?

Does not indicate why the HTTPS cert is not working

### Describe your issue as much as you can

![Evidence - SSL Cert](https://user-images.githubusercontent.com/109100003/178507700-7bee96ec-bb09-4235-ad56-0a1a6ad0e99c.png)

Have run the BNCErt-Tool and generated the certificate. The site is still showing Not Secure. We are not able to determine the issue. Any help is appreciated.

**Comment by mdhont** [comment]
That means your site has some http URL's, probably links to images:

    grep --include=\*.html -Ril "http:\/\/" /opt/bitnami/APP

**Comment by mdhont** [comment]
Sorry, the command I shared lists all html files in the `/opt/bitnami/APP` folder that contain insecure URL's. Please note that APP is a placeholder for your application's name:

    sudo grep --include=\*.html -Ril "http:\/\/" /path/to/application/

After you've obtained the list you need to open those files and replace http with https.
