### ISSUE TITLE
Bitnami-Wordpress Unable to start

### ISSUE THREAD

**Issue by dsnoble** [bitnami/vms#1090]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b8e6fb42-8b0a-3f9b-7af4-9f11e532f5ee

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Press [Enter] to continue:
Found recent WordPress plugin related error messages in the Apache error log.
```
[Wed Aug 09 16:05:08.968108 2023] [proxy_fcgi:error] [pid 1706:tid 
140496995329792] [client **ip_address**:10686] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: http://ip/wp-admin/plugin-install.php

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Aug 09 18:25:28.096826 2023] [ssl:emerg] [pid 5474:tid 139997163382592] 
AH02572: Failed to configure at least one certificate and key for 
**ip_address**:443
 [Wed Aug 09 18:25:28.096879 2023] [ssl:emerg] [pid 5474:tid 139997163382592] 
SSL Library Error: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no 
certificate assigned
 [Wed Aug 09 18:25:28.096885 2023] [ssl:emerg] [pid 5474:tid 139997163382592] 
Press [Enter] to continue:
AH02312: Fatal error initialising mod_ssl, exiting.

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
AH00526: Syntax error on line 3 of 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: Invalid command 
'SSL', perhaps misspelled or defined by a module not included in the server 
configuration
```
Please check the configuration.
 
===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Helpful but didn't solve

### Describe your issue as much as you can

This all started when attempting to install an SSL failed. All of the documentation I have found on how to install an SSL on these servers all seem to have different file structures than what this one has. For example, the documentation says the certificates are in /opt/bitnami/apache/conf/ but after running certbot or lego, the certs get put in /opt/bitnami/apache/conf/bitanmi/cert/

I've tried to move files around to match what the documentation says but I think there are some config files that I need to update or something in order to get this to fully work. The LetsEncrypt server does issue certificates successfully but the server doesn't seem to recognize them.

**Comment by dsnoble** [comment]
I fixed the error of AH00526 because I stupidly added a space on that line. Here is the updated diagnostic bundle. 

fff78938-282c-8cf8-e6b6-9751377e9160

**Comment by dsnoble** [comment]
Is there anyone who can help me with this?

**Comment by gongomgra** [comment]
Hi @dsnoble,

Thanks for using Bitnami. According to the latest bndiagnostic bundle you shared, the `apache2/conf/bitnami/certs` folder is empty

```
apache/conf/bitnami/certs:
total 8
drwxrwxr-x 2 bitnami daemon 4096 Aug 11 17:04 .
drwxrwxr-x 4 bitnami daemon 4096 Aug 11 17:05 ..
```

You need to create a symbolic link for the Let's Encrypt certificates from the `letsencrypt` folder to the one above. You can follow the steps in the next guide in case you need help

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#step-3-configure-the-web-server-to-use-the-lets-encrypt-certificate

Hope it helps!

**Comment by dsnoble** [comment]
I am now experiencing the following errors: 
One or more component's processes are not running:
```
mariadb not running
```
You can try to restart the process with the following command:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Aug 23 00:17:04.038551 2023] [proxy_fcgi:error] [pid 53903:tid 
139967984523008] [client **ip_address**:43164] AH01071: Got error 'PHP message: 
PHP Warning: require(/opt/bitnami/wordpress/wp-includes/version.php): Failed to 
open stream: Permission denied in /opt/bitnami/wordpress/wp-settings.php on line 
33PHP message: PHP Fatal error: Uncaught Error: Failed opening required 
'/opt/bitnami/wordpress/wp-includes/version.php' 
(include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/wordpres [Wed Aug 23 
00:17:37.900101 2023] [proxy_fcgi:error] [pid 53152:tid 139967976130304] [client 
**ip_address**:49132] AH01071: Got error 'PHP message: PHP Warning: 
require(/opt/bitnami/wordpress/wp-includes/version.php): Failed to open stream: 
Press [Enter] to continue:
Permission denied in /opt/bitnami/wordpress/wp-settings.php on line 33PHP 
message: PHP Fatal error: Uncaught Error: Failed opening required 
'/opt/bitnami/wordpress/wp-includes/version.php' 
(include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/wordpres [Wed Aug 23 
00:17:56.312777 2023] [proxy_fcgi:error] [pid 53152:tid 139967992915712] [client 
**ip_address**:45320] AH01071: Got error 'PHP message: PHP Warning: 
require(/opt/bitnami/wordpress/wp-includes/version.php): Failed to open stream: 
Permission denied in /opt/bitnami/wordpress/wp-settings.php on line 33PHP 
message: PHP Fatal error: Uncaught Error: Failed opening required 
'/opt/bitnami/wordpress/wp-includes/version.php' 
(include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/wordpres

**Comment by dsnoble** [comment]
Diagnostic bundle: 1477320a-d585-676a-21a2-0dc3b8b49ed0

**Comment by gongomgra** [comment]
Hi @dsnoble,

I don't see any issue with permissions in the latest bndiagnostic bundle you shared, nor in the MariaDB logs. Can you try to manually start it? Did you modify anything else on your server before getting this error?

```
sudo /opt/bitnami/ctlscript.sh start mariadb
```

**Comment by dsnoble** [comment]
The only thing I did was the steps listed prior with the certificates. I've tried to restart the database, and it doesn't start. I get this error: Failed to start mariadb: Failed to start mariadb. 

That's the confusing part - it was running fine, that was one of the elements that was always running until now. 

Here are logs from just now after a reboot via the Lightsail instance rather than command line. 
e508937c-e161-0963-42d4-dbaca207135a

**Comment by gongomgra** [comment]
Hi @dsnoble,

I checked the most recent bndiagnostic information and I found the next information related to MariaDB

```
 [Mariadb]

Some files don't have the expected permissions. 
```

We recommend you to check the following guide:

https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

Did you have any chance to manually start MariaDB as I suggested in my previous message? I also see the services monitor (gonit) is not running on your server. Did you modify any configuration or manually stopped the service?

```
-----------------------------------
Get the ctlscript status
-----------------------------------
Running: ./ctlscript.sh status
In: /opt/bitnami

Output:

Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)
```

You can get more information about the Gonit utility and how to use it in the guide below. Please try to manually start it on your server

https://docs.bitnami.com/aws/apps/wordpress/administration/configure-use-gonit/

**Comment by dsnoble** [comment]
The only way to get MariaDB to start is to do a hard restart in the Lightsail console. If I do a restart, all services start and operate, but MariaDB doesn't connect to the WordPress site. It says the permission error you indicated above but doesn't provide any additional detail on which files need to be corrected. 

Additionally, gonit shows Apache, MariaDB and PHP-FPM and running.

**Comment by dsnoble** [comment]
Here is the bundle: 
dacd638a-bdc4-ce26-ecb8-416a8d2cd45e

**Comment by gongomgra** [comment]
Hi @dsnoble,

I see the next errors in the Apache logs related to WordPress installation

```
[Wed Aug 30 19:14:08.635741 2023] [proxy_fcgi:error] [pid 2057:tid 139966931207936] [client 50.244.33.54:52205] AH01071: Got error 'PHP message: PHP Warning:  mysqli_real_connect(): (HY000/2002): No such file or directory in /opt/bitnami/wordpress/wp-includes/class-wpdb.php on line 2035'
[Wed Aug 30 19:14:08.920995 2023] [proxy_fcgi:error] [pid 2153:tid 139966793373440] [client 50.244.33.54:52207] AH01071: Got error 'PHP message: PHP Deprecated:  mysqli_real_connect(): Passing null to parameter #5 ($database) of type ?string is deprecated in /opt/bitnami/wordpress/wp-includes/class-wpdb.php on line 2035PHP message: PHP Deprecated:  mysqli_real_connect(): Passing null to parameter #7 ($socket) of type ?string is deprecated in /opt/bitnami/wordpress/wp-includes/class-wpdb.php on line 2035PHP message: PHP Warning:  mysqli_real_connect(): (HY000/2002): No such file or directory in /opt/bitnami/wordpress/wp-includes/class-wpdb.php on line 2035', referer: https://YOUR-DOMAIN-HERE/
```

I'm afraid I don't know what can be causing these issues on your installation, but it seems to be more related to the WordPress app itself than to Bitnami installation. We recommend you to open a new question in the official WordPress forums for further help on this

https://wordpress.org/support/forums/

Regarding LightSail instances, notice the burstable feature of those instance types may cause performance issues as well. You can get more information on this in the official AWS docs

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances.html

Apart from the above, I visited your website using the domain name at `https://ue<THE-REST-OF-YOUR-DOMAIN-HERE>u.net/` and it showed the WordPress login page, so I understand the site is working properly. Did you manage to solve your issue?
