### ISSUE TITLE
WordPress with NGINX and SSL Certified by Bitnami and Automattic: Please make it support AWS c6a

### ISSUE THREAD

**Issue by kdamsmt** [bitnami/vms#1092]
### Describe your suggestion as much as you can

Currently it support only c5 it too much expensive if compare to similar instance in c6a. My production site use https://aws.amazon.com/marketplace/pp/prodview-s6cuqgfczpuwm#pdp-support in marketplace that does not support c6a than I can't change it.

I found your AMI https://bitnami.com/stack/wordpress-pro/cloud/aws/amis is support c6a. 

Just for suggestion in the future please make Bitnami AWS support all latest instance type as possible, due to it cheap and faster than old.

**Comment by williamgh2019** [comment]
> Hi @williamgh2019,
> 
> Thanks for using Bitnami. I have been able to select the `c6a.large` instance type for an AWS Marketplace fresh new server in the `us-east-1` region. Can you check if this is something related to your region?
> 
> ![Screenshot 2023-08-17 at 17 17 32](https://user-images.githubusercontent.com/6660452/261360012-06c6d9a0-1011-4d5b-bee9-a633bf901f9e.png)

👉Your AMI in Marketplace can't use with `c6a.large`
<img width="1103" alt="image" src="https://github.com/bitnami/vms/assets/17005582/aba04d42-08bc-4b4e-ba3d-d787b85d8e54">

👉I can't select both for `Singapore` nor `us-east-1` for `c6a.large`

<img width="796" alt="image" src="https://github.com/bitnami/vms/assets/17005582/f084f30b-1163-406d-ba0c-8c4e14a90c03">


👉Except your AMI from Community AMI is can use with `c6a.large` [WordPress with NGINX and SSL packaged by Bitnami](https://bitnami.com/redirect/to/2361004/wordpresspro-6.3.0-6-amidebian-x64-hvm-ebs-nami?region=ap-southeast-1)
👇
<img width="737" alt="image" src="https://github.com/bitnami/vms/assets/17005582/2e60f430-d2b7-41ec-878a-84dee5dc12ed">

🫡Would you please make Bitnmai AMI more flexible with AWS instance type? You know AWS instance type is affect the cost of hosting, the newest instance is cheaper and better performance than the old one. 

🥲Please don't lock Bitnami AMI to specific instance.

💸As example WordPress with NGINX and SSL packaged by Bitnami only support `c5.large` if compare to `c6a.large` it is cheaper and faster than `c5.large`

**Comment by gongomgra** [comment]
Hi @williamgh2019,

Thanks for your message. I have created a new internal task to include the missing instance types on our AWS Marketplace images. In the meantime, you can launch your instance from the AWS console (community AMIs), which should not be missing any instance type and it is the same image available in the AWS Marketplace.

Hope it helps!

**Comment by kdamsmt** [comment]
Hi @gongomgra,
Just want to update. Now it still can't use c6.large in my old AMI. 

Community is find to create new instance with SGP c6.large but Community AMI charge for additional fee in AWS?

Pls check below screenshot aws has mention as "Additional costs apply for AMIs with pre-installed software"
<img width="564" alt="image" src="https://github.com/bitnami/vms/assets/17005582/5def8656-8373-43eb-a5a0-f79be5ed5c4e">
