### ISSUE TITLE
WordPress with NGINX and SSL packaged by Bitnami eat huge memory

### ISSUE THREAD

**Issue by williamgh2019** [bitnami/vms#1093]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d1580ea1-e363-4a00-5772-42260459c46b

### bndiagnostic output

 ? Nginx: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ? Php: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

Wrong solution

### Describe your issue as much as you can

```
[Php]

The following error appears in the /opt/bitnami/php/logs/php-fpm.log:
```
[12-Aug-2023 09:07:46] ERROR: fork() failed: Cannot allocate memory (12)

```
This error  indicates there is a problem with the memory limit in PHP. Please 
check the following guide to increase the number of PHP-FPM child processes:
 
https://docs.bitnami.com/general/apps/akeneo/administration/increase-memor
y-limit/
```

When I try to access the recommend solution url it difference from my currently use package, I use AWS but solution to increase memory take me to other than!

I was wonder why I see my bitnami instance has low memory and suggest me to increase my instance's memory. I try to increase 3 time already from 2G to 4G now to 15Gb bitnami package still said not enough memory! I run just medium ecommerce what RAM should I use when bitnami eat all memory 

[https://snipboard.io/05po1H.jpg](url)

Please kindly help why memory does not decrease even no one access website?

**Comment by mdhont** [comment]
I recommend disabling all plugins and then enable them one by one to see which one is consuming most resources. (It's usually due to some plugin)
