### ISSUE TITLE
HTTPS mode setup mismatch Your application is running with HTTPS mode set to http, but the request is an https request. This will result in errors! You will need to set the following configuration value: OPENPROJECT_HTTPS=true

### ISSUE THREAD

**Issue by nabeelrahiman** [bitnami/vms#1096]
### Name and Version

open project aws market place

### What architecture are you using?

None

### What steps will reproduce the bug?

HTTPS mode setup mismatch
Your application is running with HTTPS mode set to http, but the request is an https request. This will result in errors! You will need to set the following configuration value: OPENPROJECT_HTTPS=true

this is the error on my GUI how to fix this

where is the conf file lie let me know the command to fix this

### Are you using any custom parameters or values?

![image](https://github.com/bitnami/charts/assets/123075422/4307a81a-9db3-4575-afc3-25cac6299bda)

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/123075422/553a57f6-546b-4b55-86ba-2940b33562b7)

**Comment by gongomgra** [comment]
Hi @shroom24,

Thanks for using Bitnami. Can you give us more information on how to reproduce it?

**Comment by shroom24** [comment]
I don’t know how to reproduce it. This is what’s showing:

￼

**Comment by gongomgra** [comment]
Hi @nabeelrahiman, @shroom24,

Thanks for using Bitnami. That seems to be more related to the OpenProject application itself than with Bitnami installation. You can find all OpenProject files under the `/opt/bitnami/openproject` directory in your machines, and the related Apache configuration at `/opt/bitnami/apache2/conf/virtual-hosts`. You should be able to follow official docs from there.

Hope it helps!

**Comment by quovadisnp** [comment]
I would say this doesn't solve the problem. The fix is to run the openproject binary to set the HTTPS mode but the bitnami deploy doesn't provide this binary. I don't see how this is usable out of the box if you can't properly enable HTTPS.

**Comment by gongomgra** [comment]
Hi @quovadisnp,

Thanks for your message. I'm afraid we don't know how that `openproject` script or binary is created, but according to the `bundle rake -T` command, you should be able to update the variable using `bundle rake` commands as well, although its default value is already `true`.

```
bitnami@ip-172-31-46-245:/opt/bitnami/openproject$ RAILS_ENV=production bundle exec rake setting:available_envs | grep -i "_https"
OPENPROJECT_HTTPS (default=true) Set assumed connection security for the Rails processes
```

I have found a thread in the official OpenProject forums related to a similar installation than ours (but not Bitnami's according to the filesystem paths) with the same error. We recommend you to reopen the thread or create a follow-up to get help on this use case.

https://community.openproject.org/topics/15597

**Comment by nabeelrahiman** [comment]
![image](https://github.com/bitnami/vms/assets/123075422/f048653b-9685-4376-8114-d9d009c5510c)
Still this errors exits can anyone help to resolve this??

**Comment by jotamartos** [comment]
Hi @nabeelrahiman,

As @gongomgra mentioned above, there is a related thread in the OpenProject forums, did you contact them to get more information about the issue?

**Comment by jamietownsend** [comment]
I seem to have solved this issue by
1. editing the file /opt/bitnami/apache2/conf/vhosts/openproject-openproject-vhost.conf and changing SetEnv OPENPROJECT_HTTPS from false to true
2. restarting the services using "/opt/bitnami/ctlscript.sh restart"

**Comment by gongomgra** [comment]
Hi @jamietownsend,

Thanks for your message and for sharing your solution! I'm sure it will be of help to other users in the future.
