### ISSUE TITLE
[WordPress] How to edit PHP configuration parameters

### ISSUE THREAD

**Issue by krmtech** [bitnami/vms#1097]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a4b064e3-4900-52fb-d4dd-5c5e95ee1633

### bndiagnostic output

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 950 520 75 35 355 247 Swap: 
634 10 624
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Aug 16 08:09:09.334992 2023] [proxy_fcgi:error] [pid 1971:tid 
140468121667328] [client **ip_address**:49806] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php 
on line 173; PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 174; PHP message: PHP Warning: 
Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php 
on line 691; PHP message: PHP Warning: Unde [Wed Aug 16 11:06:25.526482 2023] 
[proxy_fcgi:error] [pid 1635:tid 140466896987904] [client **ip_address**:62183] 
AH01071: Got error 'PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 173; PHP message: PHP Warning: 
Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php on line 174; 
Press [Enter] to continue:
PHP message: PHP Warning Undef
```

### bndiagnostic was not useful. Could you please tell us why?

seems useful

### Describe your issue as much as you can

Need to increase limits for allowing large files to be uploaded so that I can restore a wordpress backup.

Modified /opt/bitnami/wordpress/wp-config.php as per plugin author directions:

@ini_set( 'upload_max_filesize' , '512M' );
@ini_set( 'post_max_size', '512M');
@ini_set( 'memory_limit', '512' );
@ini_set( 'max_execution_time', '0' );
@ini_set( 'max_input_time', '300' );

**Comment by jotamartos** [comment]
Hi @krmtech,

If you modified the configuration and you continue running into the same error, the plugin's developers should provide more information about how to debug the issue. 

Please remember that you can also edit those parameters in the PHP's conf file (/opt/bitnami/php/etc/php.ini). You will need to restart the services after applying the changes (/opt/bitnami/ctlscript.sh).
