### ISSUE TITLE
Forgot root user password of phpmyadmin  in AWS lightsail 

### ISSUE THREAD

**Issue by vasundharak** [bitnami/vms#1098]
### Describe your issue as much as you can

Hi,
I changed the password of the root user of phpmyadmin but now when I am entering that password it is not taking it. How can I reset the root user password of phpmyadmin?

**Comment by jotamartos** [comment]
Hi @vasundharak,

This guide explains how to update/reset the database's root password

https://docs.bitnami.com/general/infrastructure/lamp/administration/change-reset-password-mariadb/

**Comment by vasundharak** [comment]
I have mysql database

**Comment by vasundharak** [comment]
I don't have the following folder in  /tmp folder in my server:
/mysql-init

**Comment by jotamartos** [comment]
The documentation asks you to create a file (/tmp/mysql-init) with the content that is shown below

>I have mysql database

In that case, follow this documentation 

https://docs.bitnami.com/general/infrastructure/mysql/administration/change-reset-password-mysql/
