### ISSUE TITLE
UNABLE TO LOG IN TO WORDPRESS when created local host through oracle vm (virtual box)

### ISSUE THREAD

**Issue by ankit87099** [bitnami/vms#1099]
### Name and Version

bitnami-wordpress-6-6.2.2-r1-debian-11-amd64

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. download virtual box from bitnami wordpress https://download.virtualbox.org/virtualbox/7.0.10/VirtualBox-7.0.10-158379-Win.exe
2. download bitnami wordpress https://bitnami.com/redirect/to/2333652/bitnami-wordpress-6.2.2-r1-debian-11-amd64.ova
3. install virtual box
4. add bitnami wordpress software file to virtual box (oracle vm)
5. start the software in oracle vm , it will take some time to initiate and run the software then you will get ip adress like 192.168.0,108 and default user name and password
6. go to chrome type in the ip adress ,a web page will open
7. in avobe ip add (/wp-admin) you will be redirected to login page
8.   type in the user name and password provided

BUT WHEN I ENTER THE DEFAULT USER NAME AND PASSWORD IT SAYS WRONG PASSWORD I AM UNABLE TO LOGIN INTO WORDPRSS 
![Screenshot (13)](https://github.com/bitnami/charts/assets/142482110/aa3b0be3-14ad-40fb-9783-92b8d3fb549c)

PLEASE CHECK THE ISSUE AND GUIDE ME WHAT CAN BE DONE.........

### Are you using any custom parameters or values?

NO

### What is the expected behavior?

IT IS EXPECTED TO OPEN WORDPRESS AFTER ENTERING USER ID AND PASS 

### What do you see instead?

BUT IN MY CASE I AM UNABLE TO LOGIN INTO WOEDPRESS IT SAYS WRONG PASSWORD
![Screenshot (13)](https://github.com/bitnami/charts/assets/142482110/674323ef-6691-48be-976c-3796032a96d5)

### Additional information

HOW CAN I INSTALL WORDPRESS INTO MY COMPUTER TO TRY MAKING A WEBSITE WITHOUT HOSTING IT

**Comment by mdhont** [comment]
Please note that the last character could be capital O instead of (number) 0. Did you try that?
