### ISSUE TITLE
[Wordpress Multisite] can not upload any plugins

### ISSUE THREAD

**Issue by EmpowerDevelopment** [bitnami/vms#110]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

961f98b8-a485-b0bf-59b1-9b6ab70cada1

### bndiagnostic output

can't upload any plugins. I immediately get the following page error

Hmmm… can't reach this pageempowercloudhost.com took too long to respond
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_TIMED_OUT

### bndiagnostic was not useful. Could you please tell us why?

it doesn't resolve the issue

### Describe your issue as much as you can

this is what I have. It is a new bitnami multisite environment on AWS ec2. the primary domain is empowercloudhost.com

**Comment by jotamartos** [comment]
Please take a look at the WordPress' oficial documentation that explains things you can try to solve this.

https://wordpress.org/support/article/common-wordpress-errors/#connection-timed-out

Its support team should also provide more info 

https://wordpress.org/support/

Thanks

**Comment by EmpowerDevelopment** [comment]
This is a bitnami related issue. I had a similar issue with my other multisite but I can't seem to find my notes on it.

**Comment by EmpowerDevelopment** [comment]
i am trying to change the permissions of the wp-content folder. When I do it and check it still shows the old permissions. Please advise.
![2022-07-13_17-34-19](https://user-images.githubusercontent.com/36256730/178840902-7c0d8c2b-c063-4283-913a-a03321ecba01.jpg)

**Comment by jotamartos** [comment]
If you want to reset the permissions configuration, please check this other post 

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974
