### ISSUE TITLE
[WordPress 6.2] <Website going down 24 hours after restart>

### ISSUE THREAD

**Issue by ntsysadm** [bitnami/vms#1100]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

couldt generate id

### bndiagnostic output

Apache]

Found recent Pagespeed related error messages in the Apache error log:
```
[Thu Aug 17 11:16:42.359138 2023] [pagespeed:error] [pid 5855:tid 
140656248981248] [mod_pagespeed 1.13.35.2-0 @585
```
Found recent error or warning messages in the Apache error log.
```
[Thu Aug 17 11:07:55.847299 2023] [proxy_fcgi:error] [pid 5855:tid 
140656274159360] (70007)The timeout specified has expired: [client 
114.******:47045] AH01075: Error dispatching request to : (polling)

[Thu Aug 17 11:07:55.848184 2023] [log_config:warn] [pid 5855:tid 
140656274159360] (28)No space left on device: [client 114.***:47045] 
AH00646: Error writing to logs/access_log

[Thu Aug 17 11:12:42.122253 2023] [log_config:warn] [pid 5855:tid 
140656257373952] (28)No space left on device: [client 71.***:43896] 
AH00646: Error writing to logs/access_log
```
Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1   59G   57G     0 100% /
```
Please check your cloud provider's documentation for more information.

Your instance has little available RAM memory.
```
              total        used        free      shared  buff/cache   available
Mem:           1959        1252          79          96         628         428
Swap:             0           0           0
```
Please check the following guide to troubleshoot MySQL issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ysql/

The "/opt/bitnami/mysql/data" folder is using 66% of total disk space.
```
1/opt/bitnami/mysql/data/#innodb_temp
1/opt/bitnami/mysql/data/mysql
Press [Enter] to continue:
1/opt/bitnami/mysql/data/sys
68/opt/bitnami/mysql/data/bitnami_wordpress
2/opt/bitnami/mysql/data/performance_schema
39781/opt/bitnami/mysql/data
```
In most cases this is due to binary logging. Please check the following guide to 
disable it.
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/disable-bi
nary-logging-mysql/

[Php]

The following error appears in the 
/opt/bitnami/php/var/log/php-fpm.log:
```
[17-Aug-2023 07:31:35] WARNING: [pool www] server reached max_children setting 
(5), consider raising it

```
This error usually indicates PHP script execution is slow due to busy server 
resouces or buggy scripts. Please check the following guide to increase the 
number of PHP-FPM child processes:
Press [Enter] to continue:
 
https://docs.bitnami.com/general/apps/wordpress/configuration/configure-ph
pfpm-processes/

### bndiagnostic was not useful. Could you please tell us why?

It was useful.

### Describe your issue as much as you can

I have this website up and running for three years without any issues. Few times I year I update Linux, WordPress stack and clean the drive. Never had any issues. Over the years upgraded my AWS LIghtsail machine because content was growing, but it always went smoothly.

After last upgrade, a week ago, I noticed that the SQL bin log was growing and making disk full. Because of that all stack services started to fail. I've changed Bin log purge on 24 hours link: https://askubuntu.com/questions/1322041/how-to-solve-increasing-size-of-mysql-binlog-files-problem but issue was not reseloved.

I start to think that the website has fallen victim of DDOS?? SQL Injection?? I have no idea anymore.

**Comment by gongomgra** [comment]
Hi @ntsysadm,

Thanks for using Bitnami. According to the bndiagnostic results you shared and your investigation, the disk was full, and mostly caused by MySQL's binary logs. These kind of issues are usually caused by bots performing lots of requests to your website, making the used disk space to grow very fast due to the MySQL's binary logging feature.

We recommend you to check the guides below on how to check if you are under a bot attack, and how to disable binary logging features for MySQL:

* https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-connections-bots-apache/
* https://docs.bitnami.com/general/apps/wordpress/troubleshooting/disable-binary-logging-mysql/

Hope it helps!
