### ISSUE TITLE
[Gitea] Wrong permissions on gitea folders

### ISSUE THREAD

**Issue by EniacMlezi** [bitnami/vms#1101]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

189744af-bbfe-3506-8bbf-1a746d647348

### bndiagnostic output

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
```
               total        used        free      shared  buff/cache   available
Press [Enter] to continue:
Mem:             411         296          10          18         104          84
Swap:            634          31         603
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Aug 18 15:16:19.336935 2023] [proxy_http:error] [pid 2783:tid
139835133978368] [client **ip_address**:50887] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1

[Fri Aug 18 15:21:25.162739 2023] [proxy:error] [pid 2783:tid 139835117192960]
(111)Connection refused: AH00957: http: attempt to connect to
**ip_address**:3000 (127.0.0.1:3000) failed

[Fri Aug 18 15:21:25.163255 2023] [proxy_http:error] [pid 2783:tid
139835117192960] [client **ip_address**:32830] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1

```
Press [Enter] to continue:
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Processes]

One or more component's processes are not running:
```
gitea not running
```
You can try to restart the process with the following command:

    $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

### bndiagnostic was not useful. Could you please tell us why?

Trying to start gitea process fails

### Describe your issue as much as you can

Seems to me like permissions somehow get messed up. When first booting up the VM, the gitea service is running (and accessible through a browser). But after a while (~5minutes) somehow the service goes down on its own (Even when not having used gitea a tall). When trying to start the service again using ctlscript.sh, the service does not start and no error messages are shown.

When running /opt/bitnami/scripts/gitea/run.sh with tracing enabled, the actual error message is with the PID file:
`2023/08/18 15:20:42 cmd/web.go:97:createPIDFile() [F] Failed to create PID file: open /opt/bitnami/gitea/tmp/gitea.pid: permission denied`

Deleting the PID file stops this issue, but the next permission issue arises on the following run.sh execution:
```
2023/08/18 15:21:10 ...les/queue/manager.go:108:]() [E] Failed to create queue "notification-service": unable to open level db at /opt/bitnami/gitea/data/queues/common: open /opt/bitnami/gitea/data/queues/common/LOCK: permission denied
```

Some further investigations shows the source of the next issue:
```
root@gitea:/opt/bitnami/scripts/gitea# ls -l /opt/bitnami/gitea/data/
total 48
drwxr-xr-x 2  997 gitea 4096 Aug 18 14:54 attachments
drwxr-xr-x 2  997 gitea 4096 Aug 18 14:54 avatars
drwxr-xr-x 3 root root  4096 Aug 18 14:54 git
drwxr-xr-x 2  997 gitea 4096 Aug 18 14:54 home
drwx------ 3  997 gitea 4096 Aug 18 14:54 indexers
drwxr-xr-x 2  997 gitea 4096 Aug 18 14:54 jwt
drwxr-xr-x 2  997 gitea 4096 Aug 18 14:54 packages
drwxr-xr-x 3  997 gitea 4096 Aug 18 14:54 queues
drwxr-xr-x 2  997 gitea 4096 Aug 18 14:54 repo-archive
drwxr-xr-x 2  997 gitea 4096 Aug 18 14:54 repo-avatars
drwxr-xr-x 2  997 gitea 4096 Aug 18 14:54 ssh
drwxr-xr-x 3  997 gitea 4096 Aug 18 14:54 tmp
```

Somehow all permissions are set to user 997 (non-existing UID, gitea process is run as 'gitea', uid 1000), and the gitea group has no write permissions on the entire data folder. 

Running `sudo chown -R bitnami:gitea /bitnami/gitea/data` fixes this issue. What causes the permissions of these files to be misconfigured? And why does the service initially work for a while?

**Comment by gongomgra** [comment]
Hi @EniacMlezi,

Thanks for using Bitnami. I'm afraid I haven't been able to reproduce your issue either in Azure or the local OVA machine. Permissions continue being the expected ones after 31 minutes since the machine was launched. I also logged into Gitea web and created a test repository, but the permissions continue being the expected ones.

```
$ uptime
 10:51:32 up 31 min,  1 user,  load average: 0.07, 0.04, 0.14

$ sudo ls -larth /opt/bitnami/gitea/data/*
/opt/bitnami/gitea/data/tmp:
total 12K
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:22 package-upload
drwxr-xr-x  3 gitea   gitea 4.0K Aug 24 10:22 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/git:
total 12K
drwxr-xr-x  3 root    root  4.0K Aug 24 10:22 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..
drwxrwxr-x  3 gitea   root  4.0K Aug 24 10:42 repositories

/opt/bitnami/gitea/data/home:
total 12K
-rw-r--r--  1 gitea   gitea  379 Aug 24 10:22 .gitconfig
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:22 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/repo-avatars:
total 8.0K
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:22 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/repo-archive:
total 8.0K
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:22 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/queues:
total 12K
drwxr-xr-x  3 gitea   gitea 4.0K Aug 24 10:22 .
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:22 common
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/packages:
total 8.0K
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:22 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/avatars:
total 8.0K
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:22 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/attachments:
total 8.0K
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:22 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/jwt:
total 12K
-rw-------  1 gitea   gitea 3.2K Aug 24 10:23 private.pem
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:23 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/indexers:
total 12K
drwx------  3 gitea   gitea 4.0K Aug 24 10:23 .
drwx------  3 gitea   gitea 4.0K Aug 24 10:23 issues.bleve
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/ssh:
total 16K
-rw-------  1 gitea   gitea  725 Aug 24 10:23 gitea.rsa.pub
-rw-------  1 gitea   gitea 3.2K Aug 24 10:23 gitea.rsa
drwxr-xr-x  2 gitea   gitea 4.0K Aug 24 10:23 .
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..

/opt/bitnami/gitea/data/sessions:
total 16K
drwx------  3 gitea   gitea 4.0K Aug 24 10:42 5
drwx------  3 gitea   gitea 4.0K Aug 24 10:42 2
drwxrwxr-x 15 bitnami gitea 4.0K Aug 24 10:42 ..
drwx------  4 gitea   gitea 4.0K Aug 24 10:42 .
```

According to the information you provided, your server is running out of free memory. It shouldn't be related to the permission issues, but can you try a bigger instance just in case?
