### ISSUE TITLE
zerofree utility on bitnami virtual machines

### ISSUE THREAD

**Issue by linuxguist** [bitnami/vms#1102]
### Describe your suggestion as much as you can

Hi Bitnami Support Team,

I noticed that the Bitnami Virtual Machines do not have the zerofree utility installed by default. As you may be aware, this utility helps very much, in clearing unused space with zeros, thereby helping later in compacting / reducing the virtual disk file size and also helps in reducing the exported appliance's .ova file size, as well.

I have created a couple of live cd, with the zerofree utility built in and also shared this news, on a forum post here: https://superuser.com/a/1804786/1526250

Hope, this helps out bitnami vm users as well.

Best Regards,

Nathan S.R.

**Comment by linuxguist** [comment]
That's great ! Thank you very much.

**Comment by jeannette9728miller** [comment]
It’s great to hear that you’ve taken the initiative to create live CDs with the zerofree utility built-in, and sharing your solution with the community. The zerofree utility is indeed a valuable tool for managing disk space in virtual machines by zeroing out unused blocks, which can be particularly useful for compacting virtual disk files and reducing the size of exported .ova files.

Your suggestion for including zerofree in Bitnami Virtual Machines by default could be beneficial for many users. It seems that this issue has been noted and is currently open on the Bitnami GitHub repository. Engaging with the Bitnami community and their support team through the GitHub issue tracker is a good way to bring attention to this feature request. It allows other users to express their interest in having the utility included, which can help prioritize the request for future releases.

Thank you for contributing to the community and for sharing your insights!

**Comment by linuxguist** [comment]
Hi @gongomgra / @jeannette9728miller ,

Feeling inspired / encouraged by @jeannette9728miller comments above, I would like to contribute 3 of my significant GitHub Software Projects, for release of them, as Bitnami VMs / Stacks, for the benefit of the community. 2 of these projects have their download locations, pointing to my Sourceforge Repositories, to overcome GitHub's single file size restrictions, of 100 MB.

I fully authorize bitnami, to integrate them, in the ways, that you package such stuff. In addition, feel free to create more repositories, out of them, for community participation, mostly for enhancements, as per your client needs and feedbacks.

Here are the software repositories ( 1 & 2 below are php-mysql based, 3 is php-postgresql based ) : 

1. https://github.com/linuxguist/Easy-Team-Document-Software-And-Code-Snippets-Storage-for-all-ORGs/tree/main

2. https://github.com/linuxguist/Easy_Database_Forms_For_All

3. https://github.com/linuxguist/Capacity_Planning_And_Management_Software_For_All_Professions/tree/main

Also, Kindly keep this ticket, on-hold, to prevent this ticket from becomming stale and closed. Thanks.

Best Regards,

Nathan S.R.

**Comment by gongomgra** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

**Comment by carrodher** [comment]
Hi, unfortunately, after an internal review and due to other priorities, this solution was not considered for inclusion in the catalog in the short/mid-term.

We apologize for the inconvenience. We will be sure to reconsider it in the future.

Thanks for your suggestion!
