### ISSUE TITLE
[AWS Roundcube] Bitnami by VMware has added a new version to Roundcube packaged by Bitnami on AWS Marketplace

### ISSUE THREAD

**Issue by MAiNPRoToCoL** [bitnami/vms#1105]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic was not useful. Could you please tell us why?

N/A

### Describe your issue as much as you can

I'll get an email:

 Greetings from AWS Marketplace,

Thank you for subscribing to Roundcube packaged by Bitnami.

We are writing to inform you that Bitnami by VMware has added a new version to Roundcube packaged by Bitnami on AWS Marketplace. ...

I ask: 

To get those new updates y'all do on my existing instance, does a sudo apt update upgrade cut it or nah?

Thanks

**Comment by mdhont** [comment]
You need to launch a new instance with the newer version and then migrate your data there. The following guides might be of help:

https://docs.bitnami.com/general/apps/roundcube/administration/
