### ISSUE TITLE
WordPress with NGINX and SSL AWS Console error W3 Cache plugin when activated

### ISSUE THREAD

**Issue by williamgh2019** [bitnami/vms#1106]
### Describe your issue as much as you can

Hi,
I want to know that Bitnami has two version of AWS marketplace and Console AMI. Could you tell me what the difference?

When I use your AWS AMI console and activate W3 Cache it show this error:

![image](https://github.com/bitnami/vms/assets/17005582/18fb65a8-6ea9-4021-9a1d-0fe2b1821d36)

**Comment by gongomgra** [comment]
Hi @williamgh2019,

Thanks for using Bitnami. Can you provide us with more information about the issue? Whats the content of the `view required changes` menu that appears in your screenshot? We are aware of some issues installing W3 Cache plugin on WordPress, although you seems to be facing a different error

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/optimize-bitnami-wordpress/#w3-total-cache-troubleshooting

Can you also run the bndiagnostic tool and share the generated code with us?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by williamgh2019** [comment]
Hi @gongomgra,

I have found solution blog [AWS](https://aws.amazon.com/elasticache/memcached/wordpress-with-memcached/)

You can check section **_Set Configuration Permissions_** and **_Update File Permissions_**

These work for me.
