### ISSUE TITLE
[wordpress-multisite AWS] <504 Gateway Timeout errors Every 2 Days>

### ISSUE THREAD

**Issue by Ham2222** [bitnami/vms#1108]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9fa133b2-d81c-50c1-8b23-260c3e09f067

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1947 1370 97 109 479 288 Swap:
2023 1 2022
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
Press [Enter] to continue:

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-08-22 12:06:00 43 [Warning] Aborted connection 43 to db:
'bitnami_wordpress' user: 'bn_wordpress' host: 'localhost' (Got an error reading
communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Wordpress]

Some files don't have the expected permissions Please check the following guide:

https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

[Apache]
Press [Enter] to continue:

Found recent error or warning messages in the Apache error log.
```
[Tue Aug 22 12:10:17.049612 2023] [core:error] [pid 1699:tid 140398403917568]
[client **ip_address**:53594] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Tue Aug 22 12:10:22.112244 2023] [core:error] [pid 2092:tid 140398655698688]
[client **ip_address**:64456] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Tue Aug 22 12:10:22.995096 2023] [core:error] [pid 2092:tid 140398378739456]
[client **ip_address**:64476] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP
Press [Enter] to continue:
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I Can Not Solve The Issue 

### Describe your issue as much as you can

<504 Gateway Timeout errors Every 2 Days>

I should restart server every cupule dyes

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one.
