### ISSUE TITLE
Bitnami wordpress cloudformation template on s3 access issue

### ISSUE THREAD

**Issue by vinayranjan** [bitnami/vms#1111]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

123455677865444333

### bndiagnostic was not useful. Could you please tell us why?

I didn't find this id

### Describe your issue as much as you can

I am trying to access Quickstart cloudformation template available on S3 but it's giving access deined.

- https://aws-quickstart.s3.us-east-1.amazonaws.com/quickstart-bitnami-wordpress/templates/wordpress.template

**Comment by mdhont** [comment]
Which guide are you following exactly? Could you share the link?

**Comment by vinayranjan** [comment]
@mdhont - I am following this guide - https://aws-quickstart.s3.amazonaws.com/quickstart-bitnami-wordpress/doc/wordpress-high-availability-by-bitnami-on-the-aws-cloud.pdf (As of now this link is not active though it was working 2-3 weeks back)
[wordpress-high-availability-by-bitnami-on-the-aws-cloud.pdf](https://github.com/bitnami/vms/files/12426162/wordpress-high-availability-by-bitnami-on-the-aws-cloud.pdf)

**Comment by mdhont** [comment]
Unfortunately Bitnami does no longer support Multitier deployments for WordPress on AWS.
