### ISSUE TITLE
AWS AMI - Unable to use "User-data" script for SSM-Agent

### ISSUE THREAD

**Issue by Jellis123** [bitnami/vms#1112]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

unable to provide

### bndiagnostic was not useful. Could you please tell us why?

Unable to access Console for instance as SSH is disabled

### Describe your issue as much as you can

I have configured a new Ec2 instance with the AMI (ami-0feeda4e5579cfabf) using a launch-template with an ASG and Load-balancer however when I try to add the user-data as a script to download and start the Amazon-SSM-agent the user-data is overlooked by the instance and it doesn't install it even though in the AWS console I can see that it has been created by terraform as configured. I know the commands work as I have run them in a separately instance with no trouble

Is it possible to use User-data to run commands as part of this AMI?

**Comment by gongomgra** [comment]
Hi @Jellis123,

Thanks for using Bitnami. I'm afraid our images do not include the SSM-Agent service by default. I have just launched a fresh new server and checked the service status (if any) as [described in the official docs (step number 6)](https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-deb.html):

```
bitnami@ip-172-31-46-250:~$ sudo systemctl status amazon-ssm-agent
Unit amazon-ssm-agent.service could not be found.
```

You can launch one of our images, install the SSM-Agent on it and then create your custom image out of it so you can use it as the base image for your deployments.

https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/tkv-create-ami-from-instance.html

Hope it helps!

**Comment by Jellis123** [comment]
Hi,

Thanks for coming back to me!

Does your AMI support post launch scripts in the way Auto Scaling user data does?

**Comment by ShaunDAdams** [comment]
Hi I am also having a similar issue. I would like to use the provided AMI and run a few post launch commands. Ideally we don't want to support a custom image as we could have done that ourselves. The benefit of using bitnami images are massive.

I've set up a launch template using the bitnami wordpress AMI and the actions set in the User data are not being actioned.

**Comment by gongomgra** [comment]
Hi @ShaunDAdams, @Jellis123,

As mentioned previously, I'm afraid we don't include the required package in our images. I will check with the team if we have any plan to add this feature to our images. In the meantime, we recommend you to create your custom AWS image using ours as base image, plus installing the required package.
