### ISSUE TITLE
WordPress with NGINX and SSL on AWS Marketplace vs AWS AMI which one safe to use?

### ISSUE THREAD

**Issue by williamgh2019** [bitnami/vms#1115]
### Describe your issue as much as you can

Hi,
I have found you package both in AWS marketplace and AWS AMI, I still confuse to use it, which one safe to use?

But what I have notice is your AWS AMI is support AWS new instance than marketplace package.

Is it safe to use your package AWS AMI for production?

**Comment by gongomgra** [comment]
Hi @williamgh2019,

Thanks for your interest in Bitnami. Both images in the AWS console and the AWS marketplace are the same. You can use any of them. Regarding the instance types, are you referring to the same `c6a` instance types that you recently [asked for](https://github.com/bitnami/vms/issues/1092)?

**Comment by williamgh2019** [comment]
Exactly @gongomgra but I just wanna confirm from you it safe to use in aws. It also mention in reply here too #1092

**Comment by gongomgra** [comment]
Hi @williamgh2019,

Thanks for your message. I have already replied you in the other thread as well. In our case, both AWS Marketplace and AWS console images are the same, so you can safely use the one from the AWS console with your preferred instance type. We have an internal task to update the available instance types in AWS Marketplace, but we recommend you to use the AWS console's one in the meantime.

I'm also closing this ticket as duplicated. Let's continue the conversation in the other thread.

Hope it helps!
