### ISSUE TITLE
Cannot log into wp-admin 

### ISSUE THREAD

**Issue by jaycova** [bitnami/vms#1116]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f184ac4e-debc-6a0b-42b8-10c071bd7d8f

### bndiagnostic output

  ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Press [Enter] to continue:
Found recent error messages in the MariaDB error log:
```
2023-08-24 15:17:05 3 [Warning] Aborted connection 3 to db: 'bitnami_wordpress' 
user: 'root' host: 'localhost' (Got an error reading communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Aug 24 02:24:39.260689 2023] [proxy_fcgi:error] [pid 40316:tid 
139746021865216] [client **ip_address**:52404] AH01071: Got error 'PHP message: 
PHP Warning: require_once(/bitnami/wordpress/wp-settings.php): Failed to open 
stream: No such file or directory in /bitnami/wordpress/wp-config.php on line 
192PHP message: PHP Fatal error: Uncaught Error: Failed opening required 
'/bitnami/wordpress/wp-settings.php' (include_path='.:/opt/bitnami/php/lib/php') 
in /bitnami/wordpress/wp-config.php:192
 [Thu Aug 24 03:21:13.972762 2023] [authz_core:error] [pid 43495:tid 
Press [Enter] to continue:
139745979901696] [client **ip_address**:40702] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/index.php
 [Thu Aug 24 13:20:15.705881 2023] [authz_core:error] [pid 40316:tid 
139746231682816] [client **ip_address**:51994] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/scripts

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

### bndiagnostic was not useful. Could you please tell us why?

does not seem to be the issue

### Describe your issue as much as you can

I cannot log into wp-admin on my website: https://industry40.jaycocioservices.com. I have logged in through SSH, and I can verify I have the correct password for "user." When I go to wp-admin and use the username and password, it tells me, "ERROR: The username or password you entered is incorrect." 

I cannot use the "forgot password" because the server was not set up to send emails. I have rebooted WordPress and MariaDB and I also did a server reboot. Nothing seems to work.

**Comment by jaycova** [comment]
I recreated the user password with the MD5 generator and I could log in. UGH.

**Comment by Yasin-Ali-Cpuflat** [comment]
> I recreated the user password with the MD5 generator and I could log in. UGH.

how?
