### ISSUE TITLE
ERPNext Vm Upgrade issue

### ISSUE THREAD

**Issue by Ahm4dev** [bitnami/vms#1117]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1e53cfb7-d634-6e7c-ec1b-c46acSe17e93

### bndiagnostic output

Processes: No issues found
Resources: No issues found
Comnectivity: Found possible issues
Apache: Found possible issues
Mariadb: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

IDK

### Describe your issue as much as you can

I am using this package.
https://bitnami.com/stack/erpnext/virtual-machine

when I try to upgrade ERPNext by following this post
https://docs.bitnami.com/virtual-machine/apps/erpnext/administration/upgrade/

I face this message.
`Backup failed for Site erpnext. Database or site_config. json may be corrupted.`

![1](https://github.com/bitnami/vms/assets/99495626/33ff7afc-0efd-4e5b-ba2b-27204dc512ac)

what I did is that
```
source /opt/bitnami/erpnext/venv/bin/activate
cd /opt/bitnami/erpnext/frappe-bench/apps/erpnext
bench update
```

then the message come
I tried that
`bench update --no-backup`

but it wasn't complete, and the database is corrupted !!!

**Comment by gongomgra** [comment]
HI @Ahm4dev,

Thanks for using Bitnami and sorry for the issues you are facing. I'm afraid that seems to be an issue more related to the ERPNext application itself than with our installation. We recommend you to open a new question in the official ERPNExt forums for further help on this

https://discuss.frappe.io/
