### ISSUE TITLE
Tomcat 8.5.92 using by default Java 17 instead of Java 8

### ISSUE THREAD

**Issue by jonintell** [bitnami/vms#1118]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1a6a0784-05e2-ffb0-2085-9e58354d599a

### bndiagnostic output

No issue was found

### bndiagnostic was not useful. Could you please tell us why?

Didn't check compatibility of my app and version

### Describe your issue as much as you can

No issue was found.
I am using tomcat 8.5.92
I want to use Java 8 (java_1.8.0_301-b09), instead by default Java 17 is installed and I didn't find a way of changing the java.
Tomcat 8.5 isn't even valid for java 17 it seems
The following link explain how to change java version but it didn't work since it is for newer versions of tomcat but not for tomcat 8:
https://docs.bitnami.com/aws/infrastructure/tomcat/administration/use-independent-java-tomcat/

My app runs on other servers with the following configurations:
./version.sh
Using CATALINA_BASE:   /usr/share/tomcat8
Using CATALINA_HOME:   /usr/share/tomcat8
Using CATALINA_TMPDIR: /usr/share/tomcat8/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /usr/share/tomcat8/bin/bootstrap.jar:/usr/share/tomcat8/bin/tomcat-juli.jar
Using CATALINA_OPTS:
Server version: Apache Tomcat/8.5.90
Server built:   Jun 2 2023 17:14:04 UTC
Server number:  8.5.90.0
OS Name:        Linux
OS Version:     5.10.0-22-cloud-amd64
Architecture:   amd64
JVM Version:    1.8.0_292-b10
JVM Vendor:     AdoptOpenJDK

Thank you.

**Comment by gongomgra** [comment]
Hi @jonintell,

Thanks for using Bitnami. According to the [official Tomcat docs](https://tomcat.apache.org/whichversion.html), Tomcat 8.5.x supports Java versions 7 and later. That's why our images include Java 17 by default.

![Screenshot 2023-08-29 at 09 52 10](https://github.com/bitnami/vms/assets/6660452/c2b8b468-4d9c-4161-90a8-8c2049433edd)

You can use your custom Java version following the guide you shared. Did you have any issue following the mentioned steps?

**Comment by jonintell** [comment]
Hi, thank you for your answer, indeed I had some issue following the guide I send.
I was able to do the following : Change the JAVA_HOME variable in the /opt/bitnami/tomcat/bin/setenv.sh
Howver, I couldn't  change "JRE_HOME variable in the /opt/bitnami/tomcat/scripts/ctl.sh"
Since I my tomcat folder there is no scripts folder.
SO changing only JAVA_HOME  in setenv.sh didn't change my java version even after restart 
(running java -version was still showing java 17.x.x instead of java 8.x.x)

Where shoud I change JRE_HOME ?
My application is running fine on other servers using java 8.x.x
I even tried to change the java folder in path /opt/bitnami/java to replace it with the java folder of version java_1.8.0_301-b09 but it was still using libraries from java 17 so my application wasn't able to run.

**Comment by gongomgra** [comment]
Hi @jonintell,

Thanks for your message. I was able to update Tomcat's config to use a different Java installation on my server following our guide. You just need to update the `JAVA_HOME` variable in the `/opt/bitnami/tomcat/bin/setenv.sh` file and restart the service for changes to take effect. You can skip the part about the `JRE_HOME` variable in our guide.

In my case, I launched a fresh new server and verified Tomcat was using Java 17 from Bitnami installation

```sh
bitnami@ip-172-31-35-165:~$ which java
/opt/bitnami/java/bin/java
bitnami@ip-172-31-35-165:~$ /opt/bitnami/java/bin/java --version
openjdk 17.0.8 2023-07-18 LTS
OpenJDK Runtime Environment (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM (build 17.0.8+7-LTS, mixed mode, sharing)
```

![Screenshot 2023-09-05 at 12 33 15](https://github.com/bitnami/vms/assets/6660452/f4887ab4-da4f-4796-8bb8-b3c68ab1c5df)

Then I installed Java 11 (latest version available from system repositories, and updated the `setenv.sh` file to point to the new Java installation

```sh
bitnami@ip-172-31-35-165:~$ sudo apt-get update && sudo apt-get install -y openjdk-11-jre
(...)

# Detect new JAVA_HOME
bitnami@ip-172-31-35-165:~$ echo "export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")"
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/

# Update /opt/bitnami/tomcat/bin/setenv.sh file
bitnami@ip-172-31-35-165:~$ head /opt/bitnami/tomcat/bin/setenv.sh
#!/bin/bash
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

# export JAVA_HOME="/opt/bitnami/java"
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export JAVA_OPTS="-Djava.awt.headless=true -XX:+UseG1GC -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Duser.home=/opt/bitnami/tomcat"
export CATALINA_PID="/opt/bitnami/tomcat/temp/catalina.pid"
```

Finally, I restarted the Tomcat service and visited the admin panel again. It now shows Tomcat is running on top of Java 11 from system packages

```sh
bitnami@ip-172-31-35-165:~$ sudo /opt/bitnami/ctlscript.sh restart tomcat
Restarted tomcat
```

![Screenshot 2023-09-05 at 12 44 41](https://github.com/bitnami/vms/assets/6660452/405b81dc-fa28-4dcb-ba55-26fd45fa4058)

Hope it helps!
