### ISSUE TITLE
AWS Wordpress htaccess modifications

### ISSUE THREAD

**Issue by krmtech** [bitnami/vms#1119]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a5d49730-fa67-bb4d-fb76-6e0d36ead6dc

### bndiagnostic output

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 950 517 66 74 366 205 Swap: 
634 38 596
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Aug 27 01:31:54.541393 2023] [autoindex:error] [pid 1010:tid 
140251653682944] [client **ip_address**:59094] AH01276: Cannot serve directory 
/opt/bitnami/wordpress/wp-admin/css/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive, referer: binance.com

### bndiagnostic was not useful. Could you please tell us why?

seems unrelated to file location file permissions

### Describe your issue as much as you can

I am aware that apache excludes access directly to the .htaccess file. I have read the [bitnami document](https://docs.bitnami.com/general/apps/wordpress/administration/use-htaccess/) and as a result I attempted to modify the htaccess configuration file at 

/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf

I made the changes to add expires headers, and after saving the changes, I see an error that the file is write protected.

> Error:         	/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf: open for write: permission denied
> Error:         	File transfer failed

Am I working with the wrong  server file for my instance ?

```
## BEGIN EXPIRES HEADER CACHING ##
  <IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType image/jpg "access 1 year"
  ExpiresByType image/jpeg "access 1 year"
  ExpiresByType image/gif "access 1 year"
  ExpiresByType image/png "access 1 year"
  ExpiresByType image/svg "access 1 year"
  ExpiresByType text/css "access 1 month"
  ExpiresByType application/pdf "access 1 month"
  ExpiresByType application/javascript "access 1 month"
  ExpiresByType application/x-javascript "access 1 month"
  ExpiresByType application/x-shockwave-flash "access 1 month"
  ExpiresByType image/x-icon "access 1 year"
  ExpiresDefault "access 3 days"
  </IfModule>
## END EXPIRES HEADER CACHING ##
```

**Comment by krmtech** [comment]
Which config file should be modified if we wish to add Expires headers to the instance referenced in our OP ?  We have several instances and the paths are different for these older instances

**Comment by mdhont** [comment]
You can add the expire headers to the virtualhost at ` /opt/bitnami/apache/conf/vhosts/wordpress-vhosts.conf `. For the other instances I recommend grepping for the right vhost section:

    egrep -r  'DocumentRoot /opt/bitnami/wordpress' /opt/bitnami/

**Comment by krmtech** [comment]
After resetting the permissions on this new instance, we cannot modify the file `/opt/bitnami/apache/conf/vhosts/wordpress-vhosts.conf` The commands were accepted.  We still see "write permission denied"

```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress

sudo find /opt/bitnami/wordpress/ -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress/ -type f -exec chmod 664 {} \;
sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
```

**Comment by mdhont** [comment]
Are you using sudo?

Could you show the permissions?

    ls -la /opt/bitnami/apache/conf/vhosts/wordpress-vhosts.conf

**Comment by krmtech** [comment]
yes to sudo

```
bitnami@ip-172-***-***-***:~$ ls -la /opt/bitnami/apache/conf/vhosts/wordpress-vhosts.conf
ls: cannot access '/opt/bitnami/apache/conf/vhosts/wordpress-vhosts.conf': No such file or 
directory
```
<img width="607" alt="Screenshot 2023-09-11 at 9 37 44 AM" src="https://github.com/bitnami/vms/assets/20956210/8fc3ff99-eef3-4cad-b535-c4fb04956145">

**Comment by mdhont** [comment]
> bitnami@ip-172-***-***-***:~$ ls -la /opt/bitnami/apache/conf/vhosts/wordpress-vhosts.conf
ls: cannot access '/opt/bitnami/apache/conf/vhosts/wordpress-vhosts.conf': No such file or 
directory

The file seems to be missing. Can you check it?

**Comment by krmtech** [comment]
The file absolutely exists.  I had attached a screenshot of my FTP client that shows the file. I can download it and view it. 

It is baffling.

**Comment by mdhont** [comment]
Can you run the following command?

```
    sudo ls -la /opt/bitnami/apache/conf/vhosts/
```

To check the contents of the vhost folder?

**Comment by krmtech** [comment]
Last login: Mon Sep 11 12:21:13 2023 from 52.95.24.107
bitnami@ip:~$ sudo ls -la /opt/bitnami/apache/conf/vhosts/
total 32
drwxrwxr-x 3 bitnami root 4096 Aug 19 20:03 .
drwxrwxr-x 6 bitnami root 4096 Aug 19 20:03 ..
-rw-rw-r-- 1 bitnami root  161 Jun 27 17:37 00_status-vhost.conf
drwxrwxr-x 2 bitnami root 4096 Aug  4 09:59 htaccess
-rw-r--r-- 1 root    root 2209 Aug 19 20:03 wordpress-https-vhost.conf
-rw-rw-r-- 1 root    root 1230 Aug  4 09:59 wordpress-https-vhost.conf.back.202308192001
-rw-r--r-- 1 root    root 2353 Aug 19 20:03 wordpress-vhost.conf
-rw-rw-r-- 1 root    root 1064 Aug  4 09:59 wordpress-vhost.conf.back.202308192001
bitnami@ip-172-26-0-65:~$

**Comment by mdhont** [comment]
Sorry my mistake the file is called wordpress-vhost.conf. But in any case did you reset the permissions as shown in the guide:

```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress
sudo find TARGET -type d -exec chmod 775 {} \;
sudo find TARGET -type f -exec chmod 664 {} \;
sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
```

**Comment by krmtech** [comment]
This is very literal, so to avoid errors, what is the exact TARGET for our instance in your suggested sudo commands?

**Comment by mdhont** [comment]
Sorry, TARGET is `/opt/bitnami/wordpress/wp-content/`

**Comment by Shepdesign** [comment]
I gained access to the file located in /opt/bitnami/apache/conf/vhosts/htaccess called "wordpress-htaccess.conf" and am thinking of adding this:
`<Directory "/opt/bitnami/wordpress/wp-content/plugins/hide-my-wp">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>`

So that way the plugin has complete access to the htaccess folder. Is this the correct way of doing it?
