### ISSUE TITLE
[WordPress] nginx rewrite not performing the same way in Bitnami. 

### ISSUE THREAD

**Issue by CieRory** [bitnami/vms#112]
Hello!

I'm hitting a roadblock here and any help would be greatly appreciated. 

I have a function in my theme that checks the files being loaded through a function.  I then create a rewrite for said function that is as follows:

`rewrite "wp-content/uploads(\/\d{4}/\d{2}/[A-Za-z0-9_@.\/&+-]+)+\.([A-Za-z0-9_@.\/&+-]+)$" "/index.php?medstaff_acess=$1&file_type=$2" last;`

I then, updated it and moved it over to my local Bitnami instance to test it out before migrating to our Bitnami AWS instance.

    <Directory "C:/Bitnami/wordpress-6.0-0/apps/wordpress/htdocs">
        <IfModule mod_rewrite.c>
             RewriteEngine On
             RewriteCond %{REQUEST_FILENAME} -f
             RewriteRule ^/wp-content/uploads(\/\d{4}/\d{2}/[A-Za-z0-9_@.\/&+-]+)+\.([A-Za-z0-9_@.\/&+-]+)$ /index.php?access=$1&file_type=$2 [QSA,L]
        </IfModule>
    </Directory>

The issue I'm running into now, is that all pages are 404'ing except the home page and all media is also 404ing.  (permalinks flushed)

I put the rewrite inside of the htaccess.conf, at the bottom and on its own (not nested inside of anything).

**Comment by jotamartos** [comment]
Hi @CieRory ,

The code looks good but do not know if it's valid after "translating" the action from NGINX to Apache. I suggest you review the Apache's configuration or ask the WordPress support team to know more about why you are getting those 404 error messages 

https://wordpress.org/support/

**Comment by CieRory** [comment]
Hello @jotamartos !

Question, is running bitnami locally on windows different than the Bitnami stack deployed to AWS?

I'm testing this locally and wondering if that's the issue itself as I've gotten this to work on other local WordPress Apache installs.   (local by flywheel and destktop server).

**Comment by jotamartos** [comment]
>Question, is running bitnami locally on windows different than the Bitnami stack deployed to AWS?

The directory structure is different (for example WordPress' files are stored in different paths: installdir/apps/wordpress/htdocs vs /opt/bitnami/wordpress) and the Apache's conf files are in different paths (installdir/apps/wordpress/conf vs /opt/bitnami/apache2/conf/vhosts).

>I wonder if this would be an issue on a VM

You can try the Virtual Machine locally using VirtualBox to see if your changes work before deploying the instance in the cloud.
