### ISSUE TITLE
Lightsail WordPress site crashed

### ISSUE THREAD

**Issue by pthorup** [bitnami/vms#1122]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Cannot connect to server

### bndiagnostic was not useful. Could you please tell us why?

Could not run

### Describe your issue as much as you can

Hi

Our Lightsail Wordpress site suddenly stopped working. I tried to connect to the instance using SSH (in lightsail account page) but its just giving a blank black window. I also tried via terminal to connect but that too is hanging.

I cannot connect via SFTP or to phpmyadmin which I could some time ago.

Can suggestions what is going on?

**Comment by pthorup** [comment]
We made a new instance with a higher plan and that brought back the site. However, we needed to increase the PHP version so made a new instance and migrated the site there. It kept going to the burstable zone and crushing with a minute. 

We increased the instance plan further so now we have this one:
<img width="92" alt="image" src="https://github.com/bitnami/vms/assets/21015750/760b814a-cf69-4b32-b768-9b9b20db0138">


Here is the code from the bndiagnostic tool output:
c7d3c385-1b30-6f41-1477-e022496215d9

Site doesn't crush so often but every time I do a small change in the admin it crushes (e.g. delete 10 posts or just changing settings in a plugin). I deleted so many unused plugins and temporally revert back to twentytwentyone theme but still crushes.

Any suggestions?

**Comment by pthorup** [comment]
The metrics looks like this if this helps:
<img width="504" alt="image" src="https://github.com/bitnami/vms/assets/21015750/b38fa95c-c58e-4767-8d49-2cb4084bbb63">

**Comment by pthorup** [comment]
I understand this is a free support so I would appreciate any help I can get. I have no technical experience with this but I'll try and sum up and explain as best I can.

When I run `sudo tail -n 100 /opt/bitnami/apache2/logs/error_log`. These are the errors I get:

**The following are the ones came when the site was running but slow and crashing now and then (e.g. optimize images using smush in wordpress)**
[Wed Sep 06 16:37:12.259364 2023] [proxy_fcgi:error] [pid 8371:tid 139633585760000] [client 92.33.141.197:59492] AH01079: failed to make connection to backend: httpd-UDS, referer: https://welum.com/wp-admin/admin.php?page=smush-bulk

[Wed Sep 06 16:37:12.337763 2023] [proxy:error] [pid 8371:tid 139633010439936] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed

[Wed Sep 06 16:37:12.337799 2023] [proxy_fcgi:error] [pid 8371:tid 139633010439936] [client 92.33.141.197:59493] AH01079: failed to make connection to backend: httpd-UDS, referer: https://welum.com/wp-admin/admin.php?page=smush-bulk

[Wed Sep 06 16:37:12.427764 2023] [mpm_event:notice] [pid 7710:tid 139634146888960] AH00491: caught SIGTERM, shutting down[Wed Sep 06 16:40:20.548503 2023] [ssl:warn] [pid 10255:tid 140476555898112] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name

[Wed Sep 06 16:40:20.559076 2023] [ssl:warn] [pid 10256:tid 140476555898112] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name

[Wed Sep 06 16:40:20.561633 2023] [mpm_event:notice] [pid 10256:tid 140476555898112] AH00489: Apache/2.4.57 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations

[Wed Sep 06 16:40:20.561678 2023] [core:notice] [pid 10256:tid 140476555898112] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'

[Wed Sep 06 16:51:18.233223 2023] [proxy_fcgi:error] [pid 10915:tid 140475637827328] (70007)The timeout specified has expired: [client 18.158.50.149:55014] AH01075: Error dispatching request to : (polling)

**The site went completely down after that. Seems there is no connection to the database:**
[Wed Sep 06 18:13:20.629561 2023] [ssl:warn] [pid 785:tid 140595671399680] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name

[Wed Sep 06 18:13:20.642964 2023] [mpm_event:notice] [pid 786:tid 140595671399680] AH00489: Apache/2.4.57 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations

[Wed Sep 06 18:13:20.643003 2023] [core:notice] [pid 786:tid 140595671399680] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'

[Wed Sep 06 18:27:18.729183 2023] [proxy_fcgi:error] [pid 793:tid 140593799816960] (70007)The timeout specified has expired: [client 18.158.50.149:56284] AH01075: Error dispatching request to : (polling)

[Wed Sep 06 18:29:01.395175 2023] [proxy_fcgi:error] [pid 1448:tid 140594957485824] [client 35.227.149.36:45412] AH01067: Failed to read FastCGI header

[Wed Sep 06 18:29:01.397272 2023] [proxy_fcgi:error] [pid 1448:tid 140594957485824] (104)Connection reset by peer: [client 35.227.149.36:45412] AH01075: Error dispatching request to : 

[Wed Sep 06 18:29:01.471202 2023] [proxy:error] [pid 1448:tid 140594747668224] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed

[Wed Sep 06 18:29:01.471234 2023] [proxy_fcgi:error] [pid 1448:tid 140594747668224] [client 34.82.25.226:36588] AH01079: failed to make connection to backend: httpd-UDS

[Wed Sep 06 18:29:04.561146 2023] [mpm_event:notice] [pid 786:tid 140595671399680] AH00491: caught SIGTERM, shutting down

----------------------------------------------------

I'm trying to google and here in closed issues each of those errors but can't get it to come back. 

**When I run `free -m`. This is what I get:**
<img width="449" alt="image" src="https://github.com/bitnami/vms/assets/21015750/b6346822-e0d1-4f8c-93f0-348387272445">

**When I run `df -h`. This is what I get:**
<img width="286" alt="image" src="https://github.com/bitnami/vms/assets/21015750/e2ba2710-f3fc-4bb3-b683-d3b1efc199a2">


**When I run `sudo systemctl status bitnami.service`**
● bitnami.service - LSB: bitnami init script     
Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)     
Active: failed (Result: exit-code) since Thu 2023-09-07 07:24:22 UTC; 21min ago    
Process: 5243 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)      
Tasks: 49 (limit: 4623)     
Memory: 408.1M        
CPU: 2.646s     
CGroup: /system.slice/bitnami.service             
├─688 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)             
├─692 php-fpm: pool www             
├─693 php-fpm: pool www             
├─694 php-fpm: pool www             
├─695 php-fpm: pool www             
├─696 php-fpm: pool www             
├─697 php-fpm: pool www             
├─698 php-fpm: pool www             
├─699 php-fpm: pool www             
├─700 php-fpm: pool www             
├─701 php-fpm: pool www             
├─702 php-fpm: pool www             
├─703 php-fpm: pool www             
├─704 php-fpm: pool www             
├─705 php-fpm: pool www             
├─706 php-fpm: pool www             
├─707 php-fpm: pool www             
├─708 php-fpm: pool www             
├─709 php-fpm: pool www             
├─710 php-fpm: pool www             
├─711 php-fpm: pool www             
├─712 php-fpm: pool www             
├─713 php-fpm: pool www             
├─714 php-fpm: pool www             
├─715 php-fpm: pool www             
├─716 php-fpm: pool www             
├─717 php-fpm: pool www             
├─718 php-fpm: pool www             
├─719 php-fpm: pool www             
├─720 php-fpm: pool www             
├─721 php-fpm: pool www             
├─722 php-fpm: pool www             
├─723 php-fpm: pool www             
├─724 php-fpm: pool www             
├─725 php-fpm: pool www             
├─726 php-fpm: pool www             
├─727 php-fpm: pool www             
├─728 php-fpm: pool www             
├─729 php-fpm: pool www             
├─730 php-fpm: pool www             
├─731 php-fpm: pool www             
└─743 /opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: bitnami.service: Unit process 725 (php-fpm) remains running after unit stopped.
Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: bitnami.service: Unit process 726 (php-fpm) remains running after unit stopped.
Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: bitnami.service: Unit process 727 (php-fpm) remains running after unit stopped.
Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: bitnami.service: Unit process 728 (php-fpm) remains running after unit stopped.
Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: bitnami.service: Unit process 729 (php-fpm) remains running after unit stopped.
Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: bitnami.service: Unit process 730 (php-fpm) remains running after unit stopped.
Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: bitnami.service: Unit process 731 (php-fpm) remains running after unit stopped.
Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: bitnami.service: Unit process 743 (mysqld) remains running after unit stopped.
Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: Failed to start LSB: bitnami init script.Sep 07 07:24:22 ip-172-26-3-72 systemd[1]: bitnami.service: Consumed 2.356s CPU time.



**When I run `sudo journalctl -xe`, this is what I get:**
Sep 07 07:37:46 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:38:27 ip-172-26-3-72 sshd[5411]: Timeout, client not responding from user bitnami 54.239.6.34 port 26335
Sep 07 07:38:27 ip-172-26-3-72 sshd[5404]: pam_unix(sshd:session): session closed for user bitnami
Sep 07 07:38:27 ip-172-26-3-72 systemd[1]: session-38.scope: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit session-38.scope has successfully entered the 'dead' state.
Sep 07 07:38:27 ip-172-26-3-72 systemd-logind[593]: Session 38 logged out. Waiting for processes to exit.
Sep 07 07:38:27 ip-172-26-3-72 systemd-logind[593]: Removed session 38.
░░ Subject: Session 38 has been terminated
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ Documentation: sd-login(3)
░░ 
░░ A session with the ID 38 has been terminated.
Sep 07 07:38:56 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:38:56 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 9290ms.
Sep 07 07:38:56 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:40:06 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:40:06 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 10890ms.
Sep 07 07:40:06 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:41:04 ip-172-26-3-72 sshd[5552]: error: kex_exchange_identification: Connection closed by remote host
Sep 07 07:41:04 ip-172-26-3-72 sshd[5552]: Connection closed by 202.208.150.238 port 57248
Sep 07 07:41:07 ip-172-26-3-72 sshd[5553]: Invalid user vagrant from 202.208.150.238 port 58106
Sep 07 07:41:07 ip-172-26-3-72 sshd[5553]: Connection closed by invalid user vagrant 202.208.150.238 port 58106 [preauth]
Sep 07 07:41:09 ip-172-26-3-72 sshd[5555]: Invalid user test from 202.208.150.238 port 59118
Sep 07 07:41:09 ip-172-26-3-72 sshd[5555]: Connection closed by invalid user test 202.208.150.238 port 59118 [preauth]
Sep 07 07:41:12 ip-172-26-3-72 sshd[5557]: Invalid user user from 202.208.150.238 port 60129
Sep 07 07:41:12 ip-172-26-3-72 sshd[5557]: Connection closed by invalid user user 202.208.150.238 port 60129 [preauth]
Sep 07 07:41:16 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:41:16 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 9870ms.
Sep 07 07:41:16 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:41:17 ip-172-26-3-72 sshd[5559]: Invalid user admin from 202.208.150.238 port 32908
Sep 07 07:41:17 ip-172-26-3-72 sshd[5559]: Connection closed by invalid user admin 202.208.150.238 port 32908 [preauth]
Sep 07 07:41:21 ip-172-26-3-72 sshd[5565]: Invalid user jenkins from 202.208.150.238 port 34947
Sep 07 07:41:22 ip-172-26-3-72 sshd[5565]: Connection closed by invalid user jenkins 202.208.150.238 port 34947 [preauth]
Sep 07 07:41:24 ip-172-26-3-72 sshd[5567]: Invalid user steam from 202.208.150.238 port 36976
Sep 07 07:41:24 ip-172-26-3-72 sshd[5567]: Connection closed by invalid user steam 202.208.150.238 port 36976 [preauth]
Sep 07 07:41:26 ip-172-26-3-72 sshd[5569]: Invalid user odoo from 202.208.150.238 port 37993
Sep 07 07:41:26 ip-172-26-3-72 sshd[5569]: Connection closed by invalid user odoo 202.208.150.238 port 37993 [preauth]
Sep 07 07:41:43 ip-172-26-3-72 sshd[5571]: Invalid user ubuntu from 202.208.150.238 port 45095
Sep 07 07:41:44 ip-172-26-3-72 sshd[5571]: Connection closed by invalid user ubuntu 202.208.150.238 port 45095 [preauth]
Sep 07 07:41:45 ip-172-26-3-72 sshd[5573]: Invalid user ubuntu from 202.208.150.238 port 46111
Sep 07 07:41:45 ip-172-26-3-72 sshd[5573]: Connection closed by invalid user ubuntu 202.208.150.238 port 46111 [preauth]
Sep 07 07:41:52 ip-172-26-3-72 sshd[5575]: Invalid user solr from 202.208.150.238 port 49170
Sep 07 07:41:52 ip-172-26-3-72 sshd[5575]: Connection closed by invalid user solr 202.208.150.238 port 49170 [preauth]
Sep 07 07:42:26 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:42:26 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 9400ms.
Sep 07 07:42:26 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:43:36 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:43:36 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 9970ms.
Sep 07 07:43:36 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:44:46 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:44:46 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 10260ms.
Sep 07 07:44:46 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:45:23 ip-172-26-3-72 sudo[5592]:  bitnami : TTY=pts/0 ; PWD=/home/bitnami ; USER=root ; COMMAND=/usr/bin/systemctl status bitnami.service
Sep 07 07:45:23 ip-172-26-3-72 sudo[5592]: pam_unix(sudo:session): session opened for user root(uid=0) by bitnami(uid=1000)
Sep 07 07:45:23 ip-172-26-3-72 sudo[5592]: pam_unix(sudo:session): session closed for user root
Sep 07 07:45:56 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:45:56 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 9180ms.
Sep 07 07:45:56 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:47:06 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:47:06 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 10550ms.
Sep 07 07:47:06 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:48:16 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:48:16 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 9140ms.
Sep 07 07:48:16 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:49:26 ip-172-26-3-72 dhclient[487]: PRC: Renewing lease on ens5.
Sep 07 07:49:26 ip-172-26-3-72 dhclient[487]: XMT: Renew on ens5, interval 9150ms.
Sep 07 07:49:26 ip-172-26-3-72 dhclient[487]: RCV: Reply message on ens5 from fe80::aa:91ff:fefa:8cc4.
Sep 07 07:50:01 ip-172-26-3-72 sudo[5612]:  bitnami : TTY=pts/0 ; PWD=/home/bitnami ; USER=root ; COMMAND=/usr/bin/journalctl -xe
Sep 07 07:50:01 ip-172-26-3-72 sudo[5612]: pam_unix(sudo:session): session opened for user root(uid=0) by bitnami(uid=1000)


**When I run `sudo gonit status` I get this:**
Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)

**Latest bndiagnostic tool output:**
31d2ba69-2110-b629-d222-833b5e4f917f

Hope this helps.

**Comment by pthorup** [comment]
This is the status so far:
`bitnami@ip-172-26-3-72:~$ sudo /opt/bitnami/ctlscript.sh status
apache not running
mariadb already running
php-fpm already running`

**Comment by mdhont** [comment]
Maybe you have the system version of Apache also installed and running? Can you check the output of this command?

    ps aux | grep apache

**Comment by pthorup** [comment]
We managed to get the site back but then crashed again after doing minor work in WordPress admin. The site is still under maintenance to the public so I can imagine what will have once we have traffic.

I ran `ps aux | grep apache`. This is the output:

`bitnami@ip-172-26-3-72:~$ ps aux | grep apacheroot         799  0.0  0.2  12852  8932 ?        Ss   14:32   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.confdaemon       805  0.0  0.3 2062552 13616 ?       Sl   14:32   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.confdaemon       806  0.0  0.3 2062552 15604 ?       Sl   14:32   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.confdaemon       810  0.0  0.4 2062552 17628 ?       Sl   14:32   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.confdaemon       826  0.0  0.3 2062552 13812 ?       Sl   14:32   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.confdaemon      1329  0.0  0.4 2062552 18108 ?       Sl   14:32   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.confdaemon      1460  0.2  0.4 2062852 17972 ?       Sl   14:32   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.confdaemon      1461  0.7  0.5 2062808 20832 ?       Sl   14:32   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.confbitnami     2003  0.0  0.0   6240   636 pts/0    S+   14:32   0:00 grep apache`

**Comment by pthorup** [comment]
I can't do anything on the WordPress panel without it running into timeout or crashing.

**Comment by pthorup** [comment]
Latest bndiagnostic tool output:
 10b3d101-d3f7-5a14-45fc-2968750706a8

**Comment by pthorup** [comment]
I've now upgraded again the plan to 8 GB ram. The site still crashes quite easily. Seems the something is consuming memory on and off.

**Comment by mdhont** [comment]
You can disable the plugins from the command line:

    sudo wp plugin deactivate --all

**Comment by topithost** [comment]
I am having the exact same issue and tried everything, but no luck. 
My server spec is : 8 GB RAM, 2 vCPUs, 160 GB SSD

**Comment by mdhont** [comment]
@topithost, could you create a new issue? Many times these issues do not have a different cause.
