### ISSUE TITLE
Unable to open wp admin[<application>] <title>

### ISSUE THREAD

**Issue by desca24** [bitnami/vms#1124]
### Describe your issue as much as you can

unable to login to wp admin

<img width="957" alt="Screenshot 2023-08-29 185036" src="https://github.com/bitnami/vms/assets/143508051/8f4875a6-6318-4cb0-9f34-f6d356c8efc7">

**Comment by desca24** [comment]
<img width="960" alt="Screenshot 2023-08-29 220312" src="https://github.com/bitnami/vms/assets/143508051/ad01fcd3-afac-4ab7-a5fc-aedc61faeeea">

**Comment by mdhont** [comment]
Is this a fresh OVA that didn't work at first boot, or an older one that suddenly stopped working?

**Comment by desca24** [comment]
hi i create a new one but it also get rejected
<img width="960" alt="image" src="https://github.com/bitnami/vms/assets/143508051/34f5516f-09c8-4b75-ad04-6411c789d398">

**Comment by mdhont** [comment]
Which version of Virtualbox are you using? And on which platform?
