### ISSUE TITLE
[WordPress] Need Assistance Upgrading Wordpress by Bitnami in AWS 

### ISSUE THREAD

**Issue by MPEP103** [bitnami/vms#1125]
### Describe your issue as much as you can

We need to update our subscription to Wordpress packaged by Bitnami in AWS. However we are unsure if we will need to create a new instance in EC2 to launch our website. Currently our website is done as a result. I would like step by step instructions on how to update the Wordpress subscription by Bitnami in AWS, as well as any information on what may happen after this. Would we need to re-import all content in wordpress? do we have to re-map our website in EC2?

**Comment by williamgh2019** [comment]
Can you explain more about your case? if you are currently using bitnami why need to update to new instance? or just want to update bitnami version? it can be done in Linux update.

**Comment by jotamartos** [comment]
Hi, 

If you need to upgrade all components included in the server (Apache, PHP, MariaDB, ...), you can launch a new instance and migrate the data from the current instance to the new one 

https://docs.bitnami.com/general/how-to/migrate-wordpress/

Please remember to update your DNS records (if you use a domain to access your site) and copy/generate the SSL certificates.

**Comment by mbisque** [comment]
> If you need to upgrade all components included in the server (Apache, PHP, MariaDB, ...), you can launch a new instance and migrate the data from the current instance to the new one

Is there anyway to update "just" PHP for a given AWS bitnami instance?

**Comment by jotamartos** [comment]
>Is there anyway to update "just" PHP for a given AWS bitnami wordpress instance?
>Or as the post above suggests, can a bitnami stack (now?) be updated via Linux update?

No, you can't. We do not use install/configure the components using system's packages. We build the components from scratch and configure them using our own scripts.

>In my case, migrating to a new instance is a fairly major project (mostly because of the amount of data).

The WordPress migration plugin or any related one should take care of all that data.
