### ISSUE TITLE
[WordPress] Site keeps going down

### ISSUE THREAD

**Issue by Tidal-IT** [bitnami/vms#1127]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

816da7d2-eb8c-16a6-8e9c-b96f8de23e1c

### bndiagnostic was not useful. Could you please tell us why?

No. Not clear. 

### Describe your issue as much as you can

My site keeps going down. Can you help me understand how to fix this please? 
Here's the bndiagnostic tool result. Thank you in advance, 

[Fri Sep 01 07:01:48.265222 2023] [proxy_fcgi:error] [pid 465836:tid
140375662470912] [client **ip_address**:21207] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown                                                                                                                                                                             
on line 0', referer:
https://mysite.com/wp-admin/post.php?post=31&action=elementor
 [Fri Sep 01 07:01:51.235729 2023] [proxy_fcgi:error] [pid 465836:tid
140375704434432] [client **ip_address**:21207] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown                                                                                                                                                                             
on line 0', referer:
https://mysitecom/wp-admin/post.php?post=31&action=elementor
 [Fri Sep 01 07:07:15.978264 2023] [proxy_fcgi:error] [pid 465542:tid
Press [Enter] to continue:
140375998048000] (70007)The timeout specified has expired: [client
**ip_address**:20764] AH01075: Error dispatching request to : (polling),
referer: https://mysite.com/wp-admin/post.php?post=31&action=elementor

![image](https://github.com/bitnami/vms/assets/138704452/d1cf59d1-7e36-42a2-8593-3708ecac6182)

**Comment by jotamartos** [comment]
Please take a look at this other post where you can find useful information regarding performance issues 

https://github.com/bitnami/vms/issues/27#issuecomment-1143985862
