### ISSUE TITLE
[<Wordpress>] <Manually installing a theme broke my site>

### ISSUE THREAD

**Issue by mickhowarth** [bitnami/vms#1128]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bcb9d3df-e6cc-eede-5c19-0995a6cfae6e

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Nginx: Found possible issues
    ✓ Php: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ? Wordpress: Found possible issues
 

 
[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2023/08/31 14:43:03 [error] 733#733: *229280 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "POST /wp-plain.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "mywebsite.co.uk", 
referrer: "www.google.com"
Press [Enter] to continue:
 2023/08/31 14:43:03 [error] 733#733: *229280 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET /ycyaibxt.php?Fox=d3wL7 HTTP/1.1", 
upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"mywebsite.co.uk", referrer: "www.google.com"
 2023/08/31 14:43:03 [error] 733#733: *229278 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET /wp-content/themes/seotheme/db.php?u 
HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"mywebsite.co.uk", referrer: "www.google.com"

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
Press [Enter] to continue:

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-09-01 15:42:49 0 [ERROR] Aborting

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Wordpress]

Found recent WordPress plugin related error messages in the Nginx error log.
```
2023/08/31 12:07:01 [error] 733#733: *229138 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET 
/wp-content/plugins/envato-market/inc/class-envato-market-api.php HTTP/1.1", 
upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"mywebsite.co.uk", referrer: 
Press [Enter] to continue:
"http://mywebsite.co.uk/wp-content/plugins/envato-market/inc/class-envato-marke
t-api.php"

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Esentially tells me to look at logs, but logs not really helpful

### Describe your issue as much as you can

I manually installed a Wordpress theme purchased from Themeforrest - I copied the theme file into the WP Themes directory and enabled it within Wordpress, but it seemed to immediately break my website.

Rebooting my instance brought the site back up and gave me enough time to switch to a working theme - I then deleted the offending theme's files manually from the same folder which just seems to have totally killed my website.

I have a database backup from an older version of my site (it's seldomly updated so regular updated haven't generally been required), however, simply starting up a new instance with an up-to-date Bitnami stack, then trying to restore from my backup is proving just as difficult, as the backup was taken when the site was running on an a previous version of PHP.  My restore backup mod (https://docs.jetbackup.com/) gives me an error telling me that the version of PHP my backup file was taken on doesn't match the current PHP version, so refuses to restore my site.

I've also been trying to restore an older imaged version of my site and then updating just PHP in the bitnami stack then taking a backup, but it's been an absolute pig even update the PHP on an older image of my site. 

I've literally spent all day on it multiple attempts and constant faliures, I'm at a loss now, so I've restarted my original broken instance and run the bitnami diagnostic tool. Unfortunately it's showing me far too much than I have experience fixing and I'm struggling here.

I'm okay with Linux CLI, but I'm at a loss here, so I hope you can point me in the right direction.
----
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:
bcb9d3df-e6cc-eede-5c19-0995a6cfae6e

**Comment by gongomgra** [comment]
Hi @mickhowarth,

Thanks for using Bitnami. I checked your bnsupport bundle and I see that there seems to be an issue with your database initialization

```
2023-09-01 15:42:48 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2023-09-01 15:42:48 0 [Note] InnoDB: Using transactional memory
2023-09-01 15:42:48 0 [Note] InnoDB: Number of pools: 1
2023-09-01 15:42:48 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2023-09-01 15:42:48 0 [Note] InnoDB: Using Linux native AIO
2023-09-01 15:42:48 0 [Note] InnoDB: Initializing buffer pool, total size = 268435456, chunk size = 134217728
2023-09-01 15:42:48 0 [Note] InnoDB: Completed initialization of buffer pool
2023-09-01 15:42:48 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=19672995018,19672995018
2023-09-01 15:42:48 0 [ERROR] InnoDB: Malformed log record; set innodb_force_recovery=1 to ignore.
2023-09-01 15:42:48 0 [Note] InnoDB: Dump from the start of the mini-transaction (LSN=19672995018) to 100 bytes after the record:
 len 124; hex 34373862323438343061223b613a333a7b733a383a227363686564756c65223b733a363a22686f75726c79223b733a343a2261726773223b613a303a7b7d733a383a22696e74657276616c223b693a333630303b7d7d7d693a313639303832373932333b613a313a7b733a32313a22776f726466656e63655f6c735f; asc 478b24840a";a:3:{s:8:"schedule";s:6:"hourly";s:4:"args";a:0:{}s:8:"interval";i:3600;}}}i:1690827923;a:1:{s:21:"wordfence_ls_;
2023-09-01 15:42:48 0 [Warning] InnoDB: Log scan aborted at LSN 19673056768
2023-09-01 15:42:48 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2023-09-01 15:42:48 0 [Note] InnoDB: Starting shutdown...
2023-09-01 15:42:49 0 [ERROR] Plugin 'InnoDB' init function returned error.
2023-09-01 15:42:49 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2023-09-01 15:42:49 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-09-01 15:42:49 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2023-09-01 15:42:49 0 [ERROR] Aborting
```

Did you modify anything in its configuration before getting these errors? Apart from that, I'm afraid we can't provide support for paid plugins or themes, you may need to contact the theme developers for further help on how to install/run it on top of WordPress.
