### ISSUE TITLE
[LAMP] Can't install postfix

### ISSUE THREAD

**Issue by furballproductionsinc** [bitnami/vms#1131]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

doesn't work, won't run

### bndiagnostic output

Not very happy with this package. It works as configured, but very hard to change things.

### bndiagnostic was not useful. Could you please tell us why?

it doesn't work, won't run

### Describe your issue as much as you can

sudo apt-get -y install postfix

Doesn't work, it hangs up the terminal when it displays the configuration menus.

Do you have a recommendation for how to do this? I need a mail server running on this system.

**Comment by jotamartos** [comment]
Just tried to reproduce the issue with a fresh instance and couldn't do so. The menu works properly and I can configure Postfix without problems 

![Screenshot 2023-09-04 at 11 46 41](https://github.com/bitnami/vms/assets/8791635/c7ef8d4a-a04c-40e1-a058-a6929c02cf47)

Please try using another connection method (a different SSH client).

**Comment by furballproductionsinc** [comment]
Hello Juan, thank you for your message. It is the menu itself that didn’t work on my instance. This picture you’re showing me, is exactly what didn’t work.

This type of screen (I don’t know what it is, some kind of termcap or something?) is ubiquitous in the installations and setups, and every other one worked on my instance. Several of the applications I had to install had menus just like this one, and they all worked.

The Postfix menu, did not work on my instance. Specifically, it would not let me push the “Enter” key. The up/down arrow keys worked, but not the Enter key, therefore I could not enter any choices, and therefore the product would not install.

I don’t think it’s my Putty setup, since it worked fine with every other app/install. Is there something else I should check? Thank you - Brian

This e-mail was sent from a secure system by Furball Productions Inc. If you are not the designated recipient or you believe you have received this e-mail in error, please contact ***@***.******@***.***>

**Comment by jotamartos** [comment]
Found multiple similar issues, can you take a look at them?

https://github.com/archivematica/Issues/issues/470
https://askubuntu.com/questions/133263/after-installing-postfix-why-doesnt-it-pop-up-the-configuration-interface

Please note this is not related to the Bitnami's configuration but your client.

**Comment by furballproductionsinc** [comment]
Thank you Juan! The first link you provided is exactly the symptom I encountered. I think I did try the tab, but I’ll go back and try it again.

Thank you so much for the support, it’s greatly appreciated. The Bitnami AMI is the best of the ones I’ve tried so far, I tried Suse on an EC2 and it completely clobbered itself after about 3 minutes, the instructions were wrong and Suse itself picked up the problem in its package manager and then proceeded to render my instance into an unrecoverable state. But Bitnami works pretty good, the major problem I ran into is that once the CDN was connected the IP’s no longer matched and therefore I couldn’t verify any certificates lol 😊

I had to get “some kind of mail” working quickly for testing, so I just installed the old style Unix mail, it looks like it works okay so far. I’m negotiating with Amazon to open up port 25 so we can test it.

So you’re aware, I’ll probably be contacting you for some support in the future. We have an app called “Indie Heaven”, it’s not a “vanilla” implementation, even though we try to stay as close as possible. The app is for the entertainment business, it handles record companies, and so far our customers have been small independent record labels (hence the name), but now we have a customer that wants 1000 artist web sites with 1000 simultaneous streams from each, so we have to bring it into the Cloud.

We have some interns that have been up in the cloud for months already, but this job is too big for them. So I’m getting involved, and the first part of the effort was just to see how hard it would be to move the entire app into a VM and connect it to e-mail, push messaging, and the various streaming features.

Your documentation is pretty accurate, if perhaps a bit sparse. I had to do some research on the net to raise the instance properly. However overall it works great so far, the site is running well enough for a customer demo, which was the first milestone. So far so good. There’s a lot of connectivity in the app though, and most of it has to do with Amazon’s various gateways. The “virtual private cloud” causes some problems for our app, relative a local data center.

Do you happen to have a cPanel available? And if so, will it integrate with Amazon, or is it just for subdomains? One of the very nice things we can do in the data center version is raise a new web site from scratch in under 3 minutes, and then administer/configure it from any other site. We’d like to be able to do that same thing in AWS, however the security implementation makes that quite difficult. We’re looking into Terraform as a possible solution.

Another quick question, if I may – this Bitnami instance we have is on LightSail, and I’m not sure exactly what that is, the LightSail instance doesn’t show up in my EC2 panel so it’s somehow managed differently. My question is, if I wanted this exact same stack in an EC2 instance, do you have that, and what should I be looking for in the AMI list? What we’d like to do is separate the database and put it elsewhere in the cloud, that’s the next step for us, because we have multiple sites that share the same database. So I was thinking, let’s spin up an EC2 and then try to connect to it from inside this working LightSail instance, and then try to get both instances running off the same database. (We can’t force our customers to choose one or the other, they’ll pick whichever one works best for them, so we’d like to have both working transparently side by side).

Thank you again for your help Juan, I’ll get up on AWS and try the tab key and see if it works. - Brian

This e-mail was sent from a secure system by Furball Productions Inc. If you are not the designated recipient or you believe you have received this e-mail in error, please contact ***@***.******@***.***>

**Comment by jotamartos** [comment]
>Do you happen to have a cPanel available?

No, we don't. All changes you need/want to perform need to be applied using the command line

>the LightSail instance doesn’t show up in my EC2 panel so it’s somehow managed differently.

Correct! Lightsail is a different platform and that's why those instances are not listed in the EC2 panel. 

>if I wanted this exact same stack in an EC2 instance, do you have that, and what should I be looking for in the AMI list?

We offer the LAMP solution in the AWS Marketplace. You can launch them by using any of the options listed here

https://bitnami.com/stack/lamp/cloud/aws

>What we’d like to do is separate the database and put it elsewhere in the cloud

Of course! You can launch any of the database solutions that Bitnami offers and connect your application with that external database. If you want to disable the database that comes with the LAMP instance (if you are not going to use it again), please contact us and we will help you disable it.
