### ISSUE TITLE
Bitnami virtual machine image mariadb root password access denied

### ISSUE THREAD

**Issue by viktor94marinov** [bitnami/vms#1133]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

none

### bndiagnostic output

none

### bndiagnostic was not useful. Could you please tell us why?

none

### Describe your issue as much as you can

Hello Team,

I have downloaded this image from bitnami https://bitnami.com/stack/mediawiki/virtual-machine
i want to install the mediawiki. Following this procedure https://www.mediawiki.org/wiki/Manual:Running_MediaWiki_on_Debian_or_Ubuntu

I have installed apache2 configured port 8080 started the service.
Installed MariaDB and then i run mysql_secure_installation on the first question where it says "In order to log into MariaDB to secure it, we'll need the current password for the root user. If you've just installed MariaDB, and haven't set the root password yet, you should just press enter here."

"Enter current password for root (enter for none): "

When i press enter it throws error access denied for my user account and i am logged in with rood error 1045.

I tried with the password that it coming from the this article here
https://docs.bitnami.com/virtual-machine/faq/get-started/find-credentials/

it says that the password match have not been found in DB.

I have tried to type the root password, again access Denied.

Is there something i am missing or i need to configure before that?

The commands i used:

apt install mariadb-server mariadb-client -y
/etc/mysql/mariadb.conf.d/50-server.cnf  changed port to 3307
systemctl restart mariadb.service && systemctl enable mariadb.service

mysql_secure_installation

Regards,
Viktor Marinov

**Comment by gongomgra** [comment]
Hi @viktor94marinov,

Thanks for using Bitnami. Our virtual-machines already include the related applications installed and configured to be automatically run on first run. You don't need to manually install MediaWiki on that virtual-machine, it already includes everything required to easily use it. We recommend you to launch a fresh new image and to check the guide linked below on how to get started with our MediaWiki virtual-machine solution

https://docs.bitnami.com/virtual-machine/apps/mediawiki/get-started/first-steps/

Hope it helps!

**Comment by gongomgra** [comment]
Hi @viktor94marinov,

Thanks for your message. I hope the documentation helps you to get started. I'm closing this ticket as requested.
