### ISSUE TITLE
moodle lms

### ISSUE THREAD

**Issue by YafaShechter** [bitnami/vms#1135]
### Describe your issue as much as you can

 i use the bitnami/moodle:latest image with docker-compose for deploy moodle.
i want to change the languge to hebrew.
i download the folder from the link:  https://download.moodle.org/langpack/4.2/  and unzip the folder into: /bitnami/moodledata/lang/
but i get error: 
Your server does not seem to fully support the following languages:
                                                                                                                                                                                                  עברית ‎(he)‎
Instead, the global locale (en_AU.UTF-8) will be used to format certain strings such as dates or numbers.

**Comment by gongomgra** [comment]
Hi @YafaShechter,

Thanks for your interest in using Bitnami. Please notice this is the forum related to cloud images and virtual machines, while you are having issues with one of our container solutions. We recommend you to open your question in our [github.com/bitnami/containers](https://github.com/bitnami/containers/issues) forum instead.

Apart from the above, I found a related documentation in our [github.com/bitnami/containers/moodle](https://moodle.org/mod/forum/discuss.php?d=450114) readme file that may be of help.

I'm closing this ticket as part of this message.

Hope it helps!
