### ISSUE TITLE
[Wordpress] Lightsail instance keeps going down

### ISSUE THREAD

**Issue by piyushd1** [bitnami/vms#1136]
### Platform

AWS Lightsail

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8e5a7692-0032-80e0-d701-d61b39852407

### bndiagnostic output

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides were not very helpful

### Describe your issue as much as you can

I installed a caching plugin (W3 Total cache) in my wordpress site, and setup Cloudflare cdn service. The website started crashing there after, the instance would go down intermittently). So I removed that plugin and installed another plugin (Litespeed cache plugin) but again the instance started going down. 
There are other errors as per the diagnostics report that I would like to fix as well

**Comment by jotamartos** [comment]
Could you please take a look at this other support ticket where we explain what to check when running into performance issues? 

https://github.com/bitnami/vms/issues/27#issuecomment-1143985862

Thanks
