### ISSUE TITLE
Apache not starting 

### ISSUE THREAD

**Issue by mazambadar** [bitnami/vms#1138]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

59c87b11-bb1a-2a2c-e7f7-d77450114209

### bndiagnostic output

I have tried all options but none is working and still can not start apache. Here is outcome. 

Please note that my ports are already open and working fine but still getting this error. 

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ✓ Apache: No issues found
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

### bndiagnostic was not useful. Could you please tell us why?

It did not work and still apache server is down 

### Describe your issue as much as you can

I did not update anything and apache server went down and I tried every option but none worked so far. There is no any change in the AWS lightsail ports and ports 22, 80 and 443 are open for remote access.

**Comment by gongomgra** [comment]
Hi @mazambadar,

Thanks for using Bitnami. I have checked the content of your bndiagnostic bundle and I found the next error message in your Apache logs related to WordPress that seems to be related to a plugin. Can you check it?

```
[Wed Sep 06 22:26:41.243973 2023] [proxy_fcgi:error] [pid 18812:tid 140638821504768] [client CLIENT_IP_ADDRESS:51786] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-content/plugins/better-wp-security/core/modules/ssl/class-itsec-ssl.php on line 81'
```

Apart from that, I visited your website at `www.pets_YOUR_DOMAIN_ouse.co.uk` and the website worked fine for me. Did you manage to fix your issue?

**Comment by mazambadar** [comment]
Yes, I managed to sort this out. Thank you for your help.
