### ISSUE TITLE
[Liferay] Would it be possible to provide the Liferay V7.3 —v7.4 is too experimental/unstable

### ISSUE THREAD

**Issue by Openskies** [bitnami/vms#114]
### Describe your suggestion as much as you can

Liferay 7.4.3 is too experimental to do anything with.

Is it possible that Bitnami might consider listing the version Liferay 7.3 GA10 (I think GA 10 was the last 7.3 version)?

In the dropdown list of available versions, the only ones listed are for version 7.4.3.

Thanks for all the great work.

Nick

**Comment by mdhont** [comment]
Unfortunately it's not possible. We release the latest versions of applications when they are marked as stable by the developers.

**Comment by Openskies** [comment]
Okay, thanks.
Best Wishes, Nick
