### ISSUE TITLE
[MERN] can't allow cors headers for nodejs 

### ISSUE THREAD

**Issue by ReemMahm0ud** [bitnami/vms#1140]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d672519d-d932-6eae-3c31-1d3e2f161f67

### bndiagnostic output

===== Begin of bndiagnostic tool output =====    
 ? Resources: Found possible issues    
? Connectivity: Found possible issues    
? Processes: Found possible issues    
? Apache: Found possible issues  
[Resources]
Your instance has little available RAM memory.```               total        used        free      shared  buff/cache   availableMem:             950         304          62           0         584         499Swap:            634          79         555```
You could try to increase your instance's memory. Please check your cloud provider's documentation for more information.

[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the following guide to open server ports for remote access:
https://docs.bitnami.com/general/faq/administration/use-firewall/
[Processes]
One or more component's processes are not running:
```
apache not running
```
You can try to restart the process with the following command:     $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME
[Apache]
Found recent error or warning messages in the Apache error log.```[Thu Sep 07 13:06:10.041309 2023] [ssl:error] [pid 502113:tid 140399324568832] SSL Library Error: error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error (Type=PKCS8_PRIV_KEY_INFO)

[Thu Sep 07 13:06:10.041313 2023] [ssl:emerg] [pid 502113:tid 140399324568832] AH02312: Fatal error initialising mod_ssl, exiting.
[Thu Sep 07 13:06:10.041317 2023] [ssl:emerg] [pid 502113:tid 140399324568832] AH02564: Failed to configure encrypted (?) private key timesheet.3f.com:443:0, check /opt/bitnami/apache/conf/timesheet.3f.com.crt

### bndiagnostic was not useful. Could you please tell us why?

the suggested guids are not relate it to my issue

### Describe your issue as much as you can

hello,

i deployed my MERN stack on amazon lightsail bitnami and i made to virtual host one for  backend nodejs and the other for frontend reactjs and i added the cors middleware  in my nodejs and it works fine on another host called render.com but on lightsail bitnami, i have problem with POST request, every time i try to upload a file with POST request is says cors header is missing  and the other requests like GET it fails in the middle but not every time and it says proxy error.
i added all the headers in vhost.conf and in bitnami.conf but after i edited them the website stopped and it's not working anymore.

so how can i fix this issue ?

thanks in advance,

**Comment by ReemMahm0ud** [comment]
hello @gongomgra,

are you going to help me with my issue ?

thanks in advance,

**Comment by gongomgra** [comment]
Hi @ReemMahm0ud,

Thanks for using Bitnami. We highly recommend you to create a custom vhost configuration for your application and to add the required CORS configuration into the specific vhosts files for it. You can find more information on how to add a custom application in the guide linked below.

https://docs.bitnami.com/virtual-machine/infrastructure/lamp/configuration/configure-custom-application/

Also remember to restart the Apache server once you have updated the configuration for changes to take effect.
