### ISSUE TITLE
elastisearch - bitnami image issue

### ISSUE THREAD

**Issue by KarthikShantharam** [bitnami/vms#1141]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

na

### bndiagnostic output

https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch/#installing-the-chart

### bndiagnostic was not useful. Could you please tell us why?

Can't find anything related to bitnami elasticsearch 

### Describe your issue as much as you can

Hi,

I am having issue in building or deploying below image in Openshift Container using bitnami helm charts 
https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch/#installing-the-chart

image: 
1. https://hub.docker.com/layers/bitnami/elasticsearch/7.17.9/images/sha256-d80cf5021846f00804fb3a2a97a3b67a61d4611ee96e9c1af4c516cf96015bbb?context=explore
2. https://hub.docker.com/layers/bitnami/elasticsearch/7.17.9-debian-11-r30/images/sha256-d80cf5021846f00804fb3a2a97a3b67a61d4611ee96e9c1af4c516cf96015bbb?context=explore

Build failure
11:53:44  process failed to start with error: fork/exec /bin/sh: exec format errorprocess exited with error: exec: not startedsubprocess exited with status 1

POD initialization failure error
exec /opt/bitnami/scripts/elasticsearch/entrypoint.sh: exec format error

-Thanks

**Comment by gongomgra** [comment]
Hi @KarthikShantharam,

Thanks for using Bitnami. Unfortunately, this is the community forum for our cloud images and virtual machines. Please open a new issue in our [charts repository](https://github.com/bitnami/charts/issues).

Apart from above, I think that you are running the Elasticsearch image in a non-supported architecture. Maybe the version you are trying to use doesn't support ARM? Please open a new question providing as much details as possible in the charts repo for further help on this.

Hope it helps!
