### ISSUE TITLE
AWS LoadBalancer + Bitnami Wordpress. Losing LoadBalancer SSL

### ISSUE THREAD

**Issue by nmandri-wipass** [bitnami/vms#1142]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

none

### bndiagnostic was not useful. Could you please tell us why?

Nothing returned

### Describe your issue as much as you can

Apache: LoadBalancer works perfectly with ec2 Apache instance where bitnami is running but it loses SSL.

**Comment by gongomgra** [comment]
Hi @nmandri-wipass,

Thanks for using Bitnami. Could you provide us with more details about your issue? We have a related guide on how to configure Elastic Load Balancer with our images that I think may be of help.

https://docs.bitnami.com/aws/how-to/configure-elb-ssl-aws/

**Comment by nmandri-wipass** [comment]
Hello!

Thanks for your reply. Could we schedule a quick call for 2h since now? 19h
spanish time. Because I followed everythin and with correct ssl certificate
in load balancer when it shows the wordpress site, it changes to
certificate valid but says site insecure.

Thank you!

**Comment by nmandri-wipass** [comment]
Hello Gonzalo,

i have tried it another time and with diagnostic tool I get:

[Tue Sep 12 11:39:27.447515 2023] [proxy_fcgi:error] [pid 55837:tid

139836400654080] [client **ip_address**:10514] AH01071: Got error 'PHP
message:

PHP Warning: Undefined array key "HTTP_X_FORWARDED_PROTO" in

/bitnami/wordpress/wp-config.php on line 170'

 [Tue Sep 12 11:39:35.631141 2023] [proxy_fcgi:error] [pid 55837:tid

139836375475968] [client **ip_address**:49404] AH01071: Got error 'PHP
message:

PHP Warning: Undefined array key "HTTP_X_FORWARDED_PROTO" in

/bitnami/wordpress/wp-config.php on line 170'

 [Tue Sep 12 11:39:57.484161 2023] [proxy_fcgi:error] [pid 58552:tid

140236141385472] [client **ip_address**:14254] AH01071: Got error 'PHP
message:

PHP Warning: Undefined array key "HTTP_X_FORWARDED_PROTO" in

/bitnami/wordpress/wp-config.php on line 170'


*THE CODE SNIPPET*


define('FORCE_SSL_ADMIN', true);

if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
$_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https'){

 $_SERVER['HTTPS']='on';

}



if ( defined( 'WP_CLI' ) ) {

$_SERVER['HTTP_HOST'] = '127.0.0.1';

}


define( 'WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/' );

define( 'WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/' );

define( 'WP_AUTO_UPDATE_CORE', 'minor' );

/* That's all, stop editing! Happy publishing. */


My ticket ID : 7a6531b4-c387-447e-8333-6302979d1662

Hope you can help us with this.

Regards,

*Nil Mandri Berenguer*

**Comment by mdhont** [comment]
Could you share the code id at the end of the bndiagnostic output?
