### ISSUE TITLE
Question regarding bitnami Mediawiki Image

### ISSUE THREAD

**Issue by viktor94marinov** [bitnami/vms#1143]
### Describe your issue as much as you can

Hello Team,

The questions refer to the Bitnami image for Mediawiki, which has everything in order to run the mediawiki from the get-go.
https://bitnami.com/stack/mediawiki/virtual-machine

However, after i read carefully is article i want to try to configure it using LDAP and SSO, so i will need to join the linux machine to the AD and after that i shall continue using this article? 
https://www.mediawiki.org/wiki/Manual:Active_Directory_Integration

The steps where it shows i need to install mediawiki, i assume i need to skip this step, and just proceed with the rest of the steps.

Also, the provided Extensions, when i click on each one it shows me different version, should i use this link https://extdist.wmflabs.org/dist/extensions/

to make sure all extensions i download for the LDAP and SSO to be exactly the same for example 1.39? Does it matter if the version of the extensions for each one differs from one to another?

Those are my questions and concerns.

Regards,
Viktor Marinov

**Comment by gongomgra** [comment]
Hi @viktor94marinov,

Thanks for your message. Yes, you should skip the steps for installing MediaWiki as it is already installed and configured in our images to an starting point. You would have to follow the rest of the steps in the official docs. For questions on specific plugins versions and its related configuration, we highly recommend you to ask the upstream developers in the official MediaWiki forums, where other developers with more experience may help you.

https://www.mediawiki.org/wiki/Project:Support_desk
