### ISSUE TITLE
I got:  Hmmm… can't reach this page problem with my wordpress website . 

### ISSUE THREAD

**Issue by Yasin-Ali-Cpuflat** [bitnami/vms#1144]
### Describe your issue as much as you can

hi 
am using wordpress with google cloud . and two days ago my website stop from working , in first day i was getting "There has been a critical error on this website"  error . after one day i start to get two problem . in "https" am getting "Hmmm… can't reach this page" error . but in "http" am getting  Apache2 Debian Default Page . 
two days ago i was getting "There has been a critical error on this website" in "htttp" and "https" togather .

its not from browser or pc proxy cause i try . and visite the website from another devices 
i need help please

**Comment by gongomgra** [comment]
Hi @Yasin-Ali-Cpuflat,

Thanks for using Bitnami. If you are seeing the Apache2 Debian default file, it means you have installed the Apache server from system repositories and you are not using the server under the Bitnami installation. Please stop and disable the system service to continue using our Apache server (you may need to restart our service as well).

Regarding the WordPress errors, please run the bndiagnostic tool and share the generated code with us so we can take a look and try to understand what's happening

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by Yasin-Ali-Cpuflat** [comment]
thanks for response, now i fix apache page problem but still have " There has been a critical error on this website." error . how i can fix it please.  i tried many ways but stil can't fix it .

**Comment by Yasin-Ali-Cpuflat** [comment]
@gongomgra any solutions bro

**Comment by Yasin-Ali-Cpuflat** [comment]
????

**Comment by Yasin-Ali-Cpuflat** [comment]
> > but in "http" am getting Apache2 Debian Default Page .
> 
> As @gongomgra mentioned, if you get the Apache2 default page is because you installed the apache2 system's package. Please run the commands in this other post to remove that package and start the Bitnami's Apache again
> 
> [#26 (comment)](https://github.com/bitnami/vms/issues/26#issuecomment-1143980454)

I fix it , but still have "There has been a critical error on this website" problem in my website , [Cpuflat.com](cpuflat.com) as can you see

**Comment by jotamartos** [comment]
That's a WordPress' issue, did you take a looks at the troubleshooting page in the official documentation?

https://wordpress.org/documentation/article/faq-troubleshooting/

There are some guides in our docs/forums that may help you as well

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors/#wordpress-enters-into-maintenance-mode-after-upgrading-or-activating-a-plugin
https://docs.bitnami.com/general/apps/wordpress/administration/understand-file-permissions/
https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

**Comment by Yasin-Ali-Cpuflat** [comment]
> That's a WordPress' issue, did you take a looks at the troubleshooting page in the official documentation?
> 
> https://wordpress.org/documentation/article/faq-troubleshooting/
> 
> There are some guides in our docs/forums that may help you as well
> 
> https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors/#wordpress-enters-into-maintenance-mode-after-upgrading-or-activating-a-plugin https://docs.bitnami.com/general/apps/wordpress/administration/understand-file-permissions/ [#22 (comment)](https://github.com/bitnami/vms/issues/22#issuecomment-1143906974)

I fix one of them the wordpress problem but I still have the last problem which is :



[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Sep 11 16:19:31.392058 2023] [authz_core:error] [pid 25123:tid 
139902662444800] [client **ip_address**:40800] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
Press [Enter] to continue:
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded

**Comment by gongomgra** [comment]
Hi @Yasin-Ali-Cpuflat,

As described in the error message, you are trying to dynamically load a built-in module, which is not allowed. Please comment-out the mentioned line in the Apache config file and restart the service.

**Comment by Yasin-Ali-Cpuflat** [comment]
> Hi @Yasin-Ali-Cpuflat,
> 
> As described in the error message, you are trying to dynamically load a built-in module, which is not allowed. Please comment-out the mentioned line in the Apache config file and restart the service.

how i can comment-out the mentioned line in the Apache config file  on gcp

**Comment by Yasin-Ali-Cpuflat** [comment]
Things changed .I'm open new issue
