### ISSUE TITLE
can't access phpmyadmin

### ISSUE THREAD

**Issue by zzzh** [bitnami/vms#1146]
### Describe your issue as much as you can

Hi,

I was trying to access phpadmin following your this article: https://docs.bitnami.com/virtual-machine/faq/get-started/access-phpmyadmin/

I checked event log of putty, looks like everything works fine:
2023-09-10 15:33:36	Access granted
2023-09-10 15:33:36	Local port 8888 forwarding to localhost:80
2023-09-10 15:33:36	Opening main session channel
2023-09-10 15:33:36	Opened main channel
2023-09-10 15:33:36	Allocated pty
2023-09-10 15:33:36	Started a shell/command

But, when I try to access phpadmin by this address in edge browser:  http://127.0.0.1:8888/phpmyadmin
it always say:
Hmmm… can't reach this page 
The connection was reset.
in event log, it would say like this:
2023-09-10 15:38:22	Opening connection to localhost:80 for forwarding from 127.0.0.1:54898
2023-09-10 15:38:22	Opening connection to localhost:80 for forwarding from 127.0.0.1:54899
2023-09-10 15:38:22	Forwarded connection refused by remote: Connect failed [Connection refused]
2023-09-10 15:38:22	Forwarded connection refused by remote: Connect failed [Connection refused]

The OS I'm using is Windows 10, I tried to add a firewall rule to let 8888 port pass, but it still don't work.
Any ideas?

**Comment by gongomgra** [comment]
Hi @zzzh,

Thanks for using Bitnami. Can you check the Apache logs in the server to try to find what's happening? Can you also run the bndiagnostic tool and share the generated code with us?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by zzzh** [comment]
Hi, @gongomgra ,

Happy to use Bitnami, it's awesome.

Here's the content of  /opt/bitnami/apache/logs/error_log:
[Sun Sep 10 10:00:25.045716 2023] [mpm_event:notice] [pid 1205:tid 140665075145728] AH00489: Apache/2.4.57 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Sun Sep 10 10:00:25.045883 2023] [core:notice] [pid 1205:tid 140665075145728] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Sun Sep 10 11:48:52.241251 2023] [mpm_event:notice] [pid 1205:tid 140665075145728] AH00491: caught SIGTERM, shutting down
[Sun Sep 10 11:49:34.400107 2023] [mpm_event:notice] [pid 237:tid 139702136581120] AH00489: Apache/2.4.57 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Sun Sep 10 11:49:34.401678 2023] [core:notice] [pid 237:tid 139702136581120] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Sun Sep 10 14:34:39.691588 2023] [core:warn] [pid 237:tid 140236508351488] AH00098: pid file /opt/bitnami/apache/var/run/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sun Sep 10 14:34:39.702421 2023] [mpm_event:notice] [pid 237:tid 140236508351488] AH00489: Apache/2.4.57 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Sun Sep 10 14:34:39.702675 2023] [core:notice] [pid 237:tid 140236508351488] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'

Here's the output from the bndiagnostic tool( blank lines removed to increase readability here):
===== Begin of bndiagnostic tool output =====
    ? Apache: No issues found
    ? Processes: No issues found
    ? Resources: No issues found
    ? Php: No issues found
    ? Mariadb: No issues found
    ? Connectivity: Found possible issues
[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:
https://docs.bitnami.com/general/faq/administration/use-firewall/
===== End of bndiagnostic tool output =====

By the way, I didn't change anything in this image, just not change the default password...

I tried to change the default password, now it works!

Problem solved, thank you so much for the reply.

**Comment by Morfonio** [comment]
Hi @zzzh,

I have what I believe is the same problem you had.

You said you tried changing the default password and that worked for you. What command or steps did you use to make this change?

**Comment by Morfonio** [comment]
Hello again.

Thanks for your reply, but in my case instead of Maria DB I use Mysql so I used this guide to see the password change, [https://docs.bitnami.com/aws/infrastructure/mysql/administration/change-reset-password-mysql/] , but when I changed the password I still can't access phpmyadmin through the browser and I get the same message in the browser.

Do you know what else I can try?

**Comment by gongomgra** [comment]
Hi @zzzh,

What if you try to connect with the root user directly to MySQL from the command line on your instance? Does the new password work for you? It will prompt you for the password, but you won't see any character back while you type in the password.

```
mysql -u root -p
```

If the command above works, please restart all services and clean the browser cache on your side and try again

```
sudo /opt/bitnami/ctlscript.sh restart
```

**Comment by Morfonio** [comment]
When I run the command:

`mysql -u root -p`

Then I run

`sudo /opt/bitnami/ctlscript.sh restart`

It asks me for the password and I enter the new one I generated and it recognizes the new password.

But when I try to enter phpmyadmin from the browser it still won't let me in.

![Captura de pantalla 2024-10-02 145052](https://github.com/user-attachments/assets/240cfb33-ed00-4f68-964c-16cc04707988)

**Comment by gongomgra** [comment]
@Morfonio let's continue checking your issue in the other thread you have opened.
