### ISSUE TITLE
[VirtualBox - MacBook] How to access existing WordPress User Account

### ISSUE THREAD

**Issue by yasmeensk** [bitnami/vms#1148]
### Describe your issue as much as you can

Hi there, 

I tried searching for how to guides online but the only guides I find don't address the issue I'm having. 

I downloaded and installed Bitnami VirtualBox for my MacBook and successfully logged-in to the default generic Wordpress Account that the VirtualBox prompts you to log-in to with its instructions. Okay that's great and all but I want to actually access my existing WordPress Account and configure my real WordPress account in Bitnami VirtualBox. 

What are the exact steps to access my actual existing WordPress Account? I tried entering my real WordPress credentials into 'debain login' but it doesn't work. What am I missing?

Apologies if this question is redundant.  

Thanks,
Yasmeen

**Comment by yasmeensk** [comment]
Hi there, 

May I please get some assistance? I'm trying to launch a website and really need support with logging into my actual Wordpress Account in Bitnami Virtual Box. 

Many thanks,
Yasmeen

@gongomgra @mdhont

**Comment by yasmeensk** [comment]
Ok. Thanks for the reply. What happens if I stop using Bitnami Wordpress or uninstall it in the future - can I still access the wordpress site directly from wordpress - or the admin account and site I build through Bitnami Wordpress is lost/gone forever? 

@mdhont @carlossm @pablogalegoc

**Comment by gongomgra** [comment]
Hi @yasmeensk,

Thanks for using Bitnami. The Bitnami WordPress installation is independent from the WordPress site and account availables at wordpress.org. You will lose all your local information if you uninstall/delete the Bitnami installation from your local computer.

Regarding your question for syncing data between the WordPress site and your local installation, I'm afraid I don't know if that's possible. We recommend you to ask in the official WordPress forums at https://wordpress.org/support/forums/

Hope it helps!

**Comment by yasmeensk** [comment]
Oh wow, that's unfortunate! 

Earlier this year Bitnami had a Windows / Mac / Linux computer download option where you could access your own personal WordPress Admin Account and then build your website. Taking away this option and making everyone now dependant on the Bitnami Virtual Box's WordPress Admin Account - FOREVER - is an underhanded move that forces everyone into a corner with using Bitnami WordPress indefinitely b/c otherwise we lose the site(s) we built. 

Since I can't in good faith build and spend money on websites for myself and clients that a few years from now they'll lose if they uninstall or move away from Bitnami, I'll have to uninstall your Bitnami Virtual Box go with an alternative option in the marketplace.

**Comment by gongomgra** [comment]
Hi @yasmeensk,

Thanks for your message. I'm afraid I don't remember login with your wordpress.org credentials was available in our local installers. Did you export the wordpress.org website and imported it on your local installation so you can develop it locally, and then uploaded the updated site to the remote server in the past? I think that's the only way of working with the remote WordPress site. 

Notice the export/import procedure also applies to the OVAs.
