### ISSUE TITLE
[WordPress] How to upgrade

### ISSUE THREAD

**Issue by fcorella** [bitnami/vms#1149]
### Describe your issue as much as you can

I subscribe to WordPress Certified by Bitnami and Automattic and I receive messages from time to time from AWS Marketplace informing me of product upgrades and recommending that I update to the latest version.  For example, the last message I received says:  "As an existing customer, your subscription to the product, any running instances and access to previous versions are unaffected. However, Bitnami by VMware does recommend you to update to the latest version, WordPress Certified by Bitnami and Automattic/6.3.1-0 on Debian 11 by visiting [https://aws.amazon.com/marketplace/pp/prodview-bzstv3wbn5wkq](https://v8xqhkq3.r.us-east-1.awstrack.me/L0/https:%2F%2Faws.amazon.com%2Fmarketplace%2Fpp%2Fprodview-bzstv3wbn5wkq/1/0100018a604f038e-cee8bc8a-8f73-4654-b751-af8d2d3c9c5f-000000/_ge476rb3vo5wg_GsWy_QRgz7kg=337).
But the link takes me to a page that does not offer an option to update.  The page just has information about the product, and a box saying that I have access to the product, with a button to view my subscription.  When I click on the button to view my subscription there is again no option to upgrade.  Could you please tell me how I can upgrade.

**Comment by jotamartos** [comment]
You can launch a new instance with the latest version of Apache, PHP, MariaDB and WordPress and migrate your current data to that new server by following this link

https://docs.bitnami.com/general/how-to/migrate-wordpress/
