### ISSUE TITLE
[ERPNext] Upgrading Erpnext 

### ISSUE THREAD

**Issue by piratedkhan** [bitnami/vms#115]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4caaba59-f263-bd19-691d-c2417e19a4a9

### bndiagnostic output

   ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found

### bndiagnostic was not useful. Could you please tell us why?

It has identified some problems 

### Describe your issue as much as you can

I have erpnext server DNS multitenancy is on. from past few days i have been getting error to connecting to redis cache server. i tried to upgrade the erpnext which might solve problems but getting the following error. by running the Bndiagnostic it identified some issues.  the following issues I addressed to the best of my knowledge.

- added 5 gb space to my instance volume
- added 4 gb space to swap
- currently have 3gb free space (checked before writing here)

https://docs.bitnami.com/general/apps/erpnext/administration/upgrade/ 
following this guided  `bench update` give the following error
ERROR: [Errno 13] Permission denied: '/opt/bitnami/erpnext/frappe-bench/patches.txt'

Need help fixing issues!

**Comment by piratedkhan** [comment]
upon giving executable permission to patch.txt `chmod +x patches.txt`
this error shows up
ERROR: Command 'basename $(git symbolic-ref -q HEAD)' returned non-zero exit status 1.

**Comment by walterrivarola** [comment]
Hi, I found out this answer, I think so this Will help you. ![IMG_20220715_002249.jpg](https://user-images.githubusercontent.com/4240253/179150035-20e7bd00-4fe8-4716-a9c1-6461c065f0fc.jpg)

I leave you the link of the post
[Error Update Erpnext](https://community.bitnami.com/t/error-update-erpnext-v7-google-cloud/46420/22)

**Comment by femijoshuao** [comment]
Hello, i am also facing the issue in updating ERPNext or using bench command. after being in the directory /opt/bitnami/ernext/frappe-bench/ any bench command issued give error `PermissionError: [Errno 13] Permission denied: '/opt/bitnami/erpnext/frappe-bench/logs/bench.log'
` Pls i need help

**Comment by piratedkhan** [comment]
> Hi, I found out this answer, I think so this Will help you. ![IMG_20220715_002249.jpg](https://user-images.githubusercontent.com/4240253/179150035-20e7bd00-4fe8-4716-a9c1-6461c065f0fc.jpg)
> 
> I leave you the link of the post [Error Update Erpnext](https://community.bitnami.com/t/error-update-erpnext-v7-google-cloud/46420/22)

i have already done migrating all my sites ... but still at the same place

**Comment by piratedkhan** [comment]
Can any one here help in this regard. thanks

**Comment by mdhont** [comment]
I've reproduced the issue, thanks for reporting it. We will continue to update this thread.

**Comment by piratedkhan** [comment]
I know the support team has a lot of ground to cover but this issue has almost been a month old and no response from the support team. looking forward

**Comment by egarmendia-dac** [comment]
> upon giving executable permission to patch.txt `chmod +x patches.txt` this error shows up ERROR: Command 'basename $(git symbolic-ref -q HEAD)' returned non-zero exit status 1.

I am trying the upgrade procedure in from the documentation section of the bitnami site and I get this error, any resolution to this?

**Comment by gongomgra** [comment]
Hi @egarmendia-dac,

Thanks for using Bitnami. I can't find that instruction in our docs site. Can you share with us the place where you found it?

https://docs.bitnami.com/general/apps/erpnext/administration/upgrade/

Apart from the above, I'm afraid our engineering team didn't have time to check this issue, but they will post any update they have once they start checking it.

**Comment by egarmendia-dac** [comment]
Thanks. 
https://docs.bitnami.com/general/apps/erpnext/administration/upgrade/

This guide has not worked for me for the last three releases. Always get:
Command 'basename $(git symbolic-ref -q HEAD)' returned non-zero exit status 1 as quoted by another user above.

**Comment by gongomgra** [comment]
Hi @egarmendia-dac,

I still can't find any references to the `patches.txt` file you mentioned in a previous message. Anyways, yes, I can confirm you the upgrade process of ERPNext doesn't work. It is a known issue and we filed an internal task for our engineering team to check it, but they didn't have time to do it yet.

**Comment by redolencetech** [comment]
Any updates on this issue? I've been trying to update and played around with all sorts of different solutions, but no luck

**Comment by mdhont** [comment]
This just has been fixed in the latest release. Please accept my apologies for not notifying you earlier. While the latest version works out of the box, on your existing machine it should be possible to fix as follows:

```
    // activate the virtual environment and go to the erpnext folder
    source /opt/bitnami/erpnext/venv/bin/activate
    cd /opt/bitnami/erpnext/frappe-bench/apps/erpnext/

    // Add the upstream remote expected by bench and unshallow the repo
    git remote add upstream https://github.com/frappe/erpnext
    git fetch --unshallow
    // Fetch version-14 branch
    git fetch upstream version-14
    git checkout --track upstream/version-14

    // Do the same for apps/frappe
    cd /opt/bitnami/erpnext/frappe-bench/apps/frappe/
    git remote add upstream https://github.com/frappe/frappe
    git fetch --unshallow    
    git fetch upstream version-14
    git checkout --track upstream/version-14

    // Change permissions for erpnext/indexes to prevent permissions error during update
    sudo chown -R bitnami:daemon /opt/bitnami/erpnext/frappe-bench/sites/erpnext/indexes
    // Update bench and restart
    cd /opt/bitnami/erpnext/frappe-bench/apps/erpnext/ 
    bench update
    sudo /opt/bitnami/ctlscript.sh restart
```

**Comment by redolencetech** [comment]
> 

This worked, thank you!

**Comment by albatati3** [comment]
Do you have the link for the latest ERPNEXT installer for linux and windows?

**Comment by gongomgra** [comment]
Hi @albatati3,

Thanks for using Bitnami. We no longer provide native installers for our assets, but we provide the virtual machine as an alternative. You can download it from our website at https://bitnami.com/stack/erpnext/virtual-machine
