### ISSUE TITLE
Magento 2 - Upgrading requires different php version

### ISSUE THREAD

**Issue by KeironWalsh** [bitnami/vms#1150]
### Describe your issue as much as you can

I have a Bitnami Magento 2 installation on Amazon Lightsail. I'm following the instructions [provided by Bitnami here](https://docs.bitnami.com/general/apps/magento/administration/upgrade/). However, when I run "sudo composer update" I get the following error message: " - magento/product-community-edition 2.4.6 requires php ~8.1.0||~8.2.0 -> your php version (7.4.27) does not satisfy that requirement."

How do I _safely_ upgrade the PHP version before I upgrade Magento?

**Comment by jotamartos** [comment]
Hi @KeironWalsh,

It's not possible to upgrade PHP in the instance. However, you can launch a new VM with the latest version of Magento and PHP and migrate your data there. You will find information regarding how to perform this migration between servers in the Magento's documentation and forums.

Once data is migrated, you can stop your current server.

Thanks
