### ISSUE TITLE
[WordPress] How to update password

### ISSUE THREAD

**Issue by rajesh-siluvainathan** [bitnami/vms#1152]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

62e27275-196e-a9ff-1a63-e9ed787bfa16

### bndiagnostic was not useful. Could you please tell us why?

required docs is not available

### Describe your issue as much as you can

I am creating multiple VMs from the bitnami WP image. But I see the same Bitnami credentials on all the new WP servers. How can I create new VMs with different credentials?

**Comment by jotamartos** [comment]
The Bitnami VMs generate a random password during the first initialization, if they are already initialized they won't change the password again. 

You can try changing the password in the WordPress database as explained here

https://docs.bitnami.com/general/apps/wordpress/administration/reset-wp-admin-password/
