### ISSUE TITLE
[Wordpess] AWS Lightsail, bitnami services not working

### ISSUE THREAD

**Issue by TahaDuman** [bitnami/vms#1154]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

af849452-470a-7eb9-70c8-7a1a51d7ead1

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

I already have my 22, 80 and/or 443 ports 

### Describe your issue as much as you can

I created a bitnami wordpress server using aws lightsail and it worked fine for 1 years and now all of a sudden it stopped working without me touching it. When i look up `systemctl` , `bitnami.service` looks failed.
Also I already have my ports setup in aws but still `bndiagnostic` says they are not publicly accessible.

`sudo /opt/bitnami/ctlscript.sh start`
> Starting services..
> Job for bitnami.service failed because the control process exited with error code.
> See "systemctl status bitnami.service" and "journalctl -xe" for details.

`systemctl status bitnami.service`

>  bitnami.service - LSB: bitnami init script
>    Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Fri 2023-09-15 12:35:10 UTC; 6min ago
>   Process: 3851 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
>     Tasks: 11 (limit: 557)
>    Memory: 114.5M
>    CGroup: /system.slice/bitnami.service
>            ├─697 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
>            ├─701 php-fpm: pool www
>            ├─702 php-fpm: pool www
>            ├─703 php-fpm: pool www
>            ├─704 php-fpm: pool www
>            ├─705 php-fpm: pool www
>            ├─706 php-fpm: pool www
>            ├─707 php-fpm: pool www
>            ├─708 php-fpm: pool www
>            ├─709 php-fpm: pool www
>            └─710 php-fpm: pool www
> 
> Sep 15 12:35:10 ip-172-26-3-9 bitnami[3851]: mariadb 12:35:10.19 ERROR ==> mariadb did not start
> Sep 15 12:35:10 ip-172-26-3-9 bitnami[3851]: 2023-09-15T12:35:10.195Z - error: Unable to perform start operation Export start for mariadb fail
> Sep 15 12:35:10 ip-172-26-3-9 bitnami[3851]: ## 2023-09-15 12:35:10+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_bitnami_agen
> Sep 15 12:35:10 ip-172-26-3-9 bitnami[3851]: ## 2023-09-15 12:35:10+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agen
> Sep 15 12:35:10 ip-172-26-3-9 bitnami[3851]: ## 2023-09-15 12:35:10+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welco
> Sep 15 12:35:10 ip-172-26-3-9 bitnami[3851]: ## 2023-09-15 12:35:10+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_cred
> Sep 15 12:35:10 ip-172-26-3-9 bitnami[3851]: ## 2023-09-15 12:35:10+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metada
> Sep 15 12:35:10 ip-172-26-3-9 systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
> Sep 15 12:35:10 ip-172-26-3-9 systemd[1]: bitnami.service: Failed with result 'exit-code'.
> Sep 15 12:35:10 ip-172-26-3-9 systemd[1]: Failed to start LSB: bitnami init script.

**Comment by jotamartos** [comment]
As you can see in the log, there is something wrong with MariaDB. Did you check the log? I can see this 

```
2023-09-15 11:49:24 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=7063541,10088243
2023-09-15 11:49:24 0 [ERROR] InnoDB: Missing FILE_CREATE, FILE_DELETE or FILE_MODIFY before FILE_CHECKPOINT for tablespace 24
2023-09-15 11:49:24 0 [ERROR] InnoDB: Plugin initialization aborted with error Data structure corruption
2023-09-15 11:49:24 0 [Note] InnoDB: Starting shutdown...
2023-09-15 11:49:24 0 [ERROR] Plugin 'InnoDB' init function returned error.
2023-09-15 11:49:24 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2023-09-15 11:49:24 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-09-15 11:49:24 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2023-09-15 11:49:24 0 [ERROR] Aborting
```

Please take a look at the MariaDB's documentation and ask its support team to know how to solve this corruption issue.
