### ISSUE TITLE
[Ghost] How to delete SSL Certificate in Bitnami Ghost Image configured by bncert tool?

### ISSUE THREAD

**Issue by Harsh-2002** [bitnami/vms#1157]
### Describe your issue as much as you can

I want to setup my Ghost EC2 instance with Cloudfront but the issue I'm getting is my domain is redirecting to EC2 DNS. Previously i used this instance to setup SSL with domain. I don't know what causing the issue. To check if everything is properly configured in Cloudfront I launched another instance with Ghost image and this time it is working perfectly, I used AWS certificate manager to setup  SSL. 

So i think the issue is with the Previously configured SSL certificate or may be other thing that i didn't know. 

Please help. If you want I can share my server ssh access.

**Comment by jotamartos** [comment]
>I'm getting is my domain is redirecting to EC2 DNS

Please look for any redirection-related line in the /opt/bitnami/apache/conf/bitnami/bitnami.conf file and the ones inside the /opt/bitnami/apache/vhosts folder (specially the ghost-related ones).

Once you remove the redirection, please restart Apache 

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

**Comment by Harsh-2002** [comment]
Now I'm facing another issue 

apache already running
ghost not running
mysql already running

Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

**Comment by Harsh-2002** [comment]
total        used        free      shared  buff/cache   available
Mem:           975Mi       438Mi       118Mi       0.0Ki       418Mi       400Mi
Swap:          634Mi       0.0Ki       634Mi

**Comment by jotamartos** [comment]
Hi, 

Did you make any change lately to the Ghost's folder (/opt/bitnami/ghost)? Do you get any error message when starting the Ghost service?

```
sudo /opt/bitnami/scripts/ghost/start.sh
```

**Comment by jotamartos** [comment]
>When I run the following command sudo su ghost -c "ghost backup" to perform a backup in Ghost, it prompts me to enter an email and password. Is there a way to execute this command without the need for an email & password prompt or can I set it like env variables?

that's a Ghost-related question. Please take a look at its forums and documentation to get more information about how to use the CLI.
