### ISSUE TITLE
[Redmine] Can I have 3.3 / 3.4 / 4.0 / 4.1 / 4.2 latest Redmine native installer for Linux?

### ISSUE THREAD

**Issue by gyto6** [bitnami/vms#1158]
### Describe your issue as much as you can

Can I have latest Redmine native installer for Linux?

We have bitnami-redmine-3.3.2-2-linux-x64-installer.run.

Where I'm working now, we've an old Debian 8 server with this old Redmine running. Before migrating to Docker, I want to succesfully upgrade Redmine and Debian to finally fill the container with the up to date config files.

What should I download and and which step should I proceed with to upgrade?

Really appreciate your help!

**Comment by jotamartos** [comment]
Hi @gyto6,

As you know, we removed support for the installers serveral months ago. We also removed the old installers from our servers so I can't provide you will all the installers you requested.

https://downloads.bitnami.com/files/stacks/redmine/4.1.0-9/bitnami-redmine-4.1.0-9-linux-x64-installer.run
https://downloads.bitnami.com/files/stacks/redmine/4.2.1-3/bitnami-redmine-4.2.1-3-linux-x64-installer.run
