### ISSUE TITLE
[<Bitnami-Redmine>] <The Bitnami Redmine app has stopped working, could you please help me with below errors?>

### ISSUE THREAD

**Issue by netsanetss** [bitnami/vms#1159]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

003e90e8-55c4-83e0-65a2-23eb001ab68d

### bndiagnostic was not useful. Could you please tell us why?

the suggested guidance are not related to my issue. 

### Describe your issue as much as you can

sudo /opt/bitnami/ctlscript.sh status
Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)

sudo /opt/bitnami/ctlscript.sh start mysql
Failed to start mysql: Cannot find check with id MySQL

sudo /opt/bitnami/ctlscript.sh restart
Restarting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

sudo systemctl status bitnami.service
● bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-09-22 06:54:49 UTC; 6min ago
    Process: 18604 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
        CPU: 2.050s

Sep 22 06:54:48 debian bitnami[18705]: 2023-09-22T06:54:48.973Z - error: Unable to perform start operation Export start for apache fail>
Sep 22 06:54:48 debian bitnami[18720]: ## 2023-09-22 06:54:48+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_bitnami_age>
Sep 22 06:54:49 debian bitnami[18720]: ## 2023-09-22 06:54:49+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_age>
Sep 22 06:54:49 debian bitnami[18720]: ## 2023-09-22 06:54:49+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welc>
Sep 22 06:54:49 debian bitnami[18720]: ## 2023-09-22 06:54:49+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_cre>
Sep 22 06:54:49 debian bitnami[18720]: ## 2023-09-22 06:54:49+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metad>
Sep 22 06:54:49 debian systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
Sep 22 06:54:49 debian systemd[1]: bitnami.service: Failed with result 'exit-code'.
Sep 22 06:54:49 debian systemd[1]: Failed to start LSB: bitnami init script.
Sep 22 06:54:49 debian systemd[1]: bitnami.service: Consumed 2.050s CPU time.
lines 1-16/16 (END)

**Comment by mdhont** [comment]
Did you change any configuration? On which platform are you running the app, and which version is it?

**Comment by netsanetss** [comment]
Yes, I immediately lost the root user after running the permission command by mistake and did a lot of things to get it back. But now I have root access. the application was Redmine 5.0.4 version.
![image](https://github.com/bitnami/vms/assets/145747890/655b594b-83c6-45ed-8cfe-4bef3e763e02)

**Comment by mdhont** [comment]
> But now I have root access. 

So is it working now?

**Comment by netsanetss** [comment]
No, I only have root access, but the above errors still exist. The application is not working. Only Apache is running but MySQL is not.  When I click on the Redmin application link/url it shows me the Apache default page.

![Capture-appache](https://github.com/bitnami/vms/assets/145747890/6b6d273d-83d9-4737-bea9-f0de3c4057b9)

**Comment by netsanetss** [comment]
mysqldump -u YOUR_USERNAME -p YOUR_DATABASE_NAME > backup.sql
Enter password:
mysqldump: Got error: 2002: "Can't connect to local server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)" when trying to connect
------------------------------------------------------------------------------
sudo systemctl status bitnami.service
● bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-10-03 06:28:55 UTC; 40min ago
    Process: 5528 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
        CPU: 1.796s

Oct 03 06:28:55 debian bitnami[5629]: 2023-10-03T06:28:55.457Z - error: Unable to perform start operation Export start for apache faile>
Oct 03 06:28:55 debian bitnami[5644]: ## 2023-10-03 06:28:55+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_bitnami_agen>
Oct 03 06:28:55 debian bitnami[5644]: ## 2023-10-03 06:28:55+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agen>
Oct 03 06:28:55 debian bitnami[5644]: ## 2023-10-03 06:28:55+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welco>
Oct 03 06:28:55 debian bitnami[5644]: ## 2023-10-03 06:28:55+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_cred>
Oct 03 06:28:55 debian bitnami[5644]: ## 2023-10-03 06:28:55+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metada>
Oct 03 06:28:55 debian systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
Oct 03 06:28:55 debian systemd[1]: bitnami.service: Failed with result 'exit-code'.
Oct 03 06:28:55 debian systemd[1]: Failed to start LSB: bitnami init script.
Oct 03 06:28:55 debian systemd[1]: bitnami.service: Consumed 1.796s CPU time.

----------------------------------------------------------------------------
2023-09-18 13:30:34 0 [ERROR] InnoDB: Tablespace 25 was not found at ./bitnami_redmine/tokens.ibd.
2023-09-18 13:30:34 0 [ERROR] InnoDB: Set innodb_force_recovery=1 to ignore this and to permanently lose all changes to the tablespace.
2023-09-18 13:30:34 0 [ERROR] InnoDB: Tablespace 27 was not found at ./bitnami_redmine/users.ibd.
2023-09-18 13:30:34 0 [ERROR] InnoDB: Tablespace 32 was not found at ./bitnami_redmine/user_preferences.ibd.
2023-09-18 13:30:34 0 [ERROR] InnoDB: Plugin initialization aborted with error Tablespace not found
2023-09-18 13:30:34 0 [Note] InnoDB: Starting shutdown...
2023-09-18 13:30:34 0 [ERROR] Plugin 'InnoDB' init function returned error.
2023-09-18 13:30:34 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2023-09-18 13:30:34 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-09-18 13:30:34 0 [ERROR] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some plugins may be not loaded
2023-09-18 13:30:34 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2023-09-18 13:30:34 0 [ERROR] Aborting

**Comment by mdhont** [comment]
Could you reset the file permissions to the previous state?

**Comment by netsanetss** [comment]
could you please help me with the command to reset the permission? I am new to linux

**Comment by netsanetss** [comment]
I changed the license but still have problem:

sudo /opt/bitnami/ctlscript.sh start mysql
file '/etc/gonit/gonitrc' must be owned by you.
root@debian:/opt/bitnami/apache/logs#

Please either fix up the permissions for the insecure paths, or install Passenger in a different location that can only be modified by root.
[ N 2023-10-04 10:12:56.5102 29850/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 29850
[Wed Oct 04 10:12:56.514285 2023] [mpm_event:notice] [pid 29843:tid 140641039821824] AH00489: Apache/2.4.55 (Unix) OpenSSL/1.1.1n SVN/1.14.2 Phusion_Passenger/6.0.17 configured -- resuming normal operations
[Wed Oct 04 10:12:56.515080 2023] [core:notice] [pid 29843:tid 140641039821824] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
App 30796 output: /opt/bitnami/redmine/Gemfile:63:in `read':  (Bundler::Dsl::DSLError)
App 30796 output: [!] There was an error parsing `Gemfile`: Permission denied @ rb_sysopen - /opt/bitnami/redmine/config/database.yml. Bundler cannot continue.
App 30796 output:


[ E 2023-10-04 10:12:59.8918 29850/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/bitnami/redmine: The application process exited prematurely.
  Error ID: b7fcaee0
  Error details saved to: /tmp/passenger-error-tytcNh.html

[ E 2023-10-04 10:12:59.8968 29850/T8 age/Cor/Con/CheckoutSession.cpp:281 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is b7fcaee0. Please see earlier logs for details about the error.
[ E 2023-10-04 10:12:59.8972 29850/Ta age/Cor/Con/CheckoutSession.cpp:281 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is b7fcaee0. Please see earlier logs for details about the error.
App 30852 output: /opt/bitnami/redmine/Gemfile:63:in `read'
App 30852 output: :
App 30852 output:  (
App 30852 output: Bundler::Dsl::DSLError
App 30852 output: )
App 30852 output:
App 30852 output: [!] There was an error parsing `Gemfile`: Permission denied @ rb_sysopen - /opt/bitnami/redmine/config/database.yml. Bundler cannot continue.
App 30852 output:

root@debian:/opt/bitnami/apache/logs# sudo tail -f /opt/bitnami/apache/logs/error_log
App 33039 output:     /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/passenger-6.0.17/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 33039 output:     /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/passenger-6.0.17/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 33039 output:     /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/passenger-6.0.17/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 33039 output:     /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/passenger-6.0.17/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 33039 output:     /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/passenger-6.0.17/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2023-10-04 12:58:22.0893 29850/T2h age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/bitnami/redmine: The application encountered the following error: Access denied for user 'bn_redmine'@'localhost' (using password: YES) (ActiveRecord::ConnectionNotEstablished)
  Error ID: d4bf95a5
  Error details saved to: /tmp/passenger-error-UCSygl.html

[ E 2023-10-04 12:58:22.0932 29850/Ta age/Cor/Con/CheckoutSession.cpp:281 ]: [Client 2-5] Cannot checkout session because a spawning error occurred. The identifier of the error is d4bf95a5. Please see earlier logs for details about the error.

**Comment by netsanetss** [comment]
sudo /opt/bitnami/ctlscript.sh status
apache already running
mariadb not running
subversion not running
mysql already running

**Comment by mdhont** [comment]
You can check the following guide to fix permissions issues:

https://docs.bitnami.com/aws/how-to/troubleshoot-permission-issues/
