### ISSUE TITLE
[MEAN] Can't start services after *any* change to MongoDb auth file

### ISSUE THREAD

**Issue by MrHmmm** [bitnami/vms#1161]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7e60c6ee-1928-c5d2-0e97-d41053925ebd

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Processes: Found possible issues
    ✓ Apache: No issues found

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 954 252 73 0 629 564 Swap: 634                      
0 634
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

[Connectivity]

Press [Enter] to continue:
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Processes]

One or more component's processes are not running:
```
apache not running mongodb not running
```
You can try to restart the process with the following command:

 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Sugestions didn't help

### Describe your issue as much as you can

Used the Bitnami MEAN images many times, love them, keep up the good work!
I hope  you can help me with this one...

Found a weird bug in the ctlscript.sh and am stuck :(
After ANY change to /home/bitnami/stack/mongodb/conf/mongodb.conf the services won't restart

Recreation is really simple...

- Created a clean new VM (bitnami MEAN stack)
- Logged in to console (SSH)
- I like change some setting in /home/bitnami/stack/mongodb/conf/mongodb.conf Done this a million times in earlier versions like 6.0.9
- First I change owner of the file to bitnami to make it easy to edit/save
_sudo chown bitnami:bitnami /home/bitnami/stack/mongodb/conf/mongodb.conf_

And now I've done it... cant start the services anymore and I get. (I didn't change anything in the file itself yet!)

_Restarting services..
**Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details._**

No changes made in te files yet... making root the owner again doesn't fix it. Weird couse it is back at the starting values that way.  I can start apache no-problem, but mongoDb is the problem.

So... I ran the suggested "systemctl status bitnami.service" and "journalctl -xe" for details.

bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-09-23 15:17:36 UTC; 3min 10s ago
    Process: 4919 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
      Tasks: 398 (limit: 1120)
     Memory: 368.0M
        CPU: 1.583s
     CGroup: /system.slice/bitnami.service
             ├─2183 /opt/bitnami/gonit/bin/gonit
             ├─3385 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
             ├─3388 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
             ├─3391 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
             └─3954 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf

Sep 23 15:17:36 ip-172-31-39-193 bitnami[5026]: ## 2023-09-23 15:17:36+00:00 ## INFO ## Running /opt/>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Control process exited, code=exited, st>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Failed with result 'exit-code'.
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 2183 (gonit) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 3385 (httpd) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 3388 (httpd) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 3391 (httpd) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 3954 (httpd) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: Failed to start LSB: bitnami init script.
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Consumed 1.572s CPU time.

And then using journalctl -xe

Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: This usually indicates unclean termination of a previous>
Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: bitnami.service: Found left-over process 3385 (httpd) in>
Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: This usually indicates unclean termination of a previous>
Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: bitnami.service: Found left-over process 3388 (httpd) in>
Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: This usually indicates unclean termination of a previous>
Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: bitnami.service: Found left-over process 3391 (httpd) in>
Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: This usually indicates unclean termination of a previous>
Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: bitnami.service: Found left-over process 3954 (httpd) in>
Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: This usually indicates unclean termination of a previous>
Sep 23 15:17:34 ip-172-31-39-193 systemd[1]: Starting LSB: bitnami init script...
░░ Subject: A start job for unit bitnami.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit bitnami.service has begun execution.
░░
░░ The job identifier is 1531.
Sep 23 15:17:34 ip-172-31-39-193 bitnami[4923]: ## 2023-09-23 15:17:34+00:00 ## INFO ## Running /opt/>
Sep 23 15:17:34 ip-172-31-39-193 bitnami[4923]: ## 2023-09-23 15:17:34+00:00 ## INFO ## Running /opt/>
Sep 23 15:17:34 ip-172-31-39-193 bitnami[4923]: ## 2023-09-23 15:17:34+00:00 ## INFO ## Running /opt/>
Sep 23 15:17:34 ip-172-31-39-193 bitnami[4919]: ## 2023-09-23 15:17:34+00:00 ## INFO ## Starting serv>
Sep 23 15:17:35 ip-172-31-39-193 bitnami[4984]: 2023-09-23T15:17:35.164Z - info: Saving configuration>
Sep 23 15:17:35 ip-172-31-39-193 bitnami[4984]: 2023-09-23T15:17:35.534Z - info: Performing service s>
Sep 23 15:17:35 ip-172-31-39-193 bitnami[4984]: apache 15:17:35.82 INFO  ==> apache is already running
Sep 23 15:17:35 ip-172-31-39-193 bitnami[4984]: 2023-09-23T15:17:35.829Z - info: Performing service s>
Sep 23 15:17:36 ip-172-31-39-193 bitnami[4984]: mongodb 15:17:36.17 ERROR ==> An error occurred when >
Sep 23 15:17:36 ip-172-31-39-193 bitnami[4984]: 2023-09-23T15:17:36.183Z - error: Unable to perform s>
Sep 23 15:17:36 ip-172-31-39-193 bitnami[5026]: ## 2023-09-23 15:17:36+00:00 ## INFO ## Running /opt/>
Sep 23 15:17:36 ip-172-31-39-193 bitnami[5026]: ## 2023-09-23 15:17:36+00:00 ## INFO ## Running /opt/>
Sep 23 15:17:36 ip-172-31-39-193 bitnami[5026]: ## 2023-09-23 15:17:36+00:00 ## INFO ## Running /opt/>
Sep 23 15:17:36 ip-172-31-39-193 bitnami[5026]: ## 2023-09-23 15:17:36+00:00 ## INFO ## Running /opt/>
Sep 23 15:17:36 ip-172-31-39-193 bitnami[5026]: ## 2023-09-23 15:17:36+00:00 ## INFO ## Running /opt/>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Control process exited, code=exited, st>
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit bitnami.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit bitnami.service has entered the 'failed' state with result 'exit-code'.
Sep 23 15:17:36 ip-172-31-39-193 sudo[4910]: pam_unix(sudo:session): session closed for user root
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 2183 (gonit) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 3385 (httpd) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 3388 (httpd) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 3391 (httpd) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Unit process 3954 (httpd) remains runni>
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: Failed to start LSB: bitnami init script.
░░ Subject: A start job for unit bitnami.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit bitnami.service has finished with a failure.
░░
░░ The job identifier is 1531 and the job result is failed.
Sep 23 15:17:36 ip-172-31-39-193 systemd[1]: bitnami.service: Consumed 1.572s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit bitnami.service completed and consumed the indicated resources.
Sep 23 15:17:44 ip-172-31-39-193 dhclient[461]: XMT: Solicit on ens5, interval 124080ms.
Sep 23 15:19:48 ip-172-31-39-193 dhclient[461]: XMT: Solicit on ens5, interval 129850ms.

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one.
