### ISSUE TITLE
[Wordpress AWS] The server get stuck 

### ISSUE THREAD

**Issue by sfoulad** [bitnami/vms#1162]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

6480d47f-1927-3611-8064-18dd3e69bc17

### bndiagnostic output

<img width="833" alt="Screenshot 2023-09-23 at 7 53 28 PM" src="https://github.com/bitnami/vms/assets/53208725/5bca81b6-cf11-4380-b6bd-a54e5e801638">

### bndiagnostic was not useful. Could you please tell us why?

Many issues no route cause 

### Describe your issue as much as you can

Sometimes the server stop working the website not working 
should I upgrade the server ?? or there is away to optimize it ?

**Comment by mdhont** [comment]
I suggest temporarily disabling all WordPress plugins to determine if this resolves any performance issues. If so, re-enable the plugins one by one to identify the cause.
