### ISSUE TITLE
OpenProject VM

### ISSUE THREAD

**Issue by zergormagn** [bitnami/vms#1163]
### Describe your suggestion as much as you can

The UI is very slow,  looking at some config files, it looks like it's configured to run in dev mode?   
Can the configuration also be updated to be more dynamic, as in if we increase cpus and memory for the VM at least that it would use them?

**Comment by mdhont** [comment]
On which platform are you running the VM? And which type of machine?

**Comment by zergormagn** [comment]
Running on VMware 16.  Gave it 8GB of memory and 12CPU cores.     It slowly does start to use more memory, I think it's up to 1GB+500MB catche now after a few days.   Adding cores don't seem to make any difference,  Ruby just runs at 100% for a couple minutes when u click on any link in the UI.   Although it seems to then try to use the a catched version if u get back to the same place,  still very sluggish.    It can't be a production setup?

**Comment by mdhont** [comment]
Could you run the bndiagnostic tool?

    sudo /opt/bitnami/bndiagnostic-tool

**Comment by zergormagn** [comment]
We have already moved to devops.  As the bitnami vm was very slow while
openproject team also didnt want to support this.
The issue still remains just run your openproject  vm.   And click aeound
in the ui.  Ruby uses massive amounts of cpu with the way its setup.
