### ISSUE TITLE
[<AWS>] <Bitnami Service are not restarting.>

### ISSUE THREAD

**Issue by BushCo** [bitnami/vms#1164]
### Describe your issue as much as you can

Bitami Diagnostic Output
59ebafed-c917-6a0a-43cf-1b7be902fbde

**Platform**
AWS - Wordpress

**Issue**
Bitnami Service are not restarting.

We changed some permission within a plugin for woocommerce.  Restarted the site once Ok, now it will not restart bitnami service.  We can restart apache OK but not bitnami.

Any help much appreciated... we are not techs. 

Thanks

**Comment by mdhont** [comment]
You need to reset the permissions:

https://docs.bitnami.com/aws/apps/wordpress/administration/understand-file-permissions/
