### ISSUE TITLE
[SonarQube] I am facing issue with disabling the tls1.0 and 1.1

### ISSUE THREAD

**Issue by venkat7792** [bitnami/vms#1166]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

121

### bndiagnostic output

I am unable to restart apache while restarting getting below error.
bitnami@SonarQube-VM:~$ sudo /opt/bitnami/ctlscript.sh start apache
Failed to start apache: Failed to start apache

### bndiagnostic was not useful. Could you please tell us why?

bitnami@SonarQube-VM:~$ sudo /opt/bitnami/ctlscript.sh start apache Failed to start apache: Failed to start apache

### Describe your issue as much as you can

I am trying to disable the tls 1.0 and 1.1 on my VM. for that I agve made changes on httpd.conf nad httpd-ssl.conf and ttryng to restart the apache not able to restart the apache.
I am unable to restart apache while restarting getting below error.
bitnami@SonarQube-VM:~$ sudo /opt/bitnami/ctlscript.sh start apache
Failed to start apache: Failed to start apache

**Comment by jotamartos** [comment]
Please ensure you use a similar line to this one to disable those protocols 

```
SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
```

If you continue running into issues when starting Apache, please take a look at the Apache's log file and the errors it shows when you start it using the start.sh script

```
sudo /opt/bitnami/scripts/apache/start.sh
```

**Comment by venkat7792** [comment]
I have added the "SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1" line in **bitnami-ssl.conf** like below.

bitnami@SonarQube-VM:/opt/bitnami/apache/conf/bitnami$ cat bitnami-ssl.conf
# Default SSL Virtual Host configuration.

<IfModule !ssl_module>
  LoadModule ssl_module modules/mod_ssl.so
</IfModule>

SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLHonorCipherOrder on
SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !EDH !RC4"
SSLPassPhraseDialog  builtin
SSLSessionCache "shmcb:/opt/bitnami/apache/logs/ssl_scache(512000)"
SSLSessionCacheTimeout  300

<VirtualHost _default_:443>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"

  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html
</VirtualHost>
bitnami@SonarQube-VM:

When I try to restart or start the apache I am getting the error like below:

bitnami@SonarQube-VM:~$ sudo /opt/bitnami/scripts/apache/start.sh
apache 04:56:48.91 INFO  ==> apache started
bitnami@SonarQube-VM:~$ sudo /opt/bitnami/ctlscript.sh status apache
Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)
bitnami@SonarQube-VM:~$ sudo /opt/bitnami/ctlscript.sh start apache
Started apache
bitnami@SonarQube-VM:~$ sudo /opt/bitnami/ctlscript.sh status apache
Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)
bitnami@SonarQube-VM:~$ /var/run/gonit.pid
-bash: /var/run/gonit.pid: No such file or directory
bitnami@SonarQube-VM:~$

**Comment by jotamartos** [comment]
>Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)

Seems that gonit is not running. Can you start it?

```
sudo gonit start
sudo gonit status
```

What about the command I told you to run in my previous comment?

```
sudo /opt/bitnami/scripts/apache/start.sh
```

**Comment by jotamartos** [comment]
gonit takes some time to be up and running. If it doesn't work, you may be running into performance issues and will need to increase the resources of the VM

> bitnami@SonarQube-VM:$ sudo /opt/bitnami/scripts/apache/start.sh
> apache 16:44:14.25 INFO ==> apache is already running
> bitnami@SonarQube-VM:$

I can see there is not any problem with Apache. You can try to restart it to take your changes by running these commands 

```
sudo /opt/bitnami/scripts/apache/stop.sh
sudo /opt/bitnami/scripts/apache/start.sh
```

**Comment by pv-jonathasbenevides** [comment]
se tiver utilizando o ctlscript.sh da o comando de restart do apache
 
sudo /opt/bitnami/ctlscript.sh restart apache 

sudo /opt/bitnami/ctlscript.sh status apache
