### ISSUE TITLE
[Magento 2] ssh/sftp access from outside VM

### ISSUE THREAD

**Issue by ZenMasta** [bitnami/vms#1167]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1

### bndiagnostic was not useful. Could you please tell us why?

-bash: wget: command not found therefore I can't even try to install bndiagnostic

### Describe your issue as much as you can

I just setup this VM using the downloadable .ova  It's running as expected without any errors from what I can tell. But I don't know how I can use a 3rd party program such as putty, to ssh into the vm. I know the ip of the vm and I can access the website it's hosting no problem but when I try to ssh. The ip address is the same as if it was connected on my normal network 192.168.1.92. 

I can access the website from my browser just fine too.

![image](https://github.com/bitnami/vms/assets/823528/1a8ee627-8e82-4796-a493-96e834246898)

![image](https://github.com/bitnami/vms/assets/823528/83486f59-04d7-4dc9-b918-fbf56410cda9)

**Comment by mdhont** [comment]
You need to activate the SSH server:

https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh/
