### ISSUE TITLE
[WordPress] Hmmm… can't reach this page 

### ISSUE THREAD

**Issue by Yasin-Ali-Cpuflat** [bitnami/vms#1168]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b31c6aea-3abd-030f-46b1-6bdd4da8c795

### bndiagnostic output

    ? Connectivity: Found possible issues
    ? Resources: Found possible issues
    ✓ Php: No issues found
    ✓ Wordpress: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Press [Enter] to continue:
Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 575 295 52 0 227 178 Swap: 0 0 
0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Apache]

The Apache configuration has errors:
```
/tmp/bndiagnostic/components/bndiagnostic-apache.sh: line 32: 
/opt/bitnami/apache/bin/apachectl: Permission denied
```

### bndiagnostic was not useful. Could you please tell us why?

I can't find the slove of issue

### Describe your issue as much as you can

I can't load my WORDPRESS website and get " Hmmm… can't reach this page" error page ,even can't load wp-admin page  . I'm using GCP + WORDPRESS .

**Comment by jotamartos** [comment]
Hi @Yasin-Ali-Cpuflat,

I can see you modified the permissions configuration of the entire installation directory to something like `-rw-rw-r--`

```
apache:
total 80
drw-rw-r-- 16 root    root  4096 Aug 10 19:14 .
drw-rw-r-- 23 root    root  4096 Aug 14 17:32 ..
drw-rw-r--  2 root    root  4096 Jul 25 19:03 bin
drw-rw-r--  2 root    root  4096 Jul 25 19:03 build
drw-rw-r--  2 root    root  4096 Jul 25 19:03 build-1
drw-rw-r--  6 bitnami root  4096 Sep  8 19:46 conf
drw-rw-r--  3 root    root  4096 Jul 25 19:03 error
drw-rw-r--  2 bitnami root  4096 Jul 25 19:03 htdocs
drw-rw-r--  3 root    root  4096 Jul 25 19:03 icons
drw-rw-r--  3 root    root  4096 Jul 25 19:03 include
drw-rw-r--  4 root    root  4096 Jul 25 19:03 lib
drw-rw-r--  2 root    root  4096 Jul 25 19:03 licenses
```

That affected the whole /opt/bitnami installation directory. Please take a look at similar issues in the forum like this one 

https://github.com/bitnami/vms/issues/22#issuecomment-1186792057

or compare your permissions configuration with a fresh instance. If you have a backup, please use it to recover your site.

**Comment by Yasin-Ali-Cpuflat** [comment]
> Hi @Yasin-Ali-Cpuflat,
> 
> I can see you modified the permissions configuration of the entire installation directory to something like `-rw-rw-r--`
> 
> ```
> apache:
> total 80
> drw-rw-r-- 16 root    root  4096 Aug 10 19:14 .
> drw-rw-r-- 23 root    root  4096 Aug 14 17:32 ..
> drw-rw-r--  2 root    root  4096 Jul 25 19:03 bin
> drw-rw-r--  2 root    root  4096 Jul 25 19:03 build
> drw-rw-r--  2 root    root  4096 Jul 25 19:03 build-1
> drw-rw-r--  6 bitnami root  4096 Sep  8 19:46 conf
> drw-rw-r--  3 root    root  4096 Jul 25 19:03 error
> drw-rw-r--  2 bitnami root  4096 Jul 25 19:03 htdocs
> drw-rw-r--  3 root    root  4096 Jul 25 19:03 icons
> drw-rw-r--  3 root    root  4096 Jul 25 19:03 include
> drw-rw-r--  4 root    root  4096 Jul 25 19:03 lib
> drw-rw-r--  2 root    root  4096 Jul 25 19:03 licenses
> ```
> 
> That affected the whole /opt/bitnami installation directory. Please take a look at similar issues in the forum like this one
> 
> [#22 (comment)](https://github.com/bitnami/vms/issues/22#issuecomment-1186792057)
> 
> or compare your permissions configuration with a fresh instance. If you have a backup, please use it to recover your site.

what you mention it didn't solve . and can you give me the steps of second solution that you prefer

**Comment by jotamartos** [comment]
I asked you to review the old tickets in the forum, not only the one I shared, did you do so? Recovering a permissions issue is not easy, and takes time. Please try to fix the issues one by one (fixing Apache first, then MariaDB, ...), there is enough information in the forum. If you need further help, we suggest you find someone in your community with knowledge about the linux terminal and permissions who can help you.

**Comment by Yasin-Ali-Cpuflat** [comment]
> Hi @Yasin-Ali-Cpuflat,
> 
> I can see you modified the permissions configuration of the entire installation directory to something like `-rw-rw-r--`
> 
> ```
> apache:
> total 80
> drw-rw-r-- 16 root    root  4096 Aug 10 19:14 .
> drw-rw-r-- 23 root    root  4096 Aug 14 17:32 ..
> drw-rw-r--  2 root    root  4096 Jul 25 19:03 bin
> drw-rw-r--  2 root    root  4096 Jul 25 19:03 build
> drw-rw-r--  2 root    root  4096 Jul 25 19:03 build-1
> drw-rw-r--  6 bitnami root  4096 Sep  8 19:46 conf
> drw-rw-r--  3 root    root  4096 Jul 25 19:03 error
> drw-rw-r--  2 bitnami root  4096 Jul 25 19:03 htdocs
> drw-rw-r--  3 root    root  4096 Jul 25 19:03 icons
> drw-rw-r--  3 root    root  4096 Jul 25 19:03 include
> drw-rw-r--  4 root    root  4096 Jul 25 19:03 lib
> drw-rw-r--  2 root    root  4096 Jul 25 19:03 licenses
> ```
> 
> That affected the whole /opt/bitnami installation directory. Please take a look at similar issues in the forum like this one
> 
> [#22 (comment)](https://github.com/bitnami/vms/issues/22#issuecomment-1186792057)
> 
> or compare your permissions configuration with a fresh instance. If you have a backup, please use it to recover your site.

I visit this comment and there are no any solving of the problem . please its been one month .
