### ISSUE TITLE
After SSH Tunnel - phpmyadmin giving 500 error when attempting to access

### ISSUE THREAD

**Issue by rahepler2** [bitnami/vms#1169]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

cea0016f-a8d6-688f-f684-4bfb7b1bafed

### bndiagnostic output

...

### bndiagnostic was not useful. Could you please tell us why?

Not an error persay

### Describe your issue as much as you can

I followed the bitnami documentation for creating an SSH tunnel and then access phpmyadmin from localhost:8888. 

I was able to create the SSH tunnel successfully, but when running localhost:8888/phpmyadmin I get a 500 error. 

Any way to fix this or know what's causing it?

**Comment by gongomgra** [comment]
Hi @rahepler2,

Thanks for using Bitnami. If you are getting a 500 server error, it seems to me that the SSH tunnel worked fine but the phpMyAdmin application is failing. Please review the Apache logs to get more information on what's happening.

https://docs.bitnami.com/aws/infrastructure/lamp/troubleshooting/debug-errors-apache/

**Comment by gongomgra** [comment]
Hi @rahepler2,

I checked the content of your bndiagnostic bundle. According to it, the size of the Apache logs are so large that the tool can't include its information. Please manually check them as instructed in the guide I shared previously.

The only error messages I was able to have access to are the ones shared below, related to WordPress configuration. We recommend you to fix them as well

```
[Fri Sep 29 13:27:29.346810 2023] [proxy_fcgi:error] [pid 70472:tid 140618655143680] [client **ip_address**:60822] AH01071: Got error 'PHP message: PHP Warning: Constant WP_DEBUG already defined in /opt/bitnami/hire_tekinfoway/wp-config.php on line 91PHP message: PHP Warning: Constant WP_SITEURL already defined in /opt/bitnami/hire_tekinfoway/wp-config.php on line 101'
 [Fri Sep 29 13:29:48.049800 2023] [proxy_fcgi:error] [pid 70889:tid 140618898532096] [client **ip_address**:19354] AH01071: Got error 'PHP message: PHP Warning: Constant WP_DEBUG already defined in /opt/bitnami/hire_tekinfoway/wp-config.php on line 91PHP message: PHP Warning: Constant WP_SITEURL already defined in /opt/bitnami/hire_tekinfoway/wp-config.php on line 101'
 [Fri Sep 29 13:29:48.929875 2023] [proxy_fcgi:error] [pid 70472:tid 140618638358272] [client **ip_address**:53028] AH01071: Got error 'PHP message: PHP Warning: Constant WP_DEBUG already defined in /opt/bitnami/hire_tekinfoway/wp-config.php on line 91PHP message: PHP Warning: Constant WP_SITEURL already defined in /opt/bitnami/hire_tekinfoway/wp-config.php on line 101'
```
