### ISSUE TITLE
[WordPress] SSL Certificate Renewal Issue on GCP

### ISSUE THREAD

**Issue by claylaw** [bitnami/vms#117]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5179edc2-2f2a-0792-82b4-ab929c4d7ab6

### bndiagnostic output

Connectivity: Found possible issues
    ? Processes: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Wordpress: No issues found

### bndiagnostic was not useful. Could you please tell us why?

I don't know how to fix the issues

### Describe your issue as much as you can

Let's Encrypt certificate renewal is proving difficult. I am unable to log into the WordPress admin panel or change the default user name and password. The site has completely crashed.

**Comment by jotamartos** [comment]
There are 2 problems in your instance:

- There is a typo in the Apache's configuration, you just need to close the VirtualHost block. Please check that 
```
httpd: Syntax error on line 521 of /opt/bitnami/apache2/conf/httpd.conf: Syntax error on line 48 of /opt/bitnami/apache/conf/bitnami/bitnami.conf: Syntax error on line 15 of /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf: /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf:15: <VirtualHost> was not closed.
```

- There is a problem with the Let's Encrypt servers and they do not generate a new certificate if it receives many requests at the same time. More info [here](https://github.com/bitnami/vms/issues/43). You can update the cronjob to run it at a different time:

```
sudo crontab -e -u bitnami
```

**Comment by claylaw** [comment]
> There are 2 problems in your instance:
> 
> * There is a typo in the Apache's configuration, you just need to close the VirtualHost block. Please check that
> 
> ```
> httpd: Syntax error on line 521 of /opt/bitnami/apache2/conf/httpd.conf: Syntax error on line 48 of /opt/bitnami/apache/conf/bitnami/bitnami.conf: Syntax error on line 15 of /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf: /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf:15: <VirtualHost> was not closed.
> ```
> 
> * There is a problem with the Let's Encrypt servers and they do not generate a new certificate if it receives many requests at the same time. More info [here](https://github.com/bitnami/vms/issues/43). You can update the cronjob to run it at a different time:
> 
> ```
> sudo crontab -e -u bitnami
> ```

Thanks for the reply.

How do I close the VirtualHost block?

**Comment by jotamartos** [comment]
Open the `/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf` file with a command line editor (vim, emacs, nano, ...)

```
sudo nano /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf
```

and add `</VirtualHost>` to the end.

**Comment by claylaw** [comment]
Thank you sir, such a simple answer. thanks alot.
