### ISSUE TITLE
Website is down 'refused to connect' or 'Error establishing a database connection'

### ISSUE THREAD

**Issue by vijayhighdecora** [bitnami/vms#1170]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7578b5c3-92e9-164a-7a05-861fe044fa80

### bndiagnostic output

Nothing is readable.

### bndiagnostic was not useful. Could you please tell us why?

log files were not readable and already done some manual task to solve the issue.

### Describe your issue as much as you can

The website is hosted with an AWS Lightsail instance and secured with Let's Encrypt SSL. I have seen many times that the server stopped working in the monitoring tool and using status check in SSH, I have found Apache not running and every time I have seen the error that the website is refused to connect or 503 and for the last 2 days "Error establishing a database connection".

Initially, it was working after rebooting the instance but from yesterday it is not. I have checked log files but I am not able to identify the issue. I have 2 vCPUs, RAM 4GB, SSD 80GB instance. Also, I have another website with AWS Lightsail but there is no kind of issue found.

This is last status
bitnami@ip-###-##-##-##:~$ sudo /opt/bitnami/ctlscript.sh status
Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)

I have been facing this for the last 2 months and tried many times to find the cause and solve it but couldn't.
Any help to solve the issue will be heartily appreciated.

Screenshot of log entries
https://imgur.com/a/EOk7A3G
![1](https://github.com/bitnami/vms/assets/146712518/84dd7cfd-48c1-4d4c-ab1c-46da7bb66e61)
![2](https://github.com/bitnami/vms/assets/146712518/8c46215c-d326-44d9-b220-cbdc9686acab)
![3](https://github.com/bitnami/vms/assets/146712518/bcc28750-181c-4361-b830-406c06c9019a)

**Comment by mdhont** [comment]
Did you change any permissions, or any configuration?

**Comment by vijayhighdecora** [comment]
It shows Mariadb stopped
I have tried to start it manually but not working
