### ISSUE TITLE
[Wordpress] Permission denied. Unable to restore the following file: /opt/bitnami/wordpress/index.php

### ISSUE THREAD

**Issue by tasteitslight** [bitnami/vms#1174]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0a93d837-0ebb-90d1-b54c-9d440af4025b

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 950 500 63 39 386 260 Swap: 
634 61 573
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Oct 03 04:56:02.623612 2023] [proxy_fcgi:error] [pid 1898:tid 
140604696663808] [client **ip_address**:33194] AH01071: Got error 'PHP message: 
PHP Warning: require_once(/bitnami/wordpress/wp-settings.php): Failed to open 
stream: No such file or directory in /bitnami/wordpress/wp-config.php on line 
190; PHP message: PHP Fatal error: Uncaught Error: Failed opening required 
'/bitnami/wordpress/wp-settings.php' (include_path='.:/opt/bitnami/php/lib/php') 
in /bitnami/wordpress/wp-config.php:190\ [Tue Oct 03 10:01:15.571700 2023] 
[authz_core:error] [pid 1898:tid 140605862692608] [client **ip_address**:28817] 
AH01630: client denied by server configuration: 
/opt/bitnami/phpmyadmin/index.php
 [Tue Oct 03 15:19:40.073425 2023] [authz_core:error] [pid 2390:tid 
Press [Enter] to continue:
140605787158272] [client **ip_address**:35956] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Did not provide relevant suggestions

### Describe your issue as much as you can

Hi Bitnami,

We're attempting to restore a backup via Total Upkeep plugin. We are making a clone of our WP instance on a subdomain and are using the Total Upkeep Transfer/Restore feature to do so. The destination is a second brand new Lightsail Wordpress instance.

We've followed the file permissions steps here: https://docs.bitnami.com/aws/apps/wordpress/administration/understand-file-permissions/ And confirmed that they are in fact correct using the command line

Still, the backup will not restore due to file permissions:

"Permission denied. Unable to restore the following file: /opt/bitnami/wordpress/index.php"'

The file in question has permissions:

-rw-rw-r-- 1 bitnami daemon 405 Aug 29 15:48 index.php

What should we do?

Thanks,
Will

**Comment by jotamartos** [comment]
Please try to recover the permissions configuration 

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

**Comment by tasteitslight** [comment]
Hi jotamartos, thanks for the help. Unfortunately, after doing as you suggested, it returned the same error:

Permission denied. Unable to restore the following file: /opt/bitnami/wordpress/index.php

**Comment by jotamartos** [comment]
I do not know what WordPress is trying to do with that file. Apache (daemon user and group) has permissions to read and write the file (and delete it if needed) and the entire /bitnami/wordpress and /opt/bitnami/wordpress directories. I suggest you contact the Total Upkeep plugin's developers to know what's wrong with the backup recovery. The plugin is probably trying to create a temp directory/file and it can't do it. You will need to ensure daemon user/group has write permissions over that temp folder.
