### ISSUE TITLE
[SonarQube] The sonarQube image (SonarQube(TM) packaged by Bitnami support ios swift code scanning?

### ISSUE THREAD

**Issue by D3cs3c** [bitnami/vms#1175]
### Describe your issue as much as you can

Hi I would like to ask that is the sonarQube provide code scanning for swift?

**Comment by gongomgra** [comment]
Hi @D3cs3c,

Thanks for using Bitnami. According to the [official SonarQube docs](https://docs.sonarsource.com/sonarqube/9.8/analyzing-source-code/languages/swift/), you need a developer edition license to enable Swift analysis. Please refer to the official SonarQube support team for further help on this.

https://community.sonarsource.com/

I'm closing this ticket as solved.
