### ISSUE TITLE
[WordPress] Http to Https redirection error

### ISSUE THREAD

**Issue by Homedesign-hub** [bitnami/vms#1176]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ddds455-fsdfs-sd5565

### bndiagnostic was not useful. Could you please tell us why?

I don't know how to use it

### Describe your issue as much as you can

Website is not redirecting from http https.
We are using AWS Bitnami LAMP 7.4.30 and we followed the bellow tuturial to create the server on AWS: https://www.youtube.com/watch?v=ec5OQKBKuM8     or   https://www.webhostingforbeginners.net/how-to-setup-aws-lightsail-lamp-instance-for-vanilla-wordpress-sites/

When we go to http://coveti.com/   it says Congratulations! You are now running Bitnami LAMP 7.4.30 in the Cloud.
When we go to https://coveti.com/ it open the website normally.

When we try to install the SSL we run the command  `sudo /opt/bitnami/bncert-tool` and it give us the bellow warnning:
`Warning: Custom redirections were detected in your web server configuration 
files. This tool will not be able to enable/disable redirections.`

**Comment by jotamartos** [comment]
Hi, 

I just access your site and both http and https endpoints are working as expected now. If you continue running into issues, please take a look at our guide to force HTTPS in your site.

https://docs.bitnami.com/general/apps/wordpress/administration/force-https-apache/
