### ISSUE TITLE
ERPnext version 13 how can i create erpnext version 13 on aws by using their AMI. 

### ISSUE THREAD

**Issue by anthonylkm0613** [bitnami/vms#1177]
### Describe your issue as much as you can

ERPnext version 13 - how can i create erpnext version 13 on aws by using their AMI. 

it was okay a few weeks about but seems the AMIs for version 13 has disappeared. only version 14 AMI is available. how can i create the old version?

**Comment by mdhont** [comment]
Unfortunately ErpNext version 13 has been deprecated. However we could share the url for the ErpNext 13 OVA image if you are interested.

**Comment by anthonylkm0613** [comment]
Dear mdhont,
Yes. could you pls share? 
Regards,
Anthony

> Unfortunately ErpNext version 13 has been deprecated. However we could share the url for the ErpNext 13 OVA image if you are interested.

**Comment by jxuUP** [comment]
@mdhont Would greatly appreciate if you could share that. Thanks

**Comment by mdhont** [comment]
You can download it here:

https://downloads.bitnami.com/files/stacks/erpnext/13.9.2-0/bitnami-erpnext-13.9.2-0-linux-debian-10-x86_64.ova 

    md5:ce53c2f692329b6836b8528e49d86467

**Comment by anthonylkm0613** [comment]
hi all, 
i just like to add more comment about the result. basically i use erpnext 14 and install the hr finally. it works well so far.

**Comment by hamzabawumia** [comment]
Please this link is no longer working 

https://downloads.bitnami.com/files/stacks/erpnext/13.9.2-0/bitnami-erpnext-13.9.2-0-linux-debian-10-x86_64.ova

can i get a link for version 13 still.

Thank you.

I just downloaded the newest version 15 but i am unable to install a compartible hrms module. It always gives errors.

**Comment by jotamartos** [comment]
I'm sorry but we deprecated old installers and VMs some time ago and it's not possible to recover that version now. The official hrms module should work in ERPNext 16.x 

https://github.com/frappe/hrms
