### ISSUE TITLE
Wampstack 5.6.40

### ISSUE THREAD

**Issue by cgoguyer** [bitnami/vms#1178]
### Describe your issue as much as you can

Hello,
For an old project I'm looking for the latest wampstack with php 5.6.
Where can I download wampstack 5.6.40-1 ?
Thank you.

**Comment by jotamartos** [comment]
Hi @cgoguyer,

I'm sorry but that package is not available anymore. As you may know, we removed support for the installers several months ago and remove the old installers from our servers too. Please note that PHP 5.6 was deprecated almost 5 years ago.
