### ISSUE TITLE
[Magento] Edit Varnish configuration

### ISSUE THREAD

**Issue by bbosWebServices** [bitnami/vms#1179]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

None given

### bndiagnostic output

Issues shown from the tool not relevant to the question.

### bndiagnostic was not useful. Could you please tell us why?

diagnostic tool did not identify the cause of the issue.

### Describe your issue as much as you can

I need to add the following options to the start script for varnish, and I cant find any documentation, or anywhere that the varnish startup options are being set. How do I add these to the varnish configuration variables?
```
    -p feature=+esi_ignore_other_elements \
    -p feature=+esi_disable_xml_check \
    -p feature=+esi_ignore_https \
```
It would be very handy to have this part of the documentation updated as well. There is very little in the docs about varnish settings for Magento stack on AWS.

**Comment by jotamartos** [comment]
Hi @bbosWebServices,

The start scrips for the different components are stored in the /opt/bitnami/scripts folder. Please edit the `libvarnish.sh` one and set your parameters in the `varnish_opts()` method (bottom of the file). Those arguments are then used when starting the service (/opt/bitnami/scripts/varnish/start.sh file). Remember to restart it after editing the file.

**Comment by bbosWebServices** [comment]
That was just the info that I needed. Thanks a million.
