### ISSUE TITLE
[Wordpress] Converting Bitnami Single site to Multisite

### ISSUE THREAD

**Issue by Mindbowser** [bitnami/vms#1181]
### Describe your issue as much as you can

Hi,
We have large website hosted on GCP with single site worpdress installation, we want to add another subdomain to same Wordpress to manage it effectively form single Wordpress admin, was not able to find relevant docs for the same, so any guidance will be helpful

**Comment by jotamartos** [comment]
This guide will probably be useful for you

https://docs.bitnami.com/general/how-to/combine-wordpress-multisite/

However, please check the WordPress forums to see if there are other alternatives you can follow.

**Comment by Mindbowser** [comment]
We tried above steps and seems as our site is huge its not working for us, the backup of our site when taken using plugin is around 8GB(including media, databases etc), the export option mentioned in the link https://docs.bitnami.com/aws/how-to/combine-wordpress-multisite/ generated 115mb backup but still its not working, any idea what is the best way to convert to multisite?

**Comment by jotamartos** [comment]
Hi @Mindbowser, 

Did you ask the WordPress' developers to know if there is any other way to convert your site or migrate your data as I suggested above? The app's documentation should describe the process.

**Comment by Mindbowser** [comment]
Other way is to use plugins, we used WPStaging Pro and used for backup and restore, problem is it throws error saying backup is created from single site instance and cant be imported to multisite, whats the other way to convert single site bitnami to multisite easily? Like normal wordpress provides easy config changes so expecting same instead usign different bitnami installation.

**Comment by jotamartos** [comment]
>whats the other way to convert single site bitnami to multisite easily?

**Comment by Mindbowser** [comment]
We are confused as Bitnami has single and multi site as different instalaltions, in wordpress we can convert single site to multisite as below
https://pressable.com/knowledgebase/how-to-convert-a-wordpress-site-into-a-multisite/

So can we do same for current bitnami single site setup instead installing multi site stack?

**Comment by jotamartos** [comment]
That's what I meant with the application, that's nothing to do with Bitnami. You can edit the WordPress-related files inside the /opt/bitnami/wordpress folder and convert it to Multisite but please contact the WordPress' developers if you have any questions.
