### ISSUE TITLE
[<AWS>] <Apache service cannot be started>

### ISSUE THREAD

**Issue by IGDGithub2** [bitnami/vms#1182]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3f4b2c04-fdc6-1f5e-3d1e-03d74d18da5b

### bndiagnostic output

  ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible.

[Mariadb]

2023-10-10 13:53:10 3 [ERROR] mysqld: Table './bitnami_wordpress/wp_posts' is
marked as crashed and should be repaired

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Oct 10 13:41:29.231128 2023] [proxy_fcgi:error] [pid 605252:tid
140566008420096] [client **ip_address**:8277] AH01079: failed to make connection
to backend: httpd-UDS
 [Tue Oct 10 13:41:29.330851 2023] [proxy:error] [pid 605253:tid
140566218139392] (2)No such file or directory: AH02454: FCGI: attempt to connect
to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Tue Oct 10 13:41:29.330882 2023] [proxy_fcgi:error] [pid 605253:tid
140566218139392] [client **ip_address**:18086] AH01079: failed to make
Press [Enter] to continue:
connection to backend: httpd-UDS, referer: https://domain.com/



### bndiagnostic was not useful. Could you please tell us why?

The tool was useful for providing base information including syntax issues with httpd.conf attempting to activate baseline modules. Despite researching the issues described in the apache error logs, the service is unable to be started.

### Describe your issue as much as you can

The webserver running on this instance abruptly became unresponsive earlier today (it had previously been running without issue for a little over three months). Upon attempting to restart services while troubleshooting, the apache service was unable to be restarted. There are no other apache services running, the server was upgraded in an attempt to alleviate any potential memory issues (although none were documented), and no services appear to be listening on port 80. Any assistance in getting this resolved would be greatly appreciated.

**Comment by mdhont** [comment]
Did you change any permissions, configuration? Could you try to enable all plugins and see if it solves the issue?

    wp plugin deactivate --all

**Comment by IGDGithub2** [comment]
No permissions were changed. I briefly enabled debugging in the wp-config.php file (and have since disabled as the WordPress site is not accessible), but otherwise did not modify any configurations. Deactivating WordPress plugins does not appear to have change anything. I still receive the message "Failed to start apache: Failed to start apache" on attempting to start the service.

**Comment by jotamartos** [comment]
Seems that gonit is not running. Can you start it?

```
sudo gonit start
sudo gonit status
```

Please note that it takes some time to start. If you can't start Apache after that, you can try getting more information about the error by running this command

```
sudo /opt/bitnami/scripts/apache/start.sh
```
