### ISSUE TITLE
[Joomla 4.3.4 GCP Image] How to Upgrade to the latest PHP version

### ISSUE THREAD

**Issue by jmsarmientopalma** [bitnami/vms#1183]
### Describe your issue as much as you can

I have a warning about the PHP version installed in the VM. 

![image](https://github.com/bitnami/vms/assets/23040160/6d330461-d175-4514-b7af-465349a6084f)

I have tried to update it, but I have not been able to.
My actual PHP version is 8.0.22. Joomla is 4.3.4.

How can I upgrade PHP from the GCP console of the VM ??

Thank you in advance.

**Comment by jotamartos** [comment]
PHP updates can't be applied to a running Bitnami VM. You will need to launch a new VM with the latest version of Joomla! and PHP and migrate your data to that new instance.
