### ISSUE TITLE
Permission issues with updating wordpress  6.32

### ISSUE THREAD

**Issue by DeRespinis** [bitnami/vms#1186]
### Describe your issue as much as you can

I am having permission issues with updating to wordpress 6.32.

The error is :  Could not create dir: /opt/bitnami/wordpress/wp-content/upgrade/wordpress-6.3.2-no-content.

The opt/bitnami/wordpress/wp-content/upgrade directory has 0775 as permissions.
I am able to update all other plugins.

Can you help?
I have run the diagnostic tool
3a8f75cd-2fbc-5ce6-c937-c3a489ef4b46
 
Thanks
Don

**Comment by mdhont** [comment]
Can you reset the permissions for the Wordpress folder:

```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress
sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;
sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
```

**Comment by DeRespinis** [comment]
I have reset permissions as above but i used 0775 and 0664 to remove the 2775 settings.

When trying to update any plugin i now get an error could not remove old plugin for Aill-One, SEP Pro and Google Monster Insights.

Thanks for you help

**Comment by DeRespinis** [comment]
It looks like the file folders in the wp-content still have the permissions set to 2755.  I executed the command as above but the permissions are not changing.  When I use   WinSCP to try to change the permission I get an error code 3 Permission denied.
Can you point me in the right direction to correct it.

**Comment by mdhont** [comment]
The 775 permissions for folders are the expected ones. Does the error say which permissions it needs? I also recommend asking in the WordPress official forum or the plugin developers.  They may have more information regarding this issue.
