### ISSUE TITLE
[WordPress] Failing installation for let's encrypt

### ISSUE THREAD

**Issue by tochimclaren** [bitnami/vms#1188]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

52a965a0-db58-5af2-4b8c-df43396d4d40

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.

```
 total used free shared buff/cache available Mem: 950 452 70 37 427 303 Swap: 
634 78 556
```

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.

```
[Tue Oct 17 12:24:48.660854 2023] [authz_core:error] [pid 12264:tid 
140039757330176] [client **ip_address**:33100] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/solr
 [Tue Oct 17 12:24:53.772325 2023] [authz_core:error] [pid 12532:tid 
140038624904960] [client **ip_address**:33364] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/
 [Tue Oct 17 12:25:03.800650 2023] [authz_core:error] [pid 12532:tid 
140039421949696] [client **ip_address**:34092] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/solr
```

Press [Enter] to continue:
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

The diagnostics didn't point out where the errors just suggestions.

### Describe your issue as much as you can

I am try to install let's encrypt with sudo /opt/bitnami/bncert-tool, but it's not working.

I get the below error

Error: There has been an error.
Cannot bind to port 80 and/or 443. These ports are used for Let's Encrypt to 
verify the domain DNS configuration. Please stop any services using those ports, 
and ensure your system user has permissions to bind to them.
Press [Enter] to continue:

**Comment by jotamartos** [comment]
Hi @tochimclaren,

I can see this error within the information the tool obtained 

```
-----------------------------------
Get the ctlscript status
-----------------------------------
Running: ./ctlscript.sh status
In: /opt/bitnami

Output:


Control file '/etc/gonit/gonitrc' does not exists
```

Did you remove the gonit directory or similar? Please note that gonit is required to monitor and manage the services. You can try to start it or get more information about it by running these commands 

https://github.com/bitnami/vms/issues/1166#issuecomment-1744346950

In case you continue running into issues, you can follow the alternative approach and stop/start apache using the start.sh/stop.sh scripts

```
sudo /opt/bitnami/scripts/apache/stop.sh
sudo /opt/bitnami/scripts/apache/start.sh
```

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by tochimclaren** [comment]
@jotamartos I ran the command 

`sudo gonit start`

'/etc/gonit/gonitrc' does not exists

And No, I didn't delete any file/directory

**Comment by tochimclaren** [comment]
I tried the alternate method and got this error.

acme: error presenting token: could not start HTTPS server for challenge: listen tcp :443: bind: address already in use

**Comment by jotamartos** [comment]
>acme: error presenting token: could not start HTTPS server for challenge: listen tcp :443: bind: address already in use

Did you stop Apache before running the command? 

```
sudo /opt/bitnami/scripts/apache/stop.sh
```

If you continue running into issues with gonit, I suggest you migrate your data to a new instance and configure the SSL certificate in that new deployment 

https://docs.bitnami.com/general/how-to/migrate-wordpress/

**Comment by tochimclaren** [comment]
This didn't fix the issue.

**Comment by jotamartos** [comment]
The command I posted above should stop Apache and you should be able to run the `lego` command. If that's not the case, you probably installed a different Apache server (not the Bitnami's one) and that's preventing you to run the lego command. Please investigate and stop any Apache server that is running in your instance. As I mentioned above, if you continue running into issues, you can migrate your data to a new server 

https://docs.bitnami.com/general/how-to/migrate-wordpress/
