### ISSUE TITLE
[Redmine] <Installing 3rd party Theme>

### ISSUE THREAD

**Issue by ETOMYE** [bitnami/vms#1189]
### Describe your issue as much as you can

purchased a 3rd party theme (bestredminetheme.com) and wanted to install as described at their website.
-> create "themes" folder inside /bitnami/redmine/public/
-> copy all files into /themes/themefoldername
-> go to Administration/Settings/Display inside Redmine and choose new Theme (without restart of redmine)

1) created folder with root user
2) moved all theme files into /themes/themename/ with root user
and thats it. no matter what i do redmine is not showing my newly added theme inside the GUI.

please help.
Dont know if this is a permission issue (currently all files inside the themes folder have permissions bitnami:daemon)

Thanks

**Comment by mdhont** [comment]
Could you check this guide:

https://docs.bitnami.com/virtual-machine/apps/redmine/configuration/install-plugins/

**Comment by ETOMYE** [comment]
hey

its for installing plugins but as requested i did it for installing my theme.

following is the output:

bitnami@debian:/bitnami/redmine$ bundle install
Bundle complete! 44 Gemfile dependencies, 75 gems now installed.
Gems in the groups 'development', 'sqlite' and 'test' were not installed.
Bundled gems are installed into `../../opt/bitnami/redmine/vendor/bundle`
bitnami@debian:/bitnami/redmine$ bundle exec rake redmine:themes NAME=zenmine RAILS_ENV=production                                   rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/bitnami/redmine/bin/bundle:108:in `load'
/opt/bitnami/redmine/bin/bundle:108:in `<main>'
(See full trace by running task with --trace)
bitnami@debian:/bitnami/redmine$

still not able to change Display - Theme in redmine settings

**Comment by voodoo84** [comment]
Don't do it as root user. Change dir to /opt/bitnami/redmine/public, there should already be "themes" folder owned by bitnami:daemon, change to it and unzip the theme right there (unzip /path/to/theme.zip), it will inherit ownership.

After that, change to /opt/bitnami and run sudo ./ctlscript.sh restart apache

**Comment by ETOMYE** [comment]
very much thank you

i did as requested but in the wrong folder
i was in /bitnami/redmine ...
