### ISSUE TITLE
[Wordpress] EC2 Instance Dies Weekly Until Restart Services

### ISSUE THREAD

**Issue by stewartjp98** [bitnami/vms#119]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

662690cf-e784-0a76-60d2-ba397f4236fc

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Jul 14 02:30:26.561606 2022] [proxy_fcgi:error] [pid 20419:tid
______________] [client **ip_address**:2478] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown                 
on line 0', referer:
https://www._____________.com/wp-admin/post.php?post=25393&action=edit&classic-                 e
Press [Enter] to continue:
ditor
 [Thu Jul 14 02:31:10.537340 2022] [proxy_fcgi:error] [pid 20418:tid
______________] [client **ip_address**:2481] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer:
https://www._____________.com/wp-admin/post.php?post=25393&action=edit&classic-e
ditor
 [Thu Jul 14 02:40:48.250413 2022] [autoindex:error] [pid 20420:tid
______________] [client **ip_address**:58384] AH01276: Cannot serve directory
/opt/bitnami/wordpress/wp-admin/css/: No matching DirectoryIndex
(index.html,index.html,index.htm,index.php) found, and server-generated
directory index forbidden by Options directive, referer: binance.com

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Resources]

Your instance has little available RAM memory.
```
Press [Enter] to continue:
 total used free shared buff/cache available Mem: 1965 892 228 58 844 860 Swap:
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Following the resources suggested did not solve the issue.

### Describe your issue as much as you can

About six months ago a problem developed where WordPress would crash on my EC2 instance every week. Everything would come back fine when I restarted services. I used the diagnostic tool which had a suggestion about not enough ram. So I went up from a T3.micro instance to a T3a.small instance. However, the problem persists. It now seems to be happening more than once a week, and I am getting worries about website downtime between times when I can monitor for outages. Please help!

**Comment by mdhont** [comment]
The apache log shows this error:

```
[core:error] [pid xxxxx      :tid 139810505090816] [client xxx.xxx.xxx.xx:56766] AH102      44: invalid URI path (/cgi-bin/.%2e/%2e%2e/%2e%2e/%2e%2e/      %2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/hosts)
[pid xxxxx      :tid 139810756871936] [client xxx.xx.xx.xxx:56806] AH102      44: invalid URI path (/cgi-bin/.%2e/%2e%2e/%2e%2e/%2e%2e/      %2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/hosts)
```

This seems like a failed hacking attempt, trying to read the content of the /etc/hosts file. I recommend the following guide to prevent bot attacks:

https://docs.bitnami.com/aws/apps/wordpress-multisite/troubleshooting/deny-connections-bots-apache/

**Comment by stewartjp98** [comment]
I followed the guide, but all of the IP addresses that had high traffic seemed legit. Site is still dropping out. Any other ideas?
