### ISSUE TITLE
[Bitnami Redmine] New to supporting Redmine

### ISSUE THREAD

**Issue by SATOIT** [bitnami/vms#1191]
### Describe your issue as much as you can

New to supporting Bitnami Redmine, and could use some advice/direction. 

1. Can a company get paid support for Bitnami Redmine?
2. When moving from an older version (OVA/VM) to a newer version, how difficult is it to do? Should you step up or can you go from an older version to the latest?
3. Cautions/Comments

**Comment by mdhont** [comment]
> Can a company get paid support for Bitnami Redmine?

Unfortunately we don't offer paid support. 

> When moving from an older version (OVA/VM) to a newer version, how difficult is it to do? Should you step up or can you go from an older version to the latest?

It depends on how big the difference between versions is. If it's a big difference I recommend asking in an official Redmine forum for more complicated migrations. For small version upgrades you could check this guide:

https://docs.bitnami.com/general/apps/redmine/administration/upgrade/
