### ISSUE TITLE
[EJBCA] <Where to get superadmin.p12 ?>

### ISSUE THREAD

**Issue by H0H023** [bitnami/vms#1195]
### Describe your issue as much as you can

As I already download the EJBCA-CE 8.0 vm and set it up, and able to access (http://[IP-address]/ejbca/ra). But how can i find the superadmin.p12 file inside the VM . Thanks.

**Comment by jotamartos** [comment]
Hi, 

we configure a user and password to access the application and you can download the certificates once you are logged in. Please remember to use https when connecting to the ra endpoint

![Screenshot 2023-10-26 at 11 43 36](https://github.com/bitnami/vms/assets/8791635/c335d793-c795-4e11-91fc-6d96209b8201)

If you want to add new users, you can use the ejbca.sh script and follow the instructions to create it. Please take a look at the EJBCA's official documentation to know more about how to use it and achieve what you want. 

Thanks

**Comment by H0H023** [comment]
Hi, I try to access the link of _~/ejbca/ra/enrollwithusername.xhtml_ but seems that i cannot access it ..
![Screenshot from 2023-10-31 04-16-05](https://github.com/bitnami/vms/assets/30891988/a67f6c44-e441-41bf-8200-3c6d2b0726c1)

**Comment by jotamartos** [comment]
>Please remember to use https when connecting to the ra endpoint

It seems you didn't use https when accessing the application. You will get the different login options when using https
