### ISSUE TITLE
[WordPress High Availability]  AMI are no longer available and can no longer auto-scale

### ISSUE THREAD

**Issue by mick-t** [bitnami/vms#1196]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a450b8b4-096d-b7f7-84cc-9c7ada30deaa

### bndiagnostic was not useful. Could you please tell us why?

It is a great tool, but not useful for this use case

### Describe your issue as much as you can

Autoscaling stopped working,  instance info shows the following:

>EC2 can't retrieve the name because the AMI was either deleted or made private.

AWS warning email shows:

```
Service: AWS Auto Scaling
Time: 2023-10-23T20:37:38.345Z
RequestId: **************************
Event: autoscaling:EC2_INSTANCE_LAUNCH_ERROR
AccountId: **********
AutoScalingGroupName: WordPress-HA-by-Bitnami-test-WordPressStack
AutoScalingGroupARN: arn:aws:autoscaling:us-west-2:100838840082:*************************
ActivityId: *****************************
Description: Launching a new EC2 instance.  Status Reason: Not authorized for images: [ami-02b342430c1a5fe32]. Launching EC2 instance failed.
Cause: At 2023-10-23T20:37:37Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 1 to 2.
StartTime: 2023-10-23T20:37:38.202Z
EndTime: 2023-10-23T20:37:38.000Z
```

Please restore the AMI so that we can make plans to upgrade or migrate to a different solution.

**Comment by gongomgra** [comment]
Hi @mick-t,

Thanks for using Bitnami. Unfortunately, the WordPress High Availability product has been deprecated and we no longer provide support for it. As an alternative, you can use our [WordPress Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/wordpress), which also allows autoscaling the WordPress pods by setting the `autoscaling.enabled` and other `autoscaling.*` settings. Sorry for the inconveniences!

**Comment by mick-t** [comment]
Hi Gonzalo,

Thanks for replying, unfortunately that's not a very useful answer for us and means that moving to a newer AMI involves us having to unexpectedly shift priorities to do so.  Because of this we will be moving to using a different Wordpress solution that is quicker and simpler to deploy. 

Removing the AMI is very inconvenient for us and does not inspire confidence that future Bitnami solutions will have long term support needed for smaller organisations.

Regards

**Comment by gongomgra** [comment]
Hi @mick-t,

Thanks for your message. I'm sorry for the inconveniences it is causing your team, but we don't have enough bandwdith to support that many distribution methods and we chose to focus on our containers and Helm chart solutions for those scenarios requiring autoscaling capabilities. We hope you take a look at our Helm chart in the future!
