### ISSUE TITLE
GCP - VM - WP Multi - Not Starting

### ISSUE THREAD

**Issue by kcoffau** [bitnami/vms#1197]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c3bd45cf-26c6-65a9-c8f7-de014d37272e

### bndiagnostic output

   ? Wordpress: Found possible issues
- Ran Fix
    ? Mariadb: Found possible issues
-??
    ✓ Resources: No issues found
    ✓ Php: No issues found
    ? Apache: Found possible issues
-??
    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
- false alarm
 

### bndiagnostic was not useful. Could you please tell us why?

ran guides, couldnt determine resolution

### Describe your issue as much as you can

VM stopped operating. Restarted VM, ran diagnostics.  cant identify the source of the issue.

**Comment by mdhont** [comment]
I recommend disabling all plugins and check if that fixes the issue. If so, reenable them one by one to find out which one is causing the error.

    wp plugin deactivate --all
