### ISSUE TITLE
[WordPress] Lightsail Issue website not running 

### ISSUE THREAD

**Issue by rishabhtrumould** [bitnami/vms#1198]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

96948f38-2833-dbee-ff5a-b977152dc621

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-10-25 5:31:05 0 [ERROR] Aborting

Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

Another installation of MariaDB is running:
mysql 668 0.0 4.8 1411352 97352 ? Ssl 05:04 0:00 /usr/sbin/mariadbd root 1601 
0.0 0.0 6372 640 pts/0 S+ 05:35 0:00 grep mysql
If Bitnami MariaDB isn't starting this is the most likely cause. Please run the 
following command to stop it:

[Processes]

One or more component's processes are not running:
Press [Enter] to continue:
apache not running mariadb not running php-fpm not running
You can try to restart the process with the following command:
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Apache]
Found recent error or warning messages in the Apache error log.
[Wed Oct 25 04:42:13.756143 2023] [proxy_fcgi:error] [pid 963327:tid 
140508571625216] [client **ip_address**:57357] AH01079: failed to make 
connection to backend: httpd-UDS, referer: 
https://trumould.com/lp/?gclid=EAIaIQobChMIgta7g7CQggMV3qlmAh1ooA2sEAAYBCAAEgIy5P
D_BwE
 [Wed Oct 25 04:43:37.127133 2023] [proxy:error] [pid 963615:tid 
140509198944000] (2)No such file or directory: AH02454: FCGI: attempt to connect 
to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Wed Oct 25 04:43:37.127166 2023] [proxy_fcgi:error] [pid 963615:tid 
140509198944000] [client **ip_address**:51751] AH01079: failed to make 
connection to backend: httpd-UDS

Press [Enter] to continue:
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
Please check the configuration.
 

===== End of bndiagnostic tool output =====


### bndiagnostic was not useful. Could you please tell us why?

Do not know how to debug issues in apache, mariadb and connectivity

### Describe your issue as much as you can

My website trumould.com that was hosted was working fine and suddenly saw a 503 error. I restarted the server and then could not connect to the server using public Ip or using the domain name. When I ssh'ed into the server I am seeing these errors

**Comment by jotamartos** [comment]
> Found recent error messages in the MariaDB error log:
> 
> ```
> 2023-10-25 5:31:05 0 [ERROR] Aborting
> ```
> 
> Please check the following guide to troubleshoot MariaDB issues:
>  
> https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
> ariadb/
> 
> Another installation of MariaDB is running:
> 
> ```
> mysql 668 0.0 4.8 1411352 97352 ? Ssl 05:04 0:00 /usr/sbin/mariadbd root 1601 
> 0.0 0.0 6372 640 pts/0 S+ 05:35 0:00 grep mysql
> ```

As the tool found, it seems there is another MariaDB process running in the VM. You will need to stop and disable it 

```
sudo service mariadb stop
sudo systemctl disable mariadb
```

If that doesn't stop the process, please take a look at the documentation of the package you installed in the system. Once it's stopped, please try to start the Bitnami's one again 

```
sudo /opt/bitnami/ctlscript.sh start
```

If the Bitnami's MariaDB doesn't start, please take a look at the log file to know more about the issue 

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-mariadb/
