### ISSUE TITLE
[WordPress With NGINX And SSL Packaged By Bitnami For AWS Cloud] <500 Error while publishing a post, Updating themes or plugins>

### ISSUE THREAD

**Issue by vgnavada** [bitnami/vms#1199]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1bec5b45-6898-9100-52b1-039cdff10b3d

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ? Nginx: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem Size Used Avail Use% Mounted on /dev/nvme0n1p1 32G 25G 5.3G 83% /
```
Please check your cloud provider's documentation for more information.

[Connectivity]
Press [Enter] to continue:

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-10-25 7:14:16 6 [Warning] Aborted connection 6 to db: 'bitnami_wordpress' 
user: 'bn_wordpress' host: '**ip_address**' (Got an error reading communication 
packets)

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Nginx]

Found recent error or warning messages in the Nginx error log.
Press [Enter] to continue:
```
2023/10/25 06:53:14 [error] 687#687: *13380 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET /php.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "3.110.22.245"
 2023/10/25 06:53:14 [error] 687#687: *13382 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET /test.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "3.110.22.245"
 2023/10/25 07:14:16 [error] 676#676: *9 recv() failed (104: Connection reset by 
peer) while reading response header from upstream, client: **ip_address**, 
server: _, request: "GET /news/coastal/ky-2/ HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "karavalixpress.com"

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

[Wordpress]

Some files don't have the expected permissions Please check the following guide:
Press [Enter] to continue:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

Found recent WordPress plugin related error messages in the Nginx error log.
```
2023/10/25 06:36:37 [error] 685#685: *10268 recv() failed (104: Connection reset 
by peer) while reading response header from upstream, client: **ip_address**, 
server: _, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "karavalixpress.com", 
referrer: "https://karavalixpress.com/wp-admin/update.php?action=upload-plugin"

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

More details mentioned below

### Describe your issue as much as you can

Hello,

The website front end is loading properly, Even the WP-ADMIN is working.

But when we try to create a post, It shows a 500 error.
![image](https://github.com/bitnami/vms/assets/113204610/ca13ec55-4eea-406c-8184-9248d7f04f49)

The same is true if we try to update any themes/plugins.
Please check why this is happening and help us resolve this.

**Comment by vgnavada** [comment]
Hi . @jotamartos 
Any updates? We really need your help 😭

**Comment by vgnavada** [comment]
Hi @jotamartos any update?

**Comment by jotamartos** [comment]
Hi @vgnavada,

What changes did you make in the application lately? I suggest you disable the plugins and themes (you can rename those folders) and check if the application works properly after that. The issue seems to be in the app itself. 

I can see all services are up and running so that shouldn't be the issue. You also have enough disk space and memory for the application to run.
