### ISSUE TITLE
Failed to start bitnami service ++

### ISSUE THREAD

**Issue by siri-guru-mat** [bitnami/vms#1200]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

NA

### bndiagnostic output

NA

### bndiagnostic was not useful. Could you please tell us why?

Issue is upon boot

### Describe your issue as much as you can

[Screencast from 26. okt. 2023 kl. 15.55 +0200.webm](https://github.com/bitnami/vms/assets/86147566/869e8b3c-b012-40c0-b2c1-3e347146ba05)

**Comment by siri-guru-mat** [comment]
![image](https://github.com/bitnami/vms/assets/86147566/1bace0ef-2e70-4fd3-a7b7-da1c46b22ada)

**Comment by siri-guru-mat** [comment]
![image](https://github.com/bitnami/vms/assets/86147566/73afa726-ddfb-41de-9226-7ac9c0bd799c)

**Comment by siri-guru-mat** [comment]
![image](https://github.com/bitnami/vms/assets/86147566/7809f078-f327-4f9a-bb10-a4bf3e53399e)

**Comment by mdhont** [comment]
Could you please describe the issue and use a descriptive title?

**Comment by siri-guru-mat** [comment]
Descriptive title updated.
The video capture has all i can give for describing the issue.
..it does not load any further than in the video.

**Comment by mdhont** [comment]
Could you download any other application's OVA and see if that does work?

For example Joomla:

https://bitnami.com/stack/joomla/virtual-machine

**Comment by siri-guru-mat** [comment]
![image](https://github.com/bitnami/vms/assets/86147566/b355f21a-2465-42f5-bb89-456845323a54)

**Comment by siri-guru-mat** [comment]
I must say that was a success! :)

**Comment by siri-guru-mat** [comment]
![image](https://github.com/bitnami/vms/assets/86147566/f777ae9a-8ad7-493c-8a8c-6c3f425777c2)

**Comment by siri-guru-mat** [comment]
The import must have corrupted the other?

**Comment by siri-guru-mat** [comment]
I ended up on DigitalOcean instead so now worries...
