### ISSUE TITLE
[WordPress (Lightsail)] Where can I find the changelog?

### ISSUE THREAD

**Issue by mikalehmann** [bitnami/vms#1203]
### Describe your issue as much as you can

Is there a changelog for the Lightsail version and if yes where can I find it? I'd like to take a look at it before switching from PHP 8 to 8.2 when WP 6.4 is ready.

**Comment by gongomgra** [comment]
Hi @mikalehmann,

Thanks for using Bitnami. You can find the changelog for our AWS images in the next link

https://bitnami.com/stack/wordpress/amidebian-x64-hvm-ebs-nami/changelog.txt

**Comment by mikalehmann** [comment]
Thank you. So am I seeing this correctly that Lightsail is always a few versions behind to ensure stability?

**Comment by gongomgra** [comment]
Hi @mikalehmann,

Thanks for your message. I'm afraid I don't know the answer to that question. We send both updated images (EC2 and Lightsail) to AWS teams at the same time, but the Lightsail team usually takes a bit longer to ingest our images. You will have to ask the Lightsail support team about this, as they control the publish steps.
