### ISSUE TITLE
Wordpress login loop

### ISSUE THREAD

**Issue by WorkoutforHappiness** [bitnami/vms#1204]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bfc9ed81-0989-ff49-5f86-0cfecd8bac60

### bndiagnostic was not useful. Could you please tell us why?

could not find the solution

### Describe your issue as much as you can

Hi there, 

I can't access the Wordpress dashboard anymore. It is in a constant wp-login.php loop.

it seems that it has something to do with the mariadb.

in the my.conf I have the following adjustments otherwise the homepage is absolutely down.

If I change the user to root the page is down
if I change the the number 5 to 0 or 1 or delete the whole phrase the page is down:  innodb_force_recovery=6  

I really need to access the dashboard of Wordpress again so we can make changes to our homepage:
And the database has only reading right, I could not change something in the database with phpadmin

we would appreciate your help, since we are extremely worried to lose our page.

my.con:

[mysqladmin] 
user=bn_wordpress 
 
[mysqld] 
innodb_force_recovery=6 
skip_name_resolve 
explicit_defaults_for_timestamp 
basedir=/opt/bitnami/mariadb 
port=3306 
tmpdir=/opt/bitnami/mariadb/tmp 
socket=/opt/bitnami/mariadb/tmp/mysql.sock 
pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid 
max_allowed_packet=16M 
bind_address=127.0.0.1 
log_error=/opt/bitnami/mariadb/logs/mysqld.log 
slow_query_log=0 
slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log 
long_query_time=10.0 
character_set_server=utf8 
collation_server=utf8_general_ci 
plugin_dir=/opt/bitnami/mariadb/lib/plugin 
 
[client] 
port=3306 
socket=/opt/bitnami/mariadb/tmp/mysql.sock 
default_character_set=utf8 
plugin_dir=/opt/bitnami/mariadb/lib/plugin 
 
[manager] 
port=3306 
socket=/opt/bitnami/mariadb/tmp/mysql.sock 
pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid 
!include /opt/bitnami/mariadb/conf/bitnami/memory.conf

**Comment by mdhont** [comment]
It seems your instance is running low on resources (RAM). So I recommend upgrading to a more powerful instance. You can also disable the plugins and then enable them one by one to see if there is one or more plugins that use a lot of memory.
