### ISSUE TITLE
ERPnext login error

### ISSUE THREAD

**Issue by keosh1** [bitnami/vms#1207]
### Describe your issue as much as you can

after install ERPNext latest version and use this code 
sudo cat /home/bitnami/bitnami_credentials
to see the login username and password
and login with username: user@example.com and password in the screen and cant login to ERPNext page

**Comment by gongomgra** [comment]
Hi @keosh1 ,

Thanks for using Bitnami. Can you run the bndiagnostic tool and share the generated code with us so we can take a look at ERPNext logs?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by keosh1** [comment]
done 
diag code is : 
![Untitled](https://github.com/bitnami/vms/assets/106485828/e1166bfa-936b-460a-aacd-7f14d403b8a3)
0b242af3-d83a-ab01-b3a3-b90090a9e614

**Comment by gongomgra** [comment]
Hi @keosh1,

Thanks for your message. I can't find any related error in the logs files included in the bndiagnostic bundle. Can you check if there is any error in the `/opt/bitnami/var/log/first-boot.log` file?
