### ISSUE TITLE
How to add R kernel to JupyterHub

### ISSUE THREAD

**Issue by pvc2** [bitnami/vms#1208]
### Describe your issue as much as you can

I used image of virtual machine fo jupyterhub. It works OK. But I could not add new kernel (like R). The new kernel was not showed in the list of kernels. Could anyone have me to solve this situation

**Comment by gongomgra** [comment]
Hi @pvc2,

Thanks for using Bitnami. In order to get the Jupyterhub's R kernel working on your instance, you will have to manually install the R language and the R Kernel. You can follow official docs for this

https://irkernel.github.io/requirements/

Hope it helps!

**Comment by pvc2** [comment]
Thank you!
I followed your instruction, but  it not works. The R symbon is not showed in list. Remember that I mentioned about Bitnami Jupyterhub ( Debian virtual machine)

**Comment by gongomgra** [comment]
Hi @pvc2,

You will have to follow the official guide on this. According to it, you need manually install the R language on your server before installing the Jupyterhub's RKernel. You can get more information on this in the guide linked below

https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Installing-R-under-Unix_002dalikes
