### ISSUE TITLE
[Akeneo - EC2] Settings for Sending Emails through SES

### ISSUE THREAD

**Issue by scottysmalls** [bitnami/vms#1209]
### Describe your issue as much as you can

My emails seem to fail without error. I have been testing using the 'forgot password' button on login. I followed instructions on https://docs.bitnami.com/aws/apps/akeneo/configuration/configure-smtp/

My only .env change: 
MAILER_URL=smtp://email-smtp.us-east-1.amazonaws.com:587?encryption=tls&auth_mode=login&username=MY_SES_SMTP_USERNAME&password=MY_SES_SMTP_PASSWORD&sender_address=noreply@mydomain.com

email and domain are SES verified

Is this a formatting issue? Must other .env settings be changed? I see MAILER_DNS and MAILER_FROM - are they relevant? 

If there is a place where might one find logs giving more information as to why emails are failing I might be able to provide additional details; however so far I have found logs in opt/bitnami/apache and /var/log without any luck

**Comment by gongomgra** [comment]
Hi @scottysmalls,

Thanks for using Bitnami. We have a getting started guide on how to configure apps with AWS SES service, can you check it in case it is of help?

https://docs.bitnami.com/aws/how-to/use-ses/

If you can't find a solution to your problem in our guide, please open a new question in the official Akeneo community forums, where people with more knowledge about the application than us will help you

**Comment by scottysmalls** [comment]
Thank you for the response. 

I have already used this page in setting up SES. Is it possible to comment on whether the string provided looks correct? The guide admits "The procedure to do this varies from application to application, but typically...." - It would be very helpful, possibly to others as well, if there was somewhere it made clear - _In Akeneo,. your changes to .env should look like this: "XXXX"_ as Akeneo does not have an application interface for these settings and there are many ways to do it incorrectly

Also, is there any comment as to whether there are additional locations for logs where i might better debug this problem?

**Comment by gongomgra** [comment]
Hi @scottysmalls,

Thanks for your message. The `MAILER_URL` setting your provided looks fine according to our [docs](https://docs.bitnami.com/aws/apps/akeneo/configuration/configure-smtp/). Did you restart the Bitnami services just in case it is needed for Akeneo to reload the updated config?

```
sudo /opt/bitnami/ctlscript.sh restart
```

Regarding the logs, Akeneo writes several logs file under the `/opt/bitnami/akeneo/var/logs` directory. You can also check Apache's log files at `/opt/bitnami/apache/logs`.
