### ISSUE TITLE
[Roundcube] Windows Installer Availability?

### ISSUE THREAD

**Issue by vidiot1969** [bitnami/vms#121]
### Describe your suggestion as much as you can

Hi.  For many years, the installer for Roundcube on Windows was available, but now I see it only for MacOS.   Is this an omission, or is it coming back?  

Thanks

**Comment by jotamartos** [comment]
Hi @vidiot1969,

As explained in [this blog post](https://blog.bitnami.com/2021/04/amplifying-our-focus-on-cloud-native.html), we removed support for most of native installers in our catalogue. If you want to deploy the solution locally, you will need to use the Virtual Machines we provide in the bitnami.com site. 

Thanks
