### ISSUE TITLE
upgrading php on google cloud

### ISSUE THREAD

**Issue by rubysarda** [bitnami/vms#1214]
### Describe your issue as much as you can

How do I upgrade PHP on WordPress image on Google Cloud

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually. Instead, we recommend launching a new image with the latest versions and migrate your data there.

**Comment by rubysarda** [comment]
thanks
