### ISSUE TITLE
[WordPress] Multiple Errors in AWS Lightsail

### ISSUE THREAD

**Issue by hhaxim** [bitnami/vms#1215]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8035592a-c654-66c1-c6a0-92f708a311a2

### bndiagnostic output

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 950 317 63 0 569 453 Swap: 0 0 
0
```
Press [Enter] to continue:
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-11-06 3:31:37 0 [ERROR] InnoDB: Could not find a valid tablespace file for 
mysql/innodb_table_stats. Please refer to 
https://mariadb.com/kb/en/innodb-data-dictionary-troubleshooting/ for how to 
resolve the issue.
Press [Enter] to continue:

```
Please check the following guide to troubleshoot MariaDB issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Wordpress]

Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

Found recent WordPress plugin related error messages in the Apache error log.
```
[Mon Nov 06 01:06:13.579764 2023] [proxy_fcgi:error] [pid 774653:tid 
Press [Enter] to continue:
140089459951360] [client **ip_address**:9200] AH01071: Got error 'or Table 
'bitnami_wordpress.wp_3_options' doesn't exist for query SELECT option_value 
FROM wp_3_options WHERE option_name = 'post_count' LIMIT 1 made by 
require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, 
WP_Hook->apply_filters, _wp_admin_bar_init, WP_Admin_Bar->initialize, 
get_blogs_of_user, WP_Site->__get, WP_Site->get_details, get_
```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Nov 06 01:12:00.845949 2023] [proxy_fcgi:error] [pid 779223:tid 
140089745204992] [client **ip_address**:30188] AH01079: failed to make 
connection to backend: httpd-UDS, referer:
https://reewia.com/wp-admin/themes.php?page=merlin&step=content
 [Mon Nov 06 01:12:01.021876 2023] [proxy:error] [pid 774653:tid 
140089308882688] (2)No such file or directory: AH02454: FCGI: attempt to connect 
to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Mon Nov 06 01:12:01.021908 2023] [proxy_fcgi:error] [pid 774653:tid 
Press [Enter] to continue:
140089308882688] [client **ip_address**:30194] AH01079: failed to make 
connection to backend: httpd-UDS, referer: 
https://reewia.com/wp-admin/themes.php?page=merlin&step=content

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Is was useful. But the guides in the documentation links are not reliable.

### Describe your issue as much as you can

I'm getting multiple errors.

**Comment by jotamartos** [comment]
I can see many permission-related errors in the MariaDB's log 

```
2023-11-06  3:31:37 0 [ERROR] InnoDB: The error means mariadbd does not have the access rights to the directory.
2023-11-06  3:31:37 0 [ERROR] InnoDB: Cannot open datafile for read-only: './bitnami_wordpress/wp_posts.ibd' OS error: 81
2023-11-06  3:31:37 0 [ERROR] InnoDB: Operating system error number 13 in a file operation.
2023-11-06  3:31:37 0 [ERROR] InnoDB: The error means mariadbd does not have the access rights to the directory.
2023-11-06  3:31:37 0 [ERROR] InnoDB: Could not find a valid tablespace file for bitnami_wordpress/wp_posts. Please refer to https://mariadb.com/kb/en/innodb-data-dictionary-troubleshooting/ for how to resolve the issue.
2023-11-06  3:31:37 0 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
2023-11-06  3:31:37 0 [Note] Server socket created on IP: '127.0.0.1'.
2023-11-06  3:31:37 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.db' doesn't exist
2023-11-06  3:31:37 0 [ERROR] Aborting
```


I understand you accidentally modified that so I suggest you launch a new VM (either locally or in the cloud) and compare the permissions configuration (/opt/bitnami/mariadb folder). You can update the permissions of those files using the chmod and chown commands. 

You can also take a look at old related tickets in this forum to know what other users did to solve similar issues.
