### ISSUE TITLE
Issues with bitnami deployment after revoking SSL

### ISSUE THREAD

**Issue by honijabroni** [bitnami/vms#1216]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a02a079d-39df-d3eb-4342-4b97fd13e3e3

### bndiagnostic was not useful. Could you please tell us why?

not sure where to begin with correcting the issue

### Describe your issue as much as you can

I revoked an SSL cert as website was re-branding and wanted all traffic through a single new URL. After revoking the SSL for the old URL the site went down and I've not been able to get it live again. Any assistance would be greatly appreciated

**Comment by honijabroni** [comment]
any update on looking into this issue? Thanks

**Comment by gongomgra** [comment]
Hi @honijabroni,

Thanks for using Bitnami. I see in your bndiagnostic information that the revocation of the SSL certificate is causing issues in the Apache's configuration as the file is missing. You will have to generate a new SSL certificate for the new URL and update Apache's config to fix the issue. Remember to restart Apache service for changes to take effect

```
AH00526: Syntax error on line 4 of /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile: file '/opt/bitnami/apache/conf/soccertots.ie.crt' does not exist or is empty
```

Hope it helps!
