### ISSUE TITLE
AWS Lightsail - Manually installing wildcard SSL certificate

### ISSUE THREAD

**Issue by AdamLesh** [bitnami/vms#1218]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

224c7797-2dd7-f7e4-89bd-921be99ca3ff

### bndiagnostic output

 ? Resources: Found possible issues    ? Connectivity: Found possible issues    ✓ Mariadb: No issues found    ✓ Processes: No issues found    ✓ Wordpress: No issues found    ✓ Apache: No issues found    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Not my issue

### Describe your issue as much as you can

I'm trying to replace a LetsEncrypt SSL certificate with a wildcard certificate from GoDaddy on an AWS Lightsail Wordpress instance.  I did this several years ago, but I recently migrated the site to the newest Bitnami Wordpress instance and the file structure has completely changed.  I found the usual set of entries that used to be in the apache2.conf now seem to be in a file called bitnami-ssl.conf:

<VirtualHost _default_:443>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/voterizer.org.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/voterizer.org.key"

I uploaded my GoDaddy files to a new folder and updated it as follows (to also include the chainfile):
<VirtualHost 127.0.0.1:443 _default_:443>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/godadwildssl/7c7e8a6e03d3dca3.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/godadwildssl/star_voterizer_org.key"
  SSLCertificateChainFile "/opt/bitnami/apache/conf/bitnami/godadwildssl/gd_bundle-g2-g1.crt"

It seem to ignore my changes and just use the original SSL.  The only way I got it to work was to rename the certfile and cerkey files and replace the LetsEncryple SSL files in that folder.  Then, it seemed to recognize the new wildcard SSL, but when using SSLChecker, it is clear that the chainfile is not being recognized.

"The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. [Learn more about this error](https://www.sslshopper.com/ssl-certificate-not-trusted-error.html). You can fix this by following [GoDaddy's Certificate Installation Instructions](https://www.godaddy.com/help/install-ssl-certificates-16623?sp_hp=B&xpmst=A&xpcarveout=B) for your server platform. Pay attention to the parts about Intermediate certificates."

I assume that the commands I changed in the bitnami-ssl.conf file are either the wrong ones or not the only ones, but I can't find the way to put in the Chainfile line so it will be recognized.

**Comment by AdamLesh** [comment]
Hi,

Apologies for the delayed response.  Yes, I did.  It still does not work.  It seems to ignore the certificates I uploaded unless I replace the LetsEncrypt ones, which does not include the Chainfile.

Thanks!

A

**Comment by mdhont** [comment]
Installing wildcard certificates is not officially documented but I found the following post that could be of help:

https://repost.aws/knowledge-center/lightsail-bitnami-wildcard-ssl-cert

**Comment by jabetong1** [comment]
Any work around or had a success manually install wildcard SSL certificates in bitnami?

**Comment by jotamartos** [comment]
Hi @jabetong1,

If you upload your own certs to the server and replaced the current ones, Apache should start using them after restarting the process. 

If you are using different names for your certs, you will need to modify the "https"-related files inside the /opt/bitnami/apache/conf/vhosts folder and restart the process for the changes to take effect.
