### ISSUE TITLE
Lightsail Instance - Bitnami Application - Website is down! Urgent Help

### ISSUE THREAD

**Issue by burhanidigital** [bitnami/vms#122]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a5ba1d66-76eb-ab6b-8663-874f49126a87

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ? Wordpress: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Jul 15 02:10:22.580673 2022] [ssl:emerg] [pid 5471:tid 140257471400832] 
AH02572: Failed to configure at least one certificate and key for 
burhanidigital.com:443
 [Fri Jul 15 02:10:22.580752 2022] [ssl:emerg] [pid 5471:tid 140257471400832] 
SSL Library Error: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no 
certificate assigned
 [Fri Jul 15 02:10:22.580759 2022] [ssl:emerg] [pid 5471:tid 140257471400832] 
AH02312: Fatal error initialising mod_ssl, exiting.

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Thu Jul 14 13:59:45.503337 2022] [proxy_fcgi:error] [pid 11397:tid 
140365780682496] [client **ip_address**:29825] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://burhanidigital.com/wp-admin/plugin-install.php

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I am not technical so please help me

### Describe your issue as much as you can

My site is not opening! please me get back my site.

**Comment by burhanidigital** [comment]
Hi i have fixed it so please don't work on this now.

**Comment by juliendargaisse** [comment]
@burhanidigital How did you do it please? I got the same issue.
