### ISSUE TITLE
Bitnami AWS Wordpress Site and Database Keeps Crashing

### ISSUE THREAD

**Issue by Yo5he** [bitnami/vms#1221]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d2634cc6-f6aa-bf4c-273b-802c00d36bc6

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ? Processes: Found possible issues
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3930 3069 404 61 456 549 Swap:
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Processes]

One or more component's processes are not running:
```
php-fpm not running
```
You can try to restart the process with the following command:

 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

Press [Enter] to continue:
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Nov 09 13:37:48.662539 2023] [proxy_fcgi:error] [pid 477083:tid
140479932860160] (70007)The timeout specified has expired: [client
**ip_address**:56952] AH01075: Error dispatching request to : (polling)
 [Thu Nov 09 13:39:03.288398 2023] [proxy_fcgi:error] [pid 477088:tid
140479765006080] (70007)The timeout specified has expired: [client
**ip_address**:60612] AH01075: Error dispatching request to : (polling),
referer: https://3.15.235.149/wp-admin/edit.php?post_type=portfolio
 [Thu Nov 09 13:39:12.520374 2023] [proxy_fcgi:error] [pid 477088:tid
140479689471744] (70007)The timeout specified has expired: [client
**ip_address**:24319] AH01075: Error dispatching request to : (polling),
referer: https://3.15.235.149/wp-admin/edit.php?post_type=portfolio

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

Press [Enter] to continue:
===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Remedies the issue but does not fix it.  Need to know the root cause

### Describe your issue as much as you can

Server keeps crashing and I am having to restart mariadb and php-fpm each time to get it to work again.  I need to know why this issue is being caused and how to stop it from happening again.

**Comment by mdhont** [comment]
It seems due to low RAM memory. I recommend upgrading to a more powerful instance. If that's not possible you can also try disabling the Wordpress plugins and then re-enable them one by one to see if there is one that consumes a lot of resources.
