### ISSUE TITLE
[Wordpress] <Missing folder "/opt/bitnami/apps">

### ISSUE THREAD

**Issue by Badge2002** [bitnami/vms#1223]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4422159b-0d76-a85d-2aca-e56efef8414d

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Connectivity: Found possible issues
    ? Resources: Found possible issues
    ✓ Mariadb: No issues found
    ? Wordpress: Found possible issues
    ✓ Processes: No issues found
    ? Nginx: Found possible issues
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Press [Enter] to continue:
Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 914 513 68 61 332 172 Swap:
634 116 518
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

[Wordpress]

Found recent WordPress plugin related error messages in the Nginx error log.
```
2023/11/10 20:22:30 [error] 2020#2020: *61 FastCGI sent in stderr: "PHP message:
PHP Notice: PHP Request Startup: file created in the system's temporary
directory in Unknown on line 0" while reading response header from upstream,
client: **ip_address**, server: _, request: "POST
/wp-admin/update.php?action=upload-plugin HTTP/1.1", upstream:
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "172.172.237.10",
referrer: "http://172.172.237.10/wp-admin/plugin-install.php"

```
Please check the following guide to deactivate plugins:

Press [Enter] to continue:
https://developer.wordpress.org/cli/commands/plugin/deactivate/

[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2023/11/11 00:08:27 [error] 2020#2020: *857 access forbidden by rule, client:
**ip_address**, server: _, request: "GET /.git/config HTTP/1.1", host:
"172.172.237.10"
 2023/11/11 00:08:27 [error] 2020#2020: *858 access forbidden by rule, client:
**ip_address**, server: _, request: "GET /.git/config HTTP/1.1", host:
"172.172.237.10"
 2023/11/11 00:18:17 [error] 2020#2020: *869 access forbidden by rule, client:
**ip_address**, server: _, request: "GET /.env HTTP/1.1", host: "172.172.237.10"

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

na

### Describe your issue as much as you can

Unable to follow any guides relating to setting up Wordpress Multi Site. The directory "/opt/bitnami/apps" is missing so all commands are failing. Google is returning zero results for my issue. Was there a change recently regarding that directory?

**Comment by mdhont** [comment]
The path of the bitnami installations has changed. It is now /opt/bitnami/APP_NAME

**Comment by Badge2002** [comment]
Update the guides please. If the file path has changed then the guides should be updated that same day.

**Comment by Badge2002** [comment]
Sorry correction I'm looking for /opt/bitnami/php detailed in the guide below:

https://docs.bitnami.com/general/apps/mastodon/get-started/understand-default-config-php/

**Comment by mdhont** [comment]
That's a guide for Mastodon. Can you show me the output of the following command:

    sudo la -la /opt/bitnami/

**Comment by Badge2002** [comment]
I thought I was replying to https://github.com/bitnami/vms/issues/1263
