### ISSUE TITLE
[bitnami-mongodb-6.0.5-0-linux-debian-11-x86_64-hvm-ebs-nami] Can not attach backed up volume nor start a new instance with a volume from the a snapshot

### ISSUE THREAD

**Issue by npahucki** [bitnami/vms#1224]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

330a2ec8-0c38-2961-2826-23966a82d8af

### bndiagnostic was not useful. Could you please tell us why?

Who said it was not useful? Why is this field required?

### Describe your issue as much as you can

We are using Bitnami MongoDB 6. We have automated EBS backups of the main volume every 6 hours. With an older version (3.x) of Bitnami MongoDB, we could simply restore a snapshot into a volume and attach it to a running instance to recover data if needed, or simply throw away an existing broken server and quickly bring up a new server based on the last snapshot. After upgrading to MongoDB 6, neither of these things work. Trying to attach or volume to a running instance OR launch a new instance with a volume based off one of the backup snapshots both give a very vague and not at all helpful error message saying: `An error occurred (UnsupportedOperation) when calling the AttachVolume operation: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.`

The same message appears in the web console and the AWS cli `attach-volume` command. 

What is it about this image that is disallowing an attachment of a volume? 

A few notes: 

- The instance was stopped when we tried to attach - and we could not launch an instance with an additional volume based on a snap shot either. 
- The instance we launch and attempt to attach to is the *exact* same specs as the instance on which the snapshot was taken (e.g. not a problem with instance size or incompatible operating systems).

**Comment by npahucki** [comment]
I found the issue, I was using the wrong snapshot, it wasn't the one created from the running server after all.

**Comment by gongomgra** [comment]
Hi @npahucki,

Thanks for your message. I'm glad you fixed your issue!
