### ISSUE TITLE
[WordPress with NGINX and SSL Certified by Bitnami and Automattic] Support new instance in aws marketplace

### ISSUE THREAD

**Issue by kdamsmt** [bitnami/vms#1225]
### Describe your suggestion as much as you can

Hello,
Could you make your package in AWS marketplace be able to support new cpu rather than lock to the old? New instance provide by aws is faster and cost effective if compare to the old.

I have use other software in aws marketplace and their package does not lock to only support old aws instance cpu. They support newest cpu when aws release.

In your package below could you please adjust it to support AMD or AWS Graviton3 processors? such as m7, m6 c6, and c7?

<img width="1082" alt="image" src="https://github.com/bitnami/vms/assets/17005582/82309f7a-6d8f-49ba-8d35-2b40c9f4196a">

**Comment by jotamartos** [comment]
Thank you for reporting this. It seems to be a problem with the AWS Marketplace. If you launch any of the community AMIs we provide, m7 instances are available to launch.

https://bitnami.com/stack/wordpress-pro/cloud/aws/amis

![Screenshot 2023-11-13 at 15 45 30](https://github.com/bitnami/vms/assets/8791635/275e0b83-aab6-493e-b0e1-c8bf37a2939f)

We will investigate and report this to AWS

**Comment by williamgh2019** [comment]
Thank for the reply. I'm waiting for new aws instance type support for Bitnami image. Pls kindly update here once it support new instance than I can change to that new one. Thanks,

**Comment by williamgh2019** [comment]
Hi @jotamartos 

Is your community AMIs has additional charge?

<img width="535" alt="image" src="https://github.com/bitnami/vms/assets/17005582/f48015bb-cc4c-4d32-870b-0e3e43864602">

**Comment by jotamartos** [comment]
No, they are free to use. You will only pay AWS for the usage of the resources.
