### ISSUE TITLE
[Moodle] phpmyadmin - no login form

### ISSUE THREAD

**Issue by joeblackA** [bitnami/vms#1229]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5ad6358d-e74f-1192-263e-1be4108fc8d2

### bndiagnostic was not useful. Could you please tell us why?

I quite sure,the suggestion is not related

### Describe your issue as much as you can

When I'm trying to enable phpmyadmin in a new vm in order to import database, then there is no login form to type login/password

![image](https://github.com/bitnami/vms/assets/150668618/12effda9-d0b5-4d63-98ad-8cb1e06304c3)

**Comment by mdhont** [comment]
On which platform are you running Moodle?

**Comment by joeblackA** [comment]
https://bitnami.com/redirect/to/2393984/bitnami-moodle-4.3.0-r1-debian-11-amd64.ova

**Comment by mdhont** [comment]
With platform I mean, on a Mac, Windows? And VMware Fusion or another hypervisor?

**Comment by joeblackA** [comment]
Virtualbox on windows

**Comment by mdhont** [comment]
Could you try with another browser, to ensure it's not a local issue? If it happens on Chrome could you check the errors in the Developers console?

**Comment by garyhyam** [comment]
This is still an issue on AMI - bitnami-moodle-4.2.3-6-r11-linux-debian-11-x86_64
Is there a fix yet?

**Comment by mdhont** [comment]
Could you follow the steps in this guide?

https://docs.bitnami.com/aws/faq/get-started/access-phpmyadmin/

And try login in at _localhost:8888/phpmyadmin_

If no login form shows, could you check for errors in the Chrome console?

**Comment by garyhyam** [comment]
I have followed this guide but get the same blank page as mentioned by @joeblackA back in November. I only see the phpMyAdmin logo "Welcome to phpMyAdmin". The login form does not load at all, I have tried different browsers as well.

**Comment by jotamartos** [comment]
Hi all, 

I just reproduced the issue and found that a Moodle's specific configuration is preventing phpMyAdmin to work properly.

![Screenshot 2023-12-28 at 11 25 44](https://github.com/bitnami/vms/assets/8791635/e671b8ae-8157-438d-a244-d669912e0d16)

If you edit the `/opt/bitnami/apache/conf/vhosts/moodle-vhost.conf` file and include the phpmyadmin line like this 

```
  RewriteEngine On
  RewriteRule ^/phpmyadmin - [L,NC]
  RewriteRule "(\/vendor\/)" - [F]```
```

and restart Apache, the issue should be fixed 

![Screenshot 2023-12-28 at 11 27 58](https://github.com/bitnami/vms/assets/8791635/066a0fbc-d695-4469-ac75-9f4cb5283c08)

**Comment by garyhyam** [comment]
@jotamartos perfect, that worked a treat. Thank you kind Sir!
