### ISSUE TITLE
[bitnami/SSL] Restarted Lightsail instance, now nothing works

### ISSUE THREAD

**Issue by battenservices** [bitnami/vms#123]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a69de131-3d23-be9a-5f4f-45224676b3aa

### bndiagnostic output

===== Begin of bndiagnostic tool output =====
 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ? Resources: Found possible issues
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Jul 14 20:25:07.171151 2022] [core:error] [pid 22815:tid 140522530268928] 
[client **ip_address**:60566] AH00126: Invalid URI in request 'bin/sh' 'POST 
/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1'
 [Fri Jul 15 00:38:21.016090 2022] [authz_core:error] [pid 28573:tid 
140522253309696] [client **ip_address**:57068] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/index.php
 [Fri Jul 15 02:19:59.048504 2022] [mpm_event:alert] [pid 30952:tid 
140523460356992] (11)Resource temporarily unavailable: AH00480: 
apr_thread_create: unable to create worker thread
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
AH00534: httpd: Configuration error: No MPM loaded.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 482 241 50 5 190 222 Swap: 634 
2 632
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Diagnostic tool is giving Wordpress troubleshooting, website was running on Joomla

### Describe your issue as much as you can

Restarted Lightsail instance, now nothing works. Assuming some form of update as was working fine prior to restart.

Diagnostic tool unhelpful as is giving Wordpress troubleshooting information when website was running on Joomla.
Also not telling me anything I don't already know (i.e. website is not working when it had been prior to restart).

**Comment by mdhont** [comment]
It seems the machine does not have enough RAM for the application to work properly. I recommend upgrading the instance:

https://docs.bitnami.com/aws/faq/administration/change-server-type/

**Comment by battenservices** [comment]
Hi thanks for your response, this instance is running in Lightsail not EC2 (as per my original comment). Specs it is running are as were recommended by Bitnami/AWS on instance creation.

Have rolled back instance to a snapshot from yesterday and apache is now functional again, although bncert will not create a lets encrypt account with lego certbot, so this website instance is still broken.

**Comment by battenservices** [comment]
Sorry, just to clarify, the email am attempting to use that lego certbot  says "account" does not exist for is same one used by this sites original certs (which were issued using bncert) and works with several other sites we manage without issues.

**Comment by mdhont** [comment]
Can you try to issue the certificate manually?

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by battenservices** [comment]
this appears to have worked, will let you know in 90 days :)

**Comment by recena** [comment]
@battenservices Could you review the PR title? It is following the convention.
