### ISSUE TITLE
[Matomo] VM OS upgrade

### ISSUE THREAD

**Issue by radekskl** [bitnami/vms#1231]
### Describe your issue as much as you can

Is there a way to safely upgrade Matomo VM (created from Azure image - https://bitnami.com/stack/matomo/cloud/azure) to Debian 12? Or is there any timeline for release of Debian 12 based image?
There's few CVE's which would be fixed with this upgrade.

**Comment by jotamartos** [comment]
>Is there a way to safely upgrade Matomo VM (created from Azure image - https://bitnami.com/stack/matomo/cloud/azure) to Debian 12?
