### ISSUE TITLE
[<Odoo 15.0.20231110-0>] <Database backup error: Command `pg_dump` not found.>

### ISSUE THREAD

**Issue by ecointegrador** [bitnami/vms#1233]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1e8bc96c-f4b2-107a-ba1e-f017d52c3b2b

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Connectivity: Found possible issues
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ✓ Resources: No issues found

### bndiagnostic was not useful. Could you please tell us why?

I don't know

### Describe your issue as much as you can

When we try to do a backup from website page:

http://x.x.x.x/web/database/backup

Appear the next error:

![image](https://github.com/bitnami/vms/assets/150820805/b6206cf3-4796-461c-bbe2-4505cd58421d)

**Comment by gongomgra** [comment]
Hi @ecointegrador,

Thanks for using Bitnami. Did you modify anything in the Odoo application or its config file before facing these errors? I have not been able to reproduce that error in a fresh new server. I also see you are trying to backup a `test` database. Did you create it? Default Odoo database name is `bitnami_odoo`.

**Comment by ecointegrador** [comment]
Hi @gongomgra ,

I change into the oddo.conf the name of the database for the default name and the error persist:


![image](https://github.com/bitnami/vms/assets/150820805/be84e838-3902-4f22-9f04-bb97ea5016a1)

Any other clue?

This problem appear in other versions of the image of Virtual Machine Odoo 15.0-20231010 same issue.

Other think I did change the path into the odoo.conf file  Pg_path to:

pg_path = /opt/bitnami/postgresql/bin

and appear this other error:

Database backup error: Postgres subprocess ('/opt/bitnami/postgresql/bin/pg_dump', '--no-owner', '--file=/tmp/tmprscdrtd5/dump.sql', 'bitnami_odoo') error 1

**Comment by ecointegrador** [comment]
@gongomgra hola Gonzalo, pudiste mirar algo referente al error?

Como te comentaba en los mensajes anteriores, las ultimas imagenes de Bitnami para Odoo no permiten hacer backup.

**Comment by gongomgra** [comment]
Hi @ecointegrador,

Although we speak Spanish, we prefer to use English language in these support tickets so it can be of help to other users as well.

Regarding the database dump error I have been able to reproduce your issue with Odoo 15.x, but not with 16.x. Trying to manually run the `pg_dump` command it looks to me like Odoo's internal code is not taking into account the database user is `bn_odoo`. I have been able to run the command like below (providing the `db_password` value when prompted):

```
$ mkdir -p /tmp/tmpo7x9l4pq

$ bitnami@ip-172-31-81-98:~$ /opt/bitnami/postgresql/bin/pg_dump --no-owner --file=/tmp/tmpo7x9l4pq/dump.sql -U bn_odoo bitnami_odoo
Password:

$ ls -l /tmp/tmpo7x9l4pq/dump.sql
-rw-r--r-- 1 bitnami bitnami 2827637 Nov 21 17:09 /tmp/tmpo7x9l4pq/dump.sql

$ file /tmp/tmpo7x9l4pq/dump.sql
/tmp/tmpo7x9l4pq/dump.sql: UTF-8 Unicode text, with very long lines
```

Can you try it on your side? In case you can manually run it but not through the Odoo website, we recommend you to open a new ticket in the official Odoo forums, as it seems to be related to the Odoo app itself.

**Comment by ecointegrador** [comment]
Hi @gongomgra 

Of course this commands in shell run wihout problems, my question was about do this on the website:

http://x.x.x.x/web/database/backup

With this I can see you can do a backup and the command run without issue.

And again, Why I can't make this backup from the web?

**Comment by gongomgra** [comment]
Hi @ecointegrador,

As mentioned in my previous message, that seems to be an issue related with the app itself. In fact, there seems to be an issue already open for that

https://github.com/odoo/odoo/issues/139687

Let's see if they fix the issue in their next release.
