### ISSUE TITLE
[WordPress]  .htaccess Issue

### ISSUE THREAD

**Issue by BlackD0C** [bitnami/vms#1235]
### Describe your issue as much as you can

Hi everyone,
I'm trying to update my Wordpress Permalink, it says " Error: Your .htaccess file is not writable, so updating it automatically was not possible. These are the mod_rewrite rules you should have in your .htaccess file. Click in the field and press Ctrl + A (or ⌘ + A on Mac) to select all. "

Additionally, i tried to configure a sitemap using a plugin it said that i need to update .htaccess

I tried.htaccess permissions and edit the file, but every time it changes back.

Tried to configure in apache's settings "AllowOverride All" instead of none but it didn't work.

I read Bitnami's documentation about configuring .htaccess "https://docs.bitnami.com/aws/apps/wordpress/administration/use-htaccess". i've updated the /opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf as documented, but after i restarted Apache .htaccess was remained the same.

If someone knows how to fix it please let me know, i prefer to make .htaccess writable.

wordpress-htaccess.conf is attached
[wordpress-htaccess.conf.txt](https://github.com/bitnami/vms/files/13373437/wordpress-htaccess.conf.txt)

.htaccess was remained the same, and not writable. both ways didn't work.

Thanks in advance!

**Comment by BlackD0C** [comment]
Thanks for your response

Yes, i included this block.
I dont even have access to edit "/wp-admin/options-permalink.php"
It shows the error:
`Error: Your .htaccess file is not writable, so updating it automatically was not possible. These are the mod_rewrite rules you should have in your .htaccess file. Click in the field and press Ctrl + A (or ⌘ + A on Mac) to select all. 
Rewrite rules:
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

`
How can i add this to the configuration if it's not a plugin ?
Do you know if there's any way to make .htaccess editable again?

**Comment by jotamartos** [comment]
Hi @BlackD0C,

The block of code you posted above is not the same one than the one I posted so I suggest you review the configuration included in the wordpress-htaccess.conf file. 

However, to start using the .htaccess files, you can set the allowOverride parameter to all in the wordpress-vhost.conf and wordpress-https-vhost.conf files inside the /opt/bitnami/apache/conf/vhosts folder. Once you do that, please ensure you restart Apache for the changes to take effect and configure the permissions configuration correctly (just to avoid permission issues)

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

If you continue running into issues, please contact the plugin's developer. What I explained above allows the app use the information of the .htaccess, if it continues throwing errors, it's probably something wrong in the validation of the plugin.

**Comment by BlackD0C** [comment]
Hi @jotamartos,

I edited both wordpress-https-vhost.conf and wordpress-vhost.conf files, then i did "sudo chown bitnami:daemon .htaccess" and changed the permissions.
![change](https://github.com/bitnami/vms/assets/58911613/78fc026d-4988-47a0-b78d-7e968945479f)

Unfortunately, the file is being restored with the original file and permissions each time i edit .htaccess



Please let me know if you need any other information, thanks!

**Comment by jotamartos** [comment]
We are not editing the .htaccess file and do not have any process to recover it. Please ask the WordPress support team or disable all the plugins you have to confirm it's not something in the app-side. We also suggest you launch a fresh instance and test the changes there with no other previous change.
