### ISSUE TITLE
[Bitnami and Parse Server] Can't Update Bitnami to Latest Version

### ISSUE THREAD

**Issue by zent-co** [bitnami/vms#1236]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

cdda7720-d0d3-3516-d76b-242062e8f621

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ? Apache: Found possible issues

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 975 375 146 0 453 419 Swap:
634 85 549
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

[Connectivity]

Press [Enter] to continue:
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Nov 17 00:34:37.533128 2023] [proxy_http:error] [pid 80175:tid
140331001571072] [client **ip_address**:50878] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1

[Fri Nov 17 01:43:19.681672 2023] [proxy:error] [pid 83568:tid 140331124700928]
(111)Connection refused: AH00957: http: attempt to connect to
**ip_address**:4040 (127.0.0.1:4040) failed

[Fri Nov 17 01:43:19.681736 2023] [proxy_http:error] [pid 83568:tid
140331124700928] [client **ip_address**:43296] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1

```
Please check the following guide to troubleshoot server issues:
Press [Enter] to continue:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Not to my knowledge. Didn't see anything about not being able to update parse version

### Describe your issue as much as you can

I just created a new Parse Server by Bitnami with AWS. 

I got an email notice that a newer version of Parse/Bitnami was available to update so I gave it a try via the directions at: https://docs.bitnami.com/aws/apps/parse/administration/upgrade/

I received errors that my npm was around version 10 and was incompatible with the node.js version installed on this instance (sorry, don't remember what those version were, but they were the default for the instance). I tried updating npm and node js so that there weren't errors during "npm update -g npm" or "npm install parse-server parse-dashboard"

I eventually got rid of those errors and got what looked like a successful install of parse-server and parse-dashboard. At least all the errors went away... 

However, when I check the parse server version via starting a new SSH sessoin, it reports that the version is still at 6.3.1-3, but I am expecting it to be 6.3.1-7. 

What is going on here? How can I even start troubleshooting this?

Thanks.

**Comment by jotamartos** [comment]
>However, when I check the parse server version via starting a new SSH sessoin, it reports that the version is still at 6.3.1-3, but I am expecting it to be 6.3.1-7.

That's a fixed message. If you want to know the exact Parse and Parse Dashboard version you are running, please run these commands 

```
cd /opt/bitnami/parse
npm list
```

You can also take a look at the Parse Dashboard user interface to get that information.

**Comment by zent-co** [comment]
Seriously? No help on this at all???

**Comment by zent-co** [comment]
That helps out so much, thank you! 

One more question. Do I need to downgrade my node.js version due to the following warnings?

root@ip-XXX-XXX-XXX-XXX:/opt/bitnami/parse# npm install parse-server parse-dashboard
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'parse-server@6.3.1',
npm WARN EBADENGINE   required: { node: '>=14.21.0 <17 || >=18 <19' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.2.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'parse@4.1.0',
npm WARN EBADENGINE   required: { node: '>=14.21.0 <17 || >=18 <20' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.2.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'parse-server@6.4.0',
npm WARN EBADENGINE   required: { node: '>=14.21.0 <17 || >=18 <19' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.2.5' }
npm WARN EBADENGINE }

**Comment by jotamartos** [comment]
Nodejs 20.x is the LTS version and according to the Parse documentation they support the LTS versions of Nodejs. This version was recently moved to LTS but you shouldn't run into any issue when using it.

**Comment by zent-co** [comment]
thank you
