### ISSUE TITLE
[Alfresco] FTP SERVER

### ISSUE THREAD

**Issue by pvc2** [bitnami/vms#1237]
### Describe your issue as much as you can

I am using the Bitnami Alfresco virtual machine distribution. However, I cannot connect to the Alfresco FTP Server even though the configurations have been set up correctly.
 ftp.enabled=true 
 ftp.port=21 
ftp.ipv6.enabled=false 
#ftp.bindto=local_machine_ip 
I would appreciate your help in resolving this situation.

**Comment by jotamartos** [comment]
Please remember to open the ports in the VM 

https://docs.bitnami.com/virtual-machine/faq/administration/use-firewall/
