### ISSUE TITLE
[Wordpress] Failed to start LSB - bitnami init script

### ISSUE THREAD

**Issue by junekuhn** [bitnami/vms#1238]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

861b50b7-554d-fb3c-34fd-d938071ffa6c

### bndiagnostic output

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ✓ Resources: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
    ? Connectivity: Found possible issues
    ? Apache: Found possible issues
    ? Wordpress: Found possible issues
 

 
[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-07-21 8:41:35 210 [Warning] Aborted connection 210 to db: 
'bitnami_wordpress' user: 'bn_wordpress' host: '**ip_address**' (Got an error 
reading communication packets)
Press [Enter] to continue:

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Jul 21 08:11:49.769937 2023] [proxy_fcgi:error] [pid 20498:tid 
139650047829760] [client **ip_address**:52321] AH01071: Got error 'PHP message: 
PHP Notice:  PHP Request Startup: file created in the system's temporary 
directory in Unknown on line 0', referer: 
http://34.147.226.173/wp-admin/admin.php?import=wordpress
Press [Enter] to continue:

[Fri Jul 21 08:41:35.046201 2023] [proxy_fcgi:error] [pid 20870:tid 
139650911885056] [client **ip_address**:23042] AH01067: Failed to read FastCGI 
header, referer: 
http://34.147.226.173/?rest_route=%2Fjetpack%2Fv4%2Fsync%2Ffull-sync&_for=jetpack
&token=JN0lg%28UsxLDBxx%40b1q%28rLp%5EWKP0RIrm%28%3A1%3A0&timestamp=1689928872&no
nce=zHq9t4BMsm&body-hash&signature=EC5I7wM2FT7rmiKwzmMI2KDOdqM%3D

[Fri Jul 21 08:41:35.046255 2023] [proxy_fcgi:error] [pid 20870:tid 
139650911885056] (104)Connection reset by peer: [client **ip_address**:23042] 
AH01075: Error dispatching request to : , referer: 
http://34.147.226.173/?rest_route=%2Fjetpack%2Fv4%2Fsync%2Ffull-sync&_for=jetpack
&token=JN0lg%28UsxLDBxx%40b1q%28rLp%5EWKP0RIrm%28%3A1%3A0&timestamp=1689928872&no
nce=zHq9t4BMsm&body-hash&signature=EC5I7wM2FT7rmiKwzmMI2KDOdqM%3D

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
Press [Enter] to continue:
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.

System Apache is running:
```
root        2515  0.0  0.4   6576  4112 ?        Ss   Nov16   0:04 
/usr/sbin/apache2 -k start
www-data    2609  0.0  0.0   3492   168 ?        Ss   Nov16   0:03 
/usr/bin/htcacheclean -d 120 -p /var/cache/apache2/mod_cache_disk -l 300M -n
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Fri Jul 21 08:10:22.341955 2023] [proxy_fcgi:error] [pid 20870:tid 
139650207291136] [client **ip_address**:52264] AH01071: Got error 'PHP message: 
PHP Notice:  PHP Request Startup: file created in the system's temporary 
directory in Unknown on line 0', referer: 
Press [Enter] to continue:
http://34.147.226.173/wp-admin/plugin-install.php?s=WPGraphQL%2520for%2520Advance
d%2520Custom%2520Fields&tab=search&type=term

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

### bndiagnostic was not useful. Could you please tell us why?

I am a bit new to backend development and am having trouble understanding what to do.

### Describe your issue as much as you can

The payment was declined on Google Cloud Platform and GCP shut off the Wordpress VM instance.  When I restarted everything I go this error.

**Comment by gongomgra** [comment]
Hi @junekuhn,

Thanks for using Bitnami. According to the information you shared from the bndiagnostic tool, you have a configuration error in Apache.

```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```

Please comment-out the mentioned line by adding a `#` character at the beginning of the line, save the file, and restart Apache for changes to take effect.

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

Hope it helps!

**Comment by junekuhn** [comment]
I've commented out that line and saved it, And I got this error
Failed to restart apache: Failed to restart apache

Then commented out line 120 as suggested by the diagnostic tool
Then line 145

I have verified that ports 22, 80, and 443 are accessible from GCP.

This is the current output:



===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
    ? Connectivity: Found possible issues
    ✓ Apache: No issues found
    ✓ Wordpress: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 978 340 140 0 497 476 Swap: 
634 131 502
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

System Apache is running:
```
www-data 2609 0.0 0.0 3492 128 ? Ss Nov16 0:18 /usr/bin/htcacheclean -d 120 -p 
/var/cache/apache2/mod_cache_disk -l 300M -n root 47281 0.0 0.3 6576 3820 ? Ss 
Nov19 0:10 /usr/sbin/apache2 -k start
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:
 

===== End of bndiagnostic tool output =====

**Comment by gongomgra** [comment]
Hi @junekuhn,

Thanks for your message. According to the information you shared you have the Apache server from apt repositories running on your system instead of the Bitnami one. Please disable and stop the service, and/or uninstall the `apache2` package too, and then restart the Bitnami service.

**Comment by junekuhn** [comment]
Thanks so much!

I purged Apache2 and uncommented the lines that I commented before, and everything seems to be working now.
