### ISSUE TITLE
[<ELK>] Connect connect from external host

### ISSUE THREAD

**Issue by KarstenVogt** [bitnami/vms#124]
### Describe your issue as much as you can

Hi,

I just set up a new ELK, working fine. I edited the elasticsearch.yml to listen to external requests. I created 2 new firewall rules to accept incoming messages. Still it won't work.

The IP:
bitnami@debian:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 08:00:27:4a:95:9b brd ff:ff:ff:ff:ff:ff
    inet 10.130.91.41/24 brd 10.130.91.255 scope global dynamic enp0s3
       valid_lft 344688sec preferred_lft 344688sec
    inet6 fe80::a00:27ff:fe4a:959b/64 scope link
       valid_lft forever preferred_lft forever

My elasticsearch.yml:
bitnami@debian:~$ sudo cat /opt/bitnami/elasticsearch/config/elasticsearch.yml
http:
  port: "9200"
path:
  data: /bitnami/elasticsearch/data
transport:
  port: "9300"
action:
  destructive_requires_name: "true"
network:
  host: 0.0.0.0
  publish_host: ::ffff:127.0.0.1
  bind_host: 127.0.0.1
node:
  name: debian
discovery:
  type: single-node
xpack:
  security:
    enabled: "false"
  ml:
    enabled: "false"

Firewall:
bitnami@debian:~$ sudo ufw status
Status: active

To                         Action      From
80/tcp                     ALLOW       Anywhere
443/tcp                    ALLOW       Anywhere
22/tcp                     ALLOW       Anywhere
9200                       ALLOW       Anywhere
5601                       ALLOW       Anywhere
80/tcp (v6)                ALLOW       Anywhere (v6)
443/tcp (v6)               ALLOW       Anywhere (v6)
22/tcp (v6)                ALLOW       Anywhere (v6)
9200 (v6)                  ALLOW       Anywhere (v6)
5601 (v6)                  ALLOW       Anywhere (v6)

Elasticsearch is up:
bitnami@debian:~$ curl localhost:9200
{
  "name" : "debian",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "TqhHtw_xTS2uOO5pGQ8jAw",
  "version" : {
    "number" : "7.17.3",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "5ad023604c8d7416c9eb6c0eadb62b14e766caff",
    "build_date" : "2022-04-19T08:11:19.070913226Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

On my other machine I try to install metricbeat:
root@deb-docker-ccyl:/usr/bin# ./metricbeat setup
Exiting: couldn't connect to any of the configured Elasticsearch hosts. Errors: [error connecting to Elasticsearch at http://10.130.91.41:9200: Get "http://10.130.91.41:9200": dial tcp 10.130.91.41:9200: connect: connection refused]

root@deb-docker-ccyl:/usr/bin# ping 10.130.91.41
PING 10.130.91.41 (10.130.91.41) 56(84) bytes of data.
64 bytes from 10.130.91.41: icmp_seq=1 ttl=64 time=0.874 ms
64 bytes from 10.130.91.41: icmp_seq=2 ttl=64 time=0.825 ms
64 bytes from 10.130.91.41: icmp_seq=3 ttl=64 time=0.937 ms

I can ping the elastic stack IP. Any ideas?

I can't curl the URL from other machines. Ping works though.

**Comment by mdhont** [comment]
Can you try this command?

    curl -XGET 'localhost:9200/'

**Comment by KarstenVogt** [comment]
Hi Michiel,

thank you so much for your reply.

As requested:

bitnami@debian:~$ curl -XGET 'localhost:9200'
{
  "name" : "debian",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "TqhHtw_xTS2uOO5pGQ8jAw",
  "version" : {
    "number" : "7.17.3",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "5ad023604c8d7416c9eb6c0eadb62b14e766caff",
    "build_date" : "2022-04-19T08:11:19.070913226Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

Looks like there is no difference to what I posted above.
