### ISSUE TITLE
[<Wordpress>] <wp-config.php: No such file or directory>

### ISSUE THREAD

**Issue by riseitup** [bitnami/vms#1240]
### Describe your issue as much as you can

I'm using Bitnami WordPress on the Google Cloud platform. update the website to the new WordPress version. it wasn't compatible with the old PHP version. so I deployed a WordPress Bitnami in an instant. tried to use all migrate plugins to restore my backup to the new WordPress. I've got this error: There has been a critical error on this website
it seems all migrate plugins can't restore from the old php ver to the new one.
I tried to debug WordPress to fix the issue but in SSH, I've got this error: cat: /opt/bitnami/apps/wordpress/htdocs/wp-config.php: No such file or directory

would you please help how I can locate my wp-config.php ?
Thanks

**Comment by gongomgra** [comment]
Hi @riseitup,

Thanks for using Bitnami. The `/opt/bitnami/apps/wordpress` folder was deprecated some time ago. The new WordPress installation folder is `/opt/bitnami/wordpress`. You will find the `wp-config.php` file under that directory.

Hope it helps!

**Comment by Badge2002** [comment]
Can you update the guides then? Where else are we getting this information

**Comment by gongomgra** [comment]
HI @Badge2002,

Can you share with us the docs you are using? I checked our website and paths point to `/opt/bitnami/wordpress/wp-config.php` there

https://docs.bitnami.com/google/apps/wordpress/administration/configure-domain/

Hope it helps!
