### ISSUE TITLE
bitnami php.ini file command not found 

### ISSUE THREAD

**Issue by dankings001** [bitnami/vms#1245]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f3bde9d4-28d8-6a6e-4373-c5e53890df39

### bndiagnostic was not useful. Could you please tell us why?

can't find the php file... 

### Describe your issue as much as you can

It's not finding my php.ini file

bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/php/etc/php.ini.
sudo: /opt/bitnami/php/etc/php.ini.: command not found
bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/bndiagnostic-tool

**Comment by Badge2002** [comment]
Join the club. It seems that all the guides are out of date. I have the same issue in my Mastodon server. I can't find the pnp.ini file to setup the email....

**Comment by dankings001** [comment]
Well hopefully they can help...

**Comment by mdhont** [comment]
Could you give more details about what you are trying to achieve, and how that relates to the php.ini?

**Comment by dankings001** [comment]
Hi Sorry... 

I missed this... 

I am trying to do add Redis or Memcache but to do this I need access to the pnp.ini file but I can't find it... 

_"82.5% hit rate (3,785 hits, 801 misses)

Persistent object cache plugin not in use

Speak to your web host about enabling an object cache extension such as Redis or Memcached.:_

Thanks 

Dan

**Comment by mdhont** [comment]
The following guide shows how to add the PHP module for Redis. 

https://docs.bitnami.com/aws/infrastructure/ruby/configuration/install-modules-php/#redis

This should work for all bitnami applications that use the PHP component
