### ISSUE TITLE
[Wordpress] PHP FPM and Mariadb cannot start resulting in error 502

### ISSUE THREAD

**Issue by mark-ideatheorem** [bitnami/vms#1253]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

80330363-1af8-270f-2f42-d5422b18fcf6

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Connectivity: No issues found
    ✓ Resources: No issues found
    ✓ Mariadb: No issues found
    ? Wordpress: Found possible issues
    ? Processes: Found possible issues
    ? Nginx: Found possible issues
    ✓ Php: No issues found
 

 
[Wordpress]

Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

[Processes]

Press [Enter] to continue:
One or more component's processes are not running:
```
mariadb not running php-fpm not running
```
You can try to restart the process with the following command:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2023/11/23 15:11:04 [error] 665#665: *501 connect() to 
unix:/opt/bitnami/php/var/run/www.sock failed (111: Connection refused) while 
connecting to upstream, client: **ip_address**, server: _, request: "POST 
/wp-admin/admin-ajax.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "aoccto.ca", 
referrer: "https://aoccto.ca/wp-admin/post.php?post=86&action=edit"
 2023/11/23 15:13:04 [error] 665#665: *503 connect() to 
unix:/opt/bitnami/php/var/run/www.sock failed (111: Connection refused) while 
connecting to upstream, client: **ip_address**, server: _, request: "POST 
/wp-admin/admin-ajax.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "aoccto.ca", 
Press [Enter] to continue:
referrer: "https://aoccto.ca/wp-admin/post.php?post=86&action=edit"
 2023/11/23 15:15:05 [error] 665#665: *505 connect() to 
unix:/opt/bitnami/php/var/run/www.sock failed (111: Connection refused) while 
connecting to upstream, client: **ip_address**, server: _, request: "POST 
/wp-admin/admin-ajax.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "aoccto.ca", 
referrer: "https://aoccto.ca/wp-admin/post.php?post=86&action=edit"

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I don't know where to start

### Describe your issue as much as you can

nginx runs but php-fpm and mariadb fails to run and I am not sure why

I am getting this error when I run systemctl status bitnami.service

` bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-11-23 15:13:47 UTC; 6min ago
    Process: 40451 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
      Tasks: 3 (limit: 4696)
     Memory: 59.9M
        CPU: 885ms
     CGroup: /system.slice/bitnami.service
             ├─663 nginx: master process /opt/bitnami/nginx/sbin/nginx -c /opt/bitnami/nginx/conf/nginx.conf
             ├─664 nginx: worker process
             └─665 nginx: worker process

Nov 23 15:12:47 AOCC-VM bitnami[40495]: nginx 15:12:47.08 INFO  ==> nginx is already running
Nov 23 15:12:47 AOCC-VM bitnami[40495]: 2023-11-23T15:12:47.089Z - info: Performing service start operation for php
Nov 23 15:13:47 AOCC-VM bitnami[40495]: php 15:13:47.29 ERROR ==> php-fpm did not start
Nov 23 15:13:47 AOCC-VM bitnami[40495]: 2023-11-23T15:13:47.301Z - error: Unable to perform start operation Export start for php failed with exit code 1
Nov 23 15:13:47 AOCC-VM systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
Nov 23 15:13:47 AOCC-VM systemd[1]: bitnami.service: Failed with result 'exit-code'.
Nov 23 15:13:47 AOCC-VM systemd[1]: bitnami.service: Unit process 663 (nginx) remains running after unit stopped.
Nov 23 15:13:47 AOCC-VM systemd[1]: bitnami.service: Unit process 664 (nginx) remains running after unit stopped.
Nov 23 15:13:47 AOCC-VM systemd[1]: bitnami.service: Unit process 665 (nginx) remains running after unit stopped.
Nov 23 15:13:47 AOCC-VM systemd[1]: Failed to start LSB: bitnami init script.`

**Comment by mark-ideatheorem** [comment]
tried to enable mariadb and php-fpm separately, it echoes started but when I check the status it is stopped

**Comment by jotamartos** [comment]
> [Wordpress]
> 
> Some files don't have the expected permissions Please check the following guide:
> 
> https://docs.bitnami.com/general/apps/wordpress/administration/understand-
> file-permissions/

Can you try running these commands to solve the file permissions issue?

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

> tried to enable mariadb and php-fpm separately, it echoes started but when I check the status it is stopped

Regarding this error, can you try to start the services using the start.sh script for each service?

```
sudo /opt/bitnami/scripts/mariadb/start.sh
sudo /opt/bitnami/scripts/php/start.sh
```

They should provide more information about why they are not started.

**Comment by mark-ideatheorem** [comment]
> Can you try running these commands to solve the file permissions issue?
> 
> [#22 (comment)](https://github.com/bitnami/vms/issues/22#issuecomment-1143906974)
> 
> > tried to enable mariadb and php-fpm separately, it echoes started but when I check the status it is stopped
> 
> Regarding this error, can you try to start the services using the start.sh script for each service?
> 
> ```
> sudo /opt/bitnami/scripts/mariadb/start.sh
> sudo /opt/bitnami/scripts/php/start.sh
> ```
> 
> They should provide more information about why they are not started.

for mariadb, it outputs this: 
`sudo: /opt/bitnami/scripts/mariadb/start.sh: command not found`
for the php it outputs this: 
`php 14:25:31.31 ERROR ==> php-fpm did not start`

> Can you try running these commands to solve the file permissions issue?

I also tried these on the wordpress folder but it did not seem to take any effect

**Comment by jotamartos** [comment]
>sudo: /opt/bitnami/scripts/mariadb/start.sh: command not found

What about using this other one? Depending on the version you launched, the start.sh scripts may differ.

```
sudo /opt/bitnami/scripts/mysql/start.sh
```

If you continue getting "command not found" errors, please run this other command 

```
sudo find /opt/bitnami -name start.sh
```

>php 14:25:31.31 ERROR ==> php-fpm did not start

It seems PHP was not properly stopped and the PHP log shows this error message 

```
[22-Nov-2023 16:59:05] ERROR: Another FPM instance seems to already listen on /opt/bitnami/php/var/run/www.sock
[22-Nov-2023 16:59:05] ERROR: FPM initialization failed
```

Can you try to remove that file and start PHP again? 

```
sudo rm -rf /opt/bitnami/php/var/run/www.sock
sudo /opt/bitnami/scripts/php/start.sh
```

**Comment by jotamartos** [comment]
> but it says command not found:
> sudo: /opt/bitnami/scripts/mariadb/start.sh: command not found

You probably changed the permissions configuration. What about running these commands?

```
sudo chmod +x /opt/bitnami/scripts/mariadb/start.sh
sudo /opt/bitnami/scripts/mariadb/start.sh
```

**Comment by mark-ideatheorem** [comment]
> > but it says command not found:
> > sudo: /opt/bitnami/scripts/mariadb/start.sh: command not found
> 
> You probably changed the permissions configuration. What about running these commands?
> 
> ```
> sudo chmod +x /opt/bitnami/scripts/mariadb/start.sh
> sudo /opt/bitnami/scripts/mariadb/start.sh
> ```

I tried running the commands above and I got this error:

mariadb 19:34:43.39 ERROR ==> mariadb did not start
