### ISSUE TITLE
[Alfresco] How to change JAVA_OPTS for transform-core-aio

### ISSUE THREAD

**Issue by florianrhomberg** [bitnami/vms#1255]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4e606a21-94f7-5708-0fe5-f31078887f79

### bndiagnostic was not useful. Could you please tell us why?

Issue not related with bndiagnostic

### Describe your issue as much as you can

The  transform-core-aio has no limit according to the max number of threads allowed, therefore if you upload too many files at once the server ram will exceed and the transform process fails. In Docker you can easily change the max number of allowed threads of  transform-core-aio, how can I do this in the appliance.

Florian

**Comment by mdhont** [comment]
Are you running the Alfresco VM? If so, on which platform?

**Comment by florianrhomberg** [comment]
The problem still persists, the image in the current way ist only useable for test purpose.
