### ISSUE TITLE
Missing /opt/bitnami directory

### ISSUE THREAD

**Issue by mullalyllc** [bitnami/vms#1256]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Missing

### bndiagnostic was not useful. Could you please tell us why?

Missing /opt directory; bndiagnostic tool not present

### Describe your issue as much as you can

I have a new Lightsail Wordpress instance that is working fine.  I am trying to change the Static IP to a different URL by configuring the wp-config.php file.  

However, when I connect via SSH there is no '/opt/bitnami/apps/wordpress/htdocs/' directory.  The only directories listed are 'bitnami_application_password  bitnami_credentials  htdocs  stack'.

Where is the '/opt' located?  Or how can I create it if it wasn't included with my Bitnami image?  Thanks

<img width="1008" alt="Bitnami" src="https://github.com/bitnami/vms/assets/142606680/fee0227e-dc8e-407e-ae62-8aeaf5cc0469">

**Comment by mdhont** [comment]
You can use the following command to cd in the /opt/bitnami folder

    cd /opt/bitnami

And then list the files using `ls`

**Comment by ghroyd1110** [comment]
for me using an aws bitnami tomcat image, the /opt/bitnami folder does not exist

**Comment by jotamartos** [comment]
All Bitnami solutions include the /opt/bitnami directory. If that's not the case, please ensure you launch the correct image in the cloud
