### ISSUE TITLE
[Bitnami Apache Solr] How to upgrade apache in Bitnami Apache Solr Virtual Machine

### ISSUE THREAD

**Issue by mkarthikprabhu1** [bitnami/vms#1258]
### Describe your issue as much as you can

Team, I have to upgrade new Apache version in Bitnami Apache Solr Virtual Machine where we faced more vulnerabilities in the old version. Pls guide the steps to upgrade to latest versioin of Apache.

**Comment by gongomgra** [comment]
Hi @mkarthikprabhu1,

Thanks for using Bitnami. As mentioned in other tickets, updating core components of the Bitnami installation is not possible. You will have to launch a fresh new server with updated versions and then migrate your application data there.

Hope it helps!
