### ISSUE TITLE
[Magento] Admin Backend working in text mode only

### ISSUE THREAD

**Issue by debtanu** [bitnami/vms#1260]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

11fbe3da-66af-7204-cd63-58c272eb2a1e

### bndiagnostic output

    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3430 2073 331 81 1025 988
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

Press [Enter] to continue:
You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Nov 21 15:12:49.497504 2023] [authz_core:error] [pid 3780:tid
140606130898688] [client **ip_address**:40094] AH01630: client denied by server
configuration: /opt/bitnami/magento/app/etc/config.php
 [Tue Nov 21 15:32:45.397081 2023] [authz_core:error] [pid 3780:tid
140606458214144] [client **ip_address**:38690] AH01630: client denied by server
configuration: /opt/bitnami/magento/app/etc/config.php
 [Tue Nov 21 15:58:41.388634 2023] [authz_core:error] [pid 3780:tid
140606458214144] [client **ip_address**:53414] AH01630: client denied by server
configuration: /opt/bitnami/magento/app/etc/config.php

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

### bndiagnostic was not useful. Could you please tell us why?

The troubleshooting link which came up in the tool was not working

### Describe your issue as much as you can

The Magento admin backend is working in text mode only. It allows to sign in but there is no CSS or styling available rendering it un-usable. The bndiagnostic output says low on memory but I have used an image (D1 - General Purpose) as per the recommendation [here](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.magento?tab=PlansAndPrice).

_Front end URL of my site is [here](https://www.quantumbyte.in/) | Backend is [here](https://www.quantumbyte.in/admin)_

There is a big banner of Magento on top rest are all plain text. It is a fresh installation with hardly any data in it. Refer to the screenshot below:-
<img width="424" alt="No style" src="https://github.com/bitnami/vms/assets/1937904/aad6af89-753e-4e54-8b92-32d50971c05b">
I have tried to open the "Increase Memory Link" at Bitnami Docs [link ](https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-memory-linux/)(as came up in the bndiagnostic tool) but it is not working. Kindly recommend.

Thank You.
-Deb

**Comment by jotamartos** [comment]
Hi @debtanu,

If you open the console in the browser, you can see the following error message 

```
Mixed Content: The page at 'https://www.quantumbyte.in/admin' was loaded over HTTPS, but requested an insecure favicon 'http://www.quantumbyte.in/static/version1700831842/adminhtml/Magento/backend/en_GB/Magento_Theme/favicon.ico'. This request has been blocked; the content must be served over HTTPS.
```

As you can see, there are some wrong links and that's why your site doesn't load correctly. Please review the host/domain configuration in the app to ensure everything works with https. The official documentation and the Magento's forums should provide more information.

**Comment by AntonyF-Andreani** [comment]
And the solution?

**Comment by jotamartos** [comment]
Hi @AntonyF-Andreani,

The issue above was probably related to the http/https configuration in the application. You will need to debug the issue and find the error. The Magento's documentation should provide specific steps to take into account when debugging this type of error so please take a look at that.
