### ISSUE TITLE
Any plan to make for Bitnami package for WordPress with NGINX and SSL in other cloud?

### ISSUE THREAD

**Issue by kdamsmt** [bitnami/vms#1261]
### Describe your suggestion as much as you can

Hi,

It'd be better if **Bitnami package for WordPress with NGINX and SSL** also available in [Linode](https://www.linode.com/marketplace/) marketplace too.

**Comment by jotamartos** [comment]
Thank you for your suggestion but we only support these three major cloud providers and there is no plan to support new ones in the short term. 

https://bitnami.com/stack/wordpress-pro/cloud

Thanks
