### ISSUE TITLE
[Mastodon] /opt/bitnami/php/ missing

### ISSUE THREAD

**Issue by Badge2002** [bitnami/vms#1263]
### Describe your issue as much as you can

I can't follow any of the guides because there is no /opt/bitnami/php/ folder.

**Comment by Badge2002** [comment]
```
bitnami@Mastodon:~$ ls /opt/bitnami
bncert       bndiagnostic            bndiagnostic-tool  configure_app_domain  elasticsearch  java      mastodon  nginx  postgresql      redis  scripts  var
bncert-tool  bndiagnostic-regex.ini  common             ctlscript.sh          gonit          licenses  nami      node   properties.ini  ruby   stats
bitnami@Mastodon:~$ sudo find / -name php.ini
bitnami@Mastodon:~$

```

**Comment by Badge2002** [comment]
Bitnami Diagnostic: 13f84101-7cd4-2764-cd43-f7aa0fa91190

**Comment by jotamartos** [comment]
Mastodon requires Ruby, Node and Python to run, but does not require PHP. What guide are you following that mentions the usage of PHP?

**Comment by Badge2002** [comment]
https://docs.bitnami.com/virtual-machine/apps/mastodon/troubleshooting/send-mail/

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jotamartos** [comment]
Hi, 

Sorry for the inconvenience. As we mentioned, PHP is not included in this solution and the guide needs to be removed from our docs. Please follow the instructions @mdhont mentioned in the other thread.
