### ISSUE TITLE
[Apache Tomcat] Trouble to enable SSL access over HTTPS

### ISSUE THREAD

**Issue by forguesr** [bitnami/vms#1265]
No matter what I do I can't get rid of the Bitnami "exemple.com" certificate which is "generated at boot time".  Looks like the default certificate with the image.

I modified the "/opt/bitnami/apache-tomcat/conf/server.xml" file according to https://docs.bitnami.com/google/infrastructure/tomcat/administration/enable-ssl-tomcat/ and even tried numerous other things based on https://tomcat.apache.org/tomcat-9.0-doc/ssl-howto.html but "exemple.com" always stays there.  

What I am missing?

**Comment by jotamartos** [comment]
That's the guide to create and configure a SSL cert for Tomcat. However, you are connecting to Apache through the port 443. Please configure Apache with that SSL cert 

https://docs.bitnami.com/google/infrastructure/tomcat/administration/create-ssl-certificate-apache/

**Comment by forguesr** [comment]
> That's the guide to create and configure a SSL cert for Tomcat. However, you are connecting to Apache through the port 443. Please configure Apache with that SSL cert
> 
> https://docs.bitnami.com/google/infrastructure/tomcat/administration/create-ssl-certificate-apache/

Thanks!  It was not obvious to me that Apache was involved in the connection.  I just replaced the original certificates in /opt/bitnami/apache2/conf/bitnami/certs with ours.
