### ISSUE TITLE
pear not working on aws lightsail lamp php 8

### ISSUE THREAD

**Issue by jlcaaveiro** [bitnami/vms#1266]
### Name and Version

lightsail lamp php 8

### What architecture are you using?

None

### What steps will reproduce the bug?

update any pear module.  error on debian.. no pear updates available

### Are you using any custom parameters or values?

no

### What do you see instead?

error reported by debian

**Comment by mdhont** [comment]
/Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually.
