### ISSUE TITLE
[Wordpress] Getting error "wordpress-certified has resource level errors"

### ISSUE THREAD

**Issue by averedjoe** [bitnami/vms#1267]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

NA

### bndiagnostic output

Getting the error "wordpress-certified has resource level errors"

{"ResourceType":"runtimeconfig.v1beta1.waiter","ResourceErrorCode":"504","ResourceErrorMessage":"Timeout expired."}

What does this mean, and how to resolve this?

![405541130_730379275150106_6113732273873488964_n](https://github.com/bitnami/vms/assets/152329944/e349e4ae-727a-41d9-8165-ac29f2707df7)

### bndiagnostic was not useful. Could you please tell us why?

There is no available resource or information regarding this.

### Describe your issue as much as you can

Getting the error "wordpress-certified has resource level errors"

{"ResourceType":"runtimeconfig.v1beta1.waiter","ResourceErrorCode":"504","ResourceErrorMessage":"Timeout expired."}

What does this mean, and how to resolve this?

The VM instance it self is running in VM instance page on GCP

![405541130_730379275150106_6113732273873488964_n](https://github.com/bitnami/vms/assets/152329944/5115069c-38bb-402e-8e88-ec6cdd3051d0)

**Comment by XV02** [comment]
I have the same issue since a few days ago not being able to deploy anything. Any solution to this problem?

**Comment by jotamartos** [comment]
That should be a transient issue. I just launched a Bitnami WordPress instance in Google Cloud and it was deployed correctly. Please contact the Google's support team if the problem persists.
