### ISSUE TITLE
[WordPress] <For security reasons, this URL is only accessible using localhost (127.0.0.1) as the hostname.>

### ISSUE THREAD

**Issue by CofChips** [bitnami/vms#1269]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a38407a0-0692-9512-ddad-57847909aabb

### bndiagnostic output

? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

 The files listed below are bigger than 10MB and have not been included, please notify the support agent.

/opt/bitnami/apache/logs/error_log
/opt/bitnami/apache2/logs/error_log

### bndiagnostic was not useful. Could you please tell us why?

Cannot find any solution to my issue

### Describe your issue as much as you can

For security reasons, this URL is only accessible using localhost (127.0.0.1) as the hostname.

I was previously able to access phpmyadmin using my Putty tunnel, but am unable to do so anymore.

I checked my setup and it matches the guide.

**Comment by CofChips** [comment]
[Wed Nov 29 03:39:04.901889 2023] [autoindex:error] [pid 65679:tid 140023105971968] [client 127.0.0.1:45606] AH01276: Cannot serve directory /opt/bitnami/phpmyadmin/: No matching DirectoryIndex (index.html,index.html,index.htm,index.php) found, and server-generated directory index forbidden by Options directive

**Comment by CofChips** [comment]
Hi,

To supplement, I created a new instance of my site for testing purposes and disabled all firewalls. I am still getting the same error.

Any idea of what could be causing this?

**Comment by CofChips** [comment]
I have already created an SSH tunnel and it worked fine previously, but I'm getting the error message now despite having the SSH tunnel setup through Putty and trying to access it through my local IP.

**Comment by jotamartos** [comment]
Please ensure you are not redirected to your domain or similar. You can verify that phpMyAdmin works properly by accessing the instance using a SSH connection and running this command 

```
curl -LI localhost/phpmyadmin
```

**Comment by CofChips** [comment]
Below is the result of the above command:

HTTP/1.1 301 Moved Permanently
Date: Tue, 05 Dec 2023 16:53:36 GMT
Server: Apache
Location: http://localhost/phpmyadmin/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 403 Forbidden
Date: Tue, 05 Dec 2023 16:53:36 GMT
Server: Apache
Content-Type: text/html; charset=iso-8859-1

**Comment by jotamartos** [comment]
Sorry, can you try with 127.0.0.1?

```
curl -LI 127.0.0.1/phpmyadmin
```

**Comment by CofChips** [comment]
Below is the result of the aforementioned command:

HTTP/1.1 301 Moved Permanently
Date: Mon, 11 Dec 2023 21:45:59 GMT
Server: Apache
Location: http://127.0.0.1/phpmyadmin/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 403 Forbidden
Date: Mon, 11 Dec 2023 21:45:59 GMT
Server: Apache
Content-Type: text/html; charset=iso-8859-1

**Comment by jotamartos** [comment]
Did you make any change in the Apache configuration lately? Please note that phpMyAdmin works as expected in a fresh instance and you also mentioned that you could access the application in the past

```
$ curl -LI localhost/phpmyadmin
HTTP/1.1 301 Moved Permanently
Date: Tue, 12 Dec 2023 11:21:44 GMT
Server: Apache
Location: http://localhost/phpmyadmin/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Tue, 12 Dec 2023 11:21:44 GMT
Server: Apache
X-ob_mode: 1
X-Frame-Options: DENY
Referrer-Policy: no-referrer
Content-Security-Policy: default-src 'self' ;script-src 'self' 'unsafe-inline' 'unsafe-eval' ;style-src 'self' 'unsafe-inline' ;img-src 'self' data:  *.tile.openstreetmap.org;object-src 'none';
X-Content-Security-Policy: default-src 'self' ;options inline-script eval-script;referrer no-referrer;img-src 'self' data:  *.tile.openstreetmap.org;object-src 'none';
X-WebKit-CSP: default-src 'self' ;script-src 'self'  'unsafe-inline' 'unsafe-eval';referrer no-referrer;style-src 'self' 'unsafe-inline' ;img-src 'self' data:  *.tile.openstreetmap.org;object-src 'none';
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: noindex, nofollow
Expires: Tue, 12 Dec 2023 11:21:45 +0000
Cache-Control: no-store, no-cache, must-revalidate, pre-check=0, post-check=0, max-age=0
Pragma: no-cache
Vary: Accept-Encoding
Set-Cookie: pma_lang=en; expires=Thu, 11 Jan 2024 11:21:44 GMT; Max-Age=2592000; path=/phpmyadmin/; HttpOnly; SameSite=Strict
Set-Cookie: phpMyAdmin=et5bmqn3gar494t97foo235mce; path=/phpmyadmin/; HttpOnly; SameSite=Strict
Last-Modified: Tue, 12 Dec 2023 11:21:45 GMT
Content-Type: text/html; charset=utf-8
```

As a workaround, you can access http://myip.bitnami.com to get your public IP address and can allow that IP when accessing phpMyAdmin. You will need to edit the `Require local` line in the `/opt/bitnami/apache/conf/bitnami/phpmyadmin.conf` file and set your IP address there 

```
Alias /phpmyadmin "/opt/bitnami/phpmyadmin"
<Directory "/opt/bitnami/phpmyadmin">
  Options -Indexes +FollowSymLinks -MultiViews
  AllowOverride All
  Require ip YOUR_IP
...
```

Remember to restart Apache for the changes to take effect.

**Comment by CofChips** [comment]
Thanks. In my phpmyadmin.conf I see the following:

ErrorDocument 403 "For security reasons, this URL is only accessible using localhost (127.0.0.1) as the hostname."

Should this continue to be in here?

**Comment by jotamartos** [comment]
That line only sets the error that is going to be shown if you are not in the list of available IPs (the Require line I mentioned above). You can keep that error message there.
