### ISSUE TITLE
Kafka no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"

### ISSUE THREAD

**Issue by phucduong-ncc** [bitnami/vms#1271]
### Describe your issue as much as you can

Hello when i install kafka got the issue no matches for kind "PodDisruptionBudget" in version "policy/v1beta1", and i see in the chart we define {{- define "common.capabilities.policy.apiVersion" -}}
{{- if semverCompare "<1.21-0" (include "common.capabilities.kubeVersion" .) -}}
{{- print "policy/v1beta1" -}}

but i could not found how can we set value for semverCompare, could you guys please give me instruction how can i set semverCompare

**Comment by gongomgra** [comment]
Hi @phucduong-ncc,

Thanks for using Bitnami. This is the support forum for our virtual machines and cloud images. According to your message, it looks like you have questions for one of our Helm charts solutions. Please open a new question in the dedicated forum linked below. Our team is actively monitoring it and will be glad to help you

https://github.com/bitnami/charts/issues
