### ISSUE TITLE
[WordPress] Site keeps going down

### ISSUE THREAD

**Issue by shorman13** [bitnami/vms#1272]
### Describe your issue as much as you can

Platform
AWS

bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)
e88ae5c9-15ac-5b82-479b-9c390294d765

bndiagnostic was not useful. Could you please tell us why?
No. Not clear.

Describe your issue as much as you can
My site goes down every few days until I restart services. Can you help me understand why and how to fix please?
Here's the bndiagnostic tool result. Thank you in advance,

**Comment by shorman13** [comment]
I'm still rebooting my site every few days. May I get some specific instructions and be treated like a child?

**Comment by jotamartos** [comment]
Hi @shorman13,

The guides I mentioned above explain what to check to get more information about the issue. If a bot/attacker is accessing your site with malicious intentions, it also explains how to block it. In case it's a specific performance issue in the application, you can increase the resources and check if that solves the issue. However, if you continue running into issues, you will need to continue monitoring the server and apply any required change to make it stable.
