### ISSUE TITLE
How to install Healthcare module using bitnami erpnext package

### ISSUE THREAD

**Issue by Yogeshwaran2210** [bitnami/vms#1273]
It's possible to install Healthcare module in bitnami erpnext

**Comment by gongomgra** [comment]
Hi @Yogeshwaran2210,

Thanks for using Bitnami. ERPNext is installed in the `/opt/bitnami/erpnext` folder. You should be able to follow the official docs from ERPNext on how to install extra packages. Are you having any specific issues with that module?

**Comment by Yogeshwaran2210** [comment]
> Hi @Yogeshwaran2210,
> 
> Thanks for using Bitnami. ERPNext is installed in the `/opt/bitnami/erpnext` folder. You should be able to follow the official docs from ERPNext on how to install extra packages. Are you having any specific issues with that module?

`Can you explain the step by step procedure for installing Healthcare module in bitnami erpnext.`
`And there is not official docs for installing extra modules in bitnami erpnext`

**Comment by jotamartos** [comment]
You have one example about how to install a module in this other thread 

https://github.com/bitnami/vms/issues/1180

If you run into issues installing the healthcare module, please contact the module's developers to know more information.
