### ISSUE TITLE
[Mastodon] How to setup SMTP?

### ISSUE THREAD

**Issue by Badge2002** [bitnami/vms#1275]
### Describe your issue as much as you can

This is a followup to https://github.com/bitnami/vms/issues/1263.

The first step on https://docs.bitnami.com/virtual-machine/apps/mastodon/troubleshooting/send-mail/ fails because there is no /opt/bitnami/php folder

**Comment by mdhont** [comment]
Our apologies. Mastodon doesn't use PHP, we will remove the PHP section from the docs. For configuring SMTP you can follow the official guide:

https://docs.joinmastodon.org/admin/config/#smtp

**Comment by Badge2002** [comment]
That guide still doesn't explain how to setup SMTP. How do you run those commands?

**Comment by mdhont** [comment]
Those are environment variables which Mastodon will use. The following guide may be of help:

https://draklyckan.se/2021/10/setting-up-email-in-mastodon/
