### ISSUE TITLE
Login to AWS bitnami instance don't work anymore

### ISSUE THREAD

**Issue by digiloo** [bitnami/vms#1276]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic output

N/A

### bndiagnostic was not useful. Could you please tell us why?

Can't login an run bndiagnostic ..

### Describe your issue as much as you can

I can't login in my AWS bitnami instance (Joomla) any more. Not even after a restart of the instance. I guess that the SSH daemon fails to start. Is there any other way to login to the bitnami instance via Internet (I have full control over the firewall).

Regards
Hakan

**Comment by mdhont** [comment]
Can you check in the AWS console that the instance is running? Can you check if rebooting the instance solves it?

**Comment by digiloo** [comment]
Hi,

The web server is up and running. It is SSH
that is unavailable. Reboot don’t solve the problem

/ Digiloo

mån 4 dec. 2023 kl. 11:26 skrev Michiel ***@***.***>:

**Comment by digiloo** [comment]
Thank you.

I tried to contact AWS support but since I only have a non-support plan it don’t gav anything.

So yesterday I migrated my site to a virtual machine with a bigger footprint.

/ Hakan
