### ISSUE TITLE
[wordpress] Cannot get apps to restart so wordpress wont open

### ISSUE THREAD

**Issue by unllax167** [bitnami/vms#1279]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

57203bec-943b-85c7-5ac5-88683052d76a

### bndiagnostic output

----------------------------------------------------------------------------
Created with an evaluation version of InstallBuilder

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ? Processes: Found possible issues
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 950 413 125 6 411 352 Swap: 
634 64 570
```
Press [Enter] to continue:
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Processes]

One or more component's processes are not running:
```
apache not running php-fpm not running
```
You can try to restart the process with the following command:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
Press [Enter] to continue:
```
[Fri Dec 01 07:27:58.056495 2023] [proxy_fcgi:error] [pid 150173:tid 
139881347004160] [client **ip_address**:33881] AH01071: Got error 'PHP message: 
PHP Fatal error: Uncaught TypeError: is_dir(): Argument #1 ($filename) must be 
of type string, WP_Error given in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php:443
Stack trace:
#0 /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php(443): 
is_dir()
#1 /bitnami/wordpress/wp-content/themes/servicemaster/inc
```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

[Apache]

Found recent error or warning messages in the Apache error log.
```


```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.

Press [Enter] to continue:
System Apache is running:
```
www-data 194353 0.0 0.0 3492 240 ? Ss Dec01 0:02 /usr/bin/htcacheclean -d 120 -p 
/var/cache/apache2/mod_cache_disk -l 300M -n root 211052 0.0 2.8 220368 27936 ? 
Ss 08:40 0:00 /usr/sbin/apache2 -k start
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Somewhat but still stuck

### Describe your issue as much as you can

Can't seem to get WP to work even after digging through the diagnostic tool

**Comment by mdhont** [comment]
It seems you have another instance of Apache running. Normally that's system's Apache (Bitnami application use their own Apache component). 

You can stop the system apache instance with this command:

    sudo systemctl stop apache2
 

And uninstall it as follows:

    sudo systemctl disable apache2
    sudo apt-get purge apache2
    sudo apt-get autoremove
