### ISSUE TITLE
[WordPress Multisite] Not accessible

### ISSUE THREAD

**Issue by mohammedzayanm** [bitnami/vms#128]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

775cd17b-a616-a69b-d9bc-fe2d9fa1492d

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.

    ? Apache: Found possible issues
    ? Resources: Found possible issues
    ✓ Wordpress: No issues found
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Jul 15 12:56:23.974913 2022] [core:error] [pid 12112:tid 139697233819392]
[client **ip_address**:41446] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
Press [Enter] to continue:
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.,
referer:
http://ipaddress/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
 [Fri Jul 15 13:01:54.533718 2022] [proxy_fcgi:error] [pid 12112:tid
139697275782912] [client **ip_address**:41804] AH01071: Got error 'PHP message:
PHP Warning: Undefined array key "HTTP_HOST" in
/opt/bitnami/wordpress/wp-includes/ms-settings.php on line 57PHP message: PHP
Warning: Undefined array key "host" in
/opt/bitnami/wordpress/wp-includes/canonical.php on line 687PHP message: PHP
Warning: Undefined array key "host" in
/opt/bitnami/wordpress/wp-includes/canonical.php on line 696PHP mess [Fri Jul 15
13:35:35.802757 2022] [core:error] [pid 11815:tid 139696604694272] [client
**ip_address**:43224] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.,
referer:
http://ipaddress:80/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
Press [Enter] to continue:

The Apache configuration has errors:
```
apache2: Syntax error on line 66 of /opt/bitnami/apache2/conf/httpd.conf: Cannot
load modules/mod_mpm_event.so into server:
/opt/bitnami/apache/modules/mod_mpm_event.so: undefined symbol:
ap_run_child_stopping
```
Please check the configuration.

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 925 569 64 7 291 203 Swap: 634
2 632
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
Press [Enter] to continue:
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Some files don't have the expected permissions. Please check the following
guide:

https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Couldn't understand myself

### Describe your issue as much as you can

My site was working fine last I checked a few days back.. When I tried accessing it today, I am getting DNS_PROBE_FINISHED_NXDOMAIN for my site (both main site and subsite). 

But my main site is showing that its up on [https://downforeveryoneorjustme.com/] while its showing down for my subsite.

Please help on this issue

**Comment by jotamartos** [comment]
>  [Fri Jul 15 13:01:54.533718 2022] [proxy_fcgi:error] [pid 12112:tid
> 139697275782912] [client **ip_address**:41804] AH01071: Got error 'PHP message:
> PHP Warning: Undefined array key "HTTP_HOST" in
> /opt/bitnami/wordpress/wp-includes/ms-settings.php on line 57PHP message: PHP
> Warning: Undefined array key "host" in
> /opt/bitnami/wordpress/wp-includes/canonical.php on line 687PHP message: PHP
> Warning: Undefined array key "host" in
> /opt/bitnami/wordpress/wp-includes/canonical.php on line 696PHP mess [Fri Jul 15
> 13:35:35.802757 2022] [core:error] [pid 11815:tid 139696604694272] [client
> **ip_address**:43224] AH00124: Request exceeded the limit of 10 internal
> redirects due to probable configuration error. Use 'LimitInternalRecursion' to
> increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.,
> referer:
> http://ipaddress:80/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php

It seems these are WordPress' or a plugin's related error. We suggest you disable all plugins to see if the problem persists and contact the WordPress' support team to know more about them.

https://wordpress.org/support/
