### ISSUE TITLE
Bitnami-VMs Nginx Flavor | Introduction & General info to assess.

### ISSUE THREAD

**Issue by tziady** [bitnami/vms#1280]
### Describe your suggestion as much as you can

So, very familiar with Bitnami, Trellis, and other similiarish platforms. 
Love and have used Bitnami a few times with the Apache  Flavor.

Pretty sure this is not the right place to post this; but I really cannot find where to go and look for my answers. And please forgive me.

This is for the Bitnami LEMP AWS implementation and looking for an way to setup a local VM environment that I can deploy to AWS as a staging site and then as a production site.  I know this was doable with wsl2 (i use windblows) OR hyper-V / VirtualBox.

But rather than doing this and figuring it out on my own; perhaps that is already a bit part of the project and someone can point me in the right direction(s).

Thank you for much for your time. Now back to your regularly scheduled light text on dark bg coding.

Cheers,
T

**Comment by jotamartos** [comment]
Hi @tziady,

Both the local VM and the cloud image follow the same directory structure and configuration so you can easily deploy a local VM using (VMware Fusion or VirtualBox) and test your changes before moving them to your production site in the cloud. You can download the VM or launch the cloud image by following the instructions in our site 

https://bitnami.com/stack/nginx

**Comment by tziady** [comment]
Thank you very much for your quick response. 

Cheers,
T
