### ISSUE TITLE
[SuiteCRM] SuiteCRM is no longer accessible after VM reboot

### ISSUE THREAD

**Issue by Crepetsky** [bitnami/vms#1283]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8dd95b18-34d5-3a59-5d71-35b6a4ca7f0c

### bndiagnostic output

PHP: no issues found
Mariadb: no issues found
Processes: no issues found
Connectivity: Found possible issues
Resources: Found possible issues
Apache: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

I attempted to open port 80 in the firewall, and it appears to already be open

### Describe your issue as much as you can

I am currently running SuiteCRM as a virtual machine. Everything was working fine until yesterday, when I had to take the server down for a software update (I updated the hypervisor, not the SuiteCRM VM). After reboot, SuiteCRM is no longer accessible. I can ping the local address of the VM from the LAN, and the VM itself can ping outside internet addresses.

**Comment by jotamartos** [comment]
I can see your machine is running out of memory, there are many PHP processes running in the machine

```
               total        used        free      shared  buff/cache   available
Mem:             777         613         130           0          33           9
Swap:              0           0           0
```

Please check that all services are up and running or take a look at their log files if they aren't. You can also take a look at these guides to know if there is any performance issue or if there is a bot/attacker accessing your site with malicious intentions

https://docs.bitnami.com/general/faq/troubleshooting/troubleshoot-server-performance/
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-connections-bots-apache/

**Comment by Crepetsky** [comment]
Oddly enough, restarting Apache seems to have fixed it. I'm not sure why it's not starting automatically when the VM spins up when it did before, but at least it appears to be working. I also allocated more RAM.

Thank you!
