### ISSUE TITLE
[Wordpress] Website unreachable

### ISSUE THREAD

**Issue by StefanoCocomazzi** [bitnami/vms#1284]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ebd9fbf0-1dcb-6dc7-54be-abd91ff95982

### bndiagnostic output

The tool displayed no output after the diagnostic.

### bndiagnostic was not useful. Could you please tell us why?

Attempted to restore, but probably messed up even more.

### Describe your issue as much as you can

Most likely I messed up the permissions while trying to configure the sftp connection with FileZilla and forgot to backup.
Is there a way to restore all permissions?

Here's the apache error log
[Mon Dec 04 21:39:27.227030 2023] [proxy:error] [pid 303055:tid 140250084902656] (13)Permi
ssion denied: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var
/run/www.sock (www-fpm:8000) failed
[Mon Dec 04 21:39:27.227059 2023] [proxy_fcgi:error] [pid 303055:tid 140250084902656] [cli
ent 2.34.56.8:63615] AH01079: failed to make connection to backend: httpd-UDS, referer: ht
tp://18.153.73.90/
[Mon Dec 04 21:40:06.431541 2023] [proxy:error] [pid 305282:tid 140249883477760] (2)No suc
h file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/
php/var/run/www.sock (www-fpm:8000) failed
[Mon Dec 04 21:40:06.431582 2023] [proxy_fcgi:error] [pid 305282:tid 140249883477760] [cli
ent 2.34.56.8:63622] AH01079: failed to make connection to backend: httpd-UDS, referer: ht
tp://18.153.73.90/wp-admin/
[Mon Dec 04 21:40:06.519256 2023] [proxy:error] [pid 305282:tid 140250378647296] (2)No suc
h file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/
php/var/run/www.sock (www-fpm:8000) failed
[Mon Dec 04 21:40:06.519287 2023] [proxy_fcgi:error] [pid 305282:tid 140250378647296] [cli
ent 2.34.56.8:63621] AH01079: failed to make connection to backend: httpd-UDS, referer: ht
tp://18.153.73.90/
[Mon Dec 04 21:40:07.164132 2023] [proxy:error] [pid 305139:tid 140249900263168] (2)No suc
h file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/
php/var/run/www.sock (www-fpm:8000) failed
[Mon Dec 04 21:40:07.164176 2023] [proxy_fcgi:error] [pid 305139:tid 140249900263168] [cli
ent 2.34.56.8:63625] AH01079: failed to make connection to backend: httpd-UDS, referer: ht
tp://18.153.73.90/wp-admin/
[Mon Dec 04 21:40:07.250313 2023] [proxy:error] [pid 305139:tid 140250353469184] (2)No suc
h file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/
php/var/run/www.sock (www-fpm:8000) failed
[Mon Dec 04 21:40:07.250349 2023] [proxy_fcgi:error] [pid 305139:tid 140250353469184] [cli
ent 2.34.56.8:63624] AH01079: failed to make connection to backend: httpd-UDS, referer: ht
tp://18.153.73.90/
[Mon Dec 04 21:40:07.683977 2023] [mpm_event:notice] [pid 1144:tid 140251039292672] AH0049
1: caught SIGTERM, shutting down

**Comment by StefanoCocomazzi** [comment]
> You can reset permissions as follows:
> 
> ```
> sudo chown -R bitnami:daemon TARGET
> sudo find TARGET -type d -exec chmod 775 {} \;
> sudo find TARGET -type f -exec chmod 664 {} \;
> sudo chmod 640 TARGET/wp-config.php
> ```
> 
> Where TARGET is "/opt/bitnami/wordpress"

Unfortunately it didn't work. The permessions are resetted, but the website si still unreachable.

**Comment by mdhont** [comment]
Could you check the RAM memory available on the system:

    free -h

Also, I recommend disabling all plugins to check if one of them is causing the issue.

    wp plugin deactivate --all
