### ISSUE TITLE
ERPNext Healthcare Module Installation

### ISSUE THREAD

**Issue by Yogeshwaran2210** [bitnami/vms#1285]
### Describe your issue as much as you can

> Can you explain the step by step procedure for installing Healthcare module in bitnami erpnext version14.
> And there is not official docs for installing extra modules in bitnami erpnext.

**Comment by jotamartos** [comment]
Please do not create multiple tickets, we will continue the conversations in the other thread

https://github.com/bitnami/vms/issues/1273
