### ISSUE TITLE
[WordPress] unable to reach this site.

### ISSUE THREAD

**Issue by RogerioGT** [bitnami/vms#1286]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

139716292769536

### bndiagnostic output

✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Tue Dec 05 04:22:13.966125 2023] [proxy_fcgi:error] [pid 2
7942:tid 
139716292769536] [client **ip_address**:5877] AH01079: fail
ed to make connection 
to backend: httpd-UDS
 [Tue Dec 05 04:22:15.515635 2023] [proxy:error] [pid 27950
:tid 139715973846784] 
(2)No such file or directory: AH02454: FCGI: attempt to con
nect to Unix domain 
socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) fai
led
 [Tue Dec 05 04:22:15.515666 2023] [proxy_fcgi:error] [pid 
27950:tid 
139715973846784] [client **ip_address**:19773] AH01079: fai
led to make 
connection to backend: httpd-UDS, referer: http://13.59.54.
78/

***********
httpd: Syntax error on line 74 of /opt/bitnami/apache2/conf
/httpd.conf: Cannot 
load modules/mod_authn_core.soge into server: 
/opt/bitnami/apache/modules/mod_authn_core.soge: cannot ope
n shared object file: 
Press [Enter] to continue:
No such file or directory

### bndiagnostic was not useful. Could you please tell us why?

Says no such file or directory

### Describe your issue as much as you can

I recently installed Bitnami 6.3.2-12 in AWS Lightsail. 
Worked for over a week or two, while I was working on the WordPress single site. 
I added and assigned a static ip 13.59.54.78. 
I link a domain and open ports 20, 80, 443. 
I am nearly done with the website and started to have this site can't be reached. I rebooted the instance and it worked. 
It happened twice. I rebooted and worked. 
On the day, I tried to access the website and realize it says This site can't be reached again. I did not have time to reboot it until 2 days later. Furthermore, I tried to reboot the instance later on, and it was too late, as it is not working anymore. 
AWS Light sail takes snapshots every day, so I tried to go back to the snapshot where it was supposed to be working, but it says database error and does not load. 
I double-check the ports and they are open. 
If I do a new installation of Bitnami as a test in my account it loads, takes a bit longer than usual, but it works. 
The instance I am working on fails.

**Comment by RogerioGT** [comment]
Tried, 
sudo /opt/bitnami/ctlscript.sh stop
sudo /opt/bitnami/ctlscript.sh start

Active: failed (Result: exit-code) since Tue 2023-12-05 11:06:51 UTC; 1min 3s ago
    Process: 2366 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)

Failed to start LSB: bitnami init script.

**Comment by jotamartos** [comment]
Please check that all services are up and running or take a look at their log files if they aren't. You can also take a look at these guides to know if there is any performance issue or if there is a bot/attacker accessing your site with malicious intentions

https://docs.bitnami.com/general/faq/troubleshooting/troubleshoot-server-performance/
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-connections-bots-apache/

**Comment by RogerioGT** [comment]
Everything seems to be up and running and the ports are available to access anywhere. 
ctlscript.sh restart apache
Failed to restart apache: Failed to restart apache.

This was the only command that failed from the articles shared. 

bitnami@ip-:/opt/bitnami/apache/logs$ sudo find / -name httpd.conf
/opt/bitnami/apache/conf/bitnami/httpd.conf
/opt/bitnami/apache/conf/httpd.conf
/opt/bitnami/apache/conf/original/httpd.conf
/opt/bitnami/bndiagnostic/original-data/apache/conf/httpd.conf
/opt/bitnami/bndiagnostic/original-data/apache2/conf/httpd.conf

I don't have much experience with servers or Apache, but were this files moved or how to know if they are linked? It seems to me there was an automatic update that may have caused some changes. 

There is not much I can find from Bitnami.

**Comment by jotamartos** [comment]
> Everything seems to be up and running and the ports are available to access anywhere.
> ctlscript.sh restart apache
> Failed to restart apache: Failed to restart apache.

It seems there is a configuration error in Apache. Please take a look at the /opt/bitnami/apache/logs/error_log file and try to start the service using the /opt/bitnami/scripts/apache/start.sh to try to get more information.

```
sudo /opt/bitnami/scripts/apache/start.sh
```

>I don't have much experience with servers or Apache, but were this files moved or how to know if they are linked? It seems to me there was an automatic update that may have caused some changes.

Our stacks are not updated automatically. As I mentioned above, there should be an error in the configuration that is preventing Apache to start. Please note that we do not provide this kind of support, if you are not familiar with Apache, please find someone in your community who can help you debug this issue.
