### ISSUE TITLE
[odoo16] How to update to the latest code

### ISSUE THREAD

**Issue by laundryst** [bitnami/vms#1288]
### Describe your issue as much as you can

We have been using bitnami GCP for a while. The Bitnami odoo documentation explains how to upgrade, but I need help finding how to update to the latest code.  Does the usual apt-get upgrade keep the package updated?

Thanks,

**Comment by Cristianfllc3** [comment]
Hi, it is possible add the reference to the upgrade process!

**Comment by mdhont** [comment]
My apologies, if you meant upgrading Odoo within the same major version you can follow the steps in the guide:

https://docs.bitnami.com/aws/apps/odoo/administration/upgrade/
