### ISSUE TITLE
[Guacamole] <Please help to provide the download link of 1.4.0-82-r54-linux-vm-debian-11-x86_64-nami.ova>

### ISSUE THREAD

**Issue by hkfoolman** [bitnami/vms#1289]
When i running the latest version on ESXI 6.5, the connection become instable after connect RDP. Could anyone help to provide the link to downlad bitnami-guacamole-1.4.0-82-r54-linux-vm-debian-11-x86_64-nami.ova.

**Comment by mdhont** [comment]
You can download it here:

https://downloads.bitnami.com/files/stacks/guacamole/1.4.0-82/bitnami-guacamole-1.4.0-82-r54-linux-vm-debian-11-x86_64-nami.ova 

    md5:5ae7c309d4e8fdfc4c81d9e1e3501b98

**Comment by agarcia-oss** [comment]
Hi @hkfoolman the download URL has been restored and is operative again. Sorry for the inconvenience.
