### ISSUE TITLE
[<SSL>] How to renewall ssl certification?

### ISSUE THREAD

**Issue by lalalabro** [bitnami/vms#129]
### Describe your issue as much as you can

I am using bitnami with ssl certification. Recently it has expired SSL certification. 

How to renewal or how to remove it? 
How to use <Reall Simple SSL>?

**Comment by ibushong** [comment]
How did you set up your original cert? Who is the provider?
Did you check the docs? https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/

**Comment by lalalabro** [comment]
I've set up with bncert tool and the provider is AWS. 
I tried everything from https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/

ticket: c99de0e9-57bb-b52b-e5a3-cd5047e4c080

**Comment by mdhont** [comment]
Please try the manual approach:

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
