### ISSUE TITLE
[bitnami-redmine] Can the download link of bitnami-redmine windows exe be temporarily opened?

### ISSUE THREAD

**Issue by witcan** [bitnami/vms#1290]
@mdhont Now access the download url and the prompts are as follows:

https://downloads.bitnami.com/files/stacks/redmine/5.0.3-0/bitnami-redmine-5.0.3-0-windows-x64-installer.exe

```shell
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidObjectState</Code>
<Message>The operation is not valid for the object's storage class</Message>
<StorageClass>DEEP_ARCHIVE</StorageClass>
<RequestId>64JBEBXP70G38JE7</RequestId>
<HostId>5IE5tRV6DKfEaV9n7eejfyDOuT+f/8LQq3sGtNq0T5l0jfHJserZ0zwgmonmYOGJFIyQep7qhZ8=</HostId>
</Error>
```

**Comment by mdhont** [comment]
Unfortunately we are experiencing issues with our download page, we are working on fixing it.

**Comment by witcan** [comment]
@mdhont Excuse me, can you give me a temporary download url? Our servers cannot install virtualization software such as VirtualBox and Docker, so we need native installation packages.
