### ISSUE TITLE
[Redmine] Windows installer for bitnami/Redmine version 3.4.5

### ISSUE THREAD

**Issue by treefield00** [bitnami/vms#1291]
### Describe your issue as much as you can

Hi Bitnami Support,

Is it possible to get a Redmine Installer ?
**Windows installer for Bitnami/Redmine version 3.4.5**

**Comment by mdhont** [comment]
Unfortunately we are experiencing issues with our download page, we are working on fixing it.

**Comment by treefield00** [comment]
Okay, I will wait.
Thanks a lot.

**Comment by agarcia-oss** [comment]
Hi @treefield00 the download URL (https://downloads.bitnami.com/files/stacksmith/redmine-3.4.5-0-linux-x64-debian-8.tar.gz) has been restored and is operative again. Sorry for the inconvenience.

**Comment by treefield00** [comment]
Thanks, but I need Windows installer - Windows installer for Bitnami/Redmine version 3.4.5.
So, please let me have another URL for windows installer.

**Comment by dcristobalhMad** [comment]
Hi @treefield00 👋 !
Could you please provide us with the link you would like to access to get the binary?
Thanks!

**Comment by mdhont** [comment]
My apologies, the latest version available is 4.1.0:

https://downloads.bitnami.com/files/stacks/redmine/4.1.0-8/bitnami-redmine-4.1.0-8-windows-x64-installer.exe

    md5:5ae7c309d4e8fdfc4c81d9e1e3501b98

Please note that it's possible the link's still broken, it will be fixed soon.

**Comment by treefield00** [comment]
Hi bitnami support people
I've got it.
Thanks for your support.

**Comment by treefield00** [comment]
Hi bitnami support people
Now I noticed that I need bitnami-redmine-3.4.5-0-linux-x64-installer.run.
So, would you mind giving me the download URL for bitnami-redmine-3.4.5-0-linux-x64-installer.run?

**Comment by mdhont** [comment]
Hi @treefield00,

Unfortunately the earliest version I have is 4.1.0. You can download it using the above link.

**Comment by treefield00** [comment]
Hi @mdhont 
Understood.
I will consider using Bitnami Docker Image for Redmine.
Thank you kindly.

**Comment by treefield00** [comment]
Hi bitnami support people
I am trying to run docker.io/bitnami/redmine:3.4.5 and docker.io/bitnami/mariadb:5.5.42-1 with docker compose.
I am referring to containers/bitnami/redmine/docker-compose.yml, but as is,
"mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful".
and redmine will terminate.
So, how can we enable root to access mariadb?
First of all, I think I need the environment variables and their values, such as the root password, but if there is anything else I need to know, please let me know.
Thank you in advance.

**Comment by mdhont** [comment]
Did you follow the steps from the README?

https://github.com/bitnami/containers/tree/main/bitnami/redmine

**Comment by treefield00** [comment]
Yes I read it and used docker-compose.yml file which is mentioned in it. 
https://github.com/bitnami/containers/blob/main/bitnami/redmine/docker-compose.yml
But as is, error occurs like "mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful".
So I think I need to set environment variable for root password at least.
I used  docker.io/bitnami/redmine:3.4.5 and docker.io/bitnami/mariadb:5.5.42-1 then.

When I use docker.io/bitnami/redmine:5.x.x and docker.io/bitnami/mariadb11.x.x instead, no error occurs.

**Comment by mdhont** [comment]
My apologies for the misunderstanding, both Redmine 3 and MariaDB 5 are older versions that are not supported any longer. Could you tell me why you need a version that old?

**Comment by treefield00** [comment]
Thank you so much for your support!

We are trying to migrate from redmine:3.4.5 PostgreSQL to redmine:5.0.5 MySQL (MariaDB).
We are trying to migrate in the following steps.
step1. redmine:3.4.5 PostgreSQL -> redmine:3.4.5 MySQL(MariaDB)
step2. redmine:3.4.5 MySQL(MariaDB) -> redmine:5.0.5 MySQL(MariaDB)
In step1, we intend to use YamlDB to migrate from PostgreSQL to MySQL(MariaDB).
So we need redmine:3.4.5 MySQL(MariaDB) environment.

**Comment by mdhont** [comment]
Though it's not an easy solution I recommend installing Redmine 3 manually on following the steps from the official guide:

https://www.redmine.org/projects/redmine/wiki/RedmineInstall/308

And then continue the migration from there. Unfortunately the issue exceeds the scope of this forum but I recommend asking in the official redmine forum:

https://www.redmine.org/projects/redmine/boards

**Comment by treefield00** [comment]
Thank you for your advice!
