### ISSUE TITLE
[Suggestion] Bitnami AMI should be faster update to support AWS new instance

### ISSUE THREAD

**Issue by kdamsmt** [bitnami/vms#1292]
### Describe your suggestion as much as you can

Hello,

Base on my production experience using Bitnami 1 year, I found bitnami too much lock into older aws instance CPU. The new aws cpu run faster and cost saving.

Ex: Bitnami marketplace AMI not update to support newer aws instance, bitnami community AMI update to date but not the new one like M6a is support by community AMI in marketplace does not.

Community AMI support M6A but not support M7A instance while if we compare M7A to M6A in real world M7A is much after CPU but Bitnami not support.

M7G is much faster and cheaper is also consider to support. If Bitnami not support to newer aws instance bitnami package gonna slower when user using your package and another way user got pay higher to aws while using your package AMI becuase Bitnami image not support newer aws instance.

The suggestion, please make bitnami AMI more flexible and update to date for aws cpu newer release.

Thanks,

**Comment by jotamartos** [comment]
>Ex: Bitnami marketplace AMI not update to support newer aws instance, bitnami community AMI update to date but not the new one like M6a is support by community AMI in marketplace does not.

We are aware of this and will work with the AWS team to update the information. Please use the community image if you need to launch the solution using that instance type.
