### ISSUE TITLE
[Redmine] Reporter plugin (PRO version)

### ISSUE THREAD

**Issue by zenxen3** [bitnami/vms#1293]
### Describe your issue as much as you can

Hello,
I have installed **bitnami-redmine-5.1.0-r2-debian-11-amd64.ova**, works fine, recently I bought plugin Redmine Reporter plugin (PRO version) version 2.0.3.
When I do preview of an issue is ok, when I want to create a report, it creates something but it is not readable.

Inside this pdf:
```
Failed to execute:
["/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/bin/wkhtmltopdf", "-q", "--encoding", "UTF-8", "--orientation", "Portrait", "--page-size", "A4", "--margin-top", "20", "--margin-bottom", "20", "--margin-left", "20", "--margin-right", "20", "--footer-right", "[page]/[topage]", "file:////tmp/wicked_pdf20231207-47636-1bblwb.html", "/tmp/wicked_pdf_generated_file20231207-47636-cd3ld2.pdf"]
Error: PDF could not be generated!
 Command Error: /usr/bin/env: ‘ruby’: No such file or directory
```

What should I do to fix this problem? Can somebody help me with that?
[Green issue report-1.pdf](https://github.com/bitnami/vms/files/13600962/Green.issue.report-1.pdf)

**Comment by jotamartos** [comment]
Hi @zenxen3,

Can you try to run the wkhtmltopdf command and check if the pdf is generated correctly? 

Apart from that, instead of installing that tool as a gem, you can install it using the system packages and check if the error is solved 

https://docs.bitnami.com/aws/apps/odoo/configuration/install-wkhtmltopdf/
https://wkhtmltopdf.org/

**Comment by zenxen3** [comment]
Hello @jotamartos,
I have installed the newest package in my system along with redmine stack

```
root@redmine-tst:/home/bitnami# bundle show wkhtmltopdf-binary
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/wkhtmltopdf-binary-0.12.6.6

```
I will write to the developer, maybe they will help with this plugin.
