### ISSUE TITLE
[WordPress] Import remnants of old packaged install of Bitnami WordPress website to VM version

### ISSUE THREAD

**Issue by Dleon01** [bitnami/vms#1297]
### Describe your issue as much as you can

Hello, 
I previously had installed the packaged version of Bitnami WordPress on my PC around 1.5 - 2 years ago (which I cannot seem to find on the web anymore) to cobble together a quick website demo of some changes my uncle should make to his website. It was a few simple pages built using Brizy.

Unfortunately, I had to deal with a crippled OS install of Win10, and in the troubleshooting that followed I had deleted the installation of the packaged Bitnami from my PC.

Somehow (hopefully luckily,) I still have the root folder of the install, that I am _hoping_ contains the necessary files to present the website again!

I do not need to make any further changes or edits, I very simply am hoping to visually see each of the web pages, so I can re-do the work on his actual website when the time comes. I added significant verbiage, photos, etc. that took several hours to do, and would rather not start from scratch again if possible.

Any assistance in recovering what I can, or perhaps even getting assistance in migrating the website I made using the old packaged installer into a new VM install of Bitnami would be extremely appreciated!!

Thank you in advance.

**Comment by jotamartos** [comment]
Hi @Dleon01,

If you copied the entire installation directory, you can reinstall the services and start them by following the information in this other post 

https://github.com/bitnami/vms/issues/975

Remember that you need to copy the files to the same path where the stack was originally installed. Once you confirm you can access the application, we suggest you migrate the installation to a VM or a cloud instance to get the latest updates by following this information

https://docs.bitnami.com/general/how-to/migrate-wordpress/
