### ISSUE TITLE
[SuiteCRM] Does Bitnami still offer SuiteCRM version 7 on the Azure Marketplace? Can you provide a link ?

### ISSUE THREAD

**Issue by anthony-x3S** [bitnami/vms#1298]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0

### bndiagnostic was not useful. Could you please tell us why?

not found

### Describe your issue as much as you can

Can anyone provide a link to Bitnami's SuiteCRM 7 package on the Azure Marketplace? Thank you.

**Comment by jotamartos** [comment]
Hi @anthony-x3S,

Thank you for your interest but we only provide the latest version in the Azure cloud. 

https://bitnami.com/stack/suitecrm/cloud/azure

If you want to launch a different version, you will need to use the local VMs (you can ask for the required version) or launch the instance in [AWS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-4une6drqefwxs)

**Comment by anthony-x3S** [comment]
Okay. Thank you.
