### ISSUE TITLE
[<application>] <[wordpress with NGINX and SSL certified by BITnami and Automatic]>

### ISSUE THREAD

**Issue by Divyadevayya** [bitnami/vms#1299]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

834f9203-2e08-eeff-8557-469670549b15

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ? Nginx: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ✓ Php: No issues found

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3885 2197 284 100 1404 1497
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2023/12/09 06:25:58 [error] 708#708: *276986 FastCGI sent in stderr: "Primary
script unknown" while reading response header from upstream, client:
**ip_address**, server: _, request: "GET
/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKW
orker.js.php?
HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host:
Press [Enter] to continue:
"kannada.newsnext.live", referrer: "https://kannada.newsnext.live/wp-content/
2023/12/09 06:26:30 [error] 709#709: *277034 FastCGI sent in stderr: "Primary
script unknown" while reading response header from upstream, client:
**ip_address**, server: _, request: "GET
/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKW
orker.js.php?
HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host:
"kannada.newsnext.live", referrer: "https://kannada.newsnext.live/wp-content/p
2023/12/09 06:27:09 [error] 709#709: *277114 FastCGI sent in stderr: "PHP
message: WordPress database error Table
'bitnami_wordpress.wp_rank_math_404_logs' doesn't exist for query SELECT
bndiagnostic-common-lib.sh bndiagnostic.sh components FROM wp_rank_math_404_logs
WHERE uri =
'cinema/thebestactor-kannada-cinema-sandelwood-kannada-short-film-7081.html'
LIMIT 0, 1 made by require('wp-blog-header.php'),
require_once('wp-includes/template-loader.php'),
include('/bitnami/wordpress/wp-content/themes/publisher/404.php'), get_header,
do_action('get_he
```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

Press [Enter] to continue:

[Wordpress]

Found recent WordPress plugin related error messages in the Nginx error log.
```
2023/12/09 06:26:30 [error] 709#709: *277034 FastCGI sent in stderr: "Primary
script unknown" while reading response header from upstream, client:
**ip_address**, server: _, request: "GET
/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKW
orker.js.php?
HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host:
"kannada.newsnext.live", referrer: "https://kannada.newsnext.live/wp-content/p
```
Please check the following guide to deactivate plugins:

https://developer.wordpress.org/cli/commands/plugin/deactivate/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

issues not sorted

### Describe your issue as much as you can

already RAM size is t3a.large. Isn't it enough ? or do we need to increase RAM size ?? . Diagnostic tool showing "your instance has little available RAM Memory".  For remaining issues, we are waiting for your suggestion ??

**Comment by mdhont** [comment]
Could you describe the issue?

**Comment by Divyadevayya** [comment]
Hi,

Wordpress admin is too slow.. It's taking too much time to do any action,
and for uploading images from the backend.
*—*
*Thanks & Regards**,*

Divya Bhagath Nagar
Junior Wordpress Developer
*email: ***@***.***  | *mobile:* 8217235037
*ForthFocus Group*, #283/1A4, First Floor, Chinnu Compound, Near Sri Naga
Bobbarya Temple,
Fish Market Rd, Kundapura, Udupi Dist., Karnataka, India - 576201
[image: facebook icon] <https://www.facebook.com/forthfocusgroup> [image:
twitter icon] <https://twitter.com/forthfocusgroup> [image: youtube icon]
<https://www.youtube.com/channel/UCNUaYZqfyY0fjZRYMpSI8zg> [image: linkedin
icon] <https://www.linkedin.com/company/forthfocus-group> [image: instagram
icon] <https://www.instagram.com/forthfocusgroup>  www.forthfocus.com

**Comment by Divyadevayya** [comment]
Any updates ?? We are waiting for your reply

**Comment by mdhont** [comment]
Many times it's due to a plugin consuming a lot of resources. Could you try disabling all plugins and then re-enable them one by one to check which one?
