### ISSUE TITLE
[Odoo 17] Unable to find Wkhtmltopdf on this system.

### ISSUE THREAD

**Issue by ceni** [bitnami/vms#1300]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

55b704ed-4f91-6c5d-fffe-c85abddfdad8

### bndiagnostic was not useful. Could you please tell us why?

Not found

### Describe your issue as much as you can

Unable to find Wkhtmltopdf on this system. The report will be shown in html.<br><br><a href="http://wkhtmltopdf.org/" target="_blank">wkhtmltopdf.org</a>

**Comment by mdhont** [comment]
On which platform are you running Odoo? Could you tell me how to reproduce the issue?

**Comment by ceni** [comment]
Im using bitnami for virtualbox.The issue happens when I create pdf files (orders, invoices…)El 11 dic 2023, a las 8:56, Michiel ***@***.***> escribió:﻿
On which platform are you running Odoo? Could you tell me how to reproduce the issue?

**Comment by mdhont** [comment]
The following guide explains how you can install wkhtml on your VM:

https://docs.bitnami.com/virtual-machine/apps/pimcore/configuration/install-wkhtmltopdf/
