### ISSUE TITLE
[WordPress] Unable to login to wordpress default website

### ISSUE THREAD

**Issue by nbhalla83** [bitnami/vms#1301]
### Describe your issue as much as you can

Hello,
I am unable to log in to http://10.0.0.83/wp-admin using the default username (user) and default password.

**Comment by jotamartos** [comment]
Hi, 

Are you using a local VM or a cloud instance? Please ensure all services are up and running and use the credentials available in the bitnami_credentials file in the home folder of the bitnami user. 

```
sudo cat /home/bitnami/bitnami_credentials
```

Thanks

**Comment by nbhalla83** [comment]
I can log in now. Please close the case. Thanks 

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 11, 2023 at 9:14 AM, Juan José ***@***.***> wrote:   


Hi,

Are you using a local VM or a cloud instance? Please ensure all services are up and running and use the credentials available in the bitnami_credentials file in the home folder of the bitnami user.
sudo cat /home/bitnami/bitnami_credentials

Thanks
