### ISSUE TITLE
How to offload all resources in Wordpress bitnami lightsail

### ISSUE THREAD

**Issue by dangerdon78** [bitnami/vms#1303]
### Describe your issue as much as you can

All my resources are loading directly from my sever:
https://www.example.com/javascript.js

No, i want to configure a cdn like structure in my site and load my site resources in this way:
https://cdn.example.com/javascript.js
https://cdn.example.com/style.css
https://cdn.example.com/images.webp

Is there any special tool, setting or code, or tutorials to achieve this on wordpress-bitnami-lightsail environment.

**Comment by mdhont** [comment]
I suggest reaching out to the official WordPress forum for assistance. They have a wealth of knowledge and might be able to provide solutions for this specific request. If their response indicates changes in Apache configuration are needed, such as adding redirection rules, we'll be ready to provide guidance.
