### ISSUE TITLE
[Wordpress] Deployment from GCP marketplace  - has been deployed, but contains warnings

### ISSUE THREAD

**Issue by melbleu** [bitnami/vms#1304]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ff44f73d-4a48-b80b-52a4-0614dce11210

### bndiagnostic output

[Mon Dec 11 06:05:59.837884 2023] [proxy_fcgi:error] [pid 5201:tid 
Press [Enter] to continue:
139790204643072] [client **ip_address**:62601] AH01071: Got error '; PHP 
message: [ERROR] : WP_CACHE constant is not present in wp-config.php', referer: 
http://34.124.145.65/wp-admin/edit.php?post_type=page

[Mon Dec 11 06:06:40.924253 2023] [proxy_fcgi:error] [pid 4878:tid 
139790397675264] [client **ip_address**:62610] AH01071: Got error '; PHP 
message: [ERROR] : WP_CACHE constant is not present in wp-config.php', referer: 
http://34.124.145.65/wp-admin/admin.php?page=WordfenceWAF&subpage=waf_options

[Mon Dec 11 08:07:52.431768 2023] [proxy_fcgi:error] [pid 5201:tid 
139790087145216] [client **ip_address**:59150] AH01071: Got error '; PHP 
message: [ERROR] : WP_CACHE constant is not present in wp-config.php', referer: 
http://34.124.145.65/wp-admin/admin.php?page=Wordfence

### bndiagnostic was not useful. Could you please tell us why?

The message error received while deploying wordpress from marketplace

### Describe your issue as much as you can

in the Deployment Manager , I get this message : This deployment has resources from the Runtime Configurator service, which is in Beta. There is no planned date for moving this feature into General Availability (GA). Examples of runtimeconfig types used: runtimeconfig.v1beta1.config, runtimeconfig.v1beta1.waiter

**Comment by jotamartos** [comment]
As we mentioned in this other ticket, we are aware of that warning message. However, you can use the solution without problems

https://github.com/bitnami/vms/issues/181
