### ISSUE TITLE
[<Odoo 16>] <All my multi-company domains foreword to main domain>

### ISSUE THREAD

**Issue by etomProductions** [bitnami/vms#1305]
### Describe your issue as much as you can

Hello,

I tried to read all the documents listed in Binami website with no luck.
Can any one please give me hint how to solve this issue?

when I open www.example-2com
its not showing the website  www.example-2.com but its always foreword to  www.example-1.com.

I had previouse version of Odoo 16 with Binami in Google Cloud and it was working fine. Once I update my version with the new latest Bitnami vm this issue start to show.

Thank you

**Comment by jotamartos** [comment]
Hi @etomProductions,

Thank you for using Bitnami. That's a specific question about the application and how to configure and use different domains. I suggest you take a look at the official documentation and ask in the application's forums to get more information about that. 

Thanks
