### ISSUE TITLE
[WordPress] Bitnami Apache won't start

### ISSUE THREAD

**Issue by luisalmada** [bitnami/vms#1307]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3f2208c0-6ee2-9126-f054-0756892a2fd7

### bndiagnostic output

/|
The bndiagnostic tool has finished searching for errors and has found some 
issues that might be related to yours. The output will be shown on the next 
page:
                                    
Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 975 289 150 0 536 514 Swap: 
634 1 633
```
Press [Enter] to continue:
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Dec 11 11:30:54.383048 2023] [proxy_fcgi:error] [pid 1835290:tid 
140435171149568] [client **ip_address**:62183] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php 
on line 173PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 174PHP message: PHP Warning: Undefined 
array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php on line 
689PHP message: PHP Warning: Undefine [Mon Dec 11 14:38:51.215974 2023] 
[authz_core:error] [pid 1835142:tid 140434600838912] [client 
**ip_address**:33946] AH01630: client denied by server configuration: 
Press [Enter] to continue:
/opt/bitnami/phpmyadmin/index.php
 [Mon Dec 11 15:09:45.642239 2023] [authz_core:error] [pid 1835142:tid 
140435498465024] [client **ip_address**:52846] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/index.php

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 120 of /opt/bitnami/apache2/conf/httpd.conf: 
module version_module is built-in and can't be loaded
```
Please check the configuration.
 

===== End of bndiagnostic tool output =====

                                    
Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the fol
lowing code:

3f2208c0-6ee2-9126-f054-0756892a2fd7

And paste it in your Bitnami Support ticket.

### bndiagnostic was not useful. Could you please tell us why?

Apache service wont start

### Describe your issue as much as you can

Please help me, Im completely lost here.

I tried to Renew an Ssl certificate installed on an instance of aws lightsail and somewhere in the process, something failed, I guess, I tried to fix it changing some text in the apache conf files and ended worse. 

Ive done everything i found online and the apache service wont start, 

I get this when systemctl status bitnami.service

● bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-12-12 01:32:26 UTC; 13s ago
    Process: 8989 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
        CPU: 1.216s

Dec 12 01:32:26 ip-172-26-11-114 bitnami[9054]: 2023-12-12T01:32:26.188Z - error: Unable t>
Dec 12 01:32:26 ip-172-26-11-114 bitnami[9102]: ## 2023-12-12 01:32:26+00:00 ## INFO ## Ru>
Dec 12 01:32:26 ip-172-26-11-114 bitnami[9102]: ## 2023-12-12 01:32:26+00:00 ## INFO ## Ru>
Dec 12 01:32:26 ip-172-26-11-114 bitnami[9102]: ## 2023-12-12 01:32:26+00:00 ## INFO ## Ru>
Dec 12 01:32:26 ip-172-26-11-114 bitnami[9102]: ## 2023-12-12 01:32:26+00:00 ## INFO ## Ru>
Dec 12 01:32:26 ip-172-26-11-114 bitnami[9102]: ## 2023-12-12 01:32:26+00:00 ## INFO ## Ru>
Dec 12 01:32:26 ip-172-26-11-114 systemd[1]: bitnami.service: Control process exited, code>
Dec 12 01:32:26 ip-172-26-11-114 systemd[1]: bitnami.service: Failed with result 'exit-cod>
Dec 12 01:32:26 ip-172-26-11-114 systemd[1]: Failed to start LSB: bitnami init script.
Dec 12 01:32:26 ip-172-26-11-114 systemd[1]: bitnami.service: Consumed 1.216s CPU time.

and this when journalctl -xe

 
░░ An ExecStart= process belonging to unit bitnami.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Dec 12 01:32:26 ip-172-26-11-114 systemd[1]: bitnami.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitnami.service has entered the 'failed' state with result 'exit-code'.
Dec 12 01:32:26 ip-172-26-11-114 systemd[1]: Failed to start LSB: bitnami init script.
░░ Subject: A start job for unit bitnami.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit bitnami.service has finished with a failure.
░░ 
░░ The job identifier is 2748 and the job result is failed.
Dec 12 01:32:26 ip-172-26-11-114 systemd[1]: bitnami.service: Consumed 1.216s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitnami.service completed and consumed the indicated resources.
Dec 12 01:32:26 ip-172-26-11-114 sudo[8980]: pam_unix(sudo:session): session closed for user root
Dec 12 01:32:35 ip-172-26-11-114 dhclient[411]: PRC: Renewing lease on eth0.
Dec 12 01:32:35 ip-172-26-11-114 dhclient[411]: XMT: Renew on eth0, interval 10540ms.
Dec 12 01:32:35 ip-172-26-11-114 dhclient[411]: RCV: Reply message on eth0 from fe80::40:edff:fe01:90c3.
Dec 12 01:33:01 ip-172-26-11-114 CRON[9144]: pam_unix(cron:session): session opened for user bitnami(uid=100>
Dec 12 01:33:01 ip-172-26-11-114 CRON[9145]: (bitnami) CMD (cd /opt/bitnami/stats && ./agent.bin --run -D)
Dec 12 01:33:02 ip-172-26-11-114 CRON[9144]: pam_unix(cron:session): session closed for user bitnami
Dec 12 01:33:14 ip-172-26-11-114 sshd[9200]: Received disconnect from 220.180.112.208 port 50133:11: Bye Bye>
Dec 12 01:33:14 ip-172-26-11-114 sshd[9200]: Disconnected from authenticating user root 220.180.112.208 port>

My website is still down and I dont know what to do, help would be very much appreciated.

Thanks in advance

Regards

Luis Almada

**Comment by jotamartos** [comment]
The tool warned you about some error messages in the Apache's log 

```
apache2: Syntax error on line 120 of /opt/bitnami/apache2/conf/httpd.conf: 
module version_module is built-in and can't be loaded
```

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

Please take a look at any change you made lately in the Apache's configuration and ensure it doesn't return any errors. You can launch this script too to start the service, it should provide more information if there is any error.

```
sudo /opt/bitnami/scripts/apache/start.sh
```

**Comment by luisalmada** [comment]
Hi Juan Jose

Thanks so much for your reply, I made so many changes to the apache configuration, first trying to install the new SSL and now just to make it work, that I honestly dont know where to start. Is there a way to restore the apache configuration to default, or what it needs to run in aws lightsail? 

I also tried sudo /opt/bitnami/scripts/apache/start.sh and it did work but now php-fpm wont start.

Thanks so much for the help.

**Comment by jotamartos** [comment]
>Is there a way to restore the apache configuration to default, or what it needs to run in aws lightsail?

No, there is not a way to do so. However, you can launch another Lightsail instance or a local VM and compare the different .conf files under /opt/bitnami/apache/conf

>I also tried sudo /opt/bitnami/scripts/apache/start.sh and it did work but now php-fpm wont start.

Please take a look at the PHP's log file and try to start that service using the start.sh script under the /opt/bitnami/scripts directory as you did with Apache to try to obtain more information.

**Comment by luisalmada** [comment]
Thanks again for your reply.

I launched another lightsail instance and managed to access the server with filezilla, I then copied the conf files under /opt/bitnami/apache/conf to the instance. With that I managed to start apache, php-fpm and mariadb. But my website is still down. 

When doing sudo /opt/bitnami/ctlscript.sh start 
still shows an error.

Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

Then systemctl status shows

bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-12-13 17:54:51 UTC; 31s ago
    Process: 25466 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
      Tasks: 29 (limit: 2311)
     Memory: 242.8M
        CPU: 1.899s
     CGroup: /system.slice/bitnami.service
             ├─22245 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
             ├─22249 php-fpm: pool www
             ├─22250 php-fpm: pool www
             ├─22251 php-fpm: pool www
             ├─22252 php-fpm: pool www
             ├─22253 php-fpm: pool www
             ├─22254 php-fpm: pool www
             ├─22255 php-fpm: pool www
             ├─22256 php-fpm: pool www
             ├─22257 php-fpm: pool www
             ├─22258 php-fpm: pool www
             ├─22259 php-fpm: pool www
             ├─22260 php-fpm: pool www
             ├─22261 php-fpm: pool www
             ├─22262 php-fpm: pool www
             ├─22263 php-fpm: pool www
             ├─22264 php-fpm: pool www
             ├─22265 php-fpm: pool www
             ├─22266 php-fpm: pool www
             ├─22267 php-fpm: pool www
             ├─22268 php-fpm: pool www
             └─22280 /opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb>

Dec 13 17:54:51 ip-172-26-4-250 systemd[1]: bitnami.service: Unit process 22262 (php-fpm) >
Dec 13 17:54:51 ip-172-26-4-250 systemd[1]: bitnami.service: Unit process 22263 (php-fpm) 

Im still really lost here, is there a way to export the wordpress database to migrate to another hosting provider? 

Thanks so much for your help

**Comment by jotamartos** [comment]
It seems Apache did not start successfully. What's the error you get when launching this script 

```
sudo /opt/bitnami/scripts/apache/start.sh
```

>Im still really lost here, is there a way to export the wordpress database to migrate to another hosting provider?

You will need to create a backup of the [bitnami_wordpress database](https://docs.bitnami.com/general/apps/wordpress/administration/backup-restore-mysql-mariadb/) and copy all the files you uploaded to the application. You will find them under the /opt/bitnami/wordpress folder.
