### ISSUE TITLE
[LAMP] CORS issue

### ISSUE THREAD

**Issue by m-bance** [bitnami/vms#1308]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2f7ee3d7-dad1-26e8-dd67-ac5cfc3dd7c2

### bndiagnostic was not useful. Could you please tell us why?

Diagnostic tool did not identify my issue

### Describe your issue as much as you can

Hello,

I am having issues with CORS in my web application in AWS Lightsail using the LAMP stack.

I am receiving errors in the console relating to CORS preventing scripts/fonts from loading, an example: 
```
Access to font at 'https://xyz.com/.../libs/@mdi/font/fonts/materialdesignicons-webfont.ttf?v=2.4.85' from origin 'https://xyz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

The application itself has headers creating a CORS policy like the below and have also tried removing this with no success:

```
<!-- CSP -->
<meta http-equiv="Access-Control-Allow-Origin" content="*">
<meta http-equiv="Content-Security-Policy" content="
    default-src 'self'; 
    script-src 'self';
    style-src 'self';
    img-src 'self';
    connect-src 'self';
    font-src 'self';">
```

I have read Bitnami docs mentioning CORS is disabled by default in Wordpress in Bitnami, is this also the case in the LAMP stack, if so, how do I enable this?

I have added the following to the 00_status-vhost.conf to no avail:

```
<Directory /opt/bitnami/apache>
Header set Access-Control-Allow-Origin "*"
</Directory>
```

I'd appreciate any help with this.

**Comment by jotamartos** [comment]
Hi @m-bance,

You need to follow a similar process to the one we have documented with WordPress 

https://docs.bitnami.com/aws/apps/wordpress/configuration/enable-cors-wordpress/

However, you will need to use the path where your app is instead of using /opt/bitnami/wordpress. Remember to restart Apache for the changes to take effect.
