### ISSUE TITLE
[LAMP] Website opens different with https and without https

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1309]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f07ba749-c999-e951-677f-e714663b0471

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem Size Used Avail Use% Mounted on /dev/xvda1 20G 19G 18M 100% /
```
Please check your cloud provider's documentation for more information.

Your instance has little available RAM memory.
```
Press [Enter] to continue:
 total used free shared buff/cache available Mem: 472 335 8 52 128 72 Swap: 634 
535 99
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Dec 11 08:17:07.126157 2023] [authz_core:error] [pid 1678395:tid 
140339901773568] [client **ip_address**:51480] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
 [Tue Dec 12 18:39:41.100441 2023] [authz_core:error] [pid 1765168:tid 
140339851417344] [client **ip_address**:43886] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
 [Tue Dec 12 18:44:03.745046 2023] [authz_core:error] [pid 1765168:tid 
140339876595456] [client **ip_address**:42446] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin

```
Please check the following guide to troubleshoot server issues:
 
Press [Enter] to continue:
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

Hello,

My website opens differently with HTTPS and without HTTPS.

[With HTTPS it shows a default Bitnami page. ](https://github.com/bitnami/vms/assets/10163650/972621f0-91f3-4ba4-8436-ee6d1f8cba8e)

[Without HTTPS it shows my WordPress website.](https://github.com/bitnami/vms/assets/10163650/4ba52906-4d07-441e-b443-2f09a8f0d8ba)

Kindly support.

**Comment by huzanf** [comment]
Hi @jotamartos 
I've made the necessary changes. 

[Screenshot](https://github.com/bitnami/vms/assets/10163650/5b67a010-d7bd-4813-8c76-6b7254428edf)

**Comment by jotamartos** [comment]
This is a basic question regarding Apache, please read  the documentation carefully. You will need to set the ServerName using your non-www domain and the ServerAlias using the www one to allow both domains use the same virtual host.
