### ISSUE TITLE
Error 404: Not Found The requested URL was not found on this server

### ISSUE THREAD

**Issue by nyathirak** [bitnami/vms#131]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

df9bd9c0-acf0-6986-25ae-7daaf5a51cb1

### bndiagnostic output

No  issues found

### bndiagnostic was not useful. Could you please tell us why?

It did not detect any issue on the WordPress packaged for bitnami VSI server on IBM Cloud

### Describe your issue as much as you can

I am hosting an e-commerce WordPress website on WordPress packaged for bitnami VSI server on IBM Cloud. Everything is set up as expected and works well. I can currently access my website on the domain, however, I cannot access the sub pages and it gives the following error.
![image](https://user-images.githubusercontent.com/43218594/179450485-690fdc2c-795f-4a18-934f-1715261cb26f.png)

**Comment by jotamartos** [comment]
If you can access the main and admin sites of your deployment but can't access the "sub pages", there should be something wrong configured in the application. Did you modify any setting after deploying the solution? We suggest you contact the WordPress' support team to get more information about this error and how to fix it. 

https://wordpress.org/support/
