### ISSUE TITLE
[Moodle] How to enable php_xmlrpc extension in AMI.

### ISSUE THREAD

**Issue by rahulcpr** [bitnami/vms#1311]
### Describe your issue as much as you can

Hello Bitnami Support,

As per Moodle's Environment(Server Check) requirement,  php_extension "xmlrpc" must be enabled for best results.
We are using Bitnami AMI in which we want to enable this extension but unable to do it.

Please help for mentioned extensions. 1. extension=php_xmlrpc.dll
                                      2. zlib.output_compression=ON
                                      3. zlib.output_compression_level = 6
                                      4. display_ errors=off 

<img width="725" alt="image" src="https://github.com/bitnami/vms/assets/25370849/b6bab771-7b1f-4acf-a675-692c4668061b">

AMI Details :- 
AMI-0aef149f5ae69673b
bitnami-moodle-3.11.11-21-r25-linux-debian-11-x86_64-hvm-ebs-nami

**Comment by jotamartos** [comment]
Hi @rahulcpr,

Thank you for using Bitnami. Just to confirm, you made those changes in a fresh instance but it's shown as disabled in the Moodle's admin panel, right? Did you restart the Apache and PHP-FPM services for the changes to take effect? 

Thanks

**Comment by rahulcpr** [comment]
Hi Jotamartos,

Yes, it's shown as disabled in the Moodle's admin panel. I restarted the Apache and PHP-FPM services as well. It isn't resolve this issue. Please suggest some other solution.

**Comment by rahulcpr** [comment]
Reopening.

**Comment by jotamartos** [comment]
Hi @rahulcpr,

I just tried to reproduce the issue but all PHP extensions are properly installed and configured when using the latest version of Moodle 

![Screenshot 2024-01-15 at 11 21 12](https://github.com/bitnami/vms/assets/8791635/12d5701a-10e8-42fb-85f4-86b3b1f5a60a)

From your screenshot, I can see you are using an old version of Moodle and that can be the cause of the issue. I suggest you migrate to the latest version to make this work.

**Comment by rahulcpr** [comment]
For now, i am unable to migrate to latest version. Can you please suggest some solution for moodle 3.11.14.

**Comment by jotamartos** [comment]
xmlrpc PHP extension [requires compilation](https://www.php.net/manual/en/xmlrpc.installation.php#:~:text=XML%2DRPC%20support%20in%20PHP,to%20enable%20XML%2DRPC%20support.) and that's not something  you can enable in a running instance. You will need to migrate to a newer version.
