### ISSUE TITLE
Mastodon .well-known functionality broken by Lets Encrypt

### ISSUE THREAD

**Issue by pkreissel** [bitnami/vms#1312]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

268b94eb-fbed-e447-2fc7-4272190b7366

### bndiagnostic output

The important part is this Error: 

> 2023/12/16 13:29:37 [error] 3387#3387: *986 open() 
> "/opt/bitnami/apps/letsencrypt/.well-known/webfinger" failed (2: No such file or 
> directory), client: **ip_address**, server: _, request: "GET 
> /.well-known/webfinger?resource=acct:user@example.social HTTP/1.1", host: 
> "example.social"

### bndiagnostic was not useful. Could you please tell us why?

It was helpful

### Describe your issue as much as you can

Here is what I think is happening: Mastodon uses the .well-known endpoint but so does Letsencrypt tool. Because I created a Letsencrypt cert with /bncert-tool Mastodon was kicked out of the .well-known endpoint. However this endpoint is extremely important for Mastodons functionality.

**Comment by mdhont** [comment]
Could you give more details regarding the error(s) you are getting after running the bncert tool?

**Comment by pkreissel** [comment]
Mastodon uses the web finger spec to expose user data to other servers:

https://docs.joinmastodon.org/spec/webfinger/

Without this the functionality of mastodon is severely limited. 

In my Mastodon instance using the bitnami package this endpoint does a 404 as seen above in the logs. 

When I check my nginx config I see that the letsencrypt functionality now uses the "well known" endpoint for itself, and this is the reason why I see the 404. 

I will probably solve this by editing my nginx config manually when I get the time , but this should be fixed, because it currently prevents users from using the Mastodon bitnami package with lets encrypt (which in theory saves a lot of time).

**Comment by mdhont** [comment]
I will try to reproduce it and create a ticket to fix it, thanks for notifying

**Comment by pkreissel** [comment]
Issue is not resolved

**Comment by AndrewKMoses** [comment]
Not solved

**Comment by mdhont** [comment]
As a workaround I recommend creating a certificate using the [alternative approach](https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach).

**Comment by pkreissel** [comment]
Not resolved

**Comment by mdhont** [comment]
Hi @pkreissel, I recommend using the [alternative approach](https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach) for generating a certificate.
