### ISSUE TITLE
[wordpress] gonit not auto restarting any services on fails

### ISSUE THREAD

**Issue by ErnstDinkelmann** [bitnami/vms#1313]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2f57a063-7a96-15fb-9057-aa2a4d29df9b

### bndiagnostic output

I'd rather not show the output publicly. Kindly refer uploaded version.

### bndiagnostic was not useful. Could you please tell us why?

This has been an issue long before these minor diagnostics listings. They seem completely unrelated.

### Describe your issue as much as you can

Gonit status shows "Running" and "Monitored" for all four services (apache, mariadb, php-fpm and varnish).
However, from time to time, we have a crash, which end's up killing all these services, meaning website down.
I would have expected gonit to automatically restart all of these after a few minutes.

top output, we are on a T3 Medium, with 1GB swop:
%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.2 st
MiB Mem :   3873.9 total,    549.1 free,   2676.2 used,    648.6 buff/cache
MiB Swap:   1024.0 total,    996.2 free,     27.8 used.    834.4 avail Mem

Also, not sure if this is related, but after a server reboot, varnish is last to start and takes about 2-3 minutes to start after the other services are running I did notice in systemctl: "Skipping service start operation for varnish". But that may be normal though, not sure.

I've not made any changes to the gonit config files.

**Comment by ErnstDinkelmann** [comment]
@jotamartos 
Thanks, but there is NO restart of services at all. Just had another crash and got some additional information now.
Seems there is some OOM happening and then the OOM KIller kills one of the bitnami.service processes, which then stops gonit from monitoring.

How do we resolve this?

In the apache error log:
[Sun Dec 24 12:17:28.529452 2023] [proxy_http:error] [pid 321889:tid 139744134522624] (70007) The timeout specified has expired: [client client_ip:client_port] AH01102: error reading status line from remote server 127.0.0.1:81

Shortly after the above, time wise, bitnami.service log:
Dec 24 12:18:07 ip- systemd[1]: bitnami.service: A process of this unit has been killed by the OOM killer.
Dec 24 12:18:09 ip- bitnami[3501069]: 2023-12-24T12:18:09.132Z - info: Saving configuration info to disk
Dec 24 12:18:10 ip- bitnami[3501069]: 2023-12-24T12:18:10.022Z - info: Stop monitoring services from gonit
Dec 24 12:18:10 ip- bitnami[3501069]: 2023-12-24T12:18:10.144Z - info: Performing service stop operation for php
Dec 24 12:18:11 ip- bitnami[3501069]: php 12:18:11.77 INFO  ==> php-fpm stopped
Dec 24 12:18:11 ip- bitnami[3501069]: 2023-12-24T12:18:11.781Z - info: Performing service stop operation for mariadb
Dec 24 12:18:12 ip- bitnami[3501069]: mariadb 12:18:12.15 INFO  ==> mariadb is not running
Dec 24 12:18:12 ip- bitnami[3501069]: 2023-12-24T12:18:12.152Z - info: Performing service stop operation for apache
Dec 24 12:18:13 ip- bitnami[3501069]: apache 12:18:13.51 INFO  ==> apache stopped
Dec 24 12:18:13 ip- bitnami[3501069]: 2023-12-24T12:18:13.519Z - info: Skipping service stop operation for varnish
Dec 24 12:18:13 ip- systemd[1]: bitnami.service: Failed with result 'oom-kill'.
Dec 24 12:18:13 ip- systemd[1]: bitnami.service: Unit process 1739 (gonit) remains running after unit stopped.
Dec 24 12:18:13 ip- systemd[1]: bitnami.service: Unit process 265866 (varnishd) remains running after unit stopped.
Dec 24 12:18:13 ip- systemd[1]: bitnami.service: Unit process 265880 (cache-main) remains running after unit stopped.

**Comment by jotamartos** [comment]
Hi @ErnstDinkelmann,

>Dec 24 12:18:13 ip- systemd[1]: bitnami.service: Unit process 1739 (gonit) remains running after unit stopped.

It seems monit/gonit continued worked after the issue, did you confirm that? 

```
sudo gonit status
```

If the process is not running, it won't be able to start the services. 

You can check if gonit works as expected by stopping one of the processes and waiting for it to start the service again. gonit should start it without problems. If not, as a quick solution, I suggest you create a script that checks if the services are up and running and start them if they are not. You can run that script using a cron job.

**Comment by ErnstDinkelmann** [comment]
Hi @jotamartos 
I did confirm, and Gonit was running but was no longer monitoring anything. You'll see this in the bitnami.service log: "info: Stop monitoring services from gonit".

Why would an OOM of some, say php-fpm service, cause the bitnami.service to stop gonit from monitoring other services?

I don't know which service/process/pid caused the OOM, but surely these are the circumstances that gonit should not be stopped as its main purpose is to recover from something like that.

I'm sure there are work-arounds (like a script + cron), but I'm actually trying to avoid it for now. I don't know what other consequences that might have - e.g. under certain circumstances there being two things trying to restore services, etc. Not to mention the resource consumption of checking every few minutes whether services are up.

Could you please consider why gonit monitoring would be stopped here in the first place.
I guess the actual question is why this OOM triggered the bitnami.service shutdown script.

**Comment by jotamartos** [comment]
Hi @ErnstDinkelmann,

I just tried to reproduce the issue and everything worked as expected. I killed the Apache process by running the kill command 

```
sudo kill -9 APACHE_PIDs
```

After that, I confirmed that Apache was stopped 

```
bitnami@ip-172-31-93-209:~$ sudo /opt/bitnami/ctlscript.sh status
apache not running
mariadb already running
php-fpm already running
bitnami@ip-172-31-93-209:~$ sudo gonit status

Uptime                         1m19s
Last Check                     2024-01-08 11:59:09.308345611 +0000 UTC m=+0.007887061
Next Check                     2024-01-08 12:01:09.308345611 +0000 UTC m=+120.007887061
Pid                            2214
Pid File                       /var/run/gonit.pid
Control File                   /etc/gonit/gonitrc
Socket File                    /var/run/gonit.sock
Log File                       /var/log/gonit.log
Process 'apache'
  status                                        Stopped
  uptime                                             0s
  monitoring status                           monitored

Process 'mariadb'
  status                                        Running
  pid                                              1267
  uptime                                          1m19s
  monitoring status                           monitored

Process 'php-fpm'
  status                                        Running
  pid                                               999
  uptime                                          1m19s
  monitoring status                           monitored
```

I waited for the "Next Check" date and confirmed that Apache was started 

```
bitnami@ip-172-31-93-209:~$ sudo /opt/bitnami/ctlscript.sh status
apache already running
mariadb already running
php-fpm already running
bitnami@ip-172-31-93-209:~$ sudo gonit status

Uptime                         2m3s
Last Check                     2024-01-08 12:01:09.307680972 +0000 UTC m=+120.007222445
Next Check                     2024-01-08 12:03:09.307680972 +0000 UTC m=+240.007222445
Pid                            2214
Pid File                       /var/run/gonit.pid
Control File                   /etc/gonit/gonitrc
Socket File                    /var/run/gonit.sock
Log File                       /var/log/gonit.log
Process 'apache'
  status                                        Running
  pid                                              2506
  uptime                                             2s
  monitoring status                           monitored

Process 'mariadb'
  status                                        Running
  pid                                              1267
  uptime                                           2m3s
  monitoring status                           monitored

Process 'php-fpm'
  status                                        Running
  pid                                               999
  uptime                                           2m3s
  monitoring status                           monitored
```

If gonit is running, it should start the process if stopped. You can run the "reload" command in gonit to reinitialize the tool to see if that's the issue.

**Comment by ErnstDinkelmann** [comment]
I could not debug this to find a solution. My workaround is to setup the os itself to restart after an OOM, after 10 secs.

Realtime:
sudo sysctl vm.panic_on_oom=1
sudo sysctl kernel.panic=10

For setting to survive after restart:
add the above settings to /etc/sysctl.conf

**Comment by ErnstDinkelmann** [comment]
I suspect it happens on orders with many items and our courier plugins, which has to quote rates by calculating most optimal packaging, consumes more and more mem, then OOM.

**Comment by Chi-Hoang** [comment]
Why is this closed? We had the same issue. After the OOM killer terminated PHP-FPM, every service went offline and Gonit was unable to restart them. Instead, it displays the following messages:

Diff
Copy
Insert
New
time="2025-01-21T03:07:28Z" level=warning msg="A previous operation for mariadb-824634221664 is still in process"
time="2025-01-21T03:07:28Z" level=warning msg="A previous operation for php-fpm-824634223904 is still in process"
time="2025-01-21T03:07:28Z" level=warning msg="A previous operation for nginx-824634222784 is still in process"
time="2025-01-21T03:07:28Z" level=warning msg="A previous operation for php-fpm-824634223904 is still in process"
time="2025-01-21T03:07:28Z" level=warning msg="A previous operation for php-fpm-status-824634224784 is still in process"
time="2025-01-21T03:07:28Z" level=warning msg="A previous operation for mariadb-824634221664 is still in process"
time="2025-01-21T03:07:28Z" level=warning msg="A previous operation for nginx-824634222784 is still in process"
time="2025-01-21T03:07:28Z" level=warning msg="A previous operation for sshd-824634225264 is still in process"
time="2025-01-21T03:07:28Z" level=info msg="Performing check%!(EXTRA string=php-fpm-status)"
time="2025-01-21T03:07:28Z" level=info msg="Performing process check sshd"
time="2025-01-21T03:07:28Z" level=info msg="Performing process check sshd"
time="2025-01-21T03:07:28Z" level=info msg="Performing check%!(EXTRA string=php-fpm-status)"
time="2025-01-21T03:09:24Z" level=info msg="Performing checks"
time="2025-01-21T03:11:24Z" level=info msg="Performing checks"
time="2025-01-21T03:13:24Z" level=info msg="Performing checks"
time="2025-01-21T03:15:24Z" level=info msg="Performing checks"
time="2025-01-21T03:17:24Z" level=info msg="Performing checks"
time="2025-01-21T03:19:24Z" level=info msg="Performing checks"
time="2025-01-21T03:21:24Z" level=info msg="Performing checks"
time="2025-01-21T03:23:24Z" level=info msg="Performing checks"
time="2025-01-21T03:25:24Z" level=info msg="Performing checks"
time="2025-01-21T03:27:24Z" level=info msg="Performing checks"
time="2025-01-21T03:29:24Z" level=info msg="Performing checks"
time="2025-01-21T03:31:24Z" level=info msg="Performing checks"
time="2025-01-21T03:33:24Z" level=info msg="Performing checks"

**Comment by jotamartos** [comment]
Hi @Chi-Hoang,

Thanks for using Bitnami. This is an old thread so it'd be great if you can create a new one. 

However, before doing so, we suggest you check if your instance is running out of resources and that's the reason behind the issue. You can always try to start gonit/monit (depending on the version you have) and monitor if services are started.

**Comment by Chi-Hoang** [comment]
Hi @jotamartos ,

Sure, it's my pleasure. When I manually kill PHP-FPM or Nginx, Gonit is able to restart them. However, it doesn't work in the critical condition of an OOM (Out-of-Memory) panic. After the OOM kills the process, Gonit is still running—as seen in the log above—but it's unable to restart the process.
