### ISSUE TITLE
SuiteCRM 8.x

### ISSUE THREAD

**Issue by CrownParkComputing** [bitnami/vms#1315]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Too complicated

### bndiagnostic output

N/A

### bndiagnostic was not useful. Could you please tell us why?

did not understand

### Describe your issue as much as you can

https://community.suitecrm.com/t/oauth-problem-where-should-the-redirect-uri-point/88269

The redirecturl in SuiteCRM when creating a Microsoft Auth Connection is invalid. see the link above. It should show the current url being used.

**Comment by mdhont** [comment]
It doesn't seem related to the Bitnami configuration of the app, but rather to an upstream issue. I recommend asking the the official forum.
