### ISSUE TITLE
[Redmine] Can I have latest Redmine native installer for Windows server which with subversion plugin include ?

### ISSUE THREAD

**Issue by suzhouclark** [bitnami/vms#1319]
### Describe your issue as much as you can

Could you please provide temp address for  **latest** Redmine **native installer** for **Windows server** which with **subversion plugin include** ?
Some new version only include git, but we need subversion instead.

**Comment by mdhont** [comment]
Unfortunately,  we no longer have windows installers available for download.

**Comment by suzhouclark** [comment]
Anybody have windows install file ?

**Comment by jotamartos** [comment]
Hi @suzhouclark,

this is the last version we released in bitnami.com.

https://downloads.bitnami.com/files/stacks/redmine/5.0.3-0/bitnami-redmine-5.0.3-0-windows-x64-installer.exe

As @mdhont mentioned, we no longer support installers so this is an outdated version and we suggest you use the Redmine OVA to deploy this solution in Windows.
