### ISSUE TITLE
[<Bitnami>] <This site can’t be reached>

### ISSUE THREAD

**Issue by Kavita-desai** [bitnami/vms#132]
### Describe your issue as much as you can

Hello, Bitnami Team
I wanted to show my website to the client, but I could not do that, as facing such errors.
"This site can’t be reached" I faced this error while I Activated the "Elementor" Plugin, I tried to solve it my way, and search for this error on Youtube and other places, but could not able to solve it. and I found that many peoples have to face the same issue and No solution. So please, Help me to find a solution.
Thank You

**Comment by mfrankii** [comment]
Hi, 
Is there an update on this issue? I also have this problem.

**Comment by recena** [comment]
FYI https://github.com/bitnami/vms/issues/133#issuecomment-1188825461

**Comment by Kavita-desai** [comment]
> Hi, Is there an update on this issue? I also have this problem.

No, Still facing same issue

**Comment by Kavita-desai** [comment]
Why this issue is closed? I didn't receive any solution

**Comment by mdhont** [comment]
I recommend asking the plugin support for more information regarding this issue. It does not seem related to the Bitnami configuration.
