### ISSUE TITLE
[Wordpress-Bitnami-AWS-EC2] Services are shutting down frequently

### ISSUE THREAD

**Issue by shweta-dm** [bitnami/vms#1320]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

38d505ed-313d-e36a-72bf-1537520c3c8e

### bndiagnostic output

![Screenshot 1](https://github.com/bitnami/vms/assets/154450680/ad390e65-b055-4de8-9235-94c93903e135)
![Screenshot 2](https://github.com/bitnami/vms/assets/154450680/d8c482ca-c86d-4da9-aa1d-d4d4c0bcda53)
![Screenshot 3](https://github.com/bitnami/vms/assets/154450680/8447b27d-d788-4d85-9a37-8d4685eb88da)

### bndiagnostic was not useful. Could you please tell us why?

My server and db are shutting down automatically

### Describe your issue as much as you can

When I restart the server, the services start normally. But after 1 and 2 hours the services are shutting down automatically 

May i know the issue?

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one. In many cases a single WordPress plugin can be the cause of the issue. Try disabling the plugins to see if that changes anything:

    wp plugin deactivate --all
