### ISSUE TITLE
[<LAMP>] SSL Website not opening

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1321]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c4364902-6104-6068-f0ed-ff63fbd733b7

### bndiagnostic output

===== Begin of bndiagnostic tool output =====
 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 
[Resources]

Your instance has little available RAM memory.
 total used free shared buff/cache available Mem: 950 431 65 5 454 339 Swap: 634 
18 616
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
[Thu Dec 21 02:08:27.909063 2023] [ssl:error] [pid 62245:tid 140138801784576] 
[client **ip_address**:34126] AH02042: rejecting client initiated renegotiation

Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

Hi,
My website is not loading. Can you please help?

Additionally, this is a new instance and the resources are completely utilized. Not sure if the server is not even pointing anywhere what's causing it?

Assistance is appreciated.

Huzan

**Comment by huzanf** [comment]
My website is now showing the default Bitnami page. How do I remove that?

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one.

**Comment by huzanf** [comment]
Thanks @mdhont .
Can you help me wit the below:
> My website is now showing the default Bitnami page. How do I remove that?

**Comment by mdhont** [comment]
Did you follow the steps in this guide:

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

**Comment by huzanf** [comment]
Thanks @mdhont 
I have done this. However, the website doesn't redirect non-www to www. I had done that while setting up the SSL.

The BN Support tool is: `93e4c784-196f-fc86-0abf-3c6d04e9b8d7`

Below is the output:

```
**===== Begin of bndiagnostic tool output =====**
? Resources: Found possible issues
? Connectivity: Found possible issues
✓ Mariadb: No issues found
✓ Processes: No issues found
? Apache: Found possible issues
✓ Php: No issues found

**[Resources]**
Your instance has little available RAM memory.
total used free shared buff/cache available Mem: 950 510 77 65 363 211 Swap: 
634 135 499
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:

**[Connectivity]**

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

**[Apache]**

Found recent error or warning messages in the Apache error log.

[Thu Dec 28 06:25:55.475549 2023] [authz_core:error] [pid 222228:tid 
140275301213952] [client **ip_address**:50286] AH01630: client denied by server 
configuration: /opt/bitnami/gotaxless/favicon.ico, referer: 
https://www.digitaldwarfs.com/
 [Thu Dec 28 06:25:55.607999 2023] [authz_core:error] [pid 222228:tid 
140275292821248] [client **ip_address**:50286] AH01630: client denied by server 
configuration: /opt/bitnami/gotaxless/
 [Thu Dec 28 06:25:55.640219 2023] [authz_core:error] [pid 222228:tid 
140275284428544] [client **ip_address**:50286] AH01630: client denied by server 
configuration: /opt/bitnami/gotaxless/favicon.ico, referer: 
https://www.digitaldwarfs.com/

Press [Enter] to continue:

Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

**===== End of bndiagnostic tool output =====**
```

**Comment by huzanf** [comment]
Thanks @mdhont 
This worked. However, I followed the same steps for adding another website with a different domain, but it doesn't work. When I hit the second domain, it gets redirected to the first domain. Not sure why?

How can I have multiple websites on the same instance?

Here is the latest BN Support tool ID: `2b35f45e-62fc-9d9d-a0f6-2a8d50dd3c74`

Below is the output:

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 950 567 77 120 305 111 Swap: 
634 196 438
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Dec 28 06:25:55.475549 2023] [authz_core:error] [pid 222228:tid 
140275301213952] [client **ip_address**:50286] AH01630: client denied by server 
configuration: /opt/bitnami/gotaxless/favicon.ico, referer: 
https://www.digitaldwarfs.com/
 [Thu Dec 28 06:25:55.607999 2023] [authz_core:error] [pid 222228:tid 
140275292821248] [client **ip_address**:50286] AH01630: client denied by server 
configuration: /opt/bitnami/gotaxless/
 [Thu Dec 28 06:25:55.640219 2023] [authz_core:error] [pid 222228:tid 
140275284428544] [client **ip_address**:50286] AH01630: client denied by server 
configuration: /opt/bitnami/gotaxless/favicon.ico, referer: 
https://www.digitaldwarfs.com/

Press [Enter] to continue:
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

**Comment by huzanf** [comment]
Hi @mdhont,
There's another issue now. BN Support tool ID: `153a8295-1fef-34cd-8c63-b748cf4c5fd6`

```
===== Begin of bndiagnostic tool output ===== 
? Resources: Found possible issues
? Connectivity: Found possible issues
✓ Mariadb: No issues found
✓ Processes: No issues found
? Apache: Found possible issues
✓ Php: No issues found
 
[Resources]

Your instance has little available RAM memory.

 total used free shared buff/cache available Mem: 950 319 62 4 569 447 Swap: 634 
0 634

You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.

[Thu Dec 28 08:50:58.173181 2023] [ssl:emerg] [pid 944:tid 140642808814848] SSL 
Library Error: error:0909006C:PEM routines:get_name:no start line (Expecting: EC 
PARAMETERS) -- Bad file contents or format - or even just a forgotten 
SSLCertificateKeyFile?
 [Thu Dec 28 08:50:58.173193 2023] [ssl:emerg] [pid 944:tid 140642808814848] SSL 
Library Error: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no 
certificate assigned
 [Thu Dec 28 08:50:58.173197 2023] [ssl:emerg] [pid 944:tid 140642808814848] 
AH02312: Fatal error initialising mod_ssl, exiting.

Please check the following guide to troubleshoot server issues:
Press [Enter] to continue:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====
```

Can you also kindly assist me with the [earlier post](https://github.com/bitnami/vms/issues/1321#issuecomment-1870910601).

**Comment by huzanf** [comment]
Hi @mdhont,

I would like your help.

Huzan

**Comment by huzanf** [comment]
Hi @mdhont 
Wishing you a Happy New Year.

I'd appreciate your support on my two comments posted earlier:
https://github.com/bitnami/vms/issues/1321#issuecomment-1870910601
https://github.com/bitnami/vms/issues/1321#issuecomment-1870968930

**Comment by huzanf** [comment]
Hi @mdhont 

> One is that the system is low on resources, I recommend upgrading to a more powerful machine, or check which processes are consuming them.

I am using 2 GB RAM, 2 vCPUs, 60 GB SSD and still I am facing the memory problem. What is the minimum memory recommended?

New BN Support tool code: `1ab6f2c2-42c2-a844-2137-18834ade2a83`
If you check the storage is not even completely utilized.

Looking forward to your support.

**Comment by mdhont** [comment]
I recommend checking the following guides for troubleshooting performance issues with Bitnami LAMP:

https://docs.bitnami.com/aws/infrastructure/lamp/troubleshooting/
