### ISSUE TITLE
[WordPress] www vs non-www and "This Connection is Not Private"

### ISSUE THREAD

**Issue by mbisque** [bitnami/vms#1322]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1ffc3723-c199-031c-a0b6-720ab9a45034

### bndiagnostic output

I'm not sure where to get the summary, sorry.

### bndiagnostic was not useful. Could you please tell us why?

Doesn't address question

### Describe your issue as much as you can

I use the bitnami cert tool for my secure server certificate.  During configuration, I choose to make all non www requests go to www (and non https go to https).  

However, on the iphone using safari, if I go to "https://mysite.com", I get the error message "This Connection is Not Private" (if go to Show Details, visit this site, the redirect to www.mysite.com does indeed happen).

The iphone use to not do this I think - Is there anything I can do to make the iPhone happy?

**Comment by jotamartos** [comment]
I just accessed your site and it's working properly. The SSL certificate was generated last week and it's valid until March 17th. 

![Screenshot 2023-12-26 at 12 30 27](https://github.com/bitnami/vms/assets/8791635/914d58ae-d804-4176-9633-ad0157abc457)

**Comment by mbisque** [comment]
Thank you.  This certificate is valid.  My question was about the redirect from non www to www being seen by the iphone and giving the error message "This connection is not private".  IOW, I "wish" the transition from non www to www was transparent without an error message on the iphone (can I have a cert for the non www domain name???)

**Comment by jotamartos** [comment]
The cert you have should include both www and non-www domains. If you created it with Let's Encrypt, you can issue a new one with both domains. 

Regarding the redirection, if you want to redirect the requests to https://www, you can follow this guide 

https://docs.bitnami.com/aws/apps/wordpress/administration/use-single-domain/

**Comment by mbisque** [comment]
>>
The cert you have should include both www and non-www domains. If you created it with Let's Encrypt, you can issue a new one with both domains.
<<

Yes I'm using Let's Encrypt.  I "thought" I answered correctly when asked the questions about www vs non-www as well as redirecting non https to https (maybe my let's encrypt is old or I'm not remembering correctly). Do the two certs for www vs non-www happen "automatically" with let's encrypt? And does let's encrypt automatically do the redirects from non www to www and http to https?  Or do I follow the guide above?

>>you can issue a new one with both domains

Briefly how? (Can a force a reissue if the current one is still too new?)

(Big picture, I'm using let's encrypt, and if I go to my site with the non www, the iphone gives the error "This connection is not private" which is what I"m trying to correct.)

Again, thank you for your help.  I am very grateful.

**Comment by jotamartos** [comment]
>Do the two certs for www vs non-www happen "automatically" with let's encrypt?

If you use our bncert tool, it does ask you to include both if you want. 

>And does let's encrypt automatically do the redirect configuration from non www to www and http to https?

Our tool also asks you if you want this to be configured in Apache. However, if you already have other rewrite actions, it won't modify your configuration to avoid breaking anything. In that case, you will need to follow the guide above

>Briefly how? (Can one force a reissue if the current one is still too new?)

You can run the bncert tool again 

https://docs.bitnami.com/general/how-to/understand-bncert/

and include the non-www domain as primary domain. The tool will ask you to add the www domain and a new cert will be generated.

**Comment by mbisque** [comment]
Thank you for your help.  Please bear with me.

I'm trying to run cert tool again and get this error message:

"The domain 'www.xyx.com' resolves to a different IP address than the
one detected for this machine, which is '1.2.3.4'. Please fix its DNS
entries or remove it. "

However, the error message is in error.  IOW, the domain name resolves to exactly what is reported for "this machine" .  The firewall is configured to allow http and https, but does the bncert tool need more (at least temporarily) to be happy?

**Comment by jotamartos** [comment]
> "The domain 'www.xyx.com' resolves to a different IP address than the
> one detected for this machine, which is '1.2.3.4'. Please fix its DNS
> entries or remove it. "

Please verify that bot www and non-www domains resolve to the same IP address in all servers and retry

https://www.whatsmydns.net/

**Comment by mbisque** [comment]
whatsmydns.net reports the same IP for both www and non-www.

However, on the machine in question, from a terminal, pinging www.xyz.com resolves to "local host (127.0.0.1)".  So the 127.0.0.1 is likely the problem. In contrast, Pinging xyz.com from a terminal returns the DNS ip.

**Comment by jotamartos** [comment]
>However, on the machine in question, from a terminal, pinging [www.xyz.com](http://www.xyz.com/) resolves to "local host (127.0.0.1)". So the 127.0.0.1 is likely the problem. In contrast, Pinging xyz.com from a terminal returns the DNS ip.

**Comment by mbisque** [comment]
Fixed!  The iphone no longer gives "This connection is Not Private" error message when going to the non www domain of my site.

Details... The host file was modified in the past to fix wordpress loopback tests/functionality from failing.  By taking out those lines in the host file, then redoing my certificate for both www.xyz.com xyz.com, problem solved (then I put back the changes to the host file).

Thank you jotamartos!
