### ISSUE TITLE
Bitnami-Wordpress < bitnami.service failed because the control process exited with error code >

### ISSUE THREAD

**Issue by SyncSas** [bitnami/vms#1326]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b0e552ab-36ec-83e5-760a-f2fafbaf3062

### bndiagnostic output

Connectivity: Found possible issues
Mariadb: Found possible issues
Processes: No issues found
Wordpress: Found possible issues
Apache: Found possible issues
Php: No issues found

[Resources]
Your disk is almost full: You could try to increase your instance's storage.
Filesystem Size Used Avail Use% Mounted on /dev/nvme0n1p1 25G 24G 0 100% /
 Please check your cloud provider's documentation for more information.

### bndiagnostic was not useful. Could you please tell us why?

website is down showing Error establishing a database connection

### Describe your issue as much as you can

As my website dashboard was not accessible so I stop my AWS instance and when i restart it then this issue is coming

**Comment by mdhont** [comment]
It seems your instance is running low on resources, I recommend upgrading to a more powerful one. It's also possible a WordPress plugin is consuming a lot of memory, try disabling all of them and see if that makes a difference.

    wp plugin deactivate --all

**Comment by SyncSas** [comment]
Thanks sir, increase my instance resource and restart bitnami. everything working fine
