### ISSUE TITLE
[MEAN] non www and non https redirection issue and 400 bad request

### ISSUE THREAD

**Issue by vocso** [bitnami/vms#1327]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

dc8361c5-a138-b88b-b52d-78540ebcf6ab

### bndiagnostic output

it pointed out errors and issues related to memory, which was not my concern. 

### bndiagnostic was not useful. Could you please tell us why?

it pointed out errors and issues related to memory, which was not my concern. 

### Describe your issue as much as you can

Your help is highly needed!

Can't believe I'm scratching my head trying to solve this simple problem.
I want to redirect all non https and non www traffic to https www version i.e. https://www.schools18.com

Right now It doesn't happen. curl -I http://schools18.com and curl -I http://www.schools.com returns 400 bad request

curl -https://www.schools18.com returns 301 to https://schools18.com and curl -I https://schools18.com returns 200 status code, which is again not correct.

I'm on a bitnami aws server running my application on MERN Stack and it has apache.

Thank you in advance!

**Comment by jotamartos** [comment]
Hi @vocso,

I can see you have many different virtual host files inside the vhost folder. Please take a look at our documentation to know how to deploy a new application on top of our solution 

https://docs.bitnami.com/aws/infrastructure/mean/get-started/get-started/#step-3-serve-your-application-through-the-apache-web-server

and follow this guide to update those virtual host to force the request to use a specific domain 

https://docs.bitnami.com/aws/infrastructure/mean/administration/use-single-domain/
