### ISSUE TITLE
[WordPress] My wordpress constantly crashes and requires reboot. 

### ISSUE THREAD

**Issue by importante** [bitnami/vms#1330]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3edd3530-6bcf-bc93-5931-d61295a9616f

### bndiagnostic output

? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1947 916 359 139 670 707 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat Dec 30 19:37:55.093409 2023] [authz_core:error] [pid 760:tid 
140416892360448] [client **ip_address**:40258] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
 [Sat Dec 30 19:40:22.760726 2023] [authz_core:error] [pid 1252:tid 
140417219675904] [client **ip_address**:55512] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin



### bndiagnostic was not useful. Could you please tell us why?

I am not expert, the instance crashes instantly and I can't understand why

### Describe your issue as much as you can

My wordpress constantly crashes and requires reboot. 

![burstable](https://github.com/bitnami/vms/assets/17860707/a983d676-9fb8-4f24-bc0f-d7fa5cd55a2d)

As you can see the attachment the instance goes burstable zone. These are the times it requires reboot. 

I have done the below steps to increase swap file to 8gb

sudo fallocate -l 8G /swapfile

sudo chmod 600 /swapfile

sudo mkswap /swapfile

sudo swapon /swapfile

sudo reboot


I see many people facing the same issue but I couldn't addressed any solution so far. Any help would be great. 

Thanks!

**Comment by jotamartos** [comment]
Please take a look at similar tickets in this forum before creating a new one. For example, [this one](https://github.com/bitnami/vms/issues/1272) explains how to solve performance issues and how to check if a bot/attacker is accessing your site with malicious intentions.
