### ISSUE TITLE
PHPmyAdmin redirecting to website via tunnel

### ISSUE THREAD

**Issue by jasonnyc14** [bitnami/vms#1334]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ex

### bndiagnostic was not useful. Could you please tell us why?

old version of BNsupport-tool

### Describe your issue as much as you can

Hi
Trying to access my PHPmyadmin via Terminal / Mac
- open a terminal
- ssh -N -L 8888:127.0.0.1:80 -i 2018-dev.pem bitnami@xxx.xxx.xxx.xx
- SSH tunnel opens but will not display any output on the server console (normal)
- Open a browser
- http://127.0.0.1:8888/phpmyadmin
-  Site redirects to website

I recall a trick where you fake out your computer using host file changes

Thanks

**Comment by gongomgra** [comment]
Hi @jasonnyc14,

Thanks for reporting your issue. It is a bit weird the SSH tunnel is not properly working. Can you run the bndiagnostic tool and share the generated code with us? Also please run the command below in a command line while the tunnel is active and share the output with us

```
curl -LI http://127.0.0.1:8888/phpmyadmin 
```

**Comment by jasonnyc14** [comment]
I only have bnsupport and bnsupport-tool. 
and when i run  "sudo bnsupport-tool" is get command not found 


  *** Welcome to the Bitnami NGINX Open Source 1.14.1-0 ***
  *** Documentation:  https://docs.bitnami.com/aws/infrastructure/nginx/ ***
  ***                 https://docs.bitnami.com/aws/ ***
  *** Bitnami Forums: https://community.bitnami.com/ ***
Last login: Fri Jan  5 19:33:21 2024 from 204.210.131.64
bitnami@ip-10-0-2-16:~$ curl -LI http://127.0.0.1:8888/phpmyadmin 
curl: (7) Failed to connect to 127.0.0.1 port 8888: Connection refused
bitnami@ip-10-0-2-16:~$ 

Tunneling
i use
ssh -N -L 8888:127.0.0.1:80 -i 2018-dev.pem [bitnami@xxx.xxx.xxx.xx](mailto:bitnami@xxx.xxx.xxx.xx)

But there is no output from the terminal console, so i cant run 
curl -LI http://127.0.0.1:8888/phpmyadmin

**Comment by jasonnyc14** [comment]
btw.. this is on AWS.. not Google Cloud

**Comment by jasonnyc14** [comment]
in addition, the MySQL is on a separate RDS instance

**Comment by gongomgra** [comment]
Hi @jasonnyc14,

You can run the `curl` command from another terminal console window in your local machine. Regarding the bnsupport tool, we recommend you to install the most recent version of the tool (named `bndiagnostic`) as described in the next guide

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/
