### ISSUE TITLE
[WordPress] Redirect from IP Address to Domain name

### ISSUE THREAD

**Issue by petrait** [bitnami/vms#1336]
### Name and Version

bitnami/wordpress

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I recently installed Bitnami WordPress instance on Google Cloud, the website is accessed from both the IP address and the domain name configured with the bncert.
even when you try to sign in to the dashboard using both the IP address and domain name and view the site settings:
1. if you logged in using the IP address: the website address will be the IP address
2. if you logged in using the domain name, the website address will be the domain name.

we need the website to be accessible from the domain name only, and if someone tried to visit the IP address, it must redirect him to the domain name.

```
===== Begin of bndiagnostic tool output =====

 
    ✓ Processes: No issues found
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ✓ Wordpress: No issues found
    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ✓ Mariadb: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.

[Wed Jan 03 07:49:10.618126 2024] [access_compat:error] [pid 17806:tid 
140429987145472] [client **ip_address**:45808] AH01797: client denied by server 
configuration: /opt/bitnami/wordpress/xmlrpc.php, referer: 
https://a4link.com/xmlrpc.php
 [Wed Jan 03 07:53:51.974697 2024] [access_compat:error] [pid 17808:tid 
Press [Enter] to continue:
140429894825728] [client **ip_address**:39544] AH01797: client denied by server 
configuration: /opt/bitnami/wordpress/xmlrpc.php, referer: 
https://a4link.com/xmlrpc.php
 [Wed Jan 03 07:58:13.717321 2024] [access_compat:error] [pid 17806:tid 
140429970360064] [client **ip_address**:22267] AH01797: client denied by server 
configuration: /opt/bitnami/wordpress/xmlrpc.php, referer: 
https://a4link.com/xmlrpc.php

Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====
Press [Enter] to continue:

                                    
Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

f31e3e32-abca-cd23-b1a5-16b66db7a447
```

**Comment by jotamartos** [comment]
>we need the website to be accessible from the domain name only, and if someone tried to visit the IP address, it must redirect him to the domain name.

Please take a look at our documentation

https://docs.bitnami.com/general/apps/wordpress/administration/use-single-domain/
https://docs.bitnami.com/general/apps/wordpress/administration/configure-domain/

Remember to use the same domain (www or no-www) in the different configuration files, if not you will run into a redirection issue.
