### ISSUE TITLE
.well-known file[<Apple Pay>] <Trying to get apple pay activated on my woocommerce site and I need to upload a file to my .well-known folder>

### ISSUE THREAD

**Issue by BusinessWebSocial** [bitnami/vms#1337]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ad319eef-4ee7-c6e3-c7dd-164b08868595

### bndiagnostic output

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Not related to my issue

### Describe your issue as much as you can

I can't find the .well-known folder to put my file into to get apple pay to start working with my merchant.

**Comment by BusinessWebSocial** [comment]
Any update on this please?

**Comment by gongomgra** [comment]
Hi @BusinessWebSocial,

Sorry for the delay. A similar question was solved in another thread. Can you take a look into it?

https://github.com/bitnami/vms/issues/439

Hope it helps!
