### ISSUE TITLE
[Wordpress] Wordpress installation done on GCP suddenly stopped working. Now unable to connect to the database

### ISSUE THREAD

**Issue by pushkardeveloper** [bitnami/vms#1340]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

dd06f348-1e88-4022-c59b-542fb5047071

### bndiagnostic output

    ✓ Php: No issues found
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Resources: No issues found
    ? Mariadb: Found possible issues
    ? Wordpress: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

Yes, it is very easy to use.

### Describe your issue as much as you can

I have used a bitnami wordpress installation on Google Cloud. It suddenly stopped working around 1 month ago. I had not made any changes from my side and one day it just stopped working. When I try to connect to the VM via public IP, I get this error message - "ERR_CONNECTION_REFUSED"

**Comment by jotamartos** [comment]
The bndiagnostic tool warned you about some errors in the database, please take a look at the log file to know more about those issues and how to resolve them.
