### ISSUE TITLE
[<LAMP>] Issues with more than 1 website on a LAMP instance

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1341]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7c6d3714-061b-9e11-748c-f557eeac0790

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

? Resources: Found possible issues
? Connectivity: Found possible issues
✓ Mariadb: No issues found
? Processes: Found possible issues
? Apache: Found possible issues
✓ Php: No issues found
 
[Resources]

Your instance has little available RAM memory.

 total used free shared buff/cache available Mem: 950 346 78 4 525 455 Swap: 634 
1 633

You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Processes]

One or more component's processes are not running:

apache not running

You can try to restart the process with the following command:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Apache]

Found recent error or warning messages in the Apache error log.

[Thu Jan 04 10:32:00.394582 2024] [autoindex:error] [pid 2620:tid 
139899256678144] [client **ip_address**:64020] AH01276: Cannot serve directory 
Press [Enter] to continue:
/opt/bitnami/ddwarfs/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive
 [Thu Jan 04 10:32:08.514858 2024] [autoindex:error] [pid 2619:tid 
139899378530048] [client **ip_address**:64024] AH01276: Cannot serve directory 
/opt/bitnami/ddwarfs/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive
 [Thu Jan 04 10:33:46.158631 2024] [autoindex:error] [pid 3002:tid 
140604478584576] [client **ip_address**:64058] AH01276: Cannot serve directory 
/opt/bitnami/ddwarfs/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive

Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:

httpd: Syntax error on line 520 of /opt/bitnami/apache2/conf/httpd.conf: Syntax 
Press [Enter] to continue:
error on line 1 of /opt/bitnami/apache/conf/vhosts/nov21-https-vhost.conf: 
/opt/bitnami/apache/conf/vhosts/nov21-https-vhost.conf:1: <VirtualHost> was not 
closed.

Please check the configuration.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

Hi,

I first added a custom website using [these steps](https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/).

I then followed the same steps to add a second website using the same steps as I did for the first website. Both websites currently only have one index.html page.

When I created the first one, there were no issues and the page was visible. After creating the second website, the instance went down and Apache problems started. Can you please guide me?

Best,
Huzan

**Comment by gongomgra** [comment]
Hi @huzanf,

According to the bndiagnostic information you have a typo in your Apache configuration. Please take a look to the provided file and fix the error. After that, please restart the Apache service.

```
The Apache configuration has errors:

httpd: Syntax error on line 520 of /opt/bitnami/apache2/conf/httpd.conf: Syntax
Press [Enter] to continue:
error on line 1 of /opt/bitnami/apache/conf/vhosts/nov21-https-vhost.conf:
/opt/bitnami/apache/conf/vhosts/nov21-https-vhost.conf:1: was not
closed.
```

I also see you have many tickets opened related to similar errors. Please avoid that as much as possible, notice we have limited bandwidth for support requests and that we may also suggest different solutions in each thread that may not work if you implement too many changes at once (one from each support ticket).

Hope it helps!
