### ISSUE TITLE
[Redmine] How to transfer data from bitnami-redmine 4.1.0-8 on Windows to bitnami-redmine 5.1.1-r1 on VirtualBox?

### ISSUE THREAD

**Issue by StraightCedar** [bitnami/vms#1343]
I want to transfer data from Redmine 4.1.0.8 on Windows to Redmine 5.1.1-r1 on VirtualBox.
I installed the Windows version with 'bitnami-redmine-4.1.0-8-windows-x64-installer.exe',
and the VirtualBox version with 'bitnami-redmine-5.1.1-r1-debian-11-amd64.ova'.

First, I exported the old db data on the Windows version (redmine 4.1.0.8) as follows,
`mysqldump -u bitnami -p bitnami_redmine > C:\work\redmine_backup.dmp`

Second, I imported it to the VirtualBox version (redmine 5.1.1-r1),
`mysql -u root -p < /home/bitnami/redmine_backup.dmp`

I confirmed that the data was imported correctly with the mysql command.
But when I accessed the Redmine site with the browser and tried to log in with the imported Redmine user name, I got an internal error.
<img width="291" alt="image" src="https://github.com/bitnami/vms/assets/5700729/55e85e1b-3bf6-4be5-87cb-82f04523e4ae">

Then, I compared the user tables on Redmine 4.1.0.8 and 5.1.1-r1 and found some differences.
<img width="227" alt="image" src="https://github.com/bitnami/vms/assets/5700729/7f9f34c3-fe83-4629-b2e5-ff7aa495e0e9">

It may be the cause.

I checked the Bitnami official site and read ['Upgrade Redmine' site](https://docs.bitnami.com/virtual-machine/apps/redmine/administration/upgrade/), but it was for Linux to Linux, and I could not find any solution for my issue.

I am considering modifying the dumped text file from Redmine 4.1.0.8 and adjusting its columns for 5.1.1-r1.
Let me know if you know of any better way.

Thanks.

**Comment by jotamartos** [comment]
As the guide in our documentation mentions, you need to migrate the database (you already did that) and the files and plugins of your Windows installation. Once imported in the VM,  you also need to run the commands that the guide explains to perform the necessary changes in the database and install the plugins.
