### ISSUE TITLE
[<Azure VM with Nginx>] <Install PHPredis>

### ISSUE THREAD

**Issue by Barnabas2** [bitnami/vms#1344]
### Describe your issue as much as you can

I want to install PHPredis on my wordpress site running on Linux by Bitnami with nginx. The only guide I could find in bitnami is this one here: https://docs.bitnami.com/aws/infrastructure/ruby/configuration/install-modules-php/

I couldn't get it to work, so instead I followed this guide here: https://spinupwp.com/hosting-wordpress-yourself-server-monitoring-caching/#object-cache. However, when I activate Redis, I see that not PHPredis is installed but Predis.
<img width="269" alt="image" src="https://github.com/bitnami/vms/assets/75849247/9ca2a0e3-6e7d-43ce-aa84-5391d937891d">

 Is the bitnami image I'm using coming with a preinstalled configuration of Predis that prevents me from activating PHPredis? 
If  I can install PHPredis, what is the correct way to do it?

**Comment by mdhont** [comment]
What exact issue did you face when installing PhpRedis? Could you give more details?

**Comment by Barnabas2** [comment]
I installed version 6.0.2 it using the bitnami docs but couldn't observe it was not working on my wordpress site. Then I tried also the other method but didn't have any luck.

So to be clear, I followed all the instructions on bitnami docs and all the commands were executed OK. I just don't understand why my server is still running Predis instead of phpRedis.

**Comment by Barnabas2** [comment]
Hello, just an update that is working now. I run the following commands and it started working. 
sudo systemctl restart redis-server
sudo /opt/bitnami/ctlscript.sh restart php-fpm
