### ISSUE TITLE
[wordpress] website homepage in a subfolder

### ISSUE THREAD

**Issue by StefanoCocomazzi** [bitnami/vms#1345]
### Describe your issue as much as you can

I have a wordpress website hosted on a lightsail instance.

I migrated the blog from another provider

I also transfered the domain [https://bmscience.net/]( https://bmscience.net/) on route 53

But I want the website homepage to be [https://bmscience.net/blog/](https://bmscience.net/blog/) like the old version.

I tried configuring the wp-config with

```
define( 'WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] . '/blog/' );
define( 'WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/blog/' );
```

It works with the blog articles, but the images seems not working. (some of them are still on https://bmscience.net/wp-content/... )
Also the admin pages are unreachable this way.

I reverted back on the original wp-config file, but still want to use the subfolder ad main url without using wordpress multisite.

**Comment by mdhont** [comment]
You can find more information on how to create and deploy a custom application using Apache in our docs linked below:

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

It depends on your server to follow the steps for Approach A or Approach B. You can find a section for checking which one you are using at the beginning of the guide.

**Comment by StefanoCocomazzi** [comment]
> You can find more information on how to create and deploy a custom application using Apache in our docs linked below:
> 
> https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/
> 
> It depends on your server to follow the steps for Approach A or Approach B. You can find a section for checking which one you are using at the beginning of the guide.

Thanks for the response. 
I read the docs and in the end I came up with this solution:

1.  Edit the file /opt/bitnami/apache/conf/vhosts/myapp-https-vhost.conf adding 
```
  <Location "/blog">
      AliasPreservePath on
      Alias "/opt/bitnsudo /opt/bitnami/ctlscript.sh restart apache
ami/wordpress"
  </Location>
```
2. Restart apache with `sudo /opt/bitnami/ctlscript.sh restart apache`
3. Edit the file wp-config.php setting 
```
define( 'WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] . '/blog/' );
define( 'WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/blog/' );
```

It seems working without problems with both the domain and the subfolder.

I don't know if there are more elegant solutions, in that case let me know.
