### ISSUE TITLE
[wordpress] Change region of GCP hosted website

### ISSUE THREAD

**Issue by antrikshjohri** [bitnami/vms#1346]
### Describe your issue as much as you can

I have a wordpress website (WordPress Certified by Bitnami and Automattic) hosted on Google Cloud Platform. While creating the website on GCP, I used the region uscentral1 for the VM (since that was free tier). Now, I realised that most of my visitors are from India and hence I want to change the region of the VM to India so that website load speed is faster. I do not find a way to do it on GCP. 

Can someone help me with changing the region of the VM from uscentral1 to asia-south2 (or any region in India)?

**Comment by mdhont** [comment]
I recommend asking Google Cloud support. I also found the following guide which may help:

https://cloud.google.com/compute/docs/instances/moving-instance-across-zones
