### ISSUE TITLE
[Wordpress with NGINX] sites crashes even after giving 16 gb ram

### ISSUE THREAD

**Issue by Divyadevayya** [bitnami/vms#1347]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

31e5a0cb-f8a3-00b8-a8dc-6cdbed5e2dec

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ? Nginx: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ✓ Php: No issues found

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 15869 15068 200 164 600 384
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2024-01-09 11:34:52 9916 [Warning] Aborted connection 9916 to db:
'bitnami_wordpress' user: 'bn_wordpress' host: '**ip_address**' (Got an error
writing communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:
Press [Enter] to continue:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2024/01/09 12:14:32 [error] 705#705: *2915 FastCGI sent in stderr: "PHP message:
PHP Warning: Trying to access array offset on value of type bool in
/bitnami/wordpress/wp-content/themes/bookory/inc/elementor/widgets/breadcrumb.php
 on line 214" while reading response header from upstream, client:
**ip_address**, server: _, request: "GET / HTTP/1.1", upstream:
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "pustakamane.com"
 2024/01/09 12:14:55 [error] 705#705: *2963 FastCGI sent in stderr: "PHP
message: PHP Warning: Trying to access array offset on value of type bool in
/bitnami/wordpress/wp-content/themes/bookory/inc/elementor/widgets/breadcrumb.php
 on line 214" while reading response header from upstream, client:
**ip_address**, server: _, request: "GET / HTTP/1.1", upstream:
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "pustakamane.com"
 2024/01/09 12:16:05 [error] 704#704: *2763 FastCGI sent in stderr: "PHP
message: PHP Warning: Undefined array key "_edw_days" in
/bitnami/wordpress/wp-content/plugins/estimated-delivery-for-woocommerce/estimate
Press [Enter] to continue:
d-delivery-woocommerce.php on line 233" while reading response header from
upstream, client: **ip_address**, server: _, request: "POST
/wp-admin/admin-ajax.php HTTP/1.1", upstream:
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "pustakamane.com",
referrer: "https://pustakamane
```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Even after increasing the RAM, our website continues to crash..

### Describe your issue as much as you can

Our brand-new website, with only 50 to 100 visitors, mostly from our team, is consistently crashing despite increasing the RAM to 16 GB. We need your support to understand and fix this issue. Thank you...

**Comment by jotamartos** [comment]
Please take a look at similar tickets in this forum before creating a new one. For example, https://github.com/bitnami/vms/issues/1272 explains how to solve performance issues and how to check if a bot/attacker is accessing your site with malicious intentions.

In your case, you will need to follow the instructions for NGINX 

https://docs.bitnami.com/general/apps/wordpress-pro/troubleshooting/deny-connections-bots-nginx/

You can also take a look at the PHP log file (/opt/bitnami/php/var/log folder) and check if it's reaching the limits (you can also obtain the number of PHP-FPM process by running the `ps` command). In that case, you will need to modify the memory settings in the /opt/bitnami/php/etc/memory.conf file and restart the service.

**Comment by Divyadevayya** [comment]
Despite deactivating all plugins and the theme, still it utilizing 12GB of RAM. Seeking assistance to identify and resolve the underlying cause of this RAM consumption issue.

**Comment by Divyadevayya** [comment]
Here is the PS command result 
![Pustaka-PS-command](https://github.com/bitnami/vms/assets/153350258/d7d0df3e-cdf8-45fa-a895-d3b7fcb251af)

**Comment by jotamartos** [comment]
The ps command itself doesn't provide any information. You will need to check this guide to obtain more info

https://docs.bitnami.com/general/faq/troubleshooting/troubleshoot-server-performance/

>Despite deactivating all plugins and the theme, still it utilizing 12GB of RAM.

Did you check if there is any bot/attacker accessing your site? I also suggest you use a security plugin like Wordfence to analyze your deployment and confirm that you are not running any malicious software.
