### ISSUE TITLE
[<wordpress>] <issue with SSL certificate in subdirectories>

### ISSUE THREAD

**Issue by tati1983** [bitnami/vms#1349]
### Describe your issue as much as you can

I created an SSL certificate with Bitnami using the bncert tool. It works well for the home page of the site, that is, site.com works perfectly and is a secure connection. However, for subdirectories, if, for example, I want to navigate internally to a section of the page, site.com/section, that connection is not secure; it no longer works with HTTPS. What could be happening? My website is built with WordPress and is hosted on AWS Lightsail

**Comment by mdhont** [comment]
What exact error is showing? Could it be a mixed content error? In that case the following plugin could help:

https://wordpress.org/plugins/ssl-insecure-content-fixer/
