### ISSUE TITLE
ghost too may redirects

### ISSUE THREAD

**Issue by stephen-tenorless** [bitnami/vms#1350]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

dbac7bf5-45f0-2714-8b18-01cbdf1b03b8

### bndiagnostic output

[Thu Jan 11 18:28:04.390523 2024] [proxy:error] [pid 1842:tid 140677224527616] 
(111)Connection refused: AH00957: http: attempt to connect to 
**ip_address**:2368 (127.0.0.1:2368) failed

### bndiagnostic was not useful. Could you please tell us why?

not related - my issue has to do with mixed content http - https

### Describe your issue as much as you can

in my /opt/bitnami/ghost config file  i changes the url from http to https   this causes too many redirects
if i dont dont then i get FeedbackPage.js:12 Mixed Content: The page at 'https://kates.fclec.com/' was loaded over HTTPS, but requested an insecure resource 'http://kates.fclec.com/members/api/member/'. This request has been blocked; the content must be served over HTTPS.

**Comment by stephen-tenorless** [comment]
no that makes no difference. site still fails

**Comment by stephen-tenorless** [comment]
> The following guide shows how to force HTTPS redirection for Bitnami Ghost:
> 
> https://docs.bitnami.com/aws/apps/ghost/administration/force-https-apache/

once i update the url in config.production.json the site fails

 "url": "https://kates.fclec.com",
"server": {
"port": 2368,
"host": "0.0.0.0"
},

**Comment by stephen-tenorless** [comment]
no exactly the same. site wont work if the config.production.json url is
https://. instead of http://

**Comment by mdhont** [comment]
Could you update the `config.production.json` url parameter with only the domain name as described here:

https://docs.bitnami.com/aws/apps/ghost/administration/configure-domain/

And restart the services?

    sudo /opt/bitnami/ctlscript.sh restart

**Comment by stephen-tenorless** [comment]
no that does not work , ive tried that.
Jus gave up . I just hosted with ghost.io pro
