### ISSUE TITLE
[bitnami/redmine] How to display print information BEYOND THE screen display area

### ISSUE THREAD

**Issue by chinatochen** [bitnami/vms#1351]
### Describe your issue as much as you can

When the printed information displayed on the screen exceeds the area displayed on the screen, 
I cannot view the content printed on the last screen, which is a problem that I am very upset. 
For example, when installing plug-ins, the printed information exceeds the entire screen, so I cannot see and miss a lot of useful information before. 
How to solve this problem
![image](https://github.com/bitnami/vms/assets/43564507/a32c9b44-09c9-4b4e-863a-391a5612ee82)

**Comment by gongomgra** [comment]
Hi @chinatochen,

Thanks for your message. If the ESXi terminal app doesn't allow you to scroll up, I think you can choose one of the next alternatives:

* Use another virtual terminal app as suggested in [official VMware community forums](https://communities.vmware.com/t5/ESXi-Discussions/How-do-you-scroll-up-in-a-virtual-machine-console-window/td-p/1649467) such as connecting via SSH to the virtual machine.
* Run the commands as shown below to redirect the output to a file you can inspect later. Notice this method is a bit more tedious

```
<command you want to run with args> 2>&1 | tee output.log
```

As an example, you can run the bundle install like this, and then inspect the `output.log` file

```
bundle install 2>&1 | tee output.log
```

Hope it helps!

**Comment by chinatochen** [comment]
> Hi @chinatochen,
> 
> Thanks for your message. If the ESXi terminal app doesn't allow you to scroll up, I think you can choose one of the next alternatives:
> 
> * Use another virtual terminal app as suggested in [official VMware community forums](https://communities.vmware.com/t5/ESXi-Discussions/How-do-you-scroll-up-in-a-virtual-machine-console-window/td-p/1649467) such as connecting via SSH to the virtual machine.
> * Run the commands as shown below to redirect the output to a file you can inspect later. Notice this method is a bit more tedious
> 
> ```
> <command you want to run with args> 2>&1 | tee output.log
> ```
> 
> As an example, you can run the bundle install like this, and then inspect the `output.log` file
> 
> ```
> bundle install 2>&1 | tee output.log
> ```
> 
> Hope it helps!

Hi gongomgra   
Thank you very much for your reply. I will try to use your suggestions to solve this troublesome problem. Thank you again！
