### ISSUE TITLE
Bitnami - Magento - Azure VM - Uploading product images via API

### ISSUE THREAD

**Issue by Cefajoe** [bitnami/vms#1353]
### Describe your issue as much as you can

Hi there, 

I have created the application, following the procedures and I have a working Magento website and have console access. I am able to use the Magento API to create post requests for new product, upload stock, prices etc, but when I try and upload new product images I get the error
```
{
    "message": "The path \"%1\" is not writable.",
    "parameters": [
        "/opt/bitnami/php/tmp/."
    ]
}
```
I have tried to reset the permissions on the folder, per the instructions here https://docs.bitnami.com/aws/how-to/troubleshoot-permission-issues/ but its made no difference. The permissions on that folder are
```
bitnami@magentom3:~$ sudo stat /opt/bitnami/php/tmp/
  File: /opt/bitnami/php/tmp/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 811h/2065d	Inode: 1075285     Links: 2
```

Appreciate any help you can give me.

**Comment by gongomgra** [comment]
Hi @Cefajoe,

Thanks for using Bitnami. Can you provide us with the output of the command below?

```
sudo ls -larth /opt/bitnami/php/tmp
```

Can you also run the bndiagnostic tool and share the generated code with us?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/
