### ISSUE TITLE
Bitnami Wordpress bitnami.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by jteck** [bitnami/vms#1354]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d658f762-6f57-6b9b-f962-eb9eb0ac0215

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Fri Jan 12 15:09:33.153747 2024] [core:error] [pid 2314511:tid 140617665328896] 
[client **ip_address**:54697] AH00124: Request exceeded the limit of 10 internal 
redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Fri Jan 12 15:09:33.594959 2024] [core:error] [pid 2291459:tid 
140617094854400] [client **ip_address**:54700] AH00124: Request exceeded the 
limit of 10 internal redirects due to probable configuration error. Use 
'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel 
debug' to get a backtrace.
 [Fri Jan 12 17:34:36.681285 2024] [core:error] [pid 2291459:tid 
140617380206336] [client **ip_address**:41442] AH00124: Request exceeded the 
limit of 10 internal redirects due to probable configuration error. Use 
'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel 
debug' to get a backtrace., referer: http://simplesite.com

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

Press [Enter] to continue:
The Apache configuration has errors:
```
AH00526: Syntax error on line 18 of 
/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf: SSLCertificateFile: file 
'/opt/bitnami/apache/conf/server.crt' does not exist or is empty
```
Please check the configuration.
 

===== End of bndiagnostic tool output =====

                                    
Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

d658f762-6f57-6b9b-f962-eb9eb0ac0215

### bndiagnostic was not useful. Could you please tell us why?

unsure what to do next

### Describe your issue as much as you can

the issue started when I changed the .key and .crt to servers.key and .crt in 
/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf 

I tried to add it manually after fail to /opt/bitnami/apache2/conf/vhosts/wordpress-https-vhost.conf

I had my ssl for https with let's encrypt expire even though i had it setup for the auto renew. i used the bitnami HTTPS configuration tool to revoke and get new cert. it failed because it had expired so i wasn't able to do it wouthout removing the old certs first. 

An error occurred revoking certificates with Let's Encrypt:
2024/01/12 21:58:41 Trying to revoke certificate for domain 

Error while revoking the certificate for domain 

	acme: error: 403 :: POST :: 
https://acme-v02.api.letsencrypt.org/acme/revoke-cert :: 
urn:ietf:params:acme:error:unauthorized :: Certificate is expired

Please check our documentation and support forums, we'll be happy to help!

* Bitnami Documentation: https://docs.bitnami.com
* Bitnami Community: https://github.com/bitnami/vms

Press [Enter] to continue:
----------------------------------------------------------------------------
Error

An error occurred when applying configurations.

The web server configuration was left unchanged. There was an error in the new 
configuration, so it was reverted.

Failed steps:
* Running Let's Encrypt: Error revoking certificates

Find more details in the log file:

/tmp/bncert-202401122156.log

If you find any issues, please check Bitnami Support forums at:

https://github.com/bitnami/vms

Press [Enter] to continue:

**Comment by jteck** [comment]
$ sudo /opt/bitnami/ctlscript.sh restart
Restarting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

 sudo /opt/bitnami/ctlscript.sh status
Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)

**Comment by jteck** [comment]
additional info 

bitnami@ip-172-31-73-175:~$ journalctl -xe
Jan 13 05:37:21 ip-172-31-73-175 bitnami[3879]: ## 2024-01-13 05:37:21+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agent...
Jan 13 05:37:21 ip-172-31-73-175 bitnami[3879]: ## 2024-01-13 05:37:21+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welcome_file...
Jan 13 05:37:21 ip-172-31-73-175 bitnami[3879]: ## 2024-01-13 05:37:21+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_credentials_file...
Jan 13 05:37:21 ip-172-31-73-175 bitnami[3879]: ## 2024-01-13 05:37:21+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metadata...
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStart= process belonging to unit bitnami.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitnami.service has entered the 'failed' state with result 'exit-code'.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 681 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 685 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 686 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 687 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 688 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 689 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 690 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 691 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 692 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 693 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 694 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 695 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 696 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 697 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 698 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 699 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 700 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 701 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 702 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 703 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 704 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 705 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 706 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 707 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 708 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 709 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 710 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 711 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 712 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 713 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 714 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 715 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 716 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 717 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 718 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 719 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 720 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 721 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 722 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 723 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 724 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 736 (mysqld) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: Failed to start LSB: bitnami init script.
░░ Subject: A start job for unit bitnami.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit bitnami.service has finished with a failure.
░░ 
░░ The job identifier is 1122 and the job result is failed.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Consumed 1.981s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitnami.service completed and consumed the indicated resources.
Jan 13 05:37:21 ip-172-31-73-175 sudo[3774]: pam_unix(sudo:session): session closed for user root
bitnami@ip-172-31-73-175:~$ systemctl status bitnami.service
● bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-01-13 05:37:21 UTC; 54s ago
    Process: 3783 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
      Tasks: 49 (limit: 4623)
     Memory: 242.5M
        CPU: 1.993s
     CGroup: /system.slice/bitnami.service
             ├─681 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
             ├─685 php-fpm: pool www
             ├─686 php-fpm: pool www
             ├─687 php-fpm: pool www
             ├─688 php-fpm: pool www
             ├─689 php-fpm: pool www
             ├─690 php-fpm: pool www
             ├─691 php-fpm: pool www
             ├─692 php-fpm: pool www
             ├─693 php-fpm: pool www
             ├─694 php-fpm: pool www
             ├─695 php-fpm: pool www
             ├─696 php-fpm: pool www
             ├─697 php-fpm: pool www
             ├─698 php-fpm: pool www
             ├─699 php-fpm: pool www
             ├─700 php-fpm: pool www
             ├─701 php-fpm: pool www
             ├─702 php-fpm: pool www
             ├─703 php-fpm: pool www
             ├─704 php-fpm: pool www
             ├─705 php-fpm: pool www
             ├─706 php-fpm: pool www
             ├─707 php-fpm: pool www
             ├─708 php-fpm: pool www
             ├─709 php-fpm: pool www
             ├─710 php-fpm: pool www
             ├─711 php-fpm: pool www
             ├─712 php-fpm: pool www
             ├─713 php-fpm: pool www
             ├─714 php-fpm: pool www
             ├─715 php-fpm: pool www
             ├─716 php-fpm: pool www
             ├─717 php-fpm: pool www
             ├─718 php-fpm: pool www
             ├─719 php-fpm: pool www
             ├─720 php-fpm: pool www
             ├─721 php-fpm: pool www
             ├─722 php-fpm: pool www
             ├─723 php-fpm: pool www
             ├─724 php-fpm: pool www
             └─736 /opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=>

Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 718 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 719 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 720 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 721 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 722 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 723 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 724 (php-fpm) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Unit process 736 (mysqld) remains running after unit stopped.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: Failed to start LSB: bitnami init script.
Jan 13 05:37:21 ip-172-31-73-175 systemd[1]: bitnami.service: Consumed 1.981s CPU time.
bitnami@ip-172-31-73-175:~$

**Comment by mdhont** [comment]
> the issue started when I changed the .key and .crt to servers.key and .crt in
/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf

It seems the `SSLCertificateFile` in this file is pointing to a non existing file. Does a file still exist in the `/opt/bitnami/apache/conf/server.crt` path?

**Comment by jteck** [comment]
I put a file in Apache2. Are those connected?

To schedule time with me, please pick a time that works best for you from my calendar here: Click here to book time with ***@***.***/bookings/>. It will automatically create a Teams meeting for our phone call, video call and/or screen share.

Thanks,

Jason Teck
S4T Group
President - CEO | ***@***.*** | www.s4tgroup.com
Toll Free: 866.790.0315 | O: 954.793.4082 | D: Ext. 100 | F : 954.510.2074


*Please excuse brevity and errors as this was sent from my phone*

________________________________

**Comment by jteck** [comment]
Will you check it out again please I had moved that elastic IP to a different EC2 to try and compare when you had looked at it

To schedule time with me, please pick a time that works best for you from my calendar here: Click here to book time with ***@***.***/bookings/>. It will automatically create a Teams meeting for our phone call, video call and/or screen share.

Thanks,

Jason Teck
S4T Group
President - CEO | ***@***.*** | www.s4tgroup.com
Toll Free: 866.790.0315 | O: 954.793.4082 | D: Ext. 100 | F : 954.510.2074


*Please excuse brevity and errors as this was sent from my phone*

________________________________

**Comment by jteck** [comment]
@mdhont any advise here?

**Comment by jteck** [comment]
i got it back working and now i can't renew the certificate because it is expired. What do I do next? I am trying to use bitnami https configuration tool

**Comment by mdhont** [comment]
Instead of renewing I recommend creating a new one manually following these steps:

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by jteck** [comment]
ok. Thank you! I will update if I have any issues or when its solved.

**Comment by jteck** [comment]
@mdhont where do i find the archive number referenced in step 1 

Run the following commands to install the Lego client. Note that you will need to replace the X.Y.Z placeholder with the actual version number of the downloaded archive:

**Comment by mdhont** [comment]
With the "curl" command you downloaded the lego binary file, which consists of the name (lego) and the version of the binary. You can check the full name with these command:

    cd /tmp
    ls lego*.tar.gz

**Comment by jteck** [comment]
> With the "curl" command you downloaded the lego binary file, which consists of the name (lego) and the version of the binary. You can check the full name with these command:
> 
> ```
> cd /tmp
> ls lego*.tar.gz
> ```

Is the full name the version of the binary? Share more details please
