### ISSUE TITLE
 Bitnami wordpress using virtualbox 

### ISSUE THREAD

**Issue by vinod117** [bitnami/vms#1355]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b01a0ef-60f7-4886-c482-1394506008b9

### bndiagnostic was not useful. Could you please tell us why?

I was not able to find a way to solve my issue

### Describe your issue as much as you can

Bitnami wordpress was working on my system initially and i did a lot of progress on my website and after a point mwhen i start my virtual machine it starts and then when i open the application through my web browser using the required ip address given by the virtual machine it says the site cant be reached . can you please help me out with this
<img width="879" alt="Screenshot 2024-01-13 141614" src="https://github.com/bitnami/vms/assets/156287928/63ec2682-d098-4eab-a699-3829c19ea46e">

**Comment by gongomgra** [comment]
Hi @vinod117,

Thanks for using Bitnami. Unfortunately, I can't find a bndiagnostic bundle with that code. Can you run the tool again and share the new code with us?

**Comment by vinod117** [comment]
b02b2c39-8aea-1306-ab17-f61f34c124fa
can you check now

**Comment by gongomgra** [comment]
Hi @vinod117,

I can't find any error in the bndiagnostic bundle you shared. All services are running, and no error messages are present in Apache or MariaDB logs. Can you try disabling all plugins using the `wp-cli` tool and restart services? If that works, then your issues may be caused by a plugin.
