### ISSUE TITLE
[<LAMP>] Multiple LetsEncrypt SSL for multiple domains on 1 instance

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1356]
### Describe your issue as much as you can

Hi,

I have multiple websites in one instance. I can create SSL for all domains by following this [link](https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach). However the CN name remains of the primary domain.

How can I have multiple SSL, with CN name unique to the domain on the same instance?

**Comment by mdhont** [comment]
The following guide may be of help:

https://docs.bitnami.com/aws/apps/wordpress-multisite/administration/use-different-ssl-certificates/
