### ISSUE TITLE
[Wordpress] Website is Frozen

### ISSUE THREAD

**Issue by skiddmarks** [bitnami/vms#1358]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

20240114-213035-19986

### bndiagnostic output

Tool failed to upload the captured data.

### bndiagnostic was not useful. Could you please tell us why?

Tool failed to upload the captured data.

### Describe your issue as much as you can

Packet generated by the tool is uploaded to: https://drive.google.com/file/d/1a-6-F4vv-9G6rJw7WdnwQzThbUnfzRHp/view?usp=sharing

I have been running the website since 2020 without any issues, traffic is very low for this website. Recently I discovered that the site has not been responsive, I tried restarting the services, site would come up and then freeze again. I saw the error log on Apache and it had bunch of errors. Kindly help with a resolution.

**Comment by mdhont** [comment]
Could you give more details regarding the Apache errors?

Could you also check if disabling the plugins makes the site more responsive? Plugins are known to cause memory issues.

    wp plugins deactivate --all

**Comment by skiddmarks** [comment]
[error.log](https://github.com/bitnami/vms/files/13942890/error.log)
Please find the error_log from Apache as of today.

**Comment by skiddmarks** [comment]
And i got the below error message for the command you suggested:

```
Error: 'plugins' is not a registered wp command. See 'wp help' for available commands.
Did you mean 'plugin'?
```

**Comment by mdhont** [comment]
Sorry my fault, it should be plugin:

    wp plugin deactivate --all

**Comment by skiddmarks** [comment]
Yes, updated command worked. After deactivating all plugins, site does start working. Wordpress is asking for PHP uupdate, can i perform that from SSH window?

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually. Instead we recommend launching the latest Bitnami WordPress image and migrate your site there.

**Comment by skiddmarks** [comment]
Thanks for your help. We can close this as resolved :-)
