### ISSUE TITLE
[wordpress] Site can’t be reached

### ISSUE THREAD

**Issue by nischinth** [bitnami/vms#136]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

034ea188-ff5e-d27d-37e6-3bbcd645b32c

### bndiagnostic output

    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.

```
[Mon Jul 18 07:07:24.641031 2022] [autoindex:error] [pid 2484:tid 
139809070724864] [client **ip_address**:51815] AH01276: Cannot serve directory 
/opt/bitnami/wordpress/wp-admin/css/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive, referer: binance.com
Press [Enter] to continue:
 [Mon Jul 18 13:53:07.402457 2022] [authz_core:error] [pid 2511:tid 
139808953227008] [client **ip_address**:49344] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
 [Mon Jul 18 15:38:58.525081 2022] [core:error] [pid 2498:tid 139808911329024] 
[client **ip_address**:58600] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
```

### bndiagnostic was not useful. Could you please tell us why?

In this tool, we can't find proper solution, sometimes its shows error related to Resources, after running again it will not show

### Describe your issue as much as you can

Hello, my website is hosted in AWS Lightsail, I am facing an issue in Bitnami WordPress, "**This site can’t be reached**", every week this happens for me, after restarting the instance it will work fine, but sometimes an error shows Resources might be the issue, I have  "**8 GB RAM, 2 vCPUs, 160 GB SSD**", Then I swap the memory, but nothing works, I  can't able to solve the issue, please help me out

**Comment by nischinth** [comment]
Hello, can you please tell me how to solve this issue?

**Comment by jotamartos** [comment]
Please check the information of this post 

https://github.com/bitnami/vms/issues/27

**Comment by jotamartos** [comment]
As the other posts mentions, you have WordPress-related errors in the Apache's log 

```
[Mon Jul 18 02:54:58.027360 2022] [proxy_fcgi:error] [pid 2460:tid 139807795689216] [client 154.21.208.188:39816] AH01071: Got error 'PHP message: PHP Notice:  Undefined offset: 0 in /opt/bitnami/wordpress/wp-content/     themes/clevercourse-child/header-title.php on line 104PHP message: PHP Notice:  Undefined offset: 0 in /opt/bitnami/wordpress/wp-content/themes/clevercourse-child/header-title.php on line 106PHP message: PHP Notice:       Undefined offset: 0 in /opt/bitnami/wordpress/wp-content/themes/clevercourse-child/header-title.php on line 108PHP message: PHP Notice:  Undefined offset: 0 in /opt/bitnami/wordpress/wp-content/themes/clevercourse-child/  header-title.php on line 111'
```

Please contact the WordPress support team or the theme's developers to get more info.
