### ISSUE TITLE
[Magento] Error 503 Backend fetch failed  Backend fetch failed  Guru Meditation:  XID: 163852  Varnish cache server

### ISSUE THREAD

**Issue by X00217213** [bitnami/vms#1364]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b4892d14-b6a3-cd2e-75cf-0e0bb46cf208

### bndiagnostic was not useful. Could you please tell us why?

The suggested not relevant to my issue

### Describe your issue as much as you can

Every Bitnami Magento Application from:

[AWS Marketplace](https://aws.amazon.com/marketplace), Amazon’s online application library;
[AWS Console](https://console.aws.amazon.com/), Amazon’s online dashboard for AWS users;
[Amazon Lightsail](https://amazonlightsail.com/), Amazon’s virtual private servers.

After lunching instance, each has same error after opening http://AWSPublicIPv4/admin :

Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation:
XID: 163852
Varnish cache server

<img width="512" alt="Screenshot 2024-01-16 at 20 59 44" src="https://github.com/bitnami/vms/assets/147000969/5b0c7f19-df37-4141-a9c1-a4f9f527ce1b">

**Comment by jotamartos** [comment]
Hi @X00217213,

I just launched a fresh Bitnami Magento instance in AWS ([ami-0cf99b93583fda897](https://bitnami.com/redirect/to/2407757/magento-2.4.6-68-amidebian-x64-hvm-ebs-nami?region=us-east-1) listed [here](https://bitnami.com/stack/magento/cloud/aws/amis)) and everything worked as expected. I could access the admin panel without problems 

![Screenshot 2024-01-22 at 10 00 06](https://github.com/bitnami/vms/assets/8791635/9bf61986-326e-44ab-ad41-f31b994971e3)

Please remember that Bitnami Magento requieres at least 3GB of RAM to work
