### ISSUE TITLE
New Bitnami Wordpress Lightsail - Image Update

### ISSUE THREAD

**Issue by marcus-sm8a** [bitnami/vms#1365]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

94bcadfc-782b-1b21-796c-e874057837bb

### bndiagnostic output

? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

This is a tech questions about HTTPS - this is a dev server

### Describe your issue as much as you can

Hello Bitnami, 
I have been using your Bitnami Wordpress Images previously, I have noticed on the latest release from Lightsail Bitnami Wordpress, Lightsail(AWS) have a feature to perform the SSL/HTTPS configuration from the Lightsail Control Panel directly?, on all previously released Bitnami Wordpress Images, I always used the Bitnami HTTPS configuration tool? 

Is there a Bitnami preference here, still use the Bitnami HTTPS Configuration Tool or use the AWS Lightsail Control Panel to set the SSL/HTTPS. 

From what I can tell on a quick look at the configuration files, AWS are doing the HTTPS slightly differently to Bitnami, so I would like to get a response if possible on the following - (hope I am not asking to much here) :-) 

Question "Keep using the Bitnami HTTPS Configuration Tool or use the Lightsail Control Panel to set SSL/HTTPS"?

Cheers. 

Marcus

**Comment by mdhont** [comment]
You can set up HTTPS through the Lightsail console directly, but it would possible require making changes to the Apache configuration afterwards. With the bncert tool no further configurations are required.

**Comment by marcus-sm8a** [comment]
Hello Michiel, 

Thanks for the update, I will keep using the Bitnami HTTPS configuration tool. 

Have a great day 

Thanks 
Marcus
