### ISSUE TITLE
LAMP SSH password

### ISSUE THREAD

**Issue by adnanp78** [bitnami/vms#1368]
### Name and Version

bitnami lamp

### What is the problem this feature will solve?

I can't get ssh password

### What is the feature you are proposing to solve the problem?

I try to follow the page to set password based ssh login on aws instance
https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh-password/
however, when I start an instance and check logs I don't see a welcome massage with default usernames and pass.
pls help

**Comment by mdhont** [comment]
> When I start an instance and check logs I don't see a welcome massage with default usernames and pass.

Did you manage to [enable SSH](https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh/) so you can access?

**Comment by adnanp78** [comment]
> > When I start an instance and check logs I don't see a welcome massage with default usernames and pass.
> 
> Did you manage to [enable SSH](https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh/) so you can access?

hello,
tnx for answer. i have enable ssh but there is no welcome proms with default pass on boot, pls see log.
[i-06fb32867b66a1cca.log](https://github.com/bitnami/vms/files/14009406/i-06fb32867b66a1cca.log)

**Comment by mdhont** [comment]
Can you check the output of the following command?

    cat ~/bitnami_credentials

**Comment by adnanp78** [comment]
> Can you check the output of the following command?
> 
> ```
> cat ~/bitnami_credentials
> ```

yes, command return me default pass but it dont work
Welcome to the Bitnami package for LAMP
******************************************************************************
The default password is 'xxxxx'
i try with usernames: user or bitnami or root, dont work
i try to log with auth key and run passwd to change dont work to, get
passwd: Authentication token manipulation error
maybe thi default pass if for mysql or other services but for ssh access dont work :(
tnx in advance

**Comment by mdhont** [comment]
On which page are you trying to login exactly? If it's Phpmyadmin please check the following guide:

https://docs.bitnami.com/virtual-machine/faq/get-started/access-phpmyadmin/

**Comment by adnanp78** [comment]
Hello, tnx for answer, im trying to log to ssh, with existing credential or to create new username and passy i dont want to user key logic, just normal username and pass. default pass you mentaod are not for ssh, its maybe for wordpress od mysql, i need pass for ssh.
big tnx

**Comment by mdhont** [comment]
If you followed all the steps to enable ssh you should be able to log (using ssh in the command line) in with the password you entered at first boot. (For OVA's the username and password at first boot are both "bitnami", but after login you are prompted to change it)

**Comment by adnanp78** [comment]
> If you followed all the steps to enable ssh you should be able to log (using ssh in the command line) in with the password you entered at first boot. (For OVA's the username and password at first boot are both "bitnami", but after login you are prompted to change it)
my aws nitnami lamp setup dont give me andy pass, just key and thats it.
nothing help, i try enable ssh process, default pass and bitnami bitnami. how is it possible tha I, as server admin cant change or see password. what is my opinion now, to terminate instance and all seting and try new. is there any other way to see, change, tunr on password login ?
big tny

**Comment by mdhont** [comment]
I recommend recreating the OVA completely and then log in in the prompt that's shown in the VM's screen. 

username: bitnami
password: bitnami


![Image](https://github.com/bitnami/vms/assets/18216803/1e494a87-6f31-440b-97f7-756bf484407f)

And then you will be prompted to change the password:

![Image](https://github.com/bitnami/vms/assets/18216803/1fcc7eed-2e41-480b-a076-fb88036458e7)
