### ISSUE TITLE
[Wordpress] issues while updating plugins or configure plugins

### ISSUE THREAD

**Issue by StfBauer** [bitnami/vms#1369]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

haven't got any

### bndiagnostic output

No feedback from diagnostic output.

### bndiagnostic was not useful. Could you please tell us why?

Was successfull but couldn't upload diagnostics

### Describe your issue as much as you can

I have issues that I cannot change any configuration settings via my wordpress plugins: I get error messages such as this:

Failed to make a backup of the wp-config.php file. This operation will not go ahead.
FTP credentials don't allow to copy to file /opt/bitnami/apps/wordpress/htdocs/wp-content/advanced-cache.php

CDN Table that do not exist but exist and all kind of stuff.

**Comment by jotamartos** [comment]
That's probably related to a permission-related issue. Please run the commands in this post to reconfigure the permissions in the application

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

**Comment by StfBauer** [comment]
Thanks @jotamartos 

So far, the permission looks fine, but somehow.
![Screenshot 2024-01-22 at 11 26 49](https://github.com/bitnami/vms/assets/5503835/56566637-1af6-4b4f-a4fd-15402f7317ce)


But still getting errors that the plugin cannot modify specific files, while others don't have the issue.

**Comment by jotamartos** [comment]
In the past, we found that some plugins failed when following the symlinks in the system, can you take a look at this post? 

https://github.com/bitnami/vms/issues/672#issuecomment-1427536646

As I mentioned there, if that doesn't solve the problem, please contact the plugin's developers to know more about the error and how to solve it.

**Comment by jotamartos** [comment]
>I have diagnostic logs but nowhere to put them ;)

What's the error you find in the log files?

**Comment by StfBauer** [comment]
Thanx @jotamartos 

In the end I create a new instance it already became outdated anyways.

For example the move haven't worked for the wp-content because it was no symlink it was already in the folder.

In addition there also have been a couple of other decrepancies.

So move was a viable and quick option. Still have the old instance still running but just for reference anymore.
