### ISSUE TITLE
ERPNext - Error starting "erpnext" stack | cannot start stack: ssh not accessible

### ISSUE THREAD

**Issue by pankajxmathur** [bitnami/vms#137]
### Describe your issue as much as you can

I have downloaded the latest ERPNext Installer for Mac - 13.35.3.
I am using it on **macOS Monterey (12.1)**
On starting the stack I get an error  - **cannot start stack: ssh not accessible**
See attached screenshot
Can you please advise how to fix this error.
<img width="515" alt="Screenshot 2022-07-18 at 10 46 32 PM" src="https://user-images.githubusercontent.com/833130/179577844-1734dd2f-3879-4843-90f7-6a6bd0b11596.png">

**Comment by robert-j-peterson** [comment]
Hello -- same error here, using the Magento stack
<img width="500" alt="Screen Shot 2022-07-20 at 4 07 59 PM" src="https://user-images.githubusercontent.com/65664487/180097621-282fa733-cb74-4f52-9aa8-ae85450be838.png">.

MacOS Monterey 12.4

**Comment by mdhont** [comment]
I've reproduced the issue, we are working on a fix. We will let you know in this thread when it's released.

**Comment by jotamartos** [comment]
Hi @pankajxmathur,

We republished most of the Bitnami OS X VMs with the fix. In order to update your deployment, please follow these steps:

- Remove the ~/.bitnami/stackman/machines/erpnext folder 

```
sudo rm -rf ~/.bitnami/stackman/machines/dokuwiki
```

- Download the latest version of the solution from the bitnami.com site 

https://bitnami.com/stack/erpnext/installer

- Deploy the new version and start the VM

Thanks!

**Comment by spmundi** [comment]
I have this same problem with the WordPress stack.
So far from simplifying my life using this has turned into a headache.
I download a .dmg. When it installs, all the files  are owned by me.
This is not what your documentation says: should be owned user "daemon"

**Comment by spmundi** [comment]
Perhaps my understanding of bitnami is lacking.
I thought I was downloading a native installer for MAC OSX.
I find it by following links on the website. But when I do so
I end up downloading an installer with this name:
        bitnami-wordpress-6.0.1-2-r04-osx-x86_64-vm.dmg
Is this not an installer for a VM?

**Comment by scinquegrani** [comment]
I get the same issue with Akeneo on a Mac OSX.

**Comment by spmundi** [comment]
I am left with an overwhelming conviction that
the consistency of bitnami applications and online documentation
is a completely lacking.
Am I right?

**Comment by pankajxmathur** [comment]
Hi @jotamartos and @mdhont

I followed the instructions as per your email - however the issue does not seem to have been resolved.
While there is no error - however status of services on various tabs do not seem to start.
I am also not able to start the services manually. 
Can you please investigate the issue further
Please see screenshots below



<img width="512" alt="Screenshot 2022-07-25 at 12 43 42 PM" src="https://user-images.githubusercontent.com/833130/180719560-161335b8-da1f-4d2c-bcdc-2cb97de709fb.png">

<img width="519" alt="Screenshot 2022-07-25 at 12 44 00 PM" src="https://user-images.githubusercontent.com/833130/180719648-d062df1e-a2f1-4a8e-8c17-aae05944db87.png">

<img width="518" alt="Screenshot 2022-07-25 at 12 44 11 PM" src="https://user-images.githubusercontent.com/833130/180719691-ffca83c2-2b5a-4bfd-ac5d-d8a29a00c47c.png">

<img width="520" alt="Screenshot 2022-07-25 at 12 44 25 PM" src="https://user-images.githubusercontent.com/833130/180719749-b5c6dd9b-d743-4f33-bc12-169655494b26.png">

<img width="524" alt="Screenshot 2022-07-25 at 12 44 40 PM" src="https://user-images.githubusercontent.com/833130/180719820-d2e33c98-be9d-4833-adda-70243afd4c66.png">

**Comment by pankajxmathur** [comment]
Hi @jotamartos and @mdhont

Can you also let me know the default **UserName** and **Password** that I should use on first login.

**Comment by jotamartos** [comment]
Hi @pankajxmathur ,

The services take some time to be fully started after staring the VM. Please check the services tab after some minutes. 

Regarding the username and password, please find the information in our documentation 

https://docs.bitnami.com/installer/apps/erpnext/get-started/first-steps/#os-x-vm-123

**Comment by jotamartos** [comment]
Hi @spmundi

> bitnami-wordpress-6.0.1-2-r04-osx-x86_64-vm.dmg
> Is this not an installer for a VM?
> 
> Update: well, I guess it isn't but the name is confusing.
> I still cannot get it to work (previous comment about ssh)

That's the latest OS X VM for WordPress we released. I just downloaded it and confirmed it works as expected 

![Screen Shot 2022-07-25 at 10 36 21](https://user-images.githubusercontent.com/8791635/180734688-4e3820cf-470b-43cf-a3fd-077074c76a55.png)

Please ensure you remove the information in the ~/.bitnami folder before starting the VM.

- Close the OS X VM UI
- Remove the ~/.bitnami folder 

```
sudo rm -rf ~/.bitnami
```

- Launch the Bitnami OS X VM again and click on start
- Wait for the services to be running

**Comment by pankajxmathur** [comment]
Hi @jotamartos and @mdhont 

I have patiently waited for more than 30 minutes after starting the stack, however the service status does not change.
All services stay exactly as what you see in the screenshots that I have shared with you.
Can you please investigate further.

Regards,

Pankaj

**Comment by spmundi** [comment]
The solution upthread+1 by jotarmartos worked for me.
Deleting the .bitnami folder seemed to do the trick

**Comment by pankajxmathur** [comment]
> The solution upthread+1 by jotarmartos worked for me. Deleting the .bitnami folder seemed to do the trick

I have already tried this but did not work

**Comment by jotamartos** [comment]
Hi @pankajxmathur,

In your case, it seems you can start the OS X VM but not the services inside the VM. If you launched that instance and edit the configuration, it may be the case in which the services can't be started. If you launch the VM from scratch (remove the ~/.bitnami folder and download the latest version from the bitnami.com site), the services should work. If that's not a possible solution for you because you do not want to remove the deployment's information, please create a separate thread to help you check the status of the services.
