### ISSUE TITLE
[Joomla!] Bitnami Joomla 3 with PHP 8.0 for GCE

### ISSUE THREAD

**Issue by ManosMantzas** [bitnami/vms#1371]
### Describe your issue as much as you can

Hi,

Is it possible to install an older version of Bitnami Joomla in GCP Compute Engine? I need Joomla 3.10.12 with PHP 8.0? And how do I do that?
Thank you in advance.

**Comment by ManosMantzas** [comment]
Of course, this is fine too:
Version 3.10.1-0      2021-08-24
* Updated modsecurity-apache to 0.20210819.0
* Updated gosu to 1.14.0
* Updated composer to 2.1.6
* Updated joomla to 3.10.1

**Comment by ManosMantzas** [comment]
If none of the above are possible? How do I downgrade to PHP 8.0? This is my main issue. I tried this: https://linux.how2shout.com/easy-way-to-install-php-8-0-on-debian-11-bullseye-server/ but it didn't work.
php -v
still shows:
PHP 8.1.27

**Comment by jotamartos** [comment]
Hi @ManosMantzas,

Thank you for using Bitnami. Unfortunately, it's not possible to launch a previous version of a solution in the Google Cloud. It's not possible to downgrade the PHP version in a running instance either. 

As an alternative, you can try launching that version in AWS (its Marketplace allows you select previous versions) or deploy it locally using our OVAs. Once you deploy that old version, you can try migrating the files to a Google Cloud instance as explained here

https://docs.bitnami.com/general/apps/joomla/administration/backup-restore/
