### ISSUE TITLE
Bitnami package for WordPress with NGINX and SSL - FastCGI cache / Varnish

### ISSUE THREAD

**Issue by Barnabas2** [bitnami/vms#1374]
### Describe your issue as much as you can

Hello,

I’m using the Bitnami Nginx image for wordpress on MS Azure and I’ wondering, is it already configured the NGINX FastCGI cache or do I need to take a manual action to enable it?

Could you please also advise whether installing varnish on ngninx is a good idea or not?

Thank you

**Comment by jotamartos** [comment]
>I’m using the Bitnami Nginx image for wordpress on MS Azure and I’ wondering, is it already configured the NGINX FastCGI cache or do I need to take a manual action to enable it?

You will need to configure it. The NGINX conf file is at /opt/bitnami/nginx/conf/nginx.conf and the WordPress-related conf files are inside the /opt/bitnami/nginx/conf/server_blocks directory. 

>Could you please also advise whether installing varnish on ngninx is a good idea or not?

That depends on your needs. Please note that Varnish is a cache server that works well in many scenarios but you can also run into issues with some plugins/extensions. You can give it a try but take this into account if something doesn't work as expected.

**Comment by Barnabas2** [comment]
Thank you. Is there an official bitnami documentation to enable FastCGI or is there one other you can please recommend?

**Comment by jotamartos** [comment]
No, we do not have any specific guide about this in https://docs.bitnami.com but you will probably find many online.

**Comment by Barnabas2** [comment]
Thank you.
