### ISSUE TITLE
Need bitnami-lampstack-7.4.33-0-linux-x64-installer.run

### ISSUE THREAD

**Issue by BastyJuice** [bitnami/vms#1375]
### Describe your suggestion as much as you can

Hello,

i need bitnami-lampstack-7.4.33-0-linux-x64-installer.run, [Jota Martos]meteation on this thread https://stackoverflow.com/questions/29235186/is-there-a-way-to-download-previous-versions-of-bitnami-wamp-stack
that a user can request it here would be nice if someone can get me a link

**Comment by jotamartos** [comment]
Here you are 😄 

https://downloads.bitnami.com/files/stacks/lampstack/7.4.33-0/bitnami-lampstack-7.4.33-0-linux-x64-installer.run

**Comment by ntsrsnaresh** [comment]
Still it is not working

**Comment by jotamartos** [comment]
The link expired and we are recovering the file again. We will notify you once it's ready

**Comment by ntsrsnaresh** [comment]
it's working

**Comment by ntsrsnaresh** [comment]
Does this bitnami version supports RHEL 8 systems ?

**Comment by ntsrsnaresh** [comment]
Can you give me the Bitnami version of 7.4.32

**Comment by jotamartos** [comment]
>Does this bitnami version supports RHEL 8 systems ?

The installer should work in that system but I can't confirm it now because it's an old one and we do not have that information right now. 

>Can you give me the Bitnami version of 7.4.32

Recovering the installers is not an easy job, it takes time. You are requesting 7.4.32 when 7.4.33 is available for download, doesn't it work for you? Please note that it's only a patch version change.

**Comment by ntsrsnaresh** [comment]
I'm encountering errors with version 7.4.33; it's not functioning as expected.
![error](https://github.com/bitnami/vms/assets/80150696/7c5fbbaf-8e3d-408c-8771-6c94e7204f86)
![error](https://github.com/bitnami/vms/assets/80150696/ae7d3efc-3a78-474c-8e10-7ce2708c5253)

**Comment by jotamartos** [comment]
As it mentions, it doesn't support your platform. You will need to install it on a different OS

**Comment by ntsrsnaresh** [comment]
Thanks

**Comment by shajeerEmiratesZone** [comment]
Hi, can I get the same file? I'm unable to download from the provided link. It redirects to https://bitnami.com/

**Comment by shajeerEmiratesZone** [comment]
> Here you are 😄
> 
> https://downloads.bitnami.com/files/stacks/lampstack/7.4.33-0/bitnami-lampstack-7.4.33-0-linux-x64-installer.run

I tried to download the file and I'm being redirected to Bitnami home page. Please help.

**Comment by procopio** [comment]
same problem here. please anyone know where to find it?

**Comment by jotamartos** [comment]
We do not provide installers anymore, they were completely removed from our records. However, you can download the VM from here:

https://vcf.broadcom.com/vsc/services/details/lampstack?slug=true
https://docs.bitnami.com/virtual-machine/get-started-vmware-workstation/
