### ISSUE TITLE
[wordpress] Can't configure bitnami wordpress 301 redirects (Nginx)

### ISSUE THREAD

**Issue by nvsajeeva** [bitnami/vms#1376]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

84b6ed50-1bd2-ed56-d107-e802faca4308

### bndiagnostic was not useful. Could you please tell us why?

This is to seek advise on a configuration. Not an issue

### Describe your issue as much as you can

Hello,
I have bitnami wordpress (nginx) installation on AWS (deployed through AWS marketplace). I have been trying to configure a simple redirect as follows, with no success. 
Whenever, someone visits https://mydomain.com/section1/page1.php, it should be redirected to https://mydomain/section2/page1.php

I found a few bitnami articles, but those are related to apache. Please kindly advise. Thanks.

**Comment by mdhont** [comment]
The following Bitnami Nginx guides might be helpful:

    https://docs.bitnami.com/aws/infrastructure/nginx/configuration/understand-default-config-nginx/
    https://docs.bitnami.com/aws/infrastructure/nginx/configuration/create-vhost-nginx/

For learning how to apply redirect rules for Nginx I recommend the official documentation:

https://www.nginx.com/blog/creating-nginx-rewrite-rules/
