### ISSUE TITLE
[Akeneo] Unable to Import/Export

### ISSUE THREAD

**Issue by mikibunny99** [bitnami/vms#1379]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

180d25d2-a9e7-9752-849a-1eff6503аса8

### bndiagnostic output

[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the following guide to open server ports for remote access:
https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

This is clean start of the image

### Describe your issue as much as you can

Since version 7.0.10 the import and export functionality is broken. I have tried with two computers both on VM VirtualBox and VMware Workstaton. Anything pririor to this version is working fine. I have accees to web interface, so connectivity issue from bndiagnostic output is not related.
![akeneo-export](https://github.com/bitnami/vms/assets/157379878/328c6611-80d1-4825-b6e7-251ea7e48b50)

**Comment by jotamartos** [comment]
Hi @mikibunny99,

I just tried to reproduce the issue but the export process worked properly for me. In my case, I created a test export profile 

![Screenshot 2024-01-29 at 15 28 23](https://github.com/bitnami/vms/assets/8791635/a4bbefd8-b49e-49f1-88a2-ea9a59afbcd5)

and exported the data later 

![Screenshot 2024-01-29 at 15 28 02](https://github.com/bitnami/vms/assets/8791635/124f349b-d43b-4c19-b11c-0b41cf72e4ed)


As you can see, the data was exported correctly and I could download the csv file with the data. Please contact the Akeneo team to get more information about the issue you are running into.

**Comment by kingulrigo** [comment]
Hi everyone
I have the same Issue on AWS cloud - unfortunately it never worked on my fresh installation. doesn't matter what I do this blue button won't appear and it doesn't save any files (not even empty ones) in the tmp folder

**Comment by jotamartos** [comment]
That seems to be a specific issue of the app. Please contact the Akeneo's support team to get more information about how to resolve it.

**Comment by chavezdf** [comment]
I have the same issue, I just deployed the Bitnami VM Akeneo 7.0.50 and trying to export information it just do anything. 

I have done the same on Virtualbox and VMware

![Captura de pantalla 2024-02-22 163325](https://github.com/bitnami/vms/assets/22506527/130f0241-09d0-4b0c-94d4-3ba8547bf430)

**Comment by chavezdf** [comment]
> Hi @mikibunny99,
> 
> I just tried to reproduce the issue but the export process worked properly for me. In my case, I launched a fresh VM in AWS Cloud with Akeneo 7.0.49 and I created a test export profile
> 
> ![Screenshot 2024-01-29 at 15 28 23](https://private-user-images.githubusercontent.com/8791635/300494866-a4bbefd8-b49e-49f1-88a2-ea9a59afbcd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTYyMDEsIm5iZiI6MTcwODYxNTkwMSwicGF0aCI6Ii84NzkxNjM1LzMwMDQ5NDg2Ni1hNGJiZWZkOC1iNDllLTQ5ZjEtODhhMi1lYTlhNTlhZmJjZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTUzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBlOTU5MDY5MDFhNGYzMjEzOGE0OTQ2ZDhmZGQ0MmRlNDEzOGZiMmZiMGQyYWQ5Y2Y4NmQyNGQ2YTI4OGExZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MkL9z3aOm2OUsSUrmxaetsv8IhDxDjyy6OHD42zeQzY)
> 
> and exported the data later
> 
> ![Screenshot 2024-01-29 at 15 28 02](https://private-user-images.githubusercontent.com/8791635/300494911-124f349b-d43b-4c19-b11c-0b41cf72e4ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTYyMDEsIm5iZiI6MTcwODYxNTkwMSwicGF0aCI6Ii84NzkxNjM1LzMwMDQ5NDkxMS0xMjRmMzQ5Yi1kNDNiLTRjMTktYjExYy0wYjQxY2Y3MmU0ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTUzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmYxZGVhMzU0NDIxZjVlYjIyOGY3MDc0ZWYwZWQ3ODBiYTVkNjcxZGFkMjc0ODA5OTk1MWZlZmVmYjc0MmUzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bturdCPAi2a6jjnNgCzW26iHSajdCjyL03YOwB5bcwA)
> 
> As you can see, the data was exported correctly and I could download the csv file with the data. Please contact the Akeneo team to get more information about the issue you are running into.

Did you try on VirtualBox or VMware? The mentioned issue is on those platforms.

**Comment by jotamartos** [comment]
Hi all, 

We just reproduced the issue and found a solution, please follow these steps:

- Edit the /etc/systemd/system/bitnami.akeneo.service file and set the PATH environment parameter 

```
[Service]
Type=simple
ExecStart=/opt/bitnami/php/bin/php /opt/bitnami/akeneo/bin/console messenger:consume ui_job import_export_job data_maintenance_job --env=prod
Environment=PATH=/opt/bitnami/akeneo/bin:/opt/bitnami/apache/bin:/opt/bitnami/apache2/bin:/opt/bitnami/common/bin:/opt/bitnami/elasticsearch/bin:/opt/bitnami/gonit/bin:/opt/bitnami/java/bin:/opt/bitnami/mysql/bin:/opt/bitnami/node/bin:/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/python/bin:/opt/bitnami/nami/bin:/opt/bitnami/akeneo/bin:/opt/bitnami/apache/bin:/opt/bitnami/apache2/bin:/opt/bitnami/common/bin:/opt/bitnami/elasticsearch/bin:/opt/bitnami/gonit/bin:/opt/bitnami/java/bin:/opt/bitnami/mysql/bin:/opt/bitnami/node/bin:/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/python/bin:/opt/bitnami/nami/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
User=daemon
Group=daemon
```

- Reload the systemd information 

```
sudo systemctl daemon-reload
```

- Restart  the service 

```
sudo service bitnami.akeneo restart
```

- Confirm you can run the export process now in the application

**Comment by chavezdf** [comment]
I did exactly what you posted and it does not worked for me.

**Comment by chavezdf** [comment]
![Captura de pantalla 2024-02-26 222729](https://github.com/bitnami/vms/assets/22506527/36fb1d22-0f84-4130-8a99-4b2352e79012)
![Captura de pantalla 2024-02-26 222702](https://github.com/bitnami/vms/assets/22506527/69470177-3978-4eca-95fa-3e082f20340a)

**Comment by chavezdf** [comment]
![Captura de pantalla 2024-02-26 222540](https://github.com/bitnami/vms/assets/22506527/513021d9-50fa-451e-abb6-42d4cd2d3bb5)

**Comment by chavezdf** [comment]
I also manually installed Akeneo version 7.050 over Ubuntu 22.04 and it has the same problem.

**Comment by chavezdf** [comment]
![Captura de pantalla 2024-02-26 223316](https://github.com/bitnami/vms/assets/22506527/fbf25563-8af4-4db6-8465-b4a475fb15e1)

**Comment by chavezdf** [comment]
Now I understand what is happening. In the bitnami VM did not configured the "job queue daemon"
https://docs.akeneo.com/master/install_pim/manual/daemon_queue.html

**Comment by jotamartos** [comment]
Hi @chavezdf,

That daemon is the service you edited in the /etc/systemd/system/bitnami.akeneo.service file. I just followed my steps in a Bitnami Akeneo VM (latest version) and everything worked as expected. Please ensure you follow all steps and that the bitnami.akeneo service is up and running 

```
sudo systemctl bitnami.akeneo status
```
