### ISSUE TITLE
[<Bitnami - AWS Lightsail - Apache>] <This site can’t be reached> 

### ISSUE THREAD

**Issue by nischinth** [bitnami/vms#138]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0bf6f0a1-664e-14d7-7e42-883eae9c74b6

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Jul 18 19:45:11.897145 2022] [ssl:error] [pid 1896:tid 140490754172672] 
[client **ip_address**:33600] AH02042: rejecting client initiated renegotiation
 [Mon Jul 18 19:45:16.733513 2022] [ssl:error] [pid 848:tid 140492111181568] 
[client **ip_address**:57116] AH02042: rejecting client initiated renegotiation
 [Mon Jul 18 23:25:25.778271 2022] [proxy_fcgi:error] [pid 893:tid 
Press [Enter] to continue:
140491886630656] [client **ip_address**:54171] AH01071: Got error 'PHP message: 
PHP Notice: Undefined index: host in 
/opt/bitnami/wordpress/wp-includes/canonical.php on line 687PHP message: PHP 
Notice: Undefined index: host in 
/opt/bitnami/wordpress/wp-includes/canonical.php on line 696PHP message: PHP 
Notice: Undefined index: host in 
/opt/bitnami/wordpress/wp-includes/canonical.php on line 699'

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

[Resources]

Press [Enter] to continue:
Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 7978 5181 1264 89 1532 2435 
Swap: 3071 0 3071
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

In this tool, we can find errors and suggestion, so that we can solve

### Describe your issue as much as you can

Hello, my wordpress site is hosted in AWS Lightsail, almost twice a day, it goes down, yesterday also it was down again, whenever I try to access my website, its shows **"This site can’t be reached"**, after restarting the instance it will work fine,  please help me out on this issue

**Comment by jotamartos** [comment]
Please do not create duplicated tickets. I'll take care of your other ticket 

https://github.com/bitnami/vms/issues/136
