### ISSUE TITLE
Bitnami wordpress Apache not starting at all

### ISSUE THREAD

**Issue by bbtanou** [bitnami/vms#1381]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3db247f2-9f6e-558d-431d-88f8354c2849

### bndiagnostic output

✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

I think it has been useful to pointing out where the problem seem to be.

### Describe your issue as much as you can

Hi, I hope you're all fine. Thanks for the support.
In fact, my configuration was all good, and the site was running well until yesterday. I was in the process of making some configurations for a new site, and I don't know if I touched something that went wrong. The WordPress site crashed, and all the services wouldn't start anymore. I made some permission changes to see if I could fix the issue since apache/logs/error_log was pointing to permission problems that even bndiagnostic seems to validate, but no success. Here, for example, is the output of bndiagnostic:
`[Mon Jan 22 16:59:20.750830 2024] [proxy_fcgi:error] [pid 1181050:tid 
140706542774016] [client **ip_address**:12042] AH01079: failed to make 
connection to backend: httpd-UDS
 [Mon Jan 22 16:59:21.230020 2024] [proxy:error] [pid 1181050:tid 
140706525988608] (13)Permission denied: AH02454: FCGI: attempt to connect to 
Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Mon Jan 22 16:59:21.230049 2024] [proxy_fcgi:error] [pid 1181050:tid 
140706525988608] [client **ip_address**:12043] AH01079: failed to make 
connection to backend: httpd-UDS, referer: https://www.infpguinee.com/
`
Thank you for any support you can provide.

**Comment by mdhont** [comment]
The following guide shows how you can set the correct permissions:

https://docs.bitnami.com/aws/apps/wordpress/administration/understand-file-permissions/

Don't forget to restart Apache afterwards:

    /opt/bitnami/ctlscript.sh restart apache

**Comment by bbtanou** [comment]
Hi mdhont. Thank you very much for the support.
After following all the instructions there and ran the command below 
/opt/bitnami/ctlscript.sh restart apache

i got the error below 

Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid).

**Comment by bbtanou** [comment]
Hi mdhont.
I've been able to start apache and php-fpm but unable to start mariadb.

this error that I've mentioned previously seem to be fixed although manually by going to this directory and starting it `/opt/bitnami/gonit/bin`. 
`Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid).`

After a while running to docs trying to figure out some solutions am still short.

I need some help please.

**Comment by mdhont** [comment]
Can you try starting it in the following way:

    sudo /opt/bitnami/scripts/mariadb/start.sh

**Comment by bbtanou** [comment]
`mariadb 17:16:36.38 ERROR ==> mariadb did not start`

Hi mdhont. Thank you for the time really. Above is the result of that command

**Comment by bbtanou** [comment]
Hi. I solved it by changing the ownership of these files
`-rw-rw---- 1 mysql mysql 5855 Jan 25 05:15 mariadb/logs/mysqld.log
`
`-rw-rw---- 1 mysql mysql 6 Jan 25 05:15 mysqld.pid
srwxrwxrwx 1 mysql mysql 0 Jan 25 05:15 mysql.sock
`
Thank you so much.
