### ISSUE TITLE
[akeneo] api / app issue : Full authentication is required to access this resource.

### ISSUE THREAD

**Issue by Edgard-Unbottled** [bitnami/vms#1383]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d05f4d9a-a10a-1ebd-5732-d5762cf7f0f3

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Connectivity: Found possible issues
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ✓ Mysql: No issues found
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
Press [Enter] to continue:
```
 total used free shared buff/cache available Mem: 7959 3682 1295 67 2981 3903 
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Jan 23 18:32:55.818502 2024] [authz_core:error] [pid 2379:tid 
140257055930112] [client **ip_address**:36380] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
 [Tue Jan 23 18:32:55.818752 2024] [authz_core:error] [pid 2379:tid 
140257055930112] [client **ip_address**:36380] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
 [Wed Jan 24 01:57:33.490722 2024] [authz_core:error] [pid 772:tid 
Press [Enter] to continue: 
140256678258432] [client **ip_address**:43830] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/index.php

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

/opt/bitnami/apache/cgi-bin not exsists

### Describe your issue as much as you can

Hi,
I'm trying to connect to akeneo via api and app using credentials and token but I get "Full authentication is required to access this resource". Ports 22, 80, 443 are open and set to any. Apache configuration has been reviewed with my domain name. Akeneo API permissions has been attributed to user. 
Thank you

**Comment by gongomgra** [comment]
Hi @Edgard-Unbottled,

Thanks for using Bitnami. Did you perform any change in the Akeneo configuration? How are you trying to connect with the API? According to the official guide below, there are some extra configuration steps required to properly use the API. Can you check it?

https://api.akeneo.com/getting-started/connect-the-pim-4x/welcome.html

**Comment by Edgard-Unbottled** [comment]
Hi @gongomgra I didn't perform any changes to Akeneo configuration. I'm trying to connect to API via /api/oauth/v1/token using a Python script and my credentials. Everything is well setup according to Akeneo documentation. Something seems to block calls server side.

**Comment by gongomgra** [comment]
Hi @Edgard-Unbottled,

Did you get any related information in Akeneo or Apache logs? Can you try to increase the log level to debug and try again?

**Comment by monlouisj** [comment]
I had the same problem with version 7. It was a server configuration issue.
