### ISSUE TITLE
[RabbitMQ] How do I enable `RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true` environment variable on an azure vm?

### ISSUE THREAD

**Issue by gongomgra** [bitnami/vms#1384]
How do I enable `RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true` environment variable on an azure vm instance running the bitnami rabbitmq image?

_Originally posted by @ugumerie in https://github.com/bitnami/containers/issues/53114#issuecomment-1898621362_

**Comment by gongomgra** [comment]
Hi @ugumerie,

We created this ticket from your comment in the containers forum. To allow web access in your cloud image, you need to add the line below to the RabbitMQ config file and restart the services for changes to take effect. Remember to replace `RABBITMQ_USERNAME` with your actual value (default username is `user`)

```
loopback_users.RABBITMQ_USERNAME = false
```

You can restart the services running the commands below

```
sudo /opt/bitnami/ctlscript.sh restart
```

Hope it helps!

**Comment by ugumerie** [comment]
Hello,

Thank you, it helped, its working now.
