### ISSUE TITLE
Steps tp Disable TLS 1.0

### ISSUE THREAD

**Issue by dannypiz** [bitnami/vms#1385]
### Describe your issue as much as you can

Can you provide the steps to disable TLS 1.0.

**Comment by dannypiz** [comment]
![Capture](https://github.com/bitnami/vms/assets/56599944/00cc9445-d4bd-4007-87aa-5491010a7415)

**Comment by dannypiz** [comment]
![image](https://github.com/bitnami/vms/assets/56599944/d143cb36-5043-438f-b4aa-bb5cbdbedcde)
![Capture545](https://github.com/bitnami/vms/assets/56599944/4773c8ff-823b-4c7e-ab80-9f6e0090a64f)

**Comment by dannypiz** [comment]
![Capture545](https://github.com/bitnami/vms/assets/56599944/dc46aac4-12ca-4148-ad6a-76d24f4fcfc5)

**Comment by dannypiz** [comment]
![Capture545](https://github.com/bitnami/vms/assets/56599944/e32854b4-ac10-4c56-a506-cdceb7516d47)

**Comment by dannypiz** [comment]
![1-24-2024 11-08-26 AM](https://github.com/bitnami/vms/assets/56599944/64b69c56-bbf6-4438-aa2b-c3273fc25223)

**Comment by mdhont** [comment]
The following guide shows where the Bitnami Apache configuration files can be found:

https://docs.bitnami.com/aws/apps/wordpress/get-started/understand-config/

For disabling TLS 1.0 you can follow the official documentation:

https://httpd.apache.org/docs/trunk/ssl/ssl_howto.html
