### ISSUE TITLE
[wordpress] varnish vcl very different to official docs

### ISSUE THREAD

**Issue by ErnstDinkelmann** [bitnami/vms#139]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0c14237b-9770-1fa4-6435-7c36dc102ea6

### bndiagnostic output

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

The suggested guidelines are not relevant to my issue.

### Describe your issue as much as you can

Hi there!

wp-rocket is unable to automatically purge varnish cache, even thought the "varnish" add-on is enabled in the wp-rocket settings.

I inspected the default.vcl compared to the "official" varnish one, and there are significant differences - in particular related to "purge" things.

The one I implemented, from your docs:
https://docs.bitnami.com/aws/apps/wordpress/configuration/configure-varnish/

The "official" one:
https://www.varnish-software.com/developers/tutorials/configuring-varnish-wordpress/?utm_medium=wiki&utm_source=%2fwiki%2fcontent%2ftutorials%2fwordpress%2fwp_step_by_step.html

There is a good change that this is the reason for the inability of the wp-rocket plugin to clear the varnish cache. It would be great if you can check that. I'm worried to just make changes without understanding this.

It may also be worthwhile just checking that your vcl version is still in fact the recommended one and that it does not perhaps require some updates related to the things seen in the "official" version.

Would really appreciate help in resolving this.

Thank you.
Ernst

**Comment by mdhont** [comment]
Our documentation is meant as a way to get started with the application, where logs and configuration files are located etc. Unfortunately we can't cover all possible scenarios and we always recommend check the official guides to explore further configuration options.

**Comment by ErnstDinkelmann** [comment]
OK, thanks. I'm in discussion with wp-rocket to get to the bottom of this.
