### ISSUE TITLE
[ActiveMQ] Web console doesn't require username and password in 6.0.1

### ISSUE THREAD

**Issue by ttichy** [bitnami/vms#1390]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

90ab5f83-efff-1d6e-e68f-06513847119c

### bndiagnostic was not useful. Could you please tell us why?

It doesn't test activemq console security setup

### Describe your issue as much as you can

The 6.0.1 version of bitnami doesn't secure the web console with username and password.
Instead, it relies on host 127.0.0.1.

Previous versions (5.17 and 5.18 afaik) used `jetty-realm.properties` and `org.eclipse.jetty.security.HashLoginService` to ensure only authorized users were able to access the console

**Comment by mdhont** [comment]
Could you tell me the steps to reproduce the issue?

**Comment by ttichy** [comment]
deploy bitnami activemq 6.0.1 to aws.
ssh into the instance
`curl -XGET -H "Origin: https://localhost" --user admin:whatever http://localhost:8161/api/jolokia/read/java.lang:type=Memory/*`
Observe the JSON answer instead of HTTP 401 regardless of the user and password

**Comment by ttichy** [comment]
It happens because of change in the `org.eclipse.jetty.security.ConstraintMapping` bean, `pathSpec` property.
In ActiveMQ 5, the setting was `/,/api/*,*.jsp,*.html,*.js,*.css,*.png,*.gif,*.ico"`.
In ActiveMQ 6, the setting is `*.jsp`. 

In my case I changed the pathSpec to `/*`
