### ISSUE TITLE
[Magento] Requesting Magento 2.4.4 OVA/Linux installer

### ISSUE THREAD

**Issue by pyramicapablo** [bitnami/vms#1393]
### Describe your issue as much as you can

In other issues is pointed that old versions are attended oppening a specific request. I have tried links in previous requests (f.e. https://github.com/bitnami/vms/issues/962#issuecomment-1578351982) but the links don´t work anymore.

Can you provide some form of install or OVA for 2.4.4? Thank you!

**Comment by jotamartos** [comment]
Here you are! :) 

https://downloads.bitnami.com/files/stacks/magento/2.4.4-9/bitnami-magento-2.4.4-9-r02-linux-debian-11-x86_64-nami.ova
