### ISSUE TITLE
bitnami website: can't login

### ISSUE THREAD

**Issue by mausolos** [bitnami/vms#1397]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

doesn't apply to this situation

### bndiagnostic output

not relevant, just trying to login to bitnami.com

### bndiagnostic was not useful. Could you please tell us why?

just trying to login to bitnami.com

### Describe your issue as much as you can

when I try to login with my google account, it says i can't login because the email exists. when i try to reset my password for my email-based account, i receive nothing. i do have the original email from when i setup my bitnami account in 2015, but otherwise a full search of my email has verified that i haven't received anything from or about bitnami recently, not even in my trash or spam folder.

btw, there doesn't appear to be anywhere i can go to get help for login issues, so... i guess i'm looking for help here?

**Comment by mausolos** [comment]
oh and.. just in case it had been my github auth i was using, i tried that too. same issue.

**Comment by mausolos** [comment]
Well, it's been about 20 minutes or so...

![image](https://github.com/bitnami/vms/assets/967613/660451e8-b4bc-41fd-a16e-594d866a7341)

**Comment by jotamartos** [comment]
Hi @mausolos, 

We investigated this and saw that you requested the password reset 3 times at 2024-02-06T04:38:38.396013, 2024-02-06T04:37:14.882093 and 2024-02-06T17:09:37.835896 (UTC times) and those emails were properly sent and not bounced back so you should have received all of them in your inbox. Could you please verify you do not have any filter in place? 

If necessary, we can send you the reset password link from my work email address so you can reset the password but I also want to let you know that the login is not necessary to download or launch any of the Bitnami solutions. 

Thanks

**Comment by mausolos** [comment]
My bad, I double checked spam specifically, and sure enough... I should be
able to do it now, thanks!

**Comment by jotamartos** [comment]
Don't worry @mausolos, I'm glad to hear you could reset your password.
