### ISSUE TITLE
Apache server wont start

### ISSUE THREAD

**Issue by anthonymann628** [bitnami/vms#1398]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

67264c78-b9a4-2d15-7caf-c9a2e93174e2

### bndiagnostic output

? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

I have no idea

### Describe your issue as much as you can

edited two files:
/wordpress-https-vhost.conf
and

**Comment by anthonymann628** [comment]
wordpress-vhost.conf

Not sure what happened but apache wont start or restart now.

**Comment by anthonymann628** [comment]
I should also note, I have reverted both files back to the original without success

**Comment by gongomgra** [comment]
Hi @anthonymann628,

Thanks for using Bitnami. According to the bndiagnostic bundle you shared, the `/opt/bitnami/apache2/conf/vhosts/wordpress-https-vhost.conf` file is not properly formated

```
<VirtualHost 127.0.0.1:443 _default_:443> ServerName www.example.com ServerAlias *
  SSLEngine on SSLCertificateFile
  "/opt/bitnami/apache/conf/bitnami/certs/server.crt" SSLCertificateKeyFile
  "/opt/bitnami/apache/conf/bitnami/certs/server.key" DocumentRoot
  /opt/bitnami/wordpress <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
    # END WordPress
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
</VirtualHost>
```

You mentioned you have already updated the file. In that case, please run the command below to test Apache configuration again and then fix the new issue it detects

```
apachectl -t
```
