### ISSUE TITLE
[Bitnami Moodle 4.3] Static IP failure

### ISSUE THREAD

**Issue by martinjp84** [bitnami/vms#1403]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Nope

### bndiagnostic was not useful. Could you please tell us why?

Not related

### Describe your issue as much as you can

Instructions for static IP are incorrect for latest debian 5.10/moodle 4.3 version. 

https://docs.bitnami.com/virtual-machine/faq/configuration/configure-static-address/

Address reverts to DHCP during reboot. Restarting systemd-networkd.service resolves it temporarily.

**Comment by mdhont** [comment]
Could you explain what you mean with temporarily? Does it revert after reboot after restarting systemd-networkd.service?

**Comment by martinjp84** [comment]
It reverts after a reboot

________________________________

**Comment by martinjp84** [comment]
Editing /etc/systemd/network/25-wired.network and matching either the interface name or alt name fails to keep the static IP after a system reboot. Static IP is always applied after restarting systemd-networkd.service.

File in /etc/network/interfaces.d called '50-cloud-init' is taking priority, editing this file with the below contents will allow a static IP but it will not update the welcome screen section 'You can access the application at http://ip-address', the IP here will remain the same as before.

50-cloud-init file config for static IP. Note that 'ens3' should be replaced with the real interface name or alt name.

# The loopback network interface
auto lo
iface lo inet loopback
 
# The primary network interface
auto ens3
iface ens3  inet static
 address 192.168.1.100
 netmask 255.255.255.0
 gateway 192.168.1.254

**Comment by martinjp84** [comment]
Disabling cloud-init by creating a file at - /etc/cloud/cloud.cfg.d/99-custom-networking.cfg and containing 'network: {config: disabled}'  does not revert the control back to /etc/systemd/network. 

Editing /etc/network/interfaces or /etc/network/interfaces.d/<filename> (latter takes priority), seems to be the current solution
