### ISSUE TITLE
wordpress on aws, redirect http to https

### ISSUE THREAD

**Issue by KirillSelyak** [bitnami/vms#1407]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7b7101fe-f012-71e7-b61f-d7dbbff568d8

### bndiagnostic output

    ✓ Apache: No issues found
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

not unclear how it might help with redirect issue

### Describe your issue as much as you can

I'm trying to follow this instructions https://docs.bitnami.com/aws/apps/wordpress/administration/force-https-apache/ to setup redirect from http to https and it doesn't work. 
How this one can be troubleshooted?

**Comment by mdhont** [comment]
The following guide might be of help:

https://docs.bitnami.com/aws/apps/wordpress/administration/force-https-apache/

**Comment by KirillSelyak** [comment]
Sorry, I didn't get or missed a notification about reply. 
Reply was useless or a kind of joke. 
I used  this guide https://docs.bitnami.com/aws/apps/wordpress/administration/force-https-apache/ and it doesn't work. 
Actually that is what I initially described in the issue )))

How it could be troubleshooted?

**Comment by KirillSelyak** [comment]
Found a root cause.   
Be sure you setup such settings exactly inside **VirtualHost**, not inside **Directory**  

Initially I configured it inside Directory  and it worked well for redirect from www to not www web address, but it didn't work for redirect from http to https.  
When moved these settings from Directory tag to VirtualHost tag then the issue is gone.
