### ISSUE TITLE
[Wordpress packaged by Bitnami] <The Root certificate of the server certificate used by the backend doesn't match the trusted certificate>

### ISSUE THREAD

**Issue by usmanbinnaeem** [bitnami/vms#141]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3f6d25ef-dbaa-f7ba-7f85-a2fc9f676b6e

### bndiagnostic output

    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ✓ Apache: No issues found
    ✓ Mariadb: No issues found
    ✓ WordPress: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

its useful

### Describe your issue as much as you can

Hi I deployed Linux Vm (WordPress packaged by Bitnami ). I installed GoDaddy Class 2 Certification Authority Root Certificate – G2 (https://certs.godaddy.com/repository/gdroot-g2.crt?utm_source=AboutSSL&utm_medium=Affiliate&utm_content=/go-daddy-root-certificates/) on server root and GoDaddy's SSL certificate for Apache server. both were installed successfully. now when I try to add azure firewall I get the following error.

I appreciate it If anybody can help to find out why this happening. error image is attached below.
![error](https://user-images.githubusercontent.com/61014982/179763387-3cf759c7-8fe9-4018-a033-00b4c2fa89f8.jpeg)

**Comment by mdhont** [comment]
I recommend checking the following guide:

https://docs.bitnami.com/aws/apps/wordpress/administration/enable-https-ssl-apache/
