### ISSUE TITLE
AWS Lightsail Wordpress website down

### ISSUE THREAD

**Issue by Bahirathan** [bitnami/vms#1411]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

pid 85033:tid 140709965260544]

### bndiagnostic output

![bndiag-Error2](https://github.com/bitnami/vms/assets/7188236/78ce6372-48ea-4486-8480-d44e8e704f13)
![bndiag-Error](https://github.com/bitnami/vms/assets/7188236/6e99f4d2-1803-4c70-a92b-f5a1b512716e)
![bitnami diagnostic](https://github.com/bitnami/vms/assets/7188236/82b1f5f3-37ac-4825-b68b-002a6d282d4d)

### bndiagnostic was not useful. Could you please tell us why?

it is too long to diagnostic

### Describe your issue as much as you can

I am using the AWS Lightsail Bitnami Wordpress instances  , my website is down more than 2 weeks , I contacted AWS support Engineers but they are unable to resolve the issue and asked me to contact Bitnami support team , I had attached the BndDiagnostic tool 's images , I am requesting you pls look into this issue and resolve 
![error log](https://github.com/bitnami/vms/assets/7188236/0e63df84-8e6a-4bfe-a099-94410f2e547a)

**Comment by Bahirathan** [comment]
![bndiag-Error](https://github.com/bitnami/vms/assets/7188236/29e967ae-b846-4614-824f-3dff403d005e)

**Comment by Bahirathan** [comment]
<img width="941" alt="bndTool Error1" src="https://github.com/bitnami/vms/assets/7188236/d9dfc49a-b9e8-4c80-ad5d-571905bd8345">

**Comment by Bahirathan** [comment]
please anyone to help me the error

**Comment by Bahirathan** [comment]
Hi Gonzalo , please help me to resolve the issue

**Comment by gongomgra** [comment]
Hi @Bahirathan,

Please run the bndiagnostic tool again and paste here the generated code so we can take a look at the collected information.
