### ISSUE TITLE
Bitnami Magento 2 - elasticsearch permissions structure?

### ISSUE THREAD

**Issue by rukcus** [bitnami/vms#1413]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

https://drive.google.com/file/d/1wrEfLF2w5K8WRIU5Zmh8EhRr-WYzvww7/view?usp=sharing

### bndiagnostic output

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

https://drive.google.com/file/d/1wrEfLF2w5K8WRIU5Zmh8EhRr-WYzvww7/view?usp=sharing

### Describe your issue as much as you can

So previously I accidentally recursively modified the permissions structure to my entire server by accident to the point I lost sudo, after unmounting the volume and fixing many permissions I regaining sudo as well as fixing many other permission related issues 

**_I have Sudo and the website working again_**. 

There is only one thing that doesn't start when I do the sudo /opt/bitnami/ctlscript.sh and that is elasticsearch I expect that the permissions are not correct once again but I tried to copy another known working magento bitnami installation but it doesn't seem to work.

**_BNDIAGNOSTIC TOOL UPLOAD_**

(https://drive.google.com/file/d/1wrEfLF2w5K8WRIU5Zmh8EhRr-WYzvww7/view?usp=sharing)

===== Begin of bndiagnostic tool output =====

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3885 2631 484 70 770 901 Swap:                              
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

Press [Enter] to continue:
You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Mariadb]

Some files don't have the expected permissions. Please check the following
guide:

https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Apache]

[Fri Feb 16 13:29:11.611220 2024] [proxy_fcgi:error] [pid 25903:tid
140141116860160] (104)Connection reset by peer: [client **ip_address**:41864]
AH01075: Error dispatching request to :
 [Fri Feb 16 13:29:14.013758 2024] [proxy:error] [pid 26688:tid 140141427390208]                              
(2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain
socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
Press [Enter] to continue:
 [Fri Feb 16 13:29:14.013846 2024] [proxy_fcgi:error] [pid 26688:tid
140141427390208] [client **ip_address**:51370] AH01079: failed to make
connection to backend: httpd-UDS

===== End of bndiagnostic tool output =====

**Comment by mdhont** [comment]
The following guide may be of help:

https://docs.bitnami.com/google/how-to/troubleshoot-permission-issues/
