### ISSUE TITLE
[Redmine] Getting error while installing plugins

### ISSUE THREAD

**Issue by hvaishnav** [bitnami/vms#1414]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

I dont have one.

### bndiagnostic was not useful. Could you please tell us why?

The documentation is not useful. 

### Describe your issue as much as you can

Hello everyone, 
  I want to highlight a issue that I am getting error while installing plugins on our "Bitname Redmine" (AWS EC2 linux instance).
  I am trying to install this plugin -
   https://www.redmine.org/plugins/redmine_contacts

 Server information : 
  AWS EC2 Debian 11
  Redmine version - 5.0
  Ruby version - 3.0

 Steps : 
 1. Connected to our Ec2
 2. Downloaded the zip file from url.
 3. Extracted the zip, uploaded it to my github repository.
 4. Went to path "/opt/bitnami/redmine/Plugins".
 5. Used command "Git clone github link". It is downloading the file from github to my "Plugins" folder.
 6. After step 6 used command - "bundle install". As soon as I hit enter to execute this command.
 7. I got the bunch of errors showing in the images below.
 8  After that my redmine website stopped working and shown 

![CRM plugin issue1](https://github.com/bitnami/vms/assets/38201417/9614fe14-2aad-40e6-8b1f-8adbde0ae3d2)
![CRM plugin issue2](https://github.com/bitnami/vms/assets/38201417/d902f90c-9129-4bd6-8f17-d3dde869a920)
![CRM plugin issue3](https://github.com/bitnami/vms/assets/38201417/f7b7bd53-ef8f-4a37-82e2-f3bd683a6e48)
![CRM Plugin issue 4](https://github.com/bitnami/vms/assets/38201417/0f925747-ef77-4cda-be08-ca25fb7fd74d)

I followed this installation docs- 
  1. https://docs.bitnami.com/virtual-machine/apps/redmine/configuration/install-plugins/
  2. https://www.redmineup.com/pages/help/crm/installing-crm-on-redmine-bitnami-stack

**Comment by jotamartos** [comment]
There is a similar ticket here, could you please take a look at it?

https://github.com/bitnami/vms/issues/955#issuecomment-1578253709

It seems you are running into a permissions issue and the chown command in that comment should fix it 

```
sudo chown -R bitnami:root /opt/bitnami/ruby/lib/ruby/gems/ /opt/bitnami/ruby/bin /opt/bitnami/redmine/db /opt/bitnami/redmine/log/production.log
```
