### ISSUE TITLE
Bitnami Wordpress Lightsail AWS

### ISSUE THREAD

**Issue by digitalmate1** [bitnami/vms#142]
### Describe your issue as much as you can

Hi there,
I am using wordpress on aws lightsail.

I would like to download the server logs due to an issue i have with a theme i am using.

Where can i find them?

Thank you in advance!

**Comment by mdhont** [comment]
Please check the following documentation:

https://docs.bitnami.com/ibm/infrastructure/lamp/get-started/understand-config/
https://docs.bitnami.com/general/apps/wordpress/
