### ISSUE TITLE
[ELK] Can´t run command line tools

### ISSUE THREAD

**Issue by jgastald** [bitnami/vms#1420]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

.

### bndiagnostic was not useful. Could you please tell us why?

just reported some conectivity problems (I´m behind a proxy)

### Describe your issue as much as you can

On a fresh ELK virtual machine, if you try to run some of the command line tools, like /opt/bitnami/bin/elasticsearch-setup-passwords (or elasticsearch-cli, elasticsearch-reset-password, etc) you get:

```
warning: ignoring JAVA_HOME=/opt/bitnami/java; using bundled JDK
/opt/bitnami/elasticsearch/bin/elasticsearch-cli: line 14: /opt/bitnami/elasticsearch/jdk/bin/java: No such file or directory

```

**Comment by mdhont** [comment]
I've reproduced the issue. Thank you for notifying us. We will update this thread with further information.

**Comment by mdhont** [comment]
> If the "stale" bot closes the issue, it means that it wont be solved?

That doesn't matter. I have linked the issue to the task so it will be tracked.

**Comment by jdclarke5** [comment]
I found that creating a symlink to point to the `JAVA_HOME` directory allows the command-line utility will work.

```sh
sudo ln -s /opt/bitnami/java /opt/bitnami/elasticsearch/jdk
```

**Comment by mdhont** [comment]
Thanks, that's good to know. I will add the information to the task.

**Comment by gongomgra** [comment]
Hi @jgastald, @jdclarke5,

Thanks for using Bitnami. We have released new cloud images for our ELK and Elasticsearch solutions with a fix for this issue. We are still in the process of releasing the virtual machine. We will keep you posted.
