### ISSUE TITLE
[WAMP] old computer crashed - how to rescue old mariadb content

### ISSUE THREAD

**Issue by wonny22** [bitnami/vms#1422]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

?

### bndiagnostic was not useful. Could you please tell us why?

bndiagnostic was not usable for my problem

### Describe your issue as much as you can

Hi, my old windows 10 computer crashed and I was just able to rescue the old wampstack-7.4.32 folder. I copied the old files to my new windows 11 computer and tried to start the Webserver, but it is not running any more. So I tried to find an upload of the old bitnami wampstack 7.4.32 version and realized, that this didn't exist any more. I tried to install locally a new xampp version and copied my mariadb content, but the tables are corrupted. So now I have no idea any more how to rescue my development for our small association. I don't know, whether this is a correct way to find help - but on the bitnami page, there is no possibility to find any help or contact. Is here someone who can give me tipps or some help? There exist anywhere a archive of old version for download? I'm really desperate. 
Best regards, Yvonne

**Comment by jotamartos** [comment]
I'm sorry to hear that. As you may know, support for our installers was removed some years ago. However, you can find some information regarding how to recover/migrate the installation to a new server here

https://github.com/bitnami/vms/issues/975#issuecomment-1584057737
