### ISSUE TITLE
[WordPress] AWS LightSail Pointing Domain to Instance using IPV6 "AAAA" Record

### ISSUE THREAD

**Issue by msnet9** [bitnami/vms#1423]
### Describe your issue as much as you can

Hi

When I login to my AWS account I see a notification stating if continue using IPV4 on an instance, the price will increase and thee is an option of using IPV6.

From my understanding IPV6 value can be placed on DNS zone of a domain and can point to the WordPress site for example as an "AAAA" record replacing IPV4 value as "A" record.

I therefor have placed the IPV6 on as "AAAA" on my domain DNS manager which is handled by "Microsoft 365" and I can see this resolved using online tools. But when trying to access the domain in browser nothing comes up of it does not go to WordPress site.

I have checked the Instance and if IPV^ is active, I have renewed it and used the new IPV6 and allowed for propagation time, but it does not work.

Am I missing something, or did not understand how it is spose to work. Could someone here help please, the date is very near and need to do this on few sites.

**Comment by markrids** [comment]
Hi there,
I had exactly this, with a Joomla install on LAMP blueprint.  It turned out my router had IPv6 disabled.  Once I enabled it, it all burst into life.
Definitely worth a look, but raises some questions about our ability to move to IPv6 if users need to fiddle with their routers.
Hope this helps,
Mark

**Comment by jotamartos** [comment]
Hi @msnet9,

As @markrids mentioned, you need a valid IPv6 connection to be able to access another IPv6, could you please confirm that? As I mentioned in the other thread, we will try to document this in the future to avoid confusion

https://github.com/bitnami/vms/issues/1431

Thanks
