### ISSUE TITLE
<bitnami-redmine-4.1.1.1-7-windows-x64-installer.exe>

### ISSUE THREAD

**Issue by OlegZaborej** [bitnami/vms#1424]
### Describe your issue as much as you can

Hello, may have a link to **bitnami-redmine-4.1.1.1-7-windows-x64-installer.exe**.
I can't find it anywhere, if you have it please send it to me

**Comment by mdhont** [comment]
You can download it here:

https://downloads.bitnami.com/files/stacks/redmine/4.1.1-7/bitnami-redmine-4.1.1-7-windows-x64-installer.exe

**Comment by mdhont** [comment]
The link should work now.

**Comment by OlegZaborej** [comment]
> Ссылка теперь должна работать.

thank you so much, god bless you good man )))
