### ISSUE TITLE
[WordPress] I am not able to download the database from https://127.0.0.1:8888/phpmyadmin/index.php

### ISSUE THREAD

**Issue by helpdeskshop** [bitnami/vms#1427]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

55183d08-c208-96d6-8ef3-90d5e20c6fa9

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Feb 28 22:13:52.177645 2024] [authz_core:error] [pid 17394:tid
140092832048896] [client **ip_address**:53028] AH01630: client denied by server
configuration: /opt/bitnami/apache/cgi-bin
 [Fri Mar 01 00:04:31.819756 2024] [authz_core:error] [pid 22696:tid
140093100615424] [client **ip_address**:55298] AH01630: client denied by server
Press [Enter] to continue:
configuration: /opt/bitnami/apache/cgi-bin
 [Fri Mar 01 12:39:12.976842 2024] [proxy_fcgi:error] [pid 30545:tid
140093847041792] [client **ip_address**:33264] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0'

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Wordpress]

Some files don't have the expected permissions Please check the following guide:

https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

[Resources]

Your instance has little available RAM memory.
```
Press [Enter] to continue:
 total used free shared buff/cache available Mem: 3946 2120 239 175 1587 1375
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I have retried with the suggestion but getting the same error

### Describe your issue as much as you can

Hi support team we are unable to export the database from phpmyadmin. Can you please help us to export it. We are getting the below error while we are trying to export the database.
We have proper internet connection & we have tried it many times but getting the same error. Can you please help us to resolve it?

![database](https://github.com/bitnami/vms/assets/161843040/f0bd7bf2-6c20-47c7-8464-98d76a51b71b)

**Comment by jotamartos** [comment]
Hi @helpdeskshop,

The Apache's log can provide more details about the error. However, we also suggest you take a look at this guide to know how to export/import data in WordPress so you can take a backup if needed

https://docs.bitnami.com/general/how-to/migrate-wordpress/

**Comment by helpdeskshop** [comment]
@jotamartos Can we export the database as well using this plugin?

**Comment by jotamartos** [comment]
Yes, I'll export all data from the application. You can learn more about it in its official website

https://wordpress.org/plugins/all-in-one-wp-migration/
