### ISSUE TITLE
[Wordpress] apache mariadb php-fpm stops running automatically

### ISSUE THREAD

**Issue by ankitmakati** [bitnami/vms#1432]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

54d6ee06-dd49-1b34-716f-26bcf3ef61fb

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ✓ Apache: No issues found
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Press [Enter] to continue:
Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Couldn't understand the issue from it's results.

### Describe your issue as much as you can

I have hosted WordPress website on AWS Lightsail. My website goes down automatically several times in a day. When I check the status of Apache, mariadb and php-fpm, the status shows NOT RUNNING.

Then I manually restart these services and the website starts working. I have to restart the services several times (5-8) times a day to keep my website up and running.

This is becoming really annoying and it will be very helpful if you can identify the issue. Please please help us.

bndiagnostic ID - 54d6ee06-dd49-1b34-716f-26bcf3ef61fb

Error logs are also attached here for your reference.

[Archive.zip](https://github.com/bitnami/vms/files/14485540/Archive.zip)

Thanks,
Ankit

**Comment by jotamartos** [comment]
There is a similar issue here, could you please take a look?

https://github.com/bitnami/vms/issues/1370

If you continue running into performance issues, we suggest you take a look at the log files or increase the resources of the VM where the application is running to check if that solves the issue.

**Comment by realtebo** [comment]
We have ~ weekly the same problem.

What should be the reason?
Are the services marked to auto-restart if the vps restart?
How to diagnose?

**Comment by jotamartos** [comment]
My previous message includes a link to a post that can help you debug the issue. Apart from that, you can also create a cron job that periodically checks the status of the services and start them if needed.
