### ISSUE TITLE
ssh service won't start

### ISSUE THREAD

**Issue by beefydog** [bitnami/vms#1433]
### Describe your issue as much as you can

I downloaded and installed the virtualbox appliance OVA "common-lampstack-8.3-8.3.30r1-debian-11-amd64" and it installed fine and the machine boots up.  The problem is that the ssh server service will not enable, even after telling it to start: (sudo service ssh start). When I check the status using (sudo systemctl status ssh), I get the following:
ssh.service - OpenBSD Secure Shell server
Loaded: loaded (/lib/systemd/system/ssh.service; enable; vendor preset: enabled)
Active: inactive (dead)
Condition: start condition failed at Tue 2024-03-05 01:06:07 UTC; 57s ago
             ConditionPathExists=!etc/ssh/sshd_not_to_be_run was not met
     
I'm guessing this has something to do with a private key? Are there non-cloud instructions on how to generate a private key compatible and how to configure?

**Comment by mdhont** [comment]
Did you enable SSH?

https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh/
