### ISSUE TITLE
virtual machine bitnami wordpress 

### ISSUE THREAD

**Issue by vinod117** [bitnami/vms#1437]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2104f1d7-66ed-96ed-37da-0fa4eeaa1b0f

### bndiagnostic output

connectivity: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

I was not able to find a way to solve my issue

### Describe your issue as much as you can

I'm using vm ware bitnami on my windows computer in the starting the wordpress application used to open but after a while it stopped working and shows that the site cant be reached i've tried all possible methods to resolve it, iv'e installed it twice and the same thing happend again can you please help me out with this

**Comment by gongomgra** [comment]
Hi @vinod117,

Thanks for using Bitnami. I checked the bnsupport bundle information and I couldn't find any errors there. According to it, Bitnami services are running and there are no errors in Apache log. Can you check if your issues are related to any of the installed plugins and/or the custom theme you are using?

**Comment by vinod117** [comment]
i'm not able to access the application through any broweser, how can i check that?

**Comment by vinod117** [comment]
Hi @gongomgra 

I deactivated all the plugins and changed the theme to default as well but still i'm not able to access the website

**Comment by gongomgra** [comment]
Hi @vinod117,

Can you double-check all services are running after disabling the plugins?

```
sudo /opt/bitnami/ctlscript.sh start
```

Can you run the bndiagnostic tool again and share the new code with us?

**Comment by vinod117** [comment]
8e78e0cf-1080-5af4-bad9-82093063c4e9
<img width="461" alt="Screenshot 2024-03-19 1215271" src="https://github.com/bitnami/vms/assets/156287928/635763d7-f0fc-4a2c-8258-0ca255ad1f42">

**Comment by gongomgra** [comment]
Hi @vinod117,

I checked the bndiagnostic bundle. I see the Bitnami service is not running. Can you run the next commands and share the output with us?

```
sudo ls -larth /var/run
sudo ls -larth /var/run/gonit
sudo ls -larth /etc
sudo ls -larth /etc/gonit
journalctl -u bitnami
```

Can you also try to start them?

```
sudo systemctl start
sudo gonit
```

**Comment by vinod117** [comment]
![Screenshot 2024-03-21 201621](https://github.com/bitnami/vms/assets/156287928/dcc7f504-ec78-45df-8f58-e0312781a352)
![Screenshot 2024-03-21 201555](https://github.com/bitnami/vms/assets/156287928/fba2faee-46c2-4fd2-a352-781e2156c53b)
![Screenshot 2024-03-21 201510](https://github.com/bitnami/vms/assets/156287928/e107fa6b-4d7d-4d5e-82e7-e6cd85b63954)
![Screenshot 2024-03-21 201419](https://github.com/bitnami/vms/assets/156287928/d97d9e70-4507-4268-b4d5-e1369ffb96aa)

**Comment by vinod117** [comment]
![Screenshot 2024-03-21 201838](https://github.com/bitnami/vms/assets/156287928/8ba298c0-da34-42e1-a793-9ddd72cc532b)
![Screenshot 2024-03-21 201827](https://github.com/bitnami/vms/assets/156287928/ba37a4d6-4d16-4d0b-b643-813897eef9e9)
![Screenshot 2024-03-21 201621](https://github.com/bitnami/vms/assets/156287928/cee9552b-b01f-4ed6-8fea-941a6c652186)
![Screenshot 2024-03-21 201555](https://github.com/bitnami/vms/assets/156287928/b1ea724d-51cd-4b31-8d4a-86baebb456cd)

**Comment by jotamartos** [comment]
Hi @vinod117,

@gongomgra posted several commands and I can't see the output of all of them here. Apart from that, some of the commands you posted do not include all the parameters @gongomgra mentioned (remember to include the dashes in the commands that use them or include "bitnami" when running the systemctl command)

**Comment by vinod117** [comment]
Hi @jotamartos 

here are the outputs
![Screenshot 2024-03-25 133329](https://github.com/bitnami/vms/assets/156287928/00423585-2acb-4582-ab01-65deb635150f)
![Screenshot 2024-03-25 133502](https://github.com/bitnami/vms/assets/156287928/9bca102d-4f93-4f41-8c30-55b00776dc64)
![Screenshot 2024-03-25 133541](https://github.com/bitnami/vms/assets/156287928/dd8d6a19-06e8-4bfa-b5b7-bc1c31509782)
![Screenshot 2024-03-25 133606](https://github.com/bitnami/vms/assets/156287928/169518aa-0fb9-43db-b195-fa89cd0ccf10)
![Screenshot 2024-03-25 133707](https://github.com/bitnami/vms/assets/156287928/ad8ae188-bc02-4a41-9d92-d3143a82ecf1)
![Screenshot 2024-03-25 133747](https://github.com/bitnami/vms/assets/156287928/ee8d258e-3dd5-49db-86fe-3f9a28e7542f)

**Comment by gongomgra** [comment]
Hi @vinod117,

Thanks for your message. It looks like the gonit service is not configured nor installed on your server. Do you have any error in the `/opt/bitnami/var/log/first-boot.log` file? You will need to use `sudo` to read the file content. Can you also check the rest of the logs files (Apache, MariaDB, PHP)? What happens if you run the command below?

```
curl -Li "http://127.0.0.1"
```

**Comment by vinod117** [comment]
![Screenshot 2024-04-04 180405](https://github.com/bitnami/vms/assets/156287928/088fdf9f-9278-46f6-ac3a-eda4c8791758)

**Comment by gongomgra** [comment]
Hi @vinod117,

Are the Bitnami services running on your server? Can you copy the command results instead of sharing a screenshot?

```
sudo /opt/bitnami/ctlscript.sh status
sudo /opt/bitnami/ctlscript.sh restart
tail -n 25 /opt/bitnami/apache/logs/error_log
sudo systemctl status bitnami
sudo journalctl -u bitnami | tail -n 50
```

Can you run the bndiagnostic tool again?
