### ISSUE TITLE
[Wordpress with NGINX And SSL] Process to enable framing 

### ISSUE THREAD

**Issue by shweta-dm** [bitnami/vms#1438]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

83cf5ebf-8711-270a-b000-1c64737ada2e

### bndiagnostic was not useful. Could you please tell us why?

Could not find the file

### Describe your issue as much as you can

Could you please let us know, which file should I modify to Enable Framing on my website? Thank you...

**Comment by shweta-dm** [comment]
Could you please share the document links?

**Comment by jotamartos** [comment]
We do not have any guide that explains how to do so. Please take a look at the WordPress' documentation and any other related guide online to achieve that. 

As I mentioned above, the WordPress' files are inside the /opt/bitnami/wordpress directory and the Apache-related files are inside the /opt/bitnami/apache/conf/vhosts folder.

**Comment by shweta-dm** [comment]
When we were on another hosting, Iframes were working, When we came to bitnami stack, iframes stopped working

**Comment by jotamartos** [comment]
As I mentioned above, you can enable iframe but changing the NGINX configuration inside the /opt/bitnami/nginx/conf/server-blocks folder. 

https://docs.nginx.com/nginx-management-suite/acm/how-to/policies/proxy-response-headers/
