### ISSUE TITLE
Bitnami GitLab Can't update, stretch Release does no longer have a release file

### ISSUE THREAD

**Issue by acidtonic** [bitnami/vms#1446]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9c0aec4d-e500-84f5-30dc-bab1eaeafdc2

### bndiagnostic output

    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Didn't do anything related to my issue

### Describe your issue as much as you can

I found the ssh daemon was way out of date and failing audit checks.

I went to update it with apt-get update, and I get these errors.

# apt-get update
Ign:1 http://archive.debian.org/debian stretch InRelease
Hit:2 http://archive.debian.org/debian stretch Release
Ign:3 https://packages.gitlab.com/gitlab/gitlab-ce/debian stretch InRelease
Hit:5 http://security.debian.org/debian-security stable-security/updates InRelease
Err:6 https://packages.gitlab.com/gitlab/gitlab-ce/debian stretch Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Reading package lists... Done
E: The repository 'https://packages.gitlab.com/gitlab/gitlab-ce/debian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

This machine has been upgraded a few times to the latest gitlab and everything works. I just want to update the ssh daemon, can you assist?

**Comment by acidtonic** [comment]
Anyone?

**Comment by mdhont** [comment]
As the issue is not related to Bitnami configuration I recommend asking in the official Gitlab forum. I found a similar issue here: https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/3500

I also recommend upgrading to the latest Bitnami Gitlab on Debian 12 and then restore the data there:

https://docs.gitlab.com/ee/administration/backup_restore/index.html
