### ISSUE TITLE
[bitnami redmine] Can I have the bitnami redmine 4.0.2-0 for windows server ?

### ISSUE THREAD

**Issue by fm12345jp** [bitnami/vms#1448]
### Describe your issue as much as you can

We are using bitnami redmine 4.0.2-0 for windows sever.
We would like to get the 4.0.2-0 package for the server migration.

Could you share us the link of the 4.0.2-0 package?

Thank you for your cooperation.

**Comment by gongomgra** [comment]
Hi @fm12345jp,

Thanks for using Bitnami. I'm afraid I could not find that version on our registries. The oldest one I have found is `4.1.0-8`. I'm sharing the download link below

```
http://downloads.bitnami.com/files/stacks/redmine/4.1.0-8/bitnami-redmine-4.1.0-8-windows-x64-installer.exe
```

hope it helps!

**Comment by fm12345jp** [comment]
Thank you for sharing the bitnami redmine package.  We will try to migrate redmine.
