### ISSUE TITLE
Bitnami on Azure increase Swap file size

### ISSUE THREAD

**Issue by SOKBattery** [bitnami/vms#1450]
### Describe your issue as much as you can

I am running a stack on Azure with 1GB Ram and the default swap file size. I am getting out of memory errors on occasion when the backup runs.
I used the run the server with 2GB RAM and even then I still experienced the occasional out of memory errors.
 I would like to increase the swapfile size, but cannot find any documentation of how to do this in the bitnami image. Can someone point me in the right direction

**Comment by jotamartos** [comment]
You can follow any online guide to modify the swap file or create a new one if needed

https://serverfault.com/questions/218122/how-do-i-increase-swap-memory-in-debian

Please note that if you increase the size of the current swap file (you can take a look at the /etc/fstab file to see where the swap file is), you will not need to create a new one.
