### ISSUE TITLE
[weblate] is there a Bitnami Stack for this app?

### ISSUE THREAD

**Issue by andregreeff** [bitnami/vms#1452]
searching the issues logged in this GitHub project, I do see a few questions relating to Weblate, but I cannot find it in the Bitnami Application Catalog.. did it exist at some point before being removed?

if so, could somebody perhaps share the reason for that decision?

if not, are there any plans to create an entry for this?

**Comment by andregreeff** [comment]
just for clarification searching Google directly for "bitnami weblate" does include a result for `https://bitnami.com/stack/weblate`, but navigating to that link then redirects to `https://bitnami.com/stacks/translation-tools` with a message that reads:

> Bitnami package for Weblate has been discontinued, here are similar apps in the same category.

but then you scroll down and there are no entries at all under the "Translation Tools" category.

**Comment by mdhont** [comment]
Unfortunately the Bitnami Weblate package has been deprecated a while ago.
