### ISSUE TITLE
[JupyterHub] Container timezone

### ISSUE THREAD

**Issue by KoenWindey** [bitnami/vms#1454]
### Describe your suggestion as much as you can

Hi,

Firstly, thanks for offering all these handy VMs.
I have recently started to use JupyterLab and am now looking to deploy Jupyter hub for our small team. So far so good, I even managed to get things going behind our reverse proxy.

I've been able to set the timezone on the VM OS (dpkg-reconfigure  tzdata did the trick). However, I cannot figure out how to get the timezone correct in the docker containers running the single-user servers. They seem to be in UTC and I cannot change it. I don't know sudo password for user jovyan (if it can even do sudo), nor do I know how to specify the parameter in the docker file -where is the docker file anyway?

It would be good if the docker containers adopted the VM timezone, or at least have it as an option?

Tnx
Koen

**Comment by jotamartos** [comment]
Hi @KoenWindey,

If you are launching a container, you can set the TZ env var to specify the timezone inside the container 

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1387

However, if you still run into this issue after that, I suggest you take a look at [other Jupyterhub and timezone issues](https://www.google.com/search?q=jupyterhub+timezone) or review the app's documentation to get more information about how to set the timezone to use.
