### ISSUE TITLE
php v7.4.15 still installing on new instances? 

### ISSUE THREAD

**Issue by dankings001** [bitnami/vms#1455]
### Name and Version

bitnami/aws

### What is the expected behavior?

I need PHP 8

### What do you see instead?
```
Last login: Tue Mar 19 15:33:29 2024 from 52.94.39.67
bitnami@ip-172-26-8-88:~$ php -v
PHP 7.4.15 (cli) (built: Feb 11 2021 08:25:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies
```

**Comment by jotamartos** [comment]
Most of the bitnami cloud images are now using PHP 8.x. What app are you deploying?

**Comment by dankings001** [comment]
I’m creating an instance, Amazon AWS Lightsail… Dan KingOn 21 Mar 2024, at 14:35, Juan José Martos ***@***.***> wrote:﻿
Most of the bitnami cloud images are now using PHP 8.x. What app are you deploying?

**Comment by jotamartos** [comment]
Could you please let us know which one you deployed? Please note that AWS Lightsail solutions are updated by the AWS team itself, we can't update them by our own. With this information, we will contact the team and ask them to update our solutions in the platform.

**Comment by dankings001** [comment]
Sorry I am not as technical?

When you say which one I deployed? I did 2 sites - instances - last week.. .both have PHP 7. 

Here’s one off them:





Thanks

Dan

**Comment by jotamartos** [comment]
> When you say which one I deployed? I did 2 sites - instances - last week.. .both have PHP 7.

It seems that the image you posted is now shown correctly. I just need the names of the VMs you launched to confirm this issue and report it to the AWS Lightsail team. 

Thanks

**Comment by dankings001** [comment]
Sorry I am not sure what a VM is? 

Where do I find that information?

Thanks,

Dan

**Comment by dankings001** [comment]
Hi Not sure what a VM is but recorded AWS: https://share.zight.com/6quX4vrz

Thanks

Dan

**Comment by jotamartos** [comment]
I just launched a fresh VM and it includes PHP 8.1

![Screenshot 2024-03-26 at 10 25 25](https://github.com/bitnami/vms/assets/8791635/1be236d2-616d-4427-91dc-bc55ae24b6ab)

You are using an old deployment. If you want to update the PHP version, you will need to migrate your data to a new instance

https://docs.bitnami.com/general/how-to/migrate-wordpress/

**Comment by dankings001** [comment]
Yes that’s what I did… I started 2 new instances, but got the 7. PhpDan KingOn 26 Mar 2024, at 09:26, Juan José Martos ***@***.***> wrote:﻿
I just launched a fresh VM and it includes PHP 8.1
Screenshot.2024-03-26.at.10.25.25.png (view on web)
You are using an old deployment. If you want to update the PHP version, you will need to migrate your data to a new instance
https://docs.bitnami.com/general/how-to/migrate-wordpress/

**Comment by jotamartos** [comment]
I'm sorry @dankings001 but I do not think you launched a new instance. I confirmed all WordPress and LAMP instances include PHP 8. You are using an old version of the solutions and you need to launch a new one and follow the guide I shared above. 

![Screenshot 2024-04-01 at 10 33 26](https://github.com/bitnami/vms/assets/8791635/db81af39-5486-403b-a683-fe285de4aedf)
