### ISSUE TITLE
[<Azure Nginx>] <Issue new domain SSL certificates>

### ISSUE THREAD

**Issue by Barnabas2** [bitnami/vms#1456]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

197b8c99-4727-1702-e0b9-ca4090a14d64

### bndiagnostic output

```
2024/03/19 18:33:59 [emerg] 1117#1117: cannot load certificate
"/opt/bitnami/nginx/conf/essexmonastery.co.uk.crt": BIO_new_file() failed (SSL:
error:02001002:system library:fopen:No such file or
directory:fopen('/opt/bitnami/nginx/conf/essexmonastery.co.uk.crt','r')
error:2006D080:BIO routines:BIO_new_file:no such file)
 2024/03/19 18:34:20 [emerg] 1202#1202: cannot load certificate
"/opt/bitnami/nginx/conf/essexmonastery.co.uk.crt": BIO_new_file() failed (SSL:
error:02001002:system library:fopen:No such file or
directory:fopen('/opt/bitnami/nginx/conf/essexmonastery.co.uk.crt','r')
error:2006D080:BIO routines:BIO_new_file:no such file)
 2024/03/19 18:34:51 [emerg] 1291#1291: cannot load certificate
"/opt/bitnami/nginx/conf/essexmonastery.co.uk.crt": BIO_new_file() failed (SSL:
error:02001002:system library:fopen:No such file or
directory:fopen('/opt/bitnami/nginx/conf/essexmonastery.co.uk.crt','r')
error:2006D080:BIO routines:BIO_new_file:no such file)

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

Press [Enter] to continue:

The Nginx configuration has errors:
```
nginx: [emerg] cannot load certificate
"/opt/bitnami/nginx/conf/essexmonastery.co.uk.crt": BIO_new_file() failed (SSL:
error:02001002:system library:fopen:No such file or
directory:fopen('/opt/bitnami/nginx/conf/essexmonastery.co.uk.crt','r')
error:2006D080:BIO routines:BIO_new_file:no such file) nginx: configuration file
/opt/bitnami/nginx/conf/nginx.conf test failed
```
Please check the configuration.

### bndiagnostic was not useful. Could you please tell us why?

It helped but I just don't know how to switch ssl certificates to point to a new domain 

### Describe your issue as much as you can

I cannot start nginx service . I get error: 

"Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)"

I tried creating a new ssl certificate to point to point from a .co.uk to a .com domain but I really don't know how to do it .

In the documentation here it doesn't mention how it is possible to perform such operation https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

The bndiagnostic tool helped me understand that it needed the old certificates in place in order to start nginx. So I restored the certificates and nginx is running. 

However, how can I replace those ssl certificates with a new domain certificates?

**Comment by Barnabas2** [comment]
I found the root cause of the problem located inside /opt/bitnami/nginx/conf/server_blocks/wordpress-https-server-block.conf where there were some lines pointing to the old certificates.

**Comment by jotamartos** [comment]
Great! Glad to hear you managed to solve the issue! :) 

For future reference, if you didn't modify the conf file before, server.crt and server.key will be replaced with the new certs in this step. You will need to update the conf file otherwise. 

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#step-3-configure-the-web-server-to-use-the-lets-encrypt-certificate

**Comment by Barnabas2** [comment]
Hello Jota,
Thank you for the reply. 
In the end I used the `bncert-tool` to generate the certificate and manually added the link to the domain certificate inside `/opt/bitnami/nginx/conf/server_blocks/wordpress-https-server-block.conf`.

To generate the certificate I used the YouTube tutorial at the end of this page https://docs.bitnami.com/aws/how-to/understand-bncert/

What I'm not sure how to do is how should I enable redirection from non www to www, as when running the bncert tool I get a warning saying `Warning: Support for the nginx web server is limited. This tool will only be able to generate HTTPS certificates and configure certificate renewal. It will not enable/disable redirections or apply other types of server configurations.`

**Comment by jotamartos** [comment]
As I mentioned above, you do not need to use bncert, you can follow the guide I posted to generate a certificate with the lego tool. You can later substitute the cert file you have or edit the conf file to point to the new certificate. 

Regarding the redirection, you can follow this other guide to force all requests to use the domain you want 

https://docs.bitnami.com/general/apps/wordpress-pro/administration/use-single-domain-nginx/

**Comment by Barnabas2** [comment]
I tried using lego in the first place but I get this error and I don't know how to solve it:

`bitnami@Bookshop:~$ sudo mv /opt/bitnami/nginx/conf/bitnami/certs/server.csr /opt/bitnami/nginx/conf/bitnami/certs/server.csr.old
mv: cannot stat '/opt/bitnami/nginx/conf/bitnami/certs/server.csr': No such file or directory`

**Comment by Barnabas2** [comment]
Also I get these errors when running the last two commands

```
bitnami@Bookshop:~$ sudo chown root:root /opt/bitnami/nginx/conf/bitnami/certs/server*
chown: cannot dereference '/opt/bitnami/nginx/conf/bitnami/certs/server.crt': No such file or directory
chown: cannot dereference '/opt/bitnami/nginx/conf/bitnami/certs/server.crt.old': No such file or directory
chown: cannot dereference '/opt/bitnami/nginx/conf/bitnami/certs/server.key': No such file or directory
chown: cannot dereference '/opt/bitnami/nginx/conf/bitnami/certs/server.key.old': No such file or directory
bitnami@Bookshop:~$ ^C
bitnami@Bookshop:~$ sudo chmod 600 /opt/bitnami/nginx/conf/bitnami/certs/server*
chmod: cannot operate on dangling symlink '/opt/bitnami/nginx/conf/bitnami/certs/server.crt'
chmod: cannot operate on dangling symlink '/opt/bitnami/nginx/conf/bitnami/certs/server.crt.old'
chmod: cannot operate on dangling symlink '/opt/bitnami/nginx/conf/bitnami/certs/server.key'
chmod: cannot operate on dangling symlink '/opt/bitnami/nginx/conf/bitnami/certs/server.key.old'

```

![image](https://github.com/bitnami/vms/assets/75849247/3cfdfddb-994c-4470-929d-b80860667f23)

**Comment by Barnabas2** [comment]
Also, according to this documentation: https://docs.bitnami.com/general/apps/wordpress-pro/administration/use-single-domain-nginx/ I should find the bitnami.conf file under opt/bitnami/nginx/conf/bitnami/ but this is all I see at that location:

![image](https://github.com/bitnami/vms/assets/75849247/52034a94-14d5-4de7-9ca3-c3bfb91e102d)

**Comment by jotamartos** [comment]
Hi @Barnabas2,

It seems you removed the default server.crt and server.key files from the server and that's why the commands do not work for you. If you set the new path to the certs in the conf file, that's enough and NGINX should start using it. 

Did the redirection changes work for you?

**Comment by Barnabas2** [comment]
Hello @jotamartos 

Regarding setting the new path to the certs in the conf file these are the 2 files I modified so that they point to the certificates ```
ssl_certificate      /opt/bitnami/letsencrypt/certificates/domain.crt;
ssl_certificate_key  /opt/bitnami/letsencrypt/certificates/domain.key;
```

![image](https://github.com/bitnami/vms/assets/75849247/2076bf26-4166-445f-ab89-c22f6464d975)

Now regarding the redirection, as I said above I cannot find any `bitnami.conf` file to edit according to the documentation https://docs.bitnami.com/general/apps/wordpress-pro/administration/use-single-domain-nginx/

**Comment by jotamartos** [comment]
>Now regarding the redirection, as I said above I cannot find any bitnami.conf file to edit according to the documentation https://docs.bitnami.com/general/apps/wordpress-pro/administration/use-single-domain-nginx/

You can edit the wordpress-server-block.conf and wordpress-https-server-block.conf files and include the information to redirect the requests to your domain.

**Comment by Barnabas2** [comment]
Thank you, Jota. That's all I wanted to confirm, that the names of the files I need to edit are the ones I edited. I managed in the end to do what I wanted.
