### ISSUE TITLE
[Odoo] Error when generating a new Let's Encrypt certificate through bncert-tool

### ISSUE THREAD

**Issue by valentierra** [bitnami/vms#1459]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ec78bafe-a69c-69fa-c09e-03d51a543e84

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ? Apache: Found possible issues
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1953 488 249 55 1215 1237 
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Connectivity]

Press [Enter] to continue:
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Mar 20 17:59:03.900190 2024] [proxy_http:error] [pid 8532:tid 
140072422659840] [client **ip_address**:31912] AH01114: HTTP: failed to make 
connection to backend: 127.0.0.1

[Wed Mar 20 17:59:04.116132 2024] [proxy:error] [pid 8532:tid 140072389089024] 
(111)Connection refused: AH00957: http: attempt to connect to 
**ip_address**:8069 (127.0.0.1:8069) failed

[Wed Mar 20 17:59:04.116168 2024] [proxy_http:error] [pid 8532:tid 
140072389089024] [client **ip_address**:62590] AH01114: HTTP: failed to make 
connection to backend: 127.0.0.1

```
Please check the following guide to troubleshoot server issues:
Press [Enter] to continue:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Getting an error for issuing a new certificate via bncert-tool

### Describe your issue as much as you can

Skipping deactivating of valid auth: 
https://acme-v02.api.letsencrypt.org/acme/authz-v3/327920137027
2024/03/20 17:46:40 [INFO] Deactivating auth: 
https://acme-v02.api.letsencrypt.org/acme/authz-v3/328621304047
2024/03/20 17:46:40 Could not obtain certificates:
        error: one or more domains had a problem:
[www.mydomain.xyz] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 
Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge

**Comment by valentierra** [comment]
After pausing Cloudflare, the Let's Encrypt cert was generated via bncert-tool without problem.

**Comment by gongomgra** [comment]
Hi @valentierra,

Thanks for using Bitnami. I'm glad you fixed your issue! We will close this ticket as solved.
