### ISSUE TITLE
[Prestashop] How to stop init scripts from changing database

### ISSUE THREAD

**Issue by eralha** [bitnami/vms#146]
### Describe your issue as much as you can

Hello,

First of all i want to say that i'm a new user to linux env and i still dont know many things, so i apologize for the naive question.

I'm currently setting up 3 server's (2 for website and 1 mysql) behind a ELB to handle high traffic store. My problem is that when i want to add a new EC2 instance(third or fourth instance) to the load balancer the bitnami init script's change the ps_shop_url and ps_configuration tables altering the shop url value.

The data base is common for all instances.

After some browsing in the /home/bitnami/stack/scripts folder i deleted the files: 
prestashop-env.sh
libprestashop.sh
mariadb-env.sh
libmariadb.sh

It seem's to me that the start of the server or a new instance is no longer changing values on the data base.

I now have 2 questions?
- is this the right way to achieve this or should i do something different?
- removing those files will break something else that i'm not seeing now?

Thanks in advance the stack is really good, very optimized and very easy to use, thank you.

**Comment by mdhont** [comment]
You can create the `.app_domain_disabled` to disable domain updates:

    sudo touch /opt/bitnami/.app_domain_disabled
