### ISSUE TITLE
[Wordpress] Version with php 7.4

### ISSUE THREAD

**Issue by crowninternet** [bitnami/vms#1461]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0bd1e183-414a-246f-2f9f-4cf9012c3d2f

### bndiagnostic was not useful. Could you please tell us why?

no relevant

### Describe your issue as much as you can

Is there a way to download a previous version of the bitnami stack with wordpress running9 php 7.4 - I have an older application that I need to upgrade, but need to get it working first on the older version of php before I can migrate it over. How can I get this to install on my host?
Thanks!
John

**Comment by jotamartos** [comment]
Hi @crowninternet,

I'm sorry but we removed support for the installers and removed old installers and VMs from our records. However, you can use the Bitnami WordPress container to run WordPress with PHP 7.4. Tag 5.9.2-debian-10-r26 was the last one with PHP 7.4. 

https://github.com/bitnami/containers/blob/e77bd69429003bd11ab0e840f695c16427ae9058/bitnami/wordpress/5/debian-10/Dockerfile
