### ISSUE TITLE
[<application>] Having issues with my Simple one page site, Very slow and continuously crashing

### ISSUE THREAD

**Issue by M2KEntertainment** [bitnami/vms#1462]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

25638a04-6556-ed0b-e1a2-030313d6fc6b

### bndiagnostic output

25638a04-6556-ed0b-e1a2-030313d6fc6b

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 950 546 79 131 324 115 Swap: 
634 115 519
```

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

[Mariadb]

Some files don't have the expected permissions. 

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Wed Mar 27 00:30:58.232778 2024] [proxy_fcgi:error] [pid 1139:tid 
140112981460736] [client **ip_address**:33723] AH01071: Got error 'PHP message: 
Unable to open /opt/bitnami/wordpress/wp-content/wflogs/ips.php for reading and 
Press [Enter] to continue:
writing.', referer: 
https://domainname.com/wp-admin/plugin-install.php?s=woopayment%2520custom&
tab=search&type=term

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Mar 27 00:03:06.318931 2024] [proxy_fcgi:error] [pid 55711:tid 
140404217145088] (104)Connection reset by peer: [client **ip_address**:51396] 
AH01075: Error dispatching request to : 
 [Wed Mar 27 00:03:06.318902 2024] [proxy_fcgi:error] [pid 55711:tid 
140404191966976] (104)Connection reset by peer: [client **ip_address**:37646] 
AH01075: Error dispatching request to : 
 [Wed Mar 27 00:30:10.877195 2024] [proxy_fcgi:error] [pid 1139:tid 
140113458390784] [client **ip_address**:49216] AH01071: Got error 'PHP message: 
Unable to open /opt/bitnami/wordpress/wp-content/wflogs/ips.php for reading and 
writing.'
Press [Enter] to continue:

### bndiagnostic was not useful. Could you please tell us why?

no information or help on how to fix the issues

### Describe your issue as much as you can

I strongly beleaive i have a configuration issue. I am running a lightweight one page website for a wedding invitation 

however is extramly slow and keeps crashing

**Comment by mdhont** [comment]
I recommend disabling all Wordpress plugins and check if that solves it. If so, enable them one by one to find the one that is causing the memory issues.

    wp plugin deactivate --all
