### ISSUE TITLE
[ERPNext] I cant install apps on any site created

### ISSUE THREAD

**Issue by shaekhsolomonpaakowkaitoo** [bitnami/vms#1464]
### Describe your issue as much as you can

Please I am not able to install any app on any site i create. I can use "bench get-app (app name) " to get the app but i cannot install it using " bench --site (sitename) install-app (appname)
I always get permission denied

below is a screenshot of the user for the erpnext directory

![permision](https://github.com/bitnami/vms/assets/13142910/c711ef3f-4cbf-4dcd-ba38-0bf15ef6b658)

And this is a fresh install of erpnext appliance in a virtualbox
I experience the same problem on AWS EC2 instance.
Any help would be much appreciated.

Thank you

**Comment by jotamartos** [comment]
There is an example about how to install a plugin in ERPNext here, could you please take a look at it?

https://github.com/bitnami/vms/issues/1180#issuecomment-1755621389

Thanks
