### ISSUE TITLE
Unable to access my server - server is not responding

### ISSUE THREAD

**Issue by paulso20** [bitnami/vms#1466]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

18f542c8-4500-67a7-980b-66bb0150b671

### bndiagnostic output

Unable to access my server - server is not responding

### bndiagnostic was not useful. Could you please tell us why?

Unable to access my server - server is not responding

### Describe your issue as much as you can

Unable to access my server - server is not responding

**Comment by paulso20** [comment]
hey guys, any luck seeing what my issue might be?  thanks alot

**Comment by paulso20** [comment]
Any news?

**Comment by mdhont** [comment]
Can you give more information? Do you mean you can't access the server using SSH? If you can access it could you share the amount of available RAM? 

```
free -h
```
