### ISSUE TITLE
[Lego] Additional Instructions needed to generate install lets-encrypt-ssl for Bitnami application host that are behind a load balancer

### ISSUE THREAD

**Issue by entxcode** [bitnami/vms#1467]
### Describe your issue as much as you can

Hi I have ZERO ERRORS: I have a standard LAMP bitnami intance in AWS LightSail with Apache Virtual Host pointing to subfolders in hdocs. 
Restated, I have:
1] a Bitnami LAMP Instance in AWS Lighsail behind a Load Balancer 
2] I have 4 Domains Successfully Pointing to the Bitnami LAMP Instance's dynamic public IPv6
3] Furthermore, I have succefully configured Apache Virtual Host for the 4 domains to point to subdirectory of hdocs

WHAT I NEED:
I am following the Alternative section "Generate A Let’s Encrypt Certificate For Your Domain" on bitnami's site >> https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/ and there's a sentence that states: "If the Bitnami application host is behind a load balancer or CDN, the commands below require additional parameters, which can be provided by the Bitnami support team on request."

Now since my bitnami Instance is behind a load balancer (but still accessibly via public IPv4 and IPv6), what "additional parameters" are needed to run in my ssh commands.

CONCLUSION:
After I have successfully recieve help, I will love to contribute to this community within the scope of Amazon Lightsail

**Comment by entxcode** [comment]
![letsencrypt](https://github.com/bitnami/vms/assets/21032493/7a73dbaf-99ce-486b-b60a-d32ae0158c4a)

I have included the section in bitnami that specifies to get additional Certificate generation parameters from bitnami in cases of behind load balancers

**Comment by jotamartos** [comment]
That depends on your configuration and the services you are using. You can take a look at the Lego's documentation to know more about the parameters the tool accepts

https://github.com/go-acme/lego

**Comment by munishrtf** [comment]
![image](https://github.com/user-attachments/assets/0e1f9fbf-af55-45ee-8999-315cabb0901a)

 The Bitnami application host is behind a load balancer  require some  additional parameters so may i know that in detail
i have hosted the Bitnami package for Mattermost Team on aws ec2 which is on private subnet and accessing through application load balancer so may i know the addition steps required for the encryption  of the cert

can

**Comment by entxcode** [comment]
Hi everyone this issue should have been closed we no longer use Bitnami

thank you so much.

**Comment by anuragnp97** [comment]
Can someone please provide the steps for this resolution? It would be helpful.

**Comment by jotamartos** [comment]
That depends on your configuration as I mentioned above. Please take a look at the lego documentation

https://github.com/bitnami/vms/issues/1467#issuecomment-2029542327
