### ISSUE TITLE
pimcore maintenance cron job has an error on invalid option

### ISSUE THREAD

**Issue by EliShklovsky** [bitnami/vms#1469]
### Name and Version

Bitnami package for Pimcore

### What architecture are you using?

None

### What steps will reproduce the bug?

pimcore maintenance cron job has an error on invalid option:
console.CRITICAL: Error thrown while running command "pimcore:maintenance --async --env=prod". Message: "The "--async" option does not exist

sudo nano /etc/cron.d/pimcore
This is the error line:
`*/5 * * * * daemon /opt/bitnami/php/bin/php /opt/bitnami/pimcore/bin/console pimcore:maintenance **--async** --env=prod >> /dev/null 2>&1`

This should be the line:

`*/5 * * * * daemon /opt/bitnami/php/bin/php /opt/bitnami/pimcore/bin/console pimcore:maintenance  --env=prod >> /dev/null 2>&1`

### Are you using any custom parameters or values?

/etc/cron.d/pimcore

### What do you see instead?

`*/5 * * * * daemon /opt/bitnami/php/bin/php /opt/bitnami/pimcore/bin/console pimcore:maintenance **--async** --env=prod >> /dev/null 2>&1`

**Comment by gongomgra** [comment]
Hi @EliShklovsky,

Thanks for reporting this issue. We will work on a fix and will update this thread once the new images are released. I'm adding the on-hold tag.

**Comment by gongomgra** [comment]
HI @EliShklovsky,

We have released new images of the Pimcore solution with the updated cronjob configuration. This is the new content of the `/etc/cron.d/pimcore` file after the machine initialization process.

```
$ cat /etc/cron.d/pimcore
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

*/5 * * * * daemon /opt/bitnami/php/bin/php /opt/bitnami/pimcore/bin/console pimcore:maintenance --env=prod >> /dev/null 2>&1
```
