### ISSUE TITLE
Opencart AWS version 3

### ISSUE THREAD

**Issue by harry503** [bitnami/vms#1472]
### Describe your issue as much as you can

How do i install the opencart version 3 in AWS EC2? instead of the currently only available to install version 4.

I need this particular version bitnami-opencart-3.0.3-8-57-r09

Im not ready for the PHP 8 for my currently running apps.

Thank you

**Comment by gongomgra** [comment]
Hi @harry503,

Thanks for using Bitnami. Unfortunately, those images are not available in EC2 anymore, and I'm afraid I don't know the reason why they were removed. As an alternative, you can use the Docker image from DockerHub

https://hub.docker.com/r/bitnami/opencart/tags?page=1&name=3.0.3-8

Hope it helps!
