### ISSUE TITLE
[MEAN] How to disable the httpd service? Can't find a clear answer in documentation (to be improved?)

### ISSUE THREAD

**Issue by pcwearingmedia** [bitnami/vms#1474]
### Describe your issue as much as you can

The /opt/bitnami/ctlscript.sh script does not provide a way of disabling the service httpd (start/stop/restart yes, but not completely disable).

I checked, and I'm running the Bitnami MEAN image on Debian, however, despite the service being httpd, the update-rc.d can't find the service.

ps output:
`/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf`

**Comment by grahamrodrigue** [comment]
To disable the httpd service in Bitnami’s MEAN Lightsail image on AWS, you can follow these steps:

Stop the service if it’s currently running:
sudo /opt/bitnami/ctlscript.sh stop apache

Disable the service from starting on boot:
sudo mv /opt/bitnami/apache/scripts/ctl.sh /opt/bitnami/apache/scripts/ctl.sh.disabled
sudo mv /etc/monit/conf.d/apache.conf /etc/monit/conf.d/apache.conf.disabled

This will prevent the Apache server from starting automatically. However, please note that these changes might affect other applications that depend on the Apache service. Always ensure to backup your configuration files before making such changes.

**Comment by jotamartos** [comment]
Hi @pcwearingmedia,

Sorry for the delay in getting back to you. If you want to disable Apache in your instance, you can follow the information in this guide.

https://github.com/bitnami/vms/issues/3#issue-1252563157

Please note that this other post talks about mariadb, but you can do the same with Apache. Let us know if you find any issue.

Thanks
