### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (111)

### ISSUE THREAD

**Issue by LuisArcos** [bitnami/vms#1475]
### Name and Version

bitnami-wordpress-5-9-3-26-r15-linux-debian-10-x86-64-nami

### What architecture are you using?

amd64

### What steps will reproduce the bug?

i use Bitnami on Google Cloud Plaform
 
My site http://34.95.233.109/ it's broken with the "Error establishing a database connection" message, when I connected through SSH `mysql -u root -p` using the VM credentials shows the following error:
```
ERROR 2002 (HY000): Can't connect to local server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (111)
```
Tried to restart the service with `sudo /opt/bitnami/ctlscript.sh restart mysql` but doesn't work. It shows "Failed to restart mariadb: Failed to restart mariadb"

### What do you see instead?
```
ERROR 2002 (HY000): Can't connect to local server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (111)
```

**Comment by gongomgra** [comment]
Hi @LuisArcos,

Can you run the bndiagnostic tool and share the generated code with us so we can take a look to the Bitnami services logs?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by LuisArcos** [comment]
The diagnostic bundle was uploaded successfully, here is the code:
32d814ff-2c3b-9860-b991-656104c9fbd1

**Comment by gongomgra** [comment]
Hi @LuisArcos,

Thanks for the info. According to the MariaDB logs, there is an issue with the MariaDB data and the service can't start. Did you perform any change in the server before getting this errors? We recommend you to create a server backup so you can easily restore the current state, and then look for help in a more specialized forums. Sorry for the inconveniences.
