### ISSUE TITLE
Bitnami White screen of death, apache and connectivity issues

### ISSUE THREAD

**Issue by BATTUTA96** [bitnami/vms#1477]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5afbefbc-631b-25e7-a21b-697cf045471c

### bndiagnostic output

    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ✓ Resources: No issues found
    ✓ Wordpress: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

It was a bit useful, I could fix only the Wordpress issues, but Apache and Connectivity, I followed step by step the guide but didn't fix it.

### Describe your issue as much as you can

Well, it was only just like a normal casual day browsing the website, where it suddenly appears the white screen of death, and wp-admin doesn't recognize my users anymore. 

<img width="1420" alt="scrn1" src="https://github.com/bitnami/vms/assets/166297134/1bf04b82-663d-48aa-981b-571c86d0bea2">
<img width="750" alt="scrn2" src="https://github.com/bitnami/vms/assets/166297134/3faa96c9-3917-419b-b980-a741f30a0ead">

**Comment by gongomgra** [comment]
Hi @BATTUTA96,

I visited your website and I see the next custom maintenance mode page. It looks like there are some issues in any of your customizations. Can you check them?

![Screenshot 2024-04-09 at 17 07 59](https://github.com/bitnami/vms/assets/6660452/6ab1aaca-1367-4664-b5fa-e6d7e3eca66e)

You may want to set the Apache `LogLevel` parameter to `debug` in the `/opt/bitnami/apache2/conf/httpd.conf` file to get more information on what are the error messages you are getting. You will need to restart the Apache service for changes to take effect. Also remember to set it back to `warn` level once you have debugged your issues, because it will make the Apache log file to grow rapidly, which can cause other issues like out of free space.

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

**Comment by BATTUTA96** [comment]
Hi @gongomgra 
Thank you for your response. I have tried to set it to debug, and restarted apache properly. But I couldn't see where would the error messages appear?

**Comment by gongomgra** [comment]
Hi @BATTUTA96,

Thanks for your message. The verbose Apache logs are written to the files under the `/opt/bitnami/apache2/logs` directory on your server. 

Regarding the SSH key errors, they are not related to the issues you are having with your web application. They are simply reflecting a connection failure to your server. 

Hope it helps!

**Comment by BATTUTA96** [comment]
Server and Wordpress Bitnami is back now, but with very slow loading. Is it GCP issue or Wordpress? 
<img width="1440" alt="Screen Shot 2024-04-16 at 2 04 38 PM" 
<img width="1440" alt="Screen Shot 2024-04-16 at 2 04 45 PM" src="https://github.com/bitnami/vms/assets/166297134/354f5264-8905-44fc-8b6a-bcbdf863fe90">
src="https://github.com/bitnami/vms/assets/166297134/280f8a9a-c56d-40b0-88c2-752693f0e8de">
<img width="1440" alt="Screen Shot 2024-04-16 at 2 04 45 PM" src="https://github.com/bitnami/vms/assets/166297134/3fe06929-e6e3-437e-abb2-f2a81844e331">
<img width="1440" alt="Screen Shot 2024-04-16 at 2 04 25 PM" src="https://github.com/bitnami/vms/assets/166297134/77b75e89-9180-46e8-8f13-98caec77022d">

**Comment by gongomgra** [comment]
Hi @BATTUTA96,

Thanks for your message. I think you can give a try to some optimizations via WordPress cache plugins

https://docs.bitnami.com/google/apps/wordpress/troubleshooting/optimize-bitnami-wordpress/

Additionally, we recommend you to ask in the official WordPress forums, where you can get help from WordPress developers and/or users with more experience in developing WordPress websites

https://wordpress.org/support/forums/
