### ISSUE TITLE
[EJBCA] Cannot access application on bitnami-ejbca-8.2.0-1-r95-debian-12-amd64

### ISSUE THREAD

**Issue by a1phatesters** [bitnami/vms#1479]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0000

### bndiagnostic was not useful. Could you please tell us why?

000

### Describe your issue as much as you can

The page to access EJBCA is inaccessible through the IP address

**Comment by jotamartos** [comment]
Hi @a1phatesters,

did you take a look at this similar ticket? 

https://github.com/bitnami/vms/issues/1195

Please let us know if you continue running into issues when accessing the app.
