### ISSUE TITLE
[WordPress] SSL Certificate Renewal open /opt/bitnami/letsencrypt/certificates/clay-law.com.crt: no such file or directory

### ISSUE THREAD

**Issue by claylaw** [bitnami/vms#148]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

dcde009e-32ad-458a-be1c-afae2f3bace1

### bndiagnostic output

? Connectivity: Found possible issues
    ? Processes: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Wordpress: No issues found

The Apache configuration has errors:
```
AH00526: Syntax error on line 50 of 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile: 
file '/opt/bitnami/apache2/conf/bitnami/certs/server.crt' does not exist or is 
empty

### bndiagnostic was not useful. Could you please tell us why?

I have no idea on how to correct the Apache configuration errors

### Describe your issue as much as you can

I have tried to manually revoke the Lets Encrypt SSL certificates and failed to do so. The Apache error is confusing to me as I have the bitnami installation directory is not present when using the bitnami cert tool. Please help, thanks.

**Comment by mdhont** [comment]
Please check the following guide to revoke an existing certificate:

https://docs.bitnami.com/aws/how-to/understand-bncert/#manually-revoking-an-existing-certificate
