### ISSUE TITLE
bncert-tool for Joomla does not support IPv6

### ISSUE THREAD

**Issue by jlibasci** [bitnami/vms#1480]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

NA

### bndiagnostic was not useful. Could you please tell us why?

Not applicable

### Describe your issue as much as you can

When using the bncert-tool for bitnami Joomla you get a message that IPv6 is not supported even after downloading the latest version.

With AWS increasing the price of static ip addresses this is an important feature to keep using bitnami.

This appears to be have addressed for the Wordpress version.

Cheers,
Jason

**Comment by gongomgra** [comment]
Hi @jlibasci,

Thanks for using Bitnami. The updated bncert tool with IPv6 support (version 2.0.0) should be available in all recent cloud images, not only for WordPress images. Can you tell us which AMI are you using? Is it an EC2 or Lightsail instance? What's the error message you are getting while running the tool? Can you also share the output of the commands below with us?

```
sudo ls -l /opt/bitnami/bncert-tool
sudo /opt/bitnami/bncert-tool --version
```

In case it is not version 2.0.0, can you install the latest version as mentioned in our guide and run it again?

https://docs.bitnami.com/aws/how-to/understand-bncert/

I have followed the steps in my own machine to verify it points to the expected 2.0.0 version.

```
$ wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/latest/bncert-linux-x64.run
$ chmod +x bncert-linux-x64.run
$ ./bncert-linux-x64.run --version
Bitnami HTTPS Configuration Tool 2.0.0 --- Built on 2024-03-06 11:06:57 IB: 23.1.0-202301121337
```
