### ISSUE TITLE
How Can I Obtain the Bitnami WordPress Stack?

### ISSUE THREAD

**Issue by rnatong1** [bitnami/vms#1481]
Last year, I utilized the Bitnami WordPress stack for a training exercise. However, I’ve found that the previous download link I used is no longer operational. The address of the former link is as follows:

https://downloads.bitnami.com/files/stacks/wordpress/5.9.1-0/bitnami-wordpress-5.9.1-0-linux-x64-installer.run

Could anyone provide insight into the whereabouts of this specific version or advise on how to access the current version of the Bitnami WordPress stack? I've come to rely on the ease of use and comprehensive features that the Bitnami stack offers, and I would greatly appreciate guidance on obtaining a new installer, or if there's an alternative recommended approach to deploying WordPress with Bitnami's tools in the current year.

**Comment by gongomgra** [comment]
Hi @rnatong1,

Thanks for your interest in using Bitnami. We stopped releasing our installers back in 2022. You can get more information on this in our blogpost linked below

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

As an alternative, you can use our [virtual-machines](https://bitnami.com/stack/wordpress/virtual-machine) (OVA format), our [Docker containers](https://github.com/bitnami/containers/tree/main/bitnami/wordpress), or [Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/wordpress). You will be able to find the tagged images for previous Docker images at https://hub.docker.com/r/bitnami/wordpress/tags

Hope it helps!

**Comment by rnatong1** [comment]
Dear @gongomgra 

Thank you for your response!
