### ISSUE TITLE
Bitnami LAMP: New php8.2.x instance running php7.x after /opt/bitnami restore from application-bin.tar.gz

### ISSUE THREAD

**Issue by chiemekailo** [bitnami/vms#1483]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9ad4e12e-fff5-fce9-5e25-2b522a0fb758

### bndiagnostic output

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Apr 12 07:02:44.239876 2024] [proxy_fcgi:error] [pid 12385:tid 
140146192152320] [client **ip_address**:48683] AH01071: Got error 'PHP message: 
PHP Notice: Undefined property: stdClass::$locked in 
/opt/bitnami/apps/joomla/htdocs/administrator/components/com_installer/tmpl/manag
e/default.php on line 160PHP message: PHP Notice: Undefined property: 
stdClass::$locked in 
/opt/bitnami/apps/joomla/htdocs/administrator/components/com_installer/tmpl/manag
Press [Enter] to continue:
e/default.php on line 160PHP message: PHP Not [Fri Apr 12 07:37:06.786703 2024] 
[proxy_fcgi:error] [pid 13956:tid 139621509875456] [client **ip_address**:60964] 
AH01071: Got error 'PHP message: PHP Warning: 
file_put_contents(/opt/bitnami/apps/webmailpro/htdocs/data/cache/templates-994f1c
e7eaa6c601ed6870b1046f010e.cache): failed to open stream: Permission denied in 
/opt/bitnami/apps/webmailpro/htdocs/system/Managers/Integrator.php on line 
184PHP message: PHP Warning: 
file_put_contents(/opt/bitnami/apps/webmailpro/htdocs/data/cache/langs-Eng [Fri 
Apr 12 08:36:23.967611 2024] [proxy_fcgi:error] [pid 15430:tid 139795774809856] 
[client **ip_address**:17175] AH01071: Got error 'PHP message: PHP Notice: 
Undefined index: VERSION in 
/opt/bitnami/apps/joomla/htdocs/libraries/src/Updater/Adapter/ExtensionAdapter.ph
p on line 133', referer: https://appcedar.net/administrator/index.php
```

### bndiagnostic was not useful. Could you please tell us why?

don't understand it

### Describe your issue as much as you can

I followed the backup guide [here](https://docs.bitnami.com/aws/apps/wordpress/administration/backup-restore/) and created a backup of my php7.x Bitnami lamp stack applications. Then I created a new php8.x instance and restored the backup (also backed up and restored the mariadb the same way).
Now when id `php -v` I get version `PHP 7.4.30 (cli) (built: Sep 10 2022 03:30:25) ( NTS )` instead of the `LAMP 8.2.16-0`

**Comment by jotamartos** [comment]
Hi @chiemekailo,

The guide you followed copies the entire installation directory (PHP binaries included) and moves it to the new instance. In this case, you are replacing all files in the new instance so you basically end up having the exact same installation. 

You need to follow this other guide to only migrate the WordPress data from the old instance to the new one

https://docs.bitnami.com/aws/how-to/migrate-wordpress/
