### ISSUE TITLE
[Drupal] Problem installing CiviCRM on a Bitnami Drupal 10 VM

### ISSUE THREAD

**Issue by jppecuchet4ahsmc** [bitnami/vms#1484]
### Describe your issue as much as you can

I have just launched a Bitnami Drupal 10 VM on Google Cloud and want now to install CiviCRM.
I can install SSL with /opt/bitnami/bncert-tool and the dupal site is running at https://test.ahsmc.fr/ 
All the instructions on https://docs.civicrm.org/installation/en/latest/drupal/ to "Install a translated CiviCRM" were successful up to the "cv core:install" command.
Following the documentation, I create a /var/www/test.ahsmc.fr directory and execute all the commands in this directory.
The problem appears at the last command :

cv core:install --cms-base-url="https://test.ahsmc.fr/" --db="mysql://root:XXXXX@localhost:3306/bitnami_civicrm" --lang="fr_FR" -vv

that gives

```
=================================
Box Requirements Checker
========================

> Using PHP 8.2.17
> PHP is using the following php.ini file:
  /opt/bitnami/php/lib/php.ini

> Checking Box requirements:
  .....

                                                                                                                
 [OK] Your system is ready to run the application.                                                              
                                                                                                                


In CmsBootstrap.php line 66:
                                      
  [Exception]                         
  Failed to parse or find a CMS null  
                                      

Exception trace:
  at phar:///usr/local/bin/cv/lib/src/CmsBootstrap.php:66
 Civi\Cv\CmsBootstrap->bootCms() at phar:///usr/local/bin/cv/lib/src/Util/BootTrait.php:100
 Civi\Cv\Command\CoreInstallCommand->_boot_cms_only() at phar:///usr/local/bin/cv/src/Util/SetupCommandTrait.php:22
 Civi\Cv\Command\CoreInstallCommand->bootSetupSubsystem() at phar:///usr/local/bin/cv/src/Command/CoreInstallCommand.php:47
 Civi\Cv\Command\CoreInstallCommand->execute() at phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php:127
 Cvphar\Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/cv/vendor/symfony/console/Application.php:637
 Cvphar\Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/cv/vendor/symfony/console/Application.php:190
 Cvphar\Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/cv/src/Application.php:67
 Civi\Cv\Application->doRun() at phar:///usr/local/bin/cv/vendor/symfony/console/Application.php:101
 Cvphar\Symfony\Component\Console\Application->run() at phar:///usr/local/bin/cv/src/Application.php:33
 Civi\Cv\Application::main() at phar:///usr/local/bin/cv/bin/cv:28
 require() at /usr/local/bin/cv:14
```

**Comment by jotamartos** [comment]
>Following the documentation, I create a /var/www/test.ahsmc.fr directory and execute all the commands in this directory.
The problem appears at the last command :

Please note that we do not use /var/www when installing the application, all Drupal files are inside the /opt/bitnami/drupal folder. Remember to use the "daemon" user when running the commands to not to break the permissions configuration.

**Comment by jppecuchet4ahsmc** [comment]
> > Following the documentation, I create a /var/www/test.ahsmc.fr directory and execute all the commands in this directory.
> > The problem appears at the last command :
> 
> Please note that we do not use /var/www when installing the application, all Drupal files are inside the /opt/bitnami/drupal folder. Remember to use the "daemon" user when running the commands to not to break the permissions configuration.

Fine. Replacing /var/www/test.ahsmc.fr by /opt/bitnami/drupal fixes the problem.
Great thanks.
