### ISSUE TITLE
[Apache Guacamole] <ALL connections start timing out after a week>

### ISSUE THREAD

**Issue by dpaceoffice** [bitnami/vms#1485]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ea8753f9-e110-61b6-9f04-1e9454814535

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ? Apache: Found possible issues

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Apr 14 04:32:32.010437 2024] [ssl:error] [pid 3162841:tid 140673634252544]
Press [Enter] to continue:
[client **ip_address**:37376] AH02042: rejecting client initiated renegotiation

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Suggested guides are not related to my issue

### Describe your issue as much as you can

After updating on march 4th, running guacamole version 1.5.4. After about a weeks time all connections, SSH and RDP, suddenly stop working and begin timing out. 

Simply running ./opt/bitnami/ctlscript restart resolves the problem.

Not sure what the root of the problem is however... Any insights?

**Comment by gongomgra** [comment]
Hi @dpaceoffice,

Thanks for using Bitnami. I have checked the bndiagnostic information that you shared and I don't see any error related to Apache Guacamole. However, the bndiagnostic tool don't retrieve any information out of the Guacamole logs. Can you check if there is any error related to your issue in the `/opt/bitnami/apache2/logs/guac_log` file?

I also see there are some settings available via the "settings" > "connections" > "new connection" > "protocol: SSH" web menu. I don't have any active connection at this time in my test server, but you can find there the "server keepalive interval" parameter, that I think can be of help. You can get more information on how to configure SSH, RDP and other protocols in the official docs. I'm sharing here the link to the SSH network parameters

https://guacamole.apache.org/doc/gug/configuring-guacamole.html#ssh-network-parameters

**Comment by gongomgra** [comment]
Hi @dpaceoffice,

Thanks for your message. I saw in the Guacamole docs that other protocols have similar parameters, but I'm afraid I don't know if that can be the solution or not. Can you try increasing the verbosity of Guacamole logs to `debug` to tru to get more information on the error? You have to replace the `level="info"` setting with `level="debug"` in the `/opt/bitnami/guacamole/webroot/WEB-INF/classes/logback.xml` file. After that, restart the service for changes to take effect

```
sudo /opt/bitnami/ctlscript.sh restart guacamole
```

Take into account that increasing the verbosity of the logs will make the Guacamole log file size to increase rapidly, which will consume more disk space and can cause other issues if you run out of it. We recommend you to restore the `level="info"` log level once you have reproduced the issue and checked the logs.

**Comment by acruzel** [comment]
Hi,
I reopen this issue because we faced it with the same version 1.5.4 installed on FreeBSD 14 :
```
# guacd -v
Guacamole proxy daemon (guacd) version 1.5.4
```
It seems that guacd doesn't close sockets correctly. When clients fails to connect with error "Connection refused" we find many opened socket on the server: 
```
# sockstat -46 -p4822 | grep guacd | grep -v '*:*' | wc -l | tr -d "\t"
1783
```
I found a (very) [old issue on Sourceforge](https://sourceforge.net/p/guacamole/discussion/1110833/thread/21845ab6/) that looks like to this.

Actually we made a simple script to restart guacd when too many socket are open:
```
 #!/bin/sh

NBCONN=$(sockstat -46 -p4822 | grep guacd | grep -v '*:*' | wc -l | xargs) 

if [ $NBCONN -gt 1024 ]
then
  echo "Heuuuu, y a beaucoup de connexions guacd ($NBCONN) !"
  service guacd restart
fi
```
