### ISSUE TITLE
redmine

### ISSUE THREAD

**Issue by ashrafalzyoud** [bitnami/vms#1486]
### Describe your issue as much as you can

Thank you for your cooperation
Is it possible to know if there is a difference in downloading the Redmine system on the Ubuntu server 22.0.4 or on the windowes server 2016 and downloading bitnami?
app bitnami support more than 500 users online?
its can change mysql database to sql server?
the Improving performance with bitnami or manual setup redmine ?

**Comment by gongomgra** [comment]
Hi @ashrafalzyoud,

Thanks for your interest in using Bitnami. We dropped native installers support [some time ago](https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html) in favor of our cloud native (cloud images, containers, and charts), and virtual-machines solutions, so there is no way to run Bitnami Redmine solution in Windows systems natively at this moment. Installing the individual items separately should be exactly the same as running our solutions, and the whole purpose why we put the components together is so you would not have to. Another of the advantages of Bitnami is that you can have more up-to-date components than those usually found in the system repositories.

Do not hesitate to try the new cloud-ready solutions (some of them can be tested locally, like the virtual-machine or the Docker containers), which you can later configure to use your remote MSSQL server as long as it is [officially supported](https://www.redmine.org/projects/redmine/wiki/redmineinstall) by the Redmine developers, and ask any other questions you may have.

You can get more information on the Bitnami Redmine stack in our website at https://bitnami.com/stack/redmine
