### ISSUE TITLE
[WordPress] white screen of death

### ISSUE THREAD

**Issue by bmilioli** [bitnami/vms#1487]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

6afc1af5-4904-061f-6691-3f4e769202c9

### bndiagnostic output

    ? Mysql: Found possible issues
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ? Resources: Found possible issues
    ✓ Php: No issues found
    ✓ Connectivity: No issues found

[Mysql]

Some files don't have the expected permissions. Please check the following
guide:

https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Apache]

### bndiagnostic was not useful. Could you please tell us why?

withe screen of death . 

### Describe your issue as much as you can

I am getting the withe screen of death . 
How can I fix it?

**Comment by jotamartos** [comment]
Hi @bmilioli,

I can see many errors in the Apache's log file, the tool warned you about them. Did you take a look?

```
[Mon Apr 15 17:24:36.824814 2024] [proxy_fcgi:error] [pid 27137:tid 139871171618560] [client 185.231.154.40:39626] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /opt/bitnami/apps/wordpress/htdocs/wp-config.php on line 103'
...
[Mon Apr 15 20:27:23.208679 2024] [proxy_fcgi:error] [pid 28225:tid 139870936704768] [client 79.124.59.254:60006] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: host in /opt/bitnami/apps/wordpress/htdocs/wp-includes/canonical.php on line 714PHP message: PHP Notice:  Undefined index: host in /opt/bitnami/apps/wordpress/htdocs/wp-includes/canonical.php on line 715PHP message: PHP Notice:  Undefined index: host in /opt/bitnami/apps/wordpress/htdocs/wp-includes/canonical.php on line 725PHP message: PHP Notice:  Undefined index: host in /opt/bitnami/apps/wordpress/htdocs/wp-includes/canonical.php on line 728'
[Mon Apr 15 20:49:37.925720 2024] [autoindex:error] [pid 28225:tid 139870743672576] [client 34.106.61.185:48158] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-includes/widgets/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options  directive, referer: DOMAIN.co
```

I do not know the changes you implemented recently, but you should review these errors. I suggest you check the WordPress' forums to get more information about the issues.
