### ISSUE TITLE
[Redmine] can't change permission for /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by mwdqaqc** [bitnami/vms#1488]
### Describe your issue as much as you can

![image](https://github.com/bitnami/vms/assets/74789498/3dc9c9b4-76a4-4fd5-b3af-5588f81a2b8b)

**Comment by mwdqaqc** [comment]
I am new to Linux.
Download bitnami-redmine-5.1.2-r95-debian-12-amd64.ova and set up VM. 
Change the password and try to follow https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh-password/

Edit the /etc/ssh/sshd_config and modify or add the following line:

  PasswordAuthentication yes

Try vi  /etc/ssh/sshd_config

chmod 777 /etc/ssh/sshd_config doesn't work.

Please advise!

**Comment by jotamartos** [comment]
Hi @mwdqaqc,

You need admin permissions to edit the file. To achieve that, you simply need to use "sudo" and the command line editor you use. For example:

```
sudo vi /etc/ssh/sshd_config 
```
