### ISSUE TITLE
Bitnami unable to resolve ip address timedout - unable to reach server on AWS

### ISSUE THREAD

**Issue by sparemetrix** [bitnami/vms#149]
### Describe your issue as much as you can
Website is down! Unable to launch new Bitnami stack from AWS - instances unreachable with following error: 
[  230.546789] bitnami[1834]: 2022-07-20T17:46:16.428Z - warn: Unable to resolve IP address using http://myip.bitnami.com connect ETIMEDOUT 50.17.235.25:80

**Comment by sparemetrix** [comment]
logged into server this morning at 9:38AM EST, checked running services and all were running 
website went down an hour after - system log shows that error - unable to resolve IP address 
I tried launching a new instance from AWS - same issue 
this happens with the nginx and the debian11 instance from the aws marketplace 

not sure what happened - site has been up and backups taken without issue 
was hoping to launch a new instance and restore from backup - thinking maybe a buggy instance at AWS, but after 3 attempts, I can't. they all fail with this same error 

not sure what to do 

Scrolling up in the logs - I also see that 80 and 443 are blocked? I never noticed that in the logs before - going to look at my security groups - they were open without issue - not sure why the log says that 
Not sure if any of this info helps you triage - I can send logs or whatever you need to help me with - apologies if the issue in github isn't placed correctly, I am very rusty with my github ettiquette

**Comment by sparemetrix** [comment]
[i-0764629656de2683d.log](https://github.com/bitnami/vms/files/9152816/i-0764629656de2683d.log)

**Comment by sparemetrix** [comment]
[i-008f6ac6d7a85709f.log](https://github.com/bitnami/vms/files/9152833/i-008f6ac6d7a85709f.log)

this log is for the nginx bitnami I just tried to launch which is also unreachable

**Comment by DarkFiberMines** [comment]
> [i-008f6ac6d7a85709f.log](https://github.com/bitnami/vms/files/9152833/i-008f6ac6d7a85709f.log)
> 
> this log is for the nginx bitnami I just tried to launch which is also unreachable

I am having this same issue today. Server is unresponsive but is running the same way it has always been. No changes have been made on our side. Any idea what it may be or did you resolve it anyway?

**Comment by sparemetrix** [comment]
> > [i-008f6ac6d7a85709f.log](https://github.com/bitnami/vms/files/9152833/i-008f6ac6d7a85709f.log)
> > this log is for the nginx bitnami I just tried to launch which is also unreachable
> 
> I am having this same issue today. Server is unresponsive but is running the same way it has always been. No changes have been made on our side. Any idea what it may be or did you resolve it anyway?

Nope 

I tried launching new instance stacks - same thing everytime 
I was able to get one stood up in AWS US EAST 2 just now and am trying to connect to it with SSH and the server is rejecting - so just when I think I get a little bit closer to restoring my site - I am still up against a wall 

Something changed somewhere - I have plenty of backups to restore from - if I could only get a server to respond with bitnami and wordpress so I can restore!

**Comment by sparemetrix** [comment]
Issue opened 9 hours ago 
ecommerce site has been down 
no reply from support or triage 
mitigation - attempted to launch new instances, trying different flavors of bitnami wordpress with medium instances, much more memory and more disk space - all have the same unresponsive problems. 
Extremely frustrated. 
Going to be a late night - if anyone has suggestions on how to resolve - please let me know.

**Comment by DarkFiberMines** [comment]
I am work

> Issue opened 9 hours ago ecommerce site has been down no reply from support or triage mitigation - attempted to launch new instances, trying different flavors of bitnami wordpress with medium instances, much more memory and more disk space - all have the same unresponsive problems. Extremely frustrated. Going to be a late night - if anyone has suggestions on how to resolve - please let me know.

I am working on this as well everything seems like its working normally, security groups all in place yet the site is still unreachable. Doesn't make any sense we didn't change anything. I suspect SSL issues thats really all I can think of at the moment. If I figure it out I will post. No response from support yet unfortunately.

**Comment by sparemetrix** [comment]
WEBSITE IS STILL DOWN!   https://gre6.com/

Nothing works! 
Can't even stand up a new instance with bitnami using all instructions - it fails.

**Comment by mdhont** [comment]
Please contact AWS support. It does not seem related to the Bitnami configuration of your instance.
