### ISSUE TITLE
Bitnami Wordpress GCP CE - Updated SSL cert and now access to website is down and redirect to 127.0.0.1

### ISSUE THREAD

**Issue by mcampos009** [bitnami/vms#1492]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

26d7f5f8-e9d9-bbe6-b68f-39bd3cba637c

### bndiagnostic output

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Apr 19 00:19:32.955696 2024] [proxy_fcgi:error] [pid 2948779:tid 
140234507384576] [client **ip_address**:54277] AH01071: Got error 'PHP message: 
PHP Notice: PHP Request Startup: file created in the system's temporary 
directory in Unknown on line 0', referer: 
https://104.196.37.98/wp-admin/post.php?post=565&action=edit
Press [Enter] to continue:
 [Fri Apr 19 01:08:47.108718 2024] [authz_core:error] [pid 1136:tid 
140411566995200] [client **ip_address**:44692] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
 [Fri Apr 19 01:48:18.316348 2024] [authz_core:error] [pid 2293:tid 
140461729638144] [client **ip_address**:51308] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 978 536 81 53 360 227 Swap: 
634 75 558
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

### bndiagnostic was not useful. Could you please tell us why?

it was but the suggestions did not work

### Describe your issue as much as you can

Website was working perfect and went to update the SSL cert with Bntool.  It was successful then all of a sudden the website was down and when i try and connect, the browser immediately goes to 127.0.0.1.  No other changes were made to DNS or VM.

**Comment by mcampos009** [comment]
Hey @gongomgra Would you be able to assist me on this?  It's a pretty serious issue that I'd love to get some help on.

Thank you!

**Comment by gongomgra** [comment]
Hi @mcampos009,

Thanks for using Bitnami. I have just visited your website and everything looks fine: HTTP to HTTPS redirection worked, and the SSL certificate was issued by Let's Encrypt. Did you manage to fix your issue?
