### ISSUE TITLE
[ProcessMaker] Connection to Maria DB on process maker ver.4

### ISSUE THREAD

**Issue by erezaen** [bitnami/vms#1493]
### Describe your issue as much as you can

dear Friends
I want to connect to MariaDB On process maker with Navi cat.
Is it possible?

**Comment by jotamartos** [comment]
Hi @erezaen,

Thank you for your interest. I'm afraid we can't help you with this request, ProcessMaker is no longer in our catalog and we can't provide you with the information you are looking for. 

If you have a Bitnami MariaDB database, you can create a new database user and database by following this guide 

https://docs.bitnami.com/general/infrastructure/mariadb/configuration/create-database-mariadb/

You will later need to configure the application with those new credentials. Please take a look at the app's documentation to get more information.

**Comment by diana658h** [comment]
Hello, This link is helpful or not please tell me I rella need this info...

**Comment by erezaen** [comment]
> Hi @erezaen,
> 
> Thank you for your interest. I'm afraid we can't help you with this request, ProcessMaker is no longer in our catalog and we can't provide you with the information you are looking for.
> 
> If you have a Bitnami MariaDB database, you can create a new database user and database by following this guide
> 
> https://docs.bitnami.com/general/infrastructure/mariadb/configuration/create-database-mariadb/
> 
> You will later need to configure the application with those new credentials. Please take a look at the app's documentation to get more information.

Many thanks for your efforts.

**Comment by erezaen** [comment]
> diana658h

Dear Diana
 I want connect to MariaDB With Navicat,
this link (https://docs.bitnami.com/general/infrastructure/mariadb/configuration/create-database-mariadb/);
helps to create database in command mode on Linux.
Regards.
