### ISSUE TITLE
[bitnami redmine] Can I have the bitnami redmine 4.1.1-8 for windows server ?

### ISSUE THREAD

**Issue by AbirHossainDevOps** [bitnami/vms#1494]
### Describe your issue as much as you can

We are using bitnami redmine 4.1.1-8 for windows sever.
We would like to get the 4.1.1-8 package for the server migration.

Could you share us the link of the 4.1.1-8 package?

Thank you for your cooperation.

**Comment by gongomgra** [comment]
Hi @AbirHossainDevOps,

Thanks for using Bitnami. We dropped support of our installers solutions in [November 2022](https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html) to focus on our cloud native solutions. As an alternative, we recommend you to use our Bitnami Redmine container image from dockerhub.

https://hub.docker.com/r/bitnami/redmine/tags?page=&page_size=&ordering=&name=4.1.1

**Comment by AbirHossainDevOps** [comment]
I understand. However we require the windows installer of Redmine 4.1.1-8 urgently as our Redmine is in production. We can not make the change quickly. Could you please provide me with installer? We need this specific version asap.

**Comment by gongomgra** [comment]
Hi @AbirHossainDevOps,

I checked the version that you requested was released before our deprecation, so I have found the installer you requested in our archive. Please find the download link below

https://downloads.bitnami.com/files/stacks/redmine/4.1.1-8/bitnami-redmine-4.1.1-8-windows-x64-installer.exe

**Comment by AbirHossainDevOps** [comment]
Hi @gongomgra the link seems to not working.

**Comment by gongomgra** [comment]
Hi @AbirHossainDevOps,

Thanks for your message. Let me check it with the rest of the team

**Comment by gongomgra** [comment]
Hi @AbirHossainDevOps,

We could not recover the `4.1.1-8` installer but we recovered the `4.1.1-7`. Please find below the download link

https://downloads.bitnami.com/files/stacks/redmine/4.1.1-7/bitnami-redmine-4.1.1-7-windows-x64-installer.exe

**Comment by AbirHossainDevOps** [comment]
Hello @gongomgra, Thanks for your support. Since version 4.1.1-8 is not available, then is it possible you can any later version which uses mysql at sql engine? Like something from version 4.2 if possible. We do not want to downgrade while having minimal changes.

**Comment by gongomgra** [comment]
@AbirHossainDevOps,

For Redmine 4.2 we only have available the OVA for version `4.2.5-7`. I'm afraid we can't recover legacy installers. Please consider using the containers as mentioned in a previous message, where you can find more versions available in the dockerhub

https://downloads.bitnami.com/files/stacks/redmine/4.2.5-7/bitnami-redmine-4.2.5-7-r01-linux-debian-10-x86_64-nami.ova

Regarding MySQL and MariaDB, you should be able to replace one database engine with the other one without major issues, as both of them are officially supported by the Redmine developers. Please refer to the official docs on how to migrate the data and apply the required changes (if any).
