### ISSUE TITLE
AWS LAMP Server getting slow

### ISSUE THREAD

**Issue by vasundharak** [bitnami/vms#1497]
### Describe your issue as much as you can

Hi,
Our domain expired after which we are facing 524 cloudflare error a lot. There is one IP address with 1100 requests but not sure whether it is a bot attack or not.
![image](https://github.com/bitnami/vms/assets/29419992/dcd9ef9c-6cd8-4b45-bf5d-3c156488635d)

**Comment by gongomgra** [comment]
Hi @vasundharak,

Thanks for using Bitnami. Please check our guide on how to deny connections from bots/attackers using Apache linked below. Beware of not removing your own access, nor blocking the machine's own IP address by mistake.

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/

If your domain has expired (I understand you mean the DNS registry), the website should be accessible again once you renew it pointing it back to your server's IP address.

**Comment by Alexsmith311** [comment]
Hey, Can we use LAMP Server to Run WordPress or PHP [website](https://nsfasstatuscheck.net.za/) and show our work to clients as a portfolio. I don't want to invest on domains and hosting. Thanks
