### ISSUE TITLE
[Dolibarr] - Unable to connect to Dolibarr VM

### ISSUE THREAD

**Issue by JoCriSem** [bitnami/vms#1498]
### Describe your issue as much as you can

[Mac OS 14.4.1] - diagnostic code = 18b0114d-9834-b017-2968-adf451074296
Created a new appliance in VirtualBox using the ova file and all worked well.  Configured Dolibarr and created templates, invoices, contacts, etc.
Shutdown Mac for the weekend and restarted again this morning (Monday).  VM startup fine, but unable to connect to IP address with server not responding.  (connecting to http://192.168.0.227/admin/facture.php)

(also, there is no ifconfig on the system and "sudo apt install ifconfig" returns "Unable to locate package ifconfig" )

**Comment by JoCriSem** [comment]
![image](https://github.com/bitnami/vms/assets/32733182/70955c1b-2444-4866-a634-8735bbe73f7a)

**Comment by jotamartos** [comment]
Hi @JoCriSem,

Please access the command line in the VM and run the following commands

```
sudo /opt/bitnami/ctlscript.sh status
curl -LI localhost
sudo ifconfig
```

Thanks

**Comment by JoCriSem** [comment]
![image](https://github.com/bitnami/vms/assets/32733182/62c274b8-367f-4fc2-ab9e-e9b26b81b145)


Seems like the ifconfig command no longer exists and is replaced by the ip-command.
In doing this I noticed that the IP address is 198.168.0.229 and NOT  198.168.0.227 as mentioned in the startup window

**Comment by JoCriSem** [comment]
For me it works now.  If you have a reason why this changed, please let me know, otherwise you may close this issue

**Comment by jotamartos** [comment]
>In doing this I noticed that the IP address is 198.168.0.229 and NOT 198.168.0.227 as mentioned in the startup window

The startup window is generated at deployment time. If the IP changed (due to a reboot and the old IP probably being already assigned in your network), the startup window won't be updated and you will need to use the new one to connect to the machine.

I'm closing the ticket now. Thanks!
