### ISSUE TITLE
Bitnami Google Cloud not working after changing CPU from e2 Micro to N2

### ISSUE THREAD

**Issue by Lance-NZ** [bitnami/vms#1507]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b9ad84b6-d27a-c6ca-bdc3-1a8094878d80

### bndiagnostic output

[Nginx]

Press [Enter] to continue:
Found recent error or warning messages in the Nginx error log.
```
2024/04/22 05:27:40 [error] 794#794: *1 FastCGI sent in stderr: "PHP message: 
PHP Notice:  PHP Request Startup: file created in the system's temporary 
directory in Unknown on line 0" while reading response header from upstream, 
client: **ip_address**, server: _, request: "POST /wp-admin/async-upload.php 
HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"34.87.203.225", referrer: "http://34.87.203.225/wp-admin/upload.php"

2024/04/22 05:29:17 [error] 794#794: *16 recv() failed (104: Connection reset by 
peer) while reading response header from upstream, client: **ip_address**, 
server: _, request: "POST /wp-admin/async-upload.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "34.87.203.225", 
referrer: "http://34.87.203.225/wp-admin/upload.php"

2024/04/22 08:13:03 [error] 3698#3698: open() "/opt/bitnami/nginx/tmp/nginx.pid" 
failed (2: No such file or directory)
```

### bndiagnostic was not useful. Could you please tell us why?

Not sure what to do with this info, lol

### Describe your issue as much as you can

I changed Cpu from e2 Micro to N2 have I also put in a DNS PTR, I have removed the PTR and I did try to change the cpu back to e2 micro but that hasn't worked, I also did increase disk space becuase it was running out of storage.

Any help would be appreciate I'm not developer, just trying to avoid having to redo everything lol.

Cheers

**Comment by Lance-NZ** [comment]
Update I just got an email about my plugins updating automatically for the site but its a different IP address? my instance still says it has the same internal and external IP?

**Comment by Lance-NZ** [comment]
Have edited sudo nano /etc/hosts, I must have done it wrong site still not up.

**Comment by gongomgra** [comment]
Hi @Lance-NZ,

Thanks for using Bitnami. These are the only errors I see in your bndiagnostic bundle. 

```
2024/04/22 05:29:17 [error] 794#794: *16 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: CLIENT_IP, server: _, request: "POST /wp-admin/async-upload.php HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "YOUR_IP", referrer: "http://YOUR_IP/wp-admin/upload.php"
2024/04/22 08:13:03 [notice] 3698#3698: signal process started
2024/04/22 08:13:03 [error] 3698#3698: open() "/opt/bitnami/nginx/tmp/nginx.pid" failed (2: No such file or directory)
```

I think your server is taking so long to process the requests. Can you try to restart the services?

```
sudo /opt/bitnami/ctlscript.sh restart
```

These issues may be related to your plugins or the custom theme you have installed. We recommend you to disable all plugins using the [wp-cli too](https://developer.wordpress.org/cli/commands/plugin/deactivate/), and then restart the services again. If you get access to the website after that, then it means that one of the plugins are breaking your website

```
wp-cli deactivate --all
```

Regarding the `/etc/hosts` file, I'm not sure of which changes you did, but in principle it shouldn't be needed to edit that file.
