### ISSUE TITLE
[WordPress] Bitnami nginx - how to configure access to wp-admin for whitelisted IP addresses

### ISSUE THREAD

**Issue by Torwald45** [bitnami/vms#1508]
### Describe your issue as much as you can

I tried adding such a block (instead of xxx.xxx.xxx.xxx I provided my own IP address): 

```
location ~ ^/(wp-admin|wp-login\.php) {
                allow xxx.xxx.xxx.xxx;
                deny all;
  }
```

sequentially to files:

/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf

/opt/bitnami/nginx/conf/nginx.conf

This causes a server error every time and you can't access the site.

Where to add this block to make it work?

**Comment by Torwald45** [comment]
Ok, I figured out how to do it differently - using Basic Auth. Steps:

1. Edit file:
`sudo nano /opt/bitnami/nginx/conf/server_blocks/wordpress-https-server-block.conf`

2. In block `Server {` add:

```
# BASIC-Authentication
location ~* /wp-login.php|/wp-admin/.*\.php$ {
     auth_basic "basic authentication";
     auth_basic_user_file "/bitnami/wordpress/.htpasswd";
     fastcgi_pass unix:/opt/bitnami/php/var/run/www.sock;
     fastcgi_index index.php;
     include fastcgi_params;
     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
     fastcgi_param PATH_INFO $fastcgi_path_info;
     fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
}
# end BASIC-Authentication
```

3. Restart server:
`sudo /opt/bitnami/ctlscript.sh restart`

4. Install:
`sudo apt-get install apache2-utils`

5. Create:
`htpasswd -c /bitnami/wordpress/.htpasswd YOUR-USER`
This command will create access for YOUR-USER, you will need to provide a password.

6. Test your-application/wp-admin

**Comment by jotamartos** [comment]
Thanks for posting the information here, it'll be really helpful for others in the same situation.

Have a good week!

**Comment by BrandyN11** [comment]
To restrict access to your WordPress admin area by IP address, you should create a separate configuration file for the IP block and include it in your NGINX server block. Here’s how you can do it:

1. Create IP Block File: Make a new file, say `blocked_ips.conf`, and add your `allow` and `deny` directives there.
2. Include in Server Block: Include this file in your `/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf` by adding the line `include /path/to/blocked_ips.conf`; within the `server block`.

This method helps to keep your configurations organized and avoids errors related to direct edits in the main NGINX configuration files. Remember to replace `/path/to/` with the actual path where your `blocked_ips.conf` file is located.
