### ISSUE TITLE
Bitnami On Compute Engine - Maria DB not starting

### ISSUE THREAD

**Issue by vivagifts** [bitnami/vms#1509]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

78baf2f5-5ca9-56c8-aaf5-20c220dc9689

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Php: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Connectivity: Found possible issues
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Apr 28 09:28:20.626280 2024] [proxy_fcgi:error] [pid 6501:tid 
139817132148416] [client **ip_address**:49586] AH01071: Got error 'PHP message: 
PHP Warning: touch(): Utime failed: Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
529; PHP message: PHP Warning: chmod(): Operation not permitted in 
Press [Enter] to continue:
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173'
 [Sun Apr 28 09:29:06.804096 2024] [authz_core:error] [pid 6501:tid 
139817023043264] [client **ip_address**:40704] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
 [Sun Apr 28 09:29:06.804376 2024] [authz_core:error] [pid 6501:tid 
139817023043264] [client **ip_address**:40704] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2024-04-27 8:10:21 27 [Warning] Aborted connection 27 to db: 'bitnami_wordpress' 
user: 'priyanshu_vivagifts' host: 'localhost' (Got an error writing 
communication packets)

Press [Enter] to continue:
```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-mariadb/

Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

unable to start mariadb after multiple attempts

### Describe your issue as much as you can

Everything was working fine all of sudden site went down and after checking multiple times, I found that mariadb is not starting, increased the system configuration also but nothing helped.

**Comment by gongomgra** [comment]
Hi @vivagifts,

Thanks for using Bitnami. I reviewed the bndiagnostic bundle and I see all services are up and running

```
-----------------------------------
Get the ctlscript status
-----------------------------------
Running: ./ctlscript.sh status
In: /opt/bitnami

Output:

apache already running
mariadb already running
php-fpm already running
```

I also visited your website and it seems to be working fine. Did you manage to solve your issue? Regarding the MariaDB warning messages in the log, I noticed you are not using the default database user, but that should not be the issue here. We recommend you to ask in a more specialized forum about this. According to the bndiagnostic data your server is not running out of free disk space nor free memory.

**Comment by robert2003b** [comment]
MariaDB uses option files like my.cnf to read configuration options. If MariaDB isn’t starting, it’s possible that there’s an invalid option or value in the option file. You can check which configuration options MariaDB will use with the command mariadbd --print-defaults.
