### ISSUE TITLE
[Joomla] Documentation seems to be very out of date

### ISSUE THREAD

**Issue by nccerhostmaster** [bitnami/vms#151]
Has the documentation site been deprecated? If so it should be labeled as such. If not, it really needs some work. 
I keep finding references to features that don't work in docs that were updated recently. Search results point to pages that seem to no longer exist. 

Looking for information on changing the hostname on a Bitnami instance of Joomla, I found several links to documentation, but none of them were accurate. One referred to using bnconfig, but bnconfig no longer exists. The closest i found to a useful note was in a wordpress related community post which mentioned there's now a new way to make this change. 

Am I supposed to assume that Bitnami no longer provides special tools for this purpose? Woiuld be nice to have some guidance.

**Comment by mdhont** [comment]
What are you trying to do exactly? It should not be needed to change the hostname for the application to work.

**Comment by nccerhostmaster** [comment]
I've since encountered more, similar problems with the documentation not showing current, accurate information. 
I've had multiple recent issues, and in each case, every time I tried to find useful information, I found that the docs.bitnami.com site had either nothing, or old, out-of-date information. 

Here is one example of several I've recently encountered...(Please note that this is just one single example of several, this appears to be a systemic issue with the site)

I need to change the hostname of a VM. The reason for needing to change it is irrelevant. Consider it to be a mandatory requirement handed down from on high. 

I attempt the obvious method of using hostnamectl, but this doesn't work. 
```
sudo hostnamectl set-hostname myhost
Failed to connect to bus: No such file or directory

```
After Googling this error, I find several references to Bitnami images missing dbus components, so I give up on this approach, as it appears to be deliberately broken. 

I know that Bitnami images often make changes to the standard configuration and location of files, so my next step is to consult the website docs.bitnami.com

The first result I find on the docs site for changing hostname is this:
https://docs.bitnami.com/virtual-machine/faq/configuration/use-bnconfig/
This article explains how to change the hostname using the bnconfig command. 

However when I try to use this command, it's not available on my instance. 

Searching for bnconfig with the search feature on docs.bitnami.com, the first article I see is this: 
https://docs.bitnami.com/general/faq/configuration/understand-bnconfig/

So I search for bnconfig missing, and it again points me to the same two articles. 

Trying to do a Google search, I find mostly results pointing to the now destroyed community site. 

By narrowing the Google search to just the docs.bitnami.com site, I'm able to find a few references, but they're all either to using bnconfig, or in a few cases, renaming bnconfig to bnconfig.disabled. I can't find anything specifically saying that bnconfig is just removed, and no longer available. 

Finally, after extensive searching, I found one reference to bnconfig no longer existing on github, here. 
https://github.com/bitnami/vms/issues/41

Removal of this tool does not appear to be documented anywhere on the docs site, nor is there anything I can find on the site that explains why it was removed, what to use instead, and so forth. A vague reference to the old vs new directory structure seems to be the only explanation. 



My questions:
1. Is docs.bitnami.com the correct place to find current, up-to-date information about Bitnami instances and how to use them?
2. If not, what's the correct place?
3. If so, why are many significant changes completely unmentioned in the documentation site? 
4. Since the community was destroyed and the docs page is no help, and the github issues are not useful, where do I go for current, accurate, up-to-date information about the commands needed to administer a bitnami instance?

**Comment by nccerhostmaster** [comment]
Another example of outdated documentation being referenced can be found in this issue. 
https://github.com/bitnami/vms/issues/193
In that case, the poster is referred to the bnconfig documentation, but that documentation is not relevant for newly created Wordpress instances, because they don't have that command.

**Comment by gongomgra** [comment]
Hi @nccerhostmaster,

Yes, you can continue looking for help in our documentation site, it is the official source of documentation for our assets.

`bnconfig` is a tool only included in our installers (old and news) and in old versions of our cloud images and virtual machines only. That information is published in our documentation site for compatibility with old versions of our assets. With recent assets, you should follow the steps in the `Approach A` section. Regarding the specific guide you mention, please notice the recommended command is not the `bnconfig` tool, but the `/opt/bitnami/configure_app_domain` in case it exists. In the specific case of Joomla that should not be necessary, and therefore the `configure_app_domain` may not be present.

Apart from that, notice either `configure_app_domain` or `bnconfig` tools will configure the application domain, not the machine name itself (what you get with `hostnamectl`). If it is not present on your machine, you can try the `hostname` command instead, or update the `/etc/hostname` file.

Our cloud images and virtual machines were updated some time ago with major changes, like removing the bnconfig tool. You can get more information on this from the next guide

https://docs.bitnami.com/virtual-machine/faq/get-started/understand-upcoming-changes/
