### ISSUE TITLE
HELP! Bitnami login for WP site is not recognized.

### ISSUE THREAD

**Issue by kt7815** [bitnami/vms#1510]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

### bndiagnostic was not useful. Could you please tell us why?

I can not find anything related to my issue.

### Describe your issue as much as you can

Hi there, I created a Wordpress website via Bitnami and Virtual Box. I was in the process of migrating it over to wp-engine and I added my email username and password in the site settings. When I logged out and tried to log back in, it says it does not recognize the Bitnami username, my new username or my email. It doesn't recognize anything, and now I am stuck and can't get into my site. Please help. I spoke to wp-engine and they said that the username and password might be able to be edited through the database through the SSH. I'm not sure what that means. If you can provide any guidance on how to get access back to my site.

Thanks so much!

**Comment by kt7815** [comment]
Hi @gongomgra is there any advice you can give to help me on this one?? Thanks!

**Comment by gongomgra** [comment]
Hi @kt7815,

Thanks for using Bitnami. I don't fully understand how did you add your username and password. Can you elaborate it a bit? How did you migrate the WordPress data to your WP Engine site? We have a guide on this that should migrate all the application data to the new instance, including the administrator credentials.

https://docs.bitnami.com/aws/how-to/migrate-wordpress/

Apart from that, we don't know how WP Engine instances work, so we can provide you with help on how to SSH connect to those instances. You will need to ask the WP Engine team for help on this.

**Comment by kt7815** [comment]
Hi thanks so much for your reply. The problem is all within Bitnami login. Forget I mentioned the migration. I’m just trying to get back into my site through Bitnami. When I was logged into Wordpress using the generated bitnami username and password I updated the Wordpress settings in the dashboard. Now when I try to log back in using bitnami it doesn’t not recognize the generated user or password or the email I changed in the backend of the website. 

Is there a way to get back into my Wordpress through Bitnami if it does not accept the username or password? Can I edit the credentials through the SSH?

**Comment by kt7815** [comment]
Hi @gongomgra 

Thanks so much for your reply. The problem is all within Bitnami login. Forget I mentioned the migration. I’m just trying to get back into my site through Bitnami. When I was logged into Wordpress using the generated bitnami username and password I updated the Wordpress settings in the dashboard. Now when I try to log back in using bitnami it doesn’t not recognize the generated user or password or the email I changed in the backend of the website.

Is there a way to get back into my Wordpress through Bitnami if it does not accept the username or password? Can I edit the credentials through the SSH?

**Comment by kt7815** [comment]
@gongomgra I used Virtual Box to open the Bitnami .ova. Just need to get back into Wordpress site but generated username: user and password a2hxgulwf:j5 is not working anymore.

http://192.186.18.227/
username: user
password: A2hxguLwf:j5

**Comment by gongomgra** [comment]
Hi @kt7815,

Because you are using the OVA in your local machine, you can directly update the WordPress administrator password in the OVA command line. Updating the password from the admin panel website requires you to finish the update process clicking a link in the email it is send. However, you need to have the SMTP settings configured, which are not configured by default. I think this is the issue you are facing, that the update password process has not been finished.
 
You can get the database admin password from the OVA command line by running the next command

```
cat /home/bitnami/bitnami_credentials
```

Once you have it, you can update the admin password in the database by following the tutorial below

https://docs.bitnami.com/virtual-machine/apps/wordpress/administration/reset-wp-admin-password/

Hope it helps!
