### ISSUE TITLE
[SuiteCRM] no error logs in any PHP based image

### ISSUE THREAD

**Issue by kale1d0code** [bitnami/vms#1513]
### Describe your issue as much as you can

PHP based images do not generate error messages,

no logs can be found in /opt/bitnami/php/var/log (documented https://docs.bitnami.com/aws/infrastructure/harbor/troubleshooting/debug-errors-php-fpm/)
stdout (preferred) contains no error information.

DEBUG and BITNAMI_DEBUG environment variables are ineffective.

unable to diagnose issues for PHP based applications using bitnami images.
please advise

**Comment by jotamartos** [comment]
Hi @kale1d0code,

Are you talking about the Bitnami VMs? If there is any error in the PHP-FPM's log file, you will see it at /opt/bitnami/php/var/log/php-fpm.log. You can take a look at this related thread in the past

https://github.com/bitnami/vms/issues/1318

You should also check the Apache's log file to see if there is any error there.

**Comment by Lorena783lopez** [comment]
wow it is very helpful [HP® Store](https://www.hpinstantink-hp.com) information for me nice.

**Comment by MarkK112** [comment]
For PHP-based Bitnami images not generating error messages, check the Apache’s log file for errors and ensure that `display_errors` is set to `1` in the `php.ini` file. If issues persist, consider seeking help on the Bitnami community forums or GitHub issues page.
