### ISSUE TITLE
Older Bitnami Wordpress Stacks

### ISSUE THREAD

**Issue by gschelk** [bitnami/vms#1516]
### Describe your issue as much as you can

We have a really old Bitnami Wordpress instance, the stack is BitNami Wordpress 3.4.2-1. I have been tasked with upgrading it to a new stack (6.2.0-r11) so we can gain some functionality and get into something more recent. I have been trying to update the PHP but have been unable to find a way to accomplish this.  We downloaded a more recent stack (6.2.0-r11) and attempted to perform a migration using WP - All in One Transfer plugin but due to the difference in stack levels we were unable to get it up and functional. 

Support told me to upgrade PHP and run updates on plugins and re-try the migration. Since I have been unable to upgrade PHP I was wondering if there is a way to get some of the Bitnami Wordpress stacks in between the levels stated ablove and perform a few steps to complete the migration? Is anyone aware of where I could find any of these intermediate stack levels or is there a way to update PHP that I have not found yet?

Thanks for any assistance,

**Comment by gongomgra** [comment]
Hi @gschelk,

Thanks for using Bitnami. Updating PHP version in our installations as an individual component is not possible. We have also deprecated local installers, and we don't have access to old versions. We recommend you to use our container images with previous versions of WordPress and PHP. You can check all the available tags in Dockerhub

https://hub.docker.com/r/bitnami/wordpress/tags

**Comment by robert2001b** [comment]
Upgrading PHP in a Bitnami WordPress stack can be a bit tricky, especially when dealing with older versions. Use the plugin to export your current WordPress installation from the old Bitnami stack (version 3.4.2-1). Launch a new Bitnami WordPress instance with the desired PHP version (6.2.0-r11).  Install the same plugin on the new instance and import the backup you created earlier. erify that everything works as expected on the new instance.

**Comment by gschelk** [comment]
I had a case open with All-In-One Wordpress Backup and they were able to get to restore by disabling a handful of plugins but the default theme also had to be disabled in order to get it to restore. With the default theme disabled they were unable to get the site to load. They instructed me to Update PHP and then update the plugins and then create a fresh backup and perform the restore. This is how I got here with attempting to update PHP.

**Comment by gongomgra** [comment]
Hi @gschelk,

As mentioned in my previous message, updating individual components in a Bitnami installation is not possible. We recommend you to use as many intermediate tags from our Dockerhub history as needed.
