### ISSUE TITLE
[Wordpress] SSH key rejected after launching new instances

### ISSUE THREAD

**Issue by onlinemnn** [bitnami/vms#1518]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

I cannot access the instance therefore cannot run diagnostic 

### bndiagnostic output

I cannot access the instance therefore cannot run diagnostic 

### bndiagnostic was not useful. Could you please tell us why?

I cannot access the instance therefore cannot run diagnostic 

### Describe your issue as much as you can

When launching a new Bitnami Wordpress Instance on AWS, whether it’s create new key pair or use existing, ssh access to instance is rejected, putty saying “No supported authentication methods available (server sent: publickey)

I’ve tried different AWS accounts, tried new key and existing key in instance launch stage, i’ve tried an older version of the AMI. Simply cannot access the instance by SSH

steps to reproduce:
1. launch new bitnami wordpress certified by bitnami and automattic instance on AWS
2. try to connect to instance via SSH

**Comment by jotamartos** [comment]
>try to connect to instance via SSH

Did you follow these instructions to connect to the instance? 

https://docs.bitnami.com/aws/faq/get-started/connect-ssh/

Please remember you need to use the "bitnami" user when connecting.

**Comment by onlinemnn** [comment]
yes, connecting the correct way as described in guide and using bitnami as username

**Comment by onlinemnn** [comment]
issue resolved, updated putty to latest version and no problems now
