### ISSUE TITLE
[Moodle] How to upgrade from PHP 7.3 to PHP 8

### ISSUE THREAD

**Issue by jmalmsten-panopto** [bitnami/vms#152]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic output

N/A

### bndiagnostic was not useful. Could you please tell us why?

N/A

### Describe your issue as much as you can

Hi,

My company uses several Moodle EC2s to test our Moodle integration plugins. With the recent support for PHP 8.0 with Moodle 3.11 and Moodle 4.0 we have customer's migrating to PHP 8 and we need to be able to support that. 

I am unable to find a set of instructions to upgrade PHP in the bitnami ec2, I see the /opt/bitnami/php directory but I don't know how to upgrade that using the version of php 8.1 I am getting using "sudo apt install php8.1". 

Do you know if Bitnami is planning to release versions of moodle 3.11 and Moodle 4.0 with php 8 installed or could you please provide a link (or steps) on how to upgrade PHP myself? 

I understand from #36 that you tell people upgrading components is not possible, but I really need to test support on PHP 8 asap. 

Edit: I am assuming the latest EC2s still use PHP 7.4 based on https://bitnami.com/stack/moodle/README.txt

Thanks,
Joe Malmsten

**Comment by jotamartos** [comment]
>I am unable to find a set of instructions to upgrade PHP in the bitnami ec2, I see the /opt/bitnami/php directory but I don't know how to upgrade that using the version of php 8.1 I am getting using "sudo apt install php8.1".

You can't update the Bitnami packages using `apt`, we do not use the system's packages when building the solution, we build them from scratch.

>Do you know if Bitnami is planning to release versions of moodle 3.11 and Moodle 4.0 with php 8 installed or could you please provide a link (or steps) on how to upgrade PHP myself?

We are currently including PHP 7.4 and we do not have any Moodle version with PHP 8.1. If you want to use that version, you can launch the latest Bitnami LAMP solution with PHP 8.1 and deploy Moodle on top of it

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

**Comment by jmalmsten-panopto** [comment]
Ahh I see, I figured that was the case so building it from scratch was my next plan. I downloaded the PHP source and was going to compile it myself, then replace the current PHP version with it.

**Comment by jmalmsten-panopto** [comment]
https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/ 

Hi I am following the steps provided, but on the latest version of the LAMP stack there is no bitnami-apps-prefix.conf file as listed in the steps and shown in the video. 

Do you have updated steps for this part of the workflow?

**Comment by jotamartos** [comment]
If you are using the latest version of the Bitnami LAMP solution in AWS, you will need to follow the "Approach A", not the "Approach B". Please take that into account

**Comment by jmalmsten-panopto** [comment]
I got approach B to work, it just required the extra step I described. 

However it looks like the LAMP stack provided uses PHP 8.1.8 which Moodle does not support, is there a way to use an older version of the AMI that has PHP 8.0?

**Comment by jmalmsten-panopto** [comment]
Ok, I got Moodle fully installed and working using https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/ with the LAMP stack 8.0.2 and approach B. Limiting people to approach A doesn't really work if we are using these AMIs for development purposes. 

In-case you want to update your docs you are only missing a few steps for approach B to work on newer AMIs.

1. Change `Add the following line to the end of the /opt/bitnami/apache2/conf/bitnami/bitnami-apps-prefix.conf file:`
to
`Create /opt/bitnami/apache2/conf/bitnami/bitnami-apps-prefix.conf if it does not exist. Add the following line to the end of the /opt/bitnami/apache2/conf/bitnami/bitnami-apps-prefix.conf file:`

2. Add the following line to /opt/bitnami/apache2/conf/bitnami/bitnami.conf, after the ErrorDocument 503 /503.html line.
`Include /opt/bitnami/apps/myapp/conf/bitnami-apps-prefix.conf`

3. Add the following line to /opt/bitnami/apache2/conf/bitnami/bitnami-ssl.conf, after the ErrorDocument 503 /503.html line.
`Include /opt/bitnami/apps/myapp/conf/bitnami-apps-prefix.conf`

4. run `sudo apachectl restart`
