### ISSUE TITLE
[<Bitnami-ERPNEXT>] <Unable to access>

### ISSUE THREAD

**Issue by hemantkumar50** [bitnami/vms#1521]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Unable to access

### bndiagnostic was not useful. Could you please tell us why?

Unable to access

### Describe your issue as much as you can

Hello Team,

Please find the below screenshot, i am not able to access the application through Virtualbox. I get the IP but when i type in i am not able to access. i was able to access for few times.

**Comment by gongomgra** [comment]
Hi @hemantkumar50,

Thanks for using Bitnami. Can you give us more information about your issue? Did you modify anything in the virtual machine before facing these errors?

Can you share the screenshot you mentioned in your message? I don't see any image there, sorry. Additionally, please run the bndiagnostic tool with `sudo` privileges and share the generated code with us, so we can try to help you debug your issue.

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by robert2001b** [comment]
Ensure that your VirtualBox VM network settings are configured correctly. If you’re using NAT, try switching to a Bridged Adapter or Host-Only Networking to see if that resolves the issue. Sometimes, restarting the network services on both the host and the guest can help establish a proper connection. Check the firewall settings on both the host and the guest to make sure the necessary ports are open for communication. If you need the VM to be accessible from the host machine but not from the external network, setting up a host-only network might be the solution.

**Comment by robert2003b** [comment]
Check the firewall settings on both the host and guest operating systems. The firewall on the host may be blocking the connection to the VM. You might need to create an inbound rule to allow traffic to and from the VM’s IP address.
