### ISSUE TITLE
[bitnami/odoo] Windows crash when I try to connect to my Odoo access IP on browser

### ISSUE THREAD

**Issue by Elensito** [bitnami/vms#1522]
### Name and Version

common-odoo-17-17.0.20240405-r0-debian-12-amd64

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When I try to access for the first time to my Odoo via IP windows instantly crashes, and I don't have idea why, I already used the Odoo app before on a different computer,  but I didn't had that problem.

### What do you see instead?

I saw the BSoD of Windows the first 2-3 attempts, my last attempt directly my computed restarted instantly.

**Comment by gongomgra** [comment]
Hi @Elensito,

Thanks for using Bitnami. Did you download the VM from our website? The file shouldn't be named that way but `bitnami-odoo-17.0.20240405-r0-debian-12-amd64`. Which hypervisor are you using? Can you download the file from our website and try again? Can you also tell us if your Windows machine has enough resources to run the Odoo VM? Does the VM initialization process start before you get the BSOD?

https://bitnami.com/stack/odoo/virtual-machine
