### ISSUE TITLE
[Redmine] The service of Redmine sometimes don't run after starting by automation

### ISSUE THREAD

**Issue by YHitoshi** [bitnami/vms#1523]
### Describe your issue as much as you can

I have made the VM that is included Bitnami package for Redmine from marketplace.
Continuously them, I have set to start the VM by PowerShell in automation.
The starting of VM have worked, but it is happened to the problem that service of Redmine haven't started a few time in a half year. The problem is solved by the VM restart, I would like to know what it is the reason about the problem, also I need what to do.

thanks 

regards.

**Comment by jotamartos** [comment]
Thanks for using Bitnami.

You will need to troubleshoot this by getting the status of the bitnami service and monit after starting the VM. Please note that monit and the services can take some time to be up and running

```
sudo service bitnami status
sudo /opt/bitnami/ctlscript.sh status
sudo monit status
```

**Comment by YHitoshi** [comment]
Thank you for replying.

I would like to make sure your comment.  I need the below command type when the issued happened again.
Am I right?
 
Thanks

**Comment by jotamartos** [comment]
Yes, those commands will provide more information so you can start troubleshooting the issue.
