### ISSUE TITLE
Graylog, EFK

### ISSUE THREAD

**Issue by ZedZipDev** [bitnami/vms#1525]
### Describe your suggestion as much as you can

Hi Bitnami team,
It will be good to have VM with Graylog , EFK stack for log aggregators.
I am developer and it can be very useful for development and for production too.
Thank you

**Comment by gongomgra** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

**Comment by brandonr55** [comment]
Welcome brother.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid-term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
