### ISSUE TITLE
[<bitnami/vms ALFRESCO>] Error Busqueda en Alfresco

### ISSUE THREAD

**Issue by jsuarez1993** [bitnami/vms#1527]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

49d9839b-3fd2-b236-d7e8-39f580f46c34

### bndiagnostic was not useful. Could you please tell us why?

.

### Describe your issue as much as you can

He activado el inicio en LDAP en Alfresco versión 22 y puedo iniciar sesión correctamente pero no busca nada, ni documentos, ni sitios, categorías, usuarios...
Error en texto: 
JavaException: org.alfresco.repo.search.QueryParserException: 04120127 Solr request failed with 403 /solr/alfresco/alfresco?wt=json&fl=DBID%2Cscore&rows=1000&df=TEXT&start=0&locale=es_ES&alternativeDic=DEFAULT_DICTIONARY&fq=%7B%21afts%7DAUTHORITY_FILTER_FROM_JSON&fq=%7B%21afts%7DTENANT_FILTER_FROM_JSON
![image](https://github.com/bitnami/vms/assets/26604963/4dc0e085-00ce-4607-9870-7d37083bb13f)
![image](https://github.com/bitnami/vms/assets/26604963/d4bee8df-1047-4868-8449-a4af1dfea660)

**Comment by gongomgra** [comment]
Hi @jsuarez1993,

Thanks for using Bitnami. Although our team doesn't have any problem with reading and writing Spanish language, we highly recommend to use English in this community forum, so the biggest number of users can help you, and your question would be of help to all of them in the future as well.

Regarding your issue with Alfrescon and LDAP, I think this is more related to the application itself than to the Bitnami installation. I see error messages in Apache and Tomcat's logs files (`/opt/bitnami/tomcat/logs/catalina.out`) returning 403 errors between Alfresco and Apache Solr, which seems to be a specific error of the application when accessing Solr. We suggest you contact the Alfresco's support team to know more about the issue and how to debug it. We will keep this ticket open to allow other Bitnami users post the solution to this issue in case they also ran into it.
