### ISSUE TITLE
To access the console

### ISSUE THREAD

**Issue by Aloul2024** [bitnami/vms#1530]
### Describe your issue as much as you can

To access the console in the common wordPress file i have the hand to mentione the username, but for the password i haven't the hand at all !!! Please help me to resolve this problem.

**Comment by gongomgra** [comment]
Hi @Aloul2024,

Thanks for using Bitnami. You can get more information on how to retrieve the credentials to log into your application in the next guide

https://docs.bitnami.com/aws/faq/get-started/find-credentials/ 

In case it doesn't help, can you tell us which platform are you using (AWS, Azure, Google, OVA) and give us more details about your issue?
