### ISSUE TITLE
[Bitnami package for WordPress] Guest Additions install unsuccessful

### ISSUE THREAD

**Issue by DrippingMellow** [bitnami/vms#1531]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a35bbd2c-723c-65ba-ce3d-9155caf9687d

### bndiagnostic output

WordPress: No issues found
Apache: No issues found
Processes: No issues found
Php: No issues found
Resources: No issues found
? Connectivity: Found possible issues
Mariadb: No issues found
[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:
https://docs.bitnami.com/general/faq/administration/use—firewaIl/

### bndiagnostic was not useful. Could you please tell us why?

The suggested Articles are not related to my issue.

### Describe your issue as much as you can

I've tried multiple times to install guest Additions. Yet, it always is unsuccessful. I guess something might have changed.
![image](https://github.com/bitnami/vms/assets/79058247/b4e06afe-45cf-4220-b927-878fc948e1e0)

**Comment by Stev110** [comment]
I have use this How-to article to install it:
[Link](https://docs.bitnami.com/virtual-machine/faq/configuration/install-virtualbox-guest-additions/)

**Comment by Stev110** [comment]
Hello @gongomgra,

Thanks for your help, I appreciate it. Yet I still have the issue. Where it tells me that it wasn't able to reload. I even tried to run it on multiple VM's, just to be sure _and ended up with multiple issues along the way._

I'm sorry but it doesn't work.

Greetings

**Comment by gongomgra** [comment]
Hi @DrippingMellow,

I was able to reproduce your issue, and I have installed the following packages to solve it

```
sudo apt-get install -y libfltk1.3 libfltk1.3-dev
```

After that, the `vbox-greeter` binary can be executed on my machine

```
$ sudo /opt/VBoxGuestAdditions-7.0.18/sbin/vbox-greeter
00:00:00.000058 main     vbox-greeter 7.0.18 r162988 (verbosity: 0) linux.amd64 (May  2 2024 08:33:34) release log
00:00:00.000060 main     Log opened 2024-05-27T12:14:49.050637000Z
00:00:00.000823 main     OS Product: Linux
00:00:00.000855 main     OS Release: 6.1.0-21-amd64
00:00:00.000885 main     OS Version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)
00:00:00.000928 main     OS Service Pack: #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)
00:00:00.000969 main     Executable: /opt/VBoxGuestAdditions-7.0.18/sbin/vbox-greeter
00:00:00.000970 main     Process ID: 886
00:00:00.000970 main     Package type: LINUX_64BITS_GENERIC
Can't open display:
```

Take into account that our virtual machines do not include a graphical desktop environment, so there must be some features that can't be enabled

**Comment by DrippingMellow** [comment]
Hi @gongomgra. Thank you verry much for your help & patience till now, the Guest Additions, seem to get loaded if the two packages you've last mentioned are really needed, is still puzzling me. Yet the bidirectional copy / paste | Drag & Drop still don't seem to work, as well as the inbuilt file access.
