### ISSUE TITLE
[Wordpress w/ NGINX & SSL] Local Dev to AWS Wordflow

### ISSUE THREAD

**Issue by tziady** [bitnami/vms#1533]
### Describe your issue as much as you can

Hello:

    I am unsure that this is the best place for this.  However, I was really unable to find a general forum where I could pose my question. Please kindly let me know if this is the wrong place and where I might go to answer my question. 

   I was just wondering what is the average workflow and practice of those using Bitnami w/ NGINX and SSL from migrating their local VM (VirtualBox / hyper-V) environment to a cloud provider like AWS or Google or whoever really. 
   
   I am fairly well versed on backing up, exporting and manually moving WordPress sites. 
   
   I have used duplicator pro or even manually using mysql and taring files have moved and migrated many websites. 

   And that process is simple enough; however, I was wondering since on AWS and GCloud and others all you are basically doing is setting up a virtual instance very similar to that which you would with Virtualbox or Hyper-V. Is there a more direct path of migrating a locally run Virtual Machine to the cloud with Database and All other part for a full functional site. 

Understanding that SSL, DNS, and other things will obviously have to be set up manually. But any way to automate / migrate a development environment from my desktop running a local virtual machine downloaded from Bitnami to create an AWS or other cloud instance (whether Gcloud, AWS - Ec2 or Lightsail, ect).

Thanks,
T

**Comment by jotamartos** [comment]
>But any way to automate / migrate a development environment from my desktop running a local virtual machine downloaded from Bitnami to create an AWS or other cloud instance (whether Gcloud, AWS - Ec2 or Lightsail, ect).

You can migrate the WordPress data by following this guide 

https://docs.bitnami.com/general/how-to/migrate-wordpress/

For the Apache-related changes (conf + certs), you will need to perform the changes manually.
