### ISSUE TITLE
[WordPress] There has been a critical error on this website.

### ISSUE THREAD

**Issue by anuradhaedirisuriya** [bitnami/vms#1535]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

79ef5a6d-881e-2004-ffa4-0aecb0fde169

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 472 321 25 11 125 126 Swap: 
634 52 582
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat May 18 15:28:04.357418 2024] [proxy_fcgi:error] [pid 1514:tid 
140031384712960] [client **ip_address**:48898] AH01071: Got error 'PHP message: 
PHP Warning: require_once(/bitnami/wordpress/wp-content/db.php): Failed to open 
stream: Permission denied in /opt/bitnami/wordpress/wp-includes/load.php on line 
675PHP message: PHP Fatal error: Uncaught Error: Failed opening required 
'/opt/bitnami/wordpress/wp-content/db.php' 
(include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/wordpress/wp-in [Sat 
May 18 15:31:15.651150 2024] [proxy_fcgi:error] [pid 1514:tid 140030932498176] 
[client **ip_address**:14588] AH01071: Got error 'PHP message: PHP Warning: 
require_once(/bitnami/wordpress/wp-content/db.php): Failed to open stream: 
Permission denied in /opt/bitnami/wordpress/wp-includes/load.php on line 675PHP 
Press [Enter] to continue:
message: PHP Fatal error: Uncaught Error: Failed opening required 
'/opt/bitnami/wordpress/wp-content/db.php' 
(include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/wordpress/wp-in [Sat 
May 18 15:33:04.396435 2024] [proxy_fcgi:error] [pid 1514:tid 140030924105472] 
[client **ip_address**:41408] AH01071: Got error 'PHP message: PHP Warning: 
require_once(/bitnami/wordpress/wp-content/db.php): Failed to open stream: 
Permission denied in /opt/bitnami/wordpress/wp-includes/load.php on line 675PHP 
message: PHP Fatal error: Uncaught Error: Failed opening required 
'/opt/bitnami/wordpress/wp-content/db.php' 
(include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/wordpress/wp-i
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

It is helpful

### Describe your issue as much as you can

I'm getting the following error message when trying to acces my Bitnami Wordpress site hosted using AWS Lightsail.

![image](https://github.com/bitnami/vms/assets/7523370/68196be1-7642-4d19-b6e4-4bb20dd6a9db)

**Comment by anuradhaedirisuriya** [comment]
Solved it after running both structure 1 and structure 2 commands.
[https://raddy.dev/blog/aws-lightsail-fix-wordpress-file-permissions](https://raddy.dev/blog/aws-lightsail-fix-wordpress-file-permissions/)

and then connecting to Lightsail via SFTP and uploading the new WordPress version to /opt/bitnami/wordpress

**Comment by jotamartos** [comment]
This post contain the commands to run when restarting the permissions of the solution 

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

Thanks
