### ISSUE TITLE
[Opencart 4.0.2.3 Bitnami Google Cloud] Admin Cannot login & Bugs

### ISSUE THREAD

**Issue by JeffGaylard** [bitnami/vms#1538]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e2f05f9d-ce5e-7d4d-3d15-6f03f61d1294

### bndiagnostic was not useful. Could you please tell us why?

Only telling me what I know

### Describe your issue as much as you can

I recently changed the currency from AUD to USD in Opencart because their currency module has calculation issues and does not calculate correctly unless it is based on USD as default.
Then I changed one item in the product to reflect a different price and the whole system crashed.
Now the admin login does not allow me in and does not report errors for incorrect passwords.
After attempting to login, the login page refreshes without any warnings.
Upon password reset, the first and confirmation passwords can be different without error. 

In the Opencart forum they suggest version 4.0.2.3 has too many bugs that need to be ironed out and to use version 3.0.3.9.
Thinking Bitnami would choose a more stable release, I have purchased extensions and am now left with nothing at all.
Bitnami Opencart documentation online is for older versions which also does not help.
If it is as simple to get Opencart to tell me there are issues with this release, it just amazes me Bitnami would make this version their primary release.
From what I make out, it appears to be either a cookie session issue that I have tried everything to fix
or a duplicate database entry which appears to have been an issue through many versions.

I have tried clearing cache on browser, in VM, changing cookie settings in currency files, in framework
and other files as suggested for older version with similar issues.

If anyone has experienced this issue and may have advice, I would appreciate any feedback.

 FYI, the cookie error listed in Developer tools
 
 Cookies marked with SameSite=None must also be marked with Secure to allow setting them in a cross-site context. This behavior protects user data from being sent over an insecure connection.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests.

**Comment by gongomgra** [comment]
Hi @JeffGaylard,

Thanks for using Bitnami and for reporting this to us. Can you share the link to the thread in which the OpenCart developers recognized the issues in this version so it can be of help to other users with the same issue? Unfortunately, we do not have any control on the source code of the applications in our catalog. We use the app code published by upstream developers, and for OpenCart they publish version `4.0.2.3` in [their website](https://www.opencart.com/index.php?route=cms/download)

![Screenshot 2024-05-20 at 10 12 21](https://github.com/bitnami/vms/assets/6660452/e0a85115-3cfa-4b24-bcb8-5861c729d9ce)

I'm afraid there isn't much we can do here until they release a fix. Our system will detect any new release they perform and will try to get it published automatically. Please ask for a workaround in the official OpenCart forums and/or for a new release fixing the issue.

**Comment by JeffGaylard** [comment]
Hello 

 

I apologize for the delay because I have never played with sql and database code.

The link of where one expert stated the software has issues is :

https://forum.opencart.com/viewtopic.php?p=870251#p870251

 

I have managed to fix the issue after a long time of studying how sql and databases work
so forgive me if I sound like a newbie.

 

Here is what I posted in the forum that fixed my issue.

 

I apologize as this is my first time to play with SQL or Ddatabases so I had to learn as I go.

If the formatting is not correct for the forum please change as I have never offered any 

advice on a forum before.

 

-How to Fix issue ( it was same site cookie = none issue )

 

You will be locked out of the database as root so do the following : 

- FTP into site

- Go to /opt/bitnami/mariadb/conf

- Edit my.cnf

  -under [mysqld]

   add the following skip-grant-tables

   close and save

 

- Restart Bitnami VM for opencart 

 

Now you will be able to log into Database via an SSH Browser but bare in mind the VM instance will most likely have changed your IP address

 

-in SSH shell use the following commands

 

Sudo –i

mysql –u root –p ( then enter password )

use database bitnami_opencart       ( if this is the database name you are using )

 

select * from oc_setting     (to check config_setting_samesite key is id  342)

if it is the same id :  ( Or change to match the ID in the table )

 

update oc_setting

set value = 'Strict'

where setting_id = 342;

 

The next steps were just based on other reading and the alter user didn’t seem to work but I tried anyway 

 

flush privileges; 

ALTER USER 'root'@'localhost' IDENTIFIED BY 'NewPassword';

( if you get an error just ignore, I guess it cannot be altered when running  as root)

 

Go back to /opt/bitnami/mariadb/conf

- Edit my.cnf

   under [mysqld]

remove skip-grant-tables

 

Restart the VM and again your IP address would have changed

 

Now you should be able to log in.

 

 

 

Best Regards

 

Jeff Gaylard

 

RF Components 
51 Neuparth Road
Croydon North, 
Victoria, 3136
Australia



Phone          (03) 9727 0748  ( International +61 3 9727 0748 )
Cell Ph         0418 550 972  ( International +61 418 550 972 )

Email           ***@***.***
Ecommerce  www.rfcomponents.com.au <http://www.rfcomponents.com.au/>

**Comment by gongomgra** [comment]
Hi @JeffGaylard,

Thanks for your message. Sharing the link to the post in which you shared your solution is enough. I'm glad you have managed to fix your issue. We are closing this ticket as solved.
