### ISSUE TITLE
[node.js express] Certificates may not renew automatically, due to a web server configuration issue

### ISSUE THREAD

**Issue by Sully1570** [bitnami/vms#154]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4ab8166f-25e7-fb3d-7030-731203d35fcd

### bndiagnostic output

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Jul 21 07:32:28.197944 2022] [proxy_http:error] [pid 8095:tid 
139829457135360] [client **ip_address**:43828] AH01114: HTTP: failed to make 
connection to backend: localhost
 [Thu Jul 21 07:34:13.335712 2022] [proxy:error] [pid 8515:tid 140351092406016] 
(111)Connection refused: AH00957: http: attempt to connect to 
**ip_address**:3000 (localhost) failed
 [Thu Jul 21 07:34:13.335772 2022] [proxy_http:error] [pid 8515:tid 
140351092406016] [client **ip_address**:43846] AH01114: HTTP: failed to make 
Press [Enter] to continue:
connection to backend: localhost

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 482 243 37 1 200 224 Swap: 634 
2 632
```

### bndiagnostic was not useful. Could you please tell us why?

I have no idea what any of this means.

### Describe your issue as much as you can

I'm building a little web app to handle some HTTP POST requests for me.

I get this message when executing sudo /opt/bitnami/bncert-tool.
```
Warning: Certificates may not renew automatically, due to a web server configuration issue. For more information see: 
https://docs.bitnami.com/general/how-to/understand-bncert/#certificates-not-renewed-automatically
```
I'm able to get a secure response when I send my server a POST at https, so the cert is working now.   I've messed with the vhost config files per the instructions on the docs.bitnami.com site, but I really have no idea what I'm doing.  Sorry, I'm new to all of this.

Here's the contents of the vhost.conf files:
/opt/bitnami/apache/conf/vhosts/myapp-http-vhost.conf
```
 <VirtualHost _default_:80>
    ServerAlias *
    DocumentRoot "/home/bitnami/htdocs/Mandelbrot-PBX-Client"
    <Directory "/home/bitnami/htdocs/Mandelbrot-PBX-Client">
      Require all granted
    </Directory>
    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/
  Alias /.well-known/ "/opt/bitnami/apps/letsencrypt/.well-known/"
  <Directory "/opt/bitnami/apps/letsencrypt/.well-known">
      Options +MultiViews
      AllowOverride None
      Require all granted
  </Directory>
  </VirtualHost>
```

/opt/bitnami/apache2/conf/vhosts/myapp-https-vhost.conf
```
  <VirtualHost _default_:443>
    ServerAlias *
    SSLEngine on
    SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
    DocumentRoot "/home/bitnami/htdocs/Mandelbrot-PBX-Client"
    <Directory "/home/bitnami/htdocs/Mandelbrot-PBX-Client">
      Require all granted
    </Directory>
    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/
  Alias /.well-known/ "/opt/bitnami/apps/letsencrypt/.well-known/"
  <Directory "/opt/bitnami/apps/letsencrypt/.well-known">
      Options +MultiViews
      AllowOverride None
      Require all granted
  </Directory>
  </VirtualHost>
```

What am I missing?

**Comment by mdhont** [comment]
Please try the manual approach:

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by Sully1570** [comment]
cool, thanks for the tip.
