### ISSUE TITLE
[WordPress] version problem with cron user permissions and WordPress Cron cron job

### ISSUE THREAD

**Issue by mtnlion1** [bitnami/vms#1540]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

none

### bndiagnostic was not useful. Could you please tell us why?

Problem has nothing to do with Apache. It's related to cron permissions

### Describe your issue as much as you can

In order to bypass the WordPress interma; corn (which is needed on any site that gets good traffic), it's necessary to add an instruction in wp-config.php and create a corn job to run the Wordpress cron routine on a scheduled basis. The issue is that Bitnami does a cron-deny for user "daemon". However, you assign all Wordpress files to own/group "daemon". If the system cron job is run by  any other user, plugin updates will fail.

I took care of this by deleting the cron-deny in /etc. However, you should not prohibit "daemon" from owning cron jobs in Wordpress instances.

**Comment by dennis6101990leon** [comment]
To resolve the WordPress cron job permissions issue, you can edit the /etc/group file as root, add the daemon user to the cron group, and then re-login as the daemon user. Ensure the daemon user has the necessary permissions to execute cron jobs without affecting WordPress file ownership and plugin updates.

**Comment by mtnlion1** [comment]
I know how to fix it. Your solution won’t work. You need tp edit /etc/cron-deny. Tyat wasn’t,why I created this issue. Bitnami neees to change the configuration of the Wordpress instance to either allow daemon to run a cron job or change the owner of Wordpress files. It is a very common need to disable the WP cron and instead schedule wp-cron updates via the system cron. Bitnami is making this very difficult for users.

**Comment by jotamartos** [comment]
The instructions posted here should work for you when disabling the WordPress' cron 

https://docs.bitnami.com/general/apps/wordpress/configuration/disable-wordpress-cron/

Could you please take a look at it?

**Comment by mtnlion1** [comment]
I did the fix on my install. The file that needs to be edited is cron-deny. I am requesting that you either change ownership of WP files or stop blocking daemon in future releases.

**Comment by jotamartos** [comment]
Could you please provide more information about the changes you applied and how to reproduce the error you were running into?

**Comment by mtnlion1** [comment]
Here is the situation.

Problem: Need to disable the default WordPress internal call to thei wp-cronand  nternal cron job (wp-cron) and replace it with a system cron job that will execute on a schedule. This is necessary on sites with good traffic because wp-cron executes each time a user visits.

 

Actions needed to replace wp-cron with a system cron job:

1.	Add define ('DISABLE_WP_CRON', true); to wp-config.php
2.	Add a system cron job with the command /opt/bitnami/php/bin/php /opt/bitnami/wordpress/wp-cron.php >/dev/null 2>&1

The Problem:

1.	The system cron job has to be executed by the same user/group that owns the wp-content files. In the case of your Bitnami AWS implementation that is “daemon” You probhibit daemon from running cron jobs. If any other user runs the cron jobs, updates to plugins and other features will fail because they can’t be executed in production.

Workaround

                Edit /etc/cron-deny (I think that is the file) to remove daemon and then assign the system cron job to daemon.

 

You really need to remove the cron-deny or assign ownership of wp files to a user who can execute cron jobs.

 

Why this is important:

 

The default WordPress strategy to execute scheduled jobs by executing wp-cron is wasteful on busy sites, or doesn’t get executed often enough on sites with little traffic. The workaround above has been in use for decades. Bitnami has to support this modification since it is needed so often.

 

Proposed solution:

1.	The easiest way is to delete cron-deny and let daemon run cron jobs.
2.	The best, in my opinion, solution is to hard wire the system vron patch running every 5 minutes. There is no downside to this and it will make all  of your customers more efficient.

**Comment by mtnlion1** [comment]
I have 2 problems with your solution:

 

1.	It never showed up when I searched for the wp-cron disable.
2.	You are having daemon execute as root. The problem with that is that most wp cron jobs are for plugins which are not certified to be safe.  It’s far better to execute as daemon without the “su”.

**Comment by jotamartos** [comment]
>2.	You are having daemon execute as root. The problem with that is that most wp cron jobs are for plugins which are not certified to be safe.  It’s far better to execute as daemon without the “su”.

You are using sudo to execute a command as daemon. This is not a security issue because the command is executed as daemon.

**Comment by mtnlion1** [comment]
Why are you denying daemon direct ability  to run a cron job?

**Comment by jotamartos** [comment]
It's a good security practice not to allow users like daemon run cron jobs. This way, you need admin privileges (using sudo) to run it. If that's a problem for you, you can always edit the cron.deny file and remove the user from there.
