### ISSUE TITLE
[Apache Airflow] Service Unavailable

### ISSUE THREAD

**Issue by rahulfulzele** [bitnami/vms#1541]
### Platform

OSX VM

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Apache airflow

### bndiagnostic output

Apache airflow

### bndiagnostic was not useful. Could you please tell us why?

Apache airflow

### Describe your issue as much as you can

Login page not visible
http://192.168.0.105
Showing
![Capture](https://github.com/bitnami/vms/assets/4375599/6f3b90e5-3b6f-41de-a9d0-e486d2f6c671)

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by jotamartos** [comment]
Hi @rahulfulzele,

If you are using an OS X VM, that means that you are using an old version. We removed support for that platform long time ago. We recommend you check the logs of the app to get more information about the error but please take that into account that we can't work on reproducing the issue as it's a non-supported solution.

Please migrate to a OVA or a docker image to run updated software 

https://bitnami.com/stack/apache-airflow/virtual-machine

**Comment by brandonr55** [comment]
That's great. I was impressed by your writing. I am happy to see such a topic. Please come to my blog and read it. [Jetnet ](https://www-newjetnet.com/
)

**Comment by blanca236** [comment]
Hi
It appears that you’re dealing with a legacy system where support for the OS X VM has been discontinued. 
Best Regard
[myfordbenefits](https://www.my-fordbenefits.com)
