### ISSUE TITLE
Website performance on cPanel on ec2 is slow

### ISSUE THREAD

**Issue by petrait** [bitnami/vms#1542]
### Name and Version

bitnami/wordpress

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello,

We're using cPanel on EC2 instance, instance type is c5.xlarge and c5.4xlarge, specifications as below:

Model	vCPU	Memory (GiB)	Instance Storage (GB)	Network Bandwidth (Gbps)***	EBS Bandwidth (Mbps)
c5.xlarge	4	8	EBS-Only	Up to 10	Up to 4,750
c5.4xlarge	16	32	EBS-Only	Up to 10	4,750

### Are you using any custom parameters or values?

no

### What do you see instead?

we tried to upgrade the instance to get good fast performance but it doesn't work

kindly advise how this can be fixed, and if there are any configurations needs to be done on our side to fix this

Regards

**Comment by jotamartos** [comment]
>We're using cPanel on EC2 instance, instance type is c5.xlarge and c5.4xlarge, specifications as below:

Hi @petrait,

We do not provide support for cPanel so we can't help you with this case. Please contact the cPanel support team to get more information about how to debug the issue
