### ISSUE TITLE
[<LAMP>] Multiple websites on one instance

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1543]
### Describe your issue as much as you can

Hello,

I would like to know how to hoist multiple websites on one LAMP instance.

**Comment by gongomgra** [comment]
Hi @huzanf, 

Please find the required documentation in the link below

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

**Comment by huzanf** [comment]
Thanks @gongomgra 
How do I have multiple SSL for the same?

**Comment by huzanf** [comment]
Hi @gongomgra 

> https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

Also, if I want one subdomain to hoist a staging website how can I do that?
Do I need to replicate the content in the vhosts file and add it as a subdomain on my DNS?

**Comment by gongomgra** [comment]
Hi @huzanf,

You can generate as many SSL certificates as required by following our guide linked below, but do not create the symlinks in the step number 3 to `server.crt` and `server.key`. After that, point each `SSLCertificateFile` and `SSLCertificateKeyFile` to the generated files (named after your apps domains) in the `https-vhost.conf` files.
 
https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

Regarding the staging domain I think you are right. You need to create a new custom application as usual, configure it to use the subdomain, and also update your DNS registries.
