### ISSUE TITLE
[Azure package for Supabase] Error no Route matched with those values.

### ISSUE THREAD

**Issue by AndTmf** [bitnami/vms#1545]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9b6e614e-8e7d-ccf1-48d0-7528cb427e5a

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Connectivity: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Nginx: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1919 1242 94 145 998 676 Swap:
Press [Enter] to continue:
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

the hints did not contribute to the solution

### Describe your issue as much as you can

Hello, I would like to use the Supabase Azure VM image. after setting it up, when I try to call ip:8000 in Brwoser I get the following error:
Error
no Route matched with those values.
![image](https://github.com/bitnami/vms/assets/116666373/52924d86-a0fd-410b-84a2-9a51a8c1bfc6)
I have not changed anything in the configuration and I cannot find anything in the documentation 

port 8000 was already enabled by default. 
For test purposes I also released the others but there was no change 

![image](https://github.com/bitnami/vms/assets/116666373/6b41c883-5311-40d5-ae01-b88d079eb345)

**Comment by jotamartos** [comment]
Hi @AndTmf,

You will access the API when using port 8000. If you want to access the web interface, you will need to use port 4000. However, due to security reasons, you will need to create a SSH tunnel to access it. You can get more information about this here:

https://github.com/bitnami/vms/issues/1262
