### ISSUE TITLE
[WordPress] Download older ova

### ISSUE THREAD

**Issue by rogxprouser** [bitnami/vms#1546]
### Describe your issue as much as you can

Respected team,
I am looking to download an older version than the current version 6.5.3-0 which is showing on https://bitnami.com/stack/wordpress/virtual-machine.

Ideally, based on https://bitnami.com/stack/wordpress/vboxdebian-x64-nami/changelog.txt I'd like to download the following vereison:

version 5.0-0      released on 2018-12-07

This version of bitnami wordpress ova has the exact WordPress 5.0 which I need.

Anyone know where I can get this version from?

Thank you very much and your reply can make my day!

**Comment by jotamartos** [comment]
Hi @rogxprouser,

Thank you for your interest. That OVA is no longer in our records (it's 5+ years old) but you can try using our docker images available at https://hub.docker.com/r/bitnami/wordpress/
