### ISSUE TITLE
[Grafana]Bitnami Grafana gives plugindownstream error for cloudwatch logs

### ISSUE THREAD

**Issue by shilpasecret** [bitnami/vms#1547]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Na

### bndiagnostic was not useful. Could you please tell us why?

Na

### Describe your issue as much as you can

When querying aws cloud watch logs through Bitname Grafana AMI we are getting plugindownstreamerror code 500

**Comment by jotamartos** [comment]
Hi @shilpasecret,

Could you please provide more details about the issue and the steps we need to follow to reproduce it?
