### ISSUE TITLE
[WordPress] Version 5.6 Download

### ISSUE THREAD

**Issue by BAHRAM1024** [bitnami/vms#1548]
### Describe your issue as much as you can

Hi,

Looking for version 5.6 or nearest newer version download link if available

Thanks

**Comment by cassie2698bratt** [comment]
Hello,

Search the software's official website: Most software companies have a download section on their website. Go to the website of the software you're interested in and look for a "Downloads" or "Get Started" section. There, you should be able to find the latest version available and possibly past versions as well.

Use a search engine: If you're not sure of the software's official website, you can use a search engine like Google or DuckDuckGo. Include the software name, version number (e.g., "software name version 5.6"), and "download" in your search query. Be cautious when downloading from unofficial sources, as they might contain malware.

Software repository websites: If the software is open-source, you might find it on a software repository website like GitHub or SourceForge. These websites often host different versions of the software, including past releases.

Example:

Let's say you're looking for version 5.6 of Adobe Photoshop. Here's what you could do:

Visit the official Adobe website and look for a "Downloads" section.
Search on Google using the query "Adobe Photoshop version 5.6 download".
Check GitHub or SourceForge for the software (if it's open-source).

**Comment by gongomgra** [comment]
Hi @BAHRAM1024,

Thanks for your interest in using Bitnami. That version is very old, and we no longer have it in our records. You can try using our Docker images available in DockerHub

https://hub.docker.com/r/bitnami/wordpress/tags?page=&page_size=&ordering=&name=5.6
