### ISSUE TITLE
[wordpress] http://127.0.0.1/ Site cannot be reached

### ISSUE THREAD

**Issue by sankarcn** [bitnami/vms#155]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ac1de3bf-9e1d-6a6c-4a78-7af396f9c2b3

### bndiagnostic was not useful. Could you please tell us why?

Could not find anything useful related to the problem.

### Describe your issue as much as you can

What I did:
Wordpress site was working fine before installing SSL certificate.
1. Installed SSL certificate using bincert.
2. Once installed, it was redirecting to 127.0.0.1. The apache error log has this line. 
 AH01630: client denied by server configuration: /opt/bitnami/phpmyadmin/index.php
3. Then, edited the /opt/bitnami/apache/conf/httpd.conf and added the below lines. 
<Directory "/opt/bitnami/phpmyadmin">
Options Indexes FollowSymLinks
AllowOverride None
Require all granted
</Directory>
4. Restarted apache. 
5. The site is still redirecting to 127.0.0.1. But not error in apache error_log.

**Comment by jotamartos** [comment]
Hi @sankarcn,

If you are trying to access phpMyAdmin, you will need to create the SSH tunnel to use port 443 as destination port and use https in the request. 

- Source port:8888
- Destination port: 443
- URL: https://127.0.0.1:8888/phpmyadmin

**Comment by sankarcn** [comment]
When I type https://Web_URL on the browser, the browser shows the error Web_URL refused to connect.
The apache access_log says
45.127.46.218 - - [22/Jul/2022:10:03:18 +0000] "GET / HTTP/1.1" 302 208
There is no entry in error_log.
This is happening after I installed the certificate using bncert tool.

**Comment by jotamartos** [comment]
Port 443 is blocked in the firewall and can't be accessed through internet. Please check that 

```
/tmp                                                                                                                                                                                                                                 12:12:21
❯ nc -zv -w 2 elotree.com 80
Connection to elotree.com port 80 [tcp/http] succeeded!

/tmp                                                                                                                                                                                                                                 12:12:23
❯ nc -zv -w 2 elotree.com 443
nc: connectx to elotree.com port 443 (tcp) failed: Connection refused
```

**Comment by sankarcn** [comment]
I installed ufw and enabled 443.
sankar@elotreesite-vm:/bitnami/wordpress$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
443                        ALLOW       Anywhere                  
OpenSSH                    ALLOW       Anywhere                  
7722/tcp                   ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
8080/tcp                   ALLOW       Anywhere                  
443 (v6)                   ALLOW       Anywhere (v6)             
OpenSSH (v6)               ALLOW       Anywhere (v6)             
7722/tcp (v6)              ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)             
8080/tcp (v6)              ALLOW       Anywhere (v6)          

Still port 443 is not working.

**Comment by sankarcn** [comment]
The bitnami documentation says that I should open ports using ufw.
https://docs.bitnami.com/virtual-machine/faq/administration/use-firewall/

**Comment by jotamartos** [comment]
You are using a cloud image in Google Cloud according to the first message, please check this guide to confirm port 443 is open

https://docs.bitnami.com/google/faq/administration/use-firewall/

**Comment by sankarcn** [comment]
firewall  is open to 443. And port 443 us already opened on cloud vm image. 
But apache is not listening on port 443

sankar@elotreesite-vm:/bitnami/wordpress$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
443                        ALLOW       Anywhere                  
OpenSSH                    ALLOW       Anywhere                  
7722/tcp                   ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
8080/tcp                   ALLOW       Anywhere                  
443 (v6)                   ALLOW       Anywhere (v6)             
OpenSSH (v6)               ALLOW       Anywhere (v6)             
7722/tcp (v6)              ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)             
8080/tcp (v6)              ALLOW       Anywhere (v6)             


sankar@elotreesite-vm:/bitnami/wordpress$ sudo netstat -ntupl | grep httpd
tcp6       0      0 :::80                   :::*                    LISTEN      32300/httpd

**Comment by sankarcn** [comment]
Infact netstat does not mention 443 listened by any process. This has happened after I installed ufw.

**Comment by sankarcn** [comment]
Any update? 
Do you need access to our server? Do you suggest to re-install bitnami wordpress?

**Comment by jotamartos** [comment]
Hi @sankarcn ,

that's not what I see in the original Bitnami Diagnostic tool information you shared 

```
-----------------------------------
Check processes on ports 80 and 443
-----------------------------------
Running: netstat -tulpn | grep "80\|443"
In: /opt/bitnami

Output:

tcp6       0      0 :::443                  :::*                    LISTEN      12812/httpd
tcp6       0      0 :::80                   :::*                    LISTEN      12812/httpd
```

I do not know if you edited the Apache's configuration or if you started the system's Apache instead of the Bitnami's one. The /opt/bitnami/apache/conf/bitnami/bitnami.conf file should include the bitnami-ssl.conf file that is the one that defines the https port in Apache.

**Comment by sankarcn** [comment]
My Apologies, it was my mistake. In the process of fixing the issues, I commented out the 
include of 
/opt/bitnami/apache/conf/bitnami/bitnami.conf
But the problem that I see is that the document root directory does not point for wordpress. Is there any document that would help me in fixing this. Otherwise you can close the issue. 
Thank You Very Much for your support. I has immensely saves  a lot of my time. 
Thanks and Regards

**Comment by sankarcn** [comment]
I am referring to the SSL conf for apache not pointing to wordpress.

**Comment by jotamartos** [comment]
Hi @sankarcn,

The Apache configuration for WordPress is set in the /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf and wordpress-https-vhost.conf. If you want to use a SSL cert for WordPress, you need to edit the wordpress-https-vhost.conf file. The bncert tool should update that file when you run the tool so please undo the changes you manually applied to the conf files and run the tool again. If you continue running into issues, please run the Bitnami Diagnostic tool so we can review the info.

Thanks

**Comment by sankarcn** [comment]
I reran the  bncert tool and still the problem persists.
ef8eda8f-7a8f-9ae8-25c0-c3d07a4614d4
Kindly help me.

**Comment by jotamartos** [comment]
Hi @sankarcn,

I think the problem is that WordPress doesn't have the WP_SITEURL and WP_HOME variables configured in the wp-config.php file. You can try to configure WordPress with your www domain to solve this issue, I can see WordPress is redirecting to a wrong IP right now 

```
❯ curl -LI elotree.com
HTTP/1.1 302 Found
Date: Tue, 26 Jul 2022 14:14:32 GMT
Server: Apache
Location: https://elotree.com/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 301 Moved Permanently
Date: Tue, 26 Jul 2022 14:14:32 GMT
Server: Apache
Location: https://www.elotree.com/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 301 Moved Permanently
Date: Tue, 26 Jul 2022 14:14:33 GMT
Server: Apache
X-Redirect-By: WordPress
Location: https://127.0.0.1/
Content-Type: text/html; charset=UTF-8

curl: (7) Failed to connect to 127.0.0.1 port 443: Connection refused
```

https://docs.bitnami.com/general/apps/wordpress/administration/configure-domain/

If you continue running into errors, I suggest you contact WordPress to know how to configure the domain in the app. Another solution would be to create a new instance and migrate the data.

https://docs.bitnami.com/general/how-to/migrate-wordpress/

**Comment by sankarcn** [comment]
Thank You. The solution configure domain solved the problem. But domain should be defined with or without www prefix in the same way in the apache config file and wordpress  config file. Thanks again for your support.
