### ISSUE TITLE
[WordPress] An error occurred when initializing this installation !!!!!

### ISSUE THREAD

**Issue by saduagyei** [bitnami/vms#1550]
### Describe your issue as much as you can

Please I am so new and trying to build a website both single and multisite using bitnami on google cloud. 

Just today, i realised when used the SSH, i get below warnings. Can someone please help me how to fix this? I am not IT guru so simple words and step by step would be much appreciated:

─────────────────────────────────────────────────────────────────────────────┐
│ !!!!! IMPORTANT: An error occurred when initializing this installation !!!!! │
│ Please check the initialization logs to get more information:                │
│                                                                              │
│   sudo cat /var/log/cloud-init-output.log                                    │
│                                                                              │
│ Please try and re-create this installation. If that does not fix your issue, │
│ open a Bitnami support ticket at https://github.com/bitnami/vms/issues

**Comment by saduagyei** [comment]
This is the log:

Cloud-init v. 22.4.2 running 'modules:config' at Wed, 29 May 2024 21:26:37 +0000. Up 16.44 seconds.
Cloud-init v. 22.4.2 running 'modules:final' at Wed, 29 May 2024 21:26:49 +0000. Up 28.28 seconds.
 21:26:49.97 INFO  ==> Enabling all services
 21:26:50.42 INFO  ==> No user-data was provided in the deployment template
mariadb 21:26:51.15 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 21:26:51.18 INFO  ==> Initializing mariadb database
mariadb 21:26:51.20 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 21:26:51.21 INFO  ==> Setting user option
mariadb 21:26:51.25 INFO  ==> Setting bind_address option
mariadb 21:26:51.26 INFO  ==> Setting slow_query_log option
mariadb 21:26:51.27 INFO  ==> Setting long_query_time option
mariadb 21:26:51.28 INFO  ==> Using persisted data
/opt/bitnami/mariadb/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mariadb/bin/mariadb' instead
/opt/bitnami/mariadb/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mariadb/bin/mariadb' instead
/opt/bitnami/mariadb/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mariadb/bin/mariadb' instead
mariadb 21:26:51.34 INFO  ==> Running mysql_upgrade
mariadb 21:26:51.35 INFO  ==> Starting mariadb in background
mariadb 21:36:51.83 ERROR ==> MySQL failed to start
xargs: bash: exited with status 255; aborting
 21:36:51.89 INFO  ==> Appending error message to motd banner
xargs: bash: exited with status 255; aborting
2024-05-29 21:36:51,913 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2024-05-29 21:36:51,915 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 22.4.2 finished at Wed, 29 May 2024 21:36:51 +0000. Datasource DataSourceGCE.  Up 630.88 seconds

**Comment by saduagyei** [comment]
Please help me how to fix this . Thanking you in advance

**Comment by jotamartos** [comment]
Hi @saduagyei,

It seems there was a problem during the initialization. If it's a fresh deployment, could you please delete it and retry with a new one? 

Thanks

**Comment by yousefmaamdoh1** [comment]
![image](https://github.com/bitnami/vms/assets/155740913/3a3f60d7-38c0-4d1d-820e-8034f66df882)
i have a same problem

**Comment by jotamartos** [comment]
Did you retry the deployment? I just launched a fresh instance with [Bitnami WordPress](https://console.cloud.google.com/marketplace/product/bitnami-launchpad/wordpress) and everything worked as expected.

![Screenshot 2024-06-12 at 09 13 33](https://github.com/bitnami/vms/assets/8791635/9a6cf897-be67-44f3-a9f2-cead9e072389)
![Screenshot 2024-06-12 at 09 13 53](https://github.com/bitnami/vms/assets/8791635/3b720ac2-d8b7-450d-885e-f593aaf4c82d)

**Comment by yousefmaamdoh1** [comment]
the first problem is the SSL certification. 
I launched a new [Bitnami WordPress](https://console.cloud.google.com/marketplace/product/bitnami-launchpad/wordpress) and it works but when I try to get SSL certification by ssh by using the command (sudo /opt/bitnami/bncert-tool)  server go down
 it doesn't work 
![image](https://github.com/bitnami/vms/assets/155740913/d4837c7d-2d8d-4eb9-9195-6890bc41f66b)
and when I suspend the VM and change the Machine configuration it works again

**Comment by yousefmaamdoh1** [comment]
the second issue after many tries that happened 
![image](https://github.com/bitnami/vms/assets/155740913/90c125ee-7e4c-4c66-9890-9057f0714a7a)
and I can't open it
@jotamartos

**Comment by jotamartos** [comment]
>I launched a new [Bitnami WordPress](https://console.cloud.google.com/marketplace/product/bitnami-launchpad/wordpress) and it works but when I try to get SSL certification by ssh by using the command (sudo /opt/bitnami/bncert-tool) server go down

Hi @yousefmaamdoh1,

That's not a deployment issue, it's an issue related to the configuration and the errors you get when restarting the services. Please take a look at the errors in the Apache's log and try to solve the issues. 

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/
