### ISSUE TITLE
[EJBCA] What is the proper way to upgrade EJBCA to a newer version without reinstalling the whole VM?

### ISSUE THREAD

**Issue by david-bojnansky** [bitnami/vms#1553]
### Describe your issue as much as you can

I successfully installed the VM, almost everything seems to work correctly (except Add End Entity in RA category - #1552), but I do not know how to properly upgrade EJBCA to a newer version in the future because the documentation is out of date (seems like Apache was replaced by Wildfly?).

**Comment by jotamartos** [comment]
As I mentioned in your other ticket, you will need to launch a new instance and migrate your data. 

https://github.com/bitnami/vms/issues/1554

You will need to check the official documentation to know what folders inside the ejbca folder you need to migrate from the old instance to the new one.

**Comment by michael298f** [comment]
Hello, 
To upgrade EJBCA to a newer version with Wildfly, follow these steps:

Backup your database.
Copy conf/*.properties from your current installation.
Merge changes from *.properties.sample into your *.properties.
Deploy the new EJBCA application using ant deployear.
If using Wildfly 24 or later, configure the PKCS12 keystore type in web.properties.
Copy TLS keystores using ant deploy-keystore.
Ensure you have the necessary database privileges.
For detailed instructions, refer to the latest official EJBCA documentation or contact their support.
Sign in to [[myPascoConnect]](https://www-mypascoconnect.com)
Best Regards
