### ISSUE TITLE
[EJBCA] Documentation for VM is out of date

### ISSUE THREAD

**Issue by david-bojnansky** [bitnami/vms#1554]
### Describe your suggestion as much as you can

The documentation seems out of date (because of Apache) and there is missing a way how to properly upgrade the EJBCA to a newer version.

**Comment by jotamartos** [comment]
You are right, Apache should not be listed in the documentation. I'll work on removing those sections from there. 

Regarding how to upgrade, you will need to launch a new instance and migrate your data from the old instance to the new one. You will need to follow the upstream's instructions about how to perform this migration. We have information here regarding how to backup the database, but you will also need to migrate the files that were generated under /opb/bitnami/ejbca

https://docs.bitnami.com/general/apps/ejbca/administration/backup-restore-mysql-mariadb/

**Comment by david-bojnansky** [comment]
Upstream you mean EJBCA doc how to migrate? Yeah, database I have connected externally already (I had to update standalone.xml database connection string). Then I have customized also truststore.jks a keystore.jks... I think it would be nice if we could upgrade somehow existing instance... For example replace ejbca.ear or something like that? I just guessing because I am not very familiar with Wildfly yet.

**Comment by jotamartos** [comment]
>Upstream you mean EJBCA doc how to migrate?

Yes! The upstream project should mention how to migrate the data to a new server 

>For example replace ejbca.ear or something like that?

That depends on the application. If the app's documentation mentions that you can just replace that file to upgrade the application, that should work when using the Bitnami solution. However, app upgrades usually consist on multiple changes, not changing just one single file, so that's why we mention that migrating the data would be easier.

**Comment by esther598** [comment]
Hello,
Certainly! When upgrading EJBCA to a newer version, follow these steps:

Backup Database: Create a backup of your EJBCA database.
Copy Configuration Files: Copy conf/*.properties files from your existing installation.
Keystore Format: Switch to PKCS12 format for keystores (.p12 files).
Deploy New EJBCA Application: Deploy a new EJBCA application (ejbca.ear).
Verify Root CA and Issuing CA Versions.
For detailed instructions, refer to the official PrimeKey documentation. If you need further assistance, feel free to ask.
[Official Site](url=https://www-flyingtogether.com)
Best Regards
Esther Smith
