### ISSUE TITLE
vSphere 6.5/ 6.7 when i create from ova: 8.13.4-0 I get error: Issues detected with selected template. Details: - -1:-1:VALUE_ILLEGAL: No supported hardware versions among [vmx-19]

### ISSUE THREAD

**Issue by dimmthewitted** [bitnami/vms#1555]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

.

### bndiagnostic was not useful. Could you please tell us why?

.

### Describe your issue as much as you can

Issues detected with selected template. Details: - -1:-1:VALUE_ILLEGAL: No supported hardware versions among [vmx-19]; supported: [vmx-04, vmx-07, vmx-08, vmx-09, vmx-10, vmx-11, vmx-12, vmx-13, vmx-14, vmx-15].

amd64 image should be no problem.  reportedly I have to edit the ovf template file to added vmx-19.

**Comment by gongomgra** [comment]
Hi @dimmthewitted,

Thanks for using Bitnami. I understand this issue can be related to our generation process using a newer version than your vSphere hypervisor, is that correct? If that's the case, is it possible for you to update the hypervisor? I see in the official release notes vSphere 6.7 was released back in 2021

https://docs.vmware.com/en/VMware-vSphere/6.7/rn/vsphere-esxi-vcenter-server-67-release-notes.html

**Comment by justin984rainey** [comment]
I also have this similar question and cannot find any proper answers, But today I found my solution here. Thank you
[Labcorp](https://www.my-labcorp.com)
