### ISSUE TITLE
Redmine home page is not accessible

### ISSUE THREAD

**Issue by sava6e** [bitnami/vms#1556]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c5b43404-f316-aa71-27d6-610a1adf64f3

### bndiagnostic output

ctlscript.sh status
apache running
mariadb running
subversion running

### bndiagnostic was not useful. Could you please tell us why?

-

### Describe your issue as much as you can

after first start (so i made some setup and entered basic data: projects and few tasks) redmine went offline and after restarting WM it is not accessible at http://192.168.68.126/

**Comment by gongomgra** [comment]
Hi @sava6e,

I checked your bndiagnostic data, and according to Apache logs, the ruby binary is missing on your system. Did you remove any file in your installation or updated any filesystem permissions?

```
[Sat Jun 01 18:21:44.026313 2024] [mpm_event:notice] [pid 484:tid 140040784176960] AH00489: Apache/2.4.59 (Unix) OpenSSL/3.0.11 SVN/1.14.3 Phusion_Passenger/6.0.20 configured -- resuming normal operations
[Sat Jun 01 18:21:44.026349 2024] [core:notice] [pid 484:tid 140040784176960] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[ N 2024-06-01 18:21:45.1546 461/T1 age/Cor/TelemetryCollector.h:531 ]: Message from Phusion: End time can not be before or equal to begin time
[ N 2024-06-01 18:21:45.1794 461/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
*** ERROR: cannot execute ruby: No such file or directory (errno=2)
```

**Comment by sava6e** [comment]
> Hi @sava6e,
> 
> I checked your bndiagnostic data, and according to Apache logs, the ruby binary is missing on your system. Did you remove any file in your installation or updated any filesystem permissions?
> 
> ```
> [Sat Jun 01 18:21:44.026313 2024] [mpm_event:notice] [pid 484:tid 140040784176960] AH00489: Apache/2.4.59 (Unix) OpenSSL/3.0.11 SVN/1.14.3 Phusion_Passenger/6.0.20 configured -- resuming normal operations
> [Sat Jun 01 18:21:44.026349 2024] [core:notice] [pid 484:tid 140040784176960] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
> [ N 2024-06-01 18:21:45.1546 461/T1 age/Cor/TelemetryCollector.h:531 ]: Message from Phusion: End time can not be before or equal to begin time
> [ N 2024-06-01 18:21:45.1794 461/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
> *** ERROR: cannot execute ruby: No such file or directory (errno=2)
> ```

thank you for your reply!
of course not! i didnt change any file in my installation. 
pls advice the best decision in my case. is it possible to repair ruby? evacuate my data and reinstall redmine?

**Comment by sava6e** [comment]
![image](https://github.com/bitnami/vms/assets/79460461/3cf8ca06-c5d6-429a-9c79-58b57e27596a)

**Comment by sava6e** [comment]
meanwhile
![image](https://github.com/bitnami/vms/assets/79460461/c6f03c15-66b5-4acb-84c6-3eee68dedecf)

**Comment by gongomgra** [comment]
There seems to be a known issue in VirtualBox for that message

https://www.virtualbox.org/ticket/19781

Regarding the Ruby issue, notice my command had an extra `/*` at the end of the Ruby installation path. Please run the command again and share the output with us.
