### ISSUE TITLE
Parse-server 4.1.0 Linux installer

### ISSUE THREAD

**Issue by pastordee** [bitnami/vms#1558]
### Describe your issue as much as you can

Okay so I’ve been running your passover version 4.14 while I’ve been able to update it to version 6 but because of nodejs version 10.4 I’m no longer able to update the latest parse server, I know you no longer do the .run installers anymore for Linux but is it possible for someone to point me in the direction of getting the original source code so I can update the nodejs, MongoDB and parse-server in there before I install it?

or can someone help me on how I can still use what I have and update the node JS and etc.
 Thank you in advance

**Comment by gongomgra** [comment]
Hi @pastordee,

Thanks for using Bitnami. As you mentioned, we no longer publish native installers, and we don't have the 4.1.0 version in our records anymore. Alternativelly, you can use the different Docker images available in DockerHub

https://hub.docker.com/r/bitnami/parse/tags

Hope it helps!

**Comment by pastordee** [comment]
And they don't have the source file line anywhere in the archives

**Comment by pastordee** [comment]
The native installer for Linux allow me to really manipulate the whole program to my project.
