### ISSUE TITLE
[bitnami/Harbor] harbor-registry communication issue with AWS S3 with tls 1.3

### ISSUE THREAD

**Issue by ranjithkumar2106** [bitnami/vms#156]
### Describe your issue as much as you can

Deploying Harbor in a private EKS cluster with bitnami/harbor helm chart and storage end as AWS S3 bucket.

bitnami-docker-harbor-registry pod should communicate to s3 bucket with tls.

- Does this image support communicating to AWS S3 bucket with tls 1.3???
- Is there anything which i have to enable to configure the communication to S3 bucket with tls 1.3...

**Comment by jotamartos** [comment]
Hi @ranjithkumar2106 ,

Thank you for using our solution. You question is related to the Bitnami Charts and this repo is about the Bitnami VMs. Please create the issue in the correct repository

https://github.com/bitnami/charts

Thanks
