### ISSUE TITLE
[bitnami/ejbca] Unable to access the EJBCA web page

### ISSUE THREAD

**Issue by pnd178** [bitnami/vms#1561]
### Name and Version

bitnami/ejbca 8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1st  after installing your ova on Proxmox and it went well.
2nd I get my firefox and I connect to the ip that the bitnami told to
3rd trying to access http or https not working
4th I noticed that the network was some problem and I can't access anything
5th I can't find the apache anywhere on the system

### What is the expected behavior?

Access the EJBCA web application

### What do you see instead?

Can't access

**Comment by jotamartos** [comment]
There was a similar ticket here, could you please take a look at it?

https://github.com/bitnami/vms/issues/1195

As we mentioned in the ticket, you can also use the /opt/bitnami/ejbca/bin/ejbca.sh script to work with the solution.

**Comment by gregory109** [comment]
Thanks for your reply it's helpful to us.  [florida blue careers](https://www-floridablue.com)

**Comment by pnd178** [comment]
Hi jotamartos,
The other issue is not the same.
Can you provide me with some kind of feedback?

Thank you very much

**Comment by pnd178** [comment]
Hi there,
I was able to login.
Thank you
