### ISSUE TITLE
Ubuntu and PHP Versions of WordPress Certification by Bitnami and Automattic

### ISSUE THREAD

**Issue by infura-git** [bitnami/vms#1564]
### Describe your issue as much as you can

Thank you for your help.
If I upgrade from Ubuntu 16.04.7 LTS to Ubuntu 22.04.4 LTS for Bitnami developed software, will it be supported?

Also, I want to install PHP8.2 on Ubuntu 16.04.7 LTS, but I am unable to do so due to the following error.

`#apt` install php8.2 -y

Reading package lists... 0%Reading package lists... 100%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 1%Reading state information... Done
E: Unable to locate package php8.2
E: Couldn't find any package by glob 'php8.2
E: Couldn't find any package by regex `'php8.2`

I am aware that the above error can be resolved by upgrading to Ubuntu 22.04.4 LTS, but I would like to confirm if there is support after the upgrade.

**Comment by gongomgra** [comment]
Hi @infura-git,

As mentioned in other tickets in this forum, it is not possible to update individual base components like PHP and/or Apache in our installations. You will have to launch a new instance with updated components and migrate your WordPress data to the new one

https://docs.bitnami.com/aws/how-to/migrate-wordpress/

**Comment by infura-git** [comment]
Thank you for your response.
Is there a migration procedure for SSL certificates?

**Comment by infura-git** [comment]
What, if any, are the reconfiguration procedures that accompany the certificate renewal confirmation procedure in the event that the certificate is not renewed?

**Comment by infura-git** [comment]
Currently on AWSMarcketPlace, when I search for [WordPress Certified by Bitnami and Automattic], I can only see Debian 12 series, is there no more Ubuntu version released?

**Comment by gongomgra** [comment]
@infura-git we no longer provide Ubuntu based images in AWS marketplace. We stopped providing them long time ago. We only provide Debian based images now. Regarding SSL certificates, I think it is easier to request a new one in the new instance directly (providing you are using Let's Encrypt). For other SSL certificates (like those generated in an independent way), you can send them to the new instance and point Apache configuration to use them.
