### ISSUE TITLE
[WordPress] Apache service fails to start after configuring SSL certificates with Let's Encrypt on Google Cloud

### ISSUE THREAD

**Issue by jpaguirrech** [bitnami/vms#1565]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d89560a4-9ba6-32b7-7e59-d89243ddf005

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Processes: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
 

 
[Processes]

One or more component's processes are not running:
```
apache not running
```
You can try to restart the process with the following command:
Press [Enter] to continue:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Jun 12 02:11:36.658194 2024] [proxy_fcgi:error] [pid 2511:tid 
140188831360704] [client **ip_address**:50717] AH01071: Got error 'PHP message: 
PHP Notice:  PHP Request Startup: file created in the system's temporary 
directory in Unknown on line 0', referer: 
https://35.199.119.232/wp-admin/post.php?post=8&action=elementor

[Wed Jun 12 02:12:18.777287 2024] [proxy_fcgi:error] [pid 2027:tid 
140187682182848] [client **ip_address**:50723] AH01071: Got error 'PHP message: 
PHP Notice:  PHP Request Startup: file created in the system's temporary 
Press [Enter] to continue:
directory in Unknown on line 0', referer: 
https://35.199.119.232/wp-admin/post.php?post=8&action=elementor

[Wed Jun 12 02:13:19.282954 2024] [proxy_fcgi:error] [pid 2027:tid 
140188990822080] [client **ip_address**:50758] AH01071: Got error 'PHP message: 
PHP Notice:  PHP Request Startup: file created in the system's temporary 
directory in Unknown on line 0', referer: 
https://35.199.119.232/wp-admin/post.php?post=8&action=elementor

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 113 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.

System Apache is running:
Press [Enter] to continue:
```
www-data   13980  0.0  0.0   3408   172 ?        Ss   02:35   0:00 
/usr/bin/htcacheclean -d 120 -p /var/cache/apache2/mod_cache_disk -l 300M -n
root       14829  0.0  0.5  14488 10216 ?        Ss   02:42   0:00 
/usr/sbin/apache2 -k graceful
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

the suggested guides are not related to my specific problem.

### Describe your issue as much as you can

I am facing an issue with the Apache service on my Bitnami WordPress instance running on Google Cloud Platform. When attempting to restart the Apache service, I receive the following error message:

Job for bitnami.apache.service failed because the control process exited with error code.
See "systemctl status bitnami.apache.service" and "journalctl -xeu bitnami.apache.service" for details.
Upon checking the system logs, I see the following:

sudo journalctl -xeu bitnami.apache.service
░░ 
░░ An ExecStart= process belonging to unit bitnami.apache.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Jun 12 02:52:59 micasa-propia-vm systemd[1]: bitnami.apache.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitnami.apache.service has entered the 'failed' state with result 'exit-code'.
Jun 12 02:52:59 micasa-propia-vm systemd[1]: Failed to start bitnami.apache.service - Bitnami service for Apache HTTP Server.
The apachectl configtest command returns Syntax OK, suggesting there are no syntax errors in the configuration files. I have also tried disabling the SSL module and restarting Apache, but the issue persists.

Here are some additional details about my configuration:

SSL Configuration File (/etc/apache2/sites-available/000-default-le-ssl.conf):

<IfModule mod_ssl.c>
<VirtualHost *:443>
  ServerAdmin webmaster@localhost
  DocumentRoot /var/www/html

  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined

  ServerName micasapropia.co
  Include /etc/letsencrypt/options-ssl-apache.conf
  ServerAlias www.micasapropia.co
  SSLCertificateFile /etc/letsencrypt/live/micasapropia.co/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/micasapropia.co/privkey.pem
</VirtualHost>
</IfModule>
SSL Certificate Permissions:

sudo ls -l /etc/letsencrypt/live/micasapropia.co/
total 4
lrwxrwxrwx 1 root root  39 Jun 12 02:42 cert.pem -> ../../archive/micasapropia.co/cert1.pem
lrwxrwxrwx 1 root root  40 Jun 12 02:42 chain.pem -> ../../archive/micasapropia.co/chain1.pem
lrwxrwxrwx 1 root root  44 Jun 12 02:42 fullchain.pem -> ../../archive/micasapropia.co/fullchain1.pem
lrwxrwxrwx 1 root root  42 Jun 12 02:42 privkey.pem -> ../../archive/micasapropia.co/privkey1.pem
-rw-r--r-- 1 root root 692 Jun 12 02:42 README
The bndiagnostic tool has found possible issues, but the suggested guides are not related to my specific problem.

I would appreciate any assistance in resolving this issue.

**Comment by jotamartos** [comment]
The tool mentioned this 

> The Apache configuration has errors:
> 
> apache2: Syntax error on line 113 of /opt/bitnami/apache2/conf/httpd.conf: 
> module log_config_module is built-in and can't be loaded

Did you take a look at the Apache's configuration and disabled that module?

**Comment by monixca345** [comment]
Thanks for this i will figure out more on this.
