### ISSUE TITLE
[Wordpress] Unable to start bitnami.service after rebooting instance

### ISSUE THREAD

**Issue by niteshkejriwal** [bitnami/vms#1566]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

95494b66-4511-0742-a58b-7b8f798c1874

### bndiagnostic output

? Apache: Found possible issues    ? Mariadb: Found possible issues    ? Connectivity: Found possible issues    ✓ Wordpress: No issues found    ✓ Resources: No issues found    ✓ Processes: No issues found    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Unable to resolve using the tool

### Describe your issue as much as you can

I rebooted a bitnami Wordpress instance on AWS and after restarting the instance, my website has gone down. The diagnostic tool says there is some error with starting the "MariaDB" service.

```
2024-06-13 10:03:31 0 [Warning] InnoDB: Log scan aborted at LSN 493872486420
24-06-13 10:03:31 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-06-13 10:03:31 0 [Note] InnoDB: Starting shutdown...
2024-06-13 10:03:31 0 [ERROR] Plugin 'InnoDB' init function returned error.
2024-06-13 10:03:31 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-06-13 10:03:31 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-06-13 10:03:31 0 [ERROR] Unknown/unsupported storage engine: InnoDB2024-06-13 10:03:31 0 [ERROR] Aborting
```

**Comment by jotamartos** [comment]
Hi, 

it seems there are different errors in the deployment. Please take a look at similar tickets in the issues section that will probably help you.

https://github.com/bitnami/vms/issues?q=is%3Aissue+%22Unknown%2Funsupported+storage+engine%22

Please also note that we do not provide 1:1 support. We can help you with basic questions and links to our documentation or the official site. However, if you require further help, we suggest you find someone in your community who can help you review the changes in the MariaDB's or Apache's configuration.

**Comment by florence0239** [comment]
> ### Platform
> AWS
> 
> ### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)
> 95494b66-4511-0742-a58b-7b8f798c1874
> 
> ### bndiagnostic output
> ? Apache: Found possible issues ? Mariadb: Found possible issues ? Connectivity: Found possible issues ✓ Wordpress: No issues found ✓ Resources: No issues found ✓ Processes: No issues found ✓ Php: No issues found
> 
> ### bndiagnostic was not useful. Could you please tell us why?
> Unable to resolve using the tool
> 
> ### Describe your issue as much as you can
> I rebooted a bitnami Wordpress instance on AWS and after restarting the instance, my website has gone down. The diagnostic tool says there is some error with starting the "MariaDB" service.
> 
> ```
> 2024-06-13 10:03:31 0 [Warning] InnoDB: Log scan aborted at LSN 493872486420
> 24-06-13 10:03:31 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
> 2024-06-13 10:03:31 0 [Note] InnoDB: Starting shutdown...
> 2024-06-13 10:03:31 0 [ERROR] Plugin 'InnoDB' init function returned error.
> 2024-06-13 10:03:31 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2024-06-13 10:03:31 0 [Note] Plugin 'FEEDBACK' is disabled.
> 2024-06-13 10:03:31 0 [ERROR] Unknown/unsupported storage engine: InnoDB2024-06-13 10:03:31 0 [ERROR] Aborting
> ```

Thanks for sharing this discussion and issue. Its helpful to me also in solving my issue. [Obamacare]([url=https://www.health-insurancemarket.com](url))
