### ISSUE TITLE
[Silverstripe] Bitnami image on AWS

### ISSUE THREAD

**Issue by lalitrane** [bitnami/vms#1567]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

54ab045a-f9b6-0391-9934-62ac67827813

### bndiagnostic output

  ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ? Php: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

Couldn't identify the Root Cause

### Describe your issue as much as you can

We have been experiencing issues with our Silverstripe Bitnami virtual machine for the past week.

We are using this machine as a backend and fetching data via GraphQL into another system. However, since last week, we have been consistently receiving 504 gateway timeout errors on all API calls. As this is an internal app, the API requests are coming from only 3-4 different IP addresses.

Apache Error log - 
FCGI: attempt to connect to Unix domain
socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
[client **ip_address**:] AH01079: failed to make connection
to backend: httpd-UDS

PHP-error log - 
WARNING: [pool www] server reached max_children setting
(100), consider raising it

Initially max_children setting was set to 50, which we now changed it to 100. but still no luck.

Could you please help us identify the issue?

**Comment by jotamartos** [comment]
Bitnami SilverStripe is no longer in the catalog. However, I suggest you take a look at this guide to investigate if there is a bot/attacker accessing your site and how to block those connections

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-connections-bots-apache/

**Comment by steven268danner** [comment]
Hello,

The 504 gateway timeout errors and the logs suggest two potential issues:

PHP max_children: Even after increasing the max_children setting, if you’re still facing issues, it might be necessary to increase it further. Monitor your server’s resource usage to determine an appropriate value.
Apache Connection: The error connecting to the Unix domain socket may indicate a problem with the PHP-FPM service or its configuration.
Consider restarting the PHP-FPM service and checking its configuration for any discrepancies. If problems persist, consult Bitnami’s support forums or AWS support for more in-depth troubleshooting.

Best regards,
[Charter Panorama
](https://www-panoramacharter.com)
