### ISSUE TITLE
Bitnami Wordpress Issue

### ISSUE THREAD

**Issue by tochi1981** [bitnami/vms#1569]
### Platform

AWS

### bndiagnostic output

```
[Tue Jun 18 02:33:56.587026 2024] [access_compat:error] [pid 396989:tid
140150503384832] [client **ip_address**:39228] AH01797: client denied by server
configuration: /opt/bitnami/wordpress/xmlrpc.php, referer: http://34.193.58.178
 [Tue Jun 18 02:34:32.299228 2024] [access_compat:error] [pid 426178:tid
140150168229632] [client **ip_address**:40112] AH01797: client denied by server
configuration: /opt/bitnami/wordpress/xmlrpc.php, referer:
http://34.193.58.178/wp-json/oembed/1.0/embed?url=http%3A%2F%2F34.193.58.178%2Fla
ser-therapy%2F
 [Tue Jun 18 02:50:21.027341 2024] [proxy_fcgi:error] [pid 426178:tid
140150411618048] [client **ip_address**:31122] AH01071: Got error 'PHP message:
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php
Press [Enter] to continue:
on line 173; PHP message: PHP Warning: Undefined array key "HTTP_HOST" in
/bitnami/wordpress/wp-config.php on line 174; PHP message: PHP Warning:
Undefined array key "HTTP_HOST" in /opt/bitnami/wordpress/wp-includes/media.php
on line 1366; PHP message: PHP Warning: Und
```

### bndiagnostic was not useful. Could you please tell us why?

Pointing to my vhosts file which does not work

### Describe your issue as much as you can

Hello,
   I was trying to configure a letsencrypt certificate on my webserver and somehow my vhosts file got messed up. Now my webserver is inaccessible. Please help

**Comment by gongomgra** [comment]
@tochi1981 can you run the bndiagnostic tool and share the generated code with us? Did you use the bncert-tool to generate the certificate? Did it return any error message?

 We also recommend you to take a look at the guide below, which explains how to manually generate and configure a Let's Encrypt certificate. It should help you to find and fix your issue.

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by tochi1981** [comment]
Hello. Yes i used the bn-cert tool to generate the certificate. It worked fine for a few weeks then it stopped working for wildcard certificates. I then tried the alternative approach to try and reinstall and it crashed the server.

How do i run the bndiagnostic tool?

**Comment by tochi1981** [comment]
Here is the result from bndiagnostic tool:

===== Begin of bndiagnostic tool output =====


    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ? Processes: Found possible issues
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found



[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3873 534 760 4 2579 3052 Swap:
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
Press [Enter] to continue:===== Begin of bndiagnostic tool output =====


[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Processes]

One or more component's processes are not running:
```
apache not running mariadb not running php-fpm not running
```
You can try to restart the process with the following command:

 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Jun 18 02:33:56.587026 2024] [access_compat:error] [pid 396989:tid
Press [Enter] to continue:
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ? Processes: Found possible issues
    ✓ Wordpress: No issues found
140150503384832] [client **ip_address**:39228] AH01797: client denied by server
configuration: /opt/bitnami/wordpress/xmlrpc.php, referer: http://34.193.58.178
 [Tue Jun 18 02:34:32.299228 2024] [access_compat:error] [pid 426178:tid
140150168229632] [client **ip_address**:40112] AH01797: client denied by server
configuration: /opt/bitnami/wordpress/xmlrpc.php, referer:
http://34.193.58.178/wp-json/oembed/1.0/embed?url=http%3A%2F%2F34.193.58.178%2Fla
ser-therapy%2F
 [Tue Jun 18 02:50:21.027341 2024] [proxy_fcgi:error] [pid 426178:tid
140150411618048] [client **ip_address**:31122] AH01071: Got error 'PHP message:
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php
on line 173; PHP message: PHP Warning: Undefined array key "HTTP_HOST" in
/bitnami/wordpress/wp-config.php on line 174; PHP message: PHP Warning:
Undefined array key "HTTP_HOST" in /opt/bitnami/wordpress/wp-includes/media.php
on line 1366; PHP message: PHP Warning: Und
```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
AH00526: Syntax error on line 5 of
Press [Enter] to continue:/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
file '/opt/bitnami/apache/conf/www.spabyrescuemd.com.crt' does not exist or is
empty
```
Please check the configuration.


===== End of bndiagnostic tool output =====


    ? Apache: Found possible issues
    ✓ Php: No issues found



[Resources]
Press [Enter] to continue:
Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3873 534 760 4 2579 3052 Swap:
0 0 0
```                                                                                                                                                        The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

e3d04835-9e9e-c3cb-6723-1443350a850f

And paste it in your Bitnami Support ticket.
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ? Connectivity: Found possible issues
-bash: ?: command not found
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ✓ Mariadb: No issues found
-bash: ✓: command not found
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ? Processes: Found possible issues
-bash: ?: command not found
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ✓ Wordpress: No issues found
-bash: ✓: command not found
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ? Apache: Found possible issues
-bash: ?: command not found
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ✓ Php: No issues found
-bash: ✓: command not found
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$ [Resources]
-bash: [Resources]: command not found
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$ Your instance has little available RAM memory.
-bash: Your: command not found
bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$ ```
>  total used free shared buff/cache available Mem: 3873 534 760 4 2579 3052 Swap:
> 0 0 0
> ```
-bash: total: command not found
-bash: 0: command not found

**Comment by tochi1981** [comment]
> Here is the result from bndiagnostic tool:
> 
> ===== Begin of bndiagnostic tool output =====
> 
> ```
> ? Resources: Found possible issues
> ? Connectivity: Found possible issues
> ✓ Mariadb: No issues found
> ? Processes: Found possible issues
> ✓ Wordpress: No issues found
> ? Apache: Found possible issues
> ✓ Php: No issues found
> ```
> 
> [Resources]
> 
> Your instance has little available RAM memory.
> 
> ```
>  total used free shared buff/cache available Mem: 3873 534 760 4 2579 3052 Swap:
> 0 0 0
> ```
> 
> You could try to increase your instance's memory. Please check your cloud provider's documentation for more information. Press [Enter] to continue:===== Begin of bndiagnostic tool output =====
> 
> [Connectivity]
> 
> Server ports 22, 80 and/or 443 are not publicly accessible. Please check the following guide to open server ports for remote access:
> 
> https://docs.bitnami.com/general/faq/administration/use-firewall/
> 
> [Processes]
> 
> One or more component's processes are not running:
> 
> ```
> apache not running mariadb not running php-fpm not running
> ```
> 
> You can try to restart the process with the following command:
> 
> $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME
> 
> [Apache]
> 
> Found recent error or warning messages in the Apache error log.
> 
> ```
> [Tue Jun 18 02:33:56.587026 2024] [access_compat:error] [pid 396989:tid
> Press [Enter] to continue:
>     ? Resources: Found possible issues
>     ? Connectivity: Found possible issues
>     ✓ Mariadb: No issues found
>     ? Processes: Found possible issues
>     ✓ Wordpress: No issues found
> 140150503384832] [client **ip_address**:39228] AH01797: client denied by server
> configuration: /opt/bitnami/wordpress/xmlrpc.php, referer: http://34.193.58.178
>  [Tue Jun 18 02:34:32.299228 2024] [access_compat:error] [pid 426178:tid
> 140150168229632] [client **ip_address**:40112] AH01797: client denied by server
> configuration: /opt/bitnami/wordpress/xmlrpc.php, referer:
> http://34.193.58.178/wp-json/oembed/1.0/embed?url=http%3A%2F%2F34.193.58.178%2Fla
> ser-therapy%2F
>  [Tue Jun 18 02:50:21.027341 2024] [proxy_fcgi:error] [pid 426178:tid
> 140150411618048] [client **ip_address**:31122] AH01071: Got error 'PHP message:
> PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php
> on line 173; PHP message: PHP Warning: Undefined array key "HTTP_HOST" in
> /bitnami/wordpress/wp-config.php on line 174; PHP message: PHP Warning:
> Undefined array key "HTTP_HOST" in /opt/bitnami/wordpress/wp-includes/media.php
> on line 1366; PHP message: PHP Warning: Und
> ```
> 
> Please check the following guide to troubleshoot server issues:
> 
> https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro rs-apache/
> 
> The Apache configuration has errors:
> 
> ```
> AH00526: Syntax error on line 5 of
> Press [Enter] to continue:/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
> file '/opt/bitnami/apache/conf/www.spabyrescuemd.com.crt' does not exist or is
> empty
> ```
> 
> Please check the configuration.
> 
> ===== End of bndiagnostic tool output =====
> 
> ```
> ? Apache: Found possible issues
> ✓ Php: No issues found
> ```
> 
> [Resources] Press [Enter] to continue: Your instance has little available RAM memory.
> 
> ```
>  total used free shared buff/cache available Mem: 3873 534 760 4 2579 3052 Swap:
> 0 0 0
> ```                                                                                                                                                        The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:
> 
> e3d04835-9e9e-c3cb-6723-1443350a850f
> 
> And paste it in your Bitnami Support ticket.
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ? Connectivity: Found possible issues
> -bash: ?: command not found
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ✓ Mariadb: No issues found
> -bash: ✓: command not found
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ? Processes: Found possible issues
> -bash: ?: command not found
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ✓ Wordpress: No issues found
> -bash: ✓: command not found
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ? Apache: Found possible issues
> -bash: ?: command not found
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$     ✓ Php: No issues found
> -bash: ✓: command not found
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$ [Resources]
> -bash: [Resources]: command not found
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$ Your instance has little available RAM memory.
> -bash: Your: command not found
> bitnami@ip-172-26-15-41:/opt/bitnami/bndiagnostic$ ```
> >  total used free shared buff/cache available Mem: 3873 534 760 4 2579 3052 Swap:
> > 0 0 0
> > ```
> -bash: total: command not found
> -bash: 0: command not found
> ```

Yes. I know it says my instance has little memory but this only started after i started having certificate issues. The instance is a t3.medium with AWS. It has 4 gigs of ram with no traffic on the site at all.

**Comment by gongomgra** [comment]
@tochi1981 according to the logs you shared, the SSL certificate is missing, which is preventing Apache server from starting

> AH00526: Syntax error on line 5 of
Press [Enter] to continue:/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
file '/opt/bitnami/apache/conf/www.spabyrescuemd.com.crt' does not exist or is
empty

Please review the SSL generation and configuration process to find the issue.
