### ISSUE TITLE
EJBCA - PK12 file gives an error

### ISSUE THREAD

**Issue by pnd178** [bitnami/vms#1573]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

none

### bndiagnostic was not useful. Could you please tell us why?

not tried

### Describe your issue as much as you can

Hi there,
I was able to download the pk12 file and when I tried to import it to FireFox it gives the following error message:

"The PKCS #12 operation failed for unknown reasons." - RSA 2048

Can you understand what is the problem?

Thank you

**Comment by gongomgra** [comment]
Hi @pnd178,

Thanks for using Bitnami. Can you confirm which asset are you using? Is it a cloud image or the virtual-machine on your local computer? Can you provide us with more information about your issue and how to reproduce it?

**Comment by pnd178** [comment]
Hi @gongomgra,
I'm using the ova file inside a proxmox vm machime.
Thank you

**Comment by pnd178** [comment]
Sorry, am talking about the EJBCA

**Comment by thomasdaniel642** [comment]
Hello,
The error message you’re encountering when importing the PKCS #12 (PFX) file into Firefox can have a few potential causes. Like
Generate a New Certificate with a Password: Firefox only accepts certificates that were exported with a password. Decompose PKCS12 Using OpenSSL: Decompose the PKCS12 file into its component parts (key, certificate, and chain of parent certificates) in PEM format using OpenSSL. Assemble them back into PKCS12 again, either with or without setting a password. Check Password Entry: Ensure that you’ve entered the correct password during the import process, including capital or lowercase letters without additional whitespaces. I hope this info useful to you.
Best Regard
[Publix Passport](https://www.publix-passport.com)
