### ISSUE TITLE
Lampstack php 8.2.x and mariadb 10.6.x

### ISSUE THREAD

**Issue by secure11** [bitnami/vms#1576]
### Describe your issue as much as you can

Hi, can you provide a download URL for an older lamp stack Virtualbox .OVA with php 8.2.x and mariadb 10.6.x. I looked at 8.2.17-r1, but it has mariadb 11.x in it, so will need to be an earlier version than that? Thank you!

**Comment by gongomgra** [comment]
Hi @secure11,

Thanks for your interest in using Bitnami. Unfortunately we don't have those OVAs available in our registries anymore. The oldest PHP 8.2.x version I could find is 8.2.14, which also includes MariaDB 11.x. However, I'm sharing the download link below

https://downloads.bitnami.com/files/stacks/lampstack/8.2.14/bitnami-lampstack-8.2.14-r3-debian-11-amd64.ova

Checking our [changelog](https://bitnami.com/stack/lamp/vboxdebian-x64-nami/changelog.txt), I see the latest 8.2.x version including MariaDB 10.x series is 8.2.10. As an alternative, you can use our container image, which can be found in our DockerHub containers registry

https://hub.docker.com/r/bitnami/php-fpm/tags?page=&page_size=&ordering=&name=8.2.10

Hope it helps!
