### ISSUE TITLE
[Wordpress Multisite] - Bug with Mariadb 11.3.2-0 on AWS region us-east-1

### ISSUE THREAD

**Issue by troussema** [bitnami/vms#1579]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

92b9c504-1814-e04f-5404-294e534eb887

### bndiagnostic was not useful. Could you please tell us why?

New mariadb version that patch the bug is not available 

### Describe your issue as much as you can

We have a problem related to mariadb version **11.3.2**, each time a plugin try to run a Delete with a Join it's take down the database, this issue was reported to mariadb and corrected on the version 11.4.2  : https://jira.mariadb.org/browse/MDEV-33533

Our problem that we have bitnami wordpress multisite running with AWS lightsail on the region : **us-east-1**
The mariadb version that available for this region is : **11.3.2-0** ( this version is concerned with the bug ) 
list : https://bitnami.com/stack/mariadb/cloud/aws/amis
Can you please update the image on this region to have the version **11.4.2** 

Thank you

**Comment by jotamartos** [comment]
Hi @troussema,

Thank you for reporting this issue. I do not see the fix in 11.4.2 

https://mariadb.com/kb/en/mariadb-11-4-2-release-notes/

However, we are working on supporting MariaDB 11.4 and will deprecate MariaDB 11.3 after that as it's no longer maintained by the team. Please stay tuned.

**Comment by troussema** [comment]
Hello again ! Ok thank you.
I saw that you updated the version from 11.3.2-0 to **11.3.2-1**
We created a new instance with the ami with this new version and everything working fine :)

**Comment by florence0239** [comment]
> ### Platform
> AWS
> 
> ### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)[Official Site](https://www.hpinstantink.com.co)
> 92b9c504-1814-e04f-5404-294e534eb887
> 
> ### bndiagnostic output
> _No response_
> 
> ### bndiagnostic was not useful. Could you please tell us why?
> New mariadb version that patch the bug is not available
> 
> ### Describe your issue as much as you can
> We have a problem related to mariadb version **11.3.2**, each time a plugin try to run a Delete with a Join it's take down the database, this issue was reported to mariadb and corrected on the version 11.4.2 : https://jira.mariadb.org/browse/MDEV-33533
> 
> Our problem that we have bitnami wordpress multisite running with AWS lightsail on the region : **us-east-1** The mariadb version that available for this region is : **11.3.2-0** ( this version is concerned with the bug ) list : https://bitnami.com/stack/mariadb/cloud/aws/amis Can you please update the image on this region to have the version **11.4.2**
> 
> Thank you

Hello,

Thanks for sharing this. I also need this help and suddenly found this reply.
I also want to thanks for the valuable reply.
