### ISSUE TITLE
[SuiteCRM] Unable to rename module labels

### ISSUE THREAD

**Issue by jpblonshine** [bitnami/vms#158]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d10601b4-48ee-c5b7-c557-844462f96ae9

### bndiagnostic output

[Thu Jul 21 16:16:10.615353 2022] [authz_core:error] [pid 686:tid 
140262080636672] [client **ip_address**:57932] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/index.php
 [Thu Jul 21 16:34:43.772388 2022] [proxy_fcgi:error] [pid 70105:tid 
140262072243968] [client **ip_address**:58797] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "error" in 
/bitnami/suitecrm/public/legacy/cache/smarty/templates_c/%%4C^4CA^4CA03677%%Renam
eModules.tpl.php on line 51PHP message: PHP Warning: Undefined array key 
"dropdown_name" in 
/bitnami/suitecrm/public/legacy/cache/smarty/templates_c/%%4C^4CA^4CA03677%%Renam
eModules.tpl.php on line 61PHP message: PHP W [Thu Jul 21 16:34:58.419133 2022] 
[proxy_fcgi:error] [pid 70105:tid 140262298846976] [client **ip_address**:58798] 
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Non-static 
method DropDownHelper::saveDropDown() cannot be called statically in 
/bitnami/suitecrm/public/legacy/modules/Studio/wizards/RenameModules.php:808
Stack trace:
#0 
/bitnami/suitecrm/public/legacy/modules/Studio/wizards/RenameModules.php(366): 
RenameModules->changeAppStringEntries()
Press [Enter] to continue:
#1 /bitnami/suitecrm/pub

### bndiagnostic was not useful. Could you please tell us why?

Could not find any permission issues.

### Describe your issue as much as you can

As an Admin I go to the admin page and scroll down to Rename Modules. I go to the project title and change it to Install and Installs. I click save and am immediately directed to a blank screen.

**Comment by jotamartos** [comment]
Hi @jpblonshine,

As I mentioned in your other ticket, this issue is highly related to the application itself so please ask in the SuiteCRM's official forums or check the official documentation to get more information. 

Thanks
