### ISSUE TITLE
[bncert]  /opt/bitnami/apache/sbin/nginx: not found

### ISSUE THREAD

**Issue by Sillytomato8** [bitnami/vms#1581]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

87381f34-fd79-5232-4560-819c9c110f7f

### bndiagnostic output

===== Begin of bndiagnostic tool output =====     
✓ Processes: No issues found    
✓ Mariadb: No issues found    
? Connectivity: Found possible issues    
✓ Php: No issues found    
? Apache: Found possible issues    
? Resources: Found possible issues    
✓ Wordpress: No issues found  

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the following guide to open server ports for remote access:
https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.

[Wed Jul 03 13:30:35.903392 2024] [access_compat:error] [pid 15260:tid 139764082542272] [client **ip_address**:58362] AH01797: client denied by server configuration: /opt/bitnami/wordpress/xmlrpc.php 
[Wed Jul 03 13:30:38.263893 2024] [access_compat:error] [pid 15260:tid 139764124505792] [client **ip_address**:58362] AH01797: client denied by server configuration: /opt/bitnami/wordpress/xmlrpc.php 
[Wed Jul 03 13:47:46.822088 2024] [autoindex:error] [pid 15260:tid 139764082542272] [client **ip_address**:58420] AH01276: Cannot serve directory /opt/bitnami/apps/letsencrypt/.well-known/: No matching DirectoryIndex (index.html,index.html,index.htm,index.php) found, and server-generated directory index forbidden by Options directive

Please check the following guide to troubleshoot server issues:
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

The Apache configuration has errors:```

AH00526: Syntax error on line 5 of
Press [Enter] to continue:
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile: file '/opt/bitnami/apache/conf/varneyslaundercenter.com.crt' does not exist or is empty```

Please check the configuration.

[Resources]

Your instance has little available RAM memory.
total used free shared buff/cache available Mem: 945 533 60 4 503 411 Swap: 634 1 633```

You could try to increase your instance's memory. Please check your cloud provider's documentation for more information. 

### bndiagnostic was not useful. Could you please tell us why?

N/A

### Describe your issue as much as you can

Spun up a LightSail instance two days ago to host a WP site.

Originally got SSL and site established using the bncert tool. Tried to changed the SSL cert, and the tool failed. Now I can't get it to run again as it is looking for the installation location.

`sudo /opt/bitnami/bncert-tool`
----------------------------------------------------------------------------Welcome to the Bitnami HTTPS Configuration tool.----------------------------------------------------------------------------

Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]: Warning: The web server configuration check failed. Please fix the configuration error: /bin/sh: 1: /opt/bitnami/apache/sbin/nginx: not found
`

I tried the few solutions I found on the old thread regarding this issue. 
Apache wont restart because it can't find the previous SSL files, which the folder appears to be empty when I look in FileZilla. I tried using the backup from before the SSL from lets encrypt was successful, but it still fails.

**Comment by krina234pestro** [comment]
I didn't catch the permissions issue when i tried. [MyFordBenefits](https://www.my-fordbenefits.com)
