### ISSUE TITLE
[Bitnami Wordpress Azure VM] some errors, and cpu usage becomes high

### ISSUE THREAD

**Issue by mark-ideatheorem** [bitnami/vms#1582]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

6ff220c4-98de-9e28-f587-0d62117ebf2a

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Wordpress: No issues found
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ✓ Php: No issues found
    ✓ Processes: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Jul 03 19:01:35.236859 2024] [proxy_fcgi:error] [pid 1274:tid 
139722038822592] [client **ip_address**:50858] AH01071: Got error 'PHP message: 
PHP Fatal error: Uncaught TypeError: Cannot access offset of type string on 
string in 
/bitnami/wordpress/wp-content/themes/platinumcondodeals-5-0-0/template-parts/cont
Press [Enter] to continue:
ent-single-floorplan.php:125
Stack trace:
#0 /opt/bitnami/wordpress/wp-includes/template.php(812): require()
#1 /opt/bitnami/wordpress/wp-includes/template.php(745): load_template()\ [Wed 
Jul 03 19:02:05.493791 2024] [proxy_fcgi:error] [pid 1274:tid 139722332567232] 
[client **ip_address**:38602] AH01071: Got error 'PHP message: PHP Fatal error: 
Uncaught TypeError: Cannot access offset of type string on string in 
/bitnami/wordpress/wp-content/themes/platinumcondodeals-5-0-0/template-parts/cont
ent-single-floorplan.php:125
Stack trace:
#0 /opt/bitnami/wordpress/wp-includes/template.php(812): require()
#1 /opt/bitnami/wordpress/wp-includes/template.php(745): load_template()
# [Wed Jul 03 19:02:18.477027 2024] [proxy_fcgi:error] [pid 1274:tid 
139722223462080] [client **ip_address**:48592] AH01071: Got error 'PHP message: 
PHP Fatal error: Uncaught TypeError: Cannot access offset of type string on 
string in 
/bitnami/wordpress/wp-content/themes/platinumcondodeals-5-0-0/template-parts/cont
ent-single-floorplan.php:125
Stack trace:
#0 /opt/bitnami/wordpress/wp-includes/template.php(812): require()
#1 /opt/bitnami/wordpress/wp-includes/template.php(745): load_template()
#
```
Press [Enter] to continue:
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2024-07-03 17:18:21 42 [ERROR] mysqld: Table './bitnami_wordpress/wp_wfstatus' 
is marked as crashed and should be repaired

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-mariadb/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

Press [Enter] to continue:
https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I am not sure why it's pointing this out

### Describe your issue as much as you can

we were experiencing 524 errors and we recently upgraded our cpu. We have yet to experience another 524 error but the backend became slow and the cpu utilization was high

**Comment by gongomgra** [comment]
Hi @mark-ideatheorem,

Thanks for using Bitnami. There seems to be an issue with one of your WordPress plugins and/or theme. Can you check them? We recommend you to contact the official developers for further help on this. I can't find any other error message in Apache logs, and the performance of the server seems to be fine. You can get more information on your server performance by checking the guide linked below

https://docs.bitnami.com/aws/faq/troubleshooting/troubleshoot-server-performance/

Apart from the above, I visited your website and it seems to be working properly. Did you manage to solve your problems?

**Comment by mark-ideatheorem** [comment]
Hi Gonzalo,

The website is fine for now, but the cpu utilization is still high. I’ve been told to try and optimize our table because mysql eats up most of the cpu resources.

Kind Regards,

Mark

--
Mark Martin
Senior Developer | Idea Theorem
***@***.******@***.***> | www.ideatheorem.com<https://www.ideatheorem.com>

***@***.***>***@***.***>
[signature_2815425962]<https://www.ideatheorem.com/>
The contents of this communication, including any attachment(s), are confidential and may be privileged. If you are not the intended recipient (or are not receiving this communication on behalf of the intended recipient), please notify the sender immediately and delete or destroy this communication without reading it, and without making, forwarding, or retaining any copy or record of it or its contents. Note: We have taken precautions against digital viruses but take no responsibility for loss or damage caused by any digital virus present or transmitted.



From: Gonzalo Gómez Gracia ***@***.***>
Date: Tuesday, July 9, 2024 at 6:29 AM
To: bitnami/vms ***@***.***>
Cc: Mark Martin ***@***.***>, Mention ***@***.***>
Subject: Re: [bitnami/vms] [Bitnami Wordpress Azure VM] some errors, and cpu usage becomes high (Issue #1582)

Hi @mark-ideatheorem<https://github.com/mark-ideatheorem>,

Thanks for using Bitnami. There seems to be an issue with one of your WordPress plugins and/or theme. Can you check them? We recommend you to contact the official developers for further help on this. I can't find any other error message in Apache logs, and the performance of the server seems to be fine. You can get more information on your server performance by checking the guide linked below

https://docs.bitnami.com/aws/faq/troubleshooting/troubleshoot-server-performance/

Apart from the above, I visited your website and it seems to be working properly. Did you manage to solve your problems?

**Comment by gongomgra** [comment]
Hi @mark-ideatheorem,

We highly recommend you to first create a full server backup that can be easily restored if anything fails.

You can run the [repair table](https://mariadb.com/kb/en/repair-table/) command, but I don't know if that would be of any help for your issue. We recommend you to ask to the official developers of the plugins with failing database tables to better understand what's the issue and how to solve it. We also recommend you to ask them about the CPU usage, just in case there is any regression on their code that is causing this.
