### ISSUE TITLE
[<BITNAMI WORDPRESS>] <Website refused to connect, permission denied on SSH browser>

### ISSUE THREAD

**Issue by mayatran97** [bitnami/vms#1584]
### Platform

VMware Marketplace

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8279599b-d97a-e5ee-15ac-8c49b0b3277e

### bndiagnostic output

    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ✓ Mariadb: No issues found
    ✓ Resources: No issues found
    ✓ Apache: No issues found
    ✓ Php: No issues found
    ? Connectivity: Found possible issues
 

 

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

I tried what the guide said but my website is still down

### Describe your issue as much as you can

My website refused to connect. I contacted Google Cloud to find out why but there is nothing wrong on their end. VM instance and SSH running fine. Their support told me to contact wordpress because most likely the issue coming from there. I checked with bitnami diagnose tool to find out why, and it says CONNECTIVITY has problem, and i did follow their instruction to create Firewall rules to open server ports for remote access but NOTHING SEEMS TO WORKS??!! 

UPDATE: apparently my SSH key expired, and wp-config file is gone. 
![Screenshot 2024-07-05 112815](https://github.com/bitnami/vms/assets/174734735/7d6f18b6-cd96-47d7-a8d5-e5d5b3ba8829)
![image](https://github.com/bitnami/vms/assets/174734735/788a3789-1a51-44ff-afd5-e378e93f2494)

**Comment by mayatran97** [comment]
Should i enable Configure logs for firewall rules?

**Comment by mayatran97** [comment]
log explorer says my SSH keys are expired. So how can i renew or update them?

**Comment by mayatran97** [comment]
how can i get SSH keys? I tried in SSH but permission denied

**Comment by mayatran97** [comment]
i cant get my ssh public or private keys cause my permission got denied 
![image](https://github.com/bitnami/vms/assets/174734735/e06d681c-796a-4e4c-91c0-895e644c40c3)

**Comment by philippirsl** [comment]
Have you tried using user sudo?

**Comment by gongomgra** [comment]
Hi @mayatran97,

Thanks for using BItnami. I have reviewed the bndiagnostic output you shared and I think there is an issue in our bndiagnostic tool because the `nc` command is not present in our images

```
-----------------------------------
Check if port 80 is externally accessible:
-----------------------------------
Running: nc -zv -w5 34.143.234.48 80
In: /opt/bitnami
Error: /tmp/tmp1720153235-536308.sh: 1: nc: not found                                                                                                                                                                                                                                   Exitcode: 127


-----------------------------------
Check if port 443 is externally accessible:
-----------------------------------
Running: nc -zv -w5 34.143.234.48 443
In: /opt/bitnami
Error: /tmp/tmp1720153236-536308.sh: 1: nc: not found
Exitcode: 127
```

Can you open a new issue in our repo?

https://github.com/bitnami/bndiagnostic/tree/main


> UPDATE: apparently my SSH key expired, and wp-config file is gone.
>log explorer says my SSH keys are expired

About your issues with SSH and wp-config files, can you provide us with more information on this? Where are you seeing these errors? We don't generate SSH keys with any expiration limit, so your initial SSH keys should still work unless you have removed them from the `authorized_keys` files.

Regarding your screenshots, notice you are trying to execute the SSH key file, which is not possible. You can inspect its content using the `cat` command. Please, do not share any screenshot of it

```
cat /home/wbg/.ssh/id_rsa
```

**Comment by gongomgra** [comment]
@mayatran97 about the website issues, it looks like there is no Apache nor Gonit services running on your system, which explains why the website can't be reached. I can't find any message in the Apache log file you shared. Do you know if any of your customizations have caused these issues? Can you verify Apache configuration by running the command below?

```
sudo apachectl -t
```

Can you try to start Gonit monitor service?

```
sudo gonit
sudo gonit status
```
