### ISSUE TITLE
[bncert] ERR_SSL_PROTOCOL_ERROR no matter what i try

### ISSUE THREAD

**Issue by pixlperfect01** [bitnami/vms#1586]
### Describe your issue as much as you can

I'm trying to run a basic nodejs webserver on an AWX lightsail & node instance, and the site itself works, but no matter what I do with bncert, I get a ssl protocol error when i actually try to connect. The reason i can't solve it though, is the tool successfully generates the certificates, but they aren't actually being applied to my website (I validated this using an online tool to try and look at the certs, but it claims there are none). I checked and the .crt and .key files are both stored in `/opt/bitnami/apache2/conf/bitnami/certs/`.

Not really sure where to go from here honestly

LOG FILE: https://pastebin.com/gNJxrmFd

**Comment by jotamartos** [comment]
Hi @pixlperfect01,

I just accessed your domain jr****.me and confirmed that it has a valid certificate. Did you resolve the issue?

**Comment by pixlperfect01** [comment]
I swear to you, I changed nothing.
I haven't even ssh'd into the server in 2 days. Sometimes I really hate that this is the career path I choose, and this is one of those times.... Thank you anyways, I don't know why it works now!
