### ISSUE TITLE
Need bitnami lamp 8.x linux AL2 installer

### ISSUE THREAD

**Issue by dpoleni** [bitnami/vms#1589]
### Describe your issue as much as you can

Was looking for native installer to download, then came know that it was stopped. Please see if you can share lamp 8.2.19 installer download link for Linux as we have challenges at our environment to use vms or cloud ami. Thanks in advance.

**Comment by florence0239** [comment]
> Was looking for native installer to download, then came know that it was stopped. Please see [choiceadvantage](https://www-choiceadvantage.com) if you can share lamp 8.2.19 installer download link for Linux as we have challenges at our environment to use vms or cloud ami. Thanks in advance.

Hello,
I understand that you’re looking for a native installer for LAMP 8.2.19 on Linux. Unfortunately, the Bitnami LAMP stack installer for version 8.x on Amazon Linux 2 (AL2) is no longer available. However, I can offer an alternative solution:

Manual Installation: You can manually set up the LAMP stack on your Linux environment. Here are the general steps:
Install Apache:
`sudo apt update
sudo apt install apache2`

Install MySQL or MariaDB: Choose either MySQL or MariaDB (a drop-in replacement for MySQL):
`sudo apt install mysql-server
# OR
sudo apt install mariadb-server`
Install PHP:
`sudo apt install php libapache2-mod-php php-mysql`
Configure Apache and PHP: Adjust Apache settings and enable PHP:
`sudo a2enmod php
sudo systemctl restart apache2`
Test Your Setup: Create a PHP info file to verify that PHP is working:
`echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/info.php`
Open your browser and navigate to http://your_server_ip/info.php to see the PHP info page.

Hope this work for you.
Best regards,
florence023

**Comment by gongomgra** [comment]
Hi @dpoleni,

As mentioned in our [blog](https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html) and in your first message, we no longer generate local installers as part of our offering. According to our [changelog](https://bitnami.com/stack/lamp/vboxdebian-x64-nami/changelog.txt), that version of PHP is pretty recent (it was released in May 2024), so we don't have any installer available for it. As an alternative you can use our [virtual machine](https://bitnami.com/stack/lamp/virtual-machine) and/or our [container images](https://hub.docker.com/r/bitnami/php-fpm/tags?page=&page_size=&ordering=&name=8.2.19).

**Comment by esther598** [comment]
Hello,
Certainly! It appears that you’re looking for a LAMP stack installer for Linux. While there isn’t a specific “LAMP 8.2.19” installer, you can manually set up a LAMP stack on your Linux server. Here are the steps:

Install Apache: Start by installing the Apache web server. On Ubuntu, you can do this with the following command:
sudo apt update
sudo apt install apache2

Configure Firewall: Allow HTTP traffic (port 80) through the firewall:
sudo ufw allow 'Apache'

Install MySQL or MariaDB: Choose between MySQL or MariaDB (a drop-in replacement for MySQL). Install the database server:
sudo apt install mysql-server

Install PHP: Install PHP and necessary extensions:
sudo apt install php libapache2-mod-php php-mysql

Test Your Setup: Create a simple PHP file in the web server’s root directory to test PHP processing:
echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/info.php

Access the PHP Info Page: Open a web browser and navigate to http://your_server_ip/info.php. You should see PHP information.
Remember to replace your_server_ip with your actual server’s IP address. This setup will give you a basic LAMP stack. If you need additional components (like Python or Perl), you can add them later.  [Official Website](https://www.floridabluefl.com)

For more detailed instructions, you can refer to the DigitalOcean tutorial or this guide.

Let me know if you need further assistance.
Best Regards
esther598
