### ISSUE TITLE
[RabbitMQ] custom node name issues

### ISSUE THREAD

**Issue by gilm0079** [bitnami/vms#159]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9549a80a-70e1-6f6e-1679-b9edceb8c4ce

### bndiagnostic was not useful. Could you please tell us why?

server itself works fine. Taking RabbitMQ off default config is not working

### Describe your issue as much as you can

Not sure if you can help with this or if I need to run this by RabbitMQ people. I used the latest OVA VM image (added to VMware host). Server boots fine and I have that configured. RabbitMQ works fine with default config. I need to change the node name for RabbitMQ to "rabbit@*server FQDN*" because the node name needs to be unique and resolve in DNS for RabbitMQ clustering to work.

I have updated /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq-env.conf with many variations to get the node name to reflect correctly, but each combination seems to cause some problem with the service starting or results in an invalid generated hostname. There is one setting I want to try, but something with bitnami keeps taking control of the loopback 127.0.0.1 host resolution on boot. 

My goal is to have a RabbitMQ node name be "rabbit@*server FQDN*" and after the bitnami boot completes I am able to run "rabbitmqctl status" and the output shows no errors and it is running.

I have tried (in rabbitmq-env.conf):
```
HOME=/opt/bitnami/rabbitmq/.rabbitmq
NODE_PORT=5672
NODENAME=rabbit
USE_LONGNAME=true
```
I changed my hostname to be the FQDN (which looks dumb in a linux prompt, vs your typical machine name) and verified
`hostname --long`
resolves the FQDN

When I run:
`rabbitmqctl status`
it is unable to connect to the node. It connects to epmd, but says node 'rabbit' is not running on the server FQDN

I also tried what I've seen is the other option for getting a FQDN in the nodename. Exclude the USE_LONGNAME and put the *nodename*@*server FQDN* as the NODENAME property. e.g.
```
HOME=/opt/bitnami/rabbitmq/.rabbitmq
NODE_PORT=5672
NODENAME=rabbit@*server FQDN*
```
Supposedly, putting a fully assembled nodename and not using the USE_LONGNAME is supposed to just use the property without trying to append a machine name to the node. I don't think it likes when periods exist in the nodename (from the FQDN) as it causes a parsing errors for rabbitmqctl. 
When I run:
`rabbitmqctl status`
I just get an error:
`%Protocol.UndefinedError{description: "", protocol: String.Chars, value: {:error, {:node_name, :short}}}`

Any ideas? DNS resolves the hostname correctly. I even have the server FQDN in the /etc/hosts. I can ping the FQDN and it resolves and pings successfully. Firewall is open for the RabbitMQ ports. Again, this works fine if I stick with the default 'rabbit@localhost'. It is just that this node name can't be used with RabbitMQ clustering.

**Comment by gilm0079** [comment]
Or is using FQDN against DNS a lost cause and the preferred route is just to define all nodes in the /etc/hosts file?
[https://www.howtoforge.com/how-to-set-up-rabbitmq-cluster-on-centos-7/](https://www.howtoforge.com/how-to-set-up-rabbitmq-cluster-on-centos-7/)

**Comment by jotamartos** [comment]
Hi @gilm0079,

Sorry for the delay here. 

>Server boots fine and I have that configured. RabbitMQ works fine with default config. I need to change the node name for RabbitMQ to "rabbit@server FQDN" because the node name needs to be unique and resolve in DNS for RabbitMQ clustering to work.

As you are trying to change the RabbitMQ's configuration and us a custom one, we suggest you ask the RabbitMQ's developers to get more information about why the changes you made are not working. Please remember that in case you need to restart the RabbitMQ server, you will need to use the /opt/bitnami/ctlscript.sh script. 

We will keep this ticket open in case any other Bitnami user configured RabbitMQ the way you want to. 

Thanks.

**Comment by gilm0079** [comment]
You can close it for now. Trying to get FQDN working was more work than was worth it and I have a small cluster so I just went the route of putting the short hostnames in each server's /etc/hosts and it works fine that way.
