### ISSUE TITLE
[Redmine] Previous versions of the Redmine by Bitnami I'd like to migrate redmine 4.x or 5.x on windows

### ISSUE THREAD

**Issue by premp1981** [bitnami/vms#1592]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

yes

### bndiagnostic was not useful. Could you please tell us why?

yes

### Describe your issue as much as you can

I'm looking for previous versions of the Redmine by Bitnami
I'd like to migrate redmine 3.x or 4.x on windows, installed with the bitnami installer to a windows server

**Comment by premp1981** [comment]
I'm looking for previous versions of the Redmine by Bitnami
I'd like to migrate redmine 4.x or 5.x on windows, installed with the bitnami installer to a windows server

**Comment by jotamartos** [comment]
These are the last 4.x and 5.x installers we released

https://downloads.bitnami.com/files/stacks/redmine/4.1.1-7/bitnami-redmine-4.1.1-7-windows-x64-installer.exe
https://downloads.bitnami.com/files/stacks/redmine/5.0.3-0/bitnami-redmine-5.0.3-0-windows-x64-installer.exe

**Comment by premp1981** [comment]
thanks for your support 

if you got 5.1.3 version , more help for me

**Comment by premp1981** [comment]
> hanged the title ~previous versions of the Redmine by Bitnami I'd like to migrate redmine 4.x~

if chance please provide the Bitnami Redmine 5.1.3 version

**Comment by jotamartos** [comment]
We didn't release an installer for Redmine 5.1.x. As you may know, we removed support for the installers long ago. If you want to use Redmine 5.1.x, you will need to use the virtual machines we provide at https://bitnami.com/stack/redmine/virtual-machine

**Comment by premp1981** [comment]
ok thanks lot

**Comment by ramonreyes11** [comment]
Looking for the same thank you! [my AARP Medicare](https://www.myaarpmedicarehealth.com)

**Comment by premp1981** [comment]
already running bitnami redmine 4.0.4 version 
now i installed bitnami redmine 5.0.3 version , 
database copied , trying to login not connected 
showing error INAVLID FROM AUTHORITY TOKEN
from old version to new version what all are the files need to copy  ?

kindly help me

**Comment by jotamartos** [comment]
>from old version to new version what all are the files need to copy ?

We have a generic guide here: https://docs.bitnami.com/general/apps/redmine/administration/upgrade/

If you have any other app-related question, we suggest you ask in the Redmine's forums to know how to migrate your data from your current version to the new one.

**Comment by premp1981** [comment]
during the login 
error : invalid from authority token 
please help me

**Comment by premp1981** [comment]
production log :
can't verify CSRF token authority

**Comment by jotamartos** [comment]
That's an app-related issue so we suggest you ask in the official forums of Redmine to get more information. The official documentation should also help you.
