### ISSUE TITLE
Bitnami Matomo 5.1 AWS image not available 

### ISSUE THREAD

**Issue by coderxx05** [bitnami/vms#1593]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

NA

### bndiagnostic was not useful. Could you please tell us why?

New Image not available 

### Describe your issue as much as you can

The new release of Bitnami Matomo 5.1 is not reflecting on AWS Marketplace. It still shows the old 5.0.3 release. Please help check

**Comment by esther598** [comment]
Thanks for the info I will try to figure it out for more. [Official Website](https://www-mypascoconnect.com)

**Comment by gongomgra** [comment]
@coderxx05 sorry for the inconveniences. I have pinged our engineering team about this. We will keep you posted

**Comment by coderxx05** [comment]
Hello.. Thanks.. I see the team attempted new release 5 days ago but it is still not getting updated for AWS Cloud. Appreciate the efforts being put in by team. Kudos 👏

**Comment by gongomgra** [comment]
Hi @coderxx05,

You can get the AWS AMIs ID of the new Matomo 5.1.1 images in our website at https://bitnami.com/stack/matomo/cloud/aws/amis

Hope it helps!
