### ISSUE TITLE
Lamp website running very slow

### ISSUE THREAD

**Issue by vasundharak** [bitnami/vms#1594]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

.

### bndiagnostic output

✓ Database: No issues found
    ? Apache: Found possible issues
    ✓ Resources: No issues found
 
 
1) Found recent error messages in the Apache error log.
```
[Tue Jul 16 05:38:21.593514 2024] [proxy_fcgi:error] [pid 28242:tid 139874334111488] [client 106.192.10.84:28309]
 AH01071: Got error 'PHP message: PHP Notice:  Undefined index: txtId in /opt/bitnami/apache2/htdocs/eschoolexper
t.com/apppayment/standard/index.php on line 107
'
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

### bndiagnostic was not useful. Could you please tell us why?

Not related to my issue

### Describe your issue as much as you can

The website is taking a lot of time to login and load the pages. The cpu usage is sometimes 200%
![image](https://github.com/user-attachments/assets/c9275f25-4153-4418-b438-2f2fd13c9c2e)

**Comment by krina234pestro** [comment]
Hello,

Bitnami Troubleshooting might not address your specific problem directly, but it’s a good resource for broader troubleshooting.


Best Regard

[Vanilla Visa gift cards](https://www.vanilla-giftcardbalance.com)

**Comment by vasundharak** [comment]
> Hello,
> 
> Bitnami Troubleshooting might not address your specific problem directly, but it’s a good resource for broader troubleshooting.
> 
> Best Regard
> 
> [Vanilla Visa gift cards](https://www.vanilla-giftcardbalance.com)

I tried but still the website is slow.

**Comment by jotamartos** [comment]
>[Tue Jul 16 05:38:21.593514 2024] [proxy_fcgi:error] [pid 28242:tid 139874334111488] [client 106.192.10.84:28309]
 AH01071: Got error 'PHP message: PHP Notice:  Undefined index: txtId in /opt/bitnami/apache2/htdocs/eschoolexper
t.com/apppayment/standard/index.php on line 107

PHP errors and logging are probably the root cause of the performance issue. Could you please take a look at the errors you see in the Apache's log?

**Comment by vasundharak** [comment]
I cross checked, But this is not the issue

**Comment by jotamartos** [comment]
You can take a look at the PHP-FPM log (/opt/bitnami/php folder) and try increasing the resources PHP-FPM uses in case it's reaching the limits (/opt/bitnami/php/etc/memory.conf file).

You can also investigate if there is any bot/attacker accessing your site by taking a look at this guide 

https://docs.bitnami.com/general/infrastructure/lamp/troubleshooting/deny-connections-bots-apache/

Apart from that, you will need to continue monitoring your deployment. As I mentioned above, you deployed a custom app and you'll also need to review its code to know if it's an app-related issue.
