### ISSUE TITLE
[Odoo 17] Discuss Chat not working in real-time

### ISSUE THREAD

**Issue by webdevpriyank** [bitnami/vms#1595]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

83728dc6-cebe-b8be-8fb7-16f234857fae

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ? Apache: Found possible issues

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Jul 16 04:32:31.859370 2024] [proxy:error] [pid 470092:tid 140570714400512]
Press [Enter] to continue:
(70008)Partial results are valid but processing is incomplete: [client
**ip_address**:63094] AH01095: prefetch request body failed to 127.0.0.1:8069
(127.0.0.1) from 15.158.39.233 (), referer: https://erp.mobileartsme.com/web

[Tue Jul 16 04:32:31.859741 2024] [proxy:error] [pid 478740:tid 140569388943104]
(70008)Partial results are valid but processing is incomplete: [client
**ip_address**:17842] AH01095: prefetch request body failed to 127.0.0.1:8069
(127.0.0.1) from 15.158.39.205 (), referer: https://erp.mobileartsme.com/web

[Tue Jul 16 04:32:31.860940 2024] [proxy:error] [pid 512628:tid 140569640691456]
(70008)Partial results are valid but processing is incomplete: [client
**ip_address**:63126] AH01095: prefetch request body failed to 127.0.0.1:8069
(127.0.0.1) from 15.158.39.233 (), referer: https://erp.mobileartsme.com/web

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

### bndiagnostic was not useful. Could you please tell us why?

Not able to solve the problem need more guidance

### Describe your issue as much as you can

Discuss real-time chat is not working we have to refresh the page to see the chat and current messages.

**Comment by adamsnell543** [comment]
Thanks for the info I will try to figure it out for more. [Secure Spend](https://www.securespend.com.co)

**Comment by gongomgra** [comment]
Hi @webdevpriyank,

Thanks for using Bitnami. There are other users who reported this very same issue in the past, and they shared a solution for it. Can you check it in the thread linked below?

https://github.com/bitnami/vms/issues/1357

We have an internal task to fix it on our side, but due to other priorities we didn't have time to work on this yet. Sorry for the inconveniences.

**Comment by katelyn2598** [comment]
tthe issues, but didn't worked out I also tried this solution https://github.com/bitnami/vms/issues/1357, I also [read more](https://www.yourtexas-benefits.com) about this issues but still it din't work out Please help

**Comment by Marlene495Hadley** [comment]
Hello!
Ensure server ports 22, 80, and 443 are open. Check Apache logs for proxy errors and follow the troubleshooting guide. Verify your chat app’s real-time configuration,  [taco bell survey](https://www.tellthebell.com.co) possibly using AWS services like SNS or AppSync. If issues persist, contact AWS support for further help. Does this clarify the next steps for you? 

Regards,
Marlene

**Comment by gongomgra** [comment]
Hi @webdevpriyank 

We have released a new revision of our images including the updated Apache and Odoo configuration for this to work. You can find the new AWS AMI IDs in our website https://bitnami.com/stack/odoo/cloud/aws/amis

Hope it helps!

**Comment by webdevpriyank** [comment]
How I can configure the changes in that old package as I am not able to upgrade the instance so somehow if you can guide me to do changes that can help Discyss app to work would be great please help.

**Comment by gongomgra** [comment]
@webdevpriyank as mentioned in one of my previous messages, you can follow the steps that another user shared on how to fix the issue in an already running instance

https://github.com/bitnami/vms/issues/1357#issuecomment-2087999384
