### ISSUE TITLE
[Odoo] Looking for Odoo 9 9.0.20170915-0 virtual machine

### ISSUE THREAD

**Issue by kmlew** [bitnami/vms#1596]
### Describe your issue as much as you can

Hello,

I am looking for the Odoo 9 version 9.0.20170915-0 virtual machine.  

Best regards,
k

**Comment by gongomgra** [comment]
Hi @kmlew,

Thanks for your interest in using Bitnami. I'm afraid that is a very old version (from 2017) and we do not have it on our records anymore. As an alternative, we recommend you to check our docker images in DockerHub, where you will find some tags for the Odoo 9.x series

https://hub.docker.com/r/bitnami/odoo/tags

**Comment by krina234pestro** [comment]
Hello,

Finding a specific version of Odoo, such as 9.0.20170915-0, can be a bit challenging, especially if you’re looking for a pre-configured virtual machine. Odoo’s source code is available on GitHub. You can clone the repository and check out the specific version tag you need.

Best Regard
[Maxim Time Clock](https://www.maxim-timeclock.com)

**Comment by kmlew** [comment]
Thank you both.  I'll give both ideas a go and hopefully one of them will yield the desired result.

Cheers!
k
