### ISSUE TITLE
Website not running after installing the ssl

### ISSUE THREAD

**Issue by srikanthkatta0** [bitnami/vms#1599]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

sudo /opt/bitnami/bndiagnostic-tool

### bndiagnostic output

I didn't found any issues , but after installing the ssl not able to see application running

### bndiagnostic was not useful. Could you please tell us why?

not able to find

### Describe your issue as much as you can

tergerg

**Comment by gongomgra** [comment]
Hi @srikanthkatta0,

Thanks for using Bitnami. Can you share more details about your issue? Which changes did you perform to your server's configuration?

Additionally, can you run the bndiagnostic tool and share the generated code with us?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by gongomgra** [comment]
@srikanthkatta0 I see you have opened another ticket for the same ([issues/1602](https://github.com/bitnami/vms/issues/1602)). I'm closing this one as duplicated.
