### ISSUE TITLE
[WordPress] wp-content files being renamed with .php.suspected, cannot access Admin

### ISSUE THREAD

**Issue by docmedia2** [bitnami/vms#160]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

not-working

### bndiagnostic was not useful. Could you please tell us why?

bndiagnostic tool started but did not complete

### Describe your issue as much as you can

I tried logging into the admin dashboard two days ago, and saw a "This page isn't working" sencoten.org is currently unable to handle this request. HTTP 500 error.

After checking to ensure that all the services were still running, and that I hadn't run out of resources, I started troubleshooting the plugins, php memory limit, theme etc. to see if I could access, still no luck.

When I was able to SSH into the instance, I saw several files that ended with php.suspected appended to their names. After searching the issue I was able to generate a list of affected files, and learned that this may be some kind of malware attack the list of files is attached.

![Screen Shot 2022-07-21 at 12 55 09 PM](https://user-images.githubusercontent.com/109764206/180308398-1fd7820c-bb9a-4abd-8376-96b8c05691bf.png)

I also tried running the diagnostic tool, which ended up just hanging. I tried this three times.

I'm not sure what to do next and I feel out of my depth with this issue. Additionally I managed to disable all of my plugins via SSH, using this tutorial https://www.youtube.com/watch?v=QWTifQAnoYk - however, that also disabled two core plugins that my theme uses, and I'm not sure how to re-enable them without dashboard access.

Any help or steps I could take to get this resolved would be a real life-saver. Please help!

-Dave

**Comment by jotamartos** [comment]
Hi @docmedia2 ,

Thank you for using our solution. That's a specific question about the application so we suggest you ask in the official forums of the application to get more information about that. The app's documentation should also describe how to troubleshoot this issue.

https://wordpress.org/support/

However, we will also keep this ticket open in case any Bitnami user ran into the same issue recently.

Thanks
