### ISSUE TITLE
pgAdmin unable to connect to server : connection timeout expired

### ISSUE THREAD

**Issue by kim7406** [bitnami/vms#1601]
### Describe your issue as much as you can

Not able to connect to DB on the bitnami VM on Azure using pgAdmin 4
SSH tunnel available with putty

On the bitnami VM the postgresql.conf file was updated with listen_addresses = '*'

In pgAdmin register server with connection details and SSH tunnel details

Always get the same error unable to connect to server : connection timeout expired
what am I missing?

**Comment by kim7406** [comment]
I found my mistake, I need to put localhost in the connection tab.

**Comment by Marlene495Hadley** [comment]
> ### Describe your issue as much as you can
> Not able to connect to DB on the bitnami VM on Azure using pgAdmin 4 SSH tunnel available with putty
> 
> On the bitnami VM the postgresql.conf[MyLabcorp](https://www.my-labcorp.com) file was updated with listen_addresses = '*'
> 
> In pgAdmin register server with connection details and SSH tunnel details
> 
> Always get the same error unable to connect to server : connection timeout expired what am I missing?

Does your query solved?

Marlene

**Comment by gongomgra** [comment]
Hi @kim7406,

Thanks for using Bitnami. I'm glad you found a fix for your issue!
