### ISSUE TITLE
Wordpress - Fatal Error X2 Fatal error: Uncaught Error: Class "WP_REST_Revisions_Controller" & Fatal error: Uncaught Error: Call to a member function set() on null in /opt/bitnami/wordpress/wp-includes/l10n.php

### ISSUE THREAD

**Issue by nick941741** [bitnami/vms#1603]
### Platform

AWS Lightsail Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d6938c38-8d1f-c79c-2862-ca96e69edfa3

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 453 337 8 13 107 86 Swap: 634 
76 558
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Wordpress]
Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-file-permissions/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat Jul 27 08:07:46.845285 2024] [proxy_fcgi:error] [pid 747:tid 
139621736314624] [client **ip_address**:50858] AH01071: Got error 'PHP message: 
PHP Fatal error: Uncaught Error: Class "WP_REST_Revisions_Controller" not found 
in 
/opt/bitnami/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-global-styles
-revisions-controller.php:17
Stack trace:
#0 /opt/bitnami/wordpress/wp-settings.php(285): require()
#1 /opt/bitnami/wordpress/wp-config.php(100): require_once('...')
#2 /opt/bitnami/word [Sat Jul 27 08:12:47.744099 2024] [proxy_fcgi:error] [pid 
1083:tid 139620620609280] [client **ip_address**:58710] AH01071: Got error 'PHP 
message: PHP Fatal error: Uncaught Error: Class "WP_REST_Revisions_Controller" 
not found in 
/opt/bitnami/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-global-styles
-revisions-controller.php:17
Stack trace:
#0 /opt/bitnami/wordpress/wp-settings.php(285): require()
#1 /opt/bitnami/wordpress/wp-config.php(100): require_once('...')
#2 /opt/bitnami/wordp [Sat Jul 27 08:20:25.642390 2024] [proxy_fcgi:error] [pid 
Press [Enter] to continue:
1083:tid 139620763285248] [client **ip_address**:34284] AH01071: Got error 'PHP 
message: PHP Fatal error: Uncaught Error: Class "WP_REST_Revisions_Controller" 
not found in 
/opt/bitnami/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-global-styles
-revisions-controller.php:17
Stack trace:
#0 /opt/bitnami/wordpress/wp-settings.php(285): require()
#1 /opt/bitnami/wordpress/wp-config.php(100): require_once('...')
#2 /opt/bitnami/word
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-bots-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Attached

### Describe your issue as much as you can

I'm getting 2 fatal errors on my Wordpress site, they are
```
Fatal error: Uncaught Error: Class "WP_REST_Revisions_Controller" not found in /opt/bitnami/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-global-styles-revisions-controller.php:17 Stack trace: #0 /opt/bitnami/wordpress/wp-settings.php(285): require() #1 /opt/bitnami/wordpress/wp-config.php(100): require_once('...') #2 /opt/bitnami/wordpress/wp-load.php(50): require_once('...') #3 /opt/bitnami/wordpress/wp-blog-header.php(13): require_once('...') #4 /opt/bitnami/wordpress/index.php(19): require('...') #5 {main} thrown in /opt/bitnami/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-global-styles-revisions-controller.php on line 17

Fatal error: Uncaught Error: Call to a member function set() on null in /opt/bitnami/wordpress/wp-includes/l10n.php:856 Stack trace: #0 /opt/bitnami/wordpress/wp-includes/l10n.php(959): load_textdomain() #1 /opt/bitnami/wordpress/wp-includes/class-wp-fatal-error-handler.php(49): load_default_textdomain() #2 [internal function]: WP_Fatal_Error_Handler->handle() #3 {main} thrown in /opt/bitnami/wordpress/wp-includes/l10n.php on line 856
```
I was thinking I could just re-install Wordpress, but didn't was worried that this would overwrite some core bitnami files and config......

Any help appreciated.

**Comment by gongomgra** [comment]
Hi @nick941741,

Thanks for using Bitnami. As detected by the bndiagnostic tool, there seems to be an issue with one of your WordPress plugins, theme, or any other customization that is causing those internal errors. We highly recommend you to open a new question in the official WordPress forums for further help on this

https://wordpress.org/support/forums/

**Comment by nick941741** [comment]
What makes you think its a plugin?

**Comment by gongomgra** [comment]
Hi @nick941741,

I was just guessing it can be a plugin, a theme, or any other modification to WordPress source code you may have performed. The bndiagnostic tool tries to get the list of plugins you have installed and it failed, that's why I thought about plugins, but it may be caused by any other reasons though. Did you have any chance to ask in the official WordPress forums?

**Comment by nick941741** [comment]
Ah, OK, sorry. 
I managed to find a backup and restored the site using that, I've moved it away from AWS now too.
