### ISSUE TITLE
[<bncert>] <An error occurred when applying configurations>

### ISSUE THREAD

**Issue by Grugar96** [bitnami/vms#1604]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e24d3a2e-824c-1cd9-e996-b6458f77e4f4

### bndiagnostic output

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 969 684 130 27 332 285 Swap: 
649 35 614
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat Jul 27 19:49:57.475946 2024] [proxy_fcgi:error] [pid 3116:tid 3357] [client 
**ip_address**:49762] AH01071: Got error 'PHP message: PHP Warning: Undefined 
array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php on line 100; PHP 
message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 101; PHP message: PHP Warning: 
Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php 
on line 716; PHP message: PHP Warning: Undefined array [Sat Jul 27 
20:10:01.155669 2024] [proxy_fcgi:error] [pid 3116:tid 3363] [client 
**ip_address**:61001] AH01071: Got error 'PHP message: PHP Warning: Undefined 
array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php on line 100; PHP 
message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 101; PHP message: PHP Warning: 
Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php 
on line 716; PHP message: PHP Warning: Undefined array [Sun Jul 28 
00:37:59.431419 2024] [proxy_fcgi:error] [pid 3116:tid 3345] [client 
**ip_address**:60000] AH01071: Got error 'PHP message: PHP Warning: Undefined 
array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php on line 100; PHP 
message: PHP Warning: Undefined array key "HTTP_HOST" in 
Press [Enter] to continue:
/bitnami/wordpress/wp-config.php on line 101; PHP message: PHP Warning: 
Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php 
on line 716; PHP message: PHP Warning: Undefined array key

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible.
```
### bndiagnostic was not useful. Could you please tell us why?

the same issue was posted already but has not been resolved. https://github.com/bitnami/vms/issues/1569

### Describe your issue as much as you can

i used bncert tool to create ssl certification. but faced with an error.
Failed steps:
* Running Let's Encrypt: Error creating certificates

following which, I was looking how to resolve the issue in this forum. I'm new here and as far as I looked there were no direct resolution for this.

**Comment by gongomgra** [comment]
Hi @Grugar96,

Thanks for using Bitnami. I visited your website at `wisd***stic.in` and both the HTTP to HTTPS and the SSL certificate worked fine. I also verified the SSL certificate was issued by Let's Encrypt, as you can see in the screenshot below. Can you give us more information about your issue or if you have managed to fix it?

![Screenshot 2024-07-29 at 12 41 53](https://github.com/user-attachments/assets/e19d88a9-3f8a-42bc-80d4-3507968b0e43)

**Comment by Grugar96** [comment]
I tried it after some time and it worked. Thanks for following up on this.

**Comment by gongomgra** [comment]
@Grugar96 thanks for letting us know. I'm glad it worked for you after some retries. I'm closing this ticket as solved.
