### ISSUE TITLE
[Wordpress] Redirected you too many times

### ISSUE THREAD

**Issue by Vegas-1** [bitnami/vms#161]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bitnami-wordpress-info-20220721-221643-16297

### bndiagnostic output

? ssl:error - rejecting client intiated renegotiation
? core:error - invalid URI
?autoindex:error - Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/
? proxy_fcgi:error - Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function get_header() in /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/twentytwentyone/404.php:12\nStack trace:\n#0 {main}\n  thrown in /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/twentytwentyone/404.php on line 12'

### bndiagnostic was not useful. Could you please tell us why?

I could not find any errors in the diagnostic that shed light on the "redirected you too many times"

### Describe your issue as much as you can

Everything was working fine.  Then, I got an email message indicating the Certificate would expire soon, so I ran /opt/bitnami/bncert-tool to renew.  Since then, the website is not accessible.  Keep getting the error "_url-name_ redirected you too many times"   I have two separate Wordpress instances running on AWS Lightsail.  

bndiagnostic data is attached.  I could not find any errors in the diagnostic that shed light on the "redirected you too many times"

[bitnami-wordpress-info-20220721-221643-16297.zip](https://github.com/bitnami/vms/files/9163619/bitnami-wordpress-info-20220721-221643-16297.zip)

**Comment by jotamartos** [comment]
Hi @Vegas-1,

There is a mismatch between the domain Apache is using and the one that uses WordPress. 

```
HTTP/1.1 301 Moved Permanently
Date: Fri, 22 Jul 2022 10:08:53 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Location: https://www.ccartistsguildvegas.com/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 301 Moved Permanently
Date: Fri, 22 Jul 2022 10:08:54 GMT
Server: Apache
X-Powered-By: PHP/7.4.13
X-Redirect-By: WordPress
X-Frame-Options: SAMEORIGIN
Location: https://ccartistsguildvegas.com/
Content-Type: text/html; charset=UTF-8
```

As you can see here, Apache redirects to the www domain and WordPress redirects back to the non-www domain. Please run the bncert tool and configure the non-www domain as main domain (and the redirections) or update the wp-config.php file to use the www domain as WP_HOME and WP_SITEURL

**Comment by jotamartos** [comment]
Note: I removed the "<" and ">" characters from the title, those are just placeholders. Please take that into account for the future.

**Comment by Vegas-1** [comment]
Problem solved.  Thank you.
