### ISSUE TITLE
[Redmine] can't install virtualbox guest additon

### ISSUE THREAD

**Issue by mwdqaqc** [bitnami/vms#1610]
### Describe your issue as much as you can

Click install guest addition: nothing happens

![image](https://github.com/user-attachments/assets/5f0b90c5-832f-4c62-a72e-b9d6b13d6ef3)

**Comment by mwdqaqc** [comment]
![image](https://github.com/user-attachments/assets/1108cfaa-558b-450c-8827-1a19a440935b)

**Comment by mwdqaqc** [comment]
https://docs.bitnami.com/virtual-machine/faq/configuration/install-virtualbox-guest-additions/

Try to follow the URL and get the above error.

host OS: windows 10. Guest: Debian from redmine standalone image

**Comment by jotamartos** [comment]
That's a VirtualBox-related question. Please take a look at the forums and online guides to troubleshoot the issue.

Thanks
