### ISSUE TITLE
need Moodle last version of 3.11+ image vmware or Oralce virtual Box download Link

### ISSUE THREAD

**Issue by natsang-mfu** [bitnami/vms#1611]
### Name and Version

moodle bitnami image

### What architecture are you using?

amd64

### What steps will reproduce the bug?

**need Moodle last version of 3.11+ image vmware or Oralce virtual Box download Link**

### What do you see instead?

need download link

**Comment by darrin569** [comment]
To obtain the latest version of Moodle 3.11+ for VMware or Oracle VirtualBox, visit the official Bitnami Moodle page at Bitnami Moodle. On the page, you can find various versions of Moodle available for download. Select the version you need and choose the appropriate deployment option, either VMware or Oracle VirtualBox. Follow the provided link to download the virtual machine image, typically in .ova format for your chosen platform. If you have difficulty finding a specific version or download link, consider reaching out to Bitnami support or checking their archives for older releases. For the most current information, always refer to Bitnami’s official resources.

**Comment by natsang-mfu** [comment]
can you find direct link download ?

**Comment by gongomgra** [comment]
@natsang-mfu please find below the download link for the required Moodle 3.11.12 OVA file

https://downloads.bitnami.com/files/stacks/moodle/3.11.12-0/bitnami-moodle-3.11.12-0-linux-vm-debian-11-x86_64-nami.ova

**Comment by natsang-mfu** [comment]
> @natsang-mfu please find below the download link for the required Moodle 3.11.12 OVA file
> 
> https://downloads.bitnami.com/files/stacks/moodle/3.11.12-0/bitnami-moodle-3.11.12-0-linux-vm-debian-11-x86_64-nami.ova

ohhhh thank you,

**Comment by gongomgra** [comment]
@natsang-mfu glad to be of help! We are closing this ticket as solved.
