### ISSUE TITLE
[Redmine] Request for older version of bitnami package for Redmine virtual machines

### ISSUE THREAD

**Issue by ms-zakkin** [bitnami/vms#1612]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

no

### bndiagnostic was not useful. Could you please tell us why?

no

### Describe your issue as much as you can

Dear bitnami team,

I would like to request an older version of bitnami package for Redmine virtual machines:

bitnami-redmine-5.0.9

Highly appreciated if you could provide a download link. Thank you in advance!

**Comment by jotamartos** [comment]
We didn't release Redmine 5.0.9, this is the last Redmine 5.0.x OVA we published 

https://downloads.bitnami.com/files/stacks/redmine/5.0.6/bitnami-redmine-5.0.6-r17-debian-11-amd64.ova
