### ISSUE TITLE
[Moodle] opt directory disappeared and site is down

### ISSUE THREAD

**Issue by itcloudserver** [bitnami/vms#1618]
### Describe your issue as much as you can

Suddenly the site is down when we are fixing the vulnerabilty related to Polyfill.js. While checking we found, opt directory disappeared. We need help on restoring the application.

**Comment by itcloudserver** [comment]
Hi, Can somone help on this please.

**Comment by jotamartos** [comment]
>While checking we found, opt directory disappeared.

If you removed the /opt/bitnami folder, you probably lost all the information. If you are using a recent VM, you will probably find the files you need to restore the info inside the /bitnami/ folder. You should be able to launch a fresh VM and replace the files under that folder to try to restore the data. However, you will probably need to apply extra changes for the app to use the data if you use a newer version.
