### ISSUE TITLE
[SuiteCRM] VMware server not accessible

### ISSUE THREAD

**Issue by danielberma** [bitnami/vms#1619]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

no

### bndiagnostic was not useful. Could you please tell us why?

Not used 

### Describe your issue as much as you can

Hello
I've an issue with the virtual machine for SuiteCRM. After a day or two it stops responding to connections, making it non accessible. Up until then it works great. I have tried it on multiple occassions during July but now giving up. I cant access it externally or internally (192.168.1.xxx). When trying to access it, it says the server is available but not responding and I can see it in my router - so its definitely there but dont know how to access it. Any ideas?

Thank you

**Comment by jotamartos** [comment]
> I cant access it externally or internally (192.168.1.xxx).

Can you access the command line and get the IP of the VM? Please note that the IP can change after a reboot and you need to use the new IP to access the application

```
sudo ifconfig
```

**Comment by danielberma** [comment]
Hi,
Thank you for the response. Actually, I cant. Says the password is wrong. 
![vmware2](https://github.com/user-attachments/assets/bb3051d3-e0cb-4fbb-a0aa-114739fecee2)
![vmware1](https://github.com/user-attachments/assets/fed49dec-3b10-4063-abd3-4acda78a1866)

This is how it looks like though. I am not a console person per se but the IP is clearly there.
I created a new instance of SuiteCRM and its been running during the weekend and managed several reboots and what not. Cant tell what I did differently, so fingers crossed!

**Comment by jotamartos** [comment]
> I am not a console person per se but the IP is clearly there.

That information is generated during the first boot, if you reboot the VM, the IP may change and the text you showed won't be changed. 

Please access the console using bitnami/bitnami as username/password and run the command I posted above to get the new IP

**Comment by danielberma** [comment]
As I said, I can't. It says the password is wrong (tried with bitnami/bitnami). However, the IP is correct - at least that is what the router says. But no matters, I made a new machine and it seems to work (knock on wood) so problem solved :)
