### ISSUE TITLE
[wordpress] I need to review plugins installing versions from log files of server

### ISSUE THREAD

**Issue by q8-uc** [bitnami/vms#162]
### Describe your issue as much as you can

hi, i have got a problem with a payment gateway company while my website payment gateway has approved some wrong payments as success
the problem now is that they are saying my site was using old woocommerce and its from my side
while i have the latest woocommerce and wordpress versions always
the problem now i have the logs and i cant approve that my plug ins versions are latest
is it possible to approve it? while they are saying SQL Injection was used to pass in
i have the logs of initiating the website uploaded and your help will be valuable
[access_log.zip](https://github.com/bitnami/vms/files/9164688/access_log.zip)

**Comment by jotamartos** [comment]
Hi @q8-uc ,

Thank you for using our solution. That's a specific question about the application so we suggest you ask in the official forums of the application to get more information about that. The app's or plugin's documentation should also describe how to achieve what you want to, so please take a look at it too. 

https://wordpress.org/support/

However, we will also keep this ticket open in this forum in case any Bitnami user configured the application they way you want to. 

Thanks
