### ISSUE TITLE
[Archivematica] Please add

### ISSUE THREAD

**Issue by ispardoa** [bitnami/vms#1620]
### Describe your suggestion as much as you can

Please add the latest version of archivematica, that would make me really happy.

Thank you so much

**Comment by gongomgra** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

**Comment by carrodher** [comment]
Hi, unfortunately, after an internal review and due to other priorities, this solution was not considered for inclusion in the catalog in the short/mid-term.

We apologize for the inconvenience. We will be sure to reconsider it in the future.

Thanks for your suggestion!
