### ISSUE TITLE
Launch Forem Docker / AWS / Azure

### ISSUE THREAD

**Issue by Josephrp** [bitnami/vms#1622]
### Describe your suggestion as much as you can

New Bitnami Image: Forem
- Ref: https://developers.forem.com/getting-started/installation/linux
- Demo: https://dev.to

**Comment by gongomgra** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

**Comment by Josephrp** [comment]
thank you so much @gongomgra and @carrodher , y'all are the best !

**Comment by carrodher** [comment]
Hi, unfortunately, after an internal review and due to other priorities, this solution was not considered for inclusion in the catalog in the short/mid-term.

We apologize for the inconvenience. We will be sure to reconsider it in the future.

Thanks for your suggestion!
