### ISSUE TITLE
[Redmine] version 4.1.1 installer for linux

### ISSUE THREAD

**Issue by nkaminkami** [bitnami/vms#1623]
### Describe your issue as much as you can

Could you please let me download the redmine 4.1.1 installer for linux box?

**Comment by gongomgra** [comment]
@nkaminkami thanks for using Bitnami. Unfortunately, the installer you requested is too old and we do not have it on our records any more. As an alternative, we recommend you to use our Redmine container for version 4.1.1 that you can find in Dockerhub at https://hub.docker.com/r/bitnami/redmine/tags?page=&page_size=&ordering=&name=4.1.1

**Comment by nkaminkami** [comment]
I'll try using the link you suggested.
Thank you for your reply.
