### ISSUE TITLE
[<application>] <title>website not working after installing new theme and plugins

### ISSUE THREAD

**Issue by vhopaitsa** [bitnami/vms#1624]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8bc38650-285d-a040-71fe-decaa3c4c14a

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 950 415 67 5 467 358 Swap: 634 
1 633
```
Press [Enter] to continue:
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.

System Apache is running:
```
root 613 0.0 0.4 6592 4076 ? Ss 06:28 0:00 /usr/sbin/apache2 -k start www-data 
619 0.0 0.7 1211244 7720 ? Sl 06:28 0:00 /usr/sbin/apache2 -k start
Press [Enter] to continue:
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

suggested guides are not related with my issue

### Describe your issue as much as you can

Website not working after installing new theme and plugins. I have the following bndiagnostis tool report. Can anyone help figure out what the problem is and how to fix it? Thanks in advance for your help.

**Comment by gongomgra** [comment]
@vhopaitsa thanks for using Bitnami. As detected by the bndiagnostic tool, the Apache server can't be started because its configuration is incorrect. Please correct the issue below by commenting out the mentioned line in the config file, and then restart the services for changes to take effect

```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```

You can restart the services running the next command:

```
sudo /opt/bitnami/ctlscript.sh restart
```
