### ISSUE TITLE
[Wordpress Multi-Tier GCP ] Error establishing database connection - BDD has been lost after restarting the nodes (0 and 1).

### ISSUE THREAD

**Issue by darkladen** [bitnami/vms#1626]
### Describe your issue as much as you can

Hello !!!

I have set up 2 "Wordpress Multi-Tier GCP" servers and the second one, when I restarted the nodes, I could not access the web again because it showed the error "Error establishing a database connection". After trying to get the wordpress site up and not getting it, what I did was to enter the BDD server of node-1, and reconfigure the root access to the server. When I managed to enter the MariaDB server, I could identify that the user "bn_wordpress" and the bdd "bitnami_wordpress" did not exist. I had to create the user and the database again with all the necessary permissions to allow the connection until it finally worked. The problem occurred again when I was down the server in GCP (for lack of a payment) and when the payment was normalized, when loading the web I realize that it happened again that the BDD was lost. I do not know if it does not manage to raise some folder where the BDD is originally created with all the bitnami service but this is very serious because after much work on this server, everything that was advanced for a long time was lost. If it is not because I did a wordpress backup some time ago we would be dead and we would be losing our biggest customer. 

This bitnami service does not give any security.

Any solution ?

**Comment by darkladen** [comment]
Hello, Is there no troubleshooting support for your own services here?

**Comment by gongomgra** [comment]
Hi @darkladen,

Thanks for using Bitnami and sorry for the delay on getting back to you. it is weird that restarting the WordPress nodes ends up producing issues with the MariaDB database. Did you modify anything in your server or its configuration that can be causing this? Can you also run our bndiagnostic tool and share the generated code with us?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/
