### ISSUE TITLE
[redmine] OVA 5.1.3-0-r03 how to move redmine to a sub-URI

### ISSUE THREAD

**Issue by fenix32dark** [bitnami/vms#1627]
### Describe your issue as much as you can

I would like to use the Apache server provided in the OVA to run two additional apps (GLPI and another custom php app) and an index page.

Is it mandatory to change the configuration to something like http://www.mydomain.com/redmine/? https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_on_subdirectory_(sub-URI)_on_Apache

I chose this example because I am trying to migrate from a Windows installation to the OVA.

Could you explain how to configure the OVA to make this http://www.mydomain.com/redmine/ possible?

I appreciate your help in advance.

**Comment by fenix32dark** [comment]
Here my workaround. I am not sure if this is the best option, but works.

Edit the file ```/opt/bitnami/apache/conf/vhosts/redmine-vhost.conf``` 

To look like this

```shell
PassengerPreStart http://localhost:80/
<VirtualHost 127.0.0.1:80 _default_:80>
  ServerName www.example.com
  ServerAlias *
  
  DocumentRoot /opt/bitnami/apache/htdocs
  
  Alias /redmine /opt/bitnami/redmine/public
  
  <Directory "/opt/bitnami/redmine/public">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
    PassengerEnabled on
    PassengerBaseURI /redmine
    PassengerAppRoot /opt/bitnami/redmine
  </Directory>
  
  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
  
  RailsEnv production
  # Fixes errors caused by Passenger not loading gems from Bundler, e.g.:
  # 'You have already activated strscan 3.0.1, but your Gemfile requires strscan 3.0.4. (...)'
  SetEnv RUBYOPT "-r bundler/setup"
```

**Comment by gongomgra** [comment]
Hi @fenix32dark thanks for using Bitnami and for sharing your solution. I think it is a valid configuration for both Apache and Passenger. I'm sure it would be of help to other users in the future!
