### ISSUE TITLE
Wordpress not showing Edit Page in top header bar

### ISSUE THREAD

**Issue by jaycova** [bitnami/vms#1628]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

44dc6d38-2dd8-3712-9a20-61fbe4cf1871

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ? Resources: Found possible issues
    ✓ Wordpress: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Tue Aug 13 17:22:45.391853 2024] [proxy_fcgi:error] [pid 832245:tid 
140369605723840] [client **ip_address**:60000] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php 
on line 100; PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 101; PHP message: PHP Warning: 
Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php 
on line 716; PHP message: PHP Warning: Unde [Tue Aug 13 21:21:40.847789 2024] 
[proxy_fcgi:error] [pid 832245:tid 140369689650880] [client 
**ip_address**:54479] AH01071: Got error 'PHP message: PHP Warning: Undefined 
array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php on line 100; PHP 
message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 101; PHP message: PHP Warning: 
Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php 
on line 716; PHP message: PHP Warning: Un [Tue Aug 13 22:36:39.560910 2024] 
[proxy_fcgi:error] [pid 839672:tid 140689941575360] [client 
**ip_address**:28586] AH01071: Got error 'PHP message: PHP Warning: Undefined 
array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php on line 100; PHP 
message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 101; PHP message: PHP Warning: 
Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php 
on line 716; PHP message: PHP Warning: Und
Press [Enter] to continue:
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-conne
ctions-bots-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 974 672 64 59 461 301 Swap: 
634 53 581
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
 
Press [Enter] to continue:

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Not really it is not finding my issue

### Describe your issue as much as you can

I am working on a new site, and I don't have SSL installed yet, but the Edit Page is not showing when I am in admin mode.

**Comment by jaycova** [comment]
a little update. I have reinstalled the theme, then deactived all the plugins and now even with the Twenty twenty-four theme I don’t see edit page at the top. Very odd.

**Comment by gongomgra** [comment]
Hi @jaycova,

I have checked your bndiagnostic information and according to it your are running out of resources. Can you try using a bigger instance to check if that solves your issues? Can you also verify the `edit page` button appears right after the initialization process has finished without any further customization?

```
-----------------------------------
Display amount of free and used memory in the system
-----------------------------------
Running: free -m
In: /opt/bitnami

Output:

               total        used        free      shared  buff/cache   available
Mem:             974         666          69          61         463         307
Swap:            634          63         571
```

**Comment by jaycova** [comment]
@gongomgra Thanks for replying.

This morning, I increased the memory, and it did not change. I got disgusted and deleted the instance. I installed a new copy of Bitnami WordPress on AWS, and I am using just the bare install with no new themes. I still don't see the edit button. There seems to be some permission issues but not sure what it is saying.


I am no longer fighting for memory as I am using a t3.small vs. t3.micro. 

Is this just an issue with WordPress 6.6.1?


===== Begin of bndiagnostic tool output =====

 
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ✓ Resources: No issues found
    ✓ Wordpress: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Fri Aug 23 16:03:49.394950 2024] [proxy_fcgi:error] [pid 922:tid 
140165100066496] [client **ip_address**:52791] AH01071: Got error 'line 173; PHP 
message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173; PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173; PHP message: PHP Warning: chmod(): Operation not permitted in [Fri Aug 23 
16:03:49.407729 2024] [proxy_fcgi:error] [pid 922:tid 140165100066496] [client 
**ip_address**:52791] AH01071: Got error ': Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173; PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173; PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/cla [Fri Aug 23 16:03:49.544678 2024] 
[proxy_fcgi:error] [pid 922:tid 140165100066496] [client **ip_address**:52791] 
AH01071: Got error 'rdpress/wp-admin/includes/class-wp-filesystem-direct.php on 
line 173; PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173; PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173; PHP
Press [Enter] to continue:
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

                                    
Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

6357166a-0bee-1453-ca20-490b934365d6

**Comment by jaycova** [comment]
Ok so I just upgraded another website also using Bitnami wordpress which was on 6.5.5 so I upgraded it to 6.6.1 the same as the website I am having issues with. That still shows the edit page button at the top, so this is not something that was taken out of 6.6.1. I am just confused and lost and it is important to me to have that button.

**Comment by gongomgra** [comment]
Hi @jaycova,

Glad to know it worked for you updating another server. To try to reproduce your issue, I launched a fresh new server with WordPress 6.6.1 and I see the "Edit" button in the list of posts published in my website as you can see in the screenshot below.

![Screenshot 2024-08-28 at 14 27 43](https://github.com/user-attachments/assets/76bc423e-2205-4cff-adac-e4591dd5eeab)

Is that the button you are missing on your server? Can it be caused by your custom theme or plugins?

**Comment by gongomgra** [comment]
@jaycova for security reasons, can you attach the images to your post the same way I did in my previous message instead of sharing them via a PDF file? I'm removing the download links from your post as well. Thanks in advance.

**Comment by jaycova** [comment]
My appologies. Here are the two. Wiith the first one you see there is the edit page in the middle of the screen 
but in the second there is not. Both are Wordpress 6.6.1 The second now has a theme but even when I first installed the server before adding any plugins it was missing the edit page button

![shadow screen](https://github.com/user-attachments/assets/21f3e7d9-c14e-4285-a5bc-b10f936579e9)
![gibbs screen](https://github.com/user-attachments/assets/7867b9c8-863c-4018-8f4c-6da276021b30)

**Comment by gongomgra** [comment]
@jaycova can you ask in the official WordPress forums for further help on this? I have launched a fresh server, logged into `/wp-admin` and visited the website. It is true in the welcome page the "Edit page" button do not exists, but it does if I visit any real page, like the `/sample-page`

![Screenshot 2024-09-02 at 11 44 59](https://github.com/user-attachments/assets/f1165d76-287c-43c5-aa66-2b372a293e7c)
