### ISSUE TITLE
[Node] Angular.json permission issue on Bitnami Node image

### ISSUE THREAD

**Issue by tednice75** [bitnami/vms#1629]
### Describe your issue as much as you can

I am using a Binami Node image on AWS Lightsail. I am trying to edit my angular.json file but I don't have permission. How do I change permission on this file?

**Comment by jotamartos** [comment]
>I am trying to edit my angular.json file but I don't have permission. How do I change permission on this file?

That's a sysadmin-related question and it's out of the scope of this support forum. Please take a look at this guide to know more about how the permissions configuration work in Linux and find someone in your community who can help you with this type of issues in the future 

https://www.redhat.com/sysadmin/linux-file-permissions-explained

Thanks
