### ISSUE TITLE
[ghost] Using environmental variables in Ghost config

### ISSUE THREAD

**Issue by AndrasSandor** [bitnami/vms#163]
### Describe your issue as much as you can

Hey,

I'm using the ghost on AWS (bitnami-ghost-4.20.4-6-linux-debian-10-x86_64-hvm-ebs-nami), and don't want the database password to be hardcoded to config.production.json. 

Something like:
....
```
      "database": "bitnami_ghost",
      "user": "user",
      "password": "$DB_PASSWORD"
```
...

In this form it's obviously not working. Is there any other way to do this?

**Comment by jotamartos** [comment]
Hi @AndrasSandor,

Thank you for using our solution. That's a specific question about the application so we suggest you ask in the official forums of the application to get more information about that. The app's documentation should also describe how to achieve what you want to, so please take a look at it too. 

However, we will also keep this ticket open in this forum in case any Bitnami user configured the application they way you want to. 

Thanks
