### ISSUE TITLE
[Redmine] How to get 3.4.6 version Redmine by Bitnami for Linux

### ISSUE THREAD

**Issue by Kiki-who** [bitnami/vms#1631]
### Describe your issue as much as you can

I'm looking for 3.4.6 version Redmine by Bitnami for Linux,could someone send me one?Thanks a lot!

**Comment by Kiki-who** [comment]
Hello？Any one here？

**Comment by gongomgra** [comment]
@Kiki-who thanks for using Bitnami. Unfortunately, the installer you requested is too old (from 2018), and we do not have it on our records any more. As an alternative, we recommend you to use our Redmine container for version 3.4.6 that you can find in Dockerhub at https://hub.docker.com/r/bitnami/redmine/tags?page=&page_size=&ordering=&name=3.4.6
