### ISSUE TITLE
[<LAMP>] SSL for multiple domains

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1632]
### Describe your issue as much as you can

Hi,

I would like to have multiple websites on my LAMP instance. I want to know:

1. How I can enable SSL for multiple domains?
2. When I add a new website later, how can I enable SSL for that domain too?

Your support would be appreciated.

**Comment by huzanf** [comment]
Hi,
Looking forward for an update.

**Comment by huzanf** [comment]
Hi @gongomgra 
Waiting for your response.

**Comment by gongomgra** [comment]
@huzanf we recommend you to follow the alternative approach tutorial in our documentation website to generate and configure a single certificate for all of your domains at once, or to follow it multiple times so you can generate and configure individual SSL certificates for each domain. 

About the new domain addition, you will need to generate a new single certificate for the updated list of domains, or simply generate a new independent SSL certificate for the new app with the alternative approach workflow. Using one option or the other is up to you and your custom scenario.

You can find all the required information in the next guide:
https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/
