### ISSUE TITLE
Bitnami Redmine: Is it possible to Upgrade to Apache version 2.4.59 or later?

### ISSUE THREAD

**Issue by yhn-ncs** [bitnami/vms#1633]
### Describe your issue as much as you can

Hi Bitnami Redmine Support,

Currently we are using the below production version.

Environment:
  Redmine version                5.1.0.stable
  Ruby version                   3.0.6-p216 (2023-03-30) [x86_64-linux]
  Rails version                  6.1.7.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::InlineAdapter

SCM:
  Subversion                     1.14.2
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  no plugin installed

From VMS scanning report, we need to upgrade Apache version 2.4.59 or later. I come across the below URL. Is it possible to upgrade? Could current Redmine be crashed? Kindly help.

[https://linuxcapable.com/how-to-install-apache-on-debian-linux/](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flinuxcapable.com%2Fhow-to-install-apache-on-debian-linux%2F&data=05%7C02%7Cyehtut.naung%40ncs.com.sg%7C2d6ff8b4487a40cd0ac408dcc1b2590f%7Cca90d8f589634b6ebca99ac468bcc7a8%7C0%7C0%7C638598218995518949%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=FKYDv2hiaijfYGcOpvoxkzufH4WyHQOL96Zy8igIwlk%3D&reserved=0)

Thanks  & Regards,
Ye

**Comment by susan789wolfe** [comment]
Upgrading Apache to version 2.4.59 or later is definitely possible, and it should not crash your current Redmine setup if done correctly [my AARP Medicare](https://www.myaarpmedicarehealth.com/)
Here are the steps you can follow to upgrade Apache on your Debian-based system:

Backup Your Current Configuration:
Before making any changes, ensure you have a backup of your current Apache configuration and Redmine data .
Update Package Lists:
Run the following commands to update your package lists:
sudo apt update

Install Apache 2.4.59 or Later:
Use the following commands to install the latest version of Apache:
sudo apt install apache2

Verify Apache Version:
After installation, verify the Apache version to ensure it has been updated:
apache2 -v

Restart Apache:
Restart the Apache service to apply the changes:
sudo systemctl restart apache2

Check Redmine Configuration:
Ensure that your Redmine configuration is still intact and that the site is accessible. Check the Apache error logs if you encounter any issues:
sudo tail -f /var/log/apache2/error.log

Potential Issues and Solutions
Module Compatibility: Ensure that all Apache modules you are using are compatible with the new version. Some modules might need to be re-enabled or reconfigured.
Configuration Changes: Review any changes in Apache configuration syntax or directives between versions. You can refer to the Apache upgrade documentation for detailed information

**Comment by yhn-ncs** [comment]
> Upgrading Apache to version 2.4.59 or later is definitely possible, and it should not crash your current Redmine setup if done correctly [my AARP Medicare](https://www.myaarpmedicarehealth.com/) Here are the steps you can follow to upgrade Apache on your Debian-based system:
> 
> Backup Your Current Configuration: Before making any changes, ensure you have a backup of your current Apache configuration and Redmine data . Update Package Lists: Run the following commands to update your package lists: sudo apt update
> 
> Install Apache 2.4.59 or Later: Use the following commands to install the latest version of Apache: sudo apt install apache2
> 
> Verify Apache Version: After installation, verify the Apache version to ensure it has been updated: apache2 -v
> 
> Restart Apache: Restart the Apache service to apply the changes: sudo systemctl restart apache2
> 
> Check Redmine Configuration: Ensure that your Redmine configuration is still intact and that the site is accessible. Check the Apache error logs if you encounter any issues: sudo tail -f /var/log/apache2/error.log
> 
> Potential Issues and Solutions Module Compatibility: Ensure that all Apache modules you are using are compatible with the new version. Some modules might need to be re-enabled or reconfigured. Configuration Changes: Review any changes in Apache configuration syntax or directives between versions. You can refer to the Apache upgrade documentation for detailed information

Thank you so much for your helpful comments. I will try in UAT.

Regards,
Ye

**Comment by yhn-ncs** [comment]
Hi @gongomgra 

Do you have also any comment?

Thanks & Regards,
Ye

**Comment by gongomgra** [comment]
Hi @yhn-ncs,

Thanks for using Bitnami. As mentioned in other tickets of this forum, updating base components of our assets is not possible. Also note that the Apache server in our images is not installed from system repositories but built from source code, so you can not update it that way either. You will need to launch a new instance with the updated components and then migrate the app data there. Hope it helps!

**Comment by yhn-ncs** [comment]
Hi @gongomgra 

Thank you for your comment. I will update you back.

Regards
Ye
