### ISSUE TITLE
[WordPress] Can't Start all services after renewing SSL certificate Bitnami lightsail

### ISSUE THREAD

**Issue by isophel** [bitnami/vms#164]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

380aa3b8-d113-1dc7-d7cd-0ee14f6c8be4

### bndiagnostic output

==== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Jul 21 15:17:25.890403 2022] [ssl:emerg] [pid 29519:tid 140182117346176] 
SSL Library Error: error:0909006C:PEM routines:get_name:no start line 
(Expecting: EC PARAMETERS) -- Bad file contents or format - or even just a 
forgotten SSLCertificateKeyFile?
 [Thu Jul 21 15:17:25.890419 2022] [ssl:emerg] [pid 29519:tid 140182117346176] 
Press [Enter] to continue:
SSL Library Error: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no 
certificate assigned
 [Thu Jul 21 15:17:25.890425 2022] [ssl:emerg] [pid 29519:tid 140182117346176] 
AH02312: Fatal error initialising mod_ssl, exiting.

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I want to see how to go about these issues

### Describe your issue as much as you can

The server can't be reached, I can't start the apache and all other services after renewing the letsencrypt SSL certificate

**Comment by jotamartos** [comment]
Hi @isophel ,

It seems you didn't use our HTTPS configuration tool and followed the alternative approach to generate the SSL certs. Please follow the guide again to generate a new cert and configure Apache with it

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
