### ISSUE TITLE
[Bitnami WordPress GCP] What's the difference between /bitnami/wordpress and /opt/bitnami/wordpress?

### ISSUE THREAD

**Issue by everydayrice** [bitnami/vms#1643]
### Describe your issue as much as you can

As the title states, what is the difference between /bitnami/wordpress and /opt/bitnami/wordpress?

Also, I noticed something similar with /opt/bitnami/apache/htdocs and /opt/bitnami/apache2/htdocs. Any file I upload to apache2 is automatically mirrored in apache. How does this work?

Where exactly is the "root" directory? As in the directory where I can upload a .txt or .html or any file and be able to access it by going to mywebsite.com/file.txt.

**Comment by gongomgra** [comment]
Hi @everydayrice,

Thanks for using Bitnami. `/opt/bitnami/apache2` is a symlink to `/opt/bitnami/apache` for backward compatibility. Regarding `/bitnami/wordpress` and `/opt/bitnami/wordpress`, the former is used for persistence of the WordPress config file and the `wp-content` folder in our containers and VMs (in case you mount another volume to `/bitnami`), while the latter contains the real WordPress application. You can place your custom files in the `/opt/bitnami/wordpress` directory for them to be available via HTTP requests.

Hope it helps!

**Comment by everydayrice** [comment]
Thanks for the detailed response!
