### ISSUE TITLE
[<LAMP>] High server usage

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1648]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

---

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

My instance gets high usage although the traffic on the website is as good as zero. Not sure why this is happening.

Since the server usage is so high and inaccessible, I cannot even generate the BNSupport code.

Kindly support

**Comment by gongomgra** [comment]
Hi @huzanf,

We recommend you to take a look to our server performance troubleshooting guide at https://docs.bitnami.com/aws/faq/troubleshooting/troubleshoot-server-performance/

**Comment by huzanf** [comment]
Hi @gongomgra 
I saw [this link](https://docs.bitnami.com/aws/faq/configuration/block-suspicious-ip/) too on the link you shared above. I would like more support on this.

1. How do I see the list of IPs that are added?
2. How can I check from what IP what are they trying to access?

**Comment by gongomgra** [comment]
@huzanf the guide you shared uses the internal server firewall to block access, but it is a bit error-prone and also very easy to lose server access if you block your IP address by mistake. We recommend you to block the suspicious IP addresses via Apache configuration, which means they can't access your website, but you will still have access to port 22 (SSH) in case you block your own IP address or range by mistake. 

https://docs.bitnami.com/virtual-machine/apps/wordpress/troubleshooting/deny-connections-bots-apache/
