### ISSUE TITLE
[WordPress] Failed to start LSB: bitnami init script, Apache configuration Error after SSL Certificate Update attempt.

### ISSUE THREAD

**Issue by docmedia2** [bitnami/vms#1649]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

57c79d01-df57-c25d-3cab-cecfacc433e0

### bndiagnostic output

===== Begin of bndiagnostic tool output =====    
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Sep 01 11:42:54.132010 2024] [authz_core:error] [pid 21136:tid 
140566234793728] [client **ip_address**:59408] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
 [Sun Sep 01 12:17:09.127760 2024] [proxy_fcgi:error] [pid 20812:tid 
140566268364544] (70008)Partial results are valid but processing is incomplete: 
Press [Enter] to continue:
[client **ip_address**:53566] AH01075: Error dispatching request to : (reading 
input brigade)
 [Sun Sep 01 12:33:22.855331 2024] [authz_core:error] [pid 21136:tid 
140566234793728] [client **ip_address**:35456] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
The Apache configuration has errors:
```
AH00526: Syntax error on line 5 of 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile: 
file '/opt/bitnami/apache/conf/yardbots.ca.crt' does not exist or is empty
```
Please check the configuration.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
Press [Enter] to continue:
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 987 351 70 7 564 466 Swap: 634 
0 634
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I ran bndiagnostic tool, there are things I don't understand well enough to tackle myself.

### Describe your issue as much as you can

I ran into this issue after trying to reinstall an SSL Certificate after having to adjust my DNS Records after switching domain registrars.

These are the steps as best as I can remember that created this error:

1. I Changed DNS settings at the new registrar to point to AWS servers.
2. Setup a new DNS Zone on AWS and attached the instance to the new zone
3. I then noticed an "SSL Error" due to records not matching those on the certificate file (I think)
4. Tried renewing the SSL Certificate using the bncert-tool
5. Ran that successfully, but it gave me an error on the conical (www) domain because I had only setup the non-www version in the DNS Zone
6. Stopped the services
7. Went back and created the www version, and ran bncert-tool again, then received an message:Please type a directory that contains a Bitnami installation. The default installation directory for Linux installers is a directory inside /opt.

This is where it gets foggy...

9.  Thought that maybe I didn't restart the services, which was true, so I tried restarting with sudo /opt/bitnami/ctlscript.sh start, and received:
Starting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.
systemctl status bitnami service gave me: 
● bitnami.service - LSB: bitnami init script
   Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2024-09-01 20:38:13 UTC; 1min 16s ago
  Process: 2468 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
Failed to start LSB: bitnami init script.

11. So I tried checking the service status using sudo /opt/bitnami/ctlscript.sh status and received the following message: Cannot find any running daemon to contact. If it is running, make sure you are pointing to
 the right pid file (/var/run/gonit.pid)

Here's where I am now stuck.

**Comment by jotamartos** [comment]
The error is clear, the certificate file you configured doesn't exist

```
AH00526: Syntax error on line 5 of 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile: 
file '/opt/bitnami/apache/conf/yardbots.ca.crt' does not exist or is empty
```

Please ensure the file exists and restart Apache to start using it.

**Comment by docmedia2** [comment]
Hello Juan, thank you for your assistance. I have confirmed that the file exits, but it is empty. Is there a way to create a new certificate file to replace the old one? As I mentioned in the first part of my ticket, another certificate and key file exists for the www version of the domain, which is not empty and looks good.

If I cannot replace the empty cert file and key file, can I remove them and just use the www version?

Thanks again for your time.
-Dave

**Comment by docmedia2** [comment]
Hello Juan, I was able to fix this issue by following the alternative process for SSL [](https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach).

Once the certificates were installed, it allowed me to restart services, and everything seems to be working now. Thanks for putting me on the right path.

-Dave
