### ISSUE TITLE
[<LAMP>] port 22: Operation timed out

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1652]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1ae54dea-303b-b798-f303-96def376661f

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Processes: No issues found
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ✓ Resources: No issues found
 

 
[Mariadb]

Found recent error messages in the MariaDB error log:
```
2024-09-08 7:56:49 508 [Warning] Aborted connection 508 to db: 'xyzfoundation1' 
user: 'xyzfoundation1' host: 'localhost' (Got an error reading communication 
packets)

```
Please check the following guide to troubleshoot MariaDB issues:
Press [Enter] to continue:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-mariadb/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Sep 08 06:18:01.828647 2024] [proxy_fcgi:error] [pid 4198:tid 4438] [client 
**ip_address**:12450] AH01071: Got error 'PHP message: PHP Deprecated: Creation 
of dynamic property GW_Choice_Count::$_args is deprecated in 
/opt/bitnami/xyzfoundation/wp-content/themes/xyz/functions.php on line 702'
 [Sun Sep 08 06:19:00.288182 2024] [proxy_fcgi:error] [pid 4601:tid 4692] 
[client **ip_address**:47764] AH01071: Got error 'PHP message: PHP Deprecated: 
Creation of dynamic property GW_Choice_Count::$_args is deprecated in 
/opt/bitnami/xyzfoundation/wp-content/themes/xyz/functions.php on line 702', 
Press [Enter] to continue:
referer: https://staging.xyzfoundation.net/wp-admin/
 [Sun Sep 08 06:19:29.565029 2024] [proxy_fcgi:error] [pid 4601:tid 4695] 
[client **ip_address**:50682] AH01071: Got error 'PHP message: PHP Deprecated: 
Creation of dynamic property GW_Choice_Count::$_args is deprecated in 
/opt/bitnami/xyzfoundation/wp-content/themes/xyz/functions.php on line 702', 
referer: https://staging.xyzfoundation.net/wp-admin/

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

Suddenly my instance was not accessible. I had to stop the instance and then restart. Upon running the bnsupport tool, I got these error. Kindly assist.

**Comment by gongomgra** [comment]
Hi @huzanf,

I have visited your website and it seems to be working fine. Did you manage to solve the issues? Regarding the log messages you shared, they seem to be related to one of your WordPress plugins. We highly recommend you to open a question in the official WordPress forums or in the plugin's developers community for further help on this.
