### ISSUE TITLE
[RabbitMQ] RabbitMQ Management "User can only log in via localhost"

### ISSUE THREAD

**Issue by mppdebu** [bitnami/vms#1653]
### Describe your issue as much as you can

Im following these steps in order to create a rabbit mq VM in Azure.
1. Create Bitnami VM in Azure Marketplace
2. Leaving all settings on default, except using Authentication Type. I'm selecting Password
3. Click Create
4. Adding inbound rules -> 5672 and 15672
![Screenshot 2024-09-10 220510](https://github.com/user-attachments/assets/5e71677f-df2c-4f4a-aa9c-d162d2c2ce3d)
![Screenshot 2024-09-10 220607](https://github.com/user-attachments/assets/8d048951-59cb-446b-9212-4e8aac841ea0)
![Screenshot 2024-09-10 220629](https://github.com/user-attachments/assets/1075ddbb-28b9-46bd-9db9-a799332067ef)
5. I'm getting the credentials with cat ./bitnami_credentials
6. When browsing to RabbitMQ Management, i'm getting "User can only log in via localhost"
![Screenshot 2024-09-10 220744](https://github.com/user-attachments/assets/6e092010-ad37-488e-a741-e5d6849f4a6a)
 
How can I make sure that I can log in with

**Comment by jotamartos** [comment]
That's due to the [loopback_users configuration parameter](https://www.rabbitmq.com/docs/configure#configuration-files), you can edit it and restart the service for the changes to be applied. However, for security reasons, we suggest you use a SSH tunnel to access the web interface.
