### ISSUE TITLE
[WordPress] Demo Content Import Not Working

### ISSUE THREAD

**Issue by cartessius** [bitnami/vms#1656]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

651a69eb-1427-94d6-6ddd-966637df80e7

### bndiagnostic output

    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ? Resources: Found possible issues
    ✓ Wordpress: No issues found

### bndiagnostic was not useful. Could you please tell us why?

did not help me resolve the issue

### Describe your issue as much as you can

I am using Bitnami on top of AWS. 
And on top I am using Uncode Wordpress theme.
Form the theme I want to upload a demo content. However, this is constantly throwing an error. 
I tried changing permissions, setting max parameters for memory and number of vars, tried instructions where bndiagnostic points me, but without any success. 
The wordpress theme is one of the bestsellers, and the developer ensures me that the issue must be on the server side. So, I would appreciate if you can help me resolve this so I can import the content.
Thanks!

**Comment by jotamartos** [comment]
Thank you for using Bitnami. That's a paid theme and we can't work on reproducing the issue. This post explains how to reset the permissions configuration in WordPress, did you do so?

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

You can also try to reproduce the issue in a fresh instance, but as I mentioned before, we can't do much more as we can't work on reproducing the issue.
