### ISSUE TITLE
[WordPress] Bitnami Wordpress

### ISSUE THREAD

**Issue by Idea-Theorem** [bitnami/vms#1657]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a130fd83-8556-6be9-4191-b124ebc0e993

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ? Wordpress: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ✓ Php: No issues found
    ✓ Processes: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Sep 12 18:18:36.554795 2024] [proxy:error] [pid 1261:tid 140392366847680] 
(2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain 
socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Thu Sep 12 18:18:36.554838 2024] [proxy_fcgi:error] [pid 1261:tid 
140392366847680] [client **ip_address**:34250] AH01079: failed to make 
Press [Enter] to continue:
connection to backend: www-fpm
 [Thu Sep 12 18:20:42.127779 2024] [core:error] [pid 1160:tid 139923365545664] 
[client **ip_address**:51946] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Thu Sep 12 18:30:40.832700 2024] [proxy_fcgi:error] [pid 6626:tid 
140606357599936] [client **ip_address**:48776] AH01071: Got error 'PHP message: 
PHP Deprecated: Creation of dynamic property rs_domain_switch_update::$data is 
deprecated in 
/bitnami/wordpress/wp-content/plugins/revslider-domain-switch-addon/admin/include
s/update.class.php on line 72'

```
Press [Enter] to continue:
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

cannot properly determine the error

### Describe your issue as much as you can

the site went down and when we restarted we were faced with database connection errors, upon restarting the vm again it fixed the issue

**Comment by jotamartos** [comment]
There is an error in WordPress that you would need to investigate. You should contact the plugin's or the WordPress' developers if you need more information regarding that error.

```
140606357599936] [client **ip_address**:48776] AH01071: Got error 'PHP message: 
PHP Deprecated: Creation of dynamic property rs_domain_switch_update::$data is 
deprecated in 
/bitnami/wordpress/wp-content/plugins/revslider-domain-switch-addon/admin/include
s/update.class.php on line 72'

```

Apart from that, I suggest you take a look at the Apache's and PHP's log files to see if there is any other error to solve. 

We also suggest you take a look at this other ticket to investigate if there is any bot/attacker accessing your site and cousing performance-related issues

https://github.com/bitnami/vms/issues/1501

**Comment by imfaizanakram** [comment]
Based on the information provided, the following steps should help you resolve the issues:

1. Restart PHP-FPM to fix the FastCGI socket issue.
2. Disable or update the problematic plugin to resolve deprecation warnings.
3. Ensure the database service is running and configured correctly.
4. Ensure that necessary ports are open to allow proper server communication.

Feel free to provide more logs or details if the issue persists after trying these solutions.

**Comment by Idea-Theorem** [comment]
Hi Faizan,

when atttempting to restart php-fpm when the site is down, it gives me this error
<img width="545" alt="image" src="https://github.com/user-attachments/assets/d2e81ac9-e57a-4d41-abd8-390c0192fbb2">

i'll check the other things and will get back to you thanks

**Comment by Idea-Theorem** [comment]
hi @jotamartos,

the site went down again today, because someone uploaded a big file..
there were also still proxy fpcgi errors present on the log

**Comment by jotamartos** [comment]
As I mentioned above, please check the logs and debug the issue. This forum is meant to solve deployment or basic configuration issues. However, this one is related to specific needs you have and you will need to customize the configuration based on that.

**Comment by mark-ideatheorem** [comment]
Hi @jotamartos, 

I managed to fix the fpcgi problem, it was crashing because of cloudflare... and I think that was the main reason of the 521 errors. Thanks for your support!
