### ISSUE TITLE
[MAMP] Apache and MariaDB service becomes unresponsive, but says running

### ISSUE THREAD

**Issue by KarlF2024** [bitnami/vms#1658]
### Platform

OSX VM

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Doesn't work

### bndiagnostic was not useful. Could you please tell us why?

Could not get to run

### Describe your issue as much as you can

I tried the instructions to get the bndiagnostic to work but it does not work. I have a Mac running Monterey 12.6.3 and we have Bitnami MAMP 7.4.23-0 installed and configured to use Apache on port 80/443 and MariaDB. We just started experiencing an issue where the services will become unresponsive. If we launch the osx-manager, it lists the services as running, no issues. But attempting to reach any website, or phpmyadmin, fails until we restart the services. After the restart everything seems fine. This has been happening at least once a day, at random intervals. Any suggestions on how to go about troubleshooting? I checked the apache logs but there is nothing of significance and often doesn't have anything for hours prior to the service becoming unresponsive. Any other logs I can look at to try and determine what could be happening?

**Comment by jotamartos** [comment]
Hi,

Please note that Bitnami MAMP is no longer supported and we suggest you download the latest Bitnami LAMP VM or use the Bitnami containers and charts to deploy your application. 

However, if you want to troubleshoot the issue, there are many related tickets in this forum that will probably help you. Please take a look at this one and try to find more information about the issue 

https://github.com/bitnami/vms/issues/1501

**Comment by KarlF2024** [comment]
The system has 64GB of memory, so if memory is an issue it must be a configuration setting?

**Comment by KarlF2024** [comment]
Hi, I changed the memory limit in the php.ini to be higher than it was. It hasn't made a difference. What are the locations of the log files I should be looking at help determine the cause of the service to cease functioning?

**Comment by jotamartos** [comment]
You should be checking these logs

- installdir/apache2/logs
- installdir/mysql/logs

As you have a local installation, there shouldn't be PHP-FPM's logs under installdir/php/var/log
