### ISSUE TITLE
[Moodle] Database Issue

### ISSUE THREAD

**Issue by itcloudserver** [bitnami/vms#1659]
### Describe your issue as much as you can

Migrated the database from one instance to another Moodle instance. After restoring the database all the courses are visible and able to access but unable to access administration page and getting the error "Error reading from database"

**Comment by jotamartos** [comment]
This is an app-related question so we suggest you ask in its forums and check its documentation. Please ensure you followed this guide to perform the migration of data 

https://docs.moodle.org/404/en/Moodle_migration

**Comment by itcloudserver** [comment]
Thanks. Let me check and revert.
