### ISSUE TITLE
[WordPress] wp-config.php is not updated during deployment

### ISSUE THREAD

**Issue by vahric** [bitnami/vms#166]
### Platform

VMware Marketplace

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

812c3626-db4e-326a-7462-63748fa1756b

### bndiagnostic was not useful. Could you please tell us why?

no any issue there 

### Describe your issue as much as you can

I'm expecting that bitnami template for vmware must modify wp-config.php
when you deploy the  WordPress Virtual Appliance packaged by Bitnami 6.0.1_2_r03 , its saying "Error estabilising database connection"
i believe that template should modify the related file and it will be ready to use for customers ...

**Comment by vahric** [comment]
sorry adding more , when check log file of mariadb we are seeing "username_here" warning 
then when check wp-config no any database name , username and pass is modified 
I believe this is not a normal behaviour 
vmware users should go to related files and update that lines manually ?

**Comment by jotamartos** [comment]
Hi @vahric,

Sorry for the inconvenience. I understand you are trying to deploy the Bitnami WordPress solution in the VMware Marketplace, correct? 

https://marketplace.cloud.vmware.com/services/details/wordpress

Did you follow our guide to launch the solution? Did you use any other settings when performing the deployment?

https://docs.bitnami.com/vmware-marketplace/get-started-vmware-marketplace/

Thanks

**Comment by vahric** [comment]
Hello @jotamartos
We are usign VMware Cloud Director and its integrated with VMware Marketpalce (using App LaunchPad 2 1). Right now from VMware Cloud Director is downloading images automaticly https://marketplace.cloud.vmware.com/services/details/wordpress?slug=true 6.0.1_2_r03

Your link is vCenter view and its quite similler vmware cloud director. I believe, i did not make any mistake to install.

I'm getting error establishing a database conncetion after installation over and checking /opt/bitnami/wordpress/wp-config.php and there is a lines like below 

DB_PASSWORD is password_here
DB_USER is username_here
DB_HOST is localhost

When i update manually DB_USER  and DB_PASSWORD then wordpress page is become active ....

**Comment by vahric** [comment]
have a time to check ? i can show you remotely if you want ...

**Comment by jotamartos** [comment]
Hi @vahric,

We are going to review the information you provided and try to reproduce the issue. We will let you know when we have more information. 

Thanks

**Comment by vahric** [comment]
Hello all , did you have any findings about issue ?

**Comment by vahric** [comment]
Pls could you update me still waiting response from you about such tempalte ?

**Comment by vahric** [comment]
Did you fix or catch the issue ?

**Comment by mdhont** [comment]
I apologise for the late reply. We will try to reproduce it. In the meantime could you run the bndiagnostic tool on the machine? 

    sudo /opt/bitnami/bndiagnostic-tool 

It will gather data that can help us troubleshoot the issue.
