### ISSUE TITLE
cyberpanel Web Hosting Panel and CloudPanel Server Hosting Panel Image for Bitnami

### ISSUE THREAD

**Issue by faisalmasood** [bitnami/vms#1663]
### Describe your suggestion as much as you can

I have been looking for a web hosting and Server hosting panels. I found CyberPanel https://cyberpanel.net/ for web hosting and CloudPanel https://www.cloudpanel.io/ as Server hosting panels. Can you have their images built for bitnami?

**Comment by jotamartos** [comment]
Those are hosting sites to deploy the applications. We already provide the applications in different cloud providers, you can choose the one you need and deploy it either locally or in the cloud (containers, charts and VMs)

https://bitnami.com/stacks
