### ISSUE TITLE
[PrestaShop] AWS LightSail 8.1.7-2 - Unable to access the /administration Back Office with Bitnami password

### ISSUE THREAD

**Issue by OllyNural** [bitnami/vms#1664]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e768501d-5524-d4fa-79bb-89a6e6224d7f

### bndiagnostic output

    ✓ Processes: No issues found    
✓ Mariadb: No issues found    
? Connectivity: Found possible issues    
✓ Php: No issues found    
? Apache: Found possible issues   
 ? Resources: Found possible issues  

[Connectivity]Server ports 22, 80 and/or 443 are not publicly accessible. Please check the following guide to open server ports for remote access:https://docs.bitnami.com/general/faq/administration/use-firewall/
[Apache]Found recent error or warning messages in the Apache error log.Press [Enter] to continue:```[Fri Sep 27 12:26:36.144034 2024] [authz_core:error] [pid 1844:tid 2002] [client **ip_address**:42750] AH01630: client denied by server configuration: /opt/bitnami/apache/cgi-bin[Fri Sep 27 12:26:36.158990 2024] [authz_core:error] [pid 1843:tid 2007] [client **ip_address**:42760] AH01630

[Resources]Your instance has little available RAM memory.```Press [Enter] to continue:               total        used        free      shared  buff/cache   availableMem:             945         701          73          33         372         244Swap:            634         120         514```You could try to increase your instance's memory. Please check your cloud provider's documentation for more information.

### bndiagnostic was not useful. Could you please tell us why?

Not Applicable

### Describe your issue as much as you can

After setting up Bitnami's Prestashop image with AWS Lightsail, the back office was inaccessible using the instructions [here](https://docs.bitnami.com/aws/faq/get-started/find-credentials/#administrator-username) as the username and password were incorrect. I changed them, and it worked. See full replication details below.

<img width="522" alt="image" src="https://github.com/user-attachments/assets/fc8e7af9-6801-4166-9014-fda43c0b38c7">

---- 

Replication;

1. Set up AWS LightSail with Prestashop 8.1.7-2 following the guide herehttps://docs.aws.amazon.com/en_us/lightsail/latest/userguide/amazon-lightsail-quick-start-guide-prestashop.html.

2. Setup works correctly, and PrestaShop is available on the Static IP correctly.

3. After obtaining the Administration password using the instructions [here](https://docs.aws.amazon.com/en_us/lightsail/latest/userguide/amazon-lightsail-quick-start-guide-prestashop.html#amazon-lightsail-prestashop-get-the-default-user-password), and attempting to login to the backoffice of `http://<ip>/administration` it gives an error of "The employee does not exist, or the password provided is incorrect.".

4. Checking with `phpmyadmin` I can see the user exists, but cannot see the existing password.

5. Changing the password and then trying to log in again succeeds.

6. The password shown in the documentation on Bitnami [here](https://docs.bitnami.com/aws/faq/get-started/find-credentials/#administrator-username) seems incorrect, or at least, the setup did not immediately work for me.

I can't find any other examples of this online, so I'm making this bug. I hope it's in the right place, please let me know if not and I will edit/move it.

**Comment by OllyNural** [comment]
Hi @jotamartos  - thanks for getting back to this thread. Yes I did access and got the password through that process. That password did not work for the PrestaShop backend login. However it's worth noting, that that password did allow me access to `/phpmyadmin` when used with the default email address. Thanks!

**Comment by jotamartos** [comment]
This error is weird. We test our applications and ensure that the password we generate during the initialization works properly. If this is a fresh VM, you can deploy a new one and delete this one. Sorry for the inconvenience.
