### ISSUE TITLE
Google cloud WordPress password reset HELP 

### ISSUE THREAD

**Issue by hvfhggbb** [bitnami/vms#1666]
### Describe your issue as much as you can

Here is pastebin picture attached of error 
![Screenshot_20240930_082424_Chrome](https://github.com/user-attachments/assets/949a1c75-05c2-4a5b-9dcb-48c732e02288)

https://pastebin.com/es6Av8T0

**Comment by gongomgra** [comment]
Hi @hvfhggbb,

Thanks for using Bitnami. We highly recommend you to create a server backup before doing any modifications to it so you can easily restore it back to a well known previous state.

Regarding your ossies, I think you are missing a double quote (`"`) character at the end of the command you shared. Apart from that, please refer to our guide on how to reset the MariaDB root password at https://docs.bitnami.com/general/infrastructure/lamp/administration/change-reset-password-mariadb/

Hope it helps!
