### ISSUE TITLE
Possible Security Issue with Bitnami WordPress Image

### ISSUE THREAD

**Issue by Aui1521** [bitnami/vms#1667]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

45addad8-40e3-4015-d596-88ce7496c1e7

### bndiagnostic output

    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ? Resources: Found possible issues
    ✓ Wordpress: No issues found

### bndiagnostic was not useful. Could you please tell us why?

My issue was related to a security breach involving web phishing

### Describe your issue as much as you can

Hi Bitnami Security Team,

I am reaching out regarding a strange issue I’ve encountered and am hoping you can assist.

A domain, https://www.novelpantry.com, has seemingly been able to mirror my server, potentially for phishing purposes. Any changes I make to the original webpage (e.g., title updates on https://demo.sinudompharmacy.com) are immediately reflected on that site. When I stop the service on https://demo.sinudompharmacy.com, https://www.novelpantry.com also goes offline.

Here are the steps I followed to create the server:

1  Launched the latest Bitnami image (WordPress Certified by Bitnami and Automattic 6.6.1-14) on AWS Lightsail.
2  Assigned a public static IP.
3 Ran the bncert-tool for HTTPS configuration.
That’s it.

Notably, the same issue occurs when I launch other services using Bitnami images, such as Nginx Packaged by Bitnami 1.26.2-0. However, the problem does not happen when I launch a fresh OS, like CentOS 9, and manually install Apache.

I was wondering if there might be a security breach in Bitnami images, or if there’s something else I should investigate or shut down.

Regards,
Nathan

**Comment by Aui1521** [comment]
I believe that the attacker’s site is using a proxy service from the QUIC.cloud CDN to mirror my site. I have compiled a list of IP addresses https://www.quic.cloud/ips and blocked them using iptables. While this seems to work, I am unsure if there are any reverse proxy services or configurations within the Bitnami stack that I can disable to prevent this mirroring issue from recurring.

Could you please provide guidance on how to further secure my server and disable any potential reverse proxy configurations?
Or it might be something else?

#!/bin/bash
# List of IP addresses to block
BLOCK_IPS=(

# EXAMPLE
    102.221.36.98
    95.179.133.28
    95.216.116.209

# This list go on!

)

# Block each IP
for ip in "${BLOCK_IPS[@]}"; do
    sudo iptables -A INPUT -s $ip -j DROP
    echo "Blocked IP: $ip"
done

# Save iptables rules so they persist after reboot
sudo iptables-save > /opt/bitnami/iptables-rule

**Comment by gongomgra** [comment]
Hi @Aui1521,

Thanks for using Bitnami. I'm afraid I can't think of any configuration in our images that can lead to the issues you are facing. We recommend you to follow the guide below on how to detect if you are under a bot attack and how to block them from Apache configuration instead of using iptables. Be aware that if you block your own IP address via iptables by mistake you may lost connectivity to the server

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/

Hope it helps!

**Comment by Aui1521** [comment]
Thank you, @gongomgra, for your findings. I appreciate your efforts in helping me find a solution.

If I determine what happened, I will make sure to inform everyone and the community about it.

For now, I am happy to block those IPs using IPTABLES instead of addressing at the application level. Additionally, I have installed a WAF solution.

Regards,
Nathan1521

**Comment by gongomgra** [comment]
Hi @Aui1521,

Thanks for your message. I'm glad you have found a workaround for your issue that suits your needs. We will keep the ticket open so you can add a new post in case you find anything else or any other member of the community want to add a comment.

**Comment by Aui1521** [comment]
Hi @gongomgra 

Is /opt/bitnami/wordpress/index.php being granted access for any HTTPS request?

Do you have any tips to enhance security and prevent this file from being mirrored?

Regards,
Nathan1521

Regards,
Nathan1521

**Comment by gongomgra** [comment]
Hi @Aui1521,

The file you mentioned is the main entrypoint for the WordPress application. I'm afraid I don't know if there is any configuration available to enhance its security settings. We recommend you to open a new question in the official WordPress forums

https://wordpress.org/support/forums/

Hope it helps!
