### ISSUE TITLE
[meanstack-7.0] apache port change  causes no restart

### ISSUE THREAD

**Issue by magrasjc** [bitnami/vms#1668]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7a503622-4b51-aad2-9c59-0ca083c057b3

### bndiagnostic output

The tool gives no specific comments or error messages.

### bndiagnostic was not useful. Could you please tell us why?

no error messages there.. ctlscript merely mentions error code but no specifics.

### Describe your issue as much as you can

I installed bitnami meanstack 7.0-7.0.14-r1-debian-12-amd64 on VirtualBox on a ubuntu (kernel 6.5.0-44).
I changed the http port to 7xxx.
/opt/bitnami/ctlscript restart apache fails with a message in red saying 'control process exited with error code'. There are also references to 'journalctl -xeu' Thank in advance but that reveals nothing.
/opt/bitnami/apache/bin/apachectl -D LogLevel=debug -S -f /opt/bitnami/apache/conf/httpd.conf reports:

    VirtualHost Configuration;
    127.0.0.1:7xxx. status.localhost (/opt/bitnami/apache/conf/vhosts/00_status-vhost.conf:1)
    *:7XXX 192.168.x.y (/opt/bitnami/apache/conf/bitnami.conf:6)
    *:443. 192.168.x.y (/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf:15)

I tried LogLevel=emerg but nothing new. It still onto start.

ss shows nothing.'netstat' is not available. The conventional error_log file only shows a single line about receiving a SIGTERM. *nft has been updated. The 'apachectl configtest' says 'Syntax OK'.

ThankX in advance.

**Comment by magrasjc** [comment]
I reverted back to port 80 and got the same thing.
I then installed **strace** and the last references are to recvmesg (\7\1s\0\30\0\0\0/org/desktop/systemd1/unit/b...)

**Comment by magrasjc** [comment]
I am unable to interpret the d-bus exchange aside from a login using supposedly not on by default fd's and reading in the last exchange about the property org.freedesktop.systemd.Unit1.
NOTE: Installing python pydbus and dbus_next still will not allow me to use the Array. Why is this?

The final dbus message is:
Strace says: "1\2\1\1\22\0\0\0\26\0\0\0007\0\0\0\5\1u\0\4\0\0\0"
"\7\1s\0\30\0\0\0org.freedesktop.systemd1\0\0\0\0\0\0\0\0\10\1g\0\1v\0\0\1s\0\0\t\0\0\0exit-code\0"

**Comment by gongomgra** [comment]
Hi @magrasjc,

Thanks for using Bitnami. I see there are changes in the next Apache files. Can you double-check you have properly reverted all of them?

```
/opt/bitnami/apache2/conf/bitnami/bitnami.conf
/opt/bitnami/apache2/conf/httpd.conf
/opt/bitnami/apache2/conf/vhosts/00_status-vhost.conf
/opt/bitnami/apache2/conf/httpd.conf
```

What's the output of running the command below? It will let you know what issues are present in the Apache configuration that is preventing it to start.

```
apachectl -t
```
