### ISSUE TITLE
[WordPress] Website becomes unreachable & requires a reboot

### ISSUE THREAD

**Issue by gitatmax** [bitnami/vms#167]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7c05dde3-c593-13b9-ae60-cbe921fd1f62

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ? Wordpress: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Jul 22 23:21:10.746163 2022] [authz_core:error] [pid 5926:tid 
139654887962368] [client **ip_address**:65413] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/index.php
 [Sat Jul 23 00:28:02.852666 2022] [core:error] [pid 5925:tid 139655374096128] 
[client **ip_address**:56592] AH10244: invalid URI path 
Press [Enter] to continue:
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
 [Sat Jul 23 00:50:55.014968 2022] [core:error] [pid 5926:tid 139654988674816] 
[client **ip_address**:33380] AH10244: invalid URI path 
(/../../data/files/318.pdf)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Fri Jul 22 21:01:15.280692 2022] [proxy_fcgi:error] [pid 5925:tid 
139654971889408] [client **ip_address**:59410] AH01071: Got error 'PHP message: 
PHP Notice: Undefined index: host in 
/bitnami/wordpress/wp-content/plugins/perfmatters/perfmatters.php on line 27PHP 
message: PHP Notice: Undefined index: host in 
/opt/bitnami/wordpress/wp-includes/canonical.php on line 687PHP message: PHP 
Notice: Undefined index: host in 
/opt/bitnami/wordpress/wp-includes/canonical.php on line 688PHP message: PHP 
Press [Enter] to continue:
```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Tried disabling the mentioned plugin but the issue continues

### Describe your issue as much as you can

The website becomes unresponsive & requires a reboot. I've enabled swap [using this article](https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-memory-linux/), if relevant. Other than enabling the ram swap to try to solve this problem, we're using a completely fresh installation in Lightsail.

I'd appreciate any guidance you may have on this. We are having to reboot weekly/every few days. Thanks in advance.

**Comment by jotamartos** [comment]
Hi @gitatmax,

Thank you for using Bitnami. [This post](https://github.com/bitnami/vms/issues/27) contains general information about how to debug this error. However, I can see WordPress-related errors in the information you posted so I suggest you contact WordPress to know more about this 

https://wordpress.org/support/

> PHP Notice: Undefined index: host in 
> /bitnami/wordpress/wp-content/plugins/perfmatters/perfmatters.php on line 27PHP 
> message: PHP Notice: Undefined index: host in 
> /opt/bitnami/wordpress/wp-includes/canonical.php on line 687PHP message: PHP 
> Notice: Undefined index: host in 
> /opt/bitnami/wordpress/wp-includes/canonical.php on line 688PHP message: PHP

**Comment by gitatmax** [comment]
With errors like these, and not having the problem on my SpinupWP server, and with there being other similar issues open, how is this not to do with the Bitnami stack?

```Notice: Undefined index: host in
/opt/bitnami/wordpress/wp-includes/canonical.php on line 688PHP```

Again, I've removed the plugins throwing the error & reinstalled WordPress, but the problem persists. Is there nothing else you can recommend?

Thank you.

**Comment by jotamartos** [comment]
If you have performance issues, you can check the second post you mentioned above. However, the error you are posting in your message is related to WordPress and its plugins/themes. For example, there is a thread [here](https://wordpress.org/support/topic/undefined-index-host-in-var-www-wordpress-wp-includes-canonical-php/) talking about that. I suggest you ask WordPress to know what's happening with the application.

**Comment by gitatmax** [comment]
@jotamartos Okay, thanks for your help. Sorry for misunderstanding.
