### ISSUE TITLE
Slowness on my instance and can't be reached via url

### ISSUE THREAD

**Issue by rapoposolutions** [bitnami/vms#1670]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9c400481-0fd8-a4fa-17b4-a0136be597e1

### bndiagnostic output

Lightsail

===== Begin of bndiagnostic tool output =====

 
    ✓ Processes: No issues found
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ? Resources: Found possible issues
    ✓ Wordpress: No issues found
 

 
[Mariadb]

Found recent error messages in the MariaDB error log:
```
2024-10-02 18:58:55 242 [Warning] Aborted connection 242 to db: 
'bitnami_wordpress' user: 'bn_wordpress' host: '**ip_address**' (Got an error 
reading communication packets)

```
Press [Enter] to continue:
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-mariadb/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Oct 02 19:30:23.906911 2024] [mpm_event:error] [pid 1136:tid 1136] AH03490: 
scoreboard is full, not at MaxRequestWorkers.Increase ServerLimit.
 [Wed Oct 02 19:30:24.946826 2024] [mpm_event:error] [pid 1136:tid 1136] 
AH03490: scoreboard is full, not at MaxRequestWorkers.Increase ServerLimit.
 [Wed Oct 02 19:30:25.590093 2024] [proxy_fcgi:error] [pid 1140:tid 1293] 
(70007)The timeout specified has expired: [client **ip_address**:50503] AH01075: 
Error dispatching request to : (polling)
Press [Enter] to continue:


Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
```

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-conne
ctions-bots-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 447 366 17 39 114 80 Swap: 634 
336 298
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

### bndiagnostic was not useful. Could you please tell us why?

my other instance is mint and fast

### Describe your issue as much as you can

I can't reach my instance's admin endpoint and can't reach my dns name as well, and IP address as well

**Comment by gongomgra** [comment]
Hi @rapoposolutions,

Thanks for using Bitnami. According to the bndiagnostic information you shared, your getting around 49k out of the total 51k requests on your server from a couple of IP addresses

```
-----------------------------------
Check number of lines of Apache access log
-----------------------------------
Running: wc -l access_log
In: /opt/bitnami/apache2/logs/

Output:

50987 access_log



-----------------------------------
Check performance issues: Count number of requests for the 10 most active IP addresses in the last 100.000 requests
-----------------------------------
Running: tail -n 100000 access_log | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 10 | awk '{print $1}'
In: /opt/bitnami/apache2/logs/

Output:

33679
13904
964
842
731
316
93
76                                                                                                                                                                                                                                                                                      60
54
```

This is causing that your instance can't attend new requests from other clients. We recommend you to check what requests are those IPs performing and optionally blocked them (in case they are bots performing attacks to your server)

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/
