### ISSUE TITLE
[<Wordpress AWS>] <Bitnami Wordpress EC2 Image update from x86 to ARM>

### ISSUE THREAD

**Issue by marcus-sm8a** [bitnami/vms#1671]
### Describe your suggestion as much as you can

Hello Bitnami, 

Long time user here, are curious if you are making a Bitnami Wordpress EC2 (Apache) image for ARM? 
I have been able to transfer most of our other apps over to ARM, as you know, these ARM VMs are cheaper with AWS per hour.

Is this something Bitnami is investigating?

Thanks for your time. 

Marcus

**Comment by gongomgra** [comment]
Hi @marcus-sm8a,

Thanks for your message. We are not providing ARM64 EC2 images yet, but we provide multi-arch Docker images instead. You can check our debian-12 images at https://hub.docker.com/r/bitnami/wordpress/tags

Hope it helps!

**Comment by marcus-sm8a** [comment]
Hi, 

We will wait for the EC2 images to be updated. 

Cheers.

**Comment by gongomgra** [comment]
Hi @marcus-sm8a,

Unfortunately, I can't provide you with any ETA on this. I'm afraid I don't even know if we would provide them at some point. My recommendation would be to use the available ARM64 Docker images. Sorry for the inconveniences.
