### ISSUE TITLE
[Node.js] How can I disable Apache so it doesn't start on reboot

### ISSUE THREAD

**Issue by webservices-nm** [bitnami/vms#1672]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d3834320-984a-cbd3-3b31-9d256aa4d5c7

### bndiagnostic output

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ? Apache: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

It doesn't tell me how to disable Apache

### Describe your issue as much as you can

I would like to disable Apache so that it does NOT start on system startup or reboot. I've looked through all the Bitnami help files though, and nothing seems to work. For example, when I use "sudo systemctl disable apache2", I get the following response, "Failed to disable unit: Unit file apache2.service does not exist."

I can start and stop Apache with ctlscript.sh or apachectl, but neither of those allow me to disable apache on reboot.

Thanks

**Comment by jotamartos** [comment]
There is a similar ticket here, could you please take a look at it? 

https://github.com/bitnami/vms/issues/3#issue-1252563157

In that case, it's disabling MariaDB but you can do the same with Apache
