### ISSUE TITLE
AWS Bitnami error 

### ISSUE THREAD

**Issue by ankitbaid** [bitnami/vms#1673]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e23855f7-805d-09c6-f9a5-1af7731e209a

### bndiagnostic was not useful. Could you please tell us why?

The suugested guides dont help

### Describe your issue as much as you can

My Website is going down every 20 mins. Don't know what's the problem. I have to restart AWS instance and restart apache every 20 mins to get my website online

**Comment by gongomgra** [comment]
Hi @ankitbaid,

Thanks for using Bitnami. I have checked the bndiagnostic information and something has caught my attention. More than 19k requests out of the total 22k received by your server belongs to a single IP address.

```
-----------------------------------
Check number of lines of Apache access log
-----------------------------------
Running: wc -l access_log
In: /opt/bitnami/apache2/logs/

Output:

22706 access_log

-----------------------------------
Check performance issues: Count number of requests for the 10 most active IP addresses in the last 100.000 requests
-----------------------------------
Running: tail -n 100000 access_log | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 10 | awk '{print $1}'
In: /opt/bitnami/apache2/logs/

Output:

19292
1079
748
169
130
62
56
51
50
46
```

Can you check if your website is undergoing [a bot attack](https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/)? Can you also tell us if you are running your instance on AWS EC2 or AWS Lightsail?
