### ISSUE TITLE
[Wordpress] Installing theme from JWThemes issue

### ISSUE THREAD

**Issue by digitalmate1** [bitnami/vms#1675]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

aeefd9ba-8a01-4cfb-9277-5bfdcc47007e

### bndiagnostic was not useful. Could you please tell us why?

It is a conflict between my theme and host. It requires action from you.

### Describe your issue as much as you can

Hi there,

I just purchased the theme Auriane from theme forest.  I have a problem installing the demo. I contact the theme support and they told me the following:

"Your host seems to have an issue with SSL or some security settings, which is causing files to not function properly. Please contact your host and send them this screenshot, they will know how to fix it. After that, you can proceed with the import."

https://prnt.sc/6Oy-CHIpRjrt

Best regards,

Andreas

**Comment by gongomgra** [comment]
Hi @digitalmate1,

Thanks for using Bitnami. Unfortunately we can't provide support for paid plugins or themes as we can't reproduce it on our side. I have checked the filesystem permissions from the bndiagnostic information you shared and they seems to be fine. Please check if there is any incompatibility with the WordPress version or any other of the stack elements, or if it is required to update the Apache configuration with the official developers of the theme. 

Sorry for the inconveniences.
