### ISSUE TITLE
[ERPNext] Configure timezone

### ISSUE THREAD

**Issue by msalim79** [bitnami/vms#1676]
### Describe your issue as much as you can

Installed Bitnami ERPNext on AWs , time defaults to America/Los_Angeles.
I need to change this to Africa/JHB , my instance is already with AWS-CapeTown.
How can i change this ?

**Comment by jotamartos** [comment]
That's a specific question about the application and it's out of the scope of this forum. Please take a look at the ERPNext's documentation and its forums to know more about how to configure the app.

**Comment by msalim79** [comment]
The time zone was set by the image by bitnami , which the default user does not have access to edit on the front end. When the initail company is setup time zone is asked , this image defaults to America.

**Comment by jotamartos** [comment]
>When the initail company is setup time zone is asked , this image defaults to America.

Yes, you are right, we configure America/Los_Angeles as default timezone. But the application should allow you change that configuration. Please take a look at the ERPNext's documentation to know how to change the timezone settings.
