### ISSUE TITLE
[<application>] <title>ERPNext image on aws 

### ISSUE THREAD

**Issue by msalim79** [bitnami/vms#1677]
### Describe your suggestion as much as you can

Please could you build an image without defaulting to Amercia as a default country , rather allow the installtion to go through the company setup as a fresh company. It would help implemention from other regions.

**Comment by gongomgra** [comment]
Hi @msalim79,

Thanks for using Bitnami. We provide a ready-to-use installation in all of our images to ease the usage and adoption of our solutions. Can you give us more details on what are the issues you are finding with the current configuration?

**Comment by msalim79** [comment]
So one main issue was the region,  I could not edit it in the front it was shaded out. 
Also the images default to America,  the images should actually start with the user setting up the company from fresh and having to tinker with company details and regions etc

**Comment by msalim79** [comment]
The time zone  defaults to America because the image sets it to that region 
I think to only way to change this is from the backend server
