### ISSUE TITLE
[ERPNext] SSh into erpnext via aws dashboard

### ISSUE THREAD

**Issue by msalim79** [bitnami/vms#1678]
### Describe your issue as much as you can

tried connecting ssh via the "connect" button on aws dashboard , getting a error "Failed to connect to your instance Error establishing SSH connection to your instance. Try again later."
How do i connect ?

**Comment by jotamartos** [comment]
Please take a look at our documentation to know the different ways to connect to the instance 

https://docs.bitnami.com/aws/faq/get-started/connect-ssh/
