### ISSUE TITLE
[<application>] <PHP Fatal Error> 

### ISSUE THREAD

**Issue by Morfonio** [bitnami/vms#1679]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

24fdd80e-656c-e652-0846-07955fc2364d

### bndiagnostic output

![bitnami error 3](https://github.com/user-attachments/assets/471fcb5c-541e-4c80-8af1-249bcc6fd514)

![bitnami error 4](https://github.com/user-attachments/assets/47b338a9-5dd4-404c-888c-5dc3e3874bbb)``

### bndiagnostic was not useful. Could you please tell us why?

/

### Describe your issue as much as you can

I originally had a problem with not being able to log into phpmyadmin via my web browser.

I found this case on Github that I understood to be similar to my case and started following what they said there.

[https://github.com/bitnami/vms/issues/1146](https://github.com/bitnami/vms/issues/1146)

I also ran the Bitnami Diagnostic Tool and this was the result:

How can I fix the PHP Fatal Error?

**Comment by gongomgra** [comment]
Hi @Morfonio,

According to the bndiagnotic output there are some syntax errors in your installation. Did you manually edit those files?

```
Got error 'PHP message: PHP Notice: Undefined variable: basededatos in /opt/bitnami/apache/htdocs/list_store.php on line 333
', referer: https://www.YOUR_DOMAIN.com/
Got error 'PHP message: PHP Notice: Undefined variable: con in /opt/bitnami/apache/htdocs/list_store.php on line 348
PHP message: PHP Warning: mysqli_close() expects parameter 1 to be mysqli, null given in /opt/bitnami/apache/htdocs/list_store.php on line 348
```

Please revert the changes to the files, restart the services and try again. Did you also modify the phpMyAdmin config file for Apache located at `/opt/bitnami/apache/conf/bitnami/phpmyadmin.conf`?

I don't see any other errors in Apache logs apart from the ones above.

**Comment by Morfonio** [comment]
After I fixed the 2 errors related to undefined variables and re-run the Bitnami Diagnostic Tool:

![bitnami error 5](https://github.com/user-attachments/assets/4529e75e-a58a-4bc0-a65e-fd90a2fc51ff)

Although I don't remember modifying the phpMyAdmin config file for Apache located at ` /opt/bitnami/apache/conf/bitnami/phpmyadmin.conf`

**Comment by Morfonio** [comment]
I also asked a question on Stackoverflow (https://stackoverflow.com/questions/79095103/i-am-getting-a-lot-of-errors-related-to-class-not-found-on-apache-error-log ) and following the advice of some people they recommended that I open an instance with the current version of LAMP Bitnami.

Test 23th October: I have a new update for you.

Following your recommendations I opened a new instance (Bitnami package for LAMP 8.2.24-3) and decided not to upload the files (from the database of my original version) to see if I was allowed access to phpmyadmin through the web browser to see if the completely clean installation would let me use it.

![bitnami error phpmyadmin limpio 2](https://github.com/user-attachments/assets/201fe057-6d09-4181-99f1-6f3fc6b70b64)
![bitnami error phpmyadmin limpio 0](https://github.com/user-attachments/assets/f4981a66-bd67-4bf3-9686-50599afc7e86)
![bitnami error phpmyadmin limpio 1](https://github.com/user-attachments/assets/42afb830-6bce-42e4-a4f5-fea4034ce5f8)

**Comment by gongomgra** [comment]
Hi @Morfonio,

I have not been able to reproduce your issue. I have launched a fresh new LAMP server for the same PHP version you mentioned, and I have been able to connect with phpMyAdmin without issues right after the server has started. Are you performing any change on your server? Is the SSH tunnel running? Do you see any related error in the Apache logs?

![Screenshot 2024-10-25 at 13 53 21](https://github.com/user-attachments/assets/7f52d6ad-43f2-4f56-bee0-1663b24ba48b)

Apart from the above, you may facing these issues due to the memory issue mentioned in your screenshots. Can you try using a bigger instance?

**Comment by Morfonio** [comment]
Hello @gongomgra,

I first tried to move the instance from t2.micro to t2.small but when I tried to access phpmyadmin through the browser there were no changes.

In my case I don't remember making any changes to my server before the initial problem appeared so it's very strange. I have used the SSH Tunnel for 5 years without any problems:
[https://docs.bitnami.com/aws/faq/get-started/access-ssh-tunnel/](https://docs.bitnami.com/aws/faq/get-started/access-ssh-tunnel/)

Yesterday I was also able to access the error_log and the acces_log of Apache and these are the screenshots for (Bitnami package for LAMP 8.2.24-3). Do you see anything that could help?

![bitnami error phpmyadmin limpio 3](https://github.com/user-attachments/assets/0315fff2-2693-42e6-b1b6-4714bc244bd0)
![bitnami error phpmyadmin limpio 4](https://github.com/user-attachments/assets/cde04c7b-9fba-4feb-b1a6-e7fc50f784ed)
