### ISSUE TITLE
[<guacamole>] <guacamole missing from Azure Marketplace>

### ISSUE THREAD

**Issue by yuvaphalle** [bitnami/vms#1680]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a4e06e12-803c-bbfc-6fd4-0f10da880979

### bndiagnostic output

Error Message: The resource you are trying to deploy (**bitnami guacamole**) is no longer available for new purchases.

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.guacamole?tab=overview****

### bndiagnostic was not useful. Could you please tell us why?

Guacamole is missing from Azure Marketplace

### Describe your issue as much as you can

 Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'Offer with PublisherId: 'bitnami', OfferId: 'guacamole' cannot be purchased due to validation errors. For more information see details. Correlation Id: 'a4e06e12-803c-bbfc-6fd4-0f10da880979' Offer with PublisherId: 'bitnami', OfferId: 'guacamole' and PlanId: default was removed from the marketplace for new purchase. See similar offers here 'https://azuremarketplace.microsoft.com/en-us/marketplace/apps?page=1%26search=bitnami%20guacamole'. Correlation Id 'a4e06e12-803c-bbfc-6fd4-0f10da880979'.'"

**Comment by jotamartos** [comment]
Hi @yuvaphalle,

We deprecated Guacamole from the different Marketplaces back in July and after some grace period, it's no longer available. You will need to find an alternative solution. 

Sorry for the inconvenience
