### ISSUE TITLE
Bitnami Wordpress image on Azure

### ISSUE THREAD

**Issue by paul-reeves** [bitnami/vms#1681]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

None available

### bndiagnostic output

Unable to find legal terms for this offer.  Agreement has never been signed for this offer.

### bndiagnostic was not useful. Could you please tell us why?

Unknown

### Describe your issue as much as you can

We are trying to create a new VM in Azure using an OS disk image of a Bitnami Wordpress VM that was previously running in Azure.  When attempting to create the new VM, we get the following error.

"Unable to find legal terms for this offer.  Agreement has never been signed for this offer."

Microsoft Azure support suggested that we contact you as it looks like the 4.4 image does not have a valid license associated with it, so there is nothing that we can accept.

![image](https://github.com/user-attachments/assets/ff196b00-4187-4627-a45a-2842fd3f05d7)

![image](https://github.com/user-attachments/assets/ada4de50-4d12-4317-9435-04b8b3e05ed7)

**Comment by gongomgra** [comment]
@paul-reeves as you can see in the link shared below under the "Plans + Pricing" tab, the WordPress version we are currently offering in Azure is `6.6.2`

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.wordpress?tab=PlansAndPrice

Is it possible that you are trying to deploy an old image no longer available?
