### ISSUE TITLE
[WordPress] Unexpectedly can't sign into wordpress on my bitnami google cloud site 

### ISSUE THREAD

**Issue by rakdek** [bitnami/vms#1682]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3ba77fb0-1aad-9514-8044-33a7b968e87d

### bndiagnostic output

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Thu Oct 10 02:32:39.577908 2024] [core:error] [pid 1215:tid 139619211355840] 
[client **ip_address**:59472] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh)
 [Thu Oct 10 02:32:40.120329 2024] [core:error] [pid 539:tid 139619421042368] 
[client **ip_address**:59474] AH10244: invalid URI path 
(/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32
%65/%%32%65%%32%65/%%32%65%%32%65/bin/sh)
 [Thu Oct 10 03:02:28.538569 2024] [authz_core:error] [pid 1215:tid 
139620142520000] [client **ip_address**:57218] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin
```

### bndiagnostic was not useful. Could you please tell us why?

My site loads but I can't sign into /wp-admin 

### Describe your issue as much as you can

I'm not sure what's wrong with my site www.rakdek.org, normally it can sign into the password protected front end and also /wp-admin, but now it can't, just reloads the same screen. I have the domain on squarespace and recently made some changes there for google workspace. My site server on google cloud was stopped after I forgot to upgrade trial, which I have now. After restarting google cloud, I needed to redo the SSL certificate but its configured ok. Please help thanks

**Comment by jotamartos** [comment]
>I have the domain on squarespace and recently made some changes there for google workspace.

I suggest you undo any change you made in the application lately (if you made any using the command line) to see if that's the cause of the issue. You can also disable all plugins and themes by accessing the instance using SSH and renaming the plugins/themes folder under /opt/bitnami/wordpress/wp-content. 

I understand that this is not a password-related issue, but you can follow this guide in case you find any error with your password when log in to the application 

https://docs.bitnami.com/general/apps/wordpress/administration/reset-wp-admin-password/
