### ISSUE TITLE
Dolibarr not opening after upgrading macOS to Sequoia

### ISSUE THREAD

**Issue by kartikmittal2006** [bitnami/vms#1683]
### Describe your issue as much as you can

I’ve been using Dolibarr for past 3-4 years, but after latest upgrade of macOS to Sequoia the stack is not opening and showing error ‘cannot start stack: ssh not accessible’, I can’t confirm the version of Dolibarr I am using (since application not opening), please help.

<img width="328" alt="Screenshot 2024-10-10 at 12 47 32" src="https://github.com/user-attachments/assets/13b09744-900a-4736-9aed-37a8c2d2ddcd">

<img width="490" alt="Screenshot 2024-10-10 at 12 47 43" src="https://github.com/user-attachments/assets/ae2bc030-a1e4-478b-88dd-2d2737ed58b5">

**Comment by gongomgra** [comment]
Hi @kartikmittal2006,

Thanks for using Bitnami. We dropped support for our native installers as part of our [focus on cloud native solutions](https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html). We recommend you to use one of our supported solutions for Dolibarr like the OVA

https://bitnami.com/stack/dolibarr

Sorry for the inconveniences.
