### ISSUE TITLE
Bitnami OVAs available in VMware Marketplace

### ISSUE THREAD

**Issue by carrodher** [bitnami/vms#1686]
Important update regarding the download process for Bitnami OVAs: going forward, Bitnami OVAs will only be accessible through the VMware Marketplace, where you can continue to download them without charge. They will no longer be downloadable directly from bitnami.com.

This transition to a single repository for OVA VMs enables us to offer a consistent experience for all users. We chose to use VMware Marketplace because it is possible there to browse and access previous versions of OVAs, providing greater flexibility when managing deployments. Previously, only the latest version of any OVA was available through bitnami.com.

[Visit the VMware Marketplace](https://marketplace.cloud.vmware.com/services/?Publishers=8b8499c6-703d-4b32-a49e-36d6fd47eb00&formFactor=VirtualMachines) now to access and download your favorite apps as OVA Virtual Machines!

**Comment by KB-smi** [comment]
Once signed in to vmware, getting 403 errors trying to download ova.  Links then lead to requiring an invitation to VMware Cloud Services.  From there, cloud.vmware.com/service-catalog times out.  Sorry if this isn't the right spot to comment this issue.

**Comment by heatmiser** [comment]
> Once signed in to vmware, getting 403 errors trying to download ova. Links then lead to requiring an invitation to VMware Cloud Services. From there, cloud.vmware.com/service-catalog times out. Sorry if this isn't the right spot to comment this issue.

Seeing the same today.

**Comment by jendik** [comment]
unfortunately same here-( could you please advise how to download the image? thank you so much
Kind regards
j.

**Comment by carrodher** [comment]
I assume you’re receiving the following page, correct?
![Screenshot 2024-11-07 at 08 01 04](https://github.com/user-attachments/assets/170863e3-45ef-4f35-9143-5eb7eec59fc0)

If so, you must access the console at https://console.cloud.vmware.com/ (or by clicking the link on the 403 error page) and create an organization. Afterward, you should be able to access the marketplace without issues.

**Comment by KB-smi** [comment]
> I assume you’re receiving the following page, correct? ![Screenshot 2024-11-07 at 08 01 04](https://private-user-images.githubusercontent.com/13216600/383850247-170863e3-45ef-4f35-9143-5eb7eec59fc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTIzODUsIm5iZiI6MTczMDk5MjA4NSwicGF0aCI6Ii8xMzIxNjYwMC8zODM4NTAyNDctMTcwODYzZTMtNDVlZi00ZjM1LTkxNDMtNWViN2VlYzU5ZmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE1MDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMmZiODFlYjc3N2E1Mjg0ZTEyYzAzZmRhZjg4MzE5NzZjNzJhNmQxYzZmOWUwOTNiZWQxMjhhMTQwZDU0NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uMFl7jMxwUrlXYV2b27Z1F4hq63UWhYmtKFvAOJtUc0)
> 
> If so, you must access the console at https://console.cloud.vmware.com/ (or by clicking the link on the 403 error page) and create an organization. Afterward, you should be able to access the marketplace without issues.

Clicking the link on the error page (while signed in) gets me this page:
{
    "cspErrorCode": "340.800",
    "errorCode": null,
    "statusCode": 500,
    "traceId": "c6d016103517099b2d35bfdbff69af27",
    "metadata": null,
    "message": "Failed to execute gaz operation",
    "requestId": "05f3e43bc8144922e15f3b6774dfee38",
    "moduleCode": 340
}

When I refresh the page, I get a 'Sorry, it looks like you don't have any invitations to VMware Cloud Services'.  I'll click the link there and it times out.

I went back to the other page to see if there is a way to create an organization, but there doesn't seem to be any options to do that from the screens I looked at.  We're a vmware customer already as well for other products.  Searched for how to create org, but no results as well in the help section.

I end up in loops.

**Comment by mehmetaydogduu** [comment]
The console at https://console.cloud.vmware.com always redirects to login after successful login.

**Comment by acutbal** [comment]
Hello,
I have the same issue, I can't access to the downloads and get a great 403 result...

Best regards.

**Comment by HARIS-581** [comment]
What is the solution for this ?? Need to download file urgently

**Comment by HeliousBlogger** [comment]
Cant download :(

**Comment by herriejr** [comment]
Same issue here, I get a 'Sorry, it looks like you don't have any invitations to VMware Cloud Services', but I managed to solve it.
You then have so go to the 'All' tab on that page. On the left select 'Free' to get to see free tier products. On the right, you should now see a number of tiles, with also the 'VMWare Marketplace' tile. 
If you click 'Access' on that tile, you can create an organization. Now you can download the images.

**Comment by kevinpknight** [comment]
Also trying to download this.

I couldn't get @herriejr  workaround to work as I never see the 'invitation' message.

I can get to the marketplace list of tiles and see the tile for the image, but that then takes me back to detail page for the image and back around the sign / 403 loop

It's pretty frustrating

**Comment by archer007** [comment]
I also get stuck in a loop trying to download sometimes, and it ends by denying me the ability to download the OVA because I don't have permission because I don't have an invitation to VMware Cloud Services, and there is no way to request or get an invite. This is broken and making me reconsider using Bitnami at all if the process for even trying the product is this painful

**Comment by dtepk** [comment]
having the exact same issue and have wasted hours on this - wanted to download ova for testing it out on local virtualbox. is there an alternative to this?

**Comment by ashrafxcoder** [comment]
@carrodher unable to create organization as suggested in the comments to download free images

![Image](https://github.com/user-attachments/assets/5015d4ef-affb-4740-a599-2dbf632692a4)

**Comment by silfax** [comment]
Why not simply asking for money rather than advertising as free and making it impossible to download?

**Comment by Black6spdZ** [comment]
what an utter cluster F! anywhere the old ones are mirrored?

**Comment by supr4s** [comment]
I've finally managed to get the OVA back, but it's been a long road ... Please, go back to your old download repo. Broadcom must be boycotted with their shameful practices, and it's not normal to have to register on their platform to get a bitbami image.

**Comment by mehmetaydogduu** [comment]
It goes to a page and result 404
https://console.cloud.vmware.com/csp/gateway/portal/#/self-onboarding/organization-and-payment/steps

**Comment by greenflute** [comment]
same same always the same, not only the page, but also more important, the way ...

**Comment by bobigod6** [comment]
still getting the same issue,there aren't any alternatives?

**Comment by chizuoka** [comment]
Same here... its impossible to access and nowhere to add an organization just an error no invites

**Comment by ShahriarKh** [comment]
Sign in -> redirect -> 403 -> console -> 404 -> blah blah -> ...
Absolute shitshow

**Comment by iffyb** [comment]
Yeah, I've been trying to set up a svn server and I just don't trust myself to do it securely, but I can't figure out the simple task of downloading the supposedly free image.

**Comment by jotamartos** [comment]
The Marketplace should redirect you to https://vcf.broadcom.com/vsc, is that happening? Which solution are you trying to download? We would like to reproduce the problem

**Comment by almostobvious** [comment]
@jotamartos - there are so many problems... But let me show you a super simple way to get stuck in a quagmire of bugs and broken links.

1. Logout for all broadcom/vmware/bitnami services. Better yet start with a new web browser without any accounts (a typical use case likely common to all people who have the issue)
2. Go to https://bitnami.com/stack/gitlab/virtual-machine
3. Click on "Download OVA format"
4. Bug #1: Click on "Create marketplace account" - result is 404 Page not found
5. Click one of several "Sign in" links on the page (arguably have multiple "Sign in" links next to each other is also a bug?)
6. Bug #2: The above produces VMware marketplace titled page with a "403 No access You don't have access to application.". One would expect this to present options for access not a confusing error page.
7. The only available option at this stage is to click the "VMWare Cloud Services console" link.
8. Bug #3: Now if you are newly registered you again get a blank error page that now says "Sorry, it looks like you don't have any invitations to VMware Cloud Services.". You are now directed to click on ALL (finding it is a fuss, but really should the site be sending you there directly if that's the only option?
9. Now click "All" select "Free" and under "VMware Marketplace" click "Access" link
10. Bug #4: You wait a bit and then see "404 Page not found". Only two clickable options are to sign out or to go "Back to VMWare cloud services".

So yes, none of the bitnami images are available or accessible to new users. Please reopen this issue.

**Comment by almostobvious** [comment]
Just to add, the link you shared https://vcf.broadcom.com/vsc/ doesn't work properly either.

1. Go to https://vcf.broadcom.com/vsc/
2. Click on developer tools
3. Search Gitlab and select "Bitnami Virtual Appliance for Gitlab CE"
4. You are sent to https://vcf.broadcom.com/vsc/services/details/gitlab?slug=true
5. None of the links on that page work - they all either produce an error or send you into the vicious cycle I've described above.

**Comment by jotamartos** [comment]
Sorry for the inconvenience @almostobvious. We are investigating it with the Marketplace team and will provide more information as soon as possible.

**Comment by giuseppe-macario** [comment]
Hello everyone, I'm a new Bitnami user and I'm also unable to download the .OVA file from https://bitnami.com/stack/lamp/virtual-machine (I'm getting the same errors that almostobvious already reported)
Do you know of any alternative mirrors where I can download it?
It doesn't necessarily have to be the latest version.

**Comment by netsanetss** [comment]
Same here,  I'm also unable to download the .OVA file from https://vcf.broadcom.com/vsc/services/details/redmine?slug=true

could you please help me?

**Comment by jotamartos** [comment]
We reported the issue to the Marketplace team and they are taking a look at it. Sorry for the inconvenience.

**Comment by kaboddy** [comment]
> What a disaster. I'm getting the same redirect and permissions runaround. I even have a nda level account with Broadcom. That account or a completely new "burner" in a blank browser, same dysfunctional run around.
> 
> Probably because it is a "free" download. If it we're a $20K download somehow I think this would magically work without a hitch.
> 
> Easier to just handroll a LAMP VM in a non-VMWare format on a non-VMWare server.

Exactly what I ended up doing - 6 months ago when I submitted the issue... lol.  Glad they're just getting to it now.

**Comment by roungchen** [comment]
I having the same problem. I manage to enter Organization by going back to https://console.cloud.vmware.com/csp/gateway/portal/#/services/organization, click on All, then click any Pricing Model Free , I choose "VMware Cloud Sizer" and click access. It prompt me to enter Organization name.  So I tried with Vmware Marketplace and got 404. I believe one or all parameters maybe incorrect, https://console.cloud.vmware.com/csp/gateway/os/api/onboarding-referral?source=**MARKETING**&onboardingContextId=**5c67852a-3cde-41f5-a80a-ce7f7833c0cc**

**Comment by AeonJJohnson** [comment]
> Exactly what I ended up doing - 6 months ago when I submitted the issue... lol. Glad they're just getting to it now.

Except they're not getting to it. Behind the scenes the Broadcom Volturi are blocking access to anything free. ;-)

**Comment by jotamartos** [comment]
I'm sorry for the delay, we are still in conversations with the Marketplace team and hope to resolve this issue as soon as possible. In the meantime, you can deploy the solutions using the Bitnami Containers and Helm Charts

https://github.com/bitnami/containers
https://github.com/bitnami/charts/

**Comment by ImChiip** [comment]
Thank you, but if users want to download an OVA, it's not to launch a container or a helm chart.

Broadcom support is getting worse and worse.
I contacted them about this issue, and their response was to subscribe to Bitnami for a free product.
Nice bullshit form Broadcom again.

Good luck for talking to broadcom @jotamartos

**Comment by Black6spdZ** [comment]
Get what you can from late '24 on wayback before it was moved to F'ing
broadcom and update it..

**Comment by UtzSystemLLC** [comment]
It’s incredible that they take so long to solve it.

**Comment by jirkacapek123** [comment]
I agree that this is totally unacceptable, how can you manage to lock an open source project behind such a hassle? You should just be able to download the ova without needing to login.

**Comment by Donald-Donaldson** [comment]
Utter shit show of a company. Utter clowns.
