### ISSUE TITLE
[Dolibarr] Dolibarr stack not opening after upgrade to macOS Sequoia

### ISSUE THREAD

**Issue by kartikmittal2006** [bitnami/vms#1687]
### Name and Version

bitnami/dolibarr 12.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Upgrade to latest macOS Sequoia
2. Open application dolibarr
3. Click Start button
4. Error prompt after 30 seconds 'Error starting "dolibarr" stack' and 'Error starting "dolibarr" stack'
5. Log tab displays 'INFO: Starting "dolibarr" stack ERROR: Error starting "dolibarr" stack: cannot start stack: ssh not accessible'

### What is the expected behavior?

Application should've started along with all the services

### What do you see instead?

Error

### Additional information

Not able to access dolibarr app, the app contains data for past 4-5 years and i have 2 backup files viz. 'documents_bitnami_dolibarr_12.0.4_202409271328.tar' and 'mysqldump_bitnami_dolibarr_12.0.4_202409271327.sql'. For safety I have created a copy for folder 'stackman' as well. Please resolve the issue as the app was running smoothly before macOS upgrade.

Moreover I tried moving onto latest version of dolibarr using VM but not able to restore the backup

Please help 
<img width="503" alt="Screenshot 2024-10-11 at 14 12 19" src="https://github.com/user-attachments/assets/bfa8f910-7d3e-4544-86cd-eb269dc8b6d4">

**Comment by kartikmittal2006** [comment]
I've deleted 'stackman' from '.bitnami', restarted app, quit the app, replaced 'machine.qcow2' in 'vm' folder, now facing new error and app still not starting
ERROR: cannot map MAC address "92:29:ba:9c:ca:56" to IP: Could not find an IP address for 92:29:ba:9c:ca:56


<img width="498" alt="Screenshot 2024-10-11 at 18 27 10" src="https://github.com/user-attachments/assets/af7dfacd-402e-4d77-b91e-cb1c11e8ad31">

**Comment by jotamartos** [comment]
Hi @kartikmittal2006,

These Stackman installers deprecated some years ago and you should have moved to a different platform back in the days. We suggest you download the OVA and migrate the backups you have to that new deployment

https://bitnami.com/stack/dolibarr/virtual-machine
