### ISSUE TITLE
sudo rm -rf /opt/bitnami/mariadb

### ISSUE THREAD

**Issue by EmanuelLave** [bitnami/vms#1688]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic was not useful. Could you please tell us why?

N/A

### Describe your issue as much as you can

Hello,

I have a Bitnami installation on a Google VM. I encountered several conflicts with the MariaDB installation, and while reading forums, I found that I could reinstall it. Unfortunately, I executed the command 
**sudo rm -rf /opt/bitnami/mariadb**
but I previously backed up the data with
sudo **cp -r /opt/bitnami/mariadb/data /home/bitnami/backup/mariadb-data-backup.** 
However, as you can see, only the data folder was backed up. How can I recover my MariaDB service?

**Comment by EmanuelLave** [comment]
I've noticed that when I execute sudo systemctl start mariadb and then sudo mysql -u root -p, I can access the MariaDB service. 
It seems there might be a second MariaDB installation on the VM. Is it possible to convert this existing installation into the primary MariaDB for Bitnami, moving it to the /opt/bitnami folder and restoring the data from my previous backup?

**Comment by gongomgra** [comment]
@EmanuelLave that other MariaDB server may be the one from the official APT repositories, which is not the one we include in our images. I'm afraid that if you have removed the `/opt/bitnami/mariadb` folder from your server but you still have a backup of the data, there is only two ways to recover it:

* Launch a previous backup of the entire server and restore the data backup.
* Launch a fresh new server and restore the data backup.

Alternatively, you can continue using the MariaDB server installed from APT, but note we don't officially support that service, and that it may affect your other Bitnami services performance/compatibility.
