### ISSUE TITLE
[Bitnami Wordpress] AH00526: Syntax error on line 51

### ISSUE THREAD

**Issue by claylaw** [bitnami/vms#169]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

24ad19e0-fa6d-2f3c-bf3b-0445a30f6c89

### bndiagnostic output

? Connectivity: Found possible issues
? Processes: Found possible issues
✓ Mariadb: No issues found
✓ Php: No issues found
✓ Resources: No issues found
? Apache: Found possible issues
✓ Wordpress: No issues found
[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:
https://docs.bitnami.com/general/faq/administration/use-firewall/
[Processes]
Press [Enter] to continue:
One or more component's processes are not running:
apache not running
You can try to restart the process with the following command:
$ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME
Your instance is using swap memory: total used free shared buff/cache available
Mem: 989 376 253 12 359 447 Swap: 634 82 552This usually means that your
instance is running low on memory. You could try to increase your instance's
memory. Please check your cloud provider's documentation for more information.
[Apache]
The Apache configuration has errors:
AH00526: Syntax error on line 51 of 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile: 
file '/opt/bitnami/apache2/conf/bitnami/certs/server.crt' does not exist or is 
empty

### bndiagnostic was not useful. Could you please tell us why?

Apache confirguration issue

### Describe your issue as much as you can

The Apache configuration has errors:
AH00526: Syntax error on line 51 of
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
file '/opt/bitnami/apache2/conf/bitnami/certs/server.crt' does not exist or is
empty

### bndiagnostic was not useful. Could you please tell us why?

I tried the suggested code but I was unable to resolve the issue

### Describe your issue as much as you can

My issue involves the renewal of the Let's Encrypt SSL certificate. I have tried to manually revoke the SSL certificate and nothing seems to be working. My site is currently down and has been for two weeks now. I need to renew the certificate to have the site up and running again. Any assistance would be appreciated, thanks.

**Comment by jotamartos** [comment]
Hi @claylaw,

> The Apache configuration has errors:
> AH00526: Syntax error on line 51 of
> /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
> file '/opt/bitnami/apache2/conf/bitnami/certs/server.crt' does not exist or is
> empty

Your certificate expired and that's why you can't restart Apache now. Let's recover the archived certificate for you to be able to restart the server and then generate a new one. 

- Copy the archived certs

```
sudo cp -rp /opt/bitnami/letsencrypt/archives/*.crt /opt/bitnami/apache2/conf/bitnami/certs/server.crt
sudo cp -rp /opt/bitnami/letsencrypt/archives/*.key /opt/bitnami/apache2/conf/bitnami/certs/server.key
```

- Restart Apache

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

- Generate new SSL certs. Remember to download the latest version of the bncert tool

https://docs.bitnami.com/general/how-to/understand-bncert/

**Comment by claylaw** [comment]
Hello, 

Thank you for your response. I tried to recover the archived certificate and I got this error:

cp: cannot stat '/opt/bitnami/letsencrypt/archives/*.crt': No such file or directory
cp: cannot stat '/opt/bitnami/letsencrypt/archives/*.key': No such file or directory

What could be the problem?

**Comment by jotamartos** [comment]
Hi @claylaw,

I included an asterisk in my command that matches all names inside the directory. The Bitnami Diagnostic tool showed you have cert files there. Can you please confirm it?

```
sudo ls -la /opt/bitnami/letsencrypt/archives/
```

**Comment by claylaw** [comment]
I can confirm that they are there.

**Comment by claylaw** [comment]
But even with the command I get the same output from the system:

cp: cannot stat '/opt/bitnami/letsencrypt/archives/*.crt': No such file or directory

I included the asterisk

**Comment by jotamartos** [comment]
In that case, specify the file you want to copy

```
sudo cp -rp /opt/bitnami/letsencrypt/archives/1658155559.DOMAIN.com.crt /opt/bitnami/apache2/conf/bitnami/certs/server.crt
sudo cp -rp /opt/bitnami/letsencrypt/archives/1658155559.DOMAIN.com.key /opt/bitnami/apache2/conf/bitnami/certs/server.key
```

>Note: Replace the DOMAIN placeholder

**Comment by claylaw** [comment]
Hi, 

I tried the file copying as advised and got this error at first:

cp: not writing through dangling symlink '/opt/bitnami/apache2/conf/bitnami/certs/server.key'

then this error when running the Bitnami HTTPS Configuration Tool:

Warning: The web server configuration check failed. Please fix the configuration 
error: 
AH00526: Syntax error on line 7 of 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf:
SSLCertificateKeyFile: file 
'/opt/bitnami/apache2/conf/bitnami/certs/clay-law.com.key' does not exist or is 
empty

I don't understand why this keeps happening. Should I run the diagnostic tool again? Any assistance is appreciated as always.

**Comment by jotamartos** [comment]
Remove the file first and then run the copy command 

```
sudo rm -rf /opt/bitnami/apache2/conf/bitnami/certs/server.*
sudo cp -rp /opt/bitnami/letsencrypt/archives/1658155559.DOMAIN.com.crt /opt/bitnami/apache2/conf/bitnami/certs/server.crt
sudo cp -rp /opt/bitnami/letsencrypt/archives/1658155559.DOMAIN.com.key /opt/bitnami/apache2/conf/bitnami/certs/server.key
```

**Comment by claylaw** [comment]
cp: cannot stat '/opt/bitnami/letsencrypt/archives/1658155559.clay-law.com.com.crt': No such file or directory

same error as above.

**Comment by jotamartos** [comment]
I do not know what's happening there but let's try to follow a different approach. Could you please follow this guide to generate a new SSL certificate?

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

After that, you will need to edit the Apache's configuration to use this and restart the Apache server for the changes to take effect.

```
  SSLCertificateFile "/opt/bitnami/apache2/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache2/conf/bitnami/certs/server.key"
```

>Note: Ensure both /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf and /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf files use that configuration.

**Comment by claylaw** [comment]
Good morning.

I tried the alternative approach, did the test, and found that for my instance approach A works.

Then I tried to install the Lego client but the following error came up:

mv: cannot stat 'lego': No such file or directory

At this point, I think the best approach would be to re-do the website all over again rather than jump through all these hoops. It's time-consuming but at least I can start afresh. Thanks for your help.

**Comment by jotamartos** [comment]
>mv: cannot stat 'lego': No such file or directory

Did you replace the X.Y.Z placeholder with the one of the downloaded version? That is "4.8.0" right now. If you didn't replaced that, the place was not extracted properly and that's why the lego binary was not available. 

>At this point, I think the best approach would be to re-do the website all over again rather than jump through all these hoops. It's time-consuming but at least I can start afresh. Thanks for your help.

If you can start the project from scratch, the Bitnami HTTPS configuration tool should handle all the SSL configuration changes.
