### ISSUE TITLE
[WordPress] Cloud-init - New default deployment error-sudo cloud-init schema --system Error: Cloud config schema errors: format-l1.c1: File None needs to begin with "#cloud-config"

### ISSUE THREAD

**Issue by arshif** [bitnami/vms#1690]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4b6de147-9b5f-4400-7cbd-e4764f4e1156

### bndiagnostic output

Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

|-
The bndiagnostic tool has finished searching for errors and has found some 
issues that might be related to yours. The output will be shown on the next 
page:
                                    
Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Oct 14 22:11:18.264698 2024] [proxy_fcgi:error] [pid 2155:tid 2507] [client 
**ip_address**:62577] AH01071: Got error 'PHP message: PHP Warning: Undefined 
array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php on line 100; PHP 
message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 101; PHP message: PHP Warning: 
Press [Enter] to continue:
Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php 
on line 716; PHP message: PHP Warning: Undefined array [Mon Oct 14 
22:13:23.268870 2024] [core:error] [pid 2155:tid 2495] [client 
**ip_address**:41202] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh)
 [Mon Oct 14 22:13:24.126694 2024] [core:error] [pid 3232:tid 3316] [client 
**ip_address**:41442] AH10244: invalid URI path 
(/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32
%65/%%32%65%%32%65/%%32%65%%32%65/bin/sh)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 
Press [Enter] to continue:

===== End of bndiagnostic tool output =====

                                    
Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

4b6de147-9b5f-4400-7cbd-e4764f4e1156

And paste it in your Bitnami Support ticket.

### bndiagnostic was not useful. Could you please tell us why?

It did not catch cloud-init error.

### Describe your issue as much as you can

New default deployment on GCP is giving following error: sudo cloud-init schema --system
Error:
Cloud config schema errors: format-l1.c1: File None needs to begin with "#cloud-config"

I have noticed this on my customized VM, tried to resolve it by updating config, uninstalling reinstalling cloud-init but it does not seem to work. I then picked up default VM installation and got the same error.

**Comment by jotamartos** [comment]
I just tried to reproduce the issue and launched a Bitnami WordPress and LAMP solutions. I know you only launched WordPress, but another user mentioned this issue as well in https://github.com/bitnami/vms/issues/1669. 

However, my deployments worked as expected, there is no error in the console and the different components were launched without problems

![Screenshot 2024-10-17 at 09 18 55](https://github.com/user-attachments/assets/d7dd997d-b0a2-4954-94ba-593803d6449e)
![Screenshot 2024-10-17 at 09 24 02](https://github.com/user-attachments/assets/ef73cdf0-7097-4007-8630-a4aef4093e36)

Please ensure you launch a VM with enough resources to run the deployment process. Could you please try to launch the VM again? 

Thanks
