### ISSUE TITLE
[Prestashop] SSL setup makes site inaccessible

### ISSUE THREAD

**Issue by DaddioD** [bitnami/vms#1691]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

866c156d-8fa7-a245-61df-d6da0a05fe97

### bndiagnostic output

    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ? Resources: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

Not sure what is causing the problem

### Describe your issue as much as you can

Have installed AWS blueprint for Prestashop
Assigned static IP address
Pointed domain and www. subdomain to instance and static IP address
Reset PrestaShop to domain.com

All works fine when using HTTP

I run the bncert-tool to setup letsencrypt SSL on the domain.com and www.domain.com with the default options.

after running the bncert-tool the entire site is inaccessible. Even by IP address

**Comment by DaddioD** [comment]
Not sure what to do from there.

**Comment by jotamartos** [comment]
I can see that your site is accessible now at ***diod.com (all requests redirect to the non-www domain). The configuration looks valid and you just need to configure the SSL certs using the non-www domain as the main one. 

https://docs.bitnami.com/general/how-to/understand-bncert/

**Comment by DaddioD** [comment]
Do I use the following answers

Enable HTTP to HTTPS redirection Y

Enable non-www to www redirection N

Enable www to non-www redirection Y

In the past this has caused sight failure with an error of "too many
tedirects".

**Comment by jotamartos** [comment]
> In the past this has caused sight failure with an error of "too many redirects".

This is usually caused by the application. If prestashop is configured with www, Apache will be redirecting to non-www and the app will be redirecting to www again, creating this redirection loop.

**Comment by DaddioD** [comment]
Use certbot setup and all worked like normal.
