### ISSUE TITLE
[WordPress] About Starting and Stopping Services on Bitnami WordPress (1) on Lightsail.

### ISSUE THREAD

**Issue by bakabonpapa** [bitnami/vms#1692]
### Describe your issue as much as you can

Hello, I am a Bitnami Wordpress user on AWS Lightsail.
I have 2 questions about the management script inside the image.

**No.1**
In the documentation (2), only Apache is listed for the argument in the script. However, when I ran the following commands for PHP and Mariadb, I was able to start and stop each service.
Can I regard this behaviors as expected?

Start and stop commands for each service
PHP
```
$ sudo /opt/bitnami/ctlscript.sh start php-fpm
$ sudo /opt/bitnami/ctlscript.sh stop php-fpm
```

Mariadb
```
$ sudo /opt/bitnami/ctlscript.sh start mariadb
$ sudo /opt/bitnami/ctlscript.sh stop mariadb
```

**No.2**
If the answer for No.1 is "Yes", are these all services commands available for every Bitnami WordPress image?
I have an older version of the image running on production environment of my client and its Message-of-the-Day" message points to the same documentation as the newer one. And I wanna know if the commands are valid in it.

Thank you.
Masaki Yamanaka

1: Bitnami WordPress image on AWS Lightsail
https://aws.amazon.com/marketplace/pp/prodview-bzstv3wbn5wkq

2: Start or stop services document
https://docs.bitnami.com/aws/apps/wordpress/administration/control-services/

**Comment by bakabonpapa** [comment]
Excuse me. The point that I wanted to ask for No.1 is the following.
The stopping and starting commands for Apache service is written in the document (1), but for PHP and Mariadb there is no line for them in it. At the same time, the commands for the two services, I could successfully executed them. Can I regard the two commands and depend on them for controling the PHP and Mariadb services?

For No.2.
I executed the commands in the latest version of Bitnami Wordpress instance on AWS Lightsail.
My question is, in short, are the commands executable in older versions of the imanges?

If still unclear about the questions, please tell.

1: Bitnami WordPress image on AWS Lightsail
https://aws.amazon.com/marketplace/pp/prodview-bzstv3wbn5wkq

Commands for the two services
```
$ sudo /opt/bitnami/ctlscript.sh start php-fpm
$ sudo /opt/bitnami/ctlscript.sh stop php-fpm
```

```
$ sudo /opt/bitnami/ctlscript.sh start mariadb
$ sudo /opt/bitnami/ctlscript.sh stop mariadb
```

**Comment by jotamartos** [comment]
>In the documentation (2), only Apache is listed for the argument in the script. However, when I ran the following commands for PHP and Mariadb, I was able to start and stop each service. Can I regard this behaviors as expected?

>If the answer for No.1 is "Yes", are these all services commands available for every Bitnami WordPress image?

Yes. As the documentation mentions, Apache is just an example ("such as Apache only"). You can use the ctlscript file to manage all the services running under /opt/bitnami.

>My question is, in short, are the commands executable in older versions of the imanges?

Yes, the ctlscript.sh file has been the way to manage the services since the very beginning.

**Comment by bakabonpapa** [comment]
Thank you, jotamartos. your info is enough now for my environment.
