### ISSUE TITLE
[<LAMP>] Folder Permissions

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1693]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

fef52c66-b986-9b4a-fecf-06a794115f5f

### bndiagnostic was not useful. Could you please tell us why?

Not related

### Describe your issue as much as you can

Hi,

I have set folder permissions to 755 but still WordPress won't accept them. How can I ensure that it accepts 755 too and not only 775.

Kindly support.

**Comment by gongomgra** [comment]
Hi @huzanf,

The bndiagnostic tool can't collect any data from your custom `/opt/bitnami/FUD` folder, but I think I have an idea of what can be the issue. The system user running the Apache web server in our installations is `daemon`, and by default the filesystem permissions for the web applications are set to `bitnami:daemon`. If you don't provide enough permissions for the `daemon` group to your files, then the Apache service won't be able to access it. Can you check it on your side?

Apart from the above, please take a look at the Apache logs at `/opt/bitnami/apache/logs/error_log`. I see many errors there that are not related to filesystem permissions.

**Comment by huzanf** [comment]
Thank @gongomgra 
Just to confirm that since my website is in `/opt/bitnami/FDU` is the correct path to keep the website on? Earlier I used to hoist my website under this path: `/opt/bitnami/apache/htdocs`.

**Comment by huzanf** [comment]
Also, how do I disable `safe_mode`?

**Comment by gongomgra** [comment]
Hi @huzanf,

Yes, the `/opt/bitnami/FDU` folder is a correct path to place your custom apps inside instead of `/opt/bitnami/apache/htdocs`. Regarding the PHP `safe_mode` setting, it looks like it was deprecated back in PHP 6 long time ago

https://wiki.php.net/rfc/removal-of-deprecated-features
