### ISSUE TITLE
Renew SSL failed. Can't restart services now.

### ISSUE THREAD

**Issue by blairzotron** [bitnami/vms#1694]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a9f7f4f6-813f-96ab-2a88-16773bfdae30

### bndiagnostic was not useful. Could you please tell us why?

I don't see actionable suggestions on how to fix this

### Describe your issue as much as you can

I stopped services (sudo /opt/bitnami/ctlscript.sh stop) and ran sudo /opt/bitnami/bncert-tool which failed because it couldn't bind to port 80 or 443, even though I stopped services.  Tried again with more attempts to free up those ports (e.g. sudo service apache2 stop). Ran bncert-tool again, same issue. Tried certbot, which reported success, tried to restart services, but got an error that bncert-tool exited with error code. Tried running bncert-tool again. No luck. Manually reverted /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf to use dummy certificates, retried bncert-tool, no luck. Tried reverting to a backup copy of certs, no luck. Tried removing existing certificates with certbot delete, re ran bncert-tool, which now wants me to specify the installation directory, which I provide as /opt/bitnami, but it then reports "Warning: The web server configuration check failed. Please fix the configuration. error: /bin/sh: 1: /opt/bitnami/apache/sbin/nginx: not found"
At one point, I saw an error about "Control file '/etc/gonit/gonitrc' does not exists". 
Even though I can't start services, the website is showing "Index of /" and nothing is listed.

**Comment by blairzotron** [comment]
I have fixed the issue following these steps:

0. Stop Services:
sudo service apache2 stop
sudo /opt/bitnami/ctlscript.sh stop

1. Remove the certificates folder from the /opt/bitnami/letsencrypt/ dir:
cd /opt/bitnami/letsencrypt/
mv ./certificates/ ./__certificates/
mkdir ./certificates/
chown bitnami ./certificates/
 
 
2. Remove certificates from the /opt/bitnami/apache/conf/ dir:
cd /opt/bitnami/apache/conf/
mv ./view.winstorms.ca.crt ./__view.winstorms.ca.crt
mv ./view.winstorms.ca.key ./__view.winstorms.ca.key


3. Comment out the references to the files in step 2:
vi /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf
put a "#" before these 2 lines:
    SSLCertificateFile "/opt/bitnami/apache/conf/view.winstorms.ca.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache/conf/view.winstorms.ca.key"

4. Run bncert-tool as usual:  
sudo /opt/bitnami/bncert-tool

5. Undo step 3 (remove the "#" from those 2 lines)

6. Restart the server: 
sudo /opt/bitnami/ctlscript.sh start

**Comment by blairzotron** [comment]
I wish there was a command to reset to defaults, like _bncert-reset_ or something. 

I have encountered issues before where the bundled certificate did not auto-renew because one of the domains no longer pointed at us. Then it expired and could not be renewed or removed because it was expired. The steps above fixed that issue, too.

**Comment by jotamartos** [comment]
I'm glad to hear that you managed to solve the issue. For the record, there is a guide in our documentation that explains how to revoke a certificate.  This is valid when you have a cert for a domain that is not valid anymore. You can revoke the old certs and create new ones later

https://docs.bitnami.com/general/how-to/understand-bncert/#manually-revoking-an-existing-certificate
