### ISSUE TITLE
[postgresql] - ami-07fd49b0a3da33634

### ISSUE THREAD

**Issue by simonvolteras** [bitnami/vms#1695]
### Platform

AWS - ec2 - AMI is 07fd49b0a3da33634

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

65fef4b0-92c7-c3ef-e08b-2b85cf91072d

### bndiagnostic output

The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
    ✓ Resources: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

I don't think the ports being closed is related, we only have 5432 open for postgres

### Describe your issue as much as you can

Stopped ec2 instance and since restarting it the bitnami postgres service does not start. 

Get the following when checking the status:

 sudo service bitnami status
× bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-10-22 14:38:01 UTC; 24min ago
    Process: 4403 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
        CPU: 4.577s

Oct 22 14:38:01 ip-10-0-80-141 bitnami[4705]: 2024-10-22T14:38:01.019Z - error: Unable to perform start operation Export start for postgresql failed with exit code 1 service=provisioner
Oct 22 14:38:01 ip-10-0-80-141 bitnami[5071]: ## 2024-10-22 14:38:01+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_bitnami_agent_extra...
Oct 22 14:38:01 ip-10-0-80-141 bitnami[5071]: ## 2024-10-22 14:38:01+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agent...
Oct 22 14:38:01 ip-10-0-80-141 bitnami[5071]: ## 2024-10-22 14:38:01+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welcome_file...
Oct 22 14:38:01 ip-10-0-80-141 bitnami[5071]: ## 2024-10-22 14:38:01+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_credentials_file...
Oct 22 14:38:01 ip-10-0-80-141 bitnami[5071]: ## 2024-10-22 14:38:01+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metadata...
Oct 22 14:38:01 ip-10-0-80-141 systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
Oct 22 14:38:01 ip-10-0-80-141 systemd[1]: bitnami.service: Failed with result 'exit-code'.
Oct 22 14:38:01 ip-10-0-80-141 systemd[1]: Failed to start bitnami.service - LSB: bitnami init script.
Oct 22 14:38:01 ip-10-0-80-141 systemd[1]: bitnami.service: Consumed 4.577s CPU time.

**Comment by gongomgra** [comment]
Hi @simonvolteras,

Thanks for using Bitnami. The only error I can find in the bndiagnostic bundle that may prevent services from start is the next one

```
-----------------------------------
Get the ctlscript status
-----------------------------------
Running: ./ctlscript.sh status
In: /opt/bitnami

Output:


Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)
```

Did you modify any configuration for the Gonit service? Can you try to start it manually?

```
sudo gonit start
sudo gonit status
```

You can find more information about it at https://docs.bitnami.com/aws/apps/wordpress-multisite/administration/configure-use-gonit/
