### ISSUE TITLE
[WordPress] Memory Limit 40M

### ISSUE THREAD

**Issue by manashjyotix** [bitnami/vms#1699]
### Describe your issue as much as you can

I tried to increase the WP Memory Limit using the following changes WP-Config.PHP, PHP.ini, .user.ini, .htaccess in the wordpress directory. It's not working. Then I use FTP "/opt/bitnami/php/etc" php.ini I added 

```
; PHP Memory Limit
memory_limit = 2048M
wp_memory_limit = 2048M

; PHP Maximum Execution Time
max_execution_time = 300

; PHP Max Input Time
max_input_time = 600

; Upload and Post Limits
upload_max_filesize = 2048M
post_max_size = 2048M
```

but WordPress memory not changed. Help me, Thank you

**Comment by jotamartos** [comment]
>Then I use FTP "/opt/bitnami/php/etc" php.ini I added

Please note that some of those parameters are already in the file, you do not need to add them, just modify the values. Remember to restart the services after making the changes

```
sudo /opt/bitnami/ctlscript.sh restart
```
