### ISSUE TITLE
[Moodle] Timeout expired

### ISSUE THREAD

**Issue by ankamuellner** [bitnami/vms#1701]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

n/a

### bndiagnostic output

bitnami-lms-powered has resource level errors
moodle-software: {"ResourceType":"runtimeconfig.v1beta1.waiter","ResourceErrorCode":"504","ResourceErrorMessage":"Timeout expired."}

### bndiagnostic was not useful. Could you please tell us why?

tool did not run 

### Describe your issue as much as you can

Error is from Google Deployment manager 

This deployment has resources from the Runtime Configurator service, which is in Beta. There is no planned date for moving this feature into General Availability (GA). Examples of runtimeconfig types used: runtimeconfig.v1beta1.config, runtimeconfig.v1beta1.waiter

software config waiter

{"ResourceType":"runtimeconfig.v1beta1.waiter","ResourceErrorCode":"504","ResourceErrorMessage":"Timeout expired."}
runtimeconfig.v1beta1.waiter
failure
cardinality:
  number: 1.0
  path: status/failure

**Comment by ankamuellner** [comment]
just adding the title.

**Comment by jotamartos** [comment]
Hi, 

This may be a temporary issue (probably a performance one) when launching the VM. Could you please confirm the password was generated and all services are running?

```
sudo cat /home/bitnami/bitnami_credentials
sudo /opt/bitnami/ctlscript.sh status
```
