### ISSUE TITLE
[Tolgee] request for new Bitnami application stack

### ISSUE THREAD

**Issue by ZaLiTHkA** [bitnami/vms#1704]
### Describe your suggestion as much as you can

Tolgee is available as open source and provides an option for self-hosting, but doing so requires either Docker to spin up a preconfigured image or manual configuration of multiple different services.

would it be possible to get a Bitnami stack installer for Tolgee and Postgres that can be used on (at least) Windows Server?

---

I find myself in a situation where I literally need about 50 or 60 strings more than the 1000-string limit that their managed service free plan offers. I have access to an existing Windows Server host that I can deploy software to.. so having the option to run a Bitnami installation and have Tolgee up and running on our private server would be nothing short of amazing.

**Comment by ZaLiTHkA** [comment]
alternatively, if someone could point me to the relevant documentation to create a Bitnami stack myself, I would love to give it a shot... this repo's readme states "Before continuing, please review our useful guides about how to configure and use your application in our [documentation](https://docs.bitnami.com/general/apps/).", but that URL simply links to the list of currently available application stacks, I don't see anything there with regards to how to create a new stack.

**Comment by ZaLiTHkA** [comment]
so... by the lack of response, I'm guessing this isn't likely to happen then?

FWIW, I won't bump this request if it gets marked as "stale" a second time.

**Comment by carrodher** [comment]
Thank you for your suggestion!

We truly appreciate your input. Our team will now conduct an internal review to assess the viability of integrating this new open-source product into our catalog. As we have limited resources, please understand that this evaluation process might take some time. We will apply the' on-hold' label to ensure that your idea receives the attention it deserves. This will prevent our automated system from prematurely closing the issue.

We'll let you know of any developments regarding the addition of this product. Your patience and understanding are greatly appreciated.

**Comment by ZaLiTHkA** [comment]
thanks @carrodher, I do appreciate that.

just out of curiosity, is there any public documentation that covers the process of creating new Bitnami app stacks? if so, I honestly would love to try putting this together myself.

**Comment by ZaLiTHkA** [comment]
I'm not terribly surprised, since (I think) I'm the only person who has asked for this.. no problem though, you'll never know if you don't ask.
