### ISSUE TITLE
[WordPress] Failed to fetch https://repo.saltproject.io

### ISSUE THREAD

**Issue by jason-riley** [bitnami/vms#1705]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

898e8691-3b4a-0e39-4310-8d813399a371

### bndiagnostic was not useful. Could you please tell us why?

Nothing wrong with the build. Issue relates to a deprecated repo.

### Describe your issue as much as you can

When performing sudo apt-get update && sudo apt-get upgrade, the upgrade fails with:

W: Failed to fetch https://repo.saltproject.io/salt/py3/debian/12/amd64/latest/dists/bookworm/InRelease Could not resolve 'repo.saltproject.io'
W: Some index files failed to download. They have been ignored, or old ones used instead.

The repo at domain repo.saltproject.io has apparently been deprecated and has changed. Does anyone know hoe to work around this or will the issue be resolved by Bitnami?

**Comment by jotamartos** [comment]
As you mentioned, the repo was recently migrated. You can learn more about that migration here

https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/

**Comment by jason-riley** [comment]
It's unclear what action I need to take to resolve the failing upgrades. I am running Linux DEB. I have run the following commands, but when I try to perform an upgrade it is still pointing to the old repo.

`# Download public key
curl -fsSL https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public | sudo tee /etc/apt/keyrings/salt-archive-keyring-2023.pgp
# Create apt repo target configuration
echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.pgp arch=amd64] https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" | sudo tee /etc/apt/sources.list.d/salt.list
# Update package listings
sudo apt-get update

echo 'Package: salt-*
Pin: version 3007.*
Pin-Priority: 1001' | sudo tee /etc/apt/preferences.d/salt-pin-1001

sudo apt-get install salt-master`

**Comment by jotamartos** [comment]
The "Download public key" step should fix that problem. Can you confirm you downloaded the key to your instance?

**Comment by jason-riley** [comment]
The key is already there. I've now identified the issues in relation to the scripts provided by Salt. On any servers I'm running that are Bitnami build 6.2.0-14 or 6.3.1-0:

1. the repository configuration is stored in /etc/apt/sources.list.d/salt.list.list not /etc/apt/sources.list.d/salt.list
2. the public key is /etc/apt/keyrings/salt-archive-keyring-2023.gpg not /etc/apt/keyrings/salt-archive-keyring-2023.pgp

Running the scripts provided by Salt Project led to duplicates of the salt configuration and the public keys. The following scripts clean up everything and apt-get update now works correctly.

```
sudo rm -f /etc/apt/sources.list.d/salt.list
sudo rm -f /etc/apt/keyrings/salt-archive-keyring-2023.pgp
sudo rm -f /etc/apt/keyrings/salt-archive-keyring-2023.gpg
sudo curl -fsSL https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public | sudo tee /etc/apt/keyrings/salt-archive-keyring-2023.pgp
echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.pgp arch=amd64] https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" | sudo tee /etc/apt/sources.list.d/salt.list.list
```
