### ISSUE TITLE
[WordPress] Been 4 months and guest is not accessible remotely through browser

### ISSUE THREAD

**Issue by 7069wrk** [bitnami/vms#1706]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

unable to get because inable to access publicly

### bndiagnostic output

The bundle will not upload because the guest is not connecting to my network, and i cant extract it from the guest because it has no public connectivity.  if it were - the file would be whatever is in 20241104-151124-1693.zip
![image](https://github.com/user-attachments/assets/6dc03885-14e1-4fc3-afbd-3ebe5b538357)

### bndiagnostic was not useful. Could you please tell us why?

Says not publicly accessible but ufirewall does not appear to be issue

### Describe your issue as much as you can

i have had the instance turned off as a cold backup and need it now. but i turned the guest on and it is completely inaccessible.    I have disabled the firewall, after seeing that it is configured in the way that is recommended.  I have also switched between NAT and BRIDGED, it is painful to think that my working server will not be accessible for something silly like bitnami has some built in rule that will not allow the server to be used if it has been down for some time period.  (tin foil hat stupidity)

![image](https://github.com/user-attachments/assets/db96dd26-7e74-4bfb-9b01-d8bafbd7b9b6)

site was fully operational 4 months ago when i downed this guest.  I have restored all the way back to original snapshot, which was after first boot and testing (4 snapshots)  - even it will not allow access.  

if i can remove all blocks to it being accessible I can get my backup off and then figure out what it wrong.  i just need to recover my production server and if this is not available - it means a scratch rebuild and that will be crippling.

thank you for assistance

**Comment by jotamartos** [comment]
>Says not publicly accessible but ufirewall does not appear to be issue

First of all, let's get more information from the VM. Can you run these commands and share the output with us?

```
sudo /opt/bitnami/ctlscript.sh status
curl -LI -k localhost
sudo ifconfig -a
```

**Comment by 7069wrk** [comment]
thank you for the intel.   I have done this and what ended up needing to happen is i set the guest to host only.  backcally the guest will not pull an ip from my dhcp/ nor will it accept a static config.   super weird.   

But at the end of the day i am able to rip the config and bring the site back online.  for sure this was the motivation to not use WP for primary site and only for the integrations we require to have in WP.  nothing to do with the Bitnami team.   this is just a WP issue in general. so moving to static site as much as possible. 

thank you all for the contributions.
