### ISSUE TITLE
[Mattermost] How to get the steps for additional parameter that required to Bitnami application host is behind a load balancer or CDN

### ISSUE THREAD

**Issue by anuragnp97** [bitnami/vms#1708]
### Describe your issue as much as you can

![image](https://github.com/user-attachments/assets/414e4618-fdf3-4a1d-a399-41a96885e22a)

The Bitnami application host is behind a load balancer require some additional parameters so may i know that in detail
i have hosted the Bitnami package for Mattermost Team on aws ec2 which is on private subnet and accessing through application load balancer so may i know the addition steps required for the encryption of the cert

**Comment by jotamartos** [comment]
That depends on your configuration as I mentioned in the other thread. Please take a look at the lego documentation

https://github.com/bitnami/vms/issues/1467#issuecomment-2029542327
