### ISSUE TITLE
[Mattermost] Bitnami Stack Upgrade Issue 

### ISSUE THREAD

**Issue by BorampetBhavani** [bitnami/vms#1709]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Not using 

### bndiagnostic was not useful. Could you please tell us why?

No

### Describe your issue as much as you can

I attempted to upgrade Mattermost by following the instructions provided in the Bitnami documentation:
https://docs.bitnami.com/aws/apps/mattermost/administration/upgrade/

However, I encountered a few issues during the process. Additionally, the official Mattermost documentation states that only ESR (Extended Support Release) to ESR upgrades are supported. Could you please confirm if the method outlined in the Bitnami documentation allows for a direct upgrade to the latest version?

Furthermore, I noticed that Mattermost no longer supports MySQL and recommends migrating to PostgreSQL. To continue using the Bitnami stack, would it be necessary to migrate to PostgreSQL?

Currently, my Mattermost version is 9.4.

**Comment by jotamartos** [comment]
Hi @BorampetBhavani,

>However, I encountered a few issues during the process. Additionally, the official Mattermost documentation states that only ESR (Extended Support Release) to ESR upgrades are supported. Could you please confirm if the method outlined in the Bitnami documentation allows for a direct upgrade to the latest version?

We created that basic guide to explains the files to backup/restore but you should always follow the official instructions when performing the upgrade. Please note that we just pack and configure the application that the upstream project publish. 

>Furthermore, I noticed that Mattermost no longer supports MySQL and recommends migrating to PostgreSQL. To continue using the Bitnami stack, would it be necessary to migrate to PostgreSQL?

PostgreSQL is the preferred database but the application works with MySQL too 

https://docs.mattermost.com/install/prepare-mattermost-mysql-database.html

**Comment by jotamartos** [comment]
PostgreSQL is just a SQL database as it is MySQL. The latest version of Bitnami Mattermost uses MySQL and we didn't find any issue in our tests. As I mentioned above, the application supports MySQL. 

Please create a backup of your instance before performing the upgrade so you can recover the deployment easily if something goes wrong.

**Comment by Reston** [comment]
As per features deprecated end of support for MySQL is targeted for Mattermost v11.

https://docs.mattermost.com/about/deprecated-features.html#mattermost-server-v10-0-0

are there any plans on this?
