### ISSUE TITLE
Apache and MariaDB errors

### ISSUE THREAD

**Issue by robertthomasmarck** [bitnami/vms#1710]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2f07b9cf-e081-17dc-031a-3dc787a697fb

### bndiagnostic output

**===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1947 390 314 26 1241 1346 
Swap: 0 0 0
```
Press [Enter] to continue:
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2024-11-12 6:17:02 0 [ERROR] Aborting

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-mariadb/

[Apache]
Press [Enter] to continue:

Found recent error or warning messages in the Apache error log.
```
[Mon Nov 11 17:31:36.025980 2024] [core:error] [pid 24959:tid 140479219873536] 
[client **ip_address**:54938] AH10244: invalid URI path 
(/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32
%65/%%32%65%%32%65/%%32%65%%32%65/bin/sh)
 [Tue Nov 12 05:17:51.292711 2024] [core:error] [pid 24960:tid 140479093982976] 
[client **ip_address**:60414] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh)
 [Tue Nov 12 05:17:52.108067 2024] [core:error] [pid 24825:tid 140479177910016] 
[client **ip_address**:60430] AH10244: invalid URI path 
(/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32
%65/%%32%65%%32%65/%%32%65%%32%65/bin/sh)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
Press [Enter] to continue:
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.
 

===== End of bndiagnostic tool output =====**

### bndiagnostic was not useful. Could you please tell us why?

I could not find any info on clearing RAM, connectivity fix did not work, MariaDB fix relies on more memory, can't identify syntax error.

### Describe your issue as much as you can

The Lightsail instance went down a few weeks ago. The website shows a database error. I have not found any fixes that work.

**Comment by jotamartos** [comment]
>apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
>module log_config_module is built-in and can't be loaded

It seems there is an error in the httpd.conf file. You probably edited it by accident. Please undo the changes you made and try to restart Apache.

**Comment by robertthomasmarck** [comment]
I made no changes to line 112 in httpd.conf.

I tried commenting-out that line in the file just now. On reset I am still getting the same messages.

MariaDB is not resetting.

**Comment by jotamartos** [comment]
>On reset I am still getting the same messages.

Please debug the error and solve it. If you commented-out the line, it shouldn't return that error anymore.

>MariaDB is not resetting.

Check the logs under /opt/bitnami/mariadb/logs and debug the issue
