### ISSUE TITLE
AWS Lightsail Single Site - Cannot Migrate site

### ISSUE THREAD

**Issue by balancelogic** [bitnami/vms#1712]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b

### bndiagnostic was not useful. Could you please tell us why?

No access

### Describe your issue as much as you can

Trying to use Lightsail with a single site image. No matter what I do, I am unable to import or restore a wordpress image. I am trying to migrate my WP sites from another host, but it keeps getting stuck during import and restore. I have tried both methods. I have used file manager plugin to copy the site so I can restore and I also tried All in one migration to import.

**Comment by jotamartos** [comment]
We always suggest using the All in One WordPress migration plugin as described here

https://docs.bitnami.com/general/how-to/migrate-wordpress/

If you are reaching a PHP/Apache limit, you can try increasing those values. If it's an error related to the migration plugin, you will need to contact them of find alternative ways to migrate the data of WordPress. Please note that this question is related to the application and it's out of the scope of this support forum.
