### ISSUE TITLE
[WordPress] Timeout Error in Google Cloud

### ISSUE THREAD

**Issue by suryakantazm** [bitnami/vms#1713]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f2876197-f534-8947-3e1f-c0a1802ba534

### bndiagnostic output

Always getting error while Deploying Wordpress,
Timeout Error of runtimeconfig.v1beta1.config, runtimeconfig.v1beta1.waiter

### bndiagnostic was not useful. Could you please tell us why?

No Answer Found

### Describe your issue as much as you can

I tried Creating New Project, has positive balance of 2000, but getting error of {"ResourceType":"runtimeconfig.v1beta1.waiter","ResourceErrorCode":"504","ResourceErrorMessage":"Timeout expired."}
checked ssh it created user password correctly 
<img width="924" alt="Screenshot 2024-11-17 at 2 53 56 AM" src="https://github.com/user-attachments/assets/e1f29d46-743c-4ee4-8676-8387e58a1d6b">

**Comment by jotamartos** [comment]
Can you try increasing the resources of the VM you launched? I do not know how big the instance is but it might be running out of memory during the deployment process.
