### ISSUE TITLE
[Wordpress] gonit cannot start

### ISSUE THREAD

**Issue by ttkaka7200** [bitnami/vms#1716]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ad0e0b68-341e-7038-74d4-1e63bdd0edbc

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

apache server is well, but diagnostic tool is wrong.

### Describe your issue as much as you can

I can't `sudo gonit` because it has an error.

```
Socket file '/var/run/gonit.sock' is not writable
```

I was embarassed because server is well. But I can't execute ctlrscript.sh because gonit refuse execution.

**Comment by jotamartos** [comment]
> I can't sudo gonit because it has an error.
> 
> Socket file '/var/run/gonit.sock' is not writable
> 
> I was embarassed because server is well. But I can't execute ctlrscript.sh because gonit refuse execution.

It seems you modified the permissions configuration of the instance. You can either launch a new one and compare the permissions configuration or try to migrate your data to a new instance to resolve the issue

https://docs.bitnami.com/general/how-to/migrate-wordpress/
