### ISSUE TITLE
[WordPress] Can't activate the plugin - says  - proxy_fcgi:error 

### ISSUE THREAD

**Issue by zimmerx** [bitnami/vms#1717]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5a1ba00d-2c5b-ad74-c853-044811122555

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found:  
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
    
    [Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access

[Mariadb].

Found recent error messages in the MariaDB error log
2024-11-19 4:05:21 273 [Warning] Aborted connection 273 to db: 
'bitnami_wordpress' user: 'bn_wordpress' host: '**ip_address**' (Got an error   Return ty
reading communication packets)
```
Please check the following guide to troubleshoot MariaDB issues:: 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errockoutField.
rs-mariadb/

[Wordpress]
ckoutField.
Found recent WordPress plugin related error messages in the Apache error log.
```:  
[Tue Nov 19 04:05:21.415812 2024] [proxy_fcgi:error] [pid 52424:tid 
139673410172672] (104)Connection reset by peer: [client **ip_address**:14280] ckoutField.
AH01075: Error dispatching request to : , referer: 
https://xxx/wp-admin/plugins.phpd:  
Please check the following guide to deactivate plugins

[Apache]:  
Found recent error or warning messages in the Apache error log.ckoutField.
```
[Tue Nov 19 03:48:06.278741 2024] [proxy_fcgi:error] [pid 39553:tid   Return ty
140415139301120] (104)Connection reset by peer: [client **ip_address**:60324] [\\ReturnTy
AH01075: Error dispatching request to : koutField.p
 [Tue Nov 19 03:53:04.395739 2024] [autoindex:error] [pid 52462:tid 
139673166915328] [client **ip_address**:59795] AH01276: Cannot serve directory  Return typ
/opt/bitnami/wordpress/wp-admin/css/: No matching DirectoryIndex \\ReturnTyp
(index.html,index.html,index.htm,index.php) found, and server-generated outField.ph
directory index forbidden by Options directive, referer: binance.com
 [Tue Nov 19 04:01:53.611011 2024] [proxy_fcgi:error] [pid 52462:tid   Return ty
139671011038976] [client **ip_address**:60000] AH01071: Got error 'PHP message: [\\ReturnTy
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php koutField.p
on line 177PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 178'd:  Return 
 #[\\Return
```
 


### bndiagnostic was not useful. Could you please tell us why?

It says that there are connectivity problems, but there is not a problem at all. 

### Describe your issue as much as you can

I can't activate the plugin the website throws an error: 

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by jotamartos** [comment]
That error is related to the application itself and the plugins you are using 

```
[Tue Nov 19 04:05:21.415812 2024] [proxy_fcgi:error] [pid 52424:tid 
139673410172672] (104)Connection reset by peer: [client **ip_address**:14280] ckoutField.
AH01075: Error dispatching request to : , referer: 
https://xxx/wp-admin/plugins.phpd:  
Please check the following guide to deactivate plugins
```

Please disable all plugins and enable that one first to see if that solves the problem or contact the plugins developers to know more about the error
