### ISSUE TITLE
[Wordpress] frequently unresponsive

### ISSUE THREAD

**Issue by Australian** [bitnami/vms#1718]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ae873f10-c9fa-ef6a-7bfe-30bd9690085e

### bndiagnostic output

Startup: file created in the system's temporary directory in Unknown on line 0',
referer: https://rcat.co.uk/wp-admin/post.php?post=1004&action=edit
• [Mon Nou 18 21:43:03.344091 2024] [proy_ _fcgi:error] [pid 1017:tid 10891
Press [Enter] to continue:
Iclient **ip_address**:35286] AH01071: Got error 'PHP message: PHP Notice: PHP
Request Startup: file created in the system's temporary directory in Unknown on
line 0', referer: https://rcat.co.uk/wp-admin/post.php?post=1004&action=edit
Hon No 19 21:13:29 922452, 20241 Eproxy fogiercond pid Sob:tid 711) Calient **ip_address**：35292］ AH01071：Got error
Startup: file created in the system's temporary directory in Unknown on line 0',
referer: https://rcat.co.uk/wp-admin/post.php?post=1004&action=edit\\

![image](https://github.com/user-attachments/assets/e1277e67-f80c-45b2-88c3-16876b1efac4)

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are not related to my issue

### Describe your issue as much as you can

Site becomes unresponsive. 
Restarting services doesn't help.
Restarting VM does fix.

**Comment by jotamartos** [comment]
```
Hon No 19 21:13:29 922452, 20241 Eproxy fogiercond pid Sob:tid 711) Calient ip_address：35292］ AH01071：Got error
Startup: file created in the system's temporary directory in Unknown on line 0',
referer: [https://rcat.co.uk/wp-admin/post.php?post=1004&action=edit\\](https://rcat.co.uk/wp-admin/post.php?post=1004&action=edit%5C%5C)
```

This error is related to the application itself. I suggest you take a look at the WordPress' forums and review the list of plugins and themes you are using. Please note that PHP causes performance issues when logging too many messages in the log files.

I suggest you check other related posts in this forum like this one to try to debug the issue 

https://github.com/bitnami/vms/issues/1657#issuecomment-2349215919
