### ISSUE TITLE
[RabbiMQ] Error with image in Azure Marketplace

### ISSUE THREAD

**Issue by barcewin** [bitnami/vms#1719]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

NA

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

Hello, when taking a snapshot of a virtual machine with a rabbitmq image that was published in the Azure Marketplace, it no longer allows us to create the virtual machine because that image no longer exists and we internally require it. Is there a way to solve this?
<img width="570" alt="1" src="https://github.com/user-attachments/assets/a77f77e5-697e-4d1f-9476-8e872b75428e">

**Comment by jotamartos** [comment]
That solution was deprecated long ago and it's not available anymore in the Marketplace. You will need to migrate the data to [the CNAB-based solution](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.rabbitmq-cnab) or the [Bitnami RabbitMQ chart](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq). You can also contact the Azure's support team to know if there is any other alternative.
