### ISSUE TITLE
[<bitnami wordpress multisite>] Error when renewing a mix of live and expired domains with letsencrypt and bncert

### ISSUE THREAD

**Issue by palbratelund** [bitnami/vms#172]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ee0230b5-d073-4b7d-2b01-9e4f0d86e664

### bndiagnostic was not useful. Could you please tell us why?

I can not find anything pointing in the direction solving my issue in there. 

### Describe your issue as much as you can

I have a Bitnami Wordpress Multisite running on AWS Lightsail. I have added sites to the stack over time and therefore SSL certificates lapse at different times. For some reason, my main site domain (bratelund.no) has expired completely while I have been on vacation. When trying to renew I am asked to disable/revoke and issue new certificate. Because this main domain has expired I get a 403 and error because of this. If I select do not issue new certificate, I'm being sent back to alter the domains in the certificate. 

Because of all of this, I tried the Resetting the Certificates as advised in a different now resolved issue (as described here https://docs.bitnami.com/aws/how-to/understand-bncert/) but to no help. Yes, I did restart. 

Now, my site is completely broken and I'm a little lost. Flagging that I am not the advanced command line user. I admit I'm doing something wrong somewhere. But I'm struggling to find out where. 

All I want back is a live is the Wordpress Multisite with bratelund.no being the Main site domain and humlenshave.no back up running as a site on the stack. Please help! :)

**Comment by palbratelund** [comment]
I found how to resolve by manually clearing out old certificates using SFTP and then run bncert again.

**Comment by gongomgra** [comment]
Hi @palbratelund,

I'm glad you managed to solve your issue. Also thank you for sharing your solution with the community.
