### ISSUE TITLE
Bitnami wordpress default username and password not working

### ISSUE THREAD

**Issue by wogboy112** [bitnami/vms#1720]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

not working

### bndiagnostic was not useful. Could you please tell us why?

the suggested guides are not related to my issue

### Describe your issue as much as you can

I have installed the bitnami wordpress virtual machine in vmware, unfortunately when I go to wp-admin page and try to login the  user and password combination on the front page do not work

**Comment by jotamartos** [comment]
Hi,

Did you get any error regarding the initialization? If it worked properly, you shouldn't run into any issues when logging to the application. Please note that we test our solutions before publishing them and this login/logout tests is widely tested. 

Let us know if you keep running into this issue.
