### ISSUE TITLE
[NGINX] Can't access the instance using SSH client

### ISSUE THREAD

**Issue by thamel29446** [bitnami/vms#1721]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8f0e6e5e-ea84-a581-74bd-e9870d938e25

### bndiagnostic output

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
```
               total        used        free      shared  buff/cache   available
Press [Enter] to continue:
Mem:             447         321           7           4         135         126
Swap:            634          23         611
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
 

### bndiagnostic was not useful. Could you please tell us why?

It complains about the firewall and ports yet those are open and UFW command can not even be found

### Describe your issue as much as you can

I am using the latest predefined BITNAMI virtual machine on AWS, Bitnami package for NGINX Open Source 1.26.2-1.
I just can not SSH into the server using a stand-alone ssh client. It is always the same error with permission denied. I am able to use the Browser based AWS ssh client. And I am able to connect using Cyber Duck for file uploading. But I can not SSH in with any client.
Using the standard private key provided by aws.
Any help appreciated.

**Comment by thamel29446** [comment]
Hi.Turns out that the aws default keys are old rsa encryption type not accepted by newer linux distro.Maybe you want to make a note of that to others.TimOn 26. Nov 2024, at 9.35, Juan José Martos ***@***.***> wrote:﻿

I am able to use the Browser based AWS ssh client.

If you can access the instance using the AWS client, please ensure the SSH key is configured under /home/bitnami/.ssh/authorized_keys.

But I can not SSH in with any client.

If the SSH key is configured, please ensure the client uses the correct key to connect to the instance
https://docs.bitnami.com/aws/faq/get-started/connect-ssh/

**Comment by jotamartos** [comment]
>Hi.Turns out that the aws default keys are old rsa encryption type

You can notify AWS about that. Please note that the SSH keys generation is out of our control. Thanks
