### ISSUE TITLE
[ERPNext] wkhtmltopdf fails to export PDF with CSS or images due to file access issues

### ISSUE THREAD

**Issue by Nav-Navillera** [bitnami/vms#1727]
### **Description:**

I encountered an issue when generating PDFs using wkhtmltopdf on the Bitnami ERPNext stack. The problem is that wkhtmltopdf cannot access CSS or image files when generating PDFs, resulting in plain text output without styling or images.

### **Steps to Reproduce:**
1. Working with Bitnami ERPNext on a server with a wkhtmltopdf module finely installed.
2. Try generating a PDF from ERPNext (for example, a print format that uses CSS for styling).
3. The resulting PDF will have no styles or images, only plain text.

### **What I tried:**
I noticed that the problem is due to wkhtmltopdf not being able to access local files such as CSS or images when running in the Bitnami environment. The paths for assets like CSS are relative or based on the local file system, but wkhtmltopdf is unable to resolve them correctly.

To work around this issue, I try to bypass the problem by manually modifying the HTML before generating the PDF. I added absolute paths to the CSS files, such as:

`<link rel="stylesheet" href="file:///opt/bitnami/erpnext/frappe-bench/sites/assets/css/style.css">`

This approach worked, and the generated PDF included the correct styles. However, this is not an ideal solution, and I believe it points to an issue where wkhtmltopdf does not automatically handle the right file access, especially for CSS and images, when run in a Bitnami environment.

### **Sugested Solutions**
While I am not an expert in the field, my suggestion (and I apologize if it's not the right approach) would be that wkhtmltopdf should be able to access local CSS and image files in the ERPNext installation automatically, or at least via configuration changes. For example, setting up a virtual host or configuring file access permissions may allow wkhtmltopdf to load assets such as CSS and images correctly.

Thank you for your time and consideration. I hope this issue can be addressed, and I look forward to any updates or solutions to help resolve this problem.

**Comment by jotamartos** [comment]
>While I am not an expert in the field, my suggestion (and I apologize if it's not the right approach) would be that wkhtmltopdf should be able to access local CSS and image files in the ERPNext installation automatically, or at least via configuration changes.

Thank you for taking the time to investigate the issue but wkhtmltopdf is an external tool that seems not to be maintained anymore 

https://github.com/wkhtmltopdf/wkhtmltopdf

You will need to find alternatives to that tool or make the necessary changes for it to work they way you expect.

**Comment by Nav-Navillera** [comment]
## The Solution what I Found

Hello, after a month of debugging, I found the root cause of the issue and a solution for it. When generating a PDF in ERPNext using `wkhtmltopdf`, the HTML sent to the tool contained a malformed CSS URL, as shown in the image below:

![Problematic CSS URL](https://github.com/user-attachments/assets/ca59a650-7e2f-4379-a73b-6bee3b6a2f7a)

Notice the duplicated address in the CSS URL: `"http://"http://localhost"/"`. This causes issues with rendering CSS and images in the generated PDF.

---

## Cause and Debugging
I couldn't pinpoint the exact source of the malformed CSS URL within ERPNext or its dependencies, but I created a workaround by modifying the `get_pdf()` function in the `frappe.utils.pdf` module. 

---

## Solution
I added a custom function to filter and fix the malformed URLs in the HTML using regular expressions.

### Code Changes
1. **Import the `re` module** for regex filtering:
   ```python
   import re  # For regex filtering```

2. **Create a function** to handle the malformed URL:

  ```python
    def filter_url_all(text):
        # A function to filter and replace duplicated addresses in URLs
        return re.sub(r"http://'(http://[^']+)'", r"\1", text)
```

3. Modify the `get_pdf()` function in the `file /opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/utils/pdf.py`:

   ```python
   # The rest of the function remains unchanged
    def get_pdf(html, options=None, output: PdfWriter | None = None):
        html = scrub_urls(html)
        html = filter_url_all(html)  # <-- Custom code added here
        html, options = prepare_options(html, options)
    # The rest of the function remains unchanged```

## Result
1. The fix resolves the issue of missing CSS and images when generating PDFs.
2. It works for both locally hosted servers and servers accessed through VPN.
3. I haven't tested this solution on hosted domains, so I can't confirm if it behaves similarly in that scenario.

### Before
![Before](https://github.com/user-attachments/assets/72428dbd-9d6d-4de6-bdbb-4b7d8d661fd0)

### After
![After](https://github.com/user-attachments/assets/5b27a225-4f91-4b0d-a548-172a8db11ef4)

## Request for Feedback
If anyone knows the root cause of the malformed CSS URL/ or has encountered a similar issue, please share your insights. Additionally, let me know if this solution works for you or if there are edge cases where it fails.
