### ISSUE TITLE
[Bitnami package for WordPress with NGINX and SSL] [db_connect_error_mysqli]: MySQL server has gone away

### ISSUE THREAD

**Issue by Barnabas2** [bitnami/vms#1729]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2c3a1f86-3b59-4b5f-8dee-0872347a4e8f

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ✓ Mariadb: No issues found
    ? Wordpress: Found possible issues
    ✓ Processes: No issues found
    ? Nginx: Found possible issues
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Press [Enter] to continue:
Found recent WordPress plugin related error messages in the Nginx error log.
```
#4 /bitnami/wordpress/wp-content/plugins/independent-analy" while reading
response header from upstream, client: **ip_address**, server:
essexmonastery.com, request: "POST /wp-json/iawp/search HTTP/2.0", upstream:
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: " ",
referrer:
```

===== End of bndiagnostic tool output =====

These are my port settings: 
![image](https://github.com/user-attachments/assets/49fa5261-9cdd-43ca-bc0c-fe922be0f537)

### bndiagnostic was not useful. Could you please tell us why?

The server ports are open

### Describe your issue as much as you can

I'm using an external service [WP Umbrella](https://wp-umbrella.com/) for backups but when I try to restore a backup through their dashboard I get an error: "[db_connect_error_mysqli]: MySQL server has gone away"

Why is this happening? Can you please help?

**Comment by jotamartos** [comment]
>I'm using an external service [WP Umbrella](https://wp-umbrella.com/) for backups but when I try to restore a backup through their dashboard I get an error: "[db_connect_error_mysqli]: MySQL server has gone away"

Please contact the plugin's developers to know more about the issue and how to proceed. That's a paid product and this error is out of the scope of this support forum

**Comment by Barnabas2** [comment]
I've asked here, since themselves think that the problem is with the server, due to a timeout or too much data that cannot be received at once.

If you have any advise, I would appreciate it.

**Comment by jotamartos** [comment]
You will first need to check that you can access the database from outside the VM, did you try that? I understand the tool is trying to connect to the database from outside the VM (do not know anything about WP Umbrella) and the connection is failing. If you can run the MySQL/MariaDB login commands using the credentials in the wp-config.php file from outside the deployment, the tool should have access to the database too.

**Comment by Barnabas2** [comment]
I can login with the password that is defined in wp-config.php so I'm not sure what could be the cause of the error. 
Anyway, thanks for the reply and the suggestion.

**Comment by gongomgra** [comment]
If you are able to access the database server with the credentials present in the `wp-config.php` file, then the issue must be related to the WP Umbrella plugin and its interaction with the database. You will have to continue checking this issue with the plugin developers. Sorry for the inconveniences.

**Comment by Barnabas2** [comment]
Thank you @gongomgr. I'll get back to them plugin developers as advised.
