### ISSUE TITLE
[Wordpress] No Set-Up on Installation - No access to WP Dashboard only Blog Page

### ISSUE THREAD

**Issue by SaolAirde** [bitnami/vms#173]
### Platform

OSX VM

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

??

### bndiagnostic output

[I don't think this is relevant to my query and I couldn't access the suggested website.](https://docs.bitnami.com/general/how-to/understand-bnddiagnostics/)

### bndiagnostic was not useful. Could you please tell us why?

I don't think this is relevant to my query.

### Describe your issue as much as you can

Hello, and thank you for resolving my previous Sph connectivity issues VM on Mac.
I have been following tutorials online re setting up website via bitnami/wordpress. On all of them when installing wordpress they have a set-up feature for language passwords etc.... Then when they access via stack they can start creating a website. These are definitely older tutorials 1-3 years old. 

After downloading the most recent version from your site today as you suggested, I did not get a set up function when I was initialising word press (it never happened before either). Now when I access the site - go to application (defaults to safari browser) I only have the option of a blog - no other place I can go to from here. No specific logins etc...

I'm including a copy of a screenshot of wordpress dialogue box with my website/blog. 
This was a very good youtube tutorial I was hoping to follow.... https://www.youtube.com/watch?v=MFgZ5Vm-LU8 which is going through this process step by step - 

I'd appreciate your help
Kind regards

![Screenshot 2022-07-25 at 14 42 37](https://user-images.githubusercontent.com/109175301/180791856-eed4248e-96c0-49c0-9570-acbd94fb8882.png)

**Comment by jotamartos** [comment]
>After downloading the most recent version from your site today as you suggested, I did not get a set up function when I was initialising word press (it never happened before either). Now when I access the site - go to application (defaults to safari browser) I only have the option of a blog - no other place I can go to from here. No specific logins etc...

That's how the app works. If you want to access the admin panel, just access http://IP_ADDRESS/wp-login.php

If you want to know what credentials to use, please check this guide 

https://docs.bitnami.com/installer/apps/wordpress/get-started/first-steps/#os-x-vm-124
