### ISSUE TITLE
[Bitnami Wordpress Multisite] How to disable multisite?

### ISSUE THREAD

**Issue by flis0** [bitnami/vms#1730]
### Describe your issue as much as you can

I got a Bitnami Wordpress Multisite package installed on EC2. I'd like to disable Multisite so I'm left only with the main site as a single site installation. The process is not the same as with multisite that was enabled by hand because wp multisite by bitnami is missing `define( 'WP_ALLOW_MULTISITE', true );` in *wp-config.php*. 

When i commented the multisite specific lines in *wp-config.php* and *.htaccess* and restarted the site it was blank in browser on all paths. (also tried not touching *.htaccess* and removing it and result was the same).
I DON'T WANT TO MIGRATE !!! The site is huge and all migration tries were unsuccessful. Btw [this bitnami article](https://docs.bitnami.com/general/how-to/separate-wordpress-multisite/) is incomplete and doesn't account for the fact that you have to move plugins, themes and uploads by hand. 

I had a successful revert to single site from multisite that was enabled by hand on a different site so I know the process I'm doing is correct.

Please provide a way to change the installation to a singlesite.

EDIT: I'd also mention that the subsite I want to be left with has blog_id=4 and it's set up as a main site. Subsite with blog_id=1 is deleted.

**Comment by jotamartos** [comment]
Hi @flis0,

That's a specific question about the application. In the past, users moved from single-site to multisite but I do not know what the application will do with the data of your blog when "reducing" the number of sites from many to one. We suggest you review the app's documentation and ask the developers to know more about how to proceed.
