### ISSUE TITLE
[Redmine] Download OVA

### ISSUE THREAD

**Issue by Ezkarion** [bitnami/vms#1731]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8239gfsdgfs923-sdf23-sdf234

### bndiagnostic output

understand-bndiagnostic - false, i use windows =)

### bndiagnostic was not useful. Could you please tell us why?

Search in bd dont give me answer

### Describe your issue as much as you can

I'm trying to install [https://bitnami.com/stack/redmine/virtual-machine] but I constantly see from cloudfire [Sorry, you have been blocked]. Can u help me?

**Comment by jotamartos** [comment]
VMs are available to download in the VMware Marketplace

https://vcf.broadcom.com/vsc/services/details/redmine?slug=true
https://docs.bitnami.com/virtual-machine/get-started-vmware-workstation/
