### ISSUE TITLE
[solr] 414 large query size

### ISSUE THREAD

**Issue by abrarullah007** [bitnami/vms#1732]
### Describe your issue as much as you can

Hi,
I am using AWS bitnami solr v 9. The solr instance works fine for regular queries but I am getting 414 error for sending a large query to solr. I increased requrestHeadersize to 65536 on /opt/bitnami/solr/server/etc/jetty.xml but no luck - the same solution fixed the problem on my local dev instance.

**Comment by jotamartos** [comment]
The Bitnami SOLR VM includes Apache that proxies the requests to SOLR. You will need to increase the LimitRequestLine value inside the SOLR's virtual host under /opt/bitnami/apache/vhosts and restart the services after applying the changes

https://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline

**Comment by abrarullah007** [comment]
Thank you @jotamartos , it fixed the problem. However, the correct path was /opt/bitnami/apache/conf/vhosts
