### ISSUE TITLE
[VMware Player v.17.6.1 build-24319023] virtual machine for odoo 18, impossible to modify the keyboard layout

### ISSUE THREAD

**Issue by sergueikp** [bitnami/vms#1734]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

no

### bndiagnostic output

no

### bndiagnostic was not useful. Could you please tell us why?

Does not work

### Describe your issue as much as you can

Impossible to modify keyboard layout.
Ubuntu 22.04, virtual machine for Odoo - 18.0.20241105-0.
After those commands:
sudo apt-get install keyboard-configuration console-setup
sudo dpkg-reconfigure keyboard-configuration

In Configuring keyboard-configuration menu, on the last stage,
when press Enter to validate the "No compose key" option, the cursor is redirected back to the console command line. 
So thus it is impossible to modify the layout language.

**Comment by gongomgra** [comment]
Hi @sergueikp,

I have reproduced your scenario, but according to my tests, the changes to the keyboard layout are properly applied, you just need to restart the vm for changes to take effect. Hope it helps!
