### ISSUE TITLE
[LAMP] CRON job

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#1735]
### Describe your issue as much as you can

Hi,

I have setup a CRON job. However, I don't think it is working.

```
*/5 * * * * /usr/bin/php  /opt/bitnami/FDU/razorpay_webhook_monitor.php >> /opt/bitnami/FDU/cron.log 2>&1
*/5 * * * * /usr/bin/php  /opt/bitnami/FDU/razorpay_webhook_monitor.php >> /opt/bitnami/FDU/webhook_downtime_log.txt 2>&1
*/5 * * * * /opt/bitnami/FDU/razorpay_webhook_monitor.php >> /opt/bitnami/FDU/cron.log 2>&1
```

Is there anything wrong in the above lines?

Upon running: `cat /var/log/syslog | grep CRON` I get the below error:
`cat: /var/log/syslog: No such file or directory`

**Comment by jotamartos** [comment]
That's a generic question about cron, please check any online resource to know how to verify if cron is working. For example, you have useful information here

https://askubuntu.com/questions/85558/verify-if-crontab-works

>*/5 * * * * /usr/bin/php  /opt/bitnami/FDU/razorpay_webhook_monitor.php >> /opt/bitnami/FDU/cron.log 2>&1

By the way, if you are using Bitnami LAMP, you should be using the Bitnami's php bitnami at /opt/bitnami/php/bin/php
