### ISSUE TITLE
[Bitnami Gitea] How to upgrade from an old Gitea on Microsoft Azure

### ISSUE THREAD

**Issue by eternity1984** [bitnami/vms#1737]
### Describe your issue as much as you can

Would you help me? I tried upgrading from gitea 1.20.5 to latest. 

- Backed up the old Gitea, created a new Gitea and restored from the backup file -> did not start
- Downloaded the new Gitea binary and replaced old one  -> did not start

**Comment by gongomgra** [comment]
Hi @eternity1984,

Thanks for using Bitnami. According to other users in the official Gitea forums, launching a new machine with the updated Gitea version and migrating the data to the new server is the way to go. You can find more information on this in the next link

https://forum.gitea.com/t/move-gitea-to-another-server/1513

If you find issues following the recommended steps, please verify with the official developers if there is any restrictions regarding this process and the versions you are trying to move from and to.

**Comment by eternity1984** [comment]
Hi @gongomgra,
Thank you for your support! It worked!!!
I restored the DB from backup and carefully copied app.ini and repositories folder.
