### ISSUE TITLE
[Redmine] Path to Imagemagick's convert.exe incorrect in configuration.yml

### ISSUE THREAD

**Issue by jfix** [bitnami/vms#174]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

n/a

### bndiagnostic was not useful. Could you please tell us why?

I got a zip file which I can provide.

### Describe your issue as much as you can

I'm using the latest version as of writing 5.0.2 of the Redmine installer for Windows.

In the `configuration.yml` there is this section:

```
# Absolute path (e.g. /usr/bin/convert, c:/im/convert.exe) to
# the ImageMagick's `convert` binary. Used to generate attachment thumbnails.
imagemagick_convert_command: 'E:\Redmine/imagemagick/convert.exe'
```

However, the existing path is `E:\Redmine\imagemagick\bin\convert.exe` where `E:\Redmine` is the bitnami stack base path.

Making that change and restarting Redmine fixes the issue.

Before:
![image](https://user-images.githubusercontent.com/170240/180800172-4fba494e-ce80-44f2-ba0c-da89102a9040.png)

After:
![2022-07-25_16h22_45](https://user-images.githubusercontent.com/170240/180800093-0210730a-fcd8-489b-922a-d799b1ed6a86.png)

Now I still have to look into why the PDF support is unavailable.

**Comment by gongomgra** [comment]
Hi @jfix.

Thanks for reporting this error. Our team will evaluate the issue and will update the ImageMagick path. Regarding the other warning, please check the Redmine's official docs.

**Comment by gongomgra** [comment]
Hi @jfix,

Just a quick note to let you know that we released a new revision of our Redmine installer for Windows (5.0.2-1) including the fix for the `convert.exe` path. Please let us know if it worked for you.

**Comment by jfix** [comment]
Thank you @gongomgra I will test this the next time I need to install Redmine (probably not this week nor next), but as this is a minor issue, I think we can close this ticket. Thank you for fixing it!

**Comment by gongomgra** [comment]
@jfix thanks for your message. We will close the ticket!
