### ISSUE TITLE
[Redmine] Request for 5.0.x version of bitnami package for Redmine linux

### ISSUE THREAD

**Issue by Nori-525** [bitnami/vms#1740]
### Describe your issue as much as you can

Dear bitnami team,

I would like to request an 5.0.x version of bitnami package for Redmine linux:

bitnami-redmine-5.0.x-linux-x64-installer.run
Highly appreciated if you could provide a download link. Thank you in advance!

**Comment by gongomgra** [comment]
Hi @Nori-525,

As mentioned in other tickets in this forum, we are stopped providing native installers for our application catalog back in 2022 (see [our blogpost about this](https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html)). We recommend you to use our Docker images for Redmine available in DockerHub

https://hub.docker.com/r/bitnami/redmine/tags?name=5.0

You can find more information on how to use and configure the image in our GitHub repo for containers at https://github.com/bitnami/containers/tree/main/bitnami/redmine

Hope it helps!

**Comment by Nori-525** [comment]
Hi,gongomgra

Got it! Thank you for the detailed response and for guiding me to the Docker images. I appreciate your help!

Best regards, Nori-525
