### ISSUE TITLE
[WordPress] Can't access database after following the documentation

### ISSUE THREAD

**Issue by Honda-Manabu** [bitnami/vms#175]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Unknown

### bndiagnostic was not useful. Could you please tell us why?

The diagnostic bundle file was successfully created, but the automatic upload to Bitnami servers failed.And'/tmp/bitnami-wordpress-info-20220725-143808-13669.zip' can't be found on my terminal.

### Describe your issue as much as you can

After digesting the tutorial "https://lightsail.aws.amazon.com/ls/docs/ja_jp/articles/amazon-lightsail-connect-wordpress-to-mysql-managed-database", secure MySQL "https: // docs.bitnami.com/aws/apps/wordpress/administration/secure-server-mysql/ ”was executed in sequence, but the command fails (rejected) like the attached file.
Thank you for your help.
![LightSailWordpress220725-220725-1](https://user-images.githubusercontent.com/86801581/180814668-94647178-83e0-4e24-ae86-ed2ed8abc5dc.png)

**Comment by jotamartos** [comment]
Hi @Honda-Manabu ,

You probably removed the root@localhost entry as explained in the warning we included in the documentation. If you removed that user, you won't be able to access the database anymore. You have 2 options now:

**Comment by jotamartos** [comment]
Just for you to know, I edited the title of the issue to match with what you asked. Please take that into account in the future.
