### ISSUE TITLE
[edx] Issue with Ironwood API

### ISSUE THREAD

**Issue by mslyon** [bitnami/vms#176]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

None

### bndiagnostic was not useful. Could you please tell us why?

Api is used

### Describe your issue as much as you can

Hello

I’m using Ironwood edx and for some reason I’m not able to make the api working properly (bulk user enrollment) - see the discussion here  https://discuss.openedx.org/t/programatically-enroll-or-unenroll-students/4689/10

Was something broken in the Ironwood version?

thanks

**Comment by gongomgra** [comment]
Hi @mslyon ,

Thanks for using Bitnami. It seems it is not an issue related to the Bitnami Open edX image but about how the application or environment is being used/configured.

We highly recommend you to continue checking your issue in the official forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by mslyon** [comment]
Hi, I can't agree with you - you can do a simple test - for example example.com/api-docs
You will see that URL does not work while it should be - so I have the feeling something is not working as it should be.
So why this URL is not working? Any idea? thanks,

**Comment by mslyon** [comment]
In the meantime, I found what the issue was.

It seems that for some reason, in the httpd.conf the following is omitted and it is causing all not to work..

I have finally figured out what the problem was…

it is related to bitnami edx configuration of apache 2 - by adding this
WSGIPassAuthorization On

to the end of the httpd.conf, it solved the issue of authorization…

It would be great if you can add this as it will save some valuable time to people having this issue.

**Comment by gongomgra** [comment]
Hi @mslyon,

Thanks for investigating this issue and for sharing the solution with us. Our engineering team will check it and update our solution with that change. We will post a new message when the changes are applied.
