### ISSUE TITLE
[Testlink] Azure VM is not available

### ISSUE THREAD

**Issue by AnandSindhe** [bitnami/vms#177]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c44b4083-3bb0-49c1-b47d-974e53cbdf3c

### bndiagnostic output

Team,

We are in the migration phase from Pay-G subscription to CSP and the customer has a marketplace image of Publisher=bitnami, Offer=testlink, and  Plan=1-9. and we tried to recreate a VM in CSP (direct move not supported) by using OS disk snapshot and mentioning the Publisher,offer and Plan details (Bash commands), unfortunately received the error stating" this offer is no more available and choose an another offer".

Upon checking, the testlink image is discontinued and no more available neither in Azure marketplace nor in Bitnami official website.

Hence request to provide a workaround to migrate the VM.

### bndiagnostic was not useful. Could you please tell us why?

the testlink image is discontinued and no more available neither in Azure marketplace nor in Bitnami official website.

### Describe your issue as much as you can

Team,

We are in the migration phase from Pay-G subscription to CSP and the customer has a marketplace image of Publisher=bitnami, Offer=testlink, and  Plan=1-9. and we tried to recreate a VM in CSP (direct move not supported) by using OS disk snapshot and mentioning the Publisher,offer and Plan details (Bash commands), unfortunately received the error stating" this offer is no more available and choose an another offer".

Upon checking, the testlink image is discontinued and no more available neither in Azure marketplace nor in Bitnami official website.

Hence request to provide a workaround to migrate the VM.

**Comment by gongomgra** [comment]
Hi @AnandSindhe,

Thanks for using Bitnami. We no longer provide support for Testlink. Please ask the Azure team in case you can migrate the vm from one account to another, or ask in the official Testlink forums for help on how to migrate the data from the old instance to a new one.

**Comment by AnandSindhe** [comment]
++ looping @***@***.******@***.***> & @Arjun ***@***.***>

Hi Robert,

As guided on MS Ticket (TrackingID#2207220030001305), we raised the concern using the github and below is the reply from the Team.(mail trail)
Request you to check internally for any other available options/ work around.

Thanks and Regards ,
Anand Rao Sindhe R | Senior Cloud Engineer.
Xencia Technology Solutions Pvt. Ltd.
Mail: ***@***.******@***.***%7C> Web: www.xencia.com<https://apc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.xencia.com%2F&data=04%7C01%7Canand.rao%40xencia.com%7Ccd0f62ea02ed4a26536708d9697f6aee%7C75f2a99b01fd48f2ac60d4a7a44fd0cc%7C1%7C0%7C637656818240501752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tPNiTZPj%2F%2FmEAfrVgzfJ6J0n1frIFltR3OWzxUDay1k%3D&reserved=0> |
***@***.******@***.***

Note: Please post all your request to ***@***.******@***.***> for quicker response and resolution

**Comment by gongomgra** [comment]
Hi @AnandSindhe, it looks like you forwarded the email to another thread, and it got posted here. I removed that message from here for security reasons.

**Comment by AnandSindhe** [comment]
Hi Anand,


I hope all is well.  Thank you for your time on this service request.  Please let us know if you have any more question for us before we can proceed the case closure as we have answered all the inquiries.

Please find below a summary of your case for your reference:

Issue Definition: : Unable to deploy own Testlink image from Publisher Bitnami.  Receiving the following error:

***@***.***

Findings: The error message indicates that the offer "Testlink" has been removed from the Azure Marketplace by the vendor.  Vendor was contacted, but they said the image is no longer supported.  Possible workaround is to leave the VM in the current location or ask the Vendor for recommendation what image to use and then you can copy the data to the new VM.

Thank you again for choosing Microsoft!

Best regards,

Robert Botembo
Support Engineer
Azure - Azure IaaS VM
+1 (469) 775-3571
Working Hours: M-F 7:00am - 3:00pm CST (-5 UTC)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Malanda Rust / ***@***.******@***.***>



From: Robert Botembo
Sent: Friday, July 29, 2022 8:00 AM
To: Anand Rao Sindhe R ***@***.***>; 'Microsoft Support' ***@***.***>; Arjun YS ***@***.***>
Cc: Mention ***@***.***>; bitnami/vms ***@***.***>; Xencia Operations team ***@***.***>; bitnami/vms ***@***.***>
Subject: RE: [bitnami/vms] Unavailability of Testlink Vm Image in Azure (Issue #177)

Hi Anand,

I hope all is well.  I am following up on my service request, please let me know if we can proceed with the case closure as we have answered all your inquiries.

Thank you,

Robert Botembo
Support Engineer
Azure - Azure IaaS VM
+1 (469) 775-3571
Working Hours: M-F 7:00am - 3:00pm CST (-5 UTC)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Malanda Rust / ***@***.******@***.***>



From: Robert Botembo
Sent: Wednesday, July 27, 2022 11:18 PM
To: Anand Rao Sindhe R ***@***.******@***.***>>; Microsoft Support ***@***.******@***.***>>; Arjun YS ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>; bitnami/vms ***@***.******@***.***>>; Xencia Operations team ***@***.******@***.***>>; bitnami/vms ***@***.******@***.***>>
Subject: RE: [bitnami/vms] Unavailability of Testlink Vm Image in Azure (Issue #177)

Hi Anand,

Thank you for your email.  As you can see in the error message below the resource move is not supported because of the image plan.  There is no work around since the vendor does not longer support the image.

***@***.***

The only option would be to leave the VM in the current location or ask the Vendor for recommendation what image to use and then you can copy the data to the new VM.

Thank you,

Robert Botembo
Support Engineer
Azure - Azure IaaS VM
+1 (469) 775-3571
Working Hours: M-F 7:00am - 3:00pm CST (-5 UTC)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Malanda Rust / ***@***.******@***.***>



From: Anand Rao Sindhe R ***@***.******@***.***>>
Sent: Wednesday, July 27, 2022 11:50 AM
To: Robert Botembo ***@***.******@***.***>>; Microsoft Support ***@***.******@***.***>>; Arjun YS ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>; bitnami/vms ***@***.******@***.***>>; Xencia Operations team ***@***.******@***.***>>; bitnami/vms ***@***.******@***.***>>
Subject: [EXTERNAL] RE: [bitnami/vms] Unavailability of Testlink Vm Image in Azure (Issue #177)

++ looping @***@***.******@***.***> & @Arjun ***@***.***>

Hi Robert,

As guided on MS Ticket (TrackingID#2207220030001305), we raised the concern using the github and below is the reply from the Team.(mail trail)
Request you to check internally for any other available options/ work around.

Thanks and Regards ,
Anand Rao Sindhe R | Senior Cloud Engineer.
Xencia Technology Solutions Pvt. Ltd.
Mail: ***@***.******@***.***%7C> Web: www.xencia.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.xencia.com%2F&data=05%7C01%7CRobert.Botembo%40microsoft.com%7Cc9f8b5fcd6734b8c96ea08da6ff01d19%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637945374329682352%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WD2aNlz9Kk0JmPegC1ltR%2BoQURerIXOrhxdK52j1kR8%3D&reserved=0> |
***@***.******@***.***

Note: Please post all your request to ***@***.******@***.***> for quicker response and resolution

**Comment by gongomgra** [comment]
Hi @AnandSindhe,

Please be careful with sharing your internal information in this public thread. Notice every email forwarding or reply gets now posted here.

As mentioned previously, we no longer provide Testlink images for Azure or any other marketplace, so the solution can't be launched from the new account. As an alternative, you can launch a fresh new LAMP image and then manually install Testlink on top of it. Once you have it running on top of LAMP, you may be able to migrate the application data from the old instance.

https://docs.bitnami.com/azure/infrastructure/lamp/administration/create-custom-application-php/

**Comment by AnandSindhe** [comment]
Hi Anand,

I hope all is well.  I am following up on my service request, please let me know if we can proceed with the case closure as we have answered all your inquiries.

Thank you,

Robert Botembo
Support Engineer
Azure - Azure IaaS VM
+1 (469) 775-3571
Working Hours: M-F 7:00am - 3:00pm CST (-5 UTC)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Malanda Rust / ***@***.******@***.***>



From: Robert Botembo
Sent: Wednesday, July 27, 2022 11:18 PM
To: Anand Rao Sindhe R ***@***.***>; Microsoft Support ***@***.***>; Arjun YS ***@***.***>
Cc: Mention ***@***.***>; bitnami/vms ***@***.***>; Xencia Operations team ***@***.***>; bitnami/vms ***@***.***>
Subject: RE: [bitnami/vms] Unavailability of Testlink Vm Image in Azure (Issue #177)

Hi Anand,

Thank you for your email.  As you can see in the error message below the resource move is not supported because of the image plan.  There is no work around since the vendor does not longer support the image.

***@***.***

The only option would be to leave the VM in the current location or ask the Vendor for recommendation what image to use and then you can copy the data to the new VM.

Thank you,

Robert Botembo
Support Engineer
Azure - Azure IaaS VM
+1 (469) 775-3571
Working Hours: M-F 7:00am - 3:00pm CST (-5 UTC)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Malanda Rust / ***@***.******@***.***>



From: Anand Rao Sindhe R ***@***.******@***.***>>
Sent: Wednesday, July 27, 2022 11:50 AM
To: Robert Botembo ***@***.******@***.***>>; Microsoft Support ***@***.******@***.***>>; Arjun YS ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>; bitnami/vms ***@***.******@***.***>>; Xencia Operations team ***@***.******@***.***>>; bitnami/vms ***@***.******@***.***>>
Subject: [EXTERNAL] RE: [bitnami/vms] Unavailability of Testlink Vm Image in Azure (Issue #177)

++ looping @***@***.******@***.***> & @Arjun ***@***.***>

Hi Robert,

As guided on MS Ticket (TrackingID#2207220030001305), we raised the concern using the github and below is the reply from the Team.(mail trail)
Request you to check internally for any other available options/ work around.

Thanks and Regards ,
Anand Rao Sindhe R | Senior Cloud Engineer.
Xencia Technology Solutions Pvt. Ltd.
Mail: ***@***.******@***.***%7C> Web: www.xencia.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.xencia.com%2F&data=05%7C01%7CRobert.Botembo%40microsoft.com%7Cc9f8b5fcd6734b8c96ea08da6ff01d19%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637945374329682352%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WD2aNlz9Kk0JmPegC1ltR%2BoQURerIXOrhxdK52j1kR8%3D&reserved=0> |
***@***.******@***.***

Note: Please post all your request to ***@***.******@***.***> for quicker response and resolution

**Comment by AnandSindhe** [comment]
Hi Anand,

Thank you for your email.  As you can see in the error message below the resource move is not supported because of the image plan.  There is no work around since the vendor does not longer support the image.

***@***.***

The only option would be to leave the VM in the current location or ask the Vendor for recommendation what image to use and then you can copy the data to the new VM.

Thank you,

Robert Botembo
Support Engineer
Azure - Azure IaaS VM
+1 (469) 775-3571
Working Hours: M-F 7:00am - 3:00pm CST (-5 UTC)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Malanda Rust / ***@***.******@***.***>



From: Anand Rao Sindhe R ***@***.***>
Sent: Wednesday, July 27, 2022 11:50 AM
To: Robert Botembo ***@***.***>; Microsoft Support ***@***.***>; Arjun YS ***@***.***>
Cc: Mention ***@***.***>; bitnami/vms ***@***.***>; Xencia Operations team ***@***.***>; bitnami/vms ***@***.***>
Subject: [EXTERNAL] RE: [bitnami/vms] Unavailability of Testlink Vm Image in Azure (Issue #177)

++ looping @***@***.******@***.***> & @Arjun ***@***.***>

Hi Robert,

As guided on MS Ticket (TrackingID#2207220030001305), we raised the concern using the github and below is the reply from the Team.(mail trail)
Request you to check internally for any other available options/ work around.

Thanks and Regards ,
Anand Rao Sindhe R | Senior Cloud Engineer.
Xencia Technology Solutions Pvt. Ltd.
Mail: ***@***.******@***.***%7C> Web: www.xencia.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.xencia.com%2F&data=05%7C01%7CRobert.Botembo%40microsoft.com%7Cc9f8b5fcd6734b8c96ea08da6ff01d19%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637945374329682352%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WD2aNlz9Kk0JmPegC1ltR%2BoQURerIXOrhxdK52j1kR8%3D&reserved=0> |
***@***.******@***.***

Note: Please post all your request to ***@***.******@***.***> for quicker response and resolution

**Comment by gongomgra** [comment]
Hi @AnandSindhe,

Thanks for sharing the info with us. Unfortunately, as mentioned by the Azure team, we no longer offer those images, so you will have to export the application data from your current image, and then import it on your new application running on your custom server. Sorry for the inconvenience.

I'm closing this thread as solved.
