### ISSUE TITLE
[Akeneo] support services not starting, looks like gonitrc does not exist

### ISSUE THREAD

**Issue by scinquegrani** [bitnami/vms#178]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8c756ccd-d3d9-a317-e27f-ad632abf75be

### bndiagnostic was not useful. Could you please tell us why?

Did not identify the issue, or recommended guides did not apply

### Describe your issue as much as you can

Cannot start support services for Akeneo (Mac Installer).  When asking for status 'sudo /etc/gonit' I get a return message gonitrc does not exist.

root@debian:/etc# sudo gonit status
Control file '/etc/gonit/gonitrc' does not exists
root@debian:/etc#

**Comment by gongomgra** [comment]
Hi @scinquegrani,

Thanks for using Bitnami. According to the error, it seems gonit is not running on your server, can you try to start it by running the command `sudo gonit`?  Regarding the bndiagnostic tool, it looks like you didn't run it with sudo privileges. Please, ensure you run it using sudo in the future so it can retrieve all the needed information.

**Comment by scinquegrani** [comment]
gonit is missing.  This is what I get when I run sudo gonit

root@debian:~# sudo gonit
Control file '/etc/gonit/gonitrc' does not exists
root@debian:~#

**Comment by gongomgra** [comment]
Hi @scinquegrani,

Can you try running `sudo gonit status`? It should print more information about where it is installed, and where is the log. Please check the error message in the log file preventing gonit from start and try to fix it.

If it is not possible, we recommend you to launch a new Akeneo instance, and once all services are running, migrate your application data.

**Comment by gongomgra** [comment]
@scinquegrani, I also edited your previous message to wrap your console information between three backsticks character to properly highlight it: (```). Please take it into account for future messages, it makes a lot easier for us to get the required information.

**Comment by scinquegrani** [comment]
Maybe I'm not explaining myself.  gonit does not exist.  When I run "sudo gonit status" this is what I get, see below.  When I look into the directory /etc there is not another directory 'gonit'.  I think the installer package for the Mac is missing gonit.

Linux debian 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
       ___ _ _                   _
      | _ |_) |_ _ _  __ _ _ __ (_)
      | _ \ |  _| ' \/ _` | '  \| |
      |___/_|\__|_|_|\__,_|_|_|_|_|
  
  *** Welcome to the Akeneo packaged by Bitnami 6.0.36-0              ***
  *** Documentation:  https://docs.bitnami.com/installer/apps/akeneo/ ***
  ***                 https://docs.bitnami.com/installer/             ***
  *** Bitnami Forums: https://github.com/bitnami/vms/                 ***
Last login: Tue Jul 26 17:54:30 2022 from 192.168.65.1
root@debian:~# sudo gonit status
Control file '/etc/gonit/gonitrc' does not exists
root@debian:~#

**Comment by nuelgoz** [comment]
I have the same error does not start Akeneo OK, create the virtual machine but do not start the services, after launching the script of starting the services sudo /opt/bitnami/ctlscript.sh restart, ,Something does not work in Gonit

**Comment by nuelgoz** [comment]
![imagen](https://user-images.githubusercontent.com/9434922/181386247-845f7c53-e3bd-45d7-9793-565d6fe3350b.png)

**Comment by nuelgoz** [comment]
With the bitnami-akeneo-6.0.37-0-linux-vm-debian-11-x86_64-nami.ova version, it also gives me the same error, the services do not start at the begin the VM

**Comment by gongomgra** [comment]
Hi @scinquegrani, and @nuelgoz,

I launched the latest version of the Akeneo OS X machine and, although it is true at the very begin of the initialization gonit is not available, it takes some time to start automatically, but it does.

<img width="1307" alt="Screen Shot 2022-07-28 at 11 39 20" src="https://user-images.githubusercontent.com/6660452/181476393-570338cf-b3d2-4640-b165-afc5a7f882c3.png">

@scinquegrani as you are using a previous version of Akeneo, can you try using the most recent one?

**Comment by scinquegrani** [comment]
I am now using version 6.0.37 and same result.  No change.

**Comment by gongomgra** [comment]
@scinquegrani, did you wait some time for gonit to properly start? Can you check the content of the `~/.bitnami/stackman/machines/akeneo/log/boot.log` file for any initialization error?

**Comment by philipkaare** [comment]
I have the same problem on the AWS Magento package.

**Comment by gongomgra** [comment]
Hi @philipkaare,

Thanks for using Bitnami. As you are having issues with a different application and platform, please open a new ticket. Additionally, can you check the next logs for more information on why gonit process was not properly initialized and share the information in the new thread?

* `/opt/bitnami/var/log/first-boot.log`
* `/var/log/messages`
* `/var/log/daemon.log`
