### ISSUE TITLE
[LAMP] Failed to start LSB: bitnami init script.

### ISSUE THREAD

**Issue by extralsc** [bitnami/vms#179]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

aea6ac0e-70cd-b87a-8cec-0b659cee7de0

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Jul 25 13:31:58.766674 2022] [autoindex:error] [pid 1282:tid
139681624643328] [client **ip_address**:57164] AH01276: Cannot serve directory
/opt/bitnami/apache2/htdocs/frontend/files/s3/882236373/thumb/: No matching
DirectoryIndex (index.html,index.html,index.htm,index.php) found, and
server-generated directory index forbidden by Options directive, referer:
http://3.72.25.22:3000/
Press [Enter] to continue:
 [Mon Jul 25 13:32:12.448646 2022] [autoindex:error] [pid 1282:tid
139681270204160] [client **ip_address**:17038] AH01276: Cannot serve directory
/opt/bitnami/apache2/htdocs/frontend/files/s3/882436373/thumb/: No matching
DirectoryIndex (index.html,index.html,index.htm,index.php) found, and
server-generated directory index forbidden by Options directive, referer:
http://3.72.25.22:3000/
 [Mon Jul 25 13:52:16.680488 2022] [autoindex:error] [pid 878:tid
139681624643328] [client **ip_address**:53762] AH01276: Cannot serve directory
/opt/bitnami/apache2/htdocs/frontend/files/s3/882436373/thumb/: No matching
DirectoryIndex (index.html,index.html,index.htm,index.php) found, and
server-generated directory index forbidden by Options directive, referer:
http://3.72.25.22:3000/

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
Press [Enter] to continue:
2022-07-25 14:29:53 11 [Warning] Aborted connection 11 to db: 'klubblista' user:
'admin' host: '**ip_address**' (Got an error reading communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem Size Used Avail Use% Mounted on /dev/xvda1 59G 47G 9.6G 84% /
```
Please check your cloud provider's documentation for more information.
Press [Enter] to continue:

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1995 708 101 7 1184 1095 Swap:
4095 0 4095
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Suggestions is not related to my issue

### Describe your issue as much as you can

I can't restart any services, I wanted to restart apache then it failed. Tried to restart all services and got this error:
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

The unit bitnami.service has entered the 'failed' state with result 'exit-code'.
Jul 25 22:25:21 ip-172-26-6-62 systemd[1]: Failed to start LSB: bitnami init script.

**Comment by jotamartos** [comment]
Hi @extralsc,

It seems the gonit service is not started in your machine. It was probably killed due to low resources or similar. Let's see if you can start it and restart the Apache service 

```
sudo gonit
#wait for some seconds now
sleep 30
sudo /opt/bitnami/ctlscript.sh restart apache
```

If the service is not running after that time, you can restart the Apache's service by using these scripts 

```
sudo /opt/bitnami/scripts/apache/stop.sh
sudo /opt/bitnami/scripts/apache/start.sh
```
