### ISSUE TITLE
[WordPress with NGINX and SSL] Can't find bitnami.conf file

### ISSUE THREAD

**Issue by exentrify** [bitnami/vms#180]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7229efdc-08ba-d913-4e5e-f0b28eefe90b

### bndiagnostic output

Nginx: Found possible issues
Mariadb: No Issues found
Connectivity: Found possible issues
Wordpress: Found possible issues
Processes: No issues found
Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

It cannot assist me in this issue. 

### Describe your issue as much as you can

I am trying to implement the feature: "Access An Application Using Only A Single Domain With NGINX" through the article on docs.bitnami.com. But in the provided guide it directs me to access the bitnami.conf file. Unfortunately in the specified path, I cannot find the bitnami.conf file and I tried doing a search and still can't find it. What am I missing here? Thank you in advance.

**Comment by jotamartos** [comment]
In this case, you need to edit the WordPress' files inside the /opt/bitnami/nginx/conf/server_blocks folder. Please note that there are 2 files there, one for http and the other one for https. 

Thanks

**Comment by exentrify** [comment]
So the correct process for this would be to modify both the `wordpress-server-block.conf` file and the `wordpress-https-server-block.conf` files? and leave the `default-https-server-block.conf` file alone?

**Comment by exentrify** [comment]
Ok, I have modified the files mentioned in the previous comment through the directory you suggested and it seems to be working properly now. I appreciate the support very much.
