### ISSUE TITLE
[WordPress Multisite] Unable to Map Domain on GCP Instance

### ISSUE THREAD

**Issue by DipendraKSahay** [bitnami/vms#181]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4e17f682-bbdc-be76-94be-cee6519a7a24

### bndiagnostic output

Found recent error or warning messages in the Apache error log.
```
[Tue Jul 26 03:34:19.865133 2022] [proxy_fcgi:error] [pid 37236:tid 
139811167786752] [client **ip_address**:61443] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in 
/opt/bitnami/wordpress/wp-includes/ms-settings.php on line 57PHP message: PHP 
Warning: Undefined array key "host" in 
Press [Enter] to continue:
/opt/bitnami/wordpress/wp-includes/canonical.php on line 687PHP message: PHP 
Warning: Undefined array key "host" in 
/opt/bitnami/wordpress/wp-includes/canonical.php on line 696PHP mess [Tue Jul 26 
06:15:53.352439 2022] [proxy_fcgi:error] [pid 37236:tid 139810446472960] [client 
**ip_address**:18514] AH01071: Got error 'PHP message: PHP Warning: Undefined 
array key "HTTP_HOST" in /opt/bitnami/wordpress/wp-includes/ms-settings.php on 
line 57PHP message: PHP Warning: Undefined array key "host" in 
/opt/bitnami/wordpress/wp-includes/canonical.php on line 687PHP message: PHP 
Warning: Undefined array key "host" in 
/opt/bitnami/wordpress/wp-includes/canonical.php on line 696PHP mess [Tue Jul 26 
08:01:54.121469 2022] [proxy_fcgi:error] [pid 726:tid 139810622457600] [client 
**ip_address**:5887] AH01071: Got error 'PHP message: PHP Notice: Unknown: file 
created in the system's temporary directory in Unknown on line 0', referer: 
http://34.131.116.34.nip.io/wp-admin/post.php?post=3070&action=elementor
```

### bndiagnostic was not useful. Could you please tell us why?

The code has been attached for review.

### Describe your issue as much as you can

Dear Experts!

My Bitmani project was lost therefore I re-uploaded my project in a new instance, and configured Cloud DNS. On my deployment project dashboard, I have a warning message as :

_deploy has been deployed, but contains warnings_ 

On clicking VIEW DETAILS, it displays details on the same dashboard as
_This deployment has resources from the Runtime Configurator service, which is in Beta. There is no planned date for moving this feature into General Availability (GA). Examples of runtimeconfig types used: runtimeconfig.v1beta1.config, runtimeconfig.v1beta1.waiter_ 

I am not sure about this message warning. Is it related to GCP or Bitnami?

Ignoring the above error message and continuing with my website setup, my importance is to map my domain with my instance project on GCP (ie link to domain address). My previous tutorials were not helpful in finding the path of wp-config.php and modify using SSH. 

Can anyone help me with the new updates of Bitnami so that my website is accessible from the domain address? 

Thank you!

**Comment by jotamartos** [comment]
Hi @DipendraKSahay,

> This deployment has resources from the Runtime Configurator service, which is in Beta. There is no planned date for moving this feature into General Availability (GA). Examples of runtimeconfig types used: runtimeconfig.v1beta1.config, runtimeconfig.v1beta1.waiter
> 
> I am not sure about this message warning. Is it related to GCP or Bitnami?

We are aware of this warning. The team is working on it but it shouldn't affect you. You can continue using your deployment without issues. 

> Ignoring the above error message and continuing with my website setup, my importance is to map my domain with my instance project on GCP (ie link to domain address). My previous tutorials were not helpful in finding the path of wp-config.php and modify using SSH.
> 
> Can anyone help me with the new updates of Bitnami so that my website is accessible from the domain address?

We have this generic guide about how to configure WordPress Multisite, please check it 

https://docs.bitnami.com/google/apps/wordpress-multisite/configuration/configure-wordpress-multisite/

If you have more questions regarding the application, please contact WordPress

https://wordpress.org/support/

**Comment by DipendraKSahay** [comment]
Hi @jotamartos 

My issue with the mapping domain has been solved. That's what I really like about Bitnami, the product and support both are remarkably awesome. 

Thank you!

Regards
Dipendra

**Comment by jotamartos** [comment]
Thank you for your kind words @DipendraKSahay! I'm really glad the issue is solved now :)

**Comment by jotamartos** [comment]
This guide explains how to configure the domain in WordPress 

https://docs.bitnami.com/google/apps/wordpress-multisite/configuration/configure-wordpress-multisite/

If you run into issues when configuring the domain in the app, please contact the app's developers 

https://wordpress.org/support/

**Comment by aadajinkya8** [comment]
Thank you. Restarting all the services helped solve it
