### ISSUE TITLE
[Redmine] Two factor authentication does not work after the upgrade 5.0 -> 5.0.2-1

### ISSUE THREAD

**Issue by Nekolone** [bitnami/vms#185]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e558f8af-4b147c62-4e98-0ffc07676121

### bndiagnostic output

Apache - ok
Resources - Found possible issues (your instance has liitle available RAM memory. Total used free shared buff/cache available Mem: 1478 531 74 3 871 793 Swap: 634 0 634)
Processes - ok 
Mariadb - ok
Connectivity - Found possible issues (server ports 22, 80 and or 443 are not publicly accessible..)

### bndiagnostic was not useful. Could you please tell us why?

ports and ram is not a problem. Twofa is not related to them 

### Describe your issue as much as you can

After upgrading from version 5.0 to 5.0.2-1 twofa stopped working, gives the message "Code is invalid or outdated". 

I noticed that the systems timezone is wrong, but I can't adjust it with timedatectl. I changed timezone by changing /etc/localtime, but it did not help.

I tested blank versions of redmine without any customizations

- On redmine 5.0, twofa works without any problems
  - ![image](https://user-images.githubusercontent.com/60545501/181216626-ff076d87-fec5-42cc-9bbd-6624a9f08cdb.png)
  - ![image](https://user-images.githubusercontent.com/60545501/181218638-945fc572-9232-412f-aec6-d4c18a38dc53.png)

- On redmine 5.0.2, twofa throws the error Code is invalid or outdated
  - ![image](https://user-images.githubusercontent.com/60545501/181216970-278ebc9a-74da-45f4-a403-cdca28508701.png)
  - ![image](https://user-images.githubusercontent.com/60545501/181219242-2a970b9e-d341-4b1e-b6d8-571e9645772d.png)

Is the reason why twofa does not work is because the time is wrong? If so, how can it be fixed?

**Comment by Nekolone** [comment]
Test with [5.0.2-2](https://marketplace.cloud.vmware.com/services/details/redmine?slug=true), same problem. Twofa not working and data is wrong

**Comment by gongomgra** [comment]
Hi @Nekolone,

Thanks for using Bitnami. I was not able to access the information generated by the bndiagnostic tool. Can you execute it again and share with us the new code?

Regarding the timedatectl command, can you try to run it using sudo to gain higher privileges?

**Comment by Nekolone** [comment]
Hi, the problem was solved by synchronizing the time in the system

Since timedatectl didn't work, we had to install dbus
```
sudo apt-get update
sudo apt-get install dbus
sudo systemctl enable dbus
sudo systemctl start dbus
```

After that configure datetime synchronization
```
sudo apt-get install systemd-timesyncd
sudo timedatectl set-ntp true

```
As a result, the time synchronized with the real time and twofa worked. 

**Maybe you have a bug in your package which causes the clock to be wrong by 4 hours and 21 minutes**

**Comment by gongomgra** [comment]
Hi @Nekolone,

Thanks for your message. We are glad you managed to fix your issue. Also thank you for sharing your solution so it can be of help for other users in the future!
