### ISSUE TITLE
[CanvasLMS]  Apply branding images & custom CSS/JS files

### ISSUE THREAD

**Issue by edtekio** [bitnami/vms#186]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

No response

### bndiagnostic was not useful. Could you please tell us why?

No response

### Describe your issue as much as you can

This Canvaslms was launched with a Bitnami AMI on aws from Marketplace.

We are trying to modify the branding of the account using the "Theme Editor" - But we experience the following issues:

1) Images are not applied. None of the images uploaded appear in the theme afterwards.
For example: The navigation menu Image points to: https://3.69.171.2/accounts/1/files/11/download?verifier=uqk3yXY6z5XUysy2rHlU8fKIb6EKCXG1Ujp0sKSo inside the instance but this url seems to be down/not accesible

2) Custom CSS/JS is not applied. When uploading custom CSS/JS to the theme nothing seems to happen.
For example: The css points to https://3.69.171.2/accounts/1/files/22/download?verifier=y8ReQVy6n5VO4ebkDRxFn4Uplj1FTTXM6SUqXp4W but the url seems to be down/not accesible as well.

I think both issues could be related - As when we click in the url where the assets are stored these seem to be down or not configured correctly in terms of networking.

Some guidance/help would be much appreciated.

Thank you in advance

**Comment by edtekio** [comment]
Comento en castellano ya que veo que sois todos españoles.
Estoy convencido que es algún tema de configuración de la máquina.

No somos muy expertos con este tipo de despliegues. Así que si nos podéis dar alguna indicación os lo agradeceríamos un montón.

Muchas gracias!

**Comment by jotamartos** [comment]
Hola @edtekio,

Muchas gracias por usar nuestra solución. Tu pregunta esta altamente relacionada con la aplicacion y para descartar posibles problemas con ella, te sugiero que contactes con el equipo de soporte de CanvasLMS y que revises su documentación. Ten en cuenta que ellos son los que más facilmente pueden encontrar el problema y ayudarte. Estaremos encantados de aplicar la solución en el caso de que haya un problema de configuración. 

Dejaremos el caso abierto por si algún otro usuario ha recibido este error y sabe como solucionarlo. 

Un saludo

**Comment by edtekio** [comment]
Muchas gracias por la respuesta!

Así lo haremos. Dejaremos constancia por escrito tanto si hay que aplicar alguna solución como si no.

Un saludo

**Comment by edtekio** [comment]
Hola de nuevo,

Tras hablar con el fabricante, nos confirman que esta funcionalidad opera de manera correcta.
Tras hacer algo más de investigación, el problema parece estar en las URLs dónde se almacenan estos CSS/JS y las posteriores llamadas para retribuir dichos archivos.
Lo mismo ocurre con las imágenes de branding aplicadas sobre el tema. Estas no son visibles.

Por otro lado, vemos que la sección de perfil (donde se puede poner una foto de perfil para cada usuario) directamente no existe.
<img width="450" alt="Menu y Opciones en Canvas Bitnami" src="https://user-images.githubusercontent.com/110103175/182613405-47a8532f-339c-423c-bd41-0799eec497d0.png">

Por favor, agradeceríamos mucho vuestra ayuda. Adjunto pantallazos en caso de que faciliten en algo.
<img width="448" alt="Menu y Opciones en Canvas SaaS" src="https://user-images.githubusercontent.com/110103175/182613399-beeef081-66ec-42c1-889b-fbf6e59625ab.png">
<img width="300" alt="Configuración en Canvas Bitnami" src="https://user-images.githubusercontent.com/110103175/182613426-4398e145-dfa7-40ee-9d41-954e7d8138a2.png">

**Comment by jotamartos** [comment]
Hola @edtekio,

Nosotros no desactivamos nada en CanvasLMS, si la sección de perfil no aparece en la aplicación, es por algo directamente relacionado con la aplicación, no con Bitnami. Ten en cuenta que nosotros cogemos el código de la aplicación [desde GitHub](https://github.com/instructure/canvas-lms/tags) y configuramos todo. 

Con respecto a las URLs de los CSS y Javascript, nosotros configuramos el dominio/IP en el fichero domain.yml de la carpeta de configuración de la app. Si la app genera URLs no válidas después, es cosa de la aplicación también, nada que podamos hacer nosotros.

**Comment by edtekio** [comment]
Gracias!

Por favor, podrías indicarnos la ruta a dicho fichero?

Por otro lado, vemos que hay un fichero "configure_app_domain". Para qué sirve este último?

**Comment by jotamartos** [comment]
El fichero debería estar dentro de la carpeta /opt/bitnami/canvaslms/config/. Este es un ejemplo que hay en su repositorio 

https://github.com/instructure/canvas-lms/blob/master/config/domain.yml.example

El fichero configure_app_domain es una tool que incluimos nosotros para actualizar la configuración del dominio/IP en CanvasLMS, basicamente actualiza el fichero domain.yml.
