### ISSUE TITLE
[Wordpress] htdocs and symlinks after update

### ISSUE THREAD

**Issue by ThingUTS** [bitnami/vms#188]
### Describe your issue as much as you can

Finally migrated our existing Lightsail VPS bitnami wordpress  to a new instance, jumping forward several PHP versions, etc.
Updated to
base_stack_name=WordPress packaged by Bitnami
base_stack_version=5.9.3-8
base_stack_key=wordpress
bitnami@ip-172-26-4-223:/opt/bitnami$

And I've had a few issues.

The new instance has a much different overall structure, previously web docs lived in /opt/bitnami/apps/wordpress/htdocs/wp-content.

The new instance has /opt/bitnami/wordpress/wp-content and no htdocs anywhere I can find under the wordrpress folder, although the bitnami home folder had a symlink to apache2/htdocs
 htdocs -> /opt/bitnami/apache2/htdocs

On the previous instance we had a symlink named files in the htdocs folder to another drive containing a large volume of media files that where too large for the main volume the wordpress install is on, but need to be served out in an RSS feed.  I've tried constructing the same symlink in either/both /opt/bitnami/wordpress/wp-content/  and /opt/bitnami/apache/htdocs but it doesn't seem to resolve under <website>/files/testfile.mp3

I'm having trouble determining if this is an issue with the htaccess, permissions, or the actual folder being served for documents.

Also once we migrated the php-fpm threads quickly ate up all available memory and swap bringing the server into an incredibly laggy state.  It looks like the provisioning of the server linked us to memory-xlarge for the php-fpm pools, as we where on the previous instance (16GB memory) although the provisioned pools in this instance are much larger than on the previous site
pm.max_children=200
pm.start_servers=130
pm.min_spare_servers=130
pm.max_spare_servers=150
pm.max_requests=5000

So I created and linked to a much smaller allocation of servers, etc. and that appeared to stabilize memory usage.

None of the documents I have found on the bitnami site seem to reference this layout so I was wondering if I am missing updated documents for this new configuration?

Also in working with the All in One Migration plugin group to get the plugin to run I had to reset wordpress permissions several times.  All the bitnami guides I see appear to say ownership under wordpress should be bitnami:daemon, although their plugin wasn't happy with permissions until I changed ownership to daemon:daemon

**Comment by ThingUTS** [comment]
update, figured out my simlink works in the wordpress folder itself.

**Comment by gongomgra** [comment]
@ThingUTS,

Thank you for using our solution. I'm glad you managed to fix your issue! Regarding the changes to the filesystem, yes, we modified the structure of our images some time ago. You can read more information about this in the next link

https://docs.bitnami.com/virtual-machine/faq/get-started/understand-upcoming-changes/
