### ISSUE TITLE
[Wordpress Multisite] Error on 'A Let's Encrypt Certificate' execution

### ISSUE THREAD

**Issue by DipendraKSahay** [bitnami/vms#189]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ba4a474d-f962-0730-5eed-8becd049bad4

### bndiagnostic output

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Wed Jul 27 14:39:30.649372 2022] [authz_core:error] [pid 726:tid 
139810949773056] [client **ip_address**:44512] AH01630: client denied by server 
configuration: 
/opt/bitnami/wordpress/wp-content/plugins/akismet/class.akismet-https.php
```

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Jul 28 01:33:39.752018 2022] [core:error] [pid 69876:tid 139811083859712] 
[client **ip_address**:59972] AH00124: Request exceeded the limit of 10 internal 
redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Thu Jul 28 02:11:07.243047 2022] [core:error] [pid 69876:tid 139811092252416] 
[client **ip_address**:52796] AH00124: Request exceeded the limit of 10 internal 
redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Thu Jul 28 03:14:04.768538 2022] [core:error] [pid 726:tid 139810991736576] 
[client **ip_address**:50350] AH00124: Request exceeded the limit of 10 internal 
redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
```

### bndiagnostic was not useful. Could you please tell us why?

Unable to install letsencrypt certificate

### Describe your issue as much as you can

Dear Experts,
Greetings!

I used to assign A Let's Encrypt Certificate to my project. Lately, my instance got a technical issue, I had no option except to deploy a new instance to upload my Bitnami project. As I feel necessary to assign a temporary certificate, I find Let's Encrypt a better solution. 

Therefore, I followed the tutorials from 
https://docs.bitnami.com/google/apps/wordpress-pro/administration/generate-configure-certificate-letsencrypt/
then 
https://docs.bitnami.com/google/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

I encountered an issue after assigning the following command (amended email address and domain name)
sudo /opt/bitnami/letsencrypt/lego --tls --email="EMAIL-ADDRESS" --domains="DOMAIN" --domains="www.DOMAIN" --path="/opt/bitnami/letsencrypt" run

It displays a message
`sudo: /opt/bitnami/letsencrypt/lego: command not found`

I humbly request your guidelines. How can I solve and get the privilege of letsencrypt SSL?

Thank you for your anticipation.

Regards

**Comment by gongomgra** [comment]
Hi @DipendraKSahay,

If the lego tool is not already installed in the image, can you install it by following the steps in the [alternative approach guide](https://docs.bitnami.com/google/how-to/generate-install-lets-encrypt-ssl/#step-1-install-the-lego-client)?

**Comment by DipendraKSahay** [comment]
Hello @gongomgra 

I followed each step again to ensure the execution that is outputting error. 

On this command line, 
`tar xf lego_vX.Y.Z_linux_amd64.tar.gz`

It returns the error message as 
```
tar: lego_vX.Y.Z_linux_amd64.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

**Comment by gongomgra** [comment]
Hi @DipendraKSahay,

Notice `X.Y.Z` is a placeholder for the lego tool version that you download with the `curl` command in our guide. For instance, at this moment `4.8.0` is the latest lego version, so you need to replace `X.Y.Z` with `4.8.0` when running the rest of the commands in the guide.

**Comment by DipendraKSahay** [comment]
Hello @gongomgra 

As instructed above, I replaced `X.Y.Z.` with `4.8.0` when running the command, and the execution of the command was with no error. 

However, I encountered an error after turning off Bitnami services, then executing this command line
`sudo /opt/bitnami/letsencrypt/lego --tls --email="xxxxxxxxxxxxxx@xxxxx.com" --domains="xxxxxxxxxxxxxxx.com" --domains="www.xxxxxxxxxxxxxxx.com" --path="/opt/bitnami/letsencrypt" run`

The result show errors, I checked and confirmed Cloud DNS and found it is configured properly.

```
2022/07/30 03:42:37 No key found for account xxxxxxxxxxxxxx@xxxxx.com. Generating a P256 key.
2022/07/30 03:42:37 Saved key to /opt/bitnami/letsencrypt/accounts/acme-v02.api.letsencrypt.org/xxxxxxxxxxxxxx@xxxxx.com/keys/xxxxxxxxxxxxxx@xxxxx.com.key
2022/07/30 03:42:38 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2022/07/30 03:42:45 [INFO] acme: Registering account for xxxxxxxxxxxxxx@xxxxx.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/opt/bitnami/letsencrypt/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2022/07/30 03:42:46 [INFO] [xxxxxxxxxxxxxxx.com, www.xxxxxxxxxxxxxxx.com] acme: Obtaining bundled SAN certificate
2022/07/30 03:42:47 [INFO] [xxxxxxxxxxxxxxx.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxxxxxxxxxxx
2022/07/30 03:42:47 [INFO] [www.xxxxxxxxxxxxxxx.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxxxxxxxxxxx
2022/07/30 03:42:47 [INFO] [xxxxxxxxxxxxxxx.com] acme: use tls-alpn-01 solver
2022/07/30 03:42:47 [INFO] [www.xxxxxxxxxxxxxxx.com] acme: use tls-alpn-01 solver
2022/07/30 03:42:47 [INFO] [xxxxxxxxxxxxxxx.com] acme: Trying to solve TLS-ALPN-01
2022/07/30 03:42:51 [INFO] [xxxxxxxxxxxxxxx.com] The server validated our request
2022/07/30 03:42:51 [INFO] [www.xxxxxxxxxxxxxxx.com] acme: Trying to solve TLS-ALPN-01
2022/07/30 03:42:52 [INFO] Skipping deactivating of valid auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/136201004086
2022/07/30 03:42:52 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxxxxxxxxxxx
2022/07/30 03:42:52 Could not obtain certificates:
        error: one or more domains had a problem:
[www.xxxxxxxxxxxxxxx.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for www.xxxxxxxxxxxxxxx.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for www.xxxxxxxxxxxxxxx.com - check that a DNS record exists for this domain
```

The domain registrar is different hence all my DNS setting is configured within Google Cloud DNS (security as advised by Google Support). 

I could not figure out where did I miss?

Regards

**Comment by gongomgra** [comment]
Hi @DipendraKSahay,

That error means you don't have a www subdomain entry in your DNS registry pointing to your server (usually a CNAME entry). You will have to either add it to your DNS configuration or do not include the `--domain=www.your-domain.com` flag in the `lego` command.

**Comment by DipendraKSahay** [comment]
Hello @gongomgra 

It is true, I don't have CNAME entry on Cloud DNS. My settings for the multisite is `https://mydomain_name.com/subfolder` instead of `https://subdomain.mydomain_name.com`. Therefore, CNAME entry was ignored for now.

Correcting the command line, I followed your instruction, not to include `--domain='www.mydomain_name.com'` flag in the lego command. 

**It shows an error on the browser** `NET::ERR_CERT_AUTHORITY_INVALID`

_The commands and their respective outputs on SSH were :_

`sudo /opt/bitnami/ctlscript.sh stop`
Stoping services..

`sudo /opt/bitnami/letsencrypt/lego --tls --email="myemail_address@mailingserver.com" --domains="mydomain_name.com" --path="/opt/bitnami/letsencrypt" run`
2022/08/02 09:04:53 [INFO] [mydomain_name.com] acme: Obtaining bundled SAN certificate
2022/08/02 09:04:54 [INFO] [mydomain_name.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxxxxxxxxxxxxxx
2022/08/02 09:04:54 [INFO] [mydomain_name.com] acme: authorization already valid; skipping challenge
2022/08/02 09:04:54 [INFO] mydomain_name.com] acme: Validations succeeded; requesting certificates
2022/08/02 09:04:56 [INFO] [mydomain_name.com] Server responded with a certificate.

`sudo /opt/bitnami/ctlscript.sh start`
Starting services..

**Here is a bndiagnostic tool output :** `f8611921-a5b2-d667-dbc4-d5681c79eec3`

Regards

**Comment by gongomgra** [comment]
Hi @DipendraKSahay,

I edited your comment to update the code highlight, please use three backsticks ( ```) marks around your console output to properly format it, as it will make easier for us to review it.

The lego tool returned a valid certificate, can you check Apache is using the certificates it generated? According to the bndiagnostic information it seems to be using the original self-signed certificates. Please follow the rest of the steps in our manual approach guide to configure Apache with your Let's Encrypt certificates.

**Comment by DipendraKSahay** [comment]
Hello @gongomgra 

I retried following the tutorials again to configure Apache A 
https://docs.bitnami.com/google/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

The next error message appears in this command line
`sudo chown root:root /opt/bitnami/apache2/conf/bitnami/certs/server*`

The output is :
chown: cannot dereference '/opt/bitnami/apache2/conf/bitnami/certs/server.crt.old': No such file or directory
chown: cannot dereference '/opt/bitnami/apache2/conf/bitnami/certs/server.key.old': No such file or directory

Regards

**Comment by gongomgra** [comment]
Hi @DipendraKSahay,

Did you rename the previous certificate as mentioned in the guide? Anyways I don't think this is a problem, you can continue creating the symbolic links for the new certificates and running the other commands in the guide.

**Comment by mdhont** [comment]
Did you configure the domain as well? 

https://docs.bitnami.com/ibm/apps/wordpress-multisite/configuration/configure-wordpress-multisite/

**Comment by DipendraKSahay** [comment]
Hello @mdhont 

I tried to fix it by following every step of the guidelines. The website name is _protocoltrilogy.com_.

Regards

**Comment by gongomgra** [comment]
Hi @DipendraKSahay,

I visited your website and it is using a valid Let's Encrypt certificate. Did you manage to solve your issue?

![Screen Shot 2022-09-07 at 12 27 15](https://user-images.githubusercontent.com/6660452/188856215-aac49552-d553-4c29-ba2e-b9ce97e6f230.png)

**Comment by DipendraKSahay** [comment]
Hi @gongomgra 

Yes, I have checked in several browsers. In the Chromium browser, it shows unsecured. 

Regards
![error_on_chromium](https://user-images.githubusercontent.com/65714100/188859110-a84420b8-913c-4683-82de-a3bb80249d98.jpg)

**Comment by gongomgra** [comment]
Hi @DipendraKSahay,

I visited your website using Firefox and it is true that in the first visit with HTTPS you get an image included with an HTTP (not secure) link.

![Screen Shot 2022-09-07 at 13 08 50](https://user-images.githubusercontent.com/6660452/189067499-a89a02bc-dc43-434e-b915-0731d1809bbd.png)

I also detected you aren't forcing HTTP to HTTPS redirection on your Apache configuration, you can try enabling the Apache configuration (remember to restart Apache for changes to apply), or update the URL in the WordPress admin panel for that element with HTTPS.

```
$ curl -LI "http://protocoltrilogy.com/"
HTTP/1.1 200 OK
Date: Thu, 08 Sep 2022 07:58:08 GMT
Server: Apache
Link: <http://protocoltrilogy.com/wp-json/>; rel="https://api.w.org/", <http://protocoltrilogy.com/wp-json/wp/v2/pages/2197>; rel="alternate"; type="application/json", <http://protocoltrilogy.com/>; rel=shortlink
Content-Type: text/html; charset=UTF-8
```

https://docs.bitnami.com/aws/apps/wordpress/administration/force-https-apache/
