### ISSUE TITLE
Process: 3379 ExecStart=/etc/init.d/bitnami start

### ISSUE THREAD

**Issue by ove1990** [bitnami/vms#190]
### Describe your issue as much as you can

 Process: 3379 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)

**Comment by jotamartos** [comment]
Hi @ove1990,

Could you please provide more information about the error you are running into? 

- Is that a new deployment? Did you make changes in the configuration?
- What platform you are using? 
- What are the specs of the machine you are using? (RAM, disk, ...)
- What command you are trying to run? 

Apart from that, please edit the title of the issue to match with the template we provided ([APPLICATION NAME] TITLE OF THE ISSUE). That way, users will find the solution of this issue easily in the future.

**Comment by ove1990** [comment]
Can you Please let me know what is issue here ?
I am not able to start the MariaDB in Bitnami 

 

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock'

 



 


 

Platform -AWS

Ram – 2 GB 

Disk – 60 GB

**Comment by jotamartos** [comment]
I can't help you if you do not answer the questions I posted above. Could you please take a look at them and provide the required information?

We also have a support tool called bndiagnostic that you can run for us to obtain more info

https://docs.bitnami.com/aws/how-to/understand-bndiagnostic/

Thanks
