### ISSUE TITLE
[Moodle] Error when trying to customize the language

### ISSUE THREAD

**Issue by teksukamen** [bitnami/vms#191]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

93c70893-656e-35d6-d9ca-d77ff928931b

### bndiagnostic output

```
[Thu Jul 28 09:26:10.770095 2022] [proxy_fcgi:error] [pid 4898:tid
140116966061824] [client **ip_address**:64176] AH01071: Got error 'PHP message:
Default exception handler: Error escribiendo a la base de datos Debug: Incorrect
string value: '\xF0\x9F\x91\x8B' for column
`bitnami_moodle`.`mdl_tool_customlang`.`original` at row 1
INSERT INTO mdl_tool_customlang
Press [Enter] to continue:
(lang,componentid,stringid,original,master,timemodified,outdated,local,timecustom
ized) VALUES(?,?,?,?,?,?,?,?,?)
[array (
 0 => 'en' [Thu Jul 28 09:41:34.074052 2022] [core:error] [pid 4897:tid
140117192664832] [client **ip_address**:54672] AH10244: invalid URI path
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
```

### bndiagnostic was not useful. Could you please tell us why?

yes it was the last one but I had to install it since the command was not available.

### Describe your issue as much as you can

Moodle 4.01, updated from 3.8

Hello, when I try to customize the language I receive this error message. 

A separate issue is that I cannot enter phpmyadmin, it does not recognize my password, even though I use the same one that appears in config.php or I cannot download the database with msqldump, I receive an error:

Access denied for user bn_moodle@localhost (using password: yes)

**Comment by jotamartos** [comment]
Hi @teksukamen,

Thank you for using Bitnami and contact us. I edited the title to match with the template we provide when creating the ticket, please take that into account when creating a ticket in the future. 

Regarding the issues, 

> [Thu Jul 28 09:26:10.770095 2022] [proxy_fcgi:error] [pid 4898:tid
> 140116966061824] [client **ip_address**:64176] AH01071: Got error 'PHP message:
> Default exception handler: Error escribiendo a la base de datos Debug: Incorrect
> string value: '\xF0\x9F\x91\x8B' for column
> `bitnami_moodle`.`mdl_tool_customlang`.`original` at row 1
> INSERT INTO mdl_tool_customlang
> Press [Enter] to continue:
> (lang,componentid,stringid,original,master,timemodified,outdated,local,timecustom
> ized) VALUES(?,?,?,?,?,?,?,?,?)
> [array (

this one is highly related to the application so we suggest you ask the Moodle's support team to know more about this. We do not know why the application can't write that information in the database. 

https://moodle.org/mod/forum/index.php?id=5

>A separate issue is that I cannot enter phpmyadmin, it does not recognize my password, even though I use the same one that appears in config.php or I cannot download the database with msqldump, I receive an error:

Did you try using root and the password that is configured during the instance's initialization? That password is the same one we configure for you to access Moodle.

**Comment by teksukamen** [comment]
Hi Jotamartos, I finally found how to solve the language problem, the steps are as follows:

Must set the collation to utf8mb4_unicode_ci:

sudo php /opt/bitnami/moodle/admin/cli/mysql_collation.php --collation=utf8mb4_unicode_ci (Approach A in mi case)

then in the config.php you must adjust

$CFG->dboptions = array(
...
'dbcollation' => 'utf8mb4_unicode_ci',
...

Finally you restart the services and that's it, the error disappears and the language can be customized.

https://docs.bitnami.com/aws/apps/moodle/troubleshooting/debug-errors/ 


Now about logging into phpmyadmin, I edited the config.php file,

change this line:
$CFG->dbhost = '127.0.0.1';
for this:
$CFG->dbhost = 'localhost';

now it recognizes the dbpass password

**Comment by jotamartos** [comment]
Thanks for the information! I'm sure it'll be really useful for those other users who get the same error. 

Enjoy!
