### ISSUE TITLE
[WordPress] How to enable CORS

### ISSUE THREAD

**Issue by cguanaja** [bitnami/vms#192]
### Describe your issue as much as you can

I need to enable CORS on a Bitnami server (in the AWS cloud) - found the URL below but output of command on the URL says that my instance is under approach B but unable to find path structure suggested on the article.

```
bitnami@ip-172-26-13-20:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
bitnami@ip-172-26-13-20:~$ 
```

https://docs.bitnami.com/aws-templates/apps/wordpress/configuration/enable-cors-wordpress/

```
bitnami@ip-172-26-13-20:~$ test ! -f "/opt/bitnami/common/bin/openssl" && echo "Approach A: Using system packages." || echo "Approach B: Self-contained installation."
Approach B: Self-contained installation.
bitnami@ip-172-26-13-20:~$ 
```

URL suggests that httpd-app.conf for approach B should be in /opt/bitnami/wordpress/ but when connecting via FTP I see this one only /opt/bitnami/apps/wordpress and can't find httpd-app.conf - where is this file located at? 

Is there any other change so CORS on server is enabled?

Thanks.

**Comment by jotamartos** [comment]
Hi @cguanaja,

There is a typo in the documentation. The httpd-app.conf file is inside the `/opt/bitnami/apps/wordpress/conf` directory. The "Directory" block, should also use `/opt/bitnami/apps/wordpress/htdocs/wp-admin`. 

Sorry for the inconvenience.

Thanks

**Comment by jotamartos** [comment]
Hi! I applied the changes in the documentation and they should be live soon!

Have a good day!
