### ISSUE TITLE
[Wordpress] removing /wordpress/ in url

### ISSUE THREAD

**Issue by PureGolded** [bitnami/vms#193]
### Describe your issue as much as you can

Hi,

so, I use bitnami wordpress hosting and I have been trying to figure out how to remove that /wordpress/ out of the URL because I have my domain and it is showing after the domain, but I want that to be clear, and also when someone uses the domain it redirects him to bitnami starting page where he has to choose if he wants to enter wordpress page.

When I tried to google solution with bitnami, I found something, but when I tried to go to the link it automatically redirects me here so I just made my own post asking for help.

(I did not change anything yet)

If someone has experience with this or the same issue with a solution, please tell me,
Thanks in advance.

**Comment by jotamartos** [comment]
Hi @PureGolded,

If you are using the Bitnami native installer for WordPress, you can use the bnconfig tool inside the installdir/apps/wordpress directory to move the application to the root path.

https://docs.bitnami.com/installer/faq/linux-faq/configuration/understand-bnconfig/

If you are using linux, you basically need to run this command 

```
installdir/apps/wordpress/bnconfig --appurl /
```

I hope this help!
