### ISSUE TITLE
[Moodle] unable to access EC2 console

### ISSUE THREAD

**Issue by L3dge** [bitnami/vms#194]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Cannotaccess

### bndiagnostic output

Cannot access the console so cannot run any diagnostic tools
Failed to connect to your instance
Error establishing SSH connection to your instance. Please wait and try again later.

### bndiagnostic was not useful. Could you please tell us why?

Cannot access console to run it

### Describe your issue as much as you can

A new Bitnami LMS powered by Moodle(TM) LMS on AWS. Launched via Marketplace. Have set a PPK file and cannot access EC2-Console or via PUTTY
Failed to connect to your instance
Error establishing SSH connection to your instance. Please wait and try again later.

**Comment by gongomgra** [comment]
Hi @L3dge,

Thanks for using Bitnami. Unfortunately, I couldn't reproduce your issue when launching the Moodle image through AWS Marketplace, and I was able to connect with my server using the SSH key I selected. During the subscription process in the AWS Marketplace, there is an option to configure the new image using the web interface or the EC2 console. I followed the EC2 console workflow, can you try it? 

Apart from that, can you check you have the SSH port open in your server and accessible from everywhere? Find below a couple of guides I think that can be of help here

* https://docs.bitnami.com/aws/faq/get-started/connect-ssh/#obtain-ssh-credentials-from-the-aws-console
* https://docs.bitnami.com/aws/faq/administration/use-firewall/
