### ISSUE TITLE
[Wordpress] Download Old OVA Version

### ISSUE THREAD

**Issue by faizstud** [bitnami/vms#195]
### Describe your issue as much as you can

Hello and good day,

May I know where I can get old .ova file for Bitnami Wordpress? My project compatible with PHP 7.4 and I can see the latest .ova file preinstalled with PHP 8.0.

I would be grateful for your prompt reply.

Thank you.

**Comment by mdhont** [comment]
You can download it here:

https://downloads.bitnami.com/files/stacks/wordpress/5.9.2-6/bitnami-wordpress-5.9.2-6-linux-centos-7-x86_64-nami.ova 

`md5:5d6fe20ab11b7983422328859015e964`

**Comment by faizstud** [comment]
Hello Sir,

Thank you for the link and best support.
