### ISSUE TITLE
[Joomla] Files uploading as daemon:daemon

### ISSUE THREAD

**Issue by 90stm** [bitnami/vms#197]
### Describe your issue as much as you can

When applications are updated on the front-end of Joomla or even images saved, they are all being saved as daemon:daemon. But the permissions I believe should be set to bitnami:daemon in order to work, correct?

I have tried everything I could find on the web and still lost..
Hoping someone has encountered this and can help.

The company that made the software mentioned I may need to change webuser (apache) from daemon to bitnami on our server?  Not sure, if there is another way, but if this is the only way some instructions on this or any other resolve would be so greatly appreciated..
[error_log.txt](https://github.com/bitnami/vms/files/9228266/error_log.txt)

My root folder that everything is being downloaded from Joomla is:
/opt/bitnami/apps/xxxx/htdocs
In case this helps...
[access_log.txt](https://github.com/bitnami/vms/files/9228267/access_log.txt)

**Comment by gongomgra** [comment]
Hi @90stm,

Thanks for using Bitnami. The Apache service is run by the daemon user, so that's why the files are written with `daemon:daemon` instead of `bitnami:daemon`. However, it doesn't affect the application at all, as the application internal code is also run as the `daemon` user, so it will have the required filesystem permissions to properly work (the same it has when they were originally set as `bitnami:daemon`). The only benefit of having those files permissions configured as `bitnami:daemon` is that you can easily work with them when connecting with your server using the `bitnami` user. Hope it clarifies your question!

**Comment by 90stm** [comment]
Totally understand. Yet, still have an issue because when a file does update in the backend of Joomla.  
All of the components are immediately saved as daemon:daemon.
The only way I am sometimes able to even update some components is by using this command:

`sudo chown -R daemon /opt/bitnami/apps/xxxxxx/htdocs`

Then when updating is complete on backend of Joomla, I will put it back as;

`sudo chown -R bitnami:daemon /opt/bitnami/apps/joomla/htdocs`

Works most of the time, but have run into some updates where it didn't...
Hence, this support ticket.

Do you think this can work?

1. Chmod read and write permission to this owner/group daemon:daemon to the existing folders and files on the site.

2. Change this "bitnami" FTP user account to have permission to edit the file owner/group is under daemon:daemon

If any of these would or wouldn't work, would you mind letting me know how to go about it, please & thank you.

**Comment by gongomgra** [comment]
Hi @90stm,

I'm afraid I'm not fully understanding your question. As mentioned, you can keep the files under the htdocs folder as `daemon:daemon` if it helps you with the upgrade process. Setting them to `bitnami:daemon` is only a way of simplifying the maintenance of the installation itself (like having to update the config file for Joomla), but that's not usually necessary. The `bitnami` user has sudo privileges, so you could manage the installation even if files doesn't belong to the bitnami user directly.

**Comment by 90stm** [comment]
Yes, that is what I thought, but that isn't what is happening..  Bitnami doesn't have sudo privileges on our server for some reason.   This is why we are having an issue with updates.

Any code or tricks to get it back to what you mentioned?

**Comment by gongomgra** [comment]
Hi @90stm,

I think there is something on your reply that I'm not understanding. You said that bitnami doesn't have sudo privileges on your server, but you shared before a couple of commands using sudo. From which user did you run them? Did you modify the bitnami user somehow? If so, can you tell us why? 

Apart from that, notice that if you are using the `/opt/bitnami/apps/joomla/htdocs` filesystem structure, this means that you are using an old version of the image. We changed the filesystem structure to a different model, where Joomla is now located at `/opt/bitnami/joomla`. Will launching a new image and migrate your application data there be a solution for you?

https://docs.bitnami.com/aws/faq/get-started/understand-upcoming-changes/

**Comment by 90stm** [comment]
`Will launching a new image and migrate your application data there be a solution for you?`

Yes, I think it did resolve the issue.
We are now updated with the most recent Bitnami Joomla Stack.
It will take some getting used to with files/folders different, but we are good..
Thanks for the advice.

**Comment by gongomgra** [comment]
Hi @90stm,

Thanks for letting us know! We are glad using a newer image worked for you.
