### ISSUE TITLE
[Wordpress] How to keep Wordpress server up to date

### ISSUE THREAD

**Issue by Youlean** [bitnami/vms#198]
I have a website that has the old version of PHP and I want to update it.
 
From the research, I have concluded that the best way to do it would be to create a new VM and clone the site. Is that a preferred method for applying security updates?

If so, what would be the best method of cloning a website while keeping all custom configurations on Google Cloud for example?

**Comment by jotamartos** [comment]
Hi @Youlean,

you can follow this guide to migrate the WordPress' data to a new server. 

https://docs.bitnami.com/google/how-to/migrate-wordpress/

You will need to manually migrate any other data like SSL certificates or any Apache's conf change you applied.

Thanks!
