### ISSUE TITLE
[MOODLE] Can't get moodle to send emails via sendgrid or any other smtp even with no authentication or encryption

### ISSUE THREAD

**Issue by janus-at-pkf** [bitnami/vms#200]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9738e8b3-df1f-907b-d5ab-4ee875e6462d

### bndiagnostic output

? Apache: Found possible issues
    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ✓ Resources: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Aug 01 07:48:47.921790 2022] [proxy_fcgi:error] [pid 7847:tid 
139669341611776] [client **ip_address**:59068] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: 
https://pdp.pkfoctagononline.co.za/admin/tool/installaddon/index.php
 [Mon Aug 01 11:16:14.008049 2022] [proxy_fcgi:error] [pid 845:tid 
Press [Enter] to continue:
139865022764800] (70007)The timeout specified has expired: [client 
**ip_address**:61376] AH01075: Error dispatching request to : (polling), 
referer: https://pdp.pkfoctagononline.co.za/admin/testoutgoingmailconf.php
 [Mon Aug 01 11:24:13.411214 2022] [proxy_fcgi:error] [pid 843:tid 
139865163753216] (70007)The timeout specified has expired: [client 
**ip_address**:61435] AH01075: Error dispatching request to : (polling), 
referer: https://pdp.pkfoctagononline.co.za/admin/testoutgoingmailconf.php

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

### bndiagnostic was not useful. Could you please tell us why?

My image seems to differ from the documentation

### Describe your issue as much as you can

I am struggling with various issues which is probably related to the same problem.

1. I got the URL changed by running the SSL tool which is probably not correct but it worked. I need this properly configured.
2. The ports 443 were opened when initialising the image but as per the diagnostic there is an issue with this
3. I need to change the landing page to the login page not the home page
4. Trying to configure SMTP but it's not working probably related to point 1.
5. Not seeing all items under site administration, have to search for many settings.

**Comment by mdhont** [comment]
We have a guide for setting up SMTP for Moodle:

https://docs.bitnami.com/installer/apps/moodle/configuration/configure-smtp/

**Comment by janus-at-pkf** [comment]
Hi Michiel,

So the information is configured correctly in Moodle.

I have tested the email settings through another moodle install and it works there leading me to believe there is something not correctly set up on the bitnami image.

I have checked on GCP ports TCP 22 and 465 egress is enabled on the firewall.

Thanks,

**Comment by mdhont** [comment]
Did you follow the same steps as in the guide? I also recommend asking in a dedicated Moodle forum.
