### ISSUE TITLE
Wordpress HT Access & 301 Redirects

### ISSUE THREAD

**Issue by DanGoldsmith** [bitnami/vms#202]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

22fa31d6-36a7-ceae-30ef-443515ee1227

### bndiagnostic output

[Mon Aug 01 18:25:15.774628 2022] [proxy_fcgi:error] [pid 7243:tid 
139785230259968] [client **ip_address**:52169] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php 
on line 173PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 174PHP message: PHP Warning: Undefined 
Press [Enter] to continue:
array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php on line 
687PHP message: PHP Warning: Undefined ar [Tue Aug 02 00:04:28.079947 2022] 
[authz_core:error] [pid 8595:tid 140305751754496] [client **ip_address**:46890] 
AH01630: client denied by server configuration: /opt/bitnami/apache/cgi-bin
 [Tue Aug 02 00:06:18.422473 2022] [authz_core:error] [pid 8307:tid 
140305902823168] [client **ip_address**:51558] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin

[Mon Aug 01 18:04:29.136479 2022] [proxy_fcgi:error] [pid 7243:tid 
139785289008896] [client **ip_address**:56405] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: http://18.135.60.105/wp-admin/plugin-install.php

### bndiagnostic was not useful. Could you please tell us why?

Doesn't relate to the issue I face

### Describe your issue as much as you can

Im using Bitnami on a Wordpress AWS Lightsail installation and need to be able to write 301 redirects to the DOT HTaccess file. I've read multiple threads online about this and watched many videos including your own, (on youtube) and am still unable to resolve my issue or find a definitive answer to the best practice for 301 redirects with Bitnami.

Using the Lightsail terminal, I've;
sudo find /opt/bitnami/ -name ".htaccess"

Which gives me this path...
/opt/bitnami/wordpress/.htaccess

In here I can see the usual wordpress DOT HTaccess info and the plugin data for my caching plugin.

At the bottom of this file, I've added a usual 301 redirect to test...
Redirect 301 /privacy-policy /

Saved the file and then re-started Apache using this command....
sudo /opt/bitnami/ctlscript.sh restart apache

However this hasn't created the re-direction I was expecting?

**Comment by mdhont** [comment]
For htaccess rules bitnami uses a single htaccess.conf file. Did you check this guide?

https://docs.bitnami.com/aws/apps/wordpress/administration/use-htaccess/

**Comment by DanGoldsmith** [comment]
I've read this but I'm struggling to understand the documentation on how or which files I should edit?

If I do this.
**sudo find /opt/bitnami/ -name ".htaccess"**

I get only this returned in the CL...
**/opt/bitnami/wordpress/.htaccess**

When I 'cat' into it, I see all the usual Wordpress  HTaccess details I would expect including what my caching plugin writes.
**BUT if I write a 301 redirect in here too, it doesn't work?**

Which makes me wonder if the rest of the information written here is even being used?

********************************

Following your Bitnami documentation;
I'm using Approach A.

********************************

If I 'cat' into;
**cat /opt/bitnami/apache2/conf/vhosts/wordpress-vhost.conf**

I have this in there...

<VirtualHost 127.0.0.1:80 _default_:80>
  ServerName www.example.com
  ServerAlias *
  DocumentRoot /opt/bitnami/wordpress
  # BEGIN: Configuration for letsencrypt
  Include "/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf"
  # END: Configuration for letsencrypt
  # BEGIN: Support domain renewal when using mod_proxy without Location
  <IfModule mod_proxy.c>
    ProxyPass /.well-known !
  </IfModule>
  # END: Support domain renewal when using mod_proxy without Location
  # BEGIN: Enable HTTP to HTTPS redirection
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
  # END: Enable HTTP to HTTPS redirection
  # BEGIN: Enable www to non-www redirection
  RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^(.*)$ http://%1$1 [R=permanent,L]
  # END: Enable www to non-www redirection
  <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic 
links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
    # END WordPress
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
  # BEGIN: Support domain renewal when using mod_proxy within Location
  <Location /.well-known>
    <IfModule mod_proxy.c>
      ProxyPass !
    </IfModule>
  </Location>
  # END: Support domain renewal when using mod_proxy within Location
</VirtualHost>

********************************

If I 'cat' into;
**/opt/bitnami/apache2/conf/vhosts/htaccess/wordpress-htaccess.conf**

I have this in there...

<Directory "/opt/bitnami/wordpress/wp-content/plugins/akismet">
  # Only allow direct access to specific Web-available files.
  
  # Apache 2.2
  <IfModule !mod_authz_core.c>
  Order Deny,Allow
  Deny from all
  </IfModule>
  
  # Apache 2.4
  <IfModule mod_authz_core.c>
  Require all denied
  </IfModule>
  
  # Akismet CSS and JS
  <FilesMatch "^(form\.js|akismet\.js|akismet\.css)$">
  <IfModule !mod_authz_core.c>
  Allow from all
  </IfModule>
  
  <IfModule mod_authz_core.c>
  Require all granted
  </IfModule>
  </FilesMatch>
  
  # Akismet images
  <FilesMatch "^logo-(a|full)-2x\.png$">
  <IfModule !mod_authz_core.c>
  Allow from all
  </IfModule>
  
  <IfModule mod_authz_core.c>
  Require all granted
  </IfModule>
  </FilesMatch>
</Directory>

Can you please help me understand all this.... 
1) Most of the documentation online and on youtube relates to the previous Bitnami solution where the files were all in a different location and there seems to be differing approaches taken by all tutorials, so it is really hard to understand the best practice.

**Comment by DanGoldsmith** [comment]
I've read this but I'm struggling to understand the documentation on how or which files I should edit?

If I do this.
**sudo find /opt/bitnami/ -name ".htaccess"**

I get only this returned in the CL...
**/opt/bitnami/wordpress/.htaccess**

When I 'cat' into it, I see all the usual Wordpress  HTaccess details I would expect including what my caching plugin writes.
**BUT if I write a 301 redirect in here too, it doesn't work?**

Which makes me wonder if the rest of the information written here is even being used?

********************************

Following your Bitnami documentation;
I'm using Approach A.

********************************

If I 'cat' into;
**cat /opt/bitnami/apache2/conf/vhosts/wordpress-vhost.conf**

I have this in there...

<VirtualHost 127.0.0.1:80 _default_:80>
  ServerName www.example.com
  ServerAlias *
  DocumentRoot /opt/bitnami/wordpress
  # BEGIN: Configuration for letsencrypt
  Include "/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf"
  # END: Configuration for letsencrypt
  # BEGIN: Support domain renewal when using mod_proxy without Location
  <IfModule mod_proxy.c>
    ProxyPass /.well-known !
  </IfModule>
  # END: Support domain renewal when using mod_proxy without Location
  # BEGIN: Enable HTTP to HTTPS redirection
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
  # END: Enable HTTP to HTTPS redirection
  # BEGIN: Enable www to non-www redirection
  RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^(.*)$ http://%1$1 [R=permanent,L]
  # END: Enable www to non-www redirection
  <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic 
links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
    # END WordPress
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
  # BEGIN: Support domain renewal when using mod_proxy within Location
  <Location /.well-known>
    <IfModule mod_proxy.c>
      ProxyPass !
    </IfModule>
  </Location>
  # END: Support domain renewal when using mod_proxy within Location
</VirtualHost>

********************************

If I 'cat' into;
**/opt/bitnami/apache2/conf/vhosts/htaccess/wordpress-htaccess.conf**

I have this in there...

<Directory "/opt/bitnami/wordpress/wp-content/plugins/akismet">
  # Only allow direct access to specific Web-available files.
  
  # Apache 2.2
  <IfModule !mod_authz_core.c>
  Order Deny,Allow
  Deny from all
  </IfModule>
  
  # Apache 2.4
  <IfModule mod_authz_core.c>
  Require all denied
  </IfModule>
  
  # Akismet CSS and JS
  <FilesMatch "^(form\.js|akismet\.js|akismet\.css)$">
  <IfModule !mod_authz_core.c>
  Allow from all
  </IfModule>
  
  <IfModule mod_authz_core.c>
  Require all granted
  </IfModule>
  </FilesMatch>
  
  # Akismet images
  <FilesMatch "^logo-(a|full)-2x\.png$">
  <IfModule !mod_authz_core.c>
  Allow from all
  </IfModule>
  
  <IfModule mod_authz_core.c>
  Require all granted
  </IfModule>
  </FilesMatch>
</Directory>

Can you please help me understand all this.... 
1) Most of the documentation online and on youtube relates to the previous Bitnami solution where the files were all in a different location and there seems to be differing approaches taken by all tutorials, so it is really hard to understand the best practice.

**Comment by mdhont** [comment]
`.htacess` files are ignored due to the way Apache is configured. You need to add the htaccess rules to the following file:

    /opt/bitnami/apache2/conf/vhosts/htaccess/wordpress-htaccess.conf

**Comment by DanGoldsmith** [comment]
Thank you for this Michiel.

So to confirm I can go to;
**/opt/bitnami/apache2/conf/vhosts/htaccess/wordpress-htaccess.conf**

and add this there (for example) to perform a simple 301 re-direct.

**<IfModule mod_rewrite.c>
RewriteEngine On
Redirect 301 /tonbridge-homepage /tonbridge/nursery
</IfModule>**

***********************************************************
***********************************************************
**QUESTION**
The usual Wordpress HTaccess re-writes and the caching plugin ones all seem to be in here;
**/opt/bitnami/wordpress/.htaccess**

I see no mention of them in;
**/opt/bitnami/apache2/conf/vhosts/htaccess/wordpress-htaccess.conf**

So are they actually working? Do I need to manually move them to;
**/opt/bitnami/apache2/conf/vhosts/htaccess/wordpress-htaccess.conf**

Without doing so,
I don't see any issue with my Wordpress install and the Caching plug-in isn't flagging any warnings to me.
But if the re-writes it makes are being ignored, is it even working?

**Comment by mdhont** [comment]
.htaccess files will be ignored by Apache. You need to move the content of the .htaccess file to wordpress-htaccess.conf. 

> I don't see any issue with my Wordpress install and the Caching plug-in isn't flagging any warnings to me either.
But if the re-writes here are being ignored, are they even working?

If you are not getting any warnings and it seems to be working it's probably ok not to add the rules to the wordpress-htaccess.conf file.
