### ISSUE TITLE
Wordpress Bitnami AWS Apache Rewrite issue

### ISSUE THREAD

**Issue by roryheaney** [bitnami/vms#204]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

41b14970-0301-5ca2-e28b-00237704fba0

### bndiagnostic output

? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Tue Aug 02 19:19:25.309204 2022] [proxy_fcgi:error] [pid 13296:tid
140078739220224] [client **ip_address**:45776] AH01071: Got error 'PHP message:
PHP Warning: Constant WP_DEBUG already defined in
/bitnami/wordpress/wp-config.php on line 99PHP message: PHP Warning: Constant
SCRIPT_DEBUG already defined in /bitnami/wordpress/wp-config.php on line 100PHP
Press [Enter] to continue:
message: PHP Warning: Constant WP_DEBUG_LOG already defined in
/bitnami/wordpress/wp-config.php on line 101PHP message: PHP Warning: Constant
[Tue Aug 02 19:19:42.260140 2022] [proxy_fcgi:error] [pid 13296:tid
140079630604032] [client **ip_address**:11244] AH01071: Got error 'PHP message:
PHP Warning: Constant WP_DEBUG already defined in
/bitnami/wordpress/wp-config.php on line 99PHP message: PHP Warning: Constant
SCRIPT_DEBUG already defined in /bitnami/wordpress/wp-config.php on line 100PHP
message: PHP Warning: Constant WP_DEBUG_LOG already defined in
/bitnami/wordpress/wp-config.php on line 101PHP message: PHP Warning: Constant W
[Tue Aug 02 19:19:56.009579 2022] [proxy_fcgi:error] [pid 13164:tid
140079376803584] [client **ip_address**:45848] AH01071: Got error 'PHP message:
PHP Warning: Constant WP_DEBUG already defined in
/bitnami/wordpress/wp-config.php on line 99PHP message: PHP Warning: Constant
SCRIPT_DEBUG already defined in /bitnami/wordpress/wp-config.php on line 100PHP
message: PHP Warning: Constant WP_DEBUG_LOG already defined in
/bitnami/wordpress/wp-config.php on line 101PHP message: PHP Warning: Constant

### bndiagnostic was not useful. Could you please tell us why?

It only returned warnings inside of the wp-config.php file that weren't needed.  

### Describe your issue as much as you can

Hello.

We have the following rewrite in place in out htaccess file. 

- /opt/bitnami/apache2/conf/vhosts/htaccess
- wordpress-htaccess.conf (code placed at the bottom of the file)

```
 <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # access redirect
    RewriteEngine On
    RewriteRule ^wp-content/uploads(\/\d{4}/\d{2}/[A-Za-z0-9_@.\/&+-]+)+\.(pdf|doc|docx)$ /index.php?medstaff_acess=$1&file_type=$2 [QSA,L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
    # END WordPress
 </Directory>
```

It then references code inside our theme that checks against the mime type and then downloads the file.  This works both locally and on separate Apache installs with both Bitnami and other platforms.  Our only issue is with the AWS Bitnami version being used.  

Currently, it corrupts all medium types instead of serving the files.  

Below are the headers we are passing:

```
 header("Content-Disposition: attachment; filename=\"".$file_name."\"");
 header("Content-Type: {$mimetype}"); // always send this.
 header("Content-Length: {$filesize}");
 header("Last-Modified: {$last_modified} GMT");
 header("ETag: {$etag}");
 header("Expires: {$expire} GMT");
 header('X-Robots-Tag: none');
```

Access.php is attached as well. This is referenced in the redirect above and passes back the headers for said files.

**Comment by mdhont** [comment]
Please check the following guide:

https://docs.bitnami.com/aws/apps/wordpress/administration/use-htaccess/

For general questions about Rewrite rules I recommend asking in a general support forum like StackOverflow.

**Comment by epileftro85** [comment]
@roryheaney did you find the solution for this? I am facing this too and the documentation didn't help.

**Comment by CieRory** [comment]
@epileftro85 I actually switched to the nginx version and then my rewrites worked no problem (you'll need to adjust them for nginx).
