### ISSUE TITLE
[WordPress] chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php

### ISSUE THREAD

**Issue by DanGoldsmith** [bitnami/vms#205]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

592966a9-fc00-fb66-f2f3-7e0d1781573f

### bndiagnostic output

[Wed Aug 03 11:14:39.336871 2022] [proxy_fcgi:error] [pid 8781:tid 
139689105254144] [client **ip_address**:52220] AH01071: Got error 'n line 173PHP 
message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
Press [Enter] to continue:
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in /op [Wed Aug 03 
11:17:07.549065 2022] [proxy_fcgi:error] [pid 8472:tid 139689113646848] [client 
**ip_address**:52273] AH01071: Got error 'PHP message: PHP Warning: chmod(): 
Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173', referer: https://greenwellies.co.uk/wp-admin/update-core.php
 [Wed Aug 03 11:17:09.584472 2022] [proxy_fcgi:error] [pid 8472:tid 
139689113646848] [client **ip_address**:52273] AH01071: Got error 'PHP message: 
PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in /opt/bitnami/

### bndiagnostic was not useful. Could you please tell us why?

I don't understand how to fix this

### Describe your issue as much as you can

I've installed a fresh copy of Lightsail, created the static ip address and used the BN-cert-tool to create an ssl and set up a new Wordpress installation. I've then used the BN-testing-tool to make sure everything is completed correctly and I have this warning.

Can you explain what it means and the steps I need take please to resolve the issue.

With thanks
Dan.

**Comment by jotamartos** [comment]
Please set the title correctly for others to find the solution easily. I'm going to update it now.

Seems to be an issue with the permissions configuration, could you please take a look at this other post? 

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974
