### ISSUE TITLE
[WordPress] Refused to apply style font family because its MIME type (‘text/html’)

### ISSUE THREAD

**Issue by MrVeeto** [bitnami/vms#206]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

u

### bndiagnostic was not useful. Could you please tell us why?

can't run full bndiagnostic

### Describe your issue as much as you can

Hello.

i try inspect the source on my website and found this error.

`Refused to apply style from 'https://fonts.googleapis.com/css2?family=poppi%3Aital%2Cwght%400%2C300%3B0%2C400%3B0%2C500%3B0%2C600%3B0%2C700%3B1%2C300%3B1%2C400%3B1%2C500%3B1%2C600%3B1%2C700&display=swap&ver=6.0.1' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

How can i fixed this? i try to contact Elementor support, but they said mostly like a server issue

**It is more a server problem. You have to contact your hosting company so that

they can edit the MIME types accordingly and allow the text/html mime type:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types]
Let me know if they could sort this out.
I am looking forward to hearing back from you.**

**Comment by jotamartos** [comment]
You can configure the MIME types in the Apache configuration by following the official documentation 

https://httpd.apache.org/docs/current/mod/mod_mime.html#addtype

Please note that you need to configure these settings either in the main Apache's config file (/opt/bitnami/apache/conf/httpd.conf) or in the WordPRess' conf files inside the /opt/bitnami/apache/conf/vhosts folder.
