### ISSUE TITLE
[ReportServer Enterprise] Launchpad throwing an error on create via api/v1/user_licenses.json endpoint

### ISSUE THREAD

**Issue by iamakimmer** [bitnami/vms#208]
### Describe your issue as much as you can

I'm trying to create the "Bitnami ReportServer Enterprise Stack" via AWS launchpad:

![image](https://user-images.githubusercontent.com/335105/182624194-77887ec5-9a09-49ea-8715-295d668265b3.png)

Upon clicking Accept and Launch I receive an error at this api/v1/user_licenses.json and unable to proceed. Any thoughts here?

**Comment by gongomgra** [comment]
Hi @iamakimmer,

Thanks for your interest in using Bitnami. Unfortunately, we are in the process of removing ReportServer Enterprise from our catalog and launching new instances of it is not possible.
