### ISSUE TITLE
[Wordpress] Disk is full over time 

### ISSUE THREAD

**Issue by Hocscreative** [bitnami/vms#210]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

20220802-053643-3101

### bndiagnostic output

I cannot find this in diagnostic tool. I only get zip files 

### bndiagnostic was not useful. Could you please tell us why?

I got a zip file which I can provide.

### Describe your issue as much as you can

Hi guys, 

I am not sure what happened to original Bitnami Forum :( I remember this issuer occurred to many others but I cannot find related issue anymore. 

Anyhow, I have problem with disk being too full and cannot start the site. I believe this has to do with plug in dumping log files or something along that line. 

You can see /dev/sda1 is being use 11G out of 12G 

Filesystem      Size  Used Avail Use% Mounted on
udev            286M     0  286M   0% /dev
tmpfs            60M  7.6M   52M  13% /run
/dev/sda1        12G   11G  966M  92% /
tmpfs           297M     0  297M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           297M     0  297M   0% /sys/fs/cgroup

**Comment by gongomgra** [comment]
Hi @Hocscreative,

Thanks for using Bitnami. I edited your issue title to meet the template. Regarding the Bitnami Community Forum, we moved from there last month. You can read more about this in our blogpost linked below

https://blog.bitnami.com/2022/06/we-have-moved-bitnami-support-to-github.html

Regarding the disk space issue, I was not able to check your bndiagnostic information as the code seems invalid. Can you please run the tool again and share the new code with us? From previous questions like this, we found out that usually there are some WordPress plugins using the database to store intermediate data, which causes a lots of MySQL events that get logged into the binlog files, making them very big. Can you check it?

**Comment by Hocscreative** [comment]
Umm.. I am not sure what to do because every time I run dianostic tool. It said upload to Bitnami Server failed.

_The diagnostic bundle file was successfully created, but the automatic upload to Bitnami servers failed. You will need to upload it to your Bitnami Support ticket manually. Please locate the following file in your file browser or in your terminal: /tmp/bitnami-wordpress-info-20220804-144337-26235.zip Exercise caution when uploading the resulting diagnostic bundle to public sites as it contains detailed diagnostic information._

Is there other way I can upload the zip file to you?

**Comment by gongomgra** [comment]
Hi @Hocscreative,

Did you have any chance to check the MySQL logs I mentioned in my previous message? You can follow the steps in the next link to share the bndiagnostic information with us if the automatic upload failed.

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/#manually-upload-the-bitnami-diagnostic-tool-bundle

**Comment by Hocscreative** [comment]
@gongomgra 

> Hi @Hocscreative,
> 
> Did you have any chance to check the MySQL logs I mentioned in my previous message? You can follow the steps in the next link to share the bndiagnostic information with us if the automatic upload failed.
> 
> https://docs.bitnami.com/general/how-to/understand-bndiagnostic/#manually-upload-the-bitnami-diagnostic-tool-bundle

Hi there, 

Thanks for the reply. I followed the guideline in your link but I cannot share Google drive link via Github direct message since there is none. However I invited you to my repo under [Hocscreative](https://github.com/Hocscreative)
/
[grandnewlife-diagnostics](https://github.com/Hocscreative/grandnewlife-diagnostics)

please accept.

**Comment by gongomgra** [comment]
Hi @Hocscreative,

Unfortunately, I can't accept it. Can you run the next command inside the information it generated? It will show you the MySQL binlog files and its size. From other similar tickets we had in the past, I think this can be causing your server to run out of disk space.

```
grep -i "binlog" permissions/mysql.permissions
```

**Comment by Hocscreative** [comment]
Hi, Unfortunately, I cannot unzip the bitnami-wordpress file on the server, there is no space left and I download it to windows. 
Do you have a windows command for that? 

Yes, I think it's the binlog files which I don't know where they are locate.

**Comment by gongomgra** [comment]
Hi @Hocscreative,

Thanks for the info. We recommend you to create a server backup before performing any change so you can easily restore the previous state

https://docs.bitnami.com/aws/faq/administration/backup-restore-server/

If binary files are using too much disk space, you can check the next guide on how to disable them. Notice there is also a link to the official MySQL docs on how to remove the current binary logs properly.
 
 https://docs.bitnami.com/aws/infrastructure/mysql/troubleshooting/disable-binary-logging-mysql/
