### ISSUE TITLE
System's temporary directory in UNKNOWN and Chmod warnings.

### ISSUE THREAD

**Issue by DanGoldsmith** [bitnami/vms#214]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a19c2c3d-d882-e346-3f02-cd3e3fd798db

### bndiagnostic output

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Aug 04 08:34:35.550651 2022] [proxy_fcgi:error] [pid 15135:tid 
139626501076736] [client **ip_address**:57920] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: 
https://crimecon-live.co.uk/wp-admin/admin.php?page=ai1wm_import
Press [Enter] to continue:
 [Thu Aug 04 08:39:43.628652 2022] [proxy_fcgi:error] [pid 15418:tid 
139626274473728] [client **ip_address**:58096] AH01071: Got error 'PHP message: 
PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173', referer: https://crimecon-live.co.uk/wp-admin/update-core.php
 [Thu Aug 04 08:39:45.854654 2022] [proxy_fcgi:error] [pid 15418:tid 
139626274473728] [client **ip_address**:58096] AH01071: Got error 'PHP message: 
PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in /opt/bitnami


[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Thu Aug 04 08:33:02.028771 2022] [proxy_fcgi:error] [pid 15418:tid 
Press [Enter] to continue:
139626568218368] [client **ip_address**:57893] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://crimecon-live.co.uk/wp-admin/plugin-install.php

### bndiagnostic was not useful. Could you please tell us why?

It is but I cant clear the warnings

### Describe your issue as much as you can

1) I have a 'temporary directory in Unknown warning' that I can't clear.
It's to do with a plugin I use to migrate my Wordpress sites called All In One Migration.

The site seems to have migrated successfully onto the AWS Lightsail platform, but I've no idea how to clear this apache warning about temporary directory unknown.
.
It's showing on both the Wordpress warnings and Apache warnings.

Finally there is a chmod warning.
I followed your online video to the letter!! and reset the wp-config.php after altering the permissions back to 664, so I don't know why I've got this warning anymore.

I followed these steps as shown...
sudo chown -R bitnami:daemon /opt/bitnami/wordpress
sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;
sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
sudo chmod 664 /opt/bitnami/wordpress/wp-config.php

**Comment by mdhont** [comment]
This error usually means there is no more room to write. Please check the available RAM:

    free -m 
    
I recommend upgrading the instance:

https://docs.bitnami.com/aws/faq/administration/change-server-type/

**Comment by DanGoldsmith** [comment]
I've upgraded my instance and I'm still seeing the same warning, after I have used the All-In-One-Migration plugin. 

1) Can I clear the apache warnings and re-test? If so how? 
2) Can I clear the Temporary Directory? If so how?

**Comment by mdhont** [comment]
Can you try resetting the permissions?

https://docs.bitnami.com/google/apps/wordpress/administration/understand-file-permissions/

**Comment by DanGoldsmith** [comment]
As requested, I re-wrote the permissions and did another All-In-One Migration again this morning.
Then checked the BN Testing Tool again and this is what I got;

Ticket Code
962ffff9-631e-5085-df31-239b7500bdd7

**APACHE**

**MESSAGE**
Found recent error or warning messages in the Apache error log.
```
[Mon Aug 22 07:29:39.611908 2022] [proxy_fcgi:error] [pid 17408:tid 
140566662723328] [client **ip_address**:54720] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://crimecon-live.co.uk/wp-admin/upload.php
 [Mon Aug 22 12:34:29.954707 2022] [proxy_fcgi:error] [pid 17410:tid 
Press [Enter] to continue:
140566352193280] [client **ip_address**:51368] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://crimecon-live.co.uk/wp-admin/upload.php
 [Tue Aug 23 05:23:09.502469 2022] [proxy_fcgi:error] [pid 27871:tid 
140566385764096] (70008)Partial results are valid but processing is incomplete: 
[client **ip_address**:51933] AH01075: Error dispatching request to : (reading 
input brigade)

```
Please check the following guide to troubleshoot server issues:

**RESOURCES**
I keep getting this message too, even though I've increased my Lightsail package, I CAN NOT need to go any bigger for the tiny site that I'm hosting here, I'm now on the second tier package at (2GB RAM and 60 GB SSD).

**MESSAGE**
Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1995 877 85 75 1032 879 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.

Can you look at this for me please and advise?

**Comment by mdhont** [comment]
The message

```
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: 
```

is just a notice, and it should not matter. There is another error:

```
 [Tue Aug 23 05:23:09.xxxxxxxx 2022] [proxy_fcgi:error] [pid 27871:tid 140xxxx64096] (70008)Partial results are valid but processing is incomplete: [client 11  xxxxxxxxx:51933] AH01075: Error dispatching request to : (reading input brigade)
```
You could try increasing the timeout for PHP scripts:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/modify-execution-time/
