### ISSUE TITLE
[Wordpress] Compatible with WP STAGING?

### ISSUE THREAD

**Issue by Lehmax** [bitnami/vms#215]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

not relevant

### bndiagnostic was not useful. Could you please tell us why?

bndiagnostic issues were not related to this (no swap file)

### Describe your issue as much as you can

Before migrating to Bitnami WP Staging would always show wp-content and I would be able to unselect it. Currently it's not visible, but the staging process still works.
![image](https://user-images.githubusercontent.com/8298953/182855161-2f29ff2f-65f8-4cc2-8fc6-268f2147d338.png)

**Comment by jotamartos** [comment]
Hi @Lehmax ,

Thank you for using our solution. That's a specific question about the application and the plugin so we suggest you ask in the official forums of the plugin to get more information about that. 

https://wordpress.org/support/plugin/wp-staging/

However, we will also keep this ticket open in this forum in case any Bitnami user knows how to migrate the data the way you want. We also suggest you check this guide with an alternative to migrate your site

https://docs.bitnami.com/aws/how-to/migrate-wordpress/

Thanks

**Comment by rene-hermenau** [comment]
This should been solved in latest version of wp staging. If not please open a support ticket on https://wp-staging.com/support/

Please also check:
https://wp-staging.com/docs/activate-permalinks-staging-site/#Bitnami_Apache
