### ISSUE TITLE
[WordPress Multisite] How to configure SSL Cert on WordPress Multi-Site hosted on AWS

### ISSUE THREAD

**Issue by GarDog555** [bitnami/vms#217]
### Describe your issue as much as you can

I am a Novice-- sorry.   This is not an issue with Bitnami, it's an issue with the user. 

I did search to see if this question was answered.  I found one post that was close, but most of what I read was over my head and was for a different host.   Any help would be appreciated. 

I am trying to add free SSL certs to my main domain and sites setup as subdomain sites.  (i.e. dellazanna.com and gary.dellazanna.com).  

I see/know it is not supported using the command "sudo /opt/bitnami/bncert-tool"

Is there a workaround for this?   If so, is there a simple-to-follow instructions to do it?

I would like to make a website for each family member, as a subdomain to my main site.   Not having an SSL cert scares people away.  

Thanks for your time reading this and any help/suggestions you offer. 

Gary DZ

**Comment by jotamartos** [comment]
>I see/know it is not supported using the command "sudo /opt/bitnami/bncert-tool"

What error do you get? If you have a WordPress Multisite solution running in the cloud, you can run the tool to generate one single certificate that is valid for all your domains. You just need to ensure all domains point to the instance's IP. 

However, if you have multiple VirtualHost in Apache and need multiple SSL certs, you can follow the alternative approach and configure those certificates in each VirtualHost

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by GarDog555** [comment]
Thanks for responding.  I will read the instruction you sent and try to learn/figure out what they are saying.  
I worked in MS DOS many years ago…(I am old enough that I had the 1st home IBM PC)  I still have not figured out the basic commands and structure used in Bitnami. 
  
I generally have no idea what the command is actually doing when I enter it in Bitnami.  

This is the warning I get:

Warning: Custom redirections are not supported in the WordPress Multisite 
packaged by Bitnami. This tool will not be able to enable/disable redirections.
Press [Enter] to continue:

It adds the Cert to main domain, but not the sub/daughter domains
gary.dellazanna.com

I ended up buying another domain for my daughter and running another lightsail instance to get rid of the SSL warning.  She is setting up a website as her resume, and our virus protection (BitDefender) gave a scary warning when going to the page.  

I would like to avoid that for everyone else in the family.  

Thanks for your time.   

I might be back with some more questions as I try to work through it.

Gary DZ

**Comment by GarDog555** [comment]
No rush for a response.  I know I am asking a lot of questions—sorry.

I understand if you are not able to respond to all of them.  I apricate your help.   

I am working off of the instructions you sent-- I Cut/Pasted sections from the instruction and put them in quotes, so you know where my question is in the article. 

RE: https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
Reminder, I have a Cert on the main domain already, if it matters. Used command:  sudo /opt/bitnami/bncert-tool
Do I need to revoke the current Cert?  If so, how?

I checked and I need to use “Approach A” for AWS and LightSail.

“If your Bitnami image does not include the auto-configuration script or the /opt/bitnami/letsencrypt/ directory”

I confirmed that I have that directory, so advancing to Step 2

Under Step 2 “NOTE: Before proceeding with this step, ensure that your domain name points to the public IP address of the Bitnami application host”

I have no idea how to ensure that the domain name points to the public IP address of the Bitnami application host.
Any advice on how to check (and/or edit).  I do not think the AWS basic hosting includes load balancer. 

           “Request a new certificate for your domain as below, both with and without the www prefix”
            “sudo /opt/bitnami/letsencrypt/lego --tls --email="EMAIL-ADDRESS" --domains="DOMAIN" --domains="www.DOMAIN" --path="/opt/bitnami/letsencrypt" run”

“NOTE: You can use more than one domain (for example, DOMAIN and www.DOMAIN) by specifying the --domains option as many times as the number of domains you want to specify. When supplying multiple domains, Lego creates a SAN (Subject Alternate Names) certificate which results in only one certificate valid for all domains you entered. The first domain in your list will be added as the “CommonName” of the certificate and the rest, will be added as “DNSNames” to the SAN extension within the certificate.

Is this where I would add the sub-domains/daughter domains? AND do I keep or delete the quotes around the domain names?
Example, would I use: 

sudo /opt/bitnami/letsencrypt/lego --tls --email="gary@xyz.com" --domains="dellazanna.com" --domains=”www.dellazanna.com” --domains=”gary.dellazanna.com” --path="/opt/bitnami/letsencrypt" run”

“An output message will provide some information, including the expiry date of the certificate. Note this expiry date carefully as you will need to renew your certificate before that date in order for it to remain valid.”

“Step 3 Configure The Web Server To Use The Let’s Encrypt Certificate”  
Link the new SSL certificate and certificate key file to the correct locations, depending on which Web server you’re using. Update the file permissions to make them readable by the root user only.

I am hosted on AWS, using LightSail.  I ran the command and this is using Apache.  

            “Step 5: Renew The Let’s Encrypt Certificate”
            “sudo /opt/bitnami/letsencrypt/lego --tls --email="EMAIL-ADDRESS" --domains="DOMAIN" --path="/opt/bitnami/letsencrypt" renew --days 90

Do I just include the main domain in this command or the list of daughter domains as well?  Should I also include a www.daughterdomain.domain for each?

            “To automatically renew your certificates before they expire, write a scrip…”
            “Create a script at /opt/bitnami/letsencrypt/scripts/renew-certificate.sh

“sudo mkdir -p /opt/bitnami/letsencrypt/scripts
“sudo nano /opt/bitnami/letsencrypt/scripts/renew-certificate.sh

Will this create the “file/script”, but not add anything to it?

Will this then write the lines of code/commands to the script?  I do not need to open an editor?

            “#!/bin/bash

            sudo /opt/bitnami/ctlscript.sh stop apache
            sudo /opt/bitnami/letsencrypt/lego --tls --email="EMAIL-ADDRESS" --domains="DOMAIN" --path="/opt/bitnami/letsencrypt" renew --days 90
            sudo /opt/bitnami/ctlscript.sh start apache”

Next it says 

            “Add the following lines to the crontab file and save it:”
            “0 0 1 * * /opt/bitnami/letsencrypt/scripts/renew-certificate.sh 2> /dev/null”

No idea how to do this?

“NOTE: If renewing multiple domains, remember to update the /opt/bitnami/letsencrypt/renew-certificate.sh script to include the additional domain name(s) in the lego command.”

Do I need to add all the domains in this script?  

Example, would I use:

“#!/bin/bash

            sudo /opt/bitnami/ctlscript.sh stop apache
sudo /opt/bitnami/letsencrypt/lego --tls --email="EMAIL-ADDRESS" --domains="dellazanna.com" --domains=”www.dellazanna.com” --domains=”gary.dellazanna.com”--path="/opt/bitnami/letsencrypt" renew --days 90
            sudo /opt/bitnami/ctlscript.sh start apache”

**Comment by jotamartos** [comment]
> This is the warning I get:
> 
> Warning: Custom redirections are not supported in the WordPress Multisite
> packaged by Bitnami. This tool will not be able to enable/disable redirections.
> Press [Enter] to continue:
> 
> It adds the Cert to main domain, but not the sub/daughter domains
> gary.dellazanna.com

This is just a warning. If you want to generate one single SSL cert for all your domains, you can "tell" the tool about your other domains so it generates a new one. 

>Do I need to revoke the current Cert? If so, how?

No, you do not need to do that if you want to have multiple SSL certs. In case you only want one single SSL certificate, you will need to revoke the cert and generate a new one with all your domains.

>I have no idea how to ensure that the domain name points to the public IP address of the Bitnami application host.

Ensure your domains point to the instance's IP address 

https://www.whatsmydns.net/

> Is this where I would add the sub-domains/daughter domains? AND do I keep or delete the quotes around the domain names?
> Example, would I use:
> 
> sudo /opt/bitnami/letsencrypt/lego --tls --email="[gary@xyz.com](mailto:gary@xyz.com)" --domains="dellazanna.com" --domains=”www.dellazanna.com” --domains=”gary.dellazanna.com” --path="/opt/bitnami/letsencrypt" run”

Correct! You can add all your domains and subdomains there


> Next it says
> 
>         “Add the following lines to the crontab file and save it:”
>         “0 0 1 * * /opt/bitnami/letsencrypt/scripts/renew-certificate.sh 2> /dev/null”
> No idea how to do this?

The documentation says the following 

Execute the following command to open the crontab editor:

```
sudo crontab -e
```

>Do I need to add all the domains in this script?

No, the first one is enough for Let's Encrypt to know the SSL cert you are trying to renew.

**Comment by GarDog555** [comment]
Thanks for all your help…

 

I screwed it up several times and almost gave up.  

 

I did get it to work for all of the subdomains and created the script to auto renew. 

 

I really could not have done it without your help. 

 

Thanks. 

 

Gary DZ

**Comment by jotamartos** [comment]
I'm glad to hear everything is working fine now! 

Enjoy! :)
