### ISSUE TITLE
[Wordpress NGINX] MySQL can't be started after Let's Encrypt renewal

### ISSUE THREAD

**Issue by DaDoni** [bitnami/vms#218]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

43b098da-8f61-9d4d-6501-e0feb4681f2b

### bndiagnostic output

no output available in console.

### bndiagnostic was not useful. Could you please tell us why?

not really. didn't provide any output.

### Describe your issue as much as you can

i didn't get any output. it only told me that the info would be uploaded to your server.

The problem: 
MySQL can't be started with the ctlscript.sh start command after i renewed the letsencrypt certificate.
Nginx and php-fpm work without a problem. 

I haven't figured out a way to diagnose mysql. 
Can you give me any instructions on how to figure this one out?

**Comment by gongomgra** [comment]
Hi @DaDoni,

Thanks for using Bitnami. I updated your ticket title to meet the requirements. Please have it into account for future issues.

You are using a very old version of the bndiagnostic tool. Can you download, install, and run the latest version? You can follow the steps described in the next guide. Remember to share with us the new code.

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/#run-the-bitnami-diagnostic-tool

I also found in the MySQL logs that your server is running out of disk space. Can you check it and also run the next commands on your server?

```
free -m
df -h
```
