### ISSUE TITLE
[wordpress] aws timezone php

### ISSUE THREAD

**Issue by GabiPerieteanu** [bitnami/vms#219]
### Describe your issue as much as you can

Hi,

I changed the timezone to Europe/Bucharest in opt/bitnami/php/etc/php.ini  but UTC still appears on the server
I ran the command sudo /opt/bitnami/ctlscript.sh restart

Can you tell me if it needs to be changed elsewhere?

Thx

**Comment by gongomgra** [comment]
Hi @danielpatulea,

Thanks for using Bitnami. Do you mean the date shown when running the `date` command on your server? If this is the case, you can update it with the `tzselect` command.

**Comment by danielpatulea** [comment]
> Hi @danielpatulea,
> 
> Thanks for using Bitnami. Do you mean the date shown when running the `date` command on your server? If this is the case, you can update it with the `tzselect` command.

**Comment by danielpatulea** [comment]
Hi @gongomgra

**Comment by gongomgra** [comment]
Hi @danielpatulea,

I'm afraid I can't reproduce your issue. I created a new `timezone.php` file in `/opt/bitnami/wordpress/timezone.php` with the next content

```
<?php
echo "Timezone is ". date_default_timezone_get() . "<br>";
?>
```

Then I visited the URL `http://my-ip-address/timezone.php` and it showed the `Timezone is UTC` message. After that, I edited the `php.ini` file like you did (only the `date.timezone` value), restarted PHP-FPM service (`sudo /opt/bitnami/ctlscript.sh restart php-fpm`) and reloading the webpage I see the message `Timezone is Europe/Bucharest` now.

![Screen Shot 2022-08-09 at 12 25 49](https://user-images.githubusercontent.com/6660452/183626211-2f0dc4e8-e445-421a-81f9-fa5222c00cc5.png)

Can you check it on your side? I didn't update any other configuration in the server. In fact, the system timezone is configured as UTC, but PHP is using Europe/Bucharest

```
$ date
Tue 09 Aug 2022 10:27:27 AM UTC
```

**Comment by danielpatulea** [comment]
Hi @gongomgra 

Approach B: Self-contained installation.

I tried as follows:
sudo find / -type f -name "php.ini"
/opt/bitnami/bnsupport/original-data/php/etc/php.ini
/opt/bitnami/php/etc/php.ini

I changed php.ini with Europe/Bucharest 
![image](https://user-images.githubusercontent.com/110666277/183655317-5ace226c-d103-4867-986b-0e14b08668ec.png)

restarted PHP-FPM service 
sudo /opt/bitnami/ctlscript.sh restart
sudo /opt/bitnami/ctlscript.sh restart php-fpm

![image](https://user-images.githubusercontent.com/110666277/183656198-68840104-7d6d-4a8c-b710-59f827cb44d4.png)

UTC also shows :(

**Comment by gongomgra** [comment]
Hi @danielpatulea,

Unfortunately, I was not able to reproduce your issue. I launched an old WordPress image configured with the approach B (using the `/opt/bitnami/apps/wordpress/htdocs` folder), and I was able to properly update PHP timezone following the steps in our guide. Maybe there is any other configuration or modification on your server causing this? Can you try using a fresh new server as I did?

**Comment by danielpatulea** [comment]
@gongomgra  I already did this, I created a new instance in aws(https://aws.amazon.com/marketplace/pp/prodview-bzstv3wbn5wkq), without installing anything on the server.  I modified the php.ini file with the new timezone, then I created a php page as a template for a wordpress page.
I created a wordpress page that I attached to the php temaplate page.
Unfortunately, it still doesn't work, UTC displays.
you can do the same thing and you will see that the change in php.ini does not work

**Comment by gongomgra** [comment]
Hi @GabiPerieteanu,

Did you try the steps I followed? I mean, not using WordPress but directly accessing the new PHP file. If you are having issues getting that information from WordPress, we recommend you to open a new question in WordPress official forums, as your issue can be related to how WordPress internally processes the timezone. Please check the next two related posts

* https://wordpress.org/support/topic/read-this-first-wordpress-5-3-master-list/#post-12124062
* https://wordpress.org/support/topic/how-to-set-blog-time-in-script-w-o-date_default_timezone_set/

Also find below the link to the official WordPress forums

https://wordpress.org/support/forums/
