### ISSUE TITLE
[WordPress] Sudo find /opt/bitnami/wordpress/ -type d SKIPS wp-content and subfolders?

### ISSUE THREAD

**Issue by agomezmoron** [bitnami/vms#22]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

137138cf-e02d-f255-3563-a3c86f3232d9

### bndiagnostic output

? Apache: Found possible issues
? Wordpress: Found possible issues
? Resources: Found possible issues
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-memory-linux/

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are not related with my issue

### Describe your issue as much as you can

(migrated from community.bitnami.com)

Long story short, I am wanting to re-set wordpress permissions to their safe and default.

Following the article here (https://docs.bitnami.com/general/apps/wordpress/administration/understand-file-permissions/), I applied those commands, specifically:
sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} ;

But I noticed that wp-content wasn’t being affected, so I simply ran sudo find /opt/bitnami/wordpress -type d to see what directories it was browsing and it completely skips wp-content and all its subfolders…

I don’t understand at all why this is not listing recursively all wp-content folders and subfolders. Here’s the output of the command:

/opt/bitnami/wordpress
/opt/bitnami/wordpress/licenses
/opt/bitnami/wordpress/wp-admin
/opt/bitnami/wordpress/wp-admin/network
/opt/bitnami/wordpress/wp-admin/css
/opt/bitnami/wordpress/wp-admin/css/colors
/opt/bitnami/wordpress/wp-admin/css/colors/blue
/opt/bitnami/wordpress/wp-admin/css/colors/sunrise
/opt/bitnami/wordpress/wp-admin/css/colors/coffee
/opt/bitnami/wordpress/wp-admin/css/colors/ocean
/opt/bitnami/wordpress/wp-admin/css/colors/light
/opt/bitnami/wordpress/wp-admin/css/colors/ectoplasm
/opt/bitnami/wordpress/wp-admin/css/colors/modern
/opt/bitnami/wordpress/wp-admin/css/colors/midnight
/opt/bitnami/wordpress/wp-admin/maint
/opt/bitnami/wordpress/wp-admin/includes
/opt/bitnami/wordpress/wp-admin/user
/opt/bitnami/wordpress/wp-admin/js
/opt/bitnami/wordpress/wp-admin/js/widgets
/opt/bitnami/wordpress/wp-admin/images
/opt/bitnami/wordpress/tmp
/opt/bitnami/wordpress/wp-includes
/opt/bitnami/wordpress/wp-includes/sitemaps
/opt/bitnami/wordpress/wp-includes/sitemaps/providers
/opt/bitnami/wordpress/wp-includes/customize
/opt/bitnami/wordpress/wp-includes/IXR
/opt/bitnami/wordpress/wp-includes/assets
/opt/bitnami/wordpress/wp-includes/random_compat
/opt/bitnami/wordpress/wp-includes/Requests
/opt/bitnami/wordpress/wp-includes/Requests/Proxy
/opt/bitnami/wordpress/wp-includes/Requests/Cookie
/opt/bitnami/wordpress/wp-includes/Requests/Auth
/opt/bitnami/wordpress/wp-includes/Requests/Transport
/opt/bitnami/wordpress/wp-includes/Requests/Utility
/opt/bitnami/wordpress/wp-includes/Requests/Exception
/opt/bitnami/wordpress/wp-includes/Requests/Exception/HTTP
/opt/bitnami/wordpress/wp-includes/Requests/Exception/Transport
/opt/bitnami/wordpress/wp-includes/Requests/Response
/opt/bitnami/wordpress/wp-includes/PHPMailer
/opt/bitnami/wordpress/wp-includes/sodium_compat
/opt/bitnami/wordpress/wp-includes/sodium_compat/lib
/opt/bitnami/wordpress/wp-includes/sodium_compat/src
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core32
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core32/ChaCha20
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core32/SecretStream
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core32/Poly1305
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core32/Curve25519
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core32/Curve25519/Ge
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core/Base64
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core/ChaCha20
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core/SecretStream
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core/Poly1305
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core/Curve25519
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/Core/Curve25519/Ge
/opt/bitnami/wordpress/wp-includes/sodium_compat/src/PHP52
/opt/bitnami/wordpress/wp-includes/sodium_compat/namespaced
/opt/bitnami/wordpress/wp-includes/sodium_compat/namespaced/Core
/opt/bitnami/wordpress/wp-includes/sodium_compat/namespaced/Core/ChaCha20
/opt/bitnami/wordpress/wp-includes/sodium_compat/namespaced/Core/Poly1305
/opt/bitnami/wordpress/wp-includes/sodium_compat/namespaced/Core/Curve25519
/opt/bitnami/wordpress/wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge
/opt/bitnami/wordpress/wp-includes/ID3
/opt/bitnami/wordpress/wp-includes/rest-api
/opt/bitnami/wordpress/wp-includes/rest-api/search
/opt/bitnami/wordpress/wp-includes/rest-api/fields
/opt/bitnami/wordpress/wp-includes/rest-api/endpoints
/opt/bitnami/wordpress/wp-includes/css
/opt/bitnami/wordpress/wp-includes/css/dist
/opt/bitnami/wordpress/wp-includes/css/dist/components
/opt/bitnami/wordpress/wp-includes/css/dist/edit-widgets
/opt/bitnami/wordpress/wp-includes/css/dist/block-library
/opt/bitnami/wordpress/wp-includes/css/dist/format-library
/opt/bitnami/wordpress/wp-includes/css/dist/editor
/opt/bitnami/wordpress/wp-includes/css/dist/nux
/opt/bitnami/wordpress/wp-includes/css/dist/widgets
/opt/bitnami/wordpress/wp-includes/css/dist/list-reusable-blocks
/opt/bitnami/wordpress/wp-includes/css/dist/customize-widgets
/opt/bitnami/wordpress/wp-includes/css/dist/reusable-blocks
/opt/bitnami/wordpress/wp-includes/css/dist/block-directory
/opt/bitnami/wordpress/wp-includes/css/dist/edit-post
/opt/bitnami/wordpress/wp-includes/css/dist/block-editor
/opt/bitnami/wordpress/wp-includes/blocks
/opt/bitnami/wordpress/wp-includes/blocks/buttons
/opt/bitnami/wordpress/wp-includes/blocks/list
/opt/bitnami/wordpress/wp-includes/blocks/quote
/opt/bitnami/wordpress/wp-includes/blocks/site-logo
/opt/bitnami/wordpress/wp-includes/blocks/table
/opt/bitnami/wordpress/wp-includes/blocks/legacy-widget
/opt/bitnami/wordpress/wp-includes/blocks/latest-comments
/opt/bitnami/wordpress/wp-includes/blocks/post-content
/opt/bitnami/wordpress/wp-includes/blocks/query-title
/opt/bitnami/wordpress/wp-includes/blocks/query-pagination-numbers
/opt/bitnami/wordpress/wp-includes/blocks/freeform
/opt/bitnami/wordpress/wp-includes/blocks/verse
/opt/bitnami/wordpress/wp-includes/blocks/post-terms
/opt/bitnami/wordpress/wp-includes/blocks/social-link
/opt/bitnami/wordpress/wp-includes/blocks/gallery
/opt/bitnami/wordpress/wp-includes/blocks/heading
/opt/bitnami/wordpress/wp-includes/blocks/code
/opt/bitnami/wordpress/wp-includes/blocks/post-title
/opt/bitnami/wordpress/wp-includes/blocks/pullquote
/opt/bitnami/wordpress/wp-includes/blocks/more
/opt/bitnami/wordpress/wp-includes/blocks/post-template
/opt/bitnami/wordpress/wp-includes/blocks/site-title
/opt/bitnami/wordpress/wp-includes/blocks/media-text
/opt/bitnami/wordpress/wp-includes/blocks/categories
/opt/bitnami/wordpress/wp-includes/blocks/paragraph
/opt/bitnami/wordpress/wp-includes/blocks/site-tagline
/opt/bitnami/wordpress/wp-includes/blocks/embed
/opt/bitnami/wordpress/wp-includes/blocks/query
/opt/bitnami/wordpress/wp-includes/blocks/post-date
/opt/bitnami/wordpress/wp-includes/blocks/column
/opt/bitnami/wordpress/wp-includes/blocks/calendar
/opt/bitnami/wordpress/wp-includes/blocks/loginout
/opt/bitnami/wordpress/wp-includes/blocks/group
/opt/bitnami/wordpress/wp-includes/blocks/query-pagination
/opt/bitnami/wordpress/wp-includes/blocks/html
/opt/bitnami/wordpress/wp-includes/blocks/button
/opt/bitnami/wordpress/wp-includes/blocks/audio
/opt/bitnami/wordpress/wp-includes/blocks/search
/opt/bitnami/wordpress/wp-includes/blocks/page-list
/opt/bitnami/wordpress/wp-includes/blocks/columns
/opt/bitnami/wordpress/wp-includes/blocks/spacer
/opt/bitnami/wordpress/wp-includes/blocks/social-links
/opt/bitnami/wordpress/wp-includes/blocks/text-columns
/opt/bitnami/wordpress/wp-includes/blocks/post-featured-image
/opt/bitnami/wordpress/wp-includes/blocks/shortcode
/opt/bitnami/wordpress/wp-includes/blocks/nextpage
/opt/bitnami/wordpress/wp-includes/blocks/tag-cloud
/opt/bitnami/wordpress/wp-includes/blocks/latest-posts
/opt/bitnami/wordpress/wp-includes/blocks/query-pagination-previous
/opt/bitnami/wordpress/wp-includes/blocks/query-pagination-next
/opt/bitnami/wordpress/wp-includes/blocks/image
/opt/bitnami/wordpress/wp-includes/blocks/missing
/opt/bitnami/wordpress/wp-includes/blocks/block
/opt/bitnami/wordpress/wp-includes/blocks/separator
/opt/bitnami/wordpress/wp-includes/blocks/cover
/opt/bitnami/wordpress/wp-includes/blocks/preformatted
/opt/bitnami/wordpress/wp-includes/blocks/post-excerpt
/opt/bitnami/wordpress/wp-includes/blocks/rss
/opt/bitnami/wordpress/wp-includes/blocks/video
/opt/bitnami/wordpress/wp-includes/blocks/archives
/opt/bitnami/wordpress/wp-includes/blocks/file
/opt/bitnami/wordpress/wp-includes/pomo
/opt/bitnami/wordpress/wp-includes/block-patterns
/opt/bitnami/wordpress/wp-includes/fonts
/opt/bitnami/wordpress/wp-includes/Text
/opt/bitnami/wordpress/wp-includes/Text/Diff
/opt/bitnami/wordpress/wp-includes/Text/Diff/Engine
/opt/bitnami/wordpress/wp-includes/Text/Diff/Renderer
/opt/bitnami/wordpress/wp-includes/widgets
/opt/bitnami/wordpress/wp-includes/certificates
/opt/bitnami/wordpress/wp-includes/js
/opt/bitnami/wordpress/wp-includes/js/jquery
/opt/bitnami/wordpress/wp-includes/js/jquery/ui
/opt/bitnami/wordpress/wp-includes/js/mediaelement
/opt/bitnami/wordpress/wp-includes/js/mediaelement/renderers
/opt/bitnami/wordpress/wp-includes/js/imgareaselect
/opt/bitnami/wordpress/wp-includes/js/thickbox
/opt/bitnami/wordpress/wp-includes/js/codemirror
/opt/bitnami/wordpress/wp-includes/js/tinymce
/opt/bitnami/wordpress/wp-includes/js/tinymce/themes
/opt/bitnami/wordpress/wp-includes/js/tinymce/themes/modern
/opt/bitnami/wordpress/wp-includes/js/tinymce/themes/inlite
/opt/bitnami/wordpress/wp-includes/js/tinymce/utils
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/lists
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/directionality
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/media
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/paste
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/wordpress
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/wpautoresize
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/wpemoji
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/textcolor
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/wpeditimage
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/compat3x
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/compat3x/css
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/wpdialogs
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/wptextpattern
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/tabfocus
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/fullscreen
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/hr
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/charmap
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/image
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/wplink
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/colorpicker
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/wpview
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/link
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/wpgallery
/opt/bitnami/wordpress/wp-includes/js/tinymce/skins
/opt/bitnami/wordpress/wp-includes/js/tinymce/skins/wordpress
/opt/bitnami/wordpress/wp-includes/js/tinymce/skins/wordpress/images
/opt/bitnami/wordpress/wp-includes/js/tinymce/skins/lightgray
/opt/bitnami/wordpress/wp-includes/js/tinymce/skins/lightgray/img
/opt/bitnami/wordpress/wp-includes/js/tinymce/skins/lightgray/fonts
/opt/bitnami/wordpress/wp-includes/js/tinymce/langs
/opt/bitnami/wordpress/wp-includes/js/crop
/opt/bitnami/wordpress/wp-includes/js/swfupload
/opt/bitnami/wordpress/wp-includes/js/jcrop
/opt/bitnami/wordpress/wp-includes/js/dist
/opt/bitnami/wordpress/wp-includes/js/dist/vendor
/opt/bitnami/wordpress/wp-includes/js/plupload
/opt/bitnami/wordpress/wp-includes/SimplePie
/opt/bitnami/wordpress/wp-includes/SimplePie/Parse
/opt/bitnami/wordpress/wp-includes/SimplePie/Content
/opt/bitnami/wordpress/wp-includes/SimplePie/Content/Type
/opt/bitnami/wordpress/wp-includes/SimplePie/Cache
/opt/bitnami/wordpress/wp-includes/SimplePie/Decode
/opt/bitnami/wordpress/wp-includes/SimplePie/Decode/HTML
/opt/bitnami/wordpress/wp-includes/SimplePie/HTTP
/opt/bitnami/wordpress/wp-includes/SimplePie/Net
/opt/bitnami/wordpress/wp-includes/SimplePie/XML
/opt/bitnami/wordpress/wp-includes/SimplePie/XML/Declaration
/opt/bitnami/wordpress/wp-includes/theme-compat
/opt/bitnami/wordpress/wp-includes/images
/opt/bitnami/wordpress/wp-includes/images/crystal
/opt/bitnami/wordpress/wp-includes/images/media
/opt/bitnami/wordpress/wp-includes/images/smilies
/opt/bitnami/wordpress/wp-includes/images/wlw
/opt/bitnami/wordpress/wp-includes/block-supports
/opt/bitnami/wordpress/mic_media
/opt/bitnami/wordpress/mic_media/et_temp
/opt/bitnami/wordpress/mic_media/sb-instagram-feed-images
/opt/bitnami/wordpress/mic_media/2019
/opt/bitnami/wordpress/mic_media/2019/09
/opt/bitnami/wordpress/mic_media/2019/04
/opt/bitnami/wordpress/mic_media/2019/07
/opt/bitnami/wordpress/mic_media/2019/10
/opt/bitnami/wordpress/mic_media/2019/06
/opt/bitnami/wordpress/mic_media/2019/08
/opt/bitnami/wordpress/mic_media/wpforms
/opt/bitnami/wordpress/mic_media/formidable
/opt/bitnami/wordpress/mic_media/formidable/4
/opt/bitnami/wordpress/mic_media/formidable/1
/opt/bitnami/wordpress/mic_media/formidable/2
/opt/bitnami/wordpress/mic_media/essential-grid
/opt/bitnami/wordpress/mic_media/essential-grid/templates
/opt/bitnami/wordpress/mic_media/alm_templates

Where is the wp-content stuff?!

**Comment by srakl** [comment]
> Here’s is what I am thinking for the final solution, correct?
> 
> ```
> sudo chown -R bitnami:daemon /opt/bitnami/wordpress
> sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
> sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;
> sudo chown -R bitnami:daemon /bitnami/wordpress
> sudo find /bitnami/wordpress -type d -exec chmod 775 {} \;
> sudo find /bitnami/wordpress -type f -exec chmod 664 {} \;
> sudo chmod 640 /bitnami/wordpress/wp-config.php
> ```

this didn't work for me. i still can't update plugins and themes. My directories are also `/opt/bitnami/wordpress`

**Comment by jotamartos** [comment]
Hi @srakl,

Please create a new issue in this repository instead of using this closed one. Once the ticket is created, the team will start checking your issue and why these commands didn't work for you. 

Thanks

**Comment by vadorvatsal** [comment]
> Here’s is what I am thinking for the final solution, correct?
> 
> ```
> sudo chown -R bitnami:daemon /opt/bitnami/wordpress
> sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
> sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;
> sudo chown -R bitnami:daemon /bitnami/wordpress
> sudo find /bitnami/wordpress -type d -exec chmod 775 {} \;
> sudo find /bitnami/wordpress -type f -exec chmod 664 {} \;
> sudo chmod 640 /bitnami/wordpress/wp-config.php
> ```

This solved my issue.
