### ISSUE TITLE
[WordPress with NGINX and SSL] Mariadb/php-fpm/nginx Crashes

### ISSUE THREAD

**Issue by gunterk1** [bitnami/vms#220]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0b22a8d3-64c8-f3ac-2443-3b8886318f0f

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ✓ Php: No issues found
    ? Nginx: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 16011 12738 1210 151 2062 2791 
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Wordpress]

Found recent WordPress plugin related error messages in the Nginx error log.
```
2022/08/04 16:53:09 [error] 2773#2773: *485 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "POST 
//wp-content/plugins/mm-plugin/inc/vendors/vendor/phpunit/phpunit/src/Util/PHP/ev
al-stdin.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "35.246.192.82", 
referrer: "https://www.google.com/"

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

Press [Enter] to continue:
[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2022/08/05 08:20:54 [error] 12035#12035: *173 access forbidden by rule, client: 
**ip_address**, server: _, request: "GET /.env HTTP/1.1", host: "35.246.192.82"
 2022/08/05 08:52:38 [error] 12035#12035: *214 access forbidden by rule, client: 
**ip_address**, server: _, request: "GET /.env HTTP/1.1", host: "35.246.192.82"
 2022/08/05 09:31:27 [error] 12035#12035: *308 FastCGI sent in stderr: "PHP 
message: PHP Notice: Function is_page was called <strong>incorrectly</strong>. 
Conditional query tags do not work before the query is run. Before then, they 
always return false. Please see <a 
href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging 
in WordPress</a> for more information. (This message was added in version 
3.1.0.) in /opt/bitnami/wordpress/wp-includes/functions.php on line 5831PHP mes
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

### bndiagnostic was not useful. Could you please tell us why?

The presented error messages aren*t specific enough.

### Describe your issue as much as you can

Hey there.

this exact wordpress installation is running on older bitnami WordPress with NGINX and SSL instances very stabel. The used RAM should be enough I have studied the mariadb log and the nginx error log and can't find any related problem.

Sometimes madiadb crahses alone, some times the php processes crash too.

Very strange behaviour. Maybe you can help?

Thanks, Gunter

**Comment by gunterk1** [comment]
It seems that is a cronjob problem inside wordpress. when I stop the wordpress cron infrastructure from processing the crashes stop.

the error messages from the log are a little bit misguiding. the mm-plugin isn't installed at all. I will continue my research....

thanks

**Comment by gunterk1** [comment]
Hey Jota,
the cron processes aren't the problem, It is still the same behaviour, the processes are spontaniously crashing.
Now I deactivated all wordpress plugins and still the crashes are happening.

Do you have any suggestions?

thanks, Gunter

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.

**Comment by gunterk1** [comment]
Hey mdhont, 

after an huge amount of research I found yesterday the misconfiguration in php-fpm.

After swichting from pm=dynamic to pm=ondemand I can hold the memorydemand  in check and my application runs stable.

Bye, gunter
