### ISSUE TITLE
[Alfresco] Error apache AH00957 and AH00896 after restarting services Alfresco

### ISSUE THREAD

**Issue by faviancab** [bitnami/vms#222]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

19d76f4c-ab8e-7ea7-3890-d6243b9fdcde

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Aug 07 15:38:32.334400 2022] [proxy:error] [pid 6961:tid 139859875702528]
(111)Connection refused: AH00957: AJP: attempt to connect to **ip_address**:8009
(localhost:8009) failed

[Sun Aug 07 15:38:32.334462 2022] [proxy_ajp:error] [pid 6961:tid
139859875702528] [client **ip_address**:57981] AH00896: failed to make
connection to backend: localhost
Press [Enter] to continue:}

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

### bndiagnostic was not useful. Could you please tell us why?

the suggested guide does not solve my problem

### Describe your issue as much as you can

Best regard

I have deployed alfresco community 7.2.0-8-r01 on Debian 11 packaged by Bitnami, after running sudo /opt/bitnami/ctlscript.sh stop and sudo /opt/bitnami/ctlscript.sh start I got this error.

in the graphical interface I see other errors which I think are related to the Apache error

![error_alfresco_1](https://user-images.githubusercontent.com/110710997/183302595-2984fb48-0b3f-46ff-8c7a-2b850964b936.jpg)

**Comment by jotamartos** [comment]
Hi @faviancab,

Thank you for using our solution. Please note that the services take some time to be fully available. Are you sure Tomcat finished deploying the app after restarting the server? I can see the process is running so there shouldn't be any issue 

```
solr        8495  6.6  5.6 3666172 454332 ?      Sl   15:38   0:29 /opt/bitnami/java/bin/java -server -Xms1g -Xmx1g -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+            UseConcMarkSweepGC -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:                      CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:-OmitStackTraceInFastThrow -Xlog:gc*:file=/opt/bitnami/alfresco-search-services/logs/solr_gc.log:time,uptime:filecount=9,      filesize=20000 -Dsolr.log.dir=/opt/bitnami/alfresco-search-services/logs -Djetty.port=8983 -DSTOP.PORT=7983 -DSTOP.KEY=solrrocks -Duser.timezone=UTC -Djetty.home=/opt/bitnami/alfresco-search-services/solr/server -Dsolr.   solr.home=/opt/bitnami/alfresco-search-services/solr/../solrhome -Dsolr.install.dir=/opt/bitnami/alfresco-search-services/solr -Dlog4j.configuration=file:/opt/bitnami/alfresco-search-services/log4j.properties -Dsolr.jetty.request.header.size=1000000 -Dsolr.jetty.threads.stop.timeout=300000 -Ddisable.configEdit=true -Xss256k -Dalfresco.secureComms=secret -Dalfresco.secureComms.                                                                 secret=ec61c912dcfe930fc088582d30e4a83882e4f947cba55148c7c90089fa2ff969 -Dsolr.log.muteconsole -XX:OnOutOfMemoryError=/opt/bitnami/alfresco-search-services/solr/bin/oom_solr.sh 8983 /opt/bitnami/alfresco-search-services/  logs -jar start.jar --module=http
```

Apart from that, all services are up and running 

```
-----------------------------------
Get the ctlscript status
-----------------------------------
Running: ./ctlscript.sh status
In: /opt/bitnami

Output:

activemq already running
alfresco-search-services already running
alfresco-transform-core already running
apache already running
mariadb already running
tomcat already running
```

This seems to be a specific issue about the application so we suggest you ask in the official forums of the application to get more information about that. The app's documentation should also describe how to troubleshoot this, so please take a look at it too. 

However, we will also keep this ticket open in case any Bitnami user ran into a similar issue recently.

Thanks

**Comment by faviancab** [comment]
Hello friends

I have restarted the **alfresco-search-services** process after a few minutes I see that it has returned to normal.

   _$ sudo /opt/bitnami/ctlscript.sh restart alfresco-search-services_

best regards
