### ISSUE TITLE
[WordPress multisite] How to get the list of managed SSL domains?

### ISSUE THREAD

**Issue by vporton** [bitnami/vms#223]
### Describe your issue as much as you can

It is not clear how to get the list of domain with managed (by `bncert-tool`) SSL certificates for a Bitnami Multisite WordPress image.

**Comment by jotamartos** [comment]
The HTTPS configuration tool just generates valid SSL certs and configure them in your instance. If you want to know the domains that are included in your certificate, please open the certificate information in your website by using your browser.
