### ISSUE TITLE
[Wordpress] How to delete a Child-Theme folder using Fillezilla or PuttY

### ISSUE THREAD

**Issue by Surioxy** [bitnami/vms#224]
### Describe your issue as much as you can

Hello,

I think my problem is a bit similar to this one "Files uploading as daemon:daemon" but in my case, I have created a child theme (of DIVI) but I can't delete it. (it is also displayed as daemon:daemon)

It shows me : rm /bitnami/wordpress/wp-content/themes/Divi-child/functions.php: permission denied
(and same error for style.css etc etc...)

I don't really understand why since it's a child theme that I created myself

PS : I also have a problem where some extensions like "Really simple ssl" tell me that "The wp-config.php (or .htaccess) file is not writable" when normally it's supposed to be good since the permissions are "644"
(Sorry for the bad english, it's translated from french)

**Comment by gongomgra** [comment]
Hi @Surioxy,

You can remove the files prepending the `sudo` command, as bitnami user has the option of running commands with higher privileges on the server. Regarding the plugin and the wp-config.php permissions, we highly recommend you to open a new question in the official WordPress forums or in the plugin support platform

https://wordpress.org/support/forums/
