### ISSUE TITLE
[WordPress] Website goes down on a 160$ lightsail instance with small amount of traffic

### ISSUE THREAD

**Issue by minasgadalla** [bitnami/vms#225]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5b1b0d40-c9b2-c4c9-9187-59ea405776d9

### bndiagnostic output

    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Could resolve the issues using the documentation provided

### Describe your issue as much as you can

On an AWS LightSail 160$ instance where I'm running a WordPress website, I've seen that with fewer than 600 people over the course of two hours, the website became unusable and laggy. The following optimization measures have been carried out before the incidence, but it doesn't appear to have made any difference. On 7/8/22 @4pm server time, the CPU reached 23% (burstable zone) during that busy period, and when it returned to sustainable mode, the instance required a restart to resume normally. This is not the first time happening.

memory.conf file in /opt/bitnami/php/etc (i have doubled the default numbers)
```
pm.max_children=800
pm.start_servers=520
pm.min_spare_servers=520
pm.max_spare_servers=600
pm.max_requests=0
```

The reason I did that is because I saw on the php-fpm logs file the following message:
`... WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are ... `
However the message error still occurs more frequently.

www.conf in /opt/bitnami/php/etc/php-fpm.d
```
pm=dynamic
pm.max_children = 800
pm.min_spare_servers = 35
pm.max_requests = 0
```
Did I modify the correct files?

In the php.ini (to resolve the timeout errors)
```
max_execution_time = 1500
max_input_time  = 1500
```
In addition, I recently added 32GB of swap space to expand the RAM. However, the performance hasn't improved.

The website uses Cloudflare as a CDN and thus I have managed to block most of the bad traffic and do some page optimization, which really helped.

**Comment by ospf2fullstack** [comment]
I have similar behavior. Apache restart usually resolves it for a few weeks, but it's becoming more frequent.

**Comment by ospf2fullstack** [comment]
> I have similar behavior. Apache restart usually resolves it for a few weeks, but it's becoming more frequent.

Searched the repo for what I believe my issue will be (sorry, getting a hang of the new community). [I increased my swap to match my system RAM size](https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-memory-linux/). 

I'll report back in a few weeks if it happens again.

**Comment by gongomgra** [comment]
Hi @minasgadalla,

Thanks for using Bitnami. According to our docs, yes, you updated the right files. Did you also restart the services after that for changes to take effect? I'm sharing our guide on configuring PHP-FPM below for reference

https://docs.bitnami.com/aws/apps/wordpress/configuration/configure-phpfpm-options/

Apart from that, Lightsail instances are of type burstable, which usually don't perform well under high traffic situations. You can read more about this [in the official docs](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-frequently-asked-questions-faq#amazon-lightsail-faq-instances). We also recommend you to ask in the official Lightsail forums for further help on how to debug the performance of the instance.

**Comment by nccerhostmaster** [comment]
Lightsail instances can have problems specific to the hardware they are running on.
If that's the case, then creating a snapshot and deploying it to a new instance could help. 
Create the new instance in a different availability zone.
If that doesn't make any difference, then the problem is likely with your Wordpress environment.

**Comment by ax0n-pr1me** [comment]
I have the same issue, my diagnostic output is only showing apache errors however... happened July 29th/30th and again August 15th. did not come back up on it's own the last time but did after I ran the diagnostic tool. 

```
===== Begin of bndiagnostic tool output =====
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.

[Mon Aug 15 22:33:33.115397 2022] [proxy_fcgi:error] [pid 32236:tid
140279981950720] (70007)The timeout specified has expired: [client
**ip_address**:40480] AH01075: Error dispatching request to :25565: (polling)
 [Mon Aug 15 22:33:48.269200 2022] [proxy_fcgi:error] [pid 1009:tid
140280292415232] (70007)The timeout specified has expired: [client
Press [Enter] to continue:
**ip_address**:33052] AH01075: Error dispatching request to :25565: (polling)
 [Mon Aug 15 22:33:54.449150 2022] [proxy_fcgi:error] [pid 1156:tid
140280007096064] (70007)The timeout specified has expired: [client
**ip_address**:39120] AH01075: Error dispatching request to :25565: (polling)


Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====
```

**Comment by ospf2fullstack** [comment]
Unfortunately, after following other online documentation to tshoot this issue, including my most recent solution to increase the swap file; I'm still having the issue where apache needs to be restarted for my site to come back online. 

My instance is using less than 0.1% of it's allocated resources at any moment, with periodic jumps to 10%; but that's completely at random, and doesn't appear to be at the times that apache freaks out. 

Performing apache log searches returns no entries.

**Comment by ax0n-pr1me** [comment]
same. Very little traffic when this issue is occurring.  currently testing this... 

### Update Apache `httpd.conf`

`vim /opt/bitnami/apache/conf/httpd.conf`

and aded

```{sh}
Timeout 600
ProxyTimeout 600
```

derived from the following links
<https://stackoverflow.com/a/46798562>
<https://docs.bitnami.com/installer/infrastructure/wamp/get-started/understand-config/>
<https://stackoverflow.com/questions/65860077/how-to-restore-apache-configuration-file-in-bitnami>
```

**Comment by ospf2fullstack** [comment]
One thing I'm noticing in my apache_log file are 100's xmlrpc.php requests periodically

**Comment by gongomgra** [comment]
Hi,

As I mentioned in my previous message, these issues could be related to the AWS Lightsail instances itself. We recommend you to open a new question in the official Lightsail support channels for further help on how to troubleshoot those instances performance.

@ospf2fullstack you may be under a bot attack, please check https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/

**Comment by minasgadalla** [comment]
> Hi @minasgadalla,
> 
> Thanks for using Bitnami. According to our docs, yes, you updated the right files. Did you also restart the services after that for changes to take effect? I'm sharing our guide on configuring PHP-FPM below for reference
> 
> https://docs.bitnami.com/aws/apps/wordpress/configuration/configure-phpfpm-options/
> 
> Apart from that, Lightsail instances are of type burstable, which usually don't perform well under high traffic situations. You can read more about this [in the official docs](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-frequently-asked-questions-faq#amazon-lightsail-faq-instances). We also recommend you to ask in the official Lightsail forums for further help on how to debug the performance of the instance.

Yes, I rebooted the instance after the changes.  AWS support checked the health of the instance and didn't find any issues from their side.

Recently I did some configuration to Cloudflare and to the apache settings which lead to fewer redirections, and increased page time speed.

a) Installed an Lets Encrypt SSL using the bitnami tool with the following settings:
```
Enable HTTP to HTTPS redirection [Y/n]: Y
Enable non-www to www redirection [Y/n]: N
Enable www to non-www redirection [y/N]: Y
```
Usually, the main website is the one without the www in the prefix, so redirecting non-www to www is useless and leads to many redirections without reason.
After having that set-up I changed the SSL encryption type in Cloudflare to `Full Strict`

Before that I was using only cloudflare's SSL.

b) in the config file` /opt/bitnami/apache/conf/bitnami/bitnami.conf `
I replaced the line
`RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]`
with 
`RewriteRule ^/(.*) https://mydomain.com/$1 [R=301,L]`

Now all the requests are being redirected to the main domain without any prefix and every http request is transformed to https

Note: If you are using Cloudflare consider turning off the "Always use HTTPS"  as with this setup is not necessary.

c) set the `max_input_time `and `max_execution_time `to 300. 
Note: I noticed, having a high value on `max_input_time  `may lead to `Too many open files in system ..` errors.  So ,depending on your setup and application you should set these settings accordingly.

After these changes, the overall speed and health have improved.
However, in the php-fpm log file I can still see the `max_children `warming. Any help on that?

The new bitnami bundle id is:  `bf81342f-a891-ab46-516f-6b1c20f78a2f`

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.

**Comment by minasgadalla** [comment]
Here's something that will likely save you time if you've witnessed the same behavior on your bitanmi wordpress application. 

First of all, Lightsail is not intended to be used for production websites but rather for development websites. So if you are using Lightsail, consider moving to EC2.

Secondly, as most WordPress websites are dependent on many plugins over which we have no control and can execute stuff in a non-optimized way, I recommend changing the `pm.type` to `static` and finding the appropriate number for `pm.max_children`  by dividing the RAM you want to allocate by the average php-fpm usage memory.

After those changes you should monitor the CPU, RAM, avg php-fpm ram usage, and notice if you have any memory leaks

https://github.com/bitnami/vms/issues/248

**Comment by gongomgra** [comment]
Hi @minasgadalla,

Thanks for your message. We hope your website works better in an EC2 instance. As you mentioned, and was also mentioned in a [previous comment](https://github.com/bitnami/vms/issues/225#issuecomment-1209210022), Lightsail instances are burstable instances, which don't perform well for production environments.

We are closing this ticket as solved.
