### ISSUE TITLE
[wordpress] Unable to access website use to critical error

### ISSUE THREAD

**Issue by itsmemidhuz123** [bitnami/vms#226]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

67ecab11-bc90-ba63-46a1-8071ad63060a

### bndiagnostic output

Found recent error or warning messages in the Apache error log.
```
[Mon Aug 08 16:33:17.742630 2022] [proxy_fcgi:error] [pid 1019:tid
140681813042944] [client **ip_address**:38572] AH01071: Got error 'PHP message:
PHP Fatal error: Uncaught Error: Call to undefined function create_function() in
/bitnami/wordpress/wp-content/themes/hello-elementor/functions.php:10
Stack trace:
#0 /opt/bitnami/wordpress/wp-settings.php(566): include()
#1 /bitnami/wordpress/wp-config.php(190): require_once('...')
#2 /opt/bitnami/wordpress/wp-load.php(50): require_once('...')
#3 [Mon Aug 08 16:33:23.557590 2022] [proxy_fcgi:error] [pid 1019:tid
140682140059392] [client **ip_address**:38246] AH01071: Got error 'PHP message:
PHP Fatal error: Uncaught Error: Call to undefined function create_function() in
/bitnami/wordpress/wp-content/themes/hello-elementor/functions.php:10
Stack trace:
#0 /opt/bitnami/wordpress/wp-settings.php(566): include()
#1 /bitnami/wordpress/wp-config.php(190): require_once('...')
#2 /opt/bitnami/wordpress/wp-load.php(50): require_once('...')
 [Mon Aug 08 16:33:54.792151 2022] [proxy_fcgi:error] [pid 1019:tid
140681779472128] [client **ip_address**:16586] AH01071: Got error 'PHP message:
Press [Enter] to continue:
PHP Fatal error: Uncaught Error: Call to undefined function create_function() in
/bitnami/wordpress/wp-content/themes/hello-elementor/functions.php:10
Stack trace:
#0 /opt/bitnami/wordpress/wp-settings.php(566): include()
#1 /bitnami/wordpress/wp-config.php(190): require_once('...')
#2 /opt/bitnami/wordpress/wp-load.php(50): require_once('...')
```

### bndiagnostic was not useful. Could you please tell us why?

could find the issue

### Describe your issue as much as you can

unable to find the issue, unable to deactivate the plugin through putty as well
texcads.com

**Comment by gongomgra** [comment]
Hi @itsmemidhuz123,

Thanks for using Bitnami. There seems to be an error with you custom theme more than with the Bitnami installation itself. I don't know if this error will cause the `wp` command-line tool to also fail, so please open a new question in the official theme forums or WordPress support forums for further help on how to disable it.

https://wordpress.org/support/forums/

**Comment by itsmemidhuz123** [comment]
sure let me try it out and let you know

**Comment by itsmemidhuz123** [comment]
seems like when i updated the elementor yesterday it came. May i can try this by deleting the plugin from FileZilla but it stops me by denying the permission. So how do I able to delete a specific file especially a plugin file

**Comment by gongomgra** [comment]
Hi @itsmemidhuz123,

Can you try to [SSH connect to your server](https://docs.bitnami.com/aws/faq/get-started/connect-ssh/) and remove the file from the command line using `sudo rm /path/to/file`?

**Comment by itsmemidhuz123** [comment]
Great, let me try this

**Comment by itsmemidhuz123** [comment]
Sir, instead of using sudo chmod 775 i used 700 to change the file path for the themes and the critical error has been solved. But there's no theme active right now and when tried to install a new theme it says 

Installation failed: Could not create directory.

so what permission can we use on this

**Comment by itsmemidhuz123** [comment]
Sure sure let me do that ☺️

**Comment by itsmemidhuz123** [comment]
while trying it says critical error on website, when changing it to 700 it
works as normal but unable to add new theme

[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by itsmemidhuz123** [comment]
like same when i set 775 on plugin i could able to add new plugin without
any directory error, please help

[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by itsmemidhuz123** [comment]
i already had a backup of each day and this error comes on 10 but when take
backup of 5th august also it says this error on webiste

[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by itsmemidhuz123** [comment]
Uncaught Error: Call to undefined function hello_elementor_body_open()
in /bitnami/wordpress/wp-content/themes/hello-elementor/header.php:25
Stack trace:
#0 /opt/bitnami/wordpress/wp-includes/template.php(770): require_once()
#1 /opt/bitnami/wordpress/wp-includes/template.php(716): load_template()
#2 /opt/bitnami/wordpress/wp-includes/general-template.php(48):
locate_template()
#3 /bitnami/wordpress/wp-content/themes/hello-elementor/index.php(15):
get_header()
#4 /opt/bitnami/wordpress/wp-includes/template-loader.php(106): include('...')
#5 /opt/bitnami/wordpress/wp-blog-header.php(19): require_once('...')
#6 /opt/bitnami/wordpress/index.php(17): require('...')
#7 {main}
  thrown


i removed the filefunctions.php using sudo rm /folder-path and site
works as usual but the now the issue is that home and other pages
comes in whiote screen

**Comment by gongomgra** [comment]
Hi @itsmemidhuz123,

That seems to be an error with the custom theme you are using, please ask the theme developers for help on this. Regarding the filesystem permissions, it is so weird your website works setting 700 and not 775. Can you tell us to which folder are you referring to specifically? We also recommend you to check this permissions issues with the theme developers or the official WordPress community

**Comment by itsmemidhuz123** [comment]
File which is am specifying is /bitnami/WordPress/wp-content/themes

But i changed it to permission 775 after deleting a file functions.php and
everything is fine

But now theme doesn't open properly. I think there's some pending to be
deleted

Let me get in touch with WordPress and get back

**Comment by itsmemidhuz123** [comment]
sir, issue it now resolved. I removed the hello elementor theme and
reinstalled it. It caused by a file that added to the theme which makes
these issues. Issue has been resolved by deleting it adding the fresh theme
file

thanks

[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by gongomgra** [comment]
Hi @itsmemidhuz123,

Thanks for the info. I'm glad you managed to fix your issue!
