### ISSUE TITLE
[WordPress] Services Are Crashing When Taking Certain Actions

### ISSUE THREAD

**Issue by dblincoe24** [bitnami/vms#227]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7da43b07-b2c7-59ba-30e5-ef521439fa97

### bndiagnostic output

Here's what I found from the apache logs:

[Mon Aug 08 22:35:23.882481 2022] [proxy_fcgi:error] [pid 72968:tid 140549491574528] [client 98.184.10.222:60931] AH01067: Failed to read FastCGI header, referer: http://20.83.208.57/wp-admin/edit.php?s=home&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&action2=-1&orderby=title&order=asc
[Mon Aug 08 22:35:23.956876 2022] [proxy_fcgi:error] [pid 72968:tid 140549491574528] (104)Connection reset by peer: [client 98.184.10.222:60931] AH01075: Error dispatching request to : , referer: http://20.83.208.57/wp-admin/edit.php?s=home&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&action2=-1&orderby=title&order=asc
[Mon Aug 08 22:35:23.885529 2022] [proxy_fcgi:error] [pid 74016:tid 140549038106368] [client 98.184.10.222:60930] AH01067: Failed to read FastCGI header, referer: http://20.83.208.57/wp-admin/edit.php?s=home&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&action2=-1&orderby=title&order=asc
[Mon Aug 08 22:35:23.957248 2022] [proxy_fcgi:error] [pid 74016:tid 140549038106368] (104)Connection reset by peer: [client 98.184.10.222:60930] AH01075: Error dispatching request to : , referer: http://20.83.208.57/wp-admin/edit.php?s=home&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&action2=-1&orderby=title&order=asc
[Mon Aug 08 22:35:23.962045 2022] [proxy_fcgi:error] [pid 74016:tid 140549054891776] [client 98.184.10.222:60926] AH01067: Failed to read FastCGI header, referer: http://20.83.208.57/wp-admin/edit.php?s=home&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&action2=-1&orderby=title&order=asc
[Mon Aug 08 22:35:23.962077 2022] [proxy_fcgi:error] [pid 74016:tid 140549054891776] (104)Connection reset by peer: [client 98.184.10.222:60926] AH01075: Error dispatching request to : , referer: http://20.83.208.57/wp-admin/edit.php?s=home&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&action2=-1&orderby=title&order=asc
[Mon Aug 08 22:35:23.904342 2022] [proxy_fcgi:error] [pid 72967:tid 140549331851008] [client 98.184.10.222:60932] AH01067: Failed to read FastCGI header, referer: http://20.83.208.57/wp-admin/edit.php?s=home&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&action2=-1&orderby=title&order=asc
[Mon Aug 08 22:35:23.991631 2022] [proxy_fcgi:error] [pid 72967:tid 140549331851008] (104)Connection reset by peer: [client 98.184.10.222:60932] AH01075: Error dispatching request to : , referer: http://20.83.208.57/wp-admin/edit.php?s=home&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&action2=-1&orderby=title&order=asc
[Mon Aug 08 22:35:24.010362 2022] [proxy:error] [pid 74016:tid 140549063284480] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
[Mon Aug 08 22:35:24.010389 2022] [proxy_fcgi:error] [pid 74016:tid 140549063284480] [client 98.184.10.222:60936] AH01079: failed to make connection to backend: httpd-UDS, referer: http://20.83.208.57/?fl_builder
[Mon Aug 08 22:35:25.759492 2022] [mpm_event:notice] [pid 72964:tid 140550044477248] AH00491: caught SIGTERM, shutting down

### bndiagnostic was not useful. Could you please tell us why?

it was useful to me

### Describe your issue as much as you can

When making changes to the site we have been running into an issues with the services stopping.  It doesn't happen on any particular plugin or changes.  One time its when I submit a front end gravity form.  The next time its when I'm browsing the backend.

**Comment by jotamartos** [comment]
Hi @dblincoe24,

The errors seems to be related to the changes you are making in the application. I can see WordPress-related errors in the Apache's log 

```
[Mon Aug 08 20:17:20.477607 2022] [proxy_fcgi:error] [pid 67711:tid 139652681926400] [client 98.184.10.222:59166] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function get_field()   in /bitnami/wordpress/wp-content/themes/Lumen2019/page-team.php:43\nStack trace:\n#0 /opt/bitnami/wordpress/wp-includes/template-loader.php(106): include()\n#1 /opt/bitnami/wordpress/wp-blog-header.php(19):                require_once('...')\n#2 /opt/bitnami/wordpress/index.php(17): require('...')\n#3 {main}\n  thrown in /bitnami/wordpress/wp-content/themes/Lumen2019/page-team.php on line 43', referer: http://20.83.208.57/contact/
```

Please contact WordPress to get more info about the issues you are running into

https://wordpress.org/support/

**Comment by dblincoe24** [comment]
We were able to give the above mentioned error fixed, but are still experiencing crashing issues.  Wordpress support bounced me back here as they mentioned it appears PHP is crashing.  The apache log snippet below is from when I clicked on a link on the backend.  

[Wed Aug 10 18:02:13.272381 2022] [proxy_fcgi:error] [pid 97734:tid 139893116200704] [client 98.184.10.222:50936] AH01067: Failed to read FastCGI header, referer: http://20.83.208.57/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Wed Aug 10 18:02:13.273955 2022] [proxy_fcgi:error] [pid 97734:tid 139893116200704] (104)Connection reset by peer: [client 98.184.10.222:50936] AH01075: Error dispatching request to : , referer: http://20.83.208.57/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Wed Aug 10 18:02:13.289461 2022] [proxy_fcgi:error] [pid 97734:tid 139893132986112] [client 98.184.10.222:50934] AH01067: Failed to read FastCGI header, referer: http://20.83.208.57/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Wed Aug 10 18:02:13.289491 2022] [proxy_fcgi:error] [pid 97734:tid 139893132986112] (104)Connection reset by peer: [client 98.184.10.222:50934] AH01075: Error dispatching request to : , referer: http://20.83.208.57/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Wed Aug 10 18:02:13.397985 2022] [proxy:error] [pid 97734:tid 139893040666368] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
[Wed Aug 10 18:02:13.398027 2022] [proxy_fcgi:error] [pid 97734:tid 139893040666368] [client 98.184.10.222:50932] AH01079: failed to make connection to backend: httpd-UDS, referer: http://20.83.208.57/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Wed Aug 10 18:02:13.397973 2022] [proxy:error] [pid 96685:tid 139893409748736] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
[Wed Aug 10 18:02:13.398108 2022] [proxy_fcgi:error] [pid 96685:tid 139893409748736] [client 98.184.10.222:50935] AH01079: failed to make connection to backend: httpd-UDS, referer: http://20.83.208.57/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Wed Aug 10 18:02:13.466187 2022] [proxy:error] [pid 97734:tid 139893023880960] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
[Wed Aug 10 18:02:13.466223 2022] [proxy_fcgi:error] [pid 97734:tid 139893023880960] [client 98.184.10.222:50937] AH01079: failed to make connection to backend: httpd-UDS, referer: http://20.83.208.57/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Wed Aug 10 18:02:13.473489 2022] [proxy:error] [pid 97734:tid 139893007095552] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
[Wed Aug 10 18:02:13.473517 2022] [proxy_fcgi:error] [pid 97734:tid 139893007095552] [client 98.184.10.222:50938] AH01079: failed to make connection to backend: httpd-UDS, referer: http://20.83.208.57/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Wed Aug 10 18:02:15.055573 2022] [mpm_event:notice] [pid 96681:tid 139894251759424] AH00491: caught SIGTERM, shutting down

**Comment by dblincoe24** [comment]
Anyone have an idea?

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
