### ISSUE TITLE
[sonarqube] service is not starting

### ISSUE THREAD

**Issue by shijiltv** [bitnami/vms#228]
### Describe your issue as much as you can

Platform : Linux VM
bndiagnostic ID : 7d07589d-b9a9-ff5f-4800-c426e42a2dc1

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Connectivity: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Aug 09 09:18:25.622760 2022] [proxy_http:error] [pid 2825] [client
139.5.223.119:51000] AH01114: HTTP: failed to make connection to backend:
127.0.0.1
 [Tue Aug 09 09:18:25.622908 2022] [proxy:error] [pid 2825] (111)Connection
refused: AH00957: http: attempt to connect to 127.0.0.1:9000 (127.0.0.1) failed
 [Tue Aug 09 09:18:25.622923 2022] [proxy_http:error] [pid 2825] [client
139.5.223.119:51000] AH01114: HTTP: failed to make connection to backend:
127.0.0.1

```

===== End of bndiagnostic tool output =====

I can see that sonarqube service is failed to start

<img width="822" alt="image" src="https://user-images.githubusercontent.com/2546782/183615586-e0c0769a-a31b-43fe-b28e-5478485150fc.png">

However I don't find any relevant logs for further troubleshooting.

**Comment by gongomgra** [comment]
Hi @shijiltv,

Thanks for using Bitnami. It looks like you are not running the latest bndiagnostic tool version and there is some missing information in the bundle you shared. Can you follow the next guide to update the tool on your server?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/#run-the-bitnami-diagnostic-tool

Apart from that, according to the Apache logs, there seems to be an error with the Sonarqube application itself. Please check the application logs under `/opt/bitnami/sonarqube/logs`

**Comment by shijiltv** [comment]
>Thanks for using Bitnami. It looks like you are not running the latest bndiagnostic tool version and there is some missing information in the bundle you shared. Can you follow the next guide to update the tool on your server?

Yes. I will do that.

> Apart from that, and according to the Apache logs, there seems to be an error with the Sonarqube application itself. Please check the application logs under `/opt/bitnami/sonarqube/logs`

The path where I can find logs related to sonarqube is `/opt/bitnami/apps/sonarqube/sonarqube/logs` . Please see the screenshot. As you can see, I don't find any logs generated after Aug 5th.  I could troubleshoot further if I can find logs generated while sonarqube service is getting started. Also please note that this is configured by some one else and I don't have contact with that person right now. Not sure everything was configured appropriately. I did search for `sonar.log` in in root directory, could not find any.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/2546782/183655940-9f388205-99a0-49f8-8625-d19409a704b4.png">

Also please note that I started facing this issue after I restarted the machine. We use Sonarqube developer edition which has to be licensed. By any chance, would this be related to sonarqube licensing related ?

**Comment by shijiltv** [comment]
> Yes. I will do that.

new bndiagnostic ID
c788cb35-aedc-96c6-0c19-2f8ca58cd1ba

**Comment by gongomgra** [comment]
Hi @shijiltv,

The log files including a date are old log files that the application rotates to avoid having a single log with hundred/thousands of lines. The current files are those without the date except for `sonar.*`, that seems to always include a date. Please review the info in the different files and share the errors with us.

**Comment by shijiltv** [comment]
I ran below commands and I got below result. The message shows that sonarqube could not be started. I am unable to locate logs/details why sonarqube  could not be started. If I get those detail I should be able to trace the issue.

![image](https://user-images.githubusercontent.com/2546782/184347328-a29214e8-c5ab-4d90-af39-d175a17a8607.png)


Sharing what I could find in sonar log file after running above commands. 

```
TERM trapped.  Shutting down.
2022.08.05 16:48:58 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ce]: 129
2022.08.05 16:48:58 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is stopped
2022.08.05 16:48:58 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [web]: 143
2022.08.05 16:48:58 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
<-- Wrapper Stopped
```

**Comment by gongomgra** [comment]
Hi @shijiltv,

Thanks for the info. You will have to increase the log level of the application to get further information about the errors

https://docs.sonarqube.org/latest/instance-administration/system-info/

We also recommend you to open a new question in the official Sonarqube forums, where you will find people with more knowledge on how the application works internally

https://community.sonarsource.com/

**Comment by shijiltv** [comment]
Hi @gongomgra,

I could make it working by following the [stackoverflow](https://stackoverflow.com/a/65904139) solution. I am not sure this is the ideal way. However, it looks good now. 
I have to further investigate to know why the service did not get start while booting. Closing this issue now. 

Thanks for the support.
