### ISSUE TITLE
[wordpress] Error with php temp folder

### ISSUE THREAD

**Issue by jcmaad** [bitnami/vms#229]
### Describe your issue as much as you can

Hi everyone,

I have a wordpress site and trying to import a file using plugin WP Recipe Maker. Import is not working and the following entry is added to the entry to the error log: `[Mon Aug 08 02:19:53.990429 2022] [proxy_fcgi:error] [pid 7435:tid 140005531809536] [client 209.202.201.138:50201] AH01071: Got error 'PHP message: PHP Notice: Unknown: file created in the system's temporary directory in Unknown on line 0', referer: http://####.com/wp-admin/admin.php?page=wprm_import_json`

I checked the php.ini file. I ensured that folder permissions are set to 777. I tried changing the folder set in the php.ini. Not sure what else to try.

Thanks.

**Comment by gongomgra** [comment]
Hi @jcmaad,

Thanks for using Bitnami. There seems to be an error with one of your plugins, please ask in the official WordPress forums or to the plugins developers for more information on how to debug and fix them

https://wordpress.org/support/forums/

Apart from that, please notice there are some security concerns in setting a directory with 777 permissions and that we don't recommend you to do so. We recommend you to reset the folder permissions to its original values.

**Comment by jcmaad** [comment]
Googling this error message seems to do with PHP's temp folder. I messaged the plugin developer and they told me to talk to the hoster.

**Comment by gongomgra** [comment]
Hi @jcmaad,

I see in the PHP ini file that the tmp folder is set to ` /opt/bitnami/php/tmp` and that it is owned by `root:root`.

```
$ ls -larth /opt/bitnami/php
total 48K
drwxrwxr-x  2 root root 4.0K Jan  1  1970 tmp
```

Can you check if updating its ownership to `root:daemon` solves your issue with the plugin? `daemon` is the username running Apache server

```
sudo chown -R root:daemon /opt/bitnami/php/tmp
```

If the above doesn't solve your issue, please contact the plugin developers, as the file system permissions should be fine after running the `chown` command.

**Comment by gongomgra** [comment]
@samholguin good to know it worked for you!
