### ISSUE TITLE
[WordPress Multisite] How do I point a domain to a properly installed non-WordPressMultisite PHP site?

### ISSUE THREAD

**Issue by bvbbv** [bitnami/vms#232]
### Describe your issue as much as you can

I'm adding a new PHP non-Wordpress virtual host application to my server as I have done in the past. I followed the steps in Approach B of https://docs.bitnami.com/aws/apps/wordpress/administration/create-custom-application-php/ but there are some additional things to do including setting up an httpd-vhosts.conf file. I've tried to duplicate what I did earlier, which was iterated in a Bitnami Community thread with the same title as this one but it is unfortunately no longer accessible.

I'm at the point where where the mydomain.com URL opens the Multisite root Wordpress blog instead of my PHP app. Has any one gotten this task working?

**Comment by gongomgra** [comment]
Hi @bvbbv,

Thanks for using Bitnami. As you are using WordPress Multisite, the required changes may be a bit different, can you undo the changes you performed, and then follow the steps in the specific guide for WordPress Multisite?

https://docs.bitnami.com/aws/apps/wordpress-multisite/administration/create-custom-application-php/

**Comment by bvbbv** [comment]
Thanks. Problem solved. I forgot to follow the linked article https://docs.bitnami.com/aws/apps/wordpress-multisite/administration/redirect-custom-domains/

By the way the instructions in the two originally cited articles are identical.

**Comment by gongomgra** [comment]
Hi @bvbbv,

Thanks for letting us know. We are glad following our guide solved your issue!
