### ISSUE TITLE
[wordpress] Issues with Let's Encrypt certificate

### ISSUE THREAD

**Issue by Szpotu** [bitnami/vms#233]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

No ID

### bndiagnostic output

```
bitnami@ip-172-26-7-53:/opt/bitnami/bndiagnostic$ /opt/bitnami/bndiagnostic-tool 
Error copying file from packed archive /opt/bitnami/bndiagnostic/bndiagnostic-0.9.18-linux-
x64.run to /tmp/autoupdater/update.ini
:Destination not writable
Abort, Retry, Ignore ? [A/r/i]i

Error changing permissions to 00644 in /tmp/autoupdater/update.ini
Abort, Retry, Ignore ? [A/r/i]i

Error copying file from packed archive /opt/bitnami/bndiagnostic/bndiagnostic-0.9.18-linux-
x64.run to /tmp/autoupdater/autoupdate-linux-x64.run
:Destination not writable
Abort, Retry, Ignore ? [A/r/i]i

Error changing permissions to 00755 in /tmp/autoupdater/autoupdate-linux-x64.run
Abort, Retry, Ignore ? [A/r/i]i

Error changing permissions to 040755 in /tmp/autoupdater
Abort, Retry, Ignore ? [A/r/i]i


Error: There has been an error.
Error reading INI file /tmp/autoupdater/update.ini
Press [Enter] to continue:
bitnami@ip-172-26-7-53:/opt/bitnami/bndiagnostic$ cd ..
bitnami@ip-172-26-7-53:/opt/bitnami$ apache
-bash: apache: command not found
```

### bndiagnostic was not useful. Could you please tell us why?

Couldn't receive an ID. 

### Describe your issue as much as you can

Hey there! 

For the first time I've tried to renew SSL Certificate (LetsEncrypt). 
Validity expanded, page was not secure. 
Cleaned cache, tried on another browser.
Mulitply AWS instance reboot.  
Ran Bitnami HTTPS Configuration tool - 

```
Error: There has been an error.
Cannot bind to port 80 and/or 443. These ports are used for Let's Encrypt to 
verify the domain DNS configuration. Please stop any services using those ports, 
and ensure your system user has permissions to bind to them.
```

Checked what's use port 80. 

```
bitnami@ip-172-26-7-53:~$ netstat -tulpn | grep :80
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::80                   :::*                    LISTEN      -         
```

Reinstalled apache, probably lost all data :(         
Can't run wp-admin site anymore (404). I'm a total fresh meat, please spare me! 

Can't run Bitnami services 

```
apache not running
mariadb not running
php-fpm not running

Starting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

bitnami@ip-172-26-7-53:/opt/bitnami$ systemctl status bitnami.service
● bitnami.service - LSB: bitnami init script
   Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2022-08-10 09:42:20 UTC; 2min 18s ago
  Process: 2437 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
    Tasks: 11 (limit: 558)
   Memory: 109.7M
   CGroup: /system.slice/bitnami.service
           ├─726 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
           ├─730 php-fpm: pool www
           ├─731 php-fpm: pool www
           ├─732 php-fpm: pool www
           ├─733 php-fpm: pool www
           ├─734 php-fpm: pool www
           ├─735 php-fpm: pool www
           ├─736 php-fpm: pool www
           ├─737 php-fpm: pool www
           ├─738 php-fpm: pool www
           └─739 php-fpm: pool www

Aug 10 09:42:20 ip-172-26-7-53 bitnami[2437]: AH00015: Unable to open logs
Aug 10 09:42:20 ip-172-26-7-53 bitnami[2437]: 2022-08-10T09:42:20.798Z - error: Unable to p
Aug 10 09:42:20 ip-172-26-7-53 bitnami[2437]: ## 2022-08-10 09:42:20+00:00 ## INFO ## Runni
Aug 10 09:42:20 ip-172-26-7-53 bitnami[2437]: ## 2022-08-10 09:42:20+00:00 ## INFO ## Runni
Aug 10 09:42:20 ip-172-26-7-53 bitnami[2437]: ## 2022-08-10 09:42:20+00:00 ## INFO ## Runni
Aug 10 09:42:20 ip-172-26-7-53 bitnami[2437]: ## 2022-08-10 09:42:20+00:00 ## INFO ## Runni
Aug 10 09:42:20 ip-172-26-7-53 bitnami[2437]: ## 2022-08-10 09:42:20+00:00 ## INFO ## Runni
Aug 10 09:42:20 ip-172-26-7-53 systemd[1]: bitnami.service: Control process exited, code=ex
Aug 10 09:42:20 ip-172-26-7-53 systemd[1]: bitnami.service: Failed with result 'exit-code'.
Aug 10 09:42:20 ip-172-26-7-53 systemd[1]: Failed to start LSB: bitnami init script.
lines 1-29/29 (END)
```

Thanks in advance!

**Comment by gongomgra** [comment]
Hi @Szpotu,

Thank for using Bitnami. Notice I edit your ticket title and first post to meet the requirements. Please take it into account when opening a new one.

The bndiagnostic tool has to be run with higher privileges on your server by using the `sudo` command. Can you tell us if you are finding any error following the steps in our docs on how to generate a Let's Encrypt certificate? In which specific step?

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/

The tool should take care of stopping the Bitnami services before starting the Let's Encrypt request. Is it possible that you have any other service on your server using the port number 80?

**Comment by Szpotu** [comment]
Hi again! 
Sorry for the late reply. 
So, 
![image](https://user-images.githubusercontent.com/59575590/185651872-66c14c58-e9ae-4a07-96e2-ba25c2d2c82e.png)
the picture shows that port :80 is off. 
I've double checked if any application runs on port 80. 
Weirdly, there was a signal on port 80 so I killed it. 
![image](https://user-images.githubusercontent.com/59575590/185655107-3a36f5d3-e4d7-486c-9ade-146c457e0439.png)
..than I ran bncert-tool again. Everything goes fine until.: 
![image](https://user-images.githubusercontent.com/59575590/185655227-a4d3f349-10ff-4ab3-a12f-52b3fe27f377.png)
I hope that screenshots will be found helpful. 

Thanks for every minute of effort!

**Comment by mdhont** [comment]
Maybe you have another (non-bitnami) Apache running? 

    ps aux | grep apache

If so, you can remove it with:

    sudo service apache2 stop
    sudo apt-get purge apache2 apache2-utils apache2.2-bin apache2-common

**Comment by Szpotu** [comment]
Done

Site is available again, thank you! 
Now certificate
Validity correct, 
![image](https://user-images.githubusercontent.com/59575590/185912126-5f70d9a1-0431-40c4-9c6d-d80fa195c883.png)

Files DOMAIN.com.crt + DOMAIN.com.key placed in apache2. 
Tried manually revoke certificate: 
![image](https://user-images.githubusercontent.com/59575590/185911466-09ea2fa1-83ae-4833-8e67-d535533d6585.png)

Because I ran bncert again 'If an existing certificate already exists and it is associated to the same domains, the tool will proceed with renewing the certificate'. Certificate should be renewed with 22 Aug

Thanks in advance!

**Comment by mdhont** [comment]
Why are you trying to revoke the certificate? Can you check the renewal cronjob?

    sudo crontab -l -u bitnami

And then run the renewal cron command manually?

**Comment by Szpotu** [comment]
I was trying to revoke it in order to create a new one, thinking if the current is crashed. 
Probably I didn't get the 'revoke' command usage well.

So I've tried a crontab 
![image](https://user-images.githubusercontent.com/59575590/186144386-3f71ee84-5b59-44d7-80b6-a1cca7c0661f.png)

Than moved them on server crt directory []

sudo mv /opt/bitnami/apache2/conf/bitnami/certs/server.crt /opt/bitnami/apache2/conf/bitnami/certs/server.crt.old
sudo mv /opt/bitnami/apache2/conf/bitnami/certs/server.key /opt/bitnami/apache2/conf/bitnami/certs/server.key.old
sudo ln -sf /opt/bitnami/letsencrypt/certificates/DOMAIN.key /opt/bitnami/apache2/conf/bitnami/certs/server.key
sudo ln -sf /opt/bitnami/letsencrypt/certificates/DOMAIN.crt /opt/bitnami/apache2/conf/bitnami/certs/server.crt

![image](https://user-images.githubusercontent.com/59575590/186150654-8fbfb51b-bb38-4592-b761-facdab1eafc0.png)

Is it normal that files are compresed? 

Changing permissions to root failed.
![image](https://user-images.githubusercontent.com/59575590/186151210-f45c036b-05d0-4e0e-973f-f4a6e5ba597b.png)

**Comment by mdhont** [comment]
Can you try to manually issue the certificate?

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by Szpotu** [comment]
Hi,

I've tried manually issue the certificate - the process seems to stopped on
step no.3
[image: image.png]
and then here:
[image: image.png]

pt., 26 sie 2022 o 17:23 Michiel ***@***.***> napisał(a):

**Comment by mdhont** [comment]
I can't see the screenshots. Could you paste the error text output instead?

**Comment by Szpotu** [comment]
Sure,

***@***.***:/tmp$ sudo /opt/bitnami/letsencrypt/lego --tls
***@***.***
mail.com" --domains="raverinserepeat.com" --domains="www.raverinserepeat.com"
--path="/opt/
bitnami/letsencrypt" run
2022/08/30 13:52:11 [INFO] [raverinserepeat.com, www.raverinserepeat.com]
acme: Obtaining b
undled SAN certificate
2022/08/30 13:52:11 [INFO] [raverinserepeat.com] AuthURL:
https://acme-v02.api.letsencrypt.
org/acme/authz-v3/147557824317
2022/08/30 13:52:11 [INFO] [www.raverinserepeat.com] AuthURL:
https://acme-v02.api.letsencr
ypt.org/acme/authz-v3/147557824327
2022/08/30 13:52:11 [INFO] [raverinserepeat.com] acme: authorization
already valid; skippin
g challenge
2022/08/30 13:52:11 [INFO] [www.raverinserepeat.com] acme: authorization
already valid; ski
pping challenge
2022/08/30 13:52:11 [INFO] [raverinserepeat.com, www.raverinserepeat.com]
acme: Validations
 succeeded; requesting certificates
2022/08/30 13:52:12 [INFO] [raverinserepeat.com] Server responded with a
certificate.
***@***.***:/tmp$ sudo mv
/opt/bitnami/apache2/conf/bitnami/certs/server.crt /op
t/bitnami/apache2/conf/bitnami/certs/server.crt.old
***@***.***:/tmp$ sudo mv
/opt/bitnami/apache2/conf/bitnami/certs/server.key /op
t/bitnami/apache2/conf/bitnami/certs/server.key.old
***@***.***:/tmp$ sudo ln -sf
/opt/bitnami/letsencrypt/certificates/raverinserep
eat.com.key /opt/bitnami/apache2/conf/bitnami/certs/server.key sudo ln -sf
/opt/bitnami/let
sencrypt/certificates/raverinserepeat.com.crt
/opt/bitnami/apache2/conf/bitnami/certs/serve
r.crt
ln: target '/opt/bitnami/apache2/conf/bitnami/certs/server.crt' is not a
directory
***@***.***:/tmp$
***@***.***:/tmp$ sudo chown root:root
/opt/bitnami/apache2/conf/bitnami/certs/server*
chown: cannot dereference
'/opt/bitnami/apache2/conf/bitnami/certs/server.crt.old': No such file or
directory
chown: cannot dereference
'/opt/bitnami/apache2/conf/bitnami/certs/server.key.old': No such file or
directory
***@***.***:/tmp$ sudo chmod 600
/opt/bitnami/apache2/conf/bitnami/certs/server*
chmod: cannot operate on dangling symlink
'/opt/bitnami/apache2/conf/bitnami/certs/server.crt.old'
chmod: cannot operate on dangling symlink
'/opt/bitnami/apache2/conf/bitnami/certs/server.key.old'
***@***.***:/tmp$ sudo chmod 600
/opt/bitnami/apache2/conf/bitnami/certs/server*
chmod: cannot operate on dangling symlink
'/opt/bitnami/apache2/conf/bitnami/certs/server.crt.old'
chmod: cannot operate on dangling symlink
'/opt/bitnami/apache2/conf/bitnami/certs/server.key.old'
***@***.***:/tmp$

wt., 30 sie 2022 o 16:45 Michiel ***@***.***> napisał(a):

**Comment by mdhont** [comment]
Could you tell me the content of the `/opt/bitnami/letsencrypt/certificates/` folder?

    sudo ls -la /opt/bitnami/letsencrypt/certificates/


And run this command again:

```
sudo ln -sf /opt/bitnami/letsencrypt/certificates/raverinserepeat.com.key /opt/bitnami/apache2/conf/bitnami/certs/server.key 
```

**Comment by Szpotu** [comment]
Sure, :
***@***.***:/opt/bitnami/letsencrypt/certificates# ls

raverinserepeat.com.crt / raverinserepeat.com.json

raverinserepeat.com.issuer.crt / raverinserepeat.com.key

-------------------------------------------------------------------------------

The command ' sudo ln -sf /opt/bitnami/letsencrypt/
certificates/raverinserepeat.com.key
/opt/bitnami/apache2/conf/bitnami/certs/server.key
' didn't throw any error, however - everything in certificates directory
seems the same.

What next?
Thanks for effort !

pt., 2 wrz 2022 o 14:58 Michiel ***@***.***> napisał(a):

**Comment by gongomgra** [comment]
Hi @Szpotu,

Can you run the next command and share the output with us?

```
ls -larth /opt/bitnami/letsencrypt/certificates
```

Can you also run the bndiagnostic tool again? Getting the information from the tool will also be of help to us.

**Comment by mdhont** [comment]
Can you also run this command?

    ls -larth /opt/bitnami/apache2/conf/bitnami/certs

**Comment by Szpotu** [comment]
Done,

***@***.***:/home/bitnami# ls -larth
/opt/bitnami/apache2/conf/bitnami/certs
total 12K
drwxrwxr-x 4 bitnami root 4.0K Aug 22 10:18 ..
lrwxrwxrwx 1 root    root   48 Aug 29 20:08 server.key.old ->
/opt/bitnami/letsencrypt/cert
ificates/DOMAIN.key
lrwxrwxrwx 1 root    root   48 Aug 29 20:08 server.crt.old ->
/opt/bitnami/letsencrypt/cert
ificates/DOMAIN.crt
lrwxrwxrwx 1 root    root   61 Sep 10 11:18 server.key ->
/opt/bitnami/letsencrypt/certific
ates/raverinserepeat.com.key
drwxrwxr-x 2 bitnami root 4.0K Sep 10 11:18 .
***@***.***:/home/bitnami#

wt., 13 wrz 2022 o 19:25 Michiel ***@***.***> napisał(a):

**Comment by mdhont** [comment]
You still need to create a server.crt symlink pointing to the actual certificate in `/opt/bitnami/letsencrypt/certific
ates/`:

    sudo ln -sf /opt/bitnami/letsencrypt/certificates/DOMAIN.crt /opt/bitnami/apache2/conf/bitnami/certs/server.crt

Please note that you need to replace DOMAIN with the actual domain name.

**Comment by Szpotu** [comment]
Ok, done

Shall I reboot it afterall?

After linking server.crt to certificate the site is still not secure

Greats,


czw., 15 wrz 2022 o 13:34 Michiel ***@***.***> napisał(a):

**Comment by Szpotu** [comment]
Yes, I did

Nothing changed, still not secured.

pt., 16 wrz 2022 o 18:17 Michiel ***@***.***> napisał(a):

**Comment by mdhont** [comment]
Can you run the bnsupport tool again?
