### ISSUE TITLE
[CanvasLMS]  postgresql  could not be started

### ISSUE THREAD

**Issue by jocastillo-uc-bcf** [bitnami/vms#234]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

81af3208-4aff-069a-79dc-622c44c38b65

### bndiagnostic was not useful. Could you please tell us why?

No guide is suggested after running "sudo /opt/bitnami/bnsupport-tool"

### Describe your issue as much as you can

The service postgresql is not running or failed to start. Here is the cli output after restarting the services:

```
sudo /opt/bitnami/ctlscript.sh restart
Syntax OK
/opt/bitnami/apache2/scripts/ctl.sh : httpd stopped
Stopping canvas_init daemon, it could take some seconds...
/opt/bitnami/apps/canvaslms/scripts/ctl.sh : canvas_init not running
/opt/bitnami/postgresql/scripts/ctl.sh : postgresql not running
waiting for server to start.... stopped waiting
pg_ctl.bin: could not start server
Examine the log output.
/opt/bitnami/postgresql/scripts/ctl.sh : postgresql  could not be started
Starting canvas_init daemon, it could take some seconds...
/opt/bitnami/apps/canvaslms/scripts/ctl.sh : canvas_init could not be started
Syntax OK
/opt/bitnami/apache2/scripts/ctl.sh : httpd started at port 80
```

------------
Here's also the cli output when running the service from sudo /opt/bitnami/bnhelper-tool

```
Something when wrong while starting the services, Please run bnsupport and o
  pen a ticket at: https://community.bitnami.com Error ocurred:exit status 3

  waiting for server to start.... stopped waiting
  /opt/bitnami/postgresql/scripts/ctl.sh : postgresql  could not be started
  Starting canvas_init daemon, it could take some seconds...
  /opt/bitnami/apps/canvaslms/scripts/ctl.sh : canvas_init could not be started
  /opt/bitnami/apache2/scripts/ctl.sh : httpd (pid 23924) already running
```

------------
Image Version: Bitnami Canvas LMS 2020.07.15.28-0

**Comment by gongomgra** [comment]
Hi @jocastillo-uc-bcf,

Thanks for using Bitnami. According to the information provided by the bndiagnostic tool, your server's disk is full, and that's probably the issue causing PostgreSQL not to start, although its log file seems to be empty.

```
-----------------------------------
Check free amount of disk space
-----------------------------------
Running: df -h
In: /opt/bitnami

Output:

Filesystem       Size  Used Avail Use% Mounted on
udev             3.9G     0  3.9G   0% /dev
tmpfs            791M   17M  774M   3% /run
/dev/nvme0n1p1   126G  121G     0 100% /
tmpfs            3.9G     0  3.9G   0% /dev/shm
tmpfs            5.0M     0  5.0M   0% /run/lock
tmpfs            3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/nvme0n1p15  124M  278K  124M   1% /boot/efi
tmpfs            791M     0  791M   0% /run/user/1000
```

Can you increase the disk on your instance?

https://docs.bitnami.com/aws/how-to/modify-ebs-volume/

**Comment by jocastillo-uc-bcf** [comment]
Whoah! Thank you for pointing that out. Didn't expect the disk to be full already.

Increasing available storage space fixed the issue.
