### ISSUE TITLE
[Wordpress] Full disk space

### ISSUE THREAD

**Issue by APerusso** [bitnami/vms#237]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e7a0c53d-6368-abf1-130f-331b309558c0

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Nginx: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Mysql: No issues found
    ? Php: Found possible issues
 

 
[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2022/08/12 02:31:00 [error] 4961#0: *238466 FastCGI sent in stderr: "PHP 
message: PHP Warning: Illegal offset type in isset or empty in 
/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-optimize/minify/class-wp
-optimize-minify-front-end.php on line 708PHP message: PHP Warning: Illegal 
offset type in isset or empty in 
/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-optimize/minify/class-wp
Press [Enter] to continue:
-optimize-minify-front-end.php on line 803" while reading response header from 
upstream, cl 2022/08/12 02:32:06 [error] 4961#0: *238476 FastCGI sent in stderr: 
"PHP message: PHP Warning: Illegal offset type in isset or empty in 
/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-optimize/minify/class-wp
-optimize-minify-front-end.php on line 708PHP message: PHP Warning: Illegal 
offset type in isset or empty in 
/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-optimize/minify/class-wp
-optimize-minify-front-end.php on line 803" while reading response header from 
upstream, cl 2022/08/12 02:33:25 [error] 4961#0: *238490 FastCGI sent in stderr: 
"PHP message: PHP Warning: Illegal offset type in isset or empty in 
/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-optimize/minify/class-wp
-optimize-minify-front-end.php on line 708PHP message: PHP Warning: Illegal 
offset type in isset or empty in 
/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-optimize/minify/class-wp
-optimize-minify-front-end.php on line 803" while reading response header from 
upstream, cl
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

[Resources]
Press [Enter] to continue:

Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem Size Used Avail Use% Mounted on /dev/sda1 9.7G 8.4G 815M 92% /
```
Please check your cloud provider's documentation for more information.

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1693 1097 77 144 518 298 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Php]

The following error appears in the 
Press [Enter] to continue:
/opt/bitnami/php/var/log/php-fpm.log:
```
[11-Aug-2022 13:07:49] WARNING: [pool www] server reached max_children setting 
(5), consider raising it

```
This error usually indicates PHP script execution is slow due to busy server 
resouces or buggy scripts. Please check the following guide to increase the 
number of PHP-FPM child processes:
 
https://docs.bitnami.com/general/apps/wordpress/configuration/configure-ph
pfpm-processes/
 

===== End of bndiagnostic tool output =====

                                    
Press [Enter] to continue:
The files listed below are bigger than 10MB and have not been included, please notify the support agent.

/opt/bitnami/nginx/logs/error.log

### bndiagnostic was not useful. Could you please tell us why?

It is not clear to me.

### Describe your issue as much as you can

Good Morning.

I am using the WordPress with NGINX and SSL on GCP.
In 08/02/22 i was exporting a product from my ERP to Wordpress but this product had problems with hight resolution imagens links. The disk space increase of 60,38% to 94,62%. I am using a SSD with 10G.
I deleted the product, imagens and run a database optiomization with WP-Optimize plugin, but it not worked.
The binlog is disable in the server.

Please, what can i do to free up drive space?

**Comment by gongomgra** [comment]
Hi @APerusso,

Thanks for using Bitnami. You mentioned binlog files are disabled, but I see there is at leas one on your server. We don't recommend you to directly removing the file using `rm` command but using the [internal MySQL commands](https://dev.mysql.com/doc/refman/8.0/en/purge-binary-logs.html)

```
mysql/data:
total 298152
drwxr-x---  7 mysql root      4096 Aug  7 00:00 .
drwxr-xr-x 11 root  root      4096 Dec 29  2021 ..
-rw-r-----  1 mysql root        56 Apr 16  2021 auto.cnf
-rw-r-----  1 mysql mysql 43444613 Dec 29  2021 binlog.000069
```

Apart from that, I don't know if the process you followed to import/delete your information removed all the expected data or not. We recommend you to open a new question in the official support forums of the plugins or the previous ERP app you are using, or in the official WordPress forums

https://wordpress.org/support/forums/
