### ISSUE TITLE
[wordpress] Consistantly Unresponsive

### ISSUE THREAD

**Issue by Potato8You** [bitnami/vms#242]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

527ebe62-089a-016d-3226-2a2f16091543

### bndiagnostic output

APACHE
```
[Sun Aug 14 12:26:14.365946 2022] [ssl:error] [pid 712:tid 140547662423808] 
[client **ip_address**:43012] AH02042: rejecting client initiated renegotiation
[Sun Aug 14 12:46:15.676992 2022] [ssl:error] [pid 712:tid 140547763136256] 
[client **ip_address**:54678] AH02042: rejecting client initiated renegotiation
```
RESOURCES

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 481 283 8 53 189 132 Swap: 634 
363 270
```
### bndiagnostic was not useful. Could you please tell us why?

Useful for memory but week on Apache. Maybe a gloassory for log output. Apologies if this exists and I have not found it.

### Describe your issue as much as you can

Hi Team,

Single Wordpress site on Lightsail running for years on AWS with superb uptime. Thus a little weak on diagnostics now I have issue.

The Website becomes unavailable and would relaod after minutes. The downtime increaes and consistantly requires the VM to be rebooted which became an inconsistant fix. CUP utilization indicated no issues and helpful if RAM/HDD memory was available in the Metrics.

MIgrated to a new Lightsail instance and issues remains with sudden "site unreachable". I have been working through the self help and cleaned up plugins, database issues, etc. Infrequent "site unreachable" issues continue and until today, running the tool has resulted in the VM becoming unresponsive with site unreachable and an unresponsive console.

I see I need to increase the memory of the VM and will port to 1GB. Is there a way to see the memory utilization of the VM?

Is the SSL error due to the memory issues or do I have another issue?

Thanks in advance

**Comment by gongomgra** [comment]
Hi @Potato8You,

Thanks for using Bitnami. Apart from the errors that the bndiagnostic tool found, I see many others in the Apache log file

```
[Sun Aug 14 08:12:38.851085 2022] [mpm_event:error] [pid 697:tid 140660411460480] AH03490: scoreboard is full, not at MaxRequestWorkers.Increase ServerLimit.
(...)
[Sun Aug 14 18:40:13.147681 2022] [proxy_fcgi:error] [pid 1045:tid 140547721172736] [client 138.122.20.81:33295] AH01071: Got error 'PHP message: PHP Warning:  Trying to access array offset on value of type bool in /bitnami/wordpress/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 2638'
```

According to the errors, there seems to be an issue with one of your plugins (WooCommerce), and also that you are getting too many requests on your server (maybe under a bot attack?), which you can't attend with your current resources. You will have to check what are those requests and block the IP addresses in case you are under a bot attack. Regarding the error with the plugin, we recommend you to contact the plugin developers.
