### ISSUE TITLE
bncert tool DNS Problem

### ISSUE THREAD

**Issue by shackbill** [bitnami/vms#244]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bitnami-wordpress-info-20220815-144727-2538.zip

### bndiagnostic output

im not certain what this output means but appears to me that the IP Address it is returning is the private interface in AWS
[ssl-checker.log](https://github.com/bitnami/vms/files/9338049/ssl-checker.log)

[bitnami-wordpress-info-20220815-144727-2538.zip](https://github.com/bitnami/vms/files/9338056/bitnami-wordpress-info-20220815-144727-2538.zip)
.

### bndiagnostic was not useful. Could you please tell us why?

Im not sure what to look for. 

### Describe your issue as much as you can

attempt to renew SSL Cert has failed. error claims DNS is resolving to different IP Address then detected for machine but DNS Resolution is correct.

**Comment by mdhont** [comment]
You can check the DNS resolution here, to see if it points to the machine IP.

https://www.whatsmydns.net/

Be sure to check both www and non-www domains.

**Comment by shackbill** [comment]
the domain resolves to the correct ip address.
![dns](https://user-images.githubusercontent.com/19624982/184896673-0a494012-54de-4bba-8ef1-5198ff5656ec.JPG)

Anyway, i tried the script again this morning and it worked fine so who knows.. you can close the ticket.
