### ISSUE TITLE
mysql MariaDB Warning in ./libraries/classes/DatabaseInterface.php#815

### ISSUE THREAD

**Issue by GabiPerieteanu** [bitnami/vms#246]
### Platform

AWS
Server architecture | Linux 5.10.0-16-cloud-amd64 x86_64
PHP version | 8.0.22 (Supports 64bit values)

Server version | 10.6.8-MariaDB
Client version | mysqlnd 8.0.22
Database username | bn_wordpress
Database host | localhost:3306
Database name | bitnami_wordpress
Table prefix | wp_
Database charset | utf8mb4
Database collation | utf8mb4_unicode_520_ci
Max allowed packet size | 16777216
Max connections number | 151

</body>
</html>

</body>
</html>

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

59ef9a93-e8ad-3282-96cb-f783fd73a0ca

### bndiagnostic output

MariaDB possible issues

### bndiagnostic was not useful. Could you please tell us why?

the errors that are not related to my error in MariaDB

### Describe your issue as much as you can

Hi,
After I upgraded to the latest version of Bitnami, WordPress Certified by Bitnami and automatic/6.0.1-4-r03 on Debian 11, the following problem appeared: I wanted to modify an older view from the Mariadb database (bitnami_wordpress), but i got this error:
(regardless of which user I try, I get the same error)
(the isues appears on any view I try to modify or create)

Warning in ./libraries/classes/DatabaseInterface.php#815
 Undefined array key 1

Backtrace

CreateController.php#164: PhpMyAdmin\DatabaseInterface->getColumnMapFromSql(
string 'select `t`.`id` AS `id`,`t`.`term_id` AS `term_id`,`t`.`taxonomy` AS `taxonomy`,max(`t`.`evcal_srow`) AS `start_datetime`,case when date_format(max(`t`.`evcal_erow`),\'%H:%i\') between \'00:01\' and \'07:00\' then date_format(max(`t`.`evcal_erow`) + interval -1 day,\'%Y-%m-%d\') else max(`t`.`evcal_erow`) end AS `end_datetime`,max(`t`.`_featured`) AS `_featured`,max(`t`.`_completed`) AS `_completed` from (select `p`.`ID` AS `id`,`v_on`.`term_id` AS `term_id`,`v_on`.`taxonomy` AS `taxonomy`,`m`.`meta_key` AS `meta_key`,`m`.`meta_value` AS `meta_value`,case when lcase(`m`.`meta_key`) = \'evcal_srow\' then from_unixtime(`m`.`meta_value`) end AS `evcal_srow`,case when lcase(`m`.`meta_key`) = \'evcal_erow\' then from_unixtime(`m`.`meta_value`) end AS `evcal_erow`,case when lcase(`m`.`meta_key`) = \'_featured\' then `m`.`meta_value` end AS `_featured`,case when lcase(`m`.`meta_key`) = \'_completed\' then `m`.`meta_value` end AS `_completed` from ((`bitnami_wordpress`.`wp_postmeta` `m` join `bitnami_wordpress`.`wp_posts` `p` on(`p`.`ID` = `m`.`post_id`)) join `bitnami_wordpress`.`on_events` `v_on` on(`v_on`.`id` = `p`.`ID`)) where `p`.`post_type` = \'ajde_events\' and lcase(`p`.`post_status`) = \'publish\') `t` group by `t`.`id`,`t`.`term_id`,`t`.`taxonomy` order by max(`t`.`evcal_srow`),max(`t`.`evcal_erow`),`t`.`id`',
array,
)
Routing.php#192: PhpMyAdmin\Controllers\View\CreateController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/view/create',
,
,
)

![image](https://user-images.githubusercontent.com/110666277/184719210-77abfab0-f6d9-4b97-98af-44b2d69161af.png)

**Comment by mdhont** [comment]
This issue does not seem related to the Bitnami configuration of the application or its components. I recommend asking in a general support forum like Stackoverflow.
