### ISSUE TITLE
[Wordpress] WP crashing, appears to be related to `AH01075: Error dispatching request to :222: (polling)`

### ISSUE THREAD

**Issue by ax0n-pr1me** [bitnami/vms#247]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d26d7c08-2ab2-80c3-112e-c4daea212ae2

### bndiagnostic output

The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Aug 15 22:33:33.115397 2022] [proxy_fcgi:error] [pid 32236:tid
140279981950720] (70007)The timeout specified has expired: [client
**ip_address**:40480] AH01075: Error dispatching request to :25565: (polling)
 [Mon Aug 15 22:33:48.269200 2022] [proxy_fcgi:error] [pid 1009:tid
140280292415232] (70007)The timeout specified has expired: [client
Press [Enter] to continue:
**ip_address**:33052] AH01075: Error dispatching request to :25565: (polling)
 [Mon Aug 15 22:33:54.449150 2022] [proxy_fcgi:error] [pid 1156:tid
140280007096064] (70007)The timeout specified has expired: [client
**ip_address**:39120] AH01075: Error dispatching request to :25565: (polling)
```

Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

diagnostic tool was helpful, and running it actually restarted the wp site, but I have not been able to solve the problem

### Describe your issue as much as you can

Site goes down randomly, very little traffic and a reasonably large instance - appears to be related to apache timeout... 

Looked for the correct way to set timeout but I am not sure this is the right solution. 

I am currently trying this... 

### Update Apache `httpd.conf`

`vim /opt/bitnami/apache/conf/httpd.conf`

and aded

```{sh}
Timeout 600
ProxyTimeout 600
```

then

`sudo /opt/bitnami/ctlscript.sh restart apache`

derived from the following links
<https://stackoverflow.com/a/46798562>
<https://docs.bitnami.com/installer/infrastructure/wamp/get-started/understand-config/>
<https://stackoverflow.com/questions/65860077/how-to-restore-apache-configuration-file-in-bitnami>

**Comment by gongomgra** [comment]
Hi @ax0n-pr1me,

Thanks for using Bitnami. I understand those errors are returned by WordPress, so I understand you should increase the `max_execution_time` property in PHP ini file.

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/modify-execution-time/

Apart from that, I see the next errors in the Apache log file related to WordPress, just in case you want to take a look into this.

```
[Mon Aug 15 14:00:55.646803 2022] [proxy_fcgi:error] [pid 17935:tid 140280133052160] [client 109.248.6.91:58176] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php on line 173PHP message: PHP Warning:  Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php on line 174PHP message: PHP Warning:  Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php on line 687PHP message: PHP Warning:  Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php on line 688PHP message: PHP Warning:  Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php on line 696PHP message: PHP Warning:  Undefined array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php on line 699'
```

**Comment by ax0n-pr1me** [comment]
thanks @gongomgra 

The `max_execution_time` is already set to 1000 seconds... this should be more than sufficient right?

**Comment by gongomgra** [comment]
Hi @ax0n-pr1me,

Thanks for the info. Did you restart the services for changes to take effect?

```
sudo /opt/bitnami/ctlscript.sh restart
```

If you did, and you are still getting timeout errors, we recommend you to open a new question in the official WordPress forums for them to help you to debug the issue and find which script (from a plugin or a custom theme, for example), is causing the timeout.

https://wordpress.org/support/forums/

**Comment by ax0n-pr1me** [comment]
I did - I will watch for errors and if they persist I will post in those forums. I appreciate it @gongomgra
