### ISSUE TITLE
WordPress with NGINX and SSL - HTTP redirection to HTTPS

### ISSUE THREAD

**Issue by KhalilSecurity** [bitnami/vms#249]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c4c656d7-eda9-01b8-7b82-046882574ff4

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Nginx: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2022/08/16 05:17:13 [error] 4257#4257: *37 FastCGI sent in stderr: "Primary
script unknown" while reading response header from upstream, client:
**ip_address**, server: _, request: "GET
/wp-content/plugins/apikey/apikey.php?test=hello HTTP/1.1", upstream:
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host:
"www.sitename.com"
 2022/08/16 05:17:24 [error] 4257#4257: *39 FastCGI sent in stderr: "PHP
message: PHP Warning: Undefined array key 0 in
/bitnami/wordpress/wp-content/plugins/masterstudy-lms-learning-management-system/
lms/classes/user.php on line 555PHP message: PHP Warning: Undefined array key 0
in
/bitnami/wordpress/wp-content/plugins/masterstudy-lms-learning-management-system/
lms/classes/user.php on line 555PHP message: PHP Warning: Undefined array key 0
in /bitnami/wordpress/wp-content/plugins/masterstudy- 2022/08/16 05:18:29
[error] 4257#4257: *47 FastCGI sent in stderr: "Primary script unknown" while
reading response header from upstream, client: **ip_address**, server: _,
request: "GET /tag/index.php?tc=1&tag=qos HTTP/1.1", upstream:
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host:
"www.sitename.com"

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1959 1372 71 182 514 228 Swap:
0 0 0

### bndiagnostic was not useful. Could you please tell us why?

Not related to the issue

### Describe your issue as much as you can

I really like the NGINX image from Bitnami. The performance is super. The only thing I miss from Apache Wordpress image is the ease of use of the bncert tool, so I followed the lego client method and it was a quick learning curve. My issue is the config doesn't properly redirect non-www to www and http to https. I noticed someone tries to access an asset directly on HTTP it works (code 200) like curl -X http://siteurl.com/wp-content/image.png

I modified /opt/bitnami/nginx/conf/nginx.conf to do this
**Original code**

    # HTTP Server
    server {
        # Port to listen on, can also be set in IP:PORT format
        listen  80;

        include  "/opt/bitnami/nginx/conf/bitnami/*.conf";

        location /status {
            stub_status on;
            access_log   off;
            allow 127.0.0.1;
            deny all;
        }
    }

**Modified code:**

   # HTTP Server
    server {
        # Port to listen on, can also be set in IP:PORT format
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }
}

Post-change I see objects are being redirected to HTTPS but two issues appeared:
1. Non-WWW to WWW doesnt properly work, even though WP settings have the URL with WWW, I see users accessing http://sitename.com///?author=1 being redirected to https://sitename.com///?author=1 , which in return causes 404 on some images and a few "has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

2. PHPmyadmin no longer works through ssh tunnel, now it redirects http://localhost:8888/phpmyadmin to https://localhost:8888/phpmyadmin and even when I change it to https://localhost:8888/phpmyadmin it doesn't work - is there a way to properly setup redirection while not breaking the configs at /opt/bitnami/nginx/conf/bitnami like  php-fpm.conf  phpmyadmin.conf  protect-hidden-files.conf?

**Comment by mdhont** [comment]
Did you follow the same steps as in this guide?

https://docs.bitnami.com/aws/infrastructure/ruby/administration/force-https-nginx/

**Comment by KhalilSecurity** [comment]
> Did you follow the same steps as in this guide?
> 
> https://docs.bitnami.com/aws/infrastructure/ruby/administration/force-https-nginx/

Yes that's exactly how my config looks like

**Comment by mdhont** [comment]
> Non-WWW to WWW doesnt properly work, even though WP settings have the URL with WWW, I see users accessing http://sitename.com///?author=1 being redirected to https://sitename.com///?author=1 , which in return causes 404 on some images and a few "has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

It seems some images are not from the same domain so you need to enable CORS to allow the site to pull content from other domains:

The following guide shows how you can enable CORS for Nginx:

https://docs.bitnami.com/ibm/apps/wordpress-pro/configuration/enable-cors-nginx/
