### ISSUE TITLE
Jupyterlhub extraEnvVars - KubeSpawner instance expected a dict

### ISSUE THREAD

**Issue by chrispward** [bitnami/vms#250]
### Describe your issue as much as you can

Installing jupyerhub charts.
Trying to set some custom 'singleuser.extraEnvVars' which the docs say is  default is []
No matter how I define it in my config.yaml, when I launch my lab, there is an error

traitlets.traitlets.TraitError: The 'environment' trait of a KubeSpawner instance expected a dict, not the list [{'accept_license': 'Y'}]

It might be just how I'm defining it as this is 1st time I've used the bitnami charts.
Note: I cant find any examples of using a override chart... Would be useful to see some examples of different data types (dict list etc)

I've attached the current config file. Trying to set the environment variable 'accept_license = "Y"'

[bitnamiConfig.txt](https://github.com/bitnami/vms/files/9354538/bitnamiConfig.txt)

**Comment by gongomgra** [comment]
Hi @chrispward,

Thanks for using Bitnami. Please notice this is the support channel for virtual machines and cloud images. As you are having problems with a Helm chart, please open a new question in our [bitnami/charts](https://github.com/bitnami/charts) repository.
