### ISSUE TITLE
WordPress Multisite Multi-domain cookie issue 

### ISSUE THREAD

**Issue by dfjsmarthome** [bitnami/vms#251]
### Describe your issue as much as you can

Hi 

I have multisite Bitnami WordPress installed and added another domain / site. When I try to login to the newly added site it gives below error. I have enabled cookie and can login to the original site 
ERROR: Cookies are blocked or not supported by your browser. You must enable cookies to use WordPress.
What can be done to resolve this.
Any assistance is appreciated

**Comment by gongomgra** [comment]
Hi @dfjsmarthome,

Thanks for using Bitnami. This may be related to the way you configured your second WordPress site URL. Please take a look at our guide on how to configure it depending on your use case

https://docs.bitnami.com/aws/apps/wordpress-multisite/configuration/configure-wordpress-multisite/
