### ISSUE TITLE
[LAMP] custom PHP app won't connect to mysql 

### ISSUE THREAD

**Issue by janus-at-pkf** [bitnami/vms#252]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

58410a27-c9d7-7838-2734-4a47b10d107c

### bndiagnostic output

```
[Wed Aug 17 05:58:03.951977 2022] [proxy_fcgi:error] [pid 1782:tid 
140685361485568] [client **ip_address**:61713] AH01071: Got error 'PHP message: 
PHP Warning: mysqli::__construct(): (HY000/1045): Access denied for user 
''@'localhost' (using password: NO) in /opt/bitnami/resultsportal/class/User.php 
on line 29'
 [Wed Aug 17 05:59:17.989787 2022] [proxy_fcgi:error] [pid 1782:tid 
Press [Enter] to continue:
140685218809600] [client **ip_address**:61727] AH01071: Got error 'PHP message: 
PHP Warning: mysqli::__construct(): (HY000/1045): Access denied for user 
''@'localhost' (using password: NO) in /opt/bitnami/resultsportal/class/User.php 
on line 29'
 [Wed Aug 17 06:04:06.630176 2022] [proxy_fcgi:error] [pid 1782:tid 
140685319522048] [client **ip_address**:61748] AH01071: Got error 'PHP message: 
PHP Warning: mysqli::__construct(): (HY000/1045): Access denied for user 
''@'localhost' (using password: NO) in /opt/bitnami/resultsportal/class/User.php 
on line 29'
```
### bndiagnostic was not useful. Could you please tell us why?

Does not address my issue

### Describe your issue as much as you can

On shared hosting the app ran exactly as it is without any issue. I had to move it to one of your lampstack images on GCP for more resources.

For some reason MySQL just doesn't want to connect and I can't figure out why, I have triple checked the credentials in the config file.

**Comment by gongomgra** [comment]
Hi @janus-at-pkf,

Thanks for using Bitnami. According to the error messages you shared, and the content of the `/opt/bitnami/mariadb/logs/mysqld.log` file, it looks like you are trying to connect with the database using an empty username and no password. 

```
2022-08-17  6:04:06 10 [Warning] Access denied for user ''@'localhost' (using password: NO)
```

Can you connect with the required database using the `mysql` cli from the machine and the configured credentials? If so, please review the custom PHP application code or contact the app developers for help on how to configure/debug it.

**Comment by janus-at-pkf** [comment]
So I tried the code again as is on shared hosting and it works perfectly - bar the capacity. There are credentials configured in the config file which is being called but for some reason it keeps saying there is no login.

The config file looks like this: I am blanking out the real values. as for server I tried the VM name, 127.0.0.1 and localhost.

The code works it literally just needs the code in the web-root folder and the mysql credentials. 

So something in your image is ignoring my files. Please help I am at my wits end - that is why i chose one of your images rather than setting up lamp myself.
                                         
<?php
class dbConfig {
    protected $serverName;
    protected $userName;
    protected $password;
    protected $dbName;
    function dbConfig() {
        $this -> serverName = '127.0.0.1';
       $this -> userName = '[actual username]';
        $this -> password = '[actual password]';
        $this -> dbName = '[actual database]';
    }
}
?>

**Comment by gongomgra** [comment]
Hi @janus-at-pkf,

Do you know what is the PHP version you have on both servers? Maybe the PHP version or the MySQL driver included in our image are different and that's why you are facing these errors. 

Additionally, you can check our guide on how to install a custom PHP application on top of your LAMP server. There isn't any special configuration required for PHP, it is just a way of installing your application with its own isolated Apache configuration

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/
