### ISSUE TITLE
Bitnami WordPress on Lightsail: Slow/ unresponsive sites

### ISSUE THREAD

**Issue by nialldarvu** [bitnami/vms#253]
### Describe your suggestion as much as you can

Hi,
we've noticed in the last few days that a number of Lightsail websites we administrate are becoming unresponsive. On checking the logs it looks like the sites are becoming proxies for traffic, and are being bombarded. This traffic is generally only going to one or two IP's but coming from many different sources. (The traffic seems to be generally coming from Lithuania heading for Germany).

For example in /opt/bitnami/apache2/logs/access_log:
93.115.26.19 - - [16/Aug/2022:14:09:42 +0000] "CONNECT lenni0451.net:25564 HTTP/1.1" 302 206
93.115.29.22 - - [16/Aug/2022:14:09:42 +0000] "CONNECT lenni0451.net:25564 HTTP/1.1" 302 206
185.8.104.207 - - [16/Aug/2022:14:09:42 +0000] "CONNECT lenni0451.net:25564 HTTP/1.1" 302 206
and on a different machine:
93.115.29.30 - - [14/Aug/2022:00:16:05 +0000] "CONNECT 194.93.56.64:25565 HTTP/1.1" 504 247
93.115.28.50 - - [14/Aug/2022:00:16:13 +0000] "CONNECT 194.93.56.64:25565 HTTP/1.1" 504 247

We changed the Apache httpd.conf to disable CONNECT
<Directory "/opt/bitnami/apache/htdocs">
....
   <Limit CONNECT>
     Deny from all
    </Limit>

We rebooted the instances. Has anyone else seen this traffic or behaviour? Is there a better fix?

Thanks,
Niall

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
