### ISSUE TITLE
 WordPress Certified to  NGINX and SSL

### ISSUE THREAD

**Issue by rob585-538** [bitnami/vms#255]
### Describe your issue as much as you can

I  have built a platform on an EC2 from the standard version

WordPress Certified by Bitnami and Automattic (A)

and I want to move to this instance

WordPress with NGINX and SSL Certified by Bitnami and Automattic (B)

I have tired moving the SSD from an AMI EC2 B to B  (different subnets) and that worked fine,. I expect A to A would work as well. 
When I tried moving the SSD from B to  A (different subnets) this did not work. I noticed that the route drive is SDA v XVDA, and made those changes but it would not boot.
I tried moved from A to B and that didn't work either

Not in these cases I was detaching the storage and re-attaching it.  Is it possible to this for A to B?  If not, how do I get my dev work from A to B in the easiest way?

Thanks

Rob

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
