### ISSUE TITLE
[WordPress] Use Varnish(TM) With SSL

### ISSUE THREAD

**Issue by A2Rashad** [bitnami/vms#256]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

6c5060fe-0ec4-3e6e-37ff-ce45f26f9a41

### bndiagnostic output

Apache: Found possible issues

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Aug 17 21:06:24.051872 2022] [proxy_fcgi:error] [pid 45046:tid 
139855367661312] [client **ip_address**:45172] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://cardoo.co/ar/checkout/?coupon_code=s100
 [Wed Aug 17 21:06:55.284505 2022] [proxy_fcgi:error] [pid 46082:tid 
Press [Enter] to continue:
139855401232128] [client **ip_address**:45180] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://cardoo.co/ar/checkout/?coupon_code=s100
 [Wed Aug 17 21:07:46.276800 2022] [proxy_fcgi:error] [pid 46082:tid 
139855350875904] [client **ip_address**:11572] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://cardoo.co/ar/checkout/
```

### bndiagnostic was not useful. Could you please tell us why?

Issue are not related to my current issue

### Describe your issue as much as you can

I want to Configure Varnish (TM) For WordPress by following this [guide ](https://docs.bitnami.com/google/apps/wordpress/configuration/configure-varnish/)

After [enabling and starting the Varnish service](https://docs.bitnami.com/google/apps/wordpress/administration/configure-use-varnish/#enable-varnishtm) I start in Use Varnish(TM) With SSL as this [guide](https://docs.bitnami.com/google/apps/wordpress/administration/configure-use-varnish/#use-varnishtm-with-ssl)  But when I implement this step 

>If your Bitnami installation follows Approach A (Bitnami installations using system packages), add the same lines in any file ending with the prefix -https-vhost.conf in the /opt/bitnami/apache2/conf/vhosts/ directory.

The website not open and show this message:

<img src="https://i.ibb.co/nMJhHcr/Screenshot-2022-08-17-235156.jpg" >

As appear her 

<img src="https://i.ibb.co/qj2mMtX/Screenshot-2022-08-17-234941.jpg">

I tried to edit on wordpress-https-vhost.conf only also tried to edit on all below files but the same issue

- wordpress-https-vhost.conf
- wordpress-https-vhost.conf.back.202208110548
- wordpress-https-vhost.conf.back.202208160839

this is a screenshot of the edit I did 

<img src="https://i.ibb.co/LzLL0PW/Screenshot-2022-08-17-235045.jpg">

**Comment by gongomgra** [comment]
HI @A2Rashad,

Thanks for using Bitnami. Notice there are two major guides (usually linking other guides internally) you have to follow: first, [this one](https://docs.bitnami.com/google/apps/wordpress/configuration/configure-varnish/) to configure WordPress with Varnish, and once the previous one is working fine, then you have to follow [the steps in this other guide](https://docs.bitnami.com/google/apps/wordpress/administration/configure-use-varnish/#use-varnishtm-with-ssl) to use HTTPS and Varnish.

I reviewed the config files included in the bndiagnostic bundle and it looks like some changes are missing. For example, I don't see the changes in the guide below, which is linked [from this other guide you shared](https://docs.bitnami.com/google/apps/wordpress/configuration/configure-varnish/)

https://docs.bitnami.com/google/apps/wordpress/administration/configure-use-varnish/#modify-the-default-varnishtm-and-apache-ports

As mentioned in the guide, did you check that Varnish was properly serving your website on port 81 initially?

**Comment by hussien-ibrahem** [comment]
Hi **@gongomgra** 
I have the same problem here and I have completed all the steps in this [Guide](https://docs.bitnami.com/google/apps/wordpress/configuration/configure-varnish/) and also this [Guide](https://docs.bitnami.com/google/apps/wordpress/administration/configure-use-varnish/#modify-the-default-varnishtm-and-apache-ports) and also followed your instructions in your reply and the same problem exists.

when varnish is enabled it shows this 
![varnish issue1](https://user-images.githubusercontent.com/77053315/188311515-4baafb78-b357-4189-8496-5944d51b93a3.png)

when varnish is disabled it shows this 
![varnish issue2](https://user-images.githubusercontent.com/77053315/188311532-82a9aa5e-8d7e-47ef-9a4b-6ba7dbd14d15.png)


bndiagnostic ID : ce628490-3aa5-321d-fc04-96a0d593f490

**Comment by gongomgra** [comment]
Hi @A2Rashad,

I'm afraid I can't reproduce your issue. I followed the steps in our guide to configure Varnish to serve WordPress and enable it (first guide), and the WordPress application is served via Varnish on port 81.

```
$ curl -LI "http://127.0.0.1:81"
HTTP/1.1 200 OK
Date: Mon, 05 Sep 2022 10:49:00 GMT
Server: Apache
Link: <http://127.0.0.1:81/wp-json/>; rel="https://api.w.org/"
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
X-Varnish: 32770 3
Age: 11
Via: 1.1 varnish (Varnish/6.6)
X-Cache: HIT
Accept-Ranges: bytes
Content-Length: 55752
Connection: keep-alive
```

Next I switched Apache and Varnish ports. Now port 81 is Apache, and port 80 is Varnish. Also notice HTTPS is still served by Apache:

```
$ curl -LI "http://127.0.0.1:81"
HTTP/1.1 200 OK
Date: Mon, 05 Sep 2022 10:54:19 GMT
Server: Apache
Link: <http://127.0.0.1:81/wp-json/>; rel="https://api.w.org/"
Content-Type: text/html; charset=UTF-8

$ curl -LI "http://127.0.0.1:80"
HTTP/1.1 200 OK
Date: Mon, 05 Sep 2022 10:54:27 GMT
Server: Apache
Link: <http://127.0.0.1/wp-json/>; rel="https://api.w.org/"
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
X-Varnish: 2
Age: 0
Via: 1.1 varnish (Varnish/6.6)
X-Cache: MISS
Accept-Ranges: bytes
Content-Length: 55707
Connection: keep-alive

$ curl -kLI "https://127.0.0.1:443"
HTTP/1.1 200 OK
Date: Mon, 05 Sep 2022 10:56:42 GMT
Server: Apache
Link: <https://127.0.0.1/wp-json/>; rel="https://api.w.org/"
Content-Type: text/html; charset=UTF-8
```

Finally, I followed the steps to proxy HTTPS requests from Apache to Varnish (remember Varnish was moved to port 80 when adding the Apache configuration), and now port 443 is served by Varnish

```
$ curl -kLI "https://127.0.0.1:443"
HTTP/1.1 200 OK
Date: Mon, 05 Sep 2022 10:59:14 GMT
Server: Apache
Link: <https://127.0.0.1/wp-json/>; rel="https://api.w.org/"
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
X-Varnish: 32770
Age: 0
Via: 1.1 varnish (Varnish/6.6)
X-Cache: MISS
Accept-Ranges: bytes
Content-Length: 55722
```

Also from the browser

* HTTP

![Screen Shot 2022-09-05 at 13 05 36](https://user-images.githubusercontent.com/6660452/188435155-76e4512f-5695-4def-886a-d021b112caaf.png)

* HTTPS

![Screen Shot 2022-09-05 at 13 06 52](https://user-images.githubusercontent.com/6660452/188435232-bbc268b5-5262-4632-993f-e91eb1e2ea68.png)

Can you review your changes on your side? I see in the bndiagnostic bundle that you added the Proxy configuration for different ports. Also remember to restart Apache and Varnish for changes to take effect.

**Comment by hussien-ibrahem** [comment]
Hi @gongomgra 
Hope you're good,

I will repeat all the steps again, but I have some doubts and questions:
1- I already have SSL and HTTP/2, doing this will affect my varnish installation.
2- Is it correct to set varnish to a subdomain while the main domain is not set to varnish?
3- After the stage of Open port 81 in the server firewall, the website does not work on port 81 or 80. Is this because I have SSL?
And if this is because the SSL is there, should I do a Use Varnish(TM) With SSL step at this point or is this irrelevant?
4-What is the best time to make this step ( Use Varnish(TM) With SSL )?

Please give me the answers and thank you very much for your time.

**Comment by gongomgra** [comment]
Hi @hussien-ibrahem,

Do you mean you have configured a custom SSL certificate for your website and that all HTTP requests are redirected to HTTPS? If so, then please implement the steps in the `Use Varnish(TM) with SSL` guide, although I see in your bnsupport bundle the changes are applied, except in the `bitnami-ssl.conf` where you added the code snippet twice: one for port 80 and another one for port 81. Please update this config and restart Apache.

I also see some WordPress plugins are failing, so maybe the issues you are getting are because of that. Can you check it?

```
[Sun Sep 04 09:57:20.874180 2022] [proxy_fcgi:error] [pid 4639:tid 139703949653760] [client 41.39.37.105:53710] AH01071: Got error 'PHP message: PHP Warning:  Attempt to read property "ID" on null in /bitnami/wordpress/wp-content/plugins/elementor/core/base/document.php on line 250PHP message: PHP Warning:  Attempt to read property "ID" on null in /bitnami/wordpress/wp-content/plugins/elementor/core/base/document.php on line 250'
````

Initially, Varnish will serve and cache all requests to port 80, no matter if it is the top domain or a subdomain (remember Apache is now listening at port 81), but you can configure some URLs/domains to not be cached. However, I don't think it will have any effect in this issue

https://docs.bitnami.com/aws/apps/wordpress/administration/configure-use-varnish/#block-specified-urls-from-being-cached-by-varnishtm

According to [this website](https://info.varnish-software.com/blog/one-vcl-per-domain), there is a way of configuring Varnish for specific domains only.

Can you also try to restart Varnish just in case it is also caching your error responses?

```
sudo /opt/bitnami/ctlscript.sh restart varnish
```

**Comment by hussien-ibrahem** [comment]
Hi @gongomgra 

I've already done all these steps and your edits and the same problem.
 **note that I tried same steps on another website and it works correctly** 

kindly check bndiagnostic : 138c4b5c-d147-2765-6cc0-04bc730edbf8
what is the problem here and how can I solve it

**Comment by hussien-ibrahem** [comment]
### Information that may help you to understand the problem
1 month ago I did steps in this [guide](https://docs.bitnami.com/google/apps/wordpress/configuration/configure-varnish/) until ( **Open port 81 in the server firewall.** ) step but the website didn't work on port 81 or 80 so I started to take an image for the instance and test it on a subdomain to not make the website down.

-Now, should I continue the steps I've done before or repeat them from the beginning?
- I started doing all steps again on a subdomain and all my tests failed, I don't know the reason but when I make the same steps from scratch on another website it works correctly.
- i found that in main website instance in /opt/bitnami/varnish/var/varnish/ there's a folder with main instance name and when i create new instance to test varnish installation in /opt/bitnami/varnish/var/varnish/ a new folder with the new instance name created **beside main instance name**.   so do you think this is the problem?

**Comment by gongomgra** [comment]
Hi @hussien-ibrahem,

Thanks for your message. Unfortunately, I can't find any error in your Apache configuration (from the bnsupport bundle), but if performing the steps in a fresh new machine works fine, it seems to me it has to be an error somewhere in the old instance. My suggestion here is to migrate your WordPress data to the new instance where Varnish works fine (once Varnish has been configured).
