### ISSUE TITLE
[WordPress] 404 Error Page Not Found

### ISSUE THREAD

**Issue by lmorata** [bitnami/vms#257]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

91115254-9ea5-f224-085f-ab8b1e4346bc

### bndiagnostic output

**[Apache]**
```
 PageSpeed Serf fetch
failure rate extremely high; only 0 of 78 recent fetches fully successful; is
fetching working?

 PageSpeed Serf fetch
failure rate extremely high; only 0 of 78 recent fetches fully successful; is
fetching working?
```

We suggest disabling pagespeed and check if that improves the behavior. Please
check the following guide to disable Pagespeed:

https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespe
ed/#disable-pagespeed

Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:

```
apache2: Syntax error on line 66 of /opt/bitnami/apache2/conf/httpd.conf: Cannot
load modules/mod_mpm_event.so into server: libiconv.so.2: cannot open shared
object file: No such file or directory
```
Please check the configuration.

A high number of incoming requests originate from one or more unique IP
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

**[Connectivity]**
```
Press [Enter] to continue:
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
```
**[Php]**

The following error appears in the
/opt/bitnami/php/var/log/php-fpm.log:

```
[17-Aug-2022 12:29:43] WARNING: [pool www] server reached max_children setting
(5), consider raising it
```
This error usually indicates PHP script execution is slow due to busy server
resouces or buggy scripts. Please check the following guide to increase the
number of PHP-FPM child processes:

https://docs.bitnami.com/general/apps/wordpress/configuration/configure-ph
pfpm-processes/

### bndiagnostic was not useful. Could you please tell us why?

Tired all solutions, issue persists

### Describe your issue as much as you can

404 Page not loading for any sites only accessible https://intra.episource.com/wp-admin/

**Comment by gongomgra** [comment]
Hi @lmorata,

Thanks for using Bitnami. I see many errors in your Apache log file and I guess they may be preventing the WordPress website to be rendered properly and/or causing these 404 responses. We also recommend you to open a new question in the official WordPress forums for further help on how to debug these issues, as they must be related to your customizations or installed plugins

https://wordpress.org/support/forums/

**Comment by lmorata** [comment]
I am no longer seeing error_log being updated

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
