### ISSUE TITLE
[Magento] Class not found

### ISSUE THREAD

**Issue by tmageebtr** [bitnami/vms#258]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

425124a0-a3ed-1c9f-83ef-d7b0bfd09c5b

### bndiagnostic was not useful. Could you please tell us why?

No errors shown

### Describe your issue as much as you can

Added MagePlaza SMTP module via composer.  Config screen is blank.  Error in log below.  The same class not found issue happens with other plugins I have tried.  All plugins have worked previously on a Magento 2.3 system upgraded to 2.4.

I have tried Bitnami Magento on Lightsail (2.4.3) and AWS (2.4.5) with same result.

I have tried removing all cache and rerunning setup:di:compile as well as removing and re-adding the plugin.

[2022-08-17T23:44:26.362371+00:00] main.CRITICAL: Class "Mageplaza\Smtp\Block\Adminhtml\System\Config\Host" does not exist [] []
[2022-08-17T23:44:26.362768+00:00] main.CRITICAL: ReflectionException: Class "Mageplaza\Smtp\Block\Adminhtml\System\Config\Host" does not exist in /bitnami/magento/vendor/magento/framework/Code/Reader/ClassReader.php:34

**Comment by gongomgra** [comment]
Hi @tmageebtr,

Thanks for using Bitnami. We have a guide for installing SMTP in Magento, but it mentions installing another module. Can you check if following the steps in our guide works for you?

https://docs.bitnami.com/aws/apps/magento/configuration/install-extension-smtp/

We also recommend you to open a new question in the official Magento forums about this error, as according to the bndiagnostic bundle you shared, the mentioned file exists on your file system and the permissions look fine:

```
/bitnami/magento/vendor/magento/framework/Code/Reader:
total 48
drwxrwxr-x 2 bitnami daemon 4096 Aug 18 00:32 .
drwxrwxr-x 7 bitnami daemon 4096 Aug 18 00:32 ..
-rw-rw-r-- 1 bitnami daemon 8479 Aug 18 00:32 ArgumentsReader.php
-rw-rw-r-- 1 bitnami daemon  788 Aug 18 00:32 ClassReaderInterface.php
-rw-rw-r-- 1 bitnami daemon 4004 Aug 18 00:32 ClassReader.php
-rw-rw-r-- 1 bitnami daemon 4844 Aug 18 00:32 NamespaceResolver.php
-rw-rw-r-- 1 bitnami daemon  602 Aug 18 00:32 ScalarTypesProvider.php
-rw-rw-r-- 1 bitnami daemon 4333 Aug 18 00:32 SourceArgumentsReader.php
```

Did you get any error installing the plugin? Notice `/opt/bitnami/magento` is a symbolic link to `/bitnami/magento` folder. I'm afraid I don't know how it works internally, but is it possible that the plugin doesn't support this feature and was not able to update the required file?
