### ISSUE TITLE
WordPress Certified to NGINX and SSL / EC2  DB / Lambda (AWS)

### ISSUE THREAD

**Issue by rob585-538** [bitnami/vms#259]
### Describe your issue as much as you can

Hi,

I want access to MySQL DB for Wordpress on the EC2 via Lambda - i.,e outside of the EC2

We have an EC2 running Wordpress NGINX and SSL. We are using the default MySQL on the EC2.   We want to automate process onto the DB via Lambda. I.e to auto ingest and update data into the tables.  When we have put the WordPress DB on RDS this is very simple and we have over 100 lambda functions moving data around and accessing the DBs so this is not an issue.

However, when the DB is still on the EC2 we can't "access" it from outside the EC2. We have put the lambda function in the security group, opened up the right ports, using the right creds=- but we can't connect.  Are the ports closed by the EC2? Is there a firewall?  

How do we acess the DB from outside of the EC2 is reside on?

Thanks

Rob

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
