### ISSUE TITLE
[<application>] <title>Generate static sitemaps via server cron job 

### ISSUE THREAD

**Issue by huangdaima** [bitnami/vms#261]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

51f4ebc9-4869-004c-b132-1c4ff47a6d4f

### bndiagnostic was not useful. Could you please tell us why?

Generate static sitemaps via server cron job 

### Describe your issue as much as you can

 
Hello,  

I'm running your WordPress on aws ec2 

 My site has millions of links, Yoast SEO breaks your sitemap up into chunks. On this site, the individual chunks were loading, but the sitemap index (its “table of contents”) would not load, and was giving a timeout error。

I want to automatically generate a static sitemap index every 12 hours via the server cron job 

And, modify a rewrite in the site’s Nginx config that would make the /sitemap_index.xml path point to the cron-created static file, instead of resolving to Yoast SEO’s dynamic generation URL.  

 This is the post I found, my situation is similar to it, but it does not use the bitnami stack : https://markjaquith.wordpress.com/2018/01/22/how-i-fixed-yoast-seo-sitemaps-on-a-large-wordpress-site/

What should I do?  
 
Thank you for your time,  
Huang

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
