### ISSUE TITLE
Bitnami Wordpress EC2 Instance - Egress Traffic?

### ISSUE THREAD

**Issue by archprof8** [bitnami/vms#264]
### Describe your issue as much as you can

Hi,
**Situation**: I have an AWS EC2 Instances from Bitnami AMI at Amazon Market Place. EC2 Instance has been hosting a Wordpress Public WebSite. 

**Question**: Bitnami AMI instance has got any pre-built agents on EC2 that requires egress traffic to Internet? If yes, then what are those?
Traffic could be status of server or stats to bitnami to charge accordingly etc.?

Please confirm.

Thank You,
AP

**Comment by mdhont** [comment]
No, Bitnami images do not have its own agents installed that collect and upload information. 

> Traffic could be status of server or stats to bitnami to charge accordingly etc.?

In fact using Bitnami is free of charge, the fees are charged by the cloud providers.

**Comment by archprof8** [comment]
okay. 
I see, R53 Resolver Query Logs and that shows traffic to stats.bitnami.org. 
I am not 100% sure if that's being triggered by AWS Service or Unknown Bitnami Agent on the EC2 Instance. Any clue?
When I lookup on that address stats.bitnami.org, it gives me the IP / IP Location of AWS at US. Does that mean, its AWS initiated egress traffic from my EC2 instance? But Why? Egress traffic also gets charged by AWS in that case?

Second question is: in case of software patches and upgrades to the components of Wordpress by Bitnami (like Php, DB, Plugins, Themes etc) that would require egress traffic from EC2 to Internet., Is there a pattern / design that's been suggested to configure securely for outbound traffic from EC2 instance and make sure that's not internet initiated traffic?

#aws #querylogs #bitnami #egresstraffic #awssolution #design

**Comment by mdhont** [comment]
As it turns out we do collect some stats (some basic system info), sorry for the confusion, I wasn't aware of this. The good thing is you can turn if off 😄:

https://docs.bitnami.com/aws/faq/get-started/understand-bitnami-agent/

I found this info about egress costs:

https://aws.amazon.com/blogs/apn/aws-data-transfer-charges-for-server-and-serverless-architectures/#:~:text=The%20returning%20egress%20(E)%20traffic,have%20substantially%20different%20egress%20pricing.

**Comment by archprof8** [comment]
> As it turns out we do collect some stats (some basic system info), sorry for the confusion, I wasn't aware of this. The good thing is you can turn if off 😄:
> 
> https://docs.bitnami.com/aws/faq/get-started/understand-bitnami-agent/
> 
> I found this info about egress costs:
> 
> https://aws.amazon.com/blogs/apn/aws-data-transfer-charges-for-server-and-serverless-architectures/#:~:text=The%20returning%20egress%20(E)%20traffic,have%20substantially%20different%20egress%20pricing.

Thank you for confirming back on this.
This post can be closed now. Thank you :)
