### ISSUE TITLE
Moodle Upgrade - New version out

### ISSUE THREAD

**Issue by L3dge** [bitnami/vms#266]
### Describe your issue as much as you can

Using Bitnami LMS powered by Moodle(TM) LMS. There is a new version available and it contains security fixes. How do we upgrade the current moodle instance with the security fixes. Is there an automated process for the service?

**Comment by umquat** [comment]
Subscribing

I just upgraded to 4.0.3 following the instructions in https://docs.bitnami.com/virtual-machine/apps/moodle/administration/upgrade/

**Comment by mdhont** [comment]
To upgrade to the latest Bitnami Moodle version you need to launch a new instance with the latest version and then migrate the data there:

https://docs.bitnami.com/aws/how-to/migrate-moodle/
