### ISSUE TITLE
Bitnami AWS Lightsail Wordpress - How to setup SSL now on the instance so it will work in the future if I add a load balancer

### ISSUE THREAD

**Issue by geeftgeennaam** [bitnami/vms#268]
### Describe your issue as much as you can

Hey! 

I'm currently setting up a new Bitnami WordPress site in Lightsail.  I want to on SSL to secure the connection to the instance/webserver.  for right now, with the small traffic, I want to just set the SSL on the instance.  However, in the future as the traffic to the site grows, I want to be able to add a Lightsail load balancer and then have SSL set on the load balancer.  

In both cases, I want to force http to https.  

Can you please send instructions on how to: 

1.  Create a certificate on LS Instance - which will allow this to work also in the future after I put this instance (these instances in the future) behind a load balancer.  
2. how to install the certificates on the load balancer - including any changes I would need to make to the certificate that is on the instance. 

Thanks! 

Geeftgeennaam

**Comment by mdhont** [comment]
Please check the following guide:

https://docs.bitnami.com/aws/how-to/configure-elb-ssl-aws/

**Comment by geeftgeennaam** [comment]
Hi Michiel -

thanks for the response. However, as I mention in my email, I'm using Lightsail. Lightsail instances do not show up in the EC2 console. Therefore, the document you sent does not address my question. can you send me the corresponding set of instructions relating to a Lightsail instance and Lightsail loadbalancers?

also, specifically what I'm looking for is:

-  Can I create a certificate on my Lightsail instance NOW before I have a load balancer?
- If I create a certificate now on my Lightsail instance, will that cause problems when I create the Lightsail Load balancer?
- Will I need to make any changes to my Lightsail instance (i.e. delete the instance certificate) before I add HTTPS on my Lightsail load balancer?

Can you please answer those questions?

Thanks!

geeftgeennaam
------- Original Message -------

**Comment by mdhont** [comment]
> Can I create a certificate on my Lightsail instance NOW before I have a load balancer?
   If I create a certificate now on my Lightsail instance, will that cause problems when I create the Lightsail Load balancer?

I suggest asking AWS Lightsail support, I wouldn't think these things would be a problem.

> Will I need to make any changes to my Lightsail instance (i.e. delete the instance certificate) before I add HTTPS on my Lightsail load balancer?

You need to follow the last steps (that should be executed through an SSL connection) in the guide I shared with you after adding HTTPS on your loadbalancer.
