### ISSUE TITLE
Configuring SSL Certificates using International Domain Names

### ISSUE THREAD

**Issue by geeftgeennaam** [bitnami/vms#269]
### Describe your issue as much as you can

I am going to be generating my first certificates for a non Latin alphabet domain.  Namely, one in Bulgarian therefore in the Cyrillic alphabet.  

I want to secure connections using SSL and therefore I have to add a certificate.  However, can you please send instructions as to how this works for IDNs?  

I believe that I need to: 

1.  Create the certificate 
2. add the domains using PUNYCODE for each domain/subdomain

Is this correct?  

Thanks! 

Geeftgeennaam

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.

**Comment by geeftgeennaam** [comment]
Hi Michiel -

Actually, I don't really agree with your contention that this doesn't relate to Bitnami.

I'm currently trying to using the bncert-tool to create ssl certificates on my Lightsail instance. I am building a website for a Bulgarian customer that wants to use Cyrillic domains for example: българия.бг.

Using an IDN to puny code converter, I have converted the above IDN to the following puny code: xn--80abgvm6a7d2b.xn--90ae

upon launching the bncert-tool, when prompted for the domains I have tried to enter

xn--80abgvm6a7d2b.xn--90ae

or

българия.бг

both of them throw the same error: please enter a valid domain.

I believe the puny code should be the domain that is entered however NEITHER of them is working with the bncert-tool

What is the correct way to enter the domain into the bncert-tool to create the certificates?

Thanks!

------- Original Message -------

**Comment by mdhont** [comment]
The bncert tool is written to cover the most basic scenarios for issuing a certificate. It uses the lego tool in the background so you could also try the manual approech:

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

If that also doesn't work I recommend asking in the Let's Encrypt community:

https://community.letsencrypt.org/t/idn-support-enabled/21469

**Comment by geeftgeennaam** [comment]
HI Michiel -

thanks for this. The manual approach worked!

You can close this case!

Cheers

Geefgeennaam
------- Original Message -------
