### ISSUE TITLE
Issue in SSL setup in Bitnami jasper server AWS AMI

### ISSUE THREAD

**Issue by vivektr2007** [bitnami/vms#270]
### Describe your issue as much as you can

Hi team,
I am using bitnami image for jasper server setup. I had done changes for ssl setup in server.xml file inside tomcat conf folder. Still my application is showing not secure. Below is the code block I have used in server.xml file.

**<Connector port="8443"  maxThreads="150" minSpareThreads="25" maxSpareThreads="75" enableLookups="false" disableUploadTimeout="true" acceptCount="100" scheme="https" secure="true" SSLEnabled="true" clientAuth="false" sslProtocol="TLS" keystoreFile="/opt/bitnami/tomcat/conf/**********.pfx" keystorePass="*******" />**

**Comment by mdhont** [comment]
Can you check this guide?

https://docs.bitnami.com/installer/apps/jasperreports/administration/enable-ssl-tomcat/
