### ISSUE TITLE
O servidor [wordpress] recusou nossa chave no Filezilla[<application>] <title>

### ISSUE THREAD

**Issue by jntebaldi** [bitnami/vms#271]
### Platform

VMware Marketplace

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

29244f49-157c-5f7a-96e0-de726645be88

### bndiagnostic was not useful. Could you please tell us why?

nao achei nada.

### Describe your issue as much as you can

I'm having trouble connecting FTP.

I create a new Lightsail Wordpress Multisite, I leave the ip created low or certified and connected to FTP.

Ae I change the ip to static IP and I can no longer connect to FTP.

I get this error: FATAL ERROR: No supported authentication method available (server sent: public key)

**Comment by mdhont** [comment]
Please check the following guide:

https://docs.bitnami.com/aws/faq/administration/upload-files/
