### ISSUE TITLE
[LAMP] Where to the SSH keys end up when added to the appliance during deployment via vSphere? 

### ISSUE THREAD

**Issue by swinster** [bitnami/vms#273]
### Platform

VMware Marketplace

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

41b439dc-3f78-9c25-8c39-5de99f345aa5

### bndiagnostic was not useful. Could you please tell us why?

not relevant in this case

### Describe your issue as much as you can

Hi,

A relatively simply one I think but could not see the question asked previously. When deploying a VMware Marketplace appliance, you have the option of uploading an SSH key for the Bitnami user. See step 2 at https://docs.bitnami.com/vmware-marketplace/get-started-vmware-marketplace/#step-2-launch-a-bitnami-wordpress-virtual-machine-from-the-template, which states:

> Define the contents of the SSH public key that will be used to connect to the virtual machine. 

Where does this key get stored? 

I would expect it to be copied to the `/home/bitnami/.ssh` folder and for SSH access to be both enabled and set up for key-based authentication. None of these things happen -  the ~/.ssh folder is not created, the SSH server is not enabled, not is it configured for key-based authentication. 

Am I misunderstanding the purpose of this option?

**Comment by swinster** [comment]
FYI - the version of the appliance is 8.0.22_1_ro1

**Comment by mdhont** [comment]
That's strange. How are you connecting to the instance? Can you check the env variables?

```
env | grep SSH

```

And the contents of ssh_config?

```
cat /etc/ssh/ssh_config
```

**Comment by mdhont** [comment]
We are investigating it, I will update this thread with further information.
