### ISSUE TITLE
[WordPress with NGINX and SSL] cannotverifycopysource 

### ISSUE THREAD

**Issue by ken-afh** [bitnami/vms#274]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

16ced6ac-d01e-003d-3334-b83416000000

### bndiagnostic output

Last operation failed (Create virtual machine)

CannotVerifyCopySource (404): The specified blob does not exist. RequestId:16ced6ac-d01e-003d-3334-b83416000000 Time:2022-08-25T03:41:33.4275754Z

### bndiagnostic was not useful. Could you please tell us why?

Can't find anything related to deployment errors

### Describe your issue as much as you can

Using the Azure Launchpad. I select **WordPress with NGINX and SSL** and then **Launch**

I see progress up to ~54% and then I get the status shown in the attached image. When I look in the Azure portal, I see that a resource group and a storage group + account have been created, but nothing else.

![image](https://user-images.githubusercontent.com/44118974/186571469-faa719e6-166f-4a7a-8cce-11e6878bcab3.png)

**Comment by ken-afh** [comment]
Reproducible.

It happened several times yesterday - and with two different images (WordPress & WordPress with NGINX and SSL.) Just tried again, and it failed today.

***@***.***

***@***.***

***@***.***
________________________________

**Comment by danielberma** [comment]
Cant help, but can only confirm I have the very same issue with Wordpress. Had the same issue with Odoo earlier.

**Comment by danielberma** [comment]
Any updates? Seems pointless for me to open up my own case with the same problem.

**Comment by ken-afh** [comment]
Still broken
![image](https://user-images.githubusercontent.com/44118974/187095023-d2b76496-e288-4fca-b3d2-4a9775b5ed1f.png)
![image](https://user-images.githubusercontent.com/44118974/187095063-daddbf64-bdfc-4112-af62-af4af0e3c391.png)

**Comment by mdhont** [comment]
I've reproduced the issue. We will investigate it and I will update this thread with further information.

**Comment by danielberma** [comment]
Any luck on solving this? Was hoping to use it :)

**Comment by mdhont** [comment]
We are still working on it. I will let you know when it's fixed.

**Comment by carlossm** [comment]
We found a problem in the ingestion process of the new cloud image versions in our Launchpad service. This left an old WordPress image version no longer available in the storage as published and caused the error on launch.

We have just applied a fix and verified that the cloud image is now properly updated and the virtual machines are created correctly.
