### ISSUE TITLE
WordPress AMI on AWS - multithread

### ISSUE THREAD

**Issue by hichotu** [bitnami/vms#278]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

69f1d09e-0441-2bef-b8c7-ef3489c7e0ef

### bndiagnostic output

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ? Processes: Found possible issues
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

Press [Enter] to continue:
[Mariadb]

Found recent error messages in the MariaDB error log:
```
2022-08-27 16:54:14 203 [Warning] Aborted connection 203 to db:
'bitnami_wordpress' user: 'bn_wordpress' host: 'localhost' (Got an error reading
communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Processes]

One or more component's processes are not running:
```
apache not running
```
You can try to restart the process with the following command:

 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME
Press [Enter] to continue:

[Apache]

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf:
module log_config_module is built-in and can't be loaded
```
Please check the configuration.

A high number of incoming requests originate from one or more unique IP
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

System Apache is running:
```
www-data 88335 0.0 0.0 3432 168 ? Ss 16:54 0:00 /usr/bin/htcacheclean -d 120 -p
/var/cache/apache2/mod_cache_disk -l 300M -n root 92962 0.0 0.0 7108 3948 pts/0
T 17:02 0:00 nano /opt/bitnami/apache2/conf/httpd.conf
```
Press [Enter] to continue:
 If Bitnami Apache isn't starting this is the most likely cause. Please run the
following command to stop it:

### bndiagnostic was not useful. Could you please tell us why?

i cud not figure out how to enable multi-threading

### Describe your issue as much as you can

my AWS instance has 8 cores, however this bitnami application is able to utilise only 1 out of these 8, slowing down our processing. How do we configure this instance to use all the 8 cores?

**Comment by mdhont** [comment]
I recommend checking the amount of servers Apache is using: 

https://serverfault.com/questions/310937/setting-up-apache-to-use-multiple-cores
