### ISSUE TITLE
Bitnami MongoDB with Replication on GCP Missing

### ISSUE THREAD

**Issue by tupham81** [bitnami/vms#279]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

n/a

### bndiagnostic was not useful. Could you please tell us why?

Not applicable

### Describe your issue as much as you can

The MongoDB with Replication deployment is missing from the list of VM instances available in the GCP Marketplace. 

Your instructions reference it and is a dependency for the GCP Multitiered VMs.
https://docs.bitnami.com/google-templates/get-started/

**Comment by mdhont** [comment]
Unfortunately the MongoDB multi-tier solution is no longer available on GCE. We will adapt our documentation to reflect this.
