### ISSUE TITLE
[<Wordpress Multisites>] <502 Bad Gateway - Frequently - almost everyday>

### ISSUE THREAD

**Issue by Ham2222** [bitnami/vms#280]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d088a601-3ba6-58e1-3119-70630999d7f5

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ? Processes: Found possible issues
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Resources]

Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem Size Used Avail Use% Mounted on /dev/nvme0n1p1 9.7G 8.6G 549M 95% /
```
Please check your cloud provider's documentation for more information.

[Connectivity]
Press [Enter] to continue:

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2022-08-28 18:19:42 8 [Warning] Aborted connection 8 to db: 'bitnami_wordpress'
user: 'bn_wordpress' host: 'localhost' (Got an error writing communication
packets)

```
Please check the following guide to troubleshoot MariaDB issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Processes]

One or more component's processes are not running:
Press [Enter] to continue:
```
apache not running mariadb not running php-fpm not running
```
You can try to restart the process with the following command:

 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Wordpress]

Some files don't have the expected permissions Please check the following guide:

https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Aug 28 18:19:40.257712 2022] [core:error] [pid 92782:tid 139759284373248]
[client **ip_address**:59068] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Sun Aug 28 18:19:40.296178 2022] [core:error] [pid 98768:tid 139759753938688]
Press [Enter] to continue:
[client **ip_address**:45810] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Sun Aug 28 18:19:44.175283 2022] [core:error] [pid 92782:tid 139759259195136]
[client **ip_address**:55982] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

N/A

### Describe your issue as much as you can

Keep getting 502 Bad Gateway error (almost everyday) after restating bitnami services

**Comment by mdhont** [comment]
According to the bndiagnostic tool's output the machine is low on resources. I recommend using a more powerful instance:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-resize.html

**Comment by ambergoldstain** [comment]
I've developd a game <a href="grazeapk.com/wwe-2k20-apk/">wwe 2k20</a> based on the sport of wrestling in which i'am getting payment gateway issues
