### ISSUE TITLE
[<NGINX>] <How to create git repo to manage changes to NGINX conf>

### ISSUE THREAD

**Issue by gwhizoftv** [bitnami/vms#283]
### Describe your issue as much as you can

Hi, I have a new AWS EC2 with the Bitnami NGINX AMI. The main user is bitnami. There is no "admin" user defined. I'm ssh'd into the ec2 as bitnami. I cd to opt/bitnami/nginx. I try to create a git repo there to track my upcoming changes. I use 
`git init`
but I get permission denied because the folder is owned by root and group root.
I can sudo to root and create a git repo but git doesn't like to use root and gives errors like:
`bitnami@ip-172-31-37-26:/opt/bitnami/nginx$ git status
fatal: detected dubious ownership in repository at '/opt/bitnami/nginx'
To add an exception for this directory, call:

	git config --global --add safe.directory /opt/bitnami/nginx
`
How do I manage my changes with git on this AMI?

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.

**Comment by gwhizoftv** [comment]
Why does Bitnami ship the NGINX installed as root ?

**Comment by mdhont** [comment]
Because it needs to listen to ports below 1024, but I don't see how that's relevant to the issue. Could you give further information?
