### ISSUE TITLE
Wordpress - Can't Create new Server

### ISSUE THREAD

**Issue by Teteia** [bitnami/vms#284]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

-

### bndiagnostic was not useful. Could you please tell us why?

-

### Describe your issue as much as you can

While creating a new Server i receive this error:

 Last operation failed (Create virtual machine)
CannotVerifyCopySource (404): The specified blob does not exist. RequestId:3a1a0980-301e-00b0-0566-bc7984000000 Time:2022-08-30T11:50:48.5192259Z

**Comment by mdhont** [comment]
We are handling this issue [here](https://github.com/bitnami/vms/issues/274). I'm proceeding to close this one.
