### ISSUE TITLE
[<Community Forum>] <Link to Community on all bitnami footer pages is wrong>

### ISSUE THREAD

**Issue by gwhizoftv** [bitnami/vms#285]
### Describe your suggestion as much as you can

Hi, On all the Bitnami web pages, there is a link to Community under the Support column. When clicking the link, it brings us to GIthub, instead of to a Community forum.
Please update the links to take us to a community forum where we can share common experiences and information about working with Bitnami.

https://bitnami.com/stack/nginx/cloud

**Comment by mdhont** [comment]
We've moved support to Github since July 2022. If you have any Bitnami related question you can ask it here.
