### ISSUE TITLE
Bitnami LAMP stack enable curl issue

### ISSUE THREAD

**Issue by jayreis** [bitnami/vms#286]
### Describe your issue as much as you can

I am using the Binami PHP8 LAMOP STACK image on my AWS Lightsail. 
My issue is I am unable to get php curl enabled. I seem to have a bunch of php.ini files all over the server in diffiferent locations. So I edited all of them removing the ; from the line that read extension=curl. I then restarted the instance. However my php file is still giving me the error saying

caught Exception: Shippo needs the CURL PHP extension.
When I run a phpinfo() I see my path to the ini file is /etc/php/8.0/apache2/php.ini However when I do a which php command I am giving a path like this /opt/bitnami/php/bin/php when I do a php -v I am also seeing it say PHP 7.4.27 so my php info file seems to say I am using php7.8 and my CLI feels i am using php7.4 which could be part of my issue. Any suggestions on how to fix this? my other issue is I am having a hard time getting to the path /etc/php/8.0/apache2/php.ini I simply can not find a folder with 8.0 in it

I am just looking for guidance on where/how to get to the path that seems to be the php 8.0 path as I am unable to find a 8.0 folder in the above mentioned path

**Comment by mdhont** [comment]
The php.ini file used should be `/opt/bitnami/php/etc/php.ini`. Maybe you have another version of php installed. Can you check?

    which php

The output should be:

    /opt/bitnami/php/bin/php

**Comment by jayreis** [comment]
When I run the Which PHP command I see
/opt/bitnami/php/bin/php

When Look at the path to PHP in a phpinfo.php file I see the path of
/etc/php/8.0/apache2/php.ini 

When I run the command php -v it says
PHP 7.4.27 

which is why I question the php path in my phpinfo() page

**Comment by mdhont** [comment]
So the file /etc/php/8.0/apache2/php.ini does not exist? It's not clear to me where phpInfo gets this from. What is the output of this command:

     php -i  | grep ini
