### ISSUE TITLE
httpd full CPU's use

### ISSUE THREAD

**Issue by dlievano** [bitnami/vms#287]
### Name and Version

Bitnami LAMP 7.4.9-2 

### What steps will reproduce the bug?

I created a new instance from an image where I have a social network application but I can see all the CPU are on 100% of use I don't know why always is executing this command. What is the purpose of this? 

/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf

### What is the expected behavior?

Have minimum use of CPU's 

### What do you see instead?

![image](https://user-images.githubusercontent.com/66698658/187489732-19702735-b29f-494d-aa5a-0455d8b4befc.png)

### Additional information

I have supervisor to execute Laravel cron but I deactivate it before, and I had some cron jobs configure whit crontab to renew the SSL certificates.

**Comment by mdhont** [comment]
Those are different Apache child processes, which Apache spawns based on your configuration and the workload of your application. The following blog post might be of help to improve the performance.

https://blog.bitnami.com/2014/06/performance-enhacements-for-apache-and.html
