### ISSUE TITLE
[bitnami] How do I generate CSR to renew SSL Cert

### ISSUE THREAD

**Issue by maschooloxford** [bitnami/vms#288]
### Describe your issue as much as you can

Hi,

I've inherited a Bitnami Wordpress Stack running on Windows Server 2019 Datacenter version 1809 build 17763.3287, but with no documentation. I have no prior experience with Wordpress - Bitnami or otherwise. I do have prior experience with Windows IIS.

Would anyone be able to please direct me to, or provide to me, a step-by-step guide on generating a CSR and installing a SSL cert?

Thanks in advance, Mark

**Comment by mdhont** [comment]
We have a tool that issues and configures a new Let's Encrypt certificate which will also configure automatic renewal:

https://docs.bitnami.com/aws/faq/administration/generate-configure-certificate-letsencrypt/
