### ISSUE TITLE
Moodle Bitnami Multi Tiers Database Version not Updating to the Current Version on Azure

### ISSUE THREAD

**Issue by adebareshowemimo** [bitnami/vms#289]
### Describe your issue as much as you can

I have an instance of Moodle Bitnami Multi Tiers installed on Azure with MYSQL Managed DB.

On Azure Database Management the MYSQL version is 5.7 but on the application the MYSQL is 5.6.x. When you SSH to the Database from the frontend of Moodle Application, the Database version is 5.6.x. 

I need to change the MYSQL version to reflect the updated version of the MS MYSQL version.

Thanks

**Comment by mdhont** [comment]
Unfortunately with Bitnami updating individual components is not possible. I recommend launching a new deployment with the latest versions and then migrate the data there.
