### ISSUE TITLE
WordPress Website not loading at all; all commands in console slow to perform

### ISSUE THREAD

**Issue by smnorton** [bitnami/vms#290]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

I need to send in a PM; failed to upload to bitnami servers

### bndiagnostic was not useful. Could you please tell us why?

don't have access to the output in console

### Describe your issue as much as you can

My website wouldn't load - the server wouldn't respond - so I first attempted to restart all services.

I received an fatal error message indicating memory out of limit and ended up rebooting my lightsail instance - the website slowly came back up but almost immediately went down again.

I ran the bndiagnostic tool and it took a LONG time to run. I received a message in the console saying the support bundle file was successfully created, but the automatic upload to the servers failed. I have a Google Drive link available for a Bitnami Support agent based on instructions here: https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

Please let me know how to send this link to you securely.

I am trying to figure this out on my own. I have 13911 MB free disk space; 634 MB machine_swap_memory, 482 MB machine_total_memory

I checked the php-fpm.log and see this warning:
WARNING: [pool www] server reached max_children setting (5), consider raising it

Have I depleted my server resources and just need a bigger instance?

**Comment by mdhont** [comment]
It seems the machine is low on resources, most likely RAM, can you check?

    free -m

If the available memory is low I recommend upgrading the instance:

https://docs.bitnami.com/aws/faq/administration/change-server-type/

**Comment by smnorton** [comment]
Thank you, Michiel. The RAM available RAM was really low (~15 MB RAM available, ~60 MB Swap) when I checked free -m after posting on GitHub. 

I upgraded the instance and haven't had further  performance issues but just wanted to be sure there's want something else going on.

Thank you for your reply.

**Comment by smnorton** [comment]
I was wrong, @mdhont . The website is down completely and only comes up after rebooting my instance.

    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

Recent Apache error/warning:
```
[Wed Sep 07 13:36:37.492758 2022] [proxy_fcgi:error] [pid 1481:tid 
140319490299648] (104)Connection reset by peer: [client **ip_address**:50155] 
AH01075: Error dispatching request to : 
 [Wed Sep 07 13:36:37.662806 2022] [proxy:error] [pid 1481:tid 140319366559488] 
(2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain

RESOURCES: total used free shared buff/cache available Mem: 987 629 66 95 292 112 Swap: 634 11 623
^ I doubled the RAM and it ran fine for a few days

bndiagnostic ID: 652c8ec5-21d9-9ecf-42b3-6902e19523a1

**Comment by mdhont** [comment]
There seems to be an error with a plugin (gravityforms):

```
  [Sun Sep 04 03:37:21.08xxxxxx 2022] [proxy_fcgi:error] [pid 7629:tid 139715378259712] [client 89.xx.xxxx.115:60623] AH01071: Got error 'PHP message: PHP Fatal er  ror:  Uncaught TypeError: stripos(): Argument #1 ($haystack) must be of type string, array given in /bitnami/wordpress/wp-content/themes/Avada-Child-Theme/fun  ctions.php:296\nStack trace:\n#0 /bitnami/wordpress/wp-content/themes/Avada-Child-Theme/functions.php(296): stripos()\n#1 /bitnami/wordpress/wp-content/themes  /Avada-Child-Theme/functions.php(306): strpos_arr()\n#2 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(309): keywords_check()\n#3 /opt/bitnami/wordpress  /wp-includes/plugin.php(191): WP_Hook->apply_filters()\n#4 /bitnami/wordpress/wp-content/plugins/gravityforms/gravityforms.php(6066): apply_filters()\n#5 /bit  nami/wordpress/wp-content/plugins/gravityforms/form_display.php(1866): gf_apply_filters()\n#6 /bitnami/wordpress/wp-content/plugins/gravityforms/form_display.  php(83): GFFormDisplay::validate()\n#7 /bitnami/wordpress/wp-content/plugins/gravityforms/gravityforms.php(634): GFFormDisplay::process_form()\n#8 /opt/bitnam  i/wordpress/wp-includes/class-wp-hook.php(307): GFForms::...', referer: https://www.skatelandsofamerica.com/contact-us/
```

You could try to disable all plugins and then reenable them one by one:

    wp plugin deactivate --all

**Comment by smnorton** [comment]
Thanks again, sir. I've identified the cause of that error and removed the offending function from my functions.php that broke after Gravity Forms was updated. I appreciate you helping me identify that.

I cleared the error log on my end and have monitored it - no new fatal errors are being recorded. I am still noticing really high page load times. Could there be possibly something else I need to look at?

**Comment by mdhont** [comment]
Maybe this guide will be of use:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/optimize-bitnami-wordpress/

**Comment by smnorton** [comment]
Thanks again, Michiel, for your responses. I have launched a new instance with increased resources and still finding errors in the Apache log. 

I re-ran the diagnostic tool and code is below:
d4bd62da-4ee3-249a-6447-6627f1e40292

Files are being created in the system's temporary directory. It seems this is occurring when WordPress pages or posts are edited.

**Comment by mdhont** [comment]
That's only a PHP notice message, it shouldn't matter. Is the application giving any problems, saving posts etc?

**Comment by smnorton** [comment]
I’m not seeing any issues on the front end after making edits, no, but I’m trying to understand why everything comes to a slow crawl after the instance is running for a period of time - usually after a day or so. This newest instance has only been running since last night and while I haven’t had any issues this far, I’ve been concerned with the entire site going down and an inability to even access via SSH without a hard reboot of the instance. On Sep 13, 2022, at 11:28 AM, Michiel ***@***.***> wrote:﻿
That's only a PHP notice message, it shouldn't matter. Is the application giving any problems, saving posts etc?

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
