### ISSUE TITLE
[Wordpress] Page /bitnami/index.html appeared on site

### ISSUE THREAD

**Issue by JAZZ-FROM-HELL** [bitnami/vms#291]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bndiagnostic upload failed

### bndiagnostic output

bndiagnostic automatic upload failed. please provide a private safe upload url.

### bndiagnostic was not useful. Could you please tell us why?

upload failed

### Describe your issue as much as you can

Recently a new page /bitnami/index.html appeared on my site. I don't know what sets it and why is it there, imo it shouldn't be. It also links to internal pages like /wp-admin /phpmyadmin which causes issues with search indexing. The change happened sometime before Aug 24th 2022.

Please advise how to remove that page.

**Comment by mdhont** [comment]
Do you have SSH access to the machine? Could you run the bndiagnostic tool?

    sudo /opt/bitnami/bndiagnostic-tool

And share the long ID at the end of the output?
