### ISSUE TITLE
How to detect & restart services if they go down. 

### ISSUE THREAD

**Issue by roryheaney** [bitnami/vms#293]
I noticed in the docs, you can check if the services are down / start / restart accordingly.  [Link](https://docs.bitnami.com/aws/infrastructure/nginx/administration/control-services/)

That was super helpful in fixing a 502 error.  

I've been checking the docs and I don't think I'm seeing a way to restart them automatically if they go down?

**Comment by jotamartos** [comment]
Hi @roryheaney,

Thank you for using Bitnami. In that case, you will need to create a new script that runs the status command and checks its exit code. If there is something wrong, it can run the restart command

```
#!/bin/bash

if ! sudo /opt/bitnami/ctlscript.sh status > /dev/null; then
    echo "Restarting services"
    sudo /opt/bitnami/ctlscript.sh restart 
fi
```

You will need to add this script to the crontab's entry and run it every 30 minutes to restart the services when required.

**Comment by roryheaney** [comment]
@jotamartos thank you very much for this. 

Do you see an issue with running this check more aggressively?

Say every 5 / 10 or 15 mins?

**Comment by jotamartos** [comment]
That shouldn't be a problem. If services are running, the script will do nothing so no performance issues should happen.

**Comment by aliehanani** [comment]
> Hi @roryheaney,
> 
> Thank you for using Bitnami. In that case, you will need to create a new script that runs the status command and checks its exit code. If there is something wrong, it can run the restart command
> 
> ```
> #!/bin/bash
> 
> if ! sudo /opt/bitnami/ctlscript.sh status > /dev/null; then
>     echo "Restarting services"
>     sudo /opt/bitnami/ctlscript.sh restart 
> fi
> ```
> 
> You will need to add this script to the crontab's entry and run it every 30 minutes to restart the services when required.

Hello @jotamartos,

Can you please provide how-to and where is the crontab's entry for NGINX. My server goes down more then twice a day due to traffic. Thank you in advance.

**Comment by aliehanani** [comment]
Thank you @jotamartos Along with ChatGPT I was able to make the entry and will monitor to confirm if it actively working.

**Comment by aliehanani** [comment]
So I edited the `crontab` like below to check every 3 minutes, and still does not work. After monitoring for 3 days and adding the last line, nothing helps.
<img width="612" alt="Screenshot 2023-04-28 at 1 01 56 AM" src="https://user-images.githubusercontent.com/12172666/234936544-ca294506-7fdd-4aa4-bb54-e4261ada9cc5.png">

The script looks exactly how it was provided. Is there something I'm doing wrong?
<img width="797" alt="Screenshot 2023-04-28 at 1 05 29 AM" src="https://user-images.githubusercontent.com/12172666/234937082-40ff3c3c-d3ab-4f02-b274-aeda608ce35a.png">

**Comment by gongomgra** [comment]
Hi @aliehanani,

Can you update the crontab line to the one below? It will log the output to the `/tmp/output.log` file. Can you check the results?

```
*/3 * * * * sudo /stack/scripts/nginx-auto-restart.sh > /tmp/output.log
```

Can you also check the script has execution permissions?

```
ls -lart /stack/scripts/nginx*
```

**Comment by aliehanani** [comment]
Hello @gongomgra, 

I will monitor the logs at `/tmp/output.log,` and update you.

As for running `ls -lart stack/scripts/nginx-auto-restart.sh` I received `-rwxr-xr-x 1 root root 152 Apr 24 05:08 stack/scripts/nginx-auto-restart.sh` 

<img width="581" alt="Screenshot 2023-05-03 at 12 23 35 AM" src="https://user-images.githubusercontent.com/12172666/235726237-0bc3ac09-81f8-4bce-806d-276980c85f70.png">

**Comment by gongomgra** [comment]
Hi @aliehanani,

Thanks for your message. According to the command output, the script has the execution permissions set. Let us know what you get from the `output.log` file.

**Comment by aliehanani** [comment]
Hey @gongomgra, 

The processes shutdown again, a few more times, and nothing showed up in `output.log`

<img width="794" alt="Screenshot 2023-05-05 at 3 44 09 AM" src="https://user-images.githubusercontent.com/12172666/236312943-5c5bafc7-5ec8-44f5-b58d-948b5912c30c.png">

**Comment by gongomgra** [comment]
Hi @aliehanani,

Can you upgrade the crontab line to also redirect the messages in the `stderr` stream to the file?

```
*/3 * * * * sudo /stack/scripts/nginx-auto-restart.sh > /tmp/output.log 2>&1
```

Also please remove the redirect to `/dev/null` from the script so we can check if there is any issue running the ctlscript

```
#!/bin/bash

if ! sudo /opt/bitnami/ctlscript.sh status; then
    echo "Restarting services"
    sudo /opt/bitnami/ctlscript.sh restart 
fi
```

**Comment by aliehanani** [comment]
Thank you @gongomgra! 

No issue running the script. I will monitor for the cron job to post logs.

**Comment by gongomgra** [comment]
Hi @aliehanani,

Thanks for your message. Let us know if you found anything.

**Comment by aliehanani** [comment]
Hey, @gongomgra 

I tried the method, and seem to post status messages to `/tmp/output.log` then the database failed. I have been unable to start MariaDB. Thus, I cannot log in to the database via ssh nor perform a recovery fix using: `define('WP_ALLOW_REPAIR', true); ` & `wp-admin/maint/repair.php`. It is hard to say if it related to the change and was 3 minutes too short of an interval.

**Comment by gongomgra** [comment]
Hi @aliehanani,

Can you run the bndiagnostic tool again to check if it detects any issue with MariaDB?

**Comment by robinlavallee** [comment]
For those coming from Google on this paga.

 `/opt/bitnami/ctlscript.sh status` always returns `0`, this is why the script proposed doesn't behave as expected.

The solutions is to update the script to the following:
```
#!/bin/bash

if sudo /opt/bitnami/ctlscript.sh status | grep -q 'not'; then
    echo "Restarting services"
    sudo /opt/bitnami/ctlscript.sh restart
fi
```

**Comment by gongomgra** [comment]
Hi @robinlavallee,

Thanks for your message and for sharing your solution. I'm sure it will be of help for other users in the future.

**Comment by quauhtlimtz** [comment]
`#!/bin/bash

# Check the status of the services
STATUS=$(/opt/bitnami/ctlscript.sh status)

# Define services
APACHE_RUNNING="apache already running"
MARIADB_RUNNING="mariadb already running"
PHPFPM_RUNNING="php-fpm already running"

LOG_FILE="/var/log/service_check.log"
DATE=$(date '+%Y-%m-%d %H:%M:%S')

# Check if all services are running
if [[ "$STATUS" == *"$APACHE_RUNNING"* && "$STATUS" == *"$MARIADB_RUNNING"* && "$STATUS" == *"$PHPFPM_RUNNING"* ]]; then
  echo "$DATE - All services are running" >> $LOG_FILE
else
  echo "$DATE - One or more services are not running" >> $LOG_FILE
  
  # Send email or notification (optional)
  # echo "One or more services are not running" | mail -s "Service Alert" your-email@example.com
fi`

I you want to add it to your Cron, you can use this (to check every 10 minutes):

crontab -e
*/10 * * * * /usr/local/bin/service_check.sh
