### ISSUE TITLE
No webpage was found for the web address: https://www.pbtgroup.com.au/

### ISSUE THREAD

**Issue by MDOT77777** [bitnami/vms#294]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

22211b9a-ebcd-90f1-f51c-3eacf111aed4

### bndiagnostic output

    ? Apache: Found possible issues
    ✓ MariaDB: No issues found
    ✓ Connectivity: No issues found
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

It was useful because it shows me a clue of what the issue

### Describe your issue as much as you can

Hi 

My website url https://www.pbtgroup.com.au/ is total downtime I think there is an issue with config.php file. I have tried to disable all the plugins via terminal in Amazon LightSail please assist Asap? I even tried to reset the server setting nothing changes.

The below message I have found when I run diagnose tool on bitnami

[Wordpress]
Found recent WordPress plugin related error messages in the Apache error log.
Press [Enter] to continue:
```
[Fri Sep 02 09:30:05.745718 2022] [proxy_fcgi:error] [pid 30090:tid 
140580143146752] [client **ip_address**:60048] AH01071: Got error 'PHP message: 
PHP Parse error: syntax error, unexpected '}', expecting end of file in 
/opt/bitnami/wordpress/wp-includes/plugin.php on line 481'

Please see this message below feedback from diagnostic tool

The files listed below are bigger than 10MB and have not been included, please notify the support agent.

/opt/bitnami/apache/logs/error_log
/opt/bitnami/apache2/logs/error_log

![image](https://user-images.githubusercontent.com/112690004/188109296-c58864f0-67ca-40c9-b3a5-e52f089a8982.png)

**Comment by mdhont** [comment]
According to the Apache logs you have a syntax error on line 481 in the "/opt/bitnami/wordpress/wp-includes/plugin.php" file. Did you change anything in that file? Did you install any plugins right before the site went down?

**Comment by MDOT77777** [comment]
Hi Thanks for the reply I didn't install any plugins I was about do monthly maintenance suddenly the website is down can you able to track the plugin and disable it?

**Comment by MDOT77777** [comment]
Hello hope you had a great weekend can you please assist the matter has not been resolved?

**Comment by gongomgra** [comment]
Hi @MDOT77777,

I visited your website and it seems it is working now. Did you manage to solve your issues?

**Comment by MDOT77777** [comment]
Yes it working we tried to fix it but the issue we have now is wp-config.php not writeable can you please assist with that? can you direct us on that I know has to do with EC2.

**Comment by gongomgra** [comment]
Hi @MDOT77777,

I added a comment in [this other issue you opened](https://github.com/bitnami/vms/issues/304). Is that the one you are asking about?
