### ISSUE TITLE
[LAMP] Mysql and Apache BOTH cannot start

### ISSUE THREAD

**Issue by chiemekailo** [bitnami/vms#296]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

657e0de1-4027-e8ea-0759-c2bbc73b6193

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ? Mysql: Found possible issues
    ? Processes: Found possible issues
    ✓ Php: No issues found
 

 
[Apache]

Found recent Pagespeed related error messages in the Apache error log:

```
[Fri Sep 02 10:04:22.913613 2022] [pagespeed:error] [pid 31101:tid 
140109137217280] [mod_pagespeed **ip_address**-0 @31101] 
```

We suggest disabling pagespeed and check if that improves the behavior. Please 
check the following guide to disable Pagespeed:
 
https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespe
ed/#disable-pagespeed

Found recent error or warning messages in the Apache error log.

```
[Thu Sep 01 06:47:42.910637 2022] [proxy_fcgi:error] [pid 24358:tid 
140109592610560] [client **ip_address**:49238] AH01071: Got error 'Primary 
script unknown'
 [Thu Sep 01 08:52:54.319983 2022] [authz_core:error] [pid 16148:tid 
140109374400256] [client **ip_address**:60634] AH01630: client denied by server 
configuration: /opt/bitnami/apps/phpmyadmin/htdocs/index.php
 [Thu Sep 01 09:15:56.284529 2022] [proxy_fcgi:error] [pid 16148:tid 
140109642966784] [client **ip_address**:37848] AH01071: Got error 'PHP message: 
PHP Warning: session_start(): Failed to read session data: user (path: 
/opt/bitnami/php/tmp) in 
/opt/bitnami/apps/joomla/htdocs/libraries/joomla/session/handler/native.php on 
line 260'
```

Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:

```
apache2: Syntax error on line 66 of /opt/bitnami/apache2/conf/httpd.conf: Cannot 
load modules/mod_mpm_event.so into server: libiconv.so.2: cannot open shared 
object file: No such file or directory
```

Please check the configuration.

[Resources]

Your instance has little available RAM memory.

```
 total used free shared buff/cache available Mem: 481 396 30 1 55 72 Swap: 634 
127 507
```

You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Mysql]
Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Processes]

One or more component's processes are not running:
```
apache not running mysql not running
```
You can try to restart the process with the following command:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

### bndiagnostic was not useful. Could you please tell us why?

I took the suggestions given by the tool, but still thay cannot start.
I set ModPagespeed off and tested. still failed.
I also increased swapfile size from 634M to 1.6G, but it mysql still won't start.

### Describe your issue as much as you can

I type the following command, php-fpm starts but mysql & httpd would not start.
```
$ sudo /opt/bitnami/ctlscript.sh start
```
the following is the output of the attempts to start:
```
$ sudo /opt/bitnami/ctlscript.sh status

php-fpm already running
apache not running
mysql not running

$ sudo /opt/bitnami/ctlscript.sh start

/opt/bitnami/mysql/scripts/ctl.sh : mysql  could not be started
/opt/bitnami/php/scripts/ctl.sh : php-fpm (pid 19578) already running
Syntax OK
(98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
/opt/bitnami/apache2/scripts/ctl.sh : httpd could not be started
```

**Comment by chiemekailo** [comment]
i Just ran the following code to see what is sharing the port 80:
```
$ fuser -v -n tcp 80
```
no output at all, so nothing sharing the port.

**Comment by chiemekailo** [comment]
..Then I did this:
```
sudo netstat -ltnp | grep ':80'
```
..and got the following output. What does this mean?
```
tcp6       0      0 :::80                   :::*                    LISTEN      1525/httpd
```

**Comment by chiemekailo** [comment]
I Added these three lines to the /etc/sysctl.conf file, and apache (http) started:
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```
Now remains for mysql to start.. :-(

**Comment by chiemekailo** [comment]
I can see now that the new Bitnami Lamp 7.x now comes with ***mariadb*** and ***not mysql*** anymore. Could this be the reason why the mysql cannot start?
Is there any way I can migrate the data folders from the mysql to the mariadb to preserve my table data?!

**Comment by jotamartos** [comment]
Hi @chiemekailo,

You are using a 512MB of RAM instance and its performance is really poor. It's currently using SWAP memory so please increase the resources of the VM if you want to avoid issues. 

The support tool didn't get the MySQL's log file. Can you try to start it and paste the content of the log file here? 

```
sudo /opt/bitnami/ctlscript.sh start mysql
sudo tail -n 40 /opt/bitnami/mysql/data/mysqld.log
```
