### ISSUE TITLE
[WordPress] Updating my PHP

### ISSUE THREAD

**Issue by levelingup** [bitnami/vms#297]
I'm using [WordPress Certified by Bitnami and Automattic](https://aws.amazon.com/marketplace/pp/prodview-bzstv3wbn5wkq) for awhile now. Where I'm using AWS EC2 to host my website, but it mentioned that I should update my PHP. Is there a guide on how to do this? Is it through bitnami or would I need to go through AWS? 

Thanks!

**Comment by gongomgra** [comment]
Hi @levelingup,

Thanks for using Bitnami. In order to upgrade the PHP version included in your server, you will have to launch a newer version of our image and migrate your application data to the new instance. We have a guide about how to migrate the WordPress data using the "All-in-One WP migration" plugin, but you can follow any other method.

https://docs.bitnami.com/aws/how-to/migrate-wordpress/

**Comment by gongomgra** [comment]
Hi @levelingup,

Yes, you need to launch a fresh new image with the updated PHP version, install the plugin in both WordPress instances, and then proceed with the rest of the steps in our guide. Alternatively, you can follow any other data migration process not requiring plugins. Please check the official WordPress forums to get more information on this

https://es.wordpress.org/support/forums/

**Comment by levelingup** [comment]
Hello, I've gotten down the steps on trying to export my Wordpress and then import into another instance, but when I finally got to the point where I'm about to restore it, All-In-One-Migration plugin says restoring the Wordpress is only for paid

![Screen Shot 2022-09-13 at 9 20 25 AM](https://user-images.githubusercontent.com/1781551/189954649-39e55f25-38fd-4aac-ac9e-318b234e5a5c.png)

Where I didn't expect this. Is there another workaround?

**Comment by levelingup** [comment]
Just updating here, for anyone who has issues, this helped: https://gist.github.com/giovanni-d/f9a05638e0b31467762b71585e8c3bfa

**Comment by levelingup** [comment]
Sorry, last question: when migrating, does HTTPS and all that SSL certificate gets transferred over too? I initiated the NGINX package one. Right now when I'm going through the IP address IP_ADDRESS/wp-admin, it doesn't have it. Not sure if I need to redo the entire process again,
Thanks!

**Comment by levelingup** [comment]
been having trouble creating a new certificate with new IP address and using the same domain. Is this a known issue?

Its referencing my old (current) IP address with "Error getting validation data"

**Comment by gongomgra** [comment]
Hi @levelingup,

If you updated your DNS registries, you will have to wait some time for the new information to be propagated to all DNS servers. You can check it using the [whatsmydns.net](https://www.whatsmydns.net/) service.
