### ISSUE TITLE
create a website using MacOS

### ISSUE THREAD

**Issue by SmallGroupsVU** [bitnami/vms#298]
### Describe your issue as much as you can

I am having troubles logging in to the site created using wordpress.

**Comment by jotamartos** [comment]
We configure a default user and password in the OS X VMs

https://docs.bitnami.com/installer/apps/wordpress/get-started/first-steps/#what-is-the-administrator-password

If you deployed a VM previously, you will need to continue using the same password you used in the past or recreate the VM if needed

https://docs.bitnami.com/installer/faq/osx-vm-faq/administration/uninstall-osx-vm/
