### ISSUE TITLE
[Wordpress] Not able to launch a PHP 7.4 instance

### ISSUE THREAD

**Issue by jeremypeet** [bitnami/vms#302]
### Describe your issue as much as you can

I have been using Bitnami Wordpress on AWS Lightsail for a couple of years and need to upgrade it from PHP to 7.3 to PHP 7.4 for security reasons. 

The only AWS Lightsail Bitnami Wordpress blueprint and Bitnami Launcher versions available use PHP 8 which is not compatible with my site, so I need to launch a Bitnami Wordpress instance with PHP 7.4.

I found the Wordpress image version `5.9.2-18-r03` in AWS Marketplace and launched it through EC2 from the console but there is then no way to then login via ssh: the public key from the EC2 keypair is placed in the root account but the Linux configuration prevents a root login. An ssh key for the bitnami account is not available for me to use.

How can I either:
1. Launch Wordpress image version `5.9.2-18-r03` from AWS Lightsail or Bitnami Launcher?
or
2. Make the bitnami account accessible when launching the image from EC2? Is there a suitable launch script to call to get the public key from the launch keypair into the bitnami user's .ssh folder?

**Comment by gongomgra** [comment]
Hi @jeremypeet,

Thanks for using Bitnami. The SSH key you select in the AWS EC2 console while launching a machine should be added to the `bitnami` user as well. Can you double-check you are using the correct SSH private key against the `bitnami` user? If you continue having issues, please contact the AWS support team, as it seems to be an issue on their side.

Unfortunately, it is not possible to launch an old version either from Lightsail console or Bitnami Launchpads, you will need to launch the EC2 image instead.

**Comment by jeremypeet** [comment]
hi @gongomgra thanks for the reply. What component is responsible for placing the key into the bitnami user's .ssh folder when the VM is booted for the first time? The key from the launch keypair is obviously getting loaded into `/.ssh/authorized_keys` but not `/home/bitnami/.ssh/authorized_keys`

**Comment by jeremypeet** [comment]
I just tried this again and it worked this time. Thanks for your help.

**Comment by gongomgra** [comment]
Hi @jeremypeet,

Thanks for your message. I'm glad you fixed your issue!
