### ISSUE TITLE
[Gitlab CE] sudo: /opt/bitnami/ctlscript.sh: command not found

### ISSUE THREAD

**Issue by gdelacc** [bitnami/vms#303]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e996724c-5b45-0c7a-2ae8-a38ad4af9a2c

### bndiagnostic was not useful. Could you please tell us why?

No solution for the problem

### Describe your issue as much as you can

sudo: /opt/bitnami/ctlscript.sh: command not found 

DTLSCRIPT.sh not included at the image, any idea?

**Comment by jotamartos** [comment]
Hi @gdelacc,

We use the GitLab's packages to install the app and it includes a control script to manage all the services. Please take a look at this doc page 

https://docs.bitnami.com/aws/apps/gitlab/administration/control-server/

Happy to help!

**Comment by gdelacc** [comment]
Thanks, it works

**Comment by jotamartos** [comment]
Just for the record, we updated our documentation and removed the ctlscript.sh information for Gitlab. The gitlab-ctl documentation was moved to this new URL

https://docs.bitnami.com/general/apps/gitlab/administration/control-services/
