### ISSUE TITLE
SonarQube Azure SSO

### ISSUE THREAD

**Issue by kenyu-gnetwork** [bitnami/vms#305]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

effb2065-7c50-c1fd-a439-d484939594d0

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Sep 05 11:11:54.428069 2022] [proxy_http:error] [pid 26097:tid
140497406342912] [client **ip_address**:1333] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1, referer:
https://MyPublicDomainName/admin/system
 [Mon Sep 05 11:11:57.455590 2022] [proxy:error] [pid 25966:tid 140498547226368]
(111)Connection refused: AH00957: http: attempt to connect to
**ip_address**:9000 (127.0.0.1) failed
 [Mon Sep 05 11:11:57.455630 2022] [proxy_http:error] [pid 25966:tid
Press [Enter] to continue:
140498547226368] [client **ip_address**:1335] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1, referer:
https://MyPublicDomainName/admin/system

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3889 2558 212 121 1117 979
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
Press [Enter] to continue:
emory-linux/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

This output relates to a configuration that is attempting to use Azure SSO. and is not the actual issue

### Describe your issue as much as you can

Attempting to configure Azure SSO with SonarQube hosted in AWS (Marketplace).

The error message is:

You're not authorized to access this page. Please contact the administrator.

Reason: The response was received at http://127.0.0.1:9000/oauth2/callback/saml instead of https://MyPublicDomainName/oauth2/callback/saml

I have tried editing the ProxyPass & ProxyPassReverse urls to our public URL rather than the default http://127.0.0.1:9000/ values  in the sonarqube-https-vhost.conf & sonarqube-vhost.conf files and restarting the system/apache. But this error still persists. It does authenticate using my test Azure AD user account, but returns the error page above.

https://MyPublicDomainName/oauth2/callback/saml - this is the redirect/reply URL in the Enterprise App in Azure AD. 
https://MyPublicDomainName is not the real domain name - this is just to illustrate the error.

**Comment by gongomgra** [comment]
Hi @kenyu-gnetwork,

Thanks for using Bitnami. All I see in the Apache logs are a lot of error messages like this (I redacted your doamin name):

```
[Mon Sep 05 10:58:36.978229 2022] [proxy:error] [pid 26784:tid 140497381164800] (111)Connection refused: AH00957: http: attempt to connect to 127.0.0.1:9000 (127.0.0.1) failed
[Mon Sep 05 10:58:36.978280 2022] [proxy_http:error] [pid 26784:tid 140497381164800] [client CLIENT_IP:17277] AH01114: HTTP: failed to make connection to backend: 127.0.0.1, referer: https://your-domain.com/admin/system
```

Apparently, it couldn't contact your Sonarqube instance somehow, but unfortunately I can't check Sonarqube logs. Can you revert the change for the `ProxyPass` and `ProxyPassReverse` directives, restart the Apache service and then follow the official steps for configuring SAML authentication? I think it will also be helpful to check the Sonarqube logs. I'm sharing the link to the official docs on how to configure SAML authentication below

https://docs.sonarqube.org/latest/instance-administration/delegated-auth/#header-4

If you continue having issues after following the docs, we recommend you to ask for further help on how to debug this in the official support forums, as they have more knowledge on how the application works internally.

**Comment by semyonsh** [comment]
Putting this out there for anyone running into the same thing in the future. I had the exact same issue with an Azure deployed Bitnami VM using Azure AD SAML. 

The fault is in the default reverse proxy configuration, in order for requests to get properly handled you need to forward the headers and preserve the host. After editing the vhost configuration located at "/opt/bitnami/apache/conf/vhosts" the SAML login started to work:
` 
<VirtualHost 127.0.0.1:443 _default_:443>
  ... 
  ProxyPreserveHost On
  ProxyRequests Off
  RequestHeader set X-Forwarded-Proto "https"
  RequestHeader set X-Forwarded-Port "443"
</VirtualHost>
`
