### ISSUE TITLE
[Redmine] - Install on MacOS not possible

### ISSUE THREAD

**Issue by jfix** [bitnami/vms#307]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

not available for MacOS?

### bndiagnostic output

not exactly the andiagnostic output, but the tool does not seem to be available for MacOS (or I couldn't find it nor any documentation), but here is the error message when I try to "Start" Redline by clicking the "Start" button:

<img width="1436" alt="Screenshot 2022-09-06 at 23 23 17" src="https://user-images.githubusercontent.com/170240/188744408-a75d9282-d80c-4fed-9823-65680bb645f1.png">

### bndiagnostic was not useful. Could you please tell us why?

not available for MacOS?

### Describe your issue as much as you can

I've downloaded the latest version of Redmine for MacOS (bitnami-redmine-5.0.2-4-r04-osx-x86_64-vm.dmg).

<img width="587" alt="image" src="https://user-images.githubusercontent.com/170240/188745077-1d5e58ad-3ac3-44a7-8ce9-f5c6d835d04c.png">

I authenticated with my system account as expected. The Redmine.app window came up, I clicked the "Start" button, I saw the error message. I have reproduced this several times.

I quit the VPN service (even though it was not running) because the error message mentioned that it couldn't calculate a MAC address.

Please let me know if I can try anything else.

**Comment by jotamartos** [comment]
Hi @jfix ,

Thank you for your interest. I can see you are using a M1-based laptop. The OS X VMs do not support ARM arch so it's not possible to use these solutions in your laptop. 

Sorry for the inconvenience.

**Comment by jfix** [comment]
Thanks, @jotamartos, I see. Out of curiosity, is it planned at all to support this architecture in the future? But note this is not critical for me, I can do the development in a Windows environment.

**Comment by jotamartos** [comment]
Hi @jfix,

The team is working on adding support to the different products on top of ARM but we can't guarantee that OS X VMs will support it or when it'll be supported. You can get the latest updates on this topic regarding the Bitnami containers and charts here: 

https://github.com/bitnami/charts/issues/7305

Thanks

**Comment by jfix** [comment]
Thanks @jotamartos, I'll watch the other ticket and close this one.
