### ISSUE TITLE
[alfresco] Old alfresco version 6.1

### ISSUE THREAD

**Issue by aukfood** [bitnami/vms#308]
### Describe your issue as much as you can

Hello, there is a link for download ova with Alfresco 6.1 ?

Thanks

**Comment by gongomgra** [comment]
Hi @aukfood,

Thanks for using Bitnami. Unfortunately, we didn't release the 6.1 version. Can we provide you with any version of our [changelog](https://bitnami.com/stack/alfresco/vboxdebian-x64-nami/changelog.txt)?
