### ISSUE TITLE
[<Wordpress Multisite 6.0.2>] <Older versions or downgrade PHP>

### ISSUE THREAD

**Issue by danielberma** [bitnami/vms#309]
### Describe your issue as much as you can

Hello!

Just been switching to Wordpress Multisite via Azure. Earlier ran some VPSes elsewhere but thought this could be something to explore. I got one VPS successfully migrated from A to B but the rest does not want to come over. I use All in One Migration plugin and from what I understand the issue is within the PHP-version where my old VPS uses 7.x and this newest version run 8.x.

I have tried to understand Azure but to be honest: How can they even charge for such... anyway, as login on to the server is a no-go, I wonder if there is an archieve of older versions of WordPress Multisite, configured with an older version of PHP, to use?

Thanks in advance

**Comment by jozipaulo** [comment]
How can we select an old image on AWS. Can you advise?
