### ISSUE TITLE
[WordPress Production-Ready Certified by Bitnami and Automattic] <Make DB creation optional>

### ISSUE THREAD

**Issue by kobi-jd** [bitnami/vms#310]
### Describe your suggestion as much as you can

I am interested in using the Production-Ready CloudFormation templates on AWS, but I already have an existing Aurora DB Cluster that I'd prefer to continue using. My request is to make DB creation optional within the CloudFormation setup for situations where you already have one setup and optimized.

I know I can make a copy of the CF template and modify it, but I'd rather not get separated from the original setup process (unless you'd suggest to doing that).

**Comment by gongomgra** [comment]
Hi @kobi-jd,

Thanks for using Bitnami and for your suggestion. Our solution launches everything that is needed for the application to run from scratch. If you don't want to make a copy of the template, you can always configure its database settings afterwards to point to your current Aurora DB service.
