### ISSUE TITLE
Bug | Help me

### ISSUE THREAD

**Issue by Gabizoc** [bitnami/vms#312]
### Name and Version

Help

### What steps will reproduce the bug?

I have an error when I start.

image : [Here](https://cdn.discordapp.com/attachments/1006127188095008851/1017469826161188944/unknown.png)

**Comment by jotamartos** [comment]
Hi @Gabizoc,

This is a XAMPP related question, please open a new ticket in the XAMPP's forum 

https://community.apachefriends.org/f/

Thanks
