### ISSUE TITLE
[WordPress] IP Public browser access

### ISSUE THREAD

**Issue by helenNguyen12** [bitnami/vms#313]
### Describe your issue as much as you can

Hi team,

I have a public IP of VM on Azure, do I need to register that IP with Bitnamy before access to the adminpage?

If the public IP is: A.B.C.D.
So the admin page link will be: **http://A.B.C.D/wp-admin** right?
I have created an instance Wordpress Packaged by Bitnamy on Azure, do I need to set up any thing inside the server before it can be used?

**Comment by jotamartos** [comment]
No, the application should be working properly and the app should be configured to use that IP. Please go to http://A.B.C.D to access the application.

**Comment by helenNguyen12** [comment]
Hi Juan,
May I have the document to install SSL certificate for Bitnamy wordpress website or we will install the same as other Debian server?

Best regards,
Helen

**Comment by jotamartos** [comment]
You can follow this guide if you already have valid certificates 

https://docs.bitnami.com/azure/apps/wordpress/administration/enable-https-ssl-apache/

However, if you want to generate a Let's Encrypt certificate, we suggest you follow any of these guides 

https://docs.bitnami.com/general/how-to/understand-bncert/
https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by helenNguyen12** [comment]
Hi Juan,

While installing the Cert, I get below error, may I seek for your support?
***@***.***

Best regards,
Helen

From: Helen NGUYEN (ACN)
Sent: Friday, September 16, 2022 2:13 PM
To: bitnami/vms ***@***.***>; bitnami/vms ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [bitnami/vms] [WordPress] IP Public browser access (Issue #313)


Hi Juan,
May I have the document to install SSL certificate for Bitnamy wordpress website or we will install the same as other Debian server?

Best regards,
Helen

**Comment by jotamartos** [comment]
Do not know what error you are getting. But please confirm your domains (both www and non-www domains) point to the correct IP address and then run the tool

https://www.whatsmydns.net/

**Comment by helenNguyen12** [comment]
Hi Juan,

Problem resolved. Thanks for your support.

Best regards,
Helen
