### ISSUE TITLE
How to select specific IP range while deploying the RabbitMQ Cluster packaged

### ISSUE THREAD

**Issue by jawad846** [bitnami/vms#315]
### Describe your issue as much as you can

We have 5 subscriptions, and we have deployed the Bitnami RabbitMQ master slave product in each subscription with the default network IP Address Range: 10.0.0.0/24. The applications are working and there are no issues. 

But when we are trying to integrate PAM, we are facing challenges due to the same private IP range.

Is there any way to specify the network IP address range while deploying this product.

**_Product Details:_**
Operating system: Linux (debian 10.12)
Publisher: bitnami
Offer: rabbitmq-master-slave-multitier-image
Plan: default
VM generation: V1

**Comment by jawad846** [comment]
my i know what is the update on this

**Comment by mdhont** [comment]
It should be possible to [download ](https://docs.bitnami.com/azure/faq/administration/download-deployment-template/) the template before deploying and then change the addressPrefix of the default-subnet.
