### ISSUE TITLE
[Joomla] PHP Upgrade

### ISSUE THREAD

**Issue by muktadey-sen** [bitnami/vms#317]
### Describe your issue as much as you can

Our company using Bitnami Joomla on Linux server. we are getting warning now for PHP upgrade. 
Could you pleaseinstruct us how can we upgrade php on Bitnami Joomla.

**Comment by gongomgra** [comment]
Hi @muktadey-sen,

Thanks for using Bitnami. Unfortunately, it is not possible to update base components (Apache, PHP, MariaDB, etc.) in our images. You will have to launch another server with a newer version of PHP and then migrate your application data into it.

We have a guide on our documentation site on how to migrate the application data from one server to another. You can find it below

https://docs.bitnami.com/general/how-to/migrate-joomla/

**Comment by muktadey-sen** [comment]
Hi Gonzalo,
I followed your guide but did not find its helpful coz each path is
different then current path. I'm not finding any exact path. Do you have
any latest version of the document for data migration.

Thanks
Mukta Dey

**Comment by gongomgra** [comment]
Hi @muktadey-sen,

Thanks for your message. You are right, the guide I shared is showing the old paths. Can you please follow it but replacing the old `/opt/bitnami/apps/joomla` path with the new `/opt/bitnami/joomla` one? I will open a new task for our documentation team to upgrade the guide.

**Comment by gongomgra** [comment]
Hi @muktadey-sen,

The guide should be the same we already have, but updating the paths everywhere with the new path for Joomla installation. In case the guide is still not working for you, please refer to the official Joomla docs for migrating the information from one instance to another.

**Comment by muktadey-sen** [comment]
Hi Gongomgra,

I am stuck on database migration step. I need a live support. Would you please kindly help me. I can share my screen.
![sc1](https://user-images.githubusercontent.com/60453079/207775475-0ae3cc87-0fe7-4ac3-900e-e4b6c6256a7d.PNG)
![sc2](https://user-images.githubusercontent.com/60453079/207775496-214a5749-5095-4772-9a03-e9026bf08d52.PNG)

**Comment by gongomgra** [comment]
Hi @muktadey-sen,

Unfortunately we don't provide that kind of support. We can only help you here. Please double-check MariaDB database is running on your server and that you have provided the correct database credentials. You can test them in your command line. You can also give the database credentials from the Joomla config file a try.

**Comment by muktadey-sen** [comment]
Hi Gongomore,
I have collected correct credential and db information from configuration.php. But having same error. 
Please help me to migrate main site to new instance. 
Thanks
Mukta
