### ISSUE TITLE
Bitnami Redmine modern authentication (OAuth 2.0)

### ISSUE THREAD

**Issue by GovindanRaja** [bitnami/vms#320]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

no modern authentication explained.

### bndiagnostic was not useful. Could you please tell us why?

no modern authentication

### Describe your issue as much as you can

Currently we are using smtp method to send out email from Birtnami Redmine application, we are forced to move to microsoft mordern authentication.

I need help to configure Bitnami Redmine email with modern authentication.

Please help.

Thanks 
-/Raja G

**Comment by mdhont** [comment]
The following guide explains how to configure SMTP for Redmine:

https://docs.bitnami.com/installer/apps/redmine/configuration/configure-smtp/

**Comment by GovindanRaja** [comment]
Hello Michiel,

  Thanks for the updates.

Unfortunately, Microsoft will not support simple SMTP authentications any more from Oct’22.
We need to move to modern authentication(Oauth 2.0), by sending keys.

Please advise on how to configure email notifications in Redmine using modern authentication Oauth.

Thanks again
-/Raja g


From: Michiel ***@***.***>
Date: Monday, September 12, 2022 at 8:10 AM
To: bitnami/vms ***@***.***>
Cc: Govindan, Raja ***@***.***>, Author ***@***.***>
Subject: Re: [bitnami/vms] Bitnami Redmine modern authentication (OAuth 2.0) (Issue #320)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



The following guide explains how to configure SMTP for Redmine:

https://docs.bitnami.com/installer/apps/redmine/configuration/configure-smtp/

**Comment by GovindanRaja** [comment]
In another words:

  Need help to configure .yml file for modern authentication for email notifications.

Thanks
-/Raja G

From: Govindan, Raja ***@***.***>
Date: Monday, September 12, 2022 at 8:27 AM
To: bitnami/vms ***@***.***>, bitnami/vms ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [bitnami/vms] Bitnami Redmine modern authentication (OAuth 2.0) (Issue #320)
Hello Michiel,

  Thanks for the updates.

Unfortunately, Microsoft will not support simple SMTP authentications any more from Oct’22.
We need to move to modern authentication(Oauth 2.0), by sending keys.

Please advise on how to configure email notifications in Redmine using modern authentication Oauth.

Thanks again
-/Raja g


From: Michiel ***@***.***>
Date: Monday, September 12, 2022 at 8:10 AM
To: bitnami/vms ***@***.***>
Cc: Govindan, Raja ***@***.***>, Author ***@***.***>
Subject: Re: [bitnami/vms] Bitnami Redmine modern authentication (OAuth 2.0) (Issue #320)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.




The following guide explains how to configure SMTP for Redmine:

https://docs.bitnami.com/installer/apps/redmine/configuration/configure-smtp/

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
