### ISSUE TITLE
[XAMPP] XAMPP VM app "MAC address" error on startup, macOS 12, M1 arm CPU

### ISSUE THREAD

**Issue by JDLH** [bitnami/vms#321]
### Platform

OSX VM

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Not applicable, VM does not run, no bndiagnostic available

### bndiagnostic output

Not applicable. Since the XAMPP VM does not run, it is impossible to reach inside the VM to run bndiagnostic. 

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/ does not appear to have useful information for the XAMPP VM application. It suggest checking `https://bitnami.com/stack/APP_NAME/changelog.txt`. When I replace the APP_NAME placeholder by `xampp`, the browser redirects to https://bitnami.com/stack/xampp/installer/changelog.txt . The text there is from 2013, and not relevant to this situation.

### bndiagnostic was not useful. Could you please tell us why?

Not applicable. Since the XAMPP VM does not run, it is impossible to reach inside the VM to run bndiagnostic. 

### Describe your issue as much as you can

I installed each of the XAMPP VM for Mac OS X apps, from:
  *  https://downloadsapachefriends.global.ssl.fastly.net/7.4.29/xampp-osx-7.4.29-1-vm.dmg?from_af=true 
  * https://downloadsapachefriends.global.ssl.fastly.net/8.0.19/xampp-osx-8.0.19-0-vm.dmg?from_af=true
  * https://downloadsapachefriends.global.ssl.fastly.net/8.1.6/xampp-osx-8.1.6-0-vm.dmg?from_af=true

I am running macOS 12.6 Monterey on a MacBook Pro with an Apple M1 Max CPU (arm64 architecture). 

In each case, when I copy the app (e.g. **xampp-osx-7.4.29-1-vm.app**) to my **/Applications** directory, then run the VM app, the app runs and initialises. But when I press the Start button, the VM app displays an error message like: 

> Error starting “XAMPP” stack
cannot calculate MAC address: Using fd 16 for I/O notifications
hv_vm_create unknown error 0x00000004

Looking through the Apache Friends forum for macOS (https://community.apachefriends.org/f/viewforum.php?f=29), it is clear many people have encountered this error message. The fixes suggested by the forum post are:

1. Use a Bitnami download, `hyperkit-testing-20210430`, in place of `~/.bitnami/stackman/helpers/hyperkit` . However, the hyperkit file provided with **xampp-osx-7.4.29-1-vm.dmg** is identical to `hyperkit-testing-20210430`, so it seems that fix is already supplied. In any case, making this substitution does not prevent the error.
2. Delete `~/.bitnami/stackman/` and all its contents. This does not prevent the error. It just causes the XAMPP VM app to initialise again, and leads to the same error.
3. Use the Mac OS X native installer, e.g. **xampp-osx-8.1.6-0-installer.dmg**, instead of the VM.  This does not solve the error in the VM app, it just switches to a different app with no VM support.

Does the XAMPP VM app support Apple M1 CPUs at all?  In https://github.com/bitnami/vms/issues/307, @jotamartos said, 
> The OS X VMs do not support ARM arch so it's not possible to use these solutions in your laptop.

Is this correct?  If so, it is a very important limitation on the use of the XAMPP VM app. It should be announced prominently in the "Requirements" information at https://www.apachefriends.org/download.html , and on the XAMPP for Mac OS X forum at https://community.apachefriends.org/f/viewforum.php?f=29 . 

Do Bitnami and Apache Friends support the XAMPP Mac OS X installer at all? At https://bitnami.com/stack/xampp , Bitnami says, 

> OS X native modules have been deprecated. Please use XAMPP-VM for OS X and the Linux version of the add-ons. Check [XAMPP [VM] FAQs](https://www.apachefriends.org/faq_stackman.html#how-do-i-install-xampp-add-ons) for more info.

So, if the XAMPP Mac OS X native installer is not supported, and the XAMPP VM is not supported on Apple M1 CPUs, does that mean that XAMPP is not supported in any way on Apple M1 CPUs?

Again, basic information like this deserves a clear statement on the Download page and in the XAMPP for Mac forum.

**Comment by jotamartos** [comment]
Hi, 

As mentioned in other threads and the support ticket you mentioned above, Bitnami OS X VMs only support x64 architectures and we can't provide you with an ETA on when ARM will be supported and if it'll be supported. The team is working now on adding support for ARM in the Bitnami containers and charts

https://github.com/bitnami/charts/issues/7305

XAMPP is now a separated product and it's not maintained by Bitnami. If you have any questions regarding XAMPP, please ask in the XAMPP's forum.

https://www.apachefriends.org/blog/moves_to_github_20220610.html

Thanks

**Comment by JDLH** [comment]
Thank you for the clarification, @jotamartos . I now understand that this GitHub issues list is not the channel to get support for XAMPP weaknesses.

If I may suggest, the communication about this situation is not very clear.

1. You say, "we mention that is a 64-bit package in the download link" as if that explains that XAMPP VM supports only intel-based x64 architectures. But "64-bit" means "64-bit", not "x64".  Note that the Apple M1 CPUs also have a 64-bit architecture, "arm64". So "64-bit" also applies to "arm64" as well as "x64".
2. You point out the ApacheFriends blog post from June 2022. Note that the title of the blog post is, "Apache Friends Project Moves to GitHub". Here I am on GitHub, asking for support, and you are telling me that support comes from a forum not on GitHub. I started off on the [Apache Friends support forum](https://community.apachefriends.org/f). Then I read that blog post, and thought, "Oh, Apache Friends wants me to post GitHub issues instead of phpBB forum posts". I think it would have been clearer if the blog post was entitled, "Bitnami steps back from Apache Friends project leadership and active support". 

But I appreciate the explanation. Now the explanation is here in this issue for others to find. I will turn to the [Apache Friends GitHub repos](https://github.com/ApacheFriends) and back to the Apache Friends support forum for more help. 

Thank you again.

**Comment by JDLH** [comment]
I hope to save Bitnami from further issues of this sort. For your information, I have filed two Pull Requests for the ApacheFriends website:

1. [_Clarify macOS (OS X) options in download.html_](https://github.com/ApacheFriends/web-static/pull/4)
2. [_Add Mac VM FAQs related to arm64 non-support_](https://github.com/ApacheFriends/web-static/pull/5)

I hope this will be helpful for you eventually.

**Comment by jotamartos** [comment]
Thanks for contributing to that project! Those changes will be really helpful :)

**Comment by techieshark** [comment]
Thanks @JDLH a random google search landed me here and this solved my same issue (using M1 chip and initially trying the VM image).
