### ISSUE TITLE
[MediaWiki Upgrade Path] How to upgrade Bitnami MediaWiki 1.26.2-0 to the latest MediaWiki 1.38.2-2r02 

### ISSUE THREAD

**Issue by lnguyen314** [bitnami/vms#322]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic output

N/A

### bndiagnostic was not useful. Could you please tell us why?

Way too old, issue pre-dates bndiagnostic

### Describe your issue as much as you can

I have a very old version of Bitnami MediaWiki 1.26.2-0 and I'm trying to update to the latest Bitnami MediaWiki container or VM version 1.38.2-2r02,  is there an upgrade path that will allow me to do this?  If yes, can you describe the path using publicly available material?

**Comment by mdhont** [comment]
The following guide may be of help:

https://docs.bitnami.com/installer/apps/mediawiki/administration/upgrade/
