### ISSUE TITLE
[Lightsail] Need suggestions for running concurrent processes on PHP and server setup

### ISSUE THREAD

**Issue by dshevnock** [bitnami/vms#323]
### Describe your issue as much as you can

I need to setup a new Lightsail server so I can run concurrent processes. I considered using pcntl_fork() but I believe I would be better served using (the latest and greatest) Fiber on a PHP 8.1 server. 

If I wanted to go down the Fiber path, is my only option to setup a Lightsail OS only server and then install Bitnami LAMP stack (https://bitnami.com/stack/lamp/virtual-machine) or is there another route to take (for example, does the Lightsail Wordpress install come with >= PHP 8.1)?
- I am not a server admin so the less server management the better. I would prefer not to spend a bunch of time managing updates, etc.
- this server would not need to be publicly accessible. Just need it to handle background-type processes but it would need to have access to cUrl.
- I would not prefer to learn another language outside of PHP at this time

Or, would I be better server just sticking with the Lightsail LAMP server and using pcntl_fork() (or some other equivalent) on PHP 7.*?

To clarify, this question isn't so much about whether about whether I use pcntl_fork() or Fiber -- its more about how I would setup the server (OS only/LAMP stack install **OR** using the off-the-shelf Lightsail LAMP server setup).

**Comment by mdhont** [comment]
Bitnami WordPress on AWS LightSail uses PHP 8.1 so I guess the best option would be to use that.

**Comment by dshevnock** [comment]
Thanks @mdhont. Is there a way to then disable Wordpress?

**Comment by mdhont** [comment]
Sorry for the confusion. Unfortunately on LightSail our LAMP solution is using 7.4. However on [EC2](https://aws.amazon.com/marketplace/pp/prodview-6g3gzfcih6dvu?sr=0-1&ref_=beagle&applicationId=AWSMPContessa) it's using the latest version. I recommend using that instead.
