### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by DJ05GaZ** [bitnami/vms#326]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f7f64c17-2958-771f-1cb6-02d3159dc150

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Sep 12 15:26:49.411661 2022] [ssl:emerg] [pid 1553:tid 140243852008320] 
AH02562: Failed to configure certificate mcnallyev.uk:443:0 (with chain), check 
/opt/bitnami/apache/conf/bitnami/certs/server.crt
Press [Enter] to continue:
 [Mon Sep 12 15:26:49.411733 2022] [ssl:emerg] [pid 1553:tid 140243852008320] 
SSL Library Error: error:0908F066:PEM routines:get_header_and_data:bad end line
 [Mon Sep 12 15:26:49.411748 2022] [ssl:emerg] [pid 1553:tid 140243852008320] 
SSL Library Error: error:140DC009:SSL routines:use_certificate_chain_file:PEM 
lib

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 66 of /opt/bitnami/apache2/conf/httpd.conf: Cannot 
load modules/mod_mpm_event.so into server: 
/opt/bitnami/apache/modules/mod_mpm_event.so: undefined symbol: 
ap_run_child_stopping
```
Please check the configuration.

System Apache is running:
```
Press [Enter] to continue:
root 588 0.0 0.1 6376 4212 ? Ss 16:12 0:00 /usr/sbin/apache2 -k start www-data 
590 0.0 0.1 1211108 6136 ? Sl 16:12 0:00 /usr/sbin/apache2 -k start
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

I couldnt find a guide that was helpful, I tried many tutorials without sucess.

### Describe your issue as much as you can

The problem started once the server was rebooted, after trying to setup the SSL using certbot. Also a vhosts file was created for use with mautic installation. Im not sure which one was the cause. I have deleted the mautic.conf from vhosts but still can not get the site back online. 

Permissions are set properly for the SSL files and links are working.

**Comment by jotamartos** [comment]
Hi @DJ05GaZ,

First of all, please set the application and a title in the title field of the ticket. That info will be useful for the users when browsing the different tickets in the forum.

Regarding your issue, the bndiagnostic told you that there is another Apache process running in the instance. That's why you can't start the Bitnami's one and access the application. Please check this other ticket 

https://github.com/bitnami/vms/issues/26

If you continue running into issues with the SSL cert, please generate new SSL certificates by following our guides or ask the certbot team to generate new ones using that tool

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
