### ISSUE TITLE
[WordPress with NGINX and SSL packaged by Bitnami] <Sudden Drop in Traffic>

### ISSUE THREAD

**Issue by vgnavada** [bitnami/vms#327]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f1eaebcb-8db3-7f81-eed9-7e85b4e255c9

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Nginx: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ? Wordpress: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2022/09/12 16:31:43 [crit] 1100#1100: *90733 connect() to 
unix:/opt/bitnami/php/var/run/www.sock failed (2: No such file or directory) 
while connecting to upstream, client: **ip_address**, server: _, request: "GET 
/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKW
orker.js.php?appId=45156f3d-b1af-48ec-8f21-d73c4ed875a9?sdkVersion=151514 
Press [Enter] to continue:
HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"newsnext.live", referrer: "https://newsnext.live/k 2022/09/12 16:39:20 [error] 
30788#30788: *1017 FastCGI sent in stderr: "Primary script unknown" while 
reading response header from upstream, client: **ip_address**, server: _, 
request: "GET /wp-includes/js/tinymce/plugins/colorpicker/content.php HTTP/1.1", 
upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"newsnext.live"
 2022/09/12 16:39:31 [error] 30790#30790: *764 FastCGI sent in stderr: "PHP 
message: PHP Notice: Unknown: file created in the system's temporary directory 
in Unknown on line 0" while reading response header from upstream, client: 
**ip_address**, server: _, request: "POST /wp-admin/async-upload.php HTTP/1.1", 
upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"newsnext.live", referrer: 
"https://newsnext.live/wp-admin/post.php?post=35800&action=edit"

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

[Mariadb]

Press [Enter] to continue:
Found recent error messages in the MariaDB error log:
```
2022-09-12 16:31:41 40278 [Warning] Aborted connection 40278 to db: 
'bitnami_wordpress' user: 'bn_wordpress' host: 'localhost' (Got an error reading 
communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Wordpress]

Found recent WordPress plugin related error messages in the Nginx error log.
```
2022/09/12 16:39:20 [error] 30788#30788: *1017 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET 
/wp-includes/js/tinymce/plugins/colorpicker/content.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "newsnext.live"

```
Press [Enter] to continue:
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

No Proper Answer to my question

### Describe your issue as much as you can

Hello,
Greetings!

Our website's traffic has dropped dramatically: https://newsnext.live

Everything was fine until September 1, 2022, when we received 2,27,794 pageviews.
It began to fall the following day and has not risen since.

We currently receive between 5,000 and 6,000 page views per month.
It's almost a 190% drop.

What could be the cause?
We're a group of non-technical people, and it's becoming increasingly difficult to figure out.
Could you please check and get back to us?

**Comment by mdhont** [comment]
As the bndiagnostic tool says, there seems to be an error with the colorpicker plugin. But I recommend disabling all plugins, check if WP is running ok without them, and then enabling them one by one.

    wp plugin deactivate --all
    sudo /opt/bitnami/ctlscript.sh restart apache
