### ISSUE TITLE
[<application>] <title>upload file size limit for multisites

### ISSUE THREAD

**Issue by mubiesam** [bitnami/vms#328]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8ddb3075-9657-edc7-cc6c-3085bfe9dd71

### bndiagnostic output

    ✓ Mysql: No issues found
    ✓ Connectivity: No issues found
    ? Php: Found possible issues
    ✓ Resources: No issues found
    ? Apache: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

guide to troubleshoot is not related to my issue

### Describe your issue as much as you can

Hi there,

Tried to increase upload file size limit to 200 MB for multisites, 
Set 204800 KB in network setting,
post_max_size = 200M / upload_max_filesize = 200M in php.ini
LimitRequestBody 204800 in httpd.conf

I can see upload file size limit: 200 MB correctly,  but an error message will occurred while adding a video file with 121.2 MB testimonial2grepay2_0.mp4,...
伺服器傳回未預期的回應。檔案可能已完成上傳，請查看媒體庫或重新載入頁面。
The server returned an unexpected response. The file may have finished uploading, please check the media library or reload the page.

But if I cut the video file size to 71.9 MB testimonial4grepay2_0.mp4, then the upload was successful.

Can you tell me what else I need to do to solve this issue...
Thanks

**Comment by mdhont** [comment]
Can you check this guide?

https://docs.bitnami.com/ibm/apps/wordpress/administration/increase-upload-limit-php/

**Comment by mubiesam** [comment]
I had followed that guide and stated...
post_max_size = 200M / upload_max_filesize = 200M in php.ini
LimitRequestBody 204800 in httpd.conf

I can see upload file size limit: 200 MB correctly, but an error message will occurred...

Thanks for your help.

**Comment by mubiesam** [comment]
@mdhont 

I did follow the guide, but the problem is strange, can you take a closer look into my question?

Thanks

**Comment by mdhont** [comment]
Try increasing the max_execution time as well:

```
upload_max_filesize = 256M
post_max_size = 256M
max_execution_time = 300
```

**Comment by mubiesam** [comment]
I changed all 3 parameters (256M/256M/300) according to your suggestion, but still can not add the video file with 121.2 MB testimonial2grepay2_0.mp4 while no problem to add testimonial4grepay2_0.mp4 with 71.9 MB.

Both video files are available here...
https://drive.google.com/drive/folders/1HZuceCx-fCKl_FMY-2QzoCRr6dWOUacL?usp=sharing

Any suggestion...
Thanks

**Comment by mdhont** [comment]
I recommend asking in the application's dedicated forum. The issue does not seem related to the Bitnami configuration and usually they will have a better understanding of the specifics of the application there.

**Comment by mubiesam** [comment]
Installed a plugin...Big File Uploads – Increase Maximum File Upload Size, problem solved.
Thanks for your help
