### ISSUE TITLE
[WordPress with NGINX] Virtual Machine not available in Bitnami Console

### ISSUE THREAD

**Issue by werobotgermany** [bitnami/vms#330]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

336d2fe4-2d01-eb3d-3b97-5e471b31a4b5

### bndiagnostic output

? Nginx found possible Issues:
2022/09/13 11:33:33 [error] 850#850: *26826 access forbidden by rule, client: 
**ip_address**, server: _, request: "POST /core/.env HTTP/1.1", host: 
"34.159.74.XX"
 2022/09/13 11:33:51 [error] 850#850: *26827 access forbidden by rule, client: 
**ip_address**, server: _, request: "GET /core/.env HTTP/1.1", host: 
"34.159.74.XX""
 2022/09/13 11:35:20 [error] 850#850: *26832 access forbidden by rule, client: 
**ip_address**, server: _, request: "POST /core/.env HTTP/1.1", host: 
"34.159.74.XX"

### bndiagnostic was not useful. Could you please tell us why?

I am not able to resolve this by the output. 

### Describe your issue as much as you can

Hi, 
after the successfull deployment of the VM on the GCP I am not able to access the project via the Bitnami Console. When I open the Cloud Credentials on Bitnami.com the project shows up but without a VM. How can I resolve this issue? 
Thanks!

**Comment by gongomgra** [comment]
Hi @werobotgermany,

Thanks for using Bitnami. If you launched your server using the Google Marketplace interface or the Google Cloud Console, it is not possible to manage it through the Bitnami Launchpad. Is that your case?
