### ISSUE TITLE
[WordPress with NGINX and SSL Certified by Bitnami and Automattic] server.csr no such file or directory SSL issue

### ISSUE THREAD

**Issue by levelingup** [bitnami/vms#332]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3b73d601-14f5-8121-4248-1edfae14ab8c

### bndiagnostic output

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ? Nginx: Found possible issues
    ? Processes: Found possible issues
    ? Wordpress: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides doesn't help with not loading my certificate

### Describe your issue as much as you can

When I tried to set up SSL, I'm having issues with this step:

sudo mv /opt/bitnami/nginx/conf/bitnami/certs/server.csr /opt/bitnami/nginx/conf/bitnami/certs/server.csr.old

in the section: For NGINX under Approach A (Bitnami installations using system packages)

It keeps saying that server.csr is not found. But when I was following the steps in https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach, I was able to get "Server responded with a certificate."

Not sure if this is the issue because I can't start my server anymore either.

**Comment by mdhont** [comment]
Can you skip that step and continue with the next command?

**Comment by levelingup** [comment]
When I try the next step, I get this command

```
chown: cannot dereference '/opt/bitnami/nginx/conf/bitnami/certs/server.crt.old': No such file or directory
chown: cannot dereference '/opt/bitnami/nginx/conf/bitnami/certs/server.key.old': No such file or directory
```

**Comment by mdhont** [comment]
Can you check if the file exists?

    ls -larth /opt/bitnami/nginx/conf/bitnami/certs

**Comment by levelingup** [comment]
it outputted this:

```
total 8.0K
drwxrwxrwx 3 bitnami bitnami 4.0K Sep  7 17:16 ..
lrwxrwxrwx 1 root    root      53 Sep 14 03:44 server.key.old -> /opt/bitnami/letsencrypt/certificates/{mydomainname}.key
lrwxrwxrwx 1 root    root      53 Sep 14 03:45 server.crt.old -> /opt/bitnami/letsencrypt/certificates/{mydomainname}.crt
lrwxrwxrwx 1 root    root      53 Sep 18 06:02 server.key -> /opt/bitnami/letsencrypt/certificates/{mydomainname}.key
lrwxrwxrwx 1 root    root      53 Sep 18 06:02 server.crt -> /opt/bitnami/letsencrypt/certificates/{mydomainname}.crt
drwxrwxrwx 2 bitnami bitnami 4.0K Sep 18 06:02 .
```

And {mydomainname} with my actual domain name, but just kept it hidden for security reasons. I don't need to actually have ".com" in it, right?

**Comment by mdhont** [comment]
It seems the server.key and  server.crt symlinks exists in `/opt/bitnami/nginx/conf/bitnami/certs` and are pointed to the certificate and key file in `/opt/bitnami/letsencrypt/certificates/`. Could you continue with giving the correct permissions?

    sudo chown root:root /opt/bitnami/nginx/conf/server*
    sudo chmod 600 /opt/bitnami/nginx/conf/server*

And then restart nginx?

    sudo /opt/bitnami/ctlscript.sh restart nginx

**Comment by levelingup** [comment]
Thanks, those commands, work. A couple of things to note that I"m confused. Looks like that command is as if I have the Approach B, vs Approach A?

I used the command:

```
test ! -f "/opt/bitnami/common/bin/openssl" && echo "Approach A: Using system packages." || echo "Approach B: Self-contained installation."
```

and it output `Approach A: Using system packages.`

Another thing, is I tried to start my server using:

```
sudo /opt/bitnami/ctlscript.sh start
```

I get an error output:

```
Starting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.
```

**Comment by mdhont** [comment]
It seems the machine does not have a lot of available resources, which could explain the services not being able to start. I recommend launching another more powerful instance and try again, using the approach A or B depending on the output of the command:

    test ! -f "/opt/bitnami/common/bin/openssl" && echo "Approach A: Using system packages." || echo "Approach B: Self-contained installation."

**Comment by levelingup** [comment]
I can't just stop the same service and then change the instance? Do I have to create a new one completely?

**Comment by mdhont** [comment]
Yes, it's possible, you can find more information here:

https://docs.bitnami.com/aws/faq/administration/change-server-type/

**Comment by levelingup** [comment]
okay, yeah so I was able to switch the instance... 

When I tried to start the service, i still get the same error.

```
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.
```

However, when I checked status by running: `sudo /opt/bitnami/ctlscript.sh status` I get:

```
mariadb already running
nginx not running
php-fpm already running
```

The instance is currently t3.small

**Comment by mdhont** [comment]
Can you check my reply here? 

https://github.com/bitnami/vms/issues/359
