### ISSUE TITLE
[wordpress] The site gets down like every weekend

### ISSUE THREAD

**Issue by binampHTG** [bitnami/vms#336]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e1e61d8c-8203-33c5-713c-4cdd1eb68bc5

### bndiagnostic was not useful. Could you please tell us why?

The error could not exactly define the issue

### Describe your issue as much as you can

My site is getting down almost every time during the week. We are currently using WordPress provided by Bitnami with Lightsail for all the instances.
The Bitnami diagnostic tool shows the log as "Your instance has little available RAM memory." but we are currently having 1 GB RAM. Since the website is static and we don't change the posts/pages every week. So, with these considerations, we think this is not actually what's happening to the website. Also, currently, we are having 5 instances out of which 3 instances go down every once a week. So, can you explain what's wrong with our configurations or the reasons for actual errors that are occurring in almost all of the instances every once a week?

**Comment by gongomgra** [comment]
Hi @binampHTG,

Thanks for using Bitnami. Your issues can be related to the kind of server used in Lightsail instances (burstable instances) that reduce their performance once all the CPU credits have been consumed. It can also be related to bots making a lot of requests on your server to exhaust its resources.

```
-----------------------------------
Check performance issues: Count number of requests for the 10 most active IP addresses in the last 100.000 requests
-----------------------------------
Running: tail -n 100000 access_log | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 10 | awk '{print $1}'
In: /opt/bitnami/apache2/logs/

Output:

5757
2069
1957
1666
1604
1357
1244
1218
1163
1158
```

We recommend you to check our [guide about bots](https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/) and how to block them.

I also found a couple of WordPress errors that we recommend you to check

```
PHP Notice:  Constant WP_HOME already defined in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 188
PHP Notice:  Constant WP_SITEURL already defined in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 189
```

Finally, the bndiagnostic tool detected that your instance is running short on free RAM memory. We recommend you to increase your instance type to solve this

```
-----------------------------------
Display amount of free and used memory in the system
-----------------------------------
Running: free -m
In: /opt/bitnami

Output:

              total        used        free      shared  buff/cache   available
Mem:            987         614          66         104         305         114
Swap:           634          64         570
```
