### ISSUE TITLE
[Wordpress] How can I get the rewrite permissions?

### ISSUE THREAD

**Issue by DJG70** [bitnami/vms#337]
### Describe your issue as much as you can

Hello,

How can I get the rewrite permissions for the files:
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf
/opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf

I need to add little piece of code,, but can't do it because of permissions.

Thanks.

**Comment by DJG70** [comment]
I know how to use ssh I just need the command code

**Comment by mdhont** [comment]
You need to open the files with sudo permissions:

    sudo nano /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf

**Comment by DJG70** [comment]
> You need to open the files with sudo permissions:
> 
> ```
> sudo nano /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf
> ```

Thank you so much!
