### ISSUE TITLE
[WordPress] Admin panel is working but site is showing cant reach page

### ISSUE THREAD

**Issue by Rishabhbhutoria** [bitnami/vms#338]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

fd4d8955-1010-be1d-44f0-fa945d3bac98

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

after importing from all in one wp migrator when opening the 127.0.0.1/wordpress it shows cant reach page wheras admin panel on same 127.0.0.1/wordpress/wp-admin is working fine

The files listed below are bigger than 10MB and have not been included, please notify the support agent.

C:/Bitnami/wordpress-6.0.2-0/apache2/logs/error.log

**Comment by Rishabhbhutoria** [comment]
![Screenshot (141)](https://user-images.githubusercontent.com/78445765/190852463-737bd1c2-0368-4b94-94be-c038cba815ad.png)
![Web capture_17-9-2022_16351_127 0 0 1](https://user-images.githubusercontent.com/78445765/190852503-1cd2dbf6-0309-45de-9a6a-dc697388e8cf.jpeg)

**Comment by jotamartos** [comment]
Hi @Rishabhbhutoria,

Thank you for using our solution. That's a specific question about the application so we suggest you ask in the official forums of the application to get more information about that. Please note that if you can access the admin panel, you should be able to access the main site. The app's documentation should describe how to troubleshoot this issue.

https://wordpress.org/support/

However, we will also keep this ticket open in this forum in case any Bitnami user configured the application they way you want to. 

Thanks

**Comment by Cchirag-Selarkka** [comment]
I am facing the same issue too
![Bitnami error message](https://user-images.githubusercontent.com/114140081/191691548-fae1e60c-c95c-404b-9171-c223b07dcf0f.jpeg)

But not able to get the fix from any one.

**Comment by jotamartos** [comment]
Hi @Rishabhbhutoria,

You mentioned you could access the admin panel before, is that correct? What did you change to make it fail too? Please note that you will need to undo all the changes you applied lately to know if that's the problem. 

However, we also suggest you check if all services are up and running right now as well as take a look at the Apache's log to see if there is any error there

https://docs.bitnami.com/installer/apps/wordpress/troubleshooting/debug-errors-apache/

**Comment by Rishabhbhutoria** [comment]
@jotamartos I just reinstaled bitnami wordpress and just after that i am facing this issue even after using all in one WP migrator my site is down

**Comment by Rishabhbhutoria** [comment]
@Cchirag-Selarkka are you using bitnami wordpress

**Comment by Cchirag-Selarkka** [comment]
> @Cchirag-Selarkka are you using bitnami wordpress

I unistall Bitnami and now trying to reinstall after disabling the Firewall. Let me see what response I get. But I am with your views as the sites goes slow and machine also goes slow. Even after uninstalling the bitnami on my machine still machine is running slow which was not this case earlier.  I am beiginer in WP domain so lots of things to understand.

**Comment by Cchirag-Selarkka** [comment]
@Rishabhbhutoria I have reinstalled the Bitnami. is this not correct or any issues ? please do let me know

**Comment by Rishabhbhutoria** [comment]
@Cchirag-Selarkka @jotamartos Hi, so what i got to know from some internet searches was that the error was there because of some server issue either it had less space alloted
Solution that worked for me
Instead of bitnami wordpress install XAMPP and install wordpress through it

**Comment by jotamartos** [comment]
>so what i got to know from some internet searches was that the error was there because of some server issue either it had less space alloted

In that case, there should be an error in the Apache's or PHP's log files and you didn't see anything, right?

**Comment by Cchirag-Selarkka** [comment]
@Rishabhbhutoria

> @Cchirag-Selarkka @jotamartos Hi, so what i got to know from some internet searches was that the error was there because of some server issue either it had less space alloted Solution that worked for me Instead of bitnami wordpress install XAMPP and install wordpress through it

No I have lots of space in my laptop and now I have installed Xampp but both performace wise are not good.. Xampp and WP access made my Laptop speed low and slow...

**Comment by Cchirag-Selarkka** [comment]
> > so what i got to know from some internet searches was that the error was there because of some server issue either it had less space alloted
> 
> In that case, there should be an error in the Apache's or PHP's log files and you didn't see anything, right?

I dont know what to comment now.. as WP is the really a task along with Local host access

**Comment by Rishabhbhutoria** [comment]
@jotamartos there might have been issue in apache or php but yes i did not see anything

**Comment by Rishabhbhutoria** [comment]
@Cchirag-Selarkka it dose not matter weather your laptop have space or not

**Comment by Cchirag-Selarkka** [comment]
> @Cchirag-Selarkka it dose not matter weather your laptop have space or not

Thank you @Rishabhbhutoria for your quick response. It will be great if you share your expertise help me into WP

**Comment by Rishabhbhutoria** [comment]
@Cchirag-Selarkka actully I am also a biginner but still if you are facing any issue we can try to work on it togather

**Comment by jotamartos** [comment]
As I mentioned, you will need to look for errors in the Apache's log file. That file is at installdir/apache2/logs/error.log in the case of the Bitnami WordPress solution. If you are using XAMPP, please take a look at its documentation to know where that file is. Once you find the file, please investigate the errors that appear there. If you find nothing, please ensure Apache is running and contact WordPress to know how to investigate this issue.

**Comment by Cchirag-Selarkka** [comment]
@jotamartos Thank you for your assistance and quick suggestion to follow.
