### ISSUE TITLE
mautic by bitnami on google cloud error

### ISSUE THREAD

**Issue by hapishyguy** [bitnami/vms#34]
### Name and Version

bitnami/mautic/googlecloud

### What steps will reproduce the bug?

I clicked on install in google cloud for mautic package. I says its deployed under deployment and gives the external ip and username and temporary password. Whn I go to the IP to open mautic it gives the mautic error page 404. It dont even show the login page. Any idea what happened?

### What is the expected behavior?

Login page for mautic

### What do you see instead?

I see mautic error 404

**Comment by A360webservices** [comment]
I have had the same issue. I have tried to install Mautic from my AWS Bitnami subscription three times. After going through the installation process, I try the EC2 public IP, and I get a 404 error. When I look at the instance via the console, no Mautic files have been installed.

**Comment by mdhont** [comment]
Can you run the bndiagnostic tool?

    sudo /opt/bitnami/bndiagnostic-tool

And share the ID at the end of the output?

**Comment by A360webservices** [comment]
The result was this: a293227f-18ac-3030-11ac-aafab39de03e

I’ve been try to use GitHub CLI to install software. It worked fine before, now it keeps asking for a re-authentication each time, and fails to install the software.


From: Michiel ***@***.***>
Reply-To: bitnami/vms ***@***.***>
Date: Thursday, December 22, 2022 at 10:30 AM
To: bitnami/vms ***@***.***>
Cc: Web Services ***@***.***>, Comment ***@***.***>
Subject: Re: [bitnami/vms] mautic by bitnami on google cloud error (Issue #34)


Can you run the bndiagnostic tool?

sudo /opt/bitnami/bndiagnostic-tool

And share the ID at the end of the output?

**Comment by A360webservices** [comment]
I ran the command with `sudo`.

Looks like I need more memory.

Results:

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
[Resources]

Your instance has little available RAM memory.
```
total used free shared buff/cache available Mem: 472 299 7 4 165 155 Swap: 634
6 628
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Dec 22 18:03:07.066077 2022] [core:error] [pid 1339:tid 140718070843136]
[client **ip_address**:39368] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Thu Dec 22 18:11:27.911128 2022] [core:error] [pid 1339:tid 140718054057728]
[client **ip_address**:56456] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Thu Dec 22 18:19:58.508148 2022] [core:error] [pid 659:tid 140212473546496]
[client **ip_address**:52362] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

```
Please check the following guide to troubleshoot server issues:
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====


From: Michiel ***@***.***>
Reply-To: bitnami/vms ***@***.***>
Date: Thursday, December 22, 2022 at 10:30 AM
To: bitnami/vms ***@***.***>
Cc: Web Services ***@***.***>, Comment ***@***.***>
Subject: Re: [bitnami/vms] mautic by bitnami on google cloud error (Issue #34)


Can you run the bndiagnostic tool?

sudo /opt/bitnami/bndiagnostic-tool

And share the ID at the end of the output?

**Comment by A360webservices** [comment]
Sure. I've deleted that instance. I'll try to reinstall and run the diagnostic. The other replies, that I deleted are from my issues trying to install Mautic on a Lightsail instance on my own.

**Comment by A360webservices** [comment]
OK. I installed a new instance and it worked. I've logged in. It's like taking your car to the mechanic, once you get there the pinging sounds goes away. Thanks for your help!
