### ISSUE TITLE
[WordPress Production-Ready] <Couldn't Connect to WordPress Instance Through Bastion Host>

### ISSUE THREAD

**Issue by TokCentral** [bitnami/vms#340]
### Describe your issue as much as you can

I Launched the (WordPress Production-Ready Certified by Bitnami and Automattic Stack).
Here I am Unable to connect to my main WordPress instance through Bastion host. I followed the steps line by line But still no success.
I found no videos for this in your Bitnami website or Youtube.
>>I entered into bastion host But couldn't enter WordPress instance from there. It gave Permission denied (publickey) error.
>>Also which method should I prefer for creating key pair -- Should I take .pem file or .ppk which is better? As I prefer (.ppk) But no luck here.
>>Next, I want to ask how to redirect (naked domain) example.com to https://www.example.com version.
 Because when I put A records for both to Cloudfront then each one of them are getting (https) but in there habitat like:- example.com --> https://example.com & 
www.example.com --> https://www.example.com
I want to everything to open in Https://www Version.
Lastly, I am only worried about the naked domain name.
>>Also I see two extra Elastic IPs on console, which are unused but are created in this stack. I didn't understood it? Please explain.

I have tried hundreds of Lightsail instances but never faced any issue that I can't fix. But this Stack is different But Very Fast. So, Please my problem & help me to run it again.

**Comment by TokCentral** [comment]
Please Tell How to Solve this issue.

**Comment by TokCentral** [comment]
Please tell...I am really stuck at this stage.

**Comment by TokCentral** [comment]
Hello Bitnami Support team, Please do reply because in production stack AWS will be Billing me. So, Please help me out fast.

**Comment by mdhont** [comment]
Did you check this guide?

https://docs.bitnami.com/aws-templates/infrastructure/lamp-production-ready/get-started/connect-ssh/

**Comment by mdhont** [comment]
Could you tell me the output of `ssh-add -L`?  Also please check the Putty documentation. 

https://the.earth.li/~sgtatham/putty/0.77/htmldoc/AppendixA.html#faq-trouble

**Comment by TokCentral** [comment]
It gives:- could not open a connection to your authentication agent.

**Comment by mdhont** [comment]
Can you check the AWS guide? 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html

**Comment by TokCentral** [comment]
I tried but not working, Please @mdhont Try test to Run yourself install this stack & SSH into it, You will know the Glitch. Create a Video So that others can also benefit from it.
Please Do early as possible because this stack is costly running on aws.

**Comment by mdhont** [comment]
I haven't been able to reproduce the issue. I recommend asking in an AWS forum.
