### ISSUE TITLE
[WordPress with Amazon Aurora Certified] Can't Install Lets Encrypt SSL Through Bncert-tool

### ISSUE THREAD

**Issue by TokCentral** [bitnami/vms#341]
### Describe your issue as much as you can

I Tried implementing Bitnami WordPress with Amazon Aurora Certified Stack on AWS But can't install lets encrypt ssl.
Please do answer me question by question.
1) I launch a WordPress with Amazon Aurora Certified by Bitnami and Automattic from AWS Marketplace. But When I did to install Let's Encrypt ssl through the sudo /opt/bitnami/bncert-tool, Then it resulted in an installation error:-
{ An error occurred when applying configurations.
The web server configuration was left unchanged. There was an error in the new configuration, so it was reverted.
Failed steps:
 Starting web server: Failed to start. }

2)I have tried many times, and deleted the stack & again installed the same WordPress stacks but same error. So, please check what is causing the error from your side.

3)I also figured the (sudo /opt/bitnami/ctlscript.sh) won't work here, and some how got the new commands (sudo service command bitnami).

4)Sir, Also there is not tutorial for this stack on your Bitnami Docs Website.

**Comment by TokCentral** [comment]
Please tell how to solve it

**Comment by gongomgra** [comment]
Hi @TokCentral,

Thanks for using Bitnami. I'm afraid for multi-tier solutions it is not possible to configure a Let's Encrypt certificate as it resides in the server itself and in the multi-tier case there are N servers serving the WordPress application. For the multi-tier use case, you have to serve the SSL certificate through CloudFlare as explained in our guide linked below

https://docs.bitnami.com/aws-templates/faq/administration/enable-ssl-cloudflare/

You can also find all the multi-tier related guides under the next section of our documentation site

https://docs.bitnami.com/aws-templates/

Hope it helps!
