### ISSUE TITLE
[Plone] 503 error

### ISSUE THREAD

**Issue by CuAnnan** [bitnami/vms#342]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

07df0285-7bd1-f3c6-7d62-8a6c8ffd6901

### bndiagnostic output

----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

||
The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Sep 19 15:02:54.104672 2022] [proxy_http:error] [pid 24297] [client
**ip_address**:37924] AH01114: HTTP: failed to make connection to backend:
127.0.0.1
 [Mon Sep 19 15:02:54.105060 2022] [proxy:error] [pid 24297] (111)Connection
refused: AH00957: http: attempt to connect to **ip_address**:8081 (*) failed
 [Mon Sep 19 15:02:54.105104 2022] [proxy_http:error] [pid 24297] [client
**ip_address**:37924] AH01114: HTTP: failed to make connection to backend:
127.0.0.1
Press [Enter] to continue:

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1965 1491 76 34 397 271 Swap:
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

Press [Enter] to continue:
===== End of bndiagnostic tool output =====

Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

07df0285-7bd1-f3c6-7d62-8a6c8ffd6901

And paste it in your Bitnami Support ticket.

### bndiagnostic was not useful. Could you please tell us why?

didn't give me literally anything except "we've got a 503" which is the problem.

### Describe your issue as much as you can

503 error on attempt to open the ip address directly via the aws panel.

**Comment by CuAnnan** [comment]
/opt/bitnami/apache2/logs$ wget 127.0.0.1
--2022-09-21 14:28:16--  http://127.0.0.1/
Connecting to 127.0.0.1:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2022-09-21 14:28:16 ERROR 503: Service Unavailable.

**Comment by CuAnnan** [comment]
the zeocluster client1 event log says it's ready to handle requests.
the zeoserver log says
2022-09-21T14:28:01 daemonizing the process
2022-09-21T14:28:01 set current directory: '/opt/bitnami/apps/plone/zeocluster/parts/zeoserver'
2022-09-21T14:28:01 daemon manager started
2022-09-21T14:28:01 spawned process pid=1356
2022-09-21T14:28:02 (1356) created PID file '/opt/bitnami/apps/plone/zeocluster/var/zeoserver/zeoserver.pid'
2022-09-21T14:28:02 (1356) opening storage '1' using FileStorage
2022-09-21T14:28:02 StorageServer created RW with storages: 1:RW:/opt/bitnami/apps/plone/zeocluster/var/filestorage/Data.fs
2022-09-21T14:28:02 listening on ('127.0.0.1', 8100)
2022-09-21T14:28:10 Connected server protocol
2022-09-21T14:28:10 received handshake 'Z5'

**Comment by jotamartos** [comment]
Hi @CuAnnan,

As  you mentioned, the process seems to be running but Apache is returning a 503 error message when accessing the application. I suggest you ask the Plone's developers to get more info about the error. Please note that Apache uses a RewriteRule to access the app, did you modify the Apache's conf or the Plone's one recently? Please investigate if you can reach the ZeoCluster process directly without using Apache and get the error code it returns

```
RewriteRule ^/(.*)$ http://127.0.0.1:8081/VirtualHostBase/https/%{SERVER_NAME}:443/VirtualHostRoot/$1 [L,P]
```

As I mentioned, the Plone's support team should provide more information

https://community.plone.org/

**Comment by CuAnnan** [comment]
hey @jotamartos 
If I contact Plone with "I'm getting a 503 with bitnami's Plone distro but no errors elsewhere", I very much expect they will reply with "sounds like a bitnami problem". In the event that that occurs, what do you recommend I do next? There's no error number, there's no error log. Apache is just not connecting to the plone.

**Comment by jotamartos** [comment]
Hi @CuAnnan,

The solution passed our tests in our pipeline and it worker properly when you launched it, right? Did you change something in the app's configuration or install a plugin/theme in the application that may causing this error? In that case, you will need to investigate what's wrong in the app and revert the change or fix it. Once the app works, you should be able to access it through Apache.

**Comment by CuAnnan** [comment]
I have not changed anything in the app's configuration or installed a plugin.
I've installed mongodb on the default ports and have some scripts in a different folder running that populate the mongo db.

**Comment by CuAnnan** [comment]
[Tue Sep 27 10:36:51.390416 2022] [proxy:error] [pid 19455] (111)Connection refused: AH00957: http: attempt to connect to 127.0.0.1:8081 (*) failed
[Tue Sep 27 10:36:51.390429 2022] [proxy_http:error] [pid 19455] [client 127.0.0.1:54920] AH01114: HTTP: failed to make connection to backend: 127.0.0.1

This is what the apache logs respond with.

**Comment by CuAnnan** [comment]
curl: (7) Failed to connect to 127.0.0.1 port 8081 after 0 ms: Connection refused
And curl

**Comment by CuAnnan** [comment]
netstat -pnlt
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:41421         0.0.0.0:*               LISTEN      25763/google-chrome
tcp        0      0 127.0.0.1:37613         0.0.0.0:*               LISTEN      25043/google-chrome
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:43985         0.0.0.0:*               LISTEN      313/google-chrome
tcp        0      0 127.0.0.1:33297         0.0.0.0:*               LISTEN      19531/google-chrome
tcp        0      0 127.0.0.1:36209         0.0.0.0:*               LISTEN      8369/chromedriver
tcp        0      0 127.0.0.1:42677         0.0.0.0:*               LISTEN      13795/chromedriver
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:56599         0.0.0.0:*               LISTEN      3386/chromedriver
tcp        0      0 127.0.0.1:59929         0.0.0.0:*               LISTEN      307/chromedriver
tcp        0      0 127.0.0.1:44537         0.0.0.0:*               LISTEN      25037/chromedriver
tcp        0      0 127.0.0.1:38105         0.0.0.0:*               LISTEN      2874/google-chrome
tcp        0      0 127.0.0.1:37787         0.0.0.0:*               LISTEN      31767/chromedriver
tcp        0      0 127.0.0.1:37211         0.0.0.0:*               LISTEN      19525/chromedriver
tcp        0      0 127.0.0.1:36125         0.0.0.0:*               LISTEN      31773/google-chrome
tcp        0      0 127.0.0.1:43617         0.0.0.0:*               LISTEN      8375/google-chrome
tcp        0      0 127.0.0.1:41443         0.0.0.0:*               LISTEN      7893/google-chrome
tcp        0      0 127.0.0.1:37859         0.0.0.0:*               LISTEN      3392/google-chrome
tcp        0      0 127.0.0.1:8100          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:54725         0.0.0.0:*               LISTEN      25757/chromedriver
tcp        0      0 127.0.0.1:41157         0.0.0.0:*               LISTEN      7887/chromedriver
tcp        0      0 127.0.0.1:48773         0.0.0.0:*               LISTEN      2868/chromedriver
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:34571         0.0.0.0:*               LISTEN      13801/google-chrome
tcp6       0      0 :::80                   :::*                    LISTEN      -
tcp6       0      0 ::1:36209               :::*                    LISTEN      8369/chromedriver
tcp6       0      0 ::1:42677               :::*                    LISTEN      13795/chromedriver
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 ::1:56599               :::*                    LISTEN      3386/chromedriver
tcp6       0      0 ::1:59929               :::*                    LISTEN      307/chromedriver
tcp6       0      0 ::1:44537               :::*                    LISTEN      25037/chromedriver
tcp6       0      0 :::443                  :::*                    LISTEN      -
tcp6       0      0 ::1:37787               :::*                    LISTEN      31767/chromedriver
tcp6       0      0 ::1:37211               :::*                    LISTEN      19525/chromedriver
tcp6       0      0 ::1:54725               :::*                    LISTEN      25757/chromedriver
tcp6       0      0 ::1:41157               :::*                    LISTEN      7887/chromedriver
tcp6       0      0 ::1:48773               :::*                    LISTEN      2868/chromedriver

Nothing listening on 8081

**Comment by CuAnnan** [comment]
sudo /opt/bitnami/ctlscript.sh status
apache already running
zope already running
zeo already running

**Comment by CuAnnan** [comment]
Is it possible to nuke and pave from the command line? The Plone instance was fresh.

**Comment by jotamartos** [comment]
Hi @CuAnnan,

It's Plone what is not available and that's why you get that error message. If you do not find anything in the logs, you can try reseting the services to see if that resolves the problem 

```
sudo /opt/bitnami/ctlscript.sh restart
```

If you want to reset the deployment, you will need to launch a new instance.

**Comment by CuAnnan** [comment]
> 

sudo /opt/bitnami/ctlscript.sh restart
Syntax OK
/opt/bitnami/apache2/scripts/ctl.sh : httpd stopped
.
daemon process stopped
.
daemon process stopped
.
daemon process started, pid=23652
.
daemon process started, pid=23663
Syntax OK
/opt/bitnami/apache2/scripts/ctl.sh : httpd started at port 80

**Comment by CuAnnan** [comment]
Where can I find the Plone logs?

**Comment by jotamartos** [comment]
The Plone's files are inside the /opt/bitnami/apps/plone/htdocs. You should find the log files there.

**Comment by jotamartos** [comment]
Sorry for the wrong path. You can find some log files inside the /opt/bitnami/apps/plone/zeocluster/var/client1 folder. You can also take a look at the /opt/bitnami/apps/plone/scripts/ctl.sh to know how to manually launch the server and obtain more data. 

Please note that Plone is not supported by Bitnami anymore. You will need to investigate what's happening in the solution and contact Plone if you have any questions regarding the application.
