### ISSUE TITLE
Upgrade or Un-install Python in the Bitnami Stack

### ISSUE THREAD

**Issue by jopel-processia** [bitnami/vms#344]
### Describe your issue as much as you can

Hello, I am looking for advice or instructions on how to uninstall or upgrade the Python in the Bitnami stack. Or point me in the right direction if this is not the correct forum.

**Comment by mdhont** [comment]
Unfortunately upgrading individual components of Bitnami applications is not supported. I recommend launching a new instance with the latest component's version and then migrate the data.

**Comment by jopel-processia** [comment]
> Unfortunately upgrading individual components of Bitnami applications is not supported. I recommend launching a new instance with the latest component's version and then migrate the data.

**Comment by jopel-processia** [comment]
> Unfortunately upgrading individual components of Bitnami applications is not supported. I recommend launching a new instance with the latest component's version and then migrate the data.

From jopel: Thank you very much for the response. That was helpful. One quick follow up question. Can the Python software simply be "Removed" from the "Stack"

**Comment by mdhont** [comment]
It's possible but not straightforward because it requires some advanced Linux knowledge. Unfortunately it exceeds the scope of this forum.

**Comment by jopel-processia** [comment]
> It's possible but not straightforward because it requires some advanced Linux knowledge. Unfortunately it exceeds the scope of this forum.

Thank you very much. That should conclude my questions on this topic. Again, thanks

**Comment by jopel-processia** [comment]
Great support on this forum. Cant wait to come back
