### ISSUE TITLE
[wordpress] Does bitnami wordpress location of robots.txt

### ISSUE THREAD

**Issue by xgaibtcgd** [bitnami/vms#347]
### Describe your issue as much as you can

Does the bitnami wordpress (google cloud) ship with a different location of robots.txt than what would be under your apps/wordpress/htdocs/ folder?

was there any reason there is no default robots.txt?

**Comment by jotamartos** [comment]
We changed the directory structure of the Bitnami solutions almost 2 years ago and you can now find the WordPress' files inside the /opt/bitnami/wordpress folder.

**Comment by Ravizaum** [comment]
Either deprecated or plain wrong

**Comment by jotamartos** [comment]
Hi @Ravizaum,

Why do you say that? We changed the directory structure and all the WordPress files are now inside the /opt/bitnami/wordpress directory. If you have an old version, you can find those files in the /opt/bitnami/apps/wordpress/htdocs directory. 

Regarding the robots.txt file, we do not create it. It's something you need to create to position your site and your domain in the search engine results.
