### ISSUE TITLE
[alfresco]PDF preview and AOS

### ISSUE THREAD

**Issue by HiroyukiSakachi** [bitnami/vms#348]
Hi,

This issue may be the same as #345.

I'm testing bitnami alfresco and I'm experiencing some strange behavior.
can anyone help me
I created two environments, one from the AWS marketplace and one that created an AWS instance from the bitnami site, but I'm encountering the same phenomenon in both.
I have already dealt with SSL with bncert-tool.

1. The PDF preview of the office file uploaded to the document library as a test is not displayed.
Oddly enough, it can also appear right after environment creation.
Modify /opt/bitnami/tomcat/shared/classes/alfresco-global.properties
transformer.strict.mimetype.check=false
had no effect.
2. AOS does not work perfectly.
Alfresco Office Services Module - Version: 1.4.1
However, EXCEL etc. cannot open that file. Should I open any additional ports?
3. Recently modified content in the dashboard will show as "Error loading item".

**Comment by HiroyukiSakachi** [comment]
alfresco.log

2022-09-22 05:51:34,690 ERROR [org.alfresco.repo.web.scripts.RepositoryContainer] [http-nio-8080-exec-5] Server error (08220039)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 08220036 libreoffice returned a 500 status All in One Transformer - this OfficeManager is currently stopped http://localhost:8090/transform targetExtension=pdf sourceEncoding=UTF-8 sourceMimetype=application/vnd.openxmlformats-officedocument.presentationml.presentation sourceExtension=pptx targetMimetype=application/pdf
2022-09-22 05:51:34,693 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-5] Exception from executeScript: Server error (08220039).  Details can be found in the server logs.
java.lang.RuntimeException: Server error (08220039).  Details can be found in the server logs.
Caused by: org.alfresco.error.AlfrescoRuntimeException: 08220041 Failed to execute search: +PATH:"/app:company_home/st:sites/cm:test/cm:documentLibrary//*" +@cm\:modified:[2022\-9\-15T00\:00\:00.000 TO 2022\-9\-22T23\:59\:59.999] +@cm\:modifier:"admin" +TYPE:"cm:content" -TYPE:"cm:systemfolder" -TYPE:"fm:forums" -TYPE:"fm:forum" -TYPE:"fm:topic" -TYPE:"fm:post" +(TYPE:"content" OR TYPE:"app:filelink" OR TYPE:"folder")

**Comment by HiroyukiSakachi** [comment]
$ sudo sh ./ctlscript.sh status
activemq already running
alfresco-search-services not running
alfresco-transform-core already running
apache already running
mariadb already running
tomcat already running

**Comment by gongomgra** [comment]
Hi @HiroyukiSakachi,

Thanks for using Bitnami. We have a guide for installing Alfresco Office Services. Did you find any error installing it?

https://docs.bitnami.com/aws/apps/alfresco/configuration/install-plugins-aos/

If you follow our guide without issues and you continue having errors, we recommend you to ask the official Alfresco developers for further help on how to debug this.

**Comment by HiroyukiSakachi** [comment]
Hi gongomgra.
Thank you for your support.
I understand my situation a little.
First, how to install

$ test ! -f "/opt/bitnami/common/bin/openssl" && echo "Approach A: Using system packages." || echo "Approach B: Self-contained installation."
Approach A: Using system packages.

However, I haven't done AOS installation yet.
About that, I'll try it tomorrow and report back here.
Sorry, it's already midnight here in Japan.

**Comment by HiroyukiSakachi** [comment]
Hi gongomgra.
I have checked myself and tried your advice.
I tried creating an instance from scratch.

$ test ! -f "/opt/bitnami/common/bin/openssl" && echo "Approach A: Using system packages." || echo "Approach B: Self-contained installation."
Approach A: Using system packages.


$ java -jar alfresco-mmt.jar list /opt/bitnami/apache-tomcat/webapps/alfresco.war
Module 'alfresco-share-services' installed in '/opt/bitnami/apache-tomcat/webapps/alfresco.war'
   -    Title:        Alfresco Share Services AMP
   -    Version:      15.9
   -    Install Date: Tue Sep 27 16:25:05 UTC 2022
   -    Description:   Module to be applied to alfresco.war, containing APIs for Alfresco Share
Module 'alfresco-aos-module' installed in '/opt/bitnami/apache-tomcat/webapps/alfresco.war'
   -    Title:        Alfresco Office Services Module
   -    Version:      1.4.1
   -    Install Date: Tue Sep 27 16:25:03 UTC 2022
   -    Description:   Allows applications that can talk to a SharePoint server to talk to your Alfresco installation

But the situation remains the same.
I am getting the same error message as the first comment.
And I can't open office files with MS office applications.

**Comment by gongomgra** [comment]
Hi @HiroyukiSakachi,

Thanks for your message. Did you restart Alfresco after installing the plugin for changes to take effect as mentioned in our guide?

```
sudo /opt/bitnami/ctlscript.sh restart
```

Did you also check the extended instructions from [the official Alfresco docs site](https://docs.alfresco.com/microsoft-office/latest/install/)? 

I'm afraid I don't know if there is any other requirements for this to work. We recommend you to check the official docs and open a new question in the official Alfresco support forums if you continue facing issues with this feature.

**Comment by HiroyukiSakachi** [comment]
Hi,gongomgra.

Of course I did a restart.
sudo /opt/bitnami/ctlscript.sh restart

I have not yet determined whether this problem is caused by alfresco itself or by the Japanese environment.
(We usually use Japanese, so we install Japanese fonts)

I'll give it some more time and try it.
If you still can't solve it, ask the alfresco official.

Thank you for your support.

**Comment by HiroyukiSakachi** [comment]
Hi,gongomgra.

I noticed something strange about the issue that I can't preview today.

sudo /opt/bitnami/ctlscript.sh restart

When I run this the preview doesn't show up.
The error message is the same as the first message in this topic.
However, if I stop-start the EC2 instance, the preview displays fine.


sudo /opt/bitnami/ctlscript.sh stop
leave for 5 minutes
sudo /opt/bitnami/ctlscript.sh start

In this case, the preview may or may not be displayed. (I am re-uploading the file each time)

My guess is that this problem may be related to port release.
Other issues I will investigate bit by bit.

**Comment by gongomgra** [comment]
Hi @HiroyukiSakachi,

Thanks for your message. I understand it can be either a delay releasing internal resources as you suggest or even some internal processes taking longer than expected (like creating a cache for those previews). Can you check it with the Alfresco developers? They have a lot more knowledge than us about how the application works internally.

**Comment by HiroyukiSakachi** [comment]
Hi,@gongomgra,
I will ask the alfresco technicians.
If I have any useful information, I will report it here.

**Comment by gongomgra** [comment]
Hi @HiroyukiSakachi,

Thanks for your message. We hope you can find a solution for your issue!
