### ISSUE TITLE
[Wordpress on Bitnami in GCP running on Debian Linux] How to upgrade PHP 7.3.14 to 7.4 or later

### ISSUE THREAD

**Issue by sellnowinc** [bitnami/vms#352]
### Describe your issue as much as you can

Wordpress indicates I am currently running PHP 7.3.14 and it is recommending me to upgrade to 7.4
How do I do that?

**Comment by leadid-joey** [comment]
Hello,

I received the same warning and now I'm scrambling to try to figure it out.  What do do?

**Comment by sellnowinc** [comment]
> Hello,
> 
> I received the same warning and now I'm scrambling to try to figure it out. What do do?

For what I've researched PHP cannot be updated on a "pre-configured" Bitnami instance. 
You have to create a new virtual machine with Bitnami and migrate your current Wordpress into that one and then point DNS to the new instance and when you see everything is working out fine you can shut down the original Bitnami instance.

**Comment by leadid-joey** [comment]
Hello,

I appreciate the reply, I'm finding the same thing.  I hate to have to build a new system but what else can I do about it.  Thank you for the reply and good luck.

**Comment by dictates** [comment]
I have the same issue on AWS - Wordpress NGINX SSL image, plugins now starting to not update due to old PHP version. PHP Update Recommended - Your site is running an insecure version of PHP (7.3.18), and should be updated.

**Comment by dictates** [comment]
> > Hello,
> > I received the same warning and now I'm scrambling to try to figure it out. What do do?
> 
> For what I've researched PHP cannot be updated on a "pre-configured" Bitnami instance. You have to create a new virtual machine with Bitnami and migrate your current Wordpress into that one and then point DNS to the new instance and when you see everything is working out fine you can shut down the original Bitnami instance.

I am using the AWS Wordpress NGINX SSL image, I have SSH access so should be able to update PHP via the command line, I assume you would have the same? I just don't know how to via the command line, can't find clear steps.
