### ISSUE TITLE
[WordPress with NGINX and SSL] Importing Wordpress into New Instance Setting Up SSL

### ISSUE THREAD

**Issue by levelingup** [bitnami/vms#353]
### Describe your issue as much as you can

I'm trying to update my PHP by creating a new instance with AWS EC2, and then importing my existing WordPress data information into the new instance by using All-In-One Migration...

I've been having issues with importing data, but trying different methods. This issue now I'm having is creating a new SSL. However, I already have an existing SSL in a different IP Address. So when I run the command

```
sudo /opt/bitnami/letsencrypt/lego --tls --email="EMAIL-ADDRESS" --domains="DOMAIN" --domains="www.DOMAIN" --path="/opt/bitnami/letsencrypt" run
```

with my actual domain, I'm getting an error and its referencing my current IP Address

```
[DOMAIN.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: XX.XXX.XXX.XXX: Error getting validation data
[www.DOMAIN.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: XX.XXX.XXX.XXX: Error getting validation data
```

the XX.XXX.XXX.XXX is my current IP Address. How do I set up a new SSL with new IP address with same domain?

**Comment by jotamartos** [comment]
Hi @levelingup,

If your site is already migrated and is working properly, you can simply configure your domain to point to the new instance's IP and run the lego command again to generate a valid certificate your this new site. 

If you want to avoid SSL errors during the migration of the domain, you can simply copy the current SSL certs from `/opt/bitnami/letsencrypt/certificates` and replace the SSL certs in the new instance (/opt/bitnami/nginx/conf/bitnami/certs/ directory).

**Comment by levelingup** [comment]
Thank you this worked. I did what you suggested, configured my domain to point to the new instance.
