### ISSUE TITLE
[WordPress] Sorting the WP-Config Http to Https command. 

### ISSUE THREAD

**Issue by JKSafaris** [bitnami/vms#354]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b118447a-b581-56f7-440f-6f8da65442a3

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Php: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat Sep 24 10:24:44.847033 2022] [proxy_fcgi:error] [pid 58244:tid 
140634669082368] (70008)Partial results are valid but processing is incomplete: 
[client **ip_address**:56491] AH01075: Error dispatching request to : (reading 
input brigade)
 [Sat Sep 24 12:26:54.996683 2022] [proxy_fcgi:error] [pid 58244:tid 
Press [Enter] to continue:
140634660689664] [client **ip_address**:3505] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: 
https://www.cheetahsafaris.co.uk/wp-admin/post.php?post=795&action=elementor
 [Sat Sep 24 12:26:58.856661 2022] [proxy_fcgi:error] [pid 58244:tid 
140634769794816] [client **ip_address**:3506] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: 
https://www.cheetahsafaris.co.uk/wp-admin/post.php?post=795&action=elementor
```

### bndiagnostic was not useful. Could you please tell us why?

They were not helpful

### Describe your issue as much as you can

I am trying to sort the Http issue by accessing the wp-config via SSH, but I get a notice of denied permission. I tried the documentation on Bitnami but it has failed. 

Please advise how I can convert the HTTP to HTTPS command in wp-config. 

Mind you the SSL is active in the application.

**Comment by gongomgra** [comment]
Hi @JKSafaris,

Thanks for using Bitnami. I understand you are trying to update the `wp-config.php` file manually. If you can't edit it with the `bitnami` user, please use the `sudo` command to gain higher privileges.
