### ISSUE TITLE
[WordPress] can't reach this pageThe connection was reset.

### ISSUE THREAD

**Issue by Billa9090** [bitnami/vms#356]
### Describe your issue as much as you can

![image](https://user-images.githubusercontent.com/114410485/192281352-eb68dbde-76ca-46dc-bcde-f14a58bdbd65.png)

**Comment by Billa9090** [comment]
Please solve this

**Comment by gongomgra** [comment]
Hi @Billa9090,

Thanks for using Bitnami. It looks like you are using one of our native installers. If that's your case, please check all services are running in the application manager, or start those services not running yet.
