### ISSUE TITLE
[wordpress] Constant 404 Error using postname permalinks

### ISSUE THREAD

**Issue by ckunderd** [bitnami/vms#357]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

none created

### bndiagnostic output

bitnami-wordpress-info-20220926-143519-13408.zip
> @gongomgra removed this link.

### bndiagnostic was not useful. Could you please tell us why?

It didn't upload to the servers automatically

### Describe your issue as much as you can

I am getting a persistent 404 error with all Wordpress pages at holiday.lighthousemi.org when choosing pretty permalinks (postname in my case). the pages work fine with plain permalinks. I have deactivated all plugins and themes, and I still get the error. So I started trying to amend the htaccess files, changing to AllowOverride to All in all relevant files, etc. But still nothing. I am checking to see if there is something in this diagnostic that can point to the issue... Thank you in advance!

**Comment by ckunderd** [comment]
Also, if we could mark this private since I had to upload my diagnostic issue, that would be awesome.

**Comment by gongomgra** [comment]
Hi @ckunderd,

Thanks for using Bitnami. I downloaded your bnsupport bundle and removed the download link. However, I couldn't extract any information about your system.

```
-----------------------------------
Check Apache path:
-----------------------------------
Running: ps aux | grep 'apache\|mysql\|nginx\|/opt/bitnami\|php-fpm'
In: /opt/bitnami
Error:
Exitcode:
```

This usually means that the machine is running out of resources (usually disk or memory). Can you check the output of running the commands below?

```
uptime
free -m
df -h
```

In case your server is running out of resources, we recommend you to upgrade them. After that, if you continue having errors, please run the bnsupport bundle again and share the new code with us.

**Comment by ckunderd** [comment]
`bitnami@ip-172-31-27-122:~$ uptime
 17:51:17 up 1 day,  5:46,  0 users,  load average: 0.10, 0.03, 0.01

--

bitnami@ip-172-31-27-122:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1995        1086         112         164         796         571
Swap:             0           0           0

--

bitnami@ip-172-31-27-122:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            989M     0  989M   0% /dev
tmpfs           200M  7.9M  192M   4% /run
/dev/xvda1       30G  4.9G   24G  18% /
tmpfs           998M     0  998M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           998M     0  998M   0% /sys/fs/cgroup
/dev/xvda15     124M  278K  124M   1% /boot/efi`

**Comment by ckunderd** [comment]
===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Mysql: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent Pagespeed related error messages in the Apache error log:
```
[Tue Sep 27 17:57:51.909577 2022] [pagespeed:error] [pid 19708:tid 
139806570714880] [mod_pagespeed **ip_address**-0 @19708] PageSpeed Serf fetch 
failure rate extremely high; only 0 of 12 recent fetches fully successful; is 
fetching working?

```
Press [Enter] to continue:
We suggest disabling pagespeed and check if that improves the behavior. Please 
check the following guide to disable Pagespeed:
 
https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespe
ed/#disable-pagespeed

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1995 1392 82 164 519 265 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/
 

===== End of bndiagnostic tool output =====

**Comment by ckunderd** [comment]
Diagnostic ID: 0d9294d6-b6b2-9bb9-4c8f-f5ac323731ba

**Comment by ckunderd** [comment]
New Diagnostic ID: c88646e7-d3ce-c319-2f5e-4af8ead4049a - something about Pagespeed... I've disabled it but it still seems to be an issue...

**Comment by ckunderd** [comment]
I did one more using the bnsupport tool here: b32fbe5f-303d-99fe-8ad5-94322ce6c0fd

**Comment by gongomgra** [comment]
Hi @ckunderd,

I checked the information in the last bnsupport bundle you shared and all I found are errors with some WordPress plugins. Can you check them?

```
[Tue Sep 27 19:03:09.146931 2022] [proxy_fcgi:error] [pid 4122:tid 139791244879616] [client 24.127.254.217:58118] AH01071: Got error 'PHP message: PHP Notice:  Array to string conversion in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/gravityforms/common.php on line 6695PHP message: PHP Notice:  Array to string conversion in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/gravityforms/common.php on line 6695', referer: https://holiday.***.org/thanksgiving/
[Tue Sep 27 19:03:30.786003 2022] [proxy_fcgi:error] [pid 4473:tid 139790976313088] [client 24.127.254.217:58137] AH01071: Got error 'PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/reciprocity-adopt-a-family/includes/functions.php on line 3030', referer: https://holiday.***.org/?page_id=72
```

Apart from that, I see all services are running, and I was able to visit your website without issues. Did you manage to solve your issue?

```
-----------------------------------
Get the ctlscript status
-----------------------------------
Running: ./ctlscript.sh status
In: /opt/bitnami

Output:

php-fpm already running
apache already running
mysql already running
```

**Comment by ckunderd** [comment]
https://holiday.lighthousemi.org/phpinfo.php - this is my phpinfo. I can't verify that mod_rewrite is working. I think that may be part of the problem. 

I run sudo a2enmod rewrite, and I get command not found.  Is that proper behavior?

**Comment by ckunderd** [comment]
I did fix the count error, and the array to string conversion is a known issue that has never stopped anything from working in the past. I really believe it is something server side with htaccess. I'm trying to put it on a different server now.

**Comment by ckunderd** [comment]
Here are my server config files on the current server that's not working:

/home/bitnami/apps/wordpress/conf/httpd-app.conf - https://gist.github.com/ckunderd/c95e8b87e7893b78568610f00fc90d44

/home/bitnami/apps/wordpress/conf/htaccess.conf - https://gist.github.com/ckunderd/b3db48f2d1ccf8c8c9e311c02b3c2d1e

/opt/bitnami/apache2/conf/httpd.conf - https://gist.github.com/ckunderd/af232d28bd61831d6a2507a82dbb3bb6

**Comment by ckunderd** [comment]
> Hi @ckunderd,
> 
> I checked the information in the last bnsupport bundle you shared and all I found are errors with some WordPress plugins. Can you check them?
> 
> ```
> [Tue Sep 27 19:03:09.146931 2022] [proxy_fcgi:error] [pid 4122:tid 139791244879616] [client 24.127.254.217:58118] AH01071: Got error 'PHP message: PHP Notice:  Array to string conversion in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/gravityforms/common.php on line 6695PHP message: PHP Notice:  Array to string conversion in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/gravityforms/common.php on line 6695', referer: https://holiday.***.org/thanksgiving/
> [Tue Sep 27 19:03:30.786003 2022] [proxy_fcgi:error] [pid 4473:tid 139790976313088] [client 24.127.254.217:58137] AH01071: Got error 'PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/reciprocity-adopt-a-family/includes/functions.php on line 3030', referer: https://holiday.***.org/?page_id=72
> ```
> 
> Apart from that, I see all services are running, and I was able to visit your website without issues. Did you manage to solve your issue?
> 
> ```
> -----------------------------------
> Get the ctlscript status
> -----------------------------------
> Running: ./ctlscript.sh status
> In: /opt/bitnami
> 
> Output:
> 
> php-fpm already running
> apache already running
> mysql already running
> ```

In direct reply to this, did you click on any page besides the home page?

**Comment by ckunderd** [comment]
After much digging, I discovered the error in a configuration in a plugin!! Thank you so much for your assistance :)
