### ISSUE TITLE
[WAMP Packaged by Bitnami 8.1.7-0] How to change the PHP version used by WAMP?

### ISSUE THREAD

**Issue by sanfordandsonrc** [bitnami/vms#36]
### Describe your issue as much as you can

Hello,

I Installed WAMP Packaged by Bitnami 8.1.7-0, and it is working great. According to phpMyAdmin, PHP version 8.1.7 is installed.

I want to test my localhost Joomla website using PHP 7.4.29, but I cannot find any way to change the version of PHP that WAMP is using. Nor can I find any information via Google on how to do this. I was led to believe that one of the benefits of WAMP over XAMPP was that WAMP lets you change the version of PHP being used.

Any help would be appreciated!

**Comment by mdhont** [comment]
With Bitnami it's not possible to update individual components. You need to download the latest WAMP version - which contains the latest version of all components - and migrate your data there.

**Comment by sanfordandsonrc** [comment]
Link please?

**Comment by jotamartos** [comment]
Hi @sanfordandsonrc,

You can download the latest version of WAMP from our official site

https://bitnami.com/stack/wamp/installer

Thanks!

**Comment by sanfordandsonrc** [comment]
Juan,
 
Does the latest version allow me to change the PHP version on the fly?
 
Larry

**Comment by jotamartos** [comment]
Hi @sanfordandsonrc ,

No, if you want to update the PHP/Apache/MariaDB version in the future, you will need to download and install the latest installer and migrate the data again.

**Comment by Skipp3er** [comment]
If you want to run old php versions you will need to locate and download the now unsupported php 7 wampstack but it is no longer patched for security vulnerabilities so not recommended. Php 7.4 support expired on November 28th 2022.

**Comment by rahulsoni9098** [comment]
i want bitnami which have php 7.4 version please any one help me

**Comment by mdhont** [comment]
Unfortunately a WAMP version that uses PHP 7.4 is no longer available.

**Comment by Sx3** [comment]
> i want bitnami which have php 7.4 version please any one help me

https://mega.nz/file/pjRyWIZL#btGq2Et16de7RIp1_I4iFNGbyNFDCtBxQW7F1f6vgZo
