### ISSUE TITLE
[LAMP] not able to connect DB of different server from one server

### ISSUE THREAD

**Issue by csbiswal** [bitnami/vms#362]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9abbcb26-b06b-9d3c-5f8b-c8aee4badf76

### bndiagnostic output

HI, 

I'm using 1 LAMP server of 2 core 4 GB in AWS LightSail (Server 1) for running one high traffic WordPress website. 

Now I have taken another instance(Server 2) of similar configuration where I want to keep the DB of the existing website and my files will be at Server 1.

After importing the DB to the server 2, I have given the DB credentials and IP address of the Server 2 on wp-config.php file of server 1 but it did not connect to the DB of Server 2. 

I think i have to make some changes in configuration of server 1. 

Kindly help me in this regards

Thank you
Chandra Sekhar

### bndiagnostic was not useful. Could you please tell us why?

my issue is different 

### Describe your issue as much as you can

HI, 

I'm using 1 LAMP server of 2 core 4 GB in AWS LightSail (Server 1) for running one high traffic WordPress website. 

Now I have taken another instance(Server 2) of similar configuration where I want to keep the DB of the existing website and my files will be at Server 1.

After importing the DB to the server 2, I have given the DB credentials and IP address of the Server 2 on wp-config.php file of server 1 but it did not connect to the DB of Server 2. 

I think i have to make some changes in configuration of server 1. 

Kindly help me in this regards

Thank you
Chandra Sekhar

**Comment by jotamartos** [comment]
Hi @csbiswal,

That's a database-related question and we suggest you check the MariaDB's official documentation and the guides available online. In this case, you need to create a new user with permissions to access from outside ('new_user'@'%'), update the MariaDB's conf to allow remote connections (bind-address parameter) and restart the database for the changes to take effect.

**Comment by csbiswal** [comment]
> Hi @csbiswal,
> 
> That's a database-related question and we suggest you check the MariaDB's official documentation and the guides available online. In this case, you need to create a new user with permissions to access from outside ('new_user'@'%'), update the MariaDB's conf to allow remote connections (bind-address parameter) and restart the database for the changes to take effect.

Thanks Jota for the reply. Ok Can you please guide me about the configuration or remote user permission ? Any documentation will also help me. Please

**Comment by jotamartos** [comment]
I suggest you take a look at the MariaDB's official documentation to make these changes. However, we have some guides in our documentation that explain how to create a new user with permissions to access from anywhere, you will also need to modify the bind-address parameter in the configuration and open the ports in the firewall 

https://docs.bitnami.com/general/infrastructure/lamp/configuration/create-database-mariadb/
https://docs.bitnami.com/general/infrastructure/lamp/get-started/understand-default-config-mariadb/#mariadb-configuration-file
https://docs.bitnami.com/aws/faq/administration/use-firewall/#using-amazon-lightsail
