### ISSUE TITLE
[Moodle] Install edumy theme on GCP Moodle VM

### ISSUE THREAD

**Issue by SaeedSSH** [bitnami/vms#363]
### Describe your issue as much as you can

Hi, 

I've been testing VM deployments on GCP for quite some time, specifically, moodle. I've been able to do a lot, but there is always more complex stuff that is beyond me. 

One very specific one is called edumy for moodle, which adds a ton of features to the open source education platform. Unfortunately, it cannot be installed via the typical plugin feature baked in moodle. There are also barely any instructions to help with deployments on how to install it. From what I read, it requires a manual upload and such and a bit of directory adjustments.

I'm no expert, but the lack of information left me curious.

P.S: edumy is not a free source addition, but it is quite famous. So anyone with experience with edumy, I would like your guidance. 

Cheers,

**Comment by gongomgra** [comment]
Hi @SaeedSSH,

Thanks for using Bitnami. We have a basic guide on how to install plugins in Moodle

https://docs.bitnami.com/virtual-machine/apps/moodle/configuration/install-plugins/

As an alternative, you can find a more detailed information in the official Moodle docs linked below, but if you are having issues installing a paid plugin, we highly recommend you to check it with the plugin developers or their official docs.

https://docs.moodle.org/25/en/Installing_add-ons
