### ISSUE TITLE
[Redmine] Unable to deploy on our Web Server

### ISSUE THREAD

**Issue by sudish-vici** [bitnami/vms#364]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Unable to run

### bndiagnostic was not useful. Could you please tell us why?

No Info

### Describe your issue as much as you can

We have been unable to deploy Redmine on one of our WebServers. We keep getting Errors with the installgen.bat and the serviceinstall.bat files.  Could you please help isolate or resolve the issue? If you could point us to any KB that helps workaround this, please do let us know too.

![RedmineError1](https://user-images.githubusercontent.com/114642744/192950634-66f4957c-64a3-4a55-8e33-d075a02b7f8c.jpg)
![RedmineError](https://user-images.githubusercontent.com/114642744/192950645-d2f1067b-e0f6-4212-8c2b-9cbd7a1d6d26.jpg)

@kishore-vici

Thanks in advance.

**Comment by kishore-vici** [comment]
Continues to #364, attaching one more error image.
![Redmineerror2 (2)](https://user-images.githubusercontent.com/113436106/192969960-24e1e9bb-9e5a-4cab-a610-9791e1072698.png)

**Comment by jotamartos** [comment]
Hi @kishore-vici ,

Please ensure your machine has enough available RAM memory during the installation of the package to avoid performance issues. Apart from that, please configure your antivirus system to not to block any execution during the installation. 

Regarding the error in the last image, I found that the encoding of your system may be affecting the installation. Is this your case? 

https://bugs.ruby-lang.org/issues/13831

**Comment by kishore-vici** [comment]
Hi @jotamartos 

Thanks for the information, can you please let us know which extensions the setup will use, we have excluded installation in the antivirus.
We are getting this issue at the setup of installing RubyGem.
Regarding the last image, we do not know what it was saying, just provide information to you, please help us with this issue.
