### ISSUE TITLE
[LAMP] crbug/1173575, non-JS module files deprecated

### ISSUE THREAD

**Issue by gbarriosfdev** [bitnami/vms#365]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

59fe06cc-0480-fef9-463b-3beb782fef84

### bndiagnostic output

✓ Processes: No issues found
✓ Resources: No issues found
? Connectivity: Found possible issues
✓ Mariadb: No issues found
✓ Php: No issues found
? Apache: Found possible issues
Your instance is using swap memory: total used free shared buff/cache available
Mem: 584 318 127 9 138 163 Swap: 634 119 515This usually means that your
instance is running low on memory. You could try to increase your instance's
memory. Please check your cloud provider's documentation for more information.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

### bndiagnostic was not useful. Could you please tell us why?

Sorry, I hadn't do the diagnostic

### Describe your issue as much as you can

I installed a VM on Google CLoud and still a few days ago it worked fine. Suddenly, when I was to connect to the site I received the message "No se puede acceder a este sitio web", and reviewing the console, appear the messsage "crbug-1173575-non-js-module-files-deprecated-chromewebdata-index%ea%9e%89530595551)".
I have not made any change to the code of my site, it's developed with PHP, Bootstrap and Jquery, so I think it could be something related with the bitnami application.
I thank your help

**Comment by gongomgra** [comment]
Hi @gbarriosfdev,

Thanks for using Bitnami. We have a guide on how to install a custom PHP application on top of our LAMP stack. Can you check it in case it is of help?

https://docs.bitnami.com/google/infrastructure/lamp/administration/create-custom-application-php/

Apart from that, I found out in the bndiagnostic bundle some PHP errors related to your application. Can you check them?

```
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Sep 26 00:34:37.277722 2022] [proxy_fcgi:error] [pid 24217:tid 139698433386240] [client **ip_address**:17102] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: saldo in /opt/bitnami/apache/htdocs/model/costosdata.php on line 86PHP message: PHP Notice:  Undefined index: saldo in /opt/bitnami/apache/htdocs/model/costosdata.php on line 86PHP message: PHP Notice:  Undefined index: saldo in /opt/bitnami/apache/htdocs/model/costosdata.php on line 86PHP message: PHP Notice:  Undefined
[Mon Sep 26 00:34:47.644653 2022] [proxy_fcgi:error] [pid 24217:tid 139698483742464] [client **ip_address**:17104] AH01071: Got error 'PHP message: PHP Notice:  Undefined variable: pac in /opt/bitnami/apache/htdocs/view/intranet/dashboard.php on line 161PHP message: PHP Notice:  Trying to get property 'radicacion' of non-object in /opt/bitnami/apache/htdocs/view/intranet/dashboard.php on line 161PHP message: PHP Notice:  Undefined variable: pac in /opt/bitnami/apache/htdocs/view/intranet/dashboa
[Mon Sep 26 00:34:47.961802 2022] [proxy_fcgi:error] [pid 24217:tid 139698231961344] [client **ip_address**:17104] AH01071: Got error 'PHP message: PHP Notice:  Undefined variable: clibus in /opt/bitnami/apache/htdocs/view/intranet/procesos.php on line 98PHP message: PHP Warning:  Invalid argument supplied for foreach() in /opt/bitnami/apache/htdocs/view/intranet/procesos.php on line 98', referer: https://www.baasel.net/index.php?view=intranet/dashboard.php&detail=procesos.php
```

You can find the Apache error log file at `/opt/bitnami/apache2/logs/error_log`. The bnsupport tool also mentioned your server is running out of resources. We recommend you using a bigger instance to solve this.

**Comment by gbarriosfdev** [comment]
Good morning. Could you tell me how can I backup my databases before proceed with a new instalation?
By the way, I forgot to mention that the site doesn't work even with plain HTML
I renewed a Letsencrypt certificate about 4 months ago, I don't know if that could be a reason for the fail

**Comment by gongomgra** [comment]
Hi @gbarriosfdev,

You can find more information on how to backup/restore your database using the command-line in the guide linked below

https://docs.bitnami.com/aws/infrastructure/lamp/administration/backup-restore-mysql-mariadb/

Regarding the Let's Encrypt certificate, you will have to request a brand new certificate in case your current one has been expired. Unfortunately, I don't know if it is the SSL certificate or your application errors what's causing the website not to work.
