### ISSUE TITLE
[owncloud] Not able to start mariadb, apache and php-fpm

### ISSUE THREAD

**Issue by ppuri** [bitnami/vms#366]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

90834eb2-0ed7-f52d-588c-832119c441f5

### bndiagnostic was not useful. Could you please tell us why?

It did not show anything apart from telling that The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code: 90834eb2-0ed7-f52d-588c-832119c441f5

### Describe your issue as much as you can

After 2-3 days of using owncloud, it has stopped working and stopped responding. I checked and I see that its not able to start any of the services. 

Mariadb log is showing following error. It seems that somehow, the vm is out of space of something. I have plenty of space on the host machine. I can however see that machine.qcow2 on host machine has grown to 15 GB size, it was around 4GB when I installed bitnami owncloud on my Mac. Can you please help.

2022-09-30 12:34:47 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2022-09-30 12:34:47 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-09-30 12:34:47 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-09-30 12:34:47 0 [ERROR] InnoDB: **preallocating 12582912 bytes for file ./ibtmp1 failed with error 28**
2022-09-30 12:34:47 0 [ERROR] InnoDB: **Could not set the file size of './ibtmp1'. Probably out of disk space**
2022-09-30 12:34:47 0 [ERROR] InnoDB: Unable to create the shared innodb_temporary
2022-09-30 12:34:47 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
220930 12:34:47 [ERROR] mysqld got signal 11 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.

Server version: 10.6.8-MariaDB
key_buffer_size=134217728
read_buffer_size=131072
max_used_connections=0
max_threads=153
thread_count=0
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 467959 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
2022-09-30 12:34:47 0 [Note] InnoDB: FTS optimize thread exiting.
stack_bottom = 0x0 thread_stack 0x49000
??:0(my_print_stacktrace)[0x55d6c07e563e]
??:0(handle_fatal_signal)[0x55d6c0318035]
??:0(__restore_rt)[0x7f6457e6b140]
??:0(thd_get_ha_data)[0x55d6c00b27d7]
??:0(wsrep_notify_status(wsrep::server_state::state, wsrep::view const*))[0x55d6c05e9027]
??:0(wsrep_notify_status(wsrep::server_state::state, wsrep::view const*))[0x55d6c05ef5cc]
??:0(void std::vector<unsigned long, std::allocator<unsigned long> >::_M_realloc_insert<unsigned long>(__gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > >, unsigned long&&))[0x55d6c07638ed]
??:0(void std::this_thread::sleep_for<long, std::ratio<1l, 1l> >(std::chrono::duration<long, std::ratio<1l, 1l> > const&))[0x55d6c06bbde1]
??:0(Wsrep_server_service::log_dummy_write_set(wsrep::client_state&, wsrep::ws_meta const&))[0x55d6bffccb08]
??:0(Wsrep_server_service::log_dummy_write_set(wsrep::client_state&, wsrep::ws_meta const&))[0x55d6bffcfcfa]
??:0(wsrep_notify_status(wsrep::server_state::state, wsrep::view const*))[0x55d6c05ffef9]
??:0(ha_initialize_handlerton(st_plugin_int*))[0x55d6c031acc2]
??:0(sys_var_pluginvar::sys_var_pluginvar(sys_var_chain*, char const*, st_plugin_int*, st_mysql_sys_var*, char const*))[0x55d6c0116436]
??:0(plugin_init(int*, char**, int))[0x55d6c0117423]
??:0(unireg_abort)[0x55d6c00432a7]
??:0(mysqld_main(int, char**))[0x55d6c0048d6b]
??:0(__libc_start_main)[0x7f6457985d0a]
??:0(_start)[0x55d6c003d95a]
The manual page at https://mariadb.com/kb/en/how-to-produce-a-full-stack-trace-for-mysqld/ contains
information that should help you find out what is causing the crash.
Writing a core file...
Working directory at /bitnami/mariadb/data
Resource Limits:
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes

**Comment by mdhont** [comment]
It could be due to mariadb binary logging. The following guide shows how you can disable it:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/disable-binary-logging-mysql/

**Comment by ppuri** [comment]
I have tried to do that - added disable_log_bin to /opt/bitnami/mariadb/my.cnf

Tried restarting services but it failed with following error. Also after this restart, my.cnf got wiped with no content in it anymore.
--------------
root§debian:/opt/bitnami£ **sudo /opt/bitnami/ctlscript.sh start**
Starting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.
-------------

Below is the output for **systemctl status bitnami.service**

● bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-10-04 00:53:46 UTC; 2min 39s ago
    Process: 271 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
      Tasks: 11 (limit: 530)
     Memory: 73.3M
        CPU: 2.082s
     CGroup: /system.slice/bitnami.service
             ├─424 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
             ├─428 php-fpm: pool www
             ├─429 php-fpm: pool www
             ├─430 php-fpm: pool www
             ├─431 php-fpm: pool www
             ├─432 php-fpm: pool www
             ├─433 php-fpm: pool www
             ├─434 php-fpm: pool www
             ├─435 php-fpm: pool www
             ├─436 php-fpm: pool www
             └─437 php-fpm: pool www

Oct 04 00:53:46 debian systemd[1]: bitnami.service: Unit process 430 (php-fpm) remains ru>
Oct 04 00:53:46 debian systemd[1]: bitnami.service: Unit process 431 (php-fpm) remains ru>
Oct 04 00:53:46 debian systemd[1]: bitnami.service: Unit process 432 (php-fpm) remains ru>
Oct 04 00:53:46 debian systemd[1]: bitnami.service: Unit process 433 (php-fpm) remains ru>
Oct 04 00:53:46 debian systemd[1]: bitnami.service: Unit process 434 (php-fpm) remains ru>
Oct 04 00:53:46 debian systemd[1]: bitnami.service: Unit process 435 (php-fpm) remains ru>
Oct 04 00:53:46 debian systemd[1]: bitnami.service: Unit process 436 (php-fpm) remains ru>
Oct 04 00:53:46 debian systemd[1]: bitnami.service: Unit process 437 (php-fpm) remains ru>
Oct 04 00:53:46 debian systemd[1]: Failed to start LSB: bitnami init script.
Oct 04 00:53:46 debian systemd[1]: bitnami.service: Consumed 2.068s CPU time.

--------------------------------------------------

Can you please help

**Comment by ppuri** [comment]
I am wondering if there is a space issue on the bitnami vm. I just tried to do apt-get update and I see space error.

root@debian:/opt/bitnami# apt-get update
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Err:1 http://security.debian.org/debian-security bullseye-security InRelease
  Error writing to file - write (28: No space left on device) [IP: xx.xx.xx.xx 80]
Hit:2 https://deb.debian.org/debian bullseye InRelease  
Err:2 https://deb.debian.org/debian bullseye InRelease  
  Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_bullseye_InRelease into data and signature failed
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.debian.org/debian bullseye InRelease: Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_bullseye_InRelease into data and signature failed
W: Failed to fetch https://deb.debian.org/debian/dists/bullseye/InRelease  Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_bullseye_InRelease into data and signature failed
W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  **Error writing to file - write (28: No space left on device)** [IP: xxx.xxx.xxx.xx 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

------
**How do I increase space on the vm. I can see the machine.qcow2 size has grown to 15.45 GB in disk. My host is Mac**

**Comment by mdhont** [comment]
I recommend upgrading the instance.

**Comment by ppuri** [comment]
Well, I had to setup the instance again start from scratch.

**Comment by ppuri** [comment]
I had similar problem again as soon as the VM size reached to 15.3 GB. This time I used [these steps](https://docs.bitnami.com/installer/faq/osx-vm-faq/administration/resize-disk-osx-vm/) to resize the VM and it worked.
