### ISSUE TITLE
Can not install wordpress extensions for Unyson

### ISSUE THREAD

**Issue by FeedArmy** [bitnami/vms#367]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e607abee-e5d8-0a7d-afdf-3a87e6d071c0

### bndiagnostic output

2022/10/02 06:09:25 [error] 1562#1562: *549 FastCGI sent in stderr: "PHP 
message: PHP Warning: Cannot create directory "". It must be inside 
"/opt/bitnami/wordpress" or "/opt/bitnami/wordpress/wp-content" or 
"/opt/bitnami/wordpress/wp-content/plugins" or 
"/opt/bitnami/wordpress/wp-content/themes" in 
Press [Enter] to continue:
/bitnami/wordpress/wp-content/plugins/unyson/framework/helpers/class-fw-wp-filesy
stem.php on line 275" while reading upstream, client: **ip_address**, server: _, 
request: "POST /wp-admin/admin.php?p 2022/10/02 06:09:25 [error] 1562#1562: *549 
FastCGI sent in stderr: "PHP message: PHP Warning: Cannot create directory "". 
It must be inside "/opt/bitnami/wordpress" or 
"/opt/bitnami/wordpress/wp-content" or 
"/opt/bitnami/wordpress/wp-content/plugins" or 
"/opt/bitnami/wordpress/wp-content/themes" in 
/bitnami/wordpress/wp-content/plugins/unyson/framework/helpers/class-fw-wp-filesy
stem.php on line 275" while reading upstream, client: **ip_address**, server: _, 
request: "POST /wp-admin/admin.php?p 2022/10/02 06:22:16 [error] 1562#1562: *662 
FastCGI sent in stderr: "PHP message: PHP Warning: 
require_once(/bitnami/wordpress/wp-load.php): Failed to open stream: No such 
file or directory in 
/bitnami/wordpress/wp-content/themes/kerge/css/customization.css.php on line 
6PHP message: PHP Fatal error: Uncaught Error: Failed opening required 
'/bitnami/wordpress/wp-load.php' (include_path='.:/opt/bitnami/php/lib/php') in 
/bitnami/wordpress/wp-content/themes/kerge/css/customization.css.php:6

### bndiagnostic was not useful. Could you please tell us why?

I don't know what to do to resolve the issue

### Describe your issue as much as you can

I have an existing Bitnami Google Cloud website, and want to migrate so that I can have new a new server, PHP versions etc.

After I migrate using all in one wp migrate, I get lots of CSS errors, and I can not add Unyson extensions.

Your assistance is much appreciated.

**Comment by FeedArmy** [comment]
I resolved the issue by performing the following SSH command: sudo chown -R bitnami:daemon /opt/bitnami/wordpress/wp-content/plugins

**Comment by mdhont** [comment]
Could you please edit the title?

**Comment by FeedArmy** [comment]
Updated.
