### ISSUE TITLE
[LAMP] Could this be why apache not running

### ISSUE THREAD

**Issue by manuelseffe** [bitnami/vms#368]
### Describe your issue as much as you can

I did `ls` on /opt/bitnami/stack there i saw two folder `apache2` and `apache2.back` what do you advice i do, about the them.

![2022-10-02 (1)](https://user-images.githubusercontent.com/29127097/193470969-0fa5fab9-f9db-4b97-bb15-1224767c55f0.png)

**Comment by gongomgra** [comment]
Hi @manuelseffe,

Thanks for using Bitnami. I think both `apache2` and `apache2.back` are symbolic links to the `apache` folder. However, I don't have enough information about your issue. Can you run our bnsupport tool? It will check your server for some known issues and suggest you the solution to them.

https://docs.bitnami.com/aws/how-to/understand-bndiagnostic/
