### ISSUE TITLE
[WordPress] Can't reach the site after launching the solution from the AWS Marketplace

### ISSUE THREAD

**Issue by relyontarun** [bitnami/vms#369]
### Describe your issue as much as you can

Hi Team, 

After following the steps in this article - https://themeisle.com/blog/install-wordpress-on-aws/ I was able to get the get the hello wordpress on the web page needed. 

Unfortunately, the admin account doesn't seem to open for some reason and I am not able to connect to the server that is created on AWS. I have been stuck on this scenario for quite sometime. Hoping to get some help and support. 
![image](https://user-images.githubusercontent.com/114928137/193586773-ae1b1a1d-f591-422c-84a9-96bf5d4e6f29.png)

![image](https://user-images.githubusercontent.com/114928137/193587355-37577af7-f061-425a-8d0b-400a9576461c.png)

**Comment by jotamartos** [comment]
Hi @relyontarun,

We do not know what happened with your instance. Please note we do not have access to that information. You need to ensure it's up and running and check if the services are running by executing this command 

```
sudo /opt/bitnami/ctlscript.sh status
```

If the instance is not working for some reason, you can try restarting it or launching a new one.
