### ISSUE TITLE
[WordPress] Security certificate expired, when I ran renew tool it's asking for directory

### ISSUE THREAD

**Issue by carprelifem** [bitnami/vms#370]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d7ab90d2-2cb3-6b80-d0ce-99141b57cf3a

### bndiagnostic was not useful. Could you please tell us why?

I don't know how to fix the issues it identified with the SSL

### Describe your issue as much as you can

The website (www.krainbuild.com) is not loading because the SSL is expired. I tried to renew using the renew cert tool and the tool asks me for the Bitnami directory. I don't know how to answer that question. 

So, I tried the alternate approaches to renew an expired SSL (https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach) but the SSH terminal just locks up after the step where I request a new certificate. I waited 10 min and it didn't load. 

I tried to upload the older httpd.conf and bitnami.conf files and I don't have permission using the Bitnami user. I even tried changing to super user and still got a permission denied message. 

Please help, I need to get this page up ASAP! Thank you.

**Comment by carprelifem** [comment]
I have purchased two SSL tools, and neither of them will work. I think I need to upgrade my PHP version, but I don't know how to do that. I have searched and searched, I don't even know if Bitnami is where I would upgrade PHP or would I do that on AWS?

**Comment by gongomgra** [comment]
Hi @carprelifem,

Thanks for using Bitnami. It looks like the bnsupport tool found some errors in your installation related to Apache and WordPress. Can you check them?
    ✓ Connectivity: No issues found

```
[Apache]

Found recent Pagespeed related error messages in the Apache error log:
[Mon Oct 03 04:44:01.883981 2022] [pagespeed:error] [pid 30131:tid 139674064508672] [mod_pagespeed **ip_address**-0 @30131] PageSpeed Serf fetch failure rate extremely high; only 0 of 6 recent fetches fully successful; is fetching working?

We suggest disabling pagespeed and check if that improves the behavior. Please check the following guide to disable Pagespeed:

https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespeed/#disable-pagespeed

Found recent error or warning messages in the Apache error log.
[Mon Oct 03 01:27:34.578277 2022] [autoindex:error] [pid 30131:tid 139674886502144] [client **ip_address**:64715] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive, referer: binance.com
 [Mon Oct 03 03:36:49.590013 2022] [autoindex:error] [pid 30131:tid 139675054356224] [client **ip_address**:58977] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive, referer: binance.com
 [Mon Oct 03 16:45:16.962789 2022] [autoindex:error] [pid 3000:tid 140158246373120] [client **ip_address**:54162] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive, referer: binance.com

Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

[Resources]

Your instance has little available RAM memory.
 total used free shared buff/cache available Mem: 990 536 70 85 383 182 Swap: 634 13 621

you could try to increase your instance's memory. Please check your cloud provider's documentation for more information.
```

Regarding the SSL certificate, you will have to request a brand new SSL certificate, as an already expired certificate can't be renewed. About the PHP version, it is not possible to update the PHP version included in your server. You will have to launch a fresh new server with a newer PHP version and then migrate your application data there.
