### ISSUE TITLE
[Discourse] How to configure SMTP settings in Bitnami Discourse Azure?

### ISSUE THREAD

**Issue by tsdev-we** [bitnami/vms#371]
Writing a separate standalone ruby code to send email works no issue, but I could not send email through bitnami discourse SMTP settings mentioned it in the following link. https://docs.bitnami.com/installer/apps/discourse/configuration/configure-smtp/     I used the Azure prebuild bitnami image for discourse. 

I followed every details in the above link, also did 
sudo installdir/ctlscript.sh restart 
still no email delivered,  doubt these SMTP setting does not apply automatically, not sure how to make them work. 

In the production log I get the following delivery confirmation line (no error)

Processing by UsersController#email_login as */*
  Parameters: {"login"=>"tas@XXXXXX"}
Completed 200 OK in 184ms (Views: 0.5ms | ActiveRecord: 0.0ms | Allocations: 10901)
  Rendered layouts/email_template.html.erb (Duration: 1.7ms | Allocations: 280)
Delivered mail f497e1cb-72ec-43f0-8742-60d5d77ef00f@xxxxxx.domain.com (1513.8ms)

All services are working fine:

apache already running
postgresql already running
redis already running
sidekiq already running

No Email delivered, No log details in sidekiq.log file.  Please help me fix his.

**Comment by jotamartos** [comment]
The application says that it sent the email properly so there is something wrong in the app or in the settings. We do not provide this type of support so please take a look at the official documentation to know how to configure the latest version of Discourse or debug the issue.
