### ISSUE TITLE
[Elasticsearch] pods unable to start when scaling up the replicas

### ISSUE THREAD

**Issue by Bhargav6611** [bitnami/vms#374]
### Describe your issue as much as you can

Hi Team,

We are using the Catalog Offering: **Bitnami Elasticsearch Stack** having Offering version: **8.4.2209280752** deployed on IBM Cloud Kubernetes service, once deployed all the pods are in Running State while for the data pod, it is unable to start due to the below error seen while describing the pod.

The same error occurs while I try to scale up any of the other pods. 

`Failed to pull image "docker.io/bitnami/bitnami-shell:11-debian-11-r37": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/bitnami/bitnami-shell:11-debian-11-r37": failed to resolve reference "docker.io/bitnami/bitnami-shell:11-debian-11-r37": failed to do request: Head "https://registry-1.docker.io/v2/bitnami/bitnami-shell/manifests/11-debian-11-r37": dial tcp 34.205.13.154:443: connect: no route to host`

Another Q we have is -- I am unable to change the variable value of the Terraform Template for the variables _data.containerSecurityContext.runAsNonRoot_ : I get the error as below:

`Terraform apply | Error: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].securityContext.runAsNonRoot): invalid type for io.k8s.api.core.v1.SecurityContext.runAsNonRoot: got "string", expected "boolean"`

Kindly assist regarding the same.

Thanks.
Bhargava

**Comment by jotamartos** [comment]
Hi, 

this is a Chart-related question and this forum is just for VMs. Please create a new ticket in the [bitnami/charts](https://github.com/bitnami/charts) repository.

Thanks
