### ISSUE TITLE
[bncert-tool] Stuck in loop when launching

### ISSUE THREAD

**Issue by bwuehler** [bitnami/vms#375]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

 3bda0b61-0d6c-a01f-0647-a302f7cf8729

### bndiagnostic was not useful. Could you please tell us why?

I don't know how to read the bnsupport-tool output locally

### Describe your issue as much as you can

I've used bncert-tool many times to generate ssl certificates on our wordpress multi-site web server. Every time we add a site to the stack, I re-run the tool and add the additional domain to the certificate. However, since yesterday, the tool goes into an infinite loop when trying to launch. If first indicates that "custom redirections are not supported". This is normal and I press enter to continue. Then it asks for the "directory that contains the Bitnami installation". Which is /opt/bitnami and pre-filled. When I hit enter again, I return to the message about "custom redirections". Pressing enter loops between these two messages infinitely.

The loop looks like this (only pasted one loop, but it goes on indefinitely)"

bitnami@ip-172-26-13-76:~$ sudo /opt/bitnami/bncert-tool
Warning: Custom redirections are not supported in the Bitnami WordPress
Multisite Stack. This tool will not be able to enable/disable redirections.
Press [Enter] to continue:
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

Warning: Custom redirections are not supported in the Bitnami WordPress
Multisite Stack. This tool will not be able to enable/disable redirections.
Press [Enter] to continue:

**Comment by bwuehler** [comment]
You, sir, are the man! That worked for me as well. I didn’t know the previous versions were still easily available. Thank you so much for the help!!

**Comment by grex22** [comment]
Same issue for me -- seems fairly widespread.. :/

**Comment by mdhont** [comment]
Please note that when you see this message you need to press Enter to continue.

**Comment by luka725** [comment]
![image](https://user-images.githubusercontent.com/57828247/195673879-82ca8155-c1f9-4c6a-b913-57eb957c20d6.png)
