### ISSUE TITLE
[WordPress] My website crashed after activating the SSL certificate THROUGH SSH - Google Cloud 

### ISSUE THREAD

**Issue by minaatia0** [bitnami/vms#378]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

my problem is different 

### bndiagnostic output

my problem is different 

### bndiagnostic was not useful. Could you please tell us why?

my problem is different 

### Describe your issue as much as you can

The problem simply is after I activated the SSH for SSL certificate on my Wordpress by Bitnami, all the images on the website crashed. 
I am not sure why exactly this happened, but maybe because I selected "http to https" y, but on my internal dashboard the IP Address still suspicious and all the pictures uploaded to the media file has HTTP link. 

Here is the link for my my website: littleheaven.com 

Please advice how to solve this.

**Comment by gongomgra** [comment]
Hi @minaatia0,

Thanks for using Bitnami. Yes, WordPress internally cached that information (the image URL). You will have to update it from the admin panel from HTTP to HTTPS.

**Comment by minaatia0** [comment]
Hay gongo!

I do not know how to that because I am a newbie to this wordpress. 

Could you please let me know what exactly I should do in the admin panel? by admin panel you mean the internal dashboard of Wordpress right? 

which section controls this http to https? and how to check after that everything works correctly? is there a detector tool or somth? 

And Also I made my domain point to the IP address, and when it works find when you check the domain directly. 

But n my internal Wordpress dashboard, I still see the ip on the search bar instead of the domain name!

Do you have any solution for that?

**Comment by gongomgra** [comment]
Hi @minaatia0,

You have to update the `WP_HOME` and `WP_SITEURL` with the HTTPS url as mentioned in [our guide](https://docs.bitnami.com/google/apps/wordpress/administration/configure-domain/). For the images URL, please enter the media library in your WordPress admin panel and edit the URL of the affected images.

Apart from that, can you run our bnsupport tool and share with us the code it generates at the end of its execution? I'd like to take a look at your Apache configuration to double-check everything is fine.

https://docs.bitnami.com/google/how-to/understand-bndiagnostic/

**Comment by minaatia0** [comment]
Dear Gongo, 

Thanks for your patience. Please bear with because my business is in risk, and I can not sleep until this issue is figured out. 

**First of all,** 

Here is the results of Bitnami diagnostic tool: 
    ✓ Php: No issues found
    ✓ Connectivity: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ? Resources: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Wordpress: No issues found 

You could find all details here: a0a96afa-f184-f675-26b3-a7da6ab00519 

### And here is my reply to your comment before: 

1- I can not find my WP_HOME and WP_SITEURL because it is only the IP that is visible as attached in the screenshot below.
 
![Screen Shot 2022-10-11 at 5 21 07 PM](https://user-images.githubusercontent.com/115413328/195135267-2407d804-dd34-47e1-8acd-9c97eb6485f2.png)

**The strange thing is when you search for my domain littlheaven.com, it will take you directly to my website, and SSL certificate is already installed, so could you tell me first how to fix this? I can not find the solution for this because I do not know what to search for??**
 
I need my domain, instead of the ip address, in the search bar on the backend as it is in the front end for the users. 


2 -  When I followed the guide you sent me, I found something wrong in the system. 
I am on approach a, but when I type /opt/bitnami/wordpress/wp-config.php  or replace wp-config.php  with my domain name, it tells me there is no such file!!! kindly check the screen below. 

![Screen Shot 2022-10-11 at 5 19 48 PM](https://user-images.githubusercontent.com/115413328/195137197-faee4467-7838-493a-9643-61cf7e05f2a6.png)



3- In media library, I can not play with the URL because the search bar is blocked too edit. so I cannot add s next http or even empty the box as i attached below. 

![Screen Shot 2022-10-11 at 5 21 59 PM](https://user-images.githubusercontent.com/115413328/195137036-e9b7a70a-e140-4e02-bf5d-6d4392001467.png)

Now, you have a detialed answer about everything on my side. 

Could you please reply to me in details? Kindly copy & paste what exactly I should do in the reply box, and I will follow it.
And if there is a problem on Google Cloud Console VM, let me know in details what is it, and I will screenshot your answer and send it to their support team.  


Thanks in advance.

**Comment by minaatia0** [comment]
Hay Gango!

In case you have forgotten my issue, this is a gentle reminder.
