### ISSUE TITLE
Bitnami WP and JetPack - Can't figure out how to configure SSH/ SFTP

### ISSUE THREAD

**Issue by spikesantee** [bitnami/vms#381]
### Describe your issue as much as you can

Greetings, 

I have a Bitnami installation of WP on the Google Cloud Platform.

I cannot set up ssh for JetPack. I can't seem to figure out what to use for credentials. 

I can access my site with FileZilla so I know I can SFTP. 

I can access my site with Putty so I know I can access SSH.

Help!

Thanks in advance.

**Comment by spikesantee** [comment]
According to JetPack, they don't accept ssh keys created by PuttyGen. I created a key using the Google Command Line Interface. I added the public key to the VM instance. Still, it doesn't connect. 

I can't even get it to connect using just FTP with the system user account assigned at the time the VM was created. 

I get this error message. 

We couldn't connect to your site. Please verify that your credentials are correct and ensure that your host is not blocking the connection.

1. Could not open connection to ssh://spikesantee.com:22 with given credentials
2. Please ask your hosting provider to allow connections from the IP addresses found on this page: https://jetpack.com/support/how-to-add-jetpack-ips-allowlist/

Is my Google VM blocking IP addresses?

**Comment by spikesantee** [comment]
Has anyone ever set up the SFTP authentication for JetPack on a Bitnami Launchpad version of Wordpress on Google Cloud Platform. 

I cannot seem to get my authentication to work. 

The technician from JetPack says that JetPack does not use the same format of an SSH Key as PuttyGen creates. So I had to use the apache key-gen utility. 

Regardless of the credentials I try to use, I cannot connect to JetPack. 

I even tried just plain FTP using the Google generate user and system password. 

Surely, there are thousands of Bitnami WP installations on Google Cloud that connect with Jetpack. I could use some help from someone who has done this before. 

Please / Thanks.

**Comment by spikesantee** [comment]
I'm really stuck. I wish someone would help me.

**Comment by mdhont** [comment]
These guides can be useful:

https://docs.bitnami.com/aws/faq/administration/upload-files/
https://docs.bitnami.com/aws/apps/wordpress/configuration/use-jetpack/

**Comment by spikesantee** [comment]
Dear Michiel,

Thanks for trying to help me with my problem.

I have read both of those articles. I have downloaded the SSH from Bitnami just like your first article suggests. I can use it to access my server with both FileZilla and SSH. It works perfectly. It just doesn't work with JetPack.

I have read the second article too, it doesn't really offer much new help.

I'm not sure what my Wordpress Installation Path is. The JetPack credentials page has a suggestion of /public_html/sitename but I think that's for a site on a shared-host. I think my installation on my Google Cloud Platform is /opt/bitnami/wordpress. However, I don't think having the wrong entry in that field has anything to do with my credentials problem, do you?

Thanks again.


________________________________

**Comment by mdhont** [comment]
The installation path is `/opt/bitnami/wordpress`. I found the following guide for adding credentials to jetpack, perhaps it will be of help.

https://jetpack.com/support/backup/backups-via-the-jetpack-plugin/adding-credentials-to-jetpack/

**Comment by spikesantee** [comment]
Dear Michiel,

I'm all set up on BlueHost and my JetPack is configured and connected!!!

Thanks for all your help.

Spike

________________________________
