### ISSUE TITLE
[WordPress] Unable to set up a custom PHP application with Bitnami-powered Wordpress

### ISSUE THREAD

**Issue by pjuneja81095** [bitnami/vms#383]
I am currently in the process of trying to deploy a custom LAMP application to an AWS ec2 server which has the Bitnami Wordpress stack installed onto it. I have followed the steps given in [this](https://docs.bitnami.com/aws/apps/wordpress/administration/create-custom-application-php/) article to the T, but have been running into the following issues:

After creating & editing the files /opt/bitnami/apache2/conf/vhosts/myapp-vhost.conf & /opt/bitnami/apache2/conf/vhosts/myapp-https-vhost.conf as per the tutorial (Approach A), I restart the server

Upon restart, the following error occurs when trying to access http://server-ip/ which would typically redirect to the preinstalled Wordpress website: [Image 1](https://i.stack.imgur.com/AXa0U.png)

Also, my application directory exists under /opt/bitnami/apps/myapp but it cannot be accessed at http://server-ip/myapp despite me having specified the document root & directory correctly in the aforementioned files. The error message is: [Image 2](https://i.stack.imgur.com/EMZyg.png)

Any ideas on what may be going wrong or suggestions for a resolution? All help is greatly appreciated.

**Comment by jotamartos** [comment]
The tutorial is meant to deploy an application using a subdomain. Please configure a valid subdomain and set the ServerAlias/ServerName parameters to the correct value. Once you configure that, you will be able to access WordPress using the main domain and your new app using the subdomain.

Regarding the forbidden error, please set the correct permissions of your app's folder 

```
sudo chown -R bitnami:daemon /opt/bitnami/myapp
sudo chmod -R g+w /opt/bitnami/myapp
```

Note: You need to replae myapp with the real name of the folder where you deployed the application

**Comment by pjuneja81095** [comment]
Hi @jotamartos,

What are the steps for configuring a valid subdomain & setting those parameters to the correct values? I was under the impression that I was doing that by following the steps given in the article I mentioned in the original post. If you could point me to an already existing article if there is one, that would be sufficient as I don't want you to have to explain information that's already out there - I'm sure you have many issues you're trying to resolve simultaneously. 

For the correct permissions, I did execute those very commands to grant the necessary permissions. However, I was confused because the permissions error occurs when I try to access `http://server-ip/` which is where the Wordpress website resides from what I understood. 

For my app itself, the error message is along the lines of 'the requested URL not found on server'.

**Comment by jotamartos** [comment]
To configure the domain/subdomain to use in a custom virtual host, you need to set the correct value in the ServerName or ServerAlias parameters. You can learn more about that in the [official documentation](https://httpd.apache.org/docs/2.4/vhosts/name-based.html)

>However, I was confused because the permissions error occurs when I try to access http://server-ip/ which is where the Wordpress website resides from what I understood.

I do not know if you modified the permissions configuration of the original WordPress installation. If that's the case, please ensure daemon has read/write permissions in that folder

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974
