### ISSUE TITLE
[WordPress] Database connection error

### ISSUE THREAD

**Issue by pjuneja81095** [bitnami/vms#384]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9f7bc977-b6d8-09b7-f637-e0922c53b17f

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ? Processes: Found possible issues
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Processes]

One or more component's processes are not running:
```
mariadb not running php-fpm not running
```
You can try to restart the process with the following command:

 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME
Press [Enter] to continue:

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Oct 10 15:15:11.635286 2022] [proxy_fcgi:error] [pid 219440:tid
140712926443264] [client **ip_address**:27758] AH01071: Got error 'PHP message:
WordPress database error Can't create/write to file
'/opt/bitnami/mariadb/tmp/#sql-temptable-30876-495-0.MAI' (Errcode: 13
"Permission denied") for query SHOW FULL COLUMNS FROM `wp_options` made by
require('wp-blog-header.php'), require_once('wp-load.php'),
require_once('/bitnami/wordpress/wp-config.php'),
require_once('wp-settings.php'), do_action('wp [Mon Oct 10 15:29:09.073717 2022]
[proxy_fcgi:error] [pid 219441:tid 140712909657856] [client
**ip_address**:54884] AH01071: Got error 'PHP message: WordPress database error
Can't create/write to file
'/opt/bitnami/mariadb/tmp/#sql-temptable-30876-497-0.MAI' (Errcode: 13
"Permission denied") for query SHOW FULL COLUMNS FROM `wp_options` made by
require('wp-blog-header.php'), require_once('wp-load.php'),
require_once('/bitnami/wordpress/wp-config.php'),
require_once('wp-settings.php'), do_action(' [Mon Oct 10 15:29:09.078654 2022]
[proxy_fcgi:error] [pid 219441:tid 140712909657856] [client
**ip_address**:54884] AH01071: Got error 'PHP message: WordPress database error
Press [Enter] to continue:
Can't create/write to file
'/opt/bitnami/mariadb/tmp/#sql-temptable-30876-497-4.MAI' (Errcode: 13
"Permission denied") for query SHOW FULL COLUMNS FROM `wp_options` made by
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'),
include('wp-includes/template-canvas.php'), wp_body_open, do_action('wp_bo
```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I understand the error output but am struggling to fix the issue

### Describe your issue as much as you can

This issue stemmed from me trying to set up a custom PHP application on an AWS ec2 server but failing to do so (see [here](https://github.com/bitnami/vms/issues/383#issue-1403344225)). I believe that I may have messed up the filesystem permissions while trying to set permissions for the app folder that I had created in an attempt of setting up my custom application. 

I have tried to start/restart mariadb & php-fpm using the command `sudo /opt/bitnami/ctlscript.sh start mariadb/php-fpm`. However, I see the following error when I go to `http://localhost`:

![image](https://user-images.githubusercontent.com/38334076/194913053-9c107090-7e7a-4452-9d9d-b4cccf79d822.png)

When I run the command `sudo /opt/bitnami/ctlscript.sh restart`, it fails with the following error output:

![image](https://user-images.githubusercontent.com/38334076/194912800-0e754880-57da-4fda-9d19-3289e4fb155e.png)
![image](https://user-images.githubusercontent.com/38334076/194912900-8d72c23b-a43d-421a-a205-891249e22bb9.png)

**Comment by jotamartos** [comment]
Hi @pjuneja81095,

I do not know if you removed the user's information in the database or if you configured a new database and didn't configure the permissions correctly but I'd suggest you check that. Please ensure you can access the database using the `root` user and then try with the user/password configured in the wp-config.php file. I understand you did not modify those values, otherwise that would be the error. To solve that, you can create a new user/password and configure the app with those credentials 

https://docs.bitnami.com/general/apps/wordpress/configuration/create-database-mariadb/

**Comment by pjuneja81095** [comment]
Hi @jotamartos,

Thank you for the quick turnaround. I did not remove the user's information in the database. I created a new database for my application; however, I have not set up a new user for that database yet. At this point in time, I am simply trying to get the Wordpress website back in working order before I move on to the next steps of configuring a subdomain and trying to connect my custom application to the corresponding database that I created. 

When trying to troubleshoot permissions issues, I tried to follow the steps given in [this](https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/) article. I have attached an additional screenshot of the error output when I try to set permissions or launch Mariadb as the root user:

![image](https://user-images.githubusercontent.com/38334076/195120591-a099be4a-ff62-470f-a0b8-7abb9c7225c9.png)

What do you recommend I do from here, just so I can recover the Wordpress website first & then proceed to set up my own application & its relevant database? Perhaps I messed up the permissions while trying to troubleshoot issues I was having while setting up my custom application, but I've been struggling to find a fix everywhere that I've looked. Any and all help is much appreciated.

**Comment by jotamartos** [comment]
I can see a permission denied error message in the log that is probably causing the issue. I understand you accidentally modified that so I suggest you launch a new VM (either locally or in the cloud) and compare the permissions configuration.
