### ISSUE TITLE
[WordPress] Theme-related errors in the Apache's log

### ISSUE THREAD

**Issue by Abelcor** [bitnami/vms#385]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4d2444a7-a9b7-8d2e-080e-ee7301006643

### bndiagnostic output

    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Wordpress: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Did not fix my issue

### Describe your issue as much as you can

Hi There,

We have upgraded our azure VM and then suddenly the website started showing the 521 error message. We have checked everything on azure side and can't find the issue at all. It keeps ons showing the 521 error message. Everything looks fin on the VM and we are able to connect but the site is not displaying at all for the user. 

We have also noticed that the htaccess file looks like the following:
![image](https://user-images.githubusercontent.com/43951746/195075128-639dd6bb-e4b7-47c3-aa9d-326f76e0c87e.png)

Could this perhaps be the cause of the issue as everything worked as expected and suddenly just stopped working.

**Comment by jotamartos** [comment]
I can see errors related to the theme you have 

```
[Mon Oct 10 10:41:08.186368 2022] [proxy_fcgi:error] [pid 840:tid 140443400492800] [client **ip_address**:10896] AH01071: Got error 'PHP message: PHP Warning: Trying to access array offset on value of type bool in /bitnami/wordpress/wp-content/themes/cocoon/woocommerce/single-product/product-image.php on line 54PHP message: PHP Warning: Trying to access array offset on value of type bool in /bitnami/wordpress/wp-content/themes/cocoon/woocommerce/single-product/product-image.php on line 55PHP m [Mon Oct 10 10:47:04.712338 2022] [proxy_fcgi:error] [pid 1169:tid 140444289693440] [client **ip_address**:22796] AH01071: Got error 'PHP message: PHP Notice: Unknown: file created in the system's temporary directory in Unknown on line 0', referer: https://www.diginu.com/store-manager/products-manage/81603/
```

Please contact the cocoon theme's developers to get more info about that error and how to solve it. You can also contact the WordPress developers to know more about how to troubleshoot errors in the app.

**Comment by Abelcor** [comment]
Thank you for your response.

We have tried to change the theme but it seems that we can't connect to the
database. I believe this is due to the 521 error as it can't connect to
port 443 or 80.

We have also disabled the theme but this does not change the 521 error
message.

**Comment by Abelcor** [comment]
We were now able to resolve the issue by restarting apache. However, it seems that we are unable to connect to the database now. Where is the database located as this was automatically created in the wp-config.php file provided by bitnami?
![image](https://user-images.githubusercontent.com/43951746/195088646-0870e627-e9e8-4380-8308-78a4bd8bf73f.png)

**Comment by jotamartos** [comment]
I can see this error in the image you posted 

>Probably out of disk space

Please ensure you have enough disk space in your instance and restart the database once you confirm that.
