### ISSUE TITLE
[Magento] Elasticsearch Restart

### ISSUE THREAD

**Issue by Rohaty** [bitnami/vms#386]
### Describe your issue as much as you can

Hi,

I have Magento 2.4.5 on AWS (bitnami version).

Regularly, elasticsearch stops with the error No alive nodes found in your cluster.

Is it possible to set in the elasticsearch configuration that elasticserch restarts?

**Comment by gongomgra** [comment]
Hi @Rohaty,

Thanks for using Bitnami. Unfortunately, I didn't understand your question. Can you provide us with more detailed information? Thanks!

**Comment by Rohaty** [comment]
Hi,

the problem is that the apache server and all services stop when the error occurs:
No alive nodes found in your cluster.

At this stage, according to the discussions, 

https://stackoverflow.com/questions/22307454/how-to-configure-elasticsearch-to-restart-after-crash

it would be set Auto restart elasticsearch services:

[Service]
Restart=always

My question was how do I set this up in the Bitnami Magento 2.4.5 stack.

So far, I have solved the problem with No alive nodes found in your cluster by setting it as follows
https://discuss.elastic.co/t/disabling-geoip-downloader-is-not-working-elastic-7-16-2-and-java-11/302523/5

PUT /_cluster/settings
{
  "persistent": {
  "ingest.geoip.downloader.enabled" : "false"
  }
}

PUT /_cluster/settings
{
  "persistent": {
  "ingest.geoip.downloader.enabled" : "true"
  }
}

PUT /_cluster/settings
{
  "persistent": {
  "ingest.geoip.downloader.enabled" : "false"
  }
}

It is removed  .geoip_databases  from index.

The error does not appear yet.

But the question still remains, how to set restart elasticsearch always and help you remove the No alive nodes found in your cluster error.

Regards
Eduard

**Comment by gongomgra** [comment]
Hi @Rohaty,

Thanks for your message. Our images include the gonit service, which monitors the status of the different services includes in our installations and takes care of restarting the service if anything goes wrong. Can you check the gonit status on your server?

https://docs.bitnami.com/aws/apps/wordpress-multisite/administration/configure-use-gonit/

**Comment by Rohaty** [comment]
Hi,

I know about gonit. This week all services stopped again and I let gonit restart everything but nothing happened. I've done that by booting up the instance and now I'm waiting to see what happens.

**Comment by gongomgra** [comment]
Hi @Rohaty,

Can you share with us the status of gonit and the bitnami service by running the commands below?

```
$ sudo gonit status
$ sudo systemctl status bitnami.service
```

**Comment by Rohaty** [comment]
Hi,
here is:

sudo gonit status
https://screenrec.com/share/e7H1jgFAXs

sudo systemctl status bitnami.service
https://screenrec.com/share/aKnmkdleqP

**Comment by gongomgra** [comment]
Hi @Rohaty,

As you can see in the first screenshot, gonit is properly monitoring the rest of the services, and it should start them in case any of them are suddenly stopped.
