### ISSUE TITLE
[Wordpress] bncert-tool cannot identify install directory

### ISSUE THREAD

**Issue by kfbenz** [bitnami/vms#387]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2cf45cad-eb38-f969-70dc-fd952170fa7d

### bndiagnostic output

    ✓ Php: No issues found
    ✓ Resources: No issues found
    ✓ Apache: No issues found
    ? Connectivity: Found possible issues
    ✓ Mysql: No issues found

[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. 

NOTE: Port 22 is blocked to all except a small group of IP addresses.  Both 80 & 443 are open. 

### bndiagnostic was not useful. Could you please tell us why?

Does not appear to isolate my issue. 

### Describe your issue as much as you can

Background - This instance was recently cloned from our production instance by way of starting with a snapshot, and deploying an instance for the purposes of updating our certification environment. Deploy went well, and started new cert enviornment (changing hostname and necessary hosts file update.  Next step was to use bncert-tool to revoke old certs and deploy new ones. After a bncert-tool update, I attempted to perform the SSL changes, but bncert-tool cannot seem to find the base install path for bitnami. It's at /opt/bitnami.. 

Bitnami installation directory
Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

Warning: Currently only installations using the Apache web server are supported.
Please follow the alternative approach described in this guide:

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
 Make sure you are entering a proper path, or choose a different directory.

**Comment by breakerdes** [comment]
Having same issues, SSL expired and cannot use command:
`sudo /opt/bitnami/bncert-tool`

Keeps looping back to asking.

Even tried the manual method and revoked the certs, then re-installing bncert but still an issue.

Help?

**Comment by greg1nelson** [comment]
Same issue keeps looping around

**Comment by onsterion** [comment]
Same issue after update bncert-tool. Version that working fine bncert-1.0.0-linux-x64.run , after this version appear the error.

**Comment by danpizzy** [comment]
any fix for this yet

**Comment by jotamartos** [comment]
Hi everybody, 

I just downloaded the latest version of the tool and everything worked as expected

```
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/latest/bncert-linux-x64.run
sudo mkdir /opt/bitnami/bncert
sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
sudo ln -s /opt/bitnami/bncert/bncert-linux-x64.run /opt/bitnami/bncert-tool
```

The current version is 1.0.2 

```
bitnami@ip-172-31-19-190:~$ sudo /opt/bitnami/bncert-tool --version
Bitnami HTTPS Configuration Tool 1.0.2 --- Built on 2022-10-13 08:09:43 IB: 21.6.0-202106241241
bitnami@ip-172-31-19-190:~$
```

and the certificate was generated properly for my testing domain

```
----------------------------------------------------------------------------
Performing changes to your installation

The Bitnami HTTPS Configuration Tool will perform any necessary actions to your
Bitnami installation. This may take some time, please be patient.

----------------------------------------------------------------------------
Success

The Bitnami HTTPS Configuration Tool succeeded in modifying your installation.
```

Could you please let us know the Bitnami solution you are using and its version?

**Comment by jotamartos** [comment]
Alternatively, you can always follow our alternative approach to generate the SSL certificates 

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by kfbenz** [comment]
@jotamartos  Updated to bncert-tool 1.0.2 but did not resolve the issue. 

Bitnami Wordpress 5.5-1 (Azure Marketplace image)

Question: It appears that the original certificates may have been installed via the backup approach. If done that way, does that invalidate the ability to use bncert-tool in the future. The reason I ask, is I see Lego installed. (I was not around when this VM was created). 

# ./bncert-tool --version
Bitnami HTTPS Configuration Tool 1.0.2 --- Built on 2022-10-13 08:09:43 IB: 21.6.0-202106241241
# ./bncert-tool
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.
----------------------------------------------------------------------------
Bitnami installation directory
Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

Warning: Currently only installations using the Apache web server are supported.
Please follow the alternative approach described in this guide:

**Comment by jotamartos** [comment]
I posted in this other thread more information about how to download a previous version and debug the issue. Please let us know what Bitnami solution you are using and its version. It'll be great if you can also confirm what bncert version works for you and which one doesn't.

https://github.com/bitnami/vms/issues/403#issuecomment-1283544417

**Comment by kfbenz** [comment]
As previously listed..

Bitnami Wordpress 5.5-1 (Azure Marketplace image)

**Comment by jotamartos** [comment]
Sorry, didn't see that. Did you try a previous version of the tool as I mentioned in the other thread? We will try to reproduce the issue in the meantime to obtain more info.

**Comment by greg1nelson** [comment]
OK had some time to look at this the version in the screen shot below is not working and loops around I am running wordpress VM. I will attempt to update the version manually and if that doesn't work re-install the old version.
![Screenshot 2022-10-22 at 11 57 13](https://user-images.githubusercontent.com/6061126/197335439-db90d99d-0285-4766-88c5-1e0e270d1510.png)

**Comment by greg1nelson** [comment]
I carried out the download of the 1.0.o version and followed the commands but its still using the old version 1.1.0.
I guess its a symlink  how to I unlink the symlink? Thanks greg
![Screenshot 2022-10-16 at 16 26 43](https://user-images.githubusercontent.com/6061126/197337898-ea7bc969-0cf5-4a27-8637-a87e51d193fb.png)

**Comment by greg1nelson** [comment]
Been though it all tried version 1.0.0 then updating to version 1.3.0 still looping and won't run the updated version.
Any help would be appreciated.
Thanks Greg
![Screenshot 2022-10-22 at 13 11 07](https://user-images.githubusercontent.com/6061126/197338414-a1797f53-3aa0-4f25-b6c2-828805392e4e.png)

**Comment by jotamartos** [comment]
As I mentioned in the other thread, version 1.0.3 fixes the issues 

https://github.com/bitnami/vms/issues/403#issuecomment-1287116105

**Comment by greg1nelson** [comment]
But when I download and run 1.0.3 the install and find the 1.0.3 and uses the 1.0.1 that's why it is still looping is there a way of breaking the symlink.

Thanks greg

**Comment by jotamartos** [comment]
Run these commands 

```
cd /tmp
rm -rf bncert-linux-x64.run
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/latest/bncert-linux-x64.run
sudo mkdir /opt/bitnami/bncert
sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
sudo ln -sf /opt/bitnami/bncert/bncert-linux-x64.run /opt/bitnami/bncert-tool
sudo /opt/bitnami/bncert-tool
```

**Comment by greg1nelson** [comment]
All was fine with the commands until I tried to link the bncert to the bncert toll came up with another error.
![Screenshot 2022-10-25 at 11 52 35](https://user-images.githubusercontent.com/6061126/197755368-75a2963a-db1f-49cc-8941-b07f820050de.png)

**Comment by jotamartos** [comment]
It seems that for some reason the file is not properly downloaded. Let's try with another method

```
cd /tmp
rm -rf bncert-linux-x64.run
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/1.0.3/bncert-1.0.3-linux-x64.run
file bncert-linux-x64.run
chmod +x bncert-linux-x64.run
sudo ./bncert-linux-x64.run --version
```

Does the version command work? If that's the case please move the binary to the bncert folder 

```
sudo rm -rf /opt/bitnami/bncert/
sudo mkdir /opt/bitnami/bncert
sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
sudo ln -sf /opt/bitnami/bncert/bncert-linux-x64.run /opt/bitnami/bncert-tool
sudo /opt/bitnami/bncert-tool
```

**Comment by greg1nelson** [comment]
No there version command won't work.Is the bncert file being deleted completely doesn't t need to be purged as it keeps coming up with the same issue I have tried a few times.
![Screenshot 2022-10-26 at 11 10 02](https://user-images.githubusercontent.com/6061126/198001053-cf8cb542-bc93-4f81-934a-906da3bdf110.png)

**Comment by jotamartos** [comment]
It seems you are not downloading the file properly. I do not know what's happening but please ensure the download process works. 

```
cd /tmp
rm -rf bncert-linux-x64.run
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/1.0.3/bncert-1.0.3-linux-x64.run
chmod +x bncert-linux-x64.run
file ./bncert-linux-x64.run
sudo ./bncert-linux-x64.run
```

**Comment by kfbenz** [comment]
I'm happy to test older versions in order to identify a working version and guessed at the URL to discover 1.0.. are there previous versions? Is there pre 1.0 versions? Is there a list?


Kevin Benz

Webmaster

Archdiocese of Seattle

Desk: (206) 382-4524 | Mobile: (425) 785-7100

Archseattle.org | @archdioceseofseattle

"It is not how much we do, but how much love we put in the doing", Mother Theresa

________________________________

**Comment by greg1nelson** [comment]
It still give the same error I'm lost and the cert has run out now.
![Screenshot 2022-10-27 at 15 48 07](https://user-images.githubusercontent.com/6061126/198322296-f022379c-da87-4171-8fdf-4e081cbbd12f.png)

**Comment by jotamartos** [comment]
Hi @greg1nelson,

This seems to be a cache problem. I just clear the cache again and try in my computer and everything worked as expected. 

```
bitnami /tmp  $ file ./bncert-linux-x64.run
./bncert-linux-x64.run: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.4.0, stripped
```

The file command should return a similar output in your case, not the "UTF-8 Unicode text" output you got before.

Could you please try again? 

```
cd /tmp
sudo rm -rf bncert-linux-x64.run
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/1.0.3/bncert-1.0.3-linux-x64.run
sudo rm -rf /opt/bitnami/bncert/
sudo mkdir /opt/bitnami/bncert
sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
sudo ln -sf /opt/bitnami/bncert/bncert-linux-x64.run /opt/bitnami/bncert-tool
sudo /opt/bitnami/bncert-tool
```

**Comment by itkujo** [comment]
I am on 1.0.3 using the AMI below
"bitnami-wordpresspro-6.0.3-6-r06-linux-debian-11-x86_64-hvm-ebs-nami-78b1d030-4c7d-4ade-b8e6-f8dc86941303"
and I cant get past this error.

**Comment by jotamartos** [comment]
Hi @itkujo,

In your case, you are using a NGINX-based solution and bncert doesn't support that webserver. There is a banner in the documentation about that limitation. You will need to follow the alternative approach

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by dmeresa** [comment]
@jotamartos after I run with your recommendation 
cd /tmp
rm -rf bncert-linux-x64.run
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/latest/bncert-linux-x64.run
sudo mkdir /opt/bitnami/bncert
sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
sudo ln -sf /opt/bitnami/bncert/bncert-linux-x64.run /opt/bitnami/bncert-tool
sudo /opt/bitnami/bncert-tool

I got error with /opt/bitnami/apache/sbin/nginx: not found? any idea?

<img width="991" alt="Screen Shot 2023-02-19 at 4 40 39 PM" src="https://user-images.githubusercontent.com/125833323/219976827-1c95bf07-a06b-4d9a-9cb8-77db1b113c7e.png">

**Comment by jotamartos** [comment]
Hi @dmeresa,

As this is a separate issue, let's continue the conversation here

https://github.com/bitnami/vms/issues/698
