### ISSUE TITLE
[<application>] Connecting to bitnami on AWS from PC does not work

### ISSUE THREAD

**Issue by Soldo** [bitnami/vms#388]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

not known

### bndiagnostic output

see link in the description below

### bndiagnostic was not useful. Could you please tell us why?

not known

### Describe your issue as much as you can

Hello,

I have issues when it comes to connecting to EC2 instance.
Neither EC2 Instance Connect nor SSH Client Connect (incl. PowerShell and Putty) works.

There has to be an issue on AWS side because I followed your instructions on "Connect to Instance" page.

The issue is described in this post:
https://serverfault.com/questions/1112839/permission-denied-publickey-bitnami-at-aws-wordpress-site-connecting-wit

I kindly ask to solve the issue and/or send me step-by-step instructions on how to connect to the created EC2 instance.

Thank you!

**Comment by mdhont** [comment]
Did you associate a key pair with your AWS server? If not please [contact AWS support](https://aws.amazon.com/contact-us/) and follow their instructions to gain SSH access to your server.
