### ISSUE TITLE
[bitnami Wordpress/mariadb] Unable to start mariadb Bitnami Wordpress

### ISSUE THREAD

**Issue by Abelcor** [bitnami/vms#389]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e3b51ccc-448e-b6fe-f999-801fc1ee0684

### bndiagnostic output

    ✓ Connectivity: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Wordpress: No issues found
    ? Processes: Found possible issues
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Oct 12 01:34:35.448337 2022] [proxy_fcgi:error] [pid 4468:tid
140060619958016] [client **ip_address**:33804] AH01071: Got error 'PHP message:
PHP Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in
/opt/bitnami/wordpress/wp-includes/wp-db.php on line 1753'
 [Wed Oct 12 01:34:42.925791 2022] [proxy_fcgi:error] [pid 4668:tid
Press [Enter] to continue:
140060821284608] [client **ip_address**:51624] AH01071: Got error 'PHP message:
PHP Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in
/opt/bitnami/wordpress/wp-includes/wp-db.php on line 1753'
 [Wed Oct 12 01:37:20.698110 2022] [proxy_fcgi:error] [pid 4468:tid
140060477347584] [client **ip_address**:30042] AH01071: Got error 'PHP message:
PHP Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in
/opt/bitnami/wordpress/wp-includes/wp-db.php on line 1753'

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Processes]

One or more component's processes are not running:
```
mariadb not running

### bndiagnostic was not useful. Could you please tell us why?

Restart Mariadb did not work

### Describe your issue as much as you can
```
Hi There,

I run Bitnami WordPress on my Azure Virtual Machine and I am unable to start mariadb at all. I have noticed that I do get the following error message:

![image](https://user-images.githubusercontent.com/43951746/195229917-07fa526c-4b17-4210-be85-048092c549e5.png)

I also want to mention that I have already increased the disc space on my azure virtual machine a few times but unfortunately this did not work.

Is there perhaps something that I am missing?

![image](https://user-images.githubusercontent.com/43951746/195231716-4b950bcb-46f5-43bd-b651-4e498be4b5bb.png)

**Comment by Abelcor** [comment]
![image](https://user-images.githubusercontent.com/43951746/195231600-71e8eb5f-52be-4a7b-85d6-b749e72a0efe.png)

**Comment by mdhont** [comment]
Does this happen right after launching a new instance?
