### ISSUE TITLE
[<wordpress>] How to fix...Error dispatching request to

### ISSUE THREAD

**Issue by mubiesam** [bitnami/vms#39]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a9f57a4d-f2ed-3372-11a0-e23e8b5f409f

### bndiagnostic output

? Apache: Found possible issues
[Sun Jun 19 22:26:52.230614 2022] [proxy_fcgi:error] [pid 10848:tid 
140467861493504] (-102)Unknown error -102: [client **ip_address**:42724] 
AH01075: Error dispatching request to : (reading input brigade)

[Mon Jun 20 09:40:59.731655 2022] [core:error] [pid 6675:tid 140467962205952] 
[client **ip_address**:60468] AH00126: Invalid URI in request POST 
/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1

[Tue Jun 21 07:12:57.592052 2022] [proxy_fcgi:error] [pid 1494:tid 
140450086168320] (104)Connection reset by peer: [client **ip_address**:47394] 
AH01075: Error dispatching request to : (reading input brigade)

### bndiagnostic was not useful. Could you please tell us why?

guide to troubleshoot server issues only provide error logs, but how to fix?

### Describe your issue as much as you can

How to fix...Error dispatching request to

bndiagnostic output also mentioned...A high number of incoming requests originate from one or more unique IP addresses.
But the guide provided is for AWS, our VM is on GCP, where can I find guide for GCP?
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-bots-apache/

Thanks

**Comment by jotamartos** [comment]
Hi @mubiesam ,

I suggest you check this other issue that contains more information about how to troubleshoot this error 

https://github.com/bitnami/vms/issues/27

In your case, the PHP-FPM's logs are being rotated, please take a look at any of the previous log files to get more information about the PHP-FPM limits

```
php/var/log:
total 520
drwxr-xr-x 2 root root 12288 Jun 19 00:00 .
drwxr-xr-x 4 root root  4096 Jan 10  2020 ..
-rw------- 1 root root     0 Jun 19 00:00 php-fpm.log
-rw------- 1 root root    20 Jan 23  2020 php-fpm.log-20200126.gz
-rw------- 1 root root    20 Jan 26  2020 php-fpm.log-20200203.gz
-rw------- 1 root root   181 Feb  7  2020 php-fpm.log-20200209.gz
```
