### ISSUE TITLE
[WordPress] WordPress Multisite can't change domain name using configure_app_domain

### ISSUE THREAD

**Issue by gotbike2** [bitnami/vms#391]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

na

### bndiagnostic was not useful. Could you please tell us why?

The diagnostic freezed

### Describe your issue as much as you can

I was trying to change the domain name of a staging site I created from a Lightsail snapshot. I run the following commands: 

_sudo /opt/bitnami/configure_app_domain --domain example.com_

and got the following error:

_Configuring domain to example.com
Problem running post-install step. Installation may not complete correctly
 Error running /opt/bitnami/mysql/bin/mysql --user=admin --host=localhost --socket="/opt/bitnami/mysql/tmp/mysql.sock" --database=wordpress -p**** <<"EOF"
UPDATE wp_options SET option_value='http://example.com/wordpress' WHERE option_name='siteurl' OR option_name='home';
EOF: mysql.bin: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: YES)
Disabling automatic domain update for IP address changes_

I also run command _sudo /opt/bitnami/apps/wordpress/bnconfig --domain example.com_, and got the same error.

WordPress is pointing to a different database than the default local database.

Can you please advise how to solve this and change the domain name?

Thanks!

**Comment by gotbike2** [comment]
Hi,

Thanks for getting back to me. I did follow the instructions on the link provided. 

I did troubleshooting by editing the database via phpmyadmin for the following:
wp_options table: siteurl and home options
wp_blogs table: domain option

I made sure DOMAIN_CURRENT_SITE is correct in wp-config.php.

When I run command sudo /opt/bitnami/configure_app_domain --domain our-planets.com, it gave me error of the following:
_Problem running post-install step. Installation may not complete correctly
 Error running /opt/bitnami/mysql/bin/mysql --user=admin --host=localhost --socket="/opt/bitnami/mysql/tmp/mysql.sock" --database=wordpress -p**** <<"EOF"
UPDATE wp_options SET option_value='http://example.com/wordpress' WHERE option_name='siteurl' OR option_name='home';
EOF: mysql.bin: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: YES)
Disabling automatic domain update for IP address changes_

When I visit the site using the new domain, it gave me the error of _example.com redirected you too many times._

When I visit the site using the IP address directly, it added .xip.io to the end of the url, and gave me an error of _This site can’t be reached_

Can you please advise what else I can change to make it work?

Thanks very much!

**Comment by mdhont** [comment]
To access the database you need to use `--user=root`.

**Comment by gotbike2** [comment]
Hi,

Thanks for the pointer. Can you please show me what code to use in this case? I understand to access the database I need to use `--user=root`. Should I insert it into `sudo /opt/bitnami/configure_app_domain --domain example.com`?

Thanks,

**Comment by mdhont** [comment]
```
Configuring domain to example.com
Problem running post-install step. Installation may not complete correctly
Error running /opt/bitnami/mysql/bin/mysql --user=admin --host=localhost --socket="/opt/bitnami/mysql/tmp/mysql.sock" --database=wordpress -p**** <<"EOF"
UPDATE wp_options SET option_value='http://example.com/wordpress' WHERE option_name='siteurl' OR option_name='home';
EOF: mysql.bin: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: YES)
Disabling automatic domain update for IP address changes
```

Is mysql running? And how did you configure it? Could you try to access the database manually? 

https://docs.bitnami.com/aws/infrastructure/mysql/get-started/connect-mysql/

**Comment by gotbike2** [comment]
I made it to work after disabling Cloudflare caching. Just for future reference, I set the database outside of localhost, and I have to manually change the domain in the database manually. Thanks for your help.
