### ISSUE TITLE
[drupal] Upgrade Drupal 7 on CiviCRM image

### ISSUE THREAD

**Issue by kenahoo** [bitnami/vms#392]
### Describe your issue as much as you can

I've got a CiviCRM 5.42.1-4 image that I need to update to newer versions of Drupal (and eventually CiviCRM).  I attempted to follow the directions at https://docs.bitnami.com/installer/apps/drupal/administration/upgrade/#drupal-7 , but that fails as follows:

```
bitnami:~/stack/drupal$ drush up
Update information last refreshed: Wed, 10/12/2022 - 22:20
 Name    Installed Version  Proposed version  Message                   
 Drupal  7.82               7.92              SECURITY UPDATE available 


Code updates will be made to drupal core.
WARNING:  Updating core will discard any modifications made to Drupal core files, most noteworthy among these are .htaccess and robots.txt.  If you have made any modifications to these files, please back them up before updating so that you can re-create your modifications in the updated version of the file.
Note: Updating core can potentially break your site. It is NOT recommended to update production sites without prior testing.

Do you really want to continue? (y/n): y
Unable to load class \Drush\VersionControl\Backup
```

There is a `composer.json` file in this directory, with the following contents:

```
bitnami:~/stack/drupal$ cat composer.json 
{
    "require": {
        "drush/drush": "8.4.8"
    }
}
```

Is it advisable to add Drupal (maybe `drupal/core-recommended`) to this and try to upgrade through Composer?

**Comment by mdhont** [comment]
Can you try to update using built in tools?

https://docs.bitnami.com/installer/apps/drupal/administration/upgrade/#upgrade-using-built-in-tools

**Comment by kenahoo** [comment]
Following those instructions, I hit a snag at the `cp` stage:

```
bitnami:/opt/bitnami/drupal$ sudo cp -R ~/drupal-7.92/* .
cp: cannot overwrite non-directory './modules' with directory '/home/bitnami/drupal-7.92/modules'
cp: cannot overwrite non-directory './profiles' with directory '/home/bitnami/drupal-7.92/profiles'
cp: cannot overwrite non-directory './sites' with directory '/home/bitnami/drupal-7.92/sites'
cp: cannot overwrite non-directory './themes' with directory '/home/bitnami/drupal-7.92/themes'
```

This is because apparently in my installation, those four directories are symlinks into `/bitnami/drupal`:

```
bitnami:/opt/bitnami/drupal$ ls -l modules profiles sites themes
lrwxrwxrwx 1 root root 23 Oct 16  2021 modules -> /bitnami/drupal/modules
lrwxrwxrwx 1 root root 24 Oct 16  2021 profiles -> /bitnami/drupal/profiles
lrwxrwxrwx 1 root root 21 Oct 16  2021 sites -> /bitnami/drupal/sites
lrwxrwxrwx 1 root root 22 Oct 16  2021 themes -> /bitnami/drupal/themes
```

To be honest, I'm a little nervous about this method of just doing `cp`, it doesn't seem quite right for getting the files where they need to go?  And it seems like it could clobber things in `sites/`, e.g. my CiviCRM stuff?

**Comment by mdhont** [comment]
The information in the guide seems outdated. We will have a look at it. Another workaround would be to upgrade the whole stack by launching an installer (which has the latest application and component's versions) and then migrate your data there:

https://docs.bitnami.com/aws/how-to/migrate-drupal/
