### ISSUE TITLE
[MERN] Need a VM for the MERN stack

### ISSUE THREAD

**Issue by rupam-kundu** [bitnami/vms#393]
### Describe your suggestion as much as you can

While there is a VM for the MEAN stack, there is currently no VM for the MERN stack. Please launch a VM for the MERN stack with multi-cloud(AWS, Microsoft Azure and GCP) deployment capabilities particularly on Amazon Lightsail as it would benefit a large MERN stack developer community.

**Comment by gongomgra** [comment]
Hi @rupam-kundu,

Thanks for using Bitnami. I see you have [another issue opened with a similar question](https://github.com/bitnami/vms/issues/394). As you can manually deploy React and other dependencies required for your custom application to work on top our MEAN stack, please refer to that thread. Our team will be glad to continue helping you there.
