### ISSUE TITLE
[MEAN] How to deploy a MERN stack application to a MEAN stack VM?

### ISSUE THREAD

**Issue by rupam-kundu** [bitnami/vms#394]
### Describe your issue as much as you can

As there is no MERN stack VM available yet, I am trying to deploy a MERN stack application to a MEAN stack VM on Amazon Lightsail. Please provide step-by-step instructions on how to deploy a MERN stack application to a MEAN stack VM on Amazon Lightsail.

**Comment by jotamartos** [comment]
Please take a look at our documentation to know how to deploy a custom project on top of the MEAN stack

https://docs.bitnami.com/aws/infrastructure/mean/get-started/get-started/
