### ISSUE TITLE
[bitnami]<bncert-tool for Approach B not working >

### ISSUE THREAD

**Issue by dankings001** [bitnami/vms#395]
### Describe your issue as much as you can

I'm using the command:  sudo /opt/bitnami/bncert-tool

Instead of getting the bncert-tool I get this: 

(I am using Approach B)

Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default 
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

**what do I need to do?**

🙌 🙏 Dan

**Comment by mdhont** [comment]
Which application are you running and on which cloud platform?

**Comment by dankings001** [comment]
AWS Lightsail...

**Comment by dankings001** [comment]
Hi can you provide any help?

Thanks Dan 🙌

**Comment by dankings001** [comment]
If I update the bncert tool it then fails... 

Last login: Wed Oct 12 15:54:45 2022 from 52.94.38.36
bitnami@ip-172-26-3-72:~$ sudo /opt/bitnami/bncert-tool
An updated version is available. Would you like to download it? You would need to run it m
anually later. [Y/n]: y

The tool will exit now. To run the updated version run the following command: 

/opt/bitnami/bncert-tool 

bitnami@ip-172-26-3-72:~$ sudo /opt/bitnami/bncert-tool
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default 
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]: 

If I say no to the update, it works (I have several sites)

Last login: Wed Oct 12 15:47:58 2022 from 52.94.38.43
bitnami@ip-172-26-2-0:~$ sudo /opt/bitnami/bncert-tool
An updated version is available. Would you like to download it? You would need to run it m
anually later. [Y/n]: n

----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Domains

Please provide a valid space-separated list of domains for which you wish to 
configure your web server.

Domain list []: eblresources.com eblresources.co.uk www.eblresources.com www.eblresources.
co.uk

A certificate was found at /opt/bitnami/letsencrypt/certificates/eblresources.com.crt
It is registered for a different set of domains: eblresources.com www.eblresources.com.
Do you want to disable/revoke the existing certificate and create a new one? [y/N]: y

----------------------------

**Comment by mdhont** [comment]
Can you try the alternative approach:

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by dankings001** [comment]
I've followed that... got my certificates but the browser is still showing as not encrypted...

**Comment by dankings001** [comment]
Last login: Mon Oct 17 11:24:54 2022 from 52.94.38.37
bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/ctlscript.sh stop
Syntax OK

/opt/bitnami/apache2/scripts/ctl.sh : httpd stopped
/opt/bitnami/php/scripts/ctl.sh : php-fpm stopped
/opt/bitnami/mysql/scripts/ctl.sh : mysql stopped
bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/letsencrypt/lego --tls --email="dan_kings@icloud.com" --domains="dan-king.co.uk" --path="/
opt/bitnami/letsencrypt" renew --days 90
2022/10/17 11:55:18 [INFO] [dan-king.co.uk] acme: Trying renewal with 2158 hours remaining
2022/10/17 11:55:18 [INFO] [dan-king.co.uk, www.dan-king.co.uk] acme: Obtaining bundled SAN certificate
2022/10/17 11:55:18 [INFO] [dan-king.co.uk] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/161119218936
2022/10/17 11:55:18 [INFO] [www.dan-king.co.uk] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/161119218946
2022/10/17 11:55:18 [INFO] [dan-king.co.uk] acme: authorization already valid; skipping challenge
2022/10/17 11:55:18 [INFO] [www.dan-king.co.uk] acme: authorization already valid; skipping challenge
2022/10/17 11:55:18 [INFO] [dan-king.co.uk, www.dan-king.co.uk] acme: Validations succeeded; requesting certificates
2022/10/17 11:55:19 [INFO] [dan-king.co.uk] Server responded with a certificate.
bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/ctlscript.sh start
/opt/bitnami/mysql/scripts/ctl.sh : mysql  started at port 3306
/opt/bitnami/php/scripts/ctl.sh : php-fpm started

**Comment by dankings001** [comment]
still shows as not secure: 

https://dan-king.co.uk/

**Comment by dankings001** [comment]
There's another thread where other users are saying they have the same issue.... that's there's a bug in the bncert update... https://github.com/bitnami/vms/issues/403

**Comment by brent14** [comment]
I just ran into the same exact issue after updating the bncert-tool on AWS lightsail

**Comment by mdhont** [comment]
Could you run the bndiagnostic tool and send the ID that it outputs in the end?

    sudo /opt/bitnami/bndiagnostic-tool

**Comment by dankings001** [comment]
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the fo
llowing code:

d16d7135-6032-9eae-3ed1-c9cce1e64a08

And paste it in your Bitnami Support ticket.

**Comment by mdhont** [comment]
Is the domain pointing to your instance? You can check it here?

https://www.whatsmydns.net

**Comment by dankings001** [comment]
Yes my instance is at: 35.177.114.216

This only happened once I upgraded the bncert tool? Previously it worked fine... and it has now failed on another of my sites on a separate instance, once I updated the bncert tool.

**Comment by mdhont** [comment]
We are investigating the issue. Please follow the thread #403 for further updates. As a workaround, could you use the previous version?
