### ISSUE TITLE
[WordPress] how to upgrade PHP separately

### ISSUE THREAD

**Issue by NanyinK** [bitnami/vms#397]
### Describe your issue as much as you can

Hi,
The php version is 8.0.22 in bitnami v6.0.2-0, and we would like to upgrade it to 8.0.24.
Could you show me a way to upgrade it separately in the stack?

**Comment by gongomgra** [comment]
Hi @NanyinK,

Thanks for using Bitnami. Per the application version you mentioned, I understand you are using our WordPress solution. Please correct me in case I'm wrong.

Upgrading the base components (Apache, MariaDB, PHP...) of our images is not possible. You will have to launch a new server including the upgraded PHP version and then migrate your application data from the old server

https://docs.bitnami.com/aws/how-to/migrate-wordpress/
