### ISSUE TITLE
ELK Packaged By Bitnami For AWS Cloud: Kibana cannot connect to the Elastic Package Registry, which provides Elastic Agent integrations

### ISSUE THREAD

**Issue by ssaz96** [bitnami/vms#399]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

685c25b9-3f2f-093d-df14-ef0f983f70b1

### bndiagnostic output

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ✓ Apache: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

Not addressing the issue

### Describe your issue as much as you can

When launching an EC2 with ELK Packaged By Bitnami For AWS Cloud AMI on AWS. When I open Kibana Integrations I see a warning (screenshot attached) and a few integrations are missing like AWS Elastic Agent and Logstash Filebeat. 

![image](https://user-images.githubusercontent.com/21082341/195833368-36a5e2ea-ae85-4acd-8655-491e0edbd9c9.png)

**Comment by ssaz96** [comment]
Any udpate?

**Comment by gongomgra** [comment]
Hi @ssaz96,

Sorry for the delay and thanks for using Bitnami. I tried setting the `xpack.fleet.registryUrl: https://epr.elastic.co` value in `kibana.yml` file and restarting services, but that doesn't removed the warning. I'm afraid I don't have enough knowledge on this ELK specific configuration. Can you open a new question in the official forums?

**Comment by nasete** [comment]
Hi
Any update about this issue? Run into it on Bitnami's ELK OVA v8.6.1

**Comment by gongomgra** [comment]
Hi @nasete,

As mentioned in my previous message, can you check the official ELK forums for any questions similar to this, or open a new question there in case it doesn't exist?

**Comment by mattpainter701** [comment]
I got this on the latest OVA file still.

**Comment by gongomgra** [comment]
HI @mattpainter701,

Thanks for using Bitnami. As mentioned in one of my previous messages, I'm afraid we don't have enough knowledge about ELK for this specific configuration. Can you open a new question in the official forums?
