### ISSUE TITLE
HTTP ERROR 500 on particular URL

### ISSUE THREAD

**Issue by binampHTG** [bitnami/vms#40]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ef8fa62c-af15-6f6a-ba53-e80dfb26654e

### bndiagnostic was not useful. Could you please tell us why?

The suggested guide doesn't clarify the issue

### Describe your issue as much as you can

Currently, my website is running in WordPress. 
The website is running completely fine from its DNS URL(https://webgorkha.com/) but when the URL is changed to https://webgorkha.com/wp-admin/.  The issue is seen as :
This page isn’t workingwebgorkha.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by mdhont** [comment]
The wp-admin page seems to be accessible. Has the issue been solved?
