### ISSUE TITLE
unable to change file permission

### ISSUE THREAD

**Issue by itsmemidhuz123** [bitnami/vms#400]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ad7d4cdc-0616-6079-659c-1b24349dbb79

### bndiagnostic output

[Sun Oct 16 11:04:36.161473 2022] [proxy_fcgi:error] [pid 4667:tid 
140371560371968] [client **ip_address**:43154] AH01071: Got error 'uery.php on 
line 4190PHP message: PHP Warning: Attempt to read property "ID" on null in 
/opt/bitnami/wordpress/wp-includes/class-wp-query.php on line 4186PHP message: 
PHP Warning: Attempt to read property "post_title" on null in 
/opt/bitnami/wordpress/wp-includes/class-wp-query.php on line 4188PHP message: 
PHP Warning: Attempt to read property "post_name" on nu [Sun Oct 16 
11:04:38.426569 2022] [proxy_fcgi:error] [pid 4535:tid 140370453059328] [client 
**ip_address**:55896] AH01071: Got error 'PHP message: PHP Warning: Attempt to 
read property "ID" on null in 
/opt/bitnami/wordpress/wp-includes/class-wp-query.php on line 4186PHP message: 
PHP Warning: Attempt to read property "post_title" on null in 
/opt/bitnami/wordpress/wp-includes/class-wp-query.php on line 4188PHP message: 
PHP Warning: Attempt to read property "post_name" on null in /opt/bitnami/wo 
[Sun Oct 16 11:04:38.428400 2022] [proxy_fcgi:error] [pid 4535:tid 
140370453059328] [client **ip_address**:55896] AH01071: Got error 'uery.php on 
line 4190PHP message: PHP Warning: Attempt to read property "ID" on null in 
/opt/bitnami/wordpress/wp-includes/class-wp-query.php on line 4186PHP message: 
PHP Warning: Attempt to read property "post_title" on null in 
Press [Enter] to continue:
/opt/bitnami/wordpress/wp-includes/class-wp-query.php on line 4188PHP message: 
PHP Warning: Attempt to read property "post_name" on nu

### bndiagnostic was not useful. Could you please tell us why?

unable to change the file permission

### Describe your issue as much as you can

i have set a new light saleaws instance but unable to set the permission for WordPress with following path /op/bitnami/wordpress/wp-config.php

catching plugin dosent suport because its with permission 777, please help me with the command to change using ssh or something

**Comment by mdhont** [comment]
Please check the following guide to reset permissions:

https://docs.bitnami.com/general/apps/wordpress-production-ready/administration/understand-file-permissions/

**Comment by mdhont** [comment]
You only need to execute these commands:

```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress
sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;
sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
```

**Comment by itsmemidhuz123** [comment]
but the [permission] is still like before

**Comment by itsmemidhuz123** [comment]
hi sir, any update

**Comment by mdhont** [comment]
Could you give more information? Could you show the file' s current permissions?

**Comment by itsmemidhuz123** [comment]
here is the screenshot https://we.tl/t-l7OZrFZDLN
currently unable to edit usuing putty ssh

**Comment by mdhont** [comment]
Could you paste the screenshot here instead?

**Comment by itsmemidhuz123** [comment]
![mcubes - sftp___bitnami@3 130 52 221 - FileZilla 10_16_2022 5_02_58 PM](https://user-images.githubusercontent.com/81553642/196895623-b81df2bf-3404-4953-9178-f5b0dbc60fe5.png)

**Comment by mdhont** [comment]
Those are symlinks. (showing a little arrow on the top left of the icon). The file should be in /opt/bitnami/wordpress/wp-config.php.

**Comment by itsmemidhuz123** [comment]
Yes the file is in opt/bitnami/wordpress/wp-config.php

This is happening on new installations because i tried on another site as
well

**Comment by itsmemidhuz123** [comment]
Hi, any update

**Comment by mdhont** [comment]
> currently unable to edit usuing putty ssh

Could you please give more information. It's not exactly clear to me what the issue is.

**Comment by itsmemidhuz123** [comment]
Issue is that i couldn't able to edit the config.php file

Also i couldn't able to chage the file permissions to 664 using command line

**Comment by mdhont** [comment]
In Filezilla you need to go to the `/bitnami/wordpress` folder. There you should be able to open and edit wp-config.php on your machine by clicking on the file.

**Comment by itsmemidhuz123** [comment]
Sorry, it doesn't work
