### ISSUE TITLE
Bitnami wordpress linux machine

### ISSUE THREAD

**Issue by greg1nelson** [bitnami/vms#401]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a958c5fa-8e1a-8f1a-8adf-b20fbb9867bf

### bndiagnostic output

![Screenshot 2022-10-16 at 16 04 54](https://user-images.githubusercontent.com/6061126/196042947-4a305ae3-2de0-4e7a-a20f-654aee8891a5.png)

### bndiagnostic was not useful. Could you please tell us why?

its not the issue I have

### Describe your issue as much as you can

I recently tried to run the bn-cert tool it asked to update which I agreed to this somehow went wrong.

It then kept asking me which directory bitnami was stored in which I entered /opt/bitnami

How do I remove the bncert-tool and reinstall.

How do I remove the bncert and reinstall.

**Comment by greg1nelson** [comment]
I think its looping as the issue has been reported elsewhere but no definite answer has been given.
By the way the site is https://nation
![Screenshot 2022-10-16 at 16 26 43](https://user-images.githubusercontent.com/6061126/196043924-e150dafa-5287-4bee-9fcd-3d99b634a0bf.png)
altradesmen.co.uk/

**Comment by mdhont** [comment]
Could you try the alternative approach?

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
