### ISSUE TITLE
[WordPress] createdb.php infected with IDP.Generic

### ISSUE THREAD

**Issue by spikesantee** [bitnami/vms#405]
### Describe your issue as much as you can

I just downloaded and installed WAMP on my Windows 10 computer. Then I downloaded Wordpress. When I installed WP, I got this warning from my AVG Antivirus:

Threat Blocked. We've blocked createdb.php because it was infected with IDP.Generic. What would you like to do? Move to Quarantine or Make Exception. 

Which should I do?

**Comment by jotamartos** [comment]
Hi,

I just scanned the Bitnami WordPress installer for Windows and found no issues 

https://www.virustotal.com/gui/url/e295203a5efc59bd465fbb25fa18718f8262ebff113b0c7004719146805d6e23?nocache=1

I do not know why your antivirus is blocking that script, it basically creates the required databases in the server. Please ensure you get the installer from the bitnami.com site and run the installation again.
