### ISSUE TITLE
[Wordpress] 504 Gateway Timeout Error

### ISSUE THREAD

**Issue by AxelPina** [bitnami/vms#406]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3898a2b0-4ecb-bc5f-d3e7-4698c0de165d

### bndiagnostic output

[Mon Oct 17 15:20:32.352346 2022] [proxy:error] [pid 19173:tid 140566864049920] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed [Mon Oct 17 15:20:32.352389 2022] [proxy_fcgi:error] [pid 19173:tid 140566864049920] [client **ip_address**:6130] AH01079: failed to make connection Press [Enter] to continue:to backend: httpd-UDS [Mon Oct 17 15:35:18.464229 2022] [proxy_fcgi:error] [pid 20293:tid 139852135638784] [client **ip_address**:50822] AH01071: Got error 'PHP message: PHP Notice: Unknown: file created in the system's temporary directory in Unknown on line 0', referer: https://www.mydomain.com/wp-admin/post.php?post=21&action=elementor

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides by the tool link to an unrelated article (the deny connections bots apache one)

### Describe your issue as much as you can

I have an AWS LightSail Wordpress instance with the following specs:

- 4 GB Memory
- 2 vCPUs
- 80GB SSD
- 4 TB of transfer
(The $20 tier)

The instance will be up for a certain amount of time then it will fail the Route53 health check then proceed to get sluggish until ultimately the site goes down and it shows 504 Gateway Timeout Error. I have to restart all services for it to slowly go back up, restarting only apache won't do anything.

**Comment by mdhont** [comment]
The following guide might be helpful:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/optimize-bitnami-wordpress/

**Comment by AxelPina** [comment]
After spending several hours debugging Wordpress and dissecting the Apache logs, it turns out the website was going down because of an AWS Route 53 health-check I made. The health-check included all regions. After removing the Asia and EU checks the site has been responsive and 'Healthy' for 2 days now.

For anyone that might run into the same issue in the future:

![Untitled](https://user-images.githubusercontent.com/15352043/196708092-1ad37575-f036-4d4c-a3ae-885a0476a1ff.png)

Reduce the amount of regions that perform the health check, according to your service zone.
