### ISSUE TITLE
[<Bitnami AWS Lightsail Wordpress>] <Roll Back Last bncert-tool Update>

### ISSUE THREAD

**Issue by dilicfrancis** [bitnami/vms#407]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

43736434-f5ee-2920-d9ca-eeb3987dc1cb

### bndiagnostic was not useful. Could you please tell us why?

Problem is simple. Last bncert-tool update has a bug that breaks certificate renewals. Please fix the bug or provide roll back to pre-update bncert-tool

### Describe your issue as much as you can

Question: is there a way or Bitnami command to roll back the last bncert-tool update so people can use the old version once again? This will resolve the issue. The new update can be retried later without sites remaining inaccessible in the meantime. (*The update seems to break only sites currently running a certificate. New instances updated appear unaffected by the bug)

**Comment by mdhont** [comment]
Could you run the bndiagnostic tool? It will provide us with more information. In the meantime you can download a previous version here:

https://downloads.bitnami.com/files/bncert/1.0.1/bncert-1.0.1-linux-x64.run
