### ISSUE TITLE
[LAMP] I want to downgrade Bitnami lamp stack

### ISSUE THREAD

**Issue by suhas6262** [bitnami/vms#408]
### Name and Version

Bitnami lampstack

### What steps will reproduce the bug?

Hi,
I have created an AWS EC2 instance with bitnami LAMP stack with the latest version but in MySQL query, the upper case table names not working it shows a "table is not found" error so I want to downgrade the LAMP version to older. Please let me know the process.

Thanks.

**Comment by gongomgra** [comment]
Hi @suhas6262,

Thanks for using Bitnami. You will have to launch a fresh new server with the previous version of MySQL/MariaDB database and then migrate your application data there. It is not possible to upgrade/downgrade individual components in our cloud images.

You can find old images of our LAMP stack from the EC2 console in the community AMIs section when launching a new instance.
