### ISSUE TITLE
BNCONFIG not found

### ISSUE THREAD

**Issue by AinaLuc** [bitnami/vms#41]
### Describe your suggestion as much as you can

I have issues with bnconfig. When I try this command
/opt/bitnami/wordpress$ sudo ./bnconfig … machine_hostname tanamtech.shop
I got this
sudo: ./bnconfig: command not found.

 Any idea what is wrong?

**Comment by jotamartos** [comment]
Hi @AinaLuc ,

This is not a suggestion but a technical issue, please take that into account when creating a new ticket in the future. 

I understand you are using a Bitnami solution that is using the new directory structure (/opt/bitnami/wordpress vs /opt/bitnami/apps/wordpress). In that case, the bnconfig file does not exist. We suggest you follow this guide to configure the domain in WordPress

https://docs.bitnami.com/general/apps/wordpress/administration/configure-domain/
