### ISSUE TITLE
[OpenProject] Provided "user" password not working

### ISSUE THREAD

**Issue by orcannus** [bitnami/vms#410]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4f606720-050b-f293-e964-30bd74fe1268

### bndiagnostic output

error

### bndiagnostic was not useful. Could you please tell us why?

not related to my issue

### Describe your issue as much as you can

Invalid user or password or the account is blocked due to multiple failed login attempts. If so, it will be unblocked automatically in a short time.

Using the information in the CLI. I have uninstalled and reinstalled with same results. 

Installed on VMWare Workstation 14

**Comment by gongomgra** [comment]
Hi @orcannus,

Thanks for using Bitnami. Unfortunately, I was not able to reproduce your issue. I launched a fresh new virtual machine locally on my laptop, and I was able to access with the generated password. OpenProject initialization process may take a while, you can check it in the `/opt/bitnami/var/log/first-boot.log` file. In my case, it took around 4 minutes to finish. Can you check it on your side?

```
$ sudo cat /opt/bitnami/var/log/first-boot.log
(...)
2022-10-19T10:47:56.112Z - info: Initializing module openproject
openproject 10:47:56.35 INFO  ==> Trying to connect to the database server
openproject 10:47:56.36 INFO  ==> Configuring OpenProject with settings provided via environment variables
openproject 10:47:56.43 INFO  ==> Populating database
openproject 10:49:13.54 INFO  ==> Creating admin user
openproject 10:49:47.44 INFO  ==> Setting OpenProject hostname to localhost
openproject 10:50:07.43 INFO  ==> Configuring extra services
2022-10-19T10:50:07.447Z - info: Saving configuration info to disk
2022-10-19T10:50:07.448Z - info: Saving configuration info to disk
```
