### ISSUE TITLE
[WordPress] Error Connecting Database on AWS Lightsail 

### ISSUE THREAD

**Issue by gunjanstreams** [bitnami/vms#412]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3af950ea-3983-11f3-12e0-16f8600f4660

### bndiagnostic output

? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ? Processes: Found possible issues
    ✓ Php: No issues found

Attached below is some part of my log from InnoDB.
[SystemLog.txt](https://github.com/bitnami/vms/files/9814863/SystemLog.txt)

### bndiagnostic was not useful. Could you please tell us why?

It didnt help me solve problem. MariaDB was turning off itself. 

### Describe your issue as much as you can

Hello, I hope you are fine and doing well. I installed Bitnami Wordpress in an Instance in Singapore Region. Later it was quietly misfunctioning. My website used to crash on intself and reopen when I stopped and started the instance. But today after stopping and starting the instance, I got into Error Establishing Database error, which is not solved. I searched all over the internet and also followed Bitnami Guidelines, but none of them worked. PLease help me solve the issue, as I had lots of data there, I cannot dump the SQL file as well, it says connection ended. Below attached is the system log for my Instance from SQL. Also, MariaDB keeps on turning off on itslef with lots of Log in Log folder.

**Comment by jotamartos** [comment]
Hi,

I can see these errors in the database 

```
2022-10-18 14:39:59 0 [ERROR] InnoDB: Page [page id: space=0, page number=54] log sequence number 1361349905 is in the future! Current system log sequence number 1359333541.
2022-10-18 14:39:59 0 [ERROR] InnoDB: Your database may be corrupt or you may have copied the InnoDB tablespace but not the InnoDB log files. Please refer to https://mariadb.com/kb/en/library/innodb-recovery-modes/ for information about$
```

Please take a look at the guide to recover the database and read related articles online about this issue

https://mariadb.com/kb/en/library/innodb-recovery-modes/ 
https://dba.stackexchange.com/questions/46187/innodb-log-sequence-number-is-in-the-future/46197#46197
