### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by spam0115** [bitnami/vms#414]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

none

### bndiagnostic output

I can't run the bndiagnostic.  This what I get:
Error copying file from packed archive /opt/bitnami/bndiagnostic/bndiagnostic-0.9.17-linux-x64.run to /tmp/autoupdater/update.ini
I changed the permissions on tmp/autoupdater/ to 777 but that had no effect.

### bndiagnostic was not useful. Could you please tell us why?

It can't even run.

### Describe your issue as much as you can

I am unable to run the ssl cert tool because I get the following error: Error running diff -uw /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf.back.202210182236: child process exited abnormally

When I run that command manually, "diff -uw /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf.back.202210182236", it runs without any problem.

**Comment by mdhont** [comment]
Are you running the command with sudo? Also, could you update the ticket title?
