### ISSUE TITLE
[Wordpress] cannot find Wordpress files

### ISSUE THREAD

**Issue by petehawk** [bitnami/vms#417]
### Describe your issue as much as you can

In an attempt to upgrade the PHP version running my site, I created a new instance and can connect to the new Wordpress site.  However when I connect to the instance via SMTP(SSH) the file structure is different from the old Instance.  

Two screenshots  - the one without the APPS folder is the new one (and there is nothing in the htdocs or Stack folder either.)

<img width="203" alt="Screenshot 2022-10-19 at 12 16 22" src="https://user-images.githubusercontent.com/25504433/196677037-cdb6160d-d7c4-4cb0-a40b-e5c52d94f0bd.png">
<img width="278" alt="Screenshot 2022-10-19 at 12 16 28" src="https://user-images.githubusercontent.com/25504433/196677044-b65927e3-81a8-4cbd-9cf2-dfbeb426abfb.png">
Bitnami say their restructuring file structures but are not specific (Type A is mine).  

What have I done wrong?!

Pete

**Comment by jotamartos** [comment]
This guide explains the new directory structure

https://docs.bitnami.com/general/faq/get-started/understand-directory-structure/

You can find the WordPress' files inside the /opt/bitnami/wordpress folder

**Comment by petehawk** [comment]
Yep seen that but the file structure I see doesn’t have an /opt/ folder that I can find. Unless my path is wrong when I log in via SFTP. (I left that blank so I assumed it would take me into the root. Wordpress is there because I can log in to it!PetePete Hawkins - Writer, Walking Guide and Web Designer07811 191456On 21 Oct 2022, at 09:08, Juan José Martos ***@***.***> wrote:﻿
This guide explains the new directory structure
https://docs.bitnami.com/general/faq/get-started/understand-directory-structure/
You can find the WordPress' files inside the /opt/bitnami/wordpress folder

**Comment by jotamartos** [comment]
>Unless my path is wrong when I log in via SFTP. (I left that blank so I assumed it would take me into the root.

No, you access the user's home folder when log in via SFTP. That means you are in /home/bitnami and not in the root path. Please change directories to /opt/bitnami/wordpress to see the WordPress' files.

**Comment by petehawk** [comment]
Brilliant, thanks Juan José… I'm in.

Much appreciate your help

Pete
