### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by MFAB-LLC** [bitnami/vms#418]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2a5dd1a4-a40c-86fb-9efb-5d8264efc760

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ✓ Wordpress: No issues found
    ✓ Connectivity: No issues found
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ? Resources: Found possible issues
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Oct 19 03:26:16.320513 2022] [proxy_fcgi:error] [pid 26990:tid 
139992378570496] (70008)Partial results are valid but processing is incomplete: 
[client **ip_address**:34330] AH01075: Error dispatching request to : (reading 
Press [Enter] to continue:
input brigade)
 [Wed Oct 19 17:28:47.074294 2022] [core:error] [pid 26721:tid 139992470890240] 
[client **ip_address**:50150] AH10244: invalid URI path 
(/cgi-bin/.%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/hosts)

 [Wed Oct 19 17:28:47.294127 2022] [core:error] [pid 1669:tid 139992235894528] 
[client **ip_address**:50344] AH10244: invalid URI path 
(/cgi-bin/.%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/hosts)


```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 66 of /opt/bitnami/apache2/conf/httpd.conf: Cannot load modules/mod_mpm_event.so into server: 
/opt/bitnami/apache/modules/mod_mpm_event.so: undefined symbol: 
ap_run_child_stopping
```
Press [Enter] to continue:
Please check the configuration.

A high number of incoming requests originate from one or more unique IP addresses. This could indicate a bot attack. The following guide shows how to check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-bots-apache/

[Resources]

Your instance has little available RAM memory.
```
              total        used        free      shared  buff/cache   available
Mem:            585         418          40          24         127          50
Swap:           634         362         272
```
You could try to increase your instance's memory. Please check your cloud provider's documentation for more information.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are not related to my issue

### Describe your issue as much as you can

When attempting to verify my Wordpress site on Gravatar I am receiving the following failure message:

> **Failed to locate XML-RPC API**
> Something went wrong when trying to locate the XML-RPC API on your blog. Please log into your WordPress admin panel, then go to Settings > Writing > Remote Publishing and check the box next to 'Enable the WordPress, Movable Type, MetaWeblog and Blogger XML-RPC publishing protocols.'

[This support link is the only mention of enabling XML-RPC publishing protocols on Bitnami that I could find. ](https://docs.bitnami.com/google/apps/wordpress/troubleshooting/xmlrpc-and-pingback/)

I followed the instructions and uploaded the edited `wp-config.php` file back to `/opt/bitnami/wordpress` but I still get the same failure message.  For now I replaced the wp-config.php file back to its original state with the xmlrpc pingback removal routine in place.

Please advise on how I can enable XML-RPC publishing protocols for my website.

Thank you.

**Comment by mdhont** [comment]
I recommend asking in the application's dedicated forum. The issue does not seem related to the Bitnami configuration and usually they will have a better understanding of the specifics of the application there.

**Comment by MFAB-LLC** [comment]
I will ask on Gravatar's dedicated forum.  Thank you.
