### ISSUE TITLE
phpMyAdmin - Error session_start(): Failed to read session data: files (path: /opt/bitnami/php/var/run/session)

### ISSUE THREAD

**Issue by marcus-sm8a** [bitnami/vms#419]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

53dcd8ff-ea82-b9e8-30bf-c21fc7c2af2b

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Oct 19 20:10:39.517130 2022] [proxy_fcgi:error] [pid 22025:tid 
140011638880000] [client **ip_address**:57250] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0'
 [Wed Oct 19 20:10:40.087004 2022] [proxy_fcgi:error] [pid 22428:tid 
Press [Enter] to continue: 
140011353528064] [client **ip_address**:42774] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0'
 [Wed Oct 19 21:38:01.247713 2022] [authz_core:error] [pid 22428:tid 
140011496204032] [client **ip_address**:64380] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/index.php, referer: 
https://dev.********.au/wp-admin/admin.php?page=wp-phpmyadmin-extensio
n

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1995 1146 125 20 723 644 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
Press [Enter] to continue:
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-memory-linux/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

this tool wasn't able to examine the phpmyadmin errors, but I still think it is a great tool. 

### Describe your issue as much as you can

Running Bitnami Wordpress 6.0.3 in Amazon Lightsail, I have been trying to use the phpmyadmin page to access the non-local database, this bitnami image has php version 7.4.28.

I used the information from the following bitnami support pages to setup this process.
Please note we are not using any local database, The database is a AWS lightsail database. 

https://docs.bitnami.com/aws/faq/get-started/access-phpmyadmin/

this process has worked for years on my other sites, but for some reason it does work on this particular site. 

I also use this process to setup the linux port forwarding on my Mac, which I know how to do well. 
https://docs.bitnami.com/aws/faq/get-started/access-phpmyadmin/

I get the following screen shot below when I try to access "https://127.0.0.1:8890/phpmyadmin"

<img width="1048" alt="Screen Shot 2022-10-20 at 8 00 15 am" src="https://user-images.githubusercontent.com/60305852/196812819-aed6525b-6fb7-41d9-af67-712ca891f826.png">

Is this a Folder Permission Issue? 

Any assistance would be appreciated, please remember this is a dev site and is not production, but as I can't figure out this issue I am puzzled by this error and would know what it is and how to fix it in the future.

**Comment by marcus-sm8a** [comment]
Hello Michiel, thanks for all your help with the Bitnami support pages, I have seen several of your bitnami YouTube support videos and I find them very informative and helpful. and your responses to bitnami Wordpress support articles have help me fix and improve the current bitnami Wordpress systems that we are using here.

**Comment by mdhont** [comment]
> Hello Michiel, thanks for all your help with the Bitnami support pages, I have seen several of your bitnami YouTube support videos and I find them very informative and helpful. and your responses to bitnami Wordpress support articles have help me fix and improve the current bitnami Wordpress systems that we are using here.

I'm glad to hear that! 

> Is this a Folder Permission Issue? Any assistance would be appreciated, please remember this is a dev site and is not production, but as I can't figure out this issue I am puzzled by this error and would know what it is and how to fix it in the future.

It could be related to a lack of resources. Could you check the available RAM?

    free -m

**Comment by marcus-sm8a** [comment]
free -m
              total        used        free      shared  buff/cache   available
Mem:           1995         988         198          20         808         803
Swap:             0           0           0

**Comment by marcus-sm8a** [comment]
Hello, I did notice that the local database (mariadb) was still loading into memory even though the service is not running anymore. Is there a way to prevent the local database from loading into memory in the future? I can't seem to find anything about how to do this. Thanks for your time an efforts.

**Comment by marcus-sm8a** [comment]
Hello, sorry about the late reply - we fixed this phpmyadmin issue some time ago, but I through that I should put the solution down. the phpmyadmin error was fixed by looking at the folder permissions with the php folder, it was assigned to an incorrect group, this was a subtle overlooked. the memory and free space wasn't the issue.  Cheers.
