### ISSUE TITLE
Apache messed up after repeatedly trying to fix TLS certificate

### ISSUE THREAD

**Issue by ZioCain** [bitnami/vms#42]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

55266d88-0d0e-5630-6653-6e004b1acdfb

### bndiagnostic output

? Apache: Found possible issues
? Connectivity: Found possible issues
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-bots-apache/
https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

I do not know how to perform the changes explained in the documentation

### Describe your issue as much as you can

TLS certificate expired today.
I tried to remove it and then issue a new one with certbot.
Since it failed that way, I then tried to issue a new one using:
/opt/bitnami/bncert-tool

But it kept failing because I’m using a static IP which of course isn’t the same as the machine one.

I then tried:
/opt/bitnami/bncert-tool --perform_public_ip_validation 0 --perform_dns_validation 0

But it also failed because of connectivity issues.
After that, apache isn’t starting anymore.

I’m completely losst and I don’t know what to do, how to do it

**Comment by jotamartos** [comment]
Hi @ZioCain,

I'm glad to hear you managed to solve the issue. Please take a look at the comment I posted in the old community forum:

https://community.bitnami.com/t/apache-messed-up-after-repeatedly-trying-to-fix-tls-certificate/106568

**Comment by ZioCain** [comment]
Hello, as mentioned in the other issue on the old communicy forum, I didn't solve the problem, but I'm just offering the website _without_ TLS certificate (which is a huge problem, of course).

Is there anything else I can do?
Any extra info you need from me?

Here's a detailed log (I don't know if I should still post there or posting here is preferable):
https://community.bitnami.com/t/apache-messed-up-after-repeatedly-trying-to-fix-tls-certificate/106568/3

**Comment by mdhont** [comment]
Can you try the [alternative approach](https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach) and add the `--perform_public_ip_validation 0 --perform_dns_validation 0` to the lego command?

**Comment by ZioCain** [comment]
As stated above, I did already try that, but nothing changed.

So what I did was using the certificates I did create with letsencrypt, they were stored in the wrong folder (pelodigita.it-0001) but the apache2 conf was pointing to the pelodigital.it folder inside /etc/letsencrypt

Changing those references solved the problem for me.
