### ISSUE TITLE
[wordpress] Apache server running same process multiple times thus using a lot of memory

### ISSUE THREAD

**Issue by Lord-of-Milk** [bitnami/vms#420]
### Describe your issue as much as you can

Hi there,

I am running the bitnami wordpress stack on an aws lightsail instance. Somehow my servers memory usage increases between two restarts (at the moment 24h between two restarts). Overall the usage icreases from 35% at startup to apx 65% at shutdown. I checked the processes running and found, that there are a lot of disable banner processes running. I was not able to identify, what triggers this command. Also I found, that the flag in the end of the comment is written with a double D.

Can you point me into the direction what could be causing these issues? Or help me how I can find the root cause, that triggers the process?

excerpt from the console:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND

daemon   12634  0.0  4.9 2560356 198348 ?      Sl   00:00   0:10 /opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -DDISABLE_BANNER

daemon   12635  0.0  4.0 2553792 162048 ?      Sl   00:00   0:10 /opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -DDISABLE_BANNER

daemon   12636  0.0  4.3 2559948 176448 ?      Sl   00:00   0:10 /opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -DDISABLE_BANNER

daemon   12637  0.0  5.7 2564080 233180 ?      Sl   00:00   0:08 /opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -DDISABLE_BANNER

daemon   13286  0.0  7.7 2564392 311324 ?      Sl   00:00   0:38 /opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -DDISABLE_BANNER
```

Thanks!!

**Comment by gongomgra** [comment]
Hi @Lord-of-Milk ,

Thanks for using Bitnami. Those processes are the Apache workers that will attend the requests to your website. The `-DDISABLE_BANNER` is just an extra option we provide to the workers, but you don't have to worry. It is hiding a custom banner in your website showing the Bitnami logo.

About the performance issues you mentioned, can you run our bnsupport bundle and share the generated code with us? It will try to detect some common known problems on your server and print some references to solve them.

**Comment by Lord-of-Milk** [comment]
Hi @gongomgra,

thank you for the fast reply and explanation. Also the bnsupport bundle did work like a charm: f7eb69e0-ae8f-47a8-85d1-f40567eef1ad

Looking forward to your suggestions!

**Comment by gongomgra** [comment]
Hi @Lord-of-Milk,

Thanks for sharing the code. According to the bndiagnostic tool findings, I see you are having errors with PageSpeed.

```
[Fri Oct 21 17:52:11.263933 2022] [pagespeed:error] [pid 12027:tid 139778234251008] [mod_pagespeed **ip_address**-0 @12027] PageSpeed Serf fetch failure rate extremely high; only 0 of 700 recent fetches fully successful; is fetching working?

```
We suggest disabling pagespeed and check if that improves the behavior. Please check the following guide to disable Pagespeed:

https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespeed/#disable-pagespeed

I also see your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3946 2742 139 223 1064 707 Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud provider's documentation for more information.

Finally, I see there are a few IP addresses performing several requests to your server, which can end up exhausting your machine resources. 

```
-----------------------------------
Check performance issues: Count number of requests for the 10 most active IP addresses in the last 100.000 requests
-----------------------------------
Running: tail -n 100000 access_log | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 10 | awk '{print $1}'
In: /opt/bitnami/apache2/logs/

Output:

2592
2489
2193
1401
1148
828
808
762
751
750
```

This could indicate a bot attack. The following guide shows how to check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

**Comment by Lord-of-Milk** [comment]
Hi @gongomgra,

Thank you!! I disabled PageSpeed and will monitor the changes. I will also look for bot attacks and if needed upgrade the memory.

What I am really trying to solve though, is the increase of memory consumption thorughout the day, that I cannot explain. It feels like something has a memory leak. Is there a way to debug it? Are the 3 points you highlighted potential root causes for this? The RAM usage looks like a sawtooth. See the picture.

Thanks!

![grafik](https://user-images.githubusercontent.com/44750893/198825452-d390860d-44f8-4019-b2e5-ce583af07844.png)

**Comment by gongomgra** [comment]
Hi @Lord-of-Milk,

Thanks for your message. Sorry, there was a typo in the link to the bots guide in my previous message. I have updated it, but I'm also sharing it again for your convenience

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/

Regarding the memory usage, it is so curious it has such a periodical behavior, but I'm afraid I don't know what can be causing that. Can you run the bndiagnostic tool and share the generated code with us?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/
