### ISSUE TITLE
[Wordpress] Multiple wordpress sites?

### ISSUE THREAD

**Issue by JacqsLabz** [bitnami/vms#421]
### Describe your issue as much as you can

If I'm using the stack version of bitnami without XAMPP, can I still setup multiple wordpress sites and have full phpmyadmin access? Will they each have their own phpmyadmin, or will they all exist in on phpmyadmin? If I can make multiple wordpress sites in 1 bitnami stack install, then how do I do it? I don't see any add site button. Is there way to clone it from an existing wordpress.com site?

**Comment by gongomgra** [comment]
Hi @JacqsLabz,

Thanks for using Bitnami. Yes, you can install many independent WordPress sites on your server, each of them using its own database, following the guide below

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

You can then access all the databases from phpmyadmin. Regarding your question about cloning a site from wordpress.com, I understand you can migrate your WordPress data to the new site. We have a quick guide on how to do it as well.

https://docs.bitnami.com/aws/how-to/migrate-wordpress/
