### ISSUE TITLE
[<AWS Lightsail Bitnami WordPress>] <OS Security Patches>

### ISSUE THREAD

**Issue by liukang93** [bitnami/vms#422]
### Describe your issue as much as you can

Can I understand how to patch the security in AWS Lightsail Bitnami WordPress?

**Comment by mdhont** [comment]
I recommend launching the latest Bitnami WordPress version, which has all the latest component versions and patches, and then migrate your site there:

https://docs.bitnami.com/aws/how-to/migrate-wordpress/
