### ISSUE TITLE
[Magento] Cannot access homepage

### ISSUE THREAD

**Issue by Niblu** [bitnami/vms#423]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

dd0a9335-137a-fcec-ca68-073b6d714204

### bndiagnostic output

Found recent error or warning messages in the Apache error log.
```
[Fri Oct 21 05:48:43.376508 2022] [proxy_fcgi:error] [pid 5903:tid 
139974678583040] [client **ip_address**:56598] AH01079: failed to make 
connection to backend: httpd-UDS
 [Fri Oct 21 05:52:01.993859 2022] [authz_core:error] [pid 1416:tid 
139675859498752] [client **ip_address**:44666] AH01630: client denied by server 
configuration: /opt/bitnami/magento/app/etc/config.php
Press [Enter] to continue:
 [Fri Oct 21 05:57:27.613308 2022] [authz_core:error] [pid 1418:tid 
139676316489472] [client **ip_address**:38328] AH01630: client denied by server 
configuration: /opt/bitnami/magento/app/etc/config.php
```

### bndiagnostic was not useful. Could you please tell us why?

Cannot solve using info provided there

### Describe your issue as much as you can

I can access admin at http://3.69.142.168/admin and subpages like http://3.69.142.168/kolesa/otroska, only home page returns this error: (it is not on page, as any page that is set as homepage returns error aswell)

```
<div class="breadcrumbs" data-mage-init='{
    "breadcrumbs": {
        "categoryUrlSuffix": ".html",
        "useCategoryPathInUrl": 0,
        "product": "An error has happened during application run. See exception log for details.
```

I find this error repeating in exception.log.

```
[2022-10-21 06:31:06] main.CRITICAL: The contents from the "/bitnami/magento/pub/static/frontend/Smartwave/porto_child/de_DE/mage/requirejs/mixins.js" file can't be read. Warning!file_get_contents(/bitnami/magento/pub/static/frontend/Smartwave/porto_child/de_DE/mage/requirejs/mixins.js): failed to open stream: No such file or directory {"exception":"[object] (Magento\\Framework\\Exception\\FileSystemException(code: 0): The contents from the \"/bitnami/magento/pub/static/frontend/Smartwave/porto_child/de_DE/mage/requirejs/mixins.js\" file can't be read. Warning!file_get_contents(/bitnami/magento/pub/static/frontend/Smartwave/porto_child/de_DE/mage/requirejs/mixins.js): failed to open stream: No such file or directory at /bitnami/magento/vendor/magento/framework/Filesystem/Driver/File.php:185)"} []
```

I tried with different permission error fixes, I found apache permissions wrong and fixed them, then restarted, but still the homepage doesn't work, everything else works.

**Comment by jotamartos** [comment]
>[2022-10-21 06:31:06] main.CRITICAL: The contents from the "/bitnami/magento/pub/static/frontend/Smartwave/porto_child/de_DE/mage/requirejs/mixins.js" file can't be read. Warning!file_get_contents(/bitnami/magento/pub/static/frontend/Smartwave/porto_child/de_DE/mage/requirejs/mixins.js): failed to open stream: No such file or directory {"exception":"[object] (Magento\\Framework\\Exception\\FileSystemException(code: 0): The contents from the \"/bitnami/magento/pub/static/frontend/Smartwave/porto_child/de_DE/mage/requirejs/mixins.js\" file can't be read. Warning!file_get_contents(/bitnami/magento/pub/static/frontend/Smartwave/porto_child/de_DE/mage/requirejs/mixins.js): failed to open stream: No such file or directory at /bitnami/magento/vendor/magento/framework/Filesystem/Driver/File.php:185)"} []

This seems to be an error in the app itself, not the Bitnami's configuration. Please remember Apache always use the daemon user to read and write the app's files. If you set that username when changing permissions, everything should work. If you can't access the main site, the app's documentation and its support team should provide more information about how to troubleshoot this.
