### ISSUE TITLE
Bitnami Wordpress GCP - Unable to change Wordpress Site/Home URL - Permission Denied

### ISSUE THREAD

**Issue by ani88lain** [bitnami/vms#426]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b4684aff-2cbc-8147-108c-37f856638093

### bndiagnostic was not useful. Could you please tell us why?

Unable to change Wordpress Site/Home URL -Permission Denied

### Describe your issue as much as you can

Hi,

I was trying the whole day to change my IP static address from GCP to my domain URL name which is grayed out in WordPress Settings and is using my IP. I tried to follow these instructions from Bitnami in SSH https://docs.bitnami.com/aws/apps/wordpress/administration/configure-domain/ with approaches A and B but was unsuccessful. Command was not found. Also tried the following:

sudo -i
vim /opt/bitnami/apps/wordpress/htdocs/wp-config.php

#OR

sudo vim /opt/bitnami/apps/wordpress/htdocs/wp-config.php

I'm not sure what a swap file means and nothing I do (Open read-only, edit, recover, abort) is showing the following: 

define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/');
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/'); 

How can I get this to replace the domain IP with the Site URL?

I'm using Filezilla with RSA Putty Key and I'm unable to View/Edit files like wp-config.php or wp-content. Has 777 permission and the permission is denied. 

Attaching screenshots. 

![1](https://user-images.githubusercontent.com/105136007/197262449-446a7f42-917e-4596-9607-c5c90be265f5.JPG)

![2](https://user-images.githubusercontent.com/105136007/197262462-cabcff0c-f759-4308-ab9b-17d79207c8d2.JPG)

![3](https://user-images.githubusercontent.com/105136007/197262476-b9eb211b-5c5d-4ff0-9ff3-a6f5550493a1.JPG)

**Comment by mdhont** [comment]
For editing through SSH:

You need to open an inline editor like nano:

    nano /path/to/file

With FileZilla you can find the wp-config.php file in /bitnami/wordpress/. You can easily access this directory by entering the path in the "Remote site" field:

<img width="641" alt="Screenshot 2022-10-25 at 14 09 40" src="https://user-images.githubusercontent.com/18216803/197769374-bae84454-8bc0-4e6d-8c3c-7d25b94eddcb.png">
