### ISSUE TITLE
[Wordpress] server reached max_children setting (5), consider raising it

### ISSUE THREAD

**Issue by parsons106** [bitnami/vms#427]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

did not see this code

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Resources: No issues found
    ✓ Mysql: No issues found
    ? Php: Found possible issues

[Apache]

Found recent errors or warning messages in the Apache error log.
```
[Sat Oct 22 13:51:35.557407 2022] [proxy_fcgi:error] [pid 12492:tid
140209936983808] (70007)The timeout specified has expired: [client
**ip_address**:18274] AH01075: Error dispatching request to : (polling)
 [Sat Oct 22 13:51:36.921406 2022] [proxy_fcgi:error] [pid 12492:tid
140210079659776] (70007)The timeout specified has expired: [client
**ip_address**:16342] AH01075: Error dispatching request to : (polling),
referer:
```

Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Php]

The following error appears in the
/opt/bitnami/php/var/log/php-fpm.log:
Press [Enter] to continue:
```
[22-Oct-2022 12:54:33] WARNING: [pool www] server reached max_children setting
(5), consider raising it
```

This error usually indicates PHP script execution is slow due to busy server
resouces or buggy scripts. Please check the following guide to increase the
number of PHP-FPM child processes:

https://docs.bitnami.com/general/apps/wordpress/configuration/configure-ph
pfpm-processes/

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides did not work 

### Describe your issue as much as you can

I've edited the the common-dynamic.conf
```
include=/opt/bitnami/php/etc/common.conf
pm=dynamic
pm.max_children = 25
pm.start_servers = 15
pm.min_spare_servers = 15
pm.max_spare_servers = 25

include=/opt/bitnami/php/etc/bitnami/common.conf
```

I've also set  wordpress  to dynamic  and restartedthe services, but the same error is appearing causing the CPU spikes.

Any ideas why the max children is not increasing to values set?

**Comment by gongomgra** [comment]
Hi @parsons106,

Thanks for using Bitnami. We first recommend you to check the different items that the bndiagnostic tool suggests in order to fix the detected issues on your server. Additionally, please refer to the next guide on how to configure the PHP-FPM processes.

https://docs.bitnami.com/aws/apps/wordpress/configuration/configure-phpfpm-options/

Apart from the above, notice that increasing the number of PHP-FPM processes on your server will consume more resources, which can generate other issues.

**Comment by parsons106** [comment]
Hi, the guide you recommended suggests increasing the memory limit. Would this solve the issue (server reached max_children
 setting (5), consider raising it?)

Or should I add the below settings to the file?

pm=dynamic
pm.max_children = 25
pm.start_servers = 15
pm.min_spare_servers = 15
pm.max_spare_servers = 25

**Comment by parsons106** [comment]
![image](https://user-images.githubusercontent.com/92389291/197568868-ccbe537b-4517-4da1-8418-273a73d67306.png)

I'm noticing high CPU usage from mysqld.bin around the time of the error (server reached max_children setting (5))

**Comment by gongomgra** [comment]
Hi @parsons106,

Can you tell us if your machine is based on approach A o B according to the command below?

```
test ! -f "/opt/bitnami/common/bin/openssl" && echo "Approach A: Using system packages." || echo "Approach B: Self-contained installation."
```

In case you are using Approach A, notice you have to edit the values in the `/opt/bitnami/php/etc/memory.conf` file, and then restart the php-fpm service for changes to take effect. Remember that increasing the values there will end-up using more resources on your machine, which can cause additional issues.

```
sudo /opt/bitnami/ctlscript.sh restart php-fpm
```

Regarding the MySQL binary using a lot of CPU, this usually means that you are getting a lot of requests causing database changes. Can you check the guide I linked before about detecting and blocking bots IP addresses? 

Apart from that, can you run the bndiagnostic tool again and share with us the support code? Please paste the code here directly so we can easily check it.
