### ISSUE TITLE
[LAMP] HTTP 403 after changing vhost DocumentRoot to another volume

### ISSUE THREAD

**Issue by fernandoweise** [bitnami/vms#429]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bitnami failed to upload the diagnostic bundle

### bndiagnostic output

[bitnami-lampstack-info-20221022-213048-1498.zip](https://github.com/bitnami/vms/files/9845292/bitnami-lampstack-info-20221022-213048-1498.zip)

### bndiagnostic was not useful. Could you please tell us why?

not related to my issue (?)

### Describe your issue as much as you can

I've run out of space on my AWS Lightsail instance running Bitnami LAMP 7, so I decided to attach another disk to my instance and move some projects there. 

I have a vhost configurated for this project, under the subdomain `athena.fweise.de`. It works fine as far as the DocumentRoot is set to `/opt/bitnami/apache2/htdocs/athena`. Then I copied the files to `/neptune/htdocs/athena`, updated permissions for the new directory and edited my vhost configuration file. But when I try to access this through my web browser, I get a HTTP 403 error: Forbidden. 

My vhost configuration file looks like this:

```
<VirtualHost 127.0.0.1:443 _default_:443>
	DocumentRoot "/neptune/htdocs/athena"
    ServerAdmin fernando@fweise.de
    ServerName athena.fweise.de
	ServerAlias athena.fweise.de
	SSLEngine on
  	SSLCertificateFile "/opt/bitnami/apache2/conf/fweise.de.crt"
  	SSLCertificateKeyFile "/opt/bitnami/apache2/conf/fweise.de.key"
    <Directory "/neptune/htdocs/athena">
    	Options +Indexes +FollowSymLinks +MultiViews
      	IndexOptions FancyIndexing HTMLTable 
	AllowOverride All
    	Require all granted
 	</Directory>
	Alias /.well-known/ "/opt/bitnami/apps/letsencrypt/.well-known/"
	<Directory "/opt/bitnami/apps/letsencrypt/.well-known">
	    Options +MultiViews
	    AllowOverride None
	    Require all granted
	</Directory>
</VirtualHost>
```

As for the permissions, what I did was:

```
sudo chown -R bitnami:daemon /neptune/htdocs/*
sudo chmod -R g+w /neptune/htdocs
```

Perhaps I'm missing something very simple or perhaps this process should be more complicated than I thought.

I'd very much appreciated if anyone could give me some insight into how to solve this. I thank you all in advance for any help you can provide.

**Comment by mdhont** [comment]
Did you change the owner of the htdocs folder as well? Also, please check this guide for further information:

https://docs.bitnami.com/virtual-machine/infrastructure/lamp/configuration/configure-custom-application/

**Comment by fernandoweise** [comment]
Yes, I did.
