### ISSUE TITLE
[bncert-tool] All bitnami instances renew certificates at the same time, causing errors.

### ISSUE THREAD

**Issue by mcpherrinm** [bitnami/vms#43]
### Describe your issue as much as you can

Hello!  I'm an engineer working at Let's Encrypt, the certificate authority that Bitnami uses to issue certificates.

Recently, we've been noticing bursts of errors as tens of thousands of clients around the world try to connect all at nearly the same instant, within a few seconds of 00:00 UTC (midnight), exceeding our maximum instantaneous ability to handle those api requests.

I've been revewing logs and other data to identify the source of these bursts.  They are coming from clients identifying as `lego-cli`, and based on some investigation of hostnames and HTTP(s) servers, appear to be running common web applications like Wordpress, and are running primarily on the major cloud providers: AWS, GCP, and Azure.  Notably, I've seen the name "bitnami" reoccuring in several hostnames.  All of this leads me to suspect that this spike is caused by Bitnami.

I've set up a wordpress with bitnami (a very slick experience I might add - well done!) and verified that when I run the "bncert-tool", it adds a cronjob to the bitnami user which runs `lego` on a "0 0 * * *" schedule.

We would greatly appreciate it if the bncert-tool could be updated to instead choose a random hour and minute for each instance's renewal cron to run.  That would spread the load out more evenly, which will make your product more reliable since right now a fraction of renewals will fail due to overload.  In addition, we've [also asked the lego-cli upstream project to add a random delay](https://github.com/go-acme/lego/issues/1656) which once tagged into a release, will also help spread load throughout the minute, since generally cron job specifications are at minute granularity only.

If this isn't an appropriate venue for this request, please feel free to direct me elsewhere, or I'm available at mattm@letsencrypt.org if any bitnami developers would rather communicate over email about the details and request here.

Thank you in advance!

**Comment by mdhont** [comment]
Hi @mcpherrinm,

I've created a task for randomising the time of renewal, and I will give it some priority. We will notify you after releasing a new version of bncert tool. Unfortunately this won't change the already existing peak in activity.

**Comment by mdhont** [comment]
We will check the possibility of changing existing cronjobs during an update of the bncert tool to get rid of the existing peak.

**Comment by mcpherrinm** [comment]
Are you able to upgrade the version of `lego` on existing installations?  They’ve added a bit of jitter which would be sufficient to fix the existing leak if it is too hard to change existing cronjobs

**Comment by marcosbc** [comment]
Hi @mcpherrinm, thanks for reporting this issue. We have just released a new version of the "bncert" tool which is now setting a random time for the renewal, e.g.:

```
$ sudo crontab -u bitnami -l

41 12 * * * sudo /opt/bitnami/letsencrypt/lego --path /opt/bitnami/letsencrypt ... # bncert-autorenew
```

Note that any users that executes any version of this tool will be prompted to upgrade, after which they would be using the latest version. Check an example below:

```
$ sudo ./bncert-tool --version
Bitnami HTTPS Configuration Tool 0.7.4 --- Built on 2022-06-08 14:02:48 IB: 21.6.0-202106241241
$ sudo ./bncert-tool
An updated version is available. Would you like to download it? You would need to run it manually later. [Y/n]: y

The tool will exit now. To run the updated version run the following command:

/opt/bitnami/bncert-tool

$ sudo ./bncert-tool  --version
Bitnami HTTPS Configuration Tool 0.8.0 --- Built on 2022-06-30 15:20:55 IB: 21.6.0-202106241241
```

In addition, he crontab entry will be modified even when running for the second time on an installation already configured with "bncert", meaning that any users executing this tool from now on should not see this issue anymore.

>Are you able to upgrade the version of `lego` on existing installations? They’ve added a bit of jitter which would be sufficient to fix the existing leak if it is too hard to change existing cronjobs

We have been checking this and unfortunately there still hasn't been any new version release of the tool with the fixes.

Once that happens, we will release another new version of the tool with the new version of Lego, which will also update `lego` on the users' side upon (manual) execution of the "bncert" tool.

**Comment by marcosbc** [comment]
We also wanted to clarify that, unfortunately, it will be impossible for us to modify the crontab of existing users, if they do not execute the "bncert" tool. We are considering different ways of communicating this issue to users, so they re-execute the tool.

Let us know if you have any concerns or questions! We really appreciate your inputs on this issue.

**Comment by mcpherrinm** [comment]
Thank you so much for the prompt fix!  I'll ask the lego authors to release a new version for you to update to.

I understand the complications around updating the bncert software and existing crontabs.  Hopefully as long as we can prevent more traffic piling on at the midnight peak, things at least won't get worse.

**Comment by marcosbc** [comment]
Thanks for letting us know! We have just released the "bncert" tool version 1.0.0, which includes the `4.8.0` version of `lego`, in addition to adding a user-agent to each `lego` call, e.g.:

```
35 1 * * * sudo /opt/bitnami/letsencrypt/lego ... --user-agent bitnami-bncert/1.0.0 renew && sudo /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -k graceful # bncert-autorenew
```

It would be great if you could confirm that you are now seeing metrics with the `bitnami-bncert/1.0.0` user agent on your side.

**Comment by mcpherrinm** [comment]
Thanks!  I've confirmed we are seeing some requests with that user agent now, and that they appear to be spread out over the day, and not participating in the "midnight peak".

**Comment by mcpherrinm** [comment]
> We are considering different ways of communicating this issue to users

Do you have any updates about possibly communicating with users? While this will prevent load from getting worse, we are still hitting overload conditions at midnight and it may take too long to allow natural upgrades, since I assume most users won't re-run bncert unless they have a good reason to.

We could provide a rate-limit with a custom error message server-side, but I didn't see any way that errors would be surfaced to users, so that wouldn't help much either.

**Comment by agomezmoron** [comment]
Hi @mcpherrinm ,

We are working on the publication of a blogpost explaining what happened, how this incident was handled from your side, Lego project side and Bitnami side and also explaining in a detailed way how to upgrade the bitnami-bncert tool.

Thanks
