### ISSUE TITLE
[LAMP] bn-cert tool did not renew certificate, how to diagnose why (any logging etc)?

### ISSUE THREAD

**Issue by tommybutter** [bitnami/vms#430]
### Describe your issue as much as you can

Server did not auto-renew it's certificate spontaneously after being successful many times in the past. Had to rerun BNCert tool to get it back, even then it did not initially like my email and I had to use a direct command with lego which I was advised to do to get it going and then BNCert would run again fine after that.

I am wondering if there is somewhere these events are logged so I can investigate, in particular why the previously consistent renewal did not execute.

Thank you for any help
-T

**Comment by jotamartos** [comment]
The bncert tool configures a cron job that takes care of renewing the certificate. You can get the cron's configuration by running these commands 

```
sudo crontab -l
sudo crontab -l -u bitnami
```

You will see a lego command listed there and you can run that command to renew the certificate whenever you want. To get more information about the issues, you can either redirect the output of the lego command to a file or check the system's log files when the cron job is executed.
