### ISSUE TITLE
[WAMP] PHP 7.4.8 issues

### ISSUE THREAD

**Issue by johnwick88667** [bitnami/vms#433]
### Describe your issue as much as you can

Name and Version
Bitnami WAMP Stack[ 7.4.8-0
](https://dailyclove.com/technology/monoprice-110010-headphones-a-great-value-for-your-money/)
What steps will reproduce the bug?
This is a periodic error that happens at random.

Are you using any custom parameters or values?
No

What is the expected behaviour?
When the error occurs the WAMP server becomes inaccessible until the server is restarted.

What do you see instead?
Faulting application name: httpd.exe, version: 2.4.43.0, time stamp: 0x5ea00a5d
Faulting module name: php7ts.dll, version: 7.4.8.0, time stamp: 0x5f0710ce
Exception code: 0xc0000005
Fault offset: 0x00000000000c550b
Faulting process id: 0x480
Faulting application start time: 0x01d8e60c38ee1f8a
Faulting application path: C:\WAMPST1\apache2\bin\httpd.exe
Faulting module path: C:\WAMPST1\apache2\bin\php7ts.dll
Report Id: 812bf6cf-30eb-4977-8f26-fa3bf33d8c97
Faulting package full name:
Faulting package-relative application ID:

Additional information
The WAMP install is running on Windows 10 Pro.

**Comment by gongomgra** [comment]
Hi @johnwick88667 ,

Thanks for using Bitnami and for reporting your issue. I found another ticket here for the same PHP version and issue. It looks like it is a known issue in the PHP binary. Please check the thread linked below.

https://github.com/bitnami/vms/issues/428

We are also closing this ticket as duplicated.
