### ISSUE TITLE
[Bitnami Lightstail] Installing multiple SSLs on single AWS Lightsail instance

### ISSUE THREAD

**Issue by dshevnock** [bitnami/vms#434]
### Describe your issue as much as you can

Is it possible to install multiple LE certs on a single AWS instance? 

If the answer is yes, do I simply follow the LE Cert install instructions I used to install the first cert or is there another set of instructions to follow?
- I have read some articles where the SSL certs can clash if not setup correctly on the server.

Also, if something doesn't go right when installing the second LE cert, do I follow the instructions at https://docs.bitnami.com/aws/how-to/understand-bncert/#manually-revoking-an-existing-certificate to revoke the second cert?

Here is the situation:
- I have installed a single LE cert on a few separate AWS instances before and have had no issues (but never setup multiple certs on the same server)
- We have a single AWS server instance
- We have a page (for email unsubscribing) that I want to make available on multiple domains (as a subdomain) so we have a central place where to manage code, etc.
- we already have a functioning LE wildcard subdomain that is working for domainA.com on the AWS server
- ideally, I want to install a second LE wildcard cert for domainB.com on the same AWS server instance
- so then I can setup https://unsubscribe.domainB.com and have that point to single AWS server instance
- you can assume I know how to setup the subdomain for domainB.com and have that point to AWS server

**Comment by mdhont** [comment]
Which application are you running?

**Comment by dshevnock** [comment]
@mdhont sorry, thought I replied the same day you asked. 

The server instance is LAMP (PHP 7)

**Comment by mdhont** [comment]
You can follow the steps in this guide, and apply it to different certificates:

https://docs.bitnami.com/ibm/infrastructure/lamp/administration/enable-https-ssl-apache/
