### ISSUE TITLE
[AWS NodeJS Stack] Not serving from VHOST Document Roots

### ISSUE THREAD

**Issue by zackrspv** [bitnami/vms#435]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3bfc775d-42ad-353b-d5dc-8d5bf3b40a22

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ✓ Apache: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

The sites are accessible, and the ports open automatically via AWS SG

### Describe your issue as much as you can

With our AWS Bitnami NodeJS stack, we have created a project in the '/opt/bitnami/projects' folder called 'FLOW-3'. 

In that folder, we have multiple frontends in the 'frontend' folder: 

frontend/dashboard
frontend/mm-front
frontend/qq-front

Server Output:
![image](https://user-images.githubusercontent.com/1069198/197645901-3d552757-5ca1-4a11-8405-6a86c299cc24.png)

The system builds each frontend when the application is updated in GitHub (various npm run build commands). 

The VHOSTS are configured as follows: 
![image](https://user-images.githubusercontent.com/1069198/197644913-6e6171f5-2d9d-4f0f-9ebf-6fd8f6144652.png)

Example: 
```
<VirtualHost *:80>
  ServerName my.soarlending.com
  DocumentRoot /opt/bitnami/projects/FLOW-3/frontend/dashboard
```

Example 2: 
```
<VirtualHost *:80>
  ServerName qual.soarlending.com
  DocumentRoot /opt/bitnami/projects/FLOW-3/frontend/qq-front
```

Example 3: 
```
<VirtualHost *:80>
  ServerName apply.soarlending.com
  DocumentRoot /opt/bitnami/projects/FLOW-3/frontend/mm-front
```

For each of the vhosts above, we have similar layouts, but we are using different DocumentRoots of course. 

The status of 'httpd -s' is: 
![image](https://user-images.githubusercontent.com/1069198/197646148-52011a32-61a1-4b13-84cf-4546b9a213e0.png)

The bitnami.conf is: 
![image](https://user-images.githubusercontent.com/1069198/197645419-c468d0b7-1d31-4521-bc95-5fe347f0936a.png)

However, when visiting any of the other domains (apply, my or qual), they all serve from the default vhost (00_soarlending-my-vhost.conf) in the frontend/dashboard directory instead of honoring the DocumentRoot for each vhost.

**Comment by zackrspv** [comment]
I decided to just get rid of the concept of using a separate vhosts directory, and just put all my vhosts directly within the bitnami.conf and bitnami-ssl.conf.  Doing that, worked w/o issue. 

Even though the httpd.conf does include all of the vhosts from the vhost directory, it doesn't HONOR what's in those vhosts directories. 

But, including everything in the bitnami.conf and bitnami-ssl.conf for all the vhosts worked perfectly.

**Comment by zackrspv** [comment]
However, that to me, means it's an issue w/ the default setup lol So I'm leaving this ticket open

**Comment by mdhont** [comment]
Did you check this guide?

https://docs.bitnami.com/aws/infrastructure/mean/administration/create-custom-application-nodejs/

**Comment by zackrspv** [comment]
Yes, i followed that guide, but it didn't help. Ultimately, I had to make it so that the VHOSTS were in the bitnami.conf file and not in the VHOSTS directory, even though they were being loaded. For some reason, it just wouldn't honor them. Now, everything works fine if just added to bitnami.conf and bitnami-ssl.conf
