### ISSUE TITLE
[Liferay] Can't access the app in Azure VM

### ISSUE THREAD

**Issue by kaithzhero** [bitnami/vms#436]
### Describe your issue as much as you can

![image](https://user-images.githubusercontent.com/66239650/197700166-a45e163b-9ff7-426e-9baa-0e6a428f04a2.png)

i created a VM bitnami liferay on azure , but when i start server , the page did't not working
what should i do ?

**Comment by jotamartos** [comment]
Hi @kaithzhero,

I do not know if you chose the correct requirements for the app to work properly. Please note it requires 8GB of RAM to work and the deployment may take several minutes. Please ensure you have enough memory and the deployment finishes before accessing the app.
