### ISSUE TITLE
[LAMP] How to upgrade PHP (Lightsail)

### ISSUE THREAD

**Issue by PavlosIsaris** [bitnami/vms#437]
### Describe your issue as much as you can

I have deployed a Laravel application under a LAMP installation for Bitnami, on a Lightsail VM instance.
I would like to upgrade PHP from version 7.4 to 8.0, in order to also upgrade to the next version of Laravel.
Is there a way to do so?

**Comment by mdhont** [comment]
Unfortunately upgrading individual components of Bitnami applications is not supported. I recommend launching a new instance with the latest component's version and then migrate the data.

**Comment by tgoeminne** [comment]
is there a way to update php version? I read its not possible have to make a new vm and move all files, redo all config, and so on... Really not convenient.

**Comment by gongomgra** [comment]
Hi @tgoeminne,

I'm afraid it is not possible. You will have to launch a fresh new image and migrate your application data there.

**Comment by tgoeminne** [comment]
any plans of changing this like update from 8.03 to 8.1. Relaunching and moving data take a lot of time.

**Comment by mdhont** [comment]
Unfortunately it's not on our roadmap to add this.
