### ISSUE TITLE
[WordPress NGINX SSL] Folder .well-known 403 Forbidden

### ISSUE THREAD

**Issue by giulianopires** [bitnami/vms#439]
### Describe your issue as much as you can

I am trying to add Apple Pay to my website and in Stripe a file is provided to add inside the .well-known folder. Btw all the attempts I had to authorize this folder and the file were in vain. I want to know how I can authorize this folder and the file so that Stripe and Apple can verify the Apple Pay file?

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.

**Comment by giulianopires** [comment]
Foi o que eu pensei. Certamente esse é um assunto relacionado a pilha Bitnami, só queria saber como poderia autorizar o arquivo. Depois de um tempo, você nunca mais atualizaram a documentação das pilhas e removeram a comunidade, se aqui não for o lugar adequado para eu fazer essa pergunta, vocês só estão querendo que as pessoas reportem os bugs para vocês corrigirem, ou seja, só vocês ganham.
Tratarei de utilizar a pilha do LiteSpeed, obrigado!

**Comment by alfredonuhe** [comment]
I might be too late, but in case it helps, I believe I know the source of the issue.

The file **/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf** configures the web server to redirect all **/.well-known** and **/.well-known/** requests to a location outside the document root as specified in **httpd.conf**. Therefore, any files placed in the directory **.well-known** under the document root won't be accessible.

The content of **httpd-prefix.conf**:
~~~
Alias /.well-known/ "/opt/bitnami/apps/letsencrypt/.well-known/"
Alias /.well-known "/opt/bitnami/apps/letsencrypt/.well-known"

Include "/opt/bitnami/apps/letsencrypt/conf/httpd-app.conf
~~~
