### ISSUE TITLE
[WordPress] Bitnami stack Install issue

### ISSUE THREAD

**Issue by sparkspnt** [bitnami/vms#441]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d8ebd741-7d64-6d64-cb91-b77b00630bf3

### bndiagnostic was not useful. Could you please tell us why?

never got any other output

### Describe your issue as much as you can

I have a clean install of Linux mint and Bitnami. upon installing, I did get an error, once click it finished but then I get error connecting to database. 

I have tried this on two clean installs of ubuntu and now Linux mint. I get the same error and issue on all three. I really don't know where to start on finding the issue as there was little required on installation. 

thanks ahead for your time 
sparkspnt

**Comment by sparkspnt** [comment]
![Image](https://user-images.githubusercontent.com/116833726/198363884-14dcda05-e5bf-46d1-b8e1-b19748ad9d69.jpeg)

This is the install error on all systems.

**Comment by gongomgra** [comment]
Hi @sparkspnt,

Thanks for using Bitnami. MariaDB depends on a system library to work properly, and it seems it is not installed by default on your system. Can you remove the WordPress installation using the uninstaller located at `INSTALLDIR/uninstaller.run`, then install the missing library running the command below on your system, and after that reinstalling the WordPress stack? 

```
sudo apt-get update && sudo apt-get install -y libtinfo5
```

According to [official Linux Mint website](https://community.linuxmint.com/software/view/libtinfo5), `libtinfo5` is the name of the package providing the missing library. Please install any other package providing that library in case `libtinfo5` is not the exact package name for your Linux Mint version.

**Comment by sparkspnt** [comment]
That fixed it!

Thank you!
sparkspnt

**Comment by gongomgra** [comment]
Hi @sparkspnt,

Thanks for letting us know. We are glad it fixed your issue!
