### ISSUE TITLE
[Solr Windows] : How to download installer for version 8.8.2-4-r06?

### ISSUE THREAD

**Issue by quentinconnan-betd** [bitnami/vms#443]
### Describe your issue as much as you can

Hello, 

I want to download the installer for Solr version 8.8.2-4-r06 to update an existing instance in an old server.
I get the version 8.4.0-0 from this link https://downloads.bitnami.com/files/stacks/solr/8.4.0-0/bitnami-solr-8.4.0-0-windows-x64-installer.exe, but for the 8.8.2 i've not it.

Thanks in advance for your help

**Comment by mdhont** [comment]
Unfortunateley we don't support any Windows installers starting from version 8.4.
