### ISSUE TITLE
[LMS] Much time subscription is pending

### ISSUE THREAD

**Issue by vporton** [bitnami/vms#445]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

none

### bndiagnostic was not useful. Could you please tell us why?

I didn't install it yet

### Describe your issue as much as you can

I am trying to install Bitnami LMS. Subscription is in pending state for a much time.

Maybe, it is because I chose Nano instance and the installation works slowly?

How to exit from this trap of half-subscribed state?

**Comment by mdhont** [comment]
You need to contact AWS support for that.
