### ISSUE TITLE
[WordPress] Can't run bncert using a PHP script

### ISSUE THREAD

**Issue by fullstack71** [bitnami/vms#447]
### Name and Version

bitnami/wordpress 6.0.2-1

### What steps will reproduce the bug?
```
### cmd : printf "www.codibu.info  codibu.info\ny\ny\nn\ny\nmaster@codibu.com \nY" | sudo /opt/bitnami/bncert-tool
```
when I run this command from the lightsail wordpress terminal
1. It installed the SSL certificate perfectly.
2. https://www.codibu.info/ 
3. Automatically redirect non-www to www
4. Automatically redirect HTTP to HTTPS
##When I run this command programmatically from my PHP project/script.
1. It installed the SSL certificate perfectly.
2. https://www.codibu.info
3. Not automatically redirect non-www to www
4. Not automatically redirect HTTP to HTTPS
So, I need your suggestion to resolve 7 and 8

### What is the expected behavior?

codibu.info should automatically redirect to https://www.codibu.info

### What do you see instead?

codibu.info not redirect to https://www.codibu.info

**Comment by jotamartos** [comment]
Hi @fullstack71,

I do not know why the PHP script doesn't work for you. If the tool works when running it in the command line, there should be something in your script. Please note that we do not provide this type of support so you will need to find a solution for this (you can create a bash script that accepts arguments and execute that script when running your PHP code).
