### ISSUE TITLE
[Wordpress] vhost.conf www redirect

### ISSUE THREAD

**Issue by ryt2n** [bitnami/vms#448]
### Describe your issue as much as you can

Hello,

I am using a Bitnami WordPress Approach A image on AWS Lightsail with Cloudfront.  
My SSL is enforced in Lightsail on Cloudfront, not on the initial server.  
I am using the WPML plugin with a .com domain for English and a .fr for French.

I want to redirect my non-www traffic to www on both the .com and the .fr.  I have followed the guide below, but my website has not changed its behaviour (I did reboot).
https://docs.bitnami.com/general/apps/redmine/administration/redirect-custom-domains/

The documentation mentions the following path /opt/bitnami/apache2/ while my apache2 folder is a shortcut to /opt/bitnami/apache/.  I don't think this is the issue, but I through I would point it out.

ORIGINAL vhost.conf
```
<VirtualHost 127.0.0.1:443 _default_:443>
  ServerAlias *
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
  DocumentRoot /opt/bitnami/wordpress
  <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
    # END WordPress
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
</VirtualHost>
```

WITH MY EDITS  vhost.conf
```
<VirtualHost 18.IP_ADDRESS.77:80 _default_:80>
    ServerName www.dearreal.com
    ServerAlias dearreal.com www.dearreal.fr dearreal.fr
  DocumentRoot /opt/bitnami/wordpress
  <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
    # END WordPress
    # BEGIN www redirect
    RewriteEngine On
    RewriteCond %{HTTP_HOST} !^www\. [NC]
    RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
    # END www redirect
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
</VirtualHost>
```

I have changed the IP address to the IP address of my server.  I am not sure where the IP original IP address comes from.  My best guess would be that this was an IP address for one of my original AWS setups that I have changed.

I would greatly appreciate any pointers.
Thanks;

**Comment by gongomgra** [comment]
Hi @ryt2n,

Thanks for using Bitnami. I updated your message to avoid sharing your public IP address. I also think it is not needed to update the `VirtualHost` line. Can you set it back to the previous state and then restart Apache for changes to take effect?

```
sudo /opt/bitnami/ctlscript.sh apache restart
```

I see you added the redirect configuration for non-www to www domain in the `vhost.conf` file (which I understand it is the `wordpress-vhost.conf` file). However, it looks like CloudFront is performing the HTTP to HTTPS redirect before reaching your WordPress website, so you will have to add the non-www to www redirect to the `wordpress-https-vhost.conf` file as well. Remember to restart Apache for changes to take effect

```
$ curl -LI "http://dearreal.com"
HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Mon, 31 Oct 2022 09:54:49 GMT
Content-Type: text/html
Content-Length: 167
Connection: keep-alive
Location: https://dearreal.com/
X-Cache: Redirect from cloudfront
Via: 1.1 4ec656d2dfbb59cd7fab2ac94a540522.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: IAD55-P3
X-Amz-Cf-Id: CNojWiWReNMX5a_8nIsxqVC0VXmbtvwhb0g-3n5XHuHy8bSJG882zA==

HTTP/2 200
content-type: text/html; charset=UTF-8
date: Mon, 31 Oct 2022 09:54:49 GMT
server: Apache/2.4.51 (Unix) OpenSSL/1.1.1n
x-powered-by: PHP/7.4.24
link: <https://dearreal.com/wp-json/>; rel="https://api.w.org/", <https://dearreal.com/wp-json/wp/v2/pages/160>; rel="alternate"; type="application/json", <https://dearreal.com/>; rel=shortlink
x-cache: Miss from cloudfront
via: 1.1 d252968c504ffe8fc53a565195348068.cloudfront.net (CloudFront)
x-amz-cf-pop: IAD55-P3
x-amz-cf-id: LIP3pTQiDNv4nJDYBPwK8tRac4SwZfzLSROkquCL7Velg76Pw9SFRg==
```

**Comment by ryt2n** [comment]
Hi Gongomgra,

Many thanks for your support.

I made changes to the wordpress-https-vhost.conf while did not post to GitHub as both files are very similar.

Many thanks for pointing out my mistake with the `VirtualHost` line.  I have now corrected it.  I have used your command line, but I was not sure the server had acknowledged it, so I also rebooted the server.

Many thanks for hiding my internal IP address too.

My redirect issues are still there.  Do let me know if you can think of anything :-D.

Best regards,
Henri

**Comment by ryt2n** [comment]
Hi Gongomgra,

I checked the Apache recommended config and tried to be creative. 
https://httpd.apache.org/docs/2.2/rewrite/remapping.html#canonicalhost
 I crashed the server and reverted.

`   # BEGIN www redirect
    <VirtualHost *:80>
      ServerName dearreal.com
      ServerAlias

      Redirect 301 / https://www.dearreal.com/
    </VirtualHost>
    <VirtualHost *:80>
      ServerName dearreal.fr
      ServerAlias

      Redirect 301 / https://www.dearreal.fr/
    </VirtualHost>
    # END www redirect`

FYI, I have also opened a ticket with AWS.  I will update you if anything works from there.

Best,
Henri

**Comment by gongomgra** [comment]
Hi @ryt2n,

Thanks for your message. I don't think those redirect directives are necessary. Can you remove them, update the WordPress URL as described in our guide below, and finally restart services? Notice you should configure WordPress with the final URL you want your domain to be reached, including the `https://` and `www` strings.

https://docs.bitnami.com/aws/apps/wordpress/administration/configure-domain/

Can you also set this final domain in the Apache config file? Instead of `RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]` try setting `RewriteRule ^(.*)$ https://www.dearreal.fr/%{REQUEST_URI} [R=301,L]` instead.

**Comment by ryt2n** [comment]
Many thanks for this @gongomgra,

Your new domain configuration setting has worked.
I have edited a pull request to the AWS LightSail documentation to take this into account on the following page (https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-editing-wp-config-for-distribution#configuring-non-https-wordpress-for-distribution).
Feel all grown-up while you deserve the credit.

I did set up your Apache config file edit `RewriteRule ^(.*)$ https://www.dearreal.fr/%{REQUEST_URI} [R=301,L]` while I did not notice any difference.  Is it correct that we use the .fr domain here and not the .com?  May I ask the purpose of it?

I have one issue left with http://dearreal.fr pointing at www.dearreal.com instead of www.dearreal.fr.  This is most likely an issue with the WPML plugin.  I have opened a ticket with them.  Do let me know if you can think of something.
https://wpml.org/forums/topic/non-www-redirect-to-www-secondary-language-url-domain/

My current best bet is that the answer lies here https://docs.bitnami.com/general/apps/wordpress/administration/use-htaccess/.  I have referenced the .htaccess in the /opt/bitnami/wordpress in my wordpress-htaccess.conf per bellow with no success.

/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf
`<Directory "/opt/bitnami/wordpress/wp-content/plugins/akismet">
  # Only allow direct access to specific Web-available files.
  
  # Apache 2.2
  <IfModule !mod_authz_core.c>
  	Order Deny,Allow
  	Deny from all
  </IfModule>
  
  # Apache 2.4
  <IfModule mod_authz_core.c>
  	Require all denied
  </IfModule>
  
  # Akismet CSS and JS
  <FilesMatch "^(form\.js|akismet\.js|akismet\.css)$">
  	<IfModule !mod_authz_core.c>
  		Allow from all
  	</IfModule>
  	
  	<IfModule mod_authz_core.c>
  		Require all granted
  	</IfModule>
  </FilesMatch>
  
  # Akismet images
  <FilesMatch "^logo-(a|full)-2x\.png$">
  	<IfModule !mod_authz_core.c>
  		Allow from all
  	</IfModule>
  	
  	<IfModule mod_authz_core.c>
  		Require all granted
  	</IfModule>
  </FilesMatch>

</Directory>

  # Reference to the vanilla WordPress htaccess
<Directory "/opt/bitnami/wordpress">
  <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
  </IfModule>
</Directory>`

/opt/bitnami/wordpress/.htaccess
`# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
`

Thank you!

**Comment by gongomgra** [comment]
Hi @ryt2n,

Thanks for your message. I'm glad it worked for you. I selected the `.fr` domain by mistake, without noticing you were specifying the `.com` domain in your `ServerName` directive. Please update the redirect lines with the `.com` domain and restart Apache for changes to take effect.

Regarding the htaccess question, notice that the htaccess files are disabled by default according to the Apache Software Foundation recommendations. You can get more information on how to update the `wordpress-htaccess.conf` file, or how to enable `.htaccess` files in the guide below

https://docs.bitnami.com/aws/infrastructure/lamp/administration/use-htaccess/
