### ISSUE TITLE
[Nodejs] Websocket with socket.io is not working

### ISSUE THREAD

**Issue by icybergenome** [bitnami/vms#449]
I am using AWS Lightsail VM with NodeJS bitnami. I used `bncert-tool` to set up https and I am using Vhosts for setting up a reverse proxy. My API endpoints are working fine, however websocket(`wss`) url is not working. In my local environment everything is working however when I deployed to my Bitnami server I am facing the aforementioned issue. Here are the configurations I have tried so far:
**/opt/bitnami/apache/conf/vhosts/sample-vhost.conf**
``` .conf
<VirtualHost 127.0.0.1:80 _default_:80>
  ServerName www.example.com
  ServerAlias *
  DocumentRoot /opt/bitnami/projects/sample
  # BEGIN: Configuration for letsencrypt
  Include "/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf"
  # END: Configuration for letsencrypt
  # BEGIN: Support domain renewal when using mod_proxy without Location
  <IfModule mod_proxy.c>
    ProxyPass /.well-known !
  </IfModule>
  # END: Support domain renewal when using mod_proxy without Location
  # BEGIN: Enable HTTP to HTTPS redirection
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^localhost
  RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
  RewriteCond %{REQUEST_URI} !^/\.well-known
  # RewriteCond %{REQUEST_URI}  ^/socket.io [NC]
  # RewriteCond %{QUERY_STRING} transport=websocket    [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteCond %{HTTP:Connection} upgrade [NC]
  RewriteRule /(.*)           wss://%{SERVER_NAME}/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
  # END: Enable HTTP to HTTPS redirection
  <Directory "/opt/bitnami/projects/sample">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
  </Directory>
  ProxyPass / http://localhost:8080/
  ProxyPassReverse / http://localhost:8080/

  # BEGIN: Support domain renewal when using mod_proxy within Location
  <Location /.well-known>
    <IfModule mod_proxy.c>
      ProxyPass !
    </IfModule>
  </Location>
  # END: Support domain renewal when using mod_proxy within Location
</VirtualHost>
```
Any help regarding this would be highly appreciated.

**Comment by jotamartos** [comment]
Hi @icybergenome,

Thank you for using Bitnami but this question is out of the scope of this support forum. Please note that you are running into issues when deploying your application on top of our solution. We suggest you take a look at the Apache documentation to know how to debug this issue. Please note that if you have several VirtualHosts configured with the asterisk (*) as ServerName/ServerAlias, it will just use one no matter how many you have. For this reason, you can disable the Bitnami's default virtual host in the configuration by commenting the line in the httpd.conf file so you only have your virtual host.
