### ISSUE TITLE
[WordPress] PHP version not updated after creating new PHP 7 instance

### ISSUE THREAD

**Issue by rhastingsNEKLS** [bitnami/vms#452]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

not-able-to-get-the-number - it keeps dying on me...

### bndiagnostic was not useful. Could you please tell us why?

The site isn't actually not working properly with the old version of PHP, it just isn't seeing version 7

### Describe your issue as much as you can

I have created an instance of WP and PHP 7.1 a while back, based on an instance I was previously running with PHP 5. I've done this in the past, rather than do backups and migrate, because I'm running something like 40 sites on that server and cannot have them all down long enough to make that process work, not to mention the issues with 40 backups and migrations, so what I've done in the past is create a new instance of the updated php based on the snapshot of the previous instance and moved the IP address to the new version and, in the past, that has worked, the WP and apache software started using the PHP 7 version. For this one server, though, it's not working - it's still seeing PHP 5 and I'm not sure how to move the pointers or files to ensure that apache reads the PHP 7 information rather than the old PHP 5 info. Any tips for how to make that happen?

**Comment by jotamartos** [comment]
Hi @rhastingsNEKLS ,

>so what I've done in the past is create a new instance of the updated php based on the snapshot of the previous instance

If you take a snapshot of your instance and launch it, you will continue using the same PHP version, there is not any upgrade there. You should have performed additional steps to upgrade PHP. 

Please note that the directory structure changed some time ago that's something to consider 

https://docs.bitnami.com/general/faq/get-started/understand-directory-structure/

You have 2 options: 

- Use a plugin to migrate your sites. For example you can use the All in One WordPress Migration plugin
- Launch a new instance with the new directory structure and migrate a database's backup (you just need to migrate the bitnami_wordpress database) and the files of your current WordPress deployment. Remember that you will need to set the permissions correctly (more info [here](https://github.com/bitnami/vms/issues/22#issuecomment-1143906974))
