### ISSUE TITLE
[WordPress with NGINX] WordPress Permission Error

### ISSUE THREAD

**Issue by lddd** [bitnami/vms#453]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

21bd9c24-ed19-a8c3-7d17-c9f929e96431

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are not related with my issues

### Describe your issue as much as you can

Hello,

i am having trouble updating or installing a new plugin to my bitnami wordpress installation. 

I keep getting the following error message by wordpress:

_"Update Failed: The update could not be installed because some files could not be copied. This is mostly due to inconsistent file permissions."_

Wordpress is installed in "/opt/bitnami/wordpress/"

What i did already:

```
sudo chown -R bitnami:daemon TARGET
sudo find /opt/bitnami/wordpress/ -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress/ -type f -exec chmod 664 {} \;
sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
```

I also restarted Nginx & PHP-FPM. 

What else there is that could cause trouble?

thanks in advance

**Comment by jotamartos** [comment]
You need to set the correct permissions in both /opt/bitnami/wordpress and /bitnami/wordpress folders. Please take a look at this post 

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

**Comment by lddd** [comment]
> 

Thanks a lot. That fixed it :)
