### ISSUE TITLE
[Wordpress] bncert-tool issues on AWS lightsails

### ISSUE THREAD

**Issue by muznz** [bitnami/vms#454]
### Describe your issue as much as you can

Hi There,
I have a Bitnami Wordpress on AWS lightsails and have always been able to renewed the https// certifcate successfully using the [sudo /opt/bitnami/bncert-tool] command with Putty and following the instructions after that. But now I can't. I get the following response. "Please type a directory that contains a Bitnami installation" Which I have done but it seems to reject this. Please help. See attached responce from Putty.
Thanks...............Murray  

![AWS Bitnami Wordpress bncert-tool https](https://user-images.githubusercontent.com/18178210/199381687-6add0a9a-3ec1-4a2a-b407-c76a55351431.jpg)

**Comment by gongomgra** [comment]
Hi @muznz,

Thanks for using Bitnami. We would need more information to try to help you with your issue. Can you run the bndiagnostic tool and share the generated code with us? Please paste the code directly in your reply, not a screenshot.

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by muznz** [comment]
This is repeat of my last comment. Don't know why it is striking out the diagnostic command and response saying command not found

Last login: Wed Nov  2 20:44:11 2022 from 125.236.151.233
bitnami@ip-172-26-0-116:~$ sudo /opt/bitnami/bndiagnostic-tool
sudo: /opt/bitnami/bndiagnostic-tool: command not found
bitnami@ip-172-26-0-116:~$

**Comment by muznz** [comment]
Hi Gongomgra,

I have run the 3 commands as follows.......................

bitnami@ip-172-26-0-116:~$ ls -larth /opt/bitnami
total 3.5M
-rwx------  1 root    root    3.3M Aug 27  2019 manager-linux-x64.run
-rw-r--r--  1 root    root     754 Apr 15  2020 bnsupport-regex.ini
drwxr-xr-x 10 root    root    4.0K Jun 15  2020 common
drwxr-xr-x  2 root    root    4.0K Jun 15  2020 bnhelper
lrwxrwxrwx  1 root    root      50 Jun 15  2020 bnhelper-tool -> /opt/bitnami/bnhelper/bnhelper-0.1.0-linux-x64.run
drwxr-xr-x  5 root    root    4.0K Jun 15  2020 sqlite
drwxr-xr-x  9 root    root    4.0K Jun 15  2020 varnish
-rwxr-xr-x  1 root    root     41K Jun 15  2020 ctlscript.sh
drwxr-xr-x  2 root    root    4.0K Jun 15  2020 img
drwxr-xr-x  2 root    root    4.0K Jun 15  2020 licenses
lrwxrwxrwx  1 root    root      52 Jun 15  2020 bnsupport-tool -> /opt/bitnami/bnsupport/bnsupport-0.9.1-linux-x64.run
drwxr-xr-x  4 root    root    4.0K Jun 15  2020 config
-rwxr--r--  1 root    root     308 Jun 15  2020 use_wordpress
drwxr-xr-x 12 root    root    4.0K Jun 15  2020 php
drwxr-xr-x 14 root    root    4.0K Jun 15  2020 apache2
-rw-r--r--  1 root    root     13K Jun 15  2020 README.txt
-rw-r--r--  1 root    root     31K Jun 15  2020 changelog.txt
drwxr-xr-x  3 root    root    4.0K Jun 15  2020 scripts
drwxr-xr-x  3 root    root    4.0K Jun 15  2020 bnsupport
drwxr-xr-x  7 root    root    4.0K Aug  9  2020 var
drwxr-xr-x 11 root    root    4.0K Aug  9  2020 mysql
drwxr-xr-x  4 root    root    4.0K Aug 11  2020 ..
drwxr-xr-x  5 bitnami root    4.0K Mar 15  2021 letsencrypt
drwxr-xr-x  6 root    root    4.0K Feb 22  2022 apps
lrwxrwxrwx  1 root    root      46 Oct 16 22:33 bncert-tool -> /opt/bitnami/bncert/bncert-1.0.2-linux-x64.run
drwxr-xr-x 19 root    root    4.0K Oct 16 22:33 .
-rwxrwx---  1 bitnami root    1.9K Oct 17 21:54 properties.ini
drwxr-xr-x  2 root    root    4.0K Nov  2 02:04 bncert
drwxr-xr-x  2 bitnami bitnami 4.0K Nov  3 21:37 stats
bitnami@ip-172-26-0-116:~$

bitnami@ip-172-26-0-116:~$ ls -larth /opt/bitnami/wordpress
ls: cannot access '/opt/bitnami/wordpress': No such file or directory
bitnami@ip-172-26-0-116:~$

bitnami@ip-172-26-0-116:~$ ls -larth /bitnami
ls: cannot access '/bitnami': No such file or directory
bitnami@ip-172-26-0-116:~$

Look forward to hearing back. Thanks Murray

**Comment by muznz** [comment]
I have downloaded and installed diagnostic tool as follows.................

bitnami@ip-172-26-0-116:~$ wget -O bndiagnostic-linux-x64.run https://downloads.bitnami.com/files/bndiagnostic/latest/bndiagnostic-linux-x64.run
--2022-11-03 22:42:06--  https://downloads.bitnami.com/files/bndiagnostic/latest/bndiagnostic-linux-x64.run
Resolving downloads.bitnami.com (downloads.bitnami.com)... 13.224.174.26, 13.224.174.47, 13.224.174.64, ...
Connecting to downloads.bitnami.com (downloads.bitnami.com)|13.224.174.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30060518 (29M) [binary/octet-stream]
Saving to: ‘bndiagnostic-linux-x64.run’

bndiagnostic-linux-x64.run        100%[============================================================>]  28.67M  10.3MB/s    in 2.8s

2022-11-03 22:42:10 (10.3 MB/s) - ‘bndiagnostic-linux-x64.run’ saved [30060518/30060518]

bitnami@ip-172-26-0-116:~$ sudo mkdir /opt/bitnami/bndiagnostic
bitnami@ip-172-26-0-116:~$ sudo mv bndiagnostic-linux-x64.run /opt/bitnami/bndiagnostic/
bitnami@ip-172-26-0-116:~$ sudo chmod +x /opt/bitnami/bndiagnostic/bndiagnostic-linux-x64.run
bitnami@ip-172-26-0-116:~$ sudo ln -s /opt/bitnami/bndiagnostic/bndiagnostic-linux-x64.run /opt/bitnami/bndiagnostic-tool
bitnami@ip-172-26-0-116:~$

**Comment by muznz** [comment]
I have run the newly installed diagnostic tool as follows...............

bitnami@ip-172-26-0-116:~$ sudo /opt/bitnami/bndiagnostic-tool
----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

The diagnostic bundle file was successfully created, but the automatic upload to Bitnami servers failed. You will need to upload it to your Bitnami Support ticket manually. Please locate the following file in your file browser or in your terminal: /tmp/bitnami-wordpress-info-20221103-230130-28146.zip Exercise caution when uploading the resulting diagnostic bundle to public sites as it contains detailed diagnostic information.bitnami@ip-172-26-0-116:~$

**Comment by muznz** [comment]
Currently trying to find this file on my Windows 10 PC.................

bitnami-wordpress-info-20221103-230130-28146.zip

No luck so far using file explorer

**Comment by muznz** [comment]
Yay - I have found and attached diagnostic bundle file -
[bitnami-wordpress-info-20221103-230130-28146.zip](https://github.com/bitnami/vms/files/9933910/bitnami-wordpress-info-20221103-230130-28146.zip)

Please let me know if you require more tests to be done at my end. Kind regards Murray

**Comment by gongomgra** [comment]
Hi @muznz,

Thanks for the info. Unfortunately, the bndiagnostic tool couldn't get any information from your server.

```
-----------------------------------
Get the ctlscript status
-----------------------------------
Running: ./ctlscript.sh status
In: /opt/bitnami
Error:
Exitcode:
```

This is usually a symptom of a server running out of resources (which is likely causing the bncert-tool error as well). Can you run the next commands on your server and share the output with us?

```
sudo df -h
sudo free -m
sudo uptime
```

**Comment by muznz** [comment]
Hi Gongomgra,

I have run the 3 commnds as follows............

bitnami@ip-172-26-0-116:~$ sudo df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            233M     0  233M   0% /dev
tmpfs            49M  5.2M   43M  11% /run
/dev/xvda1       20G  5.6G   13G  31% /
tmpfs           241M     0  241M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           241M     0  241M   0% /sys/fs/cgroup
/dev/xvda15     124M  278K  124M   1% /boot/efi
tmpfs            49M     0   49M   0% /run/user/1000
bitnami@ip-172-26-0-116:~$

bitnami@ip-172-26-0-116:~$ sudo free -m
              total        used        free      shared  buff/cache   available
Mem:            481         166          76          86         238         216
Swap:           634         452         182
bitnami@ip-172-26-0-116:~$

bitnami@ip-172-26-0-116:~$ sudo uptime
 03:00:03 up 18 days,  5:06,  1 user,  load average: 0.00, 0.02, 0.00
bitnami@ip-172-26-0-116:~$

I hope this helps solve the problem. Thanks Murray

**Comment by gongomgra** [comment]
Hi @muznz,

Thanks for sharing this info with us. Your server is clearly running out of memory, and that's why both the bndiagnostic and the bncert tools didn't work. Please increase your instance type to one with more resources and then run the bncert tool again.

**Comment by muznz** [comment]
Hi Gongomgra,

Thanks for update. My current instance is as follows..............
![Current Instance](https://user-images.githubusercontent.com/18178210/200271260-50bdde08-aa0c-42a8-a9f9-8698069bbf08.jpg)

Currently: 
512MB RAM 
1 VCPU
20 GB SSD

Should I increase RAM or CPU or SSD. Or should I increase them all.

Please advise. Thanks...................Murray

**Comment by gongomgra** [comment]
Hi @muznz,

Usually when you change the instance type, you change CPU and memory values (either both of them or only one, depending on your election). I don't think you need to update your disk space according to the results of the commands you shared.

Regarding AWS Lightsail, you can get more information on how to change the instance type in the official documentation linked below

https://aws.amazon.com/premiumsupport/knowledge-center/change-lightsail-plan/

**Comment by muznz** [comment]
Hi Gongomgra,
Thanks for your help so far. I increased the resources with a stronger instance as shown in image below. But still having the same problem. I ran the diagnotic tool on the stronger instance and the results are shown below. What should I try next?
Please advise.
Thanks................Murray

bitnami@ip-172-26-1-182:~$ sudo /opt/bitnami/bndiagnostic-tool
----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.
---------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y
\-
The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:
===== Begin of bndiagnostic tool output =====

   ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ? Mysql: Found possible issues
    ✓ Processes: No issues found
    ? Php: Found possible issues



[Apache]

Found recent Pagespeed related error messages in the Apache error log:
```
[Wed Nov 09 03:34:13.988737 2022] [pagespeed:error] [pid 4515:tid
140356570048256] [mod_pagespeed **ip_address**-0 @4515] PageSpeed Serf fetch
failure rate extremely high; only 0 of 128 recent fetches fully successful; is
fetching working?

```
Press [Enter] to continue:
We suggest disabling pagespeed and check if that improves the behavior. Please
check the following guide to disable Pagespeed:

https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespe
ed/#disable-pagespeed

Found recent error or warning messages in the Apache error log.
```
[Tue Nov 08 19:30:42.204247 2022] [pagespeed:warn] [pid 1647:tid
140356553262848] [mod_pagespeed **ip_address**-0 @1647] CSS parsing error in
https://3.104.224.114/
 [Tue Nov 08 21:03:56.152644 2022] [pagespeed:warn] [pid 1647:tid
140356553262848] [mod_pagespeed **ip_address**-0 @1647] CSS parsing error in
https://3.104.224.114/
 [Wed Nov 09 00:29:04.099144 2022] [pagespeed:warn] [pid 4515:tid
140356561655552] [mod_pagespeed **ip_address**-0 @4515] CSS parsing error in
https://3.104.224.114/

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
Press [Enter] to continue:
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 987 565 76 145 345 125 Swap:
634 262 372
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
![Extra Resources](https://user-images.githubusercontent.com/18178210/200737933-53198c2c-401a-43b4-82cd-e329ab34c7d6.jpg)

[Mysql]

Found recent error messages in the MySQL error log:
```
2022-11-08T12:08:08.892625Z 1 [ERROR] [MY-012574] [InnoDB] Unable to lock
./ibdata1 error: 11

```
Please check the following guide to troubleshoot MySQL issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ysql/
Press [Enter] to continue:

[Php]

The following error appears in the
/opt/bitnami/php/var/log/php-fpm.log:
```
[08-Nov-2022 19:30:32] WARNING: [pool www] server reached max_children setting
(5), consider raising it

```
This error usually indicates PHP script execution is slow due to busy server
resouces or buggy scripts. Please check the following guide to increase the
number of PHP-FPM child processes:

https://docs.bitnami.com/general/apps/wordpress/configuration/configure-ph
pfpm-processes/

===== End of bndiagnostic tool output =====

**Comment by muznz** [comment]
Please see previous comment. Also here is code for support ticket:

Press [Enter] to continue:===== End of bndiagnostic tool output =====                                                                The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

85c09c63-8eb7-66fc-0827-93aab94699db

And paste it in your Bitnami Support ticket.

**Comment by gongomgra** [comment]
Hi @muznz,

Thanks for the updated info. According to the information you shared, your server is still missing resources to attend the requests to your website. Additionally, checking the bndiagnostic data, I found out the processes using more memory are Apache and MariaDB database.

```
-----------------------------------
Check memory usage for all current processes
-----------------------------------
Running: ps -e -orss=,args= | sort -b -k1,1n | awk '{print $1,$2}'
In: /opt/bitnami

Output:
(...)
16000 /opt/bitnami/apache2/bin/httpd.bin
32116 /opt/bitnami/apache2/bin/httpd.bin
56592 /opt/bitnami/apache2/bin/httpd.bin
63592 /opt/bitnami/apache2/bin/httpd.bin
155656 /opt/bitnami/mysql/bin/mysqld.bin
````

This usually means that you are getting a lot of requests to your server, or that your requests take too long to be processed. I also see you have very big MariaDB's `binlog` files, which means that your website performs a lot of database requests, consuming resources and eating up your disk space (these files log the database requests)

```
mysql/data:
total 2199380
drwxr-x---  7 mysql root       12288 Nov  8 19:27 .
drwxr-xr-x 11 root  root        4096 Aug  9  2020 ..
-rw-r-----  1 mysql root          56 Jun 15  2020 auto.cnf
-rw-r-----  1 mysql mysql 1075538086 Nov  1 21:59 binlog.000216
-rw-r-----  1 mysql mysql   11721670 Nov  1 22:11 binlog.000217
-rw-r-----  1 mysql mysql  367679342 Nov  4 21:45 binlog.000218
-rw-r-----  1 mysql mysql  576941047 Nov  8 12:08 binlog.000219
-rw-r-----  1 mysql mysql   23782987 Nov  8 19:27 binlog.000220
-rw-r-----  1 mysql mysql    7801082 Nov  9 04:00 binlog.000221
```

Getting these huge binlog files can be caused by some plugins using the database for temporal storage. You can take a look into those binlog files to identify what's happening by following the official guide below

https://dev.mysql.com/doc/refman/8.0/en/mysqlbinlog.html

**IMPORTANT NOTE**: do NOT remove binlog files directly from your server, or your database won't be able to start.

**Comment by muznz** [comment]
Hi Gongomgra,
Thanks for your interpretation and suspicion that a plugin could be causing the problem. When I looked more closely at my plugins I noticed a warning on the Woocommerce Plugin that it was out of date and could not be updated because my PHP was an old version and needed to be updated before my Woocommerce Plugin could be updated.  So I followed the instructions on the following link >> https://www.jaredmitcham.com/update-php-version-bitnami-wordpress/ to update my PHP. Once I had done this I was able to update the Woocommerce plugin.  I then entered the sudo /opt/bitnami/bncert-tool command (which was my initial problem) and was able to create a https:// certificate successfully.
So my plan now is to wait a few days for things to settle down and then run the Diagnostic Tool  to see if things have improved. I will keep you posted.
Cheers Murray

**Comment by gongomgra** [comment]
Hi @muznz,

Thanks for letting us know. We will move the ticket to pending until you get more information.

**Comment by muznz** [comment]
Hi Gongomgra,
My site seems to be working fine now. 
I ran the diagnostic tool again and got what appear to be be some minor issues below. Except for a shortage of RAM which I will fix by upgrading my plan.
Diagnostic bundle for this run was uploaded successfully. Ref: cc6e5fbe-eb91-0501-8596-5065241dbc59
Thanks...................Murray

The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:


===== Begin of bndiagnostic tool output =====


    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found



[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 472 332 7 59 132 67 Swap: 634
473 161
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
Press [Enter] to continue:

[Wordpress]

Some files don't have the expected permissions Please check the following guide:

https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

Found recent WordPress plugin related error messages in the Apache error log.
```
[Mon Nov 14 10:13:55.227722 2022] [proxy_fcgi:error] [pid 55301:tid
139694440261376] [client **ip_address**:41590] AH01071: Got error 'PHP message:
PHP Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type
string is deprecated in
/bitnami/wordpress/wp-content/plugins/wordfence/lib/wfScanEngine.php on line
2008PHP message: PHP Deprecated: http_build_query(): Passing null to parameter
#2 ($numeric_prefix) of type string is deprecated in
/opt/bitnami/wordpress/wp-includes/Request
```
Please check the following guide to deactivate plugins:

https://developer.wordpress.org/cli/commands/plugin/deactivate/

Press [Enter] to continue:
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Nov 15 19:15:45.603360 2022] [proxy_fcgi:error] [pid 78136:tid
139694582937344] [client **ip_address**:51742] AH01071: Got error 'PHP message:
WordPress database error Deadlock found when trying to get lock; try restarting
transaction for query DELETE FROM `wp_options` WHERE `option_name` =
'_transient_wposes_doing_cron_check' made by require('wp-blog-header.php'),
require_once('wp-load.php'), require_once('/bitnami/wordpress/wp-config.php'),
require_once('wp-settings.php'), do_action('wp_l [Tue Nov 15 19:15:48.711362
2022] [proxy_fcgi:error] [pid 77850:tid 139694381512448] [client
**ip_address**:51788] AH01071: Got error 'PHP message: WordPress database error
Deadlock found when trying to get lock; try restarting transaction for query
DELETE FROM `wp_options` WHERE `option_name` =
'_transient_wposes_doing_cron_check' made by require('wp-blog-header.php'),
require_once('wp-load.php'), require_once('/bitnami/wordpress/wp-config.php'),
require_once('wp-settings.php'), do_action('wp_l [Wed Nov 16 04:09:56.992208
2022] [proxy_fcgi:error] [pid 78136:tid 139694440261376] [client
**ip_address**:33036] AH01071: Got error 'PHP message: PHP Deprecated: Return
type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with
ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange]
attribute should be used to temporarily suppress the notice in
Press [Enter] to continue:
/opt/bitnami/wordpress/wp-includes/Requests/Cookie/Jar.php on line 63PHP
message: PHP Deprecated: Return
```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/


===== End of bndiagnostic tool output =====


Press [Enter] to continue:                                                                                                           The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

cc6e5fbe-eb91-0501-8596-5065241dbc59

And paste it in your Bitnami Support ticket.
bitnami@ip-172-26-5-86:~$

**Comment by muznz** [comment]
Hi Gongomgra,

I identified the IP's of the bots giving trouble and have blocked them. Thanks.

Then I was following bitnami instructions to disable wp-cron.php but somehow I made a mistake and now my site is down. I made the change on the wp-configure.php but somehow I uploaded the config file to the wrong place and now my site is saying "Service Unavailable"

I'm confused about where the config file should be uploaded to. I think here opt/bitnami/wordpress/wp-config.php but I'm confused about the short cut folder.

Please advise my best course of action. Thanks............Murray

![corrupted wp-config php](https://user-images.githubusercontent.com/18178210/202826079-57a8a2f6-8c8e-487a-94f8-10bdbe8851e6.jpg)

**Comment by muznz** [comment]
Please see previous. This is where I uploaded the config file
![This is the location I uploaded the config file](https://user-images.githubusercontent.com/18178210/202826616-aaae1e21-9adf-473a-a25c-bb07af098b27.jpg)

**Comment by muznz** [comment]
See previous 2 posts. This is the message I'm getting..................
![message](https://user-images.githubusercontent.com/18178210/202826957-17c31365-a2b6-4a8b-977c-0bf2d67df9a7.jpg)

**Comment by muznz** [comment]
See previous 3 posts. I ran diagnostic tool and bundle code is:  a80474a5-6e6c-c07b-00c2-c894d32cac9b. I think the serious problem which has brought up the 503 code and taken down my sites is the Apache error. I would very much like to focus on this at the moment to get my website running again which is:

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat Nov 19 07:09:38.025054 2022] [proxy_fcgi:error] [pid 128208:tid
Press [Enter] to continue:
139930210649856] [client **ip_address**:55245] AH01079: failed to make
connection to backend: httpd-UDS
 [Sat Nov 19 07:12:41.679397 2022] [proxy:error] [pid 128568:tid
139930193864448] (2)No such file or directory: AH02454: FCGI: attempt to connect
to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Sat Nov 19 07:12:41.680101 2022] [proxy_fcgi:error] [pid 128568:tid
139930193864448] [client **ip_address**:53394] AH01079: failed to make
connection to backend: httpd-UDS

Thanks.............................Murray

**Comment by muznz** [comment]
Hi Gongomgra,

Please ignore my last 4 posts regarding "Service Unavailable" I tried rebooting my instance and now everything is back to normal. I will get back to you again regards troublesome Bots once I've had a chance to investgate further.

Thanks.................Murray

**Comment by gongomgra** [comment]
Hi @muznz,

Thanks for letting us know. We are moving the ticket back to pending.
