### ISSUE TITLE
Install LAMP into redhat 8.6

### ISSUE THREAD

**Issue by srjaba** [bitnami/vms#456]
### Describe your issue as much as you can

If I install a LAMP package it shows me the following:  Bitnami installers do not support Fedora 32, CentOS 8, RHEL 8 or any newer version of those distributions.  In redhat 8

**Comment by gongomgra** [comment]
HI @srjaba,

Thanks for using Bitnami. Unfortunately, it is not possible to run our installers in RedHat Enterprise Linux 8 (RHEL 8). You can use our virtual machine (`.ova` format) with your preferred virtual machines hypervisor

https://bitnami.com/stack/lamp/virtual-machine

**Comment by srjaba** [comment]
In the future it will be possible to install LAMP on redhat 8 or higher.

**Comment by srjaba** [comment]
In the future it will be possible to install LAMP on redhat 8 or higher.

**Comment by srjaba** [comment]
In the future it will be possible to install LAMP on redhat 8 or higher.

**Comment by gongomgra** [comment]
Hi @srjaba,

Unfortunately, this is not in our roadmap right now. You will have to follow the alternative of using the virtual machine.

**Comment by srjaba** [comment]
Ok, thanks!!

**Comment by gongomgra** [comment]
Hi @srjaba,

Thanks for your message. We are closing this ticket now. Do not hesitate to open a new ticket with any other question you may have.
