### ISSUE TITLE
[SonarQube] How to Update to latest Software Version

### ISSUE THREAD

**Issue by monigala** [bitnami/vms#457]
### Describe your issue as much as you can

We are using "SonarQube packaged by Bitnami" AMI Subscription from AWS Marketplace. How do you upgrade software versions while running same instance and retaining all data (users/projects/settings/etc)?? What are the specific steps to accomplish this?

## New Version (9.7)
![marketplace_launch_instance_newer_software_version](https://user-images.githubusercontent.com/9090923/199608346-54be2afd-d0e9-420b-b9e6-95d67afec80e.png)

## Our Version (9.5)
![sonarqube_new_version_available](https://user-images.githubusercontent.com/9090923/199608701-9df232a8-42b8-4e01-9fd5-642eefaf4305.png)

Love this product btw!

**Comment by jotamartos** [comment]
You can find more information about how to upgrade the solution in our documentation:

https://docs.bitnami.com/aws/apps/sonarqube/administration/upgrade/

**Comment by monigala** [comment]
Thank you @jotamartos. I will check out the documentation.
