### ISSUE TITLE
[Bitnami Wordpress] <how to upgrade from old version azure bitnami wordpress>

### ISSUE THREAD

**Issue by cp-adisorn** [bitnami/vms#458]
### Describe your issue as much as you can

I try to create new azure bitnami Wordpress (default 6.0.3 now) that not support php7.
So, I remove the /opt/bitnami folder after stop service, then download and install linux installer "bitnami Wordpress 5.8.1"
Is that correct?

**Comment by gongomgra** [comment]
Hi @cp-adisorn,

Thanks for using Bitnami. If you need to run a WordPress version with PHP 7 support, then yes, you can launch our image, stop the services, remove the `/opt/bitnami` folder, and then install the Bitnami WordPress stack into that directory. We recommend you to install it using `sudo` to be able to use Apache privileged default ports (80 and 443).

```
sudo ./installer.run
```
