### ISSUE TITLE
[WordPress with NGINX and SSL packaged by Bitnami] <Need Help in Configuring Converter for Media – Optimize images | Convert WebP & AVIF Plugin>

### ISSUE THREAD

**Issue by vgnavada** [bitnami/vms#459]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

eb296f5d-f752-6182-dcf6-b40720a8afd1

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Nginx: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2022/11/03 08:48:44 [error] 7140#7140: *679045 FastCGI sent in stderr: "PHP 
message: PHP Warning: Undefined array key "excluded_urls" in 
/bitnami/wordpress/wp-content/plugins/super-progressive-web-apps/public/manifest.
php on line 252" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET /category/agriculture/feed/ HTTP/1.1", 
Press [Enter] to continue:
upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"tamil.newsnext.live"
 2022/11/03 08:48:46 [error] 7140#7140: *679051 FastCGI sent in stderr: "PHP 
message: PHP Warning: Undefined array key "excluded_urls" in 
/bitnami/wordpress/wp-content/plugins/super-progressive-web-apps/public/manifest.
php on line 252" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET /category/court-news/feed HTTP/1.1", 
upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"tamil.newsnext.live"
 2022/11/03 08:48:47 [error] 7140#7140: *679053 FastCGI sent in stderr: "PHP 
message: PHP Warning: Undefined array key "excluded_urls" in 
/bitnami/wordpress/wp-content/plugins/super-progressive-web-apps/public/manifest.
php on line 252" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET /category/court-news/feed/ HTTP/1.1", 
upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"tamil.newsnext.live"

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

Press [Enter] to continue:
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3901 1912 180 184 1808 1529 
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Something else

### Describe your issue as much as you can

We are trying to install **_"Converter for Media – Optimize images | Convert WebP & AVIF"_** plugin.

It is asking us to change the NGNIX config.
I followed the steps mentioned in their FAQ: https://wordpress.org/plugins/webp-converter-for-media/#configuration%20for%20nginx

But I could not find the files in the paths mentioned by them.

Could you please guide me on where exactly can i find the cond.d and mime.types file in the server?

Awaiting your response...

**Comment by mdhont** [comment]
You can find all Bitnami Nginx configuration related guides here:

https://docs.bitnami.com/aws/infrastructure/nginx/configuration/

**Comment by vgnavada** [comment]
Hello @mdhont ,

I have successfully been able to add the first part of the config rules.

Where do I add the mime.types rules?
![image](https://user-images.githubusercontent.com/113204610/199735530-b772363f-7b73-44a1-8bc0-d6f54a1f4f9e.png)

Could you please help?

**Comment by mdhont** [comment]
You can add them to the http section of the `/opt/bitnami/nginx/conf/nginx.conf` file.

**Comment by vgnavada** [comment]
Hello @mdhont ,

I did as you suggested, I added them here:

![image](https://user-images.githubusercontent.com/113204610/200121059-59173397-1bd4-41e5-913f-6b1f89368acb.png)


But when restarting the server, Got this error:

![image](https://user-images.githubusercontent.com/113204610/200121039-5c88c3f3-bc6d-4a0b-a083-9801d1475a86.png)

Did I do something wrong? Could you please educate me?

PS: I have removed those newly added lines & restarted again, The system restarted without any error/warning.

**Comment by mdhont** [comment]
I think you need to add them as follows:

```
http: { 

map $http_accept $webp_suffix {
    default "";
    "~*webp" ".webp";
}
```

In any case, I recommend checking the official Nginx documentation for the correct syntax.
