### ISSUE TITLE
[<Wordpress Bitnami>] <EBS storage 30GB is used fully when I have only 7 10 web pages>

### ISSUE THREAD

**Issue by Ahmedsaleem54** [bitnami/vms#46]
### Describe your issue as much as you can

Why does my EBS storage of 30 GB is almost full, when I have only 10 web pages, What is wrong with the bitnami? I have another website on Digital Ocean and it has 100+ web pages and storage is only 8 GB used. Please help

**Comment by jotamartos** [comment]
Please note that the plugins/themes you are using may be using the database intensively and that uses space in the disk. You can use the `df` and `du` commands of this guide to get more info about the disk usage. 

Thank

**Comment by Ahmedsaleem54** [comment]
Filesystem      Size  Used Avail Use% Mounted on
udev            485M     0  485M   0% /dev
tmpfs            99M   12M   88M  12% /run
/dev/xvda1       30G  3.0G   26G  11% /
tmpfs           494M     0  494M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           494M     0  494M   0% /sys/fs/cgroup
/dev/xvda15     124M  278K  124M   1% /boot/efi
tmpfs            99M     0   99M   0% /run/user/1000

This is what came when I used the (df -h) command to check dish space. So Basically I have used only 3 G disk space? Then why does AWS sent me an email that I have used 85% of the Elastic block storage?

**Comment by jotamartos** [comment]
Hi @Ahmedsaleem54 ,

You should contact AWS to know more about the emails you are receiving. It seems this instance is fine but I do not know if you have another instance running there.

Thanks

**Comment by Ahmedsaleem54** [comment]
Hi @jotamartos, I have only one instance running and I have taken zero snapshots. This is on free tier, maybe Amazon is doing this on purpose to make me pay for their services? These big companies are way too complicated, I guess Amazon is no more customer centric and now they have started to game their customers too. 
I'm sorry If I'm being negative but I literally panicked when I saw 27GB used email. 

Thank you for your help, means a lot.

**Comment by Ahmedsaleem54** [comment]
Hi @jotamartos this is what AWS said, "You are billed for the total amount of storage provisioned to your account, even if the storage isn't used. For example, if you provision a 100-GB EBS volume for a month, but store only 1 GB of data on that volume, you are still billed for 100 GB-month of EBS storage."  I'M STUNNED!!!

**Comment by jotamartos** [comment]
Hi @Ahmedsaleem54,

Yes, that's how it works. Please note that the disk you provisioned is reserved for you. You can find more info in the official website or by contact them.

https://aws.amazon.com/ebs/pricing/
