### ISSUE TITLE
[<MediaWiki packaged by Bitnami for AWS>] <How to edit localsettings.php file as a root user?>

### ISSUE THREAD

**Issue by MinaIbrahimSaif** [bitnami/vms#460]
### Describe your issue as much as you can

I have been trying to edit the localsettings.php file from FileZilla by connecting with the pairing key. But I can't edit, delete or replace the file. What should I do? and how to be a root user?

**Comment by mdhont** [comment]
You can use an inline editor like nano:

https://docs.bitnami.com/aws/faq/administration/edit-privileged-files/
