### ISSUE TITLE
lego script - how to get rid of an old domain?

### ISSUE THREAD

**Issue by marekyggdrasil** [bitnami/vms#462]
### Describe your issue as much as you can

Dear Bitnami Support,

I usually renew my certificate as follows

```sh
sudo /opt/bitnami/letsencrypt/lego --path /opt/bitnami/letsencrypt --email="MYEMAIL" --http --http-timeout 30 --http.webroot /opt/bitnami/apps/letsencrypt --domains="DOMAIN1" --domains="DOMAIN3" renew
```

where `MYEMAIL` is the email address and `DOMAIN1` and `DOMAIN3` are my domains. Recently I decided to get rid of one of my domains thus its DNS records no longer point to this server.

Problem is, lego script fails to renew the remaining domains because of this, it appears to ignore the `--domains=` argument and just tries to renew everything.

```
2022/11/04 07:54:54 [INFO] [DOMAIN1] acme: Trying renewal with -35 hours remaining
2022/11/04 07:54:54 [INFO] [DOMAIN1, DOMAIN2, DOMAIN3] acme: Obtaining bundled SAN certificate
2022/11/04 07:54:55 [INFO] [DOMAIN1] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/171998926657
2022/11/04 07:54:55 [INFO] [DOMAIN2] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/170566293892
2022/11/04 07:54:55 [INFO] [DOMAIN3] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/172211732877
2022/11/04 07:54:55 [INFO] [DOMAIN1] acme: authorization already valid; skipping challenge
2022/11/04 07:54:55 [INFO] [DOMAIN3] acme: authorization already valid; skipping challenge
2022/11/04 07:54:55 [INFO] [DOMAIN2] acme: Could not find solver for: tls-alpn-01
2022/11/04 07:54:55 [INFO] [DOMAIN2] acme: use http-01 solver
2022/11/04 07:54:55 [INFO] [DOMAIN2] acme: Trying to solve HTTP-01
```

in the output above `DOMAIN2` still appears while I would expect there to be only the `DOMAIN1` and `DOMAIN3` as these are the values provided with `--domains=` arguments.

How does lego script know about `DOMAIN2`? What I tried:

1. I checked directory trees rooted in `/opt/bitnami/apps/letsencrypt` and `/opt/bitnami/letsencrypt` and I could not find domains list.
2. I checked `$DOMAINS` and `$DOMAIN` environmental variables, empty.
3. I disabled SSL in Apache vhosts and in `/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf` in case if lego script takes list from there.
4. I tried to remove the certificates from `/opt/bitnami/letsencrypt/certificates/` and `/opt/bitnami/letsencrypt/archive` in case if list of domains is taken from the file names.
5. I tried running `/opt/bitnami/bncert-tool` once again without mentioning this `DOMAIN2` but lego still remembers it.
6. I found some tutorials mentioning running `./certbot` and `./certbot-auto` but my bitnami instnace on AWS Lightsail does not seem to have `certbot` installed, it seems to only have `bncert-tool` and lego script.

I'm out of ideas how to make lego script forget about `DOMAIN2`, I would prefer not to buy it again just to set the A record and let the script pass for my remaining domains.

**Comment by jotamartos** [comment]
Thank you for using Bitnami. This is a lego-related question so the lego's support team should provide support for it. Please create a new ticket in its github repository to know how to remove that second domain from the domains list 

https://github.com/go-acme/lego

**Comment by marekyggdrasil** [comment]
Thanks. For those who found same issue, here is the link to the lego community discussion I started https://github.com/go-acme/lego/discussions/1753

**Comment by marekyggdrasil** [comment]
"solved" 😂😂😂
