### ISSUE TITLE
[WordPress with NGINX and SSL packaged by Bitnami] HOW TO UPDATE THE PHP VERSION TO 8.0?

### ISSUE THREAD

**Issue by vgnavada** [bitnami/vms#463]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

diagnostic bundle attached

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Nginx: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Mysql: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2022/11/04 08:16:26 [error] 1124#0: *71943 FastCGI sent in stderr: "PHP message: 
PHP Warning: filesize(): stat failed for 
/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wpo/images/wpo_logo_small.p
ng.webp.lossy.webp in 
/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-optimize/vendor/rosell-d
k/webp-convert/src/Convert/Converters/ConverterTraits/EncodingAutoTrait.php on 
Press [Enter] to continue:line 70PHP message: PHP Warning: 
rename(/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wpo/images/wpo_logo 
2022/11/04 08:18:36 [error] 1124#0: *71769 FastCGI sent in stderr: "PHP message: 
PHP Warning: filesize(): stat failed for 
/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wpo/images/wpo_logo_small.p
ng.webp.lossy.webp in 
/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-optimize/vendor/rosell-d
k/webp-convert/src/Convert/Converters/ConverterTraits/EncodingAutoTrait.php on 
line 70PHP message: PHP Warning: 
rename(/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wpo/images/wpo_logo 
2022/11/04 08:20:03 [error] 1124#0: *72083 FastCGI sent in stderr: "PHP message: 
PHP Warning: filesize(): stat failed for 
/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wpo/images/wpo_logo_small.p
ng.webp.lossy.webp in 
/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-optimize/vendor/rosell-d
k/webp-convert/src/Convert/Converters/ConverterTraits/EncodingAutoTrait.php on 
line 70PHP message: PHP Warning: 
rename(/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wpo/images/wpo_logo
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

Press [Enter] to continue:

[Resources]

Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem Size Used Avail Use% Mounted on /dev/nvme0n1p1 26G 22G 3.2G 88% /
```
Please check your cloud provider's documentation for more information.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Something else

### Describe your issue as much as you can

Hello,

There is a Warning displayed in the WORDPRESS DASHBOARD to update the PHP Version.
![image](https://user-images.githubusercontent.com/113204610/199924470-62816ab8-2347-4c33-bf9e-ec39a916825c.png)

How to update the PHP version?
Could you please guide me?

[bitnami-wordpresspro-info-20221104-083155-13431.zip](https://github.com/bitnami/vms/files/9936744/bitnami-wordpresspro-info-20221104-083155-13431.zip)

**Comment by jotamartos** [comment]
Hi, 

In order to upgrade a base component, you will need to launch a new instance with the latest version of PHP and then migrate your data to that new instance 

https://docs.bitnami.com/aws/how-to/migrate-wordpress/
