### ISSUE TITLE
[MediaWiki] Upload file error after installing mediawiki with bitnami

### ISSUE THREAD

**Issue by MinaIbrahimSaif** [bitnami/vms#465]
### Describe your issue as much as you can

I have installed mediawiki with Bitnami, but when I uploaded file using Special:Upload page, it showed the error:

Could not open lock file for "mwstore://local-backend/local-public/b/be/Logohq.png". Make sure your upload directory is configured correctly and your web server has permission to write to that directory.

How to fix this error?

**Comment by jotamartos** [comment]
Hi @MinaIbrahimSaif,

>I have installed mediawiki with Bitnami

- What OS do you have? Where did you get the solution?
- Is this your first installation?
- Did you made any change to the application after the installation?
