### ISSUE TITLE
Bitnami Drupal AWS Lightsail] <Database mysqldump getting overwritten by default>

### ISSUE THREAD

**Issue by kdsnewb** [bitnami/vms#467]
### Describe your issue as much as you can

I have installed multiple aws lightsail bitnami drupal 9 instances that work great but I am trying to use a theme that comes with a preconfigured database.  On other typical stacks dropping and recreating the database seems to work after installing all required modules, themes, libraries.

In the bitnami stack using Mysqldump to recreate the database with the preconfigured import seems just to recreate the original bitnami install. 

I can't see if this is intentional or just something I am missing.  I've used this https://docs.bitnami.com/aws/how-to/migrate-drupal/  to attempt to do this (basically the same on any non-bitnami stack).

The concern I have now using the stack is if I had to restore an existing site from a backup would it do the same thing? Is there something obvious I am just overlooking.  Thanks in advance.

**Comment by mdhont** [comment]
> In the bitnami stack using Mysqldump to recreate the database with the preconfigured import seems just to recreate the original bitnami install. 

Could you give more details? What do you mean exactly with preconfigured import? Could you paste the commands that you are executing?

**Comment by kdsnewb** [comment]
Some themes including one I was trying to add from (morethanthemes) comes with a pre built database so that content types, custom blocks, modules are preconfigured by importing an existing database with some example content and blocks.

After adding all the extra modules and libraries a database dump is done.   

mysqldump -u root -p bitnami_drupal < backup.sql

Same as done for restoring a backup.  Where backup is the database included with the theme.  Ive tried dropping the bitnami_drupal database then create it afterwards then the MySQL dump.  Ive tried a completely new database and adjusting the drupal settings.php file to use the new database.

**Comment by mdhont** [comment]
I'm afraid there is no simple way to do this. Bitnami Drupal uses the bitnami_drupal database and configuration options and themes also get stored there. You could import both databases, for example, give the non bitnami one a different name: 

    mysqldump -u username -p database_name > data-dump.sql

Then you could move the needed data from one database to the other, but it requires some advanced knowledge on your part about Drupal and MySQL. I recommend asking in a dedicated Drupal forum.

**Comment by kdsnewb** [comment]
Ive had 2 drupal experts on this and both failed and I have reasonable drupal experience.  They were not familiar with the bitnami setup and thought it was something on bitnami's side.     

Just for clarification, we tried to do a simple database backup and restore and it wouldn't restore the backed up database which  seems to be very concerning if you can't backup a database and import it.   On restore it would just revert the database back to the original bitnami installed database even after import.

The backed up database worked in a non bitnami setup.  I would be happy to find a time to share a screen and run through it or just a simple conversation over bitnami architecture.  (not sure if its allowed but Id pay for the time) in order to get a better understanding of how bitnami package works.  Especially since database backups aren't working as typical with drupal.  

I can have the database tables imported separately but that seems to be a bad design.  Where is the bitnami drupal database stored and brought in from on a new install?  Maybe replacing that file in its location with the backup or database from the theme distribution would work?

**Comment by mdhont** [comment]
> On restore it would just revert the database back to the original bitnami installed database even after import.

Could you try to reproduce it with a fresh bitnami installation? For example:

- launch a new Drupal instance
- install a theme using the UI
- backup and restore the database following the steps in the guide

**Comment by kdsnewb** [comment]
Ya, that is the steps I'm trying. I believe I have attempted a backup and restore on 3 separate new instances. If not 3 at least 2 new and one existing instance.

Each attempt ends up with a brand new deupal 9 install as if I just created a new instance instead of restoring from a backup.

Is something starting up a new install script that is specific to bitnami? That might be seeing it as a new install vs backing up?

I'll be downloading the backup and migrate module and trying to import the database that way next.  I will report if that changes anything.

Is there anything you can think of that can help u troubleshoot?  Or something obvious I'm just overlooking.

Sent from Samsung Galaxy smartphone.
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mdhont** [comment]
There is no script that reinstalls the database. It could be that some information in the guide is outdated. Are you also following the steps in **Step 3: Copy And Restore Data On The New Instance**?

**Comment by kdsnewb** [comment]
This issue has been resolved and no action needed.  This was on my end.  Something I installed was locking the database.  I have successfully overwritten the database twice now and no issues.
