### ISSUE TITLE
[SuiteCRM] How to deploy a previous version

### ISSUE THREAD

**Issue by emorgan21** [bitnami/vms#468]
### Describe your issue as much as you can

Hi, I can see the current version of Suite is 8.2 in the GCP instance you provide.  How can I access previous versions. I'm looking for 7.10.x. Is there an archive of images by version I can access?

**Comment by jotamartos** [comment]
Hi @emorgan21,

Thank you for your interest. Only the latest versions of the Bitnami solutions are available in GCP and there is no way to deploy a  previous version. However, you can launch that previous version in AWS or deploy a local VM with that version (you can ask us to get the link) and migrate the data to a running instance in Google Cloud.

**Comment by emorgan21** [comment]
Hi Juan, thanks so much for coming back to me. Can you provide the link to
either the AWS or local older version?  Probably the aws one is easier to
migrate for me.

**Comment by jotamartos** [comment]
Some old community AMIs are available in the AWS Console. Please look for the AMI name to launch an old instance. However, I just noticed 7.10.x is not available there anymore.

<img width="1016" alt="Screen Shot 2022-11-09 at 12 18 00" src="https://user-images.githubusercontent.com/8791635/200816557-004d8bf4-dec4-4235-b187-0df30a50220b.png">

You can download the VM and launch it locally by using this link 

https://downloads.bitnami.com/files/stacks/suitecrm/7.10.11-0/bitnami-suitecrm-7.10.11-0-linux-debian-9-x86_64.ova
