### ISSUE TITLE
[Wordpress] FCGI error, Website not stable

### ISSUE THREAD

**Issue by Teteios** [bitnami/vms#469]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e1a4740d-dcdb-7068-49e3-1c8d0d4183f3

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Connectivity: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Wordpress: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Nov 07 16:50:31.765337 2022] [proxy_fcgi:error] [pid 462588:tid
139978285774592] [client **ip_address**:60620] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer: http://webdev.dtmd.eu/wp-admin/post-new.php?lang=de
 [Mon Nov 07 17:14:22.149037 2022] [proxy_fcgi:error] [pid 463513:tid
Press [Enter] to continue:
139979745384192] [client **ip_address**:61196] AH01067: Failed to read FastCGI
header, referer: http://webdev.dtmd.eu/wp-admin/index.php
 [Mon Nov 07 17:14:22.152347 2022] [proxy_fcgi:error] [pid 463513:tid
139979745384192] (104)Connection reset by peer: [client **ip_address**:61196]
AH01075: Error dispatching request to : , referer:
http://webdev.dtmd.eu/wp-admin/index.php

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Wordpress]

Some files don't have the expected permissions Please check the following guide:

https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

===== End of bndiagnostic tool output =====

Press [Enter] to continue:

Press [Enter] to continue:                                                                                          /^C
bitnami@bitnami-wordpress-c863:~$ sudo /opt/bitnami/bndiagnostic-tool2
----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

\\
The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

    ✓ Connectivity: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Wordpress: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Nov 07 16:50:31.765337 2022] [proxy_fcgi:error] [pid 462588:tid
139978285774592] [client **ip_address**:60620] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer: http://webdev.dtmd.eu/wp-admin/post-new.php?lang=de
 [Mon Nov 07 17:14:22.149037 2022] [proxy_fcgi:error] [pid 463513:tid
Press [Enter] to continue:
139979745384192] [client **ip_address**:61196] AH01067: Failed to read FastCGI
header, referer: http://webdev.dtmd.eu/wp-admin/index.php
 [Mon Nov 07 17:14:22.152347 2022] [proxy_fcgi:error] [pid 463513:tid
139979745384192] (104)Connection reset by peer: [client **ip_address**:61196]
AH01075: Error dispatching request to : , referer:
http://webdev.dtmd.eu/wp-admin/index.php

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Wordpress]

Some files don't have the expected permissions Please check the following guide:

https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

don't know how to fix / Server crashed while doing the diagnostic tool

### Describe your issue as much as you can

While tried for the first time the server Crashed so i did the Tool a 2. Time.

Server Crash sometimes, but sometimes not.
fail to read fastcgi cant find solution for in the Internet.
Please help.

**Comment by Teteios** [comment]
Hi,

I fixed some of the erros btu this one still ocur and i cant figure out why
312aeea1-609d-c8ef-16de-8cf3d7a68bd9


Found recent error or warning messages in the Apache error log.
```
[Wed Nov 09 12:39:16.682916 2022] [proxy_fcgi:error] [pid 2626:tid
140092681176832] [client **ip_address**:20434] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer:
http://webdev.dtmd.eu/wp-admin/post.php?post=179&action=edit&lang=de
Press [Enter] to continue:
 [Wed Nov 09 12:39:17.324111 2022] [proxy_fcgi:error] [pid 3631:tid
140090558904064] [client **ip_address**:20432] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer:
http://webdev.dtmd.eu/wp-admin/post.php?post=179&action=edit&lang=de
 [Wed Nov 09 12:39:18.601706 2022] [proxy_fcgi:error] [pid 3631:tid
140090508547840] [client **ip_address**:20432] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer:
http://webdev.dtmd.eu/wp-admin/post.php?post=179&action=edit&lang=de

**Comment by mdhont** [comment]
That is a PHP notice, not an error. It should not affect performance.
