### ISSUE TITLE
[<LAMP>] New PHP Version 

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#473]
### Describe your suggestion as much as you can

Hi,
I would like to know when will the updated LAMP stacks be available on AWS - lightsail & EC2 with the latest version of PHP 8.x?

Looking forward to hearing from you!

**Comment by mdhont** [comment]
It takes some time for the latest bitnami solutions to get published on AWS lightsail. This is outside of our control and unfortunately I can't give you a time schedule.
