### ISSUE TITLE
[LIFERAY] <LIFERAY BY BITNAMI OLD OVA>

### ISSUE THREAD

**Issue by gibzerajim** [bitnami/vms#475]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

The suggested guides are not relevant to the issue

### bndiagnostic output

The suggested guides are not relevant to the issue

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are not relevant to the issue

### Describe your issue as much as you can

Good day guys,

May i know where can i get or download the "Old OVA of Liferay by Bitnami" 
I need a version of 7.4.3-30-0 OVA cause my database schema are originally compatible with this version

Please help me.....

Thanks....

**Comment by mdhont** [comment]
You can download it here:

https://downloads.bitnami.com/files/stacks/liferay/7.4.3-30-0/bitnami-liferay-7.4.3-30-0-linux-vm-debian-11-x86_64-nami.ova 

     md5:c2bf0d8c99528b81fb8dfea229a8dd21

**Comment by gibzerajim** [comment]
Thanks so much may issued has been resolved
