### ISSUE TITLE
[Bitnami Lightsail]  <Single Wordpress to Multisite>

### ISSUE THREAD

**Issue by LaoshiCat** [bitnami/vms#479]
### Describe your issue as much as you can

Hi! I have a Single Wordpress Site I'd like to convert to a Multisite Wordpress that is hosted on AWS Lightsail. I tried following all of the directions in numerous places on the internet about how to convert a Single WP site to a Multisite- all of which seemed fairly straightforward and easy enough to do. The directions do not seem to be working however in Bitnami. I called AWS support and they have no idea how to do this either and said that there is no documentation on how to convert Single WP to Multi WP via Bitnami. Does anyone have the steps to follow to do this via the ssh window? Or have another route to achieve this? Thanks in advance for your help! I greatly appreciate either directions or being directed to where this type of documentation might be? Thanks again!

**Comment by jotamartos** [comment]
Hi @LaoshiCat,

Thank you for using Bitnami. We do not have any guide to convert a WordPress single-site to multisite. However, you can launch a WordPress Multisite solution and migrate your data to that new deployment 

https://docs.bitnami.com/aws/how-to/combine-wordpress-multisite/

You can also review the app's documentation to know how to migrate your data to that new deployment. There should also be some plugins/extensions that help you during this migration.

Thanks

**Comment by Mindbowser** [comment]
We tried above steps and seems as our site is huge its not working for us, the backup of our site when taken using plugin is around 8GB(including media, databases etc), the export option mentioned in the link https://docs.bitnami.com/aws/how-to/combine-wordpress-multisite/ generated 115mb backup but still its not working, any idea what is the best way to convert to multisite?

**Comment by jotamartos** [comment]
Please let's continue your conversation [here](https://github.com/bitnami/vms/issues/1181)
