### ISSUE TITLE
WordPress bitnami on Litespeed

### ISSUE THREAD

**Issue by Fushcia80** [bitnami/vms#480]
### Describe your issue as much as you can

WordPress image based on
 open litespeed on AWS .

  it's showing no such file or directory at both
 /opt/bitnami/WordPress/wp-config.php
And at /opt/bitnami/php/etc/php.ini.

It's installed on approach -A.

Can you please provide me the location of wp-config.php  and for  php.ini please!

**Comment by mdhont** [comment]
Can you share output of the following command:

    ls- la /opt/bitnami

**Comment by Fushcia80** [comment]
i have done some research and found wp-config locatipn i.e var/www/html/wp-config.php

but the php.ini file usable for server locatiuopn is not found yet i have edited many php.ini files  as per documentation .
but max input variables and exection time cant be increased can you please tell me the location to edit the same and incease it!
it would appreciate that!

output for ls- la /opt/bitnami is 

 command 'lsd' from snap lsd (0.16.0)
  command 'lsm' from deb lsm (1.0.4-2)
  command 'lsw' from deb suckless-tools (46-1)
  command 'lsh' from deb lsh-client (2.1-13)
  command 'lsc' from deb livescript (1.6.1+dfsg-2)
  command 'ls' from deb coreutils (8.32-4.1ubuntu1)

**Comment by mdhont** [comment]
It doesn't seem you are using a bitnami configured application. Could you please check the name of the solution you are using?
