### ISSUE TITLE
WordPress Certified by Bitnami and Automattic - AWS - Unable to reach the site

### ISSUE THREAD

**Issue by zahraa-m** [bitnami/vms#481]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

The tool did not provide an ID

### bndiagnostic output

    ? Apache: Found possible issues
    ? WordPress: Found possible issues
    ✓ resources: No issues found
    ✓ mysql: No issues found
    ✓ php: No issues found
 
 
Found recent error messages in the Apache error log.
```
[Sun Nov 13 01:43:35.589063 2022] [proxy_fcgi:error] [pid 1838:tid 139723229964032] [client 66.249.69.87:51354] AH01071: Got error 'PHP message: PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0PHP message: PHP Fatal error:  Unknown: Failed opening required '/opt/bitnami/apps/wordpress/htdocs/aios-bootstrap.php' (include_path='.:/opt/bitnami/php/lib/php') in Unknown on line 0'
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-file-permissions/

Found recent WordPress plugin related error messages in the Apache error log.Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

Your instance is using swap memory:This usually means that your instance is running low on memory. You could try to increase your instance's memory. Please check your cloud provider's documentation for more information.

### bndiagnostic was not useful. Could you please tell us why?

There is no documentation on how to re-install wordpress inside Bitnami in case if the site got hacked

### Describe your issue as much as you can

My site was working fine until last week it got a huge amount of brute force attacks to access the admin page. I installed Captcha, disabled all the users that I have and kept only one admin, changed the password, and added a plugin to limit time and access to the admin page. After all these measures the site kept working for a while until it got hacked. 

I accessed the htdocs inside the wordpress and found many .php files changed and they add malicious files as well. I deleted the bad files and tried to fix the modified ones. But this did not help to restore my site. Then I disabled the plugins but it did not resolve the issue. Then I tried to update the wordpress core through the terminal but it kept showing that there is no such command error. 
So I just replaced the core files manually through the ssh terminal and still the site did not work. Then, I downloaded the wp-content folder, wp-config.php file and backed up the database. Finally, I deleted everything in the htdocs and added the latest version of WordPress and it did not work also. 

Is there a way to reinstall the WordPress on bitnami?

**Comment by gongomgra** [comment]
Hi @zahraa-m,

Thanks for using Bitnami. If your site has been hacked, we recommend you to start a fresh new server and migrate the WordPress information into it. However, you should not use the "All-in-One WP Migration", just in case it also moves any hacked file or database info into your new site. For this use case, we highly recommend you to open a new question in the official WordPress forums and ask the community for help on how to rescue the non-hacked data.

https://wordpress.org/support/forums/

**Comment by zahraa-m** [comment]
@gongomgra Thanks. May I ask what you mean by starting a fresh new server? You mean I have to purchase another EC2 instance on AWS? If yes, what about the current one? I reserved it for 3 years and paid upfront so?

**Comment by zahraa-m** [comment]
I was able to restore the EC2 to the launch time version and that led to the original WordPress version from Bitami Stack. However, I tried to install the SSL Certificate but the bncert -tool keeps showing this error :

The public IP address for this machine could not be detected. A public IP address will be required for Let's Encrypt to verify that your domains point to this machine.
---------------------
Then it gives the option to proceed and it shows the same error again!  I flushed the DNS cache but did not resolve the issue. the WAN IP on the server is showing the same public IP on the AWS instance, also the same on the DNS A record. 

Any suggestions?

**Comment by gongomgra** [comment]
Hi @zahraa-m,

I'm afraid I don't know if reusing the same instance with a previous snapshot will be enough or if the snapshot belongs to an infected disk state as well. Regarding your first question, yes, I meant to start a completely new server. Unfortunately, I can't help you with the upfront payment you did, you will have to ask this to the AWS support team.

About the bncert-tool issue, did you configure the instance firewall to allow connections from port 80 and 443? Notice these are the default Apache ports. Can you run the next command on your server and share the output with us? Remember to replace `YOUR_DOMAIN` placeholder with your actual value

```
getent hosts YOUR_DOMAIN
```

**Comment by zahraa-m** [comment]
Thanks for the suggestions.  I did not play around with the firewall, it is on the default settings. How to check if the firewall is blocking the ports?

I ran this command  `sudo  netstat -pln `

The output shows that tcp6 has ports 80 and 443 open. Also, I ran the `getent `command and it shows the same public IPv4 address that is assigned to the EC2 on AWS and also shows the domain name of my site.  Any other suggestions to solve the SSL issue?

**Comment by gongomgra** [comment]
Hi @zahraa-m,

Thanks for your message. You can check the open/closed ports in your server from the AWS firewall (running outside of the server itself) using the next guide

https://docs.bitnami.com/aws/faq/administration/use-firewall/

Anyways, if the `getent hosts` command is returning your IP address properly, please update the lego binary on your server to the latest release just in case, and then run the bncert-tool again.

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#step-1-install-the-lego-client

**Comment by zahraa-m** [comment]
Hi @gongomgra,
Thank you for your suggestions and help. Yes, I checked the ports on the AWS side, and they are both open for IPv4 but the `sudo netstat -pln` shows they are open for tcp6, I am wondering if that's normal? 

Also, when I run `sudo lego` it shows version 4.2.0 which is the latest one. Also, the bn-cert-tool got updated after I restored the EC2 to the launch time version. 

The issue still persists, any other suggestions?

**Comment by zahraa-m** [comment]
Hi @gongomgra, thank you for all the suggestions. It turns out that ports 80 and 443 were closed by high-level admin in the AWS abuse team, they did that because of the attack that happened previously so I simply asked them to open the ports after I cleaned the site from the malicious code and enhanced security. After they opened the ports, I used the bncert tool and it worked perfectly. 

Thanks again for all the help and please close this ticket as solved :)

**Comment by gongomgra** [comment]
Hi @zahraa-m,

Thanks for your message. I'm glad you solved your issue! As you requested, we are closing this ticket as solved. Do not hesitate to open a new ticket with any other question you may have.
