### ISSUE TITLE
[WordPress with NGINX]Custom domain doesn't lead to wordpress

### ISSUE THREAD

**Issue by hunterwinterton** [bitnami/vms#482]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b388acbb-4668-7a32-6bbd-fc2c44ef63c0

### bndiagnostic output

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ? Nginx: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Link didn't work

### Describe your issue as much as you can

When I put in my domain name, it takes me to a page that says, "Congratulations! You are now running Bitnami NGINX Open Source 1.21.6 in the Cloud." I have tried a few troubleshooting steps like changing the server_name in the server-block, but that didn't work. There is also an error in the nginx console.

2022/11/13 06:19:28 [error] 2018#2018: *8 access forbidden by rule, client: 
**ip_address**, server: , request: "GET /.env HTTP/1.1", host: "54.148.53.201"
 2022/11/13 06:23:32 [error] 2018#2018: *10 open() 
"/opt/bitnami/nginx/html/sitemap.rss" failed (2: No such file or directory), 
client: **ip_address**, server: , request: "GET /sitemap.rss HTTP/1.1", host: 
"CUSTOMDOMAIN"
 2022/11/13 06:31:50 [error] 9526#9526: *7 FastCGI sent in stderr: "PHP message: 
PHP Warning: Undefined array key "dbname" in 
/opt/bitnami/wordpress/wp-admin/setup-config.php on line 259PHP message: PHP 
Warning: Undefined array key "uname" in 
/opt/bitnami/wordpress/wp-admin/setup-config.php on line 260PHP message: PHP 
Warning: Undefined array key "pwd" in 
/opt/bitnami/wordpress/wp-admin/setup-config.php on line 261PHP message: PHP 
Warning: Undefined array key "dbhost" in /opt/bitnami/wordpres

**Comment by hunterwinterton** [comment]
When I went to my website this morning, the problem was strangely fixed. I can now to my domain and see my Wordpress website. I ran the diagnostic again, however, and there are still errors.

2022/11/13 16:13:33 [crit] 1065#1065: *12522 SSL_do_handshake() failed (SSL: 
error:14201044:SSL routines:tls_choose_sigalg:internal error) while SSL 
handshaking, client: **ip_address**, server: 0.0.0.0:443
 2022/11/13 16:33:44 [crit] 1065#1065: *12896 SSL_do_handshake() failed (SSL: 
error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL 
handshaking, client: **ip_address**, server: 0.0.0.0:443
 2022/11/13 18:15:08 [crit] 1065#1065: *12960 SSL_do_handshake() failed (SSL: 
error:14201044:SSL routines:tls_choose_sigalg:internal error) while SSL 
handshaking, client: **ip_address**, server: 0.0.0.0:443

I haven't gotten an SSL certificate using bitnami, I got one through Cloudflare previously. Is that what is causing this error? Do I need to request an SSL certificate with bitnami instead of Cloudflare, or can I ignore this error?

**Comment by jotamartos** [comment]
I do not know if this was just simply a cache issue and that's why you didn't see your website yesterday. If you are using CloudFlare, it may be the case in which it's caching the resources so you need to wait some time for them to be updated. 

Regarding the SSL errors, I understand you enabled the encryption from CloudFlare to the running NGINX and as the certificate is a self-signed one, errors are happening. I suggest you disable the encryption between CloudFlare and your server and only keep the one between the client and CloudFlare.
