### ISSUE TITLE
[Wordpress] <Apache 301 domain redirects>

### ISSUE THREAD

**Issue by djmokoia** [bitnami/vms#483]
### Describe your issue as much as you can

I've attempted to resolve this issue myself, following the instructions here:

https://docs.bitnami.com/general/infrastructure/lamp/administration/redirect-custom-domains/

I have an AWS lightsail Bitnami wordpress instance. It's a self-contained Bitnami installation.

I have 3 different domain names pointing at the server but I want them all to resolve to just one of the domains. 

I had this working before but I think that I must have created a new instance in order to update the php version and in the process lost the configuration. 

I have virtual host configuration in:
/opt/bitnami/apache2/conf/bitnami/bitnami.conf 

and also 
/opt/bitnami/apps/wordpress/conf/http-vhosts.conf which is then referenced in bitnami-apps-vhosts.conf 

both files have ServerName and ServerAlias configured for vhosts on 80 and 443

I have let's encrypt certificate installed for all 3 domains, which works. 
http -> https redirect works and www -> non www redirect works 

but none of the ServerAlias -> ServerName redirects are working. 

The first thing I am not sure about is which of the above config locations is actually being used and therefore where to apply the changes. 
The next thing I'm unsure about is what are the correct ModRewrite rules and conditions to make this work.

Any troubleshooting clues would be appreciated. I'm sure this shouldn't be difficult to setup

**Comment by gongomgra** [comment]
Hi @djmokoia,

Thanks for using Bitnami. We would need more information to understand your issue. Can you run the bndiagnostic tool on your server and share the generated code with us?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by djmokoia** [comment]
> Hi @djmokoia,
> 
> Thanks for using Bitnami. We would need more information to understand your issue. Can you run the bndiagnostic tool on your server and share the generated code with us?
> 
> https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

Hi,

Thanks, I did that but the file wouldn't auto upload, so I have downloaded it and uploaded it to Google drive storage. What's the best way of sharing it with you?

**Comment by djmokoia** [comment]
> Hi @djmokoia,
> 
> Can you try running the bndiagnostic tool again? Let's see if the auto-upload process works this time.

Hi @gongomgra 

Just tried it again, the same issue unfortunately, it's not able to auto upload the zip file.

**Comment by gongomgra** [comment]
Hi @djmokoia,

Thanks for your message. Please upload the zip file here to the ticket and I will remove the download link as soon as I download it.

**Comment by djmokoia** [comment]
[bitnami-wordpress-info-20221118-082718-18499.zip](https://github.com/bitnami/vms/files/10039687/bitnami-wordpress-info-20221118-082718-18499.zip)

@gongomgra

**Comment by djmokoia** [comment]
@gongomgra thanks I do seem to have resource issues on the server, I am not entirely sure why

Please can you confirm which config file I need to edit with the settings you have specified? Part of the issue that I have is being unsure about which config file, in which location I should be editing

**Comment by djmokoia** [comment]
uptime : 11:40:31 up 29 days, 18:04,  1 user,  load average: 0.01, 0.00, 0.00

df:

Filesystem      Size  Used Avail Use% Mounted on
udev            485M     0  485M   0% /dev
tmpfs            99M   12M   88M  12% /run
/dev/xvda1       40G  7.1G   31G  19% /
tmpfs           494M     0  494M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           494M     0  494M   0% /sys/fs/cgroup
/dev/xvda15     124M  278K  124M   1% /boot/efi
tmpfs            99M     0   99M   0% /run/user/1000

total        used        free      shared  buff/cache   available
Mem:            987         347         203         141         436         353
Swap:           634         519         115

@gongomgra

**Comment by gongomgra** [comment]
Hi @djmokoia,

Thanks for sharing the info. Yes, it looks like your are short in RAM memory according to the `free -m` command. You may want to increase your instance type to get more resources available. This memory shortage may also be causing your issues trying to upload the bndiagnostic bundle, as this causes the server can't start new processes (like uploading the file to our system).

Regarding the file you have to edit, it is the file you already edited: `/opt/bitnami/apps/wordpress/conf/httpd-vhosts.conf`. Remember to restart the Apache service afterwards.

**Comment by gongomgra** [comment]
Hi @djmokoia,

Thanks for your message. I reviewed your bndiagnostic bundle again with another team member, and I think we found the solution for your problem.

We found you updated the `ServerName` and `ServerAlias` lines in the `bitnami.conf` file, so the requests are attended by that config file instead of `/opt/bitnami/apps/wordpress/conf/httpd-vhosts.conf`. In order to solve this, please update the `bitnami.conf` file by replacing the redirects in that file (added there by the bncert-tool) with the ones mentioned in the guide below

https://docs.bitnami.com/aws/apps/wordpress/administration/use-single-domain/#approach-b-self-contained-bitnami-installations

Remember to restart Apache. Hope it helps!

**Comment by djmokoia** [comment]
@gongomgra thank you!
