### ISSUE TITLE
[<certificate>] <upload paid certificate to the bitnami stack instead of let's encrypt free certificate>

### ISSUE THREAD

**Issue by luka725** [bitnami/vms#485]
### Describe your issue as much as you can

Hello, 

I purchased a certificate from sectigo they send us a zip file that has a two file server.crt and server.ca-bundle.
how is this possible to use this paid server.crt file generated by sectigo instead of let's encrypt free certificate

**Comment by mdhont** [comment]
The following guide explains how to set it up:

https://docs.bitnami.com/aws/apps/wordpress/administration/enable-https-ssl-apache/

**Comment by luka725** [comment]
there are some shortcuts from ~/letsencrypt directory etc www.website.com.crt www.website.com.key and without www.
should I first somehow shut down letsencrypt and use bitnami/conf directory where server.crt and server.key is placed.
there is some kind of many certificates and instruction is all about three of them [server.crt, server.key, server.csr]

**Comment by luka725** [comment]
can you tell me, please?
how can I fully disable let's encrypt configuration to the server and let the server use manually uploaded .crt .key and .csr files at the /conf directory 
also sectigo provide us ca-bundle file which should be used by the server with the new .crt .key and .csr files 
please let me know how to configure Apache to do those things possible to work.

please see the attached image  where I don't get what those shortcuts marked in red are actually doing
![Screenshot 2022-11-16 183958](https://user-images.githubusercontent.com/57828247/202210132-48ab41ac-a789-488b-ab8c-e3bd12b3e304.png)

**Comment by mdhont** [comment]
You need to edit `/opt/bitnami/apache2/conf/bitnami/bitnami.conf` and change the path of `SSLCertificateKeyFile` and `SSLCertificateFile` to point to your paid certificate:

```
SSLCertificateFile /opt/bitnami/apache2/conf/server.crt
SSLCertificateChainFile /opt/bitnami/apache2/conf/server.csr
SSLCertificateKeyFile /opt/bitnami/apache2/conf/server.key
```

**Comment by luka725** [comment]
all clear

but there is no SSLCertificateChainFile searchable string in bitnami.conf
and one more thing
in which config file should I have to write the pointer of ca-bundle file?

Thank you very much!

**Comment by dgomezleon** [comment]
Hi @luka725,

The directives `SSLCertificateChainFile` and `SSLCACertificateFile` could be defined in `conf/bitnami/bitnami-ssl.conf`, which is the preferred way. Eg:

```
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
```
to

```
  SSLCertificateFile /opt/bitnami/apache2/conf/DOMAIN.crt
  SSLCertificateKeyFile /opt/bitnami/apache2/conf/DOMAIN.key
  SSLCertificateChainFile /opt/bitnami/apache2/conf/DOMAIN.csr
  SSLCACertificateFile /opt/bitnami/apache2/conf/DOMAIN-ca.crt
```

Restart Apache after the changes.

**Comment by luka725** [comment]
Many thanks!
