### ISSUE TITLE
[Roundcube] How to access application

### ISSUE THREAD

**Issue by alta-atc** [bitnami/vms#486]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0f841adc-ad9b-42dc-e7c4-41500d517c52

### bndiagnostic output

 
    ✓ Php: No issues found
    ✓ Connectivity: No issues found
    ✓ Processes: No issues found
    ✓ Apache: No issues found
    ? Resources: Found possible issues
    ✓ Mariadb: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1681 519 64 7 1097 972 Swap: 0 
0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

### bndiagnostic was not useful. Could you please tell us why?

0f841adc-ad9b-42dc-e7c4-41500d517c52

### Describe your issue as much as you can

I have a fresh install of the Roundcube bitnami VM. 

I am navigating to the GCP Deployments page to see the username and password. 

The password is listed, the username is not. The username is not user@example.com as suggested in the help material. 

<img width="567" alt="Screen Shot 2022-11-15 at 5 29 14 PM" src="https://user-images.githubusercontent.com/102269444/202047041-e891b0db-e786-49a7-bba3-50546f325626.png">

**Comment by jotamartos** [comment]
Hi @alta-atc,

Roundcube is a SMTP client so you need to use your Gmail account and your password to access the app. The password shown there is the one configured in the database but it has nothing to do with the application. 

https://docs.bitnami.com/google/apps/roundcube/get-started/first-steps/#what-is-the-administrator-username-set-for-me-to-log-in-to-the-application-for-the-first-time

I hope this helps.
