### ISSUE TITLE
Renew SSL certificate script, How to save?

### ISSUE THREAD

**Issue by simplyhum** [bitnami/vms#487]
### Describe your issue as much as you can

Hello,

I am on a Bitnami Multisite on AWS. I am trying to create the SSL certificate renewal script, as steps provided in this link - [](https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/ ), **Step 5**

I am using the **Apache** steps. After using the command - sudo nano /opt/bitnami/letsencrypt/scripts/renew-certificate.sh , and putting the contents in the buffer file. 
**How do I save and exit the file?**  Before i go to the next step.
Please suggest, as I am not an unix user.

Thanks

**Comment by mdhont** [comment]
It depends on which program you are using of course but if you are using the nano inline editor as described in our guides you can save the file with ctrl-x and then pressing enter.

**Comment by simplyhum** [comment]
Well, ctrl -x and enter simply didn't do the trick. I was stuck on this screen - [https://imgur.com/a/qXMeWo9](url) .
Then I pressed Y and ctrl-c and ctrl-x. Not sure if this is correct way, but the contents of the file finally got saved.

Not sure though, what should be the correct command sequence.

Thanks

**Comment by simplyhum** [comment]
@mdhont much appreciate the guidance. Thank you.
