### ISSUE TITLE
[<nginx/php-fpm>] PHP Version 8.1.x possible?

### ISSUE THREAD

**Issue by latzt** [bitnami/vms#488]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

43a1905a-45f2-aed0-d2df-ad68d4098ee1

### Describe your issue as much as you can

Dear developers, 

i want to know if the AMI **ami-0a6d20eab029649c5** version **nginx/php-fpm 1.23.2-5-r06** gets updated from `PHP 8.0.x` to `8.1.x` in near future? Since many years i am using your AMI's and i am very satisfied, but i require a newer PHP version.

Many thanks in advance and best regards,
Tim

**Comment by mdhont** [comment]
Unfortunately updating individual components is not supported. To update you need to launch the [latest](https://bitnami.com/stacks) version and migrate the data there.

**Comment by latzt** [comment]
Thanks for reply and i will then have a look at the latest versions and see whats suitable for my case :)

**Comment by makkus183** [comment]
@mdhont the [latest version](https://bitnami.com/stack/nginx/stackmandebian-osx-x64-nami/changelog.txt) only contains `PHP 8.0.x` , do you know if a release with `PHP 8.1.x` is planned?

**Comment by makkus183** [comment]
I am launching on EC2.

**Comment by makkus183** [comment]
@mdhont any update to timeline on this issue? Thx in advance

**Comment by mdhont** [comment]
The latest version of Bitnami Nginx (released this week) uses PHP version 8.1.

**Comment by makkus183** [comment]
I can not see the 8.1 Version [here](https://bitnami.com/stack/nginx/stackmandebian-osx-x64-nami/changelog.txt)

**Comment by mdhont** [comment]
That changelog is no longer being updated because the OSX VM solution has been deprecated. The available Nginx solutions use PHP 8.1.
