### ISSUE TITLE
[Parse] Cannot find any running daemon to contact

### ISSUE THREAD

**Issue by RitvikSardana** [bitnami/vms#49]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2836fdfb-fa94-08a6-2ded-5bab2887c2f8

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.

    ? Apache: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Jun 28 14:01:36.190157 2022] [proxy_http:error] [pid 2997:tid
140286097348352] [client **ip_address**:64720] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1
 [Tue Jun 28 14:01:36.851517 2022] [proxy:error] [pid 2997:tid 140286080562944]
(111)Connection refused: AH00957: http: attempt to connect to
**ip_address**:4040 (127.0.0.1:4040) failed
Press [Enter] to continue:
 [Tue Jun 28 14:01:36.851550 2022] [proxy_http:error] [pid 2997:tid
140286080562944] [client **ip_address**:64726] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1, referer: http://3.6.7.138/

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 66 of /opt/bitnami/apache2/conf/httpd.conf: Cannot                                                                                                             
load modules/mod_mpm_event.so into server:
/opt/bitnami/apache/modules/mod_mpm_event.so: undefined symbol:
ap_run_child_stopping
```
Please check the configuration.

System Apache is running:
```
root 645 0.0 0.2 6392 4220 ? Ss 11:05 0:00 /usr/sbin/apache2 -k start www-data
655 0.0 0.2 1211320 6020 ? Sl 11:05 0:00 /usr/sbin/apache2 -k start
Press [Enter] to continue:
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the
following command to stop it:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Dont know what to do

### Describe your issue as much as you can

Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)

I don't know how it happened can anyone help me?

**Comment by RitvikSardana** [comment]
Hello @jotamartos .
Thank you for assisting , I got the issue, resolved, 
gonit wasn't working as Apache wasnt working, so I removed apache and installed it again and it worked, and gonit started working due to which daemon error was no more and everything worked perfectly.

Although there is another issue!
I am not able to use Puppeteer in my Bitname EC2 Instance.
Can you let me know why?

**Comment by RitvikSardana** [comment]
Error: EACCES: permission denied, open './test.jpg'

Can you tell me how can I remove this error?
I tried to do chmod 777 in the code directory

**Comment by RitvikSardana** [comment]
no not it is just an error of permission in Bitnami Server , can you tell me how do I make my ec2 instace to read and write files in my code directory??

**Comment by jotamartos** [comment]
Hi @RitvikSardana,

I do not know how you are running the Puppeteer script. Please note that this is a permissions-related error and we do not provide support for Puppeteer. You can try to run the Puppeteer script in a different folder (/tmp?), with a different user (using sudo?) or changing the permissions of the folder/files (chown/chmod)

**Comment by RitvikSardana** [comment]
I want to scrape data from a website using puppeteer , so when a user clicks on a button in the frontend , the script should be executed and should save a screenshotin the directory, but I get this error instead EACCES: permission denied, open './test.jpg'

**Comment by jotamartos** [comment]
If that process is triggered by Parse or Apache (I do not know how you are configuring the Puppeteer process), you need to use the 'parse' or 'daemon' user to configure the permissions of the folder/files. Again, this is a generic question about permissions, the application and the way you are configuring Puppeteer and we do not provide support for those type of questions.

**Comment by RitvikSardana** [comment]
Yes It is getting triggered by Parse, how do I change the folder user to parse or daemon user?

using `CHOWN`?

**Comment by RitvikSardana** [comment]
Any help over here?

**Comment by jotamartos** [comment]
Yes @RitvikSardana, you need to use `chown` and `chmod` to configure the permissions of the Puppeteer folder so Parse can read/write the necessary files.

**Comment by jotamartos** [comment]
As I mentioned, this is a permissions related question and we do not provide this kind of support. Parse works using the parse user and group so you should configure the permissions of the folder/file Parse is going to write to be writable by that user/group. 

```
sudo chown -R parse:parse path/to/the/folder/where/puppeteer/is/going/to/write
sudo chmod -R ug+w path/to/the/folder/where/puppeteer/is/going/to/write
```

If this doesn't work, then you are running into a different issue and you should contact Parse to get more information. 

https://community.parseplatform.org/
