### ISSUE TITLE
[Bitnami Wordpress] Can't find Config.php With Approach A

### ISSUE THREAD

**Issue by wiredcolony** [bitnami/vms#493]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

dab32b87-d76a-148e-3322-db83b00d3251

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 975 505 62 66 407 246 Swap: 
634 71 563
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2022-11-15 8:52:28 409 [Warning] Aborted connection 409 to db: 
'bitnami_wordpress' user: 'root' host: 'localhost' (Got an error writing 
communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Nov 17 08:17:30.569685 2022] [proxy_fcgi:error] [pid 1047:tid 
140389209872128] [client **ip_address**:49316] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://34.221.30.44/wp-admin/upload.php
Press [Enter] to continue:^C
bitnami@ip-172-26-11-177:/opt/bitnami$ sudo /opt/bitnami/bndiagnostic-tool
----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

\-
The bndiagnostic tool has finished searching for errors and has found some 
issues that might be related to yours. The output will be shown on the next 
page:
                                    
Press [Enter] to continue:


===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 975 500 64 66 410 252 Swap: 
634 75 559
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2022-11-15 8:52:28 409 [Warning] Aborted connection 409 to db: 
'bitnami_wordpress' user: 'root' host: 'localhost' (Got an error writing 
communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Nov 17 08:17:30.569685 2022] [proxy_fcgi:error] [pid 1047:tid 
140389209872128] [client **ip_address**:49316] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://34.221.30.44/wp-admin/upload.php
Press [Enter] to continue:
 [Thu Nov 17 10:34:34.620433 2022] [proxy_fcgi:error] [pid 3735:tid 
140389595936512] [client **ip_address**:53572] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php 
on line 173PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 174PHP message: PHP Warning: Undefined 
array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php on line 
689PHP message: PHP Warning: Undefined a [Thu Nov 17 11:30:36.099504 2022] 
[proxy_fcgi:error] [pid 3735:tid 140389696648960] [client **ip_address**:44936] 
AH01071: Got error 'PHP message: PHP Warning: Undefined array key 
"HTTP_USER_AGENT" in 
/bitnami/wordpress/wp-content/themes/buddyboss-theme/inc/theme/functions.php on 
line 284PHP message: PHP Warning: Undefined array key "HTTP_USER_AGENT" in 
/bitnami/wordpress/wp-content/themes/buddyboss-theme/inc/theme/functions.php on 
line 284PHP message: PHP Warning: Undefined array key "HTTP_U
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I am not having issues related to the tool.

### Describe your issue as much as you can

My issue is finding the location of my `config.php`.  I am following this https://docs.bitnami.com/aws/apps/resourcespace/configuration/install-ffmpeg/ and I am unable to complete the second-to-last step.  Thank you for your time.

PS-If you wouldn't mind checking my Bndiagnostic errors and tell me if there is anything I need to fix ASAP or if they are "common" and nothing to worry about.  I would appreciate that.  Thank you.

**Comment by jotamartos** [comment]
The guide you are following is not mean to be followed when using WordPress. Please note that that guide is specific to ResourceSpace. We do not have any guide to install and configure that component in WordPress, you will need to follow the official guides to do so.

**Comment by wiredcolony** [comment]
Thank you for responding. I didn't realize it wasn't the same application.  Please close this ticket out. Thank you.
