### ISSUE TITLE
[OpenCart packaged by Bitnami AWS] i can't change my ec2 type larger than t3a.2xlarge

### ISSUE THREAD

**Issue by KhaledAnaqwa** [bitnami/vms#494]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

i didn't find resource to help me 

### bndiagnostic output

The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.

### bndiagnostic was not useful. Could you please tell us why?

i didn't find resource to help me 

### Describe your issue as much as you can

[OpenCart packaged by Bitnami AWS] 
i can't change my ec2 type larger than t3a.2xlarge

The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.

**Comment by jotamartos** [comment]
t3a.2xlarge is the largest instance type of the t3a family 

https://aws.amazon.com/ec2/instance-types/

What type of instance are you trying to select? If you want a higher performance, you can move to the m6a instance types which are available for the latest version of the Bitnami OpenCart solution in AWS

![Screen Shot 2022-11-18 at 13 20 41](https://user-images.githubusercontent.com/8791635/202703924-f50be23b-3d3c-4e7b-a7a7-d70f2774f46f.png)

Please note that if you are using an old version of the solution, those new instance types won't be available and you would need to select one of supported instance types at the time of the publishing of that version.
