### ISSUE TITLE
[Moodle] Error : Invalid permissions detected when trying to create a directory. Turn debugging on for further details.

### ISSUE THREAD

**Issue by Boureimbi** [bitnami/vms#496]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

742ce277-0b49-a97c-1a83-3ce8daa3d670

### bndiagnostic was not useful. Could you please tell us why?

I update the memorie but still no working

### Describe your issue as much as you can

Error
Invalid permissions detected when trying to create a directory. Turn debugging on for further details.

**Comment by gongomgra** [comment]
Hi @Boureimbi,

Thanks for using Bitnami. I checked your bndiagnostic bundle and I found the next errors in your Apache logs

```
[Wed Nov 16 13:03:42.710710 2022] [proxy_fcgi:error] [pid 143784:tid 139871448332032] [client IP_ADDRESS:55977] AH01071: Got error 'PHP message: PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0', referer: http://20.102.83.136/admin/tool/uploaduser/index.php
[Thu Nov 17 19:33:56.027345 2022] [core:crit] [pid 297791:tid 139709959358208] (13)Permission denied: [client IP_ADDRESS:40818] AH00529: /opt/bitnami/moodle/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/opt/bitnami/moodle/' is executable
```

I see in your bndiagnostic bundle that the filesystem permissions for moodle where updated to `root` user and `www-data` group. These are not the default values. Can you recover the original ones? Notice the Apache server is run using the special `daemon` user account.

```
[bitnami@dockerdev:w:~/projects/scripts/bnsupport] $
lrwxrwxrwx 1 root root 15 Oct 29 05:09 moodle -> /bitnami/moodle
-rwxrwxrwx  1 root www-data    302 Oct 29 05:08 /bitnami/moodle/behat.yml.dist
-rwxrwxrwx  1 root www-data   1162 Oct 29 05:08 /bitnami/moodle/brokenfile.php
-rwxrwxrwx  1 root www-data   2247 Oct 29 05:08 /bitnami/moodle/composer.json
-rwxrwxrwx  1 root www-data 186392 Oct 29 05:08 /bitnami/moodle/composer.lock
-rwxrwxrwx  1 root www-data  60865 Oct 29 05:08 /bitnami/moodle/config-dist.php
-rwxrwxrwx  1 root www-data   1013 Oct 29 05:08 /bitnami/moodle/config.php
(...)
```

Regarding the `.htaccess` files, notice we disable them by default for security reasons. You can enable them back following the next guide

https://docs.bitnami.com/azure/infrastructure/lamp/administration/use-htaccess/
