### ISSUE TITLE
[alfresco] <Category Manager error>

### ISSUE THREAD

**Issue by yaoxinch** [bitnami/vms#497]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5305a101-aa75-ed43-2ba9-d91f2ce79f09

### bndiagnostic output

✓ Apache: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

 ? Connectivity: Found possible issues,  I checked, all ports are opened, I also disabled ufw

### Describe your issue as much as you can

Hi, i just imported your ova to esxi server, and only start alfresco, do not do any other things
when use admin tools check the Category Manager
show error:
JavaException: org.alfresco.repo.search.QueryParserException: 10180030 Solr request failed with 403 /solr/alfresco/alfresco?wt=json&fl=DBID%2Cscore&rows=1000&df=TEXT&start=0&locale=en_US&alternativeDic=DEFAULT_DICTIONARY&fq=%7B%21afts%7DAUTHORITY_FILTER_FROM_JSON&fq=%7B%21afts%7DTENANT_FILTER_FROM_JSON

and I use ctlscript.sh status, all things are running
activemq already running
alfresco-search-services already running
alfresco-transform-core already running
apache already running
mariadb already running
tomcat already running

I tried to import ova again, some error, pls help check

thanks

**Comment by gongomgra** [comment]
Hi @yaoxinch,

Thanks for using Bitnami. I was not able to download your bndiagnostic bundle. Can you recreate it and share the new code with us? Regarding the error you are facing, it looks like it is something internal to Alfresco. Can you open a question in the official Alfresco forums, where someone with more knowledge about the application can help you?

**Comment by yaoxinch** [comment]
I did the diagnostic again:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

a5c47897-ec92-54d8-07f3-288ca8754417

and I try to install the office Alfresco with their alfresco-ansible-deployment script, after install ,no same error, the display in Category Manager is normal. so I can not submit the issue on Alfresco forum, so pls help check your instance, maybe something error in your packages, I had tried 2 version's ova , same issue existed.
 Due to install app use your one click is better than others, all packages in one directory and easy to control, so pls help solve this issue.
 thanks very much.

**Comment by yaoxinch** [comment]
btw, the issue seems is solar search problem,  the alfresco's version installed by alfresco-ansible-deployment is 7.1, but now your website is only the latest version to download (7.2) i can not compare it, cloud you give me a latest 7.1 OVA's download link , let me test it? compare with official alfresco version.

**Comment by gongomgra** [comment]
Hi @yaoxinch,

I'm afraid none of us in the team were able to download the new bndiagnostic bundle either. Please find below the download link for the latest Alfresco 7.1 virtual-machine we published. Let us know if it works for you

https://downloads.bitnami.com/files/stacks/alfresco/7.1.0-1-16/bitnami-alfresco-7.1.0-1-16-r90-linux-debian-10-x86_64-nami.ova

**Comment by yaoxinch** [comment]
Hi
 I downloaded the 7.1 version and try, seems it is normal under "Category Manager", but there is another issue, when you upload a MS office doc, like doc, excel,ppt, the preview is not work, show " Could not load PDF content ", but it is works with alfresco-ansible-deployment's version. 
if you can not help solve these problem, I am very sorry can not use your package.
thanks

**Comment by gongomgra** [comment]
Hi @yaoxinch,

Thanks for your message. We do not include the Alfresco Office Services by default in our images, but you can install it following the guide below

https://docs.bitnami.com/aws/apps/alfresco/configuration/install-plugins-aos/
