### ISSUE TITLE
[edX] Can't find open edx document.

### ISSUE THREAD

**Issue by KongFuPandaa** [bitnami/vms#498]
### Describe your issue as much as you can

https://docs.bitnami.com/virtual-machine/apps/edx/#how-to-enable-and-apply-a-custom-theme

i try to open this page , but it's no longer exists, 
need help, thanks really~

**Comment by KongFuPandaa** [comment]
i want the config info about the email and ldap ..
really thanks ..

**Comment by jotamartos** [comment]
We do not have the edX solution in our catalog or provide solution for it anymore. 

Sorry for the inconvenience.

**Comment by KongFuPandaa** [comment]
Dear sir, once before, i see we have this platform document, could you please help find if have some offline version left?
thanks a lot!

**Comment by jotamartos** [comment]
There is an archived version of that website [here](https://web.archive.org/web/20220516041741/https://docs.bitnami.com/virtual-machine/apps/edx/configuration/install-theme/)
