### ISSUE TITLE
[Bncert-tool] Cannot add SSL cert to Wordpress Lightsail instance

### ISSUE THREAD

**Issue by MihaiTrinca** [bitnami/vms#499]
### Describe your issue as much as you can

Hey ! 

I've created a new instance in Lightsail and added a wordpress site
Attached a static IP to this instance.
In the domain registrar ( outside AWS ) we've added an A record routing traffic to that static IP

When checking on whatismydns and also when typing `nslookup domain_name` in bitnami console we get that staticIP
But when trying to add a ssl certificate using bncert tool we get the error

The domain <domain_name> resolves to a different IP address than the
one detected for this machine, which is '<static_ip>'. Please fix its DNS entries
or remove it.

So even though the instance ( using nslookup ) resolves the domain to the correct staticIp value and even though whatsmydns shows all green ticks ( for both www and non-www domains ) , we get this error when trying to add the certificate.

I then tried to bypass the DNS / domain validation using 
`sudo /opt/bitnami/bncert-tool --perform_public_ip_validation 0 --perform_dns_validation 0` command
But this generated another error

2022/11/18 13:13:27 Could not obtain certificates:
error: one or more domains had a problem:
[domain_name] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 
2a02:2268:ffff:ffff::4: Error getting validation data
Press [Enter] to continue:
[www.domain_name] acme: error: 400 :: urn:ietf:params:acme:error:connection 
:: 2a02:2268:ffff:ffff::4: Error getting validation data

Can you please point me in the right direction? 
THank you !

**Comment by gongomgra** [comment]
Hi @MihaiTrinca,

Thanks for using Bitnami. According to the error message, I'd say the `lego` binary is trying to check `www.your-domain.com` also points to your server IP address. If that's not the case, please update the DNS registry. If you don't want to use the `www.your-domain.com`, please disable the www redirection when running the tool.

**Comment by MihaiTrinca** [comment]
hi @gongomgra  
THank you for your reply.
The problem was that even though in DNS records the IPv4 was set to the one of the LightSail machine
There was an AAAA record with an IPv6 value that was different from the one of the machine
Changing that record to point to the LightSails IPv6 value did the trick

**Comment by gongomgra** [comment]
Hi @MihaiTrinca,

Thanks for the info. We are glad you managed to solve your issue!
