### ISSUE TITLE
[Moodle] Can't access application after enabling a plugin

### ISSUE THREAD

**Issue by Steve2023a** [bitnami/vms#500]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4436cc2a-5a2e-0b10-1674-b2ab43b33bae

### bndiagnostic output

Apache: Got error 'PHP message

### bndiagnostic was not useful. Could you please tell us why?

The guides do not fix my issue

### Describe your issue as much as you can

I installed a plugin that resulted in corrupting access. I think if I can disable plugins I will be able to fix it. However I don't know how to do this for moodle. The only version I can find is:sudo wp plugin deactivate --all for wordpress

**Comment by jotamartos** [comment]
>I installed a plugin that resulted in corrupting access.

We suggest you contact the Moodle's support team to know more about how to fix this. Please note that this is a specific error of the application and the plugin you are using.

https://moodle.org/mod/forum/index.php?id=5
