### ISSUE TITLE
[<moodle>] <HTTP ERROR 500 after update>

### ISSUE THREAD

**Issue by teksukamen** [bitnami/vms#501]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

208c65c7-14b2-8dad-419b-4c79efeb4848

### bndiagnostic output

[Fri Nov 18 15:36:40.565498 2022] [authz_core:error] [pid 3026:tid
139716485572352] [client **ip_address**:38236] AH01630: client denied by server
configuration: /opt/bitnami/phpmyadmin/index.php
 [Fri Nov 18 20:51:19.627126 2022] [core:error] [pid 11120:tid 139917694732032]
[client **ip_address**:43008] AH00126: Invalid URI in request 'bin/sh' 'POST
/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1'
Press [Enter] to continue:
 [Sat Nov 19 02:50:18.142908 2022] [core:error] [pid 18326:tid 139916948240128]
[client **ip_address**:59340] AH00126: Invalid URI in request '.git/config' 'GET
/cgi-bin/.%2e/%2e%2e/.git/config HTTP/1.1'

### bndiagnostic was not useful. Could you please tell us why?

I can't find the error, it's beyond me

### Describe your issue as much as you can

Hello, yesterday I updated moodle 3.11 to moodle 4.0.5, successfully without any error, I browsed the site and everything was perfect, then I tried to activate my theme and before selecting it an error appeared, after each moodle link repeated the same error, finally the whole website went down and it was only showing HTTP ERROR 500, I can see all the services are running

**Comment by gongomgra** [comment]
Hi @teksukamen,

Thanks for using Bitnami. I'm glad the upgrade process worked fine. According to the error messages shared here, and the results of the bndiagnostic tool, I think you may be under a bot attack

```
-----------------------------------
Check performance issues: Count number of requests for the 10 most active IP addresses in the last 100.000 requests
-----------------------------------
Running: tail -n 100000 access_log | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 10 | awk '{print $1}'
In: /opt/bitnami/apache2/logs/

Output:

1640
1216
830
821
316
173
141
126
125
94
```

You can continue checking it, and block their IP address if necessary following the next guide

https://docs.bitnami.com/aws/apps/wordpress-multisite/troubleshooting/deny-connections-bots-apache/

**Comment by teksukamen** [comment]
Hola Gonzalo, gracias por responder, podría ser, he ejecutado esa línea y veo los siguientes resultados:

bitnami@xxxxxxxx:/opt/bitnami/apache2/logs$ tail -n 10000 access_log | awk '{print $1}'| sort| uniq -c| sort -nr| head -n 10
     68 *.*.*.*
     16 *.*.*.*
     16 *.*.*.*
     12 *.*.*.*
      9 *.*.*.*
      8 *.*.*.*
      8 *.*.*.*
      6 *.*.*.*
      5 *.*.*.*
      5 *.*.*.*

y se me hace raro que esto suceda justo después de actualizar, literalmente a los 2 minutos, a moodle 4.0.5. Puedo regresar a la versión anterior activando mi backup, pero me preocupa que esto vuelve a pasar, repito, no se presentó ningún error en la actualización, seguí las indicaciones de este enlace](https://docs.bitnami.com/aws/apps/moodle/administration/upgrade/)  y todo bien, que podría ser?

**Comment by gongomgra** [comment]
Hi @teksukamen,

Thanks for your message. Although many of our team members are located in Spain and are able to read and write messages in Spanish, we ask you to use English here in GitHub so other members from the Bitnami community can both help with your questions and get answers in case they face the same issue in the future.

As mentioned in my previous message, it looks like your website is under a bot attack. It must be related to the bots looking for the updated version of Moodle to start their actions. Did you find if you are under a bot attack? And in that case, did you block the bot's IP address?

**Comment by gongomgra** [comment]
Hi @teksukamen,

Thanks for your message and don't worry for the Spanish message. I'm glad using the `4.0.5` version is working for you. We recommend you to check your question with the official Moodle developers, as it seems to be something related to their latest version (as you described).
