### ISSUE TITLE
[Redmine] <How to access adminPHP /migrate database>

### ISSUE THREAD

**Issue by Dariusz1989** [bitnami/vms#502]
### Describe your issue as much as you can

Hello

I'm setting up new vm server to learn a linux / redmine a bit better.
I wanted to copy my database over to the new server but naturally, most of my pws/logins don't work anymore. 
I wanted to find out what is the admin URL for Redmine database so I can try my luck there in copying over my data.

Does any1 know the url ?

I also tried with mysqldump -A -u root -p > backup.sql
but that just gives me permission denied, so I'm hoping to do it via gui somehow...

Regards
Dariusz

**Comment by gongomgra** [comment]
Hi @Dariusz1989,

Thanks for using Bitnami. Please find my comments in-line

> I wanted to copy my database over to the new server but naturally, most of my pws/logins don't work anymore.

I don't fully understand this sentence. You have to export your database from your old server, and then import it in your new server. For the new server database credentials, you have to use the password generated in the `/home/bitnami/bitnami_credentials` file

https://docs.bitnami.com/aws/faq/get-started/find-credentials/#option-2-find-credentials-by-connecting-to-your-application-through-ssh

I'm also sharing the tutorial for import/export a database using the command-line

https://docs.bitnami.com/aws/apps/wordpress/administration/backup-restore-mysql-mariadb/

> so I'm hoping to do it via gui somehow...

Regarding phpMyAdmin, I'm afraid we are not including it in our current Redmine cloud images or virtual-machines, but you can install it on your own following the next steps

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

**Comment by Dariusz1989** [comment]
Hello
Thanks for the links! Yep that gave me pw, still failing to log in somehow, and I thought Redmine shipped with phpadmin on AWS... uhh bad memory!

In any case. I used your script to generate a FULL backup & loaded it in my new linux.
sudo apt install mariadb-server mariadb-client
and used phpadmin to import.

Sadly it overwrites root/etc user passwords/etc. Luckily I managed to make new user rootX and give it privileges so I can keep access ( started this process 5x today) 

In any case, when I load your backup this command no longer works > 
```
SET PASSWORD FOR 'root'@localhost = PASSWORD("fancyPassword");
```
Nor I can change password for user bn_redmine.

```
MariaDB [(none)]> SET PASSWORD FOR 'bn_redmine'@'localhost ' = PASSWORD('fancyMe1');
ERROR 1133 (28000): Can't find any matching row in the user table
```
Any idea how to fix this? Something tells me I'm porting old redmine aws (4.x from last year) to never mariadb and that somehow wreck havoc everywhere.

So far I was able to make "NEW" users and "recreate" their privilages. Gonna try installing redmine next and see if I can patch over the db to work with it. Fingers cross!

**Comment by gongomgra** [comment]
Hi @Dariusz1989,

Thanks for your message. In the past we included phpMyAdmin in our Redmine images, but we removed it some months ago.

> Sadly it overwrites root/etc user passwords/etc. Luckily I managed to make new user rootX and give it privileges so I can keep access ( started this process 5x today)

I'm afraid I don't fully understand this. What passwords do you mean it overwrites? Once you import the Redmine data to your new database host, you should be able to log into Redmine with the email/password you used on your previous server (the one you exported the Redmine data from).

> Any idea how to fix this? Something tells me I'm porting old redmine aws (4.x from last year) to never mariadb and that somehow wreck havoc everywhere.

You must be importing the Redmine data from a very old version of Redmine and this may be causing your errors. We recommend you to ask in the official Redmine support forums for help on how to proceed with this upgrade process.

https://www.redmine.org/projects/redmine/boards
