### ISSUE TITLE
[Wordpress] Website not resolving

### ISSUE THREAD

**Issue by AxelPina** [bitnami/vms#503]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5a27d7bf-6799-9575-a14e-bb8592230a10

### bndiagnostic output

Was not provided by the tool

### bndiagnostic was not useful. Could you please tell us why?

The new tool did not provide a description of the possible issues like other versions did

### Describe your issue as much as you can

Website setup:

- AWS LightSail LB
- AWS Wordpress $20 tier instance
- AWS LightSail MySQL Database, $30 tier

Yesterday I was working on the website at home and it was running perfectly fine ans resolved even after tests. Noticeable changes I made that maybe could've been the reason:

- Installed Defender, with default settings used in previous sites
- created .htaccess file, and added a line from Defender to not allow remote .php execution

Today I come into work and the website doesn't resolve in our network, I've whitelisted the website before cause this happened slightly and it resolved and I was able to access it from here. Now I can't...I've tried on mobile data, on different machines, on a separate network from the ISP. I tried another ISP and it did resolve. I also tried through VPN and the website is not reachable anymore.

**Comment by gongomgra** [comment]
Hi @AxelPina,

Thanks for using Bitnami. I only see one error in your Apache logs related to plugins, but I don't know if this can be causing your errors resolving your website, can you check it? I have been able to visit your website without errors

```
[Sun Nov 20 00:54:36.707463 2022] [proxy_fcgi:error] [pid 408135:tid 140380217382656] [client IP_ADDRESS:42064] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/bitnami/wordpress/wp-includes/Requests/Cookie/Jar.php:63\nStack trace:\n#0 /opt/bitnami/wordpress/wp-includes/Requests/Cookie/Jar.php(15): FluentMail\\App\\Services\\Mailer\\Providers\\AmazonSes\\Handler->FluentMail\\App\\Services\\Mailer\\Providers\\AmazonSes\\{closure}()\n#1 /opt/bitnami/wordpress/wp-includes/class-requests.php(146): require_once('...')\n#2 /opt/bitnami/wordpress/wp-includes/class-wp-http.php(459): Requests::autoloader()\n#3 /opt/bitnami/wordpress/wp-includes/class-wp-http.php(352): WP_Http::normalize_cookies()\n#4 /opt/bitnami/wordpress/wp-includes/class-wp-http.php(615): WP_Http->request()\n#5 /opt/bitnami/wordpress/wp-includes/http.php(179): WP_Http->post()\n#6 /bitnami/wordpress/wp-content/plugins/ninja-forms/includ...', referer: https://www.timeart.org.do/wp-admin/options-general.php?page=fluent-mail
```
