### ISSUE TITLE
[WordPress] HTTP 403/Sorry, you are not allowed to access this page. When Navigating to Theme Options Page

### ISSUE THREAD

**Issue by dagohbah** [bitnami/vms#506]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

380da2e0-ce28-5bf3-818e-16082d5619b2

### bndiagnostic was not useful. Could you please tell us why?

N/A

### Describe your issue as much as you can

I am trying to install a theme and edit its settings (Angora Theme). I can install the theme successfully, and activate/install the plugins it needs. However, when navigating to `http://server-IP-goes-here/wp-admin/admin.php?page=theme-options&tab=1` it throws an error _Sorry, you are not allowed to access this page._ and, I cannot access the theme settings I should be able to in the admin area (the shortcut for the theme settings is missing and can't navigate to it).

I have tried the following troubleshooting steps:
- Checked all of the main areas folder permissions (wp-content, wp-admin, wordpress folder as a whole, etc.)
- Checked the wp-config.php and admin.php file permissions
- Tried modifying .conf files
- Tried enabling debugging and other options in wp-config file
- Tried disabling and removing all plugins
- Tried building a brand new Lightsail instance from scratch with the default theme, still could not access the theme options

Please let me know how I can help troubleshoot!

**Comment by gongomgra** [comment]
Hi @dagohbah,

Thanks for using Bitnami. I checked your bndiagnostic bundle and I found a lot of PHP errors related to WordPress. Can you review them? The file is located at `/opt/bitnami/apache2/logs/error_log. Apart from that, the bndiagnostic tool found PHP errors trying to retrieve the information of your themes. Find the error messages below

```
-----------------------------------
Get the list of WordPress installed themes
-----------------------------------
Running: wp theme list --format=csv
In: /opt/bitnami

Output:

name,status,update,version
angora,inactive,none,2.3
twentytwentytwo,active,none,1.3
PHP Deprecated:  Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63
```

We recommend you to ask the theme developers about this error and also open a new question in the official WordPress forums for further help on this

https://wordpress.org/support/forums/

**Comment by dagohbah** [comment]
Hey there @gongomgra!

Thanks for the quick reply on this. I have been in communication with the theme author who helped me try all the various fixes above, as well as AWS, who couldn't help a ton, even with business tier support.

The error_log is a jumbled mess with no carriage returns - even in notepad++. Is there a good way to format/clean this file up?

There should only be two themes installed at this time...Angora, which is not active, and the default 2022 WP theme, which is active. Is RMCCUE something that Bitnami has installed on the image by default, or no?

**Comment by gongomgra** [comment]
Hi @dagohbah,

Thanks for your message. I launched a fresh new server and I couldn't find the `rmccue` folder mentioned in your error message.

```
ssh bitnami@IP_ADDRESS
Warning: Permanently added '34.155.160.119' (ED25519) to the list of known hosts.
Linux bitnami-wordpress-dc73 5.10.0-19-cloud-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
       ___ _ _                   _
      | _ |_) |_ _ _  __ _ _ __ (_)
      | _ \ |  _| ' \/ _` | '  \| |
      |___/_|\__|_|_|\__,_|_|_|_|_|

  *** Welcome to the WordPress packaged by Bitnami 6.1.1-2            ***
  *** Documentation:  https://docs.bitnami.com/google/apps/wordpress/ ***
  ***                 https://docs.bitnami.com/google/                ***
  *** Bitnami Forums: https://github.com/bitnami/vms/                 ***
Last login: Wed Nov 23 12:26:58 2022 from IP_ADDRESS
bitnami@bitnami-wordpress-dc73:~$ cd /opt/bitnami/wp-cli/
bitnami@bitnami-wordpress-dc73:/opt/bitnami/wp-cli$ find . -type d -name rmccue
bitnami@bitnami-wordpress-dc73:/opt/bitnami/wp-cli$
```

Regarding the error log lines, notice they start with the `[date] [module/method] [pid] [client] error-message` format, where `error-message` is the error from PHP. Unfortunately, we can't control them.

**Comment by dagohbah** [comment]
OK; thanks for that extra info! I appreciate that! If I spin up a new instance and try to navigate to the theme-options URL, it doesn't work for me there either out of the box with a default theme activated. Are you seeing the same behavior on your new server as well? Maybe this is more than just a custom theme issue.

**Comment by gongomgra** [comment]
Hi @dagohbah,

I'm afraid I can't reproduce your issue in a fresh new image (WordPress version 6.1.1). I see in your bndiagnostic bundle your are using a previous version. Can you try with the latest version as well?

![Screen Shot 2022-11-25 at 16 36 12](https://user-images.githubusercontent.com/6660452/204017425-fa5597fd-420a-48fd-b667-900a2d264792.png)

**Comment by dagohbah** [comment]
Sure! 6.1.1 is done as of now, here's the page I'm going to and what I'm seeing.

http://44.202.111.39/wp-admin/admin.php?page=theme-options&tab=1

![image](https://user-images.githubusercontent.com/42973853/204029246-e9f429e2-eb6b-4ff1-8e34-34802e5f8b26.png)

**Comment by gongomgra** [comment]
Hi @dagohbah,

Thanks for your message. I think this is a feature of the theme itself. I tried installing different themes and any of them added a different list of "sub-menus" when you activate it. If you have questions regarding that specific theme, we recommend you to open a new ticket in the official WordPress forums or with the theme's developers

https://wordpress.org/support/forums/

**Comment by dagohbah** [comment]
Thank you for testing this out. I've pursued the author on this already.
