### ISSUE TITLE
Bitnami Wordpress Google Cloud VM - How do you upgrade the php version?

### ISSUE THREAD

**Issue by xgaibtcgd** [bitnami/vms#507]
### Describe your issue as much as you can

Hello,

I have a bitnami wordpress image running on google cloud.  What is the recommended steps for upgrading php versions?  I can't find this anywhere in the docs so maybe someone can point me to it, or let me know the steps.  

Much appreciated

**Comment by gongomgra** [comment]
Hi @xgaibtcgd,

Thanks for using BItnami. Unfortunately, upgrading PHP version in our images is not possible. You will have to launch a fresh new server including the newer PHP version and then migrate the WordPress data into it

https://docs.bitnami.com/aws/how-to/migrate-wordpress/

**Comment by jayenashar** [comment]
> Bitnami certified images are always up-to-date, secure, and built to work right out of the box.

**Comment by gongomgra** [comment]
Hi @jayenashar,

Thanks for your message. We publish a new image with updated components like Apache, MySQL, PHP, and others, as soon as it is published in the upstream projects. However, it is not possible to update the internal components installed by us in cloud images. For these solutions you will have to launch a fresh new server and migrate your application data. 

It is possible to upgrade our components in a easier way using our container solutions, which include a logic to automatically import the persisted information from a volume. However, please take into account you may find some issues trying to upgrade between major versions or if the upstream developers introduced any breaking change.
