### ISSUE TITLE
[LAMP] Enable PHP Extentions

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#508]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

27f0021e-d236-b2ed-d4df-b430ba3010a4

### bndiagnostic output

```
===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.

 total used free shared buff/cache available Mem: 975 626 83 112 266 90 Swap: 
634 469 165

You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:
[Apache]

Found recent error or warning messages in the Apache error log.

[Mon Nov 21 14:55:34.204372 2022] [core:error] [pid 665:tid 140642143409920] 
[client **ip_address**:57470] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
 [Tue Nov 22 01:11:09.621305 2022] [access_compat:error] [pid 70876:tid 
140641983948544] [client **ip_address**:51044] AH01797: client denied by server 
configuration: /opt/bitnami/apache/htdocs/


Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====
```

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

Hi,
I am facing certain issues. I need certain extensions enabled on my instance.
**List of my current extensions on BlueHost:**
`Core PDO PDO_ODBC Phar Reflection SPL SimpleXML SourceGuardian Zend OPcache bcmath bz2 calendar ctype curl date dom exif fileinfo filter ftp gd gettext gmp hash iconv imagick imap intl ionCube Loader json libxml litespeed mbstring mysqli mysqlnd odbc openssl pcre pdo_mysql pdo_pgsql pdo_sqlite pgsql posix pspell session soap sockets sqlite3 standard tidy tokenizer xml xmlreader xmlrpc xmlwriter xsl zip zlib`

**List of my current extensions on AWS:**
`Core PDO Phar Reflection SPL SimpleXML Zend OPcache bcmath bz2 calendar cgi-fcgi ctype curl date dom exif fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap libxml mbstring mysqli mysqlnd openssl pcntl pcre pdo_mysql pdo_sqlite posix readline session soap sockets sodium sqlite3 standard tidy tokenizer xml xmlreader xmlwriter xsl zip zlib`

I want the same extensions which are there on my BlueHost to be enabled on AWS. 

Also when I run the `sudo apachectl status` command, I get the below error.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/10163650/203241599-9d2d1b99-7e99-4c0f-8a2a-08bd5750521f.png">

Kindly help.

**Comment by jotamartos** [comment]
We have a guide here where we explain how to install some PHP modules on top of a running LAMP instance

https://docs.bitnami.com/general/infrastructure/lamp/configuration/install-modules-php/

However, please note that we didn't document all of them, so you will need to take a look at the official documentation of the module to know how to install it. Please note that if the module requires to compile PHP adding support for it, it'll become a complex process.

**Comment by huzanf** [comment]
Thanks @jotamartos 

Also can you please help with this:
Also when I run the sudo apachectl status command, I get the below error.
![image](https://user-images.githubusercontent.com/10163650/203911789-7a5ce7d2-6087-4a68-bdc7-e047880b8609.png)

**Comment by huzanf** [comment]
Hi @jotamartos 
I am trying to install IonCube basis of the documentation and I am getting the below error
![Uploading image.png…]()

Kindly support

**Comment by jotamartos** [comment]
To get the status of the service, please use the ctlscript.sh file 

```
sudo /opt/bitnami/ctlscript.sh status
```

Regarding the permission error, you do not have permissions to write in that directory. Move to a different directory before downloading the package. Please note that this is a very basic question regarding how to use the terminal and the permissions configuration. If you need help when working with that, please find someone in your community who can help you run the different commands to install the extension.
