### ISSUE TITLE
Can't find bitnami-docker-dolibarr project

### ISSUE THREAD

**Issue by eldy** [bitnami/vms#51]
### Describe your issue as much as you can

The Dolibarr ERP CRM application is available on bitnami since a long date:
https://bitnami.com/stack/dolibarr

My understanding is that you are moving your packaging on this repo ? If i am right, how can i find the one for Dolibarr ?

**Comment by eldy** [comment]
> Hi @eldy,
> 
> We provide VMs and cloud images for Dolibarr but we do not build container images for it. You can launch the solution either locally or in any of the major cloud providers as usual but we moved the support platform to this GitHub repository.

So you mean only only containers images are available as github project ? So the repo 
https://github.com/bitnami/vms
is in fact 
https://github.com/bitnami/container
May be you can rename it.

A mention in the README like this:
This repo contains sources for:
[X] container images
[] Cloud image
[] VM images

**Comment by jotamartos** [comment]
The container images information are currently published in different repos (one per solution). For example:

https://github.com/bitnami/bitnami-docker-wordpress
https://github.com/bitnami/bitnami-docker-dokuwiki

We do not have container for Dolibarr, so there is no repo for it. If you are using a Bitnami container image, our team provides support in each of those repositories.

The https://github.com/bitnami/containers repo is progress right now as explained in the README but it'll be used in the future. As I mentioned above, you still need to use the repos for every solution to get support.

This repo, https://github.com/bitnami/vms, is only used to provide support to all those users who have questions when using our VMs/cloud images. If you are using the Bitnami Dolibarr solution in the cloud, you will need to create an issue in this repo to get support. 

Is this clear now?
