### ISSUE TITLE
Moodle 4:Exception - Class 'mod_assign_renderer' not found

### ISSUE THREAD

**Issue by CHRISTOFORIDIS-CH** [bitnami/vms#511]
<html>
<body>

So i am trying to create a new user in my course but i am getting the following exception.
![Screenshot_1](https://user-images.githubusercontent.com/61056058/203550949-a1313571-0ab2-46f1-93b8-cd240564b78e.png)

My moodle version is moodle-4.0.4 and i am using the bitname installer.I have done nothing else, i just finished successfully the download,created a course and tried to add a new user.

(Note. Unfortunately, the more information Link wasn't especially helpful. "A general error occurred (sorry we can't be more helpful here!)")

</body>
</html>

**Comment by gongomgra** [comment]
Hi @CHRISTOFORIDIS-CH,

Thanks for using Bitnami. It seems it is not an issue related to the Bitnami Moodle image itself but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure, we highly recommend checking forums and user guides made available by the project behind the application or the technology.

https://moodle.org/mod/forum/index.php?id=5

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
