### ISSUE TITLE
[Redmine] How to install plugins with Gemfile issues

### ISSUE THREAD

**Issue by kolonuk** [bitnami/vms#516]
### Describe your issue as much as you can

Fresh install of Bitnami Redmine 5.0.3-4
Trying to install a few plugins, for example https://www.redmine.org/plugins/redmine_checklists
Using the instructions https://docs.bitnami.com/installer/apps/redmine/configuration/install-plugins/

When getting to "bundle install", the following error appears:
```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated ../../../../opt/bitnami/redmine/Gemfile.lock to version control.

If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze 
by running `bundle config unset deployment`.

The dependencies in your gemfile changed

You have added to the Gemfile:
* redmine_crm
```

Searching yields suggestions from a developer viewpoint - fix your gem file. However, I'm not a developer and have no idea what to do here.  The plugin install documentation doesn't specify anything on how to solve this. This happens on a number of plugins.

[This post ](https://www.redmine.org/boards/2/topics/66681)describes a potential way to get round this, but I have no idea what unsetting the deployment means and the consequences.

Can the documentation be updated to reflect what to do in this situation - it's not just this plugin!

**Comment by kolonuk** [comment]
To add, the first section of the documentation is incorrect also - 
`Before running the commands shown on this page, you should load the Bitnami stack environment by executing the installdir/use_APPNAME script `

The "use_APPNAME" script doesn't exist any more.

**Comment by jotamartos** [comment]
> To add, the first section of the documentation is incorrect also -
> Before running the commands shown on this page, you should load the Bitnami stack environment by executing the installdir/use_APPNAME script
> 
> The "use_APPNAME" script doesn't exist any more.

The guide you posted is related to the installers. That banner doesn't appear in the VM-related guide 

https://docs.bitnami.com/general/apps/redmine/configuration/install-plugins/

The error you are getting when installing a gem is something related to the ruby/gem functionality. Please take a look at the ruby/gem documentation to know how to proceed or ask the developers of the plugin to help you install the plugin you are trying to add to the deployment.
