### ISSUE TITLE
[bncert-tool] SSL validation while 3rd party CDN enabled

### ISSUE THREAD

**Issue by mumarazam** [bitnami/vms#517]
### Describe your issue as much as you can

The scenario is;
I have configured Wordpress instance on AWS Lightsail.
The static IP is attached with the domain name via A record at Ezoic DNS management.
Cloudflare is proxied via Ezoic (CNAME autoconfigs are used).
Nameservers issued by cloudflare is used at a domain name provider.
DNS lookup tools shows cloudflare IPs.

My approach 01: using bncert-tool:
sudo /opt/bitnami/bncert-tool

Warning: The domain 'name.com' resolves to a different IP address than the 
one detected for this machine, which is '0.123.456.78'. Please fix its DNS 
entries or remove it.

My approach 02:
 /opt/bitnami/bncert-tool --perform_public_ip_validation 0 --perform_dns_validation 0

An error occurred creating certificates with Let's Encrypt:

2022/11/23 22:36:23 [INFO] [domain.com, www.domain.com] acme: Obtaining 
bundled SAN certificate
2022/11/23 22:36:23 [INFO] [domain.com] AuthURL: 
https://acme-v02.api.letsencrypt.org/acme/authz-v3/179722783567
2022/11/23 22:36:23 [INFO] [www.domain.com] AuthURL: 
https://acme-v02.api.letsencrypt.org/acme/authz-v3/179722783577
2022/11/23 22:36:23 [INFO] [domain.com] acme: use tls-alpn-01 solver
2022/11/23 22:36:23 [INFO] [www.domain.com] acme: use tls-alpn-01 solver
2022/11/23 22:36:23 [INFO] [domain.com] acme: Trying to solve TLS-ALPN-01
2022/11/23 22:36:29 [INFO] [www.domain.com] acme: Trying to solve TLS-ALPN-01
2022/11/23 22:36:32 [INFO] Deactivating auth: 
https://acme-v02.api.letsencrypt.org/acme/authz-v3/179722783567
2022/11/23 22:36:32 [INFO] Deactivating auth: 
https://acme-v02.api.letsencrypt.org/acme/authz-v3/179722783577
2022/11/23 22:36:32 Could not obtain certificates:
error: one or more domains had a problem:
[domain.com] acme: error: 400 :: urn:ietf:params:acme:error:tls :: 
99.83.241.49: remote error: tls: no application protocol
[www.domain.com] acme: error: 400 :: urn:ietf:params:acme:error:tls :: 

# The question is how can I install SSL when bitnami host is behind the CDN? If Let'sEncrypt is not possible then how can I install existing SSL or puchased SSL with cloud configuration enabled?

**Comment by jotamartos** [comment]
Hi @mumarazam,

bncert works in most of the scenarios but it doesn't work in some specific ones. As you found, the tool validates the domain using the A records and does not check the CNAME or other parameters in the domain. In this case, I suggest you directly use the lego command line tool to generate your certificate.

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

Lego is a Let's Encrypt client that allows you many customizations depending on your configuration. 

https://github.com/go-acme/lego/

It's support team can help you during the process of generating the SSL certificate. You can later follow our guide to link the certificates with Apache.

**Comment by dibend** [comment]
I'm having this issue
