### ISSUE TITLE
Open Port 3306 For Database Replication Across Environments

### ISSUE THREAD

**Issue by ryanallandorn** [bitnami/vms#518]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

327b709a-376c-51f4-7adf-25dddf3e7bdc

### bndiagnostic output

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

The ports is the issue

### Describe your issue as much as you can
I'm using [LAMP packaged by Bitnami][1] (Bitnami LAMP 7.4.33) on AWS

What I want to accomplish: Open up port 3306 so that I can set up database replication across environments. More specifically I want to be able to run something like the following:
`sudo ufw allow from {{replica_server_ip}} to any port 3306`

My issue, I can't seem to figure out how the firewall is set up. The Environment seems to be telling me that UFW is installed, but it seems like the environment just uses AWS Security Groups out-of-the-box (and UFW is not installed). I have read:

 - [Connect To MySQL From A Different Machine][2]
 - [Using firewall][3]
 - [Open Or Close Server Ports][4]

My Question:

 1. Do I even need to run UFW or is AWS 'Security Groups' existing as my firewall?
 2. What is the best way for me to open port 3306 to another server? 

Other Info: 

 - Bitnami's AMI uses Debian GNU/Linux 11 (bullseye)
 - I have two AWS instances both running the exact same stack

Steps I've taken

 1. As per [Bitnami's documentation][4], I run the following to see what firewall is installed `sudo which nft >/dev/null && echo nftables is enabled in this system || echo ufw is enabled in this system`
 2. The above outputs `ufw is enabled in this system`
 3. Then I run `sudo ufw status`, but that returns `sudo: ufw: command not found`
 4. So, then I `run sudo dpkg -s ufw`, which tells me `pkg-query: package 'ufw' is not installed and no information is available`
 5. I tried going the `sudo apt-get install ufw -y` route, but then I have to add port 80 & 443 back (i.e. `ufw enable 80`)

This is where I stopped because it seems odd that I would have to reopen those ports again, when there were initially open (i.e. there was 'some' firewall doing that I'm guessing)

A few additional notes:

 1. I added my replica IP for port 3306 in my AWS Security Group in addition to UFW
 2. I've installed telnet, and when I ping my origin server from my replica server I get (i.e. `sudo telnet {{replica_server_ip}} 3306` returns `telnet: Unable to connect to remote host: Connection timed out`

  [1]: https://aws.amazon.com/marketplace/pp/prodview-6g3gzfcih6dvu
  [2]: https://docs.bitnami.com/virtual-machine/infrastructure/mysql/administration/connect-remotely-mysql/
  [3]: https://docs.bitnami.com/aws/faq/administration/use-firewall/
  [4]: https://docs.bitnami.com/virtual-machine/faq/administration/use-firewall/

**Comment by gongomgra** [comment]
Hi @ryanallandorn,

Thanks for your question. `ufw` is only needed in the virtual-machines you can run on your local computer (what we provide as `.ova` files). For AWS cloud, you only need to follow the steps in the guide you linked, and open the 3306 port in the AWS console firewall. Please, remove `ufw` from your AWS server, or launch a new server and try again.

https://docs.bitnami.com/virtual-machine/infrastructure/mysql/administration/connect-remotely-mysql/

I launched a fresh new server and I was able to remotely connect to it following the steps in the guide above. Beware of replacing the `PASSWORD` placeholder with your correct database password. As shown below, I was able to connect from a different computer to the remote MariaDB database server.

```
root@db6d6ef4cd22:/# curl myip.bitnami.com; echo ""
80._REDACTED_.61

root@db6d6ef4cd22:/# nc -zv 204._REDACTED_.114 3306
Connection to 204._REDACTED_.114 3306 port [tcp/*] succeeded!

root@db6d6ef4cd22:/# mysql -h _204.REDACTED_.114 -p -u root
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7
Server version: 10.6.11-MariaDB Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```
