### ISSUE TITLE
[Bitnami Wordpress Multisite Google Cloud] How to edit bitnami-ssl.conf

### ISSUE THREAD

**Issue by JohnZanni** [bitnami/vms#519]
### Describe your issue as much as you can

I have a SSL certificate from Digicert. I have uploaded the key and crt files to /home/jz. I need to change bitnami-ssl.conf to point to the right files but I cannot get access.

how to I install a Digicert ov ssl certificate with the following in the conf file:
<VirtualHost 192.168.0.1:443>
    DocumentRoot /var/www/html2
    ServerName www.yourdomain.com
        SSLEngine on
        SSLCertificateFile /path/to/your_domain_name.crt
        SSLCertificateKeyFile /path/to/your_private.key
        SSLCertificateChainFile /path/to/DigiCertCA.crt
    </VirtualHost>

**Comment by mdhont** [comment]
The following guide explains how you can configure Apache to use an existing certificate:

https://docs.bitnami.com/aws/apps/wordpress/administration/enable-https-ssl-apache/
