### ISSUE TITLE
[NGINX Open Source packaged by Bitnami on AWS Marketplace] Upgrade to NGINX Open Source packaged by Bitnami new version

### ISSUE THREAD

**Issue by aantoniotech** [bitnami/vms#52]
I have the following case and I wanted to see if you could help me find a solution.  

I have some EC2 Instances that are in AWS and currently AWS tells me that there is an update to the Bitnami NGINX 1.22.0-1-r01 package and the 1.18 package is currently on the Instances and I wanted to see if there was the possibility of updating without having to create a new instance and migrate everything.

¿Is there a way to update the packaged from the terminal?

**Comment by jotamartos** [comment]
Hi @aantoniotech,

Thank you for using Bitnami. If you are using a Bitnami NGINX cloud image, the only way to upgrade it is by launching a new instance with the latest version of the solution and migrate the data. 

Thanks
