### ISSUE TITLE
Cancel "deploy mampstack to the cloud in One Click" during installation

### ISSUE THREAD

**Issue by JKjoni** [bitnami/vms#520]
### Describe your issue as much as you can

Last time I installed "bitnami-mampstack-8.1.12-0", I might have accidentally let "Launch mampstack in the cloud with Bitnami" checked.(screencut attached). Two quick questions:

1. Will it incur any "pay-as you go" charges as mentioned in the following Readme link? And how to cancel it?
https://bitnami.com/stack/mamp/README.txt

2. I didn't activate any service or having an account with Bitnami/AWS as mentioned the in the below link. Can I assume that I didn't activate the cloud service and wouldn't receive any bill in this case? 
https://docs.bitnami.com/aws/get-started-launchpad/

<img width="501" alt="Screen Shot 2022-11-25 at 5 34 29 AM" src="https://user-images.githubusercontent.com/50604534/203892379-77c626c1-b0e2-4b3b-88e0-cc41d744f838.png">

**Comment by jotamartos** [comment]
>Will it incur any "pay-as you go" charges as mentioned in the following Readme link? And how to cancel it?
https://bitnami.com/stack/mamp/README.txt

No, that option simply opens the browser to let you know the benefits of launching MAMP (or LAMP) in the cloud

> I didn't activate any service or having an account with Bitnami/AWS as mentioned the in the below link. Can I assume that I didn't activate the cloud service and wouldn't receive any bill in this case?
> https://docs.bitnami.com/aws/get-started-launchpad/

Correct! The installers are not linked to any cloud account/service so you will not be charged for that.

**Comment by JKjoni** [comment]
Many thanks for the reply.
