### ISSUE TITLE
[Bncert tool] Generate a certificate using shell script (1 line command)

### ISSUE THREAD

**Issue by elad-cloudan** [bitnami/vms#521]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

999bf8dc-4a09-55f2-690f-68f88703fb34

### bndiagnostic was not useful. Could you please tell us why?

It didn't return an error.

### Describe your issue as much as you can

I want to run bncert tool using a remote shell script hence, I need a 1 line command with all the arguments set and avoid the dialog process. 
Something like `sudo /opt/bitnami/bncert-tool --domains abc.net --enable_https_redirection 1 --enable_nonwww_to_www_redirection 0`
I tried setting unattendedmodeui and different installation modes but that didn't help. 

Please advise, 
Thanks!

**Comment by mdhont** [comment]
Did you try adding `--mode unattended` as a parameter?

**Comment by elad-cloudan** [comment]
I have yes and it didn't work, perhaps the syntax was wrong - any chance you share a sample syntax? 
Thanks!

**Comment by elad-cloudan** [comment]
it says `Unattended mode is not supported yet. Please use --mode text or --mode gui instead.`

**Comment by Cojad** [comment]
Please try "expect" as alternate solution for now since unattended mode isn't ready yet.
https://likegeeks.com/expect-command/
