### ISSUE TITLE
Wordpress Bitnami in AWS lightsail kswapd0 high cpu

### ISSUE THREAD

**Issue by Aldebaran23** [bitnami/vms#522]
On the $10 instance, the kswapd0 process occupies 100% of the cpu. I tried to change the value vm.swappiness=0 but the problem is always there. Are there any suggestions on how to fix this?
Kernel version: 5.10.0-19-cloud-amd64
Linux: Debian GNU/Linux 11 (bullseye)

**Comment by mdhont** [comment]
I recommend asking in a general forum, I found the following thread about this issue:

https://askubuntu.com/questions/259739/kswapd0-is-taking-a-lot-of-cpu
