### ISSUE TITLE
[<LAMP>] Can't locate pagespeed on my instance

### ISSUE THREAD

**Issue by huzanf** [bitnami/vms#523]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e76eca24-c892-0839-f243-7d901206425e

### bndiagnostic output

```
===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Apache: No issues found
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.

 total used free shared buff/cache available Mem: 975 594 80 141 301 90 Swap: 
634 380 254

You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
 
Press [Enter] to continue:

===== End of bndiagnostic tool output =====
```

### bndiagnostic was not useful. Could you please tell us why?

pagespeed is not installed on my lamp instance.

### Describe your issue as much as you can

Hi,

I cannot see the pagespeed installed on my PHP 8 instance. Kindly support.
<img width="619" alt="image" src="https://user-images.githubusercontent.com/10163650/204128551-f9fa6780-c3f0-4a91-94c8-54efcdba9f05.png">

**Comment by mdhont** [comment]
Unfortunately mod_pagespeed is no longer compiled with our Apache and Nginx solutions.
