### ISSUE TITLE
Why Bitnami not support other cloud?

### ISSUE THREAD

**Issue by williamgh2019** [bitnami/vms#524]
### Name and Version

https://bitnami.com/stack/wordpress-pro/cloud 6.1.1

### What is the problem this feature will solve?

AWS or Google or Microsoft is higher cost, we are small start up need other low cost cloud linux.
I really need WORDPRESS WITH NGINX AND SSL PACKAGED BY BITNAMI can be installed on other cloud linux.

### What is the feature you are proposing to solve the problem?

Need WORDPRESS WITH NGINX AND SSL PACKAGED BY BITNAMI installer or pack to other cloud.

### What alternatives have you considered?

Linode or DigitalOcean is prefer.

**Comment by jotamartos** [comment]
Hi @williamgh2019,

Thank you for your interest. However, we can only offer the solution in the clouds where it's available right now 

https://bitnami.com/stack/wordpress-pro/cloud

Alternatively, if you want to deploy WordPress with NGINX, you can use our container offering to deploy it

https://github.com/bitnami/containers/tree/main/bitnami/wordpress-nginx

**Comment by williamgh2019** [comment]
😞 i request to Linode ready to corporate with Bitnami. Hope it work in the future.
