### ISSUE TITLE
[WordPress] Is there a way to restore wordpress instance back to its fresh original state?

### ISSUE THREAD

**Issue by night-01** [bitnami/vms#525]
### Describe your issue as much as you can

I tried restoring a wordpress backup file thru the SSH terminal , along doing so, some sudo commands are not working( such as sudo opt/bitnami/ctlscript.sh start

And accessing the website admin page is also not possible (shows Forbidden
You don't have permission to access this resource.) 

I definitely messed something up, hence just want to ask if there's a way to restore the wordpress application instance back to its original state.

**Comment by jotamartos** [comment]
The easiest way to do so is by launching a fresh instance with WordPress. That way, you will also benefit from the update of all the components included in the solution.
