### ISSUE TITLE
Bitnami-Parse How can I set up email adapter

### ISSUE THREAD

**Issue by buddhika-senevirathna** [bitnami/vms#527]
### Describe your issue as much as you can

I am really new to Parse environment. But I have set up Bitnami parse server successfully in the AWS. When I am trying to Reset user passwords I am calling to the below end point,
``` Parse.User.requestPasswordReset ```
For that I am getting below error when I am checking my logs
``` {"error":{"code":1,"message":"An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality."}} ```

I tried to setup different mail adapters but details are failed to help me. Most of the tutorial says need to update ```index.js``` but I did not find a index.js. Please share any tutorial or advice on this.

**Comment by mdhont** [comment]
I recommend asking in a Parse community forum, they will be able to help you further.
