### ISSUE TITLE
[mautic] Problem after update on 2022-11-29, system has not been booted with systemd as init system (pid 1). can't operate

### ISSUE THREAD

**Issue by edudesouza** [bitnami/vms#528]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0757872b-caae-0834-e9c6-d8d4a9dda44b

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.

    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

not related

### Describe your issue as much as you can

2022-11-29 there was an update on GCP, I think this might get some relation

Atfer a reboot no service was online so I tried to start it manualy:

sudo /opt/bitnami/ctlscript.sh start

I got an error message:

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by edudesouza** [comment]
![image](https://user-images.githubusercontent.com/177087/204847766-b0e565cc-d59b-45ab-b83b-57122499fea6.png)

**Comment by edudesouza** [comment]
Hi there any clue ... we did not installed nothing recently ...
This server is critial to us becase it host all our marketing campaigns, as a result, we had to freeze all campaign on Google and Meta

**Comment by edudesouza** [comment]
Is therte a way to rever this update?

**Comment by jotamartos** [comment]
>2022-11-29 there was an update on GCP, I think this might get some relation

Please note that we publish new versions in GCP frequently but servers do not auto-update. If you want to update the app, you need to manually perform the upgrade process (if the app supports it) or migrate your data to a new instance. 

In your case, if you didn't do anything, I do not know what could have happened. Did you try to restart the server completely and check if the issue is resolved?

**Comment by edudesouza** [comment]
Sure I did that  and noticed that the initialisation was changend

**Comment by jotamartos** [comment]
> initialisation was changend

What do you mean with that?  Is the issue resolved now?
