### ISSUE TITLE
[Wordpress Multiuser] LAMP Stack stops with high load

### ISSUE THREAD

**Issue by unibrain1** [bitnami/vms#529]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e319a6fb-e338-d533-ae7e-c916512168d2

### bndiagnostic output

    ✓ Resources: No issues found
    ✓ Connectivity: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Useful - Followed guides give

### Describe your issue as much as you can

At approximately 2022-11-30 18:21:45 when running a job to rebuild images via wordpress, the system became unresponsive.  When performing  sudo /opt/bitnami/ctlscript.sh status apache, mariadb, and php-fpm were stopped.   I can reproduce the issue by restarting the stack and restarting the image rebuild job.  AWS shows an increase in CPU and disk activity but I do not see and AWS errors.

**Comment by mdhont** [comment]
I recommend upgrading your instance to a more powerful one. The following guide might also be of help:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/optimize-bitnami-wordpress/

**Comment by unibrain1** [comment]
I can do that.  Two questions:  
- Is there any indication where there is a resource constraint? (CPU, Memory, I/O)
- Why didn't the processes restart after they crashed?  Is there a configuration I missed or messed up that prevented the restart?  I thought GONIT should have restarted the services? "Gonit continuously monitors server status. When a service goes down, Gonit automatically initiates the recovery of the affected services."
