### ISSUE TITLE
[WordPress Multisite] Using pre-existing WP.org account?

### ISSUE THREAD

**Issue by uscbandwebmasters** [bitnami/vms#530]
### Describe your issue as much as you can

Hi, I'm a new webmaster taking over an archaic website and was looking into using WP Multisite to make a new website while keeping the old WP one up, but I can't figure out how to log into the preexisting WP account on Multisite. Instead, the new admin account is the default user one? Is that something I have to stick with?

**Comment by uscbandwebmasters** [comment]
So I can't use a different WordPress.org account login?

**Comment by mdhont** [comment]
I recommend asking in the Wordpress.org forum:

https://wordpress.org/support/
