### ISSUE TITLE
[WordPress on AWS LightSail ] <SSL certificate pointing to an old IP address>

### ISSUE THREAD

**Issue by qasimolaa** [bitnami/vms#532]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

 af481d78-c1a5-6506-ab80-389942a45241

### bndiagnostic output

SSL certificate pointing to different IP address

### bndiagnostic was not useful. Could you please tell us why?

Not related

### Describe your issue as much as you can

Hello there,

I recently move my WordPress website with SSL certificate installed to a different instance on AWS Lightsail but when I want to generate a new SSL certificate for the new IP address issued using the old domain name from the previous instance, but it's returning an error and the domain name is still pointing to the old IP address.

Please kindly assist me with what to do.

**Comment by mdhont** [comment]
You need to change the A record to point to the new IP address. Please contact your DNS provider for further information.
