### ISSUE TITLE
[Prestashop] Unable to connect to IP address / gonitrc missing

### ISSUE THREAD

**Issue by bgschust** [bitnami/vms#534]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d7db7f2d-3f0e-8b02-ed7e-9e7df02a3e6f

### bndiagnostic output

No issues found.

### bndiagnostic was not useful. Could you please tell us why?

It did not find the issue.

### Describe your issue as much as you can

I enter the IP address found using sudo ifconfig and it does not show up.

**Comment by bgschust** [comment]
I also have bndiagnostic ID 4e9052cf-0d1e-32f2-8d8e-6921db1d05e0 showing Apache errors.

**Comment by bgschust** [comment]
I'm trying to connect through VMware Workstation on Windows 10 Pro. I installed an older version of Bitnami Prestashop and the only errors I can find (aside from the website not showing up) are PHP errors in the Apache error logs.

**Comment by mdhont** [comment]
The machine seems low on RAM memory, try increasing the available resources.
