### ISSUE TITLE
[Sonarqube] Upgrade bitnami-sonarqube-8.4.1.35646-0-linux-debian-10 to bitnami-sonarqube-8.9.10-10-r11-linux-debian-11

### ISSUE THREAD

**Issue by Sudarshan-TN** [bitnami/vms#537]
### Describe your issue as much as you can

Hi, I want to upgrade my sonarqube server from 8.4.1 (Approach B (Self-contained Bitnami installations)) to 8.9.10 and I followed https://docs.bitnami.com/aws/apps/sonarqube/administration/upgrade/ approach when I restart the server sonarque is not starting 
am getting the following message in the logs:
sonar.log
> 2022.12.08 09:11:10 INFO  app[][o.e.p.PluginsService] no modules loaded
2022.12.08 09:11:10 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2022.12.08 09:11:29 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2022.12.08 09:11:29 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/bitnami/apps/sonarqube/sonarqube]: /opt/bitnami/java/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/bitnami/apps/sonarqube/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -server -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/common/*:/opt/bitnami/apps/sonarqube/sonarqube/lib/jdbc/postgresql/postgresql-42.2.6.jar org.sonar.server.app.WebServer /opt/bitnami/apps/sonarqube/sonarqube/temp/sq-process14524984020873214643properties
2022.12.08 09:11:34 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2022.12.08 09:11:34 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2022.12.08 09:11:34 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
2022.12.08 09:11:34 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
<-- Wrapper Stopped

Hosted on AWS

**Comment by Sudarshan-TN** [comment]
yes am trying to upgrade all the components.

bitnami@ip:~$ /opt/bitnami/bndiagnostic-tool
-bash: /opt/bitnami/bndiagnostic-tool: No such file or directory

**Comment by Sudarshan-TN** [comment]
My source application (bitnami-sonarqube-8.4.1.35646-0-linux-debian-10) is of type B (Self-contained Bitnami installations)

**Comment by mdhont** [comment]
You can download it:

```
$ wget -O bndiagnostic-linux-x64.run https://downloads.bitnami.com/files/bndiagnostic/latest/bndiagnostic-linux-x64.run
$ chmod a+x bndiagnostic-linux-x64.run
$ sudo ./bndiagnostic-linux-x64.run
```

**Comment by Sudarshan-TN** [comment]
d9476cca-bc06-fe57-4bd9-5642285bc1c0

**Comment by Sudarshan-TN** [comment]
===== Begin of bndiagnostic tool output =====


    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ✓ Apache: No issues found

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend trying to upgrade the machine and then try the update.
