### ISSUE TITLE
[WordPress Multsite] how to make .htaccess file writable for WP Import Export?

### ISSUE THREAD

**Issue by johocen168** [bitnami/vms#538]
### Describe your issue as much as you can

Hi there,
According to this document...
https://docs.bitnami.com/general/apps/wordpress/administration/use-htaccess/
"Some plugins, during their installation, create a .htaccess file in either the /opt/bitnami/APPNAME/ or in the /opt/bitnami/apps/APPNAME/plugins/ directory "

But .htaccess is not found in either the /opt/bitnami/wordpress/ or /opt/bitnami/apps/wordpress/plugins/ after WP Import Export Lite is installed. 

Manually created .htaccess in the /opt/bitnami/wordpress/ with 776 still see the warning...
"WP Import Export : If your .htaccess file were writable, we could do this automatically, but it isn’t. So you must either make it writable or manually update your .htaccess with the mod_rewrite rules found under WP Settings >> Permalinks. Until then, the exported and imported files are not protected from direct access."

Failed to import web_story_media_source editor
Failed to import web_story_media_source gif-conversion
Failed to import web_story_media_source page-template
Failed to import web_story_media_source poster-generation
Failed to import web_story_media_source source-image
Failed to import web_story_media_source source-video
Failed to import web_story_media_source video-optimization
Media “” already exists.

Thanks for your help.

**Comment by mdhont** [comment]
Bitnami installation's do not use .htacess files. You need to add the htaccess rules to the wordpress-htaccess.conf file, as described in the guide.

**Comment by johocen168** [comment]
seems quite complicate, thanks
