### ISSUE TITLE
MariaDB Error

### ISSUE THREAD

**Issue by BharathVasireddy** [bitnami/vms#542]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

028b1430-06f7-c5fd-a8fa-9c62ab3b93da

### bndiagnostic output

✓ Resources: No issues found
    ✓ Connectivity: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

Error establishing database connection.

**Comment by BharathVasireddy** [comment]
Hey any Idea how can I get out of this error?

Thanks

**Comment by mdhont** [comment]
Could you give more detailed information? Which application are you running, on which platform etc? Is it a new instance?

**Comment by BharathVasireddy** [comment]
WordPress running on AWS EC2 t3a.Xlarge instance

It has been running smooth since 3-4 months
