### ISSUE TITLE
[<Wordpress>] <title>Wordpress White Screen

### ISSUE THREAD

**Issue by ogbetaeric** [bitnami/vms#543]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b2c08348-3a7a-b624-19f0-14ac9bc9c424

### bndiagnostic output

```
[Mon Dec 12 16:51:31.950908 2022] [proxy_fcgi:error] [pid 1042:tid 
140497154561792] [client **ip_address**:58540] AH01071: Got error 'PHP message: 
PHP Fatal error: Uncaught TypeError: strpos(): Argument #1 ($haystack) must be 
of type string, array given in /opt/bitnami/wordpress/wp-includes/blocks.php:20
Stack trace:
Press [Enter] to continue:
#0 /opt/bitnami/wordpress/wp-includes/blocks.php(20): strpos()
#1 /opt/bitnami/wordpress/wp-includes/blocks.php(84): 
remove_block_asset_path_prefix()
#2 /opt/bitnami/wordpress/w

### bndiagnostic was not useful. Could you please tell us why?

The Guidelines are relevant to issue

### Describe your issue as much as you can

Wordpress White Screen.

This happens when I was updating my AWS Lightsail Wordpress Plugin, I got something like Database error, which resulted to White Screen with this Message:

There has been a critical error on this website. Please check your site admin email inbox for instructions.

**Comment by mdhont** [comment]
Could you check the available resources? 

    free -h
    df -m

**Comment by ogbetaeric** [comment]
Good day.
I don't understand ; free -h
df -m.

And also, I don't understand, what you meant by  other available resources.
Where can I found it.

**Comment by mdhont** [comment]
Sorry for not explaining. It seems to me that the server instance you are running WordPress on is low on RAM memory (probable) or out of disk space (less probable). You can check the available RAM memory by executing the following command on your server. I've checked the bndiagnostic data and that seems to be the case:

```
Running: free -m
In: /opt/bitnami

Output:

              total        used        free      shared  buff/cache   available
Mem:            987         430          79          46         476         364
Swap:           634           0         634
```
                      
I recommend upgrading your instance to a more powerful one. If that's not possible I recommend disabling some WP plugins.

**Comment by ogbetaeric** [comment]
It is Plugin update that trigger this issues. I should have enough Memory space. Just few post and Plugins on it.
Now, how do I Disable Plugin, since I can not access my Wordpress Dashboard.

**Comment by mdhont** [comment]
You can use the wp-cli:

      $ wp plugin deactivate PLUGIN_NAME

**Comment by ogbetaeric** [comment]
Ok
