### ISSUE TITLE
[WordPress Multisite] Frequent site down with AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error

### ISSUE THREAD

**Issue by jcummings68** [bitnami/vms#544]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

378be8ab-8455-19d4-8d4a-f44b0e1aaf00

### bndiagnostic output

 ✓ Php: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found

### bndiagnostic was not useful. Could you please tell us why?

I am not sure what the above-mentioned details reference

### Describe your issue as much as you can

I seem to randomly get usage spikes and the site will also go offline. After a period, it comes back online but is often very slow to load.

**Comment by mdhont** [comment]
It seems likely due to a plugin PHP script. I recommend disabling all plugins and then activate them one by one to see which one is causing the issue.

**Comment by jcummings68** [comment]
Ok, thanks I disabled most of the plugins as I was working through the site yesterday. There are still a couple that could potentially be the root of this challenge. Thanks for the feedback. I will reply back with the results after I finish that.
