### ISSUE TITLE
REDASH BITMANI DB2

### ISSUE THREAD

**Issue by SIAPL2023** [bitnami/vms#546]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1f5ae743-e0d2-02ce-aff0-eff1d49a5ad8

### bndiagnostic was not useful. Could you please tell us why?

1f5ae743-e0d2-02ce-aff0-eff1d49a5ad8

### Describe your issue as much as you can

REDASH IMAGE DO NOT INCLUDE DB2 DATASOURCE.``

**Comment by mdhont** [comment]
Please be more detailed in the description of the issue.

**Comment by SIAPL2023** [comment]
is not in list when i have to choose datasource

**Comment by mdhont** [comment]
Could you be more specific? What are you trying to do? Could you describe the steps?
