### ISSUE TITLE
[Wordpress] How to upgrade php form 7.3 to 8.0

### ISSUE THREAD

**Issue by emad973** [bitnami/vms#547]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

I don't have it

### bndiagnostic was not useful. Could you please tell us why?

everything is fine but I want to upgrade to latest version

### Describe your issue as much as you can

I can't upgrade the PHP

**Comment by jotamartos** [comment]
There are multiple questions like this one already in the forum. Please take a look at this one for example 

https://github.com/bitnami/vms/issues/507

Thanks
