### ISSUE TITLE
[LAMP] Unattended installation

### ISSUE THREAD

**Issue by akinuri** [bitnami/vms#55]
I'm migrating a recent [question](https://community.bitnami.com/t/unattended-lamp-installation/106415) from the community site.

> I often create new (Lightsail) instances and upgrade the LAMP stack (from 7.4 to 8). Doing this manually is starting to become troublesome.
> 
> The first thing I want to automate is the installer. I searched for a documentation on the unattended installation, but could not find one. Tried the --help command, but that also didn't help much. Is it possible to do the installation silently? I do not want to repeat the inputs to Varnish, Zend, …, install_dir, etc. every time I upgrade.
> 
> What else do I need to add to the unattended code to match it to the following manual installation?
> 
> ```sudo ./installer.run --mode unattended --enable-components phpmyadmin```
> 
> Manual installation:
> 
> ```
> ----------------------------------------------------------------------------
> Welcome to the LAMP packaged by Bitnami Setup Wizard.
> ----------------------------------------------------------------------------
> Select the components you want to install; clear the components you do not want 
> to install. Click Next when you are ready to continue.
> Varnish [Y/n] :n
> Zend Framework [Y/n] :n
> Symfony [Y/n] :n
> CodeIgniter [Y/n] :n
> CakePHP [Y/n] :n
> Smarty [Y/n] :n
> Laravel [Y/n] :n
> PhpMyAdmin : Y (Cannot be edited)
> Is the selection above correct? [Y/n]: y
> --------------------------------------------------------------------------
> Installation folder
> Please, choose a folder to install LAMP packaged by Bitnami
> Select a folder [/opt/lampstack-8.0.20-0]: /opt/bitnami
> ----------------------------------------------------------------------------
> Create MySQL 'root' Account
> LAMP packaged by Bitnami database root user creation
> Password :
> Re-enter :
> ----------------------------------------------------------------------------
> Setup is now ready to begin installing LAMP packaged by Bitnami on your 
> computer.
> Do you want to continue? [Y/n]: y
> ----------------------------------------------------------------------------
> Please wait while Setup installs LAMP packaged by Bitnami on your computer.
>  Installing
>  0% ______________ 50% ______________ 100%
>  #########################################
> ----------------------------------------------------------------------------
> Setup has finished installing LAMP packaged by Bitnami on your computer.
> Launch LAMP packaged by Bitnami [Y/n]: y
> ```
> The missing parts (that I notice) are the Installation folder and the MySQL account. I’m not sure which parameters correspond to these.

**Comment by akinuri** [comment]
I had a response to this today, and I wanted to reply, but since the site is in read mode, I couldn't.

The response:

![Screenshot 2022-06-30 183945](https://user-images.githubusercontent.com/13146977/176719296-29c592b4-5cfd-4d33-b91a-9895185b24a3.png)

**Comment by akinuri** [comment]
I took a look at it, and still it's not that explanatory. I mean, I have to do trial and error to see if it works.

If I were to list the issues:

* I want to do a clean installation (no components). `phpmyadmin` is automatically selected as seen in the above manual installation output (`PhpMyAdmin : Y (Cannot be edited)`). This is not mentioned in the help text of the installer. Do I still have to use `--enable-components phpmyadmin` in the command?
* I suppose `--prefix <prefix>` means the installation dir. Again, the help text doesn't help with this.
* In the manual installation, theres this `Create MySQL 'root' Account` text. I just enter the password. The user is automatically set to `root`. However, in the help text, it says the default  for ` --base_user <base_user>` is `Default: user`. In this case, don't I also need to use `--base_user root`?
* What is the relation among these `base_password`, `mysql_password`, `mysql_database_password`, `phpmyadmin_password`? Does `base_password` set a password for all of them (if they are not set individually)?

Shouldn't these be documented? A user having to figure out these by himself/herself would be huge waste.

I request that the help text be edited/improved (or the text can include a url that redirects to an improved documentation).

Output of the related parameters from the help text:

```
 --enable-components <enable-components>    Comma-separated list of components
                                            Default: varnish,zendframework,symfony,codeigniter,cakephp,smarty,laravel,phpmyadmin
                                            Allowed: varnish zendframework symfony codeigniter cakephp smarty laravel phpmyadmin

 --prefix <prefix>                          Select a folder
                                            Default: 

 --base_user <base_user>                    Login
                                            Default: user

 --base_password <base_password>            Password
                                            Default: 

 --mysql_password <mysql_password>          MariaDB Server root password
                                            Default: 

 --mysql_database_password <mysql_database_password>   DB User Password
                                                       Default: 

 --phpmyadmin_password <phpmyadmin_password>           
                                                       Default: 
```

**Comment by jotamartos** [comment]
> I want to do a clean installation (no components). phpmyadmin is automatically selected as seen in the above manual installation output (PhpMyAdmin : Y (Cannot be edited)). This is not mentioned in the help text of the installer. Do I still have to use --enable-components phpmyadmin in the command?

As you saw when launching the installer, phpMyAdmin is selected by default so it'll be selected and installed no matter if you include it in the enable-components parameter or not.

>I suppose --prefix <prefix> means the installation dir. Again, the help text doesn't help with this.

Correct! Prefix is the installation dir.

>In the manual installation, theres this Create MySQL 'root' Account text. I just enter the password. The user is automatically set to root. However, in the help text, it says the default for --base_user <base_user> is Default: user. In this case, don't I also need to use --base_user root?

In the LAMP solution, that parameter won't change anything. The default user for MySQL is root and you can use base_password to set the password.

>What is the relation among these base_password, mysql_password, mysql_database_password, phpmyadmin_password? Does base_password set a password for all of them (if they are not set individually)?

Please note that phpMyAdmin works with the MySQL's credentials, there are not different ones for it. So you just need to specify the base_password parameter to configure MySQL and then use root/password when accessing the database using those credentials.

>Shouldn't these be documented? A user having to figure out these by himself/herself would be huge waste.

I'm sorry but as you may know, we removed the majority of the native installers and focused on containers, charts and VMs. We are not going to work on improving the documentation of those parameters but if you have any questions, you are always welcome! :)

**Comment by akinuri** [comment]
I see. Now, I have other concerns :)

This might be a new question/issue, but about this "removal of native installers", how will this affect AWS services (Lightsail, to be specific)?

When I create a new instance, I see a LAMP (PHP 7.4.29-0) option there. Since the current version of PHP is above 8, I usually (manually) download and install the recent stack. How will this process be affected by this removal?

If I follow the links in the LAMP pages, [Installer](https://bitnami.com/stack/lamp/installer) > [Cloud](https://bitnami.com/stack/lamp/cloud), I end up in the [VM](https://aws.bitnami.com/launch/lampstack) page. Not sure how it works yet, but since this seems like a new panel/launcher (with different pricing options too), does it mean that AWS Lighsail will be obsolete soon or later? Will I have to migrate all of my instances?

**Comment by jotamartos** [comment]
>This might be a new question/issue, but about this "removal of native installers", how will this affect AWS services (Lightsail, to be specific)?

We removed the native installers, but not the cloud images/VMs

>When I create a new instance, I see a LAMP (PHP 7.4.29-0) option there. Since the current version of PHP is above 8, I usually (manually) download and install the recent stack. How will this process be affected by this removal?

We still maintain LAMP so you can continue doing the same. As an alternative, you can launch a LAMP 8.x VM in AWS or deploy it locally using the OVAs and copy the /opt/bitnami and /bitnami folders to the Lightsail instance to have PHP 8.x

https://docs.bitnami.com/aws/infrastructure/lamp/administration/backup-restore/

>If I follow the links in the LAMP pages, [Installer](https://bitnami.com/stack/lamp/installer) > [Cloud](https://bitnami.com/stack/lamp/cloud), I end up in the [VM](https://aws.bitnami.com/launch/lampstack) page. Not sure how it works yet, but since this seems like a new panel/launcher (with different pricing options too), does it mean that AWS Lighsail will be obsolete soon or later? Will I have to migrate all of my instances?

The Lightsail team is in charge of updating the solutions in the platform. They use the solutions we publish in the AWS Marketplace but they update them from time to time not every time we update our solutions. As I mentioned before, we remove support for the native installers but OVAs and VMs will continue being supported.
