### ISSUE TITLE
Bitnami - Wordpress | File permission Errors for Apache, Maria DB

### ISSUE THREAD

**Issue by poptrek** [bitnami/vms#550]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e90707f4-4808-1b22-0042-5362f46666ac

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1982 1353 94 76 534 385 Swap: 
1024 324 700
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:Enter

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Dec 14 09:33:54.317271 2022] [proxy_fcgi:error] [pid 2499797:tid 
139669886809856] [client **ip_address**:61022] AH01079: failed to make 
connection to backend: httpd-UDS
Press [Enter] to continue:
 [Wed Dec 14 09:33:56.282091 2022] [proxy:error] [pid 2499797:tid 
139669861631744] (13)Permission denied: AH02454: FCGI: attempt to connect to 
Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Wed Dec 14 09:33:56.282128 2022] [proxy_fcgi:error] [pid 2499797:tid 
139669861631744] [client **ip_address**:64774] AH01079: failed to make 
connection to backend: httpd-UDS

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I followed the instruction for reseting permission for Apache and Maria DB and it's still not working

### Describe your issue as much as you can

I followed the instruction for reseting permission for Apache and Maria DB and it's still not working.

**Comment by gongomgra** [comment]
Hi @poptrek,

Thanks for using Bitnami. It looks like your server is running out of resources and no new processes can be started. Please upgrade your instance type to get some free memory available

```
-----------------------------------
Display amount of free and used memory in the system
-----------------------------------
Running: free -m
In: /opt/bitnami

Output:

               total        used        free      shared  buff/cache   available
Mem:            1982        1353          91          76         537         384
Swap:           1024         324         700
```
