### ISSUE TITLE
[Spark Operator] Not able to use Bitnami docker images with Spark Operator

### ISSUE THREAD

**Issue by JTBS** [bitnami/vms#551]
### Describe your issue as much as you can

I want to use Bitnami Spark images on Kubernetes (Using Spark Operator approach)
1. Tried usinghttps://hub.docker.com/layers/bitnami/spark/3.2.3/images/sha256-e663832b4c27f0e7daa6afa6c7e69675fb806ca0cad0f65710c85807de5dfc00?context=explore
2. Tried to use above as my base image for my Docker file and added additional application code
3. When I try to submit SparkApplication through Spark Operator, I get below error:
4.   StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
       StandaloneAppClient$ClientEndpoint: Failed to connect to master 
5. Please NOTE: All works fine, if I change base image to: apache/spark-py:v3.2.1

I am not sure if there are any environment settings I need to set - to get Bitnami work with Spark-Operator approach on Kubernetes.

Please NOTE; I am not looking for spark-submit approach to work on Kubernetes - rather - I am trying to use Spark Operator to submit my Spark Applications. It not clear how to get Bitnami images get to work

I used Data Mechanics and Apache Spark images without any issue.

Please help

**Comment by JTBS** [comment]
Hi,
I was able to get this further by adding below environment variable in my Pod YAML.
- name: SPARK_MASTER_URL
        value: "k8s://spark-master:7077"
That seems to now switch Spark from Stand-alone to K8s env

Now my driver and executor pods are starting. However executor pods are not able to run - due to below error:
   18:31:56.71 
   18:31:56.71 Welcome to the Bitnami spark container
   18:31:56.71 Subscribe to project updates by watching https://github.com/bitnami/containers
   18:31:56.71 Submit issues and feature requests at https://github.com/bitnami/containers/issues
   18:31:56.71 
    **/opt/bitnami/scripts/spark/entrypoint.sh: line 51: exec: executor: not found**

**Comment by JTBS** [comment]
Looking further on this, problem seems like entrypoint.sh script provided with Bitnami image
Original entrypoint.sh file reference in comments has "executor" section:
https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/entrypoint.sh

But one copied to Bitnami image has only "driver" case statement and missing "executor" case statement.

Fact that Bitnami images work in Kubernetes env, I am not sure if I should dig so much.

Any help is appreciated

**Comment by jotamartos** [comment]
Hi,

Thank you for using Bitnami. This VMs repository only hosts questions related to the Bitnami VMs and cloud images. Your question is related to the Bitnami charts so please post the question in the proper repository

https://github.com/bitnami/charts/issues

Thanks

**Comment by JTBS** [comment]
@jotamartos Thanks for getting back. I don't think this is chart related issue. This issue is related to using Bitnami image with Kubernetes using Spark Operator. Image itself is missing part of script for "executor" in entrypoint.sh - for Bitnami - compared to Apache Spark entrypoint.sh

Also any other Docker image: Apache Spark or Data Mechanics Spark images - work as-is out of box in Spark Operator env. Only Bitnami image has this issue.

But I understand your concerns and appreciate your feedback. So I posted this issue on charts link you provided. But it should not happen that they say same thing that issue is not related to HELM charts and its not.

I will leave it up to you to close this issue and link this issue to: https://github.com/bitnami/charts/issues/13974

**Comment by jotamartos** [comment]
Thanks for creating that other ticket. It's true that the issue may be related to the image itself, not the chart, but as you are using the chart, you need to use that other channel to get support.
