### ISSUE TITLE
[Wordpress]How to fix Obsoleted CBC ciphers (AES, ARIA etc.) offered

### ISSUE THREAD

**Issue by shukamu95** [bitnami/vms#555]
### Describe your issue as much as you can

Hello guys,

I received a security report from company that i work about "Obsoleted CBC ciphers (AES, ARIA etc.)            offered" 

How to fix this? I found https://ssl-config.mozilla.org/#server=apache&version=2.4.41&config=intermediate&openssl=1.1.1k&guideline=5.6 that generate SSL Configuration, but don't know here to put on. I try to change /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf and restart, then scan on https://inspect.rapydblok.com and "Obsoleted CBC ciphers (AES, ARIA etc.)            offered" still appear.

**Comment by jotamartos** [comment]
The cipher suites and protocols that Apache accepts are configured in the /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf  file. You can modify those parameters and restart the webserver for the changes to take effect.
