### ISSUE TITLE
[WordPress/Bitnami] Unable to connect to external MySQL databases

### ISSUE THREAD

**Issue by bkh33al** [bitnami/vms#556]
### Describe your issue as much as you can

I created a new instance (Bitnami WordPress) in AWS Lightsail. Everything works fine. I am trying to connect to an external MySQL server (outside of AWS) from this Lightrail instance.

I am using the command:

`mysql -u user_name -h xx.xx.xx.xx -p`

Unfortunately, I am receiving this error message. I am unsure why the Lightrail instance resolves the external IP (outside of AWS) to the local Lightrail instance.

`ERROR 1045 (28000): Access denied for user 'user_name'@'ec2-xx-xx-xx-xx.us-east-2.compute.amazonaws.com' (using password: YES)`

I have performed an extensive search and could not find any similar issues.

FWIW, I have tried to add `skip_name_resolve` to the` my.cnf` file in vain.

I hope someone has run into this situation and was able to find a solution.

I could open a ticket with AWS; however, given that I have a basic account, I cannot place any support calls with AWS. I appreciate your help in advance.

Additional Information: There is a local MySQL instance on the same AWS EC2 (WordPress/Bitnami image) where I am executing the MySQL command. However, the -h argument I provided points to a MySQL server outside AWS. What is puzzling is that the local MySQL server on the AWS EC2 instance is responding to my command despite a non-AWS public IP provided at the command line.

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
