### ISSUE TITLE
[WordPress] Manage/Access MariaDB

### ISSUE THREAD

**Issue by mbisque** [bitnami/vms#557]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2c1bb1b3-55b9-0ab4-7c85-8064c826cb3a

### bndiagnostic was not useful. Could you please tell us why?

Not related

### Describe your issue as much as you can

I need to manage the database on a local VM (bitnami-wordpress-6.1.1-9-r07-linux-vm-debian-11-x86_64-nami) being used as a sandbox server.

I'm getting the following error when attempting to log in through phpMyAdmin:
mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'127.0.0.1' (using password: YES)

Can you help me configure access?

(I am accustomed to using phpMyAdmin to manage the database on an AWS bitnami stack. Does phpMyAdmin work even though the above VM uses MariaDB???  I understand this server is gone, but below is the URL to the "perfect" answer you gave when I had to do the same kind of configuration for an AWS bitnami VM:
https://community.bitnami.com/t/can-not-log-into-mysql-with-root-account-access-denied-for-user-root-localhost/69956)

**Comment by jotamartos** [comment]
Hi @mbisque,

Thank you for using our solution. Can you try accessing the database using this command?

```
mysql -u root -p -h 127.0.0.1
```

I just launched a fresh VM and that command work so you shouldn't have problems to connect to the database. If you continue running into issues, please contact the phpMyAdmin support team.

**Comment by mbisque** [comment]
Thank you, that works.  I needed your expertise and confidence...

I was wrongly using the password for the "bitnami" user, not the password for the wordpress "user".

**Comment by jotamartos** [comment]
Great! To access the database you need to use "root" with the default password we configure during the initialization or the bn_wordpress user and the password configured in the wp-config.php file.
