### ISSUE TITLE
[WordPress] Database error Disk full

### ISSUE THREAD

**Issue by NanaYaw** [bitnami/vms#558]
### Describe your issue as much as you can

"WordPress database error Disk full (/opt/bitnami/mariadb/tmp/#sql_4ba_1.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")."

Im getting the above error saying my "/opt/bitnami/mariadb/tmp/" is full. but when I go to "/opt/bitnami/mariadb/" I don't see any "temp" folder and I have gone through the server no temp folder like that, I have check on the database no table of such.

How can I resolve this issue? Kindly help me out.

**Comment by jotamartos** [comment]
Please note that the plugins/themes you are using may be using the database intensively and that uses space in the disk. You can use the df and du commands of this guide to get more info about the disk usage.

https://docs.bitnami.com/aws/faq/troubleshooting/troubleshoot-server-performance/

Thanks

**Comment by NanaYaw** [comment]
![Screenshot 2022-12-19 at 1 54 27 PM](https://user-images.githubusercontent.com/205193/208442396-2129a4b9-0fea-4e94-8cf7-7f1579acd93b.png)
![Screenshot 2022-12-19 at 1 53 37 PM](https://user-images.githubusercontent.com/205193/208442405-f05844f6-4560-42e2-8043-00d02c81efb2.png)
![Screenshot 2022-12-19 at 2 19 23 PM](https://user-images.githubusercontent.com/205193/208446366-04d84f8f-f71a-409c-a0c6-2e53f59bc8fa.png)

i check and issued the commands above are the results.

Im still getting the error
`WordPress database error Disk full (/opt/bitnami/mariadb/tmp/#sql_4ba_1.MAI); waiting for someone to free some space... (errno: 28 "No space left on device") `

**Comment by NanaYaw** [comment]
Any help? what do I need to do next to bring the server to normal

**Comment by jotamartos** [comment]
You didn't run all the commands that are shown in the link I posted. What about the free disk space or the usage of the /opt/bitnami or /bitnami folder? 

```
df -h
cd /opt/bitnami
du -h -d 1
cd /bitnami
du -h -d 1
```

**Comment by NanaYaw** [comment]
![Screenshot 2022-12-20 at 11 41 14 AM](https://user-images.githubusercontent.com/205193/208675937-67fd2d08-b595-40a2-8ea7-98ce700cb239.png)
![Screenshot 2022-12-20 at 11 41 56 AM](https://user-images.githubusercontent.com/205193/208675946-06929172-7933-41ed-982e-36bfcbf99b87.png)
![Screenshot 2022-12-20 at 11 43 18 AM](https://user-images.githubusercontent.com/205193/208675949-ec2ef10a-1369-4b80-be79-378b568879f8.png)

**Comment by jotamartos** [comment]
You seem to have enough disk space for the database to work. Are you running any action in the application when that error happens or does it just happen automatically? I do not know what's happening here, it's probably WordPress who is working with the database and is trying to store some data there. I suggest you ask in the WordPress' support forums to get more info about how to debug this issue and know more about what the app is trying to store. 

https://wordpress.org/support/

**Comment by NanaYaw** [comment]
It happens automatically.
Okay, I will ask in the WordPress forum.
Thanks much.
