### ISSUE TITLE
What is the time window before upgrades are released (e.g. php 8.1 for the aws lightsail nginx stack)

### ISSUE THREAD

**Issue by HnLn** [bitnami/vms#559]
### Describe your suggestion as much as you can

I'm loving the lightsail nginx stack, configuration is easy and clear and it works like a charm.

But ... after setting up my server, I suddenly discover it's running on php 8.0 (php 8.1 got released a year ago and php 8.2 also got released recently).

So:
- I haven't found any information on software versions inside a package, would have been good if I could have spotted that earlier.
- What is the time window before new versions are released (a year seems a long time ?)
- I can't find any upgrade paths info, once it is release, what would be the best way to upgrade the nginx stack from php 8.0 to 8.1

Still loving the product though, but looks like I need to downgrade my app to php 8.0 for now.

**Comment by jotamartos** [comment]
Hi @HnLn,

Thank you for using Bitnami 

>I haven't found any information on software versions inside a package, would have been good if I could have spotted that earlier.

That's something we can't control. The Lightsail platform is managed by the Lightsail team, you can contact them and share your feedback. 

>What is the time window before new versions are released (a year seems a long time ?)

We update our solutions in batches, but taking into account that PHP 8.0 only receives security updates from now on and that NGINX is a infrastructure solution, I'll create a task to prioritize this update. 

>I can't find any upgrade paths info, once it is release, what would be the best way to upgrade the nginx stack from php 8.0 to 8.1

Once we release a new version with PHP 8.1, you will need to launch a new instance and migrate your data to that new instance. 

Thanks

**Comment by ponkiwonki** [comment]
Hi Jotamartos,

tnx for the reply and tnx for creating the task.

As for software information, I also can't find the php version here https://bitnami.com/stack/nginx/cloud.

A pitty that migrations are required, any plans on using something like the ondrej php ppa ?  That would allow for multiple php versions on the same server.

**Comment by jotamartos** [comment]
You are right, we are not listing the versions of the components included in the solution. I'll share your feedback.

Regarding the PHP update, we just released a new version in the AWS Marketplace and the AWS Console (1.23.3-4-r04) that includes PHP 8.1.x, you can start using it right now :) 

https://aws.amazon.com/marketplace/pp/prodview-lzep7hqg45g7k

For Lightsail, its team takes care of updating the solutions there and it will probably take some time for the new version to be available.

**Comment by ponkiwonki** [comment]
Tnx jotamartos for your quick feedback and excellent news on the release.
