### ISSUE TITLE
[ProcessMaker] PHP exec() issue

### ISSUE THREAD

**Issue by 1eungk** [bitnami/vms#56]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

 4792b768-57cb-88d7-a8a5-476d7cda4ea9

### bndiagnostic output

pdfunite: /opt/processmaker-3.2.1-0/common/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib64/libpng16.so.16)

### bndiagnostic was not useful. Could you please tell us why?

Do not know where to fix the missing / unmatch version  from Bitnami.

### Describe your issue as much as you can

I'm running Bitnami ProcessMaker 3.2.1 on OpenSuSe Leap 15.1.

Debugging information of my PHP program executing in a ProcessMaker trigger are as follows.

```
$doc1Path = /opt/processmaker-3.2.1-0/apps/processmaker/htdocs/shared/sites/workflow/files/658/949/791/62bde58ed8edb6031387589/outdocs/70980437362bde5bb068965026481252_1.pdf;

$doc2Path = /opt/processmaker-3.2.1-0/apps/processmaker/htdocs/shared/sites/workflow/files/658/949/791/62bde58ed8edb6031387589/outdocs/31336435762bde5bb5c1567011102787_1.pdf;

$joinedFilePath = /tmp/joined_34vTZO.pdf;

exec("pdfunite $doc1Path $doc2Path $joinedFilePath", @=aOutput);
ProcessMaker Error Message: Unable to upload joined file '/tmp/joined_34vTZO.pdf' to case.
```

However, an empty file /tmp/joined_34vTZO (without the extension ".pdf") is found in /tmp

On the other hand, there is no problem on executing the command "pdfunite $doc1Path $doc2Path $joinedFilePath" in a console.

**Comment by jotamartos** [comment]
Hi @1eungk ,

Thank you for using our solution. That's a specific question about the application and the dependencies it needs to run so we suggest you ask in the official forums of the application to get more information about that. The app's documentation should also describe how to achieve what you want to, so please take a look at it too. 

However, we will also keep this ticket open in case any Bitnami user configured the application the same way. 

Thanks

**Comment by 1eungk** [comment]
Hi Juan,

I raised the question to Bitnami because the problem is dealing with the 
installer version of Bitnami.
According to the diagnosis, the Bitnami ProcessMaker installation use 
its own library instead of the system library.  However, the Bitnami  
version is not compatible.

If I can be advised where and how can I update the Bitnami library may 
be able to solve the problem.  Please help.

cheers,
Karl

**Comment by jotamartos** [comment]
Updating the zlib library included in the solution will require to build the component from scratch. We do not support ProcessMaker installers anymore so we can't do anything to update that library. 

You can try replacing the library inside the common folder with the one installed in the system, but that will probably cause more issues. We suggest you try the Bitnami ProcessMaker VM to see if the problem is fixed there and migrate your data to the VM if everything works as expected.
