### ISSUE TITLE
[LAMP] ftp

### ISSUE THREAD

**Issue by PDKtnz** [bitnami/vms#560]
### Describe your issue as much as you can

I am moving a production server to this AWS/Lightsail/Bitnami LAMP stack.  I have scripts that download files from a remote ftp server.  I need to do the same on this new instance.   When I type "ftp" to test the service, I get this result:  "-bash: ftp: command not found"

I installed vsftpd, it's running, but get same result.    

So the question, how do I get ftp service running in this instance.  I don't need ftp users or need my instance to listen on any port.  Is this even a bitnami issue?

I tried this example from AWS:  https://aws.amazon.com/premiumsupport/knowledge-center/lightsail-set-up-ftp/

Same error.

**Comment by mdhont** [comment]
FTP is not installed by default on Bitnami instances. I recommend asking in specific or general support fora. I found the following guide:

https://linuxopsys.com/topics/install-vsftpd-ftp-server-on-debian

**Comment by PDKtnz** [comment]
thank you
