### ISSUE TITLE
[WordPress] Download older ova

### ISSUE THREAD

**Issue by blabley** [bitnami/vms#561]
### Describe your issue as much as you can

Greetings, Looking to download an older version than the current **6.1.1-14-r13** which is showing [https://bitnami.com/stack/wordpress/virtual-machine](https://bitnami.com/stack/wordpress/virtual-machine). Ideally, based on [https://bitnami.com/stack/wordpress/vboxdebian-x64-nami/changelog.txt](https://bitnami.com/stack/wordpress/vboxdebian-x64-nami/changelog.txt) I'd like to download **5.9.0-13-r03** anyone know where I can get this version from?

Thanks and keep up the great work!

**Comment by jotamartos** [comment]
Here you are! 

https://downloads.bitnami.com/files/stacks/wordpress/5.9.0-13/bitnami-wordpress-5.9.0-13-r03-linux-debian-10-x86_64-nami.ova

Happy to help!

**Comment by blabley** [comment]
Amazing, cheers!
