### ISSUE TITLE
[WordPress Production Ready] [DBStorageEncrypted] do not exist in the template

### ISSUE THREAD

**Issue by pinteradamn** [bitnami/vms#563]
### Describe your issue as much as you can

When I try to create the stack with AWS CLoudFromation, the following error occours and the stack creation rolls back (if I let it):
**Parameters: [DBStorageEncrypted] do not exist in the template**

The logical ID is: **WordPressStack** and the error is: **CREATE_FAILED**

I tried to make it with different settings and parameters, but nothing seems to work for me. In my opinion, I did not leave a mandatory setting empty, I tried with several EC2 sizes, including the default ones.

Thanks for any suggestion,
Adam

**Comment by jotamartos** [comment]
Hi @pinteradamn,

Sorry to hear that. Could you please contact the AWS support team to know more about this issue. We successfully release the solution some days ago and our tests didn't encounter any error. Please note that we deploy the solution in our pipelines and ensure that it works properly before making it available. They need to review if they didn't copy the information properly on their side. 

Thanks

**Comment by pinteradamn** [comment]
Hello @jotamartos,

Thanks a lot for your guidance. I will contact them too. In the meantime, do you have any other advice?
Is there any chance that this will be fixed later?

Thanks and have a nice day

**Comment by ahmedajaj** [comment]
I have the same issue right now as well :(

**Comment by jotamartos** [comment]
>Thanks a lot for your guidance. I will contact them too. In the meantime, do you have any other advice?

>UPD: so the issue is with version 6.1.1-4-r03 (Nov 30, 2022). When I tried to use 6.0.0.-8-r09 (Jul 11, 2022) everything is working with the same parameters

You can use that previous version to deploy the solution in the meantime.
