### ISSUE TITLE
AWS Lightsail Wordpress IP address indexed by google-

### ISSUE THREAD

**Issue by gecofilms** [bitnami/vms#564]
### Describe your issue as much as you can

Hi there,

I have an issue as google has indexed my website address ip instead of the domain name.

I have made the following change in the htaccess.conf file to add a 403 rewrite for the ip address:

<IfModule rewrite_module.c> 
RewriteEngine On 
RewriteCond %{HTTP_HOST} ^xx.xxx.xxx.xxx$       
RewriteRule . - [R=403,L]
</IfModule>

As I have seen this been advise in this article here: https://support.google.com/webmasters/thread/21853898/ip-address-indexed-on-google-along-with-domain?hl=en

Please can you advise if this is the right steps forwards as I am unsure if this code will have any effect.

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
