### ISSUE TITLE
[Wordpress] Bitnami service failed to start

### ISSUE THREAD

**Issue by Jim-nc** [bitnami/vms#566]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d092d36e-37f9-b1a8-ee3d-12d31744cfde

### bndiagnostic output

    ✓ Apache: No issues found
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

asking to add memory which i did by changing instance type but no result, I move to a T3asmall instance with 1M mem

### Describe your issue as much as you can

When launching Wordpress server using bitnami AMI, I have now an error indicating :

![image](https://user-images.githubusercontent.com/121211047/209053854-510964fc-2cf8-4b27-97fc-fd3eb5fdd9e7.png)

On server side, I obtain the following when restarting services through ctlscript.sh restart:

![image](https://user-images.githubusercontent.com/121211047/209054379-48d34dfc-8041-4240-b8ef-7d314a9a2490.png)

df result :

![image](https://user-images.githubusercontent.com/121211047/209054556-204f1855-35a0-471f-979d-e1fb5b13c77e.png)

I checked certificates but it looks ok, 

![image](https://user-images.githubusercontent.com/121211047/209054790-cfb10112-ca0a-4286-b40f-e2d6f3b4e40d.png)

![image](https://user-images.githubusercontent.com/121211047/209054841-20849692-a711-4675-bef9-3ef0db97c258.png)

Certificates are wildcard and used to work correctly

I do not know where to search

**Comment by jotamartos** [comment]
As the diagnostic tool warned you, your machine is clearly running out of memory. 

```
[Resources]

Your instance has little available RAM memory.

 total used free shared buff/cache available Mem: 464 237 16 9 209 204 Swap: 634 9 625

You could try to increase your instance's memory. Please check your cloud provider's documentation for more information.
```

Please increase the resources of the machine to avoid this performance issue. 

https://docs.bitnami.com/aws/faq/administration/change-server-type/
