### ISSUE TITLE
[Sonarqube] bitnami-sonarqube-8.4.1.35646-0-linux-debian-10 migrate application from Approach B. Self-contained installation to Approach A. Using system packages

### ISSUE THREAD

**Issue by Sudarshan-TN** [bitnami/vms#567]
### Describe your issue as much as you can

Hi I am running bitnami-sonarqube-8.4.1.35646 application, I want to migrate my installation approach from  Approach B. Self-contained installation to Approach A. Using system packages, could you please provide the steps for this migration

**Comment by jotamartos** [comment]
You can follow our documentation to upgrade the solution

https://docs.bitnami.com/general/apps/sonarqube/administration/upgrade/

**Comment by Sudarshan-TN** [comment]
I followed the same page 
The below page guides us to take a backup of Postgres data with this we will get again the same self-contained application 
> Back up the bitnami_sonarqube database as described on the [PostgreSQL ](https://docs.bitnami.com/general/apps/sonarqube/administration/backup-restore/)page.

And If I take only a single database backup I am not able to restore the DB it gives the error

**Comment by jotamartos** [comment]
Sorry, the link to the PostgreSQL backup is this one.

https://docs.bitnami.com/general/apps/sonarqube/administration/backup-restore-postgresql/

You need to create a backup of the bitnami_sonarqube database and then restore it. In case you run into issues when restoring it, please ensure you remove the existing bitnami_sonarqube database in the new deployment before running the psql command as shown there in the guide.
