### ISSUE TITLE
[Wordpress] - mariadb did not start

### ISSUE THREAD

**Issue by carbonnb** [bitnami/vms#569]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7849f526-7fbf-9daf-3ba4-6e9c5dc0f331

### bndiagnostic was not useful. Could you please tell us why?

bndiagnostics didn't display anything

### Describe your issue as much as you can

I was notified that my website was down, and couldn't get it to start back up.

using /opt/bitnami$ systemctl status bitnami.service
I got:
● bitnami.service - LSB: bitnami init script
   Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2022-12-23 15:17:30 UTC; 31s ago
  Process: 1507 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
    Tasks: 11 (limit: 557)
   Memory: 106.3M
   CGroup: /system.slice/bitnami.service
           ├─645 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
           ├─649 php-fpm: pool www
           ├─650 php-fpm: pool www
           ├─651 php-fpm: pool www
           ├─652 php-fpm: pool www
           ├─653 php-fpm: pool www
           ├─654 php-fpm: pool www
           ├─655 php-fpm: pool www
           ├─656 php-fpm: pool www
           ├─657 php-fpm: pool www
           └─658 php-fpm: pool www

Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: mariadb 15:17:30.39 ERROR ==> mariadb did not start
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: 2022-12-23T15:17:30.396Z - error: Unable to perform start operation Export start for mariadb failed with exit code 1
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_bitnami_agent_extra...
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agent...
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welcome_file...
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_credentials_file...
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metadata...
Dec 23 15:17:30 ip-172-26-7-63 systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
Dec 23 15:17:30 ip-172-26-7-63 systemd[1]: bitnami.service: Failed with result 'exit-code'.
Dec 23 15:17:30 ip-172-26-7-63 systemd[1]: Failed to start LSB: bitnami init script.

and then journalctl -xe gave me
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: mariadb 15:17:30.39 ERROR ==> mariadb did not start
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: 2022-12-23T15:17:30.396Z - error: Unable to perform start operation Export start for mariadb failed with exit code 1
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_bitnami_agent_extra...
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agent...
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welcome_file...
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_credentials_file...
Dec 23 15:17:30 ip-172-26-7-63 bitnami[1507]: ## 2022-12-23 15:17:30+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metadata...
Dec 23 15:17:30 ip-172-26-7-63 sudo[1498]: pam_unix(sudo:session): session closed for user root
Dec 23 15:17:30 ip-172-26-7-63 systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit bitnami.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 23 15:17:30 ip-172-26-7-63 systemd[1]: bitnami.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit bitnami.service has entered the 'failed' state with result 'exit-code'.
Dec 23 15:17:30 ip-172-26-7-63 systemd[1]: Failed to start LSB: bitnami init script.
-- Subject: A start job for unit bitnami.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit bitnami.service has finished with a failure.
-- 
-- The job identifier is 397 and the job result is failed.
Dec 23 15:17:50 ip-172-26-7-63 dhclient[429]: XMT: Solicit on eth0, interval 119510ms.
Dec 23 15:19:49 ip-172-26-7-63 dhclient[429]: XMT: Solicit on eth0, interval 121800ms.
Dec 23 15:21:51 ip-172-26-7-63 dhclient[429]: XMT: Solicit on eth0, interval 131910ms.
Dec 23 15:23:05 ip-172-26-7-63 crontab[1782]: (bitnami) LIST (bitnami)
Dec 23 15:23:05 ip-172-26-7-63 crontab[1785]: (bitnami) LIST (bitnami)
Dec 23 15:24:03 ip-172-26-7-63 dhclient[429]: XMT: Solicit on eth0, interval 120150ms.
Dec 23 15:24:43 ip-172-26-7-63 dhclient[342]: DHCPREQUEST for 172.26.7.63 on eth0 to 172.26.0.1 port 67
Dec 23 15:24:43 ip-172-26-7-63 dhclient[342]: DHCPACK of 172.26.7.63 from 172.26.0.1
Dec 23 15:24:43 ip-172-26-7-63 dhclient[342]: bound to 172.26.7.63 -- renewal in 1464 seconds.
Dec 23 15:24:46 ip-172-26-7-63 sshd[1902]: Did not receive identification string from 206.189.160.194 port 49600
Dec 23 15:26:03 ip-172-26-7-63 dhclient[429]: XMT: Solicit on eth0, interval 119650ms.

**Comment by carbonnb** [comment]
I should have also added that no changes have been made to the website in days. It just stopped working this morniing.

**Comment by carbonnb** [comment]
Restored a backup so closing the ticket.

**Comment by jordanenwright** [comment]
Did you ever get an answer to this I have the same issue
