### ISSUE TITLE
[Discourse] Blank Page CORS 

### ISSUE THREAD

**Issue by toomanylogins** [bitnami/vms#57]
### Name and Version

discourse 2.7

### What steps will reproduce the bug?

Installed the vm locally,
Discourse is working using ip address but not on forum.mydomain.com. Blank Page 
Enabled ssh
edit discourse-vhost.conf added ServerName forum.mydomain.com
edit bitnami.conf added rewrite
```
  RewriteEngine On
RewriteCond %{HTTP_HOST} !^forum.mydomain.com$
RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
RewriteRule ^(.*)$ http://forum.mydomain.com$1 [R=permanent,L]
```

### What do you see instead?

CORS problem

![image](https://user-images.githubusercontent.com/6908431/176736036-25c3dc55-d24a-4eeb-a294-52dfee42552e.png)

**Comment by mdhont** [comment]
Did you enable CORS?

https://docs.bitnami.com/ibm/infrastructure/nodejs/administration/enable-cors-nodejs

**Comment by toomanylogins** [comment]
Thanks for reply. Yes I added the domain to CORS. I tried both the bitnami.conf and discourse-https-vhost.conf in vhosts folder same result. Css is ok its the js files that give the error.

**Comment by mdhont** [comment]
Did you try with incognito mode? The browser could be using the cached JS files without crossOrigin attribute.

**Comment by toomanylogins** [comment]
Does this image come with any sort of config control panel similar to webmin or plesk. Thanks

**Comment by mdhont** [comment]
No, Bitnami VMs are configured to work out of the box without having to configure individual components, but we do not add any hosting control panel. We do add PHPMyAdmin for database administration.
