### ISSUE TITLE
[<bitnami_application_password>] <Password does not appear>

### ISSUE THREAD

**Issue by per4mance** [bitnami/vms#570]
### Describe your issue as much as you can

Hello,
Today I noticed after performing a new instance on AWS Lightsail that the password of my new WordPress website does not appear when entering the command "bitnami_application_password".

The installation process worked fine as always, the site connects with LetsEncrypt certificate correctly but I can't enter with credentials because of the missing password. Any solutions?

![24-12-2022_12-31-26](https://user-images.githubusercontent.com/3984555/209433917-93f63958-a038-4d66-9297-abdbc55f5151.jpg)

**Comment by per4mance** [comment]
Hello,
Happy New Year to you all!

Any news about the experience I gained? I still have the problem not to enter my new WordPress website because Bitname does not show the password when entering the command "cat bitnami_application_password", see screenshot below:

![image](https://user-images.githubusercontent.com/3984555/210227095-940cc987-7e74-439e-8417-e5cf99a5acdb.png)

Any help is appreciated very much!

Thank you :-)

**Comment by mdhont** [comment]
The `cat` command shows the contents of any text file. The text file containing the credentials is called  `bitnami_credentials`, so the command should be:

    cat bitnami_credentials

**Comment by per4mance** [comment]
Thank you very much, it seems the command has changed.
