### ISSUE TITLE
[<Bitnami Moodle>] <Service Error - bitnami.service>

### ISSUE THREAD

**Issue by mraghbeerasi** [bitnami/vms#571]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

367a555a-d916-cfba-82af-b6e976bbeffa

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat Dec 24 18:58:53.938330 2022] [proxy_fcgi:error] [pid 16527:tid 
139871592527616] [client **ip_address**:24112] AH01071: Got error 'PHP message: 
PHP Warning: Use of undefined constant boost - assumed 'boost' (this will throw 
an Error in a future version of PHP) in /bitnami/moodle/config.php on line 7'
Press [Enter] to continue:
 [Sat Dec 24 18:58:55.742448 2022] [proxy_fcgi:error] [pid 17219:tid 
139871137900288] [client **ip_address**:16442] AH01071: Got error 'PHP message: 
PHP Warning: Use of undefined constant boost - assumed 'boost' (this will throw 
an Error in a future version of PHP) in /bitnami/moodle/config.php on line 7'
 [Sat Dec 24 18:59:07.756424 2022] [proxy_fcgi:error] [pid 17219:tid 
139871129507584] [client **ip_address**:57608] AH01071: Got error 'PHP message: 
PHP Warning: Use of undefined constant boost - assumed 'boost' (this will throw 
an Error in a future version of PHP) in /bitnami/moodle/config.php on line 7'

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.

A high number of incoming requests originate from one or more unique IP 
Press [Enter] to continue:
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

System Apache is running:
```
root 5004 0.0 2.0 285540 41388 ? Ss 21:00 0:00 /usr/sbin/apache2 -k start 
www-data 5005 0.0 0.7 285956 14888 ? S 21:00 0:00 /usr/sbin/apache2 -k start
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:

[Mariadb]

Another installation of MariaDB is running:
```
mysql 4067 0.0 4.3 1252916 88620 ? Ssl 20:56 0:00 /usr/sbin/mysqld root 6669 0.0 
0.0 6204 820 pts/0 S+ 21:25 0:00 grep mysql
```
If Bitnami MariaDB isn't starting this is the most likely cause. Please run the 
following command to stop it:
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Yes!

### Describe your issue as much as you can

After trying to update to php8.1, my moodle site stop working and i get the defaulted to index.html, Apache2 Debian Default Page.

When I try to restart all the services I received the following error.

Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

**Comment by mraghbeerasi** [comment]
When I run 

`sudo service bitnami status`

bitnami.service - LSB: bitnami init script
   Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2022-12-24 21:47:59 UTC; 1min 45s ago
  Process: 7100 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
    Tasks: 21 (limit: 2373)
   Memory: 104.1M
   CGroup: /system.slice/bitnami.service
           ├─716 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
           ├─720 php-fpm: pool www
           ├─721 php-fpm: pool www
           ├─722 php-fpm: pool www
           ├─723 php-fpm: pool www
           ├─724 php-fpm: pool www
           ├─725 php-fpm: pool www
           ├─726 php-fpm: pool www
           ├─727 php-fpm: pool www
           ├─728 php-fpm: pool www
           ├─729 php-fpm: pool www
           ├─730 php-fpm: pool www
           ├─731 php-fpm: pool www
           ├─732 php-fpm: pool www
           ├─733 php-fpm: pool www
           ├─734 php-fpm: pool www
           ├─735 php-fpm: pool www
           ├─736 php-fpm: pool www
           ├─737 php-fpm: pool www
           ├─738 php-fpm: pool www
           └─739 php-fpm: pool www

Dec 24 21:47:59 ip-172-31-44-218 bitnami[7100]: AH00534: httpd: Configuration error: No MPM loaded.
Dec 24 21:47:59 ip-172-31-44-218 bitnami[7100]: 2022-12-24T21:47:59.751Z - error: Unable to perform start operation Export start for apache failed with exit code 1
Dec 24 21:47:59 ip-172-31-44-218 bitnami[7100]: ## 2022-12-24 21:47:59+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_bitnami_agent_extra...
Dec 24 21:47:59 ip-172-31-44-218 bitnami[7100]: ## 2022-12-24 21:47:59+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agent...
Dec 24 21:47:59 ip-172-31-44-218 bitnami[7100]: ## 2022-12-24 21:47:59+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welcome_file...
Dec 24 21:47:59 ip-172-31-44-218 bitnami[7100]: ## 2022-12-24 21:47:59+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_credentials_file...
Dec 24 21:47:59 ip-172-31-44-218 bitnami[7100]: ## 2022-12-24 21:47:59+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metadata...
Dec 24 21:47:59 ip-172-31-44-218 systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
Dec 24 21:47:59 ip-172-31-44-218 systemd[1]: bitnami.service: Failed with result 'exit-code'.
Dec 24 21:47:59 ip-172-31-44-218 systemd[1]: Failed to start LSB: bitnami init script.

**Comment by mdhont** [comment]
> After trying to update to php8.1, my moodle site stop working and i get the defaulted to index.html, Apache2 Debian Default Page.

Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components such as PHP or MariaDB individually.

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components such as PHP or MariaDB individually.
