### ISSUE TITLE
After restart the Dolibarr VMWare doesn´t starte>

### ISSUE THREAD

**Issue by Devilmorpheus** [bitnami/vms#572]
### Describe your issue as much as you can

After restarting the VMWare Dolibarr I can no longer access the program with the IP, only the image that the Apache server is running. Can someone help me?
![Unbenannt](https://user-images.githubusercontent.com/99393202/209465247-36a9ad03-2b9d-416e-bf7c-498b30a5b693.JPG)
![Unbenannt1](https://user-images.githubusercontent.com/99393202/209465256-ed76838d-f79f-4714-bd96-b8fda331ffb0.JPG)

**Comment by gongomgra** [comment]
Hi @Devilmorpheus,

Thanks for using Bitnami. That welcome page is from the system package's Apache installation, which is not the one we use in our installations. Please remove the `apache2` package from your system and restart the Bitnami services.

**Comment by Devilmorpheus** [comment]
Thanks that worked

**Comment by gongomgra** [comment]
Hi @Devilmorpheus,

Thanks for letting us know. I'm glad your issue got fixed!
