### ISSUE TITLE
[WordPress] Errors migrating old wordpress to Azure Bitnami WordPress

### ISSUE THREAD

**Issue by cp-adisorn** [bitnami/vms#575]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3849aae4-304b-8794-8826-29636fafca89

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Wordpress: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

not sure how to handle the error

### Describe your issue as much as you can

Try to upgrade WP and PHP but can't show wp-admin page with lot of error
export source : WordPress 4.7.19 / PHP 7.0.13 (wp with db)
import source : using Azure Bitnami Wordpress setup VM ( wordpress 6.0.3 / PHP 8.1.12)

I am using "all in one wp migration" to export and import the whole WP
    - during import, very long time and hold on import DB data, after few hour, still no response, open the other browser tab (result: wp-admin page show "There has been a critical error on this website. Please check your site admin email inbox for instructions. Learn more about troubleshooting WordPress. - https://wordpress.org/support/article/faq-troubleshooting)"
    - open debug mode on wp-config.php
    - open wp-admin page again (show many error for plugin & theme "unicon" error) but without login option, then rename plugin & unicon folder though ftp tools, refresh wp-admin page (can access wp-admin page).
    
    What can I do next??

**Comment by cp-adisorn** [comment]
Any update? thanks

**Comment by cp-adisorn** [comment]
Hi Jotamartos
Any finding? thanks so much.

**Comment by jotamartos** [comment]
Hi @cp-adisorn,

That's a WordPress-related issue. Please contact the WordPress' support team or the "all in one wp migration" forums to get more information about the issue and how to solve it.
