### ISSUE TITLE
[mantis on aws] How to upgrade without exchanging the full image

### ISSUE THREAD

**Issue by myonara** [bitnami/vms#576]
### Describe your issue as much as you can

I'm using mantis on aws quite intensivly, but I get only information, how to install a new image and have to initialize the installation and transfer the projects manualy. Where is the documentation to update e.g. on the ssh shell including a verion history.  With that reinitialiation for each new image the mantis installation is not really usable for me.

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually.

**Comment by myonara** [comment]
ready to use, but not ready to upgrade easily.
I have to eport all projects from the existing image, switch over to the new image, setup https and smtp again, and import all projects again. or is there a simplier way?

**Comment by mdhont** [comment]
Unfortunately migrating the data is the only way.
