### ISSUE TITLE
[Pimcore] DB is shutting down

### ISSUE THREAD

**Issue by zangab** [bitnami/vms#577]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b44acf23-13a7-bbb5-797a-2ad46b89ce05
f0280937-8978-9e7a-f49c-a3edbb7bce41 (older)

### bndiagnostic output

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ? Processes: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Didn't provide any hints for the actual problem.

### Describe your issue as much as you can

First, pls ignore the errors that the services weren't running during the diagnostic run.
They were shut down.
The reason for that is the actual issue I'm currently facing:

```
console.CRITICAL: Error thrown while running command "pimcore:maintenance". Message: "An exception occurred while executing 'DELETE FROM messenger_messages WHERE delivered_at = ?' with params ["9999-12-31 23:59:59"]:  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away"
```

Unfortunately, this happens regularly on my site. As soon as I scroll to an image (which thumbnail should be loaded / generated on the fly) the site crashes.
I installed your AWS product on my EC2 instance and removed all the default data as you install the pimcore/demo instead of the pimcore/skeleton. Next I ran `composer create-project pimcore/skeleton my-project` from the Pimcore installation steps and uploaded my files via SFTP to get a fresh and empty state. An open question are the file permissions. I saw that by default everything is owned by the `daemon` user but as the SFTP user is another one, some persmissions are / were wrong. So I adjusted the persmissions via `chown` and also `chmod`. I set up a doamin & a certificate via certbot (I used the bitnami tool) and since that something seemed to be broken. At first everything looked fine so I went to bed but in the morning the server was gone. All services were stopped and I don't know why. If I restart the services, I can open the page but the thumbnails can't be generated -> exception -> shutdown.

This happens if I run the maintenance direclty in the bash with the SSH user:
```
10:37:33 ERROR     [pimcore] Unable to create a directory at /opt/bitnami/pimcore/public/var/tmp/thumbnails/dummy/8/image-thumb__8__landscape_16x10. mkdir(): Permission denied
10:37:46 ERROR     [pimcore] Couldn't create thumbnail of image /dummy/matt-uuBBew6g2jM-unsplash.jpg
```
This was working without any problems before the next morning though.
Does all the subdirectories in the `public/var` need `chmod 775` so that the maintenance task can create files etc? 🤨

**Comment by zangab** [comment]
UPDATE
so I altered all the files to have the `daemon:daemon` group/user. I also set `127.0.0.1` in the `database.yaml` as there I read that the word `localhost` can cause an issue.  in addition I also set the `unix_socket`.

however, there still a problem with the maintenance task.
I can't figure out the problem here. i mean, i can read the error but it makes no sense as the site is running for some seconds until it runs into a `503`.

```
[2023-01-08T17:20:01.913006+00:00] console.CRITICAL: Error thrown while running command "pimcore:maintenance --async --env=prod". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /opt/bitnami/pimcore/vendor/symfony/doctrine-messenger/Transport/DoctrineSender.php:48)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /opt/bitnami/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /opt/bitnami/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /opt/bitnami/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40)","command":"pimcore:maintenance --async --env=prod","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
```

**Comment by zangab** [comment]
ANOTHER UPDATE
I usually started all the services with the `ctlscript` bash script.
Yesterday, though, I used the `gonit` to start all the services, just for fun actually.
BUT the server didn't crash and didn't ran in any exception. This server is a big blackbox tbh.
I hope u can enlighten me here.

**Comment by mdhont** [comment]
Can you check the `/opt/bitnami/pimcore/var/log/prod.log` file for errors?

**Comment by zangab** [comment]
@mdhont in the log file is the error from the [here](https://github.com/bitnami/vms/issues/577#issuecomment-1374886706).

**Comment by mdhont** [comment]
Did you run the composer command as the daemon user?

    sudo su -s /bin/bash daemon -c "composer create-project pimcore/demo-basic my-test-project"

**Comment by zangab** [comment]
I ran that with the `bitnami` user.
Am I not supposed to do this? I did `chown` all the files afterwards though.

**Comment by zangab** [comment]
hmmm, ok.
but can you tell me why you install the pimcore/demo instead of the pimcore/skeleton?
and how can I update to the latest image?

**Comment by mdhont** [comment]
Could you explain why pimcore/skeleton would be better? I guess we install Pimcore demo because it's meant for users who are new to Pimcore.

**Comment by zangab** [comment]
If I want to click around etc I can use [the pimcore demo page](https://demo.pimcore.fun/).
Best would be an option to choose what you want to install. But by installing the demo by default, this tells me, you don't want this image to be used in production because I have to clean up everything first?

**Comment by mdhont** [comment]
Bitnami images are preconfigured, meaning the installation process is automated and does not allow for user-defined installation options. However, this does not mean that the images are not suitable for use in a production environment. They can be used by both new and experienced users, as they are designed to be easy to use and set up.

**Comment by zangab** [comment]
How can I update my AWS instance to the latest releases?
