### ISSUE TITLE
[WordPress] XML-RPC not working

### ISSUE THREAD

**Issue by jozipaulo** [bitnami/vms#579]
### Describe your issue as much as you can

Hi There,
I am having an issue where a plugin I have installed is reporting that XML-RPC is not functioning by default with PHP v8.1 (which I have on my bitnami wordpress install).

I see there is a tutorial to enable XML-RPC pingback, but this is for the XML-RPC library that needs to be active

It seems XML-RPC might be enabled from what I have read on bitnami's documentation.
 But I have tried a XML-RPC validator and it shows that it is not active on my site.

Please can you advise here.

website.
www.shopfibre.co.za

**Comment by jozipaulo** [comment]
Any help please?

**Comment by jotamartos** [comment]
You need to enable XML-RPC in the solution 

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/xmlrpc-and-pingback/

If that doesn't work, please contact the WordPress' support team to know more about how to enable it in the application.
