### ISSUE TITLE
[Wordpress] PHP FPM doesn't free up memory

### ISSUE THREAD

**Issue by CervarlCG** [bitnami/vms#580]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ef276b0d-5bd7-2614-ee14-f9368b8f7d4f

### bndiagnostic output

[Tue Jan 03 18:46:44.518204 2023] [proxy_fcgi:error] [pid 575498:tid 
140256082736896] [client **ip_address**:28164] AH01071: Got error 'PHP message: 
PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in /opt/bitna [Tue 
Jan 03 18:46:44.518888 2023] [proxy_fcgi:error] [pid 575498:tid 140256082736896] 
[client **ip_address**:28164] AH01071: Got error 'age: PHP Warning: chmod(): 
Press [Enter] to continue:
Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordp [Tue Jan 03 18:46:44.701838 2023] [proxy_fcgi:error] [pid 
575498:tid 140256082736896] [client **ip_address**:28164] AH01071: Got error ' 
Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are not related to my issue

### Describe your issue as much as you can

I have two wordpress instances with the bitnami stack but both doesn't free up memory after the request ends

this is a screenshot with zero plugins installed after some requests.

![Screenshot 2023-01-03 at 11 44 09](https://user-images.githubusercontent.com/53922412/210422932-baffb59b-c5cb-49e8-9ac8-afec1b3d4185.png)

**Comment by iyurinok** [comment]
I have a similar issue. My site has 0 traffic but memory usage is ~1GB:


Periodically server crashes with OOM error:
```
Jan 05 21:00:29 ip-172-31-55-213 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/bitnami.service,task=php-fpm,pid=19397,uid=1
Jan 05 21:00:29 ip-172-31-55-213 kernel: Out of memory: Killed process 19397 (php-fpm) total-vm:554028kB, anon-rss:149540kB, file-rss:4kB, shmem-rss:151536kB, UID:1 pgtables:876kB oom_score_adj:0
Jan 05 21:00:29 ip-172-31-55-213 systemd[1]: bitnami.service: A process of this unit has been killed by the OOM killer.
Jan 05 21:00:30 ip-172-31-55-213 dhclient[478]: XMT: Solicit on ens5, interval 127580ms.
Jan 05 21:00:30 ip-172-31-55-213 bitnami[20096]: 2023-01-05T21:00:30.423Z - info: Saving configuration info to disk
Jan 05 21:00:31 ip-172-31-55-213 bitnami[20096]: 2023-01-05T21:00:31.198Z - info: Stop monitoring services from gonit
Jan 05 21:00:31 ip-172-31-55-213 bitnami[20096]: 2023-01-05T21:00:31.284Z - info: Performing service stop operation for php
Jan 05 21:00:33 ip-172-31-55-213 bitnami[20096]: php 21:00:33.02 INFO  ==> php-fpm stopped
Jan 05 21:00:33 ip-172-31-55-213 bitnami[20096]: 2023-01-05T21:00:33.026Z - info: Performing service stop operation for mariadb
Jan 05 21:00:34 ip-172-31-55-213 bitnami[20096]: mariadb 21:00:34.56 INFO  ==> mariadb stopped
Jan 05 21:00:34 ip-172-31-55-213 bitnami[20096]: 2023-01-05T21:00:34.568Z - info: Performing service stop operation for apache
Jan 05 21:00:35 ip-172-31-55-213 bitnami[20096]: apache 21:00:35.97 INFO  ==> apache stopped
Jan 05 21:00:35 ip-172-31-55-213 bitnami[20096]: 2023-01-05T21:00:35.972Z - info: Skipping service stop operation for varnish
Jan 05 21:00:36 ip-172-31-55-213 systemd[1]: bitnami.service: Failed with result 'oom-kill'.
Jan 05 21:00:36 ip-172-31-55-213 systemd[1]: bitnami.service: Unit process 1169 (gonit) remains running after unit stopped.
Jan 05 21:00:36 ip-172-31-55-213 systemd[1]: bitnami.service: Consumed 1h 32min 39.706s CPU time.
```

**Comment by jotamartos** [comment]
The permissions related errors should be fixed after running these commands 

```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress
sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;
sudo chown -R bitnami:daemon /bitnami/wordpress
sudo find /bitnami/wordpress -type d -exec chmod 775 {} \;
sudo find /bitnami/wordpress -type f -exec chmod 664 {} \;
sudo chmod 640 /bitnami/wordpress/wp-config.php
```

Please note that PHP consumes memory when logging the information in the files so if there is an error that is constantly appearing, the service will use the memory intensively.
