### ISSUE TITLE
[Guacamole ]How to enable TOTP on AzureVM

### ISSUE THREAD

**Issue by EvilQoo** [bitnami/vms#583]
### Describe your issue as much as you can

I had created a AzureVM with Bitnami guacamole from the marketplace. I want to know how to enable TOTP. Thanks.

**Comment by jotamartos** [comment]
That's a specific question about the application and exceeds the scope of this support platform. Please ask the Guacamole's support team to know how to enable TOTP in the application. 

Thanks
