### ISSUE TITLE
[Moodle] Azure vm image is out of date

### ISSUE THREAD

**Issue by Xugamonster** [bitnami/vms#584]
Hi,

The moodle vm image on azure marketplace is out of date.

Moodle version is 4.0.4-8-r09 released on Oct 2022, most recent is 4.1. PHP version is also 7.4.32 which is the minimum supported version for moodle 4.1 and will be likely not be supported in 4.2.

Thank you!

**Comment by mdhont** [comment]
The latest Moodle for Azure solution uses PHP 8.1:

https://bitnami.com/stack/moodle/azuredebian-x64-nami/changelog.txt

**Comment by Xugamonster** [comment]
Odd because on the marketplace site:

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.moodle?tab=PlansAndPrice

![image](https://user-images.githubusercontent.com/122066458/211396585-817f5810-aca7-4946-94c2-ba185e76826a.png)


It still shows 4.0.4-8-r09 and when I tried launching a instance with that, moodle 4.0.4 (and PHP 7.4.32) were installed. Not 4.1 and PHP 8.1

**Comment by mdhont** [comment]
It can take a while for the new versions are promoted on the marketplaces. It should become available in the coming days.
