### ISSUE TITLE
[WordPress] domain populated from server using old (http) domain rather than configured https domain.

### ISSUE THREAD

**Issue by ozwronski** [bitnami/vms#586]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3247cdad-8907-cdb9-a2bc-50e56bdba4c3

### bndiagnostic output

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

The issue doesn't seem related to the issues found by the tool

### Describe your issue as much as you can

WooCommerce is an app on my wordpress instance that references the WordPress Address (URL) and Site Address (URL), using variables such as {site_address}.

ISSUE

For some reason, the url pulled by WooCommerce from Wordpress is consistently http://www.questcoffee.com.au, despite the url being set to https://www.questcoffee.com.au in my bitnami configuration for Wordpress.

The wooCommerce support team informed me:

The {site_address} or {site_url} should be pulled from the settings highlighted in your screenshot [i.e. General Settings]. Since that's not what's being passed to the email, it does look like something else is overriding it. 
You can add the URL directly for now, until the issue that was previously discussed is resolved by your host or your developer. I don't see where this resource was shared with you previously, but I've included it below:

----

I know that previously, the site url was http:// but I updated it to https:// following instructions: https://docs.bitnami.com/aws/apps/wordpress/administration/configure-domain/

What could I have done incorrectly?

**Comment by jotamartos** [comment]
Hi @ozwronski,

Thank you for using our solution. We do not provide support for WooCommerce but this seems to be a configuration issue. If you configured WordPress to use https, you will also need to force https in the Apache's configuration

https://docs.bitnami.com/general/apps/wordpress/administration/use-single-domain/

You should be redirected to https://www.yourdomain.com.au after applying those changes and the WooCommerce plugin should be also using that domain.
