### ISSUE TITLE
[Pimcore] Upgrade not possible

### ISSUE THREAD

**Issue by mia0x1** [bitnami/vms#587]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f5f9c6dc-3f15-dbdd-5e9c-bb0d3ae2b287

### bndiagnostic was not useful. Could you please tell us why?

Most likely not related to my problem

### Describe your issue as much as you can

Pimcore does not run on the current version. 

Your Version: v10.5.11
New Version: 10.5.14

For the updating process I have read the instructions from the Bitnami guide to upgrade. https://docs.bitnami.com/azure/apps/pimcore/administration/upgrade/
I ran into some problems.

1. I should edit the file /opt/bitnami/pimcore/var/config/debug-mode.php to enable the debug mode. The file does not exist in my installation. I could enable the debug mode in the php and apache settings as described.
2. When I then run the command "sudo su daemon -s /opt/bitnami/php/bin/php -c /opt/bitnami/php/bin/composer update", the following error comes up: 

```
PHP: syntax error, unexpected '!' in /opt/bitnami/php/bin/composer.phar on line 1
Could not open input file: update
```

I thought that maybe something is wrong with my installation. So I set up a completely fresh VM, but I get the same error.

Thank you for your help.

**Comment by mdhont** [comment]
Can you try the following command?

    sudo su -s /bin/bash daemon -c "composer update"

**Comment by mia0x1** [comment]
It worked and I have successfully updated Pimcore. I executed the command in /opt/bitnami/pimcore.

Thank you!
