### ISSUE TITLE
[WordPress] AWS Production ready HA web servers becoming unresponsive 

### ISSUE THREAD

**Issue by alidgett** [bitnami/vms#588]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

006bf22c-0b8c-2844-9afe-cae4358ff9aa

### bndiagnostic output

Hello, 
We were not able to locate the diagnostic summary, but will provide a brief explanation of the issue below. The tool indicated that the logs had been successfully uploaded.
Thanks

### bndiagnostic was not useful. Could you please tell us why?

Was not able to locate the summary and output 

### Describe your issue as much as you can

Hello, 

AWS AMI: ami-0b8ad037ac7232eae (bitnami-wordpress-5.9.3-6-r03-linux-debian-10-x86_64-hvm-ebs-high-availability-nami)
Backend DB: Aurora MySQL

As the site starts to receive more load, the web servers slowly begin to maintain more and more open TCP and backend DB connections until the site become unresponsive.  We have set the correct number of max_connections in RDS for the db.r5.large instances. The instances (web and RDS) are sized exactly as our legacy site from which we are migrating (AWS LightSail) to the AWS Bitnami WordPress HA stack. This stack was launched with the provided AWS CloudFormation quick start. 

The bndiagnostics logs have been uploaded. Please provide any insights or guidance from those logs to assist with root cause analysis and resolution.

Thank you,
Infra team

**Comment by alidgett** [comment]
We were able to root cause this to a 3rd Party Plugin that was causing deadlocks on the database and hence the queuing and ultimate exhaustion of back DB connections.

**Comment by alidgett** [comment]
We would like to know though from Bitnami support on how to access the output from bndiagnostics.

**Comment by jotamartos** [comment]
Hi @alidgett,

The tool didn't get the Apache's log file, can you take a look at it? 

```
tail -n 50 /opt/bitnami/apache/logs/error_log
```

Please note that if there are many PHP-related errors there, the performance of the instance decreases.You can also take a look at this guide to troubleshoot server performance issues caused by bots/attackers.

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-connections-bots-apache/

**Comment by alidgett** [comment]
Unfortunately, the issue has resurfaced, this time without the plugin running. 
From the Apache error log we are seeing the following around the time the issue starts:
[Tue Jan 10 16:00:23.476599 2023] [proxy_fcgi:error] [pid 24975:tid 140403395086080] (70007)The timeout specified has expired: [client x.x.x.127:12906] AH01075: Error dispatching request to : (polling)
[Tue Jan 10 16:00:23.552598 2023] [proxy_fcgi:error] [pid 24975:tid 140403630081792] (70007)The timeout specified has expired: [client x.x.x.168:33464] AH01075: Error dispatching request to : (polling)
[Tue Jan 10 16:00:24.401031 2023] [proxy_fcgi:error] [pid 24975:tid 140403621689088] (70007)The timeout specified has expired: [client x.x.x.168:33492] AH01075: Error dispatching request to : (polling)

And from the access log around the same time from the two web servers:

x.x.x..127 - - [10/Jan/2023:16:03:54 +0000] "POST /wp-cron.php?doing_wp_cron=1673366634.2854189872741699218750 HTTP/1.1" 200 -
x.x.x..168 - - [10/Jan/2023:16:03:54 +0000] "POST /wp-cron.php?doing_wp_cron=1673366634.2883760929107666015625 HTTP/1.1" 200 -
x.x.x..168 - - [10/Jan/2023:15:58:54 +0000] "GET / HTTP/1.1" 504 247
x.x.x..127 - - [10/Jan/2023:16:03:55 +0000] "POST /wp-cron.php?doing_wp_cron=1673366635.2146821022033691406250 HTTP/1.1" 200 -
x.x.x..168 - - [10/Jan/2023:16:03:55 +0000] "POST /wp-cron.php?doing_wp_cron=1673366635.3112909793853759765625 HTTP/1.1" 200 -
x.x.x..168 - - [10/Jan/2023:16:03:55 +0000] "POST /wp-cron.php?doing_wp_cron=1673366635.3181090354919433593750 HTTP/1.1" 200 -
x.x.x..168 - - [10/Jan/2023:16:03:55 +0000] "POST /wp-cron.php?doing_wp_cron=1673366635.3125400543212890625000 HTTP/1.1" 200 -

**Comment by jotamartos** [comment]
It seems the PHP-FPM process is not responding to the requests. Please ensure all services are up and running inside the instance and restart the services if needed

```
sudo service bitnami restart
```
