### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by abdohassan4510** [bitnami/vms#589]
### Describe your issue as much as you can

how can i install bitnami wordpress for windows11

**Comment by gongomgra** [comment]
Hi @abdohassan4510 

Thanks for your interest in using Bitnami. We recently stopped providing local installers in favor of our virtual-machines, containers, and cloud images solutions. We recommend you to use the virtual-machine on your Windows system.

You can find more information about the installers removal in our blog post linked below

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html
