### ISSUE TITLE
GCP VM instance not being seen on Bitnami launchpad.

### ISSUE THREAD

**Issue by Giraffe125** [bitnami/vms#59]
### Describe your issue as much as you can

Hi. I recently installed, via GCP, a bitnami instance of Wordpress. 

Once I go to the Bitnami launchpad, I can see my project, but not my instance. The launchpad then just sends me round in a loop, asking me to purchase another instance etc. via Bitnami, when I already have one purchased on GCP. 

I am logging onto bitnami via the same account used on GCP. Is there something I am missing on GCP or Bitnami that will allow me to see my instance on GCP.

I really wish to use the Bitnami launchpad to manage my apps, DB's etc, I just can't use the launchpad at the moment.

Many thanks for your help.

**Comment by jotamartos** [comment]
Hi @Giraffe125,

Thank you for using Bitnami. Unfortunately, the Bitnami Launchpad only shows the instances that have been launched via the launchpad itself, and not the ones you launched using the Google's Console. If you want to manage that instance using the Launchpad, you will need to launch a new instance and migrate the data 

https://docs.bitnami.com/google/how-to/migrate-wordpress/

Thanks!
