### ISSUE TITLE
Does Bitnami Override .htaccess Rewrite Rules?

### ISSUE THREAD

**Issue by RewriteThis** [bitnami/vms#590]
### Name and Version

bitnami/wordpress 5.9.3

### What steps will reproduce the bug?

To reproduce the bug, install Bitnami Wordpress on a Windows PC and then try to add custom rewrite rules using Wordpress' Rewrite API.

### Are you using any custom parameters or values?

Yes, I have a parameter called urlid which needs to be displayed to users someplace like /redirect/4/ with 4 being the value of urlid.

### What is the expected behavior?

All content found in your browser at http://localhost/wordpress/redirect/4/ needs to served from http://localhost/wordpress/wp-content/plugins/myplugin/redirect/index.php?urlid=4

The end result should be a unique integer passed to the plugin which will use that integer to lookup a record containing a URL which will then be used to create a 302 redirect. This method is preferable to the rewrite template people often use in Wordpress because users need to be sent to a robots.txt blocked directory before the redirect fires to keep search engines from following it. In this case the /redirect/index.php location also has a robots file at /redirect/robots.txt which bans bots from the directory.

### What do you see instead?

Instead I see a 404 error message from Wordpress.

### Additional information

The following code is from my plugin activation file
`add_rewrite_rule('redirect/([0-9]+)/?', 'wp-content/plugins/myplugin/redirect/index.php?urlid=$1');`

This should result in all traffic to any URL containing the string redirect/ followed by an integer being rewritten to the plugin. I also tried adding `add_rewrite_tag( '%redirect%', '(.*)' );` followed by a flush of the rewrite rules but the result is the same.

I am wondering if this has more to do with Bitnami since most of Bitnami's docs point to things other than the application's .htaccess file for rewrite rules. This a plugin so I need a solution which rewrites URLs in this way entirely from code in Wordpress. I don't want to have to tell users to manually edit their .htaccess files if I can help it.

**Comment by gongomgra** [comment]
Hi @RewriteThis,

Thanks for using Bitnami. By default, our installations disable the `.htaccess` files as [recommended by the Apache Software Foundation](http://httpd.apache.org/docs/current/mod/core.html#allowoverride). All the configuration found in those files at installation time are moved in to a separated `wordpress-htaccess.conf` file under the `/opt/bitnami/apache2/conf/vhosts/htaccess` folder. You can add the needed configuration for your plugin there, or enable back `.htaccess` files. Please find more information about this in our guide linked below

https://docs.bitnami.com/virtual-machine/infrastructure/lamp/administration/use-htaccess/

**Comment by RewriteThis** [comment]
> Hi @RewriteThis,
> 
> Thanks for using Bitnami. By default, our installations disable the `.htaccess` files as [recommended by the Apache Software Foundation](http://httpd.apache.org/docs/current/mod/core.html#allowoverride). All the configuration found in those files at installation time are moved in to a separated `wordpress-htaccess.conf` file under the `/opt/bitnami/apache2/conf/vhosts/htaccess` folder. You can add the needed configuration for your plugin there, or enable back `.htaccess` files. Please find more information about this in our guide linked below
> 
> https://docs.bitnami.com/virtual-machine/infrastructure/lamp/administration/use-htaccess/

That is outrageous. How do you add things to your special file using the Wordpress Rewrite API?

**Comment by RewriteThis** [comment]
Where is /opt/ on a Windows installation by default. Please begin your answer with C:\\ followed by the exact location.

I've lost countless hours to this already so I really am at the end of my tolerance here. You should never disable that which is normally enabled by default in this scenario. Nothing some foundation says can change that. If almost every Wordpress site uses .htaccess it needs to be enabled by default.

**Comment by RewriteThis** [comment]
I think I found the folders described by your article at C:\\Bitnami\wordpress-5.9.3\apps\wordpress\conf but NONE of the files in that folder contain AllowOverride anywhere. The files in that folder include htaccess.conf, https-app.conf, and httpd-vhosts.conf.

**Comment by RewriteThis** [comment]
I finally found the override in C:\\Bitnami\wordpress-5.9.3\apps\wordpress\conf\httpd-app.conf and changed AllowOverride to All but I still get a 404 error when trying to access the page indicating that the rewrite rule still does not work.

**Comment by RewriteThis** [comment]
The override clearly does not work. As a test I added a basic 301 redirect to match any url with the pattern /wordpress/test/letterswithtwonumbers99/nothinglikethis to https://www.google.com and it doesn't match. The rule is:

`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /wordpress/
RewriteRule ^index\.php$ - [L]
Redirect 301 /wordpress/test/letterswithtwonumbers99/nothinglikethis https://google.com
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wordpress/index.php [L]
</IfModule>`

When I try to load /wordpress/test/letterswithtwonumbers99/nothinglikethis in my browser I should be redirected to Google but I get a 404 error instead.

**Comment by RewriteThis** [comment]
Icing on the cake: Adding this rule which should result in all traffic being redirected still results in a 404 error from Wordpress.

Redirect 302 / https://google.com

Same goes for Redirect 302 /wordpress/ https://google.com

**Comment by gongomgra** [comment]
Hi @RewriteThis,

It is not mandatory to stick to our initial configuration model in case your specific use case doesn't fit. You can recover the usage of `.htaccess` files updating the `AllowOverride` parameter in the file you mentioned and then restart Apache for changes to take effect. You didn't mention if you restarted the service. Can you try to do it?

If you continue facing errors, please run the bndiagnostic tool placed in your installdir (`C:\Bitnami\wordpress-5.9.3`), and share the generated code with us. It will share the Apache configuration with us so we can double-check it.

Apart from the above, please note we no longer support the local installations on Windows machines, as we don't provide the local installers on our website anymore. We recommend you to migrate your WordPress data to our virtual-machine solution. You can get more information about the installers deprecation in the next link

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html
