### ISSUE TITLE
[Wordpress] SSL renew error 400

### ISSUE THREAD

**Issue by robastarta** [bitnami/vms#592]
### Describe your issue as much as you can

Got the following error when trying to renew a certificate (using [same method](https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#troubleshooting) as always which worked fine before)

one or more domains had a problem:
[hooplainteractive.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 34.252.157.82: Error getting validation data

The only info i found on this mentioned a firewall could be the cause, but it's not something i had to deal with before so not sure if this applies to my case. 

Thanks in advance!
Rob

**Comment by jotamartos** [comment]
I can see your certificate got renewed properly till April 10th. If you run into this issue in the future, please contact the Let's Encrypt support team to know more about the error. 

Thanks
