### ISSUE TITLE
[WordPress] Server suddenly stops responding

### ISSUE THREAD

**Issue by ShadiBamlhs** [bitnami/vms#593]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

44fccbe6-8618-94e2-4848-0f7a4872c461

### bndiagnostic output

   ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ? Processes: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

i cant solve the issue

### Describe your issue as much as you can

The server suddenly stops responding, I changed the server type and also upgraded the space, but the issue still appears

**Comment by ShadiBamlhs** [comment]
Now its working but all services down, i got this message : 

`Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.`

**Comment by ShadiBamlhs** [comment]
![used](https://user-images.githubusercontent.com/20146277/211485794-7c7baca1-1b09-430a-9a0b-de0720bd4239.PNG)

**Comment by jotamartos** [comment]
From the previous execution of the Bitnami Diagnostic tool, I can see MariaDB was using most of the space in the disk 

```
-----------------------------------
Find biggest directories in installdir
-----------------------------------
Running: du -h . -d 1 | sort -h
In: /opt/bitnami

Output:

24K ./apps
88K ./var
748K    ./scripts
956K    ./peclapcu
1.8M    ./brotli
3.0M    ./stats
4.3M    ./varnish
6.3M    ./wp-cli
7.6M    ./gonit
9.1M    ./common
24M ./mysql
54M ./phpmyadmin
57M ./wordpress
60M ./bndiagnostic
61M ./bncert
65M ./letsencrypt
85M ./nami
87M ./apache
97M ./php
20G ./mariadb
21G .
```

Can you confirm the problem is the same?

```
cd /opt/bitnami
sudo du -h . -d 1 | sort -h
```

**Comment by ShadiBamlhs** [comment]
![10-1-23](https://user-images.githubusercontent.com/20146277/211497595-1f7d11fb-b921-4ddf-bf5a-c4d8e5db2b99.PNG)

**Comment by ShadiBamlhs** [comment]
`bitnami@ip-172-31-8-83:/opt/bitnami$ du -h . -d 1 | sort -h
du: cannot read directory './var/data': Permission denied
du: cannot read directory './mariadb/plugin/auth_pam_tool_dir': Permission denied
24K     ./apps
76K     ./var
748K    ./scripts
956K    ./peclapcu
1.8M    ./brotli
3.0M    ./stats
4.3M    ./varnish
6.3M    ./wp-cli
7.6M    ./gonit
9.1M    ./common
24M     ./mysql
54M     ./phpmyadmin
57M     ./wordpress
60M     ./bndiagnostic
61M     ./bncert
65M     ./letsencrypt
85M     ./nami
87M     ./apache
97M     ./php
186G    .
186G    ./mariadb
`

**Comment by ShadiBamlhs** [comment]
![image](https://user-images.githubusercontent.com/20146277/211502858-fefc64f3-9ef6-48f2-a579-74239bbe5983.png)

**Comment by ShadiBamlhs** [comment]
![image](https://user-images.githubusercontent.com/20146277/211508094-434b19d6-327d-48e4-ba63-e19ee6d0999d.png)

**Comment by jotamartos** [comment]
It seems MariaDB is logging a huge amount of information in the log and that's why you are running out of disk space. Please review the information the database is logging and act accordingly. Remember that those ".gz" files are old log files that you can easily remove to quickly solve this issue.

```
sudo rm -rf mysqld.log-*.gz
```

**Comment by ShadiBamlhs** [comment]
Removed but still the **mysqld.log** size is huge

bitnami@ip-172-31-8-83:/opt/bitnami/mariadb/logs$ ls -s
total 193958844
193958844 mysqld.log

**Comment by ShadiBamlhs** [comment]
can I remove **mysqld.log** as well ?

**Comment by ShadiBamlhs** [comment]
I increased the storage to 300GB but this file mysqld.log increased very fast

**Comment by jotamartos** [comment]
Check what the server is logging to know why the log is so big
