### ISSUE TITLE
[WordPress Bitnami MultiSite] Set up Apple Pay apple-developer-merchantid-domain-association file needs to be available

### ISSUE THREAD

**Issue by guytz72** [bitnami/vms#594]
### Describe your issue as much as you can

I'm trying to setup a new payment method - Apple Pay - that requires a domain verification with a txt file at that specific path: https://example.com/.well-known/apple-developer-merchantid-domain-association

The file is there, when I log via FTP the path is correct, but when I try to open by URL I get a 404 error..

The folder .well-known is set to 755 permission The txt file is set to 644 (the folder is placed right inside htdocs)

I have tried the following locations for the file, creating the directory .well-known:

/opt/bitnami/apps/wordpress/htdocs/.well-known
/opt/bitnami/apache2/htdocs/.well-known
/opt/bitnami/apps/letsencrypt/.well-known

None of these work.  

I do have an AWS CDN in use but have excluded any paths with  /.well-known/ from being served by the CDN.

**Comment by mdhont** [comment]
The following guide explains how to configure a .well-known directory:

https://docs.bitnami.com/general/how-to/understand-bncert/#certificates-not-renewed-automatically

**Comment by guytz72** [comment]
ok thanks.  I've aways had issues with the bncert tool though so I manually renew the certs.  One f the things I'vebeen meaning to get around to.

I get this warning when running it:

Warning: Custom redirections are not supported in the Bitnami WordPress 
Multisite Stack. This tool will not be able to enable/disable redirections.

Not sure what re-directs I had in place or if I can do without

**Comment by guytz72** [comment]
Error: Error running /opt/bitnami/apps/wordpress/bnconfig.disabled 
--machine_hostname speedstix.com: child process exited abnormally
Press [Enter] to continue:
/Warning: Certificates may not renew automatically, due to a web server 
configuration issue. For more information see: 
https://docs.bitnami.com/general/how-to/understand-bncert/#certificates-not-renew
ed-automatically

This is the error I get after running

**Comment by guytz72** [comment]
Attached the log for the cert tool, any idea @mdhont ?

[bncert-202301101157.log](https://github.com/bitnami/vms/files/10382887/bncert-202301101157.log)

**Comment by mdhont** [comment]
My apologies, I shared the guide for creating a Let's Encrypt certificate, but only because it contains the manual steps to create a .well-known directory. If you already have HTTPS and a domain configured it's not necessary to run the bncert tool.

**Comment by bombe1** [comment]
Hi, 
There is any solution for this?

**Comment by jotamartos** [comment]
Hi @bombe1,

If you need to configure a .well-known folder to include the information and validate your domain, there are some items you will need to check first:
- If you ran the Bitnami HTTPS configuration tool, you will have a letsencrypt folder with the .well-known folder inside. You will simply need to add the file to verify your domain inside. 
- If that's not the case, you will need to create a .well-known folder inside the /opt/bitnami/wordpress directory and confirm you can access the file by browsing it in your browser.
