### ISSUE TITLE
[WordPress: Self-Contained Stack] Apache2 servers the IP address, causing iOS sharing to not reflect domain name

### ISSUE THREAD

**Issue by KaitoKid** [bitnami/vms#597]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

09eea5d9-01fd-a59f-ddbe-949079b9a236

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Mariadb: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
    ✓ Connectivity: No issues found
 

 
[Mariadb]

Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Thu Jan 12 05:09:21.336104 2023] [php7:notice] [pid 10445] [client 
**ip_address**:55504] WordPress database error Table 
'bitnami_wordpress.wp_ppress_meta_data' doesn't exist for query SELECT 
bndiagnostic-common-lib.sh bndiagnostic.sh components FROM wp_ppress_meta_data 
WHERE meta_key = 'content_restrict_data' made by require('wp-blog-header.php'), 
require_once('wp-includes/template-loader.php'), do_action('template_redirect'), 
WP_Hook->do_action, WP_Hook->apply_filters, 
ProfilePress\Core\ContentProtection\Frontend\Redirect->handler, ProfileP [Thu 
Jan 12 05:09:21.355987 2023] [php7:notice] [pid 10445] [client 
**ip_address**:55504] WordPress database error Table 
'bitnami_wordpress.wp_ppress_meta_data' doesn't exist for query SELECT 
bndiagnostic-common-lib.sh bndiagnostic.sh components FROM wp_ppress_meta_data 
WHERE meta_key = 'content_restrict_data' made by require('wp-blog-header.php'), 
require_once('wp-includes/template-loader.php'), 
include('/themes/thevoux-wp/attachment.php'), get_header, locate_template, 
load_template, require_once('/themes/thevoux-wp/header.php'), wp_head, do_act 
[Thu Jan 12 05:09:21.356846 2023] [php7:notice] [pid 10445] [client 
**ip_address**:55504] WordPress database error Table 
'bitnami_wordpress.wp_ppress_meta_data' doesn't exist for query SELECT 
bndiagnostic-common-lib.sh bndiagnostic.sh components FROM wp_ppress_meta_data 
WHERE meta_key = 'content_restrict_data' made by require('wp-blog-header.php'), 
Press [Enter] to continue:
require_once('wp-includes/template-loader.php'), 
include('/themes/thevoux-wp/attachment.php'), get_header, locate_template, 
load_template, require_once('/themes/thevoux-wp/header.php'), wp_head, do_act
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

### bndiagnostic was not useful. Could you please tell us why?

Not related to my issue

### Describe your issue as much as you can

When using the [Share] icon within Chrome or Safari on iOS, my Wordpress website shares the IP address, not the domain name.

I've followed the guide to [Access An Application Using Only A Single Domain With Apache] which has worked, as http://104.215.100.228 now redirects to https://kpopconcerts.com

However, sharing still does not show the correct domain. [Image](https://i.imgur.com/iYK10yZ.jpeg)

**Comment by gongomgra** [comment]
Hi @KaitoKid,

Thanks for using Bitnami. I checked your bndiagnostic bundle and I found you didn't configure your domain name in the `wp-config.php` file. Please follow the steps in the guide linked below to configure it (remember to set it with the `https://` prefix)

https://docs.bitnami.com/general/apps/wordpress/administration/configure-domain/

If you continue having issues after configuring this setting, please contact the developers of your theme for further help on how to update that link.

**Comment by KaitoKid** [comment]
Thanks @gongomgra - I can confirm that this fixed the issue. I must've missed this as part of the migration.
