### ISSUE TITLE
[WordPress ]A definition of a site url or home url was detected in your wp-config.php, but the file is not writable. Set your wp-config.php to writable and reload this page.

### ISSUE THREAD

**Issue by itsmemidhuz123** [bitnami/vms#599]
A definition of a site url or home url was detected in your wp-config.php, but the file is not writable. Set your wp-config.php to writable and reload this page.

sir, we recently reinstalled a new instance and comes the same issue. it shows a message on dashboard

i used the below command to resolve

sudo chown -R bitnami:daemon /opt/bitnami/wordpress
sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;

_Originally posted by @itsmemidhuz123 in https://github.com/bitnami/vms/issues/400#issuecomment-1380833556_

**Comment by itsmemidhuz123** [comment]
issue solved when the permission set to .htaccess file

**Comment by jotamartos** [comment]
I'm glad to hear that the problem is solved now. Enjoy! :)
