### ISSUE TITLE
Create a wordpress instance that is proxied from a subfolder of an existing site hosted on an external server

### ISSUE THREAD

**Issue by kevin72192** [bitnami/vms#60]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8c23d42d-e745-05eb-f71d-998cab9bd12e

### bndiagnostic output

 Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Didn't tell me anything that wasn't already obvious.

### Describe your issue as much as you can

I have an existing site that lives at www.example.com and when traffic goes to www.example.com/guides/ (using nginx proxypass) they are routed to the wordpress bitnami instance but the URL remains www.example.com/guides/ and further navigation of wordpress just appends to the path as in, www.example.com/guides/wp-admin/ . 

I have tried a few time but have only been able to get as far as having everything under the subfolder but then all the assets are broken. Starting from scratch what are the steps to achieve this? Should i be using the multisite or the regular instance for this?

**Comment by mdhont** [comment]
You have configured the WordPress domain with the `/guides` subfolder:

```
  define( 'WP_HOME', 'https://your-domain.com/guides/');
```

You need to remove the subfolder from that path.
