### ISSUE TITLE
[Discourse] After attempting to install plugin, Discourse no longer loads(Phusion Passenger Cannot Start the web application)

### ISSUE THREAD

**Issue by universeastronomyblog** [bitnami/vms#600]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f18c2d99-56c8-348c-4a38-373bb9b04358

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ✓ Connectivity: No issues found
    ? Processes: Found possible issues
    ? Apache: Found possible issues
 

 
[Processes]

One or more component's processes are not running:
```
sidekiq not running
```
You can try to restart the process with the following command:
 
    $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
  Error details saved to: /tmp/passenger-error-ynmlFn.html

[ E 2023-01-12 22:49:10.3030 783/T8 age/Cor/Con/CheckoutSession.cpp:281 ]: 
[Client 1-16] Cannot checkout session because a spawning error occurred. The 
identifier of the error is 9fe7f926. Please see earlier logs for details about 
the error.

[ E 2023-01-12 22:49:10.3032 783/Ta age/Cor/Con/CheckoutSession.cpp:281 ]: 
[Client 2-16] Cannot checkout session because a spawning error occurred. The 
identifier of the error is 9fe7f926. Please see earlier logs for details about 
the error.

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Unable to locate how to fix the issue I dont want to mess things up further.

### Describe your issue as much as you can

I was attempting to install a Discourse plugin for my forums and upon doing so, Discourse completely stopped working due the plugin installation breaking Phusion Passenger not working.

I followed this guide when installing the plugin: [Install plugins](https://docs.bitnami.com/aws/apps/discourse/configuration/install-plugins/)

When you visit https://forum.joshuniverse.com/ you receive the following error page:

— ERROR MSG —
pastebin.com/Ft0cAWNC

– LOG FILE –
pastebin.com/uBxs6vJ3

**Comment by universeastronomyblog** [comment]
The log file I included is where it shows the commands I entered the the output where it completely broke discourse

**Comment by universeastronomyblog** [comment]
Help!! It is not solved..

**Comment by johnalien15** [comment]
If you are experiencing an issue with Discourse not loading after attempting to install a plugin, there could be a few different causes.

Plugin Compatibility: The plugin you installed may not be compatible with the version of Discourse you are running, causing the application to crash. Try uninstalling the plugin and see if that resolves the issue.

Incorrect Installation: The plugin may have been installed incorrectly, causing issues with the application. Check the installation instructions for the plugin and make sure they were followed correctly.

Conflicting Plugins: The plugin you installed may be conflicting with other plugins that are currently installed on your Discourse instance. Try disabling or uninstalling other plugins to see if that resolves the issue.

Permission Issues: If the plugin was installed by a different user than the one running the Discourse application, it may not have the correct permissions to run. Check the permissions on the plugin files and make sure they are set correctly.

Passenger: Phusion Passenger is an application server that runs on top of your web server. It may be the case that the Passenger process is not running or there is a problem with the configuration file. Check your log files for any error messages and try restarting the passenger process.

If none of the above steps resolve the issue, it may be necessary to restore your Discourse instance from a backup or contact support for further assistance.
