### ISSUE TITLE
Wordpress  Job for bitnami.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by jaycova** [bitnami/vms#601]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

19380f25-7538-d964-8aee-f6bb51f9e5eb

### bndiagnostic output

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Mon Jan 16 01:03:40.513886 2023] [proxy:error] [pid 260443:tid 139811545327360] 
(2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain 
socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Mon Jan 16 01:03:40.513949 2023] [proxy_fcgi:error] [pid 260443:tid 
139811545327360] [client **ip_address**:2910] AH01079: failed to make connection 
to backend: httpd-UDS, referer: https://www.jaycocioservices.com//wp-login.php
 [Mon Jan 16 01:09:56.324542 2023] [core:error] [pid 262603:tid 139727902570240] 
[client **ip_address**:39870] AH10244: invalid URI path 
(/../../../../../../../../../../../../etc/passwd)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
Press [Enter] to continue:
bots-apache/

System Apache is running:
```
root 601 0.0 0.2 8688 4532 ? Ss 01:32 0:00 /usr/sbin/apache2 -k start www-data 
604 0.0 0.3 1213412 7160 ? Sl 01:32 0:00 /usr/sbin/apache2 -k start
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:
 

### bndiagnostic was not useful. Could you please tell us why?

I tried everything you sent links for. 

### Describe your issue as much as you can

I ran the diagnostic tool a few times and I fixed all the LoadModule errors in the httpd.conf file. The ports are all open. and I tried all the suggestions. it is still not working.

**Comment by gongomgra** [comment]
Hi @jaycova,

Thanks for using Bitnami. I visited your website and it shows the default Debian Apache welcome screen, which means your server is running the Apache server installed using the system packages manager (`apt-get`), instead of the one installed by us (which also causes the `bitnami.service` to not start). Please uninstall the `apache2` package from your server and then restart the Bitnami service again.

**Comment by jaycova** [comment]
Thank you. I did the following `sudo apt-get remove apache2 ` it is still not working. No I am having an issue with Letsencrypt. so I might have removed too much. I ran the diagnostic tool 

3682e0cf-d43b-1592-ed19-041f67246c21

**Comment by jaycova** [comment]
I found an article about reinstalling some libraries. I tried that but it is still not working. is there a way to reinstall the bitnami package for apache?

**Comment by jaycova** [comment]
> Hi @jaycova,
> 
> Thanks for using Bitnami. I visited your website and it shows the default Debian Apache welcome screen, which means your server is running the Apache server installed using the system packages manager (`apt-get`), instead of the one installed by us (which also causes the `bitnami.service` to not start). Please uninstall the `apache2` package from your server and then restart the Bitnami service again.

I did as you asked I am still down. my website has been offline for almost 2 days now? I need help

**Comment by gongomgra** [comment]
Hi @jaycova,

Thanks for the updated bndiagnostic bundle. According to the Apache logs, there is a syntax error in the Let's Encrypt configuration. Can you check it?

```
AH00526: Syntax error on line 5 of /opt/bitnami/apps/letsencrypt/conf/httpd-app.conf: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
```
