### ISSUE TITLE
[redmine] <Where can I get a previous version of Redmine VM>

### ISSUE THREAD

**Issue by MichaGeh** [bitnami/vms#602]
### Describe your issue as much as you can

Hi experts.

I'm looking for previous version of the bitnami redmine vm.
I'd like to migrate redmine 4.x on windows, installed with the bitnami installer, to a linux vm.

Does anyone have the last 4.2 version of the bitnami redmine vm?

Thanks in advance.

**Comment by mdhont** [comment]
If you want to run Redmine locally you can use the Redmine OVA and launch it with VirtualBox or VMware Fusion:

https://bitnami.com/stack/redmine/virtual-machine

**Comment by mdhont** [comment]
You can download it here:

https://downloads.bitnami.com/files/stacks/redmine/4.2.2-19/bitnami-redmine-4.2.2-19-r03-linux-debian-10-x86_64-nami.ova 

    md5:70266d57863e87bcf31cf15b42f3d422

**Comment by MichaGeh** [comment]
Thank you for your support!
