### ISSUE TITLE
[NGINX] Found possible issues when deploying WordPress on top of NGINX

### ISSUE THREAD

**Issue by Taufiqs95** [bitnami/vms#605]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

04092fd2-b9c8-84ae-2cc1-aa64a210804c

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ? Nginx: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ✓ Php: No issues found
 

 
### [Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 975 439 89 61 447 303 Swap: 
634 56 578
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

### [Nginx]

Found recent error or warning messages in the Nginx error log.
```
2023/01/17 05:52:51 [error] 698#698: *13204 directory index of 
"/opt/bitnami/wordpress/wp-content/uploads/2022/10/" is forbidden, client: 
**ip_address**, server: _, request: "GET /wp-content/uploads/2022/10/ HTTP/1.1", 
host: "www.mboton.net", referrer: 
"https://www.mboton.net/wp-content/uploads/2022/10/"
 2023/01/17 05:53:02 [error] 698#698: *13215 directory index of 
"/opt/bitnami/wordpress/wp-content/uploads/2022/10/" is forbidden, client: 
**ip_address**, server: _, request: "GET /wp-content/uploads/2022/10/ HTTP/1.1", 
host: "www.mboton.net", referrer: 
"https://www.mboton.net/wp-content/uploads/2022/10/"
 2023/01/17 06:35:49 [crit] 698#698: *13942 SSL_do_handshake() failed (SSL: 
error:14201044:SSL routines:tls_choose_sigalg:internal error) while SSL 
handshaking, client: **ip_address**, server: 0.0.0.0:443

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/ress [Enter] to continue:
0m

### [Wordpress]

Found recent WordPress plugin related error messages in the Nginx error log.
```
#3 
/opt/bitnami/wordpress/wp-content/plugins/seo-by-rank-math/includes/modules/sitem
ap/class-router.php(79): RankMath\Sitemap\Sitemap_XML->__construct()

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

bndiagnostic used successfully for bndiagnostic 

### Describe your issue as much as you can

Halo Admin Bitnami

May I ask for help, I just installed nginx on the AWS Lightsail marketplace. And I followed the tutorial article on this URL page.
https://docs.bitnami.com/aws/how-to/install-wordpress-nginx/

It seems that this setting is wrong. After I used diagnostics. https://docs.bitnami.com/general/how-to/understand-bndiagnostic/.

I'm still a beginner setting up the VPS Marketplace NGINX on the AWS Lightsail server, previously I used shared hosting using the cpanel panel. Please help me To fix all this. I've found this AWS Best Server I was recommended by the facebook forum.

And I want to enable it too but I haven't been able to enable NGINX FastCGI so x-fastcgi-cache: HIT.

AWS is cool to build a blog web server to go further. Hope Bitnami Admin can help me.

Thank You
Regard
Taufiq Setiawan

**Comment by jotamartos** [comment]
Hi @Taufiqs95,

Thank you for using our solution. I see 2 different problems here: 

- Performance issues: Your machine is running out of RAM memory so I suggest you increase the instance type to avoid this kind of issues.
- Permissions issues: It seems NGINX/PHP can't write in the WordPress' folder. Please make sure the permissions are set correctly 

```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress
sudo chmod -R g+w /opt/bitnami/wordpress
```

**Comment by Taufiqs95** [comment]
> Hai@Taufiqs95,
> 
> Terima kasih telah menggunakan solusi kami. Saya melihat 3 masalah berbeda di sini:
> 
> * Masalah kinerja: Mesin Anda kehabisan memori RAM, jadi saya sarankan Anda menambah jenis instan untuk menghindari masalah seperti ini.
> * Masalah izin: Rupanya NGINX/PHP tidak dapat menulis di folder WordPress. Harap pastikan izin diatur dengan benar
> 
> ```
> sudo chown -R bitnami:daemon /opt/bitnami/wordpress
> sudo chmod -R g+w /opt/bitnami/wordpress
> ```
> 
> * Masalah terkait WordPress: Sepertinya ada masalah dengan plugin di WordPress. Silakan hubungi tim dukungan WordPress atau plugin untuk mendapatkan informasi lebih lanjut.

Hello Dear jotamartos

I am very happy to meet you and help me to fix a problem on my new deployed AWS server. I will type in the SSH terminal, just these 2 codes.


```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress
sudo chmod -R g+w /opt/bitnami/wordpress
```

After that, restart the server again or not?


Thank You
Regard
Taufiq Setiawan
