### ISSUE TITLE
[WordPress] Get 404 error messages when accessing plugins

### ISSUE THREAD

**Issue by itsmemidhuz123** [bitnami/vms#606]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5f2d9efe-6dec-53cf-3220-f95a66b7dc0a

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Tue Jan 17 07:48:33.812196 2023] [proxy_fcgi:error] [pid 8977:tid 
139660911007488] [client **ip_address**:36264] AH01079: failed to make 
connection to backend: httpd-UDS, referer: 
https://mcubes.net/wp-admin/plugins.php?plugin_status=all&paged=1&s&w3tc_note=flu
sh_all
Press [Enter] to continue:

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Jan 17 07:19:32.278375 2023] [proxy_fcgi:error] [pid 1132:tid 
139691974117120] [client **ip_address**:56902] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php 
on line 88PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 89PHP message: PHP Warning: Undefined 
array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php on line 
689PHP message: PHP Warning: Undefined ar [Tue Jan 17 07:22:34.135938 2023] 
[proxy_fcgi:error] [pid 1066:tid 139691713943296] [client **ip_address**:17796] 
AH01071: Got error 'PHP message: DeliveredPHP message: Delivered', referer: 
https://mcubes.net/wp-admin/post.php?post=91323&action=edit
 [Tue Jan 17 07:48:33.812105 2023] [proxy:error] [pid 8977:tid 139660911007488] 
(2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain 
socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
```

when i tried to access some of the plugin, there is some issue with rest api that comes into error 404

plugin creates three API endpoints to your site that will be called by our servers and it seems like our server can't reach the endpoints.

We need to call to:

I've noticed that you are using some protections on your site that could be the root cause of the problem.

OwnID plugin creates three API endpoints to your site that will be called by our servers and it seems like our server can't reach the endpoints.

We need to call to:

[mcubes.net/wp-json/ownid/v1/getOwnIDDataByLoginId](http://mcubes.net/wp-json/ownid/v1/getOwnIDDataByLoginId)
[mcubes.net/wp-json/ownid/v1/setOwnIDDataByLoginId](http://mcubes.net/wp-json/ownid/v1/setOwnIDDataByLoginId)
[mcubes.net/wp-json/ownid/v1/getSessionByLoginId](http://mcubes.net/wp-json/ownid/v1/getSessionByLoginId)

what are the possible issues on this, i think i recently changed a permission of some files that makes this issues

### bndiagnostic was not useful. Could you please tell us why?

unable to iednify myslef

### Describe your issue as much as you can

error found by using some plugin, some plugin api enpoins couldnt reach website and this comes in error 404
[
](https://mcubes.net/wp-json/ownid/v1/setOwnIDDataByLoginId)

**Comment by jotamartos** [comment]
Hi @itsmemidhuz123,

That's a plugin-related question and it's out of the scope of this forum. Please contact the plugin's developers to get more information about how it works and how to access it. 

Thanks

**Comment by itsmemidhuz123** [comment]
BASICALLY this happens to all plugin right now which uses the end points . i thing this cause by a permission that added in a file path

**Comment by itsmemidhuz123** [comment]
but i actually added permission to wp-admin and .htaccess

**Comment by jotamartos** [comment]
If you need to reset the permissions configuration, you can run the commands in this post to do so 

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

**Comment by itsmemidhuz123** [comment]
awesome, thanks
