### ISSUE TITLE
[<Moodle>] <Links get generated in emails directing to http://127.0.0.1/>

### ISSUE THREAD

**Issue by Steve2023a** [bitnami/vms#609]
### Describe your issue as much as you can

I have Bitnami Moodle running on AWS. Automatically generated emails direct to http://127.0.0.1/ instead of to my moodle site. Is there a way of fixing this?

eg
A number of students in <course> have not accessed the course recently.

[View insight](http://127.0.0.1/report/insights/insights.php?modelid=5&contextid=169)

**Comment by jotamartos** [comment]
Please take a look at the Moodle's documentation and forums

https://moodle.org/mod/forum/discuss.php?d=354861
