### ISSUE TITLE
[<MEAN PACKAGED>] <Transaction numbers are only allowed on a replica set member or mongos>

### ISSUE THREAD

**Issue by josueixcot** [bitnami/vms#610]
### Describe your issue as much as you can

MEAN packaged by Bitnami... I am implementing an application that uses transactions but when trying to execute the operations in the database it shows me the following error.

-> MongoServerError: Transaction numbers are only allowed on a replica set member or mongos ...
   ok: 0,
   code: 20,
   codeName: 'IllegalOperation'

I would like to know if it is possible to implement replicas in this package.

if possible, what is the correct procedure that bitnami suggests.

the version of mongo that I am using is v6.0.3

**Comment by mdhont** [comment]
Unfortunately MEAN packaged by Bitnami does not use replicasets.
