### ISSUE TITLE
Security Updates

### ISSUE THREAD

**Issue by stumac06** [bitnami/vms#611]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

00000

### bndiagnostic was not useful. Could you please tell us why?

00000

### Describe your issue as much as you can

Hi I am trying to pull down security patches and the upgrade but when I run the commands sudo apt upgrade I see these sites

Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://cdn-aws.deb.debian.org/debian bullseye InRelease
Hit:3 http://cdn-aws.deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://cdn-aws.deb.debian.org/debian bullseye-backports InRelease

I then run sudo apt upgrade but nothing upgrades

Have Bitnami blocked this option and are these updates done through new version of Bitnami?

Thanks

**Comment by gongomgra** [comment]
Hi @stumac06,

Thanks for using Bitnami. We do not block any system upgrade using the `apt-get` package manager in our images, but there must be no packages that need to be updated at this moment. Can you share the whole output of running the next commands on your system?

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```
