### ISSUE TITLE
[MODX] No permission for to access MODX, phpMyAdmin etc.

### ISSUE THREAD

**Issue by Blogbotana** [bitnami/vms#612]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

no-id

### bndiagnostic output

Problem with access to MODX and other applications

### bndiagnostic was not useful. Could you please tell us why?

.

### Describe your issue as much as you can

Hello. I had problem with permission for my SFTP connections. I've found solution how to do permission for modx folders, but after that I can't access to my MODX, phpmyAdmin. I think password could be change, but when I wrote _sudo cat /home/bitnami/bitnami_credentials_ it was the same. 
![image](https://user-images.githubusercontent.com/69924139/213402951-7013f12f-f6c3-45ce-8f36-d17efc833749.png)
How I can fix this?

**Comment by Blogbotana** [comment]
![image](https://user-images.githubusercontent.com/69924139/213408599-b862ae3a-5b7a-4000-ac12-d3e07b3558c8.png)

**Comment by jotamartos** [comment]
The bitnami_credentials file contains the default password we configure when you boot the instance. If you changed the password, you will need to use that new one. 

Regarding phpMyAdmin, please note that you need to use "root" as user and the password configured in the bitnami_credentials file.
