### ISSUE TITLE
[WordPress] Site disappeared after clearing cache

### ISSUE THREAD

**Issue by Marlon015MT** [bitnami/vms#613]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8606c233-8bc3-70e2-50d9-d9d75b424af3

### bndiagnostic output

✓ Resources: No issues found
? Connectivity: Found possible issues
✓ Mariadb: No issues found
? Processes: Found possible issues
✓ Wordpress: No issues found
? Apache: Found possible issues
✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

I don't know how to solve

### Describe your issue as much as you can

Guys, I come here to ask you for help because my site simply went down after I executed the code "sync; echo 1 > /proc/sys/vm/drop_caches" to clear the server's cache. Would anyone know how to resolve?

![bitnami](https://user-images.githubusercontent.com/123089249/213469399-ff556eb3-bf80-4dbc-9dbb-d29fd8b58aba.jpg)

**Comment by mdhont** [comment]
Did you try restarting the services?

    sudo /opt/bitnami/ctlscript.sh restart
