### ISSUE TITLE
[wordpress] is data at rest encrypted

### ISSUE THREAD

**Issue by revolvebranding** [bitnami/vms#615]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

many images

### bndiagnostic output

N/A

### bndiagnostic was not useful. Could you please tell us why?

query about service

### Describe your issue as much as you can

Is data at rest in an AWS bitnami Wordpress image encrypted?

**Comment by jotamartos** [comment]
That's a question related to the application. You should ask the WordPress' developers to know more about its API. 

https://wordpress.org/documentation/
