### ISSUE TITLE
[Wordpress Multisite] Hosting on two domains

### ISSUE THREAD

**Issue by vporton** [bitnami/vms#616]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

unneeded

### bndiagnostic was not useful. Could you please tell us why?

It is a soft question

### Describe your issue as much as you can

I want with Bitnami Wordpress Multisite (in addition to several sites that I already have) to host the same site on two domains.

I mean either:
- https://A/path and https://B/path to produce the same output (with the same canonical link https://B/path).
- set https://A/path to redirect to https://B/path

Both variants are acceptable. Please explain each one how to do.

I want this because I to host a site first on a temporary subdomain, and later on a not-yet-bought TLD. I want old links to keep working after I move to the TLD.

**Comment by jotamartos** [comment]
It's possible that there is a plugin in WordPress that helps you do so. However, you can also configure Apache to redirect domain A to B. If you do not have more domains, just A and B and want to always use B, you can take a look at this guide 

https://docs.bitnami.com/general/apps/wordpress-multisite/administration/use-single-domain/

If you have more domains, you will need to follow a similar approach and "tell" Apache to always redirect to domain B if user is using A.
