### ISSUE TITLE
Redirect rule with Bitnami Apache How to?

### ISSUE THREAD

**Issue by SubZ82** [bitnami/vms#618]
### Describe your issue as much as you can

I am using AWS Lightsail Bitnami WordPress.

All I wish to do is implement some rewrites and redirect rules which I would normally do in an .htaccess

Appararently Bitnami does not allow .htaccess and insteaad uses this file where you can add .htaccess rules and restart Apache but it does not seem to work.

This is the file Bitnami reference:

/opt/bitnami/apache2/conf/vhosts/htaccess/wordpress-htaccess.conf

I followed their guide and made this at the end of the file but the redirect is not working.

<Directory "/opt/bitnami/wordpress/news-and-events">
RewriteEngine On 
Redirect 301 "/test/" "/test2/"
</Directory>

Surely that should work and redirect my website /test/ to /test2/ but it does not?

Any help appreciated. I also restarted apache as it mentions to do so.

Thanks

**Comment by mdhont** [comment]
Could you check the following guide? 

https://docs.bitnami.com/aws/apps/redmine/administration/use-htaccess/

**Comment by mdhont** [comment]
Can you paste the whole <Directory> block?
