### ISSUE TITLE
Download the latest stable Bitnami ownCloud .ova

### ISSUE THREAD

**Issue by carrodher** [bitnami/vms#621]
Hi

Been reliant on Bitnami ownCloud VM for years now, and found myself grown dependent on Bitnami with regards to updates. Deprecation came unexpectedly.

Is there any way to access/download the latest stable Bitnami ownCloud .ova before deprecation, to upgrade to and give more time to learn how to rebuild and maintain the ownCloud server from scratch without Bitnami?

_Originally posted by @k-keeper in https://github.com/bitnami/containers/issues/17890#issuecomment-1399528535_

**Comment by mdhont** [comment]
Hi @k-keeper,

You can download the latest stable Owncloud .ova here:

https://downloads.bitnami.com/files/stacks/owncloud/10.11.0-0/bitnami-owncloud-10.11.0-0-linux-debian-11-x86_64-nami.ova 

    md5:85d1c005bb707c05210cf6f53a75bca6

**Comment by k-keeper** [comment]
@carrodher @mdhont 
TYVM!

You saved me no less then a day of stressful researching and rebuilding. Now I can take it in stride.

**Comment by ccie51073** [comment]
Thank you very much guys. I've been using OwnCloud VM from Bitnami for a couple years. Just an average user for home. I was wondering if you guys have a group to support each other. Let me know.

**Comment by mdhont** [comment]
Thanks for your kind words. To answer your question, we handle all support issues related issues here on Github.

**Comment by dnocsc** [comment]
Thank you!

**Comment by dnocsc** [comment]
I finally found it in my inventory. If any of you would love to have the OVA, reach out to me directly.

**Comment by dnocsc** [comment]
After doing some of the things, I decided to make my own. Here's it is. Hope it's helpful.

https://github.com/dnocsc/ocim
