### ISSUE TITLE
bitnami sonarqube - support model and license for AWS

### ISSUE THREAD

**Issue by ramanakante** [bitnami/vms#622]
### Describe your issue as much as you can

We want to setup Bitnami Sonarqube in AWS cloud for 5000 users
1) want to know support model, whom to reach out 
2) How do we get enterprise sonarqube license, we want to detailed report for end users point of view.

**Comment by ramanakante** [comment]
@mdhont I am looking for enterprise level support. How we get the enterprise license, if you can provide the path so that my management will reach out.

**Comment by mdhont** [comment]
Hi @ramanakante,

Thank you for using Bitnami. Unfortunately we only offer enterprise level support to customers of the [VMware Application Catalogue](https://tanzu.vmware.com/application-catalog). For the Bitnami solutions on different cloud marketplaces we offer free support through Github.
