### ISSUE TITLE
[WordPress] Received "Product Update:" email, don't know what to do?

### ISSUE THREAD

**Issue by FWCadmin** [bitnami/vms#623]
### Name and Version

WordPress Certified by Bitnami and Automattic

### What is the problem this feature will solve?

I received the notification for the first time about an update to WordPress Certified by Bitnami and Automattic, but it is unclear how to proceed with the update. please send instructions.

### What is the feature you are proposing to solve the problem?

Need instructions to know how to update.

**Comment by jotamartos** [comment]
If you received an email from AWS notifying you about a new version, that's just an automated email from them. You can migrate your data to a new deployment or keep using your current one. 

If you decide to migrate your data, you will need to launch the latest version and follow this guide

https://docs.bitnami.com/aws/how-to/migrate-wordpress/
