### ISSUE TITLE
Lightsail Bitnami Wordpress PHP 8.2

### ISSUE THREAD

**Issue by alex-kodr** [bitnami/vms#624]
### Describe your suggestion as much as you can

Hi,

Do you know when newly created Lightsail Bitnami WordPress instances will be packaged with PHP 8.2?

Thanks

**Comment by alex-kodr** [comment]
Thanks for the replay. That makes total sense if not everything is fully supported yet. Do you know of any Bitnami Lightsail instances that allow me to upgrade PHP without starting a new instance? LAMP (PHP 8) or Nginx Packaged by Bitnami?

**Comment by mdhont** [comment]
Unfortunately, upgrading individual components is not supported. Our applications are designed to be ready to use and upgrading components tends to break things. The best thing to do to upgrade to the latest components is to launch the latest Bitnami WordPress version and migrate the data using the All in One Migration plugin.
