### ISSUE TITLE
[Odoo] cannot install Wkhtmltopdf

### ISSUE THREAD

**Issue by msdlaurense** [bitnami/vms#625]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

-

### bndiagnostic output

-

### bndiagnostic was not useful. Could you please tell us why?

-

### Describe your issue as much as you can

I installed "Odoo packaged by Bitnami" version 16.0.20221115-19-r20-linux-vm-debian-11-x86_64-nami. (https://bitnami.com/stack/odoo/virtual-machine)
I have installed this on a synology NAS running Synology Virtual Machine Manager.

Now I want to have pdf support in Odoo. 
I have to install wkhtmltopdf.
I have used "https://docs.bitnami.com/google/apps/odoo/configuration/install-wkhtmltopdf/#troubleshooting" to install this, but now I have a problem.
Because of Odoo, I have to install version 0.12.5-1 of wkhtmltopdf. But for debian 11 (bullseye) there is no version available. How do I get the right version of wkhtmltopdf for this VM package?

**Comment by mdhont** [comment]
Unfortunately all our singleVMs use Debian 11. Did you try installing the latest wkhtmltopdf?

**Comment by msdlaurense** [comment]
problem solved. I installed the latest version and it works fine!
