### ISSUE TITLE
[Drupal] Unable to find multi-tier option for Drupal, which we were previously using in December 2022

### ISSUE THREAD

**Issue by arnieraju** [bitnami/vms#626]
We are performing an upgrade of an Drupal website that is built on the Bitnami Drupal package in Azure.  As part of the upgrade process we have performed some testing in a dev subscription.

The testing we performed in December 2022, used the Multi-tier Drupal configuration from the Azure marketplace.  

<img width="874" alt="image" src="https://user-images.githubusercontent.com/1208184/214456207-5c9ae7bf-d6b0-48ab-b7ee-4f2948dd6c95.png">

We are moving through to our test subscription to build our test environment up and are no longer find the Multi-tier Drupal option.  When going to the bitnami site we are unable to find it in the options their either.

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/1208184/214456013-460fc538-2404-498c-95df-c84fa1bf4fa4.png">

The bitnami.com/stack/drupal page does mention the multi-tier image, but when you click the link (
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.multi-tier-manageddb-drupal?tab=Overview&exp=ubp8) it goes to a 404 page.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/1208184/214467256-6cd2f421-9685-41e8-8f4e-be32f198a473.png">

Are you able to advise where we can find the multi-tier option, and if it is no longer available what you would recommend for us to move forward with our upgrade project?

**Comment by jotamartos** [comment]
Hi @arnieraju,

As we mentioned in this other post, we no longer provide Multi-Tier solutions in the Azure's cloud.

https://github.com/bitnami/vms/issues/585

You will need to move to the VM, container or chart solution if you want to continue using Bitnami Drupal.

Thanks

**Comment by arnieraju** [comment]
Thanks for confirming @jotamartos - we'll start looking at the alternative options you mentioned above.
