### ISSUE TITLE
INQUIRY

### ISSUE THREAD

**Issue by GMJar** [bitnami/vms#627]
### Name and Version

Using a Bitnami Package local PC

### What steps will reproduce the bug?

Does Redmine have an online collaboration feature (multiple can edit at the same time)?

### What do you see instead?

Can't find the feature

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
