### ISSUE TITLE
[<Apache Tomcat>] <How to configure Shibboleth on a Tomcat install - >

### ISSUE THREAD

**Issue by flahr-dev** [bitnami/vms#628]
### Describe your issue as much as you can

Hi,

How are you? 

I'm a little confused about what can, and what can't be managed by apt. I assume I can't make any changes to Apache. Is there a patch management service for services that come bundled in with Apache Tomcat? Where can I find reference about what is bundled in each Bitnami Image? I'm concerned about security updates.

I bumped into that while installing and configuring shibboleth. And that is what my main objective is, but I'm finding it hard to find a way forward, using apt to install and configure Shibboleth.

I suppose an option is to just try and install it ‘apt install libapache2-mod-shib’ and see what breaks. I suspect the shibd bit will be fine but I don’t know enough about Apache modules and how they work and what assumptions there might be.

Another option might be to install the dependencies bit by bit. Looking at shibboleth-sp-utils package it seems to install most of the dependencies i.e. the actual SP binaries and daemon etc. but importantly not apache:

[root@mgtl-tomcat-vm ~]$ apt install --dry-run --no-install-recommends shibboleth-sp-utils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcurl3-gnutls libfcgi0ldbl liblog4shib2 libmemcached11 libodbc1 libsaml12 libshibsp-plugins libshibsp10 libxalan-c112
  libxerces-c3.2 libxml-security-c20 libxmltooling10 opensaml-schemas shibboleth-sp-common xmltooling-schemas
Suggested packages:
  libmyodbc odbc-postgresql tdsodbc unixodbc-bin
Recommended packages:
  libfcgi-bin
The following NEW packages will be installed:
  libcurl3-gnutls libfcgi0ldbl liblog4shib2 libmemcached11 libodbc1 libsaml12 libshibsp-plugins libshibsp10 libxalan-c112
  libxerces-c3.2 libxml-security-c20 libxmltooling10 opensaml-schemas shibboleth-sp-common shibboleth-sp-utils xmltooling-schemas
0 upgraded, 16 newly installed, 0 to remove and 0 not upgraded.
Inst liblog4shib2 (2.0.0-2 Debian:11.6/stable [amd64])
Inst libmemcached11 (1.0.18-4.2 Debian:11.6/stable [amd64])
Inst libodbc1 (2.3.6-0.1+b1 Debian:11.6/stable [amd64])
Inst libcurl3-gnutls (7.74.0-1.3+deb11u3 Debian:11.6/stable [amd64])
Inst libxerces-c3.2 (3.2.3+debian-3 Debian:11.6/stable [amd64])
Inst libxalan-c112 (1.12-6 Debian:11.6/stable [amd64])
Inst libxml-security-c20 (2.0.2-4 Debian:11.6/stable [amd64])
Inst libxmltooling10 (3.2.0-3 Debian:11.6/stable [amd64])
Inst libsaml12 (3.2.0-2 Debian:11.6/stable [amd64])
Inst opensaml-schemas (3.2.0-2 Debian:11.6/stable [all])
Inst shibboleth-sp-common (3.2.2+dfsg1-1 Debian:11.6/stable [all])
Inst xmltooling-schemas (3.2.0-3 Debian:11.6/stable [all])
Inst libshibsp10 (3.2.2+dfsg1-1 Debian:11.6/stable [amd64])
Inst libshibsp-plugins (3.2.2+dfsg1-1 Debian:11.6/stable [amd64])
Inst libfcgi0ldbl (2.4.2-2 Debian:11.6/stable [amd64])
Inst shibboleth-sp-utils (3.2.2+dfsg1-1 Debian:11.6/stable [amd64])
Conf liblog4shib2 (2.0.0-2 Debian:11.6/stable [amd64])
Conf libmemcached11 (1.0.18-4.2 Debian:11.6/stable [amd64])
Conf libodbc1 (2.3.6-0.1+b1 Debian:11.6/stable [amd64])
Conf libcurl3-gnutls (7.74.0-1.3+deb11u3 Debian:11.6/stable [amd64])
Conf libxerces-c3.2 (3.2.3+debian-3 Debian:11.6/stable [amd64])
Conf libxalan-c112 (1.12-6 Debian:11.6/stable [amd64])
Conf libxml-security-c20 (2.0.2-4 Debian:11.6/stable [amd64])
Conf libxmltooling10 (3.2.0-3 Debian:11.6/stable [amd64])
Conf libsaml12 (3.2.0-2 Debian:11.6/stable [amd64])
Conf opensaml-schemas (3.2.0-2 Debian:11.6/stable [all])
Conf shibboleth-sp-common (3.2.2+dfsg1-1 Debian:11.6/stable [all])
Conf xmltooling-schemas (3.2.0-3 Debian:11.6/stable [all])
Conf libshibsp10 (3.2.2+dfsg1-1 Debian:11.6/stable [amd64])
Conf libshibsp-plugins (3.2.2+dfsg1-1 Debian:11.6/stable [amd64])
Conf libfcgi0ldbl (2.4.2-2 Debian:11.6/stable [amd64])
Conf shibboleth-sp-utils (3.2.2+dfsg1-1 Debian:11.6/stable [amd64])

I’m guessing that would get shibd running but of course there is no Apache module and I’m not sure where to go from there. I don’t think we could just take mod_shib.so out of the libapache2-mod-shib package and put it in the right place. Although it does look like it is built against the same version of Apache so maybe that works?! The additional dependencies that are listed for the full ‘apt install --dry-run --no-install-recommends libapache2-mod-shib’ look like (some of which are already on the system):

Inst libapr1 (1.7.0-6+deb11u1 Debian:11.6/stable [amd64])
Inst libaprutil1 (1.6.1-5 Debian:11.6/stable [amd64])
Inst libaprutil1-dbd-sqlite3 (1.6.1-5 Debian:11.6/stable [amd64])
Inst libaprutil1-ldap (1.6.1-5 Debian:11.6/stable [amd64])
Inst libjansson4 (2.13.1-1.1 Debian:11.6/stable [amd64])
Inst liblua5.3-0 (5.3.3-1.1+b1 Debian:11.6/stable [amd64])
Inst apache2-bin (2.4.54-1~deb11u1 Debian:11.6/stable [amd64])
Inst libapache2-mod-shib (3.2.2+dfsg1-1 Debian:11.6/stable [amd64])

Any idea how I could move approach the problem?
Thank you very much.
All the best,
Fabio

**Comment by mdhont** [comment]
The following guide explains how you can install Apache modules:

https://docs.bitnami.com/aws/infrastructure/lamp/configuration/enable-modules/

**Comment by flahr-dev** [comment]
Thanks Michiel. 

The link you sent is for the LAMP image, does the same apply to Apache Tomcat one?

A couple of things that still puzzle me about managing and patching bitnami stack. 
How can I determine what is services/apps are bundled with a Bitnami image? How is security patches provisioned to those bundled apps/modules? Is there documentation about what is bundled and what is not, or how to find out?
Using 'apt list --installed' doesn't list apache/httpd, or tomcat for that matter although it does list mariadb.

For example in the case of Apache Tomcat, what comes bundled, and how does that get security patches applied?
Thanks again.
All the best,
Fabio

**Comment by mdhont** [comment]
Bitnami images do not use system components, they include all necessary dependencies and services within the image itself. Our images all use the latest components versions, including security patches. To upgrade we recommend launching a newer version of the image and migrate the data to the new instance. 

Is there documentation about what is bundled and what is not, or how to find out?Is there documentation about what is bundled and what is not, or how to find out?

You can find more information about how to install Apache Tomcat modules here:

https://docs.bitnami.com/virtual-machine/infrastructure/tomcat/configuration/enable-modules//

**Comment by flahr-dev** [comment]
Sorry but I can't understand the opacity. You didn't answer my questions. What is bundled with the image and what can/has to be updated via apt? Security updates are posted on a daily basis, how do these get applied to apache for example? Just enabling modules is not enough. Thanks

**Comment by mdhont** [comment]
Please accept my apologies for not being clear enough. To answer your questions:

>  What is bundled with the image and what can/has to be updated via apt?

Bitnami images are bundled with the latest component versions. The components packed with each image are different per application. You can check the Changelog for the component versions and paches applied:

https://bitnami.com/stack/tomcat/amidebian-x64-hvm-ebs-nami/changelog.txt

Using the apt commands will update packages in the system (ssh, openssl, and other libraries) but it will not update the packed components. (which are mentioned in the Changelog)

>  how do these get applied to apache for example? 

As our images are updated on a daily basis, and contain the latest versions, we recommend launching a new image on a regular basis and then migrate your application to the new instance.

**Comment by flahr-dev** [comment]
Hi Michael,
Thanks for getting back to me. Sorry for the delay getting back to you.
Sorry but does that mean that apache does not receive security patches and
fixes when they are released?
You should consider some mechanism to allow applying updates and security
patches, it is very poor information security practice not to allow for
that. Building a new instance and migrating an application seems to be a
poor and expensive model for patch management.
If we can't find a workaround for that deficiency, we won't be able to use
or recommend the use of bitnami images internally or to any of our clients.
It's convenient to be able to spin an image but with no patch management,
it would be irresponsible to use it in production. Thanks.
All the best,
Fabio

**Comment by mdhont** [comment]
Hi @flahr-dev ,

I apologize for the misunderstanding. To clarify, while Bitnami images come with the latest versions of their components, applying patches to those components is not officially supported.

Our images are designed to provide an easy-to-use, pre-configured environment, but they may not meet the patch management needs of all users. If you require a more flexible patch management solution, you may want to consider building your environment from scratch or using a different tool or platform that offers more robust patch management capabilities.

I hope this clarifies the situation, and please let me know if you have any further questions or concerns.
