### ISSUE TITLE
[Newbie issue] Can't find old WP site

### ISSUE THREAD

**Issue by Pajeeet** [bitnami/vms#629]
### Describe your issue as much as you can

Sorry if this is wrong forum for such a question, but it was linked as support on Bitnami website...

I formated my PC, with Windows built in tool and I had a Bitnami installed on ssd with my project website.
I found the old bitnami folder, but it seems to have the default Bitnami starting website.
Could you please help me find my project website?

**Comment by mdhont** [comment]
Unfortunately we no longer offer support for Windows installers.
