### ISSUE TITLE
[Wordpress] <site can't be reached>

### ISSUE THREAD

**Issue by joshbognet** [bitnami/vms#63]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c0d652fb-250f-0067-666a-45395c035692

### bndiagnostic was not useful. Could you please tell us why?

the diagnostics was succesful

### Describe your issue as much as you can

hello, i recently installed bitnami wordpress and suddenly i can't access my website anymore (site can't be reached)

**Comment by mdhont** [comment]
The Apache error log has the following error:

```
     33 [Fri Jul 01 12:38:19.509591 2022] [mpm_winnt:notice] [pid 3512:tid 352] AH00354: Child: Starting 64 worker threads.^M
     34 VirtualProtect() failed [87] The parameter is incorrect
     35 VirtualProtect() failed [87] The parameter is incorrect
```
This seems to be related to the Elementor plugin. Can you try to disable it?

```
wp plugin deactivate elementor
```
