### ISSUE TITLE
AWS Lightsail instance keeps going down

### ISSUE THREAD

**Issue by dion1231** [bitnami/vms#630]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

686d1f69-75da-c500-2e34-d6c5ee1199bb

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 472 343 5 44 122 72 Swap: 634 
167 466
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Wordpress]

Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Jan 25 08:11:00.386434 2023] [proxy_fcgi:error] [pid 57388:tid 
140240698185472] (70007)The timeout specified has expired: [client 
**ip_address**:27522] AH01075: Error dispatching request to : (polling)
 [Wed Jan 25 08:11:01.561808 2023] [proxy_fcgi:error] [pid 67236:tid 
140240639436544] (70007)The timeout specified has expired: [client 
**ip_address**:64666] AH01075: Error dispatching request to : (polling)
 [Wed Jan 25 08:11:06.524735 2023] [proxy_fcgi:error] [pid 57138:tid 
140240396179200] (70007)The timeout specified has expired: [client 
**ip_address**:35146] AH01075: Error dispatching request to : (polling)

```
Press [Enter] to continue:
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

The Lightsail instance is relatively small in size and doesn't tell me why it's running out of resources

### Describe your issue as much as you can

The Lightsail wordpress instance I have intermittently goes offline. Which appears to be a memory resource issue according to the diagnostic tool. However, I have other LS Wordpress instances where they are far larger in size and do not have memory issues.   

Is it possible it's as simple as the image media loading on the pages are not optimized enough in size that this creates a memory hog?  I have a caching plugin and also Cloudflare CDN to optimize the site so I'm not sure why it's still getting overloaded.

Thank you!

**Comment by mdhont** [comment]
It could be due to a single or multiple plugins that make heavy use of the database, which can consume a lot of RAM.  I recommend disabling all plugins and then enabling them one by one to see which one is the most resource heavy.
