### ISSUE TITLE
[<Redmine>] <Bitnami-Redmine under VM virtual box manager can't be started.>

### ISSUE THREAD

**Issue by mwdqaqc** [bitnami/vms#631]
### Describe your issue as much as you can

Windows 2019 server.
Download bitnami-redmine-5.0.4-8-r11-linux-vm-debian-11-x86_64-nami

Then download VirtualBox-7.0.6-155176-Win.exe and VC_redist.x64.exe

Do the installation and import Download bitnami-redmine-5.0.4-8-r11-linux-vm-debian-11-x86_64-nami to the VM virtualbox.

bitnami-redmine vm aborted.
![bc29b8ec-5eb5-43d5-9ecb-5416c6c352a4](https://user-images.githubusercontent.com/74789498/214648780-bcfe6721-bb3a-4e55-ba46-2613e9369226.jpg)

![image](https://user-images.githubusercontent.com/74789498/214649096-3841bd64-65b0-4526-8898-e9aa41cd6a1c.png)

Please advise!

**Comment by mdhont** [comment]
Is it possible to launch other VM's. Can you try for example Bitnami WordPress?

**Comment by mwdqaqc** [comment]
![image](https://user-images.githubusercontent.com/74789498/214919815-b954a8d9-4f63-4066-bb6a-d3f34598c066.png)
Which OS should I select here?
Just want make sure I didn't make some stupid mistake.
Debian-64?

**Comment by mwdqaqc** [comment]
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:600;">VM Name:</span> bitnami-redmine<br /></p>
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Failed to load API DLL: WinHvPlatform.dll: VERR_MODULE_NOT_FOUND; vid.dll: VERR_MODULE_NOT_FOUND (VERR_NEM_INIT_FAILED).</p>
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">VT-x is not available (VERR_VMX_NO_VMX).</p>


Result Code: | E_FAIL (0X80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {6ac83d89-6ee7-4e33-8ae6-b257b2e81be8}

</body></html>

**Comment by mdhont** [comment]
Can you try launching a non bitnami VM? I suspect it is due to the configuration of the machine or VirtualBox.
