### ISSUE TITLE
[AWS Bitnami WordPress HA] Intermittent 504 Gateway Timeout errors

### ISSUE THREAD

**Issue by alidgett** [bitnami/vms#632]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4fee3b82-0ade-ec7c-f20f-a3f6e5321612

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ? Connectivity: Found possible issues
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Some files don't have the expected permissions Please check the following guide:

https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 7769 4406 597 107 2765 2962
Press [Enter] to continue:Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

We don't have access to the diagnostic output to know which files need to be corrected and the links provided (except one, don't work)

### Describe your issue as much as you can

We are using running WordPress using the Bitnami WordPress HA images obtained from the AWS Marketplace. We are seeing intermittent but disruptive 504 Gateway Timeout errors from the web server(s) and have not been able to identify the root cause.

The Apache error_log file shows similar entries around the time the issue occurs:
[Wed Jan 25 19:19:45.052475 2023] [proxy_fcgi:error] [pid 28466:tid 140327285339904] (70007)The timeout specified has expired: [client x.x.x.x:38700] AH01075: Error dispatching request to : (polling), referer: https://login.microsoftonline.com/
[Wed Jan 25 19:37:29.532475 2023] [proxy_fcgi:error] [pid 28466:tid 140327369266944] (70007)The timeout specified has expired: [client x.x.x.x:59034] AH01075: Error dispatching request to : (polling), referer: https://login.microsoftonline.com/

The predominate use case impacted by this issue is when users are being redirected back to the WordPress site after Microsoft AZURE SSO authentication with the auth cookie. 

Unfortunately this is becoming a serious production issue for us - has anyone else resolved this issue or been able to obtain assistance in further troubleshooting? Any assistance in this regard would be greatly appreciated.

**Comment by gongomgra** [comment]
Hi @alidgett,

Thanks for using Bitnami and for reporting the errors with the URLs from the bndiagnostic output. I will open an internal task to update them.

Regarding your issues, I see in the bndiagnostic output that you are running out of free memory, although you are using big instances. I also see your are receiving a lot of requests from three different IP addresses, which can be exhausting your machine resources in case it is a bot attack. Can you check [our guide about this](https://docs.bitnami.com/aws-templates/faq/configuration/block-suspicious-ip/)?

```
-----------------------------------
Check performance issues: Count number of requests for the 10 most active IP addresses in the last 100.000 requests
-----------------------------------
Running: tail -n 100000 access_log | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 10 | awk '{print $1}'
In: /opt/bitnami/apache2/logs/

Output:

15184
15063
8743
```

I also found a couple of error messages in the Apache log file (you can check it by yourself at `/opt/bitnami/apache2/logs/error_log`). It looks like there is an issue with your custom theme, plus a timeout handling the requests. Can you try updating [the timeout setting](https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/modify-execution-time/) in all nodes? Remember to restart the services for changes to take effect.

```
[Mon Jan 23 02:03:52.271440 2023] [proxy_fcgi:error] [pid 20685:tid 139705781790464] [client 10.155.9.90:13490] AH01071: Got error 'PHP message: PHP Warning:  Trying to access array offset on value of type null in /bitnami/wordpress/wp-content/themes/CAWeb-1.5.0/inc/class-caweb-nav-menu.php on line 97PHP message: PHP Warning:  Trying to access array offset on value of type null in /bitnami/wordpress/wp-content/themes/CAWeb-1.5.0/inc/class-caweb-nav-menu.php on line 97PHP message: PHP Warning:  Trying to access array offset on value of type null in /bitnami/wordpress/wp-content/themes/CAWeb-1.5.0/divi/extension/includes/modules/header-slideshow-banner-fullwidth/header-slideshow-banner-fullwidth.php on line 145PHP message: PHP Warning:  Trying to access array offset on value of type null in /bitnami/wordpress/wp-content/themes/CAWeb-1.5.0/divi/extension/includes/modules/post-detail/post-detail.php on line 1487'
[Mon Jan 23 05:19:54.032558 2023] [proxy_fcgi:error] [pid 20685:tid 139706872350464] (70007)The timeout specified has expired: [client 10.155.5.120:51426] AH01075: Error dispatching request to : (polling)
```

Apart from the above, we recommend you to ask in the [official wordpress forums](https://wordpress.org/support/forums/), or to the theme's developers for further help on this.

**Comment by alidgett** [comment]
Hi, I understand that this is open source and community based support, but nothing here assists us with troubleshooting the issue we are experiencing, what use/point of the bndiagnostic tool if is cannot tell us which files or folders may have permissions issues.  Yes we know there are issues that is why we are requesting assistance. We have isolated all traffic to our instance except that which causes the issue so memory and timeout extensions would only wallpaper over the true root cause of the issue. Nobody can tell us how to debug and get deeper into this issue.

**Comment by gongomgra** [comment]
Hi @alidgett,

I'm afraid we don't have enough information on how the custom theme or WordPress itself work in your specific scenario, that's why we recommended you to ask in a more specialized forum. 

On the other hand, we can help you with what is detected by our tool, which should (at least a bit) improve the overall performance of your website. The Apache log is filled entirely with the same theme error message. Additionally, and according to the AWS docs, the 504 error code through CloudFront can be related to application delays and server timeouts, which is one of the issues our tool detected. We recommend you to check it and try to fix that issue first. After that, it is possible that you find another issue that was causing the first one.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-504-gateway-timeout.html
