### ISSUE TITLE
Resource Space VM with Debian 10 - Apache Log File Format

### ISSUE THREAD

**Issue by Kyosho** [bitnami/vms#634]
### Describe your issue as much as you can

I would like to be able to modify the Bitnami Stack used with ResourceSpace in a VM that is up and running so that the Apache log configuration uses the combined format that is needed by AWStats.

I modified /home/bitnami/stack/apache2/conf/bitnami/bitnami-ssl.conf, but AWStats keeps complaining my log file format is not in the expected combined format.

Any ideas?

**Comment by mdhont** [comment]
Can you tell me which log file is AWStats referring to?

**Comment by mdhont** [comment]
We don't make any changes to the Apache error log, it should be the same as any other Apache installation. Could it be a permissions issue?

**Comment by Kyosho** [comment]
Thanks for stepping in Michiel. I have attached a zip file with some exhibits.

I was able to modify the format of the Apache access_log file (rather than the error_log) to combined by editing this file:

/opt/bitnami/apache2/conf/httpd.conf

You also have Apache configuration files at:
/opt/bitnami/apache2/conf/vhosts/resourcespace-https.vhost.conf
/opt/bitnami/apache2/conf/bitnami/bitnami-ssl.conf
I have included those files.

I am able to now execute the Perl script for AWStats from the command line.

I would like to be able to run AWStats from the browser. The suggested URL is:
http://media-archive.zmmapple.com/cgi-bin/awstats.pl?config=media-archive.zmmapple.com

This still results in a 403 Forbidden. I enclosed a screenshot.

AWStats executable is located in: 
/usr/lib/cgi-bin/awstats.pl

Not sure if you might have any suggestions about this, but it's worth a try.

[AWStat Configuration Problems-20230127T005637Z-001.zip](https://github.com/bitnami/vms/files/10514616/AWStat.Configuration.Problems-20230127T005637Z-001.zip)

**Comment by mdhont** [comment]
It seems related to file permissions, please check the following guide: 

https://docs.bitnami.com/aws/how-to/troubleshoot-permission-issues/
And for setting up a vhost:

https://docs.bitnami.com/virtual-machine/infrastructure/lamp/configuration/configure-custom-application/

I also recommend contacting the AWStats support team, they might be able to help you better.

**Comment by Kyosho** [comment]
Yes, it was a permissions issue. I had to add the lines enabling access to /usr/lib/cgi-bin into httpd.conf and then it worked.

However, when I run AWStats in the browser, rather than executing awstats.pl, it displays the text of the awstats.pl Perl executable itself. An online suggestion is maybe CGI is not enabled in Apache. Usually in an Apache configuration I run sudo a2enmod cgi. But in this Bitnami stack, there is no such command: (sudo: a2enmod command not found)

Any ideas? How do you enable CGI in a Bitnami stack?

**Comment by mdhont** [comment]
The cgi module is already enabled: 

```
apachectl -M | grep cgi
 proxy_fcgi_module (shared)

```
