### ISSUE TITLE
[<AWS Lightsail>] <Stack LAMP suddenly stopped working>

### ISSUE THREAD

**Issue by AlessandroFr** [bitnami/vms#635]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b4f0d016-2d59-78eb-b8fa-85f764e0e78b

### bndiagnostic output

? Resources: Found possible issues
? Connectivity: Found possible issues
✓ Mariadb: No issues found
✓ Processes: No issues found
? Apache: Found possible issues
✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are no related whit my issue as all the firewall rule are nsettled correctly

### Describe your issue as much as you can

Suddenly if you try to access the site the machine gives ERR_CON_REFUSED or ERR_FAILED as a result, it seems that there has been an error in the startup scripts of the bitnami stack.

**Comment by mdhont** [comment]
Can you check the machines resources? The Bndiagnostic tool is showing this error: 

? Resources: Found possible issues

That usually means the instance is low on RAM.

**Comment by AlessandroFr** [comment]
total        used        free      shared  buff/cache   available
Mem:          975Mi       78Mi       102Mi       4.0Mi       795Mi       751Mi
Swap:          634Mi       0.0Ki       634Mi

Over there the result of **free -h**

**Comment by mdhont** [comment]
It seems there's not a lot of free memory. I recommend upgrading to a machine with more RAM.
