### ISSUE TITLE
Bitnami Wordpress multiple process disable banner

### ISSUE THREAD

**Issue by JostickQuielCiat** [bitnami/vms#636]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7793fd49-436a-80bc-3449-d25d87beba83

### bndiagnostic output

100% CPU USAGE

### bndiagnostic was not useful. Could you please tell us why?

.

### Describe your issue as much as you can

I have multiple process from httpd.bin httpd.conf --DDISABLE_BANNER and all this process have a 100% CPU USAGE on my server.

this is the code generated with Bitnami Diagnostic Tool
7793fd49-436a-80bc-3449-d25d87beba83

**Comment by gongomgra** [comment]
Hi @JostickQuielCiat,

Thanks for using Bitnami. Those apache processes are started by your server to attend the requests. The `DISABLE_BANNER` flag is a setting to avoid showing a button in the botton right corner of the website. Regarding the CPU usage, it looks like the bndiagnostic tool didn't retrieve the Apache logs, so I can't check it further. Can you check the log file at `/opt/bitnami/apache2/logs/error_log`? The only reference I get about this file in your diagnostic bundle is the next error message. Can you check it as well?

```
apache2: Syntax error on line 81 of /opt/bitnami/apache2/conf/httpd.conf: Cannot load modules/mod_authn_file.so into server: libiconv.so.2: cannot open shared object file: No such file or directory
```

Apart from the above, and according to the bndiagnostic tool, you are using a XAMPP installation. Is that correct? In that case, we recommend you to open a new question in the official XAMPP forums, as this is no longer a product offered by us but from the XAMPP community developers.

https://community.apachefriends.org/f/
