### ISSUE TITLE
The ERPNext packaged by bitnami default credentials authentication error

### ISSUE THREAD

**Issue by Sertsev** [bitnami/vms#637]
I properly added the ERPNext packaged by bitnami. Then started it, then successfully accessed it through the browser using the virtual machine IP address, but When I try to log in with the default:
      username: user@example.com 
      password: the default password generated and shown on the terminal 
![ERPNext](https://user-images.githubusercontent.com/53481194/214841877-11e20827-1584-46e5-9c63-d82666933efd.PNG)

But It is not logging in
![image](https://user-images.githubusercontent.com/53481194/214842033-3bec2f27-d07c-4111-a909-fe7a26a99b8f.png)

When I checked the browser console, it shows the following error,
                    ``` POSThttps://192.168.131.45/
                    [HTTP/1.1 401 UNAUTHORIZED 388ms]
                    
                    Traceback (most recent call last):
                      File "apps/frappe/frappe/app.py", line 55, in application
                        init_request(request)
                      File "apps/frappe/frappe/app.py", line 132, in init_request
                        frappe.local.http_request = frappe.auth.HTTPRequest()
                      File "apps/frappe/frappe/auth.py", line 34, in __init__
                        self.set_session()
                      File "apps/frappe/frappe/auth.py", line 68, in set_session
                        frappe.local.login_manager = LoginManager()
                      File "apps/frappe/frappe/auth.py", line 108, in __init__
                        if self.login() is False:
                      File "apps/frappe/frappe/auth.py", line 133, in login
                        self.authenticate(user=user, pwd=pwd)
                      File "apps/frappe/frappe/auth.py", line 239, in authenticate
                        self.fail("Invalid login credentials", user=_raw_user_name)
                      File "apps/frappe/frappe/auth.py", line 292, in fail
                        raise frappe.AuthenticationError
                    frappe.exceptions.AuthenticationError ```

What should I do?

**Comment by Sertsev** [comment]
Finally found the answer.

The username was incorrect, there is no user connected with the 'user@example.com'. Bitnami should remove it from their documentation. Instead of the 'user@example.com' they stated as user name use the following:
```
    username: Administrator
    password: the default password generated
```

**Comment by mdhont** [comment]
That's weird. It should be user@example.com. I've not been able to reproduce the, but we will further investigate it.

**Comment by emilioferreyra** [comment]
I have tried both user@example.com and Administrator and neither works.

**Comment by emilioferreyra** [comment]
Thanks for the reply. I deleted the virtual machine and loaded it again and this time it worked with user user@example.com and a new auto-generated password.  So the VM is up and running right now.  Thank you @gongomgra

**Comment by gongomgra** [comment]
Hi @emilioferreyra,

Thanks for your message. Glad to know it ended up working for you!

**Comment by PITPL-Akshay-Prajapati** [comment]
I have tried both user@example.com and Administrator but not working.

Thanks and regards
Akshay

**Comment by mdhont** [comment]
Can you try to run it manually and tell me the output?

sudo /opt/bitnami/mariadb/bin/mariadbd-safe

**Comment by gongomgra** [comment]
Hi @PITPL-Akshay-Prajapati,

Thanks for using Bitnami. We couldn't reproduce your issue. Can you check the content of the `first-boot.log` file mentioned previously? Remember also that the initialization process of ERPNext may take a bit longer than expected and that, although the web interface may be up and running at some point, the initialization process behind may be updating the required data and stopping/starting the required services.
