### ISSUE TITLE
Need help with speedup wordpress

### ISSUE THREAD

**Issue by itsmemidhuz123** [bitnami/vms#640]
### Describe your suggestion as much as you can

hi, have tried several things to speedup wordpress but unable to find whats the exact issue, using catching cdn even though the website is slower. could you please tell what all the things should i follow except installing a plugin because every time server usage is really low even the plugin are deactivated. this happen only when switched to bitnami aws

what all modules should i use to make the perfomance better

**Comment by mdhont** [comment]
The following guides might be of help:

https://docs.bitnami.com/aws/faq/administration/improve-server-performance/
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/optimize-bitnami-wordpress/

**Comment by itsmemidhuz123** [comment]
these are the regular docs sir please understand  and dosent make any changes in website sir. Is it possible to identify what request slow down my website because we hve a different website and lesss configuration but it havent any issus


please help

**Comment by mdhont** [comment]
I recommend checking if any plugin is causing the issue by deactivating all plugins and then activating them one by one and check the memory usage in the meantime. I also recommend asking in the WordPress forum.

**Comment by itsmemidhuz123** [comment]
sure

**Comment by itsmemidhuz123** [comment]
hi, how do i able to see the ip request log on the server

**Comment by jotamartos** [comment]
The requests you receive are log in the access.log file inside the /opt/bitnami/apache/logs directory.
