### ISSUE TITLE
[Redmine] The machine couldn't configure the network interface

### ISSUE THREAD

**Issue by mwdqaqc** [bitnami/vms#643]
### Describe your issue as much as you can

Server team helped me set up a Linux VM.
Linux Debian machine
<The machine couldn't configure the network interface>

I can't find IP address for that machine.
Do I need config IP address?
How?
Please advise!

![image](https://user-images.githubusercontent.com/74789498/215187296-7e03aa40-6cc9-4aee-87db-3dadd472c70e.png)

**Comment by jotamartos** [comment]
Does the host machine have enough RAM memory to run that VM? If so, can you try to increase the resources of the VM to avoid issues during the initialization?

**Comment by Wolfsagency** [comment]
I have the same problem anybody please us to figure it out

**Comment by jotamartos** [comment]
> Does the host machine have enough RAM memory to run that VM? If so, can you try to increase the resources of the VM to avoid issues during the initialization?

Please check this ⬆️
