### ISSUE TITLE
[Redmine] Can I have latest Redmine native installer for Windows server?

### ISSUE THREAD

**Issue by mwdqaqc** [bitnami/vms#644]
### Describe your issue as much as you can

Can I have latest Redmine native installer for Windows server?

We have bitnami-redmine-4.2.2-1-windows-x64-installer.

What is the latest windows installer before Linux VM: bitnami-redmine-5.0.4-8-r11-linux-vm-debian-11-x86_64-nami

Really appreciate your help!

Lei

**Comment by jotamartos** [comment]
This is the last Bitnami Redmine installer for Windows we published 

https://downloads.bitnami.com/files/stacks/redmine/5.0.3-0/bitnami-redmine-5.0.3-0-windows-x64-installer.exe

**Comment by xuyang0410** [comment]
Hi  Jotamartos
 So do we have the lastest  Bitnami Redmine installer for linux.? My linux distribution is centos7.9.

**Comment by jotamartos** [comment]
This is the last Bitnami Redmine Linux installer we published 

https://downloads.bitnami.com/files/stacks/redmine/4.2.1-3/bitnami-redmine-4.2.1-3-linux-x64-installer.run

**Comment by xuyang0410** [comment]
@jotamartos   Oh, so cool, thanks very much!

**Comment by mwdqaqc** [comment]
Thanks a lot for your help!

**Comment by jibo2023** [comment]
Hi Jotamartos
So do we have  Bitnami Redmine 1.1.2-1 installer for Windows.?

**Comment by jotamartos** [comment]
Hi @jibo2023,

Thanks for your interest but we can't provide you with that version. We deprecated installers long time ago and we can only share the latest one we released. In your case, the installer you are requesting is 10+ years old and is no longer available.

**Comment by jibo2023** [comment]
Hi Jotamartos
Thanks.
I would like to be provided with a Windows server 2016 support version.

**Comment by jotamartos** [comment]
The last Redmine installer we published is this one 

https://downloads.bitnami.com/files/stacks/redmine/5.0.3-0/bitnami-redmine-5.0.3-0-windows-x64-installer.exe
