### ISSUE TITLE
[Redmine] SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) 

### ISSUE THREAD

**Issue by gorani25** [bitnami/vms#645]
### Describe your issue as much as you can

No work or test emails have been sent since November 2022.

Issue statement below will be exposed and not allowed
"An error occurred while sending the email (SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)

If the https://www.wormly.com/test-smtp-serve test proceeds ok. 

Please let me know if it's because the SSL certificate is not applied to our domain address.

**Comment by gorani25** [comment]
@jotamartos Redmine Due to the issue, there is a difficulty in proceeding with the project, so please help me.

**Comment by jotamartos** [comment]
What Bitnami Redmine version are you using? If you are using an old one, you probably need to update the certificates in the machine/installation with the latest ones. These commands should work in case you are using a cloud image

```
sudo apt update
sudo apt install ca-certificates 
cd /tmp
curl -LJO "https://curl.se/ca/cacert.pem"
sudo mv cacert.pem /opt/bitnami/common/openssl/certs/curl-ca-bundle.crt
sudo /opt/bitnami/ctlscript.sh restart
```
