### ISSUE TITLE
[Bitnami Redmine Stack] Redmine version 4.1.0 cannot start after reboot

### ISSUE THREAD

**Issue by iamriz** [bitnami/vms#646]
Installed Bitnami Redmine Stack that used Redmine version 4.1.0 on a cloud server but spent a day already figuring out why redmine cannot start after reboot. Before reboot, installation seemed to be successful. Redmine server is running. However, after reboot, for unknown reason, we cannot run Redmine server. In E:\redmine-4.1.0-9\apps\redmine\htdocs\log\production.log, we can see these messages written after trying to do Restart All via Bitnami Redmine Stack Manager Tool, which does not seem to make sense:

```
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :system. Overwriting existing method Group.sorted.
Creating scope :system. Overwriting existing method User.sorted.
```

Already tried to use another port but still both of thin and thin2 clusters of redmine cannot start. Both Apache web server and MySQL Database are running, though. 

Any other hints what could be the cause of why this is happening? Thank you very much.

**Comment by iamriz** [comment]
As an UPDATE: Apparently, there was an error logged in Event Viewer, but was not found right away because it was labeled as info. This is a log when Thin/Thin2 redmine is restarted. The error message is "Access denied for user 'user'@'localhost' (using password: YES)". Has anyone have clue with regards to how to change the user being used by Bitnami Manager Tool when restarting the Thin/Thin2 redmine service?

**Comment by gongomgra** [comment]
Hi @iamriz,

Thanks for using Bitnami. The thin servers serve Redmine for HTTP requests, so at the end it is Redmine the one trying to connect with the databae. Can you check the database information under the `E:\redmine-4.1.0-9\apps\redmine\htdocs\config\database.yml` file and try to manually connect with the database? You can load the environment (to be able to run the `mysql` command easily) executing the `E:\redmine-4.1.0-9\bnconsole.exe` file. It will open a terminal with the Bitnami environment already loaded.

Apart from the above, please notice that the local installers have been deprecated in favor of our virtual-machines solutions. We recommend you to use the virtual-machine instead and migrate your application data into it.

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

**Comment by iamriz** [comment]
@gongomgra, thank you very much for your advice above. Updating database.yml to the correct credentials made the redmine services up and running again.

**Comment by iamriz** [comment]
@gongomgra, May we know why Thin_redmine service would successfully run after installation, but would fail when restarting with Bitnami Redmine Stack? Is it a bug in the installer?

**Comment by gongomgra** [comment]
Hi @iamriz,

Restarting the services shouldn't cause any error out of the box. Is it possible that there were any other database process running on the server at the same time? We also found issues in the past when the password introduced during the installation step included some weird characters, but that doesn't seem to be the issue here. I'm sorry but I can't think of anything more or less obvious that can cause it. 

Anyways, notice that local installations aren't supported anymore, and that we highly encourage you to use either the container or the virtual-machines solutions instead.
