### ISSUE TITLE
AWS is asking for Elastic Network Adapter support when trying to launch a new instance from my AMI

### ISSUE THREAD

**Issue by tooliedotter** [bitnami/vms#648]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e43378af-decc-2714-bd94-ca6adb0d0b61

### bndiagnostic output

```
[Mon Jan 30 16:19:18.104916 2023] [proxy_fcgi:error] [pid 12636:tid
139644125562624] [client **ip_address**:17013] AH01079: failed to make
connection to backend: httpd-UDS
 [Mon Jan 30 20:10:12.217415 2023] [autoindex:error] [pid 5355:tid
140649030346496] [client **ip_address**:49885] AH01276: Cannot serve directory
/opt/bitnami/apps/letsencrypt/.well-known/: No matching DirectoryIndex
Press [Enter] to continue:
(index.html,index.html,index.htm,index.php) found, and server-generated
directory index forbidden by Options directive, referer: binance.com
 [Mon Jan 30 20:15:43.865131 2023] [proxy_fcgi:error] [pid 5353:tid
140649021953792] [client **ip_address**:35929] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer:
https://www.grantcountybeat.com/administrator/index.php?option=com_media

```

### bndiagnostic was not useful. Could you please tell us why?

My problem cannot be solved or identified by bndiagnostic

### Describe your issue as much as you can

I'm trying to create a copy (an AMI) of the Bitnami LAMP stack my client is using so that we can try for better hardware. Her instance CPU without warning drops so low that the Joomla website crashes and has to be rebooted. BUT AWS still sees the instance as viable with Health Checks coming back as valid. I cannot see anything in the Bitnami stack logs that tells us why this is happening, so we've concluded that our only recourse is to create a copy and then re-launch that AMI on a new r5a.large instance (same as the current one). 

AWS won't let me use the AMI I've created because it is now asking for the "Elastic Network Adapter" support to be installed on the instance. When I try to use the AMI (copy) as-is, it greys out the r5a.large option because my AMI lacks ENA.

Have you heard of this happening? Do you have a script I can run to install the ENA? This was supposed to be an easy option, and I'd rather not risk adding the ENA support before launching a copy with my AMI if I can work around it.

**Comment by mdhont** [comment]
It should be possible to clone an instance following the steps in this guide:

https://docs.bitnami.com/aws/faq/administration/clone-server/

If you encounter any issues I recommend asking in the AWS forum. They might be able to help you further.

**Comment by tooliedotter** [comment]
Indeed, it should be that easy, but as described above, I am unable to use the same instance type for the clone due to this new requirement. I didn't find any information about ENA support on the Bitnami site, so I suspect this is the first time anyone has reported it. I will reply again with screen shots so you can see.

**Comment by tooliedotter** [comment]
I was just in the process of providing the screen shots when AWS suddenly decided to let me use the same instance type. I'm going to try for real this evening, so please keep this open until I confirm that it worked after all. I made no changes; someone at AWS must have discovered the issue and fixed it.

**Comment by tooliedotter** [comment]
This is OK to close; the issue seems to have fixed itself.
