### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by huishen97** [bitnami/vms#649]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

123

### bndiagnostic was not useful. Could you please tell us why?

The document does not describe much

### Describe your issue as much as you can

When I configured the svn, I found that the entry and/or its revision did not exist in the version library. How can I solve it, thank you

![微信截图_20230131152512](https://user-images.githubusercontent.com/124029182/215693838-9d064db0-b8c2-456c-9dd0-9ffbe5e098b0.png)

**Comment by mdhont** [comment]
Can you update the title and the description? Which application are you using and for which platform? Can you give the steps to reproduce the issue?
