### ISSUE TITLE
[Wordpress] I can't access my site

### ISSUE THREAD

**Issue by ranvirme** [bitnami/vms#65]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

eec1a7a0-ef59-6edd-bc16-d1cfd829027f

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Jun 30 23:36:38.741711 2022] [authz_core:error] [pid 24264:tid
139725922875136] [client **ip_address**:48748] AH01630: client denied by server
configuration: /bin/bash
 [Thu Jun 30 23:38:19.323802 2022] [authz_core:error] [pid 24264:tid
139726375851776] [client **ip_address**:36698] AH01630: client denied by server
Press [Enter] to continue:
configuration: /bin/sh
 [Thu Jun 30 23:38:19.608537 2022] [authz_core:error] [pid 5691:tid
139726686078720] [client **ip_address**:36722] AH01630: client denied by server
configuration: /bin/bash

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
AH00526: Syntax error on line 4 of
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
file '/opt/bitnami/apache/conf/pacetarget.in.crt' does not exist or is empty
```
Please check the configuration.

[Mariadb]

Found recent error messages in the MariaDB error log:
```
Press [Enter] to continue:
2022-07-02 5:48:39 8 [Warning] Aborted connection 8 to db: 'bitnami_wordpress'
user: 'bn_wordpress' host: 'localhost' (Got an error reading communication
packets)

```
Please check the following guide to troubleshoot MariaDB issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 987 375 104 8 507 443 Swap:
634 0 634
Press [Enter] to continue:
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I increased the instance storage but still have same issue

### Describe your issue as much as you can

I am not able to access my WordPress website. I increased the instance storage but still have same issue

**Comment by ranvirme** [comment]
I did not get any reply till now

**Comment by mdhont** [comment]
I recommend upgrading your instance to a machine with more resources:

https://docs.bitnami.com/aws/faq/administration/change-server-type/

**Comment by ranvirme** [comment]
===== Begin of bndiagnostic tool output =====


    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found



[Apache]

The Apache configuration has errors:
```
AH00526: Syntax error on line 4 of
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
file '/opt/bitnami/apache/conf/pacetarget.in.crt' does not exist or is empty
```
Please check the configuration.



The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

12d80596-bc95-2e43-8a01-a3eea82fee96

**Comment by mdhont** [comment]
According to this error message: 

```
AH00526: Syntax error on line 4 of
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
file '/opt/bitnami/apache/conf/pacetarget.in.crt' does not exist or is empty
```
The `/opt/bitnami/apache/conf/pacetarget.in.crt` certificate file does not exist, can you check it?

**Comment by ranvirme** [comment]
I know about this issue and tried to resolve it but I could not. I created a ticket for help but you are replying like this. I tried to generate a certificate many times but still, have the same issue. Can you help me with this or not? If yes, then please guide me

**Comment by ranvirme** [comment]
I can't start my apache and other services

**Comment by ranvirme** [comment]
I found this error when I am trying to start my apache

bitnami@ip-172-31-15-47:~$ sudo /opt/bitnami/ctlscript.sh stop
Stoping services..
bitnami@ip-172-31-15-47:~$ sudo /opt/bitnami/ctlscript.sh start
Starting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.
_____________________________________________________________________________________
Please solve the issue

**Comment by amankr0786** [comment]
Please

> I solved it.

Please provide me solution , I am facing same issue

**Comment by Tee27** [comment]
> I solved it.

How .. Experiencing the issue

**Comment by jotamartos** [comment]
Hi, 

This issue is now closed and won't be reopened. Please create new issues for the team to review them. You can link your new issue with this new one in case you think it's useful for the team to have this info.

Thanks
