### ISSUE TITLE
How do I install codeview 

### ISSUE THREAD

**Issue by huishen97** [bitnami/vms#650]
### Platform

VMware Marketplace

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1

### bndiagnostic was not useful. Could you please tell us why?

The document does not describe much

### Describe your issue as much as you can

How do I install codeview

**Comment by gongomgra** [comment]
Hi @huishen97,

Can you give us more detailed information about what are you trying to achieve?

**Comment by huishen97** [comment]
I have two questions. First, there is no entry and/or its revision in the version library when redmine is connected to svn, as shown in the figure. Second, how to install codeview plug-in for code review if redmine is connected to svn. 

![微信截图_20230131152512](https://user-images.githubusercontent.com/124029182/215915849-fed67624-fc4d-4aab-aa37-cfa2a90b9b2d.png)

**Comment by huishen97** [comment]
> 



> 你好@huishen97,
> 
> 你能给我们更详细的信息吗？你想达到什么目的？



> 你好@huishen97,
> 
> 你能给我们更详细的信息吗？你想达到什么目的？

The method I used was a virtual machine, using redmine deployed by virtualbox. I had two problems. First, after the deployment, redmine connected to svn and there was no entry and/or its revision in the version library, as shown in the figure.  The second question is how to install codeview plugin for code review if redmine is connected to svn. 
![微信截图_20230131152512](https://user-images.githubusercontent.com/124029182/215916752-a8d15542-b0f9-4cc0-a1e9-2fb785e23b0b.png)

**Comment by huishen97** [comment]
svn and redmine are not installed on the same machine

**Comment by gongomgra** [comment]
Hi @huishen97,

Thanks for your message. You can install subversion using the `apt-get` package manager and then configure a subversion repository in Redmine by following the guide linked below

https://docs.bitnami.com/virtual-machine/apps/redmine/configuration/configure-use-svn-repository//
