### ISSUE TITLE
Install Bitnami redmine on Windows , I want the exe file 

### ISSUE THREAD

**Issue by MarshalJoseph** [bitnami/vms#651]
### Describe your issue as much as you can

Install Bitnami redmine on Windows , I want the exe file

**Comment by MarshalJoseph** [comment]
I need to install the Redmine application in  the Windows Server 2019 VM , Please share the link to download the exe file

**Comment by gongomgra** [comment]
Hi @MarshalJoseph,

Thanks for your interest in using Bitnami. We dropped support for our local installers in favor of our containers, cloud images, and virtual-machines assets. We highly recommend you to use them. You can get more information about the decision of focusing on our cloud native solutions in the next link

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

**Comment by Crimzin69** [comment]
Hi Gongomgra,

I do not have a problem with you dropping local installers and going to containers. but then you need to help us migrate from local installed redmine to containers.

My current instal is:

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.5.7-p206 (2019-10-01) [x64-mingw32]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.25.0
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.5.2
  redmine_checklists             3.1.16
  redmine_contacts               4.2.6
  redmine_contacts_helpdesk      4.1.8
  redmine_people                 1.4.2
  redmineup_tags                 2.0.8

How do I migrate??

**Comment by Crimzin69** [comment]
Also please share the docker stack details for us

**Comment by Crimzin69** [comment]
@gongomgra I need to know how to migrate from a windows installed environment to a docker container environment. not just from one server to another.

**Comment by gongomgra** [comment]
Hi @Crimzin69,

You have the required steps in the upgrade guide I shared in my previous message. To move the required files into the docker container you can either use a volume or manually copy them using the `docker cp` command. After that, you can manually import the SQL file into the database from the container's shell and also uncompress the Redmine's files tarball from there.
