### ISSUE TITLE
permissions to keep website secure

### ISSUE THREAD

**Issue by itsmemidhuz123** [bitnami/vms#652]
### Describe your suggestion as much as you can

hi, we recently noted  that some malware has affected on website only used plugins from the plugin directory. I wanted to show these issues and how can i keep this secure by disabling installation of new plugins and more

please help

**Comment by mdhont** [comment]
Can you give more information? Which application are you using?

**Comment by itsmemidhuz123** [comment]
am using bitnami for wordpress hosted on aws. I used the malcare plugin for wordpress, the said that the wp contains malware but we haven't installed any plugin from outside. I interested in using the security by jetpack, so does this good to secure site

**Comment by itsmemidhuz123** [comment]
https://hellobugs.in/wp-content/uploads/2023/02/S0bdfd4f33dd0460c81b5caf4329ab31dd-600x600.jpg

can you please check because the image is uploaded for a product but not visible to public, how to resolve this sir.

**Comment by mdhont** [comment]
The following guide shows how you can set the correct permissions for WordPress:

https://docs.bitnami.com/general/apps/wordpress-production-ready/administration/understand-file-permissions/

**Comment by itsmemidhuz123** [comment]
still the issue persist sir. we could not able to see the product images but it already on gallery

**Comment by itsmemidhuz123** [comment]
issue resolved sir but please let me know to secure wordpress

**Comment by mdhont** [comment]
The following guides shows how to secure WordPress:

https://docs.bitnami.com/aws-templates/apps/wordpress/troubleshooting/enforce-security/
