### ISSUE TITLE
[Wordpress] - Sorry, you are not allowed to access this page while accessing wp-admin page

### ISSUE THREAD

**Issue by biswajitkar01** [bitnami/vms#653]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

126de276-18d2-223b-a1a7-9d183ca6697e

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Nginx: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Php: No issues found
 

 
[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2023/01/31 18:27:11 [crit] 728#728: *555430 connect() to 
unix:/opt/bitnami/php/var/run/www.sock failed (2: No such file or directory) 
while connecting to upstream, client: **ip_address**, server: _, request: "GET 
/product/keep-it-raw-hoodie-red/ HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"admin.zagzuggles.com"
Press [Enter] to continue:
 2023/01/31 18:27:12 [crit] 728#728: *555426 connect() to 
unix:/opt/bitnami/php/var/run/www.sock failed (2: No such file or directory) 
while connecting to upstream, client: **ip_address**, server: _, request: "POST 
/xmlrpc.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "zagzuggles.com"
 2023/01/31 18:27:16 [crit] 728#728: *555426 connect() to 
unix:/opt/bitnami/php/var/run/www.sock failed (2: No such file or directory) 
while connecting to upstream, client: **ip_address**, server: _, request: "POST 
/xmlrpc.php HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "zagzuggles.com"

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-01-31 18:27:10 407820 [Warning] Aborted connection 407820 to db: 
'bitnami_wordpress' user: 'bn_wordpress' host: 'localhost' (Got an error reading 
Press [Enter] to continue:
communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 987 464 117 66 405 307 Swap: 
634 24 610
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Not able to fix the issue using this information. 

### Describe your issue as much as you can

Hey, 
While updating the WordPress version from 6.0.3 to 6.1.1, the error came while accessing the wp-admin page after entering the credentials. 
www.zagzuggles.com

I have tried all things that I could think of. 
1. Deactivating the plugins and reactivating 
2. deactivating the theme and reactivating
3. checking PHPMyAdmin
4. Checking logs, wp-config files etc.. 

But I am not able to figure out what happened. Request you to please help. I am stuck.

**Comment by mdhont** [comment]
The mariadb log shows this error:

```
2023-01-31 18:27:10 407820 [Warning] Aborted connection 407820 to db: 
'bitnami_wordpress' user: 'bn_wordpress' host: 'localhost' (Got an error reading 
Press [Enter] to continue:
communication packets)
```

So it seems something is wrong with the database.

Which steps did you follow to update Wordpress? Did you follow the steps in this guide?

https://docs.bitnami.com/aws-templates/apps/wordpress/administration/upgrade/

**Comment by biswajitkar01** [comment]
Hey @mdhont, I have followed exactly the steps like this. 
Still, the error happened.

Now that you have mentioned there is an issue in MariaDB.. how can I fix it? 
Please guide me.

**Comment by biswajitkar01** [comment]
Hey @mdhont please help me. I would be really grateful.

**Comment by mdhont** [comment]
According to the bndiagnostic tool your instance is running low on resources.

```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
```
 I recommend upgrading the machine to a more powerful one:

https://docs.bitnami.com/aws/faq/administration/change-server-type/

**Comment by biswajitkar01** [comment]
@mdhont  - Thanks for your input. I changed my AWS instance type to a larger type. And it worked. 

However, I see that there are many log files with 70MB file sizes being created. Is there any way to control them. 
May be like only keeping log files of the past 24 hours.

**Comment by mdhont** [comment]
It's possible to disable binary logging following this guide:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/disable-binary-logging-mysql/

**Comment by biswajitkar01** [comment]
@mdhont thank you
