### ISSUE TITLE
[AWS Bitnami HA WordPress] How to set file upload max size in AWS autoscaling HA environment

### ISSUE THREAD

**Issue by alidgett** [bitnami/vms#654]
### Describe your issue as much as you can

Hello,

We have a WordPress site built using the AWS Bitnami HA WordPress reference architecture: 
https://aws.amazon.com/solutions/partners/wordpress-high-availability-bitnami/

The site is running in HA and is configured for auto scaling. We need to be able to update the following configuration attributes (as showing in Site Health Info:

- Max size of an uploaded file
- PHP time limit

Using the /bitnami/wordpress/wp-config.php file on the EFS we have been able to update the 'PHP time limit' attribute and verify that it is persisted and applied to each new web server launched by an autoscaling event.

However, we are not able to update/modify the 'Max size of an uploaded file' attribute. 
Is this done in the server configuration files located in the path /opt/bitnami/wordpress/...? 
If this is the case how are these changes persisted and shared with other web servers that are created via an autoscaling event, or is there a way to use an .htaccess file on the EFS shared path?

Any guidance and info would be appreciated.

Thanks
Andrew

**Comment by gongomgra** [comment]
Hi @alidgett,

Thanks for your message. PHP config changes are not shared/persisted between the different machines in the HA solution. You will have to customize our image with your PHP changes and then use it in the WordPress HA product by following the steps described in the guide linked below

https://docs.bitnami.com/aws-templates/apps/wordpress-production-ready/configuration/use-custom-ami/

**Comment by alidgett** [comment]
Thank you Gonzalo, this was very helpful, the UserData SKIP_FIRST_BOOT=1 enabled us to create our custom image and persist the php.ini settings.

**Comment by gongomgra** [comment]
Hi @alidgett,

Thanks for your message. I'm glad it helped to answer your question! I'm closing this ticket as solved.
