### ISSUE TITLE
[akeneo] Missing Elements in the applications (No locales configuration possible, not import access rights configurable)

### ISSUE THREAD

**Issue by Ogami-Itto** [bitnami/vms#655]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

968dadb9-5650-c602-54b8-a8e532223d36

### bndiagnostic output

 ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ✓ Mysql: No issues found
    ✓ Php: No issues found

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3430 2492 116 75 821 632 Swap:
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

Press [Enter] to continue:
You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Feb 01 21:09:55.700463 2023] [authz_core:error] [pid 17791:tid
140494369584896] [client **ip_address**:37394] AH01630: client denied by server
configuration: /opt/bitnami/apache/cgi-bin
 [Thu Feb 02 04:29:27.045033 2023] [authz_core:error] [pid 17791:tid
140493966907136] [client **ip_address**:47008] AH01630: client denied by server
configuration: /opt/bitnami/apache/cgi-bin
 [Thu Feb 02 10:03:44.625876 2023] [core:error] [pid 36678:tid 140494193510144]
[client **ip_address**:57062] AH10244: invalid URI path
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)

### bndiagnostic was not useful. Could you please tell us why?

I believe there is an issue with the package installed from Azure as some menu items cannot be found

### Describe your issue as much as you can

The documentation from Akeneo shows that the when setting an import profile,  we should be able to set import profile permissions rights ( see documentation : https://help.akeneo.com/pim/v4/articles/access-rights-on-imports-exports.html#set-rights-to-an-import-profile

But when checking the fresh install on Azure, I do not see the menu to set the permissions rights tab 

See link to screenshot

![akeneo_accessrights_ 2023-02-02 140432](https://user-images.githubusercontent.com/11878426/216336915-24506671-8836-4a1c-ac49-8d4417be66e7.png)

Similarly, when checking the documentation on Locales, the https://help.akeneo.com/pim/v4/articles/access-rights-on-products.html, permissions can be set on locales.
On the fresh install on Azure, I do not see the menu in locales to set the permissions rights.

See the screenshot 

![akeneo_accessrights_locales_ 2023-02-02 140432](https://user-images.githubusercontent.com/11878426/216336705-4b457523-4f71-4e14-b2c2-9bea2025da8c.png)


Links to screennshots here also https://airtable.com/shr2iEkUhWf397r84

**Comment by mdhont** [comment]
I'm afraid those settings are only available in the enterprise addition.

<img width="486" alt="Screenshot 2023-02-03 at 16 42 44" src="https://user-images.githubusercontent.com/18216803/216645290-3e60f8c7-45ea-454c-81ba-5ffb402482a3.png">

**Comment by Ogami-Itto** [comment]
OK so I am back to square one with my investigation.
I have this issue where everytime i import an attribute by file (csv or excel)  the result shown is ": An identifier attribute already exists.: EAN/UPC

My assumption was that it was missing the rights to set permissions. But as it's a premium feature, something else is causing it.
Has this error occured before? 
Do file imports need to be made from the server directly? 

**See the file used**

[Import_Attribute_Export_XLSX_2023-01-28_19-40-29_1.xlsx](https://github.com/bitnami/vms/files/10580927/Import_Attribute_Export_XLSX_2023-01-28_19-40-29_1.xlsx)



**See a recording of the error**

https://user-images.githubusercontent.com/11878426/216660231-e8c38e8a-ccc9-4e3d-bde1-8f57e5e7d14a.mp4

**Comment by mdhont** [comment]
It should be possible to import files using the GUI. Regarding the "n identifier attribute already exists." error, it seems related to the application itself. I recommend asking in a dedicated Akeneo forum.

**Comment by Ogami-Itto** [comment]
Thanks I will check with an akeneo forum!
