### ISSUE TITLE
Wordpress - Error initating the server - bitnami.service: Control process exited, code=exited, status=1/FAILURE

### ISSUE THREAD

**Issue by uncavayo** [bitnami/vms#656]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

83585fe1-8306-7361-db88-4b2b7c68665a

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
Binary file (standard input) matches

```
Please check the following guide to troubleshoot server issues:
 
Press [Enter] to continue:
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-02-02 12:49:43 671 [Warning] Aborted connection 671 to db: 
'bitnami_wordpress' user: 'bn_wordpress' host: 'localhost' (Got an error writing 
communication packets)

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
Press [Enter] to continue:
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

The error logs doesnt show anything related with this problem

### Describe your issue as much as you can

Ther server was funtional but but had memory usage problems. I've foce restartet the server and then when i try to start it this error appears in systemctl status bitnami.service : **bitnami.service: Control process exited, code=exited, status=1/FAILURE**

**Comment by uncavayo** [comment]
I've startet all the services with:
_sudo /opt/bitnami/ctlscript.sh start php-fpm
sudo /opt/bitnami/ctlscript.sh start apache
sudo /opt/bitnami/ctlscript.sh start mariadb_

And then the web is working but if i do 
_sudo /opt/bitnami/ctlscript.sh status_
i get

_Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)_

**Comment by gongomgra** [comment]
Hi @uncavayo,

Thanks for using Bitnami. Can you check the content of the `/var/log/daemon.log` file to see if there is any error message related to gonit initialization process?

**Comment by uncavayo** [comment]
Hello,

I've checked this log, and there is a lot of entries related to the gonit initialization but i dont see any concrete error that i can diagnose with my knowledge.

There is any way to send or show you this log in private?

Thank you.

**Comment by gongomgra** [comment]
Hi @uncavayo,

Unfortunately, there's no way to share that information privately. If you can anonymize it (replacing the passwords with `REDACTED` or `a-random-password`, and other information alike), please paste the content here.

Can you also share the whole output of running the command below?

```
sudo systemctl status bitnami.service
```

**Comment by uncavayo** [comment]
Thats the response when i do

sudo systemctl status bitnami.service

bitnami.service - LSB: bitnami init script
   Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2023-02-10 15:28:15 UTC; 5 days ago
  Process: 532 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by gongomgra** [comment]
Hi @uncavayo,

I'm afraid we can't get any information out of that error messages. Can you try launching a new image to see if you reproduce the issue there?
