### ISSUE TITLE
[Bitnami LMS Powered By Moodle(TM) LMS] -  Documentation Error

### ISSUE THREAD

**Issue by amandaactionpact** [bitnami/vms#657]
### Describe your suggestion as much as you can

Hi,
I'm working through **Migrate Data From One Bitnami LMS Powered By Moodle(TM) LMS Instance To Another** instructions and believe I found an error.

Link: https://docs.bitnami.com/general/how-to/migrate-moodle/

Step 2: Prepare A New Moodle Instance
- Stop Apache.

Step 4: Complete Migration And Restart Services
- **Import the database backup of the old installation.**
- **Start Apache.**

The issue I have is inorder to import the database I need to connect to http://127.0.0.1:8888/phpmyadmin/. I can't do this unless Apache is running. So, should **Start Apache** come before **Import the database backup of the old installation** in Step 4?

Thanks!

**Comment by mdhont** [comment]
Yes, it should be possible to leave Apache running in step 2.
