### ISSUE TITLE
[WordPress] Forcing http to https redirect does not work

### ISSUE THREAD

**Issue by renedescartes** [bitnami/vms#658]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3a263d36-0492-972c-69f3-58b7535dc4f5

### bndiagnostic was not useful. Could you please tell us why?

HTTPS to HTTP redirect not working

### Describe your issue as much as you can

I am following https://docs.bitnami.com/aws/apps/wordpress/administration/force-https-apache/ to force https to http. I am using approach B and I have added the following lines to /opt/bitnami/apache2/conf/bitnami/bitnami.conf

```
<VirtualHost _default_:80>
    DocumentRoot "/opt/bitnami/apache2/htdocs"
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
    RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
    ...
  </VirtualHost>
```

The port 443 is enabled because when I access my website through https it works however the redirect from http to https does not work. Can someone tell me how I should go about debugging this? All stackoverflow links have just given the same instructions.

**Comment by jotamartos** [comment]
I see 3 issues in your configuration: 

- The first one is that you are including the Rewrite lines inside the "Directory" block of the 80 port and it should be out of that block, just after the DocumentRoot line. 
- Second, I'd follow this guide to always redirect to your domain https://docs.bitnami.com/aws/apps/wordpress/administration/use-single-domain/
- Third, remember to configure WordPress to work with the same domain (remember to use the same domain (www or non-www) in Apache and WordPress): https://docs.bitnami.com/aws/apps/wordpress/administration/configure-domain/

**Comment by renedescartes** [comment]
Thank you the first point was a big oversight on my part!
