### ISSUE TITLE
[Wordpress Multisite] Http to Https Redirection not Working

### ISSUE THREAD

**Issue by newbeecoderak** [bitnami/vms#66]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

728843fe-61ba-5198-eaae-384a3c4c454f

### bndiagnostic output

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat Jul 02 07:59:48.182708 2022] [proxy_fcgi:error] [pid 16836:tid 
140643326224128] [client **ip_address**:55138] AH01071: Got error 
'tem-direct.php on line 173PHP message: PHP Warning: chmod(): Operation not 
permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
Press [Enter] to continue:
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation [Sat Jul 02 07:59:48.195634 
2022] [proxy_fcgi:error] [pid 16836:tid 140643326224128] [client 
**ip_address**:55138] AH01071: Got error 'ct.php on line 173PHP message: PHP 
Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not perm [Sat Jul 02 
07:59:48.352771 2022] [proxy_fcgi:error] [pid 16836:tid 140643326224128] [client 
**ip_address**:55138] AH01071: Got error 'n line 173PHP message: PHP Warning: 
chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in 
/opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 
173PHP message: PHP Warning: chmod(): Operation not permitted in
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

### bndiagnostic was not useful. Could you please tell us why?

Still Does not Work

### Describe your issue as much as you can

HTTP to HTTPS redirection not working after following all possible articles and steps outlined in communities and Bitnami pages. HTTP page still opens up on HTTP and redirection does not work. I have only updated the bitnami.conf file and not the remaining ones. I tried updating all files as outlined and it still did not work.

**Comment by mdhont** [comment]
Could you try to use the domain name for the redirect rule:

```
    RewriteCond %{HTTPS} !=on
    RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
    RewriteRule ^/(.*) https://example.com/$1 [R,L]
```

**Comment by mdhont** [comment]
Did you follow all the steps in this guide to configure the domain for WordPress Multisite?

https://docs.bitnami.com/ibm/apps/wordpress-multisite/configuration/configure-wordpress-multisite/

**Comment by vigneshnin** [comment]
I too have the same issue and I've tried everything from the documentations and from this issue report.

There is not change. Whatever I do, the http to https redirect does not work.

**Comment by vigneshnin** [comment]
@mdhont Thank you for your response.

I have already set up the HTTPS. It is working correctly, but my site is available via HTTP and I set redirect rules to redirect HTTP requests to HTTPS and it does not work wherever I put the configuration. My site will always load HTTP and HTTPS.
For the time being I switched from using Wordpress multisite to single site wordpress since I could not waste time on this, but we have more migrations in pipeline and it would be nice if I can get the HTTP HTTPS redirection to work correctly on Bitnami Wordpress multisite in AWS Lightsail.

**Comment by jotamartos** [comment]
Hi @vigneshnin,

If you want to force https in Apache, please check this guide.

https://docs.bitnami.com/aws/apps/wordpress-multisite/administration/force-https-apache/

If you still run into issues, please create a separate issue in this repository.
