### ISSUE TITLE
[WordPress With NGINX And SSL Packaged By Bitnami] <str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated [file]>

### ISSUE THREAD

**Issue by vgnavada** [bitnami/vms#660]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

046a57e7-8214-8d9b-1321-2b1ba2ba9e72

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ? Nginx: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1953 880 227 107 845 790 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2023/02/05 16:38:16 [error] 682#682: *8854 access forbidden by rule, client: 
**ip_address**, server: _, request: "GET /development/.env HTTP/1.1", host: 
"ec2-13-232-204-255.ap-south-1.compute.amazonaws.com"
 2023/02/05 16:38:17 [error] 682#682: *8855 access forbidden by rule, client: 
**ip_address**, server: _, request: "GET /staging/.env HTTP/1.1", host: 
"ec2-13-232-204-255.ap-south-1.compute.amazonaws.com"
 2023/02/05 16:38:17 [error] 682#682: *8856 access forbidden by rule, client: 
**ip_address**, server: _, request: "GET /platform/.env HTTP/1.1", host: 
"ec2-13-232-204-255.ap-south-1.compute.amazonaws.com"

```
Please check the following guide to troubleshoot server issues:
 
Press [Enter] to continue:
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

[Wordpress]

Found recent WordPress plugin related error messages in the Nginx error log.
```
2023/02/05 08:02:04 [error] 683#683: *7219 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET /wp-content/plugins/adminer/adminer.php 
HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"13.232.204.255"

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

No answer for the issue i'm facing

### Describe your issue as much as you can

Hello,
We recently started getting this warning in the DASHBOARD as well as the FRONT END SITE:

`Array ( [type] => 8192 [message] => str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated [file] => /opt/bitnami/wordpress/wp-includes/functions.php [line] => 2162 )`

![image](https://user-images.githubusercontent.com/113204610/216832483-eadc4bd7-3c4b-4da7-aa10-0c72793193a8.png)

Not sure what is causing this issue! Is it form a theme or a plugin?
Or is it from the WP core files?

Since the warning is displayed to the normal viewer, It has become a big headache.

Could you please let us know how to fix this?
Awaiting your response...

**Comment by jotamartos** [comment]
That's a WordPress-related issue and it's out of the scope of this support forum. Please ask the WordPress support team about it or review the WordPress' forums.

https://wordpress.org/documentation/

Thanks
