### ISSUE TITLE
[LAMP] How to find version numbers of installed software PHP, Apache, MySQL

### ISSUE THREAD

**Issue by elisalee2000** [bitnami/vms#661]
### Describe your issue as much as you can

How do I find which version of Php, Apache and MySQL are installed on Bitnami LAMP 8.1.12?

**Comment by jotamartos** [comment]
If you are using a cloud image, you can find a "Changelog" button in the bitnami.com site. You can find that button for the AWS  image here 

https://bitnami.com/stack/lamp/cloud/aws

**Comment by elisalee2000** [comment]
Thank you @jotamartos
