### ISSUE TITLE
[Redmine] Access from outside of local network

### ISSUE THREAD

**Issue by MarshalJoseph** [bitnami/vms#663]
### Describe your issue as much as you can

i have installed bitnami redmine on a local computer and started the website, I can log into the server from the local network

I have added the local IP to the firewall to route to the internet and can access the site https://prosepms.prosetechnologies.com/
but after entering  the username and password the site does not respond.

Please help me to check

**Comment by gongomgra** [comment]
Hi @MarshalJoseph,

Thanks for using Bitnami. The Redmine application seems to be accessible from the Internet at the URL you provided. If you are having issues with the application itself, please check its log files for any related error.

**Comment by MarshalJoseph** [comment]
Hi,
Where do I find the logs,

**Comment by gongomgra** [comment]
Hi @MarshalJoseph,

You can check the Apache logs under the `INSTALLDIR/apache/logs` folder, and Redmine's in the `INSTALLDIR/apps/redmine/htdocs/logs`.

**Comment by MarshalJoseph** [comment]
Hi,
Can you please tell me how to add the ssl certificate in bitnami folder ,
thnks

**Comment by gongomgra** [comment]
Hi @MarshalJoseph,

We don't have any specific guide for local installers as we no longer support them, but you can follow most of the steps in the guide below just replacing the `/opt/bitnami` with your `INSTALLDIR` location. Hope it helps!

https://docs.bitnami.com/virtual-machine/infrastructure/lamp/administration/enable-https-ssl-apache/
