### ISSUE TITLE
Bitnami AWS Lightsail WordPress - Services on server keep freezing

### ISSUE THREAD

**Issue by alex-kodr** [bitnami/vms#664]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5f74caa6-eb25-b564-42c5-40112b31e6ca

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ✓ Connectivity: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-02-07 12:59:03 97 [ERROR] mysqld: Table 
'./mn4kvpay2oynfpg9k/wp_sync_core_woocommerce_sessions' is marked as crashed and 
should be repaired

```
Press [Enter] to continue:
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Feb 07 12:04:48.254468 2023] [proxy_fcgi:error] [pid 62900:tid 
139783628105472] (70007)The timeout specified has expired: [client 
**ip_address**:48655] AH01075: Error dispatching request to : (polling)
 [Tue Feb 07 12:14:23.647047 2023] [proxy_fcgi:error] [pid 61573:tid 
139783670068992] (70007)The timeout specified has expired: [client 
**ip_address**:40256] AH01075: Error dispatching request to : (polling)
 [Tue Feb 07 12:14:23.647036 2023] [proxy_fcgi:error] [pid 62667:tid 
139783628105472] (70007)The timeout specified has expired: [client 
**ip_address**:31528] AH01075: Error dispatching request to : (polling)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
Press [Enter] to continue:
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I've checked the database and run table repairs / optimize /  check. All come back ok.

### Describe your issue as much as you can

I've been moving our development WordPress site over to a new instance, so we can use the latest version of PHP. The site ran perfectly beforehand. We've moved it all and re-configured the new instance. It all works fine. Excerpt may 2 / 3 times each day services (apache / SQL / PHP-fpm) just freeze. So the instance needs rebooting. 

We can't figure out exactly why. The server is blocked off from general web traffic. So there are only 2 people on the site at any one time. The server seems to freeze in the middle of the night when no one is on the server. I've checked both snapshot backups and CRONs and they are running at different times. When I look at the metric graph within our AWS account there are little spikes in CPU usage when the freeze is happening. But they are bearly into the burstable zone and certainly should not be knocking the server offline, especially with it being the top-spec 32 GB RAM, 8 vCPUs, 640 GB SSD instance.

<img width="740" alt="aws-metric-graph" src="https://user-images.githubusercontent.com/1478808/217258525-6edddf9a-801e-46e6-9c34-8b81de8c7ae2.png">

Anyone got any idea why this might be happening? The previous instance that this site was on ran flawlessly. 

Thanks

**Comment by mdhont** [comment]
It could be due to WordPress plugins like Woocommerce, or others, that can be resource heavy. I recommend disabling the plugins and then enable them one by one to see if it makes any difference. I also recommend asking in a dedicated WordPress forum.

**Comment by Imthiyasvm** [comment]
Mostly because of bot attack to your domain IP,
If you install wordfence plugin and check the the live traffic you may can confirm it from where its coming.
And for blocking IP Attack you need to redirect instance IP to Domain
