### ISSUE TITLE
[ghost] upgrade not possible

### ISSUE THREAD

**Issue by mctogger** [bitnami/vms#667]
### Describe your issue as much as you can

Hi,

the documentation concerning the AWS image seems to be outdated. According to the manual I can performe an upgrade by switching into the ghost directory and running _sudo su ghost ghost update_

This will return the following:
`sh: 0: cannot open ghost: No such file`

Just tried it again with a clean install - same result. Also tried to run the update command under the bitnami user, even with a new user. I'm always running into the "root" issue:
> https://ghost.org/docs/faq/root-user-fix/#error
Unfortunately, this doesn't apply to AWS.

I took ownership of /opt/bitnami/ghost with a new user, after that I was able to run the update command. But I'd prefer a built-in / official solution without the need for a new user. Still getting some dodgy error messages. (can't update ghost cli i.e.)

aloha.

**Comment by mctogger** [comment]
... and there a still some more issues with https with the AWS image.

After configuring the https protocol for ghost images are not being displayed. Adding:

```
<VirtualHost *:443>
RequestHeader set X-Forwarded-Proto "https"
```

to /opt/bitnami/apps/apache2/conf/vhost/ghost-https-vhost.conf fixed it for me.

**Comment by mctogger** [comment]
... and there a still some more issues with https with the AWS image.

After configuring the https protocol for ghost images are not being displayed. Adding:

```
<VirtualHost *:443>
RequestHeader set X-Forwarded-Proto "https"
```

to /opt/bitnami/apps/apache2/conf/vhost/ghost-https-vhost.conf fixed it for me.

**Comment by gongomgra** [comment]
Hi @mctogger,

Thanks for using Bitnami and for reporting this issue. I was able to reproduce it. However, I was able to properly run the `ghost update` command using a slightly different command than the one in our documentation.

```
sudo su ghost -c "ghost update"
```

Here is the output of running this

```
$ sudo su ghost -c "ghost update"

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org

✔ Checking system Node.js version - found v16.19.0
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✔ Checking for available migrations
✔ Checking for latest Ghost version
All up to date!
```

We will open an internal task to update our documentation.

**Comment by gongomgra** [comment]
Hi @mctogger,

We updated our documentation site to reflect the new command to update Ghost.

https://docs.bitnami.com/aws/apps/ghost/administration/upgrade/

**Comment by mctogger** [comment]
thank you! much appreciated

**Comment by gongomgra** [comment]
Hi @mctogger,

Thanks for your message. We are glad it worked for you. I'm closing the ticket as solved.

**Comment by gongomgra** [comment]
HI @iliveforme,

Thanks for using Bitnami. Can you tell us from which version of Ghost you are trying to upgrade? Unfortunately, the version of Node.js can't be upgraded on your instance. You will have to launch a new server with the updated version of Ghost and migrate your app data from the old server into the new one.

We recommend you to check the official Ghost documentation on how to migrate the data from one instance to another

https://ghost.org/docs/migration/ghost/

Hope it helps!

**Comment by Brzam** [comment]
Hi @gongomgra,

Jumping onto this as experienced the same issue today. Was using a fresh instance of the Lightsail Blueprint (which is as of writing is 5.67.0-2). I can see in the bitnami [ghost changelog](https://bitnami.com/stack/ghost/amidebian-x64-hvm-ebs-nami/changelog.txt), that recent releases have the updated version of Node, but this has not yet filtered through to the Lightsail Blueprints.

As these releases are very recent do you know how long this new version would take to filter through to the Lightsail Blueprints, as the inclusion of node v18.18.2 would hopefully allow for future ghost updates to be done without a re-instance, avoid this issue for the foreseeable future.

Thanks,
Sam

**Comment by gongomgra** [comment]
Hi @Brzam,

Thanks for your message. Unfortunately, we have no control on the Lightsail internal publish process and we can't provide you with any estimation on this. We send both images at the same time to AWS, but it is true that the Lightsail team usually takes longer to publish updated images. You will need to use an EC2 instance instead of Lightsail to have access to the latest Ghost image including the updated Node.js version.
