### ISSUE TITLE
[Redmine] Can't figure out shared folders in VM

### ISSUE THREAD

**Issue by sgjohnson1981** [bitnami/vms#668]
### Describe your issue as much as you can

I'm trying to upload some plugins and I figured a shared folder was the best way. I've used shared folders in other vms and it requires a line in the /etc/group file, but I'm not sure what group id is required. In the only other vm I have it has a 998 group id for vboxsf, but that number is already taken by systemd-coredump on the redmine vm. Does the number make any difference? Do I just use one not taken?

Also, please consider adding this line to group file in the ova file. Thank you.

**Comment by sgjohnson1981** [comment]
OK. I apparently forgot to use groupadd. The group is added but I still don't see the folder. It's set to auto-mount, but I see nothing under the /media folder.

**Comment by sgjohnson1981** [comment]
FIxed it. Didn't realize Guest Additions was required. Been a while since I set up my other vm. Apparently I completely forgot how to do it.

**Comment by jotamartos** [comment]
I'm glad to hear that you manage to solve the issue. 

Enjoy :)
