### ISSUE TITLE
[<Redmine>] <how to set up https in native installer windows 2019 server >

### ISSUE THREAD

**Issue by mwdqaqc** [bitnami/vms#669]
### Describe your issue as much as you can

I tried to modify bitnami.config 

<VirtualHost _default_:8080>
  DocumentRoot "C:/Bitnami/redmine-5.0.3-0/apache2/htdocs"
  
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
    RewriteRule ^/(.*) https://AZCPRDMN002/redmine/$1 [R,L]
	
  <Directory "C:/Bitnami/redmine-5.0.3-0/apache2/htdocs">

Restart Apache. https doesn't work.

Also try to modify 

![image](https://user-images.githubusercontent.com/74789498/217968069-fae17e27-b078-44b2-b87a-b15439c24eef.png)

Did I do something wrong?
Please advise!

Lei

**Comment by mwdqaqc** [comment]
https://docs.bitnami.com/aws/apps/redmine/administration/force-https-apache/

I tried to follow the above URL. 
How many files do I need to modify to make https work?

It is windows native Redmine installer.

**Comment by mdhont** [comment]
Which error is showing? Please note that Bitnami installers use a self signed certificate, which allows you to access the application through HTTPS but the browser will still show a warning that the certificate is not valid.

**Comment by mwdqaqc** [comment]
![image](https://user-images.githubusercontent.com/74789498/218547766-1b4e2238-f04e-4cff-8657-2a922bace7f4.png)

**Comment by mwdqaqc** [comment]
Modified: bitnami.config with 
====================================================
<VirtualHost _default_:80>
  DocumentRoot "C:/Bitnami/redmine-5.0.3-0/apache2/htdocs"
  # addeded by Lei in 2/13/2023
    **_RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
    RewriteRule ^/(.*) https://AZCPRDMN002/redmine/$1 [R,L]_**
	
  <Directory "C:/Bitnami/redmine-5.0.3-0/apache2/htdocs">
==============================================================

Modified httpd-vhosts.conf file:

==============================================================
<VirtualHost *:80>
    ServerName redmine.example.com
    ServerAlias www.redmine.example.com
    DocumentRoot "C:\Bitnami\redmine-5.0.3-0/apps/redmine/htdocs/public"
    <Directory "C:\Bitnami\redmine-5.0.3-0/apps/redmine/htdocs/public">
        Options -MultiViews
        allow from all
    </Directory>

    RewriteEngine On
	# added by Lei in 02/13/2023 
    # RewriteEngine On
     RewriteCond %{HTTPS} !=on
     RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
     RewriteRule ^/(.*) https://AZCPRDMN002/redmine/$1 [R,L]
	
    RewriteRule ^/(.*)$ balancer://redminecluster%{REQUEST_URI} [P,QSA,L]
    <Proxy balancer://redminecluster>
        BalancerMember http://127.0.0.1:3001
        BalancerMember http://127.0.0.1:3002
    </Proxy>

**Comment by mwdqaqc** [comment]
Modify httpd-vhosts.conf

<VirtualHost *:80>
    ServerName redmine.example.com
    ServerAlias www.redmine.example.com
    DocumentRoot "C:\Bitnami\redmine-5.0.3-0/apps/redmine/htdocs/public"
    <Directory "C:\Bitnami\redmine-5.0.3-0/apps/redmine/htdocs/public">
        Options -MultiViews
        allow from all
    </Directory>

     RewriteEngine On
     RewriteCond %{HTTPS} !=on
     RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
     RewriteRule ^/(.*) https://AZCPRDMN002/redmine/$1 [R,L]

**Comment by mwdqaqc** [comment]
I can't find bitnami-ssl.conf file under my window's native installer.

How many files need to be modified.
Did I modify it right?
Also, I change the protocol under admin section to https.

**Comment by mwdqaqc** [comment]
Since it doesn't work, so I modified all the files back without 4 lines.
If I only keep Protocol to https under admin settings.

I can use https://azcprdmn002/redmine/  
instead of http://azcprdmn002/redmine/ 
for login page.

It was redirected from https to http URL in Chrome.

**Comment by mdhont** [comment]
For the Redmine installer you can add the modifications directly to the bitnami.conf file.
