### ISSUE TITLE
Bitnami OVA Aborts on M2 Mac Mini Using Virtualbox Developer preview for macOS / Arm64 (M1/M2) hosts

### ISSUE THREAD

**Issue by Kyosho** [bitnami/vms#671]
### Platform

OSX VM

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Cannot Boot

### bndiagnostic was not useful. Could you please tell us why?

Cannot Boot

### Describe your issue as much as you can

Using an M1 Mac Mini 2020, I found the new VirtualBox-7.0.6_BETA4-155176-macOSArm64 download at VirtualBox.org. This is the Developer preview for macOS / Arm64 (M1/M2) hosts.

VirtualBox installs fine and opens as usual.

I imported the Bitnami VM OVA for ResourceSpace bitnami-resourcespace-10.0.0-31-r29-linux-vm-debian-11-x86_64-nami.ova

No apparent problem with importing.

When I click Start, the VM starts the Linux boot, gives a little bit of progress: GRUB Booting Debian GNU/LInux and then the boot sequence aborts and VirtualBox displays Aborted for the status of the VM.

Any ideas what might be happening? Do Bitnami VMs work with the Developer version of VirtualBox for M1 and M2 Mac Minis?

Here is the VirtualBox log:
===================
[bitnami-resourcespace-2023-02-09-15-13-28.log](https://github.com/bitnami/vms/files/10708189/bitnami-resourcespace-2023-02-09-15-13-28.log)

Apple Problem Report for VirtualBoxVM:
==============================

[Apple Problem Report for VirtualBoxVM.txt](https://github.com/bitnami/vms/files/10708254/Apple.Problem.Report.for.VirtualBoxVM.txt)

**Comment by jotamartos** [comment]
>Any ideas what might be happening? Do Bitnami VMs work with the Developer version of VirtualBox for M1 and M2 Mac Minis?

We have not tested our solutions on top of the M1/M2 Mac Minis. Please note that the VirtualBox version you are using is a developer preview and the errors may be related to that. You can ask the VirtualBox developers to get more information about the issue.
