### ISSUE TITLE
[Wordpress] Services hang when editing draft posts

### ISSUE THREAD

**Issue by JM-Admin** [bitnami/vms#673]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

08dea163-8b32-bed7-a5cb-8faf4948b4b0

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Feb 10 12:39:48.304905 2023] [proxy_fcgi:error] [pid 1168:tid 
139802888283904] (70007)The timeout specified has expired: [client 
**ip_address**:29340] AH01075: Error dispatching request to : (polling)
 [Fri Feb 10 12:56:22.732126 2023] [authz_core:error] [pid 1177:tid 
140518201730816] [client **ip_address**:46758] AH01630: client denied by server 
Press [Enter] to continue:
configuration: /opt/bitnami/wordpress/.user.ini, referer: 
https://johnmasserini.com/.user.ini
 [Fri Feb 10 14:59:29.565446 2023] [autoindex:error] [pid 1177:tid 
140518025484032] [client **ip_address**:65112] AH01276: Cannot serve directory 
/opt/bitnami/wordpress/wp-admin/css/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive, referer: binance.com

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-02-10 12:29:44 0 [ERROR] InnoDB: (Duplicate key) writing word node to FTS 
auxiliary index table `bitnami_wordpress`.`wp_posts`

```
Please check the following guide to troubleshoot MariaDB issues:
Press [Enter] to continue:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Fri Feb 10 14:51:50.597332 2023] [authz_core:error] [pid 707:tid 
140518226908928] [client **ip_address**:29280] AH01630: client denied by server 
configuration: 
/opt/bitnami/wordpress/wp-content/plugins/akismet/_inc/akismet-frontend.js, 
referer: https://johnmasserini.com/2019/01/28/free-nist-csf-maturity-tool/

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

[Resources]

Your instance has little available RAM memory.
```
Press [Enter] to continue:
 total used free shared buff/cache available Mem: 482 318 10 63 152 87 Swap: 634 
251 382
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

See errors below

### Describe your issue as much as you can

The server generally runs fine on days when no one edits or creates new draft posts. Whenever either of those occur, the system hangs and must be completely restarted. 

I also see the following errors in my log file:

```
Feb 10 12:07:35 ip-172-26-7-119 systemd[1]: Stopping LSB: bitnami init script...
-- Subject: A stop job for unit bitnami.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A stop job for unit bitnami.service has begun execution.
-- 
-- The job identifier is 5123.
Feb 10 12:07:36 ip-172-26-7-119 bitnami[2314]: /etc/init.d/bitnami: 67: /etc/init.d/bitnami: Cannot fork
Feb 10 12:07:36 ip-172-26-7-119 systemd[1]: bitnami.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStop= process belonging to unit bitnami.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 2.
Feb 10 12:07:36 ip-172-26-7-119 systemd[1]: bitnami.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit bitnami.service has entered the 'failed' state with result 'exit-code'.
Feb 10 12:07:36 ip-172-26-7-119 systemd[1]: Stopped LSB: bitnami init script.
-- Subject: A stop job for unit bitnami.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A stop job for unit bitnami.service has finished.
-- 
-- The job identifier is 5123 and the job result is done.
```

**Comment by gongomgra** [comment]
Hi @JM-Admin,

Thanks for using Bitnami. According to the bndiagnostic tool your server is running out of resources, can you use a bigger instance type and see if it solves your issue?

https://docs.bitnami.com/aws/faq/administration/change-server-type/
