### ISSUE TITLE
[Prestashop] Failed attempt to update

### ISSUE THREAD

**Issue by aaldanap** [bitnami/vms#675]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ce61badf-3efb-0c71-a26d-ea5dbc3a1f36

### bndiagnostic output

    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Processes: No issues found
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3697 925 414 14 2357 2481 
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:
You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat Feb 11 01:59:38.192564 2023] [proxy_fcgi:error] [pid 5278:tid 
139710923896576] [client **ip_address**:56380] AH01071: Got error 'PHP message: 
PHP Warning: Invalid argument supplied for foreach() in 
/bitnami/prestashop/classes/shop/Shop.php on line 346', referer: 
http://opticaconfortcenter.com/sendgrid.env
 [Sat Feb 11 01:59:46.145495 2023] [proxy_fcgi:error] [pid 5278:tid 
139710890325760] [client **ip_address**:47420] AH01071: Got error 'PHP message: 
PHP Warning: Invalid argument supplied for foreach() in 
/bitnami/prestashop/classes/shop/Shop.php on line 346', referer: 
http://opticaconfortcenter.com/config.json
 [Sat Feb 11 01:59:54.198985 2023] [proxy_fcgi:error] [pid 5278:tid 
139710856754944] [client **ip_address**:38892] AH01071: Got error 'PHP message: 
PHP Warning: Invalid argument supplied for foreach() in 
/bitnami/prestashop/classes/shop/Shop.php on line 346', referer: 
Press [Enter] to continue:
http://opticaconfortcenter.com/.env
```

### bndiagnostic was not useful. Could you please tell us why?

i already uset and i cant solve the problem

### Describe your issue as much as you can

at first i try to update the prestashop version because all the week the webpage keep crashing, so i used a module called 1 click-upgrade. 

When the process finished, i cant work in the backend so i enabled the depuration mode, later i cant do anything so manually i turn off the depuration mode via ssh

I came back to the back end and try to restore the old version, the module make a backup so i try to restore it

when the process finished, throw a error 500

later i try via ssh to restore an application backup that i have in /opt directory

it didnt work.

here i am

**Comment by jotamartos** [comment]
The errors mentioned in the Apache's error log are related to the application and its plugins. I suggest you ask the Prestashop's developers to know more about the issues you ran into when upgrading the app. 

I also suggest you review the permissions configuration of the Prestashop's folder. Please note that "daemon" should have write permissions. 

```
sudo chown bitnami:daemon -R /opt/bitnami/prestashop /bitnami/prestashop
sudo chmod g+w -R /opt/bitnami/prestashop /bitnami/prestashop
```

> Note: Due to security reasons, please remove write permissions to the configuration file if you do not require them.

**Comment by aaldanap** [comment]
thanks for answering, but i have to shut down the project on gcp
