### ISSUE TITLE
[Odoo] How to get an older version of Odoo? 

### ISSUE THREAD

**Issue by zivce** [bitnami/vms#678]
### Describe your issue as much as you can

Hello, can I get the link to Odoo stack of latest 14 and latest 15 version? Thanks.
Versions I'm interested in:`15.0.20221010-3-r06; 14.0.20211010-5`

**Comment by mdhont** [comment]
You can download them here:

https://downloads.bitnami.com/files/stacks/odoo/14.0.20211010-5/bitnami-odoo-14.0.20211010-5-linux-debian-10-x86_64-nami.ova 

    md5:1be7422c6ed28169f1709829b2a74d4c

https://downloads.bitnami.com/files/stacks/odoo/15.0.20221010-3/bitnami-odoo-15.0.20221010-3-r06-linux-vm-debian-11-x86_64-nami.ova

    md5:ac784374feb1f3b71023534b36a0

**Comment by Estifanos-Neway** [comment]
Can anyone help me get odoo 13

**Comment by mdhont** [comment]
Unfortunately we don't have any versions lower than 14 available for download.

**Comment by sergueikp** [comment]
> You can download them here:
> 
> https://downloads.bitnami.com/files/stacks/odoo/14.0.20211010-5/bitnami-odoo-14.0.20211010-5-linux-debian-10-x86_64-nami.ova
> 
> ```
> md5:1be7422c6ed28169f1709829b2a74d4c
> ```
> 
> https://downloads.bitnami.com/files/stacks/odoo/15.0.20221010-3/bitnami-odoo-15.0.20221010-3-r06-linux-vm-debian-11-x86_64-nami.ova
> 
> ```
> md5:ac784374feb1f3b71023534b36a0
> ```

Download links does not work. 
Please provide working links.

**Comment by jotamartos** [comment]
Hi,

Version 15 is still available in bitnami.com

https://bitnami.com/stack/odoo/virtual-machine

Regarding version 14.x, please use this link

https://downloads.bitnami.com/files/stacks/odoo/14.0.20231110/bitnami-odoo-14.0.20231110-r0-debian-11-amd64.ova

**Comment by sergueikp** [comment]
> Hi,
> 
> Version 15 is still available in bitnami.com
> 
> https://bitnami.com/stack/odoo/virtual-machine
> 
> Regarding version 14.x, please use this link
> 
> https://downloads.bitnami.com/files/stacks/odoo/14.0.20231110/bitnami-odoo-14.0.20231110-r0-debian-11-amd64.ova

Hello, I'm looking for .run installer stuck, not for virtual machine.

**Comment by jotamartos** [comment]
Hi @sergueikp,

We deprecated Odoo's installers back in 2021 and they are no longer available. Please use the VMs I posted above or the docker images available in [Github](https://github.com/bitnami/containers/tree/main/bitnami/odoo) and [Dockerhub](https://hub.docker.com/r/bitnami/odoo)

**Comment by sunilnagmal** [comment]
where can i get odoo 8.0 virtual machine

**Comment by jotamartos** [comment]
Odoo 8.x was deprecated back in 2017 and it's no longer available. You can get the available versions here

https://vcf.broadcom.com/vsc/services/details/odoo?slug=true
