### ISSUE TITLE
[AWS Lightsail LAMP stack] <CORS error>

### ISSUE THREAD

**Issue by fernandolop** [bitnami/vms#680]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

390504d4-0b05-3d15-b015-33bc260c97f5

### bndiagnostic output

? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Apache: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

It's not related with my issue

### Describe your issue as much as you can

Hello. 
I tried to enable CORS in an instance of LightSail with stack LAMP. I tried creating a  .htaccess in the root of my project. Editing the bitnami.conf file and httpd.conf, vhost, etc... The answer when I run a query is always the same: Access to XMLHttpRequest at 'https://lightsail.us-east-1.amazonaws.com/?' from origin 'http://mysite' has been blocked by CORS policy: The response to the previous request does not pass access control: There is no 'Access-Control-Allow-Origin' header in the requested resource. Someone can help me with the final configuration. The application is written in flutter and works without problems in dev.

**Comment by fernandolop** [comment]
This is my bitnami.conf

# Default Virtual Host configuration.

# Let Apache know we're behind a SSL reverse proxy
SetEnvIf X-Forwarded-Proto https HTTPS=on

<VirtualHost _default_:80>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
  Header set Access-Control-Allow-Origin "*"
  Header set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
  Header set Access-Control-Allow-Headers "Authorization, Origin, X-Requested-With, Content-Type, Accept"

  <IfModule mod_rewrite.c>
      RewriteEngine On
      RewriteCond %{REQUEST_METHOD} OPTIONS
      RewriteRule ^(.*)$ $1 [R=200,L]
  </IfModule>

  # Error Documents
  ErrorDocument 503 /503.html
</VirtualHost>

Include "/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf"

**Comment by gongomgra** [comment]
Hi @fernandolop ,

Thanks for using Bitnami. Can you try to place the `Header` directives inside the `Directory` section? After that, restart Apache service for changes to take effect

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

**Comment by fernandolop** [comment]
Thank you for your reply.
I tried the way you mentioned and the answer is the same.
Refused to set unsafe header "Host" 
and 
Access to XMLHttpRequest at 'https://lightsail.us-east-1.amazonaws.com/?' from origin 'http://xxxxxxxx/' has been blocked by CORS policy: The response to the previous request does not pass access control: There is no 'Access-Control-Allow-Origin' header in the requested resource.

**Comment by gongomgra** [comment]
Hi @fernandolop,

Can you run the bndiagnostic tool again and share the new code with us so we can check the updated configuration? Can you also follow the steps in our guide below on how to install a custom application on top of our LAMP solution? The guide is a for PHP application, but it is generic enough to be applicable in the case of almost any other application.

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

If you follow the steps and still have errors accessing your application, please run the bndiagnostic tool after installing the custom application so we can check its configuration as well.
