### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by divisionmd** [bitnami/vms#682]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

76346e8e-2a70-11ea-130d-917770dc8603

### bndiagnostic output

No issues here.

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are not exactly my error i think

### Describe your issue as much as you can

Hello,

- Can you from the bndiagnostic ID see anything strange?
- I loose connection to my Ec2 server / instance randomly.
- But after a restart it works again.
- But not sure if its a network issue or an instance issue with this Bitnami image?
- Thanks for help,
Best regards,
Johan

**Comment by divisionmd** [comment]
super strange - server down again.

![image](https://user-images.githubusercontent.com/21598141/218783733-1db1bed5-d053-4434-99c9-0a7b0f292ca1.png)

not sure if the entire image - or something in Bitnami scripts disconnecting the network?

**Comment by divisionmd** [comment]
Now its up again..

**Comment by divisionmd** [comment]
maybe something with dhcp client - it releases ip and re-tries to get ip...

![image](https://user-images.githubusercontent.com/21598141/218785234-4fdaf6fd-f34c-454f-8b7c-8ea10e7dc070.png)

**Comment by divisionmd** [comment]
![image](https://user-images.githubusercontent.com/21598141/218786609-4d9c4a22-90ca-4323-8c2c-83d1abf51a90.png)

**Comment by mdhont** [comment]
The issue does not seem related to the Bitnami specific configuration. I recommend consulting AWS support.
