### ISSUE TITLE
[WordPress GCP] Website offline, Google maintenance?

### ISSUE THREAD

**Issue by janwillemwilmsen** [bitnami/vms#683]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1

### bndiagnostic output

✓ Resources: No issues found
? WordPress: Found possible issues
? Apache: Found possible issues
✓ Database: No issues found
 
1) The WordPress domain does not seem to be configured. Please check the following guide:
https://docs.bitnami.com/general/apps/wordpress/administration/configure-domain/

2) Found recent error messages in the Apache error log.
```
[Mon Feb 13 15:18:57.893226 2023] [proxy_fcgi:error] [pid 4252:tid 140444591503104] (70007)The timeout specified has expired: [client 62.171.173.28:53772] AH01075: Error dispatching request to : (polling)
```
Please check the following guide to troubleshoot server issues:
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/

### bndiagnostic was not useful. Could you please tell us why?

Not completely, managed to fix one issue found by it(file permissions)

### Describe your issue as much as you can

The websites is offline. Noticed today. Ing GCP there was a recent log about "Instance migrated during Compute Engine maintenance."  ("timestamp": "2023-02-11T04:56:57.510227Z",)

After running the Bitnami Diagnostics tool I saw 3 issues. 

1) Managed to solve one, the file permissions. That issue doesn't show after running diagnostics again.

2) The 'WordPress domain isn't configured' : managed to open and edit the wp-config, and changed and saved WP_SITEURL and WP_HOME (with http:// -and not- https://). After restart of the VM no change. Same error in diagnostics.

_Also increased the size of the VM  (now n1-standard-1)_ 

3) For Apache error log, see below. 

Hope you can analyze and have feedback for me to get the site up and running again!!
Sorry for not specifying the 'bndiagnostic ID' did not see that ID in de tools output.

===error logs===
[Sun Feb 05 23:49:35.692556 2023] [authz_core:error] [pid 10909:tid 140445002745600] [client 189.50.147.249:2926] AH01630: client denied by server configuration: /opt/bitnami/apps/phpmyadmin/htdocs/
[Sun Feb 05 23:49:35.692627 2023] [authz_core:error] [pid 10909:tid 140445002745600] [client 189.50.147.249:2926] AH01630: client denied by server configuration: /opt/bitnami/apps/phpmyadmin/htdocs/
[Sun Feb 05 23:49:35.692681 2023] [authz_core:error] [pid 10909:tid 140445002745600] [client 189.50.147.249:2926] AH01630: client denied by server configuration: /opt/bitnami/apps/phpmyadmin/htdocs/
[Mon Feb 06 00:00:02.038782 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00493: SIGUSR1 received.  Doing graceful restart
[Mon Feb 06 00:00:02.107644 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Mon Feb 06 00:00:02.107667 2023] [core:notice] [pid 27418:tid 140445273599616] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'
[Mon Feb 06 16:24:06.170687 2023] [autoindex:error] [pid 29309:tid 140444759357184] [client 80.76.51.29:62966] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-includes/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Tue Feb 07 00:00:02.343192 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00493: SIGUSR1 received.  Doing graceful restart
[Tue Feb 07 00:00:02.414916 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Tue Feb 07 00:00:02.414936 2023] [core:notice] [pid 27418:tid 140445273599616] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'
[Tue Feb 07 00:14:24.376835 2023] [proxy_fcgi:error] [pid 23783:tid 140444893640448] (70008)Partial results are valid but processing is incomplete: [client 185.224.128.236:61106] AH01075: Error dispatching request to : (reading input brigade)
[Tue Feb 07 19:25:22.756146 2023] [authz_core:error] [pid 23783:tid 140444767749888] [client 157.245.174.148:40324] AH01630: client denied by server configuration: /opt/bitnami/apps/phpmyadmin/htdocs
[Wed Feb 08 00:00:02.919412 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00493: SIGUSR1 received.  Doing graceful restart
[Wed Feb 08 00:00:03.019427 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Feb 08 00:00:03.019456 2023] [core:notice] [pid 27418:tid 140445273599616] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'
[Wed Feb 08 12:06:29.190387 2023] [autoindex:error] [pid 28457:tid 140444650252032] [client 20.26.113.175:60744] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive, referer: binance.com
[Thu Feb 09 00:00:02.868414 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00493: SIGUSR1 received.  Doing graceful restart
[Thu Feb 09 00:00:02.971225 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Thu Feb 09 00:00:02.971255 2023] [core:notice] [pid 27418:tid 140445273599616] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'
[Thu Feb 09 11:31:16.564995 2023] [core:error] [pid 13331:tid 140444675430144] [client 152.89.196.211:59722] AH00126: Invalid URI in request POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1
[Thu Feb 09 14:05:03.499847 2023] [autoindex:error] [pid 13331:tid 140444725786368] [client 194.87.151.73:63953] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-includes/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Thu Feb 09 20:27:08.237558 2023] [autoindex:error] [pid 13116:tid 140444826498816] [client 20.0.38.81:49436] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive, referer: binance.com
[Fri Feb 10 00:00:02.322246 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00493: SIGUSR1 received.  Doing graceful restart
[Fri Feb 10 00:00:02.398481 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Fri Feb 10 00:00:02.398500 2023] [core:notice] [pid 27418:tid 140445273599616] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'
[Fri Feb 10 04:41:03.207633 2023] [core:error] [pid 10175:tid 140444557932288] [client 152.89.196.211:59080] AH00126: Invalid URI in request POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1
[Fri Feb 10 22:52:45.508844 2023] [autoindex:error] [pid 9945:tid 140444818106112] [client 43.153.78.116:63421] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive, referer: binance.com
[Sat Feb 11 00:00:05.077715 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00493: SIGUSR1 received.  Doing graceful restart
[Sat Feb 11 00:00:05.250286 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Sat Feb 11 00:00:05.250311 2023] [core:notice] [pid 27418:tid 140445273599616] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'
[Sat Feb 11 10:47:05.689925 2023] [proxy_fcgi:error] [pid 5301:tid 140444977567488] (-102)Unknown error -102: [client 195.96.137.8:54940] AH01075: Error dispatching request to : (reading input brigade)
[Sat Feb 11 10:47:18.742081 2023] [core:error] [pid 5527:tid 140444927211264] [client 195.96.137.8:59562] AH00126: Invalid URI in request GET default.asp HTTP/1.1
[Sat Feb 11 10:47:18.850624 2023] [core:error] [pid 5300:tid 140444574717696] [client 195.96.137.8:37202] AH00126: Invalid URI in request GET default.asp HTTP/1.1
[Sun Feb 12 00:00:05.559773 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00493: SIGUSR1 received.  Doing graceful restart
[Sun Feb 12 00:00:05.648205 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Sun Feb 12 00:00:05.648225 2023] [core:notice] [pid 27418:tid 140445273599616] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'
[Sun Feb 12 03:45:24.418151 2023] [autoindex:error] [pid 32650:tid 140444717393664] [client 66.175.234.171:53073] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive, referer: binance.com
[Sun Feb 12 04:44:20.273757 2023] [autoindex:error] [pid 32650:tid 140444557932288] [client 20.205.118.216:63927] AH01276: Cannot serve directory /opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive, referer: binance.com
[Mon Feb 13 00:00:02.520403 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00493: SIGUSR1 received.  Doing graceful restart
[Mon Feb 13 00:00:02.620955 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Mon Feb 13 00:00:02.620977 2023] [core:notice] [pid 27418:tid 140445273599616] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'
[Mon Feb 13 03:49:48.521458 2023] [proxy_fcgi:error] [pid 28478:tid 140444960782080] (-102)Unknown error -102: [client 195.96.137.9:55430] AH01075: Error dispatching request to : (reading input brigade)
[Mon Feb 13 03:49:59.939316 2023] [core:error] [pid 28478:tid 140444851676928] [client 195.96.137.9:56102] AH00126: Invalid URI in request GET default.asp HTTP/1.1
[Mon Feb 13 06:25:02.161521 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00493: SIGUSR1 received.  Doing graceful restart
[Mon Feb 13 06:25:02.248541 2023] [mpm_event:notice] [pid 27418:tid 140445273599616] AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Mon Feb 13 06:25:02.248559 2023] [core:notice] [pid 27418:tid 140445273599616] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf -D DISABLE_BANNER'

**Comment by janwillemwilmsen** [comment]
@jotamartos : Managed to run the 'bnsupport-tool', export did not upload to Bitnami servers.
Have ZIP file on Dropbox.

**Comment by jotamartos** [comment]
Hi @janwillemwilmsen,

If binance.com is your domain, I can access it without problems now. If you continue running into issues, let's check the status of the processes and the available memory on your machine. What's the output of these commands?

```
sudo /opt/bitnami/ctlscript.sh status
free -m
df -H
```

If there is any process that is not running, please try to start it with the start command.

**Comment by janwillemwilmsen** [comment]
Hi @jotamartos  
Thanks for your response!
I wish Binance.com was mine. Site in question is panoramawinkel.nl.

-> sudo /opt/bitnami/ctlscript.sh status :
php-fpm already running
apache not running
mysql already running

-> free -m:
              total        used        free      shared  buff/cache   available
Mem:     3704         503        2307          41         892        2877
Swap:        0           0           0

-> df -H  :
Filesystem      Size  Used       Avail       Use%       Mounted on
udev            2.0G     0            2.0G          0%        /dev
tmpfs           389M   41M      348M        11%      /run
/dev/sda1    106G   12G        90G          12%      /
tmpfs           2.0G     0           2.0G          0%        /dev/shm
tmpfs           5.3M    0           5.3M          0%        /run/lock
tmpfs           2.0G     0           2.0G          0%        /sys/fs/cgroup

Am proceding with search for start command, if you have other suggestions, please share!

**Comment by jotamartos** [comment]
I can access your site now. It seems Apache was not running and you successfully started it. Is that correct?

**Comment by janwillemwilmsen** [comment]
Yes got some external help. Closing this!
