### ISSUE TITLE
[EJBCA] Guide on installation

### ISSUE THREAD

**Issue by H0H023** [bitnami/vms#686]
Hi, is the vm is already configured or the configuration need to be done by the user  ? if so can you guide me where to begin as it is as hard to determine what that has been done by Bitnami and whats not.... thanks

**Comment by jotamartos** [comment]
We configure the app and create an user/password for you to use to log in to the application. The configuration logic is similar to the one we publish for [our containers](https://github.com/bitnami/containers/tree/main/bitnami/ejbca/7/debian-11/rootfs/opt/bitnami/scripts). 

You can also get general information about the Bitnami solution in [our documentation](https://docs.bitnami.com/general/apps/ejbca/)
