### ISSUE TITLE
[Drupal] AWS Lightsail Bitnami failing to start 

### ISSUE THREAD

**Issue by MyaBee802** [bitnami/vms#687]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1efe04d4-c5de-1100-a74f-8ba469455648

### bndiagnostic output

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]
Press [Enter] to continue:

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf:
module log_config_module is built-in and can't be loaded
```
Please check the configuration.

System Apache is running:
```
root 671 0.0 0.2 6588 5028 ? Ss Feb13 0:04 /usr/sbin/apache2 -k start www-data
23541 0.0 0.3 752632 7896 ? Sl 00:00 0:00 /usr/sbin/apache2 -k start
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the
following command to stop it:

### bndiagnostic was not useful. Could you please tell us why?

Not sure?

### Describe your issue as much as you can

Thank you in advance for any help you might provide.

I have been asked to help fix an AWS Lightsail Bitnami image that is failing to start. I ran the bndiagnostic tool and posted the results. It says that there are firewall related issues but that doesn't make any sense since the site was once fully functional?  

Also I have run the following commands 

1. free -m 
2. df -h 
3. systemctl status bitnami.service
4. journalctl -xe

with the associated results posted below. (I have attached screen captures of 3 & 4 to make it easier to review.) But I have no background experience to interpret them...yet.

Thank you again for any help,
Mya

1. free -m total used free shared buff/cache available Mem: 1982 191 1500 5 289 1643 Swap: 0 0 0

2. df -h Filesystem Size Used Avail Use% Mounted on udev 981M 0 981M 0% /dev tmpfs 199M 416K 198M 1% /run /dev/xvda1 59G 5.1G 52G 9% / tmpfs 992M 0 992M 0% /dev/shm tmpfs 5.0M 0 5.0M 0% /run/lock /dev/xvda15 124M 11M 114M 9% /boot/efi tmpfs 199M 0 199M 0% /run/user/1000

3. sudo systemctl status bitnami.service ● bitnami.service - LSB: bitnami init script Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Mon 2023-02-13 17:06:13 UTC; 5min ago Process: 3722 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE) Tasks: 29 (limit: 2353) Memory: 240.6M CPU: 1.825s CGroup: /system.slice/bitnami.service ├─947 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf) ├─951 php-fpm: pool www ├─952 php-fpm: pool www ├─953 php-fpm: pool www ├─954 php-fpm: pool www ├─955 php-fpm: pool www ├─956 php-fpm: pool www ├─957 php-fpm: pool www ├─958 php-fpm: pool www ├─959 php-fpm: pool www ├─960 php-fpm: pool www ├─961 php-fpm: pool www ├─962 php-fpm: pool www ├─963 php-fpm: pool www ├─964 php-fpm: pool www ├─965 php-fpm: pool www ├─966 php-fpm: pool www ├─967 php-fpm: pool www ├─968 php-fpm: pool www ├─969 php-fpm: pool www ├─970 php-fpm: pool www └─982 /opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnam>

Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: bitnami.service: Unit process 964 (php-fpm) remains running after unit stopped. Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: bitnami.service: Unit process 965 (php-fpm) remains running after unit stopped. Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: bitnami.service: Unit process 966 (php-fpm) remains running after unit stopped. Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: bitnami.service: Unit process 967 (php-fpm) remains running after unit stopped. Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: bitnami.service: Unit process 968 (php-fpm) remains running after unit stopped. Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: bitnami.service: Unit process 969 (php-fpm) remains running after unit stopped. Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: bitnami.service: Unit process 970 (php-fpm) remains running after unit stopped. Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: bitnami.service: Unit process 982 (mysqld) remains running after unit stopped. Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: Failed to start LSB: bitnami init script. Feb 13 17:06:13 ip-172-26-2-48 systemd[1]: bitnami.service: Consumed 1.754s CPU time.

4. sudo journalctl -xe Feb 13 19:49:48 ip-172-26-2-48 dhclient[421]: XMT: Renew on eth0, interval 10100ms. Feb 13 19:49:48 ip-172-26-2-48 dhclient[421]: RCV: Reply message on eth0 from fe80::c2:f4ff:fe6b:8e02. Feb 13 19:49:53 ip-172-26-2-48 sshd[18843]: Received disconnect from 24.199.118.157 port 45194:11: Bye Bye [preauth] Feb 13 19:49:53 ip-172-26-2-48 sshd[18843]: Disconnected from authenticating user root 24.199.118.157 port 45194 [preauth] Feb 13 19:49:58 ip-172-26-2-48 sshd[18845]: Received disconnect from 187.95.162.20 port 22203:11: Bye Bye [preauth] Feb 13 19:49:58 ip-172-26-2-48 sshd[18845]: Disconnected from authenticating user root 187.95.162.20 port 22203 [preauth] Feb 13 19:50:08 ip-172-26-2-48 sshd[18847]: Received disconnect from 34.78.185.36 port 35536:11: Bye Bye [preauth] Feb 13 19:50:08 ip-172-26-2-48 sshd[18847]: Disconnected from authenticating user root 34.78.185.36 port 35536 [preauth] Feb 13 19:50:34 ip-172-26-2-48 sshd[18849]: Received disconnect from 103.211.217.103 port 45502:11: Bye Bye [preauth] Feb 13 19:50:34 ip-172-26-2-48 sshd[18849]: Disconnected from authenticating user root 103.211.217.103 port 45502 [preauth] Feb 13 19:50:35 ip-172-26-2-48 sshd[18851]: Received disconnect from 139.59.121.221 port 33362:11: Bye Bye [preauth] Feb 13 19:50:35 ip-172-26-2-48 sshd[18851]: Disconnected from authenticating user root 139.59.121.221 port 33362 [preauth] Feb 13 19:50:56 ip-172-26-2-48 sshd[18853]: Received disconnect from 159.223.202.231 port 36660:11: Bye Bye [preauth] Feb 13 19:50:56 ip-172-26-2-48 sshd[18853]: Disconnected from authenticating user root 159.223.202.231 port 36660 [preauth] Feb 13 19:50:58 ip-172-26-2-48 dhclient[421]: PRC: Renewing lease on eth0. Feb 13 19:50:58 ip-172-26-2-48 dhclient[421]: XMT: Renew on eth0, interval 9500ms. Feb 13 19:50:58 ip-172-26-2-48 dhclient[421]: RCV: Reply message on eth0 from fe80::c2:f4ff:fe6b:8e02. Feb 13 19:51:12 ip-172-26-2-48 sshd[18859]: Connection reset by 104.191.174.129 port 40154 [preauth] Feb 13 19:51:39 ip-172-26-2-48 sshd[18862]: Received disconnect from 222.119.64.11 port 54872:11: Bye Bye [preauth] Feb 13 19:51:39 ip-172-26-2-48 sshd[18862]: Disconnected from authenticating user root 222.119.64.11 port 54872 [preauth] Feb 13 19:51:39 ip-172-26-2-48 sshd[18864]: Received disconnect from 34.78.185.36 port 37170:11: Bye Bye [preauth] Feb 13 19:51:39 ip-172-26-2-48 sshd[18864]: Disconnected from authenticating user root 34.78.185.36 port 37170 [preauth] Feb 13 19:51:54 ip-172-26-2-48 sshd[18866]: Received disconnect from 187.95.162.20 port 21810:11: Bye Bye [preauth] Feb 13 19:51:54 ip-172-26-2-48 sshd[18866]: Disconnected from authenticating user root 187.95.162.20 port 21810 [preauth] Feb 13 19:52:01 ip-172-26-2-48 CRON[18870]: pam_unix(cron:session): session opened for user bitnami(uid=1000) by (uid=0) Feb 13 19:52:01 ip-172-26-2-48 CRON[18871]: (bitnami) CMD (cd /opt/bitnami/stats && ./agent.bin --run -D) Feb 13 19:52:01 ip-172-26-2-48 CRON[18870]: pam_unix(cron:session): session closed for user bitnami Feb 13 19:52:02 ip-172-26-2-48 sshd[18868]: Received disconnect from 103.211.217.103 port 36608:11: Bye Bye [preauth] Feb 13 19:52:02 ip-172-26-2-48 sshd[18868]: Disconnected from authenticating user root 103.211.217.103 port 36608 [preauth] Feb 13 19:52:08 ip-172-26-2-48 dhclient[421]: PRC: Renewing lease on eth0. Feb 13 19:52:08 ip-172-26-2-48 dhclient[421]: XMT: Renew on eth0, interval 9660ms. Feb 13 19:52:08 ip-172-26-2-48 dhclient[421]: RCV: Reply message on eth0 from fe80::c2:f4ff:fe6b:8e02. Feb 13 19:52:24 ip-172-26-2-48 sshd[18948]: Received disconnect from 159.223.202.231 port 39616:11: Bye Bye [preauth] Feb 13 19:52:24 ip-172-26-2-48 sshd[18948]: Disconnected from authenticating user root 159.223.202.231 port 39616 [preauth] Feb 13 19:52:27 ip-172-26-2-48 sshd[18950]: Received disconnect from 139.59.121.221 port 38756:11: Bye Bye [preauth] Feb 13 19:52:27 ip-172-26-2-48 sshd[18950]: Disconnected from authenticating user root 139.59.121.221 port 38756 [preauth] Feb 13 19:52:39 ip-172-26-2-48 sshd[18952]: Received disconnect from 24.199.118.157 port 60840:11: Bye Bye [preauth] Feb 13 19:52:39 ip-172-26-2-48 sshd[18952]: Disconnected from authenticating user root 24.199.118.157 port 60840 [preauth] Feb 13 19:53:18 ip-172-26-2-48 dhclient[421]: PRC: Renewing lease on eth0. Feb 13 19:53:18 ip-172-26-2-48 dhclient[421]: XMT: Renew on eth0, interval 9150ms. Feb 13 19:53:18 ip-172-26-2-48 dhclient[421]: RCV: Reply message on eth0 from fe80::c2:f4ff:fe6b:8e02. Feb 13 19:53:19 ip-172-26-2-48 sshd[18954]: Received disconnect from 34.78.185.36 port 46468:11: Bye Bye [preauth] Feb 13 19:53:19 ip-172-26-2-48 sshd[18954]: Disconnected from authenticating user root 34.78.185.36 port 46468 [preauth] Feb 13 19:53:28 ip-172-26-2-48 sshd[18960]: Received disconnect from 103.211.217.103 port 39666:11: Bye Bye [preauth] Feb 13 19:53:28 ip-172-26-2-48 sshd[18960]: Disconnected from authenticating user root 103.211.217.103 port 39666 [preauth] Feb 13 19:53:28 ip-172-26-2-48 sshd[18962]: Received disconnect from 222.119.64.11 port 59804:11: Bye Bye [preauth] Feb 13 19:53:28 ip-172-26-2-48 sshd[18962]: Disconnected from authenticating user root 222.119.64.11 port 59804 [preauth] Feb 13 19:53:44 ip-172-26-2-48 sudo[18973]: bitnami : TTY=pts/1 ; PWD=/ ; USER=root ; COMMAND=/usr/bin/journalctl -xe Feb 13 19:53:44 ip-172-26-2-48 sudo[18973]: pam_unix(sudo:session): session opened 
<img width="713" alt="Screen Shot 2023-02-14 at 3 51 28 PM" src="https://user-images.githubusercontent.com/113480198/218871449-a8573105-79ab-4f68-a34c-dcac52bdb7d1.png">
<img width="702" alt="Screen Shot 2023-02-14 at 3 51 08 PM" src="https://user-images.githubusercontent.com/113480198/218871451-5f52c40a-5ba4-4e06-84e8-6da70aca2484.png">
for user root(uid=0) by bitnami(uid=1000)
<img width="1010" alt="Screen Shot 2023-02-14 at 3 50 06 PM" src="https://user-images.githubusercontent.com/113480198/218871414-519296c9-0f34-4c1f-a191-6f9ed88df1c6.png">

**Comment by MyaBee802** [comment]
I've been looking thru similar issues, such as:
https://github.com/bitnami/vms/issues/512

I'm not sure its relevant?  Here is what the equivalent contains...  I hope this helps?
/opt/bitnami/apache2/conf/vhosts/drupal-https-vhost.conf
      1 <VirtualHost 127.0.0.1:443 _default_:443>
      2   ServerName www.example.com
      3   ServerAlias *
      4   SSLEngine on
      5   SSLCertificateFile "/opt/bitnami/apache/conf/www.websitename.org.crt"
      6   SSLCertificateKeyFile "/opt/bitnami/apache/conf/www.websitename.org.key"
      7   DocumentRoot /opt/bitnami/drupal
      8   # BEGIN: Configuration for letsencrypt
      9   Include "/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf"
     10   # END: Configuration for letsencrypt
     11   # BEGIN: Support domain renewal when using mod_proxy without Location
     12   <IfModule mod_proxy.c>
     13     ProxyPass /.well-known !
     14   </IfModule>
     15   # END: Support domain renewal when using mod_proxy without Location
     16   # BEGIN: Enable non-www to www redirection
     17   RewriteEngine On
     18   RewriteCond %{HTTP_HOST} !^www\. [NC]
     19   RewriteCond %{HTTP_HOST} !^localhost
     20   RewriteCond %{HTTP_HOST} !^[0-9]+.[0-9]+.[0-9]+.[0-9]+(:[0-9]+)?$
     21   RewriteCond %{REQUEST_URI} !^/\.well-known
     22   RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [R=permanent,L]
     23   # END: Enable non-www to www redirection
     24   <Directory "/opt/bitnami/drupal">
     25     Options -Indexes +FollowSymLinks -MultiViews
     26     AllowOverride None
     27     Require all granted
     28   </Directory>
     29   Include "/opt/bitnami/apache/conf/vhosts/htaccess/drupal-htaccess.conf"
     30   # BEGIN: Support domain renewal when using mod_proxy within Location
     31   <Location /.well-known>
     32     <IfModule mod_proxy.c>
     33       ProxyPass !
     34     </IfModule>
     35   </Location>
     36   # END: Support domain renewal when using mod_proxy within Location
     37 </VirtualHost>

**Comment by MyaBee802** [comment]
I have rerun the bndiagnostic tool; the latest file id is:
285b4fad-77cc-1207-c3f4-5fd1615dbf6c

**Comment by mdhont** [comment]
It seems you have another instance of Apache running alongside of the Bitnami Apache component:

```
root 671 0.0 0.2 6588 5028 ? Ss Feb13 0:04 /usr/sbin/apache2 -k start www-data
```

Try stopping it:

```
sudo systemctl stop apache2.service
```

And then starting Bitnami Apache:

    sudo /opt/bitnami/ctlscript.sh start apache

**Comment by MyaBee802** [comment]
Yes, that's true, I checked with sudo systemctl status apache2, it was running. But now nothing on the instance wants to start.  I checked another AWS Lightsail instance and it appears to also have apache2 installed, altho not running.  Please help.

**Comment by MyaBee802** [comment]
@mdhont I want to get your opinion before I try this...Do you think restoring httpd.conf and bitnami.conf files to their original state would help?  
--Mya

**Comment by mdhont** [comment]
There seems to be a syntax error in the configuration, so restoring the files to the original state should help:

```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf:
module log_config_module is built-in and can't be loaded

```

**Comment by MyaBee802** [comment]
@mdhont  I replaced the httpd.conf file with a backup copy that was made by openssl back when ssl was established and that fixed the issue...it was able to get bitnami.service running.  So the site is back up and running, tho I have not tested the functionality yet to make sure everything is working properly.  Thanks for your help! @mdhont 
-- Mya

**Comment by MyaBee802** [comment]
I have learned so much via this bug.  Best teaching drill I've ever experienced!

**Comment by sbfs-co** [comment]
I'm having the same problem with WordPress lightsail. This is a website that was working
