### ISSUE TITLE
[EJBCA] Apache Documentation All Incorrect on Website

### ISSUE THREAD

**Issue by jacksongnav** [bitnami/vms#688]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic output

N/A

### bndiagnostic was not useful. Could you please tell us why?

N/A

### Describe your issue as much as you can

I deployed this package in my Azure environment:
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.ejbca

I went change my SSL certificate for the web UI and more, but the documentation is all wrong. I have no apache folder in /opt/bitnami. It appears the app is running on wildfly? If that's the case all the apache information is incorrect.

Please advise!

**Comment by mdhont** [comment]
We will make the necessary changes to the documentation. Thank you for notifying us.
