### ISSUE TITLE
[Wordpress] Need updated instructions/docs how to run 2 wordpress installs in a single VM

### ISSUE THREAD

**Issue by muonnoi** [bitnami/vms#69]
### Describe your issue as much as you can

Hello,
This is probably disccussed much already but it seems most of the links/instructions/documents about how to setup 2 Wordpress install in a single VM are either out-of-dated or unavailable.  So please help us out with this.
We currently have an AWS VM with Wordpress stack by Bitnami and not sure how to config and run the 2nd Wordpress install on the same VM?  We are able to follow and download another Wordpress install by using the installer but then dont know what to do next due to the out-of-dated or unavailable links in previous discussions.

Any help is much appreciated!

**Comment by mdhont** [comment]
Running different WordPress sites on one database is not a supported Bitnami solution. That doesn't mean it can't be done but for that scenario we recommend using our WordPress Multisite solution instead. However, the following guide shows how you can configure one or multiple custom PHP applications on top of LAMP, which could help you:

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/
