### ISSUE TITLE
[Redmine] How to get older version Redmine by Bitnami for Windows

### ISSUE THREAD

**Issue by mohamedmamdouh1** [bitnami/vms#690]
### Describe your issue as much as you can

Hi experts.

I'm looking for previous versions of the Redmine by Bitnami
I'd like to migrate redmine 3.x or 4.x on windows, installed with the bitnami installer to a windows server

Thanks in advance.

**Comment by mdhont** [comment]
Which exact version do you need?

**Comment by mohamedmamdouh1** [comment]
I still don't know the exact version, so I was hoping for an archiving page for all previous release, 

Thank you in advance.

**Comment by mdhont** [comment]
We share the links on a per request basis. Here you have a link for Redmine version 4.1.1:

 https://downloads.bitnami.com/files/stacks/redmine/4.1.1-7/bitnami-redmine-4.1.1-7-windows-x64-installer.exe 

     md5:204f0fe6b31ae18328d4ab575c607857

**Comment by hiasl11** [comment]
Hi,
is there a chance to get the ova of version 4.1.1?

**Comment by mdhont** [comment]
Yes:

https://downloads.bitnami.com/files/stacks/redmine/4.1.1-0/bitnami-redmine-4.1.1-0-linux-debian-9-x86_64.ova 

    md5:14d50b67fb611b379797e19157d882c0

**Comment by hiasl11** [comment]
Thanks!

**Comment by OlegZaborej** [comment]
> Мы делимся ссылками по каждому запросу. Вот ссылка на Redmine версии 4.1.1:
> 
> https://downloads.bitnami.com/files/stacks/redmine/4.1.1-7/bitnami-redmine-4.1.1-7-windows-x64-installer.exe
> 
> ```
>  md5:204f0fe6b31ae18328d4ab575c607857
> ```
Good afternoon, can you please drop a link to this version bitnami-redmine-4.1.1.1-7-windows-x64-installer.exe.
That link is unfortunately not active, thanks.

**Comment by premp1981** [comment]
I'm looking for previous versions of the Redmine by Bitnami
I'd like to migrate redmine 4.x or 5.x on windows, installed with the bitnami installer to a windows server

**Comment by jotamartos** [comment]
I just updated your other ticket https://github.com/bitnami/vms/issues/1592
