### ISSUE TITLE
[Redmine] Receiving error message when attempting to install plugin

### ISSUE THREAD

**Issue by sgjohnson1981** [bitnami/vms#691]
### Describe your issue as much as you can

Trying to follow the instructions to install some Redmine plugins. Started with mega_calendar and I can't get this one installed. Might need further help even after this first one, given success so far.

When I get as far as the "bundle exec..." command, I receive the following error:
Errno::EACCES: Permission denied @ rb_sysopen - /opt/bitnami/redmine/db/schema.rb

How do I proceed?

**Comment by sgjohnson1981** [comment]
I started over and did NOT use sudo this time. Still get permission error on bundle install. The destination has root permission and apparently bundle does not. In what little experience I have with bitnami it seems you've really done nothing but traded dependency hell for permission hell.

**Comment by jotamartos** [comment]
Did you take a look at this guide in our documentation? 

https://docs.bitnami.com/general/apps/redmine/configuration/install-plugins/

You can change the permissions ownership before running the installation commands to ensure bitnami and daemon have write permissions 

```
sudo chown -R bitnami:daemon /opt/bitnami/redmine /bitnami/redmine
sudo chmod -R g+w /opt/bitnami/redmine /bitnami/redmine
```

**Comment by sgjohnson1981** [comment]
That was the guide I was using. Changing those permissions is no where in the instructions. I would have hoped it would either be there, or that feature would already be configured considering that's the entire point of these prepackaged deals. But in all fairness, it's pretty much the same in trying to install redmine anywhere else. I'm giving up for now until redmine can get it's sh*t together. I've wrestled with this for days and I'm tired of it. It baffles me that many in the open-source community complain about how more people should use open-source software but there doesn't seem to be much effort put into making these things usable for the average person. Good documentation is especially hard to come by.
