### ISSUE TITLE
[<REDMINE>] <Getting classic .exe intaller>

### ISSUE THREAD

**Issue by KlemenVoncina** [bitnami/vms#693]
### Describe your issue as much as you can

Hi,

I wanted to upgrade our Redmine Stack, but all I can find on the webpage are .ova files, not classic installers.
Am I missing something?

Please give us the option to download .exe installers.

Best regards

**Comment by gongomgra** [comment]
Hi @KlemenVoncina,

Thanks for using Bitnami. Local installers support has been dropped in favour of our containers, virtual-machines and cloud images solutions. You can get more information about this in our blogpost linked below

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

We highly recommend you to start using one of our supported solutions and migrate the Redmine data there.

https://docs.bitnami.com/general/apps/redmine/administration/upgrade/

In case you are migrating between major versions, we recommend you to open a new question in the official Redmine forums for the official developers to tell you if upgrading to any intermediate version is needed for your specific use case

https://www.redmine.org/projects/redmine/boards
