### ISSUE TITLE
[MariaDB] Bitnami.service and mariadb not starting

### ISSUE THREAD

**Issue by jswapneswar** [bitnami/vms#694]
### Describe your issue as much as you can
![image](https://user-images.githubusercontent.com/104552616/219683159-6e5d93a0-6495-4fc1-abaf-97ce4a0181c6.png)

when ever i trying to start service its not starting ,its been 10 days i tried with all posibilities ,checked so many articles but not found the correct answers ,can anyone please help me on this .
![image](https://user-images.githubusercontent.com/104552616/219683253-7b59563e-38b6-4caf-8f91-06a621f9b3c3.png)

**Comment by kkm5848** [comment]
try deleting mysqld.pid?  Seem to have helped for me when I had an OOM issue that crashed mariadb.

**Comment by jswapneswar** [comment]
this is a production server can i delete mysqld.pid.

**Comment by jotamartos** [comment]
Hi @jswapneswar,

Did you take a look at the database's log file to see if there is any error there? If you do not know what's happening, you can run the Bitnami Support Tool for us to review the info

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

**Comment by jswapneswar** [comment]
Hi @jotamartos i run bitnami support tool on server,can you please check on your side if there is any problem and here i am sharing you the support ticket.
7e745793-df87-9d2d-9118-1943144a39c1

**Comment by jotamartos** [comment]
If you take a look at the MariaDB's log files, the database is returning this error 

```
2023-02-20 13:12:39 0 [ERROR] InnoDB: Missing MLOG_CHECKPOINT at 35666707384 between the checkpoint 35666707384 and the end 35667139287.
2023-02-20 13:12:39 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
```

You can find [here](https://support.inductiveautomation.com/hc/en-us/articles/4415186180493-MySQL-or-MariaDB-is-faulted-due-a-startup-error) a suggestion to fix the issue

**Comment by jswapneswar** [comment]
already tried with this solution but its not starting, after your suggestion i tried again but nothing happen its same as previous.

**Comment by jotamartos** [comment]
In that case, please review the MariaDB's documentation and forums to know how to solve this issue. Please note that it's a specific issue of the database and it's out of the scope of this forum.
