### ISSUE TITLE
[WAMP] Where is Bitnami Wamp?

### ISSUE THREAD

**Issue by ircary** [bitnami/vms#695]
### Describe your suggestion as much as you can

Bitnami Wamp PHP v8.2 or any version for that matter is nowhere to be found.

Is it still supported?

**Comment by jotamartos** [comment]
As we announced in our blog post, we removed support for the installers in November 2022

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

You can use the Bitnami VMs for LAMP to deploy your PHP application.
