### ISSUE TITLE
[Bitnami Multisite] Home page redirecting to wp_signup page by default 

### ISSUE THREAD

**Issue by simplyhum** [bitnami/vms#696]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

84a2ba05-37f9-c0ec-960f-8d0fc0674b17

### bndiagnostic output

No such output.

### bndiagnostic was not useful. Could you please tell us why?

It was helpful, but your documentation needs to change - https://docs.bitnami.com/general/how-to/understand-bndiagnostic/ . It is now called - bnsupport-tool instead.

### Describe your issue as much as you can

Hi,

My website(.[syncup.co.in](url)) home page is automatically being redirected to the wp_signup page, although I have not configured it so. I am not even being able to log into my Wordpress admin  i.e [](https://www.syncup.co.in/admin) . 

Not sure, what is the issue and how are these redirections happening. Kindly help. I have shared the support tool o/ id.

Thanks,
Anand

**Comment by jotamartos** [comment]
That's a WordPress' configuration issue. It's probably related with the domain configuration. You can take a look at [our guide](https://docs.bitnami.com/general/apps/wordpress-multisite/configuration/configure-wordpress-multisite/) and the WordPress' documentation to know more about how to configure the app. If you have any questions regarding the app, we suggest you contact the WordPress' support team. This issue is out of the scope of this support forum

https://wordpress.org/documentation/

**Comment by simplyhum** [comment]
@jotamartos I have actually checked the Wordpress config. It all looks good, atleast at the surface. I have a feeling it has something to the SSL redirection configuration, using the Bitnami config. Request you to review the support and log shared and see if anything seems off. 
In the meanwhile, I am anyway rechecking my wordpress config at more detailed level.

Thanks,
Anand

**Comment by simplyhum** [comment]
@jotamartos Also my reasoning to suggest the above is because, when I type the URL - [](https://www.syncup.co.in) the site perfectly goes to the homepage. But when I just type [syncup.co.in](url) or when I use the address [](https://syncup.co.in) . That is when the site redirects to the wp_singup page.

**Comment by simplyhum** [comment]
@jotamartos Also to give you more details. I have checked my routing server settings i.e AWS Route 53. Please see the two A record and its alias configs are fine.  [Image 1](https://imgur.com/L05IBzA) and [Image 2](https://imgur.com/PRUZXbd)

Thanks

**Comment by jotamartos** [comment]
Checking the http codes returned by the different requests, I can confirm that it's WordPress what is redirecting to that wp_singup page. As you can see here, Apache redirects to https but WordPress redirects to the wp_singup one 

```
$ curl -LI syncup.co.in
HTTP/1.1 302 Found
Date: Wed, 22 Feb 2023 08:28:30 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Location: https://syncup.co.in/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 302 Found
Date: Wed, 22 Feb 2023 08:28:31 GMT
Server: Apache
X-Powered-By: PHP/7.3.17
X-Frame-Options: SAMEORIGIN
Location: https://www.syncup.co.in/wp-signup.php?new=syncup.co.in
Content-Type: text/html; charset=UTF-8

HTTP/1.1 200 OK
Date: Wed, 22 Feb 2023 08:28:32 GMT
Server: Apache
X-Powered-By: PHP/7.3.17
X-UA-Compatible: IE=edge
X-Frame-Options: SAMEORIGIN
Cache-Control: max-age=0, no-cache
Content-Type: text/html; charset=UTF-8
```

Please contact WordPress or review its documentation to know more about this issue.

**Comment by simplyhum** [comment]
@jotamartos Thank you so much for the detailed analysis. I shall again look into the Wordpress configuration and see where the redirection is happening from
