### ISSUE TITLE
OOM error crashes Mariadb and can't restart w/o deleting mysqld.pid file

### ISSUE THREAD

**Issue by kkm5848** [bitnami/vms#697]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b7b7e142-2c34-8a91-c62b-830f1ce11d41

### bndiagnostic output

Tool didn't output any thing.  Here is what I found in my own diagnostic attempts
![image](https://user-images.githubusercontent.com/28168589/220026257-8f81e0d6-4e4d-4459-bde0-e0e788daaeff.png)
![image](https://user-images.githubusercontent.com/28168589/220026553-652aaeee-681f-4264-b382-1f4b13215c1d.png)
![image](https://user-images.githubusercontent.com/28168589/220026634-8e10dd23-4d73-4846-b377-683eef858757.png)

Manually deleting the msqld.pid was required to get the service working ... but need help to:
1. Identify why this happened to prevent it from happening in the future
2. automating the pid cleanup on system restart so that watchdog can actually work to recover in an automated way

### bndiagnostic was not useful. Could you please tell us why?

It didn't output any useful information

### Describe your issue as much as you can

System ran out of memory causing mariadb to crash and leave behind a .pid file.  The .pid file prevented the system from recovering after a reboot.

Manually deleting the msqld.pid was required to get the service working ... but need help to:
1. Identify why this happened to prevent it from happening in the future
2. automating the pid cleanup on system restart so that watchdog can actually work to recover in an automated way

**Comment by mdhont** [comment]
I's possible that the application crash caused the PID file to not get refreshed, which is why the app couldn't start again, likely because it was reading an outdated value from the file. In any case you could add a startup script that removes the PID file:

```
#!/bin/bash

# source the mariadb-env to get the DB_PID_FILE env variable
source /opt/bitnami/scripts/mariadb-env
# Remove the file if it exists

if [ ! -z "$DB_PID_FILE" ] && [ -e "$DB_PID_FILE" ]; then
  rm "$DB_PID_FILE"
fi

```

**Comment by kkm5848** [comment]
Thanks.  /opt/bitnami/scripts/mariadb-env should be /opt/bitnami/scripts/mariadb-env.sh

Any thoughts on how I can identify the cause of the OOM issue?

**Comment by mdhont** [comment]
Did you check the amount of RAM your application is using?

    free -h

**Comment by kkm5848** [comment]
On a normal basis, I have ~1.4GB of memory free.  As you can see from the
graph, there was a spike just before the crash.
--------------------------------------------------------------------------------
Krishna Maheshwari
***@***.***
***@***.***
Hindupedia, the Hindu Encyclopedia  (www.hindupedia.com)
--------------------------------------------------------------------------------

**Comment by mdhont** [comment]
You could check if disabling binary logging works:

https://docs.bitnami.com/aws/infrastructure/mysql/troubleshooting/disable-binary-logging-mysql/

**Comment by kkm5848** [comment]
The instructions don't work -- they are for mysql.  I am running mariadb.  So, the start/stop doesn't work and the /opt/bitnami/mysql/conf/my.cnf doesn't exist.

**Comment by mdhont** [comment]
In that case it's probably not enabled. You can check it with this command:

    >  show binary logs;

In any case I recommend checking the `/opt/bitnami/mariadb/logs/mysqld.log` log to check what might have caused the error.

**Comment by kkm5848** [comment]
where do I run the command 'show binary logs'?  I am getting 'command not found'

**Comment by kkm5848** [comment]
Also, when i did 'sudo grep -i error /opt/bitnami/mariadb/logs/mysqld.log', I see the following error
2023-02-27 14:38:18 3192 [ERROR] mysqld: Table './bitnami_mediawiki/searchindex' is marked as crashed and should be repaired

**Comment by mdhont** [comment]
It seems the database has become corrupted. Maybe the following guide can help you to repair it:

https://docs.bitnami.com/aws/infrastructure/lamp/administration/recover-database-mariadb/

**Comment by kkm5848** [comment]
This worked solved another issue.  I will give it some time to see if it
addresses the OOM issue.

Krishna
--------------------------------------------------------------------------------
Krishna Maheshwari
***@***.***
***@***.***
Hindupedia, the Hindu Encyclopedia  (www.hindupedia.com)
--------------------------------------------------------------------------------

**Comment by kkm5848** [comment]
It crashed once again but I don't see anything obvious in the error other than a database corruption issue for the searchindex for mediawiki

**Comment by mdhont** [comment]
I recommend asking in the official Mediawiki forum. They might have more information about this issue.

**Comment by kkm5848** [comment]
I have more info from the logs ... does this add any light?
[mysqld.log](https://github.com/bitnami/vms/files/10993180/mysqld.log)

**Comment by mdhont** [comment]
Unfortunately the logs do not show any meaningful information in regards to the cause of the issue.

**Comment by marianopeck** [comment]
Hi @kkm5848 

[I may be seeing a similar OOM kill](https://github.com/bitnami/vms/issues/927). Did you get any more information or workaround?

thanks!

**Comment by kkm5848** [comment]
We did. We ended up implementing


  1.   a watch dog timer
  2.  Script to fix tables in case they were corrupted and another to reboot Mariadb if it crashes
  3.  Changed the caching configs to reduce the configured amount of memory.

The crashes are very infrequent and when they happen, we don’t learn about them at the moment because the system recovers quickly.


________________________________

**Comment by marianopeck** [comment]
Thanks @kkm5848 for sharing your workaround! That sounds painful :(
Would you mind explaining what do you mean by "caching configs"? 

BTW, I couldn't see this info in your reports, but in mine I suspect that the bitnami image could have been configured to allow too much memory for php-fpm. See the link I sent earlier. Did you happen to think about this too? or come to a similar conclusion/thought? I have another Lightsail instance with exact same hardware, same wordpress site but with an older bitnami image (2 years old) and this one doesn't have any problem. And in that older bitnami image, the memory allowed for php-fpm was much less.

**Comment by kkm5848** [comment]
This relates to the amount of memory MariaDB uses.  I don't have the
details as our IT person took care of this part.
--------------------------------------------------------------------------------
Krishna Maheshwari
***@***.***
***@***.***
Hindupedia, the Hindu Encyclopedia  (www.hindupedia.com)
--------------------------------------------------------------------------------

**Comment by marianopeck** [comment]
OK, I see. Thanks for your help @kkm5848 !
