### ISSUE TITLE
[bncert] /opt/bitnami/apache/sbin/nginx: not found

### ISSUE THREAD

**Issue by jotamartos** [bitnami/vms#698]
@jotamartos after I run with your recommendation 

```
cd /tmp
rm -rf bncert-linux-x64.run
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/latest/bncert-linux-x64.run
sudo mkdir /opt/bitnami/bncert
sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
sudo ln -sf /opt/bitnami/bncert/bncert-linux-x64.run /opt/bitnami/bncert-tool
sudo /opt/bitnami/bncert-tool
```

I got error with /opt/bitnami/apache/sbin/nginx: not found? any idea?

<img width="991" alt="Screen Shot 2023-02-19 at 4 40 39 PM" src="https://user-images.githubusercontent.com/125833323/219976827-1c95bf07-a06b-4d9a-9cb8-77db1b113c7e.png">

**Comment by jotamartos** [comment]
That's a weird issue. Could you please let us know the Bitnami solution you are using so we can reproduce it? 

Thanks

**Comment by geosmiles** [comment]
Same issue with Bitnami on Lightsail using Node.js 16.18.1-10 image

**Comment by jotamartos** [comment]
Hi, 

I just launched a fresh Bitnami Nodejs instance and ran the latest version of the bncert tool. The tool configured the SSL certificates without issues 

```
----------------------------------------------------------------------------
Performing changes to your installation

The Bitnami HTTPS Configuration Tool will perform any necessary actions to your
Bitnami installation. This may take some time, please be patient.

----------------------------------------------------------------------------
Success

The Bitnami HTTPS Configuration Tool succeeded in modifying your installation.

The configuration report is shown below.

Backup files:
* /opt/bitnami/apache/conf/httpd.conf.back.202302241441
* /opt/bitnami/apache/conf/bitnami/bitnami.conf.back.202302241441
* /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf.back.202302241441

Find more details in the log file:

/tmp/bncert-202302241441.log

If you find any issues, please check Bitnami Support forums at:

https://github.com/bitnami/vms

Press [Enter] to continue:
```

I do not know if you modified something in the configuration that made the tool fail. However, you can follow the manual approach to generate your certificates

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by jason5591** [comment]
I only setup my instance on lightsail LAMP a few days ago. Yesterday this script was working, then it started to keep saying to enter the path. I updated from the instructions above, then it started reporting:
Warning: The web server configuration check failed. Please fix the configuration
error:
/bin/sh: 1: /opt/bitnami/apache/sbin/nginx: not found

**Comment by marcinjackowiak** [comment]
I ran into the same thing. I added additional vhosts in `/opt/bitnami/apache/conf/vhosts/` before running the cert tool and it caused it to fail with that exact error. I renamed the files and bounced apache, and then renamed them back once the tool completed successfully.

**Comment by jotamartos** [comment]
Hi @jason5591  and @marcinjackowiak,

Could you please provide us more details about the changes you made in the vhosts folder? Did you run bncert before?

Thanks

**Comment by jason5591** [comment]
@jotamartos I added new vhosts to https-vhosts.conf and I must have made an error because that is when the tool stopped working. On a hunch I went back and restored one of the backup copies and the tool ran again.
Unfortunately, even though it did run it did not add the new certificates to the vhosts file and said it couldn't auto renew the certificates any longer. I'm unsure if this is because I followed the steps you outlined at the top and updated to the latest version. Unfortunately, now none of my sites have certificates. I looked at the alternative option but doing them all one at a time isn't really ideal for me. So I'm still looking for a solution to get the tool working again.

**Comment by jotamartos** [comment]
Hi, 

there should be something wrong in the new conf files you added to the vhosts folder. In my case, I added these 2 new files 

```
bitnami@ip-172-31-57-188:/opt/bitnami/apache/conf/vhosts$ cat test-vhost.conf
<VirtualHost 127.0.0.1:80 _default_:80>
  ServerName test.jota.domain
  DocumentRoot /tmp/test
  <Directory "/tmp/test">
    AllowOverride None
    Require all granted
  </Directory>
</VirtualHost>
bitnami@ip-172-31-57-188:/opt/bitnami/apache/conf/vhosts$ cat test-https-vhost.conf
<VirtualHost 127.0.0.1:443 _default_:443>
  ServerName test.jota.domain
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
  DocumentRoot /tmp/test
  <Directory "/tmp/test">
    AllowOverride None
    Require all granted
  </Directory>
</VirtualHost>
```

and restarted Apache to confirm there were no problems. After that, I ran bncert-tool to generate valid SSL certs for jota.domain and test.jota.domain and everything finished successfully 

```
Success

The Bitnami HTTPS Configuration Tool succeeded in modifying your installation.

The configuration report is shown below.

Backup files:
* /opt/bitnami/apache/conf/httpd.conf.back.202303201105
* /opt/bitnami/apache/conf/bitnami/bitnami.conf.back.202303201105
* /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf.back.202303201105
* /opt/bitnami/apache/conf/vhosts/test-https-vhost.conf.back.202303201105
* /opt/bitnami/apache/conf/vhosts/test-vhost.conf.back.202303201105
* /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf.back.202303201105
* /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf.back.202303201105

Find more details in the log file:

/tmp/bncert-202303201105.log

If you find any issues, please check Bitnami Support forums at:

https://github.com/bitnami/vms

Press [Enter] to continue:
```

Now, I have WordPress and my new app configured with the new SSL certificate 

```
bitnami@ip-172-31-57-188:/opt/bitnami/apache/conf/vhosts$ cat wordpress-https-vhost.conf
<VirtualHost 127.0.0.1:443 _default_:443>
  ServerName www.example.com
  ServerAlias *
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/jota.domain.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/jota.domain.key"
  DocumentRoot /opt/bitnami/wordpress
  # BEGIN: Configuration for letsencrypt
  Include "/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf"
  # END: Configuration for letsencrypt
  # BEGIN: Support domain renewal when using mod_proxy without Location
  <IfModule mod_proxy.c>
    ProxyPass /.well-known !
  </IfModule>
  # END: Support domain renewal when using mod_proxy without Location
  <Directory "/opt/bitnami/wordpress">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    RewriteEngine On
    RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
    # END WordPress
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
  # BEGIN: Support domain renewal when using mod_proxy within Location
  <Location /.well-known>
    <IfModule mod_proxy.c>
      ProxyPass !
    </IfModule>
  </Location>
  # END: Support domain renewal when using mod_proxy within Location
</VirtualHost>
bitnami@ip-172-31-57-188:/opt/bitnami/apache/conf/vhosts$ cat test-https-vhost.conf
<VirtualHost 127.0.0.1:443 _default_:443>
  ServerName test.jota.domain
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/jota.domain.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/jota.domain.key"
  DocumentRoot /tmp/test
  # BEGIN: Configuration for letsencrypt
  Include "/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf"
  # END: Configuration for letsencrypt
  # BEGIN: Support domain renewal when using mod_proxy without Location
  <IfModule mod_proxy.c>
    ProxyPass /.well-known !
  </IfModule>
  # END: Support domain renewal when using mod_proxy without Location
  <Directory "/tmp/test">
    AllowOverride None
    Require all granted
  </Directory>
  # BEGIN: Support domain renewal when using mod_proxy within Location
  <Location /.well-known>
    <IfModule mod_proxy.c>
      ProxyPass !
    </IfModule>
  </Location>
  # END: Support domain renewal when using mod_proxy within Location
</VirtualHost>
```

The bitnami-ssl.conf file also uses the same files when configuring the certificate. 

>AH00526: Syntax error on line 18 of /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf:
SSLCertificateFile: file '/opt/bitnami/apache/conf/(mydomainname).com.crt' does not exist or is empty

Try to recover the sample SSL certificate to be able to restart Apache, and then verify if the SSL cert exist in the `/opt/bitnami/letsencrypt/certificates/` folder. If it doesn't exist, please try to generate the certificate again. 

As I mentioned above, you can also follow the alternative approach to generate the SSL cert for all your domains. You just need to include all of them when running the lego command 

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by jason5591** [comment]
I've created and failed at several new lightsail instances. So I wanted to follow your outline exactly. Where it appears everything went wrong is that each VirtualHost did not have the SSLCertificateFile and SSLCertificateKeyFile references. I didn't see this listed in the guides and the bncert-tool doesn't add them on it's own.

Thanks very much for your help!

**Comment by jotamartos** [comment]
This guide explains how to deploy a custom app and how to create new vhosts files inside the vhosts folder. 

https://docs.bitnami.com/general/apps/wordpress/administration/create-custom-application-php/

**Comment by piotrmasek** [comment]
Im also getting the "/bin/sh: 1: /sbin/nginx: not found" error.

**Comment by jpSimkins** [comment]
I too am having this issue after upgrading the tool using:

```
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/latest/bncert-linux-x64.run
sudo mkdir /opt/bitnami/bncert
sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
sudo ln -s /opt/bitnami/bncert/bncert-linux-x64.run /opt/bitnami/bncert-tool
```

Now I am seeing:

```
$ sudo /opt/bitnami/bncert-tool
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default 
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]: 

Warning: The web server configuration check failed. Please fix the configuration 
error: 
/bin/sh: 1: /opt/bitnami/apache2/sbin/nginx: not found
```

I manually updated the tool due to not being able to renew my cert (cron failed and manually running it failed). This was due to this server not being updated for a few years. This was a much older setup and there is no virtual hosts being used. The project is installed at `/opt/bitnami/apps/wordpress/htdocs/`

I regrettably decided to update the tool. Now I am unable to use this tool to generate the cert. It'll probably be easier to just redeploy on a new instance than to try to get this to work.

Just adding this here for more information as this is a an actual issue although it seems to be due (for my case) to deploying older instances with AWS Lightsail.

**Comment by jotamartos** [comment]
Hi @jpSimkins,

>The project is installed at /opt/bitnami/apps/wordpress/htdocs/

I think this is the key here. You are using the old directory structure and this may be the reason why the tool doesn't work for you. Please note that we changed the directory structure some years ago and the scripts were also updated. 

To unblock you, did you try to run the lego command to renew the cert? You should find it in the cron configuration. If not, you can generate a new one following the alternative approach

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by flaav** [comment]
Getting the same error here, using the Wordpress instance on AWS lightsail

Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default 
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]: /opt/bitnami

Warning: The web server configuration check failed. Please fix the configuration 
error: 
/bin/sh: 1: /opt/bitnami/apache2/sbin/nginx: not found
Press [Enter] to continue:

**Comment by roya2543** [comment]
I am getting the same error. It happened after I tried to renew it manually yesterday , it failed. and today I get the following errors:
sudo /opt/bitnami/bncert-tool
/bin/sh: 1: /opt/bitnami/apache2/sbin/nginx: not found
I do not even have sbin at my Apache2

and it fails to restart, stop the apache. 

 sudo /opt/bitnami/ctlscript.sh restart apache
Unmonitored apache
AH00526: Syntax error on line 73 of /opt/bitnami/apache2/conf/bitnami/bitnami.conf:
SSLCertificateFile: file '/opt/bitnami/apache2/conf/www.aedescost.eu.crt' does not exist or is empty
apache config test fails, aborting

Did anyone fix the issue?

**Comment by jotamartos** [comment]
Hi @roya2543,

As I mentioned above, you are probably using the old directory structure that's why the tool doesn't work for you. Please follow the alternative approach to generate your certificates 

https://github.com/bitnami/vms/issues/698#issuecomment-1513465290

**Comment by EarthmanWeb** [comment]
I've identified a reproduction vector for this issue.

This issue occurs when the bncert tool has failed due to a missing a record for one of the domains in teh domain list.

The bncert tool worked correctly prior to the error, in a previous run with a different list of domains.

After the failure, now it fails (no directory structure has changed, other than changes made by the bncert tool) with:

```
Warning: The web server configuration check failed. Please fix the configuration 
error: 
/bin/sh: 1: /opt/bitnami/apache/sbin/nginx: not found
```

Can you please advise if you are able to recreate, by adding a domain with no a record to the configuration list, allowing the tool to fail, then trying to run again?

**Comment by EarthmanWeb** [comment]
It appears that whatever changes were made by the bncert tool have rendered the services unstartable - here is teh output:

```

bitnami@ip-172-26-10-189:~$ sudo /opt/bitnami/ctlscript.sh start
Starting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.
bitnami@ip-172-26-10-189:~$ journalctl -xe
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitnami.service has entered the 'failed' state with result 'exit-code'.
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: bitnami.service: Unit process 679 (php-fpm) remains running after u>
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: bitnami.service: Unit process 698 (php-fpm) remains running after u>
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: bitnami.service: Unit process 718 (mysqld) remains running after un>
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: Failed to start LSB: bitnami init script.
░░ Subject: A start job for unit bitnami.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit bitnami.service has finished with a failure.
░░ 
░░ The job identifier is 374 and the job result is failed.
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: bitnami.service: Consumed 2.005s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitnami.service completed and consumed the indicated resources.
Mar 16 23:41:08 ip-172-26-10-189 sudo[988]: pam_unix(sudo:session): session closed for user root

bitnami@ip-172-26-10-189:~$ systemctl status bitnami.service
● bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-03-16 23:41:08 UTC; 46s ago
    Process: 997 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
      Tasks: 10 (limit: 1116)
     Memory: 550.4M
        CPU: 2.016s
     CGroup: /system.slice/bitnami.service
             ├─679 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
             ├─698 php-fpm: pool www
             └─718 /opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/>

Mar 16 23:41:08 ip-172-26-10-189 bitnami[1099]: ## 2024-03-16 23:41:08+00:00 ## INFO ## Running /opt/bitnami/var>
Mar 16 23:41:08 ip-172-26-10-189 bitnami[1099]: ## 2024-03-16 23:41:08+00:00 ## INFO ## Running /opt/bitnami/var>
Mar 16 23:41:08 ip-172-26-10-189 bitnami[1099]: ## 2024-03-16 23:41:08+00:00 ## INFO ## Running /opt/bitnami/var>
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAIL>
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: bitnami.service: Failed with result 'exit-code'.
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: bitnami.service: Unit process 679 (php-fpm) remains running after u>
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: bitnami.service: Unit process 698 (php-fpm) remains running after u>
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: bitnami.service: Unit process 718 (mysqld) remains running after un>
Mar 16 23:41:08 ip-172-26-10-189 systemd[1]: Failed to start LSB: bitnami init script.
```

**Comment by EarthmanWeb** [comment]
The solution I found was to manually revoke the existing certificates:
https://docs.bitnami.com/general/how-to/understand-bncert/#troubleshooting

Then restart the services:
```
sudo /opt/bitnami/ctlscript.sh restart apache
sudo /opt/bitnami/ctlscript.sh rstart
```

Then re-run the bncert tool, making sure this time that all A records were correctly in place, first
```
sudo /opt/bitnami/bncert-tool
```

This issue appears to point to a defect in the error handling / rollback procedure when the bncert tool runs into an error when trying to install new certificates, after certificates are already in place.  
IE: The changes noted below

```
----------------------------------------------------------------------------
Changes to perform

The following changes will be performed to your Bitnami installation:

1. Stop web server
2. Configure web server to use a free Let's Encrypt certificate for the domains: 
snsevents.ca www.snsevents.ca sobernotsomber.ca www.sobernotsomber.ca
3. Configure a cron job to automatically renew the certificate each month
4. Configure web server name to: snsevents.ca
5. Start web server once all changes have been performed

----------------------------------------------------------------------------
Performing changes to your installation

The Bitnami HTTPS Configuration Tool will perform any necessary actions to your 
Bitnami installation. This may take some time, please be patient.

[ THIS IS WHERE IT BROKE THE APACHE SERVICES / CONFIG]

```

**Comment by k98kurz** [comment]
As of 2024-04-12, this is still an issue. Just encountered it when trying to configure for a missing A record for a subdomain because it does not support wildcard certificates. This issue should be reopened and fixed.

**Comment by EarthmanWeb** [comment]
Hi @jotamartos,

It appears I am not the only one able to reproduce this error and the resulting broken configuration.

It may not be directly related to the generation of the certs, but something to do with other changes made to the system which are not rolled back.  I have not personally reviewed the code and do not know the cause, but I am aware of reproducible results, which @k98kurz has confirmed, when they also tried the same procedure, running into an error whe the A record is not present.

@jotamartos  - Are you able to reproduce?

**Comment by EarthmanWeb** [comment]
Steps to reproduce:

- Create a new lightsail instance
- Configure SSL with bncert for a properly configured domain (domainA)
- Generate certs succesfully
- THEN
- Re-run the tool
- Add an additional domain (domainB), which does *not* have an A record properly configured
- The tool will fail (because of domainB)
- - Apache error / configuration will be broken for the previously configured domain (domainA)

**Comment by markfaust123** [comment]
> The solution I found was to manually revoke the existing certificates: https://docs.bitnami.com/general/how-to/understand-bncert/#troubleshooting
> 
> Then restart the services:
> 
> ```
> sudo /opt/bitnami/ctlscript.sh restart apache
> sudo /opt/bitnami/ctlscript.sh rstart
> ```
> 
> Then re-run the bncert tool, making sure this time that all A records were correctly in place, first
> 
> ```
> sudo /opt/bitnami/bncert-tool
> ```
> 
> This issue appears to point to a defect in the error handling / rollback procedure when the bncert tool runs into an error when trying to install new certificates, after certificates are already in place. IE: The changes noted below
> 
> ```
> ----------------------------------------------------------------------------
> Changes to perform
> 
> The following changes will be performed to your Bitnami installation:
> 
> 1. Stop web server
> 2. Configure web server to use a free Let's Encrypt certificate for the domains: 
> snsevents.ca www.snsevents.ca sobernotsomber.ca www.sobernotsomber.ca
> 3. Configure a cron job to automatically renew the certificate each month
> 4. Configure web server name to: snsevents.ca
> 5. Start web server once all changes have been performed
> 
> ----------------------------------------------------------------------------
> Performing changes to your installation
> 
> The Bitnami HTTPS Configuration Tool will perform any necessary actions to your 
> Bitnami installation. This may take some time, please be patient.
> 
> [ THIS IS WHERE IT BROKE THE APACHE SERVICES / CONFIG]
> ```

God bless.

**Comment by unforced** [comment]
Ah glad I'm not the only one, any progress on this? I'm also having a hard time fixing this with the directions @markfaust123 used. I'm now on my third go of creating a new instance because I haven't known how to fix this. Was trying to migrate my domains one at a time to enable an easier transfer but ultimately made it sloppier lol.

**Comment by refishokga** [comment]
From my /opt/bitnami/conf/httpd.conf

I had to comment out:
IncludeOptional "/opt/bitnami/apache/conf/vhosts/*.conf"
Include "/opt/bitnami/apache/conf/bitnami/bitnami.conf"

**Comment by palmtown** [comment]
Hello Community,

I encountered the same issue described below. One of the domains I included in the certificate DNS hadn't updated, causing Bitnami to fail in handling the error. As a result, my site went down, and I couldn't restart it. However, by following the steps outlined below, I was able to restore my site.

As of today, August 24, 2024, this issue is still present.

> > The solution I found was to manually revoke the existing certificates: https://docs.bitnami.com/general/how-to/understand-bncert/#troubleshooting
> > Then restart the services:
> > ```
> > sudo /opt/bitnami/ctlscript.sh restart apache
> > sudo /opt/bitnami/ctlscript.sh rstart
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then re-run the bncert tool, making sure this time that all A records were correctly in place, first
> > ```
> > sudo /opt/bitnami/bncert-tool
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This issue appears to point to a defect in the error handling / rollback procedure when the bncert tool runs into an error when trying to install new certificates, after certificates are already in place. IE: The changes noted below
> > ```
> > ----------------------------------------------------------------------------
> > Changes to perform
> > 
> > The following changes will be performed to your Bitnami installation:
> > 
> > 1. Stop web server
> > 2. Configure web server to use a free Let's Encrypt certificate for the domains: 
> > snsevents.ca www.snsevents.ca sobernotsomber.ca www.sobernotsomber.ca
> > 3. Configure a cron job to automatically renew the certificate each month
> > 4. Configure web server name to: snsevents.ca
> > 5. Start web server once all changes have been performed
> > 
> > ----------------------------------------------------------------------------
> > Performing changes to your installation
> > 
> > The Bitnami HTTPS Configuration Tool will perform any necessary actions to your 
> > Bitnami installation. This may take some time, please be patient.
> > 
> > [ THIS IS WHERE IT BROKE THE APACHE SERVICES / CONFIG]
> > ```
> 
> God bless.

**Comment by realtebo** [comment]
Same problem today.
Tool found a problem when issueing a certificate -> left apache conf unusable.
We had a down in all installed app and must restore a snapshot 
Please ... introduce a fix to simply 'restore all' bitnami config

**Comment by squidge123** [comment]
I have had every single issue mentioned here. In addition when I restored a previous instance of Wordpress on Lightsail, although the site was coming up, my cert was showing as revoked. Re-running the tool made no difference and following the 'Manually revoking an existing certificate' instructions failed as well. Every time it stated it was already configured for the domain and that it would reuse - and it does (you end up exactly where you were) .. the only way to get it to work was to follow the 'manually revoke ..' instructions but also to rename certs/keys/etc in the following locations:

/opt/bitnami/apache/conf (cert & key files)
/opt/bitnami/letsencrypt/certificates (2 certs, 1 key, 1 JSON)

This forces creation of the certs and all working now. I just hope this helps someone out there - there are a lot of hours I will never get back!
The tool really should allow a full overwrite .. it seems it is too smart for it's own good!

**Comment by koder101** [comment]
I faced the same issue with AWS LightSail, wanted to add my findings and RCA to help others:

**Issue:** When you run `sudo /opt/bitnami/bncert-tool` you get the error:
```
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.
----------------------------------------------------------------------------
Bitnami installation directory
Please type a directory that contains a Bitnami installation. The default installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]: 

Warning: The web server configuration check failed. Please fix the configuration error: 
/bin/sh: 1: /opt/bitnami/apache/sbin/nginx: not found
```

**Observation-1:** The error message itself - "Warning: The web server configuration check failed. Please fix the configuration error". It's obvious that bncert tool is trying to check some existing configuration. 

**Observation-2:** At this point I checked the path `/opt/bitnami/apache/conf/vhosts/` and it contained the HTTPS configuration, however, when checked the content of the file, the path of the file `.crt` and the `.key` didn't exist for me. So essentially, I had a malformed HTTPS conf file.

**Solution:**
 - Remove the malformed HTTPS conf file.
 - Run: `sudo /opt/bitnami/bncert-tool`   <-- This time it should fix the issue.
 - Now the `.crt` and `.key` files should exist at: `/opt/bitnami/apache/conf`
 - Now create the HTTPS conf file with the correct path to the `.crt` and `.key` file and put it at: `/opt/bitnami/apache/conf/vhosts/`
 - Run `sudo /opt/bitnami/ctlscript.sh restart apache`

**Comment by ziggyjosh16** [comment]
Still occurring in July 2023.

**Comment by wsjim** [comment]
Still an issue in August 2025
