### ISSUE TITLE
[Mastodon] How to update vmware image from 4.0.2 to 4.1.0 with user data

### ISSUE THREAD

**Issue by dice10240** [bitnami/vms#699]
### Describe your issue as much as you can

Hello folks. I need your help. 

I have been using Mastodon vmware image that runs version 4.0.2. ( detailed version is Version 4.0.2-19-r23 )
Few days ago, you have released 4.1.0. 
I would like to upgrade environment with user data.

There are few article on docs page.
I assumed that I need to do what "Create And Restore Application Backups" tells.
Is this correct? Or is there other update step?

Thanks and regards

**Comment by jotamartos** [comment]
That guide helps you move the current deployment to a new server, but it doesn't upgrade the app. I suggest you take a look at the official documentation to know how to migrate the data of your current deployment to a new instance you launch in VMware cloud. Please note that paths may be different but you can find all the files inside the /opt/bitnami/ and /bitnami folders.

Thanks
