### ISSUE TITLE
[Wordpress] To perform the requested action, WordPress needs to access your web server. 

### ISSUE THREAD

**Issue by kjuluru** [bitnami/vms#70]
I have an AWS LightSail LAMP instance (not pre-installed with Wordpress). I've installed Wordpress on my own and I have it working. From the admin page, I'm trying to install a new theme, and I'm getting this message:

"To perform the requested action, WordPress needs to access your web server." It is asking for my FTP credentials.

I have following the instructions here:
https://community.bitnami.com/t/to-perform-the-requested-action-wordpress-needs-to-access-your-web-server-please-enter-your-ftp-credentials-to-proceed/92426

My wp-config.php file now contains the line: 
define( ‘FS_METHOD’, ‘direct’);

My Wordpress site is installed in a 'Wordpress' directory. Here are the permissions:
drwxrwxr-x 5 bitnami bitnami     4096 Jul  3 18:23 wordpress

Despite refreshing my browser, logging out/in, WordPress continues to ask for my FTP credentials.

Please help me resolve this issue.

**Comment by jotamartos** [comment]
> I ran this command:
> sudo chown -R bitnami:daemon /opt/bitnami/apache2/htdocs

You also need to run the `chmod` command using that path to grant daemon write permissions in the files and folders.

**Comment by kjuluru** [comment]
Thank you so much again for your help. I've done everything you said, and still Wordpress is asking for the FTP credentials. I'm new to all this, and doing the best I can do understand. 

Here are the current permissions. 

bitnami@ip-{I am hiding this}:~$ ls -l
total 12
-rw------- 1 bitnami bitnami   13 Jul  3 17:47 bitnami_application_password
-r-------- 1 bitnami bitnami  401 Jul  3 17:47 bitnami_credentials
lrwxrwxrwx 1 bitnami daemon    27 Apr 19 14:19 htdocs -> /opt/bitnami/apache2/htdocs
drwxr-xr-x 3 bitnami bitnami 4096 Jun 22 16:38 projects
lrwxrwxrwx 1 bitnami bitnami   12 Apr 19 14:19 stack -> /opt/bitnami

bitnami@ip-{I am hiding this}:~/htdocs$ ls -l
total 20688
-rw-rw-r-- 1 bitnami daemon      410 Jun 23 21:24 index.html
-rw-rw-r-- 1 bitnami daemon      417 Jul  3 18:26 index.php
-rw-rw-r-- 1 bitnami daemon 21166276 May 24 19:03 latest.tar.gz
drwxrwxr-x 2 bitnami daemon     4096 Jun 23 21:24 nuclear-cardiology
drwxrwxr-x 5 bitnami daemon     4096 Jul  4 22:22 wordpress

**Comment by jotamartos** [comment]
Please run the Bitnami Diagnostic tool to review the permissions configuration of your instance 

https://docs.bitnami.com/aws/how-to/understand-bndiagnostic/

**Comment by kjuluru** [comment]
I ran the tool. Here's the code it provided:
13f3662a-2cbe-8192-f0b6-ba215c7ed451

**Comment by kjuluru** [comment]
Hi @jotamartos, I hope I ran the tool correctly?

**Comment by jotamartos** [comment]
Hi @kjuluru,

The permissions configuration allow the daemon group to read/write in the WordPress' files and folders (Apache uses the daemon user/group to run )

```
apache/htdocs/wordpress:
total 224
drwxrwxr-x  5 bitnami daemon  4096 Jul  4 22:22 .
drwxrwxr-x  4 bitnami daemon  4096 Jul  3 18:37 ..
-rw-rw-r--  1 bitnami daemon   405 Feb  6  2020 index.php
-rw-rw-r--  1 bitnami daemon 19915 Jan  1  2022 license.txt
-rw-rw-r--  1 bitnami daemon  7401 Mar 22 21:11 readme.html
-rw-rw-r--  1 bitnami daemon  7165 Jan 21  2021 wp-activate.php
drwxrwxr-x  9 bitnami daemon  4096 May 24 19:02 wp-admin
-rw-rw-r--  1 bitnami daemon   351 Feb  6  2020 wp-blog-header.php
-rw-rw-r--  1 bitnami daemon  2338 Nov  9  2021 wp-comments-post.php
-rw-rw-r--  1 bitnami daemon  3231 Jul  3 20:08 wp-config.php
-rw-rw-r--  1 bitnami daemon  3001 Dec 14  2021 wp-config-sample.php
drwxrwxr-x  5 bitnami daemon  4096 Jul  5 14:05 wp-content
-rw-rw-r--  1 bitnami daemon  3943 Apr 28 09:49 wp-cron.php
drwxrwxr-x 26 bitnami daemon 12288 May 24 19:02 wp-includes
-rw-rw-r--  1 bitnami daemon  2494 Mar 19 20:31 wp-links-opml.php
-rw-rw-r--  1 bitnami daemon  3973 Apr 12 01:47 wp-load.php
-rw-rw-r--  1 bitnami daemon 48498 Apr 29 14:36 wp-login.php
-rw-rw-r--  1 bitnami daemon  8577 Mar 22 16:25 wp-mail.php
-rw-rw-r--  1 bitnami daemon 23706 Apr 12 09:26 wp-settings.php
-rw-rw-r--  1 bitnami daemon 32051 Apr 11 11:42 wp-signup.php
-rw-rw-r--  1 bitnami daemon  4748 Apr 11 11:42 wp-trackback.php
-rw-rw-r--  1 bitnami daemon  3236 Jun  8  2020 xmlrpc.php
```

However, as the tool warned you, there are many WordPress-related errors in the Apache's log 

```
[Tue Jul 05 14:11:30.814134 2022] [proxy_fcgi:error] [pid 25141:tid 140162046433024] [client 69.115.176.159:59287] AH01071: Got error 'PHP message: PHP Warning:  Use of undefined constant                                   \xe2\x80\x98FS_METHOD\xe2\x80\x99 - assumed '\xe2\x80\x98FS_METHOD\xe2\x80\x99' (this will throw an Error in a future version of PHP) in /opt/bitnami/apache/htdocs/wordpress/wp-config.php on line 21PHP message: PHP        Warning:  Use of undefined constant \xe2\x80\x98direct\xe2\x80\x99 - assumed '\xe2\x80\x98direct\xe2\x80\x99' (this will throw an Error in a future version of PHP) in /opt/bitnami/apache/htdocs/wordpress/wp-config.php on  line 21', referer: https://radcentralstation.com/wordpress/wp-admin/theme-install.php?browse=popular
```

There is an error in the wp-config.php file and you should fix it before using the app. Please check with the WordPress' support team about this error.
