### ISSUE TITLE
[WordPress Multisite] OVA file an older version of Bitnami WordPress Multisite

### ISSUE THREAD

**Issue by aortega-77** [bitnami/vms#700]
### Describe your issue as much as you can

Hi I'm trying to see if its possible to download the OVA file Bitnami WordPress Multi-Site that contains WordPress version 5.1.15. I have a project that I'm trying to test but it requires an older version of Bitnami. Thank you in advance .

**Comment by jotamartos** [comment]
Hi @aortega-77,

That version of WordPress is not available for download.

Sorry for the inconvenience.
