### ISSUE TITLE
[Bitmani/admin login] <URL http://SERVER-IP/wp-admin con't be found>

### ISSUE THREAD

**Issue by engga86** [bitnami/vms#701]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

.

### bndiagnostic was not useful. Could you please tell us why?

.

### Describe your issue as much as you can

our page can't be found anymore, tried to log in to admin but the admin page can't be found as well (404 error)
We were able to log in a few weeks ago.

**Comment by gongomgra** [comment]
Hi @engga86,

Thanks for using Bitnami. Can you please run the bndiagnostic tool and paste here the outputted code? It will help you to identify common issues with WordPress, Apache or the database, and we would also be able to take a closer look to the Apache logs.
