### ISSUE TITLE
[bitnami/kubernetes/Odoo] bitnami odoo packaged kubernetes & docker is taking the old version 16.0.20221115

### ISSUE THREAD

**Issue by tedcity** [bitnami/vms#702]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

not relevant

### bndiagnostic output

not relevant

### bndiagnostic was not useful. Could you please tell us why?

not relevant

### Describe your issue as much as you can

In the Odoo packages by Bitnami kubernetes, (https://bitnami.com/stack/odoo/helm), the version is always "16.0.20221115" for the past 3 months (there were many times it was updated, but the version is not increased). 

If you refer to the odoo nightly (i.e. https://nightly.odoo.com/16.0/nightly/), new version is being release and compile daily 

May I know if there is some issue with the bitnami kubernetes odoo update which it stay at the version dated 2022-11-15 (version 16.0.20221115 was dated 15 Nov 2022). 

Not sure if you could have that updated to the latest version, and also if you could share with us how do compile that will be helpful also. 

thanks!!

**Comment by gongomgra** [comment]
Hi @tedcity,

Thanks for your interest in using Bitnami. We detected a more recent version of Odoo 16.x branch, but some verifications failed in our automated pipelines. The team is working on it.

Apart from the above, please note this forum is for questions related to our cloud images and virtual-machines. However, it looks like you are more interested in the Docker image and the Helm chart. There is an issue already open for this in our containers forum. Our team will add a message there once the issues are solved and the solution is updated. Please check the thread linked below for further updates on this.

https://github.com/bitnami/containers/issues/22877

**Comment by mdhont** [comment]
Odoo version 16.0.20230315 has been released. Closing this issue.
