### ISSUE TITLE
[Redmine] How to migrate from Redmine V3.4.5-0 Windows Server to Redmine VM 

### ISSUE THREAD

**Issue by mohamedmamdouh1** [bitnami/vms#703]
### Describe your issue as much as you can

Hi experts.

I'm looking for previous versions of the Redmine by Bitnami
I'd like to migrate redmine 3..4.5-05 on windows, installed with the bitnami installer to Redmine VM

Thanks in advance

**Comment by mdhont** [comment]
Unfortunately that version is too old. We only have Redmine starting from version 4.

**Comment by MarcinBDA** [comment]
How to migrate from 4.2.3 to 5.0.4 ?

**Comment by mohamedmamdouh1** [comment]
Ok, the situation is: the current installed version on my Windows Server is 3.4.5-0 and I need to upgrade to the latest version and move to Virtual Machine simultaneously without losing my database and smoothly migrate all the data, any advice how that can be done?

**Comment by mdhont** [comment]
I recommend asking in the official Redmine forum:

https://www.redmine.org/boards/2/topics/51439
