### ISSUE TITLE
[Bitnami] <all administrators locked out>

### ISSUE THREAD

**Issue by Martinfd168** [bitnami/vms#706]
### Describe your issue as much as you can

We have a  bitnami/ moodle site that was running perfectly  on aws and then we enabled self-enrolment and now we (there are a couple of us who are administrators) cannot log in - neither as normal nor via bitnami user/ password as per provided (we checked using the cli)  - stopped and restarted all services but still cannot log in - one of our testers can log in as a 'student' but not as admin. . neither the self enrolment nor the self registration work either

**Comment by gongomgra** [comment]
Hi @Martinfd168,

Thanks for using Bitnami. Can you run the bndiagnostic tool and share the generated code with us so we can take a look at the Apache log files?

https://docs.bitnami.com/general/how-to/understand-bndiagnostic/

Additionally, we recommend you to open a new question in the official Moodle forums in case there is any known-issue in the latest Moodle version related to that feature and how to solve it.

https://moodle.org/mod/forum/index.php?id=5

**Comment by Martinfd168** [comment]
hello gongomgra,
thank you for your response - i have done as you said and the code is 

c045b51a-766e-efe0-90f8-7280ec6b029b

i look forward to your response 
warm regards,
Martin

**Comment by gongomgra** [comment]
Hi @Martinfd168,

Thanks for sharing the bndiagnostic bundle with us. According to the Apache logs the login to your Moodle site is disabled. Please open a new ticket in Moodle's official forums, as it looks like there is some wrong configuration on your site.

```
[Wed Feb 22 16:22:22.553978 2023] [proxy_fcgi:error] [pid 13967:tid 139997889824512] [client _IP_ADDRESS_:35318] AH01071: Got error 'PHP message: [client _IP_ADDRESS_]  http://_YOUR_DOMAIN_.org  Disabled Login:  _USERNAME_  _REDACTED_USER_AGENT_', referer: http://_YOUR_DOMAIN_.org/login/index.php
```

**Comment by Martinfd168** [comment]
Dear gongomgra,
Thank you for your response .
We did as you suggested and we tried all the fixes that were suggested on the moodle forum but none of them worked and the general consensus seems to be that it is indeed a bitnami issues - 
We have Moodle working perfectly on a non aws cloud provider, and when we move the moodle version to bitanmi aws  it also works frne - until we turin on the self-registration / self enrolment  . We went back and tunred o nthe self enrollment on the dev environment and that works perfectly.   
I have copied two links for your here  .
Let me explain - we restored a back up copy (from the 1st of Feb ) which works perfectly and then we changed the enrollment and it broke . - we  then ran the bitanmi diiagnostics tool  which is linked here 
We then restored same back up copy and checked it worked perfectly and the we ran the bitnami diagnostics tool and we have also saved the link her - we hope that by checking the two files and comparing that you can see whet the error is that is causing the problem and educate us on what is the solution 

This is the code for the 'broken' version 
892e355b-9dd8-5186-d1ac-6840076722e5


This is the code for the - un-broken version 

f7dfe19b-cbf2-ead6-8229-57d48f831872


I hope this is of godd help to you in assisiting us to respolve the issues - 

Thank you again and warm regards,
Martin

**Comment by gongomgra** [comment]
Hi @Martinfd168,

I'm afraid I couldn't reproduce your issue in any of our 4.x nor 5.x series images. I launched a fresh new Moodle server for each of them, and enabled the `email-based self-registration` option as shown in the screenshot below 

![Screen Shot 2023-03-08 at 12 09 09](https://user-images.githubusercontent.com/6660452/223697893-5fc2bbc6-38a9-44cb-b95e-0011c17dded3.png)

After saving the changes and restarting the services (just in case), I was able to register two new alumns (`alumn@example.com`, `other@another-domain.com`) with custom passwords. Finally, I confirmed both subscriptions using the original admin user, and after that I can login with all the three users using either their usernames or their email addresses.

Can you try the latest images? Can you also share the thread in the Moodle community?

**Comment by gongomgra** [comment]
Hi @Martinfd168,

Please find my comments in-line

> yes have looked at moodle threads and tried various of the suggestions that work for other but do not work for this problem - have posted threads in a couple of places and generally responses are along the lines of 'the problem is another example of why we recomend people NOT to use Bitnami and such like - (but that is the problem sometimes on froums - people can be very pure-ist)

We don't perform any customization on top of the vanilla Moodle application we download from official sources. We just deploy it on top of Apache, configure it with the required credentials and database settings, and that's it. Please, insist a bit on this to the upstream developers.

> we have what we call a 'dev' site of moodle running on a non-bitnami- non-aws platform (managed by greengeeks) and we do not get these problems on that site - hence we felt we were issolating it down to bitnami

Do you know if you are using the very same version of Apache, PHP and MySQL in your other environment?

> we have considered an upgrade (its what the likes of IBM always suggest - i.e. upgrade and that will fix the problem ) and we have backups but we cannot find documentation on how to upgrade bitnami / moodle on the AWS marketplace - all it shows is launcing a new instance and even then it indicates that the version on aws marketplace may not be your latest version - so if you have place / link where we can go to download the upgrade then we will be very pleased to do that -and hen i say easy what i mean is that backing up the content is easy but restoring the content is not so easy as i have to go in and find the php files and increase the file size limit and only then can i restore the content - and my bash / linux skills are limited and so istruggle.

As we don't perform any modification to Moodle's code, you should be able to migrate your application data following the steps in the official documentation from Moodle developers. I understand you would have to go through at least the following guides, but we recommend you to also ask in the official forums just in case

* [Site backup](https://docs.moodle.org/401/en/Site_backup)
* [Site restore](https://docs.moodle.org/401/en/Site_restore)

Regarding the Moodle version in the AWS marketplace, it is true that there must be a small delay between the solution is published and the marketplace is updated by the AWS team, but you can always launch the latest image from the AWS console with the community image's ID you can find [in our website](https://bitnami.com/stack/moodle/cloud/aws/amis). Alternativelly, you can check it locally using our virtual-machine solution, which includes the same versions than cloud images.

> we also wondered if it may be an SMTP gateway issue - so i am interested in learning what settings you have put in and whether we need to set up any keys and or AWS SES ?

Not sure about this. As I used "non-real" email addresses (`@example.com` and `another-domain.com`), I had to confirm the new users subscription using the `user` admin account, but I can't tell if that has something to do with the issue or not. I don't think SMTP is an issue here. Can you try to reproduce my steps in our latest Moodle image?
