### ISSUE TITLE
WordPress- ip to domain redirect not working now

### ISSUE THREAD

**Issue by Imthiyasvm** [bitnami/vms#707]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0c2b2114-8fad-06b6-b286-76b61d849520

### bndiagnostic output

sudo nano /opt/bitnami/apache/conf/bitnami/bitnami.conf

 <VirtualHost _default_:443>
 not showing in new ui

### bndiagnostic was not useful. Could you please tell us why?

documentation is incorrect

### Describe your issue as much as you can

sudo nano /opt/bitnami/apache/conf/bitnami/bitnami.conf

 <VirtualHost _default_:443>
 not showing in new ui
![aws](https://user-images.githubusercontent.com/126055525/220556912-9c7ee02d-d76c-46f4-8696-6d2cbfe653c8.png)

**Comment by gongomgra** [comment]
Hi @Imthiyasvm,

Thanks for using Bitnami. I tested a connection with your IP address using the `curl` tool and the redirection worked for me. Did you manage to solve your issue?

```
$ curl -LI "43.IP_ADDRESS.156"
HTTP/1.1 301 Moved Permanently
Date: Thu, 23 Feb 2023 08:49:19 GMT
Server: Apache
Location: https://YOUR_DOMAIN_HERE/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
```

**Comment by Imthiyasvm** [comment]
@gongomgra 
yes,
I solved the issue
