### ISSUE TITLE
[WordPress] Files rendered with IP address instead of domain.

### ISSUE THREAD

**Issue by thomasazz** [bitnami/vms#708]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

dcac5dab-f77c-ab9a-252d-f2a3049b176a

### bndiagnostic output

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

There is no mention of the problem that I have

### Describe your issue as much as you can

The AWS Bitnami wordpress instance runs on a EC2 instance behind an ALB with the development subdomain https://wpml.azzgency.com being used behind an IP whitelist. The problem I have is that frequently wp-content files are rendered not with the subdomain, but with the private IP address:

Example:
background-image: url("https://172.31.41.94/wp-content/uploads/2023/02/home-banner-bg.jpeg");

As a result, the image is not rendered after waiting for up to 30 seconds to load.

The only way to fix this is to make go to Elementor and Regenerate CSS & Data. I cannot find any cases similar to this where WordPress uses the private key instead of domain.

Thanks

**Comment by gongomgra** [comment]
Hi @thomasazz,

Thanks for using Bitnami. I checked the bndiagnostic bundle and I saw you don't have your domain configured in `wp-config.php`. Can you check if configuring the domain name using `https://` solves the issue?

https://docs.bitnami.com/aws/apps/wordpress/administration/configure-domain/

**Comment by thomasazz** [comment]
Hi Gonzalo,

That has done the trick! Many thanks!

**Comment by gongomgra** [comment]
Hi @thomasazz,

Thanks for your message. Glad it worked for you!
