### ISSUE TITLE
[Joomla4] Proper way to create a multi-site Joomla Host

### ISSUE THREAD

**Issue by BtrieveBill** [bitnami/vms#709]
### Describe your issue as much as you can

I am currently running a Bitnami install of WAMP/Joomla3, where I have a single Win2012 web server handling multiple domains.  In that environment, we created separate folders inside the \wamp\apache2\htdocs folder (one for each site) and then copied the Joomla installation files into the folder.  After that, we created vhost definitions so that Apache could find each folder.  (Not exactly sure what else was done, but that's all I can recall.)

I now have the "new" Bitnami LAMP stack for Joomla 4 (on debian) and am trying to recreate the same thing, but I am a bit confused on how it all fits together.  When I look at the Apache configuration, I can see that the default web site appears to be in /opt/bitnami/apache/htdocs, but that folder contains only ONE file (index.html), and it does NOT contain the Joomla files.  Instead, the Joomla files are located in the folder /opt/bitnami/joomla.  Further, because it is pre-configured, I'm not sure that copying these files somewhere is the "right" way to duplicate the configuration and spin up a second domain on the same server.

Does anyone know of a guide or step-by-step instructions to setting this up (correctly)?

**Comment by gongomgra** [comment]
Hi @BtrieveBill,

Thanks for using Bitnami. The Apache configuration for the Joomla application is located under the `/opt/bitnami/apache/conf/vhosts` directory. You can place your custom files for the additional Joomla sites as described in the guide linked below

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

You can deploy the official Joomla files for your new site under the `/opt/bitnami/your-second-site` folder (as described in the guide above), and then configure the site.

**Comment by BtrieveBill** [comment]
Thanks, @gongomgra.  That is not the title I would have expected to look for such a result.

In the last 24 hours, I have done a LOT of research and digging, and a LOT of trial and error.  Because of that, I'll post what I have found here -- maybe it will save someone many hours of their own efforts collecting data from all over the web:

To set up a new Web Site (XXX) on this Server:
- Create a folder in /bitnami directory called joomla-XXX and populate it with the base install.
	cd /bitnami
	sudu mkdir joomla-XXX
	[Go to https://downloads.joomla.org/cms/joomla4 and determine the latest installer file]
	sudo wget https://downloads.joomla.org/cms/joomla4/4-2-8/Joomla_4-2-8-Stable-Full_Package.zip
	sudo unzip Joomla_4-2-8-Stable-Full_Package.zip -d /bitnami/joomla-XXX
	sudo chown -R bitnami:daemon /bitnami/joomla-XXX
	sudo chmod -R g+w /bitnami/joomla-XXX

- Create the MariaDB Database for the new web site
	sudo mysql -u root -p
	[Enter System Global Password]
	CREATE DATABASE joomlaXXX;
	GRANT GRANT ALL PRIVILEGES ON joomlaXXX.* TO 'joomla'@'localhost' IDENTIFIED BY 'somepassword';
	FLUSH PRIVILEGES;
	EXIT;

- Create a SymLink for the OPT directory (Not sure if this is required, but it mirrors other installs)
	cd /opt/bitnami
	sudo ln -s /bitnami/joomla-XXX joomla-XXX

- Set up Apache for the virtual name
	cd /opt/bitnami/apache/conf/vhosts
	sudo touch www.XXX.com.conf
	sudo nano www.XXX.com.conf
	[Here is the data that I used - much was copied from my older WAMP install, and this may or may not be current or correct]
<VirtualHost *:80>
    ServerAdmin admin@XXX.com
    DocumentRoot "/opt/bitnami/joomla-XXX"
    ServerName myhost
    ServerAlias www.XXX.com test.XXX.com [extend as needed]
    <Directory "/opt/bitnami/joomla-XXX">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog /opt/bitnami/apache/logs/XXX-error.log
    CustomLog /opt/bitnami/apache/logs/XXX-access.log combined
    RewriteEngine ON
    RewriteOptions Inherit
</VirtualHost>

	If you are still in a testing mode, then you can update the HOSTS entry on the workstation to link it to the new server, e.g.:
		192.168.xxx.yyy   test.XXX.com
    Otherwise, simply point DNS as needed to the new server.

- Restart the Bitnami Stack to get all changes to take effect
	sudo /opt/bitnami/ctlscript.sh restart
	Or just restart Apache with:
	sudo /opt/bitnami/ctlscript.sh restart apache

- You can now open the browser to the new site, which should launch the install/config page of Joomla.  When you get to the database section, be sure to enter the name of the database you just created (above) and its proper password.

**Comment by BtrieveBill** [comment]
Well, sorry folks -- apparently, copying & pasting text into this dialog completely mangles the formatting.  Why did I spend so much time making sure it looked pretty, when the system was going to mangle it for me anyway?  Reformat as needed.

**Comment by gongomgra** [comment]
Hi @BtrieveBill,

Thanks for your message and for sharing your solution. I updated the syntax highlight to make it more readable. I'm also closing the ticket as solved.
