### ISSUE TITLE
[Wordpress] Connection was reset

### ISSUE THREAD

**Issue by InfiniteArts** [bitnami/vms#71]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0a57bdf7-557c-bbe6-fd25-e81cdf168616

### bndiagnostic output

The files listed below are bigger than 10MB and have not been included, please notify the support agent.

C:/Bitnami/wordpress-5.9.3-1/apache2/logs/error.log

### bndiagnostic was not useful. Could you please tell us why?

I do not understand

### Describe your issue as much as you can

Local installation of Wordpress is getting 'Connection was reset' when trying to load Elementor on a page for editing

**Comment by mdhont** [comment]
It seems related to a lack of available resources. Did you check the available RAM and disk space? You could also try to increase the PHP memory_limit:

https://docs.bitnami.com/ibm/apps/wordpress-pro/configuration/configure-phpfpm-options/
