### ISSUE TITLE
[XAMPP] <8.1.5-0>

### ISSUE THREAD

**Issue by DimitrovaS** [bitnami/vms#710]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

[XAMPP] <8.1.5-0>

### bndiagnostic was not useful. Could you please tell us why?

I just need info about the app

### Describe your issue as much as you can

 What is the latest version of the application? 
2. When was the release date for the latest version of this application? 
3. When was the release date for version 8.1.5-0 of this application? 
4. Are there any known identified security vulnerabilities for the latest version of this application?
5. Are there any known identified security vulnerabilities for version 8.1.5-0 of this application? 
6. Is version 8.1.5-0 still supported (will receive updates, security or otherwise)?
7. Are there any plans to discontinue this application (End-of-Life)?

**Comment by gongomgra** [comment]
Hi @DimitrovaS,

Thanks for your message. According to your ticket information, you are asking for the [XAMPP installers](https://www.apachefriends.org), which are no longer maintained by Bitnami. You can get more information about this in the blogpost linked below

https://www.apachefriends.org/blog/moves_to_github_20220610.html

In case you are referring to our LAMP, WAMP, MAMP products, we deprecated the local installers to focus on our cloud native solutions (virtual-machines, cloud images, containers, helm charts). You can get more information about this in the next link 

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

PHP 8.1.5 is an old version of the 8.1.x series (our current released version for the [container](https://github.com/bitnami/containers/tree/main/bitnami/php-fpm) and the [virtual machine](https://bitnami.com/stack/lamp/virtual-machine) is 8.1.16). We recommend you to migrate your development environment to our virtual-machine or container solutions, as previous versions won't receive any security update.
