### ISSUE TITLE
Wordpress Google Cloud, Can not update plugins always get maintenance -1 error

### ISSUE THREAD

**Issue by FeedArmy** [bitnami/vms#714]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

76b6c029-478d-cbb5-7603-580f1790fa30

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Php: No issues found
    ? Nginx: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Processes: No issues found
    ? Resources: Found possible issues
    ✓ Mariadb: No issues found
    ? Wordpress: Found possible issues
 

 
[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2023/02/25 06:31:36 [error] 2881#2881: *5408591 access forbidden by rule, 
client: **ip_address**, server: _, request: "GET /.git/config HTTP/1.1", host: 
"35.199.51.45"
 2023/02/25 06:31:36 [error] 2879#2879: *5408592 access forbidden by rule, 
client: **ip_address**, server: _, request: "GET /.git/config HTTP/1.1", host: 
Press [Enter] to continue:
"35.199.51.45"
 2023/02/25 06:37:20 [error] 2881#2881: *5408689 access forbidden by rule, 
client: **ip_address**, server: _, request: "GET /.env HTTP/1.1", host: 
"35.199.51.45"

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 16011 9322 803 192 5885 6166 
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
Press [Enter] to continue:
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Wordpress]

Found recent WordPress plugin related error messages in the Nginx error log.
```
2023/02/25 02:44:30 [error] 2880#2880: *5404973 FastCGI sent in stderr: "Primary 
script unknown" while reading response header from upstream, client: 
**ip_address**, server: _, request: "GET 
/plugins/content/apismtp/apismtp.php?test=hello HTTP/1.1", upstream: 
"fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "feedarmy.com"

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I don't know what to do

### Describe your issue as much as you can

When I update the plugin, it instantly shows -1 maintenance mode.

Upon this, I must manually delete the .maintenance file to get the site working again.

However, the plugin does not update.

**Comment by mdhont** [comment]
I recommend asking the plugin developers regarding this error. It does not seem related to the app's configuration.

**Comment by FeedArmy** [comment]
The issue is not specific to a plugin, it also happens when I install a new different plugin. Instantly returns a -1 maintenance mode

**Comment by mdhont** [comment]
Can you provide me with the exact steps to reproduce the issue?

**Comment by FeedArmy** [comment]
Hello Mdhont, thank you for the continued support. 

I have created a video where I demonstrate installing a new app, and update a plugin, with the same error.
https://youtu.be/ijQqfAkQGLg

**Comment by mdhont** [comment]
I haven't been able to reproduce this with a new instance of Bitnami WordPress Nginx on GCE. Did you make any changes to the configuration?

**Comment by FeedArmy** [comment]
I have another site on the same setup, and no issues.

No, I did not change anything prior to this, only after the issue, I change the folders and files to bitnami:daemon so that I can manually upload updates for plugins.

I guess I have to setup a new server.

**Comment by mdhont** [comment]
Please note that you can also try to reset the WP permissions:

```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress/wp-content
sudo find /opt/bitnami/wordpress/wp-content -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress/wp-content -type f -exec chmod 664 {} \;
sudo chmod 640 /opt/bitnami/wordpress/wp-content/wp-config.php
```

**Comment by FeedArmy** [comment]
Unfortunately, that did not work. Same issue.

**Comment by FeedArmy** [comment]
Issue is now resolved, while setting up a new server, I tested it and had the same issue, so it must have been a plugin.
I disabled all plugins and found one plugin developed by brainstormforce.com causing the issue.

I want to thank you for the continued support.
