### ISSUE TITLE
[Guacamole] 1.5.0 not working properly yet - where can i download lates 1.4.0 releases?

### ISSUE THREAD

**Issue by mfatfhg** [bitnami/vms#715]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

NA

### bndiagnostic output

bitnami@debian:~$ /opt/bitnami/bndiagnostic-tool
----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

/\Error copying file from /opt/bitnami/tomcat/logs/catalina.2023-02-27.log to /tmp/bndiagnostic-f31bdaaeb79ca459/bitnami-guacamole-info-20230227-105922-1109/apache-tomcat/logs
:/opt/bitnami/tomcat/logs/catalina.2023-02-27.log is not readable
Abort, Retry, Ignore ? [A/r/i]

### bndiagnostic was not useful. Could you please tell us why?

See output

### Describe your issue as much as you can

Hi,

i downloaded lates 1.5.0 releases (r01 and r02 are available yet, but not working*).

Where can i download the latest 1.4.0 release? Is there a archive of older bitnami VMs avaiable?  Seems to be Version 1.4.0-82-r54      2023-02-18

*Issues:
- No Setup wizzar during OVA deployment process in vSphere 7 where i can acceps licences, setup IP, ssh etc.
- after configuring those things manuall over console leads into non working https://ip/administration (cant login with guacadmin, but the reason could be that i missed something during manual setup)

**Comment by mfatfhg** [comment]
Never mind, i can login now. 

Question remains: Where can I download old versions?

**Comment by mfatfhg** [comment]
I'm trying to get guacamole 1.5.0 r02 running in the meantime. 

I have a Ubuntu 22.04 Test VM running and i can access it via RDP and VNC from my workstation. But i can not get a connection from guacamole.

I get the error "An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs." and I dont know why.

**Comment by jotamartos** [comment]
Hi @mfatfhg,

You can download 1.4.0-82-r54 from [here](https://downloads.bitnami.com/files/stacks/guacamole/1.4.0-82/bitnami-guacamole-1.4.0-82-r54-linux-vm-debian-11-x86_64-nami.ova).

Regarding the errors you are getting, we tested the VMs before releasing them and they all passed the tests and the deployment succeeded. Please ensure your machine have enough RAM memory to host the VM and configure a correct amount of memory for the VM to run.
