### ISSUE TITLE
[<Joomla 4>] <error in every position of every template>

### ISSUE THREAD

**Issue by jkfuerte** [bitnami/vms#716]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

326f6364-f9bb-8d1f-0a0a-e7bd3f2acbdf

### bndiagnostic was not useful. Could you please tell us why?

it could be something about Joomla 4

### Describe your issue as much as you can

Hi, I just starting to use Joomla 4 and gk_magazine template, it returns me the error code referring a gk_style.php as stated in attached photo, could you please help me to understand what is going on? Even using the standard Cassiopea template it happens to...
![error_gk_style php](https://user-images.githubusercontent.com/38348016/221599239-fd54fa06-e3ef-49f4-b72c-f1537a9b50e9.png)

**Comment by jkfuerte** [comment]
![bitnami_error_1](https://user-images.githubusercontent.com/38348016/221606026-ca959aa2-680b-4d60-bd73-de3f90526a00.png)

**Comment by mdhont** [comment]
Can you share the exact steps needed to reproduce the issue?

**Comment by jkfuerte** [comment]
Hi, I just verify that something had to happened with that template, gk_magazine for Joomla 4. Probably something has changed from first releases of Joomla 4 and the actual one, something about styles declarations or something like that. Please, close this issue, it has nothing to do with Bitnami, it is something new in the CMS. Thank you very much and sorry for this.
