### ISSUE TITLE
[Joomla] Bitnami bncert tool: How to configure SSL with inbound port forwarding?

### ISSUE THREAD

**Issue by BtrieveBill** [bitnami/vms#718]
### Describe your issue as much as you can

I have configured a Joomla/Bitnami/Debian server and have everything working as expected now.  I have enabled SSL support with the built-in certificate, but wish to avoid the "self-signed" certificate error that most browsers post now.

I have used LetsEncyrpt on Windows on a different server with no issues, but this is my first attempt on this Bitnami install.  When I run the bncert-tool application, I get prompted for the domain(s).  Since I am currently hosting three separate public domains, I enter all three of them (in both forms) as "www.sigeps.org sigeps.org www.christielakemi.org christielakemi.org www.camgolfinc.com camgolfinc.com".

I then get a warning back: Warning: The domain 'www.sigeps.org' resolves to a different IP address than the one detected for this machine, which is '96.68.57.149'. Please fix its DNS entries or remove it.

So, why does this pop up?  All of these domains resolve to the same IP address: 96.68.57.147.  Traffic to this public IP address is received by my firewall and forwarded (for ports 80/443) to the internal server, specifically 192.168.5.8.  However, when any of my internal servers make an outbound request, the packets go out on for NAT address from my firewall, or 96.68.57.149.  I have to assume that bncert-tool is somehow confirming that these addresses match.  While they might match for a true public=facing server, they should NOT match when protected by a proper firewall!  (Again, I had no such issue when I deployed LE on my Windows host.)

I have to imagine that others have a similar config, no?  If so, how do I get around this issue?

**Comment by marcosbc** [comment]
Hi @BtrieveBill, you might find these CLI options useful:

* `--perform_public_ip_validation 0`: Do not perform public IP validation.
* `--perform_dns_validation 0`: Do not perform DNS validation.

Please keep in mind that if you specify those options, it will be up to Let's Encrypt whether your configuration will be considered valid (or not). And unfortunately we cannot be of much help there if it does not work.

**Comment by BtrieveBill** [comment]
Thank you for the assist!  None of the web guides I saw talked about the options for bncert-tool, but disabling the public IP address validation was sufficient to get past this, and it is has been able to complete the process just fine.  You're awesome!
