### ISSUE TITLE
[WordPress] How to prevent video download

### ISSUE THREAD

**Issue by ogbetaeric** [bitnami/vms#719]
### Describe your issue as much as you can

Good day,

hope you are good.

How  do I prevent hotlinking and videos download on aws lightsail instance from the backend. I discovered my videos are been downloaded.

I used plugins, still my videos is still expose for downloading with browser media detector or extension.

This has lower performance on my Wordpress site and increase cost.

Waiting to hear from you soon.

Best regards,
OGBETA.

**Comment by jotamartos** [comment]
Hi @ogbetaeric,

Thank you for using Bitnami. That question is out of the scope of this support forum. Please contact the WordPress' support team to get more information and know the different possibilities you have to achieve that. 

Thanks

**Comment by ogbetaeric** [comment]
Ok, Thanks for that.

best regards,
Ogbeta.
