### ISSUE TITLE
[wordpress]Using Bitnami Wordpress EC2 Package AWS

### ISSUE THREAD

**Issue by mk336** [bitnami/vms#72]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

6956729e-8451-9fd3-6b83-04051fa813ef

### bndiagnostic output

==== Begin of bndiagnostic tool output =====

    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

The Apache configuration has errors:
```
AH00526: Syntax error on line 5 of
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
file '/opt/bitnami/apache/conf/laptoprepairingmumbai.com.crt' does not exist or
is empty
```
Press [Enter] to continue:
Please check the configuration.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 987 342 62 7 581 488 Swap:
1658 0 1658
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

### bndiagnostic was not useful. Could you please tell us why?

your cert removal doc not useful for need easy steps.

### Describe your issue as much as you can

Hi Team,
I hosted the website to another IP, i just want my content back. so please let me know how to active the previous IP. Dont know why the issue comes without doing any upgradation init.

Let me know the solution, aslo your cert removal doc not useful for need easy steps.

**Comment by jotamartos** [comment]
Unless you [configured a static IP address](https://docs.bitnami.com/aws/faq/configuration/configure-static-address/), the instance's IP will change on every reboot. I suggest you configure a static IP address now using the AWS console and then configure your domain name to point to that IP using your DNS provider's dashboard.

**Comment by mk336** [comment]
done http://43.204.225.74/ but still not up..

**Comment by jotamartos** [comment]
Apache is failing to run due to a wrong certificate, please fix that 

> The Apache configuration has errors:
> 
> AH00526: Syntax error on line 5 of
> /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile:
> file '/opt/bitnami/apache/conf/laptoprepairingmumbai.com.crt' does not exist or
> is empty

**Comment by mk336** [comment]
How to delete that? i tried through your doc but not working for me.

**Comment by jotamartos** [comment]
Do not know what happened with your certificates but let's recover them:

- Edit the SSLCertificateFile and SSLCertificateKeyFile parameters in the /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf and /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf files

```
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
```

- Restart Apache

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

- You should be able to access your site again but https will throw a warning message.
- Download and run the Bitnami HTTPS configuration tool again 

https://docs.bitnami.com/aws/how-to/understand-bncert/

**Comment by mk336** [comment]
Did all the steps but got error while restart
`Failed to restart apache: Failed to restart apache
`

**Comment by jotamartos** [comment]
Please ensure you made the correct changes in the Apache's configuration and check the logs to see if you are getting new errors when starting Apache. Instead of using the restart command, use the Apache's script 

```
sudo /opt/bitnami/scripts/apache/stop.sh
sudo /opt/bitnami/scripts/apache/start.sh
```

**Comment by mk336** [comment]
`bitnami@ip-172-31-10-128:~$ sudo /opt/bitnami/scripts/apache/stop.sh
apache 08:27:10.73 INFO  ==> apache is not running
bitnami@ip-172-31-10-128:~$ sudo /opt/bitnami/scripts/apache/start.sh
AH00526: Syntax error on line 5 of /opt/bitnami/apache/conf/vhosts/wordpress-htt                                                                                        ps-vhost.conf:
SSLCertificateFile: file '/opt/bitnami/apache/conf/bitnami/certs/server.crt' doe                                                                                        s not exist or is empty
`

**Comment by jotamartos** [comment]
Hi @mk336,

It seems those certificates are wrong too. To solve this, let's generate new dummy certificates for you to be able to start Apache

- Remove the certificates in the /opt/bitnami/apache/conf folder 

```
sudo rm -rf /opt/bitnami/apache/conf/server.*
```

- Create new dummy certificates by following this guide 

https://docs.bitnami.com/aws/apps/wordpress/administration/create-ssl-certificate-apache/

- Update the SSLCertificate parameters in the Apache's conf 

```
  SSLCertificateFile "/opt/bitnami/apache/conf/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/server.key"
```

- Start Apache 

```
sudo /opt/bitnami/scripts/apache/start.sh
```

Once Apache is started, you can use our Bitnami HTTPS configuration tool to generate new Let's Encrypt certificates 

https://docs.bitnami.com/aws/how-to/understand-bncert/

**Comment by mk336** [comment]
Hi @jotamartos,

Successfully resotred all my data thank you so much for your support.

**Comment by mk336** [comment]
Last query, how to automatically renew my ssl cetificated each time?

**Comment by jotamartos** [comment]
If you used bncert, it should have configured a cron job to renew the certificate. 

```
sudo crontab -l -u bitnami
```

**Comment by mk336** [comment]
Thanks all done...
