### ISSUE TITLE
Wordpress on Bitnami and AWS unavailable

### ISSUE THREAD

**Issue by cartessius** [bitnami/vms#720]
### Describe your issue as much as you can

On AWS EC2 instance I've installed Bitnami and on top of that I've installed Wordpress and a Wordpress theme.

After few months of customization few days ago I stopped and started the instance. Since then my site is unavailable.

I am trying to bring the site up and for this I've found this tutorial: https://www.youtube.com/watch?v=xvtoVxk8kWA

Following the tutorial I can say the following:
- Status check for sys. reachability successfully passed
- Status check for instance reachability successfully passed
- Security groups look ok from my perspective
- Network ACL looks ok from my perspective (all traffic allowed)

In the tutorial (time 4:20) it says to start the following command:
`sudo systemctl status httpd`
When I run this command I get the following output
`Unit httpd.service could not be found.`

I tried running this command as "root" and as "bitnami" user. In both cases I am getting the same error message.

In the aforementioned tutorial in the comments someone wrote that "sudo systemctl restart httpd" worked for him. But when I run this command I still get "Unit httpd.service not found.".

Bottom line is - I am trying to bring the site up. This way or any other way. All checks which video describes until 4:20 minute look same/similar on my end. That's why I am trying to bring it up with "sudo systemctl...". can anyone please help me with this? Thanks!

Following the video (4:41) I've run this command to check if the traffic is received on port 80/443:

`netstat -tunlp | grep -i http`
I don't get any result (at least not the result as shown in the video). Based on this I conclude that the site is NOT listening on port 80/443

I tried running this command and here is the result

```
sudo firewall -cmd --state
sudo: firewall: command not found
```

If I run

`sudo /opt/bitnami/ctlscript.sh status`
Then I get this result

```
apache already running
mariadb already running
php-fpm already running
```

Can anyone please help me to bring the site back up? The matter is urgent and critical. Thanks for support and understanding.

**Comment by mdhont** [comment]
Please note that Bitnami stacks are configured differently from typical system installations, and they use their own system components. (like Apache)  That means that some of the commands provided in the tutorial won't work in the same way for the Bitnami stack. Could you run the bndiagnostic tool and send me the output?

    sudo /opt/bitnami/bndiagnostic-tool

**Comment by cartessius** [comment]
@mdhont Thanks for your message.
Please find the output below
`sudo /opt/bitnami/bndiagnostic-tool
An updated version is available. Would you like to download it? You would need t                                          o run it manually later. [Y/n]: n

----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

|\
The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:


===== Begin of bndiagnostic tool output =====


    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found



[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 975 386 63 1 524 420 Swap: 634
12 622
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Sun Feb 26 21:00:44.149415 2023] [proxy_fcgi:error] [pid 952:tid
140330003298048] (70007)The timeout specified has expired: [client
**ip_address**:20346] AH01075: Error dispatching request to : (polling),
referer: https://www.adresa.me/wp-admin/plugins.php?s=&plugin_status=all

```
Please check the following guide to deactivate plugins:

https://developer.wordpress.org/cli/commands/plugin/deactivate/

[Apache]
Press [Enter] to continue:

Found recent error or warning messages in the Apache error log.
```
[Sun Feb 26 20:59:56.709925 2023] [proxy_fcgi:error] [pid 952:tid
140329768302336] (70007)The timeout specified has expired: [client
**ip_address**:32977] AH01075: Error dispatching request to : (polling),
referer:
https://www.adresa.me/wp-admin/admin.php?page=w3tc_dashboard&_wpnonce=521586fa3b&
w3tc_note=flush_all
 [Sun Feb 26 20:59:43.844511 2023] [proxy_fcgi:error] [pid 952:tid
140330158352128] (70007)The timeout specified has expired: [client
**ip_address**:28814] AH01075: Error dispatching request to : (polling),
referer:
https://www.adresa.me/wp-admin/admin.php?page=w3tc_dashboard&_wpnonce=521586fa3b
 [Sun Feb 26 21:00:29.519343 2023] [proxy_fcgi:error] [pid 689:tid
140329474819840] (70007)The timeout specified has expired: [client
**ip_address**:51737] AH01075: Error dispatching request to : (polling)

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
Press [Enter] to continue:


===== End of bndiagnostic tool output =====


Press [Enter] to continue:                                                                                              The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

68c41c59-2922-1493-7306-970580d0b299

And paste it in your Bitnami Support ticket.
`

**Comment by cartessius** [comment]
@mdhont  Re. "connectivity":

- this is how my inbound rules are defined: https://prnt.sc/ieCq2NSsX6B6
-

**Comment by cartessius** [comment]
This video (https://www.youtube.com/watch?v=uLmjoHDCkag) shows how the issue with unreachable site is resolved (14:56 min). 
However, when I connect as bitnami user I can't run the commands show in the video.
On the other hand, if I try to connect with the instance over console-aws either as "admin" or "ec2-user", I get the following error 
`Failed to connect to your instance
Error establishing SSH connection to your instance. Try again later.` 

Why can't I connect with the instance?

**Note**: neither of videos is related with bitnami, and all I am trying to do is to bring the site up. Not sure if what video describes as solution would 100% apply to my site, but I am not finding any other solutions.

**Comment by mdhont** [comment]
According to the bndiagnostic tool the machine is running low on resources. I recommend upgrading it to a more powerful one.

**Comment by cartessius** [comment]
@mdhont - everything was working perfectly well before I stopped and started the instance. I did not experience any performance issues. Thus I doubt that upgrade to a more powerful machine will. I actually doubt it will.

Do you perhaps have any other ideas? 
I am not infrastructure expert, so I'd appreciate detailed infos. Thanks.

**Comment by cartessius** [comment]
@mdhont 
Please understand that my site is down for 5 days already.
And that I am not an infrastructure expert.

I'd therefore appreciate detailed instructions and any help I can get.
I am running out of options who/where to ask. If you have any recommendation regarding this, please send them to me.
I am surprised that this question hasn't already been addressed. It can't be I am the first person who stopped and started an instance under bitnami and it's rocket science to re-run the site which was working perfectly well before the stoppage.

Thanks for your understanding.

**Comment by cartessius** [comment]
I am watching the whole time on AWS side and I don't see anything wrong. 
- There is 1 VPC and 1 EC2 instance
- There is 1 route table (public hosting zone)
- There is 1 network ACL
- There is 1 elastic IP which seems to be connected to VPC and EC2
- There are 4 security groups all connected to that 1 VPC (3/4 groups are bitnami, 1 is default)
- 1 internet gateway
- 1 DHCP option set

Can it be that something on bitnami side needs to be done to bring the site back up?

**Comment by mdhont** [comment]
> Can it be that something on bitnami side needs to be done to bring the site back up? 

That's not possible. Bitnami pre-configures, packs, and publishes applications which can be deployed by end-users. Our applications are tested to work out of the box so it's unlikely that the issue is related to Bitnami configuration itself. Most of the time when the applications fail after deployment, it's due to either changes in the configuration or a lack of machine resources. Did you try checking the available RAM?

    free -m

**Comment by cartessius** [comment]
Here is the result:


bitnami@ip-<IP_address>:~$ free -m
               total        used        free      shared  buff/cache   available
Mem:             975         160         237           0         577         664
Swap:            634          38         596

Any ideas?

**Comment by cartessius** [comment]
@mdhont : please have a look at this: https://prnt.sc/i_MEiZ5Q27mV
To me it seems that memory is OK. As mentioned before, I did not have any issues with the performance.

**Comment by cartessius** [comment]
I found a solution - when I ran this command "sudo /opt/bitnami/ctlscript.sh restart" my site was up again.
Hope this helps someone in the future

**Comment by mdhont** [comment]
Thanks for sharing the solution.
