### ISSUE TITLE
[<Bitnami>] <unable to access wordpress acount>

### ISSUE THREAD

**Issue by hexcol** [bitnami/vms#721]
### Describe your issue as much as you can

Hello,
My partner and I are having issues with access our wordpress account via bitnami (command line).  I accidentally reinstalled apache2, and then noticed that when i opened wp-config.php it was blank.  Then when I went back to the wordpress (wp-admin) side, I realized there was no connection.

**Comment by mdhont** [comment]
Please note that reinstalling individual components like Apache or PHP is not supported. Bitnami applications use their own preconfigured components. I recommend launching a new Bitnami WordPress instance and copy the wp-config.php file to the old instance, and check if it's possible to restart the application.

**Comment by hexcol** [comment]
Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hexcol** [comment]
I was able to copy and past the new wp-config.php file to the old wp-config.php in the old ec2 instance.  Now it says error establishing database connection.

**Comment by mdhont** [comment]
You need to change the database password inside the wp-config file to the one used by the installation.
