### ISSUE TITLE
[Azure | Bitnami | Virtual Machine] Drupal 9 on Azure

### ISSUE THREAD

**Issue by arnieraju** [bitnami/vms#722]
### Describe your issue as much as you can

I would like to use the Bitnami Drupal Virtual machine on Microsoft Azure.  We have an existing Drupal 9 we need to do an upgrade on so would like to create a Drupal 9 VM.

When we use the Drupal packaged by Bitnami, we get a Drupal 10 VM.
Is there any way to create a Azure Bitnami Virtual machine which uses a Drupal 9 image?

I can see that in the change log (https://bitnami.com/stack/drupal/azuredebian-x64-nami/changelog.txt) the last v9 release was on the 10th of December.

**Comment by mdhont** [comment]
We have Drupal 9 available for download in OVA format. Unfortunately I'm not sure if it's possible to launch it on Azure.

https://downloads.bitnami.com/files/stacks/drupal/9.5.3-9/bitnami-drupal-9.5.3-9-r09-linux-vm-debian-11-x86_64-nami.ova 

    md5:15e5bf791630759a53864ef90c64c6c1
