### ISSUE TITLE
[RabbitMQ] How to upgrade Erlang?

### ISSUE THREAD

**Issue by alexandernajafi** [bitnami/vms#723]
### Describe your issue as much as you can

I have launched an EC2 instance in AWS using your RabbitMQ AMI (ami-0bce5bbb2017208d7) 

I followed the [upgrade guide](https://docs.bitnami.com/aws/infrastructure/rabbitmq/administration/upgrade/ ) to upgrade RabbitMQ to the latest version (3.11.9). However, according to the [compatibility matrix ](https://www.rabbitmq.com/which-erlang.html) I also have to upgrade Erlang since the AMI only comes with Erlang OTP 23 and I need OTP 25. 

Do you have any instructions on a simple way to upgrade Erlang? How was Erlang installed in the first place on the instance?

**Comment by alexandernajafi** [comment]
I ended up deleting everything in ` /opt/bitnami/erlang/` and then I installed Erlang using the guide on `https://www.erlang-solutions.com/downloads/`

Is there any easier way? Maybe this should be included in your [upgrade guide](https://docs.bitnami.com/aws/infrastructure/rabbitmq/administration/upgrade/) since it is very crucial to use the correct Erlang version.

**Comment by jotamartos** [comment]
Hi @alexandernajafi,

I'm glad to hear that you manage to update Erlang that way. We always suggest launching a new instance and migrating the data from the old instance to the new one. 

We will monitor this ticket and if we see that there are more people interested in this upgrade information, we will work on adding it to our documentation. In the meantime, users will be able to find this information in this support forum. 

Thanks
