### ISSUE TITLE
[LAMP] Where to find bitnami lampstack latest installers for version 8.x

### ISSUE THREAD

**Issue by knockshore** [bitnami/vms#724]
### Describe your issue as much as you can

I dont see any installer links for lampstack v8.x. There are only Cloud deploy and VM downloads. Are installers discontinued?

**Comment by knockshore** [comment]
Thanks Juan

**Comment by isfarca** [comment]
@jotamartos How can I update an existing AWS Lightsail server instance with Bitnami LAMP stack from version 7.3 to 8.2?

**Comment by jotamartos** [comment]
That's a different question than the original one, so please create a new topic the next time. If you want to update the PHP version in the instance, you will need to launch a new one with the new version of PHP and migrate your files and database to that new instance. Remember to migrate any SSL certificate or Apache-related change too.
