### ISSUE TITLE
[Weblate] How to upgrade weblate on AWS

### ISSUE THREAD

**Issue by sowinski** [bitnami/vms#725]
### Describe your issue as much as you can

Hi,

in the docs there is no command listed how exactly I have to upgrade weblate: `https://docs.bitnami.com/virtual-machine/apps/weblate/administration/upgrade//`

Is there a specific command I have to run? Or do I have to upgrade the package myself? (For example by updating the package in the venv?)

Thank you

**Comment by mdhont** [comment]
I'm not sure I understand your question. You need to execute all steps from the guide to upgrade Weblate.

**Comment by sowinski** [comment]
How do I do this step "Install the new version of Weblate"?

Which guide?

**Comment by mdhont** [comment]
Install the new version of Weblate means that you need to install Weblate itself, (using pip install) as described in the generic instructions from the guide:

https://docs.weblate.org/en/latest/admin/upgrade.html#generic-upgrade-instructions

**Comment by sowinski** [comment]
Thank you. I thought the Bitnami is doing it somehow. So its the same process as managing the package on my own, correct?
