### ISSUE TITLE
[Wordpress] bncert-tool cannot identify install directory 

### ISSUE THREAD

**Issue by kfbenz** [bitnami/vms#726]
### Describe your issue as much as you can

Update to issue 387 [Closed]. I was able to replicate the issue on another system. I was in the process of adding a domain to Apache and attempting to acquire a new LetsEncrypt certificate.  Things progressed as expected, but ultimately failed to what appeared to be an auth issue with one of the certificates. bncert-tool then attempted to restore the previous configuration, however that failed as well. 

Further attempts to update the certificate returned the error message that the bncert-tool was unable to find the bintani instance at /opt/bitnami (where it is)

I'm wondering if during the revoke of a previous certificate, the attempt to restore leaves bncert-tool in a bad place.

**Comment by jotamartos** [comment]
Hi @kfbenz,

Can you provide us more information about the issue?

- What version of Bitnami WordPress are you using?
- Are you using the latest version of Bncert?
- What are the steps to reproduce the issue? Does it happen when running bncert for the first time? Does it happen when changing the domain?

**Comment by kfbenz** [comment]
*   Version 5-5.1

  *   bncert-tool was updated that day.

  *   There was already a certificate with a number of domains assigned to it. What I was attempting to do, was add an additional domain to the list. In my call to bncert-tool, I disabled domain-ip address checks because one of the domains in question uses Sitelock, which acts as a WAF proxy and I didn't want to take down a production site When prompted to delete the old certificate, I did so. The Certificate appeared to be created/downloaded and as the process continued, a number of validation error messages were displayed with at the end, I was alerted that the bncert process had failed and was rolling back. Then a message saying that rollback had failed. I then attempted to re-run the tool which then displays the message that it can't find a bitnami instance at /opt/bitnami (which is where it is) and unable to progress from here.

[cid:7e5bbf7e-45b2-4ab6-af5a-855adc2e9bec]


Kevin Benz

Webmaster

Archdiocese of Seattle

Desk: (206) 382-4524 | Mobile: (425) 785-7100

Archseattle.org | @archdioceseofseattle

"It is not how much we do, but how much love we put in the doing", Mother Theresa

________________________________

**Comment by jotamartos** [comment]
Hi @kfbenz,

Thanks for the info. I understand you are using WordPress 5.5.1 which is from almost 3 years ago. I'll try to reproduce the issue with a new VM and update the ticket

**Comment by jotamartos** [comment]
Hi, 

As I mentioned, I tried to reproduce the issue but I couldn't do so. I created a certificate using bncert for one of my domains. Then executed the tool again to add more domains to the certificate. The tool revoked the previous certificate and generated a new one without issues. 

I suggest you follow the alternative approach so you can generate new certificates manually and avoid the issues you are running into when using the tool

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
