### ISSUE TITLE
[JOOMLA] port 3306 not aviable

### ISSUE THREAD

**Issue by maycaCARAC** [bitnami/vms#727]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

73d06d7a-bdaa-d549-2ec6-df3adf9ea54b

### bndiagnostic output

 ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

i dont found help to my inssue

### Describe your issue as much as you can

Port 3306 is not aviable to LISTEN and i cant found the way to restore it

- Active Internet connections (only servers)
- Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
- tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      530/sshd
- tcp6       0      0 :::80                   :::*                    LISTEN      1388/httpd
- tcp6       0      0 :::22                   :::*                    LISTEN      530/sshd
- tcp6       0      0 :::443                  :::*                    LISTEN      1388/httpd
- udp        0      0 0.0.0.0:68              0.0.0.0:*                           345/dhclient
- udp        0      0 127.0.0.1:323           0.0.0.0:*                           529/chronyd
- udp6       0      0 fe80::8de:a4ff:fe10:546 :::*                                423/dhclient
- udp6       0      0 ::1:323                 :::*                                529/chronyd

**Comment by jotamartos** [comment]
Hi @maycaCARAC,

Did you take a look at the MariaDB's log file as the tool suggested? You would have found this error 

```
2023-03-01 17:18:25 0 [Note] Recovering after a crash using tc.log
2023-03-01 17:18:25 0 [ERROR] Can't init tc log
2023-03-01 17:18:25 0 [ERROR] Aborting
```

It seems there is something wrong with the tc.log file. Please try to rename it and restart the database 

```
sudo mv /bitnami/mariadb/data/tc.log /bitnami/mariadb/data/tc.log.back
sudo /opt/bitnami/ctlscript.sh restart mariadb
```

Does the database work now? If not, please take a look at the database's documentation and the different guides available online related to this error.
