### ISSUE TITLE
[<bitnami wordpress multisite on aws>] <.htaccess - Authorization header not found.>

### ISSUE THREAD

**Issue by SashL84** [bitnami/vms#728]
### Describe your issue as much as you can

Hello,
I have an bitnami wordpress multisite stack on aws and try to use the  WP REST API via JWT auth.
The token generates well, but the token validation failes with this issue in postman:
```
 "success": false,
    "statusCode": 403,
    "code": "jwt_auth_no_auth_header",
    "message": "Authorization header not found.",
    "data": []
```
I set the .htaccess as well as the htaccess.conf for the required rows:

```
RewriteRule .* - [E=HTTP_AUTHORIZATION:%1]
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteCond %{HTTP:Authorization} ^(.*)
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$0
```
but it´s still not working.

I hope anyone have an idea how I can fix this issue.

Thanks in advance

**Comment by mdhont** [comment]
I recommend asking in the application's dedicated forum. The issue does not seem related to the Bitnami configuration and usually they will have a better understanding of the specifics of the application there.

**Comment by SashL84** [comment]
Thank you for your answer.
I think the issue is on the .htaccess bitnami configuartion, which in the bitnami stack is pointed from other files like `http-app.conf`
The docs to this understanding are naming files, which are not on the described file structures.

https://docs.bitnami.com/general/apps/wordpress-multisite/administration/use-htaccess/

Is there another resource for more information to handle the .htaccess on bitnami configuration?

Thanks in advance.

**Comment by mdhont** [comment]
You can find the wordpress-htaccess.conf in the following path:

     /opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf
