### ISSUE TITLE
How to Monitor and Automatically Restart Services

### ISSUE THREAD

**Issue by dblincoe24** [bitnami/vms#729]
### Describe your issue as much as you can

This isn't really a technical issue, so hopefully I'm posted this in the correct location.  I want to setup a script to check if services are running and restart services if they aren't running.  I'm trying to follow these instructions:

https://www.cyberciti.biz/tips/howto-monitor-and-restart-linux-unix-service.html

and use the monit app to accomplish this goal.  I have installed the app and am working on configuring apache monitoring, but do not see a *.pid file that I can use to monitor.  

When I go into the ctlscript.sh I see that this uses gonit to monitor and restart the services.  
Does anyone know how I can accomplish this?  Ideally, every minute or so it would monitor the status and restart services if stopped.  

Thanks in advance

**Comment by jotamartos** [comment]
We already include gonit to monitor the different services. You can learn more about it here 

https://docs.bitnami.com/general/apps/wordpress/administration/configure-use-gonit/

**Comment by dblincoe24** [comment]
I did see gonit before, but am unsure how to trigger the app to monitor services status on an interval and restart if the service isn't running.  Do you have any documentation on how to set that up?

**Comment by dblincoe24** [comment]
Ahhh, got it.  We had a couple of instances when the website was down and the services were stopped, but not restarted.  I'm going to look through the log files to see if I can see a reason why.  
Thank you!
