### ISSUE TITLE
[Parse] React Website Host

### ISSUE THREAD

**Issue by RitvikSardana** [bitnami/vms#73]
### Describe your issue as much as you can

I am unable to host my React Website on Bitnami Parse using Apache!
Can anyone help?

**Comment by mdhont** [comment]
The following guide explains how to run a custom app on Bitnami LAMP:

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

**Comment by RitvikSardana** [comment]
I followed all the instructions, but whenever I go to the URL it takes me to my Parse Server, which is hosted on the same instance.
Any help over here?

**Comment by mdhont** [comment]
My guess is that your parse server is using the same port. To run two different server applications on the same instance you would need to use a different port like 81. 

https://docs.bitnami.com/aws/apps/wordpress/administration/configure-port/
