### ISSUE TITLE
[wordpress] error installing memcache

### ISSUE THREAD

**Issue by JaycoCIO** [bitnami/vms#730]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

 45357f90-59ad-46e8-3e09-050a16dd5773

### bndiagnostic output

[Thu Mar 02 01:19:36.451588 2023] [proxy_fcgi:error] [pid 533681:tid 
140643863095040] [client **ip_address**:47010] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key 2691 in 
/opt/bitnami/wordpress/wp-includes/nav-menu-template.php on line 211PHP message: 
PHP Warning: Undefined array key 2691 in 
Press [Enter] to continue:
/opt/bitnami/wordpress/wp-includes/nav-menu-template.php on line 211'
 [Thu Mar 02 01:19:39.051769 2023] [proxy_fcgi:error] [pid 533692:tid 
140644148217600] [client **ip_address**:43634] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key 2691 in 
/opt/bitnami/wordpress/wp-includes/nav-menu-template.php on line 211PHP message: 
PHP Warning: Undefined array key 2691 in 
/opt/bitnami/wordpress/wp-includes/nav-menu-template.php on line 211'
 [Thu Mar 02 01:19:41.948648 2023] [proxy_fcgi:error] [pid 533681:tid 
140643846309632] [client **ip_address**:52426] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key 2691 in 
/opt/bitnami/wordpress/wp-includes/nav-menu-template.php on line 211PHP message: 
PHP Warning: Undefined array key 2691 in 
/opt/bitnami/wordpress/wp-includes/nav-menu-template.php on line 211'

### bndiagnostic was not useful. Could you please tell us why?

Not sure it is related to my issue

### Describe your issue as much as you can

I was following the article for https://docs.bitnami.com/general/apps/wordpress/configuration/install-modules-php/#installation-129

to install memcache and when I type make I get the following errors 
tmp/php-memcached/php_memcached.c: In function ‘zim_Memcached___construct’:
/tmp/php-memcached/php_memcached.c:1282:20: error: lvalue required as left operand of assignment
 1282 |   GC_REFCOUNT(&le) = 1;
      |                    ^
make: *** [Makefile:208: php_memcached.lo] Error 1

**Comment by jotamartos** [comment]
I'm not really sure if that library supports PHP 8, please note that it was released long time ago. As an alternative, you can install this other PHP extension 

https://github.com/php-memcached-dev/php-memcached

**Comment by JaycoCIO** [comment]
@jotamartos Thank you. Are there any instructions? Not sure exactly what to do.

**Comment by JaycoCIO** [comment]
@jotamartos and my website now have a problem. I cannot successfully log out. Does it have anything to do with installing the Memcache files?
