### ISSUE TITLE
[DigiCert Global Root G2] Renewal of Digicert Root Certificate

### ISSUE THREAD

**Issue by kshibay** [bitnami/vms#731]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

I have not run Bitnami diagnostic tool.

### bndiagnostic was not useful. Could you please tell us why?

Because there is no error.

### Describe your issue as much as you can

Regarding Digicert's SSL certificates.Root certificate will be changed to the new specification.

The following actions are required due to this change in certificate specifications.

Root Certificates
　　　Secure Server ID/Global Server ID/Quick SSL Premium
　　　(Before change) DigiCert Global Root CA
　　　(After change) DigiCert Global Root G2
Intermediate CA Certificate
　　　Secure Server ID/Global Server ID
　　　(Before change) DigiCert TLS RSA SHA256 2020 CA1
　　　(After change) DigiCert Global G2 TLS RSA SHA256 2020 CA1

I have created a redmine server in marketplace in Azure.
OS is Linux (debian 10.13).

How do I install a G2 root certificate on my server?

**Comment by mdhont** [comment]
The following guide explains how to configure your application with an existing certificate:

https://docs.bitnami.com/virtual-machine/apps/wordpress/administration/enable-https-ssl-apache/

**Comment by kshibay** [comment]
Thank you for your response.

I think your answer is the procedure for connecting from the Remine server to the client.

We are connecting from Redmine server to Sendgrid via smtp 587. The following is commented out

enable_starttls_auto: false

Are you using DigiCert certificates when relaying to SendGrid?

If so, I would like to know where to import the SSL certificates used in the communication between RedmineSV and Sendgrid.

Thank you in advance.

**Comment by mdhont** [comment]
The application is preconfigured to use with any third-party CA like DigiCert. I recommend asking in a dedicated Redmine forum for information about configuring Redmine with SendGrid. 

The following guide shows how to configure (regular) SMTP  for Redmine.

https://docs.bitnami.com/azure/apps/redmine/configuration/configure-smtp/

**Comment by kshibay** [comment]
Thank you for your response.

I would like to ask an additional question.

1. Does the Bitnami Redmine server communicate with the Internet via API? And is it configured by default?

2. Does Bitnami offer Japanese language support or paid support plans?

Thank you in advance.

**Comment by mdhont** [comment]
Our installers do not need an internet connection. Regarding the language, you can choose the language during the installation process.

**Comment by kshibay** [comment]
Thank you for providing an answer to my question. 

I understand that Redmine is not connected to the internet.

I only use SMTP as the only port for mail delivery, so I just need to open the firewall only for 587, right?

Does Bitnami have Japanese support?

**Comment by mdhont** [comment]
> I only use SMTP as the only port for mail delivery, so I just need to open the firewall only for 587, right?

You still need to open port 80 and 443 to be able to access the application in the browser. 

> Does Bitnami have Japanese support?

That differs per application. I'm not sure if it's possible to add Japanese Language support in the application's settings. I recommend asking in the offiicial Redmine forum.
