### ISSUE TITLE
AWS Lightsail having 100% capacity, due to which website getting very slow

### ISSUE THREAD

**Issue by vasundharak** [bitnami/vms#732]
### Describe your issue as much as you can

Hi,
My AWS Lightsail account recently is slowing down and CPU usage is reaching 100%. How can I know the real cause behind it.

**Comment by vasundharak** [comment]
![image](https://user-images.githubusercontent.com/29419992/222634300-bd94e978-6c07-4263-8ea0-6161d40a3040.png)

**Comment by jotamartos** [comment]
It seems the database is being used intensively. It's probably the application you are running the culprit of that high usage. I suggest you take a look at our bots/attackers guide to know if you are receiving more requests than expected

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/

**Comment by vasundharak** [comment]
212 127.0.0.1
   1000 105.157.111.160
    747 180.188.248.147
    359 180.188.248.171
    268 106.204.212.155
    208 106.211.82.51
    205 61.3.91.102
    178 124.253.181.12
    138 125.62.126.208
    137 49.156.103.90

**Comment by vasundharak** [comment]
How Can I find out which part of the application is problematic?

**Comment by vasundharak** [comment]
Hi,
Please help

**Comment by benytinck** [comment]
Check whether any IPs trying to access any location/url on your sites again and again that does not exist.
If it is trying to run binaries or scripts directly, it is likely that IP address is a bot.
Check the above mentioned link by jota: https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/
