### ISSUE TITLE
Mautic Bitnami Installer for windows 64

### ISSUE THREAD

**Issue by educrue** [bitnami/vms#733]
### Describe your issue as much as you can

How to get the last version mautic installer by Bitnami for Windows 64?

**Comment by mdhont** [comment]
You can download it here:

https://downloads.bitnami.com/files/stacks/mautic/3.3.3-0/bitnami-mautic-3.3.3-0-windows-x64-installer.exe 

    md5:1a92a1a5a09a027cb920df2223ee306f

**Comment by educrue** [comment]
THANK YOU VERY MUCH!!!😃👌
