### ISSUE TITLE
Aws lightsail Bitnami wordpress old image upgrading

### ISSUE THREAD

**Issue by benytinck** [bitnami/vms#735]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7ae1448b-4cce-dc8a-390f-668defd7dc9a

### bndiagnostic output

    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Mysql: No issues found
    ? Php: Found possible issues

[Apache]

Found recent Pagespeed related error messages in the Apache error log:
```
[Sat Mar 04 00:34:30.689439 2023] [pagespeed:error] [pid 22448:tid
140588682823424] [mod_pagespeed **ip_address**-0 @22448] PageSpeed Serf fetch
failure rate extremely high; only 0 of 119 recent fetches fully successful; is
fetching working?

```
We suggest disabling pagespeed and check if that improves the behavior. Please
Press [Enter] to continue:
check the following guide to disable Pagespeed:

https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespe
ed/#disable-pagespeed

Found recent error or warning messages in the Apache error log.
```
[Fri Mar 03 12:39:10.116274 2023] [autoindex:error] [pid 18533:tid
140589404104448] [client **ip_address**:33386] AH01276: Cannot serve directory
/opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex
(index.html,index.php) found, and server-generated directory index forbidden by
Options directive, referer: binance.com
 [Fri Mar 03 13:20:53.274998 2023] [autoindex:error] [pid 17373:tid
140589800486656] [client **ip_address**:13668] AH01276: Cannot serve directory
/opt/bitnami/apps/wordpress/htdocs/wp-includes/: No matching DirectoryIndex
(index.html,index.php) found, and server-generated directory index forbidden by
Options directive
 [Fri Mar 03 19:43:26.404384 2023] [autoindex:error] [pid 22448:tid
140589286606592] [client **ip_address**:35458] AH01276: Cannot serve directory
/opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex
(index.html,index.php) found, and server-generated directory index forbidden by
Options directive, referer: binance.com

Press [Enter] to continue:
```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1995 1353 83 199 558 259 Swap:
0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

Press [Enter] to continue:
You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Php]

The following error appears in the
/opt/bitnami/php/var/log/php-fpm.log:
```
[03-Mar-2023 15:38:21] WARNING: [pool www] server reached max_children setting
(5), consider raising it

```
This error usually indicates PHP script execution is slow due to busy server
resouces or buggy scripts. Please check the following guide to increase the
number of PHP-FPM child processes:

https://docs.bitnami.com/general/apps/wordpress/configuration/configure-ph
pfpm-processes/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

guides are ok

### Describe your issue as much as you can

I am Running WordPress on a old Bitnami lightsail Wordpress environment.

I am running two wordpress installation on a single instance.
example.com
example.com/blog/

I want to upgrade the Linux, apache, mysql, and php modules for security reason.
Can i update these on my current instance?
or
I need to create a new instance from my snapshot and then update the modules.

I have provided all the information below.

Here are my System Information:

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Server version: Apache/2.4.46 (Unix)
Server built:   Feb 11 2021 08:21:53

PHP 7.4.15 (cli) (built: Feb 11 2021 08:25:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies

My SQL Version:
8.0.23

**Comment by mdhont** [comment]
> I want to upgrade the Linux, apache, mysql, and php modules for security reason.
Can i update these on my current instance?

Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually.

I recommend launching a new instance and then migrate your application there.
