### ISSUE TITLE
You don't have permission to access /wp-admin/network/ on this server.

### ISSUE THREAD

**Issue by akrai05** [bitnami/vms#738]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

https://prnt.sc/pyHYgfjFXlNp

### bndiagnostic output

https://prnt.sc/pyHYgfjFXlNp

### bndiagnostic was not useful. Could you please tell us why?

I am unable to find the suggested folder

### Describe your issue as much as you can

I  have Installed one plugin "Crocoblock" to my wordpress site and after a while my site goes down. 
It is only showing white screen [https://authentica.com/](url)
My site has the multisite configuration so I am unable to access my Network admin dashboard when I am trying to access it I am getting error "Forbidden You don't have permission to access /wp-admin/network/ on this server."
[https://authentica.com/wp-admin/network/](url).

To fix this I connected to my AWS  EC2 instance and connected to the server and deleted the plugin "Crocoblock" but still getting the same issue.

Site URL : [https://authentica.com/](url)
Site Network admin URl : [https://authentica.com/wp-admin/network/](url)

My site has the multi site configuration so I can access the individual site dashboard  but not the network dashboard.
1. [https://authentica.com/wp-admin/](url)
2. [https://internships.authentica.com/wp-admin/](url)
Bothe sites dashboard is assessable but both sites are not working only white screen is showing.

**Comment by mdhont** [comment]
It seems there are many incoming requests from a small number of IPs. I recommend checking the following guide:

https://docs.bitnami.com/aws/apps/wordpress-multisite/troubleshooting/deny-connections-bots-apache/

**Comment by akrai05** [comment]
Hi there!
Sorry for the late response.
Thanks for the information my issue got resolved.
Best regards,
Amrendra
