### ISSUE TITLE
Redmine installer 3.4.3 for ubuntu

### ISSUE THREAD

**Issue by klopotnik** [bitnami/vms#739]
### Describe your issue as much as you can

Hi,

is there somewhere ubuntu installer (package) still available? 
  Redmine version                3.4.3.stable
  Ruby version                   2.3.3
  Rails version                  4.2.8
(this was for windows.. but need something very similar if possible.)
kind of desparate :-/

**Comment by jotamartos** [comment]
Hi @klopotnik,

Thank you for the interest but we do not provide support for installers anymore. The version you are looking for is from 2018 and it's not available in our records. 

Sorry for the inconvenience.

**Comment by klopotnik** [comment]
uff.. that is very sad.. 
there is really no way i can get to the installer? without restoring old data i cannot migrate to new version :(

**Comment by jotamartos** [comment]
You can use the [Bitnami Redmine container image](https://hub.docker.com/r/bitnami/redmine/tags?page=1&name=3.4.3) to restore that old data. However, you can also ask in the Redmine's forums to know if there is any alternative way to restore that data without having that old version.
