### ISSUE TITLE
[Bitnami WordPress AWS] RDS Failover not being detected by WordPress web server

### ISSUE THREAD

**Issue by alidgett** [bitnami/vms#740]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7d12b3af-1221-627e-55cd-a92d4852b056

### bndiagnostic was not useful. Could you please tell us why?

No relevant information relating to provisioner-peer host file setting

### Describe your issue as much as you can

We have a WordPress Bitnami stack running in AWS. The back-end RDS Aurora MySQL database is configured in HA with a reader and a writer node. After a failover of the RDS database the web servers continue to point to the IP of the now reader or offline node (via the provisioner-peer host file setting). It appears that the provisioner-peer variable is only set once during the instance launch and bootstrap and uses the IP of RDS node. The only way to bring the web servers back online after an RDS failover is to update the wp-config.php file and set the 'DB_HOST' attribute to the actual RDS endpoint name instead of the 'provisioner-peer:3306' value.

Question: 
For RDS HA deployments how does the stack track failover - should the wp-config.php setting file be updated with the actual RDS endpoint (writer) DNSs that does indeed track failover. If so what other side effects could occur after a failover given that the 'provisioner-peer:3306' variable could be referencing the now offline or reader node.

Thanks,
Andrew

**Comment by mdhont** [comment]
Unfortunately the stack itself does not detect a failover nor reset the provisioner-peer value. However updating the wp-config.php file with the actual RDS endpoint DNS name should not cause side effects, as Route 53 should automatically route traffic to the healthy endpoint after a failover.
