### ISSUE TITLE
[Bitnami] Unable to access phpmyadmin

### ISSUE THREAD

**Issue by joekolassa** [bitnami/vms#742]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bf7aa333-981d-5d9d-c215-39d1941cb5f0

### bndiagnostic was not useful. Could you please tell us why?

The output only had one possible issue but it didn't seem to be about phpmyadmin

### Describe your issue as much as you can

I have been working to get a new admin console spun up for an app in bitnami.  Someone else got the old console set up.  They made some documentation of the process, but it was outdated, and I had to do a bit of research as well as trial and error to get it running. Prior to getting the app installed I was able to log into phpmyadmin by going to localhost:8080/phpmyadmin. The console is mostly working now but when I try accessing phpmyadmin it pulls up the auth0 login page I set up for the app instead of the phpmyadmin login page.  This is not the case with the old console.  I can still access phpmyadmin on that old console.  

I'm somewhat of a novice with this so if I have left out any important information please let me know and I will try to add it.

**Comment by mdhont** [comment]
This issue exceeds the scope of this forum as it does not seem related to the Bitnami specific configuration of the application or its components. As we support many applications our support team cannot cover all possible scenarios. I recommend consulting the application's or component's documentation, or asking in specific or general support fora.
