### ISSUE TITLE
[redash] Connection types are missing in data sources

### ISSUE THREAD

**Issue by szymek28** [bitnami/vms#744]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3fcfd106-b686-d710-1ecd-7d05b65d6f3d

### bndiagnostic was not useful. Could you please tell us why?

because it's a problem with the redash application

### Describe your issue as much as you can

The list for selecting connections is missing items, i.e. Mysql, Google Analytics, etc.
There are only 21 types and it should be: https://redash.io/help/data-sources/querying/supported-data-sources

**Comment by sea121** [comment]
How you said that [bndiagnostic](https://kisanstatus.com) was unuseful?

**Comment by szymek28** [comment]
> How you said that [bndiagnostic](https://kisanstatus.com) was unuseful?

He showed no problems, because the application itself works but problem is with sub-functionality.

**Comment by jotamartos** [comment]
Hi all,

We take the reDash files from [its GitHub repository](https://github.com/getredash/redash/tags) and configure it for you to use it. If data sources do not appear there, it may be related to an issue in the application or with the way they have to enable the different data sources depending on if you are hosting the application or not. Can you ask the app's developers to know more about this? 

Thanks

**Comment by damusthe** [comment]
I downloaded the Bitnami Redash v10.1.0 from [https://bitnami.com/stack/redash/virtual-machine](url) and VM starts fine into VirtalBox.
But I can't create a new Data Source of type MySQL, because it's missing into the list.

**Comment by jotamartos** [comment]
As I mentioned above, did you contact the developers of the app?

https://github.com/bitnami/vms/issues/744#issuecomment-1460366580

**Comment by damusthe** [comment]
I created a new issue #1534 and downloaded the diagnostics.
