### ISSUE TITLE
Wordpress Too many redirects

### ISSUE THREAD

**Issue by Mindbowser** [bitnami/vms#745]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2a15de5e-8689-4f38-31b7-950a3ffacb73

### bndiagnostic output

The Apache error log may have more information.
 
    ✓ Resources: No issues found
    ? Php: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mysql: No issues found
    ? Apache: Found possible issues
 

 
[Php]

The following error appears in the 
/opt/bitnami/php/var/log/php-fpm.log:
```
[07-Mar-2023 09:42:36] WARNING: [pool www] server reached max_children setting 
(5), consider raising it

```
Press [Enter] to continue:
This error usually indicates PHP script execution is slow due to busy server 
resouces or buggy scripts. Please check the following guide to increase the 
number of PHP-FPM child processes:
 
https://docs.bitnami.com/general/apps/wordpress/configuration/configure-ph
pfpm-processes/

[Apache]

The Apache configuration has errors:
```
apache2: Syntax error on line 66 of /opt/bitnami/apache2/conf/httpd.conf: Cannot 
load modules/mod_mpm_event.so into server: libiconv.so.2: cannot open shared 
object file: No such file or directory
```
Please check the configuration.

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/
Press [Enter] to continue:
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Too Many redirect

### Describe your issue as much as you can

Suddenly we started getting too many redirect error, we haven't touched servers. One thing I noticed is that SSL certificate might got have renewed as it is showing today's date as start date, not sure what things need to be changed on server to make it work. Our site is https://www.mindbowser.com

Site is down so quick help is appreciated

**Comment by mdhont** [comment]
It seems to be due to a PHP script execution that is making the page inaccessible. Usually a WP plugin is the culprit. I  recommend disabling all plugins and then restart the services:

    wp plugin deactivate --all
    sudo /opt/bitnami/ctlscript.sh restart

If that brings the site back, enable the plugin's one by one to find the cause.
