### ISSUE TITLE
Apache Guacamole: Cannot start services

### ISSUE THREAD

**Issue by frhodes-aam** [bitnami/vms#746]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ed9c9e43-75b6-96e4-ab27-2c8986cd9e8a

### bndiagnostic output

Resources: No Issues found
Connectivity: Found possible issues
Processes: No issues found
Apache: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

Was useful but problem persist

### Describe your issue as much as you can

We have been using the Apache Guacamole and decided to upgrade\update to the latest march 1 release. I followed the stepps outlines here [](https://docs.bitnami.com/aws/apps/guacamole/administration/backup-restore/) to do a backup on the current working one and a restore on thenew instance containing latest image from AWS Marketplace.

After the restore i tried to start the server and got error message (Job for bitnami.service failed because the control process exited with error code.) Check apache log and have an error about server certificate not including an ID (this was working perfectly in the old instance, checked the conf files and same config exist with the current working instance). I tried to change everywhere I had www.example.com to my domain for which I have the certs installed. Now I cam getting another error HTTP: failed to make connection to backend: localhost

I have spent half a day on this already, can you help out pls?

Thank you.

**Comment by mdhont** [comment]
Did you follow the steps from this guide?

https://docs.bitnami.com/virtual-machine/apps/guacamole/administration/backup-restore/

**Comment by frhodes-aam** [comment]
> Did you follow the steps from this guide?
> 
> https://docs.bitnami.com/virtual-machine/apps/guacamole/administration/backup-restore/

Yes, that is the guide I followed yet it did not work as expected. still having the issues. This is the error I get now.

**_[ssl:warn]  AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name_**

**Comment by mdhont** [comment]
```
[ssl:warn] AH01909: [www.example.com:443:0](http://www.example.com:443:0/) server certificate does NOT include an ID which matches the server name
```

That's only a warning, which should not prevent the application from starting. Are there any further errors?

**Comment by BeanSampa** [comment]
Hi,
I don't know if it has anything to do and if the structures are the same.
Honestly, I have little Linux/Apache knowledge, but I'm just sharing my experience that happened today, hope it helps.

I faced a similar issue with AWS Lightsail (Bitnami Nodejs)
bndiagnostic found a problem in:
/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf

     SSL Engine Enabled
     SSLCertificateFile "/opt/bitnami/apache/conf/xxx.non-existent.crt"
     SSLCertificateKeyFile "/opt/bitnami/apache/conf/xxx.non-existent.key"

I just edited and informed valid files.
This solved my problem.

**Comment by frhodes-aam** [comment]
> ```
> [ssl:warn] AH01909: [www.example.com:443:0](http://www.example.com:443:0/) server certificate does NOT include an ID which matches the server name
> ```
> 
> That's only a warning, which should not prevent the application from starting. Are there any further errors?

Hi,

I followed the procedure and did another restore today from backup and as always rght after the services did not start. I ran the diagnosis tool again and this is the output:

The bndiagnostic tool has finished searching for errors and has found some issues that might be related to yours. The output will be shown on the next page:

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ✓ Apache: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the following guide to open server ports for remote access.

I definitely have ports 80 and 443 open, even though I think that will nor prevent the services from starting.

**Comment by mdhont** [comment]
Could you share the bnsupport code that is shown at the end?

**Comment by frhodes-aam** [comment]
> 

c7aeca78-e93d-93d5-8076-2a65daad6488

**Comment by mdhont** [comment]
Did you create a certificate for the new instance:

https://docs.bitnami.com/google/apps/guacamole/administration/create-ssl-certificate-apache/

**Comment by frhodes-aam** [comment]
> Did you create a certificate for the new instance:
> 
> https://docs.bitnami.com/google/apps/guacamole/administration/create-ssl-certificate-apache/

In the backup\restore process that was given, there is no mention of creating a certificate. Moreover the certificate currently being used in the working service where imported as part of the backup\restore process, I have verified that they are there.

**Comment by frhodes-aam** [comment]
> Can you describe the exact steps you executed to backup and restore Guacamole, so I can try to reproduce it?

The exact steps I used are what is in the documentation (link below), nothing added, nothing removed.

[https://docs.bitnami.com/aws/apps/guacamole/administration/backup-restore/](url)

**Comment by frhodes-aam** [comment]
> sudo gonit start guacamole-server

Hi,

Thanks for your help in trying to resolve this. I tried the above and it is not working.

I am going to ask, if there a way to lift off the database which contains the users and connections, from the current running server to the new release?

This has taken too much of my time and as an organization we cannot remain stuck in the old versions, also I need to find a method that works for us else it will not be of any benefit using this product anymore.

Pls let me know if/how I can list the database and drop in a new guacamole server.

Thank you.

Fego

**Comment by mdhont** [comment]
It's possible to backup and restore the Postgresql database. The following guide could be of help:

https://docs.bitnami.com/aws/infrastructure/lapp/administration/backup-restore-postgresql/
