### ISSUE TITLE
[WordPress] Network error: Connection refused.

### ISSUE THREAD

**Issue by avg7115** [bitnami/vms#748]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

do not know how to find this ID

### bndiagnostic output

![image](https://user-images.githubusercontent.com/127334513/223786031-dcf6539c-76c6-469a-98e2-580e6e18b764.png)

### bndiagnostic was not useful. Could you please tell us why?

error messages after running the tool

### Describe your issue as much as you can

I installed Bitnami WordPress on a VMware VM, exported the image to create a custom AMI in AWS and launched an EC2 instance from the AMI successfully. I generated a key pair when launching the EC2 instance but I am not able to SSH to the instance. I keep receiving a Network error: Connection refused.

I am using Putty from a Windows machine to SSH to the EC2 instance.
Got the .ova file here: https://bitnami.com/stack/wordpress/virtual-machine

![ssherror](https://user-images.githubusercontent.com/127334513/223783320-c2954a0c-1348-4d77-905e-955ce1934004.png)

**Comment by jotamartos** [comment]
Hi, 

Please ensure the ssh service is running and that he firewall is configured to accept incoming connections to port 22 

https://docs.bitnami.com/aws/faq/administration/use-firewall/

If you moved from a VM, you will probably need to take a look at these guides 

https://docs.bitnami.com/virtual-machine/faq/get-started/connect-ssh/
https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh/
