### ISSUE TITLE
[CanvasLMS] Unable to start service on VMWare Workstation Player

### ISSUE THREAD

**Issue by miquelnebotaragon** [bitnami/vms#75]
### Describe your issue as much as you can

Hi everyone!
I have downloaded the OVA image, imported to VMWare Workstation Player, there is ping to this machine but nothing display in the web browser... Where is the problem? Thanks!
See the [image](https://drive.google.com/file/d/1vEN-IiMRCzqcS51FrSsZ1UyytbnyzdDm/view?usp=sharing)

**Comment by mdhont** [comment]
Can you access the VM using [SSH](https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh/) and then run the [bndiagnostic tool](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)?
