### ISSUE TITLE
PHP WordPress Application 

### ISSUE THREAD

**Issue by srvsable** [bitnami/vms#750]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2da2e7cc-32b7-c61e-2e30-4902f59cb4b2

### bndiagnostic output

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
[error_log.zip](https://github.com/bitnami/vms/files/10924192/error_log.zip)

### bndiagnostic was not useful. Could you please tell us why?

Cannot find this error in the dndiagnostic

### Describe your issue as much as you can

Apache service is stopping automatically. The website is becoming unreachable without warning
[access_log-20230305.gz](https://github.com/bitnami/vms/files/10924198/access_log-20230305.gz)

**Comment by oxgen1** [comment]
bumping I've been having the same issue
