### ISSUE TITLE
[Wordpress] Permission issue preventing plugin upload or updates

### ISSUE THREAD

**Issue by FransB123** [bitnami/vms#752]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c403a415-8a84-f57e-d06a-a876f668db31

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ? Nginx: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Nginx]

Press [Enter] to continue:
Found recent error or warning messages in the Nginx error log.
```
2023/03/08 17:54:03 [error] 206475#206475: *77 access forbidden by rule, client:
**ip_address**, server: _, request: "GET /.env HTTP/1.1", host: "16.162.109.60"
 2023/03/08 18:51:47 [error] 206474#206474: *95 access forbidden by rule,
client: **ip_address**, server: _, request: "GET /.env HTTP/1.1", host:
"16.162.109.60"
 2023/03/08 19:15:53 [error] 206475#206475: *171 access forbidden by rule,
client: **ip_address**, server: _, request: "GET /.env HTTP/1.1", host:
"16.162.109.60"

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

The errors were not related to my issue

### Describe your issue as much as you can

I have reset all the permissions on my stack as instructed on this page https://docs.bitnami.com/general/apps/wordpress-production-ready/administration/understand-file-permissions/#:~:text=Bitnami%20applies%20the%20following%20default,with%20permissions%20664%20by%20default.
But I am still getting permission errors when I try to install or update a plugin. 

![BitnamiCommands](https://user-images.githubusercontent.com/15902984/223826112-deaf2f55-3f24-4dd4-9b78-6a6f9124b963.PNG)

![Plugindownload](https://user-images.githubusercontent.com/15902984/223826745-1ac65edd-44a8-49fa-96c3-beb32bcd1ff0.PNG)
![pluginupdate](https://user-images.githubusercontent.com/15902984/223826766-78f033f0-1472-4e9f-a1eb-c2a8f1a20ffc.PNG)

**Comment by jotamartos** [comment]
Hi

Please run the commands in this post to reset the permissions

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

**Comment by FransB123** [comment]
That worked
