### ISSUE TITLE
[Canvas] Error when launching LTI 1.3 link - configuration problem

### ISSUE THREAD

**Issue by bibli-alex** [bitnami/vms#753]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

28521571-cbdf-b70f-ae57-aff0527373a8

### bndiagnostic output
```

✓ Resources: No issues found
? Connectivity: Found possible issues
? Processes: Found possible issues
✓ Apache: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Processes]

One or more component's processes are not running:
canvaslms-delayed-jobs not running
```

### bndiagnostic was not useful. Could you please tell us why?

Issue is related to functionality in canvas

### Describe your issue as much as you can

I'm getting a 500 error when trying to launch an LTI 1.3 link with the default setup. The error from Canvas says: 

```
undefined method `sign' for nil:NilClass
```

Seems to be reported a bit in the canvas community, with a specific reference to a bitnami setup here:
https://community.canvaslms.com/t5/Canvas-Question-Forum/Public-JWKS-URL-is-not-working/m-p/225583

I've also found that copying the keys from the development block to the production block works as a stop-gap.

**Comment by mdhont** [comment]
Can you describe the exact steps to try to reproduce the issue?
