### ISSUE TITLE
Roundcube last version

### ISSUE THREAD

**Issue by operations-ics** [bitnami/vms#754]
### Describe your issue as much as you can

Dear All,
We are downloaded and installed the last available version of roundcube .ova package.
Starting the first time, application credential was missed
We need to use the roundcube with internal smtp/imap so We have installed (following Your instruction) dovecot and postfix and We have also installed sendmail. We have modified as requested all the necessary file in according with Your instruction.
Where, now, We can find the roundcube credentials?
Documentation not explain where and or how We obtain the credentials using internal SMTP, IMAP server
Thank You so much
Antonio

**Comment by mdhont** [comment]
You can find the credentials in the pre-start.log:

    sudo cat /opt/bitnami/var/log/pre-start.log
