### ISSUE TITLE
Wordpress Azure - Site Origin

### ISSUE THREAD

**Issue by Teteios** [bitnami/vms#755]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ef5cd2c2-8342-c412-cbf5-1220a371c62a

### bndiagnostic output

 ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Wordpress: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sat Mar 11 09:49:30.156819 2023] [autoindex:error] [pid 399955:tid
139647745177344] [client **ip_address**:35074] AH01276: Cannot serve directory
/opt/bitnami/wordpress/wp-includes/blocks/button/: No matching DirectoryIndex
(index.html,index.html,index.htm,index.php) found, and server-generated
directory index forbidden by Options directive, referer:
https://www.dtmd.eu/wp-includes/blocks/button/index.php
 [Sat Mar 11 09:49:33.895077 2023] [autoindex:error] [pid 399657:tid
139647971780352] [client **ip_address**:35334] AH01276: Cannot serve directory
/opt/bitnami/wordpress/wp-includes/blocks/button/: No matching DirectoryIndex
(index.html,index.html,index.htm,index.php) found, and server-generated
directory index forbidden by Options directive, referer:
https://www.dtmd.eu/wp-includes/blocks/button/index.php
 [Sat Mar 11 15:20:14.939446 2023] [autoindex:error] [pid 399670:tid
Press [Enter] to continue:[Sat Mar 11 09:49:30.156819 2023] [autoindex:error] [pid 399955:tid
139647745177344] [client **ip_address**:35074] AH01276: Cannot serve directory
/opt/bitnami/wordpress/wp-includes/blocks/button/: No matching DirectoryIndex
(index.html,index.html,index.htm,index.php) found, and server-generated
directory index forbidden by Options directive, referer:
https://www.dtmd.eu/wp-includes/blocks/button/index.php
139646860011264] [client **ip_address**:57055] AH01276: Cannot serve directory
/opt/bitnami/wordpress/wp-admin/css/: No matching DirectoryIndex
(index.html,index.html,index.htm,index.php) found, and server-generated
directory index forbidden by Options directive, referer: binance.com

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

### bndiagnostic was not useful. Could you please tell us why?

no usefull help

### Describe your issue as much as you can

I've got a problem with siteorigin on my website:
please see this threat, they ask if it might could be a problem from bitnami side?
https://siteorigin.com/thread/error-with-widget-settings/

while running your tool im also getting a meesage that there is less free buff/Cache available: we got a server with 16gb Ram. 
any ideas, on this point maybe as well? =)

Kind regards

**Comment by mdhont** [comment]
The bndiagnostic tool shows this error:

```
A high number of incoming requests originate from one or more unique IP
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.
```

Could you check this guide? 

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/
