### ISSUE TITLE
bitnami wordpress aws htaccess redirects rules not working?

### ISSUE THREAD

**Issue by SubZ82** [bitnami/vms#756]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

n/a

### bndiagnostic was not useful. Could you please tell us why?

n/a

### Describe your issue as much as you can

Hello,

As per the documentation I am adding htaccess rules to this file:

/opt/bitnami/apache/vhosts/htaccess/wordpress-htaccess.conf

Some entries in this file I did as test:

#testing redirect
<Directory "/opt/bitnami/wordpress/">
RewriteEngine On
Redirect 301 /test/ https://www.google.com 
</Directory>

#testing second redirect without directory 
RewriteEngine On
Redirect 301 /test1 /new

What am I doing wrong? neither one of these redirects is working at all?

My WordPress is installed within this directory if it makes any difference:

/opt/bitnami/wordpress/news-and-events/
I also tried replacing the directory path to the news-and-events too but it makes no difference, and i've restarted Apache.

Thank you
Rob

**Comment by SubZ82** [comment]
I also tried adding a redirect in the default wordpress-vhost.conf (tried this and the https one)

<VirtualHost 127.0.0.1:80 _default_:80>
ServerName www.example.com
ServerAlias *
DocumentRoot /opt/bitnami/wordpress
<Directory "/opt/bitnami/wordpress">
Options -Indexes +FollowSymLinks -MultiViews
AllowOverride All
Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
RewriteEngine On
RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
    Redirect 301 /wp-admin/ /test
    # END WordPress
</Directory>
Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
</VirtualHost>


You can see the line I added 'Redirect 301 /wp-admin /test

saved and restart apache but does not work.

**Comment by SubZ82** [comment]
This is what I followed. https://docs.bitnami.com/aws/infrastructure/lamp/administration/use-htaccess/ with regards to my first reply by trying to create a new <directory>htaccess block.

My block is the following with default wordpress rules and some test redirects at the bottom which don't work. It's the content in the .htaccess file at that location within /news-and-events/

<Directory "/opt/bitnami/wordpress/news-and-events">
# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /news-and-events/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /news-and-events/index.php [L]
</IfModule>

# END WordPress

Options +FollowSymLinks
RewriteEngine On
redirect 301 /wpdirectory /wp-new
RewriteRule ^/news-and-events/news/(.*)$ ./news-and-events/news/?id=$1
</Directory>

**Comment by SubZ82** [comment]
Ideally I would just like .htaccess to work, but I even tried changing all the confs to AllowOverride All and restart apache but still they aren't being picked up.

**Comment by SubZ82** [comment]
Can anyone help with this? Desperate to get it fixed, not having any working redirects is causing a real problem. Thanks.

**Comment by mdhont** [comment]
Can you try the following:

Add this line to `/opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf`:

    RewriteRule ^test1/?$ /new [R=301,L]

**Comment by SubZ82** [comment]
Yes sure @mdhont here is the block

VirtualHost 127.0.0.1:80 _default_:80>
ServerName www.example.com
ServerAlias *
DocumentRoot /opt/bitnami/wordpress
<Directory "/opt/bitnami/wordpress">
Options -Indexes +FollowSymLinks -MultiViews
AllowOverride All
Require all granted
    # BEGIN WordPress fix for plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
RewriteEngine On
RewriteRule ^bitnami/wordpress(/.*) $1 [L]
    # END WordPress fix for plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/htaccess/#basic-wp
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
    # END WordPress
RewriteRule ^test1/?$ /new [R=301,L]
  </Directory>
Include "/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf"
</VirtualHost>

I've restarted apache and tried to go to /test1/ but it does not redirect, I just get 404. I should say my WP is installed within this directory if it makes a difference: /opt/bitnami/wordpress/news-and-events$

rather than directory in /opt/bitnami/wordpress/ which is what the default confs are saying?

Thanks
Rob

**Comment by marianopeck** [comment]
Hi @SubZ82 . I think I am having the same issue. Any progress?

**Comment by SubZ82** [comment]
@marianopeck it does work - just you need to specify 'RewriteEngine On' above your rewrite code or redirect code e.g.:

RewriteEngine On
Redirect 301 /test/ https://www.google.com

This will work in the wordpress-htaccess.conf or any of the vhost conf files

**Comment by costaysol** [comment]
Hi SubZ82,

I'm struggling since weeks with the same issue. All tutorials are outdated and Bitnami hasn't published any updates yet to fix this issue. May I ask you to please post how the whole wordpress-vhost.conf file should look like in order to get .htaccess working? Do I also need to modify the wordpress-https-vhost.conf or any other file too?

Thanks in advance.

**Comment by gongomgra** [comment]
Hi @costaysol,

As mentioned in [our docs](https://docs.bitnami.com/virtual-machine/apps/wordpress/administration/use-htaccess/) `.htaccess` files are disabled by default due to performance and security reasons. If you want to enable them, update the `AllowOverride` parameter in both vhosts files for WordPress (`wordpress-vhost.conf` and `wordpress-https-vhost.conf`) by replacing the setting from `AllowOverride None` to `AllowOverride All` in both files and then restart Apache for changes to take effect

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

**Comment by costaysol** [comment]
Thank you very much. The issue was that after uploading modified wordpress-https-vhost.conf, file the change did not appear after opening the file to check. Anyways, this tutorial https://raddy.dev/blog/wordpress-aws-lightsail-security-headers/)helped additionally helped me to understand better how to do it. I'm glad that it's working now.

**Comment by gongomgra** [comment]
Hi @costaysol,

Thanks for letting us know. I'm glad it fixed your issue. We are closing this ticket as solved.
