### ISSUE TITLE
[WordPress] I mm having issue connecting to my site

### ISSUE THREAD

**Issue by obalolapius77** [bitnami/vms#76]
### Name and Version

aws lightsail bitnami/worpresss

### What steps will reproduce the bug?

bndiagnostic-tool
f4bb1647-0e52-758c-bd74-dd106af31880

### What is the expected behavior?

After updating some Plugins 

I discovered that am unable to access my website

### What do you see instead?
When i tried Https, i get Unable to connect

https://user-images.githubusercontent.com/30949149/177299329-78b9f209-2ec6-46dd-87f9-d5e8e4d430f9.png)

### Additional information

After using bndiagnotic tool 

This is the report id that was generated

f4bb1647-0e52-758c-bd74-dd106af31880

**Comment by jotamartos** [comment]
Please take a look at this other issue to disable the system's Apache and restart the Bitnami's one 

https://github.com/bitnami/vms/issues/26

**Comment by obalolapius77** [comment]
> 

Thanks @jotamartos ,
I had already done that from the steps [here](https://community.bitnami.com/t/failed-to-start-lsb-bitnami-init-script-apache-configuration-has-errors/101634/2)

Now resolved
