### ISSUE TITLE
[Dolibarr] Bitnami Installer for Windows 64

### ISSUE THREAD

**Issue by educrue** [bitnami/vms#760]
### Describe your issue as much as you can

How to get the latest version of dolibarr installer by Bitnami for Windows 64?. Thanks in advance.

**Comment by jotamartos** [comment]
As we announced in our blog post, we removed support for the installers in November 2022

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

However, Windows' installers were deprecated even before that date. The last one we released was in 2021 

https://downloads.bitnami.com/files/stacks/dolibarr/13.0.3-0/bitnami-dolibarr-13.0.3-0-windows-x64-installer.exe

We suggest you use the Virtual Machines we provide in bitnami.com to get the latest updates

https://bitnami.com/stack/dolibarr/virtual-machine

**Comment by educrue** [comment]
Thank you very much @jotamartos, I'll take your advice!!!
