### ISSUE TITLE
[Lightsail-bitnami-instance] Error establishing a database connection

### ISSUE THREAD

**Issue by ph0429** [bitnami/vms#761]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bdb6c79a-8604-2e53-543e-c0b9f8d74b6d

### bndiagnostic output

I am using bnsupport - see my other issue in which I cannot download bndiagnostic: https://github.com/bitnami/vms/issues/758

### bndiagnostic was not useful. Could you please tell us why?

ttps://docs.bitnami.com/aws/how-to/troubleshoot-permission-issues/;  https://aws.amazon.com/premiumsupport/knowledge-center/lightsail-wordpress-fix-database-errors/

### Describe your issue as much as you can

My site (https://www.meatfreed.com/wp-admin/) is showing an error, see below.
I am using AWS Lightsail with a Bitnami instance and Route 53 for my domain.

Yesterday 13 March, I increased the size of our Lightsail instance and the instance is now 40gb SSD. When I changed, the website worked.
However, I checked again today and I see the same error message that you can view: https://www.meatfreed.com/wp-admin/
In the SSH client on the Lightsail instance, I entered sudo df -h with the response below. I do not see any usage at 100% or close to 100%, the highest is 17%.
For the metrics, see attached - no burst in CPU utilisation.

We have tried the following to no avail:
- start/stop the instance
- reboot the instance
- reset file permissions per [https://docs.bitnami.com/aws/apps/wordpress/administration/understand-file-permissions/ ](https://docs.bitnami.com/aws/apps/wordpress/administration/understand-file-permissions/), [https://docs.bitnami.com/aws/how-to/troubleshoot-permission-issues/ ](https://docs.bitnami.com/aws/how-to/troubleshoot-permission-issues/))

Per https://aws.amazon.com/premiumsupport/knowledge-center/lightsail-wordpress-fix-database-errors/:
I have tried the following below.
Can anyone share how I can fix?

--
Result when trying Insufficient space on your volume of https://aws.amazon.com/premiumsupport/knowledge-center/lightsail-wordpress-fix-database-errors/:
bitnami@ip-172-26-2-159:~$ sudo df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            485M     0  485M   0% /dev
tmpfs            99M  2.9M   96M   3% /run
/dev/xvda1       40G  6.1G   32G  17% /
tmpfs           494M     0  494M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           494M     0  494M   0% /sys/fs/cgroup
/dev/xvda15     124M  278K  124M   1% /boot/efi
tmpfs            99M     0   99M   0% /run/user/1000

Result when trying Database service is down of https://aws.amazon.com/premiumsupport/knowledge-center/lightsail-wordpress-fix-database-errors/:
bitnami@ip-172-26-2-159:~$ test ! -f "/opt/bitnami/common/bin/openssl" && echo "Approach A"
 || echo "Approach B"
Approach B
bitnami@ip-172-26-2-159:~$ test -d /opt/bitnami/mariadb && echo "MariaDB" || echo "MySQL"
MySQL
bitnami@ip-172-26-2-159:~$ sudo /opt/bitnami/ctlscript.sh status mysql
mysql not running
bitnami@ip-172-26-2-159:~$ sudo /opt/bitnami/ctlscript.sh start mysql
/opt/bitnami/mysql/scripts/ctl.sh : mysql  could not be started
file '/etc/gonit/gonitrc' must be owned by you.

--
Result when trying to access /opt/bitnami/mysql/data/mysqld.log:
bitnami@ip-172-26-2-159:~$ /opt/bitnami/mysql/data/mysqld.log
-bash: /opt/bitnami/mysql/data/mysqld.log: Permission denied

Result per Incorrect login credentials in your WordPress settings section:
ERROR 2005 (HY000): Unknown MySQL server host 'localhost:3306' (22)
--

bitnami@ip-[ip]:~$ sudo df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            485M     0  485M   0% /dev
tmpfs            99M  2.9M   96M   3% /run
/dev/xvda1       40G  6.1G   32G  17% /
tmpfs           494M     0  494M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           494M     0  494M   0% /sys/fs/cgroup
/dev/xvda15     124M  278K  124M   1% /boot/efi
tmpfs            99M     0   99M   0% /run/user/1000

--

Error establishing a database connection
This either means that the username and password information in your wp-config.php file is incorrect or that contact with the database server at localhost:3306 could not be established. This could mean your host’s database server is down.

Are you sure you have the correct username and password?
Are you sure you have typed the correct hostname?
Are you sure the database server is running?
If you are unsure what these terms mean you should probably contact your host. If you still need help you can always visit the [WordPress Support Forums](https://wordpress.org/support/forums/).

**Comment by ph0429** [comment]
New code available after installing bndiagnostic: 1be03436-1844-c10c-f320-157bf334acce

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ? Mysql: Found possible issues
    ? Processes: Found possible issues
    ? Php: Found possible issues
 

 
[Apache]

Found recent Pagespeed related error messages in the Apache error log:
```
[Tue Mar 14 07:58:19.732668 2023] [pagespeed:error] [pid 9657:tid 
139826401629952] [mod_pagespeed **ip_address**-0 @9657] PageSpeed Serf fetch 
failure rate extremely high; only 0 of 193 recent fetches fully successful; is 
fetching working?

Press [Enter] to continue:
We suggest disabling pagespeed and check if that improves the behavior. Please 
check the following guide to disable Pagespeed:
 
https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespe
ed/#disable-pagespeed

Found recent error or warning messages in the Apache error log.
```
[Mon Mar 13 09:50:30.961162 2023] [proxy_fcgi:error] [pid 2665:tid 
139826971842304] [client **ip_address**:54085] AH01071: Got error 'PHP message: 
WordPress database error File './bitnami_wordpress/wp_uap_ranks.MYD' not found 
(OS errno 13 - Permission denied) for query SELECT rank_id
FROM wp_uap_affiliates
WHERE NOT EXISTS
 (SELECT 
wp_uap_ranks.id,wp_uap_ranks.slug,wp_uap_ranks.label,wp_uap_ranks.amount_type,wp_
uap_ranks.amount_value,wp_uap_ranks.bonus,w [Mon Mar 13 09:50:36.065353 2023] 
[proxy_fcgi:error] [pid 2665:tid 139827425048320] [client **ip_address**:54091] 
AH01071: Got error 'PHP message: WordPress database error File 
'./bitnami_wordpress/wp_uap_ranks.MYD' not found (OS errno 13 - Permission 
denied) for query SELECT rank_id
FROM wp_uap_affiliates
WHERE NOT EXISTS
Press [Enter] to continue:


 (SELECT 
wp_uap_ranks.id,wp_uap_ranks.slug,wp_uap_ranks.label,wp_uap_ranks.amount_type,wp_
uap_ranks.amount_value,wp_uap_ranks.bonus,w [Mon Mar 13 20:59:50.876673 2023] 
[proxy_fcgi:error] [pid 7817:tid 139827030591232] (70008)Partial results are 
valid but processing is incomplete: [client **ip_address**:59549] AH01075: Error 
dispatching request to : (reading input brigade)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Resources]

Your instance has little available RAM memory.
```
              total        used        free      shared  buff/cache   available
Mem:            987         344          64          37         577         440
Swap:           634           0         634
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Mysql]

Found recent error messages in the MySQL error log:

Most likely, you have hit a bug, but this error can also be caused by 
malfunctioning hardware.

```
Please check the following guide to troubleshoot MySQL issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ysql/

Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Processes]

One or more component's processes are not running:

[Processes]

One or more component's processes are not running:
Press [Enter] to continue:
```
mysql not running
```
You can try to restart the process with the following command:
 
    $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Php]

The following error appears in the 
/opt/bitnami/php/var/log/php-fpm.log:
```
[14-Mar-2023 01:07:47] WARNING: [pool www] server reached max_children setting 
(5), consider raising it

```
This error usually indicates PHP script execution is slow due to busy server 
resouces or buggy scripts. Please check the following guide to increase the 
number of PHP-FPM child processes:
 
https://docs.bitnami.com/general/apps/wordpress/configuration/configure-ph
pfpm-processes/
 
Press [Enter] to continue:

===== End of bndiagnostic tool output =====

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one.

**Comment by ph0429** [comment]
I tried to create a new instance, see the option that notes 10 USD/month per screenshot

<img width="1128" alt="Screenshot 2023-03-14 at 11 40 34" src="https://user-images.githubusercontent.com/47425504/224990295-4a9cbd50-d507-4676-a7a8-ed9112ee75d5.png">

With this instance, I am still seeing the same issue. My site is only a few pages and does not have heavy traffic. Is there a need to increase the instance size/resources to the next?

**Comment by ph0429** [comment]
I've increased the size of my instance although will need to look into this issue more since my site is only a few landing pages and does not have heavy traffic. I can close the issue for now, thanks for your help!
