### ISSUE TITLE
[Alfresco] Problem with SOLR after restart server

### ISSUE THREAD

**Issue by jlramv** [bitnami/vms#762]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f881e7e9-536d-8593-5493-8f04f31bdbbe

### bndiagnostic output

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Mar 14 11:51:46.793324 2023] [proxy_ajp:error] [pid 1049:tid 
140411985086208] [client **ip_address**:62711] AH00896: failed to make 
connection to backend: localhost
 [Tue Mar 14 11:51:46.798450 2023] [proxy:error] [pid 1072:tid 140411733305088] 
(111)Connection refused: AH00957: AJP: attempt to connect to **ip_address**:8009 
(localhost:8009) failed
 [Tue Mar 14 11:51:46.798584 2023] [proxy_ajp:error] [pid 1072:tid 
Press [Enter] to continue:
140411733305088] [client **ip_address**:62712] AH00896: failed to make 
connection to backend: localhost, referer: 
http://alfresco.unedmelilla.es/share/page/user/admin/dashboard

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

The suggested guided are no relationated with the issue

### Describe your issue as much as you can

After the first server restart after install the virtual machine, with no changes, only the networking configuration, SOLR doesn't  work. As an example of the issue, the Images Preview of the "Sample: Web Site Design Project" shows: 

"02140013 Wrapped Exception (with status template): 02140074 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/images.get.js': 02140073 Failed to execute search: +PATH:"/app:company_home/st:sites/cm:swsdp/cm:documentLibrary//*" +TYPE:"cm:content" +@cm\:content.mimetype:image/*"

**Comment by mdhont** [comment]
>  with no changes, only the networking configuration, SOLR doesn't work

Which changes did you make to the networking?

**Comment by jlramv** [comment]
Yes, I’ve executed "sudo ./configure_app_domain --domain alfresco.unedmelilla.es <http://alfresco.unedmelilla.es/>", but the problem persists.

**Comment by jlramv** [comment]
I've dowloaded the .ova file and created de VM. With no configuration changes, after the first reboot, the problem appears.

**Comment by pablodazevedo** [comment]
I have this same problem, but I'm using an instance directly in GCP .
I opened this ticket https://github.com/bitnami/vms/issues/887 yesterday.
