### ISSUE TITLE
Erro bncert

### ISSUE THREAD

**Issue by leocsum** [bitnami/vms#763]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7146092d-4042-3c7e-c600-4dad7d079d0f

### bndiagnostic output

The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Press [Enter] to continue:
The Apache configuration has errors:
```
AH00526: Syntax error on line 36 of
/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf: Invalid
command 'php_value', perhaps misspelled or defined by a module not included in
the server configuration
```
Please check the configuration.

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

.

### Describe your issue as much as you can

Good afternoon, I'm a lay user of the GitHub platform, so I'm sorry if I don't use the correct way to open a support.

I'm trying to run the Bncert tool.

and the following error appears.

[Warning: The web server configuration check failed. Please fix the configuration
error:
AH00526: Syntax error on line 36 of
/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf:
Invalid command 'php_value', perhaps misspelled or defined by a module not
included in the server configuration]

Verificando o arquivo menciondo no erro ele esta assim.

<Directory` "/opt/bitnami/wordpress/wp-content/plugins/akismet">
  # Only allow direct access to specific Web-available files.
  # Apache 2.2
  <IfModule !mod_authz_core.c>
  	Order Deny,Allow
  	Deny from all
  </IfModule>
  
  # Apache 2.4
  <IfModule mod_authz_core.c>
  	Require all denied
  </IfModule>
  
  # Akismet CSS and JS
  <FilesMatch "^(form\.js|akismet\.js|akismet\.css)$">
  	<IfModule !mod_authz_core.c>
  		Allow from all
  	</IfModule>
  	
  	<IfModule mod_authz_core.c>
  		Require all granted
  	</IfModule>
  </FilesMatch>
  
  # Akismet images
  <FilesMatch "^logo-(a|full)-2x\.png$">
  	<IfModule !mod_authz_core.c>
  		Allow from all
  	</IfModule>
  	
  	<IfModule mod_authz_core.c>
  		Require all granted
  	</IfModule>
  </FilesMatch>
</Directory>
php_value upload_max_filesize 256M
php_value post_max_size 256M
php_value max_execution_time 300
php_value max_input_time `300

Poderiam me ajudar?

**Comment by mdhont** [comment]
There seems to be an error on line 36 of `/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf`

```
AH00526: Syntax error on line 36 of
/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf: Invalid
command 'php_value', perhaps misspelled or defined by a module not included in
the server configuration
```

Did you make any changes in that file?

**Comment by leocsum** [comment]
A unica alteração que fiz foi php_value upload_max_filesize 256M php_value post_max_size 256M
