### ISSUE TITLE
[Azure RabbitMQ] package is not up-to-date

### ISSUE THREAD

**Issue by cat-mucius** [bitnami/vms#765]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Not relevant

### bndiagnostic was not useful. Could you please tell us why?

Not relevant

### Describe your issue as much as you can

Good day,

The https://bitnami.com/stack/rabbitmq/cloud/azure page says the version of RabbitMQ VM for Azure is `3.11.10`, the same version is also listed in [changelog.txt](https://bitnami.com/stack/rabbitmq/azuredebian-x64-nami/changelog.txt) - however, the **actual** version [available on Azure](https://portal.azure.com/#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/bitnami.rabbitmq) is the previous one, `3.11.9-2-r02`.

Are there any plans to update it?

**Comment by mdhont** [comment]
Version 3.11.10 has been released but unfortunately the time it takes to publish the asset can differ per cloud provider.

**Comment by cat-mucius** [comment]
Thank, Michael, I see that the [Azure image](https://portal.azure.com/#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/bitnami.rabbitmq) has been updated. :-)
