### ISSUE TITLE
Subscribing container image MediaWiki packaged by Bitnami to Azure Container Registry WikiContainerRegistry failed with error: Unknown.

### ISSUE THREAD

**Issue by JS-Ambiq** [bitnami/vms#766]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

I cant even get that far

### bndiagnostic output

Subscribing container image MediaWiki packaged by Bitnami to Azure Container Registry AmbiqITContainerRegistry failed with error: Unknown.

### bndiagnostic was not useful. Could you please tell us why?

I cant even get the container to even deploy

### Describe your issue as much as you can

When trying to "create" the container from the marketplace, microsoft throws this error:

Subscribing container image MediaWiki packaged by Bitnami to Azure Container Registry AmbiqITContainerRegistry failed with error: Unknown.

Which means nothing to me, so how do I get past this error? Microsoft, the champion of stupid meaningless error codes.

**Comment by jotamartos** [comment]
I'm glad to hear that you managed to solve the issue. For future reference, if you have a problem with the Bitnami containers, please post the question in this other forum

https://github.com/bitnami/containers/issues
