### ISSUE TITLE
[bitnami>] Wordpress multisite - creating SSL cert without the main domain

### ISSUE THREAD

**Issue by martinclo** [bitnami/vms#767]
### Describe your suggestion as much as you can

Hi,
I am managing a bitnami installation using the Wordpress Multisite version.

The wordpress multisite is configured like so:

domain.com (this domain resides somewhere else)
sub1.domain.com
sub2.domain.com
...

I need to generate SSL certificate for the subdomain only as the main site is not on the same server.  (using the bncert-tool)

If I issue the certificate request for just the sub domains, the tool will reconfigure the wordpress installation with the sub1.domain.com as the main domain then change my sub domains in the wordpress installation to:
 sub1.sub1.domain.com and
 sub2.sub1.domain.com

Is there a way to disable this functionnality?

**Comment by mdhont** [comment]
This guide shows how to configure WP multisite with different certificates:

https://docs.bitnami.com/aws/apps/wordpress-multisite/administration/use-different-ssl-certificates/

**Comment by martinclo** [comment]
Thank you for your prompt answer. I will be testing the configuration in a sandbox.
Would I then be able to use the bn-cert app normally afterward?

Kind regards

**Comment by mdhont** [comment]
In this case I recommend the manual approach using lego.

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
