### ISSUE TITLE
[Ghost on Azure] Redirecting non www to www

### ISSUE THREAD

**Issue by dwhiteddsoft** [bitnami/vms#768]
### Describe your issue as much as you can

I have a domain that is non-www domain (say example.com). I have https:// set up correctly but I always get the 301 back and it goes to www.example.com. I have played with a number of config settings but cannot seem to find the one that stops this.

**Comment by mdhont** [comment]
You need to configure the domain:

https://docs.bitnami.com/aws/apps/ghost/administration/configure-domain/

**Comment by dwhiteddsoft** [comment]
while mine is different, is the https:// screwing it up?
![image](https://user-images.githubusercontent.com/4751106/226064710-d6da8a55-2c57-4a35-9633-fd41ffd0a73d.png)

**Comment by dwhiteddsoft** [comment]
Changed to this as well to no avail
![image](https://user-images.githubusercontent.com/4751106/226071693-ebfff184-e40d-491c-a6aa-7915b241efd9.png)

**Comment by mdhont** [comment]
Did you try www.YOURDOMAIN.dev?
