### ISSUE TITLE
How to handle over 100 domains?

### ISSUE THREAD

**Issue by jason5591** [bitnami/vms#769]
The bncert does not support more than 100 domains. I've read that a separate certificate must be used/created. I have been unable to find directions on how to accomplish this. On Lightsail version of Bitnami LAMP 8.
Any steps/directions are greatly appreciated.

**Comment by jotamartos** [comment]
Correct! If you want different SSL certs, you can follow the alternative approach different times and specify the domains you want to include in that generated SSL cert when running the lego command 

https://github.com/bitnami/vms/issues/698#issuecomment-1476040561
