### ISSUE TITLE
[Wordpress] - PHP 7.4

### ISSUE THREAD

**Issue by medicto** [bitnami/vms#77]
### Describe your issue as much as you can

Please let us know how to install the Bitnami Wordpress AMI with PHP 7.4

In the AWS marketplace the versions available are with PHP 8.0, but my wordpress theme can work with PHP 7.4 only at the moment. 

Kindly share the link for the AMI of old PHP versions (specifically with PHP 7.$)

**Comment by medicto** [comment]
Thank you. But not at all helpful.


Thanks and Best Regards,
*Arpit Ahuja*
Medicto.com
+44 20 3960 5000

**Comment by medicto** [comment]
Hi, I could not find that AMI on AWS. Do you have the link for that AMI?


Thanks and Best Regards,
*Arpit Ahuja*
Medicto.com
+44 20 3960 5000

**Comment by jotamartos** [comment]
Hi, 

Please use this link 

https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:ami=ami-08022156664076928

or look for "ami-08022156664076928" in the us-east-1 region.

**Comment by jotamartos** [comment]
In Google, it's not possible to launch a deployment with a previous version. You can use a Bitnami solution in AWS or deploy a VM locally.
