### ISSUE TITLE
[Apache] Error 403 on sites without directory variable

### ISSUE THREAD

**Issue by jason5591** [bitnami/vms#770]
### Describe your issue as much as you can

When adding new sites to vhosts, I copied all our records from a previous host, but discovered that every site will display an error 403 page. I've tested with different owners and even 777 permissions, but it doesn't change.
Only adding in directory variables allow the sites to load, is this normal? Anyway to apply them system wide instead of adding 100+ directory variables?

**Example:**
```
<VirtualHost *:80>
ServerName domain.com
ServerAlias www.domain.com
DocumentRoot /sites/domain.com
</VirtualHost>
```
Does not work.

This does work:
```
<VirtualHost *:80>
  ServerName domain.com
  ServerAlias www.domain.com
  DocumentRoot /sites/domain.com
  <Directory "/sites/domain.com">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```

**Comment by jotamartos** [comment]
That's an Apache-related question and it's out of the scope of this support forum. We suggest you take a look at the official documentation to know more about the lines you added 

https://httpd.apache.org/docs/2.4/mod/core.html
