### ISSUE TITLE
[Moodle] Cannot run bncert

### ISSUE THREAD

**Issue by gourteacher** [bitnami/vms#774]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

this did no work as I had the same loop

### bndiagnostic output

Bitnami installation directory []: /opt/bitnami

Warning: The path does not seem to contain a valid Bitnami installation. Make
sure you have proper access rights, or choose a different directory.
Press [Enter] to continue:n
----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

Warning: The path does not seem to contain a valid Bitnami installation. Make
sure you have proper access rights, or choose a different directory.
Press [Enter] to continue:
----------------------------------------------------------------------------
Bitnami installation directory

### bndiagnostic was not useful. Could you please tell us why?

I had the same issue with failing to locate the bitnami install directory

### Describe your issue as much as you can

Hello,
I installed Bitnami moodle Docker version on an AWS EC2 instance.
I am using the Moodle docker version (https://hub.docker.com/r/bitnami/moodle)

Now, I want to generate a LetsEncrypt SSL certificate on the bitnami moodle instance.

I installed bncert as explained here:
https://docs.bitnami.com/virtual-machine/faq/administration/generate-configure-certificate-letsencrypt/

But when I run it, I keep having a forever loop like explained above.:

Tried older versions of bncert as suggested in other posts but this did not solve it.
 
Thanks.

**Comment by mdhont** [comment]
Unfortunately the bncert tool only works for singleVMs, and not for our containers. You can find more information on how to configure SSL for Apache based containers here:

https://github.com/bitnami/containers/tree/main/bitnami/apache

**Comment by gourteacher** [comment]
Ok. thanks. I have created the certs through another bitnami and moved them to moodle.
Would have been helpful to have that documented so we do not spend so much time trying.
Issue resolved for me.
