### ISSUE TITLE
[redmine] How can I transfer my Database and attchment (on bitnami-redmine3.4.5) to new server with version 5.0.1 install from redmine.org

### ISSUE THREAD

**Issue by clouds1203** [bitnami/vms#777]
### Describe your issue as much as you can

The original server : ubuntu 16.04 and redmine install with 'bitnami-redmine-3.4.5-0-linux-x64-installer.run'
The new server : ubuntu 20.04 and redmine 5.0.1 install step by step from redmine.org website

How can i transfer my Database and attchment from original server to the new one.
Thank you very much for your help.

**Comment by mdhont** [comment]
The following guide shows how to create a backup and how to restore it:

https://docs.bitnami.com/aws/apps/redmine/administration/backup-restore/

To restore it on a non-bitnami Redmine installation I recommend asking in the official Redmine forum.
