### ISSUE TITLE
[Odoo] Website editor can't load properly

### ISSUE THREAD

**Issue by sarvex** [bitnami/vms#778]
### Describe your issue as much as you can

bn-cert tool does make the necessary change to httpd.conf required for Odoo template. 

```conf
Header always set Content-Security-Policy "upgrade-insecure-requests;"
```

needs to be added to httpd.conf so that Website editor can load the editor properly. 

```xml
<IfModule headers_module>
    #
    # Avoid passing HTTP_PROXY environment to CGI's on this or any proxied
    # backend servers which have lingering "httpoxy" defects.
    # 'Proxy' request header is undefined by the IETF, not listed by IANA
    #
    Header always set Content-Security-Policy "upgrade-insecure-requests;"
    RequestHeader unset Proxy early
</IfModule>
```

This is causing problems for a lot of [developers][1] 

[1]: https://stackoverflow.com/questions/75441416/odoo-16-website-editor-i-cannot-edit-on-my-website

**Comment by jotamartos** [comment]
Hi @sarvex,

Thank you for the suggestion. This is not a bncert-related issue but a configuration one. I'll create a task to make this change in the application but can't provide with an ETA on when it'll be available. In the meantime, the info will be posted here for those users who run into the issue. 

Thanks

**Comment by etomProductions** [comment]
I know this issue has been closed, but did any one have clear fix for it? thank you

**Comment by jotamartos** [comment]
You can apply the changes that @sarvex suggested to fix the issue in the application.

**Comment by demuxer86** [comment]
I need to apply this fix, but where do i edit httpd.conf ?

**Comment by wild-bil** [comment]
@jotamartos, any updates on a fix from Bitnami?

**Comment by etomProductions** [comment]
I solved this by doing the following:
# "upgrade-insecure-requests;" Odoo Website Editor not working
sudo nano /opt/bitnami/apache2/conf/vhosts/odoo-https-vhost.conf

Am not really sure if there are better way as I could not find any clear info about it.

Hope this will help.

**Comment by jotamartos** [comment]
I'm glad to hear that you could solve the issue. This information will be really helpful for others

> edit /opt/bitnami/apache/conf/httpd.conf with below
> 
> <IfModule headers_module>
>     #
>     # Avoid passing HTTP_PROXY environment to CGI's on this or any proxied
>     # backend servers which have lingering "httpoxy" defects.
>     # 'Proxy' request header is undefined by the IETF, not listed by IANA
>     #
>     Header always set Content-Security-Policy "upgrade-insecure-requests;"
>     RequestHeader unset Proxy early
>     RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
>     RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}
> 
> </IfModule>

However, instead of editing the httpd.conf file, you should edit the Odoo's configuration files at /opt/bitnami/apache2/conf/vhosts folder. Can you give it a try and confirm it it works? You will need to restart Apache for the changes to take effect.

**Comment by wild-bil** [comment]
> RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
>     RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}

I had to add these to get it to work. Just adding "upgrade-insecure-requests;" didn't work for me in Version 17.

Thanks for your help gang!!
