### ISSUE TITLE
[PARSE] Setup Apache for WSS for live queries

### ISSUE THREAD

**Issue by sfraise** [bitnami/vms#780]
### Describe your issue as much as you can

I was able to get websockets working under WSS in Apache on the AWS Parse-Platform and in turn able to get the live queries working in an older version "4.3.0" through hours upon hours of trial and error.

Since there was no way to update to a new version in that build we setup a new server using the latest Bitnami parse-platform ami.

No matter what I do I can't for the life of me get WSS or even WS to resolve and in turn can't get the live queries running again.

I ensured that the Apache mod_proxy and mod_proxy_wstunnel were enabled and edited the Apache conf files just as before as well as tried several different variations of the rewrite conditions and proxypass/proxypass reverse.

I'm using the same elastic IP and domain name under the same load balancer and using the same security group I used in the prior build.

I was able to install the ssl certs using the alternative method and https is working fine.

What is different in this newer build from 4.3.0 that I'm missing in order to get this working?

An up to date working "how to" in the docs would be OUTSTANDING on getting live queries working in the AWS ami since parse isn't very useful without the live queries in my opinion.

DIAGNOSTIC TOOL GIVES:

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ? Apache: Found possible issues

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Mar 20 21:48:07.441704 2023] [proxy_http:error] [pid 184728:tid
Press [Enter] to continue:
139765634406144] [client **ip_address**:3674] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1, referer: https://MYDOMAIN.com/apps

[Mon Mar 20 21:48:08.974759 2023] [proxy:error] [pid 184730:tid 139766724933376]
(111)Connection refused: AH00957: http: attempt to connect to
**ip_address**:1337 (127.0.0.1:1337) failed

[Mon Mar 20 21:48:08.974794 2023] [proxy_http:error] [pid 184730:tid
139766724933376] [client **ip_address**:3684] AH01114: HTTP: failed to make
connection to backend: 127.0.0.1, referer: https://MYDOMAIN.com/apps

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP
addresses. This could indicate a bot attack. The following guide shows how to
check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/
Press [Enter] to continue:

===== End of bndiagnostic tool output =====

**Comment by mdhont** [comment]
Can you check the solution provided here:

https://stackoverflow.com/questions/68732634/parse-server-live-query-wss-connection-on-apache-403-error

**Comment by sfraise** [comment]
I'm the one that actually posted that solution a year and a half ago under
version 4.3.0.  At the same time I also discovered an issue with the
Bitnami ami having a mismatch of version numbers on parse that caused
issues as well.

Unfortunately there's no way to just update Parse 4.X to the next major
version under that old ami and no matter what I do with the latest Bitnami
version I can't get the livequery server working setting up apache just
like I did then.

There is a big difference this time.  Before it was an ssl issue, getting
https to resolve correctly and making sure Apache had the correct rewrite
rules and reverse proxy but ws:// worked out of the box and the livequery
server always started.

This time the livequery server just never even seems to start.

The only time it logs "livequery server has started" is if I change the
port for the livequery server to something else like 1338 but then it gives
a termination call and I have to reboot the entire server.

I'm going to try and setup redis and separate the livequery server out to
another instance and see if I can get it going that way which is how we
need to set it up anyway for production.  It's just odd that I can't get it
going under the single server configuration like I was able to before.

Here's what my Apache log looks like when I start Apache:
[Tue Mar 21 22:20:23.954077 2023] [ssl:warn] [pid 6406:tid 140491026897920]
AH01909: www.example.com:443:0 server certificate does NOT include an ID
which matches the server name
[Tue Mar 21 22:20:23.965535 2023] [ssl:warn] [pid 6415:tid 140491026897920]
AH01909: www.example.com:443:0 server certificate does NOT include an ID
which matches the server name
[Tue Mar 21 22:20:23.968825 2023] [mpm_event:notice] [pid 6415:tid
140491026897920] AH00489: Apache/2.4.56 (Unix) OpenSSL/1.1.1n configured --
resuming normal operations
[Tue Mar 21 22:20:23.968853 2023] [core:notice] [pid 6415:tid
140491026897920] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f
/opt/bitnami/apache/conf/httpd.conf'

Here's what my log looks like when I start Parse:
Termination signal received. Shutting down. [38;5;6mparse
[38;5;5m23:16:47.41 [0m [38;5;2mINFO [0m ==> ** Starting Parse **
Configuration loaded from /opt/bitnami/parse/config.json
warn: DeprecationWarning: The Parse Server option
'allowClientClassCreation' default will change to 'false' in a future
version.
warn: DeprecationWarning: The Parse Server option
'allowExpiredAuthDataToken' default will change to 'false' in a future
version.
allowClientClassCreation: true
allowCustomObjectId: false
allowExpiredAuthDataToken: true
appId: myappID
appName: parse-server
cacheMaxSize: 10000
cacheTTL: 5000
cloud: /opt/bitnami/parse/cloud/main.js
collectionPrefix:
customPages: {}
databaseURI: ***@***.***:27017/bitnami_parse
defaultLimit: 100
directAccess: true
emailVerifyTokenReuseIfValid: false
enableAnonymousUsers: true
enableExpressErrorHandler: false
enforcePrivateUsers: true
expireInactiveSessions: true
fileUpload:
{"enableForAnonymousUser":false,"enableForPublic":false,"enableForAuthenticatedUser":true}
graphQLPath: /graphql
host: 127.0.0.1
idempotencyOptions: {"ttl":300,"paths":[]}
liveQuery: {"classNames":["_User","_Role","Messages"]}
liveQueryServerOptions:
{"_appId":"myappID","_port":"1337","serverURL":"wss://
www.akashichealthrecords.com/parse/
","_masterKey":"wVKgangx0mxa","_logLevel":"VERBOSE","appId":"myappID","masterKey":"wVKgangx0mxa","cacheTimeout":5000,"server":{"_events":{"connection":[null,null]},"_eventsCount":5,"_connections":0,"_handle":{"reading":false},"_usingWorkers":false,"_workers":[],"_unref":false,"allowHalfOpen":true,"pauseOnConnect":false,"noDelay":false,"keepAlive":false,"keepAliveInitialDelay":0,"httpAllowHalfOpen":false,"timeout":0,"keepAliveTimeout":5000,"maxHeadersCount":null,"maxRequestsPerSocket":0,"headersTimeout":60000,"requestTimeout":0,"_connectionKey":"4:
127.0.0.1:1337"}}
logLevels:
{"triggerAfter":"info","triggerBeforeError":"error","triggerBeforeSuccess":"info"}
logsFolder: ./logs
maintenanceKeyIps: ["127.0.0.1","::1"]
masterKey: ***REDACTED***
masterKeyIps: ["127.0.0.1","::1"]
maxUploadSize: 20mb
mountGraphQL: false
mountPath: /parse
mountPlayground: false
objectIdSize: 10
pages:
{"enableRouter":false,"enableLocalization":false,"localizationFallbackLocale":"en","placeholders":{},"forceRedirect":false,"pagesPath":"./public","pagesEndpoint":"apps","customUrls":{},"customRoutes":[]}
playgroundPath: /playground
port: 1337
preserveFileName: false
preventLoginWithUnverifiedEmail: false
protectedFields: {"_User":{"*":["email"]}}
rateLimit: []
requestKeywordDenylist:
[{"key":"_bsontype","value":"Code"},{"key":"constructor"},{"key":"__proto__"}]
revokeSessionOnPasswordReset: true
scheduledPush: false
security: {"enableCheck":false,"enableCheckLog":false}
serverURL: https://akashichealthrecords.com/parse
sessionLength: 31536000
startLiveQueryServer: true
trustProxy: []
verifyUserEmails: false
jsonLogs: false
verbose: false
level: undefined
state: initialized

[14498] parse-server running on https://akashichealthrecords.com/parse

WARNING, Unable to connect to 'wss://www.akashichealthrecords.com/parse/'
as the URL is invalid. Cloud code and push notifications may be unavailable!


Thanks!

Spencer

**Comment by sfraise** [comment]
I just created a new instance using the latest Bitnami image with 5.4.3 and
everything seems to work fine except for the known bug in Parse trying to
add a new column with type array, object or geo (which obviously is not a
Bitnami issue).

There must have just been something with that previous Bitnami build that
wasn't quite right I guess.

One other question though...
I need to point over to an AWS redis elasticache but apparently the
"cacheAdapter" and "redisURL" keys don't work in the config.js like they
would in a regular build under index.js.

How do I go about setting this up in Bitnami?  I tried using the cli on
that previous build but said redis-cli was not recognized.

Thanks again!

Spencer

**Comment by mdhont** [comment]
> How do I go about setting this up in Bitnami?  I tried using the cli on that previous build but said redis-cli was not recognized.

Could you explain this? Also the following guide may be of help:

https://docs.bitnami.com/aws/apps/parse/get-started/connect/

**Comment by sfraise** [comment]
[image: image.png]
Following the Bitnami docs to connect to an external redis gives me this
screenshot above.

Following the regular Parse docs you would add this into an index.js:
  "cacheAdapter": "redisCache",
  "redisURL": "redis://
***@***.***:6379
"

Since this is all offloaded over to the /opt/bitnami/parse/config.json file
I tried adding that in there and it gives an error saying unrecognized key
pair for both cacheAdapter and redisURL.  If I remember correctly in the
older versions (4.X) there was a server.js file I could have added this
into but there is no such file in the newer builds.  Now it seems that
server.js file is split out into multiple files with the options getting
passed into the /opt/bitnami/parse/lib/ParseServer.js with the _options
variable.  Before I go hacking things up I figured I better reach out to
you on the correct way to set this up because if I ever go update the Parse
version I'm guessing that would be lost.

As it sits right now without redis, the simple app we're building is almost
unusably slow.  What we want to do is separate the livequery server as well
as the mongodb for scalability and use AWS redis elasticache for
performance.

Maybe I have to install redis-cli through npm or something here?  I guess I
assumed you would just add this to the config.json since the existing
standard convention is adding the parse server config settings there as you
would normally in the index.js.

Maybe I'm completely misunderstanding or missing something in the doc too,
I'm not sure.

I'm still not sure what was happening in the previous build regarding
websockets using the 5.0.0 AMI.  I did update the Parse server to 6.0.0 and
the Parse Dashboard to whatever the latest was there so maybe that messed
something up.  It threw a fit and all sorts of errors when I tried to
downgrade back to 5.4.3 or even 5.0.0 removing package-lock.json and
replacing the package.json for that version.  It's almost like something
got corrupted, even wiping out the node_modules folder didn't help before
re-running the install.  Whatever it was, a new clean install with the
latest Bitnami AMI with 5.4.3 worked like a champ and had it up and running
in under 10 minutes fully configured.

Just be aware that in these newer versions of the Parse Dashboard
regardless if in alpha or beta or whatever versions, you're unable to add a
new columns while selecting a column type of array, object or geo.  Once
you click on any of those 3 types you'll get a blank white screen and have
to refresh.  It's not a Bitnami issue but rather a Parse Dashboard issue
that they're aware of.  They said it was fixed in the latest Alpha version
but when I tried it the bug was still there.  If you get any support
tickets over it I'd recommend telling them to just create those types of
columns through the API Console->JS Console in the dashboard until the bug
is fixed.

Basically something like this:
// ADD ARRAY COLUMN THROUGH JAVASCRIPT API CONSOLE IN DASHBOARD
const mySchema = new Parse.Schema('MyClass');
mySchema
  .addArray('myColumn');
mySchema.save().then((result) => {
  console.log(result);
});
mySchema.update().then((result) => {
  console.log('added field');
});

By the way, I went ahead and posted a more thorough guide on setting up SSL
for https/wss with the Bitnami AMI under an AWS elastic IP and load
balancer in the Parse community at:
https://community.parseplatform.org/t/bitnami-parse-api-ssl-https-wss-with-apache-under-load-balancer-setup-guide/3345

I would use that as your "go-to" link for this from here on out instead of
my super vague StackOverflow post from a year and a half ago as there's
more that goes into it than just adding a rewrite and reverse proxy in one
Apache config file.  You need to uncomment the wstunnel module, set up the
right type of load balancer, set the targets and ports up correctly, setup
Route53 correctly for the load balancer, run the AWS SSL cert manager,
update the Apache ServerName values, install LetsEncrypt LEGO instead of
using the prepackaged bncert tool, generate the internal SSL certs and then
move them to the correct Bitnami directory.  After all of that, THEN you
configure the config.js correctly using https and wss. I've had a few
people reach out to me directly since I initially posted that issue a year
and a half ago asking how to actually do it so hopefully this helps more
for those that are coming from something like a LAMP stack or Wordpress
background and not very familiar with Apache or AWS.

I have to admit that my team had a pretty good laugh yesterday when I got
that email and clicked on the link only to find that you were referring me
to myself from a year and a half ago to solve my problem.  Granted I was in
much better shape then but you know you're screwed when you get referred to
yourself lmao.  If nothing else that helped take some stress off of a 5 day
insane brick wall we were hitting.  When I saw that new AMI release and it
actually worked right out of the box yesterday morning about a ton of
pressure came off of me.  We're putting a ton of eggs into this one Parse
basket and a year's worth of code would have been for not if we couldn't
get a new version of Parse working.

Since the Bitnami AMI build is a little different than a standard
Docker/Kubernete or DIY Parse build the few config/setup docs out there
don't really make much sense, especially for someone that is coming in
brand new to this stack under this AMI using Apache.  Especially if you
factor in that the defacto "go-to" doc for configuring the LiveQuery server
under a load balancer is geared towards Nginx (which is probably the better
play for websockets) it can be extremely confusing.  The Bitnami docs don't
even mention live queries and Apache setup at all for websockets and is
unknown territory for a lot of devs without much server-side experience.
Throw the super confusing AWS load balancing aspect in and it's probably
too overwhelming for a lot of people that would like to use the Parse AMI.
Probably to the point where they'd just walk away from it and go find
something else, it's a little much even for someone that's been around a
minute without any real documentation.

Sure you could pretty easily get a standard Parse server running without a
load balancer under https, but without live queries and without websockets
working over wss:// you're missing the most powerful aspect of Parse and at
that point there's not many reasons to use it.  My "go-to" would have been
Firebase if we didn't have to comply with HIPAA, AWS API Gateway with
websockets is almost like a mythical unicorn to use in any meaningful
understandable way for anything just a little complex and the few docs they
have seem to update every other day and completely change the game and
otherwise there's just not much out there with out of the box API websocket
capability.

Again, feel free to use the guide I just posted in the Parse community.  It
would probably be worthwhile to add some version of it to your docs since
most people that would be using that AMI for AWS would be using an elastic
IP and load balancer.  "IF" it were me building this AMI I'd just
pre-package the thing to be set up for the LiveQuery server and include the
alternative method of generating the SSL certs through LEGO and then just
add an underscore to the "startLiveQueryServer" option.  Then it's just a
matter of saying in your docs to remove that underscore if you want to
enable it.  Obviously pre-package it with the wstunnel module uncommented
as well, it's not hurting anything if someone doesn't want live queries and
would make Bitnami's life much easier on the support ticket side I'm sure.

All of that aside, once I figure out the AWS redis ElastiCache piece and
separating the LiveQuery server & MongoDB I'll add a new guide for that as
well.

A step-by-step guide on how to setup a scalable efficient Parse server with
live queries using the Bitnami AMI would be a very powerful I think.

Any input on the redis elasticache is appreciated.

Thanks again!

Spencer

**Comment by sfraise** [comment]
I installed redis-cli and am able to connect to the elasticache cluster in
the command line using:
redis-cli -h clustercfg.messenger.9vb0ub.usw2.cache.amazonaws.com --tls -c
-a mypassword -p 6379

However I'm still not sure how to set it in the parse config.

I get an error in the log saying:
node:internal/modules/cjs/loader:1024
  throw err;
  ^

Error: Cannot find module 'redisCache'

Same goes for trying to use 'redisURL'.

However I do not get an error when I put them in the liveQueryServerOptions
although I'm not sure if it's actually connecting and using the elasticache
cluster or not yet.

**Comment by mdhont** [comment]
Can you check if it's possible to load the modules following these steps?

https://docs.bitnami.com/aws/apps/parse/configuration/install-modules/

**Comment by sfraise** [comment]
I don't think trying to load extra modules to redis would be a solution to
the question.

Really what I'm asking here is how to set the "cacheAdapter": "redis" in
the config.json where cacheAdapter is a key option listed in the Parse docs.

When I try to set that and start the parse server I get a key not found
error.

In my log I can see the majority of config options however cacheAdapter is
not one of them and I'm still not 100% sure how the Bitnami AMI is handling
the config.json over to the actual Parse config.

Here's what I see in my log when I startup the parse server:
** Starting Parse **
Configuration loaded from /opt/bitnami/parse/config.json
warn: DeprecationWarning: The Parse Server option 'enforcePrivateUsers'
default will change to 'true' in a future version.
warn: DeprecationWarning: The Parse Server option
'allowClientClassCreation' default will change to 'false' in a future
version.
allowClientClassCreation: true
allowCustomObjectId: false
appId: myappID
appName: parse-server
cacheMaxSize: 10000
cacheTTL: 5000
cloud: /opt/bitnami/parse/cloud/main.js
collectionPrefix:
customPages: {}
databaseURI: ***@***.***:27017/bitnami_parse
defaultLimit: 100
directAccess: true
emailVerifyTokenReuseIfValid: false
enableAnonymousUsers: true
enableExpressErrorHandler: false
enforcePrivateUsers: false
expireInactiveSessions: true
fileUpload:
{"enableForAnonymousUser":false,"enableForPublic":false,"enableForAuthenticatedUser":true}
graphQLPath: /graphql
host: 127.0.0.1
idempotencyOptions: {"ttl":300,"paths":[]}
liveQuery: {"classNames":["_User","_Role","Groups","Messages"]}
liveQueryServerOptions: {"appId":"myappID","serverURL":"wss://
akashichealthrecords.com/parse/
","masterKey":"piKxQvBupzw7","logLevel":"INFO","cacheTimeout":5000,"server":{"_events":{"connection":[null,null]},"_eventsCount":5,"_connections":0,"_handle":{"reading":false},"_usingWorkers":false,"_workers":[],"_unref":false,"allowHalfOpen":true,"pauseOnConnect":false,"noDelay":false,"keepAlive":false,"keepAliveInitialDelay":0,"httpAllowHalfOpen":false,"timeout":0,"keepAliveTimeout":5000,"maxHeadersCount":null,"maxRequestsPerSocket":0,"headersTimeout":60000,"requestTimeout":0,"_connectionKey":"4:
127.0.0.1:1337"}}
logsFolder: ./logs
masterKey: ***REDACTED***
masterKeyIps: []
maxUploadSize: 20mb
mountGraphQL: false
mountPath: /parse
mountPlayground: false
objectIdSize: 10
pages:
{"enableRouter":false,"enableLocalization":false,"localizationFallbackLocale":"en","placeholders":{},"forceRedirect":false,"pagesPath":"./public","pagesEndpoint":"apps","customUrls":{},"customRoutes":[]}
playgroundPath: /playground
port: 1337
preserveFileName: false
preventLoginWithUnverifiedEmail: false
protectedFields: {"_User":{"*":["email"]}}
requestKeywordDenylist:
[{"key":"_bsontype","value":"Code"},{"key":"constructor"},{"key":"__proto__"}]
revokeSessionOnPasswordReset: true
scheduledPush: false
security: {"enableCheck":false,"enableCheckLog":false}
serverURL: https://akashichealthrecords.com/parse
sessionLength: 31536000
startLiveQueryServer: true
trustProxy: []
verifyUserEmails: false
jsonLogs: false
verbose: false
level: undefined

[18391] parse-server running on https://akashichealthrecords.com/parse
info: Parse LiveQuery Server started running
