### ISSUE TITLE
[WordPress Multisite] php-fpm maxing out CPU websites unresponsive

### ISSUE THREAD

**Issue by guytz72** [bitnami/vms#781]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

???????????

### bndiagnostic output

    ? Apache: Found possible issues
    ✓ Resources: No issues found
    ✓ Database: No issues found
    ? WordPress: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

I've deactivated the suggested plugin, still unresponsive server

### Describe your issue as much as you can

the diagnostic tool did not provide an id.

My server is unresponsive and has been for a few days. I restored from a back-up prior to the issues starting but have the same issue.

Getting this error in /opt/bitnami/php/var/log/php-fpm.log

WARNING: [pool www] server reached max_children setting (5), consider raising it
 
top shows the below:
 6435 daemon    20   0  527048 292636 138456 R  65.8  7.3   1:27.94 .php-fpm.bin                                                                                                                                                                             
 6437 daemon    20   0  522400 287088 138296 R  56.2  7.2   1:12.94 .php-fpm.bin                                                                                                                                                                             
 6441 daemon    20   0  419528 181660 136284 R  30.3  4.6   0:29.35 .php-fpm.bin                                                                                                                                                                             
 6432 daemon    20   0  716000 243068 146692 R  28.0  6.1   0:35.11 .php-fpm.bin                                                                                                                                                                             
 6482 daemon    20   0  468304 230608 136176 D   9.2  5.8   0:25.27 .php-fpm.bin   

I tried to alter the /opt/bitnami/php/etc/php-fpm.d/www.conf.default setting below then restarted the services but it still has the same error:

pm.max_children = 10

Not sure what else to do, hope someone can help.

**Comment by jotamartos** [comment]
Hi @guytz72 ,

If the bndiagnostic tool didn't provide you with an ID, it's probably because the machine is running out of memory and that's probably the reason why you are also running into issues with your website. How much memory is available in the instance? 

```
free -m
```

To run the diagnostic tool without problems, you can try stopping the services and running the tool again

```
sudo /opt/bitnami/ctlscript.sh stop
sudo /opt/bitnami/bndiagnostic-tool
sudo /opt/bitnami/ctlscript.sh start
```

If the problem is the available RAM memory, we suggest you increase the resources of the VM to avoid this performance issue.

**Comment by guytz72** [comment]
It was CPU not memory that was the problem.  I increased the instance type to make more CPU (and memory) available but it still did not help.

In the end it turned out to be a plugin causing the problem, and I fixed it by disabling all the plugins via the database, that allowed me access to the admin console.

My question still stands though, why after changing /opt/bitnami/php/etc/php-fpm.d/www.conf.default setting to the below:

pm.max_children = 10

..does the max number of .php-fpm.bin threads stay at 5?  One change that did work was setting a max for the number of executions for a single process, that stopped the worst of it but I still had issues until I removed the plugin.

**Comment by jotamartos** [comment]
To increase the number of PHP-FPM children, you will need to edit the `/opt/bitnami/php/etc/memory.conf` file which is symlinked to another one inside the `/opt/bitnami/php/etc/memory/` folder. Remember to restart PHP-FPM after applying this change.

**Comment by mikkelDalby** [comment]
Setting pm=ondemand in /opt/bitnami/php/etc/php-fpm.d/www.conf worked for me.
