### ISSUE TITLE
Bitnami Mediawiki  bitnami  "Error contacting the Parsoid/RESTBase server (HTTP 415)"

### ISSUE THREAD

**Issue by subesingh1981** [bitnami/vms#783]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ca04593a-3da2-0796-d5d2-22dfb35f3c5c

### bndiagnostic was not useful. Could you please tell us why?

Error contacting the Parsoid/RESTBase server (HTTP 415)

### Describe your issue as much as you can

Hi,

I am not able to use visual editor while bitnami mediawiki running in https mode. Facing below given error.

Error contacting the Parsoid/RESTBase server (HTTP 415)

Thanks,
Sube

**Comment by subesingh1981** [comment]
```
[Mon Mar 20 21:05:25.949837 2023] [authz_core:error] [pid 12778:tid 
140718194472704] [client **ip_address**:49670] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/, referer: 
https://www.abc.com/

**Comment by mdhont** [comment]
Did you make any changes? Can you describe the steps to reproduce the issue?

**Comment by subesingh1981** [comment]
step 1) Create a new instance using google market place. 
step 2) restore backup following instruction mentioned in web link https://docs.bitnami.com/aws/apps/mediawiki/administration/backup-restore/
step 3) Assign dns name to instance.
step 4) run the instance in https mode following instruction given in web link given below.
https://docs.bitnami.com/virtual-machine/faq/administration/generate-configure-certificate-letsencrypt/
https://docs.bitnami.com/virtual-machine/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
step 5) Login with admin user and try to edit a page using Visual Editor.

**Comment by mdhont** [comment]
Did you try to configure the domain?

    sudo ./configure_app_domain --domain YOUR.DOMAIN.COM

**Comment by subesingh1981** [comment]
Visual editor start working after running following command in bitnami directory. 

sudo ./configure_app_domain --enable-automatic-configuration

However it redirect the pages using IP address instead of domain name.

**Comment by mdhont** [comment]
Can you try with the domain name?

     sudo ./configure_app_domain --domain YOUR.DOMAIN.COM

**Comment by subesingh1981** [comment]
Yes, I tried( sudo ./configure_app_domain --domain YOUR.DOMAIN.COM) this command but it does not work. 
But when I follow/ the same command with sudo ./configure_app_domain --enable-automatic-configuration

**Comment by mdhont** [comment]
Could you explain why it does not work? Please note that you need to replace YOUR.DOMAIN with the actual domain.

 ./configure_app_domain --domain YOUR.DOMAIN.COM

**Comment by subesingh1981** [comment]
Its work for me once I updated $wgServer = 'htpps//domain.com' in LocalSettings.php
