### ISSUE TITLE
[WordPress] 504 Gateway Time-out

### ISSUE THREAD

**Issue by gtflip** [bitnami/vms#784]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic was not useful. Could you please tell us why?

Failed to upload

### Describe your issue as much as you can

We have a load balancer in front of the AWS Lightsail WordPress instance, which is where I assume the 504 error is coming from.

I rebooted the Lightsail instance since the website was unresponsive.  Now, when I log into the Lightsail instance, it's very slow and the load average is high.  I saw it hit 15 at one point.  Here's what it looks like right now:
```
top - 15:19:18 up  1:17,  1 user,  load average: 5.08, 5.02, 6.03
Tasks: 129 total,   5 running, 124 sleeping,   0 stopped,   0 zombie
%Cpu(s):  7.4 us,  0.6 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si, 92.0 st
KiB Mem :   498448 total,    11404 free,   308288 used,   178756 buff/cache
KiB Swap:   649996 total,   196360 free,   453636 used.    80512 avail Mem
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                 
 1877 mysql     20   0 1257816  56056   3784 S 25.6 11.2   9:52.11 mysqld.bin             
 2183 daemon    20   0 1273164   9384   3828 S 23.0  1.9   0:12.02 httpd.bin              
 2255 daemon    20   0  655544  98016  65856 R 17.3 19.7   7:25.16 .php-fpm.bin           
 2252 daemon    20   0  668232 110948  67308 R 15.3 22.3   7:38.14 .php-fpm.bin           
 1998 daemon    20   0  653664  97560  67092 R 10.5 19.6   7:34.60 .php-fpm.bin           
 2264 daemon    20   0  653468  93868  63048 S  7.3 18.8   7:21.97 .php-fpm.bin 
```
I don't see another way to contact Bitnami, so I'm submitting this issue.

**Comment by jotamartos** [comment]
It seems there are many php-fpm processes running in the instance. However, you have a 512MB of RAM instance which performance is really poor. We suggest you increase the resources of the VM to avoid this performance issue. 

In addition, we suggest you check this guide to know if someone is accessing your site with malicious intentions 

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-connections-bots-apache/
