### ISSUE TITLE
Cron Job not workingon AWS lightsale

### ISSUE THREAD

**Issue by Homedesign-hub** [bitnami/vms#788]
### Name and Version

bitbami/wordpress

### What steps will reproduce the bug?

We are trying to run a cron job
``` 
* * * * * php /opt/bitnami/wordpress/index.php -- wpaicg_cron=yes  
```
but it is not working

We tried to change the cron job code to be: 
```
* * * * * /opt/bitnami/php/bin/php  /opt/bitnami/wordpress/index.php -- wpaicg_cron=yes
```
It didn't work too...

### Are you using any custom parameters or values?

No

### What is the expected behavior?

We need the cron job to work

### What do you see instead?
```
bitnami@ip-172-26-4-7:~$ crontab -l
* * * * * /opt/bitnami/php/bin/php  /opt/bitnami/wordpress/index.php -- wpaicg_cron=yes
```

**Comment by Homedesign-hub** [comment]
The corn job is for the following plugin: https://gptaipower.com/how-to-add-cron-job/
It enable us to run the schedule tasks.
When we tried to run the corn on the server like that:
 `* * * * *sudo  /opt/bitnami/php/bin/php  /opt/bitnami/wordpress/index.php -- wpaicg_cron=yes`
We got the following error: 
`-bash: bitnami_application_password: command not found`

We also tried to add the command like that:
`* * * * * su daemon -s /bin/sh -c "cd /opt/bitnami/wordpress; /opt/bitnami/php/bin/php -q wp-cron.php"`
We go the error when we run the corn
`-bash: bitnami_application_password: command not found`

**Comment by mdhont** [comment]
Can you run this command?

    sudo /opt/bitnami/php/bin/php  /opt/bitnami/wordpress/index.php -- wpaicg_cron=yes

And tell me the output?

**Comment by Homedesign-hub** [comment]
We did fix our issue by adding the following cron:
`*/1 * * * * sudo php /opt/bitnami/coveti.com/index.php -- wpaicg_cron=yes`

**Comment by Homedesign-hub** [comment]
Thank you very much for your help

**Comment by Homedesign-hub** [comment]
We run the comand crontab -e and then added the code at the begining of the file
