### ISSUE TITLE
Shocked: As there is no documentation on WP-ROCKET by Bitnami

### ISSUE THREAD

**Issue by benytinck** [bitnami/vms#789]
### Describe your suggestion as much as you can

Bitnami WordPress stack on AWS lightsail is one of the useful solution for businesses to start online.

WordPress sites needs optimization to perform well.

I found the WordPress optimization documentation by Bitnami here: 
[https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/optimize-bitnami-wordpress/
](https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/optimize-bitnami-wordpress/
)
There are mention of plugins like; W3 Total Cache, WP Super Cache, and etc. But the most shocking thing is that there is no documentation on WP-ROCKET, one of the most important and useful WordPress optimization plugin used by millions.

I will request the Bitnami Team to provide a documentation on WP-ROCKET. Also, if the environment does not compatible with WP-ROCKET then there should be clearly mention about it.

Though the WP-ROCKET team has a documentation on it: https://docs.wp-rocket.me/article/670-hosting-compatibility#lightsail

But, still i need the confirmation from the Bitnami team to whether to use it or not on Wordpress-Bitnami-Lightsail environment.

**Comment by mdhont** [comment]
A Bitnami WordPress installation supports most plugins, however, for commercial plugins we recommend the plugin's own support channel, as it is not feasible for us to reproduce their specific functionalities.
