### ISSUE TITLE
[WordPress] sudo service bitnami restart failed

### ISSUE THREAD

**Issue by alex-kodr** [bitnami/vms#790]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

54f611ca-1b77-e3bd-353e-a222d489af03

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ✓ Connectivity: No issues found
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ✓ Apache: No issues found
    ✓ Php: No issues found
 

 
[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-03-22 13:49:17 0 [ERROR] Aborting

```
Please check the following guide to troubleshoot MariaDB issues:
 
Press [Enter] to continue:
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Wed Mar 22 11:38:24.151529 2023] [proxy_fcgi:error] [pid 1567478:tid 
139703919560448] [client **ip_address**:50609] AH01071: Got error 'PHP message: 
PHP Fatal error: Uncaught mysqli_sql_exception: Connection refused in 
/bitnami/wordpress/wp-content/plugins/kodr-black-list/kodr-black-list-ip.php:15
Stack trace:
#0 
/bitnami/wordpress/wp-content/plugins/kodr-black-list/kodr-black-list-ip.php(15):
 mysqli_connect()
#1 /opt/bitnami/wordpress/index.php(84): require_once('...')
#2 {main}
 throw
```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/

### bndiagnostic was not useful. Could you please tell us why?

Doesn't tell me how to connect to db

### Describe your issue as much as you can

Lightsail Bitnami instance had frozen. I've got apache & PHP back up and running. But can't get SQL (mariadb) running. I've looked in the log and can see some table crash errors. But can't connect to the database via ssh to repair and restart. If i try and start services `sudo /opt/bitnami/ctlscript.sh start` i get error:

`Job for bitnami.service failed because the control process exited with error code.`
`See "systemctl status bitnami.service" and "journalctl -xe" for details.`

The plugin error. I've deactivated the plugin, so not sure why it's still showing that in the bndiagnostic tool output. The main issue is connecting to the db.

Any ideas?

**Comment by alex-kodr** [comment]
Just to add to this. The issue is just connecting to MariaDB. Everything is fine in the apache log and that service is up and running fine. I've also checked memory and space and there are lots available. No matter what I try connecting to the database is unresponsive.

**Comment by jotamartos** [comment]
Hi @alex-kodr,

As the tool warned you, there is an error in the MariaDB's log and that's why it can't run 

```
2023-03-22 13:49:17 0 [ERROR] InnoDB: Missing FILE_CHECKPOINT at 10547337744 between the checkpoint 10547337744 and the end 10548540816.
2023-03-22 13:49:17 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2023-03-22 13:49:17 0 [Note] InnoDB: Starting shutdown...
2023-03-22 13:49:17 0 [ERROR] Plugin 'InnoDB' init function returned error.
2023-03-22 13:49:17 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2023-03-22 13:49:17 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-03-22 13:49:17 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2023-03-22 13:49:17 0 [ERROR] Aborting
```

You can find similar issues in this forum or online to fix that

https://github.com/bitnami/vms/issues?q=is%3Aissue+Missing+FILE_CHECKPOINT
