### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by belletinodev** [bitnami/vms#791]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b7c7349b-2701-eae5-32b8-efbb4c63113a

### bndiagnostic output

    ✓ Connectivity: No issues found
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ? Wordpress: Found possible issues
 

 
[Resources]

Your instance has little available RAM memory.
```
              total        used        free      shared  buff/cache   available
Mem:            989         618          88          86         283         146
Swap:           634         228         406
```
You could try to increase your instance's memory. Please check your cloud 
Press [Enter] to continue:
provider's documentation for more information.

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Mar 22 02:30:51.174312 2023] [proxy_fcgi:error] [pid 23720:tid 
139773377201920] [client **ip_address**:59355] AH01071: Got error 'PHP message: 
PHP Notice:  Unknown: file created in the system's temporary directory in 
Unknown on line 0', referer: 
https://belletino.ca/wp-admin/post.php?post=554&action=edit&app=uxbuilder&type=ed
itor

[Wed Mar 22 03:25:19.704230 2023] [autoindex:error] [pid 23720:tid 
139773142206208] [client **ip_address**:56756] AH01276: Cannot serve directory 
/opt/bitnami/wordpress/wp-includes/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
directory index forbidden by Options directive

[Wed Mar 22 11:06:16.862999 2023] [autoindex:error] [pid 23455:tid 
139772378994432] [client **ip_address**:45398] AH01276: Cannot serve directory 
/opt/bitnami/wordpress/wp-admin/maint/: No matching DirectoryIndex 
(index.html,index.html,index.htm,index.php) found, and server-generated 
Press [Enter] to continue:
directory index forbidden by Options directive,referer: 
https://belletino.ca/wp-admin/maint/index.php

[Wordpress]

Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

Found recent WordPress plugin related error messages in the Apache error log.
```
[Mon Mar 20 14:23:53.127008 2023] [autoindex:error] [pid 5907:tid 
139773049886464] [client **ip_address**:27160] AH01276: Cannot serve directory 
/opt/bitnami/wordpress/wp-includes/js/tinymce/plugins/compat3x/css/: No matching 
DirectoryIndex (index.html,index.html,index.htm,index.php) found, and 
server-generated directory index forbidden by Options directive, referer: 
Press [Enter] to continue:
https://belletino.ca/wp-includes/js/tinymce/plugins/compat3x/css/index.php

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/



### bndiagnostic was not useful. Could you please tell us why?

was able to fix the issue

### Describe your issue as much as you can

I have been trying to upload the file using FileZilla - SFTP and I am unable to as it says that "could not start the transfer" , moreover I have been unable to verify the apple domain using the file that I have to upload to. .well-known folder. Please help as I am loosing lot of customers and on potential business.

**Comment by belletinodev** [comment]
I am trying to upload the document to .well-known folder and It won't let
me. I need to verify domain to enable apple pay.

**Comment by belletinodev** [comment]
The issue exists when I try to upload the document for the apple verification. I want to add the apple pay to the web and the file that I have to add for the stripe, I am unable to. I keep receiving the error that it could not start transfer. I am using filezilla.

**Comment by mdhont** [comment]
I recommend the following guide:

https://docs.bitnami.com/aws/faq/administration/upload-files/

**Comment by belletinodev** [comment]
The error that I have reported was after following the step that is mentioned on the link you shared.

**Comment by mdhont** [comment]
If you need to upload files to a folder with restricted permissions I recommend using WinSCP as mentioned in the guide.

**Comment by belletinodev** [comment]
Now the problem is that it is now I am unable to add the SSH to my VM.

**Comment by belletinodev** [comment]
I am trying WinSCP and for that I am following the steps here :https://docs.bitnami.com/google/faq/administration/upload-files/#connect_ssh. But the public key I generated using the putty gen seems to be not working on GCP since it misses the username and expiry.

**Comment by belletinodev** [comment]
This is the error I keep on getting when I am adding the ssh key to the VM
nvalid key. Required format: <protocol> <key-blob> <username@example.com> or <protocol> <key-blob> google-ssh {"userName":"<username@example.com>","expireOn":"<date>"}

**Comment by mdhont** [comment]
Please check the following guide:

https://docs.bitnami.com/google/faq/get-started/connect-ssh/
