### ISSUE TITLE
[ResourceSpace] Instructions to Migrate to New Server Instance

### ISSUE THREAD

**Issue by amandaactionpact** [bitnami/vms#792]
### Describe your issue as much as you can

Hi,
Can you please create instructions to migrate a ResourceSpace installation to a new server instance as you do for Moodle?
https://docs.bitnami.com/aws/how-to/migrate-moodle/

**Comment by mdhont** [comment]
Unfortunately we don't have a specific guide for migrating ResourceSpace but I recommend checking the following guide to backup and restore the database:

https://docs.bitnami.com/general/apps/resourcespace/administration/backup-restore/

And for further instructions I recommend the official ResourceSpace documentation.
