### ISSUE TITLE
[WordPress] file replication in WP load balance systems

### ISSUE THREAD

**Issue by KingMilli75** [bitnami/vms#793]
### Describe your issue as much as you can

Hi There,

hope your all ok. Now i have some instances on AWS with the bitnami WP recent instal. Now create a load balanced system with a few instances.  Its separated out the dbase so on the instances only runs wp and dbase is a separated instance. Also there is a s3 bucket attached to it. There is WooCommerce running and some plugins. Now when there is a update this gets interesting. Instead of creating images and running new instances and deleting old ones i need something to replicate all the data from design to WP update/plugin update and so forth.

I know for example Unison is a way to go on ubuntu however i do not know how to make this part work on the BITNAMI instances. 

Now the part is how to replicate the data across multi instances. Example i have 3x instances running WP i push a design update and plugin update on 1 server, how to update this all to the others. 

Any help as i can not find it in the bitnami docs...

Cheers!

**Comment by KingMilli75** [comment]
Hi Jota,

Maybe not clear enough described. Unison does server replication as well so not only WP. Did you test unison...?

Example if there is a apache Patch or something similar and have have 5 identical Servers running how can I push the data to be replicated. Or a bit of an change in a config file or... This is not just the WP part.

Instead of manually doing on each server this update that why I ask for the replication part. The idea i to assign 1 ip of the server which is a master and the others do pull in the changed data. 

As far as I researched andbif I correctly understand it you have something similar on Google cloud pre packaged but for AWS I can not find it.

Maybe something to include in the packages...?

**Comment by jotamartos** [comment]
I think you should use a shared disk and mount it in every instance. You can create symlinks to link the Apache/WordPress/etc configuration with the one in the shared disk. That way, if you edit it in one instance, it'll be replicated in the rest of instances. Please note that this doesn't only require to sync the data, you will probably need to run commands and will also need to automate that. You should take a look at Ansible in case it works for you. As I mentioned above, this is out of the scope of this forum. You should investigate what's the best approach for you to solve this or find someone in your community who can help you with the configuration.

**Comment by KingMilli75** [comment]
Thank you i will i will investigate this part more. I thought maybe you guys had a out of the box solution for these kind of challenges...

And maybe somebody else has a better idea as well we are open for suggestions
