### ISSUE TITLE
[LAMP] Incorrect Docs under "Create A New MariaDB Database And User" Page

### ISSUE THREAD

**Issue by intile** [bitnami/vms#794]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

na

### bndiagnostic was not useful. Could you please tell us why?

Incorrect Docs under "Create A New MariaDB Database And User" Page

### Describe your issue as much as you can

After creating a LAMP Stack on AWS Lightsail, I went to start installing packages on the instance. I am used to Bitnami instances having custom built file structures similar to Wordpress or Node instances I have spun up in the past by Bitnami but when I logged via ssh, it was very similar to ec2 & the instructions on bitnami where not cohesive with the the file structures. I have added pictures to prove that it is a bitnami instance so there's no confusion.
<img width="1024" alt="Screenshot 2023-03-22 at 3 46 57 PM" src="https://user-images.githubusercontent.com/44528940/227019779-4b6f010d-826b-4320-8809-bb242cc526fa.png">
<img width="1624" alt="Screenshot 2023-03-22 at 3 46 08 PM" src="https://user-images.githubusercontent.com/44528940/227019784-368a4961-0d51-4f86-bb56-37b77a5a9072.png">

**Comment by jotamartos** [comment]
Hi @intile,

That's not a Bitnami instance. All Bitnami solutions use /opt/bitnami to store the scripts and data and it seems that instance doesn't have that folder. Apart from that, you are using the ec2-user user to access the instance when we configure the bitnami user. Can you contact the AWS support team to report this issue?

**Comment by intile** [comment]
> Hi @intile,
> 
> That's not a Bitnami instance. All Bitnami solutions use /opt/bitnami to store the scripts and data and it seems that instance doesn't have that folder. Apart from that, you are using the ec2-user user to access the instance when we configure the bitnami user. Can you contact the AWS support team to report this issue? 
> 
> 

Okay thank you for clarifying. Would you mind elaborating on what "packaged by Bitnami" means? I will contact them.

**Comment by jotamartos** [comment]
It's the way we title our solutions to let the user's know that it created by us. All Bitnami solutions follow the same configuration and directory structure so no matter if you use the VM, or a container/chart, you will find the same product. You will also benefit from the latest updates and security practices.

**Comment by intile** [comment]
> It's the way we title our solutions to let the user's know that it created by us. All Bitnami solutions follow the same configuration and directory structure so no matter if you use the VM, or a container/chart, you will find the same product. You will also benefit from the latest updates and security practices.

That is precisely why I am confused. You are explain me what I already thought was the case but previously you said that was an AWS instance but its tagged as if its Bitnami's. I believe the attached photos show that... I would expect because this instance is packaged by Bitnami, I would have a bitnami directory somewhere but I dont.

**Comment by intile** [comment]
> As I mentioned, there may be an issue in the Lightsail platform and it's not launching the correct VM. Did you contact them? Please note that we do not manage the available VMs in that platform, it's AWS who copies/moves the VMs from the Marketplace to that other platform.

I have not but I will contact them & if you would like I can inform you on what they say. If not, thanks again for pointing me in the right direction!

**Comment by jotamartos** [comment]
Of course! It'll be great if you can provide more information about what's happening. If something wrong is happening to you, it may be happening to others and that info will be really valuable for them as well. 

Thanks
