### ISSUE TITLE
[bncert-tool]: How to revert changes or delete a domain

### ISSUE THREAD

**Issue by celebraciones** [bitnami/vms#795]
### Describe your issue as much as you can

Is there a way to have bncert-tool remove a domain or revert any changes previously applied by the tool?. 

I know it creates a backup of three Apache2 files so in case the tool does not have a revert functionality, is there any guideline to revert them manually?. 

I wonder if only the three Apache2 files need to be recovered or if crontab, letsencrypt, or any other change needs to be done.

**Comment by jotamartos** [comment]
Our guide explains how to revoke the certificates 

https://docs.bitnami.com/general/how-to/understand-bncert/#manually-revoking-an-existing-certificate

**Comment by celebraciones** [comment]
Thank you @jotamartos, the summary of changes is also included in https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/ so I used it as a supplementary guide. 

My only last concern is about a line found in /opt/bitnami/properties.ini that includes "hostname=DOMAIN NAME". Was It added by bncert-tool? I don't recall adding it manually. What is the default value of such field for a new stack installation?

**Comment by jotamartos** [comment]
Hi @celebraciones,

It's probably bncert what is editing that file. You shouldn't worry about it, it's just a metadata file. You can remove that line if you want.
