### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by roprice** [bitnami/vms#798]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

849d4732-a328-71d6-0714-c651c26f503a

### bndiagnostic output

```
Domain list []: example.com

The following domains were not included: www.example.com. Do you want to add them? [Y/n]: y

Warning: The domain 'example.com' resolves to a different IP address than the 
one detected for this machine, which is '54.174.149.223'. Please fix its DNS 
entries or remove it. 
```

I keep getting this error when I try to run bncert. I have verified dozens of times that the domain does resolve to the IP address in question. I even tried editing /hosts/etc; that didnt work. http://54.174.149.223/ is my AWS Lightsail static IP for the site in question.

### bndiagnostic was not useful. Could you please tell us why?

I don't think it reveals why bncert thinks my domain doesn't resolve to http://54.174.149.223/

### Describe your issue as much as you can

AWS Lightsail, migrated WordPress instance, migrated from Pantheon.io, PHP is a bit out of date on Lightsail's OOB WP instance, hence the Apache errors in log. Domain does currently resolve to IP in question actually (you can verify this http://54.174.149.223/) just without SSL. I don't have a DNS Zone setup.

Thanks!

**Comment by mdhont** [comment]
It seems you are using example.com as the domain, or you replaced it to hide the domain of course. In any way, you can check where your domain points to here:

https://www.whatsmydns.net/
