### ISSUE TITLE
[<application>] <title>Force-strong-passwords mu-plugin for Bitnami Wordpress image is enabled by default - is it possible to disable it?

### ISSUE THREAD

**Issue by rsugathapala** [bitnami/vms#799]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

042720af-e187-eb4b-9552-cd0d50df5a51

### bndiagnostic was not useful. Could you please tell us why?

Question is not related to diagnostics

### Describe your issue as much as you can

Hi, 
We can see that the bitnami image for wordpress comes with the Must Use plugin (mu-plugin) - force-strong-passwords enabled by default. 
It looks like this plugin has been discontinued as its not compatible with PHP 8.1
When we go to /opt/bitnami/wordpress/wp-content/mu-plugins on the server we can see the folder for this plugin.
It appears this is causing some issues with our website, can you please advise, why this plugin comes enabled by default on the Bitnami Wordpress image?

Also, can you please advise the process to disable it?
Thanks

**Comment by mdhont** [comment]
Bitnami WordPress does not come with the MU plugin enabled. Here is a list of installed plugins:

| akismet                        | inactive | none   | 5.1     |
| all-in-one-wp-migration        | inactive | none   | 7.72    |
| all-in-one-seo-pack            | inactive | none   | 4.3.3   |
| amp                            | inactive | none   | 2.4.1   |
| google-analytics-for-wordpress | inactive | none   | 8.13.1  |
| hello                          | inactive | none   | 1.7.2   |
| jetpack                        | active   | none   | 11.9.1  |
| simple-tags                    | inactive | none   | 3.6.7   |
| w3-total-cache                 | inactive | none   | 2.3.0   |
| wp-mail-smtp        | inactive | none   | 3.7.0   |
