### ISSUE TITLE
Hi   I launched  VM  on vmware  and    installed   bitnami review board  .  I am able to access through ip  but  not able to access thorugh hostname   getting 400 error.    can some  one help on this his    

### ISSUE THREAD

**Issue by giribc** [bitnami/vms#801]
### Name and Version

bitnami/reivewbaord 5.01 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When i type Host  server domain  name not getting ip 

connection timed out; no servers could be reached

### Are you using any custom parameters or values?

i   When i type Host  server domain  name not getting ip 

connection timed out; no servers could be reached

### What is the expected behavior?

When i type Host  server domain  name not getting ip 

connection timed out; no servers could be reached

### What do you see instead?

When i type Host  server domain  name not getting ip 

connection timed out; no servers could be reached

### Additional information

When i type Host  server domain  name not getting ip 

connection timed out; no servers could be reached

**Comment by giribc** [comment]
Hi 
I have configured  the same  ,  and   restarted the ./ctl script  . Now   iam getting bad request 400 error 
Error :   Host is  resolving local ip as well
==============================
   host att-reviewboard.capgemini.com
;; connection timed out; no servers could be reached

Please find  nic configuration: 
root@att-reviewboard:/opt/bitnami# ifconfig
ens32: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.31.141.199  netmask 255.255.255.224  broadcast 172.31.141.223
        inet6 fe80::20c:29ff:fe5a:5065  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:5a:50:65  txqueuelen 1000  (Ethernet)
        RX packets 260  bytes 34862 (34.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 234  bytes 40856 (39.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 18  base 0x2000

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 77  bytes 13270 (12.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 77  bytes 13270 (12.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0






./configure_app_domain --domain att-reviewboard.capgemini.com
Configuring domain to att-reviewboard.capgemini.com
2023-03-28T10:27:52.442Z - info: Saving configuration info to disk
reviewboard 10:27:52.76 INFO  ==> Setting Review Board application domain
reviewboard 10:27:56.87 INFO  ==> ** Reloading Apache configuration *

**Comment by giribc** [comment]
Hi  After configuring  no with ip  also iam  getting   bad request 400  error 

could you please help quickly

**Comment by mdhont** [comment]
Can you run the bndiagnostic tool and share the code at the end of the output?

    sudo /opt/bitnami/bndiagnostic-tool

**Comment by giribc** [comment]
Hi  md Host 
Please find the output of diag  tool
root@att-reviewboard:/opt/bitnami/apache/conf/vhosts# cd /opt/bitnami/
root@att-reviewboard:/opt/bitnami# ./ctlscript.sh restart apache
Restarted apache
root@att-reviewboard:/opt/bitnami# ./ctlscript.sh stop
Stoping services..
root@att-reviewboard:/opt/bitnami# ./ctlscript.sh start
Starting services..
root@att-reviewboard:/opt/bitnami# sudo /opt/bitnami/bndiagnostic-tool
----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

\^C
root@att-reviewboard:/opt/bitnami# sudo /opt/bitnami/bndiagnostic-tool
----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

\/
The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:


===== Begin of bndiagnostic tool output =====


    ✓ Apache: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues



[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/


===== End of bndiagnostic tool output =====

**Comment by giribc** [comment]
apache logs 
root@att-reviewboard:/opt/bitnami# tail -f /opt/bitnami/apache/logs/error_log
[Tue Mar 28 11:16:49.062128 2023] [mpm_event:notice] [pid 1512:tid 140666224228160] AH00493: SIGUSR1 received.  Doing graceful restart
[Tue Mar 28 11:16:49.450152 2023] [ssl:warn] [pid 1512:tid 140666224228160] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Mar 28 11:16:49.451362 2023] [mpm_event:notice] [pid 1512:tid 140666224228160] AH00489: Apache/2.4.54 (Unix) OpenSSL/1.1.1n mod_wsgi/4.9.4 Python/3.8 SVN/1.14.2 configured -- resuming normal operations
[Tue Mar 28 11:16:49.451380 2023] [core:notice] [pid 1512:tid 140666224228160] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Wed Mar 29 09:15:05.823405 2023] [mpm_event:notice] [pid 1512:tid 140666224228160] AH00491: caught SIGTERM, shutting down
[Wed Mar 29 09:15:06.288614 2023] [mpm_event:notice] [pid 61617:tid 140576010180416] AH00489: Apache/2.4.54 (Unix) OpenSSL/1.1.1n mod_wsgi/4.9.4 Python/3.8 SVN/1.14.2 configured -- resuming normal operations
[Wed Mar 29 09:15:06.288740 2023] [core:notice] [pid 61617:tid 140576010180416] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Wed Mar 29 09:15:13.214843 2023] [mpm_event:notice] [pid 61617:tid 140576010180416] AH00491: caught SIGTERM, shutting down
[Wed Mar 29 09:15:23.416866 2023] [mpm_event:notice] [pid 62995:tid 140401746364224] AH00489: Apache/2.4.54 (Unix) OpenSSL/1.1.1n mod_wsgi/4.9.4 Python/3.8 SVN/1.14.2 configured -- resuming normal operations
[Wed Mar 29 09:15:23.417010 2023] [core:notice] [pid 62995:tid 140401746364224] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'

**Comment by giribc** [comment]
hi 
Need urgent support ..     could you please help on this  my mailid is giri.babu@capgemini.com

**Comment by mdhont** [comment]
Please accept my apologies for the late reply. Could you share the 16 digit code at the end of the bndiagnostic output?

**Comment by giribc** [comment]
I have made some changes   .  aim able to access the page with ip  but not with domain name   
login as: bitnami
bitnami@172.31.141.199's password:
Linux att-reviewboard.capgemini.com 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
       ___ _ _                   _
      | _ |_) |_ _ _  __ _ _ __ (_)
      | _ \ |  _| ' \/ _` | '  \| |
      |___/_|\__|_|_|\__,_|_|_|_|_|

  *** Welcome to the Review Board packaged by Bitnami 5.0.1-3                    ***
  *** Documentation:  https://docs.bitnami.com/virtual-machine/apps/reviewboard/ ***
  ***                 https://docs.bitnami.com/virtual-machine/                  ***
  *** Bitnami Forums: https://github.com/bitnami/vms/                            ***
Last login: Thu Apr  6 10:17:58 2023 from 10.99.148.139
bitnami@att-reviewboard:~$
bitnami@att-reviewboard:~$ sudo su
root@att-reviewboard:/home/bitnami# cd /opt/bitnami/
root@att-reviewboard:/opt/bitnami# ls
apache        bndiagnostic-regex.ini  gonit           python       var
apache2       bndiagnostic-tool       mariadb         reviewboard
bncert        common                  memcached       scripts
bncert-tool   configure_app_domain    nami            stats
bndiagnostic  ctlscript.sh            properties.ini  subversion
root@att-reviewboard:/opt/bitnami# ./bndiagnostic-tool
----------------------------------------------------------------------------
Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

\/
The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:


===== Begin of bndiagnostic tool output =====


    ? Apache: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues



[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Apr 11 21:39:32.502567 2023] [core:error] [pid 203771:tid 140573046458112]
[client **ip_address**:45196] AH10244: invalid URI path
(/cgi-bin/.%2e/%2e%2e/%2e%2e/%2e%2e/Windows/win.ini)
 [Tue Apr 11 21:39:32.658775 2023] [core:error] [pid 5983:tid 140573046458112]
[client **ip_address**:18853] AH10244: invalid URI path
(/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32
%65/%%32%65%%32%65/%%32%65%%32%65/Windows/win.ini)
Press [Enter] to continue:

**Comment by mdhont** [comment]
Could you check the end of the output of the bndiagnostic tool? It should show a long 16 digit code. Could you share that with me>
