### ISSUE TITLE
[Drupal] Is AWS Lightsail Drupal Certified by Bitnami 9.2.7-5 designed to manage multisites?

### ISSUE THREAD

**Issue by MarcoDelCorto** [bitnami/vms#802]
### Describe your issue as much as you can

The version in question is designed to manage multisites (multiple domains that run on the web server apache)?
thanks

**Comment by jotamartos** [comment]
Hi @MarcoDelCorto,

Thanks for your interest. That solution runs a single-site version of Drupal. We do not have any guide regarding how to move/configure the Bitnami Drupal solution to multisite, but you will probably find something in the Drupal's official documentation. Please remember the Drupal files are inside the /opt/bitnami/drupal folder and you will find the Apache-related configuration inside the /opt/bitnami/apache/conf/vhosts folder.
