### ISSUE TITLE
[Wordpress] Desire Case Insensitive URLS

### ISSUE THREAD

**Issue by mbisque** [bitnami/vms#803]
### Describe your issue as much as you can

I'd like my wordpress site to be case insensitive.

Bitnami support solved this question for me already but the old URL is gone (here just in case it helps internally: https://community.bitnami.com/t/desire-case-insensitive-urls/64996/5?u=matt6)

The old solution told me to edit:
/opt/bitnami/apache2/conf/httpd.conf

And add this:
(I cannot get the editor to put in the code)

But I'm on a new AWS bitnami wordpress stack and cannot locate htaccess.conf.

Can you help me find htaccess.conf? 

Thank you in advance.

**Comment by mdhont** [comment]
You can find it here:

```
/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf
```

**Comment by mbisque** [comment]
Thank you!  My site now serves /wp-content/hellO.pHp as  /wp-content/hello.php.
