### ISSUE TITLE
[WordPress] How to Backup WordPress site the best way in this environment

### ISSUE THREAD

**Issue by benytinck** [bitnami/vms#804]
### Describe your issue as much as you can

I am running a WordPress website on lightsail-bitnami-wordpress environment.

I am really worried about taking backups of my WordPress site.

I have these questions about backup:

- Currently I am using AWS Snapshots to keep backup of entire server including application. Is it enough?
- Should I use backup plugins like; UpdraftPlus, Jetpack Backup?
- Will using plugin create security loopholes by storing the backup in the server?

Also, I will request the bitnami team to create a backup documentation if possible.

**Comment by jotamartos** [comment]
>Currently I am using AWS Snapshots to keep backup of entire server including application. Is it enough?

If you are using snapshots, it's the perfect way to backup your site. If something happens, you can easily recover a previous snapshot and continue running your site. 

>Should I use backup plugins like; UpdraftPlus, Jetpack Backup?

This helps you backup the WordPress' files but not the certificates or the changes in the Apache's configuration files. The snapshot covers everything. 

>Will using plugin create security loopholes by storing the backup in the server?

Those files shouldn't be available online so this shouldn't be a problem. 

>Also, I will request the bitnami team to create a backup documentation if possible.

We have some guides available in our documentation 

https://docs.bitnami.com/aws/faq/administration/backup-restore-server/
https://docs.bitnami.com/general/how-to/migrate-wordpress/#how-to-export-wordpress-content

**Comment by benytinck** [comment]
Thanks.
