### ISSUE TITLE
[Nginx-Proxy-Manager] Any plans for NPM packed in a nice VM?

### ISSUE THREAD

**Issue by BobWs** [bitnami/vms#805]
### Describe your suggestion as much as you can

Hello,

I am curious to know if you have any plans to package Nginx-Proxy-Manager into a virtual machine. Although I am currently using the Docker version, its limitations restrict me from utilizing NPM for LAN-specific purposes due to Docker's inability to communicate effectively with the host. Hence, I believe if NPM can be made available as a virtual machine, the issue could be resolved. For reference, I am operating NPM on a Synology NAS.
[Nginx-Proxy-Manager](https://nginxproxymanager.com/)

**Comment by mdhont** [comment]
Unfortunately we currently have no plans to add NPS as a vm.
