### ISSUE TITLE
[WordPress] Weak Ciphers Enabled issue

### ISSUE THREAD

**Issue by KingMilli75** [bitnami/vms#806]
### Describe your issue as much as you can

Hi There, 

we did a scan on our site and it listed in this Weak Ciphers Enabled as a security risk. However we do not know how to change this into best practice as for example its specific and to which value to modify it so that the site does not break. 

Any tips how to change this or how to make it much appreciated?

Keep up the work!

**Comment by jotamartos** [comment]
The cipher suites and protocols that Apache accepts are configured in the /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf file. You can modify those parameters and restart the webserver for the changes to take effect.

**Comment by KingMilli75** [comment]
Thanks a million.

Is there any recommended value string to be used to ensure compatibility with all the browsers?

Dragan
