### ISSUE TITLE
[Bitnami wordpress AWS] autorenewal failed

### ISSUE THREAD

**Issue by alexla** [bitnami/vms#811]
### Describe your issue as much as you can

I had this working for a while but the latest autorenewal failed. The .well-known folder is empty. all I found was this:

> Certificates not renewed automatically
> 
> In order to renew certificates in cron jobs, the Bitnami HTTPS Tool configures Let’s Encrypt to perform a HTTP challenge to verify the domains are still valid. This way it is not required to restart the web server and suffer downtime.
> 
> When running this tool, it performs the following actions:
> 
>     Create a directory at /opt/bitnami/apps/letsencrypt/.well-known, and map it to http://SERVER-IP by configuring the web server. This directory will be used by Let’s Encrypt for storing a challenge file to verify the domains.
>     Check a sample file created inside .well-known can be fetched from http://SERVER-IP, to ensure the web server configuration is valid.
> 
> If the check fails (a sample file created inside .well-known is not accessible), it is highly probable that Let’s Encrypt will fail to perform the HTTP challenge and therefore the automatic certificate renewal will fail. Please check the following scenarios:
> 
>     The web server configuration is invalid. Check that files inside /opt/bitnami/apps/letsencrypt/.well-known are accessible at http://SERVER-IP/.well-known for all domains.
> 
>     Custom redirections are enabled. In such case you need to disable the redirection when accessing /.well-known by adding the following rule, right before the line performing the redirection, inside the virtual host:
> 
>       RewriteCond %{REQUEST_URI} !^/\.well-known
> 
>     mod_proxy is used for handling requests to the application (without using a directive). In this case, to avoid /.well-known being affected by the proxy configuration, you need to add the line below before any “Location” directive.
> 
>       ProxyPass /.well-known !
> 
>     mod_proxy is used for handling requests to the application within a directive. In this case, to avoid /.well-known being affected by the proxy configuration, you need to add the line below after any “Location” directive.
> 
>       <Location /.well-known>
>           ProxyPass !
>       </Location>

as the well-known folder is empty. is that supposed to be like that? Where would I make those above changes to the app conf? The Wordpress app conf folder? The apache conf? the letsencrypt conf folder?

Thanks

**Comment by mdhont** [comment]
Please check the following guide:

https://docs.bitnami.com/aws/how-to/understand-bncert/#certificates-not-renewed-automatically

**Comment by alexla** [comment]
As you can see, the process is quoted above but that did not help. Weher are these changes to be made? The Wordpress app conf folder? The apache conf? the letsencrypt conf folder?

**Comment by mdhont** [comment]
My apologies for the late answer, you can find detailed instructions about where you can manually install a new certificate here:

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
