### ISSUE TITLE
[WordPress] How to update the instance deployed from older ami to the latest

### ISSUE THREAD

**Issue by NDokz** [bitnami/vms#812]
I have an instance that deploied from bitanami ami id "bitnami-wordpress-5.3.2-3-r04-linux-debian-9-x86_64-hvm-ebs-high-availability-nami"
The versions of LAMP are bellow,
・Debian--9
・apache--2.4.41
・MySQL--5.7.mysql_aurora.2.11.0
・PHP--7.3.13
and
・wordpress--5.3.4

I want to update these versions to the latest.
How can I update them ?
Should I update them individually?
or Is there a good way to update it all at once?

Thanks,
NDokz

**Comment by jotamartos** [comment]
You should migrate your data from that instance to a new one with the latest versions of the different components. This guide explains how to migrate the WordPress' data to that new instance 

https://docs.bitnami.com/aws/how-to/migrate-wordpress/

**Comment by NDokz** [comment]
Hi, jotamartos
Thank you for how to migration of wordpress.

Is there any  infomation or guide of others compornets(apache, MySQL, PHP, Debian)?

**Comment by jotamartos** [comment]
If you export the WordPress' data, the database information will be also migrated. Regarding Apache, you will need to generate new SSL certs (or move the current ones) in the new instance. If you applied other changes to the PHP's or the system's configuration, you will need to redo the changes in the new instance.

**Comment by brianatbisley** [comment]
If you use https you should obtain a certificate for your new site before you 'restore' (All-in-One WP Migration) your migration data as well as change your routing to your new IP (if neccessary). If you don't then all of your old url's will be replaced with the site's IP address.   This will only set you back a day or so.  Migrating also seems to break Yoast breadcrumbs.

**Comment by jotamartos** [comment]
Thanks for the information @brianatbisley. It'll be helpful for those migrating the data.
