### ISSUE TITLE
Opencart AWS version 3

### ISSUE THREAD

**Issue by pulseimpulse** [bitnami/vms#814]
### Describe your issue as much as you can

How do i install the opencart version 3? instead of the currently only available to install version 4?

**Comment by pulseimpulse** [comment]
weird, i can only see version 4 instances in that

**Comment by pulseimpulse** [comment]
ahh, it is available in the Bahrain server region but not in the UAE region

**Comment by gongomgra** [comment]
Hi @pulseimpulse,

Thanks for your message. if that region is newer than the image you are looking for, then you will have to use it from another region in which the Opencart 3.x image was previously released. Sorry for the inconvenience. I'm also closing this ticket.
