### ISSUE TITLE
[<Apache>] <Service doesn't start>

### ISSUE THREAD

**Issue by devpbeat** [bitnami/vms#815]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ea3a3b93-f04e-bf29-c786-fbb38198e5ac

### bndiagnostic output

Press [Enter] to continue:
[Tue Mar 28 19:54:46.136213 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL 
Library Error: error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested 
asn1 error (Type=PKCS8_PRIV_KEY_INFO)
 [Tue Mar 28 19:54:46.136220 2023] [ssl:emerg] [pid 2647:tid 140400966600512] 
AH02312: Fatal error initialising mod_ssl, exiting.
 [Tue Mar 28 19:54:46.136225 2023] [ssl:emerg] [pid 2647:tid 140400966600512] 
AH02564: Failed to configure encrypted (?) private key www.example.com:443:0, 
check /opt/bitnami/apache/conf/bitnami/certs/server.key

### bndiagnostic was not useful. Could you please tell us why?

The guide is not helping me to fix the bug

### Describe your issue as much as you can

I recently uploaded my *.domain cert with its key, apache service is not being started.
I debuged them, with the following guide and it returns the same output
https://docs.bitnami.com/azure/apps/erpnext/administration/check-ssl-certificate/
I would like to get help because the service it's not running

**Comment by gongomgra** [comment]
Hi @devpbeat,

According to the Apache logs, it looks like the SSL certificate is waiting a password that you didn't provide correctly. Can it be the case? If not, can you retry to recreate the SSL certificates?

```
[Tue Mar 28 19:54:46.136036 2023] [ssl:error] [pid 2647:tid 140400966600512] AH02578: Init: Unable to read pass phrase [Hint: key introduced or changed before restart?]
[Tue Mar 28 19:54:46.136106 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL Library Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
[Tue Mar 28 19:54:46.136130 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL Library Error: error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error (Type=PKCS8_PRIV_KEY_INFO)
[Tue Mar 28 19:54:46.136142 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL Library Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
[Tue Mar 28 19:54:46.136155 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL Library Error: error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error
[Tue Mar 28 19:54:46.136167 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL Library Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
[Tue Mar 28 19:54:46.136179 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL Library Error: error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error (Type=RSAPrivateKey)
[Tue Mar 28 19:54:46.136190 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL Library Error: error:04093004:rsa routines:old_rsa_priv_decode:RSA lib
[Tue Mar 28 19:54:46.136201 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL Library Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
[Tue Mar 28 19:54:46.136213 2023] [ssl:error] [pid 2647:tid 140400966600512] SSL Library Error: error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error (Type=PKCS8_PRIV_KEY_INFO)
[Tue Mar 28 19:54:46.136220 2023] [ssl:emerg] [pid 2647:tid 140400966600512] AH02312: Fatal error initialising mod_ssl, exiting.
[Tue Mar 28 19:54:46.136225 2023] [ssl:emerg] [pid 2647:tid 140400966600512] AH02564: Failed to configure encrypted (?) private key www.example.com:443:0, check /opt/bitnami/apache/conf/bitnami/certs/server.key
```
