### ISSUE TITLE
[Wordpress ] <Bitnami>

### ISSUE THREAD

**Issue by akrai05** [bitnami/vms#816]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

cba7e918-7eba-6972-b5e8-5b596e055c41

### bndiagnostic output

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Mon Mar 27 15:49:42.907599 2023] [authz_core:error] [pid 45116:tid
140134967990016] [client **ip_address**:38718] AH01630: client denied by server
configuration: /opt/bitnami/phpmyadmin/scripts
 [Tue Mar 28 06:33:02.066893 2023] [authz_core:error] [pid 45117:tid
140135186200320] [client **ip_address**:35720] AH01630: client denied by server
configuration: /opt/bitnami/phpmyadmin/scripts
 [Tue Mar 28 15:09:06.116894 2023] [core:error] [pid 45117:tid 140135253341952]
[client **ip_address**:59652] AH10244: invalid URI path
(/cgi-bin/.%%%%32%%65/.%%%%32%%65/.%%%%32%%65/.%%%%32%%65/.%%%%32%%65/bin/sh)

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

It is useful

### Describe your issue as much as you can

Hi there!
I am unable to access my WordPress site [and](http://dev.authentica.com/ ) dashboard.
I am facing white page issue. I have not install the cPanel and worried how to fix this issue using terminal.

Can you please help me how to fix this issue

**Comment by gongomgra** [comment]
Hi @akrai05,

Thanks for using Bitnami. I see you are using a custom `hello-elementor` theme. Can you activate another theme using the [`wp` command line tool](https://wp-cli.org/) and try again? I also see you have many plugins installed, please try to disable them as well.

**Comment by akrai05** [comment]
Hi Thanks,

Thanks for the response.
I have not taken the backup of the site If I will deactivate the theme  Will there be any data loss?

**Comment by gongomgra** [comment]
Hi @akrai05,

I'm afraid we can't give you an answer to that question. However, we highly recommend you to create a server backup before doing any major change so you can easily restore it. I'm sharing below our guide on how to create and restore a server backup from the AWS console for your convenience

https://docs.bitnami.com/aws/faq/administration/backup-restore-server/

Hope it helps!
