### ISSUE TITLE
Magento OVA how to pull specific version

### ISSUE THREAD

**Issue by ralsim** [bitnami/vms#817]
### Describe your issue as much as you can

How can you pull a specific version of a bitmani stack in ova format I want to compare the server configuration between 2.4.2 and 2.4.3 and 2.4.4

I can't seem to see any method of doing this. I can do this with docker but I want to see the rest of the OS configuration, are the debian images based on the same yaml as the docker containers?

I have the ova for 2.4.5 and 2.4.6 but nothing earlier

thanks

**Comment by gongomgra** [comment]
Hi @ralsim,

Thanks for using Bitnami. The oldest OVA I can find in our registries is for version `2.4.3`. I'm sharing the download links below

* https://downloads.bitnami.com/files/stacks/magento/2.4.3-89/bitnami-magento-2.4.3-89-r14-linux-debian-10-x86_64-nami.ova
* https://downloads.bitnami.com/files/stacks/magento/2.4.4-9/bitnami-magento-2.4.4-9-r02-linux-debian-11-x86_64-nami.ova 

Take into account that the OVA for version 2.4.3 is based on Debian 10, while the others are for Debian 11. Unfortunately, we don't have an OVA for that version with Debian 11. Additionally, please remember that theses are old versions of the OVAs including old base components.

Hope it helps!
