### ISSUE TITLE
[Tomcat] Website page not displaying after cert install

### ISSUE THREAD

**Issue by u35tr3** [bitnami/vms#818]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic was not useful. Could you please tell us why?

N/A

### Describe your issue as much as you can

Hello Bitnami Support,

I'm having trouble with starting/enabling the bitnami.service which I think maybe causing my site not to display and gets directed to a Apache page. Please see below for further details of somethings I've done so far:

_My domain is:_

https://share.cnic-n9portal.net/

_I ran this command:_

systemctl status bitnami.service

_It produced this output:_

● bitnami.service - LSB: Bitnami Init Script
Loaded: loaded (/etc/init.d/bitnami; bad; vendor preset: enabled)
Active: failed (Result: exit-code) since Thu 2023-03-30 14:25:29 UTC; 2h 55min ago
Docs: man:systemd-sysv-generator(8)
Process: 9923 ExecStart=/etc/init.d/bitnami start (code=exited, status=203/EXEC)

Mar 30 14:25:29 xxxx systemd[1]: Starting LSB: Bitnami Init Script...
Mar 30 14:25:29 ip-10-3-5-5 systemd[1]: bitnami.service: Control process exited, code=exited status=203
Mar 30 14:25:29 xxxx systemd[1]: Failed to start LSB: Bitnami Init Script.
Mar 30 14:25:29 xxxx systemd[1]: bitnami.service: Unit entered failed state.
Mar 30 14:25:29 xxxx systemd[1]: bitnami.service: Failed with result 'exit-code'.

_I ran this command:_

systemctl start bitnami.service

_It produced this output:_

Job for bitnami.service failed because the control process exited with error code. See "systemctl status bitnami.service" and "journalctl -xe" for details.

_I ran this command:_

sudo /opt/bitnami/ctlscript.sh status

_It produced this output:_

apache not running
tomcat already running
mysql already running

_The operating system my web server runs on is (include version):_

**Ubuntu 16**

_My hosting provider, if applicable, is:_

_I can login to a root shell on my machine (yes or no, or I don't know):_

I use MobaXterm

_The version of my client is (e.g. output of certbot --version or certbot-auto --version if you're using Certbot):_

certbot 0.27.0

**Comment by jotamartos** [comment]
It seems Apache is not working properly 

```
apache not running
```

Can you take a look at the Apache's log file? `/opt/bitnami/apache/logs/error_log`. You will also get more information if you try to start Apache

```
sudo /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
```

**Comment by u35tr3** [comment]
Your request: /opt/bitnami/apache/logs/error_log

> 
``
bitnami@ip-10-3-5-5:/opt/bitnami/apache2/logs$ vi error_log
[Tue Mar 28 14:52:47.220052 2023] [mpm_prefork:notice] [pid 2037] AH00163: Apache/2.4.12 (Unix) OpenSSL/1.0.1m configured -- resuming normal operations
[Tue Mar 28 14:52:47.220124 2023] [core:notice] [pid 2037] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd -f /opt/bitnami/apache2/conf/httpd.conf'
[Tue Mar 28 14:52:50.607835 2023] [proxy:error] [pid 2041] (111)Connection refused: AH00957: AJP: attempt to connect to 127.0.0.1:8009 (localhost) failed
[Tue Mar 28 14:52:50.607934 2023] [proxy:error] [pid 2041] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 60s
[Tue Mar 28 14:52:50.607968 2023] [proxy_ajp:error] [pid 2041] [client 136.226.18.91:64761] AH00896: failed to make connection to backend: localhost
[Tue Mar 28 14:53:05.965686 2023] [proxy:error] [pid 2041] AH00940: AJP: disabled connection for (localhost)
[Tue Mar 28 14:54:21.221157 2023] [proxy_ajp:error] [pid 2039] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Tue Mar 28 14:54:21.221274 2023] [proxy_ajp:error] [pid 2039] [client 136.226.18.91:7473] AH00992: ajp_read_header: ajp_ilink_receive failed, referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 14:54:21.221298 2023] [proxy_ajp:error] [pid 2039] (70007)The timeout specified has expired: [client 136.226.18.91:7473] AH00878: read response failed from 127.0.0.1:8009 (localhost), referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 14:55:36.481142 2023] [proxy_ajp:error] [pid 2041] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Tue Mar 28 14:55:36.481229 2023] [proxy_ajp:error] [pid 2041] [client 136.226.18.91:62735] AH00992: ajp_read_header: ajp_ilink_receive failed, referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 14:55:36.481255 2023] [proxy_ajp:error] [pid 2041] (70007)The timeout specified has expired: [client 136.226.18.91:62735] AH00878: read response failed from 127.0.0.1:8009 (localhost), referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 14:56:51.725122 2023] [proxy_ajp:error] [pid 2039] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Tue Mar 28 14:56:51.725198 2023] [proxy_ajp:error] [pid 2039] [client 136.226.18.91:54960] AH00992: ajp_read_header: ajp_ilink_receive failed, referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 14:56:51.725216 2023] [proxy_ajp:error] [pid 2039] (70007)The timeout specified has expired: [client 136.226.18.91:54960] AH00878: read response failed from 127.0.0.1:8009 (localhost), referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 14:58:07.065158 2023] [proxy_ajp:error] [pid 2041] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Tue Mar 28 14:58:07.065242 2023] [proxy_ajp:error] [pid 2041] [client 136.226.18.91:17146] AH00992: ajp_read_header: ajp_ilink_receive failed, referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 14:58:07.065328 2023] [proxy_ajp:error] [pid 2041] (70007)The timeout specified has expired: [client 136.226.18.91:17146] AH00878: read response failed from 127.0.0.1:8009 (localhost), referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 14:59:22.552532 2023] [proxy_ajp:error] [pid 2040] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Tue Mar 28 14:59:22.552676 2023] [proxy_ajp:error] [pid 2040] [client 136.226.18.91:61812] AH00992: ajp_read_header: ajp_ilink_receive failed, referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 14:59:22.552700 2023] [proxy_ajp:error] [pid 2040] (70007)The timeout specified has expired: [client 136.226.18.91:61812] AH00878: read response failed from 127.0.0.1:8009 (localhost), referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 15:00:37.933118 2023] [proxy_ajp:error] [pid 2038] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Tue Mar 28 15:00:37.933252 2023] [proxy_ajp:error] [pid 2038] [client 136.226.18.91:25862] AH00992: ajp_read_header: ajp_ilink_receive failed, referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 15:00:37.933276 2023] [proxy_ajp:error] [pid 2038] (70007)The timeout specified has expired: [client 136.226.18.91:25862] AH00878: read response failed from 127.0.0.1:8009 (localhost), referer: https://share.cnic-n9portal.net/share/page/user/cShields/dashboard
[Tue Mar 28 15:56:49.702479 2023] [lbmethod_heartbeat:notice] [pid 8758] AH02282: No slotmem from mod_heartmonitor
[Tue Mar 28 15:56:49.702683 2023] [core:warn] [pid 8758] AH00098: pid file /opt/bitnami/apache2/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Mar 28 15:56:49.869214 2023] [mpm_prefork:notice] [pid 8758] AH00163: Apache/2.4.12 (Unix) OpenSSL/1.0.1m configured -- resuming normal operations
[Tue Mar 28 15:56:49.869305 2023] [core:notice] [pid 8758] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd -f /opt/bitnami/apache2/conf/httpd.conf'
``

**Comment by u35tr3** [comment]
> 
I don't have a Apache .... it's only showing Apache2
``
root@ip-10-3-5-5:~# /opt/bitnami/apache2/bin/httpd -f /opt/bitnami/apache2/conf/httpd.conf
/opt/bitnami/apache2/bin/httpd: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
``

**Comment by u35tr3** [comment]
Hello Juan,

I’ve provided an update in regards to what you’ve requested. Please let me
know if anything else is needed. Thanks!

**Comment by u35tr3** [comment]
Hello @jotamartos 

I’ve provided an update in regards to what you’ve requested. Please let me
know if anything else is needed. Thanks!

**Comment by jotamartos** [comment]
```
root@ip-10-3-5-5:~# /opt/bitnami/apache2/bin/httpd -f /opt/bitnami/apache2/conf/httpd.conf /opt/bitnami/apache2/bin/httpd: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
```

It seems it can't load some libraries, but it may be related to the user you are using to run the command. Can you use the `bitnami` user to run it? 

```
sudo su bitnami
sudo /opt/bitnami/apache2/bin/httpd -f /opt/bitnami/apache2/conf/httpd.conf 
```

**Comment by u35tr3** [comment]
I will try this shortly and provide results.

**Comment by u35tr3** [comment]
These are results below from running that command above you provided

```
/opt/bitnami/apache2/bin/httpd:` error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory

**Comment by u35tr3** [comment]
Apache2 Ubuntu Default Page is displaying in my web browser instead of the actual webpage for https://share.cnic-n9portal.net/

I noticed that when I run the following commands:
```
sudo systemctl stop apache2
sudo systemctl disable apache2
```
Followed by:
```
sudo /opt/bitnami/ctlscript.sh restart
```
My website comes back up successfully:

```
https://share.cnic-n9portal.net/
```

This leads me to believe Apche2 somewhere might be interfering with the setup?

**Comment by jotamartos** [comment]
Correct! The Apache package should not be installer or running when using the Bitnami solution. We include the Apache binaries we compile and you can start it using the ctlscript.sh file.

**Comment by u35tr3** [comment]
Ok that's good progress is being made. How would I resolve this? How do I have my website display while Apache2 is running?

**Comment by u35tr3** [comment]
![image](https://user-images.githubusercontent.com/116172227/232803078-5d45b4fd-bbf0-4830-ac35-68e6ffd6140c.png)

**Comment by u35tr3** [comment]
Is there anyway I can reach you @jotamartos to do a screen share by chance?

**Comment by jotamartos** [comment]
Hi @u35tr3,

We do not provide that kind of support. If your site is not secure, there are different reasons for that to happen:

- First of all ensure that the certificates are properly configured in Apache. You can take a look at this guide where we explain how to manually configure Let's Encrypt certificates using the lego Let's Encrypt client (it's similar to the certbot tool you are using)

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

- If the certificates are configured correctly, ensure there is not any http link when accessing the website using https.

**Comment by u35tr3** [comment]
@jotamartos 

When trying to run the steps above this .... when I get the email address part, this is what comes back. Do I need to change the mail option? I'm inputting a correct email that is active.

![image](https://user-images.githubusercontent.com/116172227/233087978-d1ddf5ca-bafc-44df-a17d-1277ba284164.png)

**Comment by jotamartos** [comment]
You are using the old directory structure and that's why the doc doesn't work for you. Please note that we updated the directory structure some years ago and that's why we only mention the apache folder. In your case, you will need to run these commands after running the lego one

```
sudo mv /opt/bitnami/apache2/conf/server.crt /opt/bitnami/apache2/conf/server.crt.old
sudo mv /opt/bitnami/apache2/conf/server.key /opt/bitnami/apache2/conf/server.key.old
sudo ln -sf /opt/bitnami/letsencrypt/certificates/DOMAIN.key /opt/bitnami/apache2/conf/server.key
sudo ln -sf /opt/bitnami/letsencrypt/certificates/DOMAIN.crt /opt/bitnami/apache2/conf/server.crt
sudo chown root:root /opt/bitnami/apache2/conf/server*
sudo chmod 600 /opt/bitnami/apache2/conf/server*
sudo /opt/bitnami/ctlscript.sh restart apache
```

**Comment by u35tr3** [comment]
Hello @jotamartos 
 
 I restored my server back  (before install) and I will restart the process from here:
 
 https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
 
 And then when I get to step , I will try that part above. Standby as I'm performing now

**Comment by u35tr3** [comment]
I tried the steps above and I'm still having the issue. Is there a way I can provide a text file to show you the output of my steps performed?

@jotamartos

**Comment by u35tr3** [comment]
@jotamartos Here are the results

![image](https://user-images.githubusercontent.com/116172227/233405418-a4a016e7-0e4f-457c-8074-56f8ed4043f6.png)

![image](https://user-images.githubusercontent.com/116172227/233405566-c5db162a-b2cb-451e-8414-2dd2f6686906.png)

![image](https://user-images.githubusercontent.com/116172227/233405681-ab7c6991-4465-4aeb-ba66-d3375384d80f.png)

**Comment by jotamartos** [comment]
The SSLCertificateKeyFile and SSLCertificateFile parameters are not using the server.key and server.crt files you created with the symlinks. You will need to update the bitnami.conf configuration file or the name of the files to use the correct certificates. I also suggest you remove the SSLCertificateChainFile as it's an old one.

**Comment by u35tr3** [comment]
@jotamartos  Please images below. How would I make correction in here?

![image](https://user-images.githubusercontent.com/116172227/233426657-bb2bc0a7-ac21-4985-a5fb-5ce4d71ac9e6.png)

![image](https://user-images.githubusercontent.com/116172227/233426728-d5331619-220e-4c9a-b69c-abbfb8e642b2.png)

![image](https://user-images.githubusercontent.com/116172227/233426858-fd21afd4-6716-4237-ae64-4390aef10f9b.png)

![image](https://user-images.githubusercontent.com/116172227/233426940-da9b6302-0604-4a3f-badb-90895a4a8af5.png)

**Comment by jotamartos** [comment]
As I mentioned above, you are using ssl_cert.pem and ssl_key.pem as certificate and key in the bitnami-ssl.conf file. The symlink you created to your Let's Encrypt certificates are server.crt and server.key. Please point to those files in the SSLCertificate* lines of the bitnami-ssl.conf file and restart Apache

**Comment by u35tr3** [comment]
@jotamartos Are you talking about these?
![image](https://user-images.githubusercontent.com/116172227/234274960-292f61e9-7871-423b-8a43-8e2b32d57661.png)

**Comment by u35tr3** [comment]
@jotamartos Like this?

Are you talking about these?:

![image](https://user-images.githubusercontent.com/116172227/234276948-64755523-c240-4ee9-9a71-c5fe8f8baad9.png)

**OLD:**

![image](https://user-images.githubusercontent.com/116172227/234276629-6670734a-6de7-4671-a647-a49b37eaf1c3.png)

**NEW:**

![image](https://user-images.githubusercontent.com/116172227/234276818-30ceeb85-ec15-4dde-a2ea-84bcba267f0d.png)

**Comment by jotamartos** [comment]
Hi @u35tr3,

The commands in the guide helps you create a server.crt and server.key files in the /opt/bitnami/apache2/conf folder for you to use them in the bitnami-ssl.conf file. You can use the lines you posted (remember to remove the SSLCertificateChainFile one because it's non-related to the certificates you generated) or you can use the created server.crt and server.key files 

```
SSLCertificateFile "/opt/bitnami/apache2/conf/server.crt"
SSLCertificateKeyFile "/opt/bitnami/apache2/conf/server.key"

```
