### ISSUE TITLE
 Failed to start LSB: bitnami init script. (Tried a lot of related issues but they do not work)

### ISSUE THREAD

**Issue by burfbari** [bitnami/vms#82]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

81042845-df1c-ec9d-0a69-4c7952fc6199

### bndiagnostic output

    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Yes, it pointed at the issues... although they weren't too clear to be solved

### Describe your issue as much as you can

Hi,

This all started after I tried to comment out `bind_address` in mysql in order to allow remote mysql connections.
Now it seems none of the bitnami services are starting even when I have reverted the change...

`sudo /opt/bitnami/ctlscript.sh status`
`Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/var/run/gonit.pid)`

```
● bitnami.service - LSB: bitnami init script
   Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2022-07-06 08:05:27 UTC; 13min ago
  Process: 1872 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
...
Jul 06 08:05:27 ip-172-26-1-212 systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
Jul 06 08:05:27 ip-172-26-1-212 systemd[1]: bitnami.service: Failed with result 'exit-code'.
Jul 06 08:05:27 ip-172-26-1-212 systemd[1]: Failed to start LSB: bitnami init script.
```

The threads look like this earlier
```
ps aux | grep 'apache\|mysql\|nginx\|/opt/bitnami'
bitnami   3817  0.0  0.0   6208   820 pts/1    S+   08:36   0:00 grep apache\|mysql\|nginx\|/opt/bitnami
```

The mysql logs (the threads did not list any multiple mysql threads but it did list multiple bitnami apache threads which I killed)
```
2022-07-06  8:24:32 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-07-06  8:24:32 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2022-07-06  8:24:32 0 [Note] Server socket created on IP: '127.0.0.1'.
2022-07-06  8:24:32 0 [ERROR] Can't start server: Bind on TCP/IP port. Got error: 98: Address already in use
2022-07-06  8:24:32 0 [ERROR] Do you already have another server running on port: 3306 ?
2022-07-06  8:24:32 0 [ERROR] Aborting
```

Edited - added mysql logs

**Comment by mdhont** [comment]
Did you follow these steps?

https://docs.bitnami.com/virtual-machine/infrastructure/mysql/administration/connect-remotely-mysql/

**Comment by burfbari** [comment]
Yes, I did but it never worked. Rather it brought it all down.

Attaching apache logs for your reference:
```
[Wed Jul 06 07:26:59.471936 2022] [mpm_event:notice] [pid 5845:tid 140713816341376] AH00491: caught SIGTERM, shutting down
[Wed Jul 06 07:43:22.847718 2022] [mpm_event:notice] [pid 27353:tid 140490560674688] AH00489: Apache/2.4.53 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Wed Jul 06 07:43:22.847847 2022] [core:notice] [pid 27353:tid 140490560674688] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Wed Jul 06 07:44:54.057696 2022] [mpm_event:notice] [pid 27353:tid 140490560674688] AH00491: caught SIGTERM, shutting down
[Wed Jul 06 07:44:54.568553 2022] [mpm_event:notice] [pid 27879:tid 140163775781760] AH00489: Apache/2.4.53 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Wed Jul 06 07:44:54.568684 2022] [core:notice] [pid 27879:tid 140163775781760] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Wed Jul 06 07:51:30.729214 2022] [mpm_event:notice] [pid 27879:tid 140163775781760] AH00491: caught SIGTERM, shutting down
[Wed Jul 06 07:55:01.290276 2022] [mpm_event:notice] [pid 993:tid 140439079033728] AH00489: Apache/2.4.53 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Wed Jul 06 07:55:01.290822 2022] [core:notice] [pid 993:tid 140439079033728] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
```



> Did you follow these steps?
> 
> https://docs.bitnami.com/virtual-machine/infrastructure/mysql/administration/connect-remotely-mysql/

**Comment by burfbari** [comment]
```
bitnami@ip-172-26-10-0:[~]: ps aux | grep mysql
mysql     1333  0.0  8.3 960716 84196 ?        Sl   Jul07   0:29 /opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
bitnami   6404  0.0  0.0   6072   892 pts/0    S+   14:51   0:00 grep mysql
bitnami@ip-172-26-10-0:[~]: sudo netstat -tulpn | grep 3306
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1333/mysqld
```

**Comment by mdhont** [comment]
Can you stop the mysql process?

First get the PID of the mariadb process:

    pgrep mysql

Then stop the process:
   
    sudo kill -9 PID

Where PID is the output of the first command.

Then restart mariadb:

    sudo /opt/bitnami/ctlscript.sh start mariadb

**Comment by ysidro** [comment]
i have same issue

**Comment by mdhont** [comment]
Hi @ysidro,

Could you please create a separate issue?

**Comment by Metrophobe** [comment]
experiencing the same bloody issue .... what is this mess? I renewed a certificate as per Aws documentation and now the server won't fire up .... (lightsail) any help would be appreciated

**Comment by Metrophobe** [comment]
ok will do
