### ISSUE TITLE
bitnami redmine 4.2.3-3 windows installer required 

### ISSUE THREAD

**Issue by zeeshanahmed0334** [bitnami/vms#820]
### Describe your issue as much as you can

bitnami redmine 4.2.3-3 windows installer.

**Comment by gongomgra** [comment]
Hi @zeeshanahmed0334,

Thanks for using Bitnami. Unfortunately, we don't have any local installer available for that version. The closest asset we have available to that version is the OVA for Redmine 4.2.5. Please find the download link below

* https://downloads.bitnami.com/files/stacks/redmine/4.2.5-7/bitnami-redmine-4.2.5-7-r01-linux-debian-10-x86_64-nami.ova

Take into account that the OVA is an old asset shipping old versions of base components.
