### ISSUE TITLE
[Apache Guacamole] <Cannot connect ssh>

### ISSUE THREAD

**Issue by frhodes-aam** [bitnami/vms#824]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f8ef1882-57d2-1825-e9cc-7b20c7a9385f

### bndiagnostic output

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ✓ Apache: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Found connectivity issues relating to open ports which is not relevant to my case

### Describe your issue as much as you can

I recently backed up the Postgres Database on my functional Apache guacamole by Bitnami instance and restored it to the latest AMI on offer, since the backup and restore procedure they provided will not work.

Since i restored the db I had all my connection and users which are working well in the old version. I can connect via rdp without issue however when I try to connect via ssh I get the error message 'Log in failed. Pls reconnect and try again.' This is working well in the old instance but here it is not working for linux, ubuntu older versions.

I hope someone has experienced this, using this product is becoming a nightmare honestly. I will appreciate any answers that can point in the right direction as I have several unix based workloads and I cannot connect to them now.

**Comment by gongomgra** [comment]
Hi @frhodes-aam,

Thanks for using Bitnami. I checked the Tomcat logs included in the bndiagnostic bundle (you can check them in your server at `/opt/bitnami/tomcat/logs/catalina.out`) and I see Guacamole is failing to initialize some authenticator providers.

```
26-Mar-2023 23:43:24.882 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.73]
26-Mar-2023 23:43:24.898 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/bitnami/tomcat/webapps/guacamole]
26-Mar-2023 23:43:27.458 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
23:43:28.159 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/opt/bitnami/guacamole".
23:43:28.348 [main] INFO  o.a.g.GuacamoleServletContextListener - Read configuration parameters from "/opt/bitnami/guacamole/guacamole.properties".
23:43:28.349 [main] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule - Multiple extensions are installed and will be loaded in order of decreasing priority:
23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule -  - [mysql] "MySQL Authentication" (/opt/bitnami/guacamole/extensions/guacamole-auth-jdbc-mysql-1.5.0.jar)
23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule -  - [postgresql] "PostgreSQL Authentication" (/opt/bitnami/guacamole/extensions/guacamole-auth-jdbc-postgresql-1.5.0.jar)
23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule -  - [sqlserver] "SQLServer Authentication" (/opt/bitnami/guacamole/extensions/guacamole-auth-jdbc-sqlserver-1.5.0.jar)
23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule - To change this order, set the "extension-priority" property or rename the extension files. The default priority of extensions is dictated by the sort order of their filenames.
23:43:29.068 [main] ERROR o.a.g.extension.ProviderFactory - authentication provider extension failed to start: Property mysql-database is required.
23:43:29.069 [main] ERROR o.a.g.extension.ProviderFactory - authentication provider extension failed to start: Property mysql-database is required.
23:43:29.208 [main] INFO  o.a.g.extension.ExtensionModule - Extension "MySQL Authentication" (mysql) loaded.
23:43:30.976 [main] INFO  o.a.g.extension.ExtensionModule - Extension "PostgreSQL Authentication" (postgresql) loaded.
23:43:30.990 [main] ERROR o.a.g.extension.ProviderFactory - authentication provider extension failed to start: Property sqlserver-database is required.
23:43:30.990 [main] ERROR o.a.g.extension.ProviderFactory - authentication provider extension failed to start: Property sqlserver-database is required.
23:43:31.016 [main] INFO  o.a.g.extension.ExtensionModule - Extension "SQLServer Authentication" (sqlserver) loaded.
23:43:31.200 [main] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
23:43:32.119 [main] WARN  o.g.jersey.server.wadl.WadlFeature - JAXBContext implementation could not be found. WADL feature is disabled.
26-Mar-2023 23:43:32.563 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/bitnami/tomcat/webapps/guacamole] has finished in [7,664] ms
26-Mar-2023 23:43:32.572 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
26-Mar-2023 23:43:32.595 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-127.0.0.1-8009"]
26-Mar-2023 23:43:32.601 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [7839] milliseconds
23:58:47.870 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
23:58:47.877 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
23:58:48.103 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
23:58:48.103 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
00:31:28.356 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
00:31:28.357 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
00:31:28.362 [http-nio-8080-exec-7] WARN  o.a.i.d.pooled.PooledDataSource - Execution of ping query 'SELECT 1' failed: FATAL: terminating connection due to administrator command
00:31:28.380 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
00:31:28.380 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
00:31:46.320 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
00:31:46.321 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
00:31:46.348 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
00:31:46.348 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
00:31:46.348 [http-nio-8080-exec-6] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 122.150.69.113 for user "_REDACTED_" failed.
```

According to those logs, it looks like some authenticator methods were loaded, and others not, but I can't see what are those failing. Can you try increasing the debug level? Additionally, the next error message in those logs caught my attention. Can you double-check the database settings are correct?

```
00:31:28.362 [http-nio-8080-exec-7] WARN  o.a.i.d.pooled.PooledDataSource - Execution of ping query 'SELECT 1' failed: FATAL: terminating connection due to administrator command
```

**Comment by frhodes-aam** [comment]
> Hi @frhodes-aam,
> 
> Thanks for using Bitnami. I checked the Tomcat logs included in the bndiagnostic bundle (you can check them in your server at `/opt/bitnami/tomcat/logs/catalina.out`) and I see Guacamole is failing to initialize some authenticator providers.
> 
> ```
> 26-Mar-2023 23:43:24.882 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.73]
> 26-Mar-2023 23:43:24.898 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/bitnami/tomcat/webapps/guacamole]
> 26-Mar-2023 23:43:27.458 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
> 23:43:28.159 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/opt/bitnami/guacamole".
> 23:43:28.348 [main] INFO  o.a.g.GuacamoleServletContextListener - Read configuration parameters from "/opt/bitnami/guacamole/guacamole.properties".
> 23:43:28.349 [main] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
> 23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule - Multiple extensions are installed and will be loaded in order of decreasing priority:
> 23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule -  - [mysql] "MySQL Authentication" (/opt/bitnami/guacamole/extensions/guacamole-auth-jdbc-mysql-1.5.0.jar)
> 23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule -  - [postgresql] "PostgreSQL Authentication" (/opt/bitnami/guacamole/extensions/guacamole-auth-jdbc-postgresql-1.5.0.jar)
> 23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule -  - [sqlserver] "SQLServer Authentication" (/opt/bitnami/guacamole/extensions/guacamole-auth-jdbc-sqlserver-1.5.0.jar)
> 23:43:29.045 [main] INFO  o.a.g.extension.ExtensionModule - To change this order, set the "extension-priority" property or rename the extension files. The default priority of extensions is dictated by the sort order of their filenames.
> 23:43:29.068 [main] ERROR o.a.g.extension.ProviderFactory - authentication provider extension failed to start: Property mysql-database is required.
> 23:43:29.069 [main] ERROR o.a.g.extension.ProviderFactory - authentication provider extension failed to start: Property mysql-database is required.
> 23:43:29.208 [main] INFO  o.a.g.extension.ExtensionModule - Extension "MySQL Authentication" (mysql) loaded.
> 23:43:30.976 [main] INFO  o.a.g.extension.ExtensionModule - Extension "PostgreSQL Authentication" (postgresql) loaded.
> 23:43:30.990 [main] ERROR o.a.g.extension.ProviderFactory - authentication provider extension failed to start: Property sqlserver-database is required.
> 23:43:30.990 [main] ERROR o.a.g.extension.ProviderFactory - authentication provider extension failed to start: Property sqlserver-database is required.
> 23:43:31.016 [main] INFO  o.a.g.extension.ExtensionModule - Extension "SQLServer Authentication" (sqlserver) loaded.
> 23:43:31.200 [main] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
> 23:43:32.119 [main] WARN  o.g.jersey.server.wadl.WadlFeature - JAXBContext implementation could not be found. WADL feature is disabled.
> 26-Mar-2023 23:43:32.563 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/bitnami/tomcat/webapps/guacamole] has finished in [7,664] ms
> 26-Mar-2023 23:43:32.572 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
> 26-Mar-2023 23:43:32.595 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-127.0.0.1-8009"]
> 26-Mar-2023 23:43:32.601 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [7839] milliseconds
> 23:58:47.870 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 23:58:47.877 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 23:58:48.103 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 23:58:48.103 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 00:31:28.356 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 00:31:28.357 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 00:31:28.362 [http-nio-8080-exec-7] WARN  o.a.i.d.pooled.PooledDataSource - Execution of ping query 'SELECT 1' failed: FATAL: terminating connection due to administrator command
> 00:31:28.380 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 00:31:28.380 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 00:31:46.320 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 00:31:46.321 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 00:31:46.348 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 00:31:46.348 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
> 00:31:46.348 [http-nio-8080-exec-6] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from _REDACTED_IP_ for user "_REDACTED_USER_" failed.
> ```
> 
> According to those logs, it looks like some authenticator methods were loaded, and others not, but I can't see what are those failing. Can you try increasing the debug level? Additionally, the next error message in those logs caught my attention. Can you double-check the database settings are correct?
> 
> ```
> 00:31:28.362 [http-nio-8080-exec-7] WARN  o.a.i.d.pooled.PooledDataSource - Execution of ping query 'SELECT 1' failed: FATAL: terminating connection due to administrator command
> ```

Hi,

Thank for investigating this and getting back to me.

I have set the log level to debug and ran the bndiagnostics tool again (770502d0-77f5-0db3-ba0a-0ab602520871).

Honestly I am not very savvy with this so can you pls tell me what the expected database settings should be and where I can find this settings?

Thank you.

Fego

**Comment by gongomgra** [comment]
Hi @frhodes-aam,

The config file for Guacamole is at `/opt/bitnami/guacamole/guacamole.properties`, can you check the database settings there (if any), and test them again the PostgreSQL database? 

Regarding Tomcat's logs, although I see some errors there, I'm afraid we don't have enough knowledge about Guacamole to understand what's happening. We recommend you to open a new question in the official Guacamole forums for further help on this

https://guacamole.apache.org/support/
