### ISSUE TITLE
[Apache Guacamole] IP address of guacamole server changes to wrong network interface

### ISSUE THREAD

**Issue by testtobi** [bitnami/vms#825]
### Describe your issue as much as you can

Used version:
bitnami-guacamole-1.5.0-6-r08-linux-vm-debian-11-x86_64-nami

System Setup:
Guacamole VM is used with two network interfaces, one for connecting to the guacamole webUI and the second one is used as connection to the system. Both network interfaces are in their own IP address range. 

Issue:
After a reboot it happens from time to time that the guacamole server changes its ip configuration from the first interface to the second interface (can be easily seen on the console starting banner). Hence the server is no longer reachable on its initial configured ip address. If i rename the *.network files or change any parameter in it and restart the server again then the guacamole-server changes back to the other network interface and is again reachable on the right ip address.

I tried to follow the [guide for updating the ip address](https://docs.bitnami.com/virtual-machine/apps/guacamole/administration/update-ip-hostname/) to disable an automatic configure during startup but i wasn't able to find neither bnconfig nor configure_app_domain on the machine.

Is there a way to disable the automatic configuration on startup or to define a certain network interface which has to be used by guacamole-server?

**Comment by gongomgra** [comment]
Hi @testtobi,

Thanks for using Bitnami. Can you give us more information about your issue? What is the setting you get wrongly updated? How did you configure those interfaces? Do they have a static IP address (both of them), or do they get their IP address dynamically via DHCP? Are you using the most recent virtual-machine from our website or a previous one?

Additionally, can you share the output of running the commands below with us?

```
ls -larth /opt/bitnami/scripts/guacamole/
sudo systemctl list-units -t service | grep -i bitnami
```

**Comment by testtobi** [comment]
The VM has two network interfaces with static IPs. One is used to have access to the guacamole webUI and the other is for the connection to the system, where I want to have access with guacamole

e.g. network 1 has the ip 192.168.123.111 which is used to access the webUI and network 2 has 178.50.100.50.
After a reboot of the VM it happened sporadically that guacamole is no longer available via 192.168.123.111, instead it changed to the other address 178.50.100.50.
If I change anything in the *.network file for network 1 then guacamole changes interface back to the IP from network 1 and is again available via 192.168.123.111

Output of the mentioned commands:

bitnami@debian:~$ ls -larth /opt/bitnami/scripts/guacamole/
total 20K
-rwxr-xr-x 1 root root 2.0K Mar 20 04:53 setup.sh
-rwxr-xr-x 1 root root 4.2K Mar 20 04:53 postunpack.sh
drwxr-xr-x 2 root root 4.0K Mar 20 04:53 .
drwxr-xr-x 9 root root 4.0K Mar 20 05:05 ..

bitnami@debian:~$ sudo systemctl list-units -t service | grep -i bitnami
  bitnami.service                      loaded active running LSB: bitnami init script

**Comment by gongomgra** [comment]
Hi @testtobi,

Thanks for your message. I'm not sure if this can be caused by some init scripts we include in the machine you are currently using. We released a new virtual machine solution for Odoo recently removing those init scripts. Can you give our latest image a try? 

https://bitnami.com/stack/guacamole/virtual-machine

**Comment by sollyn21** [comment]
i cant execute bnconfig tool, it ist not in the path "/opt/bitnami/apps/APP-NAME"

https://docs.bitnami.com/general/faq/configuration/understand-bnconfig/

**Comment by gongomgra** [comment]
Hi @sollyn21,

The bnconfig tool is no longer included in recent versions of our solutions. Please open a new ticket adding as much information about your issue and our support team will help you. I'm closing this ticket.
