### ISSUE TITLE
[Wordpress] <AWS WP shutdown ERR_CONNECTION_REFUSED>

### ISSUE THREAD

**Issue by KingMilli75** [bitnami/vms#826]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c5a58bf3-9ab8-dc7b-130d-b9581d4aa71

### bndiagnostic output

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

 
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue Apr 04 07:38:15.805455 2023] [proxy_fcgi:error] [pid 256746:tid 
139950527817472] [client **ip_address**:61083] AH01079: failed to make 
connection to backend: httpd-UDS
 [Tue Apr 04 07:38:15.999793 2023] [proxy:error] [pid 256746:tid 
139950519424768] (2)No such file or directory: AH02454: FCGI: attempt to connect 
to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Tue Apr 04 07:38:15.999830 2023] [proxy_fcgi:error] [pid 256746:tid 
139950519424768] [client **ip_address**:61082] AH01079: failed to make 
connection to backend: httpd-UDS, referer: https://kupoholik.rs/
```

### bndiagnostic was not useful. Could you please tell us why?

i knew there is a issue but not sure what this is and how it came to be

### Describe your issue as much as you can

Hi There, 

last night everything was working properly and without any problems. Now we can not access the WP build via the admin panel neither the site is accessible. 

running:
```
itnami@ip-172-26-13-126:~$ netstat -tulpn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Progra
m name    
tcp        0      0 127.0.0.1:11211         0.0.0.0:*               LISTEN      -         
          
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -         
          
tcp6       0      0 :::22                   :::*                    LISTEN      -         
          
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -         
          
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -         
          
udp6       0      0 ::1:323                 :::*                                -         
          
udp6       0      0 fe80::ea:a4ff:fe57::546 :::*                                -       
```

there are clearly no ports as defined in lightsail

Application | Protocol | Port or range / Code | Restricted to |  
-- | -- | -- | -- | --
SSH | TCP | 22 | Any IPv4 addressLightsail browser SSH/RDP |  
HTTP | TCP | 80 | Any IPv4 address |  
HTTPS | TCP | 443 | Any IPv4 address

running: sudo service bitnami start apache
did not yield also results.

We did not change anything to the config neither to the port access and so forth.

Swift help is appreciated. 

Cheers 
Dragan

**Comment by KingMilli75** [comment]
Just to add this part also in the WP config file the server IP is the same one as above but not the static IP or login IP which is posted in here 

netstat IP : 127.0.0.1
WP config IP: 127.0.0.1
bitnami@ip-172-26-13-126 (the latter is the private IP)
and there is another static IP assigned in lightsail

**Comment by KingMilli75** [comment]
some additional info when trying to restart services:

bitnami@ip-172-26-13-126:~$ sudo service bitnami status
● bitnami.service - LSB: bitnami init script
     Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-04-04 08:25:03 UTC; 43min ago
    Process: 1457 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
      Tasks: 41 (limit: 4692)
     Memory: 145.7M
        CPU: 1.869s
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 685 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 686 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 687 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 688 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 689 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 690 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 691 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 692 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: Failed to start LSB: bitnami init script.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Consumed 1.718s CPU time.

bitnami@ip-172-26-13-126:~$ sudo service bitnami restart apache
Job for bitnami.service failed because the control process exited with error code.

**Comment by KingMilli75** [comment]
r 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 676 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 677 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 678 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 679 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 680 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 681 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 682 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 683 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 684 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 685 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 686 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 687 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 688 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 689 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 690 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 691 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Unit process 692 (php-fpm) remains running after unit stopped.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: Failed to start LSB: bitnami init script.
░░ Subject: A start job for unit bitnami.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit bitnami.service has finished with a failure.
░░ 
░░ The job identifier is 712 and the job result is failed.
Apr 04 09:13:03 ip-172-26-13-126 systemd[1]: bitnami.service: Consumed 1.718s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitnami.service completed and consumed the indicated resources.
Apr 04 09:13:05 ip-172-26-13-126 dhclient[439]: PRC: Renewing lease on eth0.
Apr 04 09:13:05 ip-172-26-13-126 dhclient[439]: XMT: Renew on eth0, interval 9630ms.
Apr 04 09:13:05 ip-172-26-13-126 dhclient[439]: RCV: Reply message on eth0 from fe80::e5:69ff:fe7b:93c.
Apr 04 09:14:15 ip-172-26-13-126 dhclient[439]: PRC: Renewing lease on eth0.
Apr 04 09:14:15 ip-172-26-13-126 dhclient[439]: XMT: Renew on eth0, interval 9120ms.
Apr 04 09:14:15 ip-172-26-13-126 dhclient[439]: RCV: Reply message on eth0 from fe80::e5:69ff:fe7b:93c.
Apr 04 09:15:25 ip-172-26-13-126 dhclient[439]: PRC: Renewing lease on eth0.
Apr 04 09:15:25 ip-172-26-13-126 dhclient[439]: XMT: Renew on eth0, interval 9630ms.
Apr 04 09:15:25 ip-172-26-13-126 dhclient[439]: RCV: Reply message on eth0 from fe80::e5:69ff:fe7b:93c.

**Comment by KingMilli75** [comment]
we got the site running miraculously to be honest do not even know after a apache restart it showed the page however we ran again the diagnostic tool and still shows errors. 

77de2bd7-f106-e8b8-6b43-82be701cc64

**Comment by gongomgra** [comment]
Hi @KingMilli75,

Thanks for using Bitnami. I checked you bndiagnostic bundle information and I see there are at least 10 different IP address performing a lot of requests against your server. Can you check if you are under bots attacks?

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/deny-connections-bots-apache/

```
-----------------------------------
Check performance issues: Count number of requests for the 10 most active IP addresses in the last 100.000 requests
-----------------------------------
Running: tail -n 100000 access_log | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 10 | awk '{print $1}'
In: /opt/bitnami/apache2/logs/

Output:

9807
9132
8720
7997
3339
3337
3305
3304
3277
3274
```

I also see some WordPress internal errors running the `wp-cli` tool. Can you check them? 

```
wp plugin list --format=csv
```

FInally, I see a lot of timeouts and other PHP errors in the Apache logs (at `/opt/bitnami/apache2/logs/error_log`) that seems to be related with you plugins and/or custom theme. Can you review them and contact the plugin developers for further help on this? You may also get some help in the official WordPress forums

https://wordpress.org/support/forums/

**Comment by KingMilli75** [comment]
Hi Gonzalo, 

there is no bot attack we run it and its my IP with AWS IP addresses with GET commands..

The error log show a translation file not done correctly which we changed and this error is not shown anymore however when restarting the services we get this part. 

sudo /opt/bitnami/ctlscript.sh restart
bitnami@ip-172-26-13-126:~$ sudo /opt/bitnami/ctlscript.sh restart
Restarting services..
Job for bitnami.service failed.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

and then it stops. i can not find these logs now

**Comment by KingMilli75** [comment]
bitnami@ip-172-26-13-126:~$ sudo /opt/bitnami/ctlscript.sh status
Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/v
ar/run/gonit.pid)
bitnami@ip-172-26-13-126:~$

**Comment by KingMilli75** [comment]
here is the latest log be4bbbb5-de70-702e-b5e9-2618a62fc78b  is it not maybe wise to repair/reinstall apache or to launch a new instance from a snapshot

**Comment by KingMilli75** [comment]
We now upgraded the instance to get rid of the memory issue which was strange why it happened but its telling us the UDS problem and a proxy_fcgi: error now

e71113f1-26d0-d5be-1307-3f306381baff

**Comment by gongomgra** [comment]
Hi @KingMilli75,

I visited your website and I see some errors related to the WooCommerce plugin. This can also be related to the error you are getting in the logs. We recommend you to check those errors with the WooCommerce developers.

![Screen Shot 2023-04-10 at 17 05 30](https://user-images.githubusercontent.com/6660452/230928645-f094ec01-a77e-43ab-95c6-cb4a6a37e915.png)

**Comment by gongomgra** [comment]
Hi @KingMilli75,

Thanks for the update. We hope you can find a solution for your issue!
