### ISSUE TITLE
bitnami redmine 3.4.3.1 windows installer required

### ISSUE THREAD

**Issue by Jvarioz** [bitnami/vms#827]
### Platform

Installers

### Describe your issue as much as you can

I want bitnami redmine 3.4.3.1 windows installer, is available?

**Comment by gongomgra** [comment]
Hi @Jvarioz,

Thanks for your interest in using Bitnami. I'm afraid we don't have such an old version available. The oldest installer I could find for Redmine on Windows is for version 5.0.0. Would that work for you? 

Alternatively, you can use our Docker image for Redmine 3.4.3, which is available in DockerHub

https://hub.docker.com/r/bitnami/redmine/tags?page=1&ordering=last_updated&name=3.4.3

Hope it helps!
