### ISSUE TITLE
[bitnami/airflow] azure agent issue

### ISSUE THREAD

**Issue by adarshananda** [bitnami/vms#828]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

agent upgrade issue

### bndiagnostic was not useful. Could you please tell us why?

agent upgrade issue

### Describe your issue as much as you can

Hi Team,

We are from Cecelia and we are using bitnami image to run our airflow application in Linux (debian 10.13).  

We have old version of agent installed in bitnami (WALinuxAgent: 2.2.34) so our question is do we need to upgrade our agent version to new one.
*If we need to upgrade do we face any challenges in our prod system?
*Is it require any downtime?
*what are all the pre-requisites we need to take care before upgrade?
*will this effect to airflow application?
* which one is the recommended version need to install?

**Comment by gongomgra** [comment]
Hi @adarshananda,

Thanks for using Bitnami. I'm afraid we can't help you with that question in this forum. We recommend you to open a new question in a more specialized forum or to the Azure support team for further help on this. I also found some related documentation to this in the official Azure website, just in case it is of help.

https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/update-linux-agent

We highly recommend you to create a server backup before doing any change so you can easily restore it in case something fails.
