### ISSUE TITLE
Bitnami virtual machine error 

### ISSUE THREAD

**Issue by giribc** [bitnami/vms#829]
### Describe your issue as much as you can

HI  
I Have installed  new vm    bitnami review board  server .  Iam  able to access through ip  but not with  name 

Issues 
1)  host  att-reviewbaord.capgemini.com    -- Getting error     able to access through ip  
**host att-reviewboard.capgemini.com
;; connection timed out; no servers could be reached**

2) Error Apache logs 

apache logs
root@att-reviewboard:/opt/bitnami# tail -f /opt/bitnami/apache/logs/error_log
[Tue Mar 28 11:16:49.062128 2023] [mpm_event:notice] [pid 1512:tid 140666224228160] AH00493: SIGUSR1 received. Doing graceful restart
[Tue Mar 28 11:16:49.450152 2023] [ssl:warn] [pid 1512:tid 140666224228160] AH01909: [www.example.com:443:0](http://www.example.com:443:0/) server certificate does NOT include an ID which matches the server name
[Tue Mar 28 11:16:49.451362 2023] [mpm_event:notice] [pid 1512:tid 140666224228160] AH00489: Apache/2.4.54 (Unix) OpenSSL/1.1.1n mod_wsgi/4.9.4 Python/3.8 SVN/1.14.2 configured -- resuming normal operations
[Tue Mar 28 11:16:49.451380 2023] [core:notice] [pid 1512:tid 140666224228160] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Wed Mar 29 09:15:05.823405 2023] [mpm_event:notice] [pid 1512:tid 140666224228160] AH00491: caught SIGTERM, shutting down
[Wed Mar 29 09:15:06.288614 2023] [mpm_event:notice] [pid 61617:tid 140576010180416] AH00489: Apache/2.4.54 (Unix) OpenSSL/1.1.1n mod_wsgi/4.9.4 Python/3.8 SVN/1.14.2 configured -- resuming normal operations
[Wed Mar 29 09:15:06.288740 2023] [core:notice] [pid 61617:tid 140576010180416] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Wed Mar 29 09:15:13.214843 2023] [mpm_event:notice] [pid 61617:tid 140576010180416] AH00491: caught SIGTERM, shutting down
[Wed Mar 29 09:15:23.416866 2023] [mpm_event:notice] [pid 62995:tid 140401746364224] AH00489: Apache/2.4.54 (Unix) OpenSSL/1.1.1n mod_wsgi/4.9.4 Python/3.8 SVN/1.14.2 configured -- resuming normal operations
[Wed Mar 29 09:15:23.417010 2023] [core:notice] [pid 62995:tid 140401746364224] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'

**Comment by giribc** [comment]
Hi  Have runned the  the bind diagnostic tool    i got  the following out put 

===== Begin of bndiagnostic tool output =====
✓ Apache: No issues found
✓ Resources: No issues found
✓ Processes: No issues found
✓ Mariadb: No issues found
? Connectivity: Found possible issues

**Comment by gongomgra** [comment]
Hi @giribc,

Thanks for using Bitnami. Can you share with us the code that the bndiagnostic tool generated so we can take a look at the server logs? I visited the URL for your website and it returns a 400 Bad Request message, so I understand the server is fine but the website is not properly configured. Did you modify any setting before getting these errors?

Can you try updating the website settings as described in the official docs linked below accessing with the IP address?

https://www.reviewboard.org/docs/manual/5.0/admin/configuration/general-settings/

**Comment by giribc** [comment]
thanks  Gongomgra 

Please find the  error  i have made changes in  vitual host files   .  now i have taken backup and  restored original file 

==== Begin of bndiagnostic tool output =====


    ? Apache: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues



[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Apr 03 21:07:41.722370 2023] [core:error] [pid 135582:tid 140409619588864]
[client **ip_address**:59460] AH10244: invalid URI path
(/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32
%65/%%32%65%%32%65/%%32%65%%32%65/Windows/win.ini)
 [Tue Apr 04 16:32:45.935938 2023] [ssl:error] [pid 386429:tid 139872698353408]
[client **ip_address**:27310] AH02042: rejecting client initiated renegotiation
 [Tue Apr 04 16:32:47.958297 2023] [ssl:error] [pid 386429:tid 139872689960704]
Press [Enter] to continue:
[client **ip_address**:57716] AH02042: rejecting client initiated renegotiation

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/


===== End of bndiagnostic tool output =====

**Comment by giribc** [comment]
I have also Updated  certificate in this  files 

=============================================
# cat /opt/bitnami/apache/conf/bitnami/bitnami.conf |grep SSLCert
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"

Take backup of ssl certificate   .key .crt amd .csr files 

https://docs.bitnami.com/aws/apps/reviewboard/administration/enable-https-ssl-apache/


root@att-reviewboard:/opt/bitnami/apache/conf# cp server.key /opt/bitnami/apache/conf/bitnami/certs/server_pri.key

m -rf server.key
root@att-reviewboard:/opt/bitnami/apache/conf/bitnami/certs# rm -rf server.crt
root@att-reviewboard:/opt/bitnami/apache/conf/bitnami/certs# cp att-reviewboard_capgemini_com_cert.crt server.crt
root@att-reviewboard:/opt/bitnami/apache/conf/bitnami/certs# cp server_pri.key server.key

**Comment by gongomgra** [comment]
Hi @giribc,

Thanks for your message. Unfortunately, that's not the bndiagnostic output we need to inspect your server's logs. At the end of the bndiagnostic tool execution it will generate a code string separated by dashes and upload your information to our servers for us to check it, but I need that code to identify your information on our side. Can you run the tool again and share that code?

Apart from that, I don't see any issue with the SSL certificate, I visited your website and the SSL certificate is valid, as shown in the screenshot below. However, there should be an issue in your ReviewBoard settings.

![Screen Shot 2023-04-10 at 17 19 02](https://user-images.githubusercontent.com/6660452/230931209-8de264b0-4ba2-48de-a3b2-da44c4f7b672.png)
