### ISSUE TITLE
[Odoo] How to install it on custom VPS server.

### ISSUE THREAD

**Issue by Weesaal** [bitnami/vms#831]
### Describe your issue as much as you can

Hi Team,

I have been using Bitnami since so long on Amazon aws and using aws is fine where I can install bitnami stacks directly from marketplace but amazon aws is expensive we found an alternative server which is 90 times heaper than amazon but I am not sure I can I install bitnami stacks on their server. If anyone can help me with that?

**Comment by gongomgra** [comment]
Hi @Weesaal,

Thanks for your interest in using Bitnami. We [no longer provide local installers|https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html], but you can give our container solution for Odoo a try on your new server.

https://github.com/bitnami/containers/tree/main/bitnami/odoo

Hope it helps!
