### ISSUE TITLE
Add "expires" info to response headers

### ISSUE THREAD

**Issue by nlschutz** [bitnami/vms#832]
### Describe your issue as much as you can

I am the sys admin for our web hosting. We host our Wordpress site on AWS and Bitnami. I need to add expire headers to our images/videos. I added the following code to .htaccess and alternatively httpd.conf. Neither option worked. 
<IfModule mod_expires.c>
  ExpiresActive On
  # Images
  ExpiresByType image/jpeg "access plus 1 year"
  ExpiresByType image/gif "access plus 1 year"
  ExpiresByType image/png "access plus 1 year"
  ExpiresByType image/webp "access plus 1 year"
  ExpiresByType image/svg+xml "access plus 1 year"
  ExpiresByType image/x-icon "access plus 1 year"
  # Video
  ExpiresByType video/mp4 "access plus 1 year"
  ExpiresByType video/mpeg "access plus 1 year"
  # CSS, JavaScript
  ExpiresByType text/css "access plus 1 month"
  ExpiresByType text/javascript "access plus 1 month"
  ExpiresByType application/javascript "access plus 1 month"
  # Others
  ExpiresByType application/pdf "access plus 1 month"
  ExpiresByType application/x-shockwave-flash "access plus 1 month"
</IfModule>

What do I need to configure?  
Thank you for your help!
Nan

**Comment by gongomgra** [comment]
Hi @nlschutz,

Thanks for using Bitnami. We disable `.htaccess` files by default as [recommended by the Apache Software Foundation](https://httpd.apache.org/docs/current/mod/core.html#allowoverride). You will need to update a different config file to include the required configuration and then restart the Apache server for changes to take effect. Please find below the link to our documentation site on this

https://docs.bitnami.com/aws/apps/wordpress/administration/use-htaccess/
