### ISSUE TITLE
[Bitnami-WP on AWS] Creating a secondary .htaccess file for a child theme? Or add to the existing?

### ISSUE THREAD

**Issue by adixon97** [bitnami/vms#833]
### Describe your issue as much as you can

Hello, I am very new to this platform as well as making tickets so I hope I am in the right place. I am currently hosting a site using a Bitnami AMI for AWS for a school project. One of the features of our site is an API call to demonstrate the use of a One Time Secret URL. I believe I have added the needed code and it somewhat works but I find two issues. 

1. I have activated the code via a child theme rather than a plug in. The content appears on the main landing (index) page but I do not know how to apply this child theme/code to a specific page I built instead of putting itself on the index page. 

2. I have a functional user input text box and generate button. The text leaves when generated to hit One Time Secret's site, and then comes back with a built link of "www.(ourhostname)/s/(the hash value)". When I visit One Time Secret site to my account I can see the number of "secrets created" increase. So I know my call is working. The problem is, when I click the generated link that is returned I get an "this page does not exist" error. I am using the API call of a template a friend of mine made and his works perfectly. The only difference is in the zip file he sent me there is an .htaccess file I have not used or added. Could my issue come from the fact that I have not used that file? Perhaps because I have read  it handles redirection? If I do need it, is it safe to add that content to the existing .htaccess file? Or can I have more than one, and create a second .htaccess file within the child theme folder? I tread lightly as I have read how important and sensitive the root .htaccess file is.

As deadlines approach I am absolutely stumped and would be grateful for anyones help!!

**Comment by gongomgra** [comment]
Hi @adixon97 ,

Thanks for using Bitnami. We disable `.htaccess` files by default as [recommended by the Apache Software Foundation](https://httpd.apache.org/docs/current/mod/core.html#allowoverride). You will need to update a different config file to include the required configuration and then restart the Apache server for changes to take effect. Please find below the link to our documentation site on this

https://docs.bitnami.com/aws/apps/wordpress/administration/use-htaccess/
