### ISSUE TITLE
[Bitnami-Wordpress] <301 redirect error message>

### ISSUE THREAD

**Issue by methay** [bitnami/vms#834]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

6ef7251d-8478-6a31-de3b-7186ed5173aa

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1982 945 102 96 933 
756 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cl
oud 
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increa
se-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please che
ck the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
[Mariadb]

Some files don't have the expected permissions. Please check the follo
wing 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues
/

[Wordpress]

Press [Enter] to continue:
Some files don't have the expected permissions Please check the follow
ing guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/underst
and-
file-permissions/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Apr 05 01:12:34.761280 2023] [proxy_fcgi:error] [pid 48897:tid 
140002084243200] [client **ip_address**:64358] AH01079: failed to make
 
connection to backend: httpd-UDS
 [Wed Apr 05 01:12:35.298032 2023] [proxy:error] [pid 48893:tid 140002
205857536] 
(2)No such file or directory: AH02454: FCGI: attempt to connect to Uni
x domain 
socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
 [Wed Apr 05 01:12:35.298086 2023] [proxy_fcgi:error] [pid 48893:tid 
140002205857536] [client **ip_address**:35476] AH01079: failed to make
 
connection to backend: httpd-UDS
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-
erro
Press [Enter] to continue:
rs-apache/
```

The Apache configuration has errors:
```
AH00526: Syntax error on line 23 of 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: Invalid co
mmand 
'define('WP_SITEURL',', perhaps misspelled or defined by a module not 
included 
in the server configuration
```
Please check the configuration.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Broken links

### Describe your issue as much as you can

I am receiving 301 redirect error message

**Comment by gongomgra** [comment]
Hi @methay,

Thanks for using Bitnami. According to the error messages found by the bndiagnostic tool, you have a configuration issue in the WordPress config file. Please update the `WP_SITEURL` parameter in the `wp-config.php` file with your website's URL (including the `http://` or `https://` schemas).

```
AH00526: Syntax error on line 23 of 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: Invalid co
mmand 
'define('WP_SITEURL',', perhaps misspelled or defined by a module not 
included in the server configuration
```
