### ISSUE TITLE
Bitnami Wordpress services shut down periodically & my wordpress Admin return "Unexpected Error" while i update a page

### ISSUE THREAD

**Issue by sRapa94** [bitnami/vms#836]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

77f2d86c-dba2-94b5-7ff7-f3c7da99aa72

### bndiagnostic output

? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

it good for me, but it is not exactly

### Describe your issue as much as you can

First problem: Periodically my EC2 instance where is installed my wordpress it is unattainable, so i need to run "sudo /opt/bitnami/ctlscript.sh start" because apache, mariadb and php-fpm are "not running". I already install a cache plugin on my website and it works fine. Is a memory problem? I need to increase my CPU ?

Second problem: When i saved from my admin panel a page, an error is thrown, searching the logs I found this error: 

```
Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /opt/bitnami/wordpress/wp-includes/class -wp-block-parser.php:417\nStack trace:\n#0 /opt/bitnami/wordpress/wp-includes/class-wp-block-parser.php
```

This Website before migration on bitnami run on server with php version 7.3.3 and bitnami has installed php 8.1....It could be the cause of this error
Thanks

**Comment by gongomgra** [comment]
Hi @sRapa94,

Thanks for using Bitnami. According to the bndiagnostic information, I see there are some PHP errors caused by your custom theme

```
[Fri Apr 07 08:01:48.661008 2023] [proxy_fcgi:error] [pid 30541:tid 140698095417088] [client **ip_address**:51564] AH01071: Got error 'PHP message: PHP Warning: Trying to access array offset on value of type bool in /bitnami/wordpress/wp-content/themes/salient/nectar/helpers/media.php on line 368PHP message: PHP Warning: Trying to access array offset on value of type bool in /bitnami/wordpress/wp-content/themes/salient/nectar/helpers/media.php on line 368', referer: https://www.runromethemarath [Fri Apr 07 08:01:49.978302 2023] [proxy_fcgi:error] [pid 29887:tid 140698103809792] [client **ip_address**:51576] AH01071: Got error 'PHP message: PHP Warning: Trying to access array offset on value of type bool in /bitnami/wordpress/wp-content/themes/salient/nectar/helpers/media.php on line 368PHP message: PHP Warning: Trying to access array offset on value of type bool in /bitnami/wordpress/wp-content/themes/salient/nectar/helpers/media.php on line 368', referer: https://www.runromethemarath [Fri Apr 07 08:01:51.067230 2023] [proxy_fcgi:error] [pid 30541:tid 140697969526528] [client **ip_address**:51577] AH01071: Got error 'PHP message: PHP Warning: Trying to access array offset on value of type bool in /bitnami/wordpress/wp-content/themes/salient/nectar/helpers/media.php on line 368PHP message: PHP Warning: Trying to access array offset on value of type bool in /bitnami/wordpress/wp-content/themes/salient/nectar/helpers/media.php on line 368', referer: https://www.runromethemarath
```

Can you check them with the theme developers? We also recommend you to check the PHP version upgrade you mentioned in your message, just in case that theme, or any plugin you are using, doesn't fully support PHP 8 yet.

I also see the service using most RAM memory in your server is the MariaDB database server. This usually happens when your server has a lot of requests (like in a bot attack), or plugins using the database to store temporary information. Can you check this with the plugins developers? This can be causing your server to become unresponsive from time to time.
