### ISSUE TITLE
ghost lightsail instance fails to link updated bin directory link on upgrade

### ISSUE THREAD

**Issue by gotangst** [bitnami/vms#839]
### Describe your suggestion as much as you can

Every time I upgrade ghost the script fails to update the symbolic link to the new bin directory. This causes problems since ghost deletes old versions.

These commands complete successfully.
sudo npm install -g ghost-cli
sudo su ghost -c "ghost update"

ls -al
bin -> /opt/bitnami/ghost/versions/5.39.0/node_modules/.bin/    <-Points to wrong bin directory
current -> /opt/bitnami/ghost/versions/5.42.2

When I update the link and restart ghost it works.

ln -nsf /opt/bitnami/ghost/versions/5.42.2/node_modules/.bin/ bin
ls -al
bin -> /opt/bitnami/ghost/versions/5.42.2/node_modules/.bin/
current -> /opt/bitnami/ghost/versions/5.42.2

I hope this helps.

**Comment by gongomgra** [comment]
Hi @gotangst,

Thanks for using Bitnami and for reporting this issue. I understand your issue is caused by the `ghost update` command, which is developed by the Ghost team itself. Can you ask them for help on this on their official forums?

https://forum.ghost.org/
