### ISSUE TITLE
[<Bitnami-Wordpress>] <Cloudflare>

### ISSUE THREAD

**Issue by methay** [bitnami/vms#841]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ba3fcf79-823f-bfcd-4597-4d826083e043

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1982 871 117 94 993 832 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Wordpress]

Press [Enter] to continue:
Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

Found recent WordPress plugin related error messages in the Apache error log.
```
[Sun Apr 09 02:05:04.280817 2023] [proxy_fcg


### bndiagnostic was not useful. Could you please tell us why?

It  directed me to what was broken

### Describe your issue as much as you can

For some reason, I still have error messages even though my site is up and running now. Any time I attempt to enable Cloudflare it works for 10mins but then fails with the Too many redirects error message.

**Comment by mdhont** [comment]
Can you check this guide? It contains useful information about how to set up SSL with cloudflare.

https://docs.bitnami.com/aws/faq/administration/enable-ssl-cloudflare/
