### ISSUE TITLE
[Redmine] I want to know the root password for MariaDB.

### ISSUE THREAD

**Issue by sj1027** [bitnami/vms#842]
### Describe your issue as much as you can

Hello.

I have installed the following Redmine package for Windows:

bitnami-redmine-5.0.3-0-windows-x64-installer.exe

I would like to inquire if you could provide the root password for MariaDB used in the Bitnami installation package. I need to backup or handle the DB after installation and configuration, but I cannot do so without knowing the root password. It seems that forcibly changing the root password is not working well in recent versions of MariaDB. If it is difficult to provide the information here in the comments, please kindly let me know via email. 
My email address is 
sj1027@gmail.com
(mailto:sj1027@gmail.com).

Thank you.

**Comment by mdhont** [comment]
The root password for MariaDB is the same as the application password, it is configured ( by the user) at installation time.

**Comment by sj1027** [comment]
During the installation process of Redmine Windows package, it creates an admin account and asks for a password. Is this password the same as the root password for MariaDB?

After installation, if I change the admin password in Redmine and log in, will this affect the MariaDB root password?

**Comment by mdhont** [comment]
Yes, the password is the same but it will not affect the MariaDB root password if you change it later.
