### ISSUE TITLE
Amazon Lightsail - LAMP (PHP 8) - Disable The Server Cache

### ISSUE THREAD

**Issue by Display2022** [bitnami/vms#844]
### Describe your issue as much as you can

On Amazon Lightsail, I created a new LAMP (PHP 8) instance.

I followed the official instructions on the Bitnami website to Disable The Server Cache. https://docs.bitnami.com/aws/infrastructure/lamp/administration/disable-cache/

The lines related to PageSpeed were not available to comment out.

I followed the official instructions of the Bitnami website to Start Or Stop Services. https://docs.bitnami.com/aws/faq/administration/control-services/

I used the control script to restart the Apache service.

On my Amazon Lightsail instance, I created created `/home/bitnami/htdocs/index.php`

In that file, I created a test line `<?PHP echo "ONE" ?>` and saved the file.

When I load the file from the browser, it shows the expected output.

However, when I change the text in the file, it takes time to update.

This suggests that the server is still caching and not serving instantly.

How do I correctly disable the server cache so I can build out my site?

**Comment by mdhont** [comment]
It could also be the browser cache. Did you try with an incognito browser window, or another browser?

**Comment by Display2022** [comment]
Thanks. I just ran another test. I cleared All Browsing Data for All Time in Chrome, which is signed in to a Guest Account on a Chromebook. I also used and have been using Control - Shift - R to reload the page. Finally, I now used `curl` to load the page contents through the terminal. The results are the same. It takes upwards of 60 seconds or 15 reloads for the page to show the correct content.

**Comment by mdhont** [comment]
The PHP component comes with the OPcache extension enabled. This extension loads precompiled script bytecode into memory. You can either clear it before running a command if needed, using `opcache_reset()` or you can disable it completely in the PHP configuration:

opcache.enable=0

https://docs.bitnami.com/aws/apps/wordpress-multisite/configuration/configure-phpfpm-options/

But I don't recommend it as it slows down PHP scripts considerably.

**Comment by Display2022** [comment]
> I followed the official instructions on the Bitnami website to Disable The Server Cache. https://docs.bitnami.com/aws/infrastructure/lamp/administration/disable-cache/

I already disabled OPcache from the very start, as you described, and as described in the above instructions. Unfortunately it doesn't work, and I do not know why. Fresh, blank, standard server instance.

**Comment by mdhont** [comment]
I've not been able to reproduce the issue using the following snippet. In my case the string get's updated immediately. 

```
<?php
opcache_reset();
echo "ONE";
?>
```

**Comment by Display2022** [comment]
If the OPCache is disabled completely through `opcache.enable=0`, is there a purpose in using `opcache_reset()`?

**Comment by Display2022** [comment]
Just gave `opcache_reset();` a try and it does seem to work. Not ideal but probably sufficient for my purposes. Thanks for the recommendation.

**Comment by msnet9** [comment]
Hi Guys,
I have the same issue, I can not clear the cache or find the files that need to be edited. Do you guys have the latest links to the files, I am AWS Lightsail WordPress.
Thanks in advance

**Comment by mdhont** [comment]
As the guide mentions you need to edit the `/opt/bitnami/php/etc/php.ini` file and set `opcache.enable=0`. Then you need to restart php:

    sudo /opt/bitnami/ctlscript.sh restart

**Comment by gidzr** [comment]
Bad bot.. naughty naught bad bot..

I'm using Lightsail, Bitnami LAMP 8.1

I've got the same problem. I've followed the instructions per Bitnami here: https://docs.bitnami.com/aws/infrastructure/lamp/administration/disable-cache/

As mentioned above, there is no pagespeed to comment out in the httpd.conf file, but I did set the opcache.enable to 0 in the php.ini file.

Yes - I restarted apache. I even rebooted the server and restarted Bitnami services.

Using a testfile, index.php in htdocs folder, I made changes and saved these on the server using winscp. I hard reloaded in Chrome (ie not a browser cache), then waited, then hard reloaded again.. nothing. Then after 30 to 45 seconds the update appears.

There's definitely an issue here. From a dev perspective, this is a nightmare.

**Comment by gidzr** [comment]
@mdhont : Thanks! it's working now..

**Comment by foinf** [comment]
> Bad bot.. naughty naughty bad bot.. this issue is not solved.
> 
> I'm using Lightsail, Bitnami LAMP 8.1
> 
> I've got the same problem. I've followed the instructions per Bitnami here: https://docs.bitnami.com/aws/infrastructure/lamp/administration/disable-cache/
> 
> As mentioned above, there is no pagespeed to comment out in the httpd.conf file, but I did set the opcache.enable to 0 in the php.ini file.
> 
> Yes - I restarted apache. I even rebooted the server and restarted Bitnami services.
> 
> Using a testfile, index.php in htdocs folder, I made changes and saved these on the server using winscp. I hard reloaded in Chrome (ie not a browser cache), then waited, then hard reloaded again.. nothing. Then after 30 to 45 seconds the update appears.
> 
> There's definitely an issue here. From a dev perspective, this is a nightmare.

After wasting one hour of my life, I finally figured out what the h was going on thanks to this thread.

**Comment by mdhont** [comment]
Did you set the revalidation frequency to 0 as per my previous reply?

https://github.com/bitnami/vms/issues/844#issuecomment-1755819148
