### ISSUE TITLE
[Alfresco] The machine could not configure the network interface

### ISSUE THREAD

**Issue by canlepi** [bitnami/vms#845]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic was not useful. Could you please tell us why?

The suggest guides are not related wuth my issue.

### Describe your issue as much as you can

Hello. I have tried to initialize the Alfresco community application through the VMware Workstation 17 Player virtual machine, but I don't get the url, the password, or the user. Instead of this data, a message appears informing that "The machine could not configure the network interface". Could someone please tell me how I can solve this problem in order to get the data to connect to this application? Thank you so much!

**Comment by jotamartos** [comment]
Hi @canlepi,

Alfresco is a solution that requires a big amount of RAM to work. Did you check if the host machine has enough RAM memory to run the VM? You can also configure more RAM memory for the VM during this first initialization stage to avoid running into performance issues and decrease the RAM memory and use the default value once it's running.

**Comment by canlepi** [comment]
Thanks jotamartos, I'll follow your recommendations!
Have a nice day!
