### ISSUE TITLE
Unable to run composer in drupal installation under Lighsail

### ISSUE THREAD

**Issue by ShimonDekel** [bitnami/vms#846]
### Name and Version

bitnami/lightsail drupal 9.5.7-1

### What architecture are you using?

None

### What steps will reproduce the bug?

Using built-in ssh from Lightsail
Typing: "composer require 'drupal/bootstrap:^3.28'"
I get composer.json not fund

Any tutorial on how to create one?
Any simple solution?

**Comment by gongomgra** [comment]
Hi @ShimonDekel,

Thanks for using Bitnami. Drupal is installed under the `/opt/bitnami/drupal` folder. Can you try running the composer command from there?

**Comment by ShimonDekel** [comment]
Thank you Gonzalo Gómez Gracia,
It works
Did I miss something in the documentation?
Thanks, you saved my week.

Best regards

[ShimonDekelLogo]
You eat life, or life eats you

**Comment by gongomgra** [comment]
Hi @ShimonDekel,

Thanks for your message. As mentioned in the error message you received originally, you need to run composer commands from the directory where the `composer.json` file is located, and for our CiviCRM images, that folder is `/opt/bitnami/drupal`. Anyways, I'm glad you were able to successfully run your command~. I'm closing this ticket as solved.

**Comment by ShimonDekel** [comment]
Thank  you

[ShimonDekelLogo]
You eat life, or life eats you
