### ISSUE TITLE
[WordPress Multisite] Configure The Domain For The WordPress Multisite in the old version

### ISSUE THREAD

**Issue by johocen168** [bitnami/vms#847]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bb858de9-ea02-362f-8c60-df9bf5c9f3fb

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Connectivity: Found possible issues
    ? Apache: Found possible issues
    ? Resources: Found possible issues
    ? Php: Found possible issues
    ✓ Mysql: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
Press [Enter] to continue:
[Fri May 20 13:09:19.837279 2022] [autoindex:error] [pid 29745:tid 
140709151627008] [client **ip_address**:27472] AH01276: Cannot serve directory 
/opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex 
(index.html,index.php) found, and server-generated directory index forbidden by 
Options directive, referer: binance.com
 [Fri May 20 14:34:09.493359 2022] [autoindex:error] [pid 29745:tid 
140710146959104] [client **ip_address**:57926] AH01276: Cannot serve directory 
/opt/bitnami/apps/wordpress/htdocs/wp-admin/css/: No matching DirectoryIndex 
(index.html,index.php) found, and server-generated directory index forbidden by 
Options directive, referer: binance.com
 [Fri May 20 14:41:25.567027 2022] [core:error] [pid 29745:tid 140709084485376] 
[client **ip_address**:53680] AH00126: Invalid URI in request 'bin/sh' 'POST 
/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1'

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
Press [Enter] to continue:
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3682 968 126 7 2587 2425 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Php]

The following error appears in the 
/opt/bitnami/php/var/log/php-fpm.log:
Press [Enter] to continue:
```
[19-May-2022 06:59:58] WARNING: [pool www] server reached max_children setting 
(5), consider raising it

```
This error usually indicates PHP script execution is slow due to busy server 
resouces or buggy scripts. Please check the following guide to increase the 
number of PHP-FPM child processes:
 
https://docs.bitnami.com/general/apps/wordpress/configuration/configure-ph
pfpm-processes/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

not relate with our issue

### Describe your issue as much as you can

Tried to restore an old backup with wp-config.php is under /opt/bitnami/apps/wordpress/htdocs/

There is no configure_app_domain under /opt/bitnami and it seems not working for this old version.

Need to reconfigure The Domain for this old backup from johocen.com to mubie.com, since  johocen.com is used by a new instance.

can you guide me where can i find the instruction for older version?

Thanks

**Comment by johocen168** [comment]
btw, bndiagnostic shows that Server ports 22, 80 and/or 443 are not publicly accessible.
VPC firewall rules shows that "Target tags wordpress-multisite-1sam-deployment" for tcp 80 and 443
see screenshot https://i.imgur.com/ylLSc1d.png
What should I add?
Thanks

**Comment by jotamartos** [comment]
Hi @johocen168 ,

>There is no configure_app_domain under /opt/bitnami and it seems not working for this old version.

The old stacks had a bnconfig file inside the /opt/bitnami/apps/wordpress folder. You can run that file this way 

```
sudo /opt/bitnami/apps/wordpress/bnconfig --machine_hostname DOMAIN
```

You can learn more about that tool here

https://docs.bitnami.com/google/faq/configuration/understand-bnconfig/

Note: I understand you are following [this guide](https://docs.bitnami.com/google/apps/wordpress-multisite/configuration/configure-wordpress-multisite/) and are running into issues when running the configure_app_domain command, right?

**Comment by johocen168** [comment]
Hi @jotamartos 

Yes, search in bitnami docs will find the new guide only, thanks for your help to provide the tool for old stacks.
