### ISSUE TITLE
[Wordpress] Downgrade PHP in Lightsail

### ISSUE THREAD

**Issue by justinvforvendetta** [bitnami/vms#848]
### Describe your issue as much as you can

how can i downgrade the php version from 8.1 to 7.4?

**Comment by jotamartos** [comment]
Hi @justinvforvendetta,

You can't in AWS Lightsail. They only provide 1 version and downgrading PHP in a running instance is not possible. If you want to use a previous version of PHP, you will need to launch an old version of the solution in the AWS Marketplace or its console.

**Comment by justinvforvendetta** [comment]
yes i figured it out. thank you =]
