### ISSUE TITLE
Magento 2.4.6 Port must be configured within host parameter (like localhost:3306

### ISSUE THREAD

**Issue by AngeloZou** [bitnami/vms#849]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b78bd8f8-6ac0-b22e-d2ff-f58f13c4b913

### bndiagnostic output

/-
The bndiagnostic tool has finished searching for errors and has found some 
issues that might be related to yours. The output will be shown on the next 
page:
                                    
Press [Enter] to continue:

===== Begin of undiagnostic tool output =====

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found
 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3930 1586 497 97 1846 1966 
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

Press [Enter] to continue:
You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Apr 13 16:05:45.772344 2023] [authz_core:error] [pid 1097:tid 
139888703670016] [client **ip_address**:57230] AH01630: client denied by server 
configuration: /opt/bitnami/magento/vendor/phpunit
 [Thu Apr 13 19:12:02.798590 2023] [authz_core:error] [pid 1750:tid 
139888829560576] [client **ip_address**:53016] AH01630: client denied by server 
configuration: /opt/bitnami/magento/vendor/phpunit
 [Fri Apr 14 01:39:14.849065 2023] [authz_core:error] [pid 1097:tid 
139889140516608] [client **ip_address**:54857] AH01630: client denied by server 
configuration: /opt/bitnami/magento/vendor/phpunit

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
Press [Enter] to continue:
rs-apache/

===== End of bndiagnostic tool output =====
                                    
Press [Enter] to continue:
The files listed below are bigger than 10MB and have not been included, please notify the 
support agent.

/opt/bitnami/magento/var/log/cron.log
/opt/bitnami/magento/var/log/debug.log

The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the fo
llowing code:

demo123-123-456-789-demo123467789

And paste it in your Bitnami Support ticket.

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are not ralated with my issue

### Describe your issue as much as you can

I have a Magento 2.4.6 website built using Amazon Lightsail (4 GB RAM，2 个 vCPU，80 GB SSD), which is auto-configured. I’m installing MinimogMG theme, but I’m having trouble.

Port must be configured within host parameter (like localhost:3306

https://prnt.sc/lYTjNjn9-DGk

I followed the steps of the official tutorial. https://docs.bitnami.com/aws/apps/magento/configuration/install-theme/ https://www.youtube.com/watch?v=gpPJTfQoA0c&list=PLGgVZHi3XQNl2T8Q1RMfgLIop3TIFwVad&t=3s

How can i solve?

```
bitnami@ip-172-00-00-01:~/minimog_theme$ sudo /opt/bitnami/magento/bin/magento-cli setup:upgrade
Cache types config flushed successfully
Port must be configured within host parameter (like localhost:3306
In Abstract.php line 144:                                             
  SQLSTATE[HY000] [2002] Connection refused                                               
In Abstract.php line 128:                                             
  SQLSTATE[HY000] [2002] Connection refused                                               
bitnami@ip-172-00-00-01:~/minimog_theme$ 
```

**Comment by gongomgra** [comment]
Hi @AngeloZou,

Thanks for using Bitnami. That seems to be an issue with your custom theme and not with the Bitnami installation. Can you check it with the theme developers?

**Comment by gongomgra** [comment]
Hi @spagu,

Thanks for using Bitnami. As mentioned in a previous message, it seems to be an issue with the theme itself

**Comment by gongomgra** [comment]
Hi @spagu,

Thanks for using Bitnami. As mentioned in a previous message, it seems to be an issue with the theme itself. Can you open a question in the official Magento forums?

https://community.magento.com/
