### ISSUE TITLE
[WordPress] Fails to start MariaDB in Bitnami Google cloud Wordpress

### ISSUE THREAD

**Issue by Perry76** [bitnami/vms#85]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

023d3882-af0d-e6f6-7afe-0a6abe8c4acb

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Wordpress: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Resources: No issues found
    ? Php: Found possible issues
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ? Connectivity: Found possible issues
 

 
[Wordpress]

Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

[Mariadb]

Press [Enter] to continue:
Found recent error messages in the MariaDB error log:
```
2022-06-30 8:26:40 0 [ERROR] Aborting

```
Please check the following guide to troubleshoot MariaDB issues:
 
https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

[Php]

The following error appears in the /opt/bitnami/php/logs/php-fpm.log:
```
[27-Jun-2022 21:30:06] ERROR: fork() failed: Cannot allocate memory (12)

```
This error indicates there is a problem with the memory limit in PHP. Please 
check the following guide to increase the number of PHP-FPM child processes:
 
https://docs.bitnami.com/general/apps/akeneo/administration/increase-memor
y-limit/

Press [Enter] to continue:
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Jun 27 20:50:26.952314 2022] [proxy_fcgi:error] [pid 6935:tid 
139834639234816] (70007)The timeout specified has expired: [client 
**ip_address**:34860] AH01075: Error dispatching request to : (polling)
 [Mon Jun 27 21:05:39.807526 2022] [proxy_fcgi:error] [pid 7332:tid 
139834219599616] (70007)The timeout specified has expired: [client 
**ip_address**:34874] AH01075: Error dispatching request to : (polling)
 [Mon Jun 27 21:20:44.251492 2022] [proxy_fcgi:error] [pid 18966:tid 
139834664412928] (70007)The timeout specified has expired: [client 
**ip_address**:34890] AH01075: Error dispatching request to : (polling)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
Press [Enter] to continue:
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Failed to start LSB: bitnami init script.

### Describe your issue as much as you can

Our website did go down and we could not start up the MariaDB. See log.

**Comment by jotamartos** [comment]
Hi @Perry76,

There are different errors in the MariaDB's log file (/opt/bitnami/mariadb/logs/mysqld.log). 

```
2022-06-27 21:30:47 0 [ERROR] Could not open mysql.plugin table: "Unknown storage engine 'Aria'". Some plugins may be not loaded
2022-06-27 21:30:47 0 [ERROR] Failed to initialize plugins.
2022-06-27 21:30:47 0 [ERROR] Aborting
2022-06-30  7:44:52 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-06-30  7:44:52 0 [Note] InnoDB: Using transactional memory
2022-06-30  7:44:52 0 [Note] InnoDB: Number of pools: 1
2022-06-30  7:44:52 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-06-30  7:44:52 0 [Note] InnoDB: Using Linux native AIO
2022-06-30  7:44:52 0 [Note] InnoDB: Initializing buffer pool, total size = 2147483648, chunk size = 134217728
2022-06-30  7:44:52 0 [Note] InnoDB: Completed initialization of buffer pool
2022-06-30  7:44:52 0 [ERROR] InnoDB: Missing FILE_CHECKPOINT at 511229889927 between the checkpoint 511229889927 and the end 511229889785.
2022-06-30  7:44:52 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2022-06-30  7:44:52 0 [Note] InnoDB: Starting shutdown...
```

Please check the official documentation and its forums to know how to solve this problem.
