### ISSUE TITLE
[Drupal] how to upgrade PHP Version

### ISSUE THREAD

**Issue by irfankhan-art** [bitnami/vms#850]
### Describe your issue as much as you can

Hi,
I am using Bitnami, Drupal Application which has PHP Version 7.4 now i need to update Drupal Application version to 9.5 and it requires PHP Version 8.1. 
I would like to upgrade PHP from version 7.4 to 8.1,Is there a way to do so?

**Comment by gongomgra** [comment]
Hi @irfankhan-art,

Thanks for using Bitnami. It is not possible to increase base dependencies directly from the machine itself. You will have to launch a new Drupal server that already includes PHP 8.x and then migrate the application data there. We recommend you to check official Drupal docs and/or support forums on how to migrate the data from one instance to another.

https://www.drupal.org/forum
