### ISSUE TITLE
[Magento] Fail to install module

### ISSUE THREAD

**Issue by sopi** [bitnami/vms#852]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ace77adb-93b2-ec5f-3878-aba954d0e3bb

### bndiagnostic output

[Fri Apr 14 18:35:09.242918 2023] [authz_core:error] [pid 4526:tid 
140371602401024] [client **ip_address**:40498] AH01630: client denied by server 
configuration: /opt/bitnami/magento/app/etc/config.php
 [Fri Apr 14 18:47:23.241151 2023] [authz_core:error] [pid 3003:tid 
140371786778368] [client **ip_address**:54614] AH01630: client denied by server 
configuration: /opt/bitnami/magento/app/etc/config.php

### bndiagnostic was not useful. Could you please tell us why?

access is 

### Describe your issue as much as you can

I created a new instance (several times already) v. 2.4.6 
Everything was working fine
I uploaded a module under app/code directory
I fix permissions and ownership according to https://docs.bitnami.com/aws/apps/magento/troubleshooting/debug-errors/ .
but looks like generated code cannot instantiate interface of module 
Cannot instantiate interface Amasty\\Base\\Model\\Feed\\Response\\FeedResponseInterface

**Comment by sopi** [comment]
Following error is logged:
`main.CRITICAL: Error: Cannot instantiate interface Amasty\Base\Model\Feed\Response\FeedResponseInterface in /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#1 /bitnami/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create()
#2 /bitnami/magento/generated/code/Amasty/Base/Model/Feed/Response/FeedResponseInterfaceFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create()
#3 /bitnami/magento/app/code/Amasty/Base/Model/Feed/FeedContentProvider.php(92): Amasty\Base\Model\Feed\Response\FeedResponseInterfaceFactory->create()
#4 /bitnami/magento/app/code/Amasty/Base/Model/Feed/FeedTypes/Extensions.php(99): Amasty\Base\Model\Feed\FeedContentProvider->getFeedResponse()
#5 /bitnami/magento/app/code/Amasty/Base/Model/Feed/FeedTypes/Extensions.php(87): Amasty\Base\Model\Feed\FeedTypes\Extensions->getFeed()
#6 /bitnami/magento/app/code/Amasty/Base/Model/Feed/ExtensionsProvider.php(37): Amasty\Base\Model\Feed\FeedTypes\Extensions->execute()
#7 /bitnami/magento/app/code/Amasty/Base/Model/Feed/ExtensionsProvider.php(68): Amasty\Base\Model\Feed\ExtensionsProvider->getAllFeedExtensions()
#8 /bitnami/magento/app/code/Amasty/Base/Model/AmastyMenu/ActiveSolutionsProvider.php(57): Amasty\Base\Model\Feed\ExtensionsProvider->getAllSolutionsData()
#9 /bitnami/magento/app/code/Amasty/Base/Block/Adminhtml/System/Config/Tabs.php(97): Amasty\Base\Model\AmastyMenu\ActiveSolutionsProvider->get()
#10 /bitnami/magento/app/code/Amasty/Base/Block/Adminhtml/System/Config/Tabs.php(84): Amasty\Base\Block\Adminhtml\System\Config\Tabs->prepareConfigData()
#11 /bitnami/magento/app/code/Amasty/Base/view/adminhtml/templates/config/amasty_tabs.phtml(19): Amasty\Base\Block\Adminhtml\System\Config\Tabs->getConfigDataSerialized()
#12 /bitnami/magento/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#13 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#14 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#15 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#16 /bitnami/magento/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#17 /bitnami/magento/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#18 /bitnami/magento/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#19 /bitnami/magento/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#20 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#21 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#22 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#23 /bitnami/magento/app/code/Amasty/Base/Plugin/Config/Block/System/Config/BuildAmastyTabsPlugin.php(48): Magento\Framework\View\Element\AbstractBlock->toHtml()
#24 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(146): Amasty\Base\Plugin\Config\Block\System\Config\BuildAmastyTabsPlugin->afterToHtml()
#25 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Block\System\Config\Tabs\Interceptor->Magento\Framework\Interception\{closure}()
#26 /bitnami/magento/generated/code/Magento/Config/Block/System/Config/Tabs/Interceptor.php(23): Magento\Config\Block\System\Config\Tabs\Interceptor->___callPlugins()
#27 /bitnami/magento/vendor/magento/framework/View/Layout.php(578): Magento\Config\Block\System\Config\Tabs\Interceptor->toHtml()
#28 /bitnami/magento/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#29 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#30 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#31 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#32 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#33 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#34 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#35 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#36 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#37 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#38 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#39 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#40 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#41 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#42 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#43 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#44 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#45 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#46 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#47 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#48 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#49 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#50 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#51 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#52 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#53 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#54 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#55 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#56 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#57 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#58 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#59 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#60 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#61 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#62 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#63 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#64 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#65 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#66 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#67 /bitnami/magento/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement()
#68 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout->getOutput()
#69 /bitnami/magento/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#70 /bitnami/magento/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#71 /bitnami/magento/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(140): Magento\Framework\View\Result\Layout->renderResult()
#72 /bitnami/magento/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#73 /bitnami/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#74 /bitnami/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#75 /bitnami/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#76 {main} {"exception":"[object] (Error(code: 0): Cannot instantiate interface Amasty\\Base\\Model\\Feed\\Response\\FeedResponseInterface at /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121)"} []`
when I access admin store configuration http://3.127.57.26/admin/admin/system_config/index/key/34ec836209e3a175e3e6bc446b470d45d9848a8b50de8694e8ac5ad7fa61a9f4/

**Comment by gongomgra** [comment]
Hi @sopi,

Thanks for using Bitnami. It seems it is not an issue related to the Bitnami Magento image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

https://community.magento.com/

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
