### ISSUE TITLE
[ResourceSpace] The machine could not configure the network interface

### ISSUE THREAD

**Issue by Motocycle347** [bitnami/vms#853]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bitnami-xxx4564678o

### bndiagnostic output

I have tried downloading and running bitnami-resourcespace-10.1.0-r8-debian-11-amd64.ova twice in vmworkstation 17.0.1 build-21139696 second time I boosted Memory to 4096 Meg 6   both times *** The machine could not configure the netwokr interface ***  I looked a a few youtube videos each showed to Bitnami program coming up with an IP. 
#sudo /opt/bitnami/configure_app_domain --domain IP-ADDRESS did not work nor did #sudo /opt/bitnami/apps/APPNAME/bnconfig --machine_hostname IP-ADDRESS

Thaks in advance

### bndiagnostic was not useful. Could you please tell us why?

no ip can not move file

### Describe your issue as much as you can

nothing else

**Comment by Motocycle347** [comment]
Tried same in Virtual Box that correctly finds ip

**Comment by jotamartos** [comment]
Hi @Motocycle347,

did you try other network configuration parameters when deploying the VM using VMware Workstation? 

https://docs.vmware.com/en/VMware-Workstation-Player-for-Linux/16.0/com.vmware.player.linux.using.doc/GUID-C82DCB68-2EFA-460A-A765-37225883337D.html

VirtualBox uses a bridged adapter by default, did you try that one in Workstation? 

Thanks

**Comment by jotamartos** [comment]
That's a strange issue. I just tested the latest OVA with VMware Fusion (Workstation is not available for Mac OS X) and everything worked as expected

![Screenshot 2023-04-19 at 10 22 09](https://user-images.githubusercontent.com/8791635/233014572-a4694d03-fed3-4956-847c-ca802aa89045.png)

Please ensure the VM and the host machine have enough resources when deploying the VM. However, as the VM works well in VirtualBox, you can continue using it there.
