### ISSUE TITLE
Wordpress vm could not configure network interface

### ISSUE THREAD

**Issue by Perks001** [bitnami/vms#854]
### Describe your issue as much as you can

Installed virtual box and inport bitnami wordpress 6.2.0-6r debian. started it, but it says cannot configure network interface. This leaves me with no ip address to type in url of browser. pls i need help

**Comment by gongomgra** [comment]
Hi @Perks001,

Thanks for using Bitnami. I was not able to reproduce your issue. Can you send us a screenshot of the error message your are getting and more details on how to reproduce it? Can you also share your network settings from the VirtualBox settings for the WordPress virtual machine?
