### ISSUE TITLE
[WordPress with nginx] How to increase worker process

### ISSUE THREAD

**Issue by aliehanani** [bitnami/vms#856]
### Describe your issue as much as you can

In increasing the Nginx worker process using `sudo nano /etc/nginx/nginx.conf`, the changes do not reflect after restarting the server. The same limit shows when checking with`ulimit -n`. 

My website crashes everyday due to Google Ad traffic.

**Comment by jotamartos** [comment]
The NGINX's conf file is inside the /opt/bitnami/nginx/ folder. Please edit the configuration as needed and restart the service using the /opt/bitnami/ctlscript.sh file.

Thanks

**Comment by aliehanani** [comment]
I checked the `/opt/bitnami/nginx/conf/nginx.conf` and it reflected the same changes I had made in `/etc/nginx/nginx.conf`.

The only other place is was to edit the worker is in `/opt/bitnami/nginx/conf/nginx.conf.default` but that too didn't worked.

**Comment by aliehanani** [comment]
I made the changes like below, and after restarts, including the VM, it does not reflect the change.

`worker_processes  4;

.....................

events {
    worker_connections  2024;
}`

**Comment by jotamartos** [comment]
Hi @aliehanani,

This is a NGINX-related question so we suggest you check its official documentation and guidelines regarding how to configure this parameter. As I mentioned above, the conf file is at `/opt/bitnami/nginx/conf/nginx.conf` and you should edit that one. You should use the /opt/bitnami/ctlscript.sh file to restart the service. You can perform any change in the conf file and restart the service after that.

**Comment by aliehanani** [comment]
Hey @jotamartos, 

I created a new VM on Azure with Bitnami image. I tried increasing the `worker_processes` and `worker_connections`, I followed NGINX documentations, but the changes are not taking into effect. 

Were you able to replicate the issue on your end? 

I have included a screenshot of the 2 simple changes I had first tested. The `worker_connections 4096;` from `worker_connections 1096;` and `worker_processes  8;` from `worker_processes  auto;`. I had even included `worker_rlimit_nofile 4096;` for open file limitations.

At this point I suspect that the rules made in `/opt/bitnami/nginx/conf/nginx.conf` are being overridden elsewhere.



<img width="830" alt="Screenshot 2023-04-19 at 1 09 47 AM" src="https://user-images.githubusercontent.com/12172666/232867372-240963b6-7a74-49f2-bdfd-76c4a3349112.png">

**Comment by jotamartos** [comment]
Hi @aliehanani,

I could edit those parameters without problems

```
bitnami@debian:~$ head -n 10 /opt/bitnami/nginx/conf/nginx.conf
# Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
user              daemon daemon;  ## Default: nobody

worker_processes  3;
error_log         "/opt/bitnami/nginx/logs/error.log";
pid               "/opt/bitnami/nginx/tmp/nginx.pid";

events {
    worker_connections  4096;
}
bitnami@debian:~$ ps aux | grep nginx
root        1948  0.0  0.1  10756  1480 ?        Ss   10:59   0:00 nginx: master process /opt/bitnami/nginx/sbin/nginx -c /opt/bitnami/nginx/conf/nginx.conf
daemon      1949  0.0  0.4  11976  4988 ?        S    10:59   0:00 nginx: worker process
daemon      1950  0.0  0.4  11976  4988 ?        S    10:59   0:00 nginx: worker process
daemon      1951  0.0  0.4  11976  4988 ?        S    10:59   0:00 nginx: worker process
bitnami     1956  0.0  0.0   6244   700 pts/0    S+   10:59   0:00 grep nginx
```

As you can see there are 3 nginx worker processes because I set the parameter to 3. Regarding the worker connections, you can [increase the limits in the system](https://askubuntu.com/questions/162229/how-do-i-increase-the-open-files-limit-for-a-non-root-user) and then modify the webserver's configuration.
