### ISSUE TITLE
[Lighsail Wordpress AWS 6.1.1-60] <Failed to import Media>

### ISSUE THREAD

**Issue by Taufiqs95** [bitnami/vms#857]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

adbbcd9c-3d05-63f2-7a35-d2529274b5e7

### bndiagnostic output

===== Begin of bndiagnostic tool output =====
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
 
 [Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 472 336 7 42 127 81 Swap: 634 
231 403
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Some files don't have the expected permissions Please check the following guide:
 
https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Apr 16 10:11:06.510789 2023] [proxy_fcgi:error] [pid 11053:tid 
140349406152448] [client **ip_address**:23149] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php 
on line 172PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
Press [Enter] to continue:
/bitnami/wordpress/wp-config.php on line 173'
 [Sun Apr 16 10:36:53.852283 2023] [proxy_fcgi:error] [pid 11053:tid 
140350312105728] [client **ip_address**:46756] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php 
on line 172PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 173'
 [Sun Apr 16 11:21:20.456306 2023] [proxy_fcgi:error] [pid 8595:tid 
140350379247360] [client **ip_address**:27206] AH01071: Got error 'PHP message: 
PHP Warning: Undefined array key "HTTP_HOST" in /bitnami/wordpress/wp-config.php 
on line 172PHP message: PHP Warning: Undefined array key "HTTP_HOST" in 
/bitnami/wordpress/wp-config.php on line 173PHP message: PHP Warning: Undefined 
array key "host" in /opt/bitnami/wordpress/wp-includes/canonical.php on line 
689PHP message: PHP Warning: Undefined a
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the fo
llowing code:

adbbcd9c-3d05-63f2-7a35-d2529274b5e7

And paste it in your Bitnami Support ticket.

### bndiagnostic was not useful. Could you please tell us why?

bndiagnostic used successfully Import media Wordpress failed

### Describe your issue as much as you can

Hello Admin Support Bitnami Wordpress AWS Lighsail

Please help me, having a problem when I import wordpress XML file
1. Wordpress Media Failed.
2. Successfully import Wordpress posts
3. Successfully import WordPress pages

Previously, my Wordpress version uploaded all the WordPress files successfully and successfully. When there was an update I found an error that I couldn't import media files.

`the important point is that I restarted wordpress on lightsail, I still experience the same thing, namely import media wordpress still fails.`

Please help me to overcome all of this, so that I can keep going well in renting on AWS.
[https://prnt.sc/UFQO7hYxKeer](https://prnt.sc/UFQO7hYxKeer)

Thank You
Taufiq Setiawan

**Comment by mdhont** [comment]
It does not seem related to the bitnami configuration. I recommend asking in the official WordPress forum.

https://wordpress.com/forums/
