### ISSUE TITLE
[WordPress] Website is down after trying to install Really Simple SSL

### ISSUE THREAD

**Issue by FerozeHanif** [bitnami/vms#858]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f602798c-248b-bd53-62f7-80e9d205e91a

### bndiagnostic output

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 472 339 11 4 121 115 Swap: 634 
2 632
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

The Apache configuration has errors:
```
AH00526: Syntax error on line 6 of 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: 
SSLCertificateKeyFile: file '/opt/bitnami/apache/conf/bitnami/certs/server.key' 
does not exist or is empty
```
Please check the configuration.

### bndiagnostic was not useful. Could you please tell us why?

I have renamed the really simple ssl folder but still getting the error

### Describe your issue as much as you can

The issue began when I tried to install Really Simple SSL.  My WP admin site is no longer available.

I have renamed the Really Simple SLL folder.

In Lightsail by ports are enabled but bndiagnostics shows the ports are not publicly accessible.  I'm not sure how to enable them in bitnami or if that even is possible.

**Comment by jotamartos** [comment]
It seems the .key file was removed when you used Really Simple SSL. We always recommend using our SSL configuration tool that allows you easily generate the SSL certificates in the instance

https://docs.bitnami.com/general/how-to/understand-bncert/

You have 2 options now:

- Manually generate a sample SSL certificate to fix the current error

https://docs.bitnami.com/general/how-to/understand-bncert/

>Note: You need to create the SSL certs inside the /opt/bitnami/apache/conf/bitnami/certs/ folder.

and then run bncert as explained in the guide above. 

- Or you can follow the manual approach

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
