### ISSUE TITLE
[<Joomla>] <OVA>

### ISSUE THREAD

**Issue by lennart-live** [bitnami/vms#859]
### Describe your issue as much as you can

Where can i download a Bitnami Joomla appliance with PhP 7.5 and Joomla 3.10.11 or something like that. My Joomla template does not support PhP 8. 
I know there must be a OVA near this config consulting the Bitnami changelog but i can't seem to find any download mirror.

**Comment by gongomgra** [comment]
Hi @lennart-live,

Thanks for using Bitnami. Unfortunately, the oldest Joomla virtual-machine I could found includes PHP 8.0 and Joomla 3.10.11. Sorry for the inconveniences.

**Comment by lennart-live** [comment]
Hi gongomgra,
Thanks for your reply.
Is it possible to downgrade PhP in this version and is there any how to for that?
What kind of SSL is Bitnami using for this appliance? Is it PEM or can i use my .crt certificate which i bought from my hosting provider?
Thanks again. 
Lennart
