### ISSUE TITLE
[<Bitnami AWS Wordpress Production Ready>] <504 Gateway Time-out>

### ISSUE THREAD

**Issue by smartcafirms** [bitnami/vms#86]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

849fabe0-d11f-11cb-4a34-e4ec5361be461

### bndiagnostic was not useful. Could you please tell us why?

i am not able to run bndiagnostic

### Describe your issue as much as you can

While performing an import in one of the plugin in wordpress admin panel, it all of a sudden stuck (may be due to too many requests). 

The website ([https://www.smartcafirms.com/ ](https://www.smartcafirms.com/)) as well as the WP Admin URL ([https://smart-appli-yviomc5l402s-889893408.ap-south-1.elb.amazonaws.com/wp-admin ](https://smart-appli-yviomc5l402s-889893408.ap-south-1.elb.amazonaws.com/wp-admin)) throws 504 Gateway Time-out error

For your information, I have launched a Bitnami Wordpress Production Ready Stack

**Comment by mdhont** [comment]
Could you check the available resources? 

    free -h

And could you run the bndiagnostic tool again and send me the output ID?

    sudo /opt/bitnami/bndiagnostic-tool
