### ISSUE TITLE
[Odoo] Settings not available

### ISSUE THREAD

**Issue by kpgarrod** [bitnami/vms#860]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

885dd55f-22ed-35bb-abd2-245ada50c770

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Connectivity: Found possible issues
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ✓ Resources: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Apr 17 05:26:09.314223 2023] [proxy:error] [pid 5352:tid 139748146530048] 
Press [Enter] to continue:
(111)Connection refused: AH00957: http: attempt to connect to 
**ip_address**:8069 (127.0.0.1:8069) failed
 [Mon Apr 17 05:26:09.314309 2023] [proxy_http:error] [pid 5352:tid 
139748146530048] [client **ip_address**:45858] AH01114: HTTP: failed to make 
connection to backend: 127.0.0.1

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

There doesn't appear to be a network issue because I am able to connect to the Odoo application correctly

### Describe your issue as much as you can

When I log into the Odoo database as 'Mitchell Admin' I am not able to see any Settings except Users and Companies. This is despite the fact that the user has 'settings' access rights.

I have tried creating new databases but still experience the same behaviour.
 
![Screenshot from 2023-04-17 15-54-18](https://user-images.githubusercontent.com/2155409/232505447-c3a68947-b26c-4c58-9241-3e36b7f4bb5d.png)

**Comment by jotamartos** [comment]
Hi @kpgarrod ,

This is a Odoo-related question so we suggest you check its documentation and support forums to know more about this. Please note that we take the open source files and configure the application but do not block or limit any functionality. 

Thanks
