### ISSUE TITLE
[Apache]  - HTTP/1.1 302 Found - Request exceeded the limit of 10 internal redirects

### ISSUE THREAD

**Issue by BubblesFWalsh** [bitnami/vms#862]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5fd74f62-4254-f71c-c2b8-2382cb8607e1

### bndiagnostic output

? Apache: Found possible issues
[Mon Apr 17 07:09:04.602261 2023] [core:error] [pid 14328:tid 139730687473408] 
[client **ip_address**:35284] AH00124: Request exceeded the limit of 10 internal 
redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Mon Apr 17 07:09:05.247416 2023] [core:error] [pid 14327:tid 139730712651520] 
[client **ip_address**:35764] AH00124: Request exceeded the limit of 10 internal 
redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Mon Apr 17 11:36:26.407912 2023] [core:error] [pid 14328:tid 139730586760960] 
[client **ip_address**:42304] AH00124: Request exceeded the limit of 10 internal 
redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
Press [Enter] to continue:
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., 
referer: 
https://34.245.181.202/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php

### bndiagnostic was not useful. Could you please tell us why?

I still do not know what is causing the internal redirect loop and 302

### Describe your issue as much as you can

Hi Bitnami Support,

I am attempting to setup Gelato and Woocommerce store integration. I have installed the Gelato Wordpress plugin and I the Gelato app flagged a redirection issue. Please see below for full warning message:-

 

> If your site is configured with redirection to another URL, there might be some issues. Usually, this happens with incorrect HTTP to HTTPS redirects or yourdomain.com to www.yourdomain.com. Please check your settings.

I then used their recommended tool seen below to verify the issue.  It flagged the following issue:-
[https://www.redirect-checker.org/index.php](url)

Result:-

> http://trevorwalsh.art
> 302 Found
> https://trevorwalsh.art/
> 200 OK
> 
> 
> Problems found:
> 
> You use a 302 redirect. This means, that the actually content is temporary not reachable and will come back soon. To use a 302 redirection for generally moved pages is a bad idea. Search engine bot might not follow it or handle it as temporary. For SEO this is also a bad idea, because no link juice will be transferred to the linked page.

------------

I verified the using the following HTTP curl to my root domain seen in the Gelato recommended tool. I have uploaded the curl output txt file. I can see my Apache server responds with the 302 Found and then 200 OK. 
--> curl -L -svo /dev/null trevorwalsh.art
< HTTP/1.1 302 Found
< HTTP/1.1 200 OK

From investigating this with online resources it appears to be related to a redirect loop and when I ran the Bitnami Diagnostic Tool it confirmed this with the following error (more were included):-
> [Mon Apr 17 11:36:26.407912 2023] [core:error] [pid 14328:tid 139730586760960] 
> [client **ip_address**:42304] AH00124: Request exceeded the limit of 10 internal 
> redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
> Press [Enter] to continue:
> increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

I have checked the 'wordpress-htaccess.conf' file and I cannot see any problem lines in the code. It is the default 'wordpress-htaccess.conf' file that was added with the creation of the stack apart from adding the required following code line to setup the Woocommerce/Gelato store integration.

The WooCommerce plugin intergration required line
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1"`

I have also reviewed in the 'wordpress-vhost.conf'. I can see the following active line of code that I thought might be causing the issue:-
`RewriteRule ^/?(.*) %{REQUEST_SCHEME}://%1.nip.io%2/$1 [L,R=302,NE]`

I changed it the 'R=302' to 'R=301' and restarted Apache.

I also did the same in the 'wordpress-https-vhost.conf'.  I changed it the 'R=302' to 'R=301' in the following line and restarted Apache. But this did not resolve the 302 issue.
`RewriteRule ^/?(.*) %{REQUEST_SCHEME}://%1.nip.io%2/$1 [L,R=302,NE]`

I also disabled all active plugins but I still saw the 302 when carrying out the same curl test.

So I am stumped and would appreciate any help to configure Apache to return '301 Moved Permanently'. 

Trevor

[curl-trevorwalsh-art-302-found.txt](https://github.com/bitnami/vms/files/11255219/curl-trevorwalsh-art-302-found.txt)
[wordpress-vhost.txt](https://github.com/bitnami/vms/files/11255220/wordpress-vhost.txt)
[wordpress-https-vhost.txt](https://github.com/bitnami/vms/files/11255221/wordpress-https-vhost.txt)
[wordpress-htaccess.txt](https://github.com/bitnami/vms/files/11255222/wordpress-htaccess.txt)

**Comment by BubblesFWalsh** [comment]
Sorry about the formatting of the post. This is my first post on Github so I am not familiar with the tools yet

**Comment by BubblesFWalsh** [comment]
Hello,

I carried out a test by launching a new Lightsail instance using the 'WordPress Multisite Certified by Bitnami and Automattic 6.1.1-60' stack. I carried out no changes on the server. I did not even login to it :) However when I carried out a HTTP 'curl -L' test to the instances public IP saw the 'HTTP/1.1 302 Found' redirect to 'Location: http://34.255.29.142.nip.io'.  Then another request is sent to URL: 'http://34.255.29.142.nip.io/'. Please see attached curl output. So the 302 is present in the default config from what I can see.

Thanks,

Trevor

[curl-L-34-255-29-142.txt](https://github.com/bitnami/vms/files/11266544/curl-L-34-255-29-142.txt)

**Comment by jotamartos** [comment]
The redirection to nip.io is configured by default in WordPress Multisite because it requires a domain to work and IP.nip.io is a valid domain that points to the IP of the machine. 

Regarding the permanent redirection in your configuration, you have many custom rules in the Apache's configuration. To solve this easily, you can update the R flag in all rewrite lines in the `apache/conf/bitnami/bitnami*` and `apache/conf/vhosts/wordpress*` files.

**Comment by BubblesFWalsh** [comment]
Hi Juan,

Thanks for the reply.  I have carried out the steps you recommended and updated all R flags in all the files to 'R=301' and I now see --> HTTP/1.1 301 Moved Permanently.

Yes I agree that I had no issue with the server or the 302 Found response. However I am developing an art store and my next task was to integrate Gelato print on demand service with my WooCommerce store. However the Gelato app flagged the 302 response as an issue and would not finalise the integration using their API.  So had to figure out how to configure Apache to return the required 301 redirect code. I am sure other people are having the same issue. 

This is great to get updated so thank you very much for the support 😊

Trevor
