### ISSUE TITLE
[Bitnami Moodle] Always crashing on Kubernetes

### ISSUE THREAD

**Issue by patrickk2000** [bitnami/vms#865]
### Describe your issue as much as you can

i have tried bitnami moodle helm and bitnami image with local K8S deployment, it always crashes when installing moodle script, only works with docker compose. Doesn't work as a helm chart 0% also tried a custom deployment file, the image is broken for Kubernetes.

**Comment by patrickk2000** [comment]
Doesn't work at all please fix, docker compose only works and only!

**Comment by patrickk2000** [comment]
Kindly note that i am using an RKE cluster

**Comment by patrickk2000** [comment]
I have tried multiple approaches such as allocating high resources, increasing pod setup timeout, nothing worked then i thought helm would work, which also did not work, please help as i need to run bitnami moodle on K8S

**Comment by gongomgra** [comment]
Hi @patrickk2000,

Thanks for your interest in using Bitnami, and sorry for the inconveniences you are facing. Notice this is the forum for virtual machines and cloud images solutions, while you are having issues with our Helm chart. Please open your question in our [charts repository](https://github.com/bitnami/charts/issues), where our team will do their best to help you with your issue. Remember to include as much information as possible to help them diagnose your issue (describe pods, logs, install command, any custom `values.yaml` file you used, etc.).

I'm closing this ticket as it doesn't apply to this forum.

**Comment by patrickk2000** [comment]
Hi @gongomgra 

Issue has been raised to bitnami charts, thank you!

**Comment by gongomgra** [comment]
Hi @patrickk2000,

Thanks for letting us know. Our team will help you there. I'm just sharing the link here for the record

https://github.com/bitnami/charts/issues/16200
