### ISSUE TITLE
[Bitnami Wordpress] Server freezes for no reason

### ISSUE THREAD

**Issue by wedevafrica** [bitnami/vms#866]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ae7fc1ee-5a0a-c156-fcf4-343d2e4d972c

### bndiagnostic output

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Not very useful documented

### Describe your issue as much as you can

Server goes down for no reason. According to the logs there's a imeout

```
[Fri Apr 21 00:40:16.005901 2023] [proxy_fcgi:error] [pid 9285:tid 140634132276992] (70007)The timeout specified has expired: [client 13.50.250.178:34132] AH01075: Error dispatching request to : (polling)
[Fri Apr 21 00:40:17.012282 2023] [proxy_fcgi:error] [pid 9285:tid 140633863710464] (70007)The timeout specified has expired: [client 13.50.250.178:33974] AH01075: Error dispatching request to : (polling)
[Fri Apr 21 00:40:14.861005 2023] [proxy_fcgi:error] [pid 9285:tid 140633762998016] (70007)The timeout specified has expired: [client 13.50.250.178:33902] AH01075: Error dispatching request to : (polling)
```

I have to Force Stop the instance in AWS, sometimes need to click "Force Stop" 3-4 times

```
[Fri Apr 21 04:46:11.383933 2023] [core:warn] [pid 815:tid 140183954029824] AH00098: pid file /opt/bitnami/apache/var/run/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Apr 21 04:46:11.387751 2023] [mpm_event:notice] [pid 815:tid 140183954029824] AH00489: Apache/2.4.56 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Fri Apr 21 04:46:11.387902 2023] [core:notice] [pid 815:tid 140183954029824] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Fri Apr 21 04:50:32.177536 2023] [ssl:warn] [pid 805:tid 140479067524352] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Apr 21 04:50:32.187937 2023] [ssl:warn] [pid 806:tid 140479067524352] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Apr 21 04:50:32.188291 2023] [core:warn] [pid 806:tid 140479067524352] AH00098: pid file /opt/bitnami/apache/var/run/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Apr 21 04:50:32.190252 2023] [mpm_event:notice] [pid 806:tid 140479067524352] AH00489: Apache/2.4.56 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Fri Apr 21 04:50:32.190289 2023] [core:notice] [pid 806:tid 140479067524352] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
```

**Comment by wedevafrica** [comment]
Server went again own

`[Sat Apr 22 01:42:24.545301 2023] [proxy_fcgi:error] [pid 294633:tid 140018978825984] [client 13.244.53.239:38016] AH01067: Failed to read FastCGI header
[Sat Apr 22 01:42:24.546154 2023] [proxy_fcgi:error] [pid 294633:tid 140018978825984] (104)Connection reset by peer: [client 13.244.53.239:38016] AH01075: Error dispatching request to : 
[Sat Apr 22 01:42:24.579773 2023] [proxy_fcgi:error] [pid 294000:tid 140017963865856] [client 20.25.184.84:63479] AH01067: Failed to read FastCGI header
[Sat Apr 22 01:42:24.579803 2023] [proxy_fcgi:error] [pid 294000:tid 140017963865856] (104)Connection reset by peer: [client 20.25.184.84:63479] AH01075: Error dispatching request to : 
[Sat Apr 22 01:42:24.581309 2023] [proxy_fcgi:error] [pid 293984:tid 140019079538432] [client 13.244.53.239:38060] AH01067: Failed to read FastCGI header
[Sat Apr 22 01:42:24.581328 2023] [proxy_fcgi:error] [pid 293984:tid 140019079538432] (104)Connection reset by peer: [client 13.244.53.239:38060] AH01075: Error dispatching request to : 
[Sat Apr 22 01:42:25.701107 2023] [proxy:error] [pid 294633:tid 140018752354048] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
[Sat Apr 22 01:42:25.701144 2023] [proxy_fcgi:error] [pid 294633:tid 140018752354048] [client 20.25.184.84:62390] AH01079: failed to make connection to backend: httpd-UDS
[Sat Apr 22 01:42:26.832452 2023] [proxy:error] [pid 294633:tid 140018995611392] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed
[Sat Apr 22 01:42:26.832484 2023] [proxy_fcgi:error] [pid 294633:tid 140018995611392] [client 20.25.184.84:63022] AH01079: failed to make connection to backend: httpd-UDS
[Sat Apr 22 01:42:27.845088 2023] [mpm_event:notice] [pid 293974:tid 140019840163072] AH00491: caught SIGTERM, shutting down`

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading to a more powerful one:

https://docs.bitnami.com/aws/faq/administration/upgrade-ami/

**Comment by wedevafrica** [comment]
Hi there @mdhont ,

I changed from Dynamic Mode to OnDemand Mode and this did the trick. No more downtimes since then
