### ISSUE TITLE
How to connect to Bitnami ERPNext, hosted as a VM on virtual box on windows, over the internet (not within DHCP server).

### ISSUE THREAD

**Issue by newtonkakadia** [bitnami/vms#867]
### Describe your issue as much as you can

I have setup Bitnami ERPNext VM on a virtual box on windows. I want to host it and connect to it from another device online on the internet. (PS: The another device wanting to connect is not on the same DHCP server).
I am able to connect using DHCP server's ip, while on internal network.

Please help.

**Comment by mdhont** [comment]
This guide might be helpful:

https://docs.bitnami.com/virtual-machine/faq/administration/connect-remotely/

However, that is only if the device is on the same network as the host. To connect it fully to the internet I recommend asking in the virtualbox forum. I found a thread that explains how it could be done:

https://www.golinuxcloud.com/connect-internet-bridge-nat-vmware-virtualbox/
