### ISSUE TITLE
[Alfresco] solr error

### ISSUE THREAD

**Issue by apompilio95** [bitnami/vms#868]
### Describe your issue as much as you can

hi, i downloaded the latest ova of alfresco by bitnami version 7.3
after installing and starting the SORL part it gives me error,
not allowing you to insert tags or search for documents.
Anyone who can help me?
Thank you

the error is:
"Solr request failed with 403 /solr/alfresco/alfresco?"

**Comment by jotamartos** [comment]
Hi @apompilio95,

>after installing and starting the SORL part it gives me error,

I understand you manually installed Solr in the virtual machine, right? If you have any connectivity issue, we suggest you review the official documentation of the application or contact the app's developers to get more information about the issue. We do not have any guide that explains how to connect these 2 apps and this type of questions are out of the scope of this forum.

Thanks
