### ISSUE TITLE
[Bitnami Wordpress] <Website Crashed - MariaDB Cannot be started>

### ISSUE THREAD

**Issue by ECPAdmin** [bitnami/vms#87]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7d2e4c64-556d-ecfb-e4fd-91550d8c1138

### bndiagnostic output

-\Error copying file from /opt/bitnami/mariadb/logs/mysqld.log to /tmp/bndiagnostic-05b4c91a354b8b18/bitnami-wordpress-info-20220707-130250-1860/mariadb/logs
:/opt/bitnami/mariadb/logs/mysqld.log is not readable
Abort, Retry, Ignore ? [A/r/i]test ! -f "/opt/bitnami/common/bin/openssl" && echo "Approach A: Using system packages." || echo "Approach B: Self-contained installation."

Error copying file from /opt/bitnami/mariadb/logs/mysqld.log to /tmp/bndiagnostic-05b4c91a354b8b18/bitnami-wordpress-info-20220707-130250-1860/mariadb/logs
:/opt/bitnami/mariadb/logs/mysqld.log is not readable
Abort, Retry, Ignore ? [A/r/i]a

Error copying file from /opt/bitnami/php/logs/php-fpm.log to /tmp/bndiagnostic-05b4c91a354b8b18/bitnami-wordpress-info-20220707-130250-1860/php/logs
:/opt/bitnami/php/logs/php-fpm.log is not readable
Abort, Retry, Ignore ? [A/r/i]a

### bndiagnostic was not useful. Could you please tell us why?

bndiagnostic couldn't show me the errors

### Describe your issue as much as you can

Dear Bitnami Community,

Our website was working so good yesterday but I don't know what happened during the night but it crashed so bad and I can't make it work :( I suspected from the hardware resources and tried to have the snapshot and run it on a more powerful machine but it's still the same.

the main issue is seems like MariaDB cannot be started, I followed the all tutorials on the community website, none of them worked, I also renewed the SSL Certificate, just in case.

Please help me :) hehe

Looking forward to hearing back from you,
All the best,
ECP Admin.

**Comment by ECPAdmin** [comment]
bitnami@ip-172-26-13-187:/opt/bitnami$ systemctl status bitnami.service
● bitnami.service - LSB: bitnami init script
   Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2022-07-07 14:19:37 UTC; 2min 16s ago
  Process: 2643 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
    Tasks: 21 (limit: 2373)
   Memory: 232.2M
   CGroup: /system.slice/bitnami.service
           ├─644 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
           ├─648 php-fpm: pool www
           ├─649 php-fpm: pool www
           ├─650 php-fpm: pool www
           ├─651 php-fpm: pool www
           ├─652 php-fpm: pool www
           ├─653 php-fpm: pool www
           ├─654 php-fpm: pool www
           ├─655 php-fpm: pool www
           ├─656 php-fpm: pool www
           ├─657 php-fpm: pool www
           ├─658 php-fpm: pool www
           ├─659 php-fpm: pool www
           ├─660 php-fpm: pool www
           ├─661 php-fpm: pool www
           ├─662 php-fpm: pool www
           ├─663 php-fpm: pool www
           ├─664 php-fpm: pool www
           ├─665 php-fpm: pool www
           ├─666 php-fpm: pool www
           └─667 php-fpm: pool www

Jul 07 14:19:37 ip-172-26-13-187 bitnami[2643]: mariadb 14:19:37.63 ERROR ==> mariadb did not start
Jul 07 14:19:37 ip-172-26-13-187 bitnami[2643]: 2022-07-07T14:19:37.636Z - error: Unable to perform start operation Export start for mariadb failed with exit code 1
Jul 07 14:19:37 ip-172-26-13-187 bitnami[2643]: ## 2022-07-07 14:19:37+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_bitnami_agent_extra...
Jul 07 14:19:37 ip-172-26-13-187 bitnami[2643]: ## 2022-07-07 14:19:37+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agent...
Jul 07 14:19:37 ip-172-26-13-187 bitnami[2643]: ## 2022-07-07 14:19:37+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welcome_file...
Jul 07 14:19:37 ip-172-26-13-187 bitnami[2643]: ## 2022-07-07 14:19:37+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_credentials_file...
Jul 07 14:19:37 ip-172-26-13-187 bitnami[2643]: ## 2022-07-07 14:19:37+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metadata...
Jul 07 14:19:37 ip-172-26-13-187 systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
Jul 07 14:19:37 ip-172-26-13-187 systemd[1]: bitnami.service: Failed with result 'exit-code'.
Jul 07 14:19:37 ip-172-26-13-187 systemd[1]: Failed to start LSB: bitnami init script.
lines 17-39/39 (END)

**Comment by ECPAdmin** [comment]
I started a new instance from the snapshot and applied to the codes below:

```
sudo mv /bitnami/mariadb/data/ibdata1 /bitnami/mariadb/data/ibdata1.bak
sudo mv /bitnami/mariadb/data/ib_logfile0 /bitnami/mariadb/data/ib_logfile0.bak
```
And then restart mariadb:

`sudo /opt/bitnami/ctlscript.sh restart mariadb`

This took me to the WordPress installation page and when I proceed with the installation I have so many database error as seen attached:
[wpdberrors.txt](https://github.com/bitnami/vms/files/9065584/wpdberrors.txt)

Surprisingly it says Success! whenever I proceed with the log in button, it's taking me to the beginning - to the wordpress installation page and this is a never ending loop ( already tried 5 times :) )

**Comment by mdhont** [comment]
Can you check if the permissions for the `/opt/bitnami/mariadb/data` folder are correct? 

https://docs.bitnami.com/google/how-to/troubleshoot-permission-issues/

**Comment by ECPAdmin** [comment]
![mariadb](https://user-images.githubusercontent.com/108880786/179224230-8f044361-bdc9-4f34-876e-6936ca5d4566.png)

@mdhont I'm attaching a screenshot of the mariadb and contents' file/folder permissions, it seems everything is okay.
website somehow started working after I deleted the ib_logfile0 previously but it crashed again and even that method is not working now.

**Comment by mdhont** [comment]
I recommend disabling all WordPress plugins and check if the issue still happens:

    wp plugin deactivate --all

If not, then the issue is due to a plugin and you can activate them one by one to find out which one.

**Comment by ECPAdmin** [comment]
I ran some other tests, the root cause is the database, AWS Lightsail somehow not stable enough to run Bitnami Wordpress yet.. I moved one of my websites into FastComet shared hosting- the speed is trippled and crashing of the db is never happened again.
Please check out the AWS Lightsail wordpress installer, it may have some issues.

**Comment by ToddE** [comment]
I'm seeing the same issue with Lightsail Wordpress MultiSite -- no issue with non-Multisite wordpress

**Comment by mdhont** [comment]
@ToddE, could you try disabling the plugins as per my previous reply? If it doesn't work please create a new separate issue.
