### ISSUE TITLE
[Wordpress] App creates Admin Account  and Sending Emails Itself

### ISSUE THREAD

**Issue by mazambadar** [bitnami/vms#870]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3159e7a0-8010-2b2a-f9ca-942d14ffebd1

### bndiagnostic output

<img width="857" alt="email-Ss" src="https://user-images.githubusercontent.com/49985366/233836399-ac2c20ad-6a1c-4280-bdef-bd976a8e2162.png">

### bndiagnostic was not useful. Could you please tell us why?

I can not understand 

### Describe your issue as much as you can

I am using WordPress Bitnami Image on AWS Lightsail and having some security issues since March. System is creating accounts with Administrator permissions and sending emails and also changed admin email also. Please let me know what is wrong and how to fix this.

**Comment by jotamartos** [comment]
That's a WordPress-related question so we suggest you ask in the official forums of the application to get more information. We also suggest you install any security plugin to scan and analyze your installation. 

Thanks
