### ISSUE TITLE
[Bitnami WordPress 5.7.2-34] Existing app stopped working, runs cleanly on restart for several minutes then php-fpm processes hang

### ISSUE THREAD

**Issue by bitmyhaven** [bitnami/vms#871]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3de5a0ef-f324-2a51-6d3b-ba1517ced664

### bndiagnostic output

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Apr 23 13:24:55.884505 2023] [proxy_fcgi:error] [pid 1548:tid 
139912812504832] (70007)The timeout specified has expired: [client 
**ip_address**:33432] AH01075: Error dispatching request to : (polling)
 [Sun Apr 23 13:24:56.926502 2023] [proxy_fcgi:error] [pid 1548:tid 
139912686614272] (70007)The timeout specified has expired: [client 
Press [Enter] to continue:
**ip_address**:9946] AH01075: Error dispatching request to : (polling), referer: 
http://friedensbewegung.com
 [Sun Apr 23 13:25:10.528324 2023] [proxy_fcgi:error] [pid 
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

[Resources]

Your instance has little available RAM memory.
```
Press [Enter] to continue:
 total used free shared buff/cache available Mem: 482 316 7 27 159 125 Swap: 634 

### bndiagnostic was not useful. Could you please tell us why?

will check on its suggestions, but look unlikely

### Describe your issue as much as you can

Site has been running unattended since 2021 the a few days ago we started getting gateway timeout errors when connecting. We use all factory settings. After restart, the app works well for a few minutes then we see 15 php-fpm processes spawned and load goes to ~ 15 and the app is again giving gateway timeouts. Tried reducing the number of php-fpm processes in the config by setting pm=ondemand and pm=fixed, but always 15 processes are spawned

**Comment by bitmyhaven** [comment]
Thank you very much. Your diagnostic tool is great and your interpretation of the results; I blocked the offending IP and the site has returned to being usable again

Thanks Again!
K

________________________________

**Comment by gongomgra** [comment]
Hi @bitmyhaven,

Thanks for your message. I'm glad you could fix your issue! We are closing this ticket as solved.
