### ISSUE TITLE
[Mediawiki] Sidebar category/menu collapsible navigation. Looking for side, up and down arrow(>) mark

### ISSUE THREAD

**Issue by subesingh1981** [bitnami/vms#874]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ca04593a-3da2-0796-d5d2-22dfb35f3c5c

### bndiagnostic was not useful. Could you please tell us why?

It is not related to it.

### Describe your issue as much as you can

Hi,

We are using Mediawiki on gcp. Looking for Sidebar category/menu collapsible navigation. Would like to add side, up and down arrow(>) mark.
I tried Extension:CollapsibleVector. https://www.mediawiki.org/wiki/Extension:CollapsibleVector.
Collapsible navigation start working after installation of plugin.  But arrow mark is not there.

After it I tried CategoryTree and TreeAndMenu extension but it does not apply the required changes. 

I am also looking for multiple level categories in side bar. 

e.g.    *welcome1
                      **welcome2
                                    *** welcome3
I tried in Mediawiki:Sidebar edit page. but does work.

Please guide how I can proceed further.

Thanks,
Sube

**Comment by subesingh1981** [comment]
Any update please

**Comment by jotamartos** [comment]
Hi @subesingh1981,

Thank you for using Bitnami but that's a Mediawiki-related question and it's out of the scope of this support forum. Please contact the Mediawiki's community or the plugin's developers to get more information about how to use that extension. 

Thanks

**Comment by subesingh1981** [comment]
thank you for update
