### ISSUE TITLE
[Mediawiki] User access management

### ISSUE THREAD

**Issue by subesingh1981** [bitnami/vms#875]
### Describe your suggestion as much as you can

Hi,

Is it feasible to implement that "A member of one group must be able to edit only the pages created by members of that group".

Best Regards,
Sube

**Comment by subesingh1981** [comment]
Any update please

**Comment by jotamartos** [comment]
Hi again @subesingh1981,

Thank you for using Bitnami but that's a Mediawiki-related question and it's out of the scope of this support forum. Please contact the Mediawiki's community or review the information in its documentation to know more about how to use the application.

Thanks

**Comment by subesingh1981** [comment]
ok thank you for update
