### ISSUE TITLE
[bitnami/wordpress] php.ini settings doesnt change in phpinfo();

### ISSUE THREAD

**Issue by srakl** [bitnami/vms#878]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2bd17cf8-781d-5ddd-1aee-d81660c63077

### bndiagnostic output

? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

nope, i have issues with php.ini

### Describe your issue as much as you can

followed [this.](
https://docs.bitnami.com/aws/apps/simple-machines-forum/get-started/understand-default-config-php/) 
i changed settings of memory_limit in php.ini. saved it, restarted. but in phpinfo() it still shows the old memory limit. why does changes in `/opt/bitnami/php/etc/php.ini` not reflect?

**Comment by srakl** [comment]
anyone?

**Comment by gongomgra** [comment]
Hi @srakl,

Thanks for using Bitnami. I launched a fresh new server and I double-checked our default value for the memory setting in the `php.ini` file is `512M`, while your website returns `128M` in the phpinfo output. As an additional check I launched a fresh new WordPress server, checked `512M` is both the value in the `php.ini` file and the value returned in the `phpinfo()` method. I updated the `php.ini` file and restarted all services (`sudo /opt/bitnami/ctlscript.sh restart`). Reloaded the phpinfo page (from a incognito tab, to avoid issues with the cache), and the updated value was there. Can you verify the steps on your side?

**Comment by srakl** [comment]
> sudo /opt/bitnami/ctlscript.sh restart

i did as asked, and opened site in incognito, still shows as 128M on my side.

**Comment by gongomgra** [comment]
Hi @srakl,

It is weird the change is not reflecting after restarting the services. Can you check the output from the next command?

```
php -i | grep -i memory_limit
```

**Comment by srakl** [comment]
ok that worked. there was an error in php.ini. thank you
