### ISSUE TITLE
[nginx] how to disable RSA key pair generating on start

### ISSUE THREAD

**Issue by tomaskodaj** [bitnami/vms#879]
please can you help how to disable key RSA pair generation on start of bitnami/nginx? it takes about 25 seconds and the server is not running ssl, so it is useless...

```
nginx 20:56:35.30 WARN ==> The NGINX configuration file '/opt/bitnami/nginx/conf/nginx.conf' is not writable by current user. Configurations based on environment variables will not be applied.

Generating RSA private key, 4096 bit long modulus (2 primes)
.....................++++
.....................................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = example.com
Getting Private key

nginx 20:57:00.90 INFO ==> No custom scripts in /docker-entrypoint-initdb.d
```

**Comment by jotamartos** [comment]
Hi @tomaskodaj,

The Bitnami solutions generate dummy SSL certs during the initialization to allow you use https for testing purposes. You can't disable that generation during the initialization and there is not any problem on having https enabled when you do not use it. However, if you want to disable https in the VM, you have different options:

- Close the port in the firewall https://docs.bitnami.com/virtual-machine/faq/administration/use-firewall/
- Remove the server block in NGINX that defines the connection to port 443 (/opt/bitnami/nginx/conf path)

**Comment by tomaskodaj** [comment]
solved by mapping empty file to /certs/server.crt ... the file existence is enough for the init script to skip generating ssl dummy ssl cert :)
