### ISSUE TITLE
[bncert-tool 1.0.0] <Running Manually Error: EMAIL not Registered> SOLVED

### ISSUE THREAD

**Issue by JSLittlefield** [bitnami/vms#88]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

I can share bndiagnostic via gdrive link privately 

### bndiagnostic output

No errors from bndiagnostic

### bndiagnostic was not useful. Could you please tell us why?

There's no unusual output form bndiagnostic. I've spent two days trying to resolve reading docs and community posts.

### Describe your issue as much as you can

Background: I'm using the bncert-tool to manage/reconfigure SSL for a Bitnami Wordpress Multisite installation. I have new sites I want to add to an existing SSL. Per instructions I'm running bncert-tool specifying all the sites in this implementation. I did accept the upgrade to lego 4.8.0

There are some subdomain sites that have SSL certificates I'm not wanting reestablished because they now have regular domain *new* names.

Error: Account "{MYEMAIL}" is not registered. Use 'run' to register a new account.

I'm using the same "{MYEMAIL}" email I'm currently receiving LetsEncrypt bot messages. 

I have the bndiagnostic output but it did not get uploaded to bitnami. I can share a gdrive link. I also have the log file for bncert-tool.

**Comment by JSLittlefield** [comment]
Where can I put the bndiagnostic and bncert-tool.log?

**Comment by mdhont** [comment]
Can you paste the code ID that is outputted at the end of the execution of the bndiagnostic tool?

**Comment by JSLittlefield** [comment]
No code was generated, I figured the code is associated with an automatic upload which did not occur.

This is the output from bndiagnostic tool:

The diagnostic bundle file was successfully created, but the automatic upload to Bitnami servers failed. You will need to upload it to your Bitnami Support ticket manually. Please locate the following file in your file browser or in your terminal: /tmp/bitnami-wordpressmultisite-info-20220708-114705-26259.zip Exercise caution when uploading the resulting diagnostic bundle to public sites as it contains detailed diagnostic information.root@willbuy-wpms-vm:/opt/bitnami#

**Comment by JSLittlefield** [comment]
**SOLVED**: Tried using other email addresses that I found in /opt/bitnami/letsencrypt/accounts/acme-v02.api.letsencrypt.org. 
The error was being raised because I was not renewing all my domains in Wordpress Multisite (un-renewed domains initiates a -revoke for the old domains). The error message:

**Account "{MYEMAIL}" is not registered. Use 'run' to register a new account.**

is triggered because the -revoke option requires the same email that was used to create the **active** certificate.

Note: If my understanding is incorrect on my explanation please correct. There are other community / support threads that do not seem to address the underlying cause of the error.
