### ISSUE TITLE
[bitnami/wordpress]  ssl and server error

### ISSUE THREAD

**Issue by hakxcore** [bitnami/vms#880]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

56bdac95-a951-7e7a-8017-3adafbcc26e0

### bndiagnostic output

WordPress-1- Terminal | Lightsail - Google Chrome
& lightsail.aws.amazon.com/ls/remote e Press-1/tel c

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

The Apache configuration has errors
```
AH00526: Syntax error on line 5 of
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf: SSLCertificateFile

file '/opt/bitnami/apache/conf/howtohack.tech.crt' does not exist or is empty
```
Please check the configuration

End of bndiagnostic tool output
Press [Enter] to continue

The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code
56bdac95-a951-7e7a-8017-3adafbcc26e0

And paste it in your Bitnami Suppbrt ticket
bitnami@ip-172-26-3-17:~$

### bndiagnostic was not useful. Could you please tell us why?

It has show the errors working well

### Describe your issue as much as you can

My _ssl_ certificates were expired and I was just updating them 4 or 5 months before then _bncert_ was not working and I accidentally deleted some _conf_ files as shown in error from diagnostics-tool and my website stopped working.
I have been finding solutions for months please help me with a possible solution. Thanks in advance.

**Comment by gongomgra** [comment]
Hi @hakxcore,

Thanks for using Bitnami. From time to time, it is normal to have some minor issues with the `lego` binary included in the machine as it gets old and it may not be compatible with the latest Let's Encrypt requirements. Can you try updating the `lego` tool and manually generate the Let's Encrypt certificate as described in the guide linked below?

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

Once you have created the new SSL certificate and the Apache configuration is working, the bncert tool should continue working as before (it should pass the Apache configuration check now).

Hope it helps!
