### ISSUE TITLE
I wanna use bitnami image stack for private cloud 

### ISSUE THREAD

**Issue by aliii021** [bitnami/vms#883]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

67fb50e7-f89d-561d-a4ae-593ccc0bb247

### bndiagnostic output

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Nginx: Found possible issues
    ✓ Php: No issues found
    ? Processes: Found possible issues
    ? Connectivity: Found possible issues

[Nginx]

Found recent error or warning messages in the Nginx error log.
```
2023/04/30 20:27:14 [error] 518#518: *8 open()
"/opt/bitnami/nginx/html/favicon.ico" failed (2: No such file or directory),
client: **ip_address**, server: , request: "GET /favicon.ico HTTP/1.1", host:
"5.34.196.137"
 2023/05/01 07:02:38 [alert] 516#516: unlink()
"/opt/bitnami/nginx/tmp/nginx.pid" failed (2: No such file or directory)
 2023/05/01 07:28:32 [error] 523#523: *2 open()
Press [Enter] to continue:
"/opt/bitnami/nginx/html/dispatch.asp" failed (2: No such file or directory),
client: **ip_address**, server: , request: "GET /dispatch.asp HTTP/1.1", host:
"5.34.196.137"

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

[Processes]

One or more component's processes are not running:
```
mariadb not running
```
You can try to restart the process with the following command:

    $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
Press [Enter] to continue:
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

i know what is the problem and write for you please help me to fix the problem or please advise me how can i download image or give the code of cloud base and guidance me to how to config that please 

### Describe your issue as much as you can

I want to use Bitname images as a personal image, but the updated images, for example, the nginx Stack 1-24 are written for ova and I can't use them for private cloud, and the images you used to upload were the same as aws images, please help me be able to download the same aws image because when I customize Image nginx, i had to change and customize the image beacuse it cannot get the data from the metadata because we use the open stack infrastructure and the comments written in libcloud.sh are for vmware and from Most importantly, when I customize the image of the item, it cannot regenerate the new password and set it for the services.
how can fix this problem ?

**Comment by gongomgra** [comment]
Hi @aliii021,

Thanks for using Bitnami and sorry for the delay on our response. We are in the process of updating our OVAs to use more standard utilities like `systemd` to manage the services, among other changes. Unfortunately, we don't support getting the metadata from OpenStack at this moment. 

Our recommendation here is to unpack the OVA, mount the VMDK and modify the files per your requirements, and then re-create the OVA.

**Comment by aliii021** [comment]
Can you give a link to download AWS stacks because our infrastructure is in the same format or could you help me how can i rerun cloud init beacuse when i customize the image cloud init can not reinstall the firstboot i want when the customize the image and create image from that and create instance with new image but the new password not regenerate and the password and ip in the mod in the welcome screen not change

**Comment by aliii021** [comment]
In Cloudstack images, the scripts are in the format. Can you give a link to download Cloudstack images?
bitnami@debian:/opt/bitnami$ cd scripts/init/
bitnami_agent                clean_metadata               hostname                     update_welcome_file
bitnami_agent_extra          enable_ufw                   recreate_ssh_host_keys       welcome_message
bitnami_credentials_file     functions                    resize_fs_partition          welcome_message_reload
change_boot_log_permissions  get_default_passwords        set_system_user_password
check_if_demo_machine        get_metadata                 swap_file
bitnami@debian:/opt/bitnami$ cd scripts/init/
bitnami@debian:/opt/bitnami/scripts/init$ ls
bitnami_agent                clean_metadata         hostname                  update_welcome_file
bitnami_agent_extra          enable_ufw             recreate_ssh_host_keys    welcome_message
bitnami_credentials_file     functions              resize_fs_partition       welcome_message_reload
change_boot_log_permissions  get_default_passwords  set_system_user_password
check_if_demo_machine        get_metadata           swap_file

**Comment by gongomgra** [comment]
Hi @aliii021,

Thanks for your message and sorry for the delay getting back to you. We currently only offer solutions for VMware and VirtualBox OVAs, and cloud images for the major cloud providers (AWS, GCE, Azure). Unfortunately, we don't provide native support for OpenStack. If you want to get the AWS disk image, you will need to launch an instance and then download the disk from the AWS console, as we only publish the images there. Please find below the official AWS docs 
on how to export and EC2 instance

https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport.html

Hope it helps!
