### ISSUE TITLE
[Redmine] Windows installer for previously released version

### ISSUE THREAD

**Issue by JLuisGallegos** [bitnami/vms#884]
### Describe your issue as much as you can

I understand that windows installers are no longer provided for new versions of Bitnami solutions, but is it possible to get one that has already been released? I'm looking into moving a server that I recently took over, but I can't find the bitnami installer that was used at the time. It is for Bitnami Redmine Stack Version 3.2.2-0

**Comment by jotamartos** [comment]
Hi @JLuisGallegos,

As you mentioned, we do not provide installers anymore. However, we kept the last installers we released but this one is from 7 years ago and is no longer available. 

Sorry for the inconvenience.
