### ISSUE TITLE
[Bitnami] Server didnt respond

### ISSUE THREAD

**Issue by Juulian74** [bitnami/vms#885]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9ed5a5e0-2584-c3bc-ece2-8f8341a1c778

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Processes: Found possible issues
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ? Wordpress: Found possible issues
 

 
[Processes]

One or more component's processes are not running:
```
apache not running mariadb not running
```
You can try to restart the process with the following command:
Press [Enter] to continue:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue May 02 04:09:25.472977 2023] [proxy_fcgi:error] [pid 8274:tid 
140087371216640] [client **ip_address**:53842] AH01071: Got error 'PHP message: 
PHP Notice:  Unknown: file created in the system's temporary directory in 
Unknown on line 0', referer: 
https://tgmc.events/wp-admin/themes.php?page=starter-templates&ci=3&s=Agency

[Tue May 02 04:22:48.512863 2023] [proxy_fcgi:error] [pid 8766:tid 
140087966803712] [client **ip_address**:54037] AH01071: Got error 'PHP message: 
PHP Notice:  Unknown: file created in the system's temporary directory in 
Press [Enter] to continue:
Unknown on line 0', referer: 
https://tgmc.events/wp-admin/post.php?post=205&action=elementor

[Tue May 02 05:38:24.465180 2023] [core:error] [pid 8766:tid 140087782164224] 
[client **ip_address**:55678] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
Press [Enter] to continue:
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/

System Apache is running:
```
root         443  0.0  0.2   6576  4484 ?        Ss   10:06   0:00 
/usr/sbin/apache2 -k start
www-data     447  0.0  0.4 752732  7192 ?        Sl   10:06   0:00 
/usr/sbin/apache2 -k start
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Tue May 02 02:39:23.205975 2023] [proxy_fcgi:error] [pid 8275:tid 
140087966803712] [client **ip_address**:50448] AH01071: Got error 'PHP message: 
PHP Notice:  Unknown: file created in the system's temporary directory in 
Unknown on line 0', referer: https://tgmc.events/wp-admin/plugin-install.php

Press [Enter] to continue:
```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I have tried different things but haven't been able to fix it.

### Describe your issue as much as you can

I have tried various solutions but have been unable to fix the issue. I restarted Apache, but it still shows as inactive. I also made ports 80 and 443 public using commands, but that didn't work either. The website used to work fine before, but when I checked it today, it was no longer accessible. Whenever I try to access my server using HTTPS, it shows a connection rejection error. On the other hand, when I use HTTP, it displays the Apache2 default installation page. Can you please suggest what could be causing this issue and how I can fix it?

**Comment by mdhont** [comment]
There's a high number of incoming requests originating from one or more unique IP addresses. This could indicate a bot attack. The following guide shows how to check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-bots-apache/

**Comment by Juulian74** [comment]
Finally I created another vm instance for another project, but I get the same error, this time the dignostic tool, it does not show a bot attack error. It shows a problem with a plugin, which I have deactivated and then deleted, but it gives the same error. I have also created a firewall rule to allow the ports of the server not accessible, to show publicly accessible. do you have an idea to solve it?

here is the new report with the diganostic tool:

Id: dd0a7347-b772-e392-8f46-b4fd52f62e89

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Processes: Found possible issues
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ? Wordpress: Found possible issues
 

 
[Processes]

One or more component's processes are not running:
```
apache not running
```
You can try to restart the process with the following command:
Press [Enter] to continue:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed May 03 19:17:38.977820 2023] [proxy_fcgi:error] [pid 81835:tid 
139954982147840] (70007)The timeout specified has expired: [client 
**ip_address**:54801] AH01075: Error dispatching request to : (polling), 
referer: 
https://www.rzrmazatlan.com/wp-admin/tools.php?page=better-search-replace

[Wed May 03 19:22:59.570396 2023] [proxy_fcgi:error] [pid 82237:tid 
139954772461312] (70007)The timeout specified has expired: [client 
**ip_address**:54804] AH01075: Error dispatching request to : (polling), 
Press [Enter] to continue:
referer: 
https://www.rzrmazatlan.com/wp-admin/tools.php?page=better-search-replace

[Wed May 03 19:25:06.578299 2023] [proxy_fcgi:error] [pid 82237:tid 
139954747283200] (70007)The timeout specified has expired: [client 
**ip_address**:54877] AH01075: Error dispatching request to : (polling)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.

System Apache is running:
```
root         430  0.0  0.2   6568  4424 ?        Ss   01:14   0:01 
Press [Enter] to continue:
/usr/sbin/apache2 -k start
www-data     433  0.0  0.4 752684  7060 ?        Sl   01:14   0:00 
/usr/sbin/apache2 -k start
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the 
following command to stop it:

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Wed May 03 19:17:17.980275 2023] [proxy_fcgi:error] [pid 82237:tid 
139954822817536] (70007)The timeout specified has expired: [client 
**ip_address**:54804] AH01075: Error dispatching request to : (polling), 
referer: 
https://www.rzrmazatlan.com/wp-admin/plugins.php?plugin_status=all&paged=1&s

```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
 

Press [Enter] to continue:
===== End of bndiagnostic tool output =====

**Comment by mdhont** [comment]
Can you confirm that the issue only happens after you install the plugin on a fresh instance? In that case I would contact the plugin vendor for support.

**Comment by Juulian74** [comment]
Hi, thanks for replying, I was able to solve it, I just had to kill the apache process and then start it again. I just had to kill the apache process and then start it again, it didn't stop.

**Comment by Yasin-Ali-Cpuflat** [comment]
> Hi, thanks for replying, I was able to solve it, I just had to kill the apache process and then start it again. I just had to kill the apache process and then start it again, for some reason it didn't stop.

how did you do it
