### ISSUE TITLE
[moodle] HTTP ERROR 500 while trying to update moodle database

### ISSUE THREAD

**Issue by lizen827** [bitnami/vms#886]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3ffb48cd-c3de-fd5e-5c4a-9184125e5f5d

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
 
[Resources]

Your disk is almost full: You could try to increase your instance's storage.
```
Filesystem Size Used Avail Use% Mounted on /dev/sda1 9.7G 7.5G 1.7G 82% /
```
Please check your cloud provider's documentation for more information.

[Apache]

Press [Enter] to continue:
Found recent error or warning messages in the Apache error log.
```
[Mon May 01 09:12:33.097565 2023] [authz_core:error] [pid 744:tid 
140069335717632] [client **ip_address**:4664] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/, referer: http://35.234.36.218/
 [Tue May 02 06:02:29.155065 2023] [authz_core:error] [pid 744:tid 
140069117507328] [client **ip_address**:57704] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/scripts
 [Tue May 02 09:50:05.454932 2023] [authz_core:error] [pid 744:tid 
140068849170176] [client **ip_address**:43842] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/scripts

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

client denied by server...not sure what is the cause

### Describe your issue as much as you can

While login as admin, asked to perform the update, but when trying to update moodle database, got HTTP ERROR 500

There is nothing can do when stopped at this step, Restart all servers will not change anything.

Thanks for your help.

**Comment by jotamartos** [comment]
That error is probably related to an issue with the permissions configuration. Let's try to reconfigure the permissions 

```
sudo find /opt/bitnami/moodle /bitnami/moodle -type d -exec chmod 0775 {} \;
sudo find /opt/bitnami/moodle /bitnami/moodle -type f -exec chmod 0664 {} \;
sudo chown bitnami:daemon -R /opt/bitnami/moodle /bitnami/moodle
```

Does the process work properly now?

**Comment by lizen827** [comment]
Still the same problem...HTTP ERROR 500

Found a similar issue [here...](https://moodle.org/mod/forum/discuss.php?d=172540)

"client denied by server configuration" in Apache said that "disabled mod_evasive" will help.

If it will help, can you tell me how to disable?

Thanks

**Comment by jotamartos** [comment]
To enable/disable modules in Apache, you need to edit the `/opt/bitnami/apache/conf/httpd.conf` file. Once you do that, restart the service for the changes to take effect 

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

**Comment by lizen827** [comment]
Hi @jotamartos 

Can not find the string "mod_evasive" in the `/opt/bitnami/apache/conf/httpd.conf` file.
Does it mean "mod_evasive" is never enabled, so it is no point to disable, right?

Can you tell me what might cause HTTP ERROR 500/client denied by server other than permissions configuration?

Thanks

**Comment by jotamartos** [comment]
mod_evasive is not included in the solution so that's not the problem. 

>Can you tell me what might cause HTTP ERROR 500/client denied by server other than permissions configuration?

There are many reasons why you can receive a 5xx code 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

In this case, I think something is not working on the app-side and that's why Apache returns that code. You can contact the Moodle's developers or post a question in its forum to get more information about how to troubleshoot this issue in the application.
