### ISSUE TITLE
[<wordpress>] <corrupted woocommerce plugin>

### ISSUE THREAD

**Issue by mdrplg** [bitnami/vms#888]
### Describe your issue as much as you can

diagnostic bundle code: 4a869be2-b2f7-2f45-059c-7bb060166614
Using woocommerce plugin, using printful plugin
Adding product to printful.
plugin (printful) attempts to add product to woocommerce store.
process fails returning error code 500, server error
Question: does the diagnostic help determine the server error?
Question: Have any ideas on how to fix?

**Comment by mdhont** [comment]
It seems like a permissions issue. Could you try resetting wp-content folder to the default permissions?

https://docs.bitnami.com/aws/apps/wordpress/administration/understand-file-permissions

**Comment by mdrplg** [comment]
By default permissions do you mean root:root? Or user:usersgroup?

**Comment by mdhont** [comment]
No, the user should be **bitnami** and the group **daemon**:

    sudo chown -R bitnami:daemon /opt/bitnami/wordpress/
    sudo find /opt/bitnami/wordpress/ -type d -exec chmod 775 {} \;
    sudo find /opt/bitnami/wordpress/ -type f -exec chmod 664 {} \;
    sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
