### ISSUE TITLE
[Wordpress] Common Access Card (CAC) how-to setup

### ISSUE THREAD

**Issue by bits45** [bitnami/vms#889]
### Describe your issue as much as you can

I am looking for instructions to properly setup Common Access Card (CAC) Authentication with Bitnami's Provided Wordpress 6.2 running with nginx.  There seems to be very little out there in regards to instructions with this combination of software.

This would likely fill the need for a good many folks out there and provide another level of security.

Thank you for your time and understanding.

**Comment by gongomgra** [comment]
Hi @bits45,

Thanks for your interest in using Bitnami. Can you provide us with more information on what you are trying to achieve? In general, you can update the NGINX config updating the needed files under the `/opt/bitnami/nginx/conf` folder, and WordPress from `/opt/bitnami/wordpress`. Which changes are you having issues to implement?
