### ISSUE TITLE
[Magento] Goes down frequently after any update in magento admin

### ISSUE THREAD

**Issue by lchkg** [bitnami/vms#89]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

0a94b268-87ce-c208-57a1-fa55c34ff749

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

 
[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Jul 08 06:48:28.726463 2022] [proxy_fcgi:error] [pid 15641:tid 
140542688007936] (104)Connection reset by peer: [client **ip_address**:42712] 
AH01075: Error dispatching request to :81: 
 [Fri Jul 08 06:48:33.749240 2022] [proxy:error] [pid 15641:tid 140542587295488] 
(2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain 
socket /opt/bitnami/php/var/run/www.sock (www-fpm) failed
Press [Enter] to continue:
 [Fri Jul 08 06:48:33.749290 2022] [proxy_fcgi:error] [pid 15641:tid 
140542587295488] [client **ip_address**:34542] AH01079: failed to make 
connection to backend: httpd-UDS

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3946 2055 758 10 1133 1602 
Swap: 634 0 634
Press [Enter] to continue:
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
 

===== End of bndiagnostic tool output =====

                                    
Press [Enter] to continue:
The files listed below are bigger than 10MB and have not been included, please notify the 
support agent.

/opt/bitnami/magento/var/log/cron.log
/opt/bitnami/magento/var/log/debug.log
/opt/bitnami/magento/var/log/system.log

The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the fo
llowing code:

0a94b268-87ce-c208-57a1-fa55c34ff749

And paste it in your Bitnami Support ticket.
bitnami@ip-172-26-5-170:~$ 

### bndiagnostic was not useful. Could you please tell us why?

We could not get enough information to make a relevant decision

### Describe your issue as much as you can

Whenever we clear the cache in magento backend the server goes down. 
Also mariadb and elastic search frequently go down even if there are no usage of the site. We get 503 error.

Restarting mariadb or elastic search or even all the services does not help. We stop/start the instance (AWS LightSale : 4GB, 2vCPU)

Thanks in advance for your recommendations.

**Comment by jotamartos** [comment]
Please take a look at this other issue to get more information about the issues you are running into 

https://github.com/bitnami/vms/issues/27
