### ISSUE TITLE
[bitnami/wordpress] htaccess file isn't being picked up from wordpress-htaccess.conf

### ISSUE THREAD

**Issue by xgaibtcgd** [bitnami/vms#890]
### Name and Version

bitnami/wordpress

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Edited  /opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf
2. Restarted apache
3. Visited the 301 redirect which works on other servers - didn't work in bitnami

### Are you using any custom parameters or values?

no

### What is the expected behavior?

A 301 redirect to happen

### What do you see instead?

A 404 page

### Additional information

I've been through the .htaccess documents on the bitnami site.  Still I can't get this to work.  Its probably more of something i'm doing wrong - but can't figure out what and found this support channel through the recommended bitnami support site.

This is the contents I've added:

`<Directory "/opt/bitnami/wordpress/">
   Options FollowSymLinks
   AllowOverride All
   <IfVersion < 2.3 >
      Order allow,deny                          
      Allow from all                              
   </IfVersion>
   <IfVersion >= 2.3>
      Require all granted                        
   </IfVersion>
   RewriteEngine On
   RewriteRule ^/site-v1/(.*)$ https://www.domain.com/site-v2/$1 [R=301,L]
</Directory>`

**Comment by mdhont** [comment]
The following guide explains how you can configure the htaccess rules for a Bitnami vm:

https://docs.bitnami.com/aws/infrastructure/lamp/administration/use-htaccess/

**Comment by mdhont** [comment]
From the title of the issue "htaccess file isn't being picked up from wordpress-htaccess.conf" I understand that you are using an .htaccess file, is that correct? Or do you mean you are adding the htaccess rules to the htaccess.conf file?

**Comment by xgaibtcgd** [comment]
I've tried both.....  

Doing it the way of adding the 301 directly into the htaccess.conf file:
'm adding the rules into the htaccess.conf file ...  the documentation said: "The /opt/bitnami/apache/conf/vhosts/APPNAME-vhost.conf file is the main application configuration file. It also sources the APPNAME-htaccess.conf file."  

In that directory i have two files:
wordpress-https-vhost.conf
wordpress-vhost.conf

I've edited both and inside the DocumentRoot i've added the 301 redirect to the example.com domain
https://drive.google.com/uc?id=1QRvUOKaASjh_FhWYAzGyM66jOdnj5EvF

When that didn't work I restarted Apache regardless, tried again, still isn't working.... 



Doing it the way of adding the 301 redirect into the .htaccess file i went into:
/opt/bitnami/apache/conf/vhosts/htaccess/ and edited the only file there called wordpress-htaccess.conf
and added:
<Directory "/opt/bitnami/wordpress/">
RewriteEngine On
Redirect 301 /order-promos/ https://www.example.com/order-promo/
</Directory>

and restarted apache... 

nothing... not sure if i'm missing something when reading these docs?

**Comment by mdhont** [comment]
Could you paste the complete <Directory> directive here?

**Comment by xgaibtcgd** [comment]
Sure:

<Directory "/opt/bitnami/wordpress/">
RewriteEngine On
Redirect 301 /order-promos/ https://www.example.com/order-promo/
</Directory>

And posted it in this file:
/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf

Then executed:  sudo /opt/bitnami/ctlscript.sh restart apache

I expected this change to take place right away after the apache restart... when it didn't, I reverted it back.

**Comment by mdhont** [comment]
Can you try adding the rule to the  existing rewrite rules inside the <Directory> directive of the  `/opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf` file?

**Comment by xgaibtcgd** [comment]
Didn't have the time available to troubleshoot this so just using CloudFlare to do the 301s which is doing just fine
