### ISSUE TITLE
[<wampstack>] <How to get the last version wampstack installer by Bitnami for Windows 64?>

### ISSUE THREAD

**Issue by educrue** [bitnami/vms#891]
### Describe your issue as much as you can

How to get the last version wampstack installer by Bitnami for Windows 64?. May someone help me!?. Thanks in advance.

**Comment by gongomgra** [comment]
Hi @educrue,

Thanks for using Bitnami. Find below the download link to the most recent Bitnami WAMP Stack installer for Windows we published:

https://downloads.bitnami.com/files/stacks/wampstack/8.1.9-0/bitnami-wampstack-8.1.9-0-windows-x64-installer.exe

Notice this is an old installer including old versions of the included components and that we dropped support for local installers in favor of our virtual machines solutions as you can read in the next blog post

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

**Comment by educrue** [comment]
Thak you so much @gongomgra !!!😃✌

**Comment by gongomgra** [comment]
Hi @educrue,

Glad to be of help! I'm closing this ticket as solved.
