### ISSUE TITLE
<GCP Bitnami Instance> Not able to run the bitnami services after restart

### ISSUE THREAD

**Issue by mattcmlee** [bitnami/vms#893]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8c2798e5-3569-164a-aeab-6a1a91437bec

### bndiagnostic output

 
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Resources: No issues found
    ✓ Php: No issues found
    ✓ Wordpress: No issues found
    ? Nginx: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

I've fixed some of the issues showed by the tool, but there're still something not working properly. 

### Describe your issue as much as you can

I restarted my instance earlier today, however, I am not able to start the bitnami service due to the following errors:

`sudo /opt/bitnami/ctlscript.sh start`
> Starting services..
> Job for bitnami.service failed because the control process exited with error code.
> See "systemctl status bitnami.service" and "journalctl -xe" for details.

`systemctl status bitnami.service`
> ● bitnami.service - LSB: bitnami init script
>      Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Fri 2023-05-05 16:32:04 UTC; 15min ago
>     Process: 3050 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
>         CPU: 823ms
> 
> May 05 16:32:04 wordpresspro-1-vm bitnami[3115]: nginx: [emerg] still could not bind()
> May 05 16:32:04 wordpresspro-1-vm bitnami[3115]: 2023-05-05T16:32:04.505Z - error: Unable to perform start operation Export start for nginx failed with exit code 1
> May 05 16:32:04 wordpresspro-1-vm bitnami[3130]: ## 2023-05-05 16:32:04+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_bitnami_agent_extra...
> May 05 16:32:04 wordpresspro-1-vm bitnami[3130]: ## 2023-05-05 16:32:04+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agent...
> May 05 16:32:04 wordpresspro-1-vm bitnami[3130]: ## 2023-05-05 16:32:04+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_update_welcome_file...
> May 05 16:32:04 wordpresspro-1-vm bitnami[3130]: ## 2023-05-05 16:32:04+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_bitnami_credentials_file...
> May 05 16:32:04 wordpresspro-1-vm bitnami[3130]: ## 2023-05-05 16:32:04+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_clean_metadata...
> May 05 16:32:04 wordpresspro-1-vm systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE
> May 05 16:32:04 wordpresspro-1-vm systemd[1]: bitnami.service: Failed with result 'exit-code'.
> May 05 16:32:04 wordpresspro-1-vm systemd[1]: Failed to start LSB: bitnami init script.

`journalctl -xe`

> May 05 16:49:09 wordpresspro-1-vm sshd[4420]: Invalid user idsconx from 218.104.237.213 port 42660
> May 05 16:49:09 wordpresspro-1-vm sshd[4420]: Received disconnect from 218.104.237.213 port 42660:11: Bye Bye [preauth]
> May 05 16:49:09 wordpresspro-1-vm sshd[4420]: Disconnected from invalid user idsconx 218.104.237.213 port 42660 [preauth]
> May 05 16:49:15 wordpresspro-1-vm sshd[4422]: Received disconnect from 112.104.52.145 port 33664:11: Bye Bye [preauth]
> May 05 16:49:15 wordpresspro-1-vm sshd[4422]: Disconnected from authenticating user root 112.104.52.145 port 33664 [preauth]
> May 05 16:49:36 wordpresspro-1-vm sshd[5035]: Received disconnect from 68.183.232.27 port 54098:11: Bye Bye [preauth]
> May 05 16:49:36 wordpresspro-1-vm systemd[1]: Starting GCE Workload Certificate refresh...
> ░░ Subject: A start job for unit gce-workload-cert-refresh.service has begun execution
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░ 
> ░░ A start job for unit gce-workload-cert-refresh.service has begun execution.
> ░░ 
> ░░ The job identifier is 1222.
> May 05 16:49:36 wordpresspro-1-vm sshd[5035]: Disconnected from authenticating user root 68.183.232.27 port 54098 [preauth]
> May 05 16:49:36 wordpresspro-1-vm gce_workload_cert_refresh[5037]: 2023/05/05 16:49:36: Error getting config status, workload certificates may not be configured: HTTP 4>
> May 05 16:49:36 wordpresspro-1-vm gce_workload_cert_refresh[5037]: 2023/05/05 16:49:36: Done
> May 05 16:49:36 wordpresspro-1-vm systemd[1]: gce-workload-cert-refresh.service: Succeeded.
> ░░ Subject: Unit succeeded
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░ 
> ░░ The unit gce-workload-cert-refresh.service has successfully entered the 'dead' state.
> May 05 16:49:36 wordpresspro-1-vm systemd[1]: Finished GCE Workload Certificate refresh.
> ░░ Subject: A start job for unit gce-workload-cert-refresh.service has finished successfully
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░ 
> ░░ A start job for unit gce-workload-cert-refresh.service has finished successfully.
> ░░ 
> ░░ The job identifier is 1222.
> May 05 16:49:36 wordpresspro-1-vm sshd[5041]: Received disconnect from 8.222.247.127 port 39726:11: Bye Bye [preauth]
> May 05 16:49:36 wordpresspro-1-vm sshd[5041]: Disconnected from authenticating user root 8.222.247.127 port 39726 [preauth]
> May 05 16:50:10 wordpresspro-1-vm sshd[5043]: Received disconnect from 218.104.237.213 port 60834:11: Bye Bye [preauth]
> May 05 16:50:10 wordpresspro-1-vm sshd[5043]: Disconnected from authenticating user root 218.104.237.213 port 60834 [preauth]
> May 05 16:50:11 wordpresspro-1-vm sshd[5045]: Invalid user sudev from 43.154.95.120 port 43348
> May 05 16:50:11 wordpresspro-1-vm sshd[5045]: Received disconnect from 43.154.95.120 port 43348:11: Bye Bye [preauth]
> May 05 16:50:11 wordpresspro-1-vm sshd[5045]: Disconnected from invalid user sudev 43.154.95.120 port 43348 [preauth]
> lines 2209-2246/2246 (END)

So I tried bndiagnostic and it shows me these:
> 2023/05/05 16:32:01 [emerg] 3128#3128: bind() to **ip_address**:80 failed (98: 
> Address already in use)
> 
> 2023/05/05 16:32:01 [emerg] 3128#3128: bind() to **ip_address**:80 failed (98: 
> Address already in use)
> 
> 2023/05/05 16:32:01 [emerg] 3128#3128: still could not bind()

I've been trying to fix them but still not entirely sure about what the solution is. Everything was fine before the instance restarted, really don't understand why this is happening. Could someone please help? Thank you!

**Comment by mattcmlee** [comment]
Issues solved. Thank you.

**Comment by jotamartos** [comment]
I'm glad to hear that you managed to solve the issue. I understand you had another webserver running and that prevented the Bitnami one to start, right? It'd be great if you can provide more information to help other users resolve the issue.

Thanks

**Comment by mattcmlee** [comment]
Yeah, it seems like the server was running something else at the same time but I am not entirely sure about the cause.  

So here're some backgrounds:
- The problem happened right after I restarted the GCP instance. All of a sudden, 80 and 443 was occupied. Therefore, I could not get my wordpress site running. 

How I fixed it:
- After some research, I copied the 'HTTP server' code from my other wordpress site, and it works. 

```
#HTTP Server 
server {
        # Port to listen on, can also be set in IP:PORT format
        listen  80;

        include  "/opt/bitnami/nginx/conf/bitnami/*.conf";

        location /status {
            stub_status on;
            access_log   off;
            allow 127.0.0.1;
            deny all;
        }
    }
}
```

I don't know stop and restart the instance could cause this kind of error. But lucky me, not too much damage.

**Comment by mattcmlee** [comment]
However, I just encountered another error again after I restarted the instance...Before the restart, everything was ok. 

This time it says:

> [Connectivity]
> 
> Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
> following guide to open server ports for remote access:
> 
> https://docs.bitnami.com/general/faq/administration/use-firewall/
> 
> [Nginx]
> 
> Press [Enter] to continue:
> Found recent error or warning messages in the Nginx error log.
> ```
> 2023/06/18 11:27:00 [emerg] 4827#4827: "location" directive is not allowed here 
> in /opt/bitnami/nginx/conf/bitnami/bncert.conf:1
> 
> 2023/06/18 11:27:31 [emerg] 4833#4833: "location" directive is not allowed here 
> in /opt/bitnami/nginx/conf/bitnami/bncert.conf:1
> 
> 2023/06/18 13:32:47 [emerg] 13426#13426: "location" directive is not allowed 
> here in /opt/bitnami/nginx/conf/bitnami/bncert.conf:1

I checked the firewall, I guess it looks okay. About the 'nginx location not available' issue, I have no idea...
Could you please give a hand? So confused...(Or should I open another ticket? )

Thank you!

**Comment by jotamartos** [comment]
>After some research, I copied the 'HTTP server' code from my other wordpress site, and it works.

> ```
> #HTTP Server 
> server {
>         # Port to listen on, can also be set in IP:PORT format
>         listen  80;
> 
>         include  "/opt/bitnami/nginx/conf/bitnami/*.conf";
> 
>         location /status {
>             stub_status on;
>             access_log   off;
>             allow 127.0.0.1;
>             deny all;
>         }
>     }
> }
> ```

This configuration comes from an old instance and that's why you are running into issues right now. Please update the include line to this one 

```
include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";
```

and restart NGINX for the changes to take effect. 

Thanks!
