### ISSUE TITLE
[WordPress with NGINX and SSL] Job for bitnami.service failed

### ISSUE THREAD

**Issue by BrownBear127** [bitnami/vms#894]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1d1d32f6-65d1-1a23-3ffb-eb897bb06d61

### bndiagnostic output

===== Begin of bndiagnostic tool output =====
 
    ? Wordpress: Found possible issues
    ? Connectivity: Found possible issues
    ? Nginx: Found possible issues
    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ✓ Php: No issues found
    ✓ Resources: No issues found
 
 
[Wordpress]
Found recent WordPress plugin related error messages in the Nginx error log.
```
2023/05/07 06:39:59 [error] 19548#19548: *48829 FastCGI sent in stderr: "PHP 
message: PHP Notice: Unknown: file created in the system's temporary directory 
in Unknown on line 0" while reading response header from upstream, client: 
**ip_address**, server: _, request: "POST 
/wp-content/plugins/translatepress-multilingual/includes/trp-ajax.php HTTP/1.1", 
Press [Enter] to continue:
upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: 
"www.trouver.art", referrer: "https://www.trouver.art/en/product/gmund-bavaria
```
Please check the following guide to deactivate plugins:
 
https://developer.wordpress.org/cli/commands/plugin/deactivate/
[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:
https://docs.bitnami.com/general/faq/administration/use-firewall/

[Nginx]
Found recent error or warning messages in the Nginx error log.
```
2023/05/07 07:19:05 [emerg] 1655#1655: cannot load certificate 
"/opt/bitnami/nginx/conf/bitnami/certs/server.crt": BIO_new_file() failed (SSL: 
error:02001002:system library:fopen:No such file or 
directory:fopen('/opt/bitnami/nginx/conf/bitnami/certs/server.crt','r') 
error:2006D080:BIO routines:BIO_new_file:no such file)
Press [Enter] to continue:
 2023/05/07 07:29:19 [emerg] 731#731: cannot load certificate 
"/opt/bitnami/nginx/conf/bitnami/certs/server.crt": BIO_new_file() failed (SSL: 
error:02001002:system library:fopen:No such file or 
directory:fopen('/opt/bitnami/nginx/conf/bitnami/certs/server.crt','r') 
error:2006D080:BIO routines:BIO_new_file:no such file)
 2023/05/07 07:30:34 [emerg] 885#885: cannot load certificate 
"/opt/bitnami/nginx/conf/bitnami/certs/server.crt": BIO_new_file() failed (SSL: 
error:02001002:system library:fopen:No such file or 
directory:fopen('/opt/bitnami/nginx/conf/bitnami/certs/server.crt','r') 
error:2006D080:BIO routines:BIO_new_file:no such file)
```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/installer/infrastructure/nginx/troubleshooting/

The Nginx configuration has errors:
```
nginx: [emerg] cannot load certificate 
"/opt/bitnami/nginx/conf/bitnami/certs/server.crt": BIO_new_file() failed (SSL: 
error:02001002:system library:fopen:No such file or 
directory:fopen('/opt/bitnami/nginx/conf/bitnami/certs/server.crt','r') 
Press [Enter] to continue:
error:2006D080:BIO routines:BIO_new_file:no such file) nginx: configuration file 
/opt/bitnami/nginx/conf/nginx.conf test failed
```
Please check the configuration.
 
===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

it can not fix this question

### Describe your issue as much as you can

I'm in the process of renewing my SSL certificate
Finally I use : sudo service bitnami start

system show info:
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

pls help me fix that, thank you

**Comment by BrownBear127** [comment]
sudo systemctl status bitnami.service
● bitnami.service - LSB: bitnami init script
   Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2023-05-07 13:26:18 UTC; 4min 26s ago
  Process: 26550 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
    Tasks: 41 (limit: 4415)
   Memory: 336.2M
   CGroup: /system.slice/bitnami.service
           ├─597 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
           ├─601 php-fpm: pool www
           ├─602 php-fpm: pool www
           ├─603 php-fpm: pool www
           ├─604 php-fpm: pool www
           ├─605 php-fpm: pool www
           ├─606 php-fpm: pool www
           ├─607 php-fpm: pool www
           ├─608 php-fpm: pool www
           ├─609 php-fpm: pool www
           ├─610 php-fpm: pool www
           ├─611 php-fpm: pool www
           ├─612 php-fpm: pool www
           ├─613 php-fpm: pool www
           ├─614 php-fpm: pool www
           ├─615 php-fpm: pool www
           ├─616 php-fpm: pool www
           ├─617 php-fpm: pool www
           ├─618 php-fpm: pool www
           ├─619 php-fpm: pool www
           ├─620 php-fpm: pool www
           ├─621 php-fpm: pool www
           ├─622 php-fpm: pool www
           ├─623 php-fpm: pool www
           ├─624 php-fpm: pool www
           ├─625 php-fpm: pool www
           ├─626 php-fpm: pool www
           ├─627 php-fpm: pool www
           ├─628 php-fpm: pool www
           ├─629 php-fpm: pool www
           ├─630 php-fpm: pool www
           ├─631 php-fpm: pool www
           ├─632 php-fpm: pool www
           ├─633 php-fpm: pool www
           ├─634 php-fpm: pool www
           ├─635 php-fpm: pool www
           ├─636 php-fpm: pool www
           ├─637 php-fpm: pool www
           ├─638 php-fpm: pool www
           ├─639 php-fpm: pool www
           └─640 php-fpm: pool www
May 07 13:26:18 bitnami-wordpresspro-0b7e bitnami[26550]: nginx: [emerg] cannot load certificate "/opt
May 07 13:26:18 bitnami-wordpresspro-0b7e bitnami[26550]: 2023-05-07T13:26:18.384Z - error: Unable to 
May 07 13:26:18 bitnami-wordpresspro-0b7e bitnami[26550]: ## 2023-05-07 13:26:18+00:00 ## INFO ## Runn
May 07 13:26:18 bitnami-wordpresspro-0b7e bitnami[26550]: ## 2023-05-07 13:26:18+00:00 ## INFO ## Runn
May 07 13:26:18 bitnami-wordpresspro-0b7e bitnami[26550]: ## 2023-05-07 13:26:18+00:00 ## INFO ## Runn
May 07 13:26:18 bitnami-wordpresspro-0b7e bitnami[26550]: ## 2023-05-07 13:26:18+00:00 ## INFO ## Runn
May 07 13:26:18 bitnami-wordpresspro-0b7e bitnami[26550]: ## 2023-05-07 13:26:18+00:00 ## INFO ## Runn
May 07 13:26:18 bitnami-wordpresspro-0b7e systemd[1]: bitnami.service: Control process exited, code=ex
May 07 13:26:18 bitnami-wordpresspro-0b7e systemd[1]: bitnami.service: Failed with result 'exit-code'.
May 07 13:26:18 bitnami-wordpresspro-0b7e systemd[1]: Failed to start LSB: bitnami init script.

**Comment by jotamartos** [comment]
Hi @BrownBear127,

the error is clear 

```
 2023/05/07 07:30:34 [emerg] 885#885: cannot load certificate 
"/opt/bitnami/nginx/conf/bitnami/certs/server.crt": BIO_new_file() failed (SSL: 
error:02001002:system library:fopen:No such file or 
directory:fopen('/opt/bitnami/nginx/conf/bitnami/certs/server.crt','r') 
error:2006D080:BIO routines:BIO_new_file:no such file)
```

If you take a look at the certs folder, you can see this 

```
nginx/conf/bitnami/certs:
total 8
drwxrwxr-x 2 bitnami root 4096 May  7 06:52 .
drwxrwxr-x 3 bitnami root 4096 Dec  1  2021 ..
lrwxrwxrwx 1 root    root   53 Dec  3  2021 server.crt.old -> /opt/bitnami/letsencrypt/certificates/trouver.art.crt
lrwxrwxrwx 1 root    root   53 Dec  3  2021 server.key.old -> /opt/bitnami/letsencrypt/certificates/trouver.art.key
```

Please rename these files again or generate new SSL certs if needed

```
sudo mv /opt/bitnami/nginx/conf/bitnami/certs/server.crt.old /opt/bitnami/nginx/conf/bitnami/certs/server.crt
sudo mv /opt/bitnami/nginx/conf/bitnami/certs/server.key.old /opt/bitnami/nginx/conf/bitnami/certs/server.key
sudo /opt/bitnami/ctlscript.sh restart nginx
```

**Comment by BrownBear127** [comment]
@jotamartos it's work!! thank you very much!!
