### ISSUE TITLE
[AWS/Bitnami/WordPress] .htaccess file problems with most of plugins

### ISSUE THREAD

**Issue by mukatrpetra** [bitnami/vms#895]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5eb23dd5-bc4b-7329-9c12-f4561154ec9d

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ✓ Apache: No issues found
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 7956 7125 119 184 711 369 
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]
Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides are not related to my issues

### Describe your issue as much as you can

I have a problem with the .htaccess file:
All the plugin has the same issue because no plugin can detect the .htaccess file, especially the cache and SSL plugins and those are mandatory requirements for any website
I tried a lot to override the .htaccess file, but it was not fixed, and the plugins still cannot read the file as it is deactivated.
Kindly let me know how to fix this file problem, I'm using WP Rocket plugin and Really Simple SSL

**Comment by gongomgra** [comment]
Hi @mukatrpetra,

Thanks for using Bitnami. `.htaccess` files are disabled by default for security reasons. You can get more information about this in our docs linked below

https://docs.bitnami.com/aws/apps/wordpress/administration/use-htaccess/

If you still need to enabled `.htaccess` files, update the `AllowOverride` option in Apache's config and restart the service for changes to take effect

```
sudo /opt/bitnami/ctlscript.sh restart apache
```

Hope it helps!

**Comment by gongomgra** [comment]
Hi @mukatrpetra,

Thanks for your message. The files are listed in the docs I shared, did you have any chance to check it? In case you are having any issues following our guides, can you tell us in which part of the guide you are having problem with so we can improve it?
