### ISSUE TITLE
[Bitnami Guacamole] <Unable to connect to SSH>

### ISSUE THREAD

**Issue by frhodes-aam** [bitnami/vms#898]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8211039f-939f-d1b6-c1b3-49d1f26f747a

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
    ✓ Apache: No issues found

### bndiagnostic was not useful. Could you please tell us why?

It seems not to detect issues pertaining to my problem, ports are open and I can reach application from the internet

### Describe your issue as much as you can

I launched a new guacamole instance using the bitnami AMI, I am unable to connect to any ssh client from this guacamole instance. I get the error messages below when checking syslog. I am unsure what to do, can you pls help?

Creating new client for protocol "ssh"
May  9 00:46:22 ip-10-0-20-26 guacd[2017]: Connection ID is "$5c926d1e-43ae-4f3a-b87a-adc9551e75a9"
May  9 00:46:22 ip-10-0-20-26 guacd[3190]: User "@6dd9cf9f-a41a-42ed-94a0-c5cf7b03da7e" joined connection "$5c926d1e-43ae-4f3a-b87a-adc9551e75a9" (1 users now present)
May  9 00:46:22 ip-10-0-20-26 guacd[3190]: Auth key successfully imported.
May  9 00:46:22 ip-10-0-20-26 guacd[3190]: No known host keys provided, host identity will not be verified.
May  9 00:46:22 ip-10-0-20-26 guacd[3190]: Public key authentication failed: Unable to extract public key from private key.
May  9 00:46:22 ip-10-0-20-26 guacd[3190]: User "@6dd9cf9f-a41a-42ed-94a0-c5cf7b03da7e" disconnected (0 users remain)
May  9 00:46:22 ip-10-0-20-26 guacd[3190]: Last user of connection "$5c926d1e-43ae-4f3a-b87a-adc9551e75a9" disconnected
May  9 00:46:22 ip-10-0-20-26 guacd[2017]: Connection "$5c926d1e-43ae-4f3a-b87a-adc9551e75a9" removed.

**Comment by mdhont** [comment]
Can you tell me the exact steps to reproduce the issue?

**Comment by frhodes-aam** [comment]
> Can you tell me the exact steps to reproduce the issue?

1. I launch a new Guacamole instance using the latest AMI on AWS Marketplace for ap-southeast-2 region.
2. Once launch was complete, i logged in and created connections for a Windows and Linux based EC2 instance (existing instances), for the linux based during creation I added the username and private key
 
![image](https://github.com/bitnami/vms/assets/92558511/df6ef1f6-1fbe-4dbe-a9b1-639860bb88fb)
3. I save the connections and try to connect, RDP connection was successful, ssh connection unsuccessful..checked syslog and repeatedly get the error i put in my first post.

**Comment by mdhont** [comment]
Could you check the official documentation to see if you are following the same steps?

https://guacamole.apache.org/doc/gug/configuring-guacamole.html#ssh

**Comment by frhodes-aam** [comment]
> Could you check the official documentation to see if you are following the same steps?
> 
> https://guacamole.apache.org/doc/gug/configuring-guacamole.html#ssh

Hi

I am well aware and following the steps to configure and initiate connections, I have an earlier version of your bitnami product that worked seamlessly but this latest version is not working.

**Comment by frhodes-aam** [comment]
> I've been investigating the issue further. Could you ensure that the private key is in the PEM format? If it's not, could you try that?
> 
> ```
> ssh-keygen -t rsa -b 4096 -m PEM
> ```

Hi Michiel

Thanks for looking into this, the certificate in in PEM format.

**Comment by mdhont** [comment]
It seems it has to do with the crypto backend the libssh component was compiled against. Could you launch a fresh instance and try to build the libssh library using an OpenSSL crypto backend?


    # back up the existing libs:
    cd ~/
    cp /usr/lib/x86_64-linux-gnu/libssh2.so .

    # clone the repo, create folders
    sudo apt-get install -y git libssh-dev cmake
    git clone https://github.com/libssh2/libssh2.git
    cd libssh2
    mkdir bin
    cd bin

    # recompile the libs
    cmake -DCRYPTO_BACKEND=OpenSSL ..
    cmake --build .
    sudo cp src/libssh2.so* /usr/lib/x86_64-linux-gnu
     
And then try again?

**Comment by frhodes-aam** [comment]
Thanks mate, that worked!!!

**Comment by mdhont** [comment]
Great! I will create a task for fixing the issue. We will notify you if a new version with a fix comes out.

**Comment by phuleratribhuwan** [comment]
Hi Team,

I tried above shared steps also digged into the issues list but still unable to resolve the issue.
I am currently trying to connect to Oracle Cloud Infrastructure Oracle Linux OS with provided private key which starts and ends with 	-----BEGIN RSA PRIVATE KEY----- 	-----END RSA PRIVATE KEY-----

But after creating connection with providing Hostname, Port, username and private key with other required details. I am getting below error in syslog: 

Jun  8 04:08:24 btspldevremote01 guacd[332330]: Auth key successfully imported.
Jun  8 04:08:24 btspldevremote01 guacd[332330]: No known host keys provided, host identity will not be verified.
Jun  8 04:08:24 btspldevremote01 guacd[332330]: Public key authentication failed: Unable to extract public key from private key file: Unsupported private key file format
Jun  8 04:08:24 btspldevremote01 guacd[332330]: User "@f9735490-e9c3-4c54-a9cf-c033fee0d707" disconnected (0 users remain)
Jun  8 04:08:24 btspldevremote01 guacd[332330]: Last user of connection "$00231ee9-34f2-4f68-b625-375188a0a25f" disconnected
Jun  8 04:08:25 btspldevremote01 guacd[330638]: Connection "$00231ee9-34f2-4f68-b625-375188a0a25f" removed.

![config](https://github.com/bitnami/vms/assets/112239282/9a299d27-4c6a-43fa-b8ce-5d3a196858bd)
![error](https://github.com/bitnami/vms/assets/112239282/cf5dd999-6fba-493a-93fe-48e8f56e4642)
