### ISSUE TITLE
Bitnami Wordpress in Lightsail

### ISSUE THREAD

**Issue by rahepler2** [bitnami/vms#901]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4c2c7855-c457-ad42-4c97-3f8667d1075b

### bndiagnostic output

Wordpress:
 PHP Parse error: syntax error, unexpected token ":'  in wp-config.php file on line 215. 

Apache: 
 PHP parse error: syntax error, unexpected token ":' in wp-config.php on line 215 
    - this line is shown 3 times. 

### bndiagnostic was not useful. Could you please tell us why?

n/a

### Describe your issue as much as you can

So, suddenly the site went down and I was unable to access this. Upon looking into it, we found no issues that would cause the site to not serve content. The only change was moving from GoDaddy DNS to Cloudflare DNS (proxy toggled on and off to no avail). I also disabled plugins by renaming plugins file, and this did not restore function either. 

Currently the server is refusing to connect. Previously I received 302 redirect loops. 

No idea what would have caused this.

**Comment by mdhont** [comment]
There seems to be a syntax error on line 215 of wp-config.php.
.
```
PHP Parse error: syntax error, unexpected token ":' in wp-config.php file on line 215.
```

Could you check it?

**Comment by rahepler2** [comment]
So the wp-config file is only 100 lines which is part of the issue.

**Comment by mdhont** [comment]
Maybe it has been altered then? Could you paste the last few lines?
