### ISSUE TITLE
[WordPress] Daily downtime 

### ISSUE THREAD

**Issue by DoctorOnCall** [bitnami/vms#902]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

n/a

### bndiagnostic output

n/a

### bndiagnostic was not useful. Could you please tell us why?

Bitnami wordpress daily downtime

### Describe your issue as much as you can

Hi,

We are using LightSail Bitnamo wordpress and it is getting daily down, we have checked the resources, even no issues there. We have enough space there (88% free), no high cpu.

and it goes randmonly down and we have to restart using sudo /opt/bitnami/ctlscript.sh restart

Please do suggest how to improve this?

**Comment by jotamartos** [comment]
Please take a look at the existing tickets before creating a new one. There are many in the issues tab already, for example this one: 

https://github.com/bitnami/vms/issues/27#issuecomment-1143985862
