### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by callmesnake1977** [bitnami/vms#904]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

521f8f1b-1ba8-a7aa-65e5-3a386f0bf240

### bndiagnostic output

A high number of incoming requests originate from one or more unique IP 
addresses. This could indicate a bot attack. The following guide shows how to 
check for and block suspicious IP addresses.
 
https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/
our instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 481 300 9 59 171 109 Swap: 634 
359 275

The following error appears in the 
/opt/bitnami/php/var/log/php-fpm.log:
```
[10-May-2023 16:55:27] WARNING: [pool www] server reached max_children setting 
(5), consider raising it

### bndiagnostic was not useful. Could you please tell us why?

Following the directions in the guides recommended results in errors like no such directory

### Describe your issue as much as you can

There has been a critical error on this website.

**Comment by mdhont** [comment]
Could you please be more specific about the error? According to the bndiagnostic output there is a high number of incoming requests from the same IP, which could indicate a bot attack. The following guide shows how you can block those:

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-
bots-apache/
