### ISSUE TITLE
[WordPress High Availability] Are you no longer supporting this solution on AWS—Partner Solution?

### ISSUE THREAD

**Issue by SC-Josh** [bitnami/vms#905]
### Describe your issue as much as you can

It was up a few days ago on AWS and now it is gone. What do you have planned?

**Comment by aingham** [comment]
Hi @jotamartos,

we are now looking at the new Bitnami solutions, but we really need to keep our current sites up-to-date in terms of PHP and Apache versions until we can potentially migrate across to the new approaches.

Given that PHP and Apache seem to be compiled from source on the Bitnami HA WP AMIs, could you give us any guidance on updating these on an AMI? It would be hugely appreciated!

Many thanks,

Andy

**Comment by jotamartos** [comment]
As I mentioned above, this solution is no longer supported. You can take a look at the Bitnami WordPress Chart and the features it includes. If you have any questions, you can also create a new support ticket in the charts repository 

https://github.com/bitnami/charts/issues
