### ISSUE TITLE
[Alfresco] Alfresco search services does't index new documents (pdf)

### ISSUE THREAD

**Issue by pablodazevedo** [bitnami/vms#906]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b1fd8291-6927-8b14-511d-e950d014cb10

### bndiagnostic output

    ✓ Processes: No issues found
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Apache: No issues found

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

This is a problem using Alfresco.

### Describe your issue as much as you can

Alfresco Share instance run, but when i added new documents, Solr doesn't index them.

I've tried everything to get alfresco search services to index new documents. Unsuccessfully!

**Comment by jotamartos** [comment]
Hi @pablodazevedo,

That's an Alfresco-related question so we suggest you contact its developers or create a topic in its support forum to get more information about the issue. If all services are up and running, the document should be indexed. 

Thanks
