### ISSUE TITLE
[<Azure>] <Cant access my website from the ip address anymore>

### ISSUE THREAD

**Issue by ADNANE-RBT** [bitnami/vms#908]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3109e18e-5b59-5d8b-b1f0-6505b9e964bd

### bndiagnostic output

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found
 

### bndiagnostic was not useful. Could you please tell us why?

i was redirected to a non existing page "https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro"

### Describe your issue as much as you can

Im running a magento by bitnami Vm on azure. My issue started when i couldnt access my home page anymore, only the Apache2 page showing up. everything was working alright until this moment.
i tried restarting the services at first : 
` sudo /opt/bitnami/ctlscript.sh restart`
returned :
```
Restarting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.
```
then tried :
`sudo systemctl status bitnami.service`
returned the following : 

> bitnami.service - LSB: bitnami init script
>      Loaded: loaded (/etc/init.d/bitnami; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Fri 2023-05-12 12:56:43 UTC; 9min ago
>     Process: 73292 ExecStart=/etc/init.d/bitnami start (code=exited, status=1/FAILURE)
>       Tasks: 989 (limit: 4091)
>      Memory: 1017.3M
>         CPU: 2.960s
>      CGroup: /system.slice/bitnami.service
>              ├─ 1033 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
>              ├─ 1037 php-fpm: pool www
>              ├─ 1038 php-fpm: pool www
>              ├─ 1039 php-fpm: pool www
>              ├─ 1040 php-fpm: pool www
>              ├─ 1041 php-fpm: pool www
>              ├─ 1042 php-fpm: pool www
>              ├─ 1043 php-fpm: pool www
>              ├─ 1044 php-fpm: pool www
>              ├─ 1045 php-fpm: pool www
>              ├─ 1046 php-fpm: pool www
>              ├─ 1047 php-fpm: pool www
>              ├─ 1048 php-fpm: pool www
>              ├─ 1049 php-fpm: pool www
>              ├─ 1050 php-fpm: pool www
>              ├─ 1051 php-fpm: pool www
>              ├─ 1052 php-fpm: pool www
>              ├─ 1053 php-fpm: pool www
>              ├─ 1054 php-fpm: pool www
>              ├─ 1055 php-fpm: pool www
>              ├─ 1056 php-fpm: pool www
>              ├─ 1057 php-fpm: pool www
>              ├─ 1058 php-fpm: pool www
>              ├─ 1059 php-fpm: pool www
>              ├─ 1060 php-fpm: pool www
>              ├─ 1061 php-fpm: pool www
>              ├─ 1062 php-fpm: pool www
>              ├─ 1063 php-fpm: pool www
>              ├─ 1064 php-fpm: pool www
>              ├─ 1065 php-fpm: pool www
>              ├─ 1066 php-fpm: pool www
>              ├─ 1067 php-fpm: pool www
>              ├─ 1068 php-fpm: pool www
>              ├─ 1069 php-fpm: pool www
>              ├─ 1070 php-fpm: pool www
>              ├─ 1071 php-fpm: pool www
>              ├─ 1072 php-fpm: pool www
>              ├─ 1073 php-fpm: pool www
>              ├─ 1074 php-fpm: pool www
>              ├─ 1075 php-fpm: pool www
>              ├─ 1076 php-fpm: pool www
>              ├─ 1089 /opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/>
>              ├─ 1143 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
>              ├─ 1146 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
>              ├─ 1147 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
>              ├─ 1148 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
>              ├─ 1149 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
>              ├─ 1670 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
>              ├─ 1801 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
>              ├─ 1802 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
>              └─15783 php-fpm: pool www
> 
> May 12 12:56:43 magento-testing-vm systemd[1]: bitnami.service: Unit process 1146 (httpd) remains running after unit stopped.
> May 12 12:56:43 magento-testing-vm systemd[1]: bitnami.service: Unit process 1147 (httpd) remains running after unit stopped.
> May 12 12:56:43 magento-testing-vm systemd[1]: bitnami.service: Unit process 1148 (httpd) remains running after unit stopped.
> May 12 12:56:43 magento-testing-vm systemd[1]: bitnami.service: Unit process 1149 (httpd) remains running after unit stopped.
> May 12 12:56:43 magento-testing-vm systemd[1]: bitnami.service: Unit process 1670 (httpd) remains running after unit stopped.
> May 12 12:56:43 magento-testing-vm systemd[1]: bitnami.service: Unit process 1801 (httpd) remains running after unit stopped.
> May 12 12:56:43 magento-testing-vm systemd[1]: bitnami.service: Unit process 1802 (httpd) remains running after unit stopped.
> May 12 12:56:43 magento-testing-vm systemd[1]: bitnami.service: Unit process 15783 (php-fpm) remains running after unit stopped.
> May 12 12:56:43 magento-testing-vm systemd[1]: Failed to start LSB: bitnami init script.
> May 12 12:56:43 magento-testing-vm systemd[1]: bitnami.service: Consumed 2.104s CPU time.
> 
i tried `sudo journalctl -xe` too and it returned:

> 
> May 12 13:00:04 magento-testing-vm CRON[73656]: pam_unix(cron:session): session closed for user daemon
> May 12 13:01:01 magento-testing-vm CRON[73674]: pam_unix(cron:session): session opened for user daemon(uid=1) by (uid=0)
> May 12 13:01:01 magento-testing-vm CRON[73675]: (daemon) CMD (/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run 2>&1 | grep -v "Ran jobs by sche>
> May 12 13:01:04 magento-testing-vm CRON[73674]: pam_unix(cron:session): session closed for user daemon
> May 12 13:01:41 magento-testing-vm dhclient[458]: XMT: Solicit on eth0, interval 109180ms.
> May 12 13:02:01 magento-testing-vm CRON[73713]: pam_unix(cron:session): session opened for user daemon(uid=1) by (uid=0)
> May 12 13:02:01 magento-testing-vm CRON[73714]: (daemon) CMD (/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run 2>&1 | grep -v "Ran jobs by sche>
> May 12 13:02:03 magento-testing-vm CRON[73713]: pam_unix(cron:session): session closed for user daemon
> May 12 13:02:31 magento-testing-vm waagent[2151]: 2023-05-12T13:02:31.275365Z INFO ExtHandler ExtHandler No requested version specified, checking for all version>
> May 12 13:03:01 magento-testing-vm CRON[73729]: pam_unix(cron:session): session opened for user daemon(uid=1) by (uid=0)
> May 12 13:03:01 magento-testing-vm CRON[73730]: (daemon) CMD (/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run 2>&1 | grep -v "Ran jobs by sche>
> May 12 13:03:04 magento-testing-vm CRON[73729]: pam_unix(cron:session): session closed for user daemon
> May 12 13:03:30 magento-testing-vm dhclient[458]: XMT: Solicit on eth0, interval 109410ms.
> May 12 13:04:01 magento-testing-vm CRON[73743]: pam_unix(cron:session): session opened for user daemon(uid=1) by (uid=0)
> May 12 13:04:01 magento-testing-vm CRON[73744]: (daemon) CMD (/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run 2>&1 | grep -v "Ran jobs by sche>
> May 12 13:04:03 magento-testing-vm CRON[73743]: pam_unix(cron:session): session closed for user daemon
> May 12 13:04:07 magento-testing-vm waagent[2151]: 2023-05-12T13:04:07.606444Z INFO ExtHandler ExtHandler [HEARTBEAT] Agent WALinuxAgent-2.9.0.4 is running as the>
> May 12 13:05:01 magento-testing-vm CRON[73759]: pam_unix(cron:session): session opened for user daemon(uid=1) by (uid=0)
> May 12 13:05:01 magento-testing-vm CRON[73760]: (daemon) CMD (/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run 2>&1 | grep -v "Ran jobs by sche>
> May 12 13:05:04 magento-testing-vm CRON[73759]: pam_unix(cron:session): session closed for user daemon
> May 12 13:05:20 magento-testing-vm dhclient[458]: XMT: Solicit on eth0, interval 116620ms.
> May 12 13:06:01 magento-testing-vm CRON[73827]: pam_unix(cron:session): session opened for user daemon(uid=1) by (uid=0)
> May 12 13:06:01 magento-testing-vm CRON[73828]: (daemon) CMD (/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run 2>&1 | grep -v "Ran jobs by sche>
> May 12 13:06:03 magento-testing-vm CRON[73827]: pam_unix(cron:session): session closed for user daemon
> May 12 13:06:08 magento-testing-vm sudo[73887]:  bitnami : TTY=pts/0 ; PWD=/bitnami/magento ; USER=root ; COMMAND=/usr/bin/systemctl status bitnami.service
> May 12 13:06:08 magento-testing-vm sudo[73887]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
> May 12 13:06:48 magento-testing-vm sudo[73887]: pam_unix(sudo:session): session closed for user root
> May 12 13:07:01 magento-testing-vm CRON[74041]: pam_unix(cron:session): session opened for user daemon(uid=1) by (uid=0)
> May 12 13:07:01 magento-testing-vm CRON[74042]: (daemon) CMD (/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run 2>&1 | grep -v "Ran jobs by sche>
> May 12 13:07:04 magento-testing-vm CRON[74041]: pam_unix(cron:session): session closed for user daemon
> May 12 13:07:16 magento-testing-vm dhclient[458]: XMT: Solicit on eth0, interval 125200ms.
> May 12 13:07:43 magento-testing-vm sshd[74079]: Unable to negotiate with 218.92.0.47 port 26244: no matching key exchange method found. Their offer: diffie-hellm>
> May 12 13:08:01 magento-testing-vm CRON[74081]: pam_unix(cron:session): session opened for user daemon(uid=1) by (uid=0)
> May 12 13:08:01 magento-testing-vm CRON[74082]: (daemon) CMD (/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run 2>&1 | grep -v "Ran jobs by sche>
> May 12 13:08:04 magento-testing-vm CRON[74081]: pam_unix(cron:session): session closed for user daemon
> May 12 13:08:35 magento-testing-vm sudo[74138]:  bitnami : TTY=pts/0 ; PWD=/bitnami/magento ; USER=root ; COMMAND=/usr/bin/journalctl -xe
> May 12 13:08:35 magento-testing-vm sudo[74138]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
>  
also may be worth the note but i tried: 
```
bitnami@magento-testing-vm:/var/run$ ls
0_waagent.pid  chrony       crond.reboot        initctl       mount            sshd        udev                          uuidd
agetty.reload  chrony-dhcp  dbus                initramfs     network          sshd.pid    unattended-upgrades.lock      waagent.pid
apache2        cloud-init   dhclient6.eth0.pid  lock          screen           sudo        unattended-upgrades.progress
atd.pid        credentials  dhclient.eth0.pid   log           sendsigs.omit.d  systemd     user
blkid          crond.pid    exim4               motd.dynamic  shm              tmpfiles.d  utmp
bitnami@magento-testing-vm:/var/run$ cat gonit.pid
```

**Comment by mdhont** [comment]
According to the bndiagnostic tool it seems the machine is running low on resources. I recommend upgrading it to a more powerful one.

**Comment by ADNANE-RBT** [comment]
@mdhont thank you, however, wouldn't the second apache issue be the cause for the inability to access my IP address ?
as im not able to find the gonit.pid file

**Comment by mdhont** [comment]
Could you explain what you mean with inability to access your IP address? Does the page have a domain configured? Can you access it through that?
