### ISSUE TITLE
[WordPress] How to bulk redirect urls in WordPress NGINX?

### ISSUE THREAD

**Issue by gjcounter** [bitnami/vms#91]
### Describe your issue as much as you can

Hi
I'm new on NGINX and i'm moving a website from a proprietary CMS to WordPress. I figured out that bitnami package doesn't use htaccess, so I would like to know how I can bulk redirect my old URLs (about 10k) to the new ones.

The old ones don't look anything like the WordPress URLs so I have to redirect them one by one. Can somebody give me some directions? 

I really appreciate any help you can provide.

**Comment by jotamartos** [comment]
You have two options here:

- I understand there should be a WordPress' plugin that can help you redirect some URLs
- If that's not a possibility, then you will need to configure your redirections in the "wordpress" files inside the /opt/bitnami/nginx/conf/server_blocks/ folder. You will need to restart NGINX later.

**Comment by jotamartos** [comment]
Thanks @gjcounter,

I forgot to mentioned that you also have this guide in our documentation to redirect all your requests to your domain 

https://docs.bitnami.com/general/apps/wordpress-pro/administration/use-single-domain/
