### ISSUE TITLE
Bitnami LAMP stack on AWS: Error with bncert-tool: "Starting web server: Failed to start"

### ISSUE THREAD

**Issue by giorgiomarrale** [bitnami/vms#911]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5e9de17f-2119-ad0d-9aee-847c9dc22677

### bndiagnostic output

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Apache: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

I have set-up LAMP stacks before, same way, without any issues

### Describe your issue as much as you can

I have an issue when running the bncert-tool. It creates the certificates as expected, but won't finish and reverts the changes because the Apache server won't start.

Error

An error occurred when applying configurations.

The web server configuration was left unchanged. There was an error in the new 
configuration, so it was reverted.

Failed steps:
* Starting web server: Failed to start

Find more details in the log file:

/tmp/bncert-202305131916.log

However, when manually executing: "sudo /opt/bitnami/ctlscript.sh start" it starts without any problems. These are the logfile errors:

Error running ./autoupdate-linux-x64.run --mode unattended: child process exited abnormally

Error running diff -uw /opt/bitnami/apache/conf/httpd.conf /opt/bitnami/apache/conf/httpd.conf.back.202305131916: child process exited abnormally

Error running diff -uw /opt/bitnami/apache/conf/bitnami/bitnami.conf /opt/bitnami/apache/conf/bitnami/bitnami.conf.back.202305131916: child process exited abnormally

Error running diff -uw /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf.back.202305131916: child process exited abnormally

I have been trying to find it on my own but am stuck. Hope someone can help.

**Comment by giorgiomarrale** [comment]
I also changed the instance type from t2.micro to t2.small to see if that makes a difference, but it doesn't.

**Comment by giorgiomarrale** [comment]
After analysing the situation, it would make sense that it fails because of an edit that bncert-tool makes to one of the conf files. This is probably one file that has the vhosts in it, which I manually edited. I will revert these files and try again.

**Comment by giorgiomarrale** [comment]
This is coming from the error log:

[Mon May 15 20:43:56.031051 2023] [ssl:warn] [pid 28873:tid 139754441669632] AH01909: mydomain.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon May 15 20:43:56.032027 2023] [security2:notice] [pid 28873:tid 139754441669632] ModSecurity for Apache/2.9.7 (http://www.modsecurity.org/) configured.
[Mon May 15 20:43:56.032127 2023] [security2:notice] [pid 28873:tid 139754441669632] ModSecurity: APR compiled version="1.7.4"; loaded version="1.7.4"
[Mon May 15 20:43:56.032216 2023] [security2:notice] [pid 28873:tid 139754441669632] ModSecurity: PCRE compiled version="8.39 "; loaded version="8.39 2016-06-14"
[Mon May 15 20:43:56.032308 2023] [security2:notice] [pid 28873:tid 139754441669632] ModSecurity: LIBXML compiled version="2.9.10"
[Mon May 15 20:43:56.032429 2023] [security2:notice] [pid 28873:tid 139754441669632] ModSecurity: StatusEngine call: "2.9.7,Apache,1.7.4/1.7.4,8.39/8.39 2016-06-14,(null),2.9.10,ddc626e8d1b181f392df770c3fb3ea7175fe2aef"
[Mon May 15 20:43:56.042380 2023] [security2:notice] [pid 28873:tid 139754441669632] ModSecurity: StatusEngine call failed. Query: GIXDSLRXFRAXAYLDNBSSYMJOG4XDILZR.FY3S4NBMHAXDGOJPHAXDGOJAGIYDCNRN.GA3C2MJUFQUG45LMNQUSYMROHEXDCMBM.MRSGGNRSGZSTQZBRMIYTQMLGGM4TEZDG.G43TAYZTMZRDGZLBG4YTONLGMUZGCZLG.1684183436.status.modsecurity.org
[Mon May 15 20:43:56.060209 2023] [ssl:warn] [pid 28874:tid 139754441669632] AH01909: mydomain.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon May 15 20:43:56.063222 2023] [mpm_event:notice] [pid 28874:tid 139754441669632] AH00489: Apache/2.4.57 (Unix) OpenSSL/1.1.1n proxy_html/3.1.2 configured -- resuming normal operations
[Mon May 15 20:43:56.063343 2023] [core:notice] [pid 28874:tid 139754441669632] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'

Hope someone can help out.

**Comment by giorgiomarrale** [comment]
I have everything up and running but the bncert-tool still fails to restart. Here's what happens:

Executing the bncert-tool
Running through the process
It actually creates the certificates
It fails to restart and reverts all changes (to the .conf files)
It does not revoke the certificates that have been created (so made the changes to the bitnami.conf and bitnami-ssl.conf manually, as well as to my vhosts.conf files

So, somehow it keeps failing and as far as I understand, this may have something to do with this error:

server certificate does NOT include an ID which matches the server name

**Comment by mdhont** [comment]
> server certificate does NOT include an ID which matches the server name

That's just a warning which doesn't indicate the real problem. 

Could you follow the manual approach (without using bncert) using the guide I shared:

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

Also, the output from the bndiagnostic-tool indicates that the machine is running low on resources (RAM memory), so in any case I recommend upgrading the machine:

https://docs.bitnami.com/aws/faq/administration/change-server-type/
