### ISSUE TITLE
How can I download bitnami-erpnext-13.14.1-4-linux-debian-10-x86_64-hvm-ebs-nami

### ISSUE THREAD

**Issue by kervanaslan** [bitnami/vms#917]
### Describe your issue as much as you can

Hello,

I was using Bitnami ERP Next with image name `bitnami-erpnext-13.14.1-4-linux-debian-10-x86_64-hvm-ebs-nami` on AWS.
Today I wanted to migrate it to digitalocean. I wanted to download this image and upload it to digitalocean as custom image but I can't find 13.14.1 on bitnami.com

Is there a way to download this image?

Thanks.

**Comment by gongomgra** [comment]
Hi @kervanaslan,

Thanks for using Bitnami. It is true that we no longer provide images for ERPNext 13.x versions, but you can still launch our already published images from the AWS console. You can also export an AWS instance using the official docs linked below

https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport.html

Hope it helps!
