### ISSUE TITLE
How to update php and apache packages on AWS Marketplace product "Bitnami LMS powered by Moodle(TM) LMS"

### ISSUE THREAD

**Issue by bhavukm** [bitnami/vms#918]
### Describe your issue as much as you can

Hello Bitnami Support,

As part of vulnerability management, we want to upgrade php version from 7.3.27 to 8.0.28 and apache from 2.4.38 to 2.4.56 on an AWS Marketplace product that we have been using to deploy one of our applications. The product that we are using is:

Bitnami LMS powered by Moodle(TM) LMS (https://aws.amazon.com/marketplace/pp/prodview-4vrsnatvdabsc#pdp-overview)

The other details from the current AMI:

OS: Debian Buster 10
Moodle: 3.8 ( We want this to be upgraded to 3.11 as well)
Apache: 2.4.38
PHP: 7.3.27
openssl : earlier than 1.1.1u (it should be greater than or equal to 1.1.1u)

Please assist as this is critical for us.

Regards
Bhavuk Mudgal
bmudgal@gtlaw.com.au

**Comment by bhavukm** [comment]
Any update on this issue?

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually.

**Comment by bhavukm** [comment]
@mdhont Thanks for the update. I have another question on: what if we have to upgrade Moodle from current 3.8 to 3.11, and as part of that, we need to upgrade php and apache versions?

**Comment by bhavukm** [comment]
Is there any further update on this?

**Comment by bhavukm** [comment]
I went through Moodle documentation to understand from what versions we can upgrade moodle from, to 4.2 (the version available with Bitnami Moodle AMI on AWS Marketplace). Currently, we are on 3.8. We can upgrade to 4.2 only from 3.9 or later.
Since, we are on 3.8, any idea how to upgrade to 4.2?

**Comment by mdhont** [comment]
Perhaps a bit of a hassle but you could install Moodle 3.9 using the linux-x64 installer:

https://downloads.bitnami.com/files/stacks/moodle/3.9.0-0/bitnami-moodle-3.9.0-0-module-linux-x64-installer.run 

    md5:f924edd11cea0b6e691e1e82c3c3b690

And first migrate the data there as an intermediate step.

**Comment by bhavukm** [comment]
Hello Michiel,

I have some questions raised by the developer team. Please have a look and suggest a solution:

Developer Team: As you know I upgraded Smartskills(our application name) from Moodle 3.8 to Moodle 3.11 on my local.

We can’t upgrade directly to Moodle 4.2 from Moodle 3.8 (As per documentation :- https://docs.moodle.org/402/en/Upgrading). We can only upgrade to Moodle 4.2 from Moodle 3.9 or later.

Why I choose Moodle 3.11 :- Because it is compatible with PHP 8.0.x and Apache 2.4.56, which is our requirement.

So we want PHP 8.0.x and Apache 2.4.56 to run our upgraded Smartskills on dev. We can try Apache 2.4.46 if 2.4.56 is not available but PHP 8.0.x is required.

So kindly find an AMI which is having same version of PHP and Apache. And update this on dev so that I can commit upgraded files/folders. Once updated files moved to dev then moodle update the database itself and site is start running on updated moodle after that.

Ask to bitnami team that how we can run Moodle 3.11 with PHP 8.0 and Apache 2.4.56 on dev. Or ask about Moodle 3.11 available AMI. There must be something for Moodle 3.11 as this is a stable version from Moodle.

**Comment by mdhont** [comment]
Our applications are configured with the latest components, and unfortunately there has been no Moodle release with those specific component versions. You can find more information in the Changelog:

https://bitnami.com/stack/moodle/gcedebian-x64-nami/changelog.txt
