### ISSUE TITLE
[ResourceSpace] Upgrade RS from 9.3 to 10.1 documentation does not match current setup

### ISSUE THREAD

**Issue by hahriley** [bitnami/vms#919]
### Describe your issue as much as you can

Attempting to upgrade an AWS database with ResourceSpace (to version 10.1) currently operating on RS version 9.3.1. I'm using WinSCP with PuTTY to access RS, however documentation to upgrade RS only advises upgrade to be done in git. I was able to download the new version by replacing the "git svn copy" with "svn checkout" however cannot find the directory with the current version in the path shown in documentation I believe I found it in the path "/opt/bitnami/apps/resourcespace" . With both the path and code used in the documentation not valid for my system, I am unsure how to proceed. Please advise how I can proceed via PuTTY, or how I can access and use Git.

**Comment by jotamartos** [comment]
Depending on how old the deployment is, you may find the app's files at /opt/bitnami/apps/resourcespace/htdocs (old directory structure) or at /opt/bitnami/resourcespace (new directory structure). Please note that we updated the directory structure some years ago and that's why the documentation is now updated with the new path. However, you should be able to follow the same documentation just changing the path where the app is installed.

**Comment by hahriley** [comment]
That helped. However due to a mistake, I had deleted all contents of the 'conf' directory. Is there a way to restore it or find the files online? I could not find a Windows or Linux version that came with it to extract it?

**Comment by jotamartos** [comment]
> Is there a way to restore it or find the files online? I could not find a Windows or Linux version that came with it to extract it?

Could you let us know the exact version you have so we can take a look in our records and provide you with some instructions about how to recover that info? You will probably need to launch a new instance/VM and copy the data from that new deployment to the current one.

**Comment by hahriley** [comment]
I'm trying to go from Version 9.3 to 10.1
Presently I'm troubleshooting endless syntax errors when I try to start or restart apache 2 services. I got a copy of my original RS's Conf folder (I'm working on an exact copy). The syntax errors are for lines that have "include ..." (referencing bitnami.conf, bitnami-apps-prefix.conf, hittpd-prefix.conf). I'm getting the syntax errors even when it's correct, so I think that could be a permission issue but I'm not entirely sure. Other errors I've gotten include "php-fpm configuration is incorrect" and "FPM initialization failed"

**Comment by jotamartos** [comment]
I understand the issues are happening in the old instance, right? This is the last Bitnami ResourceSpace 9.3.x OVA we released

https://downloads.bitnami.com/files/stacks/resourcespace/9.3.15737-1/bitnami-resourcespace-9.3.15737-1-linux-debian-10-x86_64.ova

You can launch it in your local computer and copy the missing files. Please remember to set the permissions as well. Once you finish with that, you should be able to restart Apache in that instance and finish with the migration process.

**Comment by hahriley** [comment]
I had successfully replaced the missing files and updated it from 9.3 to 10.1, however I had to reset my test environment due to multiple issues. I believe I had placed the SVN clone in the wrong location, or had updated; php, Apache2, RS ,and MySQL incorrectly. Based on my file system (screenshot provided), can you advise me on where I should place the clone, and how to update each part?
![System SC1](https://github.com/bitnami/vms/assets/133808164/64e2afcb-cf3e-4891-8744-7dcddb43daa3)

**Comment by jotamartos** [comment]
If you want to create a repository to store the information of the installation, you need to store all the files included in the /bitnami and /opt/bitnami directories. It's similar to what is explained here

https://docs.bitnami.com/general/apps/resourcespace/administration/backup-restore/

**Comment by hahriley** [comment]
Considering the amount of time we have spent on this with little progress. We feel we need paid support to complete this process. Do you provide that, and if so how do I request it?

**Comment by jotamartos** [comment]
I'm sorry but we do not provide that kind of support.

**Comment by jotamartos** [comment]
Yes, in that case, you will need to migrate the database and all the necessary files for the application to run.

https://docs.bitnami.com/general/apps/resourcespace/administration/backup-restore-mysql-mariadb/

However, we suggest you take a look at the app's official documentation to know if any extra step is needed during this migration. Please note that you will probably need to update the database information to match with the info of the new version.

**Comment by hahriley** [comment]
After exhausting every piece of documentation, attempting this through different means, I have concluded that I cannot complete this on my own due to the level of complexity . Is there any third party company you would recommend, that would be able to perform this upgrade?

**Comment by jotamartos** [comment]
I'm sorry but we do not know anybody that takes care of this migration. However, you can ask the ResourceSpace support team to know if they offer support to migrate the application or if they know somebody that can help. 

Thanks
