### ISSUE TITLE
[wordpress] https issue

### ISSUE THREAD

**Issue by ErnstDinkelmann** [bitnami/vms#92]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

8194dd3d-15d6-d11c-0e82-2841fa3dec6a

### bndiagnostic output

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

The suggested guidelines are not relevant to my issue.

### Describe your issue as much as you can

Hi!

Website: https://www.crywolf.co.za

Recent migration from shared linux managed hosting to aws ec2 bitnami self-hosting.
The browser indicates certificate is valid. Everything seems to be working on the website, except:

**Firstly**
One of our critical plugins is having an http/https issue on the aws bitnami hosting solution.
Plugin: Send PDF for Contact Form 7
Issue: Settings allows specifying a logo image. If browsing to the image, it inserts the location as https
But it does not generate in the generated PDF. If overwriting the setting as http, it works. I guess it has a work-around, but suggests a problem. 
There is also an signature image inserted with tag img src="[your-signature]" height="200", which does not work at all. This used to work on the previous hosting solution. This img tag obviously resolves to https as well.
Is this a plugin permission issue not allowing it to access https content? Or some setting I've missed?

**Secondly**
We get this warning on our website, viewable with chrome developer tools (F12):
Mixed Content: The page loaded over HTTPS requested an insecure element http ... /wp-content/plugins/custom-facebook-feed/assets/img/cff-avatar.png. This request was automatically upgraded to HTTPS.
I've asked the developers of the custom-facebook-feed plugin and they suggested their is some setup issue on the host.

**Help please**
It's possible that the issue lies within the plugins themselves, but these are things that worked previously. So the only logical conclusion for now is that there is a setup issue and probably related to https.

Assistance would be greatly appreciated. Just some sanity check of whether everything is in fact correctly setup to resolve properly on the server.

Thank you

**Comment by ErnstDinkelmann** [comment]
Second issue solved. I posted my solution on the facebook-feed plugin page: https://wordpress.org/support/topic/mixed-content-http-elements-on-https-website/#post-15813461

First issue is unsolved. At the moment, I have workarounds by altering https to http, just to see logo and signature in the pdf. But that plugin is still unable to "retrieve" https images.

**Comment by mdhont** [comment]
I recommend contacting the plugin support for the first issue. It is most probably not related to permissions issues but rather to the plugin's htaccess rules. Please note that Bitnami uses a single htaccess file where you can add the plugin's htaccess rules:

https://docs.bitnami.com/ibm/infrastructure/lamp/administration/use-htaccess/

**Comment by ErnstDinkelmann** [comment]
@mdhont  Thanks Michael, appreciate the suggestion.

I've already created a ticket with the pluging author. 
I will investigate the htaccess matter myself as well.

Just to be clear, on two things:
1) The link you included is for "LAMP Packaged By Bitnami For IBM Cloud". Is The content applicable to my scenario as well - AWS (EC2) bitnami wordpress AMI ("using sytem packages")?
2) I currently have a .htaccess file in /opt/bitnami/wordpress/ 
Looking that link you sent, it suggets this htaccess file, is actually not used at the moment, until certain changes are made. Is that correct?

**Comment by ErnstDinkelmann** [comment]
@mdhont 
Hi
I've checked and there are no other htaccess files, except the one in /opt/bitnami/wordpress, which I've tested and it's not getting included. I'll move the content of this htaccess, as appropriate, to the /opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf file.

I'm still waiting for the plugin author to give feedback, which may take some time.

But, I've also stumbled upon something that may be the cause of this. It seems we are missing some ssl internediate/chain certificate(s): https://www.sslshopper.com/ssl-checker.html#hostname=www.crywolf.co.za
e.g. `curl https://www.crywolf.co.za` fails, with "curl: (60) SSL certificate problem: unable to get local issuer certificate"

Could this be the cause?

I've contacted our previous shared host and ask them to share any further certificates that they may have which is not available off their cpanel. I'll report back.

**Comment by mdhont** [comment]
The SSL certificate seems correct now when I check it with SSLshopper. Can you confirm?

**Comment by ErnstDinkelmann** [comment]
Yes! I literally just made the the changes.

Copied the ca-bundle file, requested from previous host, into the /opt/bitnami/apache/conf/bitnami/certs/ directory.
Then ensured, 
/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf, and 
/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf, contained references to all three certificate related files:
```
SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
SSLCertificateChainFile "/opt/bitnami/apache/conf/bitnami/certs/ca-bundle"
```
in the VirtualHost directive.

I then, from the plugin php removed the code which I added as a work-around which forced https to http references, to test. And I'm happy to report, it works! Ie, logo and signature is now displaying with https references, without any work-arounds needed.

That means, issue one is resolved.

Unfortunately, issue two has returned. Mixed content. But I'll investigate as it's clearly now not related to https/ssl setup issues. This must be some other issue.
