### ISSUE TITLE
[Bitnami] Apache not running

### ISSUE THREAD

**Issue by stroombvba** [bitnami/vms#920]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

708f6c5e-bf72-4629-d1dd-15e81e6db8ad

### bndiagnostic output

    ? Apache: Found possible issues
    ? Resources: Found possible issues
    ? Mysql: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Processes: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

The suggested guides did not solve the problem

### Describe your issue as much as you can

My website is down because There is something wrong with the Bitnami Wordpress Virtual Machine.
If I use command
`sudo /opt/bitnami/ctlscript.sh restart apache`
It just gives a bunch of errors around permissions and port 80
I was trying to use the guide below to restart the webserver on Google Cloud, but then I got in to permission problems.
[](https://codesteps.com/2018/10/30/how-to-fix-98address-already-in-use-ah00073-make_sock-unable-to-listen-for-connections-on-address-80-error/)

Screenshot of these errors.
![Capture](https://github.com/bitnami/vms/assets/133874708/ea8e9c41-848b-4be6-bd5f-72b492a9e1f5)

How do I get Wordpress up and running again?

**Comment by mdhont** [comment]
It's probably because you have an instance of apache already running. (the system's apache, not Bitnami). You can stop the service and remove it following the steps in this guide:

https://phpcod.com/how-to-remove-apache2-from-ubuntu-server/

**Comment by stroombvba** [comment]
@mdhont I followed the guide you suggested. I ran the diagnostic tool again and it gave me the following code:
**f97d3366-0848-ed95-c115-7ce86797d52f**
Something changed, but Wordpress is still down unfortunaty.
I still get the message: file '/etc/gonit/gonitrc' must be owned by you.
![Capture2](https://github.com/bitnami/vms/assets/133874708/8970ffa0-609d-4d73-b6ce-cc25036ed4fd)

**Comment by mdhont** [comment]
Could you try resetting the permissions of gonitrc?

    sudo chmod 600 /etc/gonit/gonitrc
