### ISSUE TITLE
[Redmine] Requesting Redmine 4.2.1-0 Linux standalone stack installer

### ISSUE THREAD

**Issue by jonathanabishop** [bitnami/vms#922]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Not related

### bndiagnostic was not useful. Could you please tell us why?

Not related

### Describe your issue as much as you can

Requesting the .run file for the Linux standalone stack for Redmine 4.2.1-0.

Thank you!

**Comment by mdhont** [comment]
You can download it here:

https://downloads.bitnami.com/files/stacks/redmine/4.2.1-0/bitnami-redmine-4.2.1-0-linux-x64-installer.run 

    md5:5239fb168d01bb36e831409b1bc57db1
