### ISSUE TITLE
[<Moodle>] <ERR_SSL_PROTOCOL_ERROR>

### ISSUE THREAD

**Issue by teksukamen** [bitnami/vms#924]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

9c10bde4-da3d-2d69-2bbe-bea23502de7f

### bndiagnostic output

    ✓ Connectivity: No issues found
    ✓ Resources: No issues found
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Error on Apache not is the problem

### Describe your issue as much as you can

Hello, I have a bitnami moodle stack, the problem is that when I changed the SSL, from one domain to another, since I couldn't make the change, I followed the instructions in this [link ](https://docs.bitnami.com/aws/how-to/understand-bncert/) to remove the ssl, after that I couldn't log in to my site using the dns configured in azure, now i have been able to run the bncert-tool and activated ssl without errors, but i still can't enter moodle whether i go by the new domain or azure dns. Every time I log in, I get this browser response ERR_SSL_PROTOCOL_ERROR. On the other hand, if I use the IP if I can enter and see moodle without problems

any ideas, thanks

**Comment by gongomgra** [comment]
Hi @teksukamen,

Thanks for using Bitnami. I was able to visit your Moodle login page without errors, and the SSL certificate is valid. However, checking your Apache logs, I found the next error related to the Moodle login.

```
[Fri May 19 16:26:22.500651 2023] [proxy_fcgi:error] [pid 3973:tid 139662689507072] [client CLIENT-IP:65379] AH01071: Got error 'PHP message: [client CLIENT-IP]  http://YOUR-MOODLE-IP  Invalid Login Token:  YOUR-USERNAME  YOUR-USER-AGENT', referer: http://YOUR-MOODLE-IP/login/index.php
```

I understand that's an issue related to the Moodle application itself. Can you check it with the Moodle team on the official forums?

https://moodle.org/mod/forum/index.php?id=5

**Comment by teksukamen** [comment]
Thanks for answering, the apache error is due to a token issue, but that doesn't worry me, the detail was that I couldn't see moodle from the dns provided by azure, but only by ip, before I could access it from both, this started with revoke the ssl certificates, anyway, finally lift the backup and start again, now everything is fine
