### ISSUE TITLE
Akeneo Upgrade to latest version

### ISSUE THREAD

**Issue by MudGreg** [bitnami/vms#925]
### Describe your issue as much as you can

Hi,

I'm trying to upgrade our Akeneo v5 instance which is currently runnin on version 5.0.46-0 of your stack.

To upgrade it requires PHP 8. As far as I can tell, you can't upgrade the PHP version on an instance can you? Or upgrade the whole instance?

So how do I migrate files and DB across and run the updates because your instance would already have a newer Akeneo installed and I need to import all the old data. The actual update of Akeneo from version to version is quite straightforward. What they don't cover is importing an older version into a new version which is why I'd rather upgrade the stack than make a whole new instance.

Also I assume that version 7.0.14 (the latest) is running php 8?

Thanks in advance for you help.

**Comment by gongomgra** [comment]
Hi @MudGreg,

Thanks for using Bitnami. I launched a fresh new Akeneo 7.0.14 server and I can confirm it includes PHP version 8.1

```
  *** Welcome to the Akeneo packaged by Bitnami 7.0.14-4        ***
  *** Documentation:  https://docs.bitnami.com/aws/apps/akeneo/ ***
  ***                 https://docs.bitnami.com/aws/             ***
  *** Bitnami Forums: https://github.com/bitnami/vms/           ***
bitnami@ip-172-31-28-92:~$ /opt/bitnami/php/bin/php -v
PHP 8.1.19 (cli) (built: May 19 2023 21:44:57) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.19, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.19, Copyright (c), by Zend Technologies
```

About the process for migrating the data, we highly recommend you to create a server backup to easily restore the current state in case anything fails. 

Regarding Akeneo, please [confirm with the upstream developers](https://www.akeneo.com/support-help-center/) what should be the right path to follow. Checking the official docs, I understand you would need to first prepare your data for the next major version (Akeneo 6.x), migrate data, prepare data for the latest major (Akeneo 7.x), and finally migrate the data again.

You can find previous Akeneo 6.x images we released in the AWS console, just in case it is of help for the upgrade process.

Also, these are the related guides I checked in the official docs
* [How to upgrade to a major version?](https://docs.akeneo.com/latest/migrate_pim/upgrade/upgrade_from_50_to_60.html)
* [How to export/import data](https://docs.akeneo.com/latest/import_and_export_data/index.html)

Hope it helps!
