### ISSUE TITLE
[Wordpress] Bitnami force http redirect to https

### ISSUE THREAD

**Issue by srakl** [bitnami/vms#929]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e494e001-8267-7646-6af7-ebae770bd813

### bndiagnostic output

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

still cant redirect to https

### Describe your issue as much as you can

I'm trying to force the redirect to https on my wesbite, and added this into my `/opt/bitnami/apache2/conf/bitnami/bitnami.conf` 

After i restart apache, it still doesnt redirect. Any ideas? Thanks

```
# Default Virtual Host configuration.

# Let Apache know we're behind a SSL reverse proxy
SetEnvIf X-Forwarded-Proto https HTTPS=on

<VirtualHost _default_:80>
    DocumentRoot "/opt/bitnami/apache/htdocs"
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    #RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
    RewriteRule ^/(.*) https://MYWEBSITE.com/$1 [R,L]
    RewriteRule /<none> / [L,R]
  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html
```
and in this file `/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf`, here is my code

```
<VirtualHost _default_:443>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  #RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
  RewriteRule ^/(.*) https://MYWEBSITE.com/$1 [R,L]
  RewriteRule /<none> / [L,R]

  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"

  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html
</VirtualHost>

**Comment by mdhont** [comment]
Could you try following the steps in this guide?

https://docs.bitnami.com/aws/apps/wordpress/administration/force-https-apache/
