### ISSUE TITLE
[Wordpress] Can not access wordpress on virtualbox

### ISSUE THREAD

**Issue by Sponsoredby** [bitnami/vms#93]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

83ae467f-7814-72dc-f433-340afdbe56e4

### bndiagnostic output

Your instance has little available RAM
? connectivity: found possible issues

### bndiagnostic was not useful. Could you please tell us why?

ram is at 700mb default set by your ova? 

### Describe your issue as much as you can

I am uing virtuialbox on windows x64 the bitnami app is 

bitnami-wordpress-6.0.0-9-r04-linux-vm-debian-11-x86_64-nami.ova

The app does not get to the setup page 
the wordpress url shows 

Error establishing a database connection
<img width="841" alt="2022-07-08 23_38_44-Database Error - Brave" src="https://user-images.githubusercontent.com/74147554/178079396-007080a6-37cf-47a9-9052-c7d24490e2de.png">

The virtualbox did report an issue with Video Ram, which I increased from 4MB to 128MB I did this AFTER running your diagnostic tool

**Comment by jotamartos** [comment]
Can you try using more RAM memory when deploying the VM? Please remember that the host machine should have enough available RAM memory when running the VM, if not it will affect its performance

**Comment by jotamartos** [comment]
It seems WordPress is not configured properly and that's probably because the initialization didn't finish properly. I can see the `/opt/bitnami/var/logs/first-boot.log` file doesn't contain any reference to WordPress. Can you take a look at it and check if there is any error there? You can also check if the initialization process finishes by checking the `~/bitnami-credentials` file.

```
sudo cat /opt/bitnami/var/logs/first-boot.log
cat ~/bitnami-credentials
```

**Comment by Sponsoredby** [comment]
I have added a screenshot of the output first-boot.log there is no clear error but there is a warning shown
<img width="370" alt="2022-07-12 13_04_57-bitnami-wordpress 1  Running  - Oracle VM VirtualBox" src="https://user-images.githubusercontent.com/74147554/178487009-9e6e0878-5411-4c21-9a5b-09153e05639f.png">


the bitnami credentials show the default username and password and no errors, so I guess this is as expected?

**Comment by jotamartos** [comment]
I just deployed the VM on my laptop and I didn't have problems. 

<img width="744" alt="Screen Shot 2022-07-13 at 09 38 25" src="https://user-images.githubusercontent.com/8791635/178678164-bc6060ae-84c9-4054-a51f-d26e5e362348.png">

Please ensure your host machine has enough disk space and RAM memory when deploying the VM. Please also try with the latest version of the Bitnami WordPress solution available in the bitnami.com website.

**Comment by vinod117** [comment]
My bitnami wordpress used to work and i had done a lot of progress to my website and suddenly it stopped working, i'm not able to open the dashboard using the ip address it says that the site can't be reached can you please help me out with this how do i get my website back
<img width="879" alt="Screenshot 2024-01-13 141614" src="https://github.com/bitnami/vms/assets/156287928/c2a15ed5-ad26-42fe-bbf9-1c8802e30c82">

**Comment by jotamartos** [comment]
Please confirm that all services are up and running 
```
sudo /opt/bitnami/ctlscript.sh start
```

and that you are using the correct IP address to access the application. If you continue running into issues, please create a different support ticket instead of reusing this one.
