### ISSUE TITLE
Lego SSL tls error

### ISSUE THREAD

**Issue by DCrash** [bitnami/vms#932]
### Describe your issue as much as you can

Hello, getting this error when trying to add or renew a cert.  It works with other domains and this one used to work until the latest renewal this week. lightsail install with domains on route 53.
2023/05/23 05:48:04 [INFO] [domain.com] acme: Trying to solve TLS-ALPN-01
2023/05/23 05:48:07 [INFO] Skipping deactivating of valid auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/230303644157 
2023/05/23 05:48:07 [INFO] Skipping deactivating of valid auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/230303644167
2023/05/23 05:48:07 [INFO] Skipping deactivating of valid auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/230303644177
2023/05/23 05:48:08 [INFO] Skipping deactivating of valid auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/230303644187
2023/05/23 05:48:08 [INFO] Skipping deactivating of valid auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/230303644197
2023/05/23 05:48:08 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/230307868427
2023/05/23 05:48:08 Could not obtain certificates:error: one or more domains had a problem:[domain.com] acme: error: 400 :: urn:ietf:params:acme:error:tls :: 35.168.67.138: remote error: tls: no application protocol****

thanks for your help
Jim

**Comment by DCrash** [comment]
Hi Checked tis here https://www.site24x7.com/tools/tls-checker.html
Working domains say this
tls 1.3 disabled
tls 1.2 enabled
tls 1.1 enabled
tls 1.0 enabled
The one that doesn't says this
tls 1.3 enabled
tls 1.2 enabled
tls 1.1 disabled
tls 1.0 disabled

not sure why it would be different they were setup the same way (i thought)
thanks

**Comment by DCrash** [comment]
More info: dig is showing wrong ip from the A record in route 53
dig +noall +answer beachhouseimports.com
beachhouseimports.com.	120	IN	A	3.230.199.117
beachhouseimports.com.	120	IN	A	35.168.67.138

A record is as follows
Record name [beachhouseimports.com](http://beachhouseimports.com/)
Record type A Value 3.221.66.194 Alias No TTL (seconds) 300 Routing policy Simple

**Comment by DCrash** [comment]
I guess some how the dns nameservers got changed and are not pointing to route53. checking it now, but that would explain everything.

**Comment by DCrash** [comment]
godaddy randomly changed my nameservers when they upgraded their dns system. not sure why but that was it.

**Comment by gongomgra** [comment]
Hi @DCrash,

Thanks for using Bitnami. I'm glad you managed to solve your issue!
