### ISSUE TITLE
[WordPress] Bitnami provisoneer-peer & AWS RDS

### ISSUE THREAD

**Issue by james-green-affinity** [bitnami/vms#933]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

NA

### bndiagnostic output

N/A

### bndiagnostic was not useful. Could you please tell us why?

I do not want to run this tool against a production environment

### Describe your issue as much as you can

We host Bitnami instances on AWS EC2 instances.

We are using the AWS Bitnami quick starts. In the EC2 user data we pass in the RDS database to use. Within the wp_config it wordpress knows what database to use based on a provisoner_peer.

Within  the /etc/hosts file the provisoner_peer points at a internal RDS DB.

This morning we had an RDS DB failover, it caused the provisoner_peer fixed IP to become read only rather than a writable DB.

Bitnami needs to be updated to go back to using fixed writer addresses rather than IP addresses. 

To fix our issues we have hardcoded the DB writer URL endpoint within the wp-config.php but we are making you aware of this issue.

__________________________________________________________________________________________________________________

root@ip-10-131-23-227:/usr/bin# cat /etc/hosts

Your system has configured 'manage_etc_hosts' as True.

As a result, if you wish for changes to this file to persist

then you will need to either

a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl

b.) change or remove the value of 'manage_etc_hosts' in

/etc/cloud/cloud.cfg or cloud-config from user-data

127.0.1.1 ip-10-131-23-227.eu-west-2.compute.internal ip-10-131-23-227
127.0.0.1 localhost

The following lines are desirable for IPv6 capable hosts

::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

BEGIN PROVISIONER MANAGED HOST RECORDS

10.131.13.189 provisioner-peer database mariadb mysql aurora
10.131.23.227 provisioner-local

END PROVISIONER MANAGED HOST RECORDS

______________________________________________________________________________

https://repost.aws/knowledge-center/aurora-mysql-db-cluser-read-only-error

root@ip-10-131-23-227:/usr/bin# mysql -u root -h 10.131.13.189 -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 13722
Server version: x.x.xx MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> show variables where variable_name='innodb_read_only';
+------------------+-------+
| Variable_name    | Value |
+------------------+-------+
| innodb_read_only | ON    |
+------------------+-------+
1 row in set (0.003 sec)

**Comment by james-green-affinity** [comment]
AWS Support response:

"So from your response I see you've been using the IP address, so this explains the reason why you are noticing readonly errors. 

I recommend that you work with your application team to consider the use cluster endpoints intead of tying your application to IP addresses. 

Thanks
"

**Comment by jotamartos** [comment]
Hi @james-green-affinity,

I'm glad to hear that you managed to solve the issue. However, we dropped support for this solution and the rest of available MultiTier solutions in the AWS Marketplace on March 31st. We suggest you launch any other Bitnami WordPress solution in AWS. For example, you can launch the Bitnami WordPress Chart solution in AWS that allows you deploy multiple WordPress replicas

https://docs.bitnami.com/aws/get-started-charts-eks-marketplace/
https://github.com/bitnami/charts/tree/main/bitnami/wordpress#wordpress-deployment-parameters

Thanks

**Comment by aingham** [comment]
Hi @jotamartos - Just checking on this...presumably the AMIs that accompanied the HA WP solution will no longer be updated either, so;

bitnami-wordpress-6.2.0-1-r01-linux-debian-11-x86_64-hvm-ebs-high-availability-nami

....will be the last published AMI? Could you offer any advice at all for people who will need to keep using this stack, at least for the foreseeable future, in terms of keeping that AMI updated? 

A particular issue is that PHP is compiled from source, rather than through a package, so can't easily be updated?

**Comment by jotamartos** [comment]
> Could you offer any advice at all for people who will need to keep using this stack, at least for the foreseeable future, in terms of keeping that AMI updated?

As I mentioned above, we suggest you deploy the Bitnami WordPress Chart that allows you deploy multiple WordPress replicas. As an alternative, you can also launch a singleVM with Bitnami WordPress (the one that is published in the Marketplace) and migrate the database to a new RDS deployment. That way you will have a similar deployment to the one you currently have. In the future, you will only need to upgrade that WordPress singleVM with the latest version and continue using the same RDS database you already deployed.

Sorry for the inconvenience.
