### ISSUE TITLE
[ERPNext] Can't login in ERPNext 12.24.3 on AWS EC2 servers

### ISSUE THREAD

**Issue by anthonylkm0613** [bitnami/vms#934]
### Describe your issue as much as you can

I use ASW Amazon Machine Images (AMIs) to create an instance ( bitnami-erpnext-14.24.3-1-r01-linux-debian-11-x86_64-hvm-ebs-nami). i saw the instance is running but i try to go to the erpnext login page http://xxx.xxx.xxx/login i see nothing. 

Could i know if i should have any cofiguration/settig to kick start this application ? Many thank in advanced for your help i found very few documentation about this. 
nthony Lam
a

**Comment by jotamartos** [comment]
Hi @anthonylkm0613,

This version of the solution passed our tests before promoting it to the AWS platform so there should be something on your side that is preventing the app to work properly. Please ensure the instance has more than 2GB of RAM for the application to work properly and that you have an updated version of the web browser. You can also try with an incognito window just in case it is a cache-related problem in the browser. 

Thanks

**Comment by anthonylkm0613** [comment]
Hi Jotamartos,
Thank you for your quick reply. Does it mean that the application will automoatically start and i supposedly can see the page at http://my-ip/login?

Regards,
Anthony Lam

**Comment by anthonylkm0613** [comment]
Dear Jotamartos, 
I finally can access it http://ec2-54-152-17-0.compute-1.amazonaws.com/login#login   
Now try to find the login password and ID.  
Regards,
Anthony Lam

**Comment by jotamartos** [comment]
>Now try to find the login password and ID.

https://docs.bitnami.com/aws/faq/get-started/find-credentials/

**Comment by anthonylkm0613** [comment]
i can login now. but how can i see the HR module? it seems in other installtion, it will have the HR module by default?

Also, what is the link for normal user to login? i supposedly think the http://my-ip/login is for backend(administrator?) 
Thank you

**Comment by jotamartos** [comment]
Hi @anthonylkm0613,

We take the files from the upstream project and configure the application for you to use it. If you want a specific module, please verify how to install it, if it's not installed it's because it is not included by default with the source code of the app. 

Regarding the login page, please take a look at its documentation. It is out of the scope of this forum.
