### ISSUE TITLE
Could you package jellyfin server pls?

### ISSUE THREAD

**Issue by kdamsmt** [bitnami/vms#936]
### Describe your suggestion as much as you can

Could you please package open source media server https://jellyfin.org/ please?

**Comment by jotamartos** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the ‘on-hold’ label.

**Comment by robert1997b** [comment]
Install necessary development tools and libraries. Ensure you have a suitable version of .NET SDK since Jellyfin is built with .NET. Clone the Jellyfin repository from GitHub to your local machine. Navigate to the cloned repository directory. Use the .NET CLI to build the project: dotnet build. After a successful build, you can create a package using dotnet pack which will compile the code and package it into a NuGet package.

**Comment by esther598** [comment]
Hello,
Certainly! Jellyfin is a volunteer-built media solution that allows you to manage and stream your media from your own server. Here are the key features:

Media Types:
Movies: Easily browse your movie collection with beautiful artwork.
TV Shows: Automatically sorted by season for binge-watching.
Music: Listen to artists and playlists at home or on the go.
Live TV & DVR: Watch TV and set automatic recordings.
Books: Read books, comics, and magazines.
Photos: Organize and share memories with friends and family.
SyncPlay: Remotely enjoy movie nights with friends.
Platform Support: Jellyfin is available on various platforms, including:
Web
Desktop
Android
Apple
Amazon
Roku
Kodi …and more!
Free Software:
Licensed under the GNU GPL, Jellyfin is free to use, modify, and distribute.
It’s community-built, relying on contributions from volunteers.
No hidden fees—download and use it without cost. [Official Website](https://www.floridabluefl.com)

Privacy-Focused:
No tracking or central servers collecting your data.
Your media library remains private.
Best Regards
esther598

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid-term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
