### ISSUE TITLE
Mariadb not start

### ISSUE THREAD

**Issue by Juulian74** [bitnami/vms#937]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3610a695-a797-9382-6f77-5c88cc0b69e6

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Processes: Found possible issues
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ✓ Wordpress: No issues found
 

 
[Processes]

One or more component's processes are not running:
```
mariadb not running
```
You can try to restart the process with the following command:
Press [Enter] to continue:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1681 455 68 8 1157 1035 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

Press [Enter] to continue:
https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Tue May 23 20:53:38.413781 2023] [core:error] [pid 243536:tid 140694882387712] 
[client **ip_address**:60248] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
 [Wed May 24 00:43:25.771929 2023] [core:error] [pid 243536:tid 140695167739648] 
[client **ip_address**:46836] AH10244: invalid URI path 
(/../../mnt/mtd/Config/Account1)
 [Wed May 24 02:05:28.390492 2023] [core:error] [pid 243536:tid 140694991492864] 
[client **ip_address**:41952] AH10244: invalid URI path 
(/../../mnt/mtd/Config/Account2)
Press [Enter] to continue:

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I cant resolve with bndiagnostic

### Describe your issue as much as you can

I try to start mariadb, with multiple forms, and not start. additional when i try to restart the service, i get this error
Job for mariadb.service failed because the control process exited with error code.
See "systemctl status mariadb.service" and "journalctl -xe" for details.

**Comment by mdhont** [comment]
It seems the machine is running low on resources, which is causing MariaDB to crash. I recommend upgrading it to a more powerful one.

**Comment by Juulian74** [comment]
i incrase the resources but now i get this error, in apache and mariadb, i cannot start

juligrippo@wordpress-otr-vm:~$ sudo /opt/bitnami/ctlscript.sh stop apache
Failed to stop apache: [apache] Other action already in progress -- please try again later
juligrippo@wordpress-otr-vm:~$ sudo /opt/bitnami/ctlscript.sh stop mariadb
Failed to stop mariadb: [mariadb] Other action already in progress -- please try again later

**Comment by mdhont** [comment]
Can you run the bndiagnostic-tool again?

**Comment by Juulian74** [comment]
===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.
 
    ? Processes: Found possible issues
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ✓ Wordpress: No issues found
 

 
[Processes]

One or more component's processes are not running:
```
mariadb not running
```
You can try to restart the process with the following command:
Press [Enter] to continue:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Some files don't have the expected permissions. Please check the following 
guide:
 
https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/


[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu May 25 08:36:20.273667 2023] [core:error] [pid 377822:tid 140298076100352] 
Press [Enter] to continue:
[client **ip_address**:36016] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
 [Fri May 26 01:01:49.650165 2023] [authz_core:error] [pid 1945:tid 
139984568796928] [client **ip_address**:49980] AH01630: client denied by server 
configuration: /opt/bitnami/phpmyadmin/index.php
 [Fri May 26 04:28:49.513799 2023] [core:error] [pid 2610:tid 139984468084480] 
[client **ip_address**:58992] AH10244: invalid URI path 
(/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)

```
Please check the following guide to troubleshoot server issues:
 
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded
```
Please check the configuration.
 

Press [Enter] to continue:
===== End of bndiagnostic tool output =====

                                    
Press [Enter] to continue:
The diagnostic bundle was uploaded successfully to the Bitnami servers. Please copy the following code:

0f37c895-64c9-a15f-d246-b18701ff2ab6

**Comment by mdhont** [comment]
Could you check the syntax error on line 112 of /opt/bitnami/apache2/conf/httpd.conf: 
module log_config_module is built-in and can't be loaded

I suggest commenting out the line:

    # LoadModule log_config_module modules/mod_log_config.so

And restart apache:

   /opt/bitnami/ctlscript.sh restart apache

**Comment by mdhont** [comment]
Could you check the  `/opt/bitnami/mariadb/logs/mysqld.log` for any errors?

**Comment by Juulian74** [comment]
i try to acces to the log, but i dont found anything, then i see if i have permissions  and i got it, but i get there is 0bytes in the logs

juligrippo@wordpress-otr-vm:~$ ls -l /opt/bitnami/mariadb/logs/mysqld.log
-rwxrwxrwx 1 mysql mysql 0 May 28 00:00 /opt/bitnami/mariadb/logs/mysqld.log

**Comment by Juulian74** [comment]
juligrippo@wordpress-otr-vm:~$ sudo /opt/bitnami/mariadb/bin/mariadbd-safe
Warning: World-writable config file '/opt/bitnami/mariadb/conf/my.cnf' is ignored
Warning: World-writable config file '/opt/bitnami/mariadb/conf/my.cnf' is ignored
230602 18:58:50 mysqld_safe Logging to '/opt/bitnami/mariadb/data/wordpress-otr-vm.err'.
230602 18:58:50 mysqld_safe Starting mariadbd daemon with databases from /opt/bitnami/mariadb/data

juligrippo@wordpress-otr-vm:~$ sudo /opt/bitnami/ctlscript.sh status
apache already running
mariadb not running
php-fpm already running

**Comment by mdhont** [comment]
It seems to work correctly. Could you try to start it?

    /opt/bitnami/ctlscript.sh start mariadb

Also please note that the apache configuration still has errors:

```
apache2: Syntax error on line 120 of /opt/bitnami/apache2/conf/httpd.conf: 
module version_module is built-in and can't be loaded
```

**Comment by Juulian74** [comment]
i reinstall all wordpress

**Comment by Yasin-Ali-Cpuflat** [comment]
> It seems to work correctly. Could you try to start it?
> 
> ```
> /opt/bitnami/ctlscript.sh start mariadb
> ```
> 
> Also please note that the apache configuration still has errors:
> 
> ```
> apache2: Syntax error on line 120 of /opt/bitnami/apache2/conf/httpd.conf: 
> module version_module is built-in and can't be loaded
> ```

how to fix apache i have the same problem

**Comment by mdhont** [comment]
@Yasin-Ali-Cpuflat, could you open a new issue?
