### ISSUE TITLE
[Wordpress] How to install a non-Let's Encrypt certificate

### ISSUE THREAD

**Issue by JacquesGrove1** [bitnami/vms#938]
### Describe your issue as much as you can

AWS Bitnami Wordpress stack on Lightsail

My customer has purchased a full certificate as they do not like the 3 month expiry on LE certificates.  I need the paths where the .crt and .pem should be stored, and the location of the vhosts file where I add the paths to the certificates, as this deviates from standard Debian paths in this stack.  Any help or pointers would be appreciated.  

Regards

Jacques

**Comment by jotamartos** [comment]
You can find all the information here

https://docs.bitnami.com/general/apps/wordpress/administration/enable-https-ssl-apache/

Please ensure that you update the SSLCertificate lines with the names of the certificates you create in the /opt/bitnami/apache/conf/bitnami/certs/ folder. You will need to edit the /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf and /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf files and restart Apache for the changes to take effect.
