### ISSUE TITLE
[virtual machines] Easier way to rebuild vm images?

### ISSUE THREAD

**Issue by v1nsai** [bitnami/vms#939]
I've been looking at how to rebuild a bitnami vm image (wordpress, specifically) and though I haven't found a repo specifically for rebuilding the vm appliances, I do see that the minideb code is available.  Is there a better way to rebuild the wordpress image than to chroot into the extracted filesystem after building minideb, installing packages and copying over /etc/cloud files and the scripts they reference in other directories from a running bitnami/wordpress instance?

If it helps, the reason I'm trying to do this is because I'm using openstack and I can't get cloud-init to run any of the user_data I'm injecting to run.

Thanks for any insight, I know openstack isn't officially supported but if there's some specific changes I have to make for cloud-init to work I'd be happy to push those changes upstream if you're interested

**Comment by mdhont** [comment]
Unfortunately rebuilding a Bitnami VM image is currently not supported.

**Comment by mdhont** [comment]
We've investigated a bit further, its possible to do if you specify SKIP_FIRST_BOOT=true in the userdata. After that you can make the necessary changes in the VM, and finally convert it to VMDK or OVA format again. It should also be possible to automate that process using Packer.
