### ISSUE TITLE
[Wordpress Multisite] Internet URL resolving to Internet_URL/Local_Hostname.Local_Domain

### ISSUE THREAD

**Issue by chatmandu-uk** [bitnami/vms#94]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

50e6b192-1d1c-8c9b-a87f-b7539c1b3948

### bndiagnostic output

![image_2022-07-09_004649541](https://user-images.githubusercontent.com/107044828/178082705-70f9f7c4-f291-4b21-8762-cb4aea4512e3.png)

### bndiagnostic was not useful. Could you please tell us why?

It says port 443 isn't accessible, but it is because it worked fine for a single site and my multisite domain is being added to to the internet url.

### Describe your issue as much as you can

I have successfully installed Bitnami Multisite on my internal network.

Everything is working correctly in terms of creating new subdomain sites. 

I am currently using the free 'noip' service to map an internet domain name to my home network. Everything worked correctly for a single site install that I previously created. That site was created using the default IP address of 192.168.0.128 and the internet url mapped to the website without this /subfolder issue. 

When I attempt to connect to the wordpress multisite via the internet URL, my browser is redirected to: 

https://internet_url/local_hostname.local_domain 

The website fails to load and I receive a 'too many redirects' error.

Do I need to edit the Wordpress config to resolve this issue or is it something that needs to be resolved on the server or home router?

I have installed Webmin and also Squid because I thought it might be something that needs to be resolved via a reverse proxy, but I've no idea how to configure Squid to get this fixed. 

Is this something that other people have encountered before? Any idea where to start my troubleshooting steps? 

Thanks,

**Comment by mdhont** [comment]
You need to access the WordPress site using a xip domain: 

    https://IP_ADDRESS.xip.io

More details here:

https://docs.bitnami.com/installer/apps/wordpress-multisite/administration/accessing-by-ip/
