### ISSUE TITLE
[WordPress with NGINX and SSL] Install lets encrypt ssl if Bitnami application host is behind CDN

### ISSUE THREAD

**Issue by jack2iutre** [bitnami/vms#940]
### Describe your issue as much as you can

Hi there,

I'm setting up my Bitnami-based WordPress site on AWS EC2 instance, behind CloudFront, I follow the "alternative approach" guide here, 
https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

It says:
"NOTE: Before proceeding with this step, ensure that your domain name points to the public IP address of the Bitnami application host. If the Bitnami application host is **behind a load balancer or CDN**, the commands below **require additional parameters**, which can be provided by [the Bitnami support team](https://github.com/bitnami/vms/) on request."

Could you please help me provide those **additional parameters**?

Thank you very much!
Jack

**Comment by jotamartos** [comment]
The lego tool supports [many different DNS providers](https://github.com/go-acme/lego#dns-providers), you can take a look at its documentation to know how you can configure the SSL certs and you can also take a look at [already existing support tickets in its forum](https://community.letsencrypt.org/t/lightsail-cloudfront-ssl-certificate-origin-policy-issues/135260) to know how to proceed

**Comment by jack2iutre** [comment]
> 乐高工具支持[许多不同的 DNS 提供商](https://github.com/go-acme/lego#dns-providers)，您可以查看其文档以了解如何配置 SSL 证书，还可以查看[其论坛中现有的支持票证](https://community.letsencrypt.org/t/lightsail-cloudfront-ssl-certificate-origin-policy-issues/135260)以了解如何进行

I'll try it.
