### ISSUE TITLE
How to download Bitnami Wordpress 5.3.2-4 for Windows

### ISSUE THREAD

**Issue by mwakelam** [bitnami/vms#941]
### Describe your issue as much as you can

Need to upgrade our Bitnami Wordpress stack but cannot find where to download these .exe's.

Can I be provided with a link or the download itself, need version 5.3.2-4

**Comment by mwakelam** [comment]
Any updates on this?

**Comment by afresneda1985** [comment]
Im same "problem" its posible not be more for windows?

I need the last version ....in the web its 6.2.2 Version.

Thanks!

**Comment by jotamartos** [comment]
As you know, we removed support for native installers last year. We only kept the last installers we release but we do not update them anymore. You can download 5.3.2 using this link 

https://downloads.bitnami.com/files/stacks/wordpress/5.3.2-3/bitnami-wordpress-5.3.2-3-windows-x64-installer.exe

If you want to use an updated version, please use any of the Bitnami containers, charts or VMs

**Comment by mwakelam** [comment]
Is there version 5.3.2.-4 ?

**Comment by jotamartos** [comment]
No, that version was not released

**Comment by mwakelam** [comment]
What about version 5.4.0?

**Comment by jotamartos** [comment]
https://downloads.bitnami.com/files/stacks/wordpress/5.4-0/bitnami-wordpress-5.4-0-windows-x64-installer.exe

**Comment by mwakelam** [comment]
Thank you very much

**Comment by afresneda1985** [comment]
> As you know, we removed support for native installers last year. We only kept the last installers we release but we do not update them anymore. You can download 5.3.2 using this link
> 
> https://downloads.bitnami.com/files/stacks/wordpress/5.3.2-3/bitnami-wordpress-5.3.2-3-windows-x64-installer.exe
> 
> If you want to use an updated version, please use any of the Bitnami containers, charts or VMs

Thanks!!! i think its more easy try to it debian image and more sure, its the same than *.exe solution....

Regards and thanks!

**Comment by deedcod** [comment]
this linke app [](https://bitnami-wordpress-stack.apponic.com/)
