### ISSUE TITLE
[Ghost] How I can setup my Bitnami Ghost CMS with AWS Cloudfront?  

### ISSUE THREAD

**Issue by Harsh-2002** [bitnami/vms#942]
### Describe your issue as much as you can

My blog https://firstfinger.in/  is running on AWS EC2 instance and i want to setup Cloudfront with ec2. I tried to setup but got error I tried to fix it ... and still after 1 week I can't. There are some issue with Caching Policy and header I don't know. Please help me to Set it up. If possible share detailed guides. Thanks

**Comment by jotamartos** [comment]
Hi @Harsh-2002,

That's a specific question about how to configure the application and Cloudfront and it's out of the scope of this forum. I suggest you take a look at its documentation and forums to know more about that.

**Comment by Harsh-2002** [comment]
I tried to understand & implement lot of guides but still i don't know why is this not working.

**Comment by jotamartos** [comment]
I'm sorry but as I mentioned above, this question is out of the scope of this forum. We will keep the ticket open for some time just in case any Bitnami user implemented the same changes and provides some information.
