### ISSUE TITLE
WordPress Certified by Bitnami and Automattic 6.2.0-14] <PHP-FMP auto script>

### ISSUE THREAD

**Issue by KingMilli75** [bitnami/vms#943]
### Describe your issue as much as you can

Dear,

we checked the guide here : https://docs.bitnami.com/google/apps/espocrm/configuration/configure-phpfpm-processes/

when we cat the file  
cat /opt/bitnami/php/etc/php-fpm.d/www.conf 
results in the following:
include=/opt/bitnami/php/etc/environment.conf
include=/opt/bitnami/php/etc/common.conf
pm=dynamic
listen=/opt/bitnami/php/var/run/www.sock
listen.allowed_clients=127.0.0.1

; Memory settings adapted to the machine
; The file below will be overwritten after restarts
include=/opt/bitnami/php/etc/memory.conf

then we check the memory.conf file and see the following

; Bitnami memory configuration for PHP-FPM
;
; Note: This will be modified on server size changes

pm.max_children=200
pm.start_servers=130
pm.min_spare_servers=130
pm.max_spare_servers=150
pm.max_requests=5000

however if the file changes according to the config of the server then we are lost. As we have a 16 GB RAM, 4 vCPUs server. 
So if we understand it all correct, pm.start_servers=pm.min_spare_servers should be the the cores multiplied by 4 so value should be 16?  So min server should be 8 and max should be 16?   How does autoconfig come to 130?

now to calculate the children i need to know how much the process takes if i am correct.  However when i take a look at the value set i am not sure where this number come from. Because when i run:  ps --no-headers -o "rss,cmd" -C php-fpm8.1.16 | awk '{ sum+=$1 } END { printf ("%d%s\n
", sum/NR/1024,"M") }'   the value printed is a minus value -2147483647M  Now how to know and to calculate the children?

And then in the guide it says to add the file but as you can see it refers to something else. Any help would be appreciated maybe i typed a command wrong to cat it out or simply the numbers do not make sense to me now. What would the values be which we should use...?

cheers

**Comment by KingMilli75** [comment]
just to add why i started this: [24-May-2023 01:59:21] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_s
pare_servers), spawning 16 children, there are 105 idle, and 165 total children

**Comment by mdhont** [comment]
The memory.conf file is automatically updated upon server restart, providing values somewhat higher than the estimate of memory requirements for a typical WordPress installation. However, it may not be ideal for all scenarios. You have the option to exclude the memory.conf file and utilize your own custom configuration.
