### ISSUE TITLE
[bncert-tool] "Please enter a valid email" returned for valid email addresses

### ISSUE THREAD

**Issue by richardwfrancis** [bitnami/vms#945]
bncert-1.1.1-linux-x64.run

When running through the setup process for a new Let's Encrypt certificate (or a renewal), I get to the final stage of accepting the subscriber agreement and entering the correct email address to associate with the certificate, but on entering a valid email address I am encountering a "Please enter a valid email" error as follows:

```
----------------------------------------------------------------------------
Create a free HTTPS certificate with Let's Encrypt

Please provide a valid e-mail address for which to associate your Let's Encrypt 
certificate.

Domain list: sampledomain.com

Server name: sampledomain.com

E-mail address []: sample@email.com

The Let's Encrypt Subscriber Agreement can be found at:

https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf

Do you agree to the Let's Encrypt Subscriber Agreement? [Y/n]: Y


Warning: Please enter a valid email
Press [Enter] to continue:

```

This then sends me back to the prompt to accept the agreement again and then on to asking for the email address. 

I have tried an @ersnet.org and an @dal.ca address (both live and valid addresses) but the only one I can get it to accept is my personal @gmail.com address. Any ideas why?

Many thanks for your help in advance

**Comment by mdhont** [comment]
Here is the code that is executed"

https://github.com/bitnami/bncert/blob/0ef40f30bb77e18ccffd878802d452aac9769e80/project/bncert-letsencrypt-mode.xml#LL74C46-L74C75

It checks for the following regex:

    ^[a-z0-9._\-]+@[a-z0-9._\-]+$

Could you check if your email matches it?

https://regex101.com/r/1nOveb/1

**Comment by richardwfrancis** [comment]
Thanks for getting back to me. It's the case of the `Firstname.Lastname@...` they distribute their addresses as that doesn't fit the regex. Using the following regex worked but I'll make sure the address used is all lower case:

```
^[A-Za-z0-9._\-]+@[a-z0-9._\-]+$
```
