### ISSUE TITLE
Ubuntu distro application package support

### ISSUE THREAD

**Issue by ghost** [bitnami/vms#946]
### Describe your suggestion as much as you can

aside from debian, is there a support for ubuntu distro application package?

**Comment by gongomgra** [comment]
Hi @jepwiz,

Unfortunately, we do not offer our free catalog of cloud images on top of any operating system other than Debian 11. Alternatively, you can get Debian 10 based OVAs from the [VMware Application Catalog](https://tanzu.vmware.com/application-catalog).
