### ISSUE TITLE
[Bitnami Drupal 10 VM VirtualBox] Comp[oser module install failure

### ISSUE THREAD

**Issue by bv1000** [bitnami/vms#947]
### Describe your issue as much as you can

Hi,

I have successfully installed a few drupal 10 modules. However, now I am only getting the following error(s)

![image](https://github.com/bitnami/vms/assets/44737824/bcb90bfe-da3c-4163-8083-954d5768dc25)

In case the image above does not work it says  the module could not be found in any version due to 
1) a typo
2) package not available in stable enough version according to your minimum stability setting

The composer command was taken from the module page on drupal.org
composer require 'Drupal/inline_entity_form:^1.0@RC'

The same thing happens when I try other modules.

I noticed also when I looked at the VM image via 7zip that the composer.json file has nothing in it ( even after 'require' installed some other modules successfully)

I appreciate any help!

Thanks very much.

**Comment by mdhont** [comment]
Could you tell me the exact steps to reproduce the issue?

**Comment by bv1000** [comment]
Good Morning Michiel,

 

Thanks for your reply.

 

I am trying to extend a drupal 10 site via adding modules.

 

The site is running via Bitnami and is on Oracle VM VirtualBox.

 

I have successfully installed a couple of modules for instance Admin Toolbar.

 

I am now unable to install a the last 3 modules I tried.

 

I tried to instal as usual with composer.

 

For instance – 

 

$ composer requires ***@***.***’

 

Error comes up – 

 

Your requirements could not be resolved to an installable set of packages



 

Same result for metatag module for example.



 

I have tried  clearing the cache

 

I appreciate any help you can provide!

 

All the best

 

Brendan

**Comment by mdhont** [comment]
The error seems due to incompatible package version requirements. As the issue is more related to the application itself I recommend asking in a dedicated Drupal forum.
