### ISSUE TITLE
[Mautic] cant ssh into ec2 and start and stop server after i had to backup from a an ec2 snapshot/volume

### ISSUE THREAD

**Issue by 3lonious** [bitnami/vms#948]
### Name and Version

bitnami/mautic aws

### What architecture are you using?

None

### What steps will reproduce the bug?

how do i ssh in and get the ec2 working again?

### Are you using any custom parameters or values?

how do i ssh in and get the ec2 working again?

### What is the expected behavior?

how do i ssh in and get the ec2 working again?

### What do you see instead?

how do i ssh in and get the ec2 working again?

### Additional information

how do i ssh in and get the ec2 working again?

**Comment by jotamartos** [comment]
First of all, try to restart the server using the AWS console and check if the services start running after that. If not, try to ssh the instance and run the start command 

```
sudo /opt/bitnami/ctlscript.sh start
```

Can you access your app now?
