### ISSUE TITLE
[Wordpress Multi-Tier GCP ] Error establishing database connection & sudo: /opt/bitnami/ctlscript.sh: command not found

### ISSUE THREAD

**Issue by Uta2** [bitnami/vms#95]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

849

### bndiagnostic was not useful. Could you please tell us why?

unable to execute

### Describe your issue as much as you can

I've been having some challenges working on the multi-tier stack. 

When deployed, there is a warning msg as below:

_`This deployment has resources from the Runtime Configurator service, which is in Beta. There is no planned date for moving this feature into General Availability (GA). Examples of runtimeconfig types used: runtimeconfig.v1beta1.config, runtimeconfig.v1beta1.waiter`_ 

Despite the warning msg, the instances are launched successfully. 

After launched, in node-0, I imported media and products using csv. The files are successfully imported. However, after a while, it will run into `Error establishing database connection`. `sudo: /opt/bitnami/ctlscript.sh: command not found`.  No script has been deleted. The imported csv should be fine since it works alright in a single tier environment.  Rebooting doesn't help. 

added `define ('WP_ALLOW_REPAIR', true);` and it produces the following: 

`Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'bn_wordpress'@'192.168.0.22' (using password: YES) in /opt/bitnami/wordpress/wp-includes/wp-db.php on line 1753`

Thanks

**Comment by Uta2** [comment]
` sudo ls -la /opt/bitnami/`

**Output**
```
total 96
drwxr-xr-x 21 root    root    4096 Jul  8 10:43 .
drwxr-xr-x  3 root    root    4096 Jul  1 08:32 ..
drwxr-xr-x 16 root    root    4096 Jun  8 13:35 apache
lrwxrwxrwx  1 root    root       6 Jul  1 08:38 apache2 -> apache
-rw-r--r--  1 root    root    1360 Jul  1 07:52 .bitnami_components.json
drwxr-xr-x  3 root    root    4096 Jun 30 18:53 bncert
lrwxrwxrwx  1 root    root      46 Jun 30 18:38 bncert-tool -> /opt/bitnami/bncert/bncert-0.8.0-linux-x64.run
drwxr-xr-x  3 root    root    4096 May  5 11:03 bndiagnostic
lrwxrwxrwx  1 root    root      59 May  5 10:55 bndiagnostic-tool -> /opt/bitnami/bndiagnostic/bndiagnostic-0.9.17-linux-x64.run
drwxr-xr-x  6 root    root    4096 May  5 11:23 brotli
drwxr-xr-x  6 root    root    4096 Jun  8 11:59 common
-rw-r--r--  1 root    root       4 Jul  8 10:43 .firstboot.status
drwxr-xr-x  4 root    root    4096 May 19 21:19 gonit
drwxr-xr-x  3 root    root    4096 Jun 29 10:01 licenses
drwxr-xr-x 12 root    root    4096 Jul  1 08:38 mariadb
drwxr-xr-x  6 root    root    4096 Jul  1 08:38 mysql
drwxr-xr-x  5 root    root    4096 Jun 29 10:01 nami
drwxr-xr-x  4 root    root    4096 Jun  8 05:51 peclapcu
drwxr-xr-x 12 root    root    4096 Jun  8 05:51 php
drwxrwxr-x 14 bitnami daemon  4096 Jul  1 08:38 phpmyadmin
-rw-r--r--  1 root    root      86 Jul  8 10:43 properties.ini
drwxr-xr-x 12 root    root    4096 Jul  1 07:52 scripts
drwxr-xr-x  2 bitnami bitnami 4096 Jul  9 06:43 stats
drwxr-xr-x  3 root    root    4096 Jul  1 08:38 var
drwxr-xr-x 10 root    root    4096 Jul  1 07:52 varnish
drwxrwxr-x  6 bitnami daemon  4096 Jul  9 06:42 wordpress
drwxr-xr-x  7 daemon  daemon  4096 Jul  1 08:38 wp-cli
```

**Comment by Uta2** [comment]
I just realised that multi-tier has to use `sudo service bitnami` instead of `/opt/bitnami/ctlscript.sh`

The `error establishing database connection` happens after restarting node-1. The credential change after shutting down and re-starting the instance? How can I re-establish the database connection after a reboot or ensure the credentials stay the same?

Thanks!

**Comment by jotamartos** [comment]
Hi @Uta2,

> When deployed, there is a warning msg as below:
> 
> This deployment has resources from the Runtime Configurator service, which is in Beta. There is no planned date for moving this feature into General Availability (GA). Examples of runtimeconfig types used: runtimeconfig.v1beta1.config, runtimeconfig.v1beta1.waiter

We are aware of that warning and are working on it. You can continue using the solution without problems.

> added define ('WP_ALLOW_REPAIR', true); and it produces the following:
> 
> Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'bn_wordpress'@'192.168.0.22' (using password: YES) in /opt/bitnami/wordpress/wp-includes/wp-db.php on line 1753

Did you modify the database credentials in the /opt/bitnami/wordpress/wp-config.php file? You can try accessing the database using the WordPress' credentials 

```
mysql -u bn_wordpress -p bitnami_wordpress
```

> The error establishing database connection happens after restarting node-1. The credential change after shutting down and re-starting the instance? How can I re-establish the database connection after a reboot or ensure the credentials stay the same?

Credentials don't change after a reboot. You should be able to access the database using root or bn_wordpress if the database is running.

**Comment by Uta2** [comment]
Thanks for the reply. 

I tested with a new deployment. I stop and restart the database instance node-1 and got this error

`ERROR 2002 (HY000): Can't connect to local server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)`

On the front end, it says `error establishing database connection`

**Comment by jotamartos** [comment]
>ERROR 2002 (HY000): Can't connect to local server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)

Are you trying to access the database from node-1 or node-0? If you are running the `mysql` command from node-0, you also need to specify the host where the database is running.

```
mysql -u bn_wordpress -h DATABASE_HOST_HERE -p bitnami_wordpress
```

>Note: The database host is configured in the wp-config.php file.

**Comment by ajlgk** [comment]
Hello.

Im not sure if im doing this the correct way, but this issue should be reopened.

We needed to restart the instances, multi-tier solution creates node-0 and node-1, i restarted those instance from the gcp panel and for some reason the access to the database breaks down.

Bitnami documentation regarding this issue its non-existing

I could provide more information on this issue if i see someone at least replies.

Thanks!

**Comment by jotamartos** [comment]
Hi @ajlgk,

Please create a new ticket instead of reusing this old one and provide all the information you have. This way, we will maintain this support forum clean and others can find the information easily. 

Thanks
