### ISSUE TITLE
[OpenProject] SMTP-AUTH requested but missing secret phrase

### ISSUE THREAD

**Issue by yuki-kawai2023** [bitnami/vms#950]
### Describe your issue as much as you can

**Platform**
  AWS(tokyo region)

  AMI-ID: ami-059877cf0c983858a
  bitnami-openproject-12.5.4-1-r02-linux-debian-11-x86_64-hvm-ebs-nami-b687dffb-f799-490a-bea9-e68695fead34

**Describe  issue**
  GUI: Administration > Users > select user > Send invitation
  The following message appears on the screen:
    An invitation has been sent to [user mail address].

  But I get an error message in the log and the email never arrives
  /opt/bitnami/openproject/log/production.log

E, [2023-05-30T19:04:21.067407 #1998] ERROR -- : [ActiveJob] [Mails::MailerJob] [e6a1a337-2b6d-4e28-bcc3-223b53b6a3e9] Error performing Mails::MailerJob (Job ID: e6a1a337-2b6d-4e28-bcc3-223b53b6a3e9) from DelayedJob(mailers) in 39.61ms: ArgumentError (SMTP-AUTH requested but missing secret phrase):

  However, with the following operation, the mail arrives normally
  GUI: Administration > Emails and notification > Email notifications > Send a test mail
  The following message appears on the screen:
    An email was sent to [Emission email address]

  Email settings are as follows
    /opt/bitnami/openproject/config/configuration.yml

  default:
    log_level: info
    email_delivery_method: :smtp
    smtp_enable_starttls_auto: true
    smtp_address: "email-smtp.ap-northeast-1.amazonaws.com"
    smtp_port: 587
    smtp_domain: "mydomain.jp"
    smtp_authentication: :plain
    smtp_user_name: "AWS SES user"
    smtp_password: "AWS SES password"

Am I missing a setting somewhere?

**Comment by jotamartos** [comment]
Hi @yuki-kawai2023,

That's a specific issue with the application so I suggest you take a look at the app's official documentation and its forums. You can also find some related tickets in StackOverflow that may be of help to you.

**Comment by yuki-kawai2023** [comment]
app's forums had the following note:
Please note that Bitnami offers packages for OpenProject that are unrelated to our offers.
We do not know their specific packages and will not be able to provide support for them.

Could you tell me how to pass variables from bitnami's startup script to OpenProject?

**Comment by yuki-kawai2023** [comment]
I don't know if this is the correct answer, but I wrote it because it started to work.

:/opt/bitnami/scripts/openproject-env.sh
```
export OPENPROJECT_SMTP_HOST="email-smtp.ap-northeast-1.amazonaws.com"
export OPENPROJECT_SMTP_PORT_NUMBER=587
export OPENPROJECT_SMTP_USER="SES USER"
export OPENPROJECT_SMTP_PASSWORD="SES PASSWORD"
export SMTP_HOST="email-smtp.ap-northeast-1.amazonaws.com"
export SMTP_PORT=587
export SMTP_USER="SES USER"
export SMTP_PASSWORD="SES PASSWORD"
```

**Comment by jotamartos** [comment]
That's only valid if you are using a container to deploy the solution. In your case, you need to update the app's configuration with the SMTP configuration

https://docs.bitnami.com/general/apps/openproject/configuration/configure-smtp/
