### ISSUE TITLE
[Bitnami Launchpad] Implications of deprecation and shutdown

### ISSUE THREAD

**Issue by harrybou** [bitnami/vms#953]
### Describe your issue as much as you can

Have just received notice of impending shutdown (I have set up since the original notice, so was not aware of the situation) but not sure what it might mean for me.  

I have tried following the instructions for adding the ssh key to Google Cloud VM, but it keeps saying it is not a valid key.  The format is ssh-rsa AAAA..... bitnami which seems to comply with the format given by Google and the instruction set.  The key is the one that is used by Filezilla to access my files.  Is that the one, or am I on the completely wrong track?

My other question then is, will I be still able to use Filezilla for file access if I cannot get GCP to accept the/any other key?
As an aside, I doubt that I have used Bitnami launchpad since I set up the GCP account.

Also, I am using Bitnami LAMP

**Comment by gongomgra** [comment]
Hi @harrybou,

Thanks for using Bitnami. I understand you are trying to add a new SSH key to your server from the GCP console, is that correct? If so, please check the SSH key format, as FileZilla usually generates the SSH keys in a non-valid format (you will need to include it as a single line key in GCP).

In case you are trying to install a new SSH from an already opened SSH session, you can simply add the new SSH public key at the end of the `/home/bitnami/.ssh/authorized_keys` file.
