### ISSUE TITLE
[bitnami/wordpress-multisite] Directory/File default permissions

### ISSUE THREAD

**Issue by jason5591** [bitnami/vms#957]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

n/a

### bndiagnostic was not useful. Could you please tell us why?

Not related

### Describe your issue as much as you can

Our site recently had malware installed on it. We completely made a new lightsail install and only moved the DB and image uploads over. To be safe, we installed security software. 

It is providing the following output and curious if the default install is not secure/if we should adjust to these permissions?

**Permissions for files and directories from the list are unsafe. We recommend change it to 755 for each directory and 644 for each file from the list.**

Path	Permission
/index.php	664
/wp-admin	775
/wp-includes	775
/wp-content	775
/wp-content/themes	775
/wp-content/plugins	775
/wp-content/uploads	775

**Comment by gongomgra** [comment]
Hi @jason5591,

Thanks for using Bitnami. By default, our images run the Apache service with the special `daemon` system user, while sysadmins connect via SSH to the server as the `bitnami` user, so most of the files have the `bitnami:daemon` ownership. That's also why most of the directories have the `775` permissions, so both the system admin and Apache have fully access to them (for example when upgrading plugins from the WordPress admin panel). 

I'm not sure about the `index.php` file, but it makes sense to me setting it as `644`, unless any WordPress feature fails for it. I think you could also ask this question in the official WordPress forums, where users with more experience will be able to answer.

https://wordpress.org/support/forums/

Hope it helps!
