### ISSUE TITLE
[Bitnami WordPress] AWS WordPress Production-Ready Certified by Bitnami and Automattic -- going out of support

### ISSUE THREAD

**Issue by alidgett** [bitnami/vms#958]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

N/A

### bndiagnostic output

N/A

### bndiagnostic was not useful. Could you please tell us why?

Not related

### Describe your issue as much as you can

Hello,

We are currently using the 'WordPress Production-Ready Certified by Bitnami and Automattic' solution in AWS. Recently VM notified that this would no longer be available after May 2023. Since we are current subscribers in AWS the notification indicates we can continue use beyond that date without support. 
  
  Is this just for the older AMIs in the AWS Market Place for the above or is it a full discontinuation?
  Are there any comparable AMIs that could be leveraged to replace the above in the existing stack without the need for a full solution replacement?
  
  Any other info or guidance in this respect would be very helpful.
  
  Thank you,
  Andrew

**Comment by gongomgra** [comment]
Hi @alidgett,

Thanks for your message. We dropped support for the entire solution, not only for old images. You can continue using the current one, but it won't receive any update from our side. As an alternative, you can use our Helm chart

https://github.com/bitnami/charts/tree/main/bitnami/wordpress

Hope it helps!
