### ISSUE TITLE
Puppeteer on AWS EC2 Bitnami

### ISSUE THREAD

**Issue by RitvikSardana** [bitnami/vms#96]
### Describe your issue as much as you can

The puppeteer script to login into a website and scrape some data, is working perfectly fine on my PC, but it does not work on the AWS EC2 bitnami instance. The script is able to login into the website but unable to scrape data when running in the instance.

**Comment by jotamartos** [comment]
We are already talking about this issue in this other thread. 

https://github.com/bitnami/vms/issues/49

Let's continue the conversation there.
