### ISSUE TITLE
bitnami wordpress wp-admin permission issue

### ISSUE THREAD

**Issue by queenian** [bitnami/vms#960]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

it failed to upload the bndiagnostic file

### bndiagnostic output

bitnami-wordpress-info-20230605-035120-4225.zip

### bndiagnostic was not useful. Could you please tell us why?

can't upload the file

### Describe your issue as much as you can

I can't access to https://nyresidentsalliance.org/wp-admin, I received "You don't have permission to access this resource.". I check the ownership and permission under ./wordpress/htdocs, they look ok to me. I also tried to restore the permission and ownership, but the problem still exists. 
I generated the bndiagnostic file, I can upload the zip file for you to review if you tell me where should I send the dropbox link to

Thanks.

**Comment by gongomgra** [comment]
Hi @queenian,

Thanks for using Bitnami. Can you try running the bndiagnostic tool again in case it can properly upload the data to our servers now? If you continue having errors, please try stopping the Bitnami services before running the bndiagnostic tool again.
