### ISSUE TITLE
[magento] Requesting 2.3.3 virtual machiene and intaller

### ISSUE THREAD

**Issue by SzabKel** [bitnami/vms#962]
### Requesting

Could you please give me download links for a Magento version 2.3.3 virtual machine? If it is possible, for the linux installer as well? Thank you!

https://bitnami.com/stack/magento/virtual-machine

**Comment by gongomgra** [comment]
Hi @SzabKel,

Thanks for using Bitnami. I'm afraid we no longer have available the required files for that version. The oldest version we have available is `2.4.4-6`. You can find the download link below

https://downloads.bitnami.com/files/stacks/magento/2.4.4-6/bitnami-magento-2.4.4-6-linux-debian-11-x86_64-nami.ova

We only have the OVA file to be downloaded, as we [no longer provide local installers](https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html). Hope it helps!
