### ISSUE TITLE
[WordPress] SSL errors after upgrading instance

### ISSUE THREAD

**Issue by KingMilli75** [bitnami/vms#963]
### Describe your issue as much as you can

Hi There,

we upgrade our instance to a bigger instance which of course carries a different IP now. Now we get the SSL errors in the logs where BNcert tool tell us the installed certificate is on another IP address.

Any help how to solve this issue now

**Comment by jotamartos** [comment]
If the IP address changed, you need to update the DNS records to point your domain to the new IP address. Once you do it, everything should work as expected. You can verify that it's correctly configured here

https://www.whatsmydns.net/

**Comment by jotamartos** [comment]
>Only the server does not have this via BNCERT

bncert does not support this scenario. If you had the instance behind cloudfront previously, you probably generated the SSL cert following a different method. 

>To trick the server we used a self signed certificete from your site and this worked actually. Now its still giving some strange SSL error related to this.

I do not know what guide you followed when configuring this for the first time, but you will need to configure everything again. 

>Problem i tries to revoke the BNCERT certificate but it did not want to do it. 

As I just mentioned, bncert doesn't support this scenario so do not know what you did in the past. 

>Even the cron job removed from the server but still it "reads" the certificate. 

If you want Apache to use port 443, you need a certificate (a valid or a self-signed one)

>Is there a way to disable BCcert certificate or to deinstall it or something similar?

If you remove the certificate, you will need to stop Apache from accepting https connections.

**Comment by KingMilli75** [comment]
OK thank you,

we will run the configuration again. We issued the BNCERT on a smaller instance and before we were behind cloudfront and then we issued via cloudfront a SSL certificate it of course runs correctly. 

This is the guide we followed; https://docs.bitnami.com/aws/apps/wordpress/administration/create-ssl-certificate-apache/

made the self signed certificate for apache etc. So we do not use bncert... Now thats clear maybe a idea is to update this on the docs page if your behind cloudfornt do BNcert will not work.. o something similar. We did not know about this part, and upgraded the instance...

**Comment by KingMilli75** [comment]
Thanks a million we will give this a try.

**Comment by KingMilli75** [comment]
![image](https://github.com/bitnami/vms/assets/101454545/1dc9f376-038a-4fa6-9a00-8f91bd83e3db)

hi There 

it says that in the guide now i run the part. Before that i need to revoke the certificate. But it give me bad substitution error.

bitnami@ip-172-26-5-62:~$ certbot revoke --cert-path /etc/letsencrypt/archive/${kupoholik.rs}/cert1.pem
-bash: /etc/letsencrypt/archive/${kupoholik.rs}/cert1.pem: bad substitution

Also running the command 
udo /opt/bitnami/letsencrypt/lego --http --email="email" --domains="kupoholik.rs" --domains="www.kupoholik.rs" --domains="xxxx.cloudfront.net" --path="/opt/bitnami/letsencrypt" 
run

23/06/15 09:00:38 [INFO] [kupoholik.rs, www.kupoholik.rs, d2si0dhe935ngk.cloudfront.net] acme: Obtaining bundle
d SAN certificate
2023/06/15 09:00:39 [INFO] [d2si0dhe935ngk.cloudfront.net] AuthURL: https://acme-v02.api.letsencrypt.org/acme/aut
hz-v3/236992084647
2023/06/15 09:00:39 [INFO] [kupoholik.rs] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/23699208465
7
2023/06/15 09:00:39 [INFO] [www.kupoholik.rs] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2369920
84667
2023/06/15 09:00:39 [INFO] [d2si0dhe935ngk.cloudfront.net] acme: Could not find solver for: tls-alpn-01
2023/06/15 09:00:39 [INFO] [d2si0dhe935ngk.cloudfront.net] acme: use http-01 solver
2023/06/15 09:00:39 [INFO] [kupoholik.rs] acme: Could not find solver for: tls-alpn-01
2023/06/15 09:00:39 [INFO] [kupoholik.rs] acme: use http-01 solver
2023/06/15 09:00:39 [INFO] [www.kupoholik.rs] acme: Could not find solver for: tls-alpn-01
2023/06/15 09:00:39 [INFO] [www.kupoholik.rs] acme: use http-01 solver
2023/06/15 09:00:39 [INFO] [d2si0dhe935ngk.cloudfront.net] acme: Trying to solve HTTP-01
2023/06/15 09:00:44 [INFO] [kupoholik.rs] acme: Trying to solve HTTP-01
2023/06/15 09:00:51 [INFO] [www.kupoholik.rs] acme: Trying to solve HTTP-01
2023/06/15 09:00:57 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/236992084647
2023/06/15 09:00:58 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/236992084657
2023/06/15 09:00:58 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/236992084667
2023/06/15 09:00:58 Could not obtain certificates:
error: one or more domains had a problem:
[d2si0dhe935ngk.cloudfront.net] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 2600:9000:24ce:900
0:12:18b3:4100:93a1: Invalid response from https://d2si0dhe935ngk.cloudfront.net/.well-known/acme-challenge/rXz5Z
_wfWeZLNRK5rDe3Gp22picueKSPRqu34FvpYjw: 502
[kupoholik.rs] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 18.160.143.73: Invalid response fro
m https://kupoholik.rs/.well-known/acme-challenge/40rV5hXWH0ZnHoKTk-gbcMXZP6nZXRaGn0FyEKSPcdM: 502
[www.kupoholik.rs] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 18.160.143.82: Invalid response
 from https://www.kupoholik.rs/.well-known/acme-challenge/H-P4H_FjMBV16429FRC0lpWs3hSkk1a40BPqYOTpLnA: 502

any idea how this can be solved?

**Comment by jotamartos** [comment]
Those domains are behind cloudfront and they can't be validated. Please take a look at the lego/certbot documentation and find how to achieve what you want. You can also ask the developers of the tools to know how to proceed.
