### ISSUE TITLE
[bitnami-redmine-5.0.0-0-windows-x64] how to update Bitnami Redmine 5.0.0 for Windows

### ISSUE THREAD

**Issue by MFurminsky** [bitnami/vms#965]
### Describe your suggestion as much as you can

It's a pity that they stopped making builds for Windows. How to update the application now? I need instructions for updating Redmine for Windows.

**Comment by gongomgra** [comment]
Hi @MFurminsky,

Thanks for using Bitnami. You can continue using the Bitnami Redmine stack in our virtual-machine. You will need to migrate the Redmine data from your local installation to the virtual machine first, following the upgrade steps in our guide, providing you can upgrade between both versions (local and virtual-machine's) without performing additional steps. We recommend you to check official guides about this. 

Once you have migrated to the virtual machine, you can continue with the regular upgrade process from one virtual machine to the new one:

https://docs.bitnami.com/virtual-machine/apps/redmine/administration/upgrade/

Hope it helps!

**Comment by MFurminsky** [comment]
Help update Redmine on the current Windows platform. Changing the platform is quite a cardinal step. However, if it's too hard for you, you can't...

**Comment by gongomgra** [comment]
Hi @MFurminsky,

As mentioned in a previous message, we no longer provide support for the local installers. Please migrate the Redmine information to the virtual-machine and then proceed with the migration/upgrade process from there.
