### ISSUE TITLE
[<Bitnami SuiteCRM>] <Upgrade 7.12 => 8.XX - PHP issue>

### ISSUE THREAD

**Issue by AshAmine** [bitnami/vms#967]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

29725eec-21ea-057f-38bf-c66d9dbe0e42

### bndiagnostic was not useful. Could you please tell us why?

Not Applicable - there is no issue with the current app

### Describe your issue as much as you can

We are attempting to upgrade from Bitnami SuiteCRM 7.12.6 on AWS EC2 to Bitnami SuiteCRM 8.xx. However, we are encountering PHP incompatibility issues when we try to upgrade using the SuiteCRM upgrade Wizard. SuiteCRM 8.xx requires PHP 7.4 or 8.x, whereas SuiteCRM 7.12 is currently using PHP 7.3. We also tried upgrading PHP separately, but it caused SuiteCRM to crash!

Could you please advise on the best approach to address this issue?

**Comment by AshAmine** [comment]
Hi, 

We are facing the same issue when trying to even 7.13.3. Technically we have this issues with any release after 7.12.8 which requires PHP upgrade.

**Comment by mdhont** [comment]
I recommend asking in a dedicated SuiteCRM forum for any alternative ways to upgrade to 8.0.0.
