### ISSUE TITLE
[TYPO3] How to update the VM

### ISSUE THREAD

**Issue by kleinrene** [bitnami/vms#968]
### Describe your issue as much as you can

I use V11.5, have added various content and would like to update or even upgrade in Composer mode, but the attempts end with being able to update only up to V9. Where can I find instructions to update a VM on my own? Thanks very much.

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually. Instead we recommend launching the latest version of the solution and migrate the data there.

**Comment by kleinrene** [comment]
Many thanks for the answer. How is the VM created? Is each new release compiled and not the previous VM updated?

**Comment by mdhont** [comment]
Yes, we compile the latest versions of each component, so they will have all the latest updates and security patches. Then the components are configured to work out of the box (using installation scripts) and finally tested and made available on different cloud provider marketplaces.
