### ISSUE TITLE
[WordPress] AWS Binami Package specify IP on /wp-admin page

### ISSUE THREAD

**Issue by herryfi188** [bitnami/vms#969]
### Describe your issue as much as you can

Hi Support

We have a website running on Lightsail using by wordpress bitnami package. Currently, we have receive many brute force attack about using /xmlrpc.php try to login, thus we would like to suspend xmlrpc.php respond on it without using plugins.

Found that under server path /opt/bitnami/apache/conf/vhosts/ path has many .htaccess file which should we add the config on. like below code

Block WordPress xmlrpc.php requests
`<Files xmlrpc.php>
order deny,allow
deny from all
allow from 127.0.0.1
</Files>`

Please advise us which correct directory should be edit. 

Thanks,
Herry

**Comment by jotamartos** [comment]
Hi @herryfi188,

The pingback functionality is disabled in our solution 

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/xmlrpc-and-pingback/

However, if you want to block access to the xmlrpc.php file, you can include that block in the htaccess.conf file inside the /opt/bitnami/apache/conf/vhosts/htaccess/ folder. As the xmlrpc.php file is inside the /opt/bitnami/wordpress directory, you will need to include the "Files" block inside the block of code that refers to the wordpress directory.

```
<Directory "/opt/bitnami/wordpress">
    <Files xmlrpc.php>
...
```
```
