### ISSUE TITLE
[WordPress with NGINX and SSL packaged by Bitnami] Replacing SSH Key pair

### ISSUE THREAD

**Issue by exentrify** [bitnami/vms#97]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Not-Available

### bndiagnostic was not useful. Could you please tell us why?

I am not able to connect to my bitnami instance

### Describe your issue as much as you can

I have lost the SSH key pair to my AWS instance and I am following the guide provided by AWS on how to replace your key pair for the instance. Although when I get to the point where you have to copy your new key pair the key pair on the bitnami configuration, I cannot find the key location.

Here is the video link: https://www.youtube.com/watch?v=F8jXE-_hdfg
Here is the command I am trying to do: `cp .ssh/authorized_keys /mnt/tempvol/home/ec2-user/.ssh/`

I've tried looking through the bitnami forums to see if it was mentioned but I cannot find it anywhere. Any suggestions?

**Comment by jotamartos** [comment]
The authorized_keys file is stored at /home/bitnami/.ssh/authorized_keys. You should be able to use to copy the file using the bitnami user. However, if you removed/renamed it, you will need to create a new file in the mounted disk. 

There is also another alternative to use a new key pair in your instance, you can create a snapshot of your instance and launch it. The AWS console will ask you for the SSH key to use.

https://docs.bitnami.com/aws/how-to/troubleshoot-ssh-issues/#was-the-instance-created-with-a-ssh-key-pair

**Comment by exentrify** [comment]
I did manage to get the new key attached to the original volume, and I put the original volume back on the original instance. I am trying to access MyPhpAdmin though given the directions from bitnami by creating an SSH Tunnel. 

When trying to login to MyPhpAdmin I still receive: 
`mysqli::real_connect(): (HY000/1045): Access denied for user 'user'@'127.0.0.1' (using password: YES)`
I tried disabling the NoPassword option in the MySQL config and I get the same error except instead of 'YES' I get 'NO'.

**Comment by jotamartos** [comment]
>mysqli::real_connect(): (HY000/1045): Access denied for user 'user'@'127.0.0.1' (using password: YES)

You need to use `root` and the default password we configure when deploying the instance to access the database. More info [here](https://docs.bitnami.com/aws/apps/wordpress-pro/get-started/access-phpmyadmin/)
