### ISSUE TITLE
[Wordpress] Apache, mariadb not starting

### ISSUE THREAD

**Issue by alessandrocurcio** [bitnami/vms#970]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a56de8ba-3015-ed34-7b69-37d9a9234a31

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

Action '-t -f /opt/bitnami/apache2/conf/httpd.conf' failed.
The Apache error log may have more information.

    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ? Connectivity: Found possible issues
    ? Wordpress: Found possible issues
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ? Php: Found possible issues

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Jun 07 09:32:44.708857 2023] [proxy_fcgi:error] [pid 6236:tid
140463541380864] [client **ip_address**:32951] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
Press [Enter] to continue:
on line 0', referer: https://picmood.com/wp-load.php
 [Wed Jun 07 09:32:45.879616 2023] [proxy_fcgi:error] [pid 6162:tid
140463776376576] [client **ip_address**:11414] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer: https://picmood.com/wp-load.php
 [Wed Jun 07 09:32:47.377427 2023] [proxy_fcgi:error] [pid 6216:tid
140463826732800] [client **ip_address**:61557] AH01071: Got error 'PHP message:
PHP Notice: Unknown: file created in the system's temporary directory in Unknown
on line 0', referer: https://picmood.com/wp-load.php

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

The Apache configuration has errors:
```
apache2: Syntax error on line 66 of /opt/bitnami/apache2/conf/httpd.conf: Cannot
load modules/mod_mpm_event.so into server:
/opt/bitnami/apache/modules/mod_mpm_event.so: undefined symbol:
ap_run_child_stopping
```
Press [Enter] to continue:
Please check the configuration.

System Apache is running:
```
root 639 0.0 0.0 6380 3996 ? Ss 11:03 0:00 /usr/sbin/apache2 -k start www-data
640 0.0 0.0 1931920 7936 ? Sl 11:03 0:00 /usr/sbin/apache2 -k start
```
 If Bitnami Apache isn't starting this is the most likely cause. Please run the
following command to stop it:

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2023-06-07 11:03:13 0 [ERROR] InnoDB: Your database may be corrupt or you may
have copied the InnoDB tablespace but not the InnoDB log files. Please refer to
https://mariadb.com/kb/en/library/innodb-recovery-modes/ for information about
forcing recovery.

```
Please check the following guide to troubleshoot MariaDB issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
Press [Enter] to continue:
ariadb/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Some files don't have the expected permissions Please check the following guide:

https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

[Php]

The following error appears in the /opt/bitnami/php/logs/php-fpm.log:
```
[05-Jun-2023 23:04:07] ERROR: fork() failed: Cannot allocate memory (12)

```
Press [Enter] to continue:
This error  indicates there is a problem with the memory limit in PHP. Please
check the following guide to increase the number of PHP-FPM child processes:

https://docs.bitnami.com/general/apps/akeneo/administration/increase-memor
y-limit/

===== End of bndiagnostic tool output =====

Press [Enter] to continue:                                                                                                                     -
                                                                                                                                              The files listed below are bigger than 10MB and have not been included, please notify the support agent.

/opt/bitnami/mariadb/logs/mysqld.log

### bndiagnostic was not useful. Could you please tell us why?

too many error

### Describe your issue as much as you can

We can not start the server yet

**Comment by gongomgra** [comment]
Hi @alessandrocurcio,

Thanks for using Bitnami. As described by the bndiagnostic tool, it looks like you are using the Apache server from the system packages instead of the one we included in the `/opt/bitnami/apache` directory. Please stop and remove that service using `apt-get` manager and then try to start our Apache service again.

Regarding the database errors, please follow the official guide in the error message, as it seems to be a database internal error.
