### ISSUE TITLE
[WordPress] Configure and Enable Varnish

### ISSUE THREAD

**Issue by pjwilson1977** [bitnami/vms#972]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2e6310d0-00f5-17de-4974-e96d5f6d0398

### bndiagnostic output

Resources: No issues found
? Mysql: Found possible issues
✓ Php: No issues found
✓ Connectivity: No issues found
? Apache: Found possible issues

[Mysql]

Found recent error messages in the MySQL error log:
```
2023-06-08T01:46:18.068621Z 0 [Warning] 1 [Server] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.

```
Please check the following guide to troubleshoot MySQL issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-mysql/

[Apache]

Found recent Pagespeed related error messages in the Apache error log:
```
[Thu Jun 08 01:34:13.480942 2023] [pagespeed:error] [pid 6553:tid 140232468711168] [mod_pagespeed 1.13.35.2-0 @6553] PageSpeed Serf fetch failure rate extremely high; only 0 of 161 recent fetches fully successful; is fetching working?

```
We suggest disabling pagespeed and check if that improves the behavior. Please check the following guide to disable Pagespeed:

https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespeed/#disable-pagespeed

A high number of incoming requests originate from one or more unique IP addresses. This could indicate a bot attack. The following guide shows how to check for and block suspicious IP addresses.

https://docs.bitnami.com/bch/apps/moodle/troubleshooting/deny-connections-bots-apache/

### bndiagnostic was not useful. Could you please tell us why?

Issue enabling Varnish

### Describe your issue as much as you can

Trying to setup page caching for our servers. I'm using a live DEV server we use, before executing in UAT & Production.

Using this link - https://docs.bitnami.com/azure/apps/wordpress/configuration/configure-varnish/

I have come to the stage where I need to enable Varnish.
When I have come to this page - https://docs.bitnami.com/azure/apps/wordpress/administration/configure-use-varnish/#enable-varnishtm

I have disabled "PageSpeed" as recommended as part of the setting up of Varnish.

Then attempted to enable the service. I'm able to successfully execute the first terminal command line.
However, there is an issue when trying to execute the second terminal command line 
"sudo mv /etc/monit/conf.d/varnish.conf.disabled /etc/monit/conf.d/varnish.conf"

As the directory "monit" doesn't exist.

I can confirm that "gonit" service is running on the server.

I'm unsure on how to proceed.

**Comment by gongomgra** [comment]
Hi @pjwilson1977,

Thanks for using Bitnami. I see in the bndiagnostic bundle you are using a previous image for the Bitnami WordPress solution on Azure. Can you give the most recent image a try? Our docs are supposed to work with the most recent version of our solutions.
