### ISSUE TITLE
[Ghost CMS] Ghost instance not able to start after updating: "Cannot read properties of undefined (reading 'members')"

### ISSUE THREAD

**Issue by Harsh-2002** [bitnami/vms#973]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

d12fa820-dc19-e30b-13a2-5d35dd4708ae

### bndiagnostic output

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 975 490 164 0 320 335 Swap: 
634 229 405
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Processes]
Press [Enter] to continue:

One or more component's processes are not running:
```
ghost not running
```
You can try to restart the process with the following command:
 
 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Jun 08 12:24:05.963635 2023] [proxy_http:error] [pid 15835:tid 
140380569646848] [client **ip_address**:51249] AH01114: HTTP: failed to make 
connection to backend: 127.0.0.1

[Thu Jun 08 12:26:06.530067 2023] [proxy:error] [pid 15835:tid 140380544468736] 
(111)Connection refused: AH00957: http: attempt to connect to 
**ip_address**:2368 (127.0.0.1:2368) failed

[Thu Jun 08 12:26:06.530105 2023] [proxy_http:error] [pid 15835:tid 
140380544468736] [client **ip_address**:33662] AH01114: HTTP: failed to make 
Press [Enter] to continue:
connection to backend: 127.0.0.1

```

### bndiagnostic was not useful. Could you please tell us why?

It can't detect actual issue which is the mysql database

### Describe your issue as much as you can

Recently, I updated the CMS, but after updating, an error message appeared stating that 

``` Ghost instance is not running! Starting... A GhostError occurred. ```

I attempted to resolve the issue by restarting Bitnami services, including Apache, Ghost, and MySQL, but unfortunately, the Ghost instance still did not start. Instead, the following output was displayed: 

``` Message: Ghost was able to start, but errored during boot with: Cannot read properties of undefined (reading 'members'). ```

``` Debug Information:
    OS: Debian GNU/Linux, v11
    Node Version: v18.16.0
    Ghost Version: 5.50.4
    Ghost-CLI Version: 1.24.0
    Environment: production
    Command: 'ghost restart'
Message: Ghost was able to start, but errored during boot with: Cannot read properties of undefined (reading 'members')
Stack: Error: Ghost was able to start, but errored during boot with: Cannot read properties of undefined (reading 'members')
    at ChildProcess.<anonymous> (/opt/bitnami/node/lib/node_modules/ghost-cli/lib/utils/local-process.js:75:35)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I am unsure why this issue occurred, as the Ghost CMS is only being run on my test server and should not affect my live production server. The instance with the issue is a snapshot of my original EC2 server.

If you require SSH credentials access to resolve this issue, please let me know.

Please help me to fix this issue ASAP.

Thanks

**Comment by jotamartos** [comment]
Hi @Harsh-2002,

Thank you for using Bitnami but that's a specific issue of the application and it's out of the scope of this support forum. We suggest you ask the Ghost's developers or in its forums to know more about the issue and how to resolve it. For example, there is already a similar ticket [in the Ghost's forum](https://forum.ghost.org/t/cannot-start-a-new-install-of-ghost/38941)

We will keep this ticket open for some time in case any Bitnami user ran into this issue in the past and want to share the information about how to solve it. 

Thanks
