### ISSUE TITLE
[Harbor] cannot login via docker cli

### ISSUE THREAD

**Issue by jeffellin** [bitnami/vms#974]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2b232ce8-963c-02f4-8a7a-4b466a466d72

### bndiagnostic output

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

not the problem I am having

### Describe your issue as much as you can

I am trying to run harbor on a VM.  I deployed the OVF and am successfully able to login to the UI.  However I can not login with docker. 

```bash
docker login harbor.ellin.net
Username: admin
Password: 
Error response from daemon: login attempt to https://harbor.ellin.net/v2/ failed with status: 401 Unauthorized
```

Steps I have taken.

1. Install OVF
2. Update cert in /opt/bitnami/nginx/conf/certs/bitnami with a self signed cert for harbor.ellin.net
3. Update /opt/bitnami/harbor-core/.env. and set the value `EXT_ENDPOINT` to https://harbor.ellin.net
4. Add cert to /etc/docker/certs.d/harbor.ellin.net
5. run docker login and get error above.    The user I am using admin, can login fine to the UI and is an administrator.

There is something not configured correctly and I am having a hard time debugging this.  THe install is not standard for harbor. ( normally It uses docker). so mapping suggested values from a docker-compose file in the harbor docs to some other value is impossible.   I had a hard enough time locating /opt/bitnami/harbor-core/.env.  which isn't documented anywhere as far as I can tell in the harbor bitnami docs.

**Comment by mdhont** [comment]
Hi Jeff, 

I've reproduced the issue using an OVA, it also happens without a self signed certificate only adding the IP to the --insecure-registries on Docker for Desktop. It does work on AWS so it seems due to a configuration error on our side. I will create a task for investigating it further. We will update this thread with any further information.

**Comment by mdhont** [comment]
It's on our shortlist to be fixed, I've increased the priority of the task.

**Comment by jeffellin** [comment]
> It's on our shortlist to be fixed, I've increased the priority of the task.

Thanks only pinging you because of the stale tag

**Comment by jeffellin** [comment]
@mdhont any updates on this

**Comment by mdhont** [comment]
@jeffellin, I've updated the priority of the task.

**Comment by b0xCH** [comment]
Are there any news on this issue? I still run into the same problem.

**Comment by mdhont** [comment]
I've increased the priority again so it should be picked up soon.

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the very long delay.
  [Habor 2.10.0-r85](https://downloads.bitnami.com/files/stacks/harbor/2/bitnami-harbor-2.10.0-r85-debian-11-amd64.ova) was released and fixed this issue, could you give it a try ?
