### ISSUE TITLE
[<Bitnami SuiteCRM>] <Error with person forms>

### ISSUE THREAD

**Issue by sarger604** [bitnami/vms#976]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

f90885b6-a096-a33e-14bc-9b1fc97ab99e

### bndiagnostic output

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

    ? Connectivity: Found possible issues
    ? Resources: Found possible issues
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Resources]

Your instance has little available RAM memory.
Press [Enter] to continue:
```
 total used free shared buff/cache available Mem: 3933 2275 112 1 1545 1371
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Thu Jun 08 20:34:04.401015 2023] [proxy_fcgi:error] [pid 520412:tid
139898174543616] [client **ip_address**:38558] AH01071: Got error 'PHP message:
PHP Deprecated: Return type of
Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::getIterator()
should either be compatible with IteratorAggregate::getIterator(): Traversable,
or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress
the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/At [Thu
Press [Enter] to continue:
Jun 08 20:34:04.787441 2023] [proxy_fcgi:error] [pid 520281:tid 139896882624256]
[client **ip_address**:38608] AH01071: Got error 'PHP message: PHP Deprecated:
Return type of
Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::getIterator()
should either be compatible with IteratorAggregate::getIterator(): Traversable,
or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress
the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/At [Thu
Jun 08 20:34:05.333981 2023] [proxy_fcgi:error] [pid 520736:tid 139897956333312]
[client **ip_address**:38768] AH01071: Got error 'PHP message: PHP Deprecated:
Return type of
Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::getIterator()
should either be compatible with IteratorAggregate::getIterator(): Traversable,
or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress
the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/At
```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

===== End of bndiagnostic tool output =====

Press [Enter] to continue:

Press [Enter] to continue:                                                        

### bndiagnostic was not useful. Could you please tell us why?

it didnt help with the issue

### Describe your issue as much as you can

We are having an issue with Bitnami SuiteCRM. We deployed a brand new test instance with minimal config and the same error happens.

We create a new person form tied to a campaign. We dont change the URL It outputs a URL:
https://www.xxx.com/index.php?entryPoint=WebToPersonCapture (xxx is our company name)

when i go and fill out the form the browser gives the error

This page isn’t working is currently unable to handle this request.
HTTP ERROR 500

I will paste the html of the form below with our URL erased

Can anyone help?

<html lang='en_us'><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body><style type="text/css"></style>

<form id="WebToLeadForm" action="https://www.com/index.php?entryPoint=WebToPersonCapture" method="POST" name="WebToLeadForm">

<h2>Web form to create Leads</h2>

<p>Submitting this form will create Leads</p>

<div class="row">

<div class="col"><label>Last Name: <span class="required">*</span></label><input name="last_name" id="last_name" type="text" required="" /></div>

<div class="col"> </div>

<div class="clear"> </div>

</div>

<div class="row">

<div class="col"><label>Lead Category: <span class="required">*</span></label><select name="lead_category_c" id="lead_category_c" tabindex="1" required="">

<option value="International">International</option>

<option value="Domestic">Domestic</option>

</select></div>

<div class="col"> </div>

<div class="clear"> </div>

</div>

<div class="row">

<div class="col"><label>lead type: <span class="required">*</span></label><select name="lead_type_c" id="lead_type_c" tabindex="1" required="">

<option value="Student">Student</option>

<option value="Agency">Agency</option>

<option value="Coop_Employer">Co-op Employer</option>

<option value="Service_Provider">Service Provider</option>

<option value="Government_Official">Government Official</option>

</select></div>

<div class="col"> </div>

<div class="clear"> </div>

</div>

<div class="row center buttons"><input class="button" name="Submit" type="submit" value="Submit"  />

<div class="clear"> </div>

</div>

<input name="campaign_id" id="campaign_id" type="hidden" value="efe22bf4-1326-98c2-7466-6476124e7d0b" /> <input name="assigned_user_id" id="assigned_user_id" type="hidden" value="9f865c38-6f5c-1247-8638-645183e2c68f" /> <input name="moduleDir" id="moduleDir" type="hidden" value="Leads" /></form>

<p>

// <![CDATA[

    function submit_form() {

        if (typeof(validateCaptchaAndSubmit) != 'undefined') {

            validateCaptchaAndSubmit();

        } else {

            check_webtolead_fields();

            //document.WebToLeadForm.submit();

        }

    }

    function check_webtolead_fields() {

        if (document.getElementById('bool_id') != null) {

            var reqs = document.getElementById('bool_id').value;

            bools = reqs.substring(0, reqs.lastIndexOf(';'));

            var bool_fields = new Array();

            var bool_fields = bools.split(';');

            nbr_fields = bool_fields.length;

            for (var i = 0; i < nbr_fields; i++) {

                if (document.getElementById(bool_fields[i]).value == 'on') {

                    document.getElementById(bool_fields[i]).value = 1;

                } else {

                    document.getElementById(bool_fields[i]).value = 0;

                }

            }

        }

    }

// ]]>

</p></body></html>

**Comment by gongomgra** [comment]
Hi @sarger604,

Thanks for using Bitnami. According to the Apache error messages, your issue may be more related to the SuiteCRM application itself than with the Bitnami installation. Can you open a new question in the official forums for the official developers to help you? 

```
[Thu Jun 08 20:34:51.745872 2023] [proxy_fcgi:error] [pid 520736:tid 139897922762496] [client CLIENT-IP:44578] AH01071: Got error 'PHP message: PHP Deprecated:  Return type of Symfony\\Component\\HttpFoundation\\Session\\Attribute\\AttributeBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php on line 134PHP message: PHP Deprecated:  Return type of Symfony\\Component\\HttpFoundation\\Session\\Attribute\\AttributeBag::count() should either be compatible with Countable::count(): int, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php on line 144PHP message: PHP Deprecated:  Return type of Symfony\\Component\\HttpFoundation\\Session\\Session::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/Session.php on line 131PHP message: PHP Deprecated:  Return type of Symfony\\Component\\HttpFoundation\\Session\\Session::count() should either be compatible with Countable::count(): int, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/Session.php on line 141'
```
