### ISSUE TITLE
In NGINX Open Source packaged by Bitnami 1.25.0, it is not possible to disable PHP-FPM and MariaDB because the gonit software is not available.

### ISSUE THREAD

**Issue by johnblesswindypvp** [bitnami/vms#977]
### In NGINX Open Source packaged by Bitnami 1.25.0, it is not possible to disable PHP-FPM and MariaDB because the gonit software is not available.

How to do it?

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update or remove components individually.
