### ISSUE TITLE
[WordPress+Nginx+SSL] - You appear to be offline

### ISSUE THREAD

**Issue by aaronsmulktis** [bitnami/vms#98]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

80b42185-3249-a3cb-8aaf-cbb7b34b94bb

### bndiagnostic output

2022/07/10 20:06:56 [error] 3893#3893: *3 FastCGI sent in stderr: "PHP message:
PHP Parse error: syntax error, unexpected identifier "https", expecting ")" in
/bitnami/wordpress/wp-config.php on line 176" while reading response header from
upstream, client: **ip_address**, server: _, request: "GET / HTTP/1.1",
upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host:
Press [Enter] to continue:
"instinct.is"
 2022/07/10 20:35:45 [error] 4883#4883: *14 access forbidden by rule, client:
**ip_address**, server: _, request: "GET /.env HTTP/1.1", host: "3.226.149.121"
 2022/07/10 20:55:48 [crit] 4883#4883: *176 SSL_do_handshake() failed (SSL:
error:14201044:SSL routines:tls_choose_sigalg:internal error) while SSL
handshaking, client: **ip_address**, server: 0.0.0.0:443

### bndiagnostic was not useful. Could you please tell us why?

I've tried resolving the reported issues in several ways

### Describe your issue as much as you can

I've attempted explicitly setting the HTTPS (with a single domain) in /wp-config.php
I've attempted setting permissions according to Bitnami troubleshooting docs
I've attempted to adjust upload limits according to Bitnami docs

**Comment by mdhont** [comment]
Can you check this guide for forcing HTTPS redirects using Bitnami WordPress with Nginx:
https://docs.bitnami.com/ibm/infrastructure/ruby/administration/force-https-nginx/
