### ISSUE TITLE
[Mattermost] Can't find mattermost.conf

### ISSUE THREAD

**Issue by cesaronte** [bitnami/vms#980]
### Describe your issue as much as you can

In order to import my current data into my new installation I need update the nginx config to allow bigger upload sizes.
I cant find and edit the nginx config file for mattermost (it is supposed to be located here  /etc/nginx/conf.d/mattermost.conf then configure the client_max_body_size to be bigger than your zip file).
Help please

**Comment by jotamartos** [comment]
Hi @cesaronte,

You can find that configuration file inside the /opt/bitnami/nginx/conf/server_blocks directory. Please remember to edit the necessary files and restart NGINX for the changes to take effect.
