### ISSUE TITLE
Bitnami AWS Lightsail WordPress Multisite - Services on server go down

### ISSUE THREAD

**Issue by jason5591** [bitnami/vms#981]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

c0c538bc-55cd-66b8-94de-9a3611e0ccc6

### bndiagnostic output

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1982 1337 74 78 570 433 Swap:
0 0 0

[Tue Jun 13 03:53:58.488941 2023] [core:error] [pid 1119:tid 140680957347584]
[client **ip_address**:38436] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion' to
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.,
referer:
https://www.ourdomain.com/old-calendar/cal_day.php?op=day&date=2010-02-05&catvie



### bndiagnostic was not useful. Could you please tell us why?

Unsure of cause

### Describe your issue as much as you can

After several days, CPU usage goes to 100% and sites are unavailable and SSH connects but produces no output. Can not reboot server or "stop" it. Have to force stop it and start again.

**Comment by mdhont** [comment]
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one.

**Comment by jason5591** [comment]
Is there a command to watch for low resources? We're trying to budget. We didn't have any trouble with the lower tier lightsail plan but now have the problems with this higher end one. Unfortunately, can't downgrade, only upgrade.

**Comment by mdhont** [comment]
You can check RAM usage of the machine with the following command:

    free -m

And you can check disk usage with:

    df -h
