### ISSUE TITLE
Technical Support Reuiqred

### ISSUE THREAD

**Issue by karthickselvam2** [bitnami/vms#983]
### Describe your issue as much as you can

after migrating from On-perm to AWS some of the data missing 

1. When I logged in to Redmine, I got a 403 error, but the user is able to log in.
2. When clicking on the Project menu, the QMO_Compliance project was displayed. When I clicked on the QMO_Compliance project, the internal error page was displayed.

<img width="601" alt="Screenshot 2023-06-13 at 4 47 30 PM" src="https://github.com/bitnami/vms/assets/136440694/58ebadb8-fbd9-42c9-9ae3-53da93ea00c4">

**Comment by mdhont** [comment]
Did you follow the steps from this guide?

https://docs.bitnami.com/virtual-machine/apps/redmine/administration/upgrade/

**Comment by karthickselvam2** [comment]
HI mdhont,

we are trying to migrate the Windows Redmine server

**Comment by mdhont** [comment]
Unfortunately the Redmine Windows installer has been deprecated. I recommend asking in the official Redmine forum.

**Comment by karthickselvam2** [comment]
if there any technical support available while the migration activity??
also please share with me how to migrate plugins in the Redmine tool.

**Comment by mdhont** [comment]
To debug the issue can you run the bndiagnostic tool on the AWS instance? 

    sudo /opt/bitnami/bndiagnostic-tool

**Comment by karthickselvam2** [comment]
we are expecting the Plugins below if you have please share them with installation cmd.
OS : Windows server
Redmine version: 4.1.0.-8

**Plugins details:-**
redmine_ldap_syn  2.1.1.devel
  redmine_monitoring_controlling 0.1.1

**Comment by mdhont** [comment]
I recommend asking in a dedicated Redmine forum. Unfortunately we can't provide you with any individual application components.

**Comment by karthickselvam2** [comment]
My requirement is needed to migrate the Windows Redmine which is deployed in our Datacenter.
we are going to migrate the environment to AWS with using any OS.
Also, we need to expect some support from Redmine during this activity if there is any possibility.

**Comment by mdhont** [comment]
Unfortunately, as there are many Bitnami applications we can't provide full support for each application. This forum is meant for issues regarding the Bitnami configuration of the application, that's why I recommend asking in an official Redmine forum.
