### ISSUE TITLE
Bitnami question

### ISSUE THREAD

**Issue by ian-p-2508** [bitnami/vms#985]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

Bitnami

### bndiagnostic output

General question relating to my bitnami

### bndiagnostic was not useful. Could you please tell us why?

N/A

### Describe your issue as much as you can

I received a notification that Bitnami's launchpad is being decommissioned soon. I don't use launchpad but I use the Bitnami package that wraps my Wordpress install on my EC2 webservers does this have to be migrated off as well?

**Comment by ian-p-2508** [comment]
Is there an update please ?

**Comment by gongomgra** [comment]
Hi @ian-p-2508,

Thanks for using Bitnami. We have only decommissioned our launchpads as an alternative way of launching our images in the cloud providers like AWS. However, you can continue using your current serves in AWs, and also launch new servers in the future directly from the AWS EC2 console or the AWS Marketplace.

**Comment by ian-p-2508** [comment]
Many thanks.

**Comment by gongomgra** [comment]
You are welcome! I'm closing this ticket as solved.
