### ISSUE TITLE
[WordPress] Unable to edit site url in settings & wp-config not writable

### ISSUE THREAD

**Issue by miarosemathews** [bitnami/vms#986]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

na

### bndiagnostic output

----------------------------------------------------------------------------
Created with an evaluation version of InstallBuilder

Welcome to the Bitnami Diagnostic tool.

----------------------------------------------------------------------------
Please read the following information carefully.

Press [Enter] to continue:
This tool collects system information and files from a Bitnami stack into a
diagnostic bundle file to be uploaded and reviewed by the Bitnami Team, for the
sole purpose of providing you support for any issue you may find.

The uploaded information will be automatically removed from our systems after 1
month. In case you have any doubt regarding our privacy policy please check:

https://www.vmware.com/help/privacy.html
Press [Enter] to continue:

Do you accept? [y/n]: y

\\
The bndiagnostic tool has finished searching for errors and has found some 
issues that might be related to yours. The output will be shown on the next 
page:
                                    
Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ✓ Apache: No issues found
    ✓ Php: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 1982 762 251 50 967 999 Swap: 
0 0 0
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.
 
https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-m
emory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Wed Jun 14 17:34:31.011203 2023] [proxy_fcgi:error] [pid 2939:tid 
140625147983616] [client **ip_address**:59292] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0', referer: https://edusocialist.org/wp-admin/plugin-install.php


### bndiagnostic was not useful. Could you please tell us why?

didn't output id

### Describe your issue as much as you can

I am trying install really simple ssl and it needs the config to be writable. Nothing has been changed on the site but when I use this help article nothing changes. https://stackoverflow.com/questions/42113289/amazon-ec2-how-to-make-wp-config-php-to-writable

**Comment by jotamartos** [comment]
Please reset the permissions configuration by running the commands in this other post 

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

and try to edit the wp-config.php file later.
