### ISSUE TITLE
[btinami wordpress] <services stopped running>

### ISSUE THREAD

**Issue by KingMilli75** [bitnami/vms#988]
### Describe your issue as much as you can

error on services:
Cannot find any running daemon to contact. If it is running, make sure you are pointing to the right pid file (/v
ar/run/gonit.pid)

running bndiagnostic-tool does not work 

bitnami@ip-172-26-5-62:~$ sudo /opt/bitnami/ctlscript.sh start
Starting services..
Job for bitnami.service failed because the control process exited with error code.
See "systemctl status bitnami.service" and "journalctl -xe" for details.

**Comment by gongomgra** [comment]
Hi @KingMilli75,

Thanks for using Bitnami. Can it be a similar situation to others you previously had? Can you check if the suggested solutions still apply?

https://github.com/bitnami/vms/issues/855

**Comment by KingMilli75** [comment]
Hi There, 

no its not we got it up and running and now no errors anymore. We just used a snapshot to make a new instance. 

It seems to be connected to SSL, what we did yesterday was to reinstall the certificated on the server.  We used the following command for it. 

sudo /opt/bitnami/letsencrypt/lego --http --email="dragan@prodato.rs" --domains="kupoholik.rs" --domains="www.kupoholik.rs" --path="/opt/bitnami/letsencrypt" run


This did the trick it and suddensly most error disappeared, however we run the log again now and came with these. 

[Fri Jun 16 06:32:01.592739 2023] [mpm_event:notice] [pid 11044:tid 139787213540352] AH00493: SIGUSR1 received. Doing graceful restart
[Fri Jun 16 06:32:01.602421 2023] [ssl:warn] [pid 11044:tid 139787213540352] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 16 06:32:01.602900 2023] [mpm_event:notice] [pid 11044:tid 139787213540352] AH00489: Apache/2.4.55 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Fri Jun 16 06:32:01.602911 2023] [core:notice] [pid 11044:tid 139787213540352] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'

Now we changed the file as per instruction in here;
https://kinsta.com/knowledgebase/xampp-server-certificate-does-not-include-an-id-which-matches-the-server-name/#:~:text=prevent%20future%20problems.-,The%20%E2%80%9CServer%20certificate%20does%20NOT%20include%20an%20ID%20which%20matches,Apache%20is%20part%20of%20XAMPP

we needed to remove the CloudFront distribution as we clould not get it properly working for the time being. Seems that the server certificate does not want to play ball with the CDN (CloudFront)... We are even in talks with LEtsEncrypt community which provided us with some insights but we still did not manage to solve the problem 100%. 

Only this did not solve the issue for now i checked the log of apache and apache 2 they are identical now and still show this warning. It seems now when we run ATOP. So we thought the commented out process and adding the localhost would solve this as well but it still present there. 

We think the main reason of the crash was that it went into somekind of a loop and consumed a whole lot of resources and the server simply said your not allowed to. As we saw several SIGTERM issued. 

If we solve this issue we are golden i believe...

**Comment by KingMilli75** [comment]
This is what we ended up with.  44f62a65-27f9-b555-bb0f-2146671d19f6

[Fri Jun 16 06:32:01.592739 2023] [mpm_event:notice] [pid 11044:tid 139787213540352] AH00493: SIGUSR1 received.  Doing graceful restart
[Fri Jun 16 06:32:01.602421 2023] [ssl:warn] [pid 11044:tid 139787213540352] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 16 06:32:01.602900 2023] [mpm_event:notice] [pid 11044:tid 139787213540352] AH00489: Apache/2.4.55 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Fri Jun 16 06:32:01.602911 2023] [core:notice] [pid 11044:tid 139787213540352] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Fri Jun 16 07:36:05.385453 2023] [mpm_event:notice] [pid 11044:tid 139787213540352] AH00491: caught SIGTERM, shutting down
[Fri Jun 16 07:36:05.822007 2023] [ssl:warn] [pid 29277:tid 139953384905728] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 16 07:36:05.831978 2023] [ssl:warn] [pid 29278:tid 139953384905728] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 16 07:36:05.842688 2023] [mpm_event:notice] [pid 29278:tid 139953384905728] AH00489: Apache/2.4.55 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Fri Jun 16 07:36:05.842732 2023] [core:notice] [pid 29278:tid 139953384905728] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Fri Jun 16 07:38:09.582465 2023] [mpm_event:notice] [pid 29278:tid 139953384905728] AH00491: caught SIGTERM, shutting down
[Fri Jun 16 07:38:10.021000 2023] [ssl:warn] [pid 31485:tid 140186585500672] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 16 07:38:10.030606 2023] [ssl:warn] [pid 31486:tid 140186585500672] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 16 07:38:10.037615 2023] [mpm_event:notice] [pid 31486:tid 140186585500672] AH00489: Apache/2.4.55 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Fri Jun 16 07:38:10.053335 2023] [core:notice] [pid 31486:tid 140186585500672] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'

however this document does not excist to make a swap memory for linux  https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-memory-linux/

**Comment by KingMilli75** [comment]
We solved it thanks !

**Comment by gongomgra** [comment]
Hi @KingMilli75,

Good to know you managed to solve your issue! We are closing this ticket as solved.
