### ISSUE TITLE
[Bitnami Wordpress Lightsail] ACME Challenge bncert

### ISSUE THREAD

**Issue by samashford** [bitnami/vms#989]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

e0a3d8cd-51f9-67ac-c150-ccf811942f96

### bndiagnostic was not useful. Could you please tell us why?

ports already open in Lighsail

### Describe your issue as much as you can

Hi all,
Migrating a wordpress site to bitnami.
All going well, but bncert is outputting the below:

Log started 06/15/2023 at 14:54:06
Preferred installation mode : text
Trying to init installer in mode text
Mode text successfully initialized
Executing /opt/bitnami/apache/bin/apachectl configtest
Script exit code: 0

Script output:
 

Script stderr:
 Syntax OK

Executing ./autoupdate-linux-x64.run --mode unattended
Script exit code: 1

Script output:
 

Script stderr:
 child process exited abnormally

Error running ./autoupdate-linux-x64.run --mode unattended: child process exited abnormally
Stopping web server
Executing /opt/bitnami/ctlscript.sh status varnish
Script exit code: 0

Script output:
 

Script stderr:
 

Executing /opt/bitnami/ctlscript.sh stop apache > /dev/null 2> /dev/null
Script exit code: 0

Script output:
 

Script stderr:
 

Executing /opt/bitnami/letsencrypt/lego --version
Script exit code: 0

Script output:
 lego version 4.9.1 linux/amd64

Script stderr:
 

Configuring Let's Encrypt certificates
Executing /opt/bitnami/letsencrypt/lego --path /opt/bitnami/letsencrypt --email="support@sheffield-systems.co.uk" --accept-tos --tls --domains=ultimatebattery.com --domains=www.ultimatebattery.com --user-agent bitnami-bncert/1.1.1 run
Script exit code: 1

Script output:
 

Script stderr:
 2023/06/15 14:54:49 [INFO] [ultimatebattery.com, www.ultimatebattery.com] acme: Obtaining bundled SAN certificate
2023/06/15 14:54:50 [INFO] [ultimatebattery.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/237059471287
2023/06/15 14:54:50 [INFO] [www.ultimatebattery.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/237059471297
2023/06/15 14:54:50 [INFO] [ultimatebattery.com] acme: use tls-alpn-01 solver
2023/06/15 14:54:50 [INFO] [www.ultimatebattery.com] acme: use tls-alpn-01 solver
2023/06/15 14:54:50 [INFO] [ultimatebattery.com] acme: Trying to solve TLS-ALPN-01
2023/06/15 14:55:03 [INFO] [www.ultimatebattery.com] acme: Trying to solve TLS-ALPN-01
2023/06/15 14:55:19 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/237059471287
2023/06/15 14:55:19 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/237059471297
2023/06/15 14:55:19 Could not obtain certificates:
	error: one or more domains had a problem:
[ultimatebattery.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 18.168.214.41: Timeout during connect (likely firewall problem)
[www.ultimatebattery.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 18.168.214.41: Timeout during connect (likely firewall problem)

Error running /opt/bitnami/letsencrypt/lego --path /opt/bitnami/letsencrypt --email="support@sheffield-systems.co.uk" --accept-tos --tls --domains=ultimatebattery.com --domains=www.ultimatebattery.com --user-agent bitnami-bncert/1.1.1 run: 2023/06/15 14:54:49 [INFO] [ultimatebattery.com, www.ultimatebattery.com] acme: Obtaining bundled SAN certificate
2023/06/15 14:54:50 [INFO] [ultimatebattery.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/237059471287
2023/06/15 14:54:50 [INFO] [www.ultimatebattery.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/237059471297
2023/06/15 14:54:50 [INFO] [ultimatebattery.com] acme: use tls-alpn-01 solver
2023/06/15 14:54:50 [INFO] [www.ultimatebattery.com] acme: use tls-alpn-01 solver
2023/06/15 14:54:50 [INFO] [ultimatebattery.com] acme: Trying to solve TLS-ALPN-01
2023/06/15 14:55:03 [INFO] [www.ultimatebattery.com] acme: Trying to solve TLS-ALPN-01
2023/06/15 14:55:19 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/237059471287
2023/06/15 14:55:19 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/237059471297
2023/06/15 14:55:19 Could not obtain certificates:
	error: one or more domains had a problem:
[ultimatebattery.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 18.168.214.41: Timeout during connect (likely firewall problem)
[www.ultimatebattery.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 18.168.214.41: Timeout during connect (likely firewall problem)
Executing chown -R bitnami /opt/bitnami/letsencrypt
Script exit code: 0

Script output:
 

Script stderr:
 

Executing chown -R bitnami /opt/bitnami/apps/letsencrypt
Script exit code: 0

Script output:
 

Script stderr:
 

Executing find /opt/bitnami/apps/letsencrypt   -type f  -print0 | xargs -0 chmod 664
Script exit code: 0

Script output:
 

Script stderr:
 

Executing find /opt/bitnami/apps/letsencrypt   -type d  -print0 | xargs -0 chmod 775
Script exit code: 0

Script output:
 

Script stderr:
 

Restoring web server configuration
[14:55:32] Restoring configuration file /opt/bitnami/apache/conf/httpd.conf from /opt/bitnami/apache/conf/httpd.conf.back.202306151454
Setting variable diff from diff -uw /opt/bitnami/apache/conf/httpd.conf /opt/bitnami/apache/conf/httpd.conf.back.202306151454
Script exit code: 0

Script output:
 

Script stderr:
 

[14:55:33] Restoring configuration file /opt/bitnami/apache/conf/bitnami/bitnami.conf from /opt/bitnami/apache/conf/bitnami/bitnami.conf.back.202306151454
Setting variable diff from diff -uw /opt/bitnami/apache/conf/bitnami/bitnami.conf /opt/bitnami/apache/conf/bitnami/bitnami.conf.back.202306151454
Script exit code: 0

Script output:
 

Script stderr:
 

[14:55:33] Restoring configuration file /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf from /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf.back.202306151454
Setting variable diff from diff -uw /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf.back.202306151454
Script exit code: 0

Script output:
 

Script stderr:
 

[14:55:34] Restoring configuration file /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf from /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf.back.202306151454
Setting variable diff from diff -uw /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf.back.202306151454
Script exit code: 0

Script output:
 

Script stderr:
 

[14:55:34] Restoring configuration file /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf from /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf.back.202306151454
Setting variable diff from diff -uw /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf.back.202306151454
Script exit code: 0

Script output:
 

Script stderr:
 

Stopping web server
Executing /opt/bitnami/ctlscript.sh status varnish
Script exit code: 0

Script output:
 

Script stderr:
 

Executing /opt/bitnami/ctlscript.sh stop  > /dev/null 2> /dev/null
Script exit code: 0

Script output:
 

Script stderr:
 

Starting web server
Executing /opt/bitnami/ctlscript.sh stop  > /dev/null 2> /dev/null
Script exit code: 0

Script output:
 

Script stderr:
 

Executing /opt/bitnami/ctlscript.sh start  > /dev/null 2> /dev/null
Script exit code: 0

Script output:
 

Script stderr:
 
I've ensured there's a dns record for both, port 80 and 443 open on AWS but still no dice.

Any help appreciated,

Cheers,
Sam

**Comment by mdhont** [comment]
Can you try the manual approach? It will be easier to troubleshoot:

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach
