### ISSUE TITLE
AWS EC2 - Upgrade Bitnami-wordpress-5.4.1 to 6.0.0-9?

### ISSUE THREAD

**Issue by archprof8** [bitnami/vms#99]
### Describe your issue as much as you can

Hi,
Currently I have an EC2 Instance running (Production) which is hosting a Wordpress WebSite and it's on following Bitnami Version from AWS Marketplace: aws-marketplace/bitnami-wordpress-**5.4.1**-0-r02-**linux-debian-10**-x86_64

I am getting Email Alerts from AWS Marketplace to upgrade AMI to WordPress Certified by Bitnami and Automattic/**6.0.0-9**-r05 on **Debian 11**.

Now a larger question is **1.** "How to do it"? 
**2.** Is there a manual to follow along?
**3.** What are the pre-requisites?
**4.** Can an existing EC2 instance be directly upgraded with Bitnami upgrades with its internal components like php, sql etc.?
or 
**5.** Do I need to spin up new EC2 instance with New Bitnami version and Lift-&-Shift the Wordpress Data Backup from old EC2 instance? If yes, then what are the steps/instructions?
**6.** Is following suggested version a stable (in terms of Security) version of Bitnami or What's the most preferred latest version to upgrade to? (WordPress Certified by Bitnami and Automattic/**6.0.0-9**-r05 on **Debian 11**)

Please suggest. Thank you in advance.

**Comment by mdhont** [comment]
To upgrade you need to launch a new instance of the latest Bitnami WordPress version and then migrate the data there:

https://docs.bitnami.com/aws/how-to/migrate-wordpress/
