### ISSUE TITLE
Bitnami [LAMP] Enabling CORS

### ISSUE THREAD

**Issue by justperbox** [bitnami/vms#993]
### Describe your issue as much as you can

Hi Team,

We are hosting multiple PHP (WordPress & Laravel) apps inside one EC2 instance running LAMP stack.

All applications are working fine except for one Laravel app that gives out CORS is blocked.

 I followed some of the solutions from forums especially from Bitnami, but I can't seem to enable it.
I'm starting to guess this is an issue with the application itself rather than Apache.

Could you please assist us on this matter?

Thank you.

**Comment by mdhont** [comment]
Can you check the following guide for enabling cors?

https://docs.bitnami.com/aws/apps/wordpress/configuration/enable-cors-wordpress/

It's for Wordpress but I think it should work for LAMP as well.
