### ISSUE TITLE
Suitecrm Email Issue

### ISSUE THREAD

**Issue by bbaeta** [bitnami/vms#995]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5573b50e-f80e-373f-d247-ed95cf41e793

### bndiagnostic output

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Fri Jun 16 00:06:42.523760 2023] [proxy_fcgi:error] [pid 1106:tid 
140109391316736] (104)Connection reset by peer: [client **ip_address**:56185] 
AH01075: Error dispatching request to : , referer: 
https://10.10.20.201/legacy/index.php?return_module=InboundEmail&return_action=De
tailView&return_id=25ac9df7-cd4a-90ab-f503-6488e91c9739&module=InboundEmail&actio
n=EditView&record=25ac9df7-cd4a-90ab-f503-6488e91c9739
Press [Enter] to continue:

[Fri Jun 16 00:06:42.539425 2023] [proxy_fcgi:error] [pid 435:tid 
140108166571776] [client **ip_address**:56177] AH01067: Failed to read FastCGI 
header, referer: 
https://10.10.20.201/legacy/index.php?return_module=InboundEmail&return_action=De
tailView&return_id=25ac9df7-cd4a-90ab-f503-6488e91c9739&module=InboundEmail&actio
n=EditView&record=25ac9df7-cd4a-90ab-f503-6488e91c9739

[Fri Jun 16 00:06:42.539552 2023] [proxy_fcgi:error] [pid 435:tid 
140108166571776] (104)Connection reset by peer: [client **ip_address**:56177] 
AH01075: Error dispatching request to : , referer: 
https://10.10.20.201/legacy/index.php?return_module=InboundEmail&return_action=De
tailView&return_id=25ac9df7-cd4a-90ab-f503-6488e91c9739&module=InboundEmail&actio
n=EditView&record=25ac9df7-cd4a-90ab-f503-6488e91c9739



### bndiagnostic was not useful. Could you please tell us why?

I wasn't able to solve the problem from the documentation given

### Describe your issue as much as you can

The Suitecrm InboundEmail module which is not loading the IMAP configured INBOX folders in the popup as shown in the screenshot. The solution is to iinstall the php-imap and php-zip plug-in on server. i've installed those packages but it still isn't working.

**Comment by bbaeta** [comment]
SuiteCRM 8.3 requires PHP 8.0. The Bitnami Suitecrm mage uses version 8.1. According to other sources online that is the cause of the problem with loading IMAP folders.

**Comment by mdhont** [comment]
I'm checking the issue. Could you share the links to those sources?

**Comment by bbaeta** [comment]
Hello Michiel,

Please see the SuiteCRM compatibility link: https://docs.suitecrm.com/8.x/admin/compatibility-matrix/

Kind Regards,

Boris Baeta CISSP
Sales Engineer
950 Eagles Landing Pkwy, Suite 670
Stockbridge, GA 30281
Phone: 404-513-7957
www.threeoakstech.com



From: Michiel ***@***.***>
Date: Thursday, June 22, 2023 at 12:35 PM
To: bitnami/vms ***@***.***>
Cc: bbaeta ***@***.***>, Author ***@***.***>
Subject: Re: [bitnami/vms] Suitecrm Email Issue (Issue #995)

I'm checking the issue. Could you share the links to those sources?

**Comment by bbaeta** [comment]
Thank you sir. Sent from my iPhoneOn Jul 13, 2023, at 8:31 AM, Michiel ***@***.***> wrote:﻿
I've created an internal task for using PHP 8.0 instead of 8.1. We will notify you with further information in this thread.
