### ISSUE TITLE
[<ELK>] Connect connect from external host

### ISSUE THREAD

**Issue by patdelaney** [bitnami/vms#996]
### Describe your issue as much as you can

Yesterday I downloaded the Elk Stack OVA file and deployed it on Virtual Box. I can access the Web page with no problem. I'm building this to try and ship log files from several Raspberry Pis to the stack. Wehn I configured the service on the pi I get a connection refused. Here is what I tried so far:
Local console I am able to "curl GET 127.0.0.1:9200" as well as "curl GET localhost:9200", but I can't "curl GET 192.168.1.208:9200"  which is the IP address if the Elkstack. I reviewed some the suggestions to modify the elasticsearch.yml file by changing the host to 0.0.0.0.   Here is the current file.
http:
  port: "9200"
path:
  data: /bitnami/elasticsearch/data
transport:
  port: "9300"
action:
  destructive_requires_name: "true"
network:
  host: 0.0.0.0
  publish_host: 127.0.1.1
  bind_host: 127.0.0.1
node:
  name: debian
discovery:
  type: single-node
xpack:
  security:
    enabled: "false"
  ml:
    enabled: "false"

I also added the port 9200 to the nftables.conf

        # Allow selected ports for IPv4 and IPv6.
        tcp dport { 22, 80, 443, 9200 } accept

I tried then to restart the services and even reboot but when I test locally or from a remote pc, I still get:

bitnami@debian:~$ curl -GET 192.168.1.208:9200
curl: (7) Failed to connect to 192.168.1.208 port 9200: Connection refused

I'm sure it's something simple, but any help would be greatly appreciated

**Comment by jotamartos** [comment]
Hi @patdelaney,

Apart from opening the port in the firewall, you also need to configure Elasticsearch to accept remote connections. In this case, you need to configure the bind_host parameter in the conf file. You can learn more about it in [the official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html)

**Comment by patdelaney** [comment]
Thank you for replay, I looked it over and I Think I made the correct changes, but I can't seem to connect to the ES from a remote PC. I get the following results when I try the curl command on a ES server:

bitnami@debian:~$ curl -GET localhost:9200
{
  "name" : "debian",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "_e6v_UUdRH6OOBWjxJ9IaQ",
  "version" : {
    "number" : "8.8.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "f8edfccba429b6477927a7c1ce1bc6729521305e",
    "build_date" : "2023-06-05T21:32:25.188464208Z",
    "build_snapshot" : false,
    "lucene_version" : "9.6.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}

bitnami@debian:~$ curl -GET 127.0.0.1:9200
{
  "name" : "debian",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "_e6v_UUdRH6OOBWjxJ9IaQ",
  "version" : {
    "number" : "8.8.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "f8edfccba429b6477927a7c1ce1bc6729521305e",
    "build_date" : "2023-06-05T21:32:25.188464208Z",
    "build_snapshot" : false,
    "lucene_version" : "9.6.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}

`bitnami@debian:~$ curl -GET 192.168.1.208:9200
curl: (7) Failed to connect to 192.168.1.208 port 9200: Connection refused
bitnami@debian:~$
`

Here is a copy of the elasticsearch.yml
`http:
  port: "9200"
path:
  data: /bitnami/elasticsearch/data
transport:
  port: "9300"
action:
  destructive_requires_name: "true"
network:
  host: 0.0.0.0
  publish_host: 127.0.1.1
  bind_host: 127.0.0.1
node:
  name: debian
discovery:
  type: single-node
xpack:
  security:
    enabled: "false"
  ml:
    enabled: "false"

`
I also have the following setting in the nftables chain inbound:
`        # Allow selected ports for IPv4 and IPv6.
        tcp dport { 22, 80, 443, 5044, 9200 } accept
`

I'm trying to use the Chrome Elastic Search head plugin, but it can't connect:
![image](https://github.com/bitnami/vms/assets/8147459/b1fb1554-bdf3-4ba5-8a32-38eafcd1493e)

I'm sure I am missing something simple, I just can't figure it out.

Thanks for looknig at this

**Comment by patdelaney** [comment]
Update: I got it to work by removing these 2 lines
publish_host: 127.0.1.1
bind_host: 127.0.0.1

and now the config looks like this:

http:
  port: "9200"
path:
  data: /bitnami/elasticsearch/data
transport:
  port: "9300"
action:
  destructive_requires_name: "true"
network:
  host: 0.0.0.0
node:
  name: debian
discovery:
  type: single-node
xpack:
  security:
    enabled: "false"
  ml:
    enabled: "false"

I think we can close the case
