### ISSUE TITLE
[Bitnami WOrdpress on AWS Lightsail] <Apache does not start- AH01075: Error dispatching request >

### ISSUE THREAD

**Issue by iw1** [bitnami/vms#998]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

47417fc1-8b78-4d3e-3b8c-a4eb023a3858

### bndiagnostic output

[Mariadb]Press [Enter] to continue:Some files don't have the expected permissions. Please check the following guide: https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/[Apache]

Found recent error or warning messages in the Apache error log.
[proxy_fcgi:error] [pid 151110:tid 140418586801920] (70007)The timeout specified has expired: [client **ip_address**:55462] AH01075: Error dispatching request to : (polling)

### bndiagnostic was not useful. Could you please tell us why?

The suggested help did not resolve th eissue

### Describe your issue as much as you can

Using an AWS lightsail implementation of Bitnami Wordpress with a static IP address
the bitnami service stack hangs on the apache start with an error .

The issue appeared after a server hang from a upload that generated a maria db error AH01075: Error dispatching request to : (polling), referer: https://dev.xx.zzz/wp-admin/upload.php?item=283
troubleshooting steps that have not help include:
* removing the upload, and purging the maria DB entries have not helped.
* rolling back the site to a prior snapshot continues to generate the same apache error 
* resetting the mariaDB and apache permissions per the bitnami help
* adjusting the maxtimeout and max memory settings of php.ini

Rolling back to an snapshot before the upload still generates the bitnami service stack hang on the apache start event though the errors are gone.

**Comment by gongomgra** [comment]
Hi @iw1,

Thanks for using Bitnami. Regarding Apache initialization, it is not possible to start because there is another NGINX process on your server using ports 80 and 443. It looks like this NGINX server was installed using the system packages

```
-----------------------------------
Check Apache path:
-----------------------------------
Running: ps aux | grep 'apache\|mysql\|nginx\|/opt/bitnami\|php-fpm'
In: /opt/bitnami

Output:

root         569  0.0  0.0  56372  1596 ?        Ss   19:20   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data     571  0.0  0.1  56748  3268 ?        S    19:20   0:00 nginx: worker process
```

Please stop and disable the nginx service and then restart Bitnami services running the command below

```
sudo /opt/bitnami/ctlscript.sh restart
```

Hope it helps!

**Comment by iw1** [comment]
Thanks Gonzalo,

That worked.

------- Original Message -------

**Comment by gongomgra** [comment]
Hi @iw1,

Thanks for letting us know. I'm glad it solved your issue!
